### ISSUE TITLE
CollectionEditor save changes after cancel pressed for referenced types

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#10001]
### .NET version

All up to 7.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

This `propertyGrid1.SelectedObject = new Params();` will save `p1` and `p2` changes even after Cancel button pressed.
```cs
  public class Params
  {
      public List<P> List { get; set; } = new List<P>() { new P() };
  }

  public class P
  {
      public int p1 { get; set; }
      public int p2 { get; set; }

      public override string ToString()
      {
          return $"{p1}, {p2}";
      }
  }
```

https://github.com/dotnet/winforms/assets/17767561/2d98239d-0f28-431e-b005-47adb9461608

The problem is here (`_originalItems[i]` is the same object as `Items[i]`):
https://github.com/dotnet/winforms/blob/bbe3f455171e0158a2238282d30d001d2fdda5c6/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionEditorCollectionForm.cs#L768-L773
and then here:
https://github.com/dotnet/winforms/blob/bbe3f455171e0158a2238282d30d001d2fdda5c6/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionEditorCollectionForm.cs#L278-L284

Saving changes after pressing cancel is very surprising and often leads to fatal results (from the user's point of view).
Regarding the solution to the problem... I have no other thoughts other than deep cloning of the original collection :⁠-⁠(

### Steps to reproduce

See video above.
[CollectionEditorBug.zip](https://github.com/dotnet/winforms/files/12739622/CollectionEditorBug.zip)

**Comment by merriemcgaw** [comment]
Thanks for raising this issue @kirsan31!If you do have any ideas or a PR you would like to throw together, we'd be happy to look at it. It would be a change of behavior, but the current behavior isn't quite ideal by any stretch.

**Comment by kirsan31** [comment]
@merriemcgaw 
Theoretically this can be solved with (we doing it that way):
```cs
public override object EditValue(ITypeDescriptorContext context, IServiceProvider provider, object value)
{
    var res = base.EditValue(context, provider, value?.DeepCopy());
    return _cancel ? value : res;
}
```

But the main problem is realisation of `DeepCopy()` - full deep copy of object in .Net. We doing it with reflection and `MemberwiseClone`. But we know aur collections, we know that we have no events / pointers / etc in it. 
And what to do in the general case? I also don’t know how to solve this problem otherwise without completely rewriting the `CollectionEditor` (actually writing a new one) :(

**Comment by Tanya-Solyanik** [comment]
Since this is a .NET Framework issue with workarounds on the application level possible, we'll close it.

**Comment by kirsan31** [comment]
@Tanya-Solyanik changes not reverted on cancel pressed and you close this as is - eally??? From user side of view this is **FATAL** error. And to do a workaround **you need to encounter this bug first**! In our case, we were just very lucky that we got off cheap.
After all you need to dig into. net code and do lots of debugging and other things... I mean that the fix is not trivial at all.
If you strongly decide not to fix this. May be do some big red notes in documentation at least? May be in description of class to?
