### ISSUE TITLE
advanceddatagridview from Nuget can not be used in Visual Studio 17.5.4

### ISSUE THREAD

**Issue by jory999** [dotnet/winforms#10026]
I have to rollback to 17.5.3

https://github.com/davidegironi/advanceddatagridview

**Comment by elachlan** [comment]
@davidegironi Are you aware of this issue?

**Comment by davidegironi** [comment]
Hello, nope I wasn't. I'm now using VS 17.7.6. I've try right now with NET 7.0 and NET framework and I don't have this issue. Have you a sample project that does not work?

**Comment by elachlan** [comment]
Not from the reporter. I will close this for now and @jory999 can comment if they still have an issue.

Thanks for your help!
