### ISSUE TITLE
[Loc]The text for OK and Cancel buttons is not completely localized or is localized differently compared to Desktop Framework in warning dialog

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#1004]
![image](https://user-images.githubusercontent.com/10677481/57948083-8f3b5000-7895-11e9-9267-857dafad0edc.png)

**Comment by zsd4yr** [comment]
`PropertyGridView.ShowFormatExceptionMessage(string propName, object value, Exception ex)` makes use of `PropertyGridView.get_ErrorDialog()` which creates a new `GridErrorDlg` if there is not one yet.

The [constructor for `GridErrorDlg`](https://github.com/dotnet/winforms/blob/9411ed26437905ed3d8148b73ea0dbed47704a5b/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridErrorDlg.cs#L72) makes use of SR to set the okay button and cancel button text

```cs
okBtn.Text = SR.ExDlgOk;
cancelBtn.Text = SR.ExDlgCancel;
```

**Comment by zsd4yr** [comment]
I have confirmed that ExDlgOk is **not** translated for _any_ language

**Comment by zsd4yr** [comment]
I have confirmed that ExDlgCancel **is** translated for _all_ languages, but if these translations are different than the Framework translations, than someone with native understanding of the languages should decide which is better. I don't think parity trumps understanding here. If the new translation is better, then we should keep it.

**Comment by zsd4yr** [comment]
@vivmishra @janbaltus @v-zbsail Who is in charge of these two issues? 
* Should I mark in source the OK entries as `state="untranslated"` or something?
* What about the difference in translation of Cancel?

**Comment by dreddy-work** [comment]
"OK" string earlier was translated but not now. I won't see any reason why we can;t do it now. @zsd4yr , can you check of "OK" string is translated for any other dialog?

**Comment by zsd4yr** [comment]
> "OK" string earlier was translated but not now. I won't see any reason why we can;t do it now. @zsd4yr , can you check of "OK" string is translated for any other dialog?

I am saying that the string is not translated in the xlfs

**Comment by lukaschal** [comment]
Localized in a NetFX in a year 2005.

File: 0; "TextParseFailedFormat"
ID: Localized\ENU\System.Drawing.dll
SRC: Text "{0}" cannot be parsed. The expected text format is "{1}".
TGT: {0} metni ayrıştırılamıyor. Beklenen metin biçimi: "{1}".

**Comment by lukaschal** [comment]
TRK button "OK" localized now in a xlf file.

File: System.Windows.Forms\src\Resources\xlf\SR.xlf
ID: 0; "ExDlgOk"
SRC: OK
TGT: Tamam

**Comment by zsd4yr** [comment]
@vivmishra what do we want to do about places where translations differ between desktop fx and core?

**Comment by vivmishra** [comment]
We should get it reviewed by loc team at a minimum so that we are not introducing bugs.

**Comment by lukaschal** [comment]
String mentioned below is localized in a NetFX_Dev1 and NetFXRel1, but for now not occurs in a dotnet_winforms localization resources.

File: Localized\ENU\System.Drawing.dll
ID: 0; "TextParseFailedFormat"
SRC: Text "{0}" cannot be parsed. The expected text format is "{1}".
TGT: {0} metni ayrıştırılamıyor. Beklenen metin biçimi: "{1}".

**Comment by weltkante** [comment]
@lukaschal I think System.Drawing is not part of WinForms, its part of corefx and lives in a separate repository.

**Comment by janbaltus** [comment]
@vivmishra we are able to fix the OK and Cancel issue, but not the untranslated issue for source (SRC: Text "{0}" cannot be parsed. The expected text format is "{1}".) as this is located in corefx which is now with no loc support.

**Comment by janbaltus** [comment]
OK translation issue fixed with PR https://github.com/dotnet/winforms/pull/1022/files

**Comment by Jessie-Zhang01** [comment]
Verified in .Net Core SDK 3.0.100 Preview6 latest build 3.0.100.12103 from Master branch. This bug is fixed.
![image](https://user-images.githubusercontent.com/45864649/58542299-ea732800-822f-11e9-8bdf-90d8c8560deb.png)
