### ISSUE TITLE
Toolstrip dropdown items freeze Office UI application

### ISSUE THREAD

**Issue by XavierNV** [dotnet/winforms#10056]
### .NET version

This issue occurs within office com add ins and concerns the .net framework (4.8). It's quite annoying as it prevent usage of toolstrip in Office application (Excel, Powerpoint, Word) if we use dropdown items - which is the main reason/advantage of using this control...

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Not concerned : Office com addins canno't use .Net 5 + (only .Net Framework)
(but the bug does not arrive on a "classic" windows form application  - developped using .Net 7.0 ) 

### Issue description

I'm using a toolstrip with toolstripitems: buttons and dropdownbuttons (or splitbutton) to display custom usercontrol (form's Options, Filters for a gridview...) When manipulating the toolstrip if you open a dropdown menu, then go with mouseto a sub menu items or an hosted (user)control and then leave the dropdown by entering another toolstrip item using the mouse, the Office UI application become frozen (1). This arrives immediatly (if the form is modeless) of after closing the form (for a modal form)
(1) Frozen behaviour :
- In Powerpoint: the working space (slide) do not allow selecting shapes anymore, the ribbon may become disabled
- In Excel: the working space (worksheet) do not allow selecting shapes anymore, cells may be selected but not filled with value, the ribbon may become disabled
- In Word: the working space do not allow selecting shapes anymore

NB : The problem do not arrive if the toolstrip :
- contains a single toolstripitem using a dropdown (ie no other toolstrip items (eg buttons) included)
- if the mouse go over the dropdown submemnu or hosted (user)control and then leave the toolstrip without hovering another toolstripitems

NB : If you activate another application (eg : browser, visual studio...) and then go back to Office, the ribbon of your Office application may become enabled (allowing closing the app) - but if you click on the working space the ribbon will come back to disabled state ! NB : you may need to use the Windows Task manager dialog box (Ctl+Alt+Del) to terminate the Office application process...

### Steps to reproduce

How to reproduce the problem :
- Create an Office VSTO/ COM addins
- Create a new empty form :
- Call the following code (in the Form_Load event for example)
- Manipulate any dropdown buttons this way : Click on "C 2" to open the dropdown menu. Move the cursor on the "B" letter of the "checkBox" then from there move the cursor upper to "C 3" button (then the dropdown automatically close)
- Close the form. Et voila ! 

```
Private Sub CreateToolstripDropDownsItems() 
      'Create Toolstrip 
      'NB: if bUseMultiToolStrips= true (ie DropDownsItems are in different toolstrip) the UI remains stable 
      'If false the UI will freeze 
      Dim bUseMultiToolStrips = False 
      'Use a ToolStripDropDownMenu with margins or classic (no incidence) 
      Dim bUseDropDownItems = False 
      ' 
      Dim tsToolStrip As ToolStrip 
      'Add 5  
      For i = 1 To 5 
          If i = 1 OrElse bUseMultiToolStrips Then 
              tsToolStrip = New ToolStrip 
              Me.Controls.Add(tsToolStrip) 
              tsToolStrip.Dock = DockStyle.Top 
          End If 
          'Add a native control but we could also use a usercontrol 
          Dim chkBox As New CheckBox() 
          chkBox.Text = $"CheckBox {i}" 
          Dim tsControlHost As New ToolStripControlHost(chkBox) 
          'Create a ToolStripDropDownButton 
          Dim tsDDownBtn = New ToolStripDropDownButton() 
          tsDDownBtn.Text = $"C {i}" 
          tsDDownBtn.DisplayStyle = ToolStripItemDisplayStyle.Text 
          'Définit le ToolStripDropDown avec le control dedans 
          If bUseDropDownItems Then 'use a ToolStripDropDownMenu with margins.. 
              tsDDownBtn.DropDownItems.Add(tsControlHost) 
              Dim tsDropDownMenu = DirectCast(tsDDownBtn.DropDown, ToolStripDropDownMenu) 
          Else 'use a classic ToolStripDropDown 
              Dim tsDropDown As New ToolStripDropDown() 
              tsDropDown.Items.Add(tsControlHost) 
              tsDDownBtn.DropDown = tsDropDown 
          End If 
          'Add at End 
          tsToolStrip.Items.Add(tsDDownBtn) 
      Next 

  End Sub 
```

See also the discussion on addin express forum : [https://www.add-in-express.com/forum/read.php?FID=5&TID=16604](url)

**Comment by elachlan** [comment]
@merriemcgaw this is a .net framework issue.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you move this to the internal AzDO and then close this issue?

@XavierNV thank you so much for filing this issue. As you may know .NET Framework is considered "done" and the bar for any fixes is extremely high. At present we are focused on security and accessibility primarily. I will be happy to investigate the broader impact of this issue and see if it is suitable for a .NET Framework servicing update, but as I mentioned the bar is quite high to clear.

**Comment by XavierNV** [comment]
I understand... Thanks for your answer @merriemcgaw...

**Comment by Olina-Zhang** [comment]
@XavierNV could you please provide a sample application? In order to I can use it to repro your issue in Visual Studio, then file an internal bug to track. Thanks!

**Comment by Olina-Zhang** [comment]
@XavierNV I have created a reproduce application now.

**Comment by XavierNV** [comment]
@Olina-Zhang : did you created a VSTO addin and a form with the code in my first message (or any toolstrip with dropdown items?). Not sure to understand if you still need a sample application from me ?
I will not be able to give you a sample VSTO addin (i'm using addin express tool for Com addins creation)... But i can give you the code for the form - or i can suggest ADX team to give you a VSTO addin...

**Comment by Olina-Zhang** [comment]
@XavierNV Yes, I used that form_load event code in my created PowerPoint/word add-in application, with added a ribbon to show form, and click the MenuItem to open its dropdown, then close from. It leads to I cannot interact with slide in PowerPoint, cannot input something in word-- see following recording. Don't need a sample from your side now.
![PowerPoint_freeze](https://github.com/dotnet/winforms/assets/26474449/e014e313-9391-43da-9a73-3c1b6382d6f0)
