### ISSUE TITLE
Remove all Instances of System.Configuration

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#1007]
From email thread:

> In .NETCore we don’t recommend the use of app.config (none of the framework types honor its settings) nor does machine.config exist. 

> App.config doesn’t flow into AppContext since CoreCLR doesn’t read app.config.  AppContext still exists and you can access the values via the API.

**Comment by zsd4yr** [comment]
@dreddy-work has a PR almost ready for this

**Comment by zsd4yr** [comment]
Adding content from email thread:

> ASP.NET has its own config API https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2
> https://github.com/aspnet/Extensions/tree/master/src/Configuration
> 
> In CoreFX we opt for API for most config settings.  In some cases we use AppContext.  RuntimeConfig can plumb through host  config values which can drive AppContext and be accessed through AppContext.GetData or AppContext.TryGetSwitch.
> https://github.com/dotnet/cli/blob/master/Documentation/specs/runtime-configuration-file.md
> 
> For example a RuntimeConfig with the following settings:
> {
>   "runtimeOptions": {
>     "tfm": "netcoreapp3.0",
>     "framework": {
>       "name": "Microsoft.NETCore.App",
>       "version": "3.0.0-preview6-27629-04"
>     },
>     "configProperties": {
>       "MyProperty": true,
>       "AnotherProperty": 24,
>       "YetAnotherProperty": "Value"
>     }
>   }
> }
> 
> 
> These can be accessed as follows
>             Console.WriteLine(AppContext.GetData("MyProperty"));
>             Console.WriteLine(AppContext.GetData("AnotherProperty"));
>             Console.WriteLine(AppContext.GetData("YetAnotherProperty"));
>             if (AppContext.TryGetSwitch("MyProperty", out bool isEnabled))
>             {
>                 Console.WriteLine($"MyProperty is set to {isEnabled}");
>             }
> 
> And the output is 
> true
> 24
> Value
> MyProperty is set to True
> 
> Users can control the content of the runtimeconfig via methods mentioned here: https://github.com/dotnet/docs/issues/2645#issuecomment-458288615

**Comment by merriemcgaw** [comment]
@dreddy-work please submit this PR when you can
