### ISSUE TITLE
How can I make my top-level bin folder contains only the .exes and .exe.configs, and all the interop dll's are neatly tucked away?

### ISSUE THREAD

**Issue by wang9th** [dotnet/winforms#10075]
### Which files are affected?

I have a Winforms project running on .NET 6.0 in Windows 11.
It refers to some third-party dll, and they will be copied to ouputpath at build time.
How can I make my top-level bin folder contains only the .exes and .exe.configs, and all the interop dll's are neatly tucked away?
For example:
```shell
├─app.exe
├─app.config
├─app.deps.json
├─dll
│   └─a.dll
│   └─b.dll
│   └─c.dll
│   └─ ···
```

I tried to add an app.config file, like this:
``` xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="dll;" />
    </assemblyBinding>
  </runtime>
</configuration>
```
But it does not work.

### Which languages are affected?

c#

**Comment by elachlan** [comment]
@JeremyKuhne would this be more msbuild or SDK?

**Comment by elachlan** [comment]
@KlausLoeffelmann maybe you know?

**Comment by KlausLoeffelmann** [comment]
FWIW, you could achieve this with PostBuildEvents, but then you would need to resolve the assemblies also manually in a dedicated assembly resolver inside of your app in addition, if I assess this correctly. I would personally not recommend that. 

But yes, this is not a WinForms specific topic and more something for StackOverflow, I assume.
