### ISSUE TITLE
After moving Button on the Manually Align Controls by hand page of the DemoConsole application, it fails to focus on component controls

### ISSUE THREAD

**Issue by MandiMan** [dotnet/winforms#10082]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.Net 8.0 from Release/8.0 branch of Winforms repo without buttons

### Issue description

In the Align Controls by hand page of the [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test application in the Winforms repo, moving Button3 or Button4 and then clicking on component control, the component control cannot be focused and moved.

### Steps to reproduce

Actual result in DemoConsole application when testing main branch:

https://github.com/dotnet/winforms/assets/108860782/e838fc43-2456-4b6f-8496-a2a5fcd843fe

**Comment by Olina-Zhang** [comment]
Verified this issue in main branch of Winforms repo, it was fixed, now all controls can be focused in "Align control by hand" tabpage of [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) application:
![GH10082](https://github.com/dotnet/winforms/assets/26474449/da8b61a1-0b6c-4d90-8ec8-90eda8e1f1c5)
