### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.' occurs when delete button control then click undo in DemoConsole application

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#10096]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works well in .Net 8.0 from Release/8.0 branch of Winforms repo. The original issue is [9412](https://github.com/dotnet/winforms/issues/9412).

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, System.NullReferenceException: 'Object reference not set to an instance of an object.' occurs when delete button control then click undo.
Actual result in DemoConsole application when **testing main branch**:

https://github.com/dotnet/winforms/assets/94418985/80c58b85-6df8-4d5b-acf7-2a7655cbc567

**Call Stack:**
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Windows.Forms.Design
  StackTrace:
   at System.ComponentModel.Design.Serialization.CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.DeserializeModifier(IDesignerSerializationManager manager, String name, Object state) in C:\test\winforms\src\System.Windows.Forms.Design\src\System\ComponentModel\Design\Serialization\CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs:line 421

  This exception was originally thrown at this call stack:
    System.ComponentModel.Design.Serialization.CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.DeserializeModifier(System.ComponentModel.Design.Serialization.IDesignerSerializationManager, string, object) in CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs

Expected result in DemoConsole application when **testing release/8.0 branch**:

https://github.com/dotnet/winforms/assets/94418985/bcaf868f-1ff7-4f16-bbf5-942a3e1b1cfe

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by Olina-Zhang** [comment]
Another repro scenario: for TreeView control in DemoConsole application, add a treeNode in "TreeNode Collection Editor" dialog, then click "Cancel" button, it goes to above same exception with an error.
![Exception1](https://github.com/dotnet/winforms/assets/26474449/a2fa8601-360f-4dd7-ace5-efcf49575571)

**Comment by gpetrou** [comment]
@halgab looks like https://github.com/dotnet/winforms/pull/9120 caused this.

**Comment by halgab** [comment]
I'll have a look asap

**Comment by halgab** [comment]
Thanks a lot for the heads up, and really sorry for the bug. I've managed to track in down to a missing null check. Fix is #10122

**Comment by Zheng-Li01** [comment]
Verified this issue from main branch of winforms repo, this issue have been fixed that the applicaiton working well when delete button control then click undo in DemoConsole application or add a treeNode in "TreeNode Collection Editor" dialog, then click "Cancel" button, see below screenshot. and also do others basic testing, no new issue found.
![Issue10096](https://github.com/dotnet/winforms/assets/38325459/5641e8a4-3949-4368-9abd-ae052daf1684)
