### ISSUE TITLE
[Announcement] Dreddy-work is signing off!

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#10094]
After having served as the repository owner and maintainer for the past year, I am embarking on a new chapter within Microsoft. This journey has been genuinely rewarding, and together, we have made great progress in advancing WinForms and nurturing a thriving community. WinForms has played a significant role in my Microsoft career, and I intend to continue contributing to this repository in a contributor capacity whenever the opportunity arises.

I'd like to express my sincere thanks to @lonitra for accepting the responsibility of taking over as the repository owner and maintainer moving forward.

Please don't hesitate to mention me in issues or pull requests where my input could be valuable.

Thank you, everyone!
Devendar

**Comment by elachlan** [comment]
Thanks @dreddy-work and good luck!

**Comment by gpetrou** [comment]
Thanks for your work on WinForms. Best of luck with your new role.
