### ISSUE TITLE
Visual Studio doesn't support ILProtector project files

### ISSUE THREAD

**Issue by whitequill** [dotnet/winforms#1009]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.105 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

* Have you experienced this same bug with .NET Framework?: N/A

**Problem description:**
When you open the project file for Winforms it throws a warning saying that Accessibility.ilproj is unsupported.

I have opened this up in VS 2013 and VS 2015 they both show it as being unsupported as well.
The warning I pasted is from

**Actual behavior:** 

_Note: This warning was thrown in VS 2015 Community even though it says it can be opened in VS 2015_

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Accessibility, "D:\Users\brazg\Documents\GitHub\winforms\src\Accessibility\src\Accessibility.ilproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - WinformsControlsTest, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\WinformsControlsTest.csproj"
	 - System.Windows.Forms, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Windows.Forms\src\System.Windows.Forms.csproj"
	 - System.Windows.Forms.Tests, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Windows.Forms\tests\UnitTests\System.Windows.Forms.Tests.csproj"
	 - System.Windows.Forms.Design.Editors, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Windows.Forms.Design.Editors\src\System.Windows.Forms.Design.Editors.csproj"
	 - System.Windows.Forms.Design.Editors.Tests, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Windows.Forms.Design.Editors\tests\UnitTests\System.Windows.Forms.Design.Editors.Tests.csproj"
	 - System.Windows.Forms.Design.Tests, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Windows.Forms.Design\tests\UnitTests\System.Windows.Forms.Design.Tests.csproj"
	 - System.Windows.Forms.Design, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Windows.Forms.Design\src\System.Windows.Forms.Design.csproj"
	 - System.Drawing.Design.Facade, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Drawing.Design\src\System.Drawing.Design.Facade.csproj"
	 - System.Design.Facade, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Design\src\System.Design.Facade.csproj"
	 - Microsoft.Private.Winforms, "D:\Users\brazg\Documents\GitHub\winforms\pkg\Microsoft.Private.Winforms\Microsoft.Private.Winforms.csproj"
	 - Microsoft.Dotnet.Winforms.ProjectTemplates, "D:\Users\brazg\Documents\GitHub\winforms\pkg\Microsoft.Dotnet.WinForms.ProjectTemplates\Microsoft.Dotnet.Winforms.ProjectTemplates.csproj"
	 - pkg, "pkg"
	 - src, "src"
	 - tests, "tests"
	 - facade, "facade"
	 - unit, "unit"
	 - integration, "integration"
	 - System.Windows.Forms.IntegrationTests, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Windows.Forms\tests\IntegrationTests\System.Windows.Forms.IntegrationTests\System.Windows.Forms.IntegrationTests.csproj"
	 - System.Drawing.Facade, "D:\Users\brazg\Documents\GitHub\winforms\src\System.Drawing\src\System.Drawing.Facade.csproj"
	 - InternalUtilitiesForTests, "D:\Users\brazg\Documents\GitHub\winforms\src\Common\tests\InternalUtilitiesForTests\InternalUtilitiesForTests.csproj"
	 - Accessibility-version, "D:\Users\brazg\Documents\GitHub\winforms\src\Accessibility\ver\Accessibility-version.csproj"
	 - Accessibility, "Accessibility"
	 - Winforms, "D:\Users\brazg\Documents\GitHub\winforms\Winforms.sln"

**Expected behavior:**
The project loads normally without warnings or errors.

**Minimal repro:**

**Comment by merriemcgaw** [comment]
@whitequill Is this a .NET Core WinForms project? You may need to contact the software vendor for ILProtector to find out what is happening here. It seems to be outside the scope of WinForms for .NET Core.

**Comment by weltkante** [comment]
Yes [Accessibility.ilproj](https://github.com/dotnet/winforms/blob/master/src/Accessibility/src/Accessibility.ilproj) is a .NET Core WinForms project.

The OP may have misassociated the ilproj file extension to ILProtector when its more likely a VS extension like https://github.com/DzonnyDZ/ILProj

> This warning was thrown in VS 2015 Community even though it says it can be opened in VS 2015

I think the original problem is that he's trying to open the .NET Core WinForms solution in VS 2015 ... I don't know if thats a supported scenario.

**Comment by weltkante** [comment]
Found dotnet/coreclr#20816 which says ilproj is now an "official" project type but has no VS project system yet. I assume they never intended it to be opened in older VS versions.

If .NET Core WinForms claims somewhere to build in pre-VS 2017 that may need to be corrected.

**Comment by RussKie** [comment]
I can't find where we're saying the project can be built in 2017.
