### ISSUE TITLE
DataGridColumn's default property points to a non-existing property

### ISSUE THREAD

**Issue by dotMorten** [dotnet/winforms#101]
In the following line:

https://github.com/dotnet/winforms/blob/cfde4d047a4724a69d90f4bec57f29af1f1e83ab/src/System.Windows.Forms/src/System/Windows/Forms/DataGridColumn.cs#L35

The `[DefaultProperty]` tag points to the property `Header` which doesn't exist. I'm assuming it was meant to point to the `HeaderText` property.

Discovered as part of PR #86

**Comment by karelz** [comment]
Seems to be present also on .NET Framework.
Any idea what is the impact on apps / dev scenarios?

**Comment by karelz** [comment]
Seems to be present also on .NET Framework.
Any idea what is the impact on apps / dev scenarios?

**Comment by zsd4yr** [comment]
@merriemcgaw do we have any idea what we want to do about this?

**Comment by merriemcgaw** [comment]
It looks like the following code needs to be removed and the property changed to "HeaderText". 
```cs
 #if false
            DataTable myDataTable = myTable.DataTable;
            if (myDataColumn.Table != myDataTable) {
                throw new InvalidOperationException(string.Format(SR.DataGridColumnDataSourceMismatch, Header));
            }

            /* FOR DEMO: Microsoft: DataGridColumnStyle::CheckValidDataSource: make the check better */
            if (((DataView) value.DataSource).Table == null) {
                throw new InvalidOperationException(string.Format(SR.DataGridColumnNoDataTable, Header));
            }
            else {
                /* FOR DEMO: Microsoft: DataGridColumnStyle::CheckValidDataSource: make the check better */
                if (!myTable.DataTable.Equals(((DataView) value.DataSource).Table)) {
                    throw new InvalidOperationException(string.Format(SR.DataGridColumnNoDataSource, Header, myTable.DataTable.TableName));
                }
            }
#endif // false 
```
