### ISSUE TITLE
MenuStrip constructor throwing exception

### ISSUE THREAD

**Issue by jmarkyston** [dotnet/winforms#1015]
I don't know if this actually has anything to do with this repo itself. The error actually gets thrown from System.Drawing.Common. Let me know if I should post this over there instead.

When my Designer.cs file news-up a MenuStrip (`this.nav = new System.Windows.Forms.MenuStrip()`), the following exception is thrown:

`System.TypeInitializationException: 'The type initializer for 'Gdip' threw an exception.'

TypeLoadException: Could not load type 'System.Runtime.InteropServices.NativeLibrary' from assembly 'System.Runtime.InteropServices, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.`

Again, the `Source` of this exception is System.Drawing.Common, so let me know if this is unrelated to this repo. Also, note that the project builds without errors. This only happens at runtime.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you help us confirm that the menustrip can be created successfully.

**Comment by Amy-Li02** [comment]
Verified the issue with the latest .NET Core SDK 3.0.100.12499 -preview7 from master branch, menustrip can be created successfully, no exception was thrown both design time and runtime.

**Comment by jmarkyston** [comment]
Great! I'm not seeing that preview version in the usual places: https://dotnet.microsoft.com/download/dotnet-core/3.0
https://github.com/dotnet/core/releases

Should I wait for it to become available publically, or should I install it from somewhere else?

**Comment by weltkante** [comment]
@jmarkyston preview7 isn't released yet, you'll have to consume [daily builds](https://github.com/dotnet/core/blob/master/daily-builds.md) or wait for it

**Comment by jmarkyston** [comment]
Cool. Thanks guys. I'll let you know how it goes.

**Comment by merriemcgaw** [comment]
Sounds like this is taken care of, fantastic! I'll close the issue but if it recurs feel free to reopen it.
