### ISSUE TITLE
Automation case about XHtmlElementCollection met an error "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#10188]
### .NET version

.NET 9.0.100-alpha.1.23523.12

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro in .NET SDK 8.0.100-rc.2.23502.2.

https://github.com/dotnet/winforms/assets/94418985/c59cbc12-21e3-4341-81bf-ff2c43dcb902

### Issue description

Automation case about XHtmlElementCollection met an error "Object reference not set to an instance of an object"

https://github.com/dotnet/winforms/assets/94418985/8f067419-f30c-4420-88f7-4bce50ca98e7

**Call Stack:**
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Windows.Forms.Primitives
  StackTrace:
   at Windows.Win32.System.Com.IDispatch.QueryInterface(Guid* riid, Void** ppvObject)
   at System.Windows.Forms.HtmlElementCollection.get_Item(String elementId)
   at WinFormsApp113.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\xxx\source\repos\WinFormsApp113\WinFormsApp113\Form1.cs:line 26

### Steps to reproduce

1. Download and extract project: [XhtmlElements error.zip](https://github.com/dotnet/winforms/files/13162167/XhtmlElements.error.zip)
2. Build and run
3. Click button1

**Comment by Philip-Wang01** [comment]
Verified this on .NET 9.0.100-alpha.1.23551.16, issue was fixed. Automation case about XHtmlElementCollection does not pop up an error message.

https://github.com/dotnet/winforms/assets/86937911/d6eeb9bc-b2bd-4c8c-81c7-d8c88154e357
