### ISSUE TITLE
An exception pops up when testing HtmlWindow's Opener and WindowFrameElement properties

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#10193]
### .NET version

.NET 9.0.100-alpha.1.23523.12

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes

### Issue description

Automation case about XHtmlWindow met an error "Object reference not set to an instance of an object" when testing HtmlWindow's Opener and WindowFrameElement properties. 

We created a test sample with that exception in .Net 9, got following result:
**HtmlWindow's Opener** 
![image](https://github.com/dotnet/winforms/assets/26474449/d6844085-3826-4d13-9b6f-8440d2c537dc)
_System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Windows.Forms.Primitives
  StackTrace:
   at Windows.Win32.System.Com.IDispatch.QueryInterface(Guid* riid, Void** ppvObject)
   at System.Windows.Forms.HtmlWindow.get_Opener()
   at WinFormsApp20.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\xxx\source\repos\WinFormsApp20\WinFormsApp20\Form1.cs:line 12_

**HtmlWindow's WindowFrameElement** 
![image](https://github.com/dotnet/winforms/assets/26474449/235d2233-3862-471e-b81f-5e437ee0983b)
_System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Windows.Forms.Primitives
  StackTrace:
   at Windows.Win32.Web.MsHtml.IHTMLFrameBase.QueryInterface(Guid* riid, Void** ppvObject)
   at System.Windows.Forms.HtmlWindow.get_WindowFrameElement()
   at WinFormsApp20.Form1.button2_Click(Object sender, EventArgs e) in C:\Users\xxx\source\repos\WinFormsApp20\WinFormsApp20\Form1.cs:line 17_

### Steps to reproduce

1. Download and extract project: [HtmlWindowSample.zip](https://github.com/dotnet/winforms/files/13172458/HtmlWindowSample.zip)
2. Build and run
3. Click buttons: HtmlWindow.Opener and HtmlWindow.WindowFrameElement

**Comment by MelonWang1** [comment]
Verified this on .NET 9.0.100-alpha.1.23551.16, issue was fixed. No exception pops up when testing HtmlWindow's Opener and WindowFrameElement properties. But the automation case about XHtmlWindow still has error, filed a new issue [10218](https://github.com/dotnet/winforms/issues/10218).

https://github.com/dotnet/winforms/assets/94418985/ec05416a-f0f1-4c48-9eaa-08007289dcca
