### ISSUE TITLE
DataGridTextBox's default property points to a non-existing property

### ISSUE THREAD

**Issue by dotMorten** [dotnet/winforms#102]
In the following line:

https://github.com/dotnet/winforms/blob/cfde4d047a4724a69d90f4bec57f29af1f1e83ab/src/System.Windows.Forms/src/System/Windows/Forms/DataGridTextBox.cs#L25

The `[DefaultProperty]` tag points to the property `GridEditName` which doesn't exist. I'm not sure which property this was really meant to point to - especially considering this class doesn't have any properties.

Discovered as part of PR #86

**Comment by karelz** [comment]
@dotMorten assigning to you as you volunteered ;)

**Comment by dotMorten** [comment]
Fixed and merged!

**Comment by dotMorten** [comment]
@karelz Errr that milestone though... :)

**Comment by karelz** [comment]
Base on my experience from CoreFX repo, it is best to update milestones on closed issues and PRs on regular basis, after the fact. I do it every 1-4 weeks on CoreFX, at minimum prior to a release.
There is no way all engineers will pay attention to milestones. It is lost battle + it is easier to do batch changes later on than train everyone and push process on them 😉 (I am big believer in minimal process).

That said, I will fix this one ;)
