### ISSUE TITLE
Winforms NativeAOT

### ISSUE THREAD

**Issue by dadavadd** [dotnet/winforms#10208]
Are there any plans to optimize WinForms for NativeAOT? Or will this never happen?

**Comment by danmoseley** [comment]
I’m curious whether there’s insurmountable technical reasons or it’s more about the work required.

cc @eerhardt

**Comment by elachlan** [comment]
There is a large effort happening in winforms at the moment to enable AOT/trimming.

See #4649

**Comment by merriemcgaw** [comment]
@danmoseley it's about how much work there is to make this happen. That said, we're really focusing right now on the fundamentals that will enable AOT and Trimming over the next release or two. We've got lots of folks asking for it and the team is in agreement about how important the work is for us.

I am going to close this issue, in favor of the one @elachlan linked. That's the parent issue we're using as we work through getting this enabled.
