### ISSUE TITLE
Inconsistent DomWindow values

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#10218]
### .NET version

.NET 9.0.100-alpha.1.23551.16

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it cannot repro in .NET 3.1/5.0/6.0/7.0/8.0.

### Issue description

Automation case about XHtmlWindow met an error "FAIL: equality between windows failed" when testing HtmlWindow's op_Equality, get_Frames methods.

We created a test sample in .NET 9, got following result:
**The DomWindow has inconsistent values. In .NET 9.0:**
![CORE9 0](https://github.com/dotnet/winforms/assets/94418985/3781aac1-2060-4710-8659-143dc35a3f2f)

**In .NET 3.1~8.0 and Framework app:**
![FRAMEWORK](https://github.com/dotnet/winforms/assets/94418985/06943c25-1861-451e-9c31-2b7beff344c4)

### Steps to reproduce

1. Download and extract project: [DomWindow.zip](https://github.com/dotnet/winforms/files/13233689/DomWindow.zip)
2. Build and run
3. Click button1 and observe DomWindow value

**Comment by elachlan** [comment]
Is the issue that the `DomWindow` in main branch doesn't have the same properties as the olded .net versions?

> Gets the unmanaged interface wrapped by this class.

https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.htmlwindow.domwindow?view=windowsdesktop-7.0

It's typed as an object:
```csharp
public object DomWindow { get; }
```

**Comment by lonitra** [comment]
Yes, we had changed the inner type to an `AgileComPointer` and this is now no longer giving back the COM interface, which is a mistake.

**Comment by MelonWang1** [comment]
Verified this on .NET 9.0.100-alpha.1.23558.10, issue was fixed. But the automation case about XHtmlWindow still has error, filed a new issue [10261](https://github.com/dotnet/winforms/issues/10261).
![domwindow](https://github.com/dotnet/winforms/assets/94418985/231fb12d-9033-40f8-a904-876d87f01dd0)
