### ISSUE TITLE
Unable to add columns/rows via the Edit Rows and Columns window of the TableLayoutPanel control in the DemoConsole application

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#10213]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it doesn't work in .Net 8.0 from Release/8.0 branch of Winforms repo

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, unable to add columns/rows via the Edit Rows and Columns window of the TableLayoutPanel control.

**Actual result** in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app:

https://github.com/dotnet/winforms/assets/94418985/8734d29d-5db7-4674-8065-339b38f22e35

**Expected result**:
Columns/rows can be added via the Edit Rows and Columns window of the TableLayoutPanel control. But the column and row will not be refreshed in TableLayoutPanel after click the 'X' to close the Column and Row Styles dialog. Has known issue: [2508](https://github.com/microsoft/winforms-designer/issues/2508).

https://github.com/dotnet/winforms/assets/94418985/ff614d04-d333-4894-9030-d9692b25a8ed

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team take a look at this? It may be interesting/educational for the other project you're working on.

**Comment by LeafShi1** [comment]
> @LeafShi1 can your team take a look at this? It may be interesting/educational for the other project you're working on.

OK, we will investigate this issue.

**Comment by Philip-Wang01** [comment]
Verified this on winforms repo from main branch, columns/rows can be added via the Edit Rows and Columns window of the TableLayoutPanel control.

https://github.com/dotnet/winforms/assets/86937911/f4b54df6-9fa3-49bb-94aa-353dbaf3b112
