### ISSUE TITLE
[Accessibility] Accessibility Insights tool keeps loading when detecting listBox control with scrollbar

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#10258]
### .NET version

9.0.100-alpha.1.23558.10

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

It's a regression issue. Not repro on .NET 8.0/7.0/6.0.

### Issue description

Accessibility Insights tool keeps loading and does not display test results.

https://github.com/dotnet/winforms/assets/86937911/e54014b2-8d7e-45b7-a50e-66abc009a750

![image](https://github.com/dotnet/winforms/assets/86937911/bb9349e7-cfa2-4be5-b929-0bb0aa7e3c26)

### Steps to reproduce

1. Create a WinForms .NET Core application with ListBox control.
2. Add multiple Items to the ListBox and make sure it has scrollbars.
3. Build and run the application.
4. Open the Accessibility Insights tool, Select the ListBox and click Test Element.

**More Info:**
1. This issue is also reproduced in the CheckListBox control.
2. This issue is not reproduced in the ComboBox and TreeView controls.
3. **This issue is only reproduced when the control has a scrollbar.**

**Comment by Amy-Li03** [comment]
This issue also reproes for ListView control, no matter it has scrollBar or not.

**Comment by Tanya-Solyanik** [comment]
Seems to be related to https://github.com/dotnet/winforms/commit/383225d62ba125f3dfc0183d2f24dfd03da04a3d

**Comment by Zheng-Li01** [comment]
Verified the issue on 9.0.0-alpha.1.23558.4 with dlls build form main branch, the issue has been fixed that the Accessibility Insights tool working well when detecting listBox/CheckListBox /LisView controls with scrollbar or not.
![10258](https://github.com/dotnet/winforms/assets/38325459/befe6909-8e79-4c74-b749-aadd0a6ea56e)
