### ISSUE TITLE
ValuePattern.Value property changed event is not sent from TextBox control.

### ISSUE THREAD

**Issue by heh-ad** [dotnet/winforms#10257]
### .NET version

.NET 8.0 RC2

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET 7.0.13

### Issue description

When listening to UIA events from the TextBox control, only text changed event is sent in .NET 8. However, there is also value property changed event in .NET 7.

.NET 7
https://github.com/dotnet/winforms/assets/85718983/6fbb2ba7-083a-4185-8662-a411fe9d2fcd

.NET 8
https://github.com/dotnet/winforms/assets/85718983/fd75b565-f281-4a48-aa00-1fe1ac568c22

This may be caused by this PR https://github.com/dotnet/winforms/pull/7741 that implements the UIA provider for TextBox.

### Steps to reproduce

1. Insert a TextBox control to a Form.
2. Run the application.
3. Open Accessibility Insights for Windows and listen to UIA events of the TextBox.
4. Input characters in the TextBox and observe the events.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this to confirm?

**Comment by Zheng-Li01** [comment]
@elachlan  @heh-ad , test this issue on the .NET7 & .NET8 & .NETFramework 4.8.1 that all have the same results, only text changed event is sent when Inputting  characters in the TextBox, see below details.

**.NET7**
![NET7](https://github.com/dotnet/winforms/assets/38325459/8ed93b5c-5b84-45bf-9251-153a987ca5f1)

**.NET8**
![NET8](https://github.com/dotnet/winforms/assets/38325459/10b65833-d377-4e27-8169-6a3549fc712f)

**.NETFramework4.8.1**
![NETFramework](https://github.com/dotnet/winforms/assets/38325459/d08be9f0-42b0-4580-8872-a83a95fe77f6)

**Comment by elachlan** [comment]
@heh-ad can you comment on the above results please?

**Comment by Olina-Zhang** [comment]
@elachlan @heh-ad I double-checked this issue again, it seems above Zheng's result is not correct in .Net 7.0, maybe he didn't check properties for listening events. In .Net 7.0, it has AutomationPropertyChanged event about ValuePattern.Value sent, but hasn't in .Net 8.0 and .Net 9.0. So it is a regression issue.
**.Net 7.0:**
![image](https://github.com/dotnet/winforms/assets/26474449/880c1fc4-ff36-4905-afb1-ce759b6428ce)
**.Net 8.0 and 9.0:**
![image](https://github.com/dotnet/winforms/assets/26474449/5ac250c1-043e-49a6-9436-05583752d88c)

**Comment by Amy-Li03** [comment]
Verified the issue on .NET 9.0.100-alpha.1.23613.9 with dlls built from main branch, it has been fixed that ValuePattern.Value property changed event is sent when we make changes to the text in the TextBox.
![image](https://github.com/dotnet/winforms/assets/62929087/8ccd02b1-4f83-4c07-af6e-9ef92244a4f6)
