### ISSUE TITLE
Accessibility: While Narrator on, caps lock right arrow jumps out of list box prematurely

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#1026]
**Repro steps:**
- Using the Narrator with caps lock mode set focus to list box item.
- Press caps lock + right arrow to set focus to next list box item.

**Actual:**
The Narrator jumps out of the list box without traversing the complete list.

**Expected result:**
Using Narrator with caps lock mode set to an item, caps lock right arrow passes in order of the elements of the list up and down without jumping out of the list.

**Comment by merriemcgaw** [comment]
@vladimir-krestov are you still working on this issue?

**Comment by vladimir-krestov** [comment]
@merriemcgaw I fixed this issue. I will create a new issue with items selection by the Narrator as a separate bug
