### ISSUE TITLE
Refactor `System.Drawing` to remove `DeviceContext`

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#10293]
Based on comment at https://github.com/dotnet/winforms/pull/10291#pullrequestreview-1728514633

> The System.Drawing usage (of WeakRefCollection) can ultimately go away. It is only used to get call backs on the DeviceContext disposals. If someone is feeling up for a challenge they can kill the DeviceContext class in System.Drawing. I did the same for WinForms some time ago. #3553 was the last of that change.

Related: #9879

**Comment by elachlan** [comment]
@JeremyKuhne One thing I noticed is that the `DeviceContextHdcScope` is in `System.Windows.Forms.Primatives` and relies on some of the CsWin32 types. Would these get moved to `System.Drawing.Common`?

**Comment by JeremyKuhne** [comment]
> One thing I noticed is that the DeviceContextHdcScope is in System.Windows.Forms.Primatives and relies on some of the CsWin32 types. 

Taking a dependency on CsWin32 should be explored. Note that `WindowsGraphics` is part of what goes away with this. Following the patterns in the #3553 should help in converting this stuff. All of this was in the same codebase in the past.

**Comment by elachlan** [comment]
@JeremyKuhne now that #10645 is merged, can we resolve this issue?
