### ISSUE TITLE
Tabpage should not be moved in the DemoConsole application

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#10307]
### .NET version

.NET 9.0.100-alpha.1.23564

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

It also repro's in .NET 8.0.

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, tabpage shoud not be moved.

**Actual result** in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app:

https://github.com/dotnet/winforms/assets/104609169/61c945b7-b584-478b-a981-7638e738db0e

**Expected result:**
Tabpage shoud not be moved.

https://github.com/dotnet/winforms/assets/104609169/c4c33a64-99bc-44e9-bfb6-da7d3cfc46cd

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by merriemcgaw** [comment]
@Nora-Zhou01 did this repro in .NET 6?

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team take a look too?

**Comment by LeafShi1** [comment]
> @LeafShi1 can your team take a look too?

OK, we will investigate this issue.

**Comment by Nora-Zhou01** [comment]
> @Nora-Zhou01 did this repro in .NET 6?

The tabcontrol control began to exist in the .NET 8.0 DemoConsole application, and this problem also reappears in .NET 8.0.

**Comment by Zheng-Li01** [comment]
Verified the issue on the latest  [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo from main branch, the issue has been fixed that the Tabpage cannot be moved in the DemoConsole application for now.
![10307](https://github.com/dotnet/winforms/assets/38325459/ee36dd2c-9f92-423a-bf86-10f3011cce47)

**Comment by John-Qiao** [comment]
Verified this issue in the release/9.0-preview4 branch of winforms repo, it was fixed. Test result is same as above.
