### ISSUE TITLE
The default value of bindSource.SortDesciptions has been changed

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#10342]
### .NET version

.NET 9.0 main branch

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in .NET 6.0/7.0/8.0. **Regression from: https://github.com/dotnet/winforms/pull/10253, this affects our automation test cases.**

### Issue description

.NET 9.0:
![image](https://github.com/dotnet/winforms/assets/86937911/6042b1eb-acc9-457b-b323-fc5f7c9fef82)
.NET 8.0:
![image](https://github.com/dotnet/winforms/assets/86937911/246234b7-f345-4ebb-aa6c-0ab4ddb2380e)

### Steps to reproduce

1. Create a WinForms .NET Core project with a BindingSource.
2. Double click Form1 and type below code in `Form1_Load` event:
`bindingSource1.DataSource = new string[] { "a", "b", "c" };`
3. Add a breakpoint to the event, build and run the application.
4. Check the value of bindindSource.SortDesciptions.

**Comment by Philip-Wang01** [comment]
@lonitra Below are the affected automated test cases:
![image](https://github.com/dotnet/winforms/assets/86937911/2a3bb794-3c33-420c-aeaf-a165eac5fb4d)

In .NET 9.0, the value of dc.SortDescriptions is {System.ComponentModel.ListSortDescriptionCollection}, is not equal to the expected value of null, so the test case fails. I'll modify the test case to solve this issue.

**Comment by lonitra** [comment]
Thank you for the details! Yes the expected would need to be updated to empty `ListSortDescriptionCollection` now. I will close issue since what is described is expected behavior
