### ISSUE TITLE
[Accessibility] Accessibility Insights tool keeps loading when mouse-over DataGridView 

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#10343]
### .NET version

9.0.100-alpha.1.23564.26

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

It works in .Net 7.0, doesn't in .Net 8.0

### Issue description

If mouse-click textBox cell in DataGridView, open AccessibilityInsight, then mouse-over DataGridView cell. It leads to AccessibilityInsight keeps loading.

**.Net 9.0/.Net 8.0: AccessibilityInsight keeps loading**
![DataGridView_AccessibilityInsightIssue](https://github.com/dotnet/winforms/assets/26474449/fb8ccacd-9d93-4f0d-9ddc-eeda7e2291b0)

**.Net 7.0: AccessibilityInsight works well**
![DataGridView_NET7 0](https://github.com/dotnet/winforms/assets/26474449/6743c7a0-1135-4be5-a728-02fb1e1f2f85)

### Steps to reproduce

1. Create a Winforms .Net 9.0/8.0 application
2. Add a DataGridView with TextBox cell
3. Build and run application
4. Mouse-click in DataGridView_textBox cell
5. Launch AccessibilityInsight, then mouse-over DataGridView

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - we would want to service this issue to release\8.0

**Comment by Philip-Wang01** [comment]
Verified the issue on 9.0.100-alpha.1.23614.10 with dlls build form main branch, the issue has been fixed that Accessibility Insights tool loads successfully when mouse-over DataGridView

**Comment by Philip-Wang01** [comment]
Verified issue on .NET 8.0.200 with dlls built from Release/8.0 branch of WinForms repo, the issue was fixed, test result is as above video.

**Comment by Philip-Wang01** [comment]
Verified with .NET SDK 8.0.2 test pass build, this issue was fixed. Test result is same as above.
