### ISSUE TITLE
[Accessibility] Select ListView item with mouse, Narrator can't select whole rows

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#10355]
### .NET version

9.0.100-alpha.1.23564.26

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this issue also repro's on .NET 6.0/7.0/8.0.

### Issue description

Narrator does not select the entire row when the ListView item is selected with the mouse, but it selects the entire row when it is selected with the keyboard.
**The behavior for .NET 9.0:**
![core](https://github.com/dotnet/winforms/assets/104609169/bc2b9f4c-6ffa-4f92-a119-be1d811de93c)

https://github.com/dotnet/winforms/assets/104609169/6ffed828-685c-44fc-aef0-0b501df4bb44

**The behavior for .Net framework:**
![framework](https://github.com/dotnet/winforms/assets/104609169/f6cb5ea1-2f41-40cd-ada7-cc548ba848dc)

https://github.com/dotnet/winforms/assets/104609169/1a4ed23d-a388-4457-a458-0e0f360c83ce

### Steps to reproduce

1. Create a WinForms .NET Core application with ListView control.
2. Add some columns and items to it and set the checkbox property to true.
3. Set ListView's View as Details.
4. Build and run the application.
5. Launch the Narrator tool, try to focus on the item of ListView with mouse.
6. Press up/down keyboard to focus on the other item.

**Comment by merriemcgaw** [comment]
This is combination of keyboard and mouse. Narrator works fine with just the keyboard so we won't be addressing this.
