### ISSUE TITLE
Suppress finalizeation of ThreadMethodEntry class

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#10361]
### Background and motivation

[ThreadMethodEntry](https://github.com/dotnet/winforms/blob/d20f9c71a189693c6c3475253397665bce0a1354/src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs#L11) class have a Finalizer but not implement an `IDisposable` interface. So, after **every** call to `BeginInvoke`/`Invoke` instance of `ThreadMethodEntry` will end up in Freachable queue:
![Snipaste_2023-11-22_14-23-10](https://github.com/dotnet/winforms/assets/17767561/18e44560-5e00-4c90-a447-36f2f1faf1aa)

Finalizer here to free WH:
https://github.com/dotnet/winforms/blob/d20f9c71a189693c6c3475253397665bce0a1354/src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs#L51-L54
We have 3 cases here (for all of them `ThreadMethodEntry` will end up in Freachable queue any way) :
- We not allocate WH.
- We allocate WH and use it internally (`Invoke`) - we not free it. This already violate `IAsyncResult.AsyncWaitHandle` [using rules](https://learn.microsoft.com/en-us/dotnet/api/system.iasyncresult.asyncwaithandle?view=net-8.0#notes-to-callers).
- User allocate WH through `IAsyncResult.AsyncWaitHandle` (`BeginInvoke`). And even if he properly Close this WH, `ThreadMethodEntry` will end up in Freachable queue :(

### Proposal

Suggestions:
- implement `IDisposable`?
- register for finalization only when WH is allocated.
- SuppressFinalize after WH disposed.

If you don't mind in principle, you can assignee this to me. I have some ideas on this matter, and will try to implement them as soon as find time.

### Risks

Must be minimal...

### Will this feature affect UI controls?

No

**Comment by elachlan** [comment]
@kirsan31 `ThreadMethodEntry` is `private`, so I don't think a full API review is required. Do you want to submit a PR demonstrating the fix?

**Comment by kirsan31** [comment]
> Do you want to submit a PR demonstrating the fix?

Yea:
>If you don't mind in principle, you can assignee this to me. I have some ideas on this matter, and will try to implement them as soon as find time.

**Comment by kirsan31** [comment]
@elachlan 
Sadly I need to wait until 17.8 become stable enough :(

17.7.7:
> error NETSDK1209: The current Visual Studio version does not support targeting .NET 9.0.  Either target .NET 9.0 or lower, or use Visual Studio version 17.8 or higher

P.s. error text is a bit contusing  🙄
