### ISSUE TITLE
Add webbrowser dialog

### ISSUE THREAD

**Issue by PieterjanDeClippel** [dotnet/winforms#10367]
### Background and motivation

![image](https://github.com/dotnet/winforms/assets/9629574/08f31d61-6f10-43a3-8d7d-b5000e735b35)

[Code repository](https://github.com/MintPlayer/MintPlayer.BrowserDialog)

### API Proposal

```csharp
namespace System.Xxx;

public interface IWebBrowserDiscovery {
    Task<IEnumerable<WebBrowser>> GetInstalledBrowsers();
    Task<WebBrowser> GetDefaultBrowser(EProtocolType protocol); // http, https, ftp, mailto, webcal
    Task<WebBrowser> GetDefaultBrowser(string fileType); // html, htm, xml, pdf, ...
}

internal class WebBrowserDiscovery {}
```

### API Usage

```csharp
public class TestModel {
    public TestModel(IWebBrowserDiscovery webBrowserDiscovery) {}

    public async Task Load() {
        var browsers = await webBrowserDiscovery.GetInstaledBrowsers();
    }
}
```

### Will this feature affect UI controls?

No

**Comment by elachlan** [comment]
Wouldn't you want something along the lines of #5918?

**Comment by elachlan** [comment]
@PieterjanDeClippel I guess it isn't exactly a "Broswer Selector", but it allows you to show a dialog to select the browser to open a URL.

I used [SHOpenWithDialog](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shopenwithdialog). It uses the windows APIs, so there is a chance that the team would accept this into winforms. The bonus is this is just a dialog for "Open With" and can be used for any file/URI. Its not limited to URLs.

![image](https://github.com/dotnet/winforms/assets/2433737/d5234f37-8b28-4fa2-ae1c-a8ae1230e02b)

```csharp
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
private struct OPENASINFO
{
    public string cszFile;
    public string cszClass;
    public OpenAsInfoFlags oaifInFlags;
}

[Flags]
private enum OpenAsInfoFlags
{
    OAIF_ALLOW_REGISTRATION = 0x00000001,   // Show "Always" checkbox
    OAIF_REGISTER_EXT = 0x00000002,         // Perform registration when user hits OK
    OAIF_EXEC = 0x00000004,                 // Exec file after registering
    OAIF_FORCE_REGISTRATION = 0x00000008,   // Force the checkbox to be registration
    OAIF_HIDE_REGISTRATION = 0x00000020,    // Vista+: Hide "Always" checkbox
    OAIF_URL_PROTOCOL = 0x00000040,         // Vista+: cszFile is actually a URI scheme; show handlers for that scheme
    OAIF_FILE_IS_URI = 0x00000080           // Win8+: The location pointed to by cszFile is given as a URI
}

[DllImport("shell32.dll", CharSet = CharSet.Unicode)]
private static extern int SHOpenWithDialog(IntPtr hwndParent, ref OPENASINFO oOAI);

public static void OpenUrlWithDialog(string url)
{
    OPENASINFO oai = new OPENASINFO
    {
        cszFile = url,
        cszClass = null,
        oaifInFlags = OpenAsInfoFlags.OAIF_EXEC | OpenAsInfoFlags.OAIF_FILE_IS_URI
    };

    SHOpenWithDialog(IntPtr.Zero, ref oai);
}
```

**Comment by elachlan** [comment]
@KlausLoeffelmann You might be interested in this. Any thoughts?

**Comment by RussKie** [comment]
The aim of the Windows Forms SDK is to primarily provide a more developer-friendly way (compared to MFC) to build Windows native applications. This means providing abstractions over the Windows native Win32 API.
Whilst the Windows Forms SDK provides several custom controls, it is not the charter of the SDK. The suggested controls doesn't look like it belongs to Windows, and as such it's better suited to live as a standalone 3rd party control.

**Comment by KlausLoeffelmann** [comment]
I have to agree with @RussKie on this.

This very much has the characteristics of a Third Party-Control, as it is too domain-specific (no pun intended).
I like the general idea of providing this, it's good and attentive thinking. But I am afraid not in the context of a native WinForms control.

I am closing this for now, but I have an idea in mind, we'd need to talk about around early spring next year with the WinForms Team, @RussKie, and the leading community members (looking especially at you, @elachlan, @paul1956, @kirsan31). Remind and ping me please, that I wrote this, when the snow starts melting in the Cascades, and I haven't followed up! 😸

**Comment by merriemcgaw** [comment]
I’m with @KlausLoeffelmann and @RussKie on this one.
