### ISSUE TITLE
ColumnType is disabled for Columns in EditColumns dialog

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#10364]
### .NET version

9.0.100-alpha.1.23564.26

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, reproduce in previous .Net versions

### Issue description

After the PR: https://github.com/dotnet/winforms/pull/10247, we can add different Columns Type in DataGridView by "Add Ciolumn" dialog.
 In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, find DataGridView in form designer, open "Edit Columns" dialog, the ColumnType property for Column is disabled, we cannot expand it to choose all supported column type. 

**Actual:**
![image](https://github.com/dotnet/winforms/assets/26474449/3c335ca9-ccec-4595-b93a-dfa2c25f2da3)

**Expected:**
![image](https://github.com/dotnet/winforms/assets/26474449/55875bfa-0655-43d7-9c6d-efcb5571572e)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by elachlan** [comment]
CC: @LeafShi1

**Comment by Olina-Zhang** [comment]
Verified it in DemoConsole app from main branch of winforms repo, the issue has been fixed: Now in EditColumns dialog, it supports all ColumnType, and we can modify column's ColumnType.

https://github.com/dotnet/winforms/assets/26474449/d4d52f3c-8e71-4409-ae4b-24faa918502a

**Comment by Nora-Zhou01** [comment]
Verified this issue with .NET 9 Preview 2 test pass build, it was fixed. Test result is same as above.
