### ISSUE TITLE
When operating on part of a sorted TreeView tree: Clear() hangs in a loop; Remove() removes wrong nodes.

### ISSUE THREAD

**Issue by Syspixie** [dotnet/winforms#10376]
### .NET version

.NET 8.0.

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Works as expected in .NET 7.0.

### Issue description

Starting with a clean empty TreeView:

1. Add a top level node.
2. Under the top level node, add two nodes with their Text in reverse alphabetial order.
3. Sort the TreeView to change the order of the two sub-nodes.
4. Clear the sub-nodes.

The Clear() operation hangs, and never completes.

If, instead of clearing the nodes, you try:

4. Remove the first sub node
5. Remove the second sub node.

The first Remove() removes the wrong node; the second throws an index out of range exception.

### Steps to reproduce

	var devices = new TreeNode("Devices");
	TreeView1.Nodes.Add(devices);

	var switches = new TreeNode("Switches");
	devices.Nodes.Add(switches);
	var leds = new TreeNode("LEDs");
	devices.Nodes.Add(leds);

	TreeView1.Sort();

	// Test 1
	devices.Nodes.Clear();			// Hangs
	MessageBox.Show("Cleared");		// Never reached

	// Test 2
	devices.Nodes.Remove(switches);		// Removes LEDs
	devices.Nodes.Remove(leds);		// Throws exception

**Comment by gpetrou** [comment]
I suspect I introduced this problem in https://github.com/dotnet/winforms/pull/9078.
It looks like we did not update the index correctly when sorting.

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net 9.0 SDK build + binaries built from main branch of Winforms repo, it was fixed:

https://github.com/dotnet/winforms/assets/26474449/9126597b-fe10-46bc-bb93-d2d790b200ce

**Comment by MelonWang1** [comment]
Verified this issue on .NET 8.0.100 with dlls build form release/8.0 branch, it was fixed. Test result is same as above.

**Comment by MelonWang1** [comment]
Verified with .NET SDK 8.0.101 test pass build, this issue was fixed. Test result is same as above.
