### ISSUE TITLE
WinForms TableLayoutPanel doesn't shrink correctly

### ISSUE THREAD

**Issue by CuteLeon** [dotnet/winforms#10379]
### .NET version

.Net 8.0

### Did it work in .NET Framework?

Yes

### Issue description

I hope to put a TableLayoutPanel in a Form and turn on AutoScroll to make sure have ability to display every controls in it, one of its inner control is changing height (such as a AutoSized FlowLayoutTable will change its height when inner control rearranged due to width's change), the issue is that outside TableLayoutPanel doesn't shrink with inner FlowLayoutPanel's height reducing.

### Steps to reproduce

Scenario 1:
Dock a TableLayoutPanel with {AutoScroll=true, AutoSize=true, AutoSizeMode=GrowAndShrink and one AutoSize row} to a form, dock a FlowLayoutPanel with {AutoSize=true and AutoSizeMode=GrowAndShrink} to the only row of TableLayoutPanel. TableLayoutPanel and FLowLayoutPanel don't shrink although they have enough space to display all inner controls.
``` csharp
    public Form1()
    {
        InitializeComponent();

        var tableLayoutPanel = new TableLayoutPanel
        {
            AutoScroll = true,
            AutoSize = true,
            Dock = DockStyle.Fill,
            AutoSizeMode = AutoSizeMode.GrowAndShrink,
            RowCount = 0,
            BackColor = Color.Blue,
            CellBorderStyle = TableLayoutPanelCellBorderStyle.Single
        };

        tableLayoutPanel.RowStyles.Clear();
        tableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tableLayoutPanel.RowCount++;

        var flowLayoutPanel = new FlowLayoutPanel()
        {
            AutoSize = true,
            AutoSizeMode = AutoSizeMode.GrowAndShrink,
            Margin = new Padding(20),
            BackColor = Color.Red,
            Dock = DockStyle.Fill,
        };

        for (var index = 0; index < 100; index++)
        {
            flowLayoutPanel.Controls.Add(new Button()
            {
                Text = index.ToString()
            });
        }

        tableLayoutPanel.Controls.Add(flowLayoutPanel, 0, 0);
        this.Controls.Add(tableLayoutPanel);
    }
```
![image](https://github.com/dotnet/winforms/assets/17419770/2b5e429f-650e-48c3-8245-1b87a0899d9d)

Scenario 2:
Add a empty row at bottom of TableLayoutPanel of above scenario. The 1st row will shrink correctly, but the 2nd row keeps occuping lot of height, and the whole TableLayoutPanel doesn't shrink.
``` csharp
    public Form1()
    {
        InitializeComponent();

        var tableLayoutPanel = new TableLayoutPanel
        {
            AutoScroll = true,
            AutoSize = true,
            Dock = DockStyle.Fill,
            AutoSizeMode = AutoSizeMode.GrowAndShrink,
            RowCount = 0,
            BackColor = Color.Blue,
            CellBorderStyle = TableLayoutPanelCellBorderStyle.Single
        };

        tableLayoutPanel.RowStyles.Clear();
        tableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tableLayoutPanel.RowCount++;

        var flowLayoutPanel = new FlowLayoutPanel()
        {
            AutoSize = true,
            AutoSizeMode = AutoSizeMode.GrowAndShrink,
            Margin = new Padding(20),
            BackColor = Color.Red,
            Dock = DockStyle.Fill,
        };

        for (var index = 0; index < 100; index++)
        {
            flowLayoutPanel.Controls.Add(new Button()
            {
                Text = index.ToString()
            });
        }

        tableLayoutPanel.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        tableLayoutPanel.RowCount++;

        tableLayoutPanel.Controls.Add(flowLayoutPanel, 0, 0);
        this.Controls.Add(tableLayoutPanel);
    }
```
![image](https://github.com/dotnet/winforms/assets/17419770/3030b515-f8d3-4cc9-b5bf-15077d819eff)

**Comment by CuteLeon** [comment]
A workaround is that reset TableLayoutPanel's AutoScroll once its size changed, but it caused a nother HorizontalScrollBar's issue.
``` csharp
  tableLayoutPanel.SizeChanged += (s, e) =>
  {
      tableLayoutPanel.AutoScroll = false;
      tableLayoutPanel.AutoScroll = true;
  };
```

**Comment by elachlan** [comment]
@Olina-Zhang could your team please regression test this?

**Comment by Zheng-Li01** [comment]
@elachlan Verified the issue with the code section provided by @CuteLeon, there have the same results between .NET 3.1 ~ 9.0 and .NET Framework4.6 ~ 4.8.1, see below details.

.NET:
[10379_Core_App.zip](https://github.com/dotnet/winforms/files/13469191/10379_Core_App.zip)
![10379_Core](https://github.com/dotnet/winforms/assets/38325459/71f53673-3ac7-4d03-b829-4b53d2a57a9c)

.NET Framework:
[10379_Framework.zip](https://github.com/dotnet/winforms/files/13469189/10379_Framework.zip)
![10379_Framework](https://github.com/dotnet/winforms/assets/38325459/4b03c030-896f-4fab-a966-babd26127409)

**Comment by merriemcgaw** [comment]
Thank you for reporting this! Given that this is the behavior that has been around since at least .NET Framework 4.6 we are reluctant to make changes in this space. And, since you have a workaround the best course of action would be for your product to use the workaround.
