### ISSUE TITLE
DPI rendering issue since .NET 8

### ISSUE THREAD

**Issue by StefanKoell** [dotnet/winforms#10373]
### .NET version

8.0.100

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Worked in .NET 7 and .NET 6

### Issue description

I'm aware that this is a "special" issue which may only affect me in this particular use case but I hope I can find a solution or workaround.

I have an Open Source project utilizing FreeRDP to do remote desktops in a WinForms control:
https://github.com/royalapplications/royalapps-community-freerdp

It basically starts wfreerdp.exe with a couple of CLI args to pass on a window handle, a desktop width and a desktop height.
The wfreerdp.exe then "paints" into that window handle and processes input (mouse and keyboard). This worked fine until I updated to .NET 8. I guess the DPI changes in .NET 8 broke this and I'm not sure if and how I can restore the "previous" behavior.

I tested 3 High DPI Modes with display scaling > 100%:
* DpiUnaware: scaling works fine in .NET 7 and .NET 8
* SystemAware: scaling works fine in .NET 7 but does not work in .NET 8
* PerMonitorV2: scaling works fine in .NET 7 but does not work in .NET 8

The control I use to wrap FreeRDP does some scaling calculations based on the DPI to properly "zoom" the remote session. Even if I skip these calculations and simply pass on the dimensions, scaling seems to be off.

### Steps to reproduce

1)
Clone Repo:
https://github.com/royalapplications/royalapps-community-freerdp

2)
Set display settings on the local machine to > 100%

3)
Start the Demo with .NET 7 and use Connection -> Connect to connect to a Windows machine (host and creds are prompted if not specified in code or config window)
Scaling works as expected.

4)
Start the Demo with .NET 8 and do the same as in 3)
Scaling is off

**Comment by elachlan** [comment]
@StefanKoell could you please attach some recordings/screenshots to demonstrate the issue?

**Comment by StefanKoell** [comment]
@elachlan I just found a solution at "the other side": I did some experiments with FreeRDP and when I make the process DPI aware, it is working as expected.

I'm curious though why it happened and what changed to make this necessary now but I feel the solution I found is OK and probably the correct way to handle it.

**Comment by elachlan** [comment]
Excellent to hear you found a solution. One of the winforms team might be able to give you a bit more information. But I imagine it's got to do with the mixing of dpi modes.

**Comment by StefanKoell** [comment]
Yeah, I think so too. Just curious why that worked in .NET 7 and earlier... Maybe someone can shed some light on that.
