### ISSUE TITLE
[LOC] Shortcuts localization in .net 8 must use CurrentUICulture

### ISSUE THREAD

**Issue by pmiossec** [dotnet/winforms#10384]
### Which files are affected?

With the following configuration:

- Microsoft Windows 11 (NT 10.0.22621.0)

![image](https://github.com/gitextensions/gitextensions/assets/460196/b5ad9eec-f04b-445f-aeea-afbb8544e737)

![image](https://github.com/gitextensions/gitextensions/assets/460196/bd704d50-7a24-4f2b-ba9f-ea0eb9b6ee2b)

The application [GitExtensions](https://github.com/gitextensions/gitextensions) with a keyboard shortcut defined in `.Designer.cs` file like that:

```csharp
            // 
            // fileExplorerToolStripMenuItem
            // 
            fileExplorerToolStripMenuItem.Image = Properties.Images.BrowseFileExplorer;
            fileExplorerToolStripMenuItem.Name = "fileExplorerToolStripMenuItem";
            fileExplorerToolStripMenuItem.ShortcutKeys = ((Keys)(((Keys.Control | Keys.Shift) 
            | Keys.O)));
```

when launched using .net6 ( .NET 6.0.25 ) displays shortcuts like that (in english):

![image](https://github.com/gitextensions/gitextensions/assets/460196/80ef85ab-5dc0-47bf-970b-f92ef17cd6b6)

whereas in .net8 (.NET 8.0.0 ), the shortcut is displayed in french (even if the OS is in english due to the settings defined above):

![image](https://github.com/gitextensions/gitextensions/assets/460196/1ddd7fff-41dd-4c25-96bc-04b49b27457e)

I think that keyboard shortcuts should use `CurrentUICulture` to localize instead of using the `CurrentCulture`.

It is strange to have the OS and the application in English (by choice) and just the keyboard shortcuts in French...

### Which languages are affected?

French

**Comment by merriemcgaw** [comment]
@SimonZhao888 can you have someone investigate and share findings with us about where the problem is and we'll go from there.

**Comment by elachlan** [comment]
@merriemcgaw This is what I found. I think its related to KeysConverter. But I am unsure how `TypeDescriptor.GetConverter` manages the culture?

https://github.com/dotnet/winforms/blob/85c155eef5de2dc0163a60147fa9bbc045323ef8/src/System.Windows.Forms/src/System/Windows/Forms/ToolStrips/ToolStripMenuItem.cs#L1230-L1243

Related:
#9660, #8440, #8527

**Comment by elachlan** [comment]
wait, do we just change this from:
```csharp
return TypeDescriptor.GetConverter(typeof(Keys)).ConvertToString(shortcutKeys); 
```

To:
```csharp
return TypeDescriptor.GetConverter(typeof(Keys)).ConvertToString(context: null, CultureInfo.CurrentUICulture, shortcutKeys);
```

**Comment by SimonZhao888** [comment]
> @SimonZhao888 can you have someone investigate and share findings with us about where the problem is and we'll go from there.

All right, we'll look into this.

**Comment by pmiossec** [comment]
Thanks all for having spent time on it and fixed the issue.

**Comment by Eudora-Li01** [comment]
Verified this issue on the latest .NET 9.0.100-alpha.1.23620.7 from main branch, it was fixed. Menustrip's shortcut key language is CurrentUICulture's language. 

https://github.com/dotnet/winforms/assets/130345015/a563e83f-0e04-4eaa-92e9-94d9e0cd753d
