### ISSUE TITLE
MemoryLeak in AxHost

### ISSUE THREAD

**Issue by pedromcrocha** [dotnet/winforms#10405]
### .NET version

7.0
8.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

not tested

### Issue description

AxHost does not dispose correctly.
is retained in ContainingControl and in private readonly AxHost _host in OleInterfaces class

with 
 this.axCoPDFXCview1.Dispose() //axCoPDFXCview1 my class that derive from AxHost
![image](https://github.com/dotnet/winforms/assets/4311100/4237b5d8-cdc4-4cff-8ce4-dec0d14c32a4)

and if i do 
this.axCoPDFXCview1.ContainingControl = null;
this.axCoPDFXCview1.Dispose();
![image](https://github.com/dotnet/winforms/assets/4311100/88eb9704-2a31-4f84-a3ae-244a80e28b8d)

i cannot get rid of AxHost.OleInterfaces

### Steps to reproduce

-

**Comment by elachlan** [comment]
@pedromcrocha is there a chance you could create a small reproduction project?

**Comment by pedromcrocha** [comment]
https://github.com/pedromcrocha/MemoryLeak_AxHost

**Comment by elachlan** [comment]
@Olina-Zhang could your team please verify?

**Comment by Olina-Zhang** [comment]
Hi @pedromcrocha we tried to use the sample: https://github.com/pedromcrocha/MemoryLeak_AxHost you provided to reproduce it, but project is missing COM dependencies, didn't find them in our testing machine. Could you please give some guidance how to reproduce it? Thanks!

**Comment by JeremyKuhne** [comment]
@pedromcrocha I believe this is ok with .NET 9 now as we don't cache object wrapped interfaces.
