### ISSUE TITLE
HelpProvider unable to load DLL 'htmlhelp.dll' or one of its dependencies

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#10410]
### .NET version

9.0.100-alpha.1.23580.4

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in .NET 8.0/7.0/6.0. It's a regression issue in .NET 9.0.

### Issue description

The 'Unable to load DLL 'htmlhelp.dll' or one of its dependencies' exception occurs when invoke HelpProvider in runtime.

**The behavior for .NET 9.0:**
![9 0-result](https://github.com/dotnet/winforms/assets/45864985/6289dfa7-b5c6-4306-b780-b590b9c7ffcc)

https://github.com/dotnet/winforms/assets/45864985/e255e2df-7954-4934-adf7-fced235a394e

**The behavior for .NET 8.0 or .NET Framework:**

https://github.com/dotnet/winforms/assets/45864985/9e6df513-d035-4749-bfae-ed86cc30d900

### Steps to reproduce

1. Open the [HelpProvider-TestApp.zip](https://github.com/dotnet/winforms/files/13521770/HelpProvider-TestApp.zip) project.
2. Build and run project.
3. Click the **?** icon in the upper right corner in form.
4. Then click the textbox under **Address:**.

**Comment by Tanya-Solyanik** [comment]
Oops, there is no htmlHelp.dll indeed, only hhctrl.ocx... CSWin32 does not know that - 	
```
		[DllImport("htmlhelp.dll", ExactSpelling = true, EntryPoint = "HtmlHelpW")]
			static extern winmdroot.Foundation.HWND LocalExternFunction(winmdroot.Foundation.HWND hwndCaller, winmdroot.Foundation.PCWSTR pszFile, uint uCommand, nuint dwData);
```

**Comment by Tanya-Solyanik** [comment]
@LeafShi1, @SimonZhao888, @Epica3055, @ricardobossan  - could one of you please review test coverage for the help provider control and add any missing tests

**Comment by elachlan** [comment]
@Tanya-Solyanik is `htmlhelp.dll` not in windows anymore or has it always been `hhctrl.ocx`?

This might be a `win32metadata` issue. @mikebattista @AArnott

**Comment by Tanya-Solyanik** [comment]
>is htmlhelp.dll not in windows anymore or has it always been hhctrl.ocx

It had always been the OCX

**Comment by elachlan** [comment]
Thanks. It's a metadata issue. I will raise an issue and investigate a fix.

**Comment by elachlan** [comment]
We should probably wait for the release of `win32metadata` and then `cswin32`.

I have a tracking issue to update cswin32 for another issue: #10348

**Comment by John-Qiao** [comment]
Verified the issue on .NET 9.0.100-alpha.1.23614.10 with dlls build form main branch, it has been fixed that HelpProvider works well in runtime now.


https://github.com/dotnet/winforms/assets/45864985/754d8c21-217c-469e-80dd-8b03824875fe
