### ISSUE TITLE
ErrorProvider HasErrors returns incorrect value after clearing an error

### ISSUE THREAD

**Issue by a-teece** [dotnet/winforms#10424]
### .NET version

7.0

### Did it work in .NET Framework?

Not tested/verified

### Issue description

The implementation of #5912 does not take into account clearing an individual error. The documentation for ErrorProvider.SetError states for the value "The error description string, or null or Empty to remove the error."

So HasErrors returns an incorrect value if SetError has ever been used, even if there is now no error.

### Steps to reproduce

Basic application logic is
  SetError(control, "Some error");
  _HasErrors should be true at this point_
  SetError(control, null);
  _HasErrors should be **false** at this point_
  
Given that GetError also creates an entry in _items with a null error the following will also cause incorrect results:
  _ = GetError(control);
  _HasErrors should be **false** at this point_

**Comment by a-teece** [comment]
For anyone that finds this issue, a crude workaround is this extension method:
        public static bool ReallyHasErrors(this ErrorProvider provider)
        {
            // ErrorProvider.HasErrors doesn't actually work; see https://github.com/dotnet/winforms/issues/10424
            // If HasErrors = false then there definately are 0 errors.
            // If HasErrors = true then there MAY be errors.
            if (!provider.HasErrors) { return false; }

            // There is no public property to get the list of Errors
            var privateItems = (System.Collections.IDictionary)(typeof(ErrorProvider).GetField("_items", BindingFlags.NonPublic | BindingFlags.Instance)!.GetValue(provider)!);
            // privateItems is Dictionary<Control, ControlItem> but ControlItem is an internal class.
            var controls = privateItems.Keys;

            foreach (Control item in controls)
            {
                if(!string.IsNullOrEmpty(provider.GetError(item))) { return true; }
            }

            return false;
        }

**Comment by eriawan** [comment]
> @eriawan I see you implemented the HasErrors property. Thoughts?
> 
> Arguably if the error has been cleared, why is it still in the _items collection. If feels like a bug in SetError not matching the documentation. However that may be a larger change so it may make more sense if HasErrors took into account the strange behaviour.

@a-teece 

Hi, yes I implemented that. Of course I would love to fix it and add more unit tests 🙂 
Do you have a small sample of code to repro? Or could you explain your case using one or two lines of code?

**Comment by elachlan** [comment]
I've put through a PR at #10440

**Comment by eriawan** [comment]
@elachlan 
> @eriawan it would be great if you could give it a review?

Sure! I'm going to review it in one hour.

**Comment by eriawan** [comment]
@elachlan 

Done reviewing your PR. Thanks for the fix! 👍

**Comment by Zheng-Li01** [comment]
Verified the issue on .NET 9.0.100-alpha.1.23614.10 with dlls build form main branch, the issue has been fixed that ErrorProvider HasErrors returns correct value after clearing an error. see below screenshot.
![image](https://github.com/dotnet/winforms/assets/38325459/173f0fd9-2242-4ba3-97e2-c7c4437065e5)
