### ISSUE TITLE
Exception in PropertyGrid when it run in RemoteDesignerHost

### ISSUE THREAD

**Issue by NikiforovSerg** [dotnet/winforms#10427]
### Environment

Microsoft Visual Studio Professional 2022 (64-bit) 17.8.2

### .NET version

.net 6+

### Issue description

Hello. I’m from DevExpress.
We have a problem with PropertyGrid when it run in RemoteDesignerHost:
<img width="645" alt="Screen2" src="https://github.com/dotnet/winforms/assets/115987452/6274c52e-297d-449a-99cd-76f29f098bd0">

Our research led to the PropertyDescriptorGridEntry class. In the NotifyParentChange method we found a difference in the code for .net 6 and .net framework versions.
<img width="678" alt="Screen3" src="https://github.com/dotnet/winforms/assets/115987452/39842717-e16c-483d-aa04-be666b6d11c9">

In .net framework this code look like this
<img width="879" alt="Screen4" src="https://github.com/dotnet/winforms/assets/115987452/a61bed32-aa61-4b52-87ac-cd5acc951c56">

I attach an example. In this example in .net version I wrote comment in ComponentChangeService class where an exception occurs in  RemoteDesignerHost class

### Steps to reproduce

1. Download and unzip [Pivot_Error.zip](https://github.com/dotnet/winforms/files/13556605/Pivot_Error.zip)
2. Build and run WinFomNetExample project

**Comment by elachlan** [comment]
@Olina-Zhang could your team please test?

**Comment by Olina-Zhang** [comment]
Tested it using provided application, repro in .Net 6.0 to .Net 9.0, works in .Net framework 4.8.1

.Net 9.0:
![image](https://github.com/dotnet/winforms/assets/26474449/24208846-dd01-45fe-9f67-b0933a36c0b1)

.Net framework 4.8.1:
![image](https://github.com/dotnet/winforms/assets/26474449/efcab79c-569d-498e-9c77-6151defb8649)

**Comment by Tanya-Solyanik** [comment]
This has regressed in NET6 - https://github.com/dotnet/winforms/pull/5251

**Comment by Tanya-Solyanik** [comment]
>We have a problem with PropertyGrid when it run in RemoteDesignerHost:

@NikiforovSerg  - could you please clarify what RemoteDesignerHost is?

**Comment by merriemcgaw** [comment]
I believe that DevExpress created a separate app for report designing, using just the runtime bits. Thanks @elachlan for picking this up so fast.

**Comment by John-Qiao** [comment]
Verified the issue on .NET 9.0.100-alpha.1.23614.10 with dlls build form main branch, it can still be reproduced as below:

![10427-testresult](https://github.com/dotnet/winforms/assets/45864985/4a43f0b6-316f-41e9-ad06-ddc16c8ed7c6)

**Comment by Tanya-Solyanik** [comment]
@John-Qiao  - could you please retest? Works fine for me...

**Comment by John-Qiao** [comment]
@Tanya-Solyanik in my opinion, the main branch of Winforms repo is the latest .NET 9.0 SDK version, so I migrate the above test app codes to the WinformsControlsTest app(download from main branch of Winforms repo), then run the WinformsControlsTest to testing this issue, but the issue can still be reproduced. Do you know which kye points I missed in my steps? Or how did you test this issue?

https://github.com/dotnet/winforms/assets/45864985/01ef6239-483f-4338-ab89-a3a6f66573f7

**Comment by Tanya-Solyanik** [comment]
I see, I'm testing the main branch of this repo only. The issue here is that the main was not flowing into the SDK for a few days.

**Comment by John-Qiao** [comment]
@Tanya-Solyanik Verified this issue on the latest .NET 9.0.100-alpha.1.23618.4 from main branch, but this issue can still be reproduced as same as above test result.

**Comment by elachlan** [comment]
The error is when you enter a value and it doesn't update in its parent.

**Comment by Tanya-Solyanik** [comment]
@John-Qiao when the property grid is up, expand the item to show `ComboName` and then type something intho the `comboName` value textbox. Before the fix you should see an error box, after the fix text that you types should be displayed in both lines - 
ComboName=test
and
Path={ComboName=`test`}

**Comment by John-Qiao** [comment]
@Tanya-Solyanik Followed your steps to re-verify the issue on the latest .NET 9.0.100-alpha.1.23618.4 from main branch, it was fixed that types be displayed in both lines and no exception occurs.


https://github.com/dotnet/winforms/assets/45864985/4a90c599-f1b7-44af-8d1b-ce9a49477e7e

**Comment by Tanya-Solyanik** [comment]
Thank you, @John-Qiao !

**Comment by Eudora-Li01** [comment]
Verified issue on Scratch Project(using provided application codes in repro steps) from Release/8.0 branch of Winforms repo, the issue was fixed. 

https://github.com/dotnet/winforms/assets/130345015/b3f49ff3-0bd2-4584-a3ec-84e4cfc01c98

**Comment by Nora-Zhou01** [comment]
Verified with .NET SDK 8.0.2 test pass build, this issue was fixed. Test result is same as above.

**Comment by Olina-Zhang** [comment]
Verified this issue with .NET 9 Preview 1 test pass build, it was fixed. Test result is same as above.
