### ISSUE TITLE
[Accessibility] Narrator can't announce the new added row correctly for DataGrridView control

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#10428]
### .NET version

9.0.0-alpha.1.23576.1

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, Narrator can announce the new added row correctly for DataGrridView control in 8.0/7.0
For the 9.0, have the new change was introduced by PR: #10243 which caused this issue.

### Issue description

Narrator can't announce the new added row correctly for DataGrridView control in 9.0

### Steps to reproduce

**Reproduce steps:**
1. Create .NET Core winforms project targeting 9.0.
2. Add DataGridView control to the Form1.cs[Design] with some columns.
3. Build and run the project.
4. Launch the Narrator tool, and focus on first row.
5. Input some text on the textbox cell.
6. Press the Down keyboard to move the new added row.
7. Observe the results.

**Actual Results:**
After steps #5, the Narrator announce "Row 2 is added"
After steps #6, the Narrator announce  "Row 3, Column1 Row 3, Not sorted......."
![ActualBehaviour](https://github.com/dotnet/winforms/assets/38325459/44fabe28-386e-4809-9460-2604417cee52)
![image](https://github.com/dotnet/winforms/assets/38325459/1878fcf6-743f-40e1-a949-a84ec349a42a)

**Expected Results:**
After steps #5, the Narrator announce the new added row correctly
![80Behaviour](https://github.com/dotnet/winforms/assets/38325459/6210ea42-57b4-4855-8e38-ec790bd48699)
![image](https://github.com/dotnet/winforms/assets/38325459/efeee649-8c9b-4513-b84b-639e1bfbdbc7)

**More info:**
After steps #6. continue input some text on the new added new row, the Narrator always announce that" **Row 1, Editing Control, edit, <say-as interpret-as="spell">t</say-as>, Row Header Row 1, Row** <say-as interpret-as="cardinal">1</say-as> of <say-as interpret-as="cardinal">4</say-as> "
![image](https://github.com/dotnet/winforms/assets/38325459/eefd21a1-7ed6-40ce-8347-792e80fc750f)

**Comment by Tanya-Solyanik** [comment]
@Zheng-Li01 @ricardobossan the "second" part of this issue can be treated as a separate fix.I will require a code change in a different spot. P{lease open a new issue

**Comment by Zheng-Li01** [comment]
@Tanya-Solyanik  @ricardobossan, filed the https://github.com/dotnet/winforms/issues/10494 issue to track the "second" part of this issue.

**Comment by John-Qiao** [comment]
@ricardobossan Verified this issue on the latest .NET 9.0.100-alpha.1.23620.7 from main branch, after steps 5, it still announces "Row 2 is added", is that the expected result?


https://github.com/dotnet/winforms/assets/45864985/12401b8e-11af-4df5-8f14-f1095cd9ff45
