### ISSUE TITLE
The smart tag icon in the DemoConsole application becomes very large

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#10444]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue.

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, Smart tag icons getting very large.

![image](https://github.com/dotnet/winforms/assets/86937911/dfdb07ad-a73b-4117-8948-cd7f2dabc929)

https://github.com/dotnet/winforms/assets/86937911/59da3f2e-a1df-4d4b-bb9d-39cb5ac38c6d

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by merriemcgaw** [comment]
@Philip-Wang01 what was the DPI Awareness of the sample designer app?

**Comment by Philip-Wang01** [comment]
@merriemcgaw It's not an HDPI error, it can be reproduced on 100% of the screen. The DemoConsole application was tested from .NET 8.0 and this issue did not repro on .NET 8.0, it is a recent regression in .NET 9.0.

**Comment by MandiMan** [comment]
Verified this issue on winforms repo from main branch, it was fixed, now the size of the Smart tag icon is normal.

https://github.com/dotnet/winforms/assets/108860782/00691876-b73b-4153-9784-a5dd9b52148f
