### ISSUE TITLE
The WinformsControlTest application under the Winforms repository has the wrong button anchor property setting in the drag and drop form.

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#10449]
### .NET version

.NET 9.0.100-alpha.1.23606.1

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, reproduce in previous .Net versions

### Issue description

In the E2E test, the button in the lower right corner of the drag and drop form in the WinformsControlTest application under the Winforms repository disappears when the form is resized.

https://github.com/dotnet/winforms/assets/104609169/70f02b24-1bf8-4131-b487-abcdb7b2f479

### Steps to reproduce

1. Git clone  https://github.com/dotnet/winforms
2. Open CMD from clone folder and run "start-vs.cmd" command open project
3. Select WinformsControlTest app, right click it to set as startup project
4. Build and run, click "drag and drop" button and resize form.

**Comment by merriemcgaw** [comment]
@Nora-Zhou01 feel free to make the change to the test application and confirm nothing strange happens. Good catch!

**Comment by willibrandon** [comment]
I also suspect that someone more creative than I could come up with a better demo, but the cats will be hard to beat.

**Comment by MelonWang1** [comment]
Verified this issue on winforms repo from main branch, when decreasing or increasing the size of the current window, as long as buttons are in the current tablelayout cell, they are visible and their size are fixed.

https://github.com/dotnet/winforms/assets/94418985/06a0e9a7-041e-4e00-9720-2769a9832664
