### ISSUE TITLE
Designer Crash in Net 7.0

### ISSUE THREAD

**Issue by RaghavendraSudhakar** [dotnet/winforms#10482]
### Environment

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.6.3

### .NET version

Net 7.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

No

### Issue description

The design page of Net 7.0 is not refreshed and shows `System.IO.MemoryStream` exception.

### Steps to reproduce

1. Run the sample.
2. Open the design page.

![Designer issue](https://github.com/dotnet/winforms/assets/153831960/27e295ee-2db0-40e9-9b7a-30423fdbdc66)

[NetCore-Designer-Issue.zip](https://github.com/dotnet/winforms/files/13673705/NetCore-Designer-Issue.zip)

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you check this out?

**Comment by elachlan** [comment]
> Version 17.6.3

@RaghavendraSudhakar this isn't the latest version of visual studio 2022. Can you please update visual studio and let us know if the issue persists?

**Comment by Olina-Zhang** [comment]
I tested the provided app in the latest VS, form designer is not opened with keeping loading designer. It just has a form.cs file, no its designer.cs and program.cs file in that sample project. All supported code in one file. Here is the output log from Windows Forms:

                        _Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: Type  could not be read from the data in line 404, position 5.  The type's internal structure may have changed.  Either implement ISerializable on the type or provide a type converter that can provide a more reliable conversion format, such as text or an array of bytes.  The conversion exception was: Type 'System.IO.MemoryStream' in Assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable. ---> Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: Type  could not be read from the data in line 404, position 5.  The type's internal structure may have changed.  Either implement ISerializable on the type or provide a type converter that can provide a more reliable conversion format, such as text or an array of bytes.  The conversion exception was: Type 'System.IO.MemoryStream' in Assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable. Line 404, position 5. ---> Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: Type 'System.IO.MemoryStream' in Assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable._
                        
 And I tried to copy the code from form designer.cs and program.cs file to one file: form.cs, then delete form designer.cs and program.cs file, form designer can be displayed well with no issue.
[WinFormsApp43.zip](https://github.com/dotnet/winforms/files/13681511/WinFormsApp43.zip)

 @RaghavendraSudhakar Can you try the application I provided above to see if form designer can be loaded? And if you create a new project in Visual Studio, the designer should have loaded it successfully, right?

**Comment by Raghav-Sudhakar** [comment]
@elachlan Have checked with the latest version but the issue persists.

@Olina-Zhang The application that you have provided is working fine. But our query is when we create a sample and it produces some exception even after removing all the code of control from the cs file, the design page is not refreshed and shows the same error. 

For the loading of the designer page switch to another application and navigate back to the designer page, the design page will be loaded

**Comment by Tanya-Solyanik** [comment]
Designer can't load the resx file, specifically  it can't deserialize this memory stream:
```
<data name="dockingManager1.DockLayoutStream" mimetype="application/x-microsoft.net.object.binary.base64">
  <value>
      AAEAAAD/////AQAAAAAAAAAEAQAAABZTeXN0ZW0uSU8uTWVtb3J5U3RyZWFtCgAAAAdfYnVmZmVyB19v
```
because MemoryStream type is no longer serializable in .NET - https://learn.microsoft.com/dotnet/api/system.io.memorystream?view=net-7.0

@Raghav-Sudhakar  - if you own DockingManager class, you can change it to store the layout in a text format by implementing a custom TypeConverter

**Comment by merriemcgaw** [comment]
Please let us know if @Tanya-Solyanik's suggestion helps your scenario.

**Comment by Raghav-Sudhakar** [comment]
@merriemcgaw We have not used DockingManager or any controls in our sample but still, the designer crash occurs.

**Comment by Tanya-Solyanik** [comment]
@Raghav-Sudhakar  - you are referencing DockingManager on line 24 in the resx file.

**Comment by antdef** [comment]
@Tanya-Solyanik :  Thanks for pointing to the issue.  I had the same, I simply removed the binary blob from the .resx and now can edit again.
