### ISSUE TITLE
build.sh fails

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/winforms#10491]
The repository offers a build.sh fails which indicates that you can build at least some of the product on Unix, but it actually fails:

```
 /usr/bin/sh: 2: /tmp/MSBuildTempcodespace/tmp18e73eea1740495bb87e848e5b3ee6a6.exec.cmd: vswhere.exe: not found
/workspaces/winforms/src/BuildAssist/BuildAssist.msbuildproj(38,5): error MSB3073: The command "..." exited with code 127.
```

**Comment by RussKie** [comment]
Windows Forms is Windows-only SDK, so bash scripts aren't expected to work. These scripts were added in #940, whic pre-dates my tenure in this repo. The bash scripts that aren't part of the Arcade SDK should be removed.

**Comment by merriemcgaw** [comment]
@RussKie thanks! @ViktorHofer can you help me understand the priority of this? Given that we're Windows-only is there an impact to having this file?

**Comment by ViktorHofer** [comment]
I personally find it important to be able to build this Windows only product also on Linux as it allows open source contributors that are on different OSs to contribute. Enabling and protection that also makes sure that we aren't too strongly tied to VS / desktop MSBuild or any other Windows only technology.

That's just my personal opinion though. From a technical side, the current build.sh script is broken so you can either try to fix that or remove it.

**Comment by merriemcgaw** [comment]
@lonitra @JeremyKuhne do you think that just removing this for now is our best bet?

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team do the honors?

**Comment by LeafShi1** [comment]
> @LeafShi1 can your team do the honors?

Do we need to repair or delete this file directly?

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - please delete this file, we'll have to re-add it when needed.
