### ISSUE TITLE
Enable IDE0008 and IDE0090 in System.Windows.Forms.Tests.csproj

### ISSUE THREAD

**Issue by lonitra** [dotnet/winforms#10500]
Currently IDE0008 and IDE0090 are disabled in System.Windows.Forms.Tests.csproj:
https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj#L13

This should be enabled to help enforce style guidelines in the project. Existing build errors will need to be fixed upon enabling.

**Comment by elachlan** [comment]
@lonitra is `IDE0008` required? We have it set to `Suggestion` in the globalconfig for non-test projects.
