### ISSUE TITLE
The expand/collapse arrow icon is double-scaled in the ThreadExceptionDialog 

### ISSUE THREAD

**Issue by Eudora-Li01** [dotnet/winforms#10512]
### .NET version

9.0.100-alpha.1.23620.7

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works well on .NET 8.0.

### Issue description

The down arrow icon align with Details is not tangible in Thread exception dialog 

## Repro steps:
1. Git clone  https://github.com/dotnet/winforms
2. Open CMD from clone folder and run "start-vs.cmd" command open project
3. Select WinformsControlTest app, right click it to set as startup project
4. Build and run, click  "Dialog" button -> "Thread exception dialog" button

## Actual result:  
The down arrow icon align with Details is not tangible.

![image](https://github.com/dotnet/winforms/assets/130345015/faaf5b7b-d887-4ca4-ac87-a160a1d95451)

## Expect result: 
The down arrow icon align with Details is tangible.
![image](https://github.com/dotnet/winforms/assets/130345015/4f544a1e-5210-4fb9-a7b5-8c6201a27b0c)

## More Info:
1. This issue exists in DPI 100%.

**Comment by Tanya-Solyanik** [comment]
@Eudora-Li01 @merriemcgaw @lonitra  - this looks like an improvement to me, the arrow was too small before.
@Eudora-Li01 - what scaling percentage is your image taken at? I want to compare images at 200% and at 100%

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik it's an improvement in that we can see it easier because it's larger, but it also looks like it's scaled and fuzzy, which is less than ideal. I can live with it either way, but I agree that I'd like to see comparison shots.

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - this could be another case of https://github.com/dotnet/winforms/pull/10459, but we are not sure if we want to fix it yet.

**Comment by Eudora-Li01** [comment]
Verified on latest .NET 9.0.100-alpha.1.23620.14, [issue 10444](https://github.com/dotnet/winforms/issues/10444)  has been fixed by [#10459](https://github.com/dotnet/winforms/pull/10459), and this issue still reproduce. 

https://github.com/dotnet/winforms/assets/130345015/6f5f8eb7-295c-45ba-b4af-cc5f53a44610

Here is result on 100% and 200%:
100%:
![DownArrowIn100%](https://github.com/dotnet/winforms/assets/130345015/88f436c8-a5ea-4600-bc27-e04c3a5a65e4)
200%:
![DownArrowIn200%](https://github.com/dotnet/winforms/assets/130345015/52602997-fd32-4f1f-b8fe-75269f4fe19e)

**Comment by LeafShi1** [comment]
> @LeafShi1 - this could be another case of #10459, but we are not sure if we want to fix it yet.

I will investigate issue.

**Comment by Tanya-Solyanik** [comment]
@Eudora-Li01  - thank you for getting these images!

@LeafShi1 - yes, please investigate, the 200% image shows that icon overlaps with the text, we should fix it.

**Comment by Eudora-Li01** [comment]
Verified this on .NET 9.0.100-alpha.1.24062.11, issue was fixed, expand/collapse arrow iscon scale well in DPI 100% and 200%:
DPI is 100%:
![image](https://github.com/dotnet/winforms/assets/130345015/c82c44f5-ec8c-45a6-8602-eb62d8100978)
![image](https://github.com/dotnet/winforms/assets/130345015/3694901f-8433-4f35-99bf-2f9645833d92)

DPI is 200%:
![image](https://github.com/dotnet/winforms/assets/130345015/35f1921c-553f-4fe1-8ba5-a3b031d4ed93)
![image](https://github.com/dotnet/winforms/assets/130345015/8d7f9b77-3401-445c-9c0e-dc2bd6854c7f)

**Comment by Zheng-Li01** [comment]
Verified this in the release/9.0-preview1 branch of winforms repo, which has been fixed that have the same results as above.
