### ISSUE TITLE
VS stop running while opening message box with Options's value to DefaultDesktopOnly/ServiceNotification

### ISSUE THREAD

**Issue by Eudora-Li01** [dotnet/winforms#10513]
### .NET version

9.0.100-alpha.1.23620.7

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, It also repro on .NET 8.0.

### Issue description

VS stop running while opening message box with Options's value to DefaultDesktopOnly/ServiceNotification

## Repro steps:
1. Git clone  https://github.com/dotnet/winforms
2. Open CMD from clone folder and run "start-vs.cmd" command open project
3. Select WinformsControlTest app, right click it to set as startup project
4. Build and run, click "MessageBox button
5. Set Options's value to DefaultDesktopOnly/ServiceNotification, Click Show MessageBox

https://github.com/dotnet/winforms/assets/130345015/51b017d2-8540-4e53-90ad-bb4050f695a5

## Actual result: 
VS stop running

## Expected  result: 
Message box will be opened without error

**Comment by Tanya-Solyanik** [comment]
@elachlan issue details say that this repros in NET8 why did you mark it as a regression?

**Comment by elachlan** [comment]
Sorry, I read that as starting in dot net 8.

**Comment by RussKie** [comment]
@Eudora-Li01 there's a bug that crashes the app, and since you're running a release build VS doesn't break on the failure.
![image](https://github.com/dotnet/winforms/assets/4403806/8b0b9281-c100-4326-a0a2-47d3570fe210)

Run a debug build and set to break on AE.

**Comment by elachlan** [comment]
Its on purpose and crashes to desktop because we don't have a try catch in the `_btnOpen.Click` event handler. `MessageBoxOptions.ServiceNotification` and `MessageBoxOptions.DefaultDesktopOnly` cannot be used when there is an owner or you are passing help information.

https://github.com/dotnet/winforms/blob/ffef3077af6bb10910587f9aa4f4b6c78b8cc254/src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/MessageBox.cs#L54-L67

**Comment by Tanya-Solyanik** [comment]
@elachlan - would you be interested to fix the  test app to not crash for the expected exception?

**Comment by elachlan** [comment]
Sure, But I think we should probably call a different overload for the `(MessageBoxOptions.ServiceNotification | MessageBoxOptions.DefaultDesktopOnly)` options.

**Comment by elachlan** [comment]
@Tanya-Solyanik also, help button is throwing an exception. But I am unsure if that is correct or not.

**Comment by Amy-Li03** [comment]
Verified this on .NET 9.0.100-alpha.1.24062.11, issue was fixed, message box opened without error while opening message box with Options's value to DefaultDesktopOnly/ServiceNotification.
![Fixed](https://github.com/dotnet/winforms/assets/62929087/e1a9e044-5b21-4455-8264-20a6e60a2fa1)

**Comment by elachlan** [comment]
@Amy-Li03 Yes. Help button cannot show with either `DefaultDesktopOnly` or `ServiceNotification`. As an exception will be thrown.
