### ISSUE TITLE
Controls anchored Left+Right and/or Top+Bottom scale incorrectly when window is moved from high to low DPI screen in .NET 8

### ISSUE THREAD

**Issue by PredatH0r** [dotnet/winforms#10531]
### .NET version

.NET 8.0.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

yes, works fine with 7.0.0

### Issue description

See attached sample application. 
In the .csproj file you can select the desired runtime. "net48" and "net7.0-windows" work fine, "net8.0-windows" doesn't.

Initial layout:
![grafik](https://github.com/dotnet/winforms/assets/6238104/fdc35664-1edd-4e9a-874a-aeb7a325a2aa)

Layout after moving from low to high and then high to low DPI screen:
![grafik](https://github.com/dotnet/winforms/assets/6238104/f946afaa-37d3-4241-92d0-8a0f7cec50b5)

Note: Setting "System.Windows.Forms.AnchorLayoutV2" in runtimeconfig.json to false or true doesn't make any difference.
(see https://github.com/dotnet/winforms/blob/main/docs/design/anchor-layout-changes-in-net80.md)

### Steps to reproduce

Start the application built for target framework "net8.0-windows" on a screen with 96dpi.
Move the window to the screen with higher DPI. So far so good.
Move the window back to the screen with 96 DPI and the Label control with yellow background has the wrong size.

[WinFormsScalingWithAnchor.zip](https://github.com/dotnet/winforms/files/13766551/WinFormsScalingWithAnchor.zip)

**Comment by Philip-Wang01** [comment]
@PredatH0r You can try to set `"System.Windows.Forms.AnchorLayoutV2": true` in the runtimeconfig.json. This may solve your problem for now.

https://github.com/dotnet/winforms/assets/86937911/bf77eee0-88c5-4161-9a3f-3956404eac25

**Comment by PredatH0r** [comment]
Thank you very much!

My previous attempt to use this setting failed because as it turned out, the contents of my runtimeconfig.template.json didn't get copied into WinFormsScalingWithAnchor.runtimeconfig.json.
After manually editing the file I can confirm that the setting works as documented.

**Comment by merriemcgaw** [comment]
Since you've got this working for your project, I'm going to close this issue. Thanks for confirming everything worked!
