### ISSUE TITLE
Cursor class does unnecessary finalization in some cases

### ISSUE THREAD

**Issue by jgilbert2017** [dotnet/winforms#10539]
### .NET version

8

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

unknown

### Issue description

Constructors for `Cursor` for the common case of system cursors should call `GC.SuppressFinalize(this)` so that the objects don't get unnecessarily queued for finalization.  This is currently what happens when a call is made to `Cursor.Current`.

pull request at
https://github.com/dotnet/winforms/pull/10538

### Steps to reproduce

n/a

**Comment by elachlan** [comment]
@Tanya-Solyanik here is the issue for the pr.

**Comment by Tanya-Solyanik** [comment]
@jgilbert2017 - how does this issue manifest in your app?

**Comment by jgilbert2017** [comment]
@Tanya-Solyanik i found it as part of a general sweep for memory related issues.  theoretically it puts a small bit of pressure on the GC.

**Comment by Tanya-Solyanik** [comment]
@jgilbert2017  - then we'll fix it in NET9 only, sounds good?

**Comment by jgilbert2017** [comment]
@Tanya-Solyanik hey, i'm just happy to get it merged at all... november is just a short 11 months away :-).

**Comment by Tanya-Solyanik** [comment]
@jgilbert2017  - perfect! But keep investigating your memory issues, this one seems to be a minor one.
