### ISSUE TITLE
[Accessibility]Inspect or AccessibilityInsights tool's rectangle can't focus on the entire FlowLayoutPanel/Panel/SplitContainer/TableLayoutPanel/TabControl/TextBox with scrollBar

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#10540]
### .NET version

9.0.0-alpha.1.23621.3

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

1. Controls repro on .NET 9.0/8.0/7.0, not repro on 6.0 and previous version: FlowLayoutPanel, Panel, SplitContainer, TableLayoutPanel
2. Controls repro on .NET 9.0/8.0/7.0/6.0, not repro on 5.0 and previous version: TabControl
3. Controls repro on .NET 9.0/8.0, not repro on .NET 7.0 and previous version: TextBox

### Issue description

[Accessibility]Inspect or AccessibilityInsights tool's rectangle can't focus on the entire FlowLayoutPanel/Panel/SplitContainer/TableLayoutPanel/TabControl/TextBox with scrollBar

### Steps to reproduce

1. Open and run the attached reproduce application
[ScrollBarTest.zip](https://github.com/dotnet/winforms/files/13782718/ScrollBarTest.zip)
2. Launch Inspect or Accessibility Insight tool
3. Focus on the entire cotnrol

**Actual result:**
1. Controls repro on .NET 9.0/8.0/7.0, not repro on 6.0 and previous version: FlowLayoutPanel, Panel, SplitContainer, TableLayoutPanel
![image](https://github.com/dotnet/winforms/assets/38325459/5a6b8c79-ce62-418c-a953-718e156e5e4d)
2. Controls repro on .NET 9.0/8.0/7.0/6.0, not repro on 5.0 and previous version: TabControl
![image](https://github.com/dotnet/winforms/assets/38325459/80b9973c-21a2-4ab5-bdd4-aafe5adf448b)
3. Controls repro on .NET 9.0/8.0, not repro on .NET 7.0 and previous version: TextBox
![image](https://github.com/dotnet/winforms/assets/38325459/2f10ef12-224a-4613-bd46-3345bd379d95)

**Expected result:**
1. Controls repro on .NET 9.0/8.0/7.0, not repro on 6.0 and previous version: FlowLayoutPanel, Panel, SplitContainer, TableLayoutPanel
![image](https://github.com/dotnet/winforms/assets/38325459/3db13ec7-ee3c-44bf-9f4d-0e71d896116b)
2. Controls repro on .NET 9.0/8.0/7.0/6.0, not repro on 5.0 and previous version: TabControl
![image](https://github.com/dotnet/winforms/assets/38325459/2d0c015a-60ec-4ae7-a0bc-86160f85f191)
3. Controls repro on .NET 9.0/8.0, not repro on .NET 7.0 and previous version: TextBox
![image](https://github.com/dotnet/winforms/assets/38325459/24c15fa2-d2f9-45d1-ac18-442b5380c3d4)

**Comment by Tanya-Solyanik** [comment]
@Epica3055  - could you please edit these controls in WinformsControlsTest to have scrollbars, if needed.

**Comment by MelonWang1** [comment]
Verified the issue on lastest .NET 9.0 SDK 9.0.100-alpha.1.24062.11, it was fixed.  Inspect or AccessibilityInsights tool's rectangle can focus on the entire FlowLayoutPanel/Panel/SplitContainer/TableLayoutPanel/TabControl/TextBox with scrollBar.
![Untitled](https://github.com/dotnet/winforms/assets/94418985/0e2cf6c0-ddf4-4d19-abe4-d2ef00a5b0b6)

**Comment by Zheng-Li01** [comment]
Verified this issue with .NET 9 Preview 1 test pass build, it was fixed. Test result is same as above.

**Comment by MelonWang1** [comment]
Verified issue on .NET 8.0.300 with dlls built from Release/8.0 branch of Winforms repo, the issue was fixed, test result is same as above.

**Comment by MelonWang1** [comment]
Verified with .NET SDK 8.0.3 test pass build, this issue was fixed. Test result is same as above.
