### ISSUE TITLE
No text for new tabpage item that added by TabPages property in the properties window in the DemoConsole application

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#10545]
### .NET version

9.0.0-alpha.1.23621.3

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

The issue also can reproduce .NET 8.0, which start support the TabControl.

### Issue description

No text for new tabpage item added by TabPages property in the properties window in the DemoConsole application

### Steps to reproduce

1. Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo
2. Add new tabpage item by TabPages property in the properties window 

**Actually Results:**
No text for new tabpage item added by TabPages property in the properties window
![image](https://github.com/dotnet/winforms/assets/38325459/fff07432-f8f3-4b82-a2a4-6ea5f77b8a77)
![TabControl](https://github.com/dotnet/winforms/assets/38325459/e1788125-2832-45b1-8148-1640a410b094)

**Expected Results:**
Have text for new tabpage item added by TabPages property in the properties window

**More info:**
The issue can't reproduce when added new tabpage item by using Command/SmartTag

**Comment by elachlan** [comment]
Name is set via `TabControlDesigner.OnAdd` for the "Add Tab" and "Remove Tab" buttons on the property grid. But its set via `TabPageCollectionEditor.CreateInstance` when using the collection editor.

An example of a collectioneditor which sets the name based on the number of items is `ListViewGroupCollectionEditor`.

You would adjust the code to something along the lines of:
```csharp
internal class TabPageCollectionEditor : CollectionEditor
{
    private TabPageCollection _collection;

    public TabPageCollectionEditor() : base(typeof(TabControl.TabPageCollection))
    {
    }

    /// <summary>
    ///  Sets the specified collection to have the specified array of items.
    /// </summary>
    protected override object SetItems(object editValue, object[] value)
    {
        var tabControl = Context.Instance as TabControl;
        tabControl?.SuspendLayout();

        object retValue = base.SetItems(editValue, value);

        tabControl?.ResumeLayout();
        return retValue;
    }

    protected override object CreateInstance(Type itemType)
    {
        object instance = base.CreateInstance(itemType);
        ReadOnlySpan<char> tabPageName = nameof(TabPage);
        int i = 1;
        string result = $"{tabPageName}{i}";

        while (_collection[result] is not null)
        {
            i++;
            result = $"{tabPageName}{i}";
        }

        TabPage tabPage = instance as TabPage;
        tabPage.Name = result;
        tabPage.Text = result;
        tabPage.UseVisualStyleBackColor = true;

        return tabPage;
    }

    public override object EditValue(ITypeDescriptorContext context, IServiceProvider provider, object value)
    {
        _collection = (TabPageCollection)value;
        object result;

        // This will block while the TabPageCollectionEditor is running.
        result = base.EditValue(context, provider, value);

        // The user is done with the TabPageCollectionEditor, don't need the edit value any longer.
        _collection = null;

        return result;
    }
}
```

I did this but the behavior was a bit weird when removing items that already existed in the collection. Compared to items you added via the collection editor, which work as expected.

**Comment by elachlan** [comment]
@Tanya-Solyanik I really don't like the solution I am suggesting above because the creating of the name is done in two places. Ideally it would be centralized so that we don't repeat code in `TabPageCollectionEditor` and the `TabControlDesigner`. Are we supposed to use something like `ListViewGroupCollectionEditor.CreateListViewGroupName` and utilize `INameCreationService`?
https://github.com/dotnet/winforms/blob/50972fd053a8f7b569fac7d214ac25c0251c35ec/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListViewGroupCollectionEditor.cs#L39-L43

I think we actually have an example in `DesignSurfaceExt`:
https://github.com/dotnet/winforms/blob/50972fd053a8f7b569fac7d214ac25c0251c35ec/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs#L10-L89

**Comment by Syareel-Sukeri** [comment]
Verified this issue from main branch of winforms repo, the issue has been fixed where there are texts for new tabpage item added by TabPages property in the properties window in the DemoConsole application.

[Video 2-22 at 14.09.webm](https://github.com/dotnet/winforms/assets/156630333/060d2ef1-a3a9-4e3a-a191-c6569734516e)

**Comment by Eudora-Li01** [comment]
Verified this issue with .NET 9 Preview 2 test pass build, it was fixed. Test result is same as above.
