### ISSUE TITLE
The "Input Mask" dialog for MaskedTextBox have wrong Control in the DemoConsole application

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#10546]
### .NET version

9.0.0-alpha.1.23621.3

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, the MaskedTextBox start support from 9.0

### Issue description

The "Input Mask" dialog for MaskedTextBox have incorrect ControlType - LIst instead of Table

### Steps to reproduce

1. Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo
2. Open the inspect tool to observe the ControlType of the "Input Mask" dialog for MaskedTextBox 

**Actually Results:**
The "Input Mask" dialog for MaskedTextBox have incorrect ControlType
![image](https://github.com/dotnet/winforms/assets/38325459/71e382aa-51f2-45a3-a9b7-9e82e6fbf74e)

**Expected Results:**
The "Input Mask" dialog for MaskedTextBox have correct ControlType
![image](https://github.com/dotnet/winforms/assets/38325459/ba735897-4f64-4257-9858-665bca9bb482)

**Comment by elachlan** [comment]
The `MaskDesignerDialog` uses a `ListView` for its `_listViewCannedMasks` control.

`ListViewAccessibleObject` specifies its `UIA_ControlTypePropertyId` as `UIA_CONTROLTYPE_ID.UIA_ListControlTypeId`
https://github.com/dotnet/winforms/blob/f6bfe1bdef13d4539ad6116cfdabed46f50ba627/src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.ListViewAccessibleObject.cs#L239-L252

I imagine this would have to be changed to `UIA_CONTROLTYPE_ID.UIA_TableControlTypeId`?

**Comment by elachlan** [comment]
Sorry, I was wrong. 
I think we just add the following to the `MaskDesignerDialog`.
`_listViewCannedMasks.AccessibleRole = AccessibleRole.Table;`

**Comment by John-Qiao** [comment]
Verified this on .NET 9.0.100-alpha.1.24062.11, issue was fixed, the "Input Mask" dialog for MaskedTextBox has correct ControlType now.

![10546-testresult](https://github.com/dotnet/winforms/assets/45864985/a97369aa-c881-44a5-8b1e-a99cc3f6ac97)

**Comment by Zheng-Li01** [comment]
Verified this in the release/9.0-preview1 branch of winforms repo, which has been fixed that have the same results as above.
