### ISSUE TITLE
 The selected icon for Icon property cannot be refreshed in time when adding the icon by using "Choose Icon..." command line until clicked any where in the propertyGide Window

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#10579]
### .NET version

9.0.0-alpha.1.24053.2

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it doesn't work in .Net 8.0 from Release/8.0 branch of Winforms repo

### Issue description

 The selected icon for Icon property cannot be refreshed in time when adding the icon by using "Choose Icon..." command line until clicked any where in the propertyGide Window

### Steps to reproduce

1. Build & Run test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo
2. Adding the icon for Icon property by using "Choose Icon..." command line
3. Observed the added icon for Icon property
4. Clicked any where in the propertyGide Window
5. Observed the added icon for Icon property

**Actual Results:**
After stpes#4, the added icon for Icon property is not refresh in time
After stpes#5, the added icon for Icon property is refreshed
![DemoConsole](https://github.com/dotnet/winforms/assets/38325459/b0529be4-0432-4768-a074-af71510b757b)

**Expected Results:**
After stpes#4, the added icon for Icon property can refresh in time

**More info:**
1. The issue cannot reproduce when adding the icon by using Icon property.
2. The selected icon for Icon property can be refreshed in time when adding the icon by using "Choose Icon..." command line in Design time property grid.
3. Can't support modified the icon property of the NotifyIcon control in runtime property grid by using command line.

**PropertyGrid_RunTime**
![PropertyGrid_RunTime](https://github.com/dotnet/winforms/assets/38325459/461354c7-0fa3-4b3e-826e-57b0d86553d1)
**PropertyGrid_DesignTime**
![PropertyGrid_DesignTime](https://github.com/dotnet/winforms/assets/38325459/f0836272-b60c-44ac-90c4-1ebcedcf6eb1)

**Comment by elachlan** [comment]
I think `NotifyIconActionList.ChooseIcon` probably needs to trigger a component changed event of some kind? Reminds me a little of #10427

**Comment by Zheng-Li01** [comment]
The issue also can reproduce when using "Set Mask..." & "Choose Image..." commands to set the property value.
![image](https://github.com/dotnet/winforms/assets/38325459/2489e6d5-86fa-4fc4-8bb4-f5b8d5b414e8)

**Comment by elachlan** [comment]
https://github.com/dotnet/winforms/blob/62612eea70eef656e0b2f19442b126e296e4ffee/src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CommandsPane.cs#L113-L135

If after the `Invoke()` call we then call `OwnerPropertyGrid.RefreshProperties(false);` to trigger a refresh, it seemed to fix the problem. But I am unsure if it is the "correct" way to do it.

I feel like there should be a lower level monitoring/binding of property values that then triggers the refresh.

**Comment by elachlan** [comment]
@JeremyKuhne can you provide guidance on the above? Should the `CommandsPane` be calling a refresh on the `PropertyGrid` when the `Invoke` is called? I am unsure how "correct" this fix is.

**Comment by JeremyKuhne** [comment]
I'd double check with .NET Framework before making any decisions. Then my gut reaction is that `CommandsPane` should own solving this problem.

**Comment by LeafShi1** [comment]
This issue only appears in DemoConsole Application, it work well in Winform Designer.
I compared the code with Winform Designer, and find that the _selectedObjects always null when executing function [OnComponentChanged ](https://github.com/dotnet/winforms/blob/bd0e29875b819a0467427cb9dc6f27852d5635a6/src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs#L2445) in PropertyGrid.cs.  
![image](https://github.com/dotnet/winforms/assets/132890443/688c12a8-af53-4b8b-a4aa-1f3caff6ddc6)
But in Winform Designer, the _selectedObjects is "NotifyIcon".

If adding a PropertyGrid page for the NotifyIcon control in Form, the _selectedObjects will be "NotifyIcon" and the Icon can be refreshed in Form designer.
![BeforeChange](https://github.com/dotnet/winforms/assets/132890443/2156bc39-50bd-4177-86f3-ec0515e7e070)

**Comment by Syareel-Sukeri** [comment]
Verified the issue on latest [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo from main branch, the issue has been fixed where the selected icon for Icon property can be refreshed in time when adding the icon by using "Choose Icon...." command line.

![IconTest](https://github.com/dotnet/winforms/assets/156630333/03955b4e-75cc-4718-a2a8-a6a6a4e658ce)

**Comment by John-Qiao** [comment]
Verified this issue in the release/9.0-preview4 branch of winforms repo, it was fixed. Test result is same as above.
