### ISSUE TITLE
An error occurs after resizing a control in the DemoConsole application

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#10580]
### .NET version

9.0.0-alpha.1.24053.2

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue.

### Issue description

In the **Use SnapLines** of the [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, control cannot be resized.

**Actual result** in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app:

https://github.com/dotnet/winforms/assets/104609169/2773f67d-d721-4d66-8ebc-8fc44f4f04fa

**Expected result:**
Controls can be resized.

https://github.com/dotnet/winforms/assets/104609169/968971fe-2c4b-4aad-bb62-0515938541b6

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by elachlan** [comment]
#10279 just made changes to this.

**Comment by Tanya-Solyanik** [comment]
@elachlan  - would  you be interested in fixing this issue?

**Comment by elachlan** [comment]
@Tanya-Solyanik done PR is at #10584

**Comment by Tanya-Solyanik** [comment]
@elachlan  - could you please add the repeating segment of the stack to the bug for a better description, if you have one handy

**Comment by elachlan** [comment]
Here we go.
![image](https://github.com/dotnet/winforms/assets/2433737/228b6d58-f9b8-44ac-be59-f73019024a3d)
![image](https://github.com/dotnet/winforms/assets/2433737/978d4797-29b5-483f-8089-bbbd568ee69b)

**Comment by Zheng-Li01** [comment]
Verified this in the release/9.0-preview1 branch of winforms repo, which has been fixed that have the same results as above.
