### ISSUE TITLE
Fix ApiCompatBaseline.netcoreapp.txt 

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#1059]
Minimise the number of APIs missing. Some sort of tooling allowing false-negatives (i.e. APIs that actually do exist but are written in as not existing) to be notified would help!

**Comment by hughbe** [comment]
@zsd4yr @ViktorHofer is there a way to re-generate the ApiCompatBaseline file, or at least test it?

**Comment by zsd4yr** [comment]
> @zsd4yr @ViktorHofer is there a way to re-generate the ApiCompatBaseline file, or at least test it?

@Shyam-Gupta 	may know more

**Comment by ViktorHofer** [comment]
C:\git\corefx\src\shims>dotnet msbuild /t:Rebuild ApiCompat.proj

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by ericstj** [comment]
As Viktor mentioned you can build the project that runs APICompat specifying /p:BaselineApiCompat=true.  In this case its `src/System.Design/src/System.Design.Facade.csproj`

**Comment by RussKie** [comment]
Added to the wiki - https://github.com/dotnet/winforms/wiki/Re-generate-the-ApiCompatBaseline-file

**Comment by hughbe** [comment]
I modified `src/System.Drawing.Design/src/ApiCompatBaseline.txt` to read the following (deleting FontNameEditor which does in fact exist and deleting ToolboxItemCreator which does not exist);

```
Compat issues with assembly System.Drawing.Design:
TypesMustExist : Type 'System.Drawing.Design.ContentAlignmentEditor' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'System.Drawing.Design.IconEditor' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'System.Drawing.Design.ToolboxItemContainer' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'System.Drawing.Design.ToolboxService' does not exist in the implementation but it does exist in the contract.
Total Issues: 6
```

I then ran
```
C:\Users\hughbe\Documents\GitHub\winforms>C:\Users\hughbe\Documents\GitHub\winforms\.dotnet\dotnet.exe msbuild /t:Rebuild ./src/System.Drawing.Design/src/System.Drawing.Design.Facade.csproj /p:BaselineApiCompat=true
```

and got the following output:
```
Microsoft (R) Build Engine version 16.2.0-preview-19278-01+d635043bd for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Accessibility-version -> C:\Users\hughbe\Documents\GitHub\winforms\artifacts\bin\Accessibility-version\Debug\netcoreapp3.0\Accessibility-version.dll
  Accessibility -> C:\Users\hughbe\Documents\GitHub\winforms\artifacts\bin\Accessibility\Debug\netcoreapp3.0\Accessibility.dll
  System.Windows.Forms -> C:\Users\hughbe\Documents\GitHub\winforms\artifacts\bin\System.Windows.Forms\Debug\netcoreapp3.0\System.Windows.Forms.dll
  System.Windows.Forms.Design.Editors -> C:\Users\hughbe\Documents\GitHub\winforms\artifacts\bin\System.Windows.Forms.Design.Editors\Debug\netcoreapp3.0\System.Windows.Forms.Design.Editors.dll
  System.Drawing.Design.Facade -> C:\Users\hughbe\Documents\GitHub\winforms\artifacts\bin\System.Drawing.Design.Facade\Debug\netcoreapp3.0\System.Drawing.Design.dll
C:\Users\hughbe\Documents\GitHub\winforms>
```

Am I doing smething wrong? It appears as if the ApiCompatBaseline.txt file is not being read - I'd expect an error here

**Comment by ericstj** [comment]
If you specify `/p:BaselineApiCompat=true` you will not get any error and the baseline text file will be rewritten.  Is this what you are observing?

**Comment by hughbe** [comment]
https://github.com/dotnet/winforms/pull/1538 has a fix. The problem was that we didn’t reference Microsoft.DotNet.ApiCompat package anywhere so we never used it!

**Comment by ericstj** [comment]
right, I discussed that with @zsd4yr last week.  Had assumed you were doing that as part of this work.
