### ISSUE TITLE
Enable ToolStripItem to support specifying specific Renderer

### ISSUE THREAD

**Issue by CuteLeon** [dotnet/winforms#10592]
### Background and motivation

I implemented a specified ToolStripItem class, and hope to specify a renderer for it to reuse base OnPaint logic, instead of using owner's renderer. While ToolStripItem's Renderer property was decleared as Internal and not overrideable.

### API Proposal

```csharp
public abstract partial class ToolStripItem
{
    protected virtual ToolStripRenderer? Renderer
    {
        get
        {
            if (Owner is not null)
            {
                return Owner.Renderer;
            }

            return ParentInternal?.Renderer;
        }
    }
}
```

### API Usage

```csharp
public class MyToolStripButton : ToolStripButton
{
    protected static ToolStripProfessionalRenderer OverrideRenderer = new();

    protected override ToolStripRenderer? Renderer { get => OverrideRenderer; }
}
```

### Will this feature affect UI controls?

1. No
2. No
3. No

**Comment by terrajobst** [comment]
Reviewed and approved offline.
