### ISSUE TITLE
Winforms apps crash when using clipboard APIs

### ISSUE THREAD

**Issue by miguep** [dotnet/winforms#1060]
.NET Core Version: 3.0.100-preview6-012099

Windows version: Win10

Does the bug reproduce also in Winforms for .NET Framework 4.8?: No

Problem description:
Using some of the Clipboard APIs, throw exceptions and cause application crashes.
E.g.
Clipboard.SetData(DataFormats.UnicodeText, "abc");

Actual behavior: 
Throws an ExecutionEngineException.

Expected behavior:
sets the data to the clipboard without issue

Minimal repro:
Clipboard.SetData(DataFormats.UnicodeText, "abc");

this issue was found in WPF as well, we've filed a coreclr issue as we believe that's where the root cause is.

https://github.com/dotnet/coreclr/issues/24816
https://github.com/dotnet/wpf/issues/775

**Comment by miguep** [comment]
Looks like this has been fixed in dotnet/coreclr#24818.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you confirm and close all the related issues?

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you test this scenario out?

**Comment by Olina-Zhang** [comment]
Verified in  .Net Core SDK 3.0.100 Preview6 3.0.100.12258 build, this issue has been fixed. Closing it.
