### ISSUE TITLE
.NET 8.0 listview SelectedItems not working

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#10606]
### .NET version

.NET 8.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET 4.8

### Issue description

When checking listviewitems in a listview , the SelectedItems  of the listview doesn't change.

### Steps to reproduce

1. create listview
2. enable multi select for the listview and checkboxes too
3. check some listviewitems with mouse
4. the SelectedItems of listview is not updated after doing 3. If you check SelectedItems.Count, the value is always 0 which is impossible because you have selected more then 1 listviewitem in 3.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this?

**Comment by Olina-Zhang** [comment]
Tested ListView's SelectedItems.Count in .Net framework 4.8.1 and .NET 8, they have same result, in above step3, you must click listView items to select, not checkBox.
.Net framework 4.8.1 behavior:

https://github.com/dotnet/winforms/assets/26474449/f7083815-af70-4aa2-968f-72cc6b6c47be


.NET 8 behavior:

https://github.com/dotnet/winforms/assets/26474449/86b5fbd0-1fc6-4830-b4b9-dee346a001ff

**Comment by JeremyKuhne** [comment]
Thanks @Olina-Zhang!
