### ISSUE TITLE
KeysConverter.GetStandardValues() throws an exception

### ISSUE THREAD

**Issue by cadilhac** [dotnet/winforms#10610]
### .NET version

8.0.100

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Used to work in .Net 6 and 7.

### Issue description

Simply calling

`var test = new KeysConverter().GetStandardValues();`

throws the exception:

> System.Collections.Generic.KeyNotFoundException: 'The given key 'en-US' was not present in the dictionary.'

Looking at the KeysConverter source code, it's easy to see that the CultureToKeyName property is initialized only with the invariant culture at construction time. Other cultures are added only if ConvertFrom() or ConvertTo() are called first. This is a serious breaking change.

If this was intended, is it documented? What is a workaround?

### Steps to reproduce

Create a console app targetting .net 8. Simply add the code:

`var test = new KeysConverter().GetStandardValues();`

### Possible fix

In GetStandardValue(), this guard should be added:

```
if (!CultureToKeyName.ContainsKey(CultureInfo.CurrentCulture))
	AddLocalizedKeyNames(CultureInfo.CurrentCulture);
```

Note that I think CultureInfo.CurrentCulture was changed to CurrentUICulture in .Net 9 preview if I remember well a post that I saw previously.

On a deeper level, prior to .Net 8, ConvertTo, ConvertFrom and GetStandardValues were not using culture for localization. With .Net 8, it seems it changed but partially only. If it was working correctly, it seems that it is always expected that GetStandardValues() returns results for the current culture, although ConvertTo and ConvertFrom can adapt to any culture... ?

**Comment by Tanya-Solyanik** [comment]
No, it wasn't intentional. We should fix GetStandardValues to add other cultures as well.

**Comment by cadilhac** [comment]
> No, it wasn't intentional. We should fix GetStandardValues to add other cultures as well.

While you were responding, I was adding some thoughts in a "Possible fix" section of my original post.
What do you think?
What workaround would you advise for me in .Net 8? My code is in a commercial product and I'm just realizing that it broke because of that.

**Comment by cadilhac** [comment]
> @cadilhac - yes, same as your suggestion, either CurrentCulture or CurrentUICulture.

But what about a workaround for now? For a client app using .Net 8? I can't modify KeysConverter source code nor write a subclass because it can't access KeysConverter's private members.

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team take point on this issue? @KlausLoeffelmann will be able to help you with any guidance your team needs (assign your person to this issue too). We should also service .NET 8 with whatever fix we approve.

**Comment by cadilhac** [comment]
I see some work done and the use of CurrentCulture in KeysConverter. But shouldn't CurrentUICulture be used instead as per https://github.com/dotnet/winforms/issues/10384?

**Comment by Tanya-Solyanik** [comment]
@cadilhac  - good point, we were using CUrrentUICulture in .NET Framework too - https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/KeysConverter.cs,64

**Comment by Tanya-Solyanik** [comment]
@cadilhac  - i'm wrong. GetStandardValues is supposed to return the enum values, I was looking at the keys collection instead of the values collection. "Standard values" are always culture-independent.

**Comment by cadilhac** [comment]
> @cadilhac - i'm wrong. GetStandardValues is supposed to return the enum values, I was looking at the keys collection instead of the values collection. "Standard values" are always culture-independent. Before the fix, we were looking up by a culture that wasn't initialized. After the fix, we are looking up by culture that is always initialized.

Ok, got it. Can't remember how/when I had seen some references to CurrentCulture in this file... and someone had mentioned this issue and it was planned to use CurrentUICulture instead. Forget it.

**Comment by cadilhac** [comment]
> I'm wrong. GetStandardValues is supposed to return the enum values, I was looking at the keys collection instead of the values collection. "Standard values" are always culture-independent. Before the fix, we were looking up by a culture that wasn't initialized. After the fix, we are looking up by culture that is always initialized.

I was not looking at GetStandardValues only, but the whole code in [KeyxConverter](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/Input/KeysConverter.cs). Shouldn't CurrentCulture be replaced by CurrentUICulture in general?

**Comment by Tanya-Solyanik** [comment]
Now I see what you mean. Had you experienced any problems caused by that issue?

**Comment by cadilhac** [comment]
> Now I see what you mean. Had you experienced any problems caused by that issue?

Not personally, but as the developer of a custom PropertyGrid, I had not tried to adhere to the user's UI culture and I realize that shortcuts should be displayed in the user's language. It was working in .Net Framework without I even realized it. Stopped working in core without I even knew...

**Comment by Zheng-Li01** [comment]
Verified the issue on 9.0.0-preview.2.24073.3, the issue has been fixed that calling `var test = new KeysConverter().GetStandardValues(); `to return standard key values, and tested ShortcutKeys scenarios, GH issue [2886](https://github.com/dotnet/winforms/issues/2886) verification, no new issue found.
![image](https://github.com/dotnet/winforms/assets/38325459/3cc4b8f4-512f-4bd1-bdfc-b361f99bfc7d)

**Comment by Eudora-Li01** [comment]
Verified this issue with .NET 9 Preview 1 test pass build, it was fixed. Test result is same as above.

**Comment by MandiMan** [comment]
Verified issue on .NET 8.0.200 with dlls built from Release/8.0 branch of WinForms repo, the issue was fixed, test result is as above screenshot.

**Comment by Nora-Zhou01** [comment]
Verified with .NET SDK 8.0.3 test pass build, this issue was fixed. Test result is same as above.

**Comment by Zheng-Li01** [comment]
Verified with .NET SDK 9.0.100-preview.2.24129.7 test pass build, this issue was fixed. Test result is same as above.
