### ISSUE TITLE
The horizontal scrollbar is unnecessarily visible in the listbox at a 110 scaling in Winforms.

### ISSUE THREAD

**Issue by sneha-latha-kv** [dotnet/winforms#10618]
### .NET version

.Net 7.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

NO

### Issue description

When using the listbox at a 110 scaling , the horizontal scrollbar is visible, whereas in 125 or 150 scaling, the horizontal scrollbar is not visible.
![image](https://github.com/dotnet/winforms/assets/121555390/991df866-0557-421a-80f0-2e3458ab650b)

### Steps to reproduce

Set the Screen scaling to 110
Add listbox into the form with HorizontalScrollbar property set to true
Run the Sample
Note that the HorizontalScrollbar will be visible
Now change the scaling to 125 OR 150 , Note that the HorizontalScrollbar will not be visible now
[HorizontalScrollBar.zip](https://github.com/dotnet/winforms/files/13874386/HorizontalScrollBar.zip)

**Comment by elachlan** [comment]
@sneha-latha-kv can you provide labelled screenshots at different dpi settings?

**Comment by merriemcgaw** [comment]
We may not be able to prevent scrollbars in all random dpi scaling. The font from the application plays a role here in Windows determining if a scrollbar is needed. In the case of 110% the text would be truncated without the scrollbar.
