### ISSUE TITLE
An exception pops up when using the method System.Diagnostics.Process.Start() in the .NET Core 3.0 winforms application

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/winforms#1061]
* .NET Core Version: .NET Core 3.0.100-preview6-012101 from master branch
* Have you experienced this same bug with .NET Framework?: No

**Steps to Reproduce:**

1. Create a Winforms .Net Core application.
2. Write code to Form1.cs.
   System.Diagnostics.Process.Start("http://www.bing.com");
3. Build and run the application.

**Actual behavior:** 
When debugging to _System.Diagnostics.Process.Start("http://www.bing.com")_, the exception pops up.
![Error](https://user-images.githubusercontent.com/49627022/58533671-b5f57100-821b-11e9-89ea-a7bf8aff7191.png)

**Call Stack:**
System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=The system cannot find the file specified.
  Source=System.Diagnostics.Process
  StackTrace:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at test1.Form1..ctor() in C:\Users\v-jiaol\Desktop\demo\test1\Form1.cs:line 18
   at test1.Program.Main() in C:\Users\v-jiaol\Desktop\demo\test1\Program.cs:line 19

**Expected behavior:**
No exception pops up, application runs successfully.

**Comment by RussKie** [comment]
I'm guessing this is a CoreFx issue

**Comment by Amy-Li02** [comment]
CoreFx exists the same issue: [Process Start fails with URL on .NET Core 3](https://github.com/dotnet/corefx/issues/33714), so close it.

**Comment by RussKie** [comment]
Duplicate of dotnet/corefx#33714
