### ISSUE TITLE
[9.0.100-alpha.1.24055.6] HtmlDocument.Write() throw System.Runtime.InteropServices.COMException (0x80020008): Bad variable type.

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/winforms#10615]
### .NET version

```
.NET SDK:
 Version:           9.0.100-alpha.1.24055.6
 Commit:            ca1439c8ae
 Workload version:  9.0.100-manifests.f3b52893

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-alpha.1.24055.6\

.NET workloads installed:
 There are no installed workloads to display


Host:
  Version:      9.0.0-alpha.1.24054.18
  Architecture: x64
  Commit:       9325d3836d

.NET SDKs installed:
    9.0.100-alpha.1.24055.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-alpha.1.24055.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-alpha.1.24054.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-alpha.1.24055.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes
1. Windows10 21h2 x64 + dotnet-sdk-7.0.405: Pass
2. Windows10 21h2 x64 + dotnet-sdk-8.0.101： Pass
3. Windows10 21h2 x64 + dotnet-sdk-9.0.100-alpha.1.24055.6: Fail

### Issue description

When calling ```HtmlDocument.Write()``` to write a HTML page on dotnet-sdk-9.0.100-alpha.1.24055.6, it throws ```"System.Runtime.InteropServices.COMException (0x80020008): Bad variable type"``` exception.

**Application Name**: Character-Builder-5
**OS**： Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-9.0.100-alpha.1.24055.6
**App or App source checking at:**  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1936945

**Github link:** https://github.com/MalukuSeito/Character-Builder-5

### Steps to reproduce

**Minimal Repro steps (Demo attached):**
[BadVariableDemo.zip](https://github.com/dotnet/winforms/files/13871376/BadVariableDemo.zip)

**The machine has dotnet-sdk-9.0.100-alpha.1.24055.6 installed.**

​​1.Create a .NET 7 or .NET 8 WinForm project.
2. Add following code in Form1.cs file:
```
public Form1()
{
    InitializeComponent();
        
    WebBrowser webBrowser = new WebBrowser();
    string s = "<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<html>\r\n</html>";
    webBrowser.Navigate("about:blank");
    webBrowser.Document.Write(s);
}
```
4. Build the project.
5. Update the runtime config file to .NET 9 versions:
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-alpha.1.24054.18"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-alpha.1.24055.1"
      }
    ],
```
7. Launch the app

**Expected Result:**
App launch successfully.

**Actual Result:**
App launch failed with Bad variable type exception.

**StackTrace:**
```
Exception Info: System.Runtime.InteropServices.COMException (0x80020008): Bad variable type.

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at Windows.Win32.Foundation.HRESULT.ThrowOnFailure(IntPtr errorInfo)
   at System.Windows.Forms.HtmlDocument.Write(String text)
   at BadVariableDemo.Form1..ctor() in E:\Demos\BadVariableDemo\BadVariableDemo\Form1.cs:line 12
   at BadVariableDemo.Program.Main() in E:\Demos\BadVariableDemo\BadVariableDemo\Program.cs:line 14
```
@dotnet-actwx-bot @dotnet/compat

**Comment by John-Qiao** [comment]
Verified on .NET 9.0.100-alpha.1.24068.28 + latest dlls from Winforms Repo of main branch, it was fixed. The app can be launched successfully without error now.

![10615-testresult](https://github.com/dotnet/winforms/assets/45864985/b3662606-a0f4-460b-b24b-768ad35fa118)

**Comment by Junjun-zhao** [comment]
Verified this issue with dotnet-sdk-9.0.100-alpha.1.24070.3, it has been fixed.

**Comment by Eudora-Li01** [comment]
Verified this issue with .NET 9 Preview 1 test pass build, it was fixed. Test result is same as above.
