### ISSUE TITLE
An exception dialog appeared after calling the Clipbpard.SetImage() method

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#1062]
**OS:** RS4 X64
**VS:** Visual Studio 2019 Version 16.2.0 Preview 1.0 [28921.214.d16.2]
**.NET SDK:** .NET Core 3.0 3.0.100-preview6-012102 from master branch
* Have you experienced this same bug with .NET Framework?: No

**More info:** 
The issue also can reproduce when setting the image's format is "emf, gif, ico".

**Steps to Reproduce:**
1. Create a Winforms .Net Core application by command: 
2. Adding the below code in the form1.cs file;
`using System.Drawing.Imaging;     Image actual = null; Image expected = Image.FromFile(@"D:\Test.png"); Clipboard.SetImage(expected);  actual = Clipboard.GetImage();`
3. Debugging the "Clipboard.SetImage(expected)" method.

**Actual:**
When debugging to Clipboard.SetImage(expected); method, an exception dialog appeared.
![Actual](https://user-images.githubusercontent.com/38325459/58543736-9b7ac200-8232-11e9-9645-12d5e1d38189.PNG)

**Expected:**
There no exception appeared.

**Comment by Tanya-Solyanik** [comment]
@Zheng-Li01  - could you please add a couple more details:
1. do you know if this had regressed recently?
2. could you please add a call stack for this exception(in "view details" link)

**Comment by weltkante** [comment]
@Tanya-Solyanik is probably a duplicate of #1060 which is fixed by dotnet/coreclr#24818

**Comment by Zheng-Li01** [comment]
Verified the issue with the latest .NET Core SDK 3.0.100.12121 -preview6 from master branch, the issue has been fixed. So closed it.
