### ISSUE TITLE
[9.0.100-alpha.1.24055.6] AutoVersionsDB app UI mess up when scrolling

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/winforms#10630]
### .NET version

```
.NET SDK:
 Version:           9.0.100-alpha.1.24055.6
 Commit:            ca1439c8ae
 Workload version:  9.0.100-manifests.f3b52893

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-alpha.1.24055.6\

.NET workloads installed:
 There are no installed workloads to display


Host:
  Version:      9.0.0-alpha.1.24054.18
  Architecture: x64
  Commit:       9325d3836d

.NET SDKs installed:
    9.0.100-alpha.1.24055.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-alpha.1.24055.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-alpha.1.24054.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-alpha.1.24055.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

yes

1. Windows10 21h2 x64 + dotnet-sdk-8.0.101: Pass
2. Windows10 21h2 x64 + dotnet-sdk-9.0.100-alpha.1.24055.6: Fail

### Issue description

AutoVersionsDB UI is messed up when scrolling on dotnet-sdk-9.0.100-alpha.1.24055.6. But there is no any exception thrown.

**Application Name:** AutoVersionsDB
**OS：** Windows 10 21H2
**CPU:** X64
**.NET Build Numbe**r: dotnet-sdk-9.0.100-alpha.1.24055.6
**Checking the repro environment** at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1938706

### Steps to reproduce

**The machine has dotnet-sdk-9.0.100-alpha.1.24055.6 installed.**

1. Launch AutoVersionsDB.WinApp under C:\App\AutoVersionsDB.
2. Click "New Project" button.
3. Scroll the content.

**Expected Result:**
Window content will display normally.

**Actual Result:**
The content on Window is messed up.
![ReproSteps](https://github.com/dotnet/winforms/assets/83067197/e7c6d4da-05b6-46c6-b984-63f48d69f108)

@dotnet-actwx-bot @dotnet/compat

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team find the root PR that introduced this.

**Comment by LeafShi1** [comment]
> @LeafShi1 can your team find the root PR that introduced this?

This issue caused by PR #10448

**Comment by Nora-Zhou01** [comment]
Verified this issue on .NET 9.0.0-alpha.1.24061.5 with dlls built form winforms repo of main branch, Change the **AutoVersionsDB.WinApp.runtimeconfig.json** file to 9.0, it was fixed, Window content will display normally.
[test.zip](https://github.com/dotnet/winforms/files/13985402/test.zip)


https://github.com/dotnet/winforms/assets/104609169/2aff933e-2c99-4bce-ac0d-66b100a1ac1e

**Comment by Junjun-zhao** [comment]
Verified this issue with dotnet-sdk-9.0.100-alpha.1.24070.3, it has been fixed.

**Comment by Eudora-Li01** [comment]
Verified this issue with .NET 9 Preview 1 test pass build, it was fixed. Test result is same as above.
