### ISSUE TITLE
Unified Build control update

### ISSUE THREAD

**Issue by mmitche** [dotnet/winforms#10650]

**Comment by lonitra** [comment]
@mmitche is there anything that needs to be done on our side for this currently?

**Comment by mmitche** [comment]
Not currently. We're currently introducing the new controls. This repo should be a simple rename of X->Y

**Comment by merriemcgaw** [comment]
Assigning @lonitra to monitor for when there is work needed from us. Thanks @mmitche!

**Comment by mmitche** [comment]
https://github.com/dotnet/winforms/pull/10765
