### ISSUE TITLE
Dark mode, the scroll bar theme is incorrect.

### ISSUE THREAD

**Issue by EVA-SS** [dotnet/winforms#10665]
### .NET version

.net6.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

all

### Issue description

After enabling dark mode, the scroll bar remains in the light theme.

![DarkTestGIF](https://github.com/dotnet/winforms/assets/13210002/4d5fac95-d3a4-428e-b35c-ea881f6ff7c5)

```csharp
        private void button1_Click(object sender, EventArgs e)
        {
            Dark = !Dark;
        }

        bool dark = false;
        public bool Dark
        {
            get => dark;
            set
            {
                dark = value;
                if (value)
                {
                    BackColor = Color.Black;
                    ForeColor = Color.White;
                }
                else
                {
                    BackColor = Color.White;
                    ForeColor = Color.Black;
                }
                int useImmersiveDarkMode = value ? 1 : 0;
                DwmSetWindowAttribute(Handle, DWMWA_USE_IMMERSIVE_DARK_MODE, ref useImmersiveDarkMode, sizeof(int));
            }
        }

        #region DarkDwm

        [DllImport("dwmapi.dll")]
        static extern int DwmSetWindowAttribute(IntPtr hwnd, int attr, ref int attrValue, int attrSize);

        const int DWMWA_USE_IMMERSIVE_DARK_MODE = 20;

        #endregion
```

[DarkTest.zip](https://github.com/dotnet/winforms/files/13944921/DarkTest.zip)

### Steps to reproduce

After invoking "Dark=true", the scroll bar color remains in the light theme.

**Comment by elachlan** [comment]
Call `Invalidate()` after the call to `DwmSetWindowAttribute`.
https://stackoverflow.com/a/62811758

**Comment by merriemcgaw** [comment]
We are unable to change the background color of scrollbars. This is an area that we're looking at for the theming and seeing if we can get a solution in the future. For now, this is a known issue.

**Comment by EVA-SS** [comment]
😭Alright, this is pretty frustrating, I'm really hoping to get some good news from you guys.

**Comment by elachlan** [comment]
@EVA-SS I'd encourage you to investigate a solution if you have the time and ability. Especially if this is blocking you and your app.

**Comment by elachlan** [comment]
This looks promising!
https://learn.microsoft.com/en-us/windows/win32/controls/wm-ctlcolorscrollbar

**Comment by EVA-SS** [comment]
> This looks promising!
> 
> > The WM_CTLCOLORSCROLLBAR message is used only by child scroll bar controls. Scrollbars attached to a window (WS_SCROLL and WS_VSCROLL) do not generate this message. To customize the appearance of scrollbars attached to a window, use the flat scroll bar functions.
> 
> * https://learn.microsoft.com/en-us/windows/win32/controls/wm-ctlcolorscrollbar
> * https://learn.microsoft.com/en-us/windows/win32/controls/flat-scroll-bars
> * https://learn.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-flatsb_setscrollprop
> 
> And disappointment:
> 
> > Flat scroll bars are supported by Comctl32.dll versions 4.71 through 5.82. Comctl32.dll versions 6.00 and later do not support flat scroll bars.

🙂 Thank you for bringing up the idea, FlatSB can indeed change the scrollbar style. As you pointed out, there are some issues with it, and it's not perfect. overriding the native scrollbar is a challenging task indeed.

**Comment by elachlan** [comment]
Maybe its something that can be done using VisualStyles and the `ScrollBarRenderer`?

**Comment by EVA-SS** [comment]
#4479  #2040 I think currently, ScrollBarRenderer isn't up to the task.

**Comment by elachlan** [comment]
@EVA-SS Are you happy for me to close this issue in favor of those issues?

**Comment by EVA-SS** [comment]
okay

**Comment by KlausLoeffelmann** [comment]
#10985
