### ISSUE TITLE
The caret is in the wrong place When typing into a MaskedTextBox using JP IME, 

### ISSUE THREAD

**Issue by changhao6** [dotnet/winforms#10662]
### .NET version

.net8

### Did it work in .NET Framework?

Yes

### Issue description

![MaskedTextBox](https://github.com/dotnet/winforms/assets/47862827/b5115e20-9d0f-42f4-929c-270274f916c1)
Typing some words to MaskedTextBox using Japanese IME, the position of the caret will always be in the leftmost part of the textbox if Select All (CTRL+A) first

> 

### Steps to reproduce

1. Drag and drop a MaskedTextBox to the designer form from the toolbox.
2. Set MaskedTextBox Mask property to `(999) 000-0000`
3. Run application.
4. Click the MaskedTextBox and press `Ctrl+A`.
5. Type `123` to the MaskedTextBox by using  MS JP IME and then press `Enter`.
6. The caret position still at the start of MaskedTextBox (it's wrong).

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang can your team please test this?

It is not a regression issue, still reproduce from .Net framework 4.7.2 to .Net 9 in MS Japanese IME.

https://github.com/dotnet/winforms/assets/26474449/c1378ad8-d77f-4617-98b5-e9a613cb1a6b

**Comment by merriemcgaw** [comment]
Thank you for reporting this! It looks like this issue has been around for all of .NET Framework. There's likely a problem with the Common Control and that's not something we're able to address at this time.
