### ISSUE TITLE
VS is not responding after adding a user control that with events handling to the Form designer

### ISSUE THREAD

**Issue by SimonZhao888** [dotnet/winforms#10677]
### .NET version

9.0.100-alpha.1.24066.10

### Did it work in .NET Framework?

Not tested/verified

### Issue description

VS is not responding after adding a user control that with events handling to the Form designer.
![84885709-fee9c300-b0c5-11ea-986c-1c4ae0352f57](https://github.com/dotnet/winforms/assets/133954995/e19ca3bd-f364-40ff-bc57-ec83e49adcec)

### Steps to reproduce

1. Create a Winforms core project.
2. Add a User Control to the same project.
3. Generate the UserControl1_Load event with following code: MessageBox.Show("Not Responding");
4. Build and reopen the Form designer.
5. Drag the user control to the Form designer.

Or

1. Open the attached project. [NotResponding.zip](https://github.com/dotnet/winforms-designer/files/4791793/NotResponding.zip)
2. Build and Drag the user control to the Form designer.

**Comment by SimonZhao888** [comment]
Tanya provides a solution at: https://github.com/microsoft/winforms-designer/issues/1995#issuecomment-1890223773

**Comment by MandiMan** [comment]
Verified this issue on .NET 9.0.100-preview.2.24107.18 with dlls built from winforms repo of main branch, the issue has been fixed. No MessageBox pop up when adding a user control with events handing to the Form designer.

https://github.com/dotnet/winforms/assets/108860782/0991ff93-0e24-40ba-b38e-3438d331c28a
