### ISSUE TITLE
KeysConverter should use CurrentUICulture when converting to name in default context.

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#10687]
KeysConverter in NET8 started converting keys to strings based on the CurrentCulture - https://github.com/dotnet/winforms/blob/f7d6850caa53f62816d977e737d6cb2a537f0d9a/src/System.Windows.Forms/src/System/Windows/Forms/Input/KeysConverter.cs#L332-L354

However, in .NET Framework, we were looking up names based on the CurrentUICulture - https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/KeysConverter.cs,64 from the resources like this:

AddKey(SR.**GetString**(SR.toStringPageDown), Keys.Next);

this code goes to [ResourceManager.GetString Method (System.Resources) | Microsoft Learn](https://learn.microsoft.com/dotnet/api/system.resources.resourcemanager.getstring?view=netframework-4.8.1#system-resources-resourcemanager-getstring(system-string))
and returns

> The value of the resource localized for the caller's current UI culture, or null if name cannot be found in a resource set.

_Originally posted by @cadilhac in https://github.com/dotnet/winforms/issues/10610#issuecomment-1897509534_

**Comment by elachlan** [comment]
I'd like to see this change, but what about the comment?
`// Use CurrentCulture as default to match other TypeConverters.`

We use `CultureInfo.CurrentCulture` all over the place and don't use `CultureInfo.CurrentUICulture`  for whatever reasons. When should we be using `CurrentUICulture` over `CurrentCulture`?

**Comment by Tanya-Solyanik** [comment]
Comment refers to https://github.com/dotnet/runtime/blob/9f8f6531b72c44da09d5ffcadf638f11cf51d227/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeConverter.cs#L49
I guess that TypeConverter is not optimized for UI while this converter has been using the UI culture in .NET Framework.

**Comment by merriemcgaw** [comment]
@LeafShi1 can you please have your team fix this as a follow up to the previous servicing you all did?
