### ISSUE TITLE
Investigate SetClientSite(null) in AxHost.DisposeAxControl

### ISSUE THREAD

**Issue by lonitra** [dotnet/winforms#10692]
While adding tests for `AxSystemMonitor` in https://github.com/dotnet/winforms/pull/10675 , it was found that we get an HRESULT error while attempting to dispose of the control. There is an odd call to `IOleObject.SetClientSite(null)` in `AxHost.DisposeAxControl` that gives back `HRESULT.E_POINTER` when attempting to dispose an ActiveX control. We have always been passing `null` to `IOleObject.SetClientSite` since Framework so it is unclear whether or not this method has ever succeeded. The [docs](https://learn.microsoft.com/en-us/windows/win32/api/oleidl/nf-oleidl-ioleobject-setclientsite#notes-to-callers) seems to indicate that it is ok to pass `null` pointer so we should investigate what is happening in the windows code and determine next steps to resolve this.

Repro (could also use other active x controls):
```c#
        using Form form = new();
        using AxSystemMonitor.AxSystemMonitor control = new();
        ((ISupportInitialize)control).BeginInit();
        form.Controls.Add(_control);
        ((ISupportInitialize)_control).EndInit();
```

Once fixed, we should also update our tests that test ActiveX controls to dispose of them properly.

**Comment by JeremyKuhne** [comment]
The [ATL host `CAxFrameWindow`](https://learn.microsoft.com/cpp/atl/atl-control-containment-faq?view=msvc-170) is setting null when tearing down (in atlhost.h in atlmfc sources which can be found in the VS folder). It doesn't check the result.
