### ISSUE TITLE
[dotnet-sdk-9.0.100-alpha.1.24070.3] AnalogyLogViewer launch failed with error: "System.AccessViolationException: Attempted to read or write protected memory..."

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/winforms#10719]
### .NET version

```
.NET SDK:
 Version:           9.0.100-alpha.1.24070.3
 Commit:            f91d4ca399
 Workload version:  9.0.100-manifests.0d37fe7a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-alpha.1.24070.3\

.NET workloads installed:
 [wasm-tools]
   Installation Source: VS 17.8.34408.163
   Manifest Version:    9.0.0-alpha.1.24066.33/9.0.100-alpha.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-alpha.1\microsoft.net.workload.mono.toolchain.current\9.0.0-alpha.1.24066.33\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      9.0.0-alpha.1.24066.33
  Architecture: x64
  Commit:       dbb335c6ba

.NET SDKs installed:
  9.0.100-alpha.1.24070.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-alpha.1.24068.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-alpha.1.24066.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-alpha.1.24068.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

**Yes** 

1). Windows 10 21h2 AMD64 + dotnet-sdk-9.0.100-alpha.1.24070.3: Fail

2). Windows 10 21h2 AMD64 + dotnet-sdk-9.0.100-alpha.1.24072.15: Fail

3). Windows 10 21h2 AMD64 + dotnet-sdk-9.0.100-alpha.1.24066.1: Pass

4). Windows 10 21h2 AMD64 + dotnet-sdk-8.0.101-win-x64: Pass

5). Windows 10 21h2 AMD64 + dotnet-sdk-7.0.405-win-x64: Pass

### Issue description

When launching a 3rd party application with latest .NET 9 version, a System.AccessViolationException: " Attempted to read or write protected memory. This is often an indication that other memory is corrupt" will be encountered.

**Application Name**: AnalogyLogViewer
**OS**: Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-9.0.100-alpha.1.24070.3
**Github link**: https://github.com/Analogy-LogViewer/Analogy.LogViewer
**App or App source checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1943748
### Steps to reproduce

**App repro steps:**
**The machine only has dotnet-sdk-9.0.100-alpha.1.24070.3 installed. And environment variable DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX set as 2**
1.Launch Analogy.exe in "\Analogy.LogViewer".

**Expected Result**: Launch successfully.
**Actual Result**: Launch failed with error: 
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at DynamicClass.__get_handle(System.Drawing.Icon)
   at DevExpress.Utils.Helpers.IconGuard.IsDisposedOrInvalid(System.Drawing.Icon)
   at DevExpress.XtraEditors.FormIconOptions+FormIconHelper.GetIconHandleSafely(System.Drawing.Icon)
   at DevExpress.XtraEditors.FormIconOptions.CheckUpdateIcon()
   at DevExpress.XtraEditors.FormIconOptions.get_Icon()
   at DevExpress.XtraEditors.FormIconOptions.get_UseIconImage()
   at DevExpress.XtraEditors.FormIconOptions.UpdateIcon(Boolean)
   at DevExpress.XtraEditors.FormIconOptions.InitializeIcon(Boolean)
   at DevExpress.XtraEditors.FormIconOptions..ctor(DevExpress.XtraEditors.IFormIconOptionsOwner, Boolean)
   at DevExpress.XtraEditors.FormIconOptions..ctor(DevExpress.XtraEditors.IFormIconOptionsOwner)
   at DevExpress.XtraEditors.XtraForm.CreateIconOptions()
   at DevExpress.XtraEditors.XtraForm..ctor()
   at DevExpress.XtraBars.Ribbon.RibbonForm..ctor()
   at Analogy.Forms.MainForm..ctor(Analogy.Common.Interfaces.IFactoriesManager, Analogy.Common.Interfaces.IExtensionsManager, Analogy.CommonControls.Managers.BookmarkPersistManager, Analogy.Managers.UpdateManager, Analogy.Common.Managers.FileProcessingManager, Analogy.Managers.NotificationManager, Analogy.Interfaces.IAnalogyFoldersAccess, Analogy.Managers.AnalogyOnDemandPlottingManager)
   at Analogy.Program.Main()

```
**Minimal Repro steps (Demo attached):**
[WinFormsDemo.zip](https://github.com/dotnet/winforms/files/14019505/WinFormsDemo.zip)
1. Create a new winform app with .net8.0.

2. Add Assembly reference: DevExpress.Utils.v23.1 and DevExpress.XtraBars.v23.1 from \WinFormsDemo\DevExpress\.net core.

3. Add an inheritance of devexpress in Form1.cs:
` public partial class Form1 : DevExpress.XtraBars.FluentDesignSystem.FluentDesignForm`
4. Build app.
5. Change runtime to .net9.0: 
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-alpha.1.24066.33"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0-alpha.1.24068.7"
      }
    ]
```
6. Launch app.

**Findings:**
It looks like an exception thrown when inheriting from DevExpress.XtraBars.FluentDesignSystem.FluentDesignForm. The current version being used is v23.1. We upgraded to the latest version v23.2.3, it still doesn't work.

@dotnet-actwx-bot @dotnet/compat

**Comment by JeremyKuhne** [comment]
From the call stack it looks like DevExpress is using reflection to get at the private `_handle` field. The type of that field did change so that might be the problem.

It is not supported to use reflection to access private fields or members. Looking at the names of the methods, the right answer here is to `try...catch` around the `Handle` property to handle the `ObjectDisposedException` if that is what they are trying to avoid.

**Comment by merriemcgaw** [comment]
@merriemcgaw to talk to DevExpress to see if they are able to make changes on their end as Jeremy describes. This is a case of using reflection to hit internal stuff that is subject to change. 

cc:/ @PriyaPurkayastha FYI

**Comment by Junjun-zhao** [comment]
Thanks @merriemcgaw and @JeremyKuhne for helping locate the cause root. Do you get any update from DevExpress?

**Comment by merriemcgaw** [comment]
Oh  my gosh, thank you for the reminder @Junjun-zhao - I am letting them know right now!

**Comment by merriemcgaw** [comment]
This is an issue with DevExpress components and we have notified them. They will need to update their controls suite to account for this as private reflection can always result in problems. I would certainly consider this non-blocking.

**Comment by Junjun-zhao** [comment]
Thank you @merriemcgaw for your update. I will close this issue as an application issue.
