### ISSUE TITLE
CancelEdit property has no effect (does not restore old label) in ListView Forms control

### ISSUE THREAD

**Issue by jbennink** [dotnet/winforms#10746]
### .NET version

net8.0-windows

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

net6.0-windows

### Issue description

Instantiate the listview control and when editing the label and leaving it, the old label contents should be restored, but it still displays the new label contents.

P.S. a collegue posted it in the [developer community](https://developercommunity.visualstudio.com/t/CancelEdit-property-has-no-effect-does/10572240?ref=native&refTime=1706262356391&refUserId=ca7d50f0-1802-42f5-ba66-f1d85f34eae9) but I thought it was better suited for this repo.

### Steps to reproduce

See sample code below:
```c#
listView1 = new System.Windows.Forms.ListView();
listView1.LabelEdit = true;
this.listView1.Items.Add(new ListViewItem("test"));
listView1.AfterLabelEdit += listView1_AfterLabelEdit;

    private void listView1_AfterLabelEdit(object sender, LabelEditEventArgs e)
    {
        e.CancelEdit = true;
    }
```

**Comment by elachlan** [comment]
@Olina-Zhang could your team please test this?

**Comment by John-Qiao** [comment]
@jbennink I cannot repro this issue and confirmed more info with you in your initial community ticket, please check it.

**Comment by jbennink** [comment]
(double posting here and on developercommunity)

I made a simple program an ran it with both net6 and net8 to show what goes wrong. The code can be found here, but it’s not much more that listed before: [https://github.com/jbennink/CancelEditListViewRepro](https://github.com/jbennink/CancelEditListViewRepro)

NET 6.0: [https://calwaystorage.blob.core.windows.net/imageuploads/johan/CancelEditListViewRepro\_XLrtxQoPhd.mp4](https://calwaystorage.blob.core.windows.net/imageuploads/johan/CancelEditListViewRepro_XLrtxQoPhd.mp4)

NET 8.0: [https://calwaystorage.blob.core.windows.net/imageuploads/johan/CancelEditListViewRepro\_Q3xzL07Axp.mp4](https://calwaystorage.blob.core.windows.net/imageuploads/johan/CancelEditListViewRepro_Q3xzL07Axp.mp4)

**Comment by JeremyKuhne** [comment]
@John-Qiao can you try again with the additional details given?

**Comment by Olina-Zhang** [comment]
I tested this issue, can repro it. It was regressed from .Net 8, cannot repro in .Net 7 and 6.

.Net 8 and .Net 9 behavior:

https://github.com/dotnet/winforms/assets/26474449/815328cf-06e1-40a9-a339-77b0974b9963


.Net 7 and 6 behavior:

https://github.com/dotnet/winforms/assets/26474449/273de6b5-26a4-4eea-a33f-9032e28fec9c

**Comment by Zheng-Li01** [comment]
Verified this issue on .NET 9.0.0-preview.2.24076.2 with dlls built form winforms repo of main branch, it was fixed that CancelEdit property working well in ListView Forms control.
![10746](https://github.com/dotnet/winforms/assets/38325459/38e3c11c-88a8-430d-b40a-6bc82b2a874c)

**Comment by John-Qiao** [comment]
Verified issue on .NET 8.0.300 with dlls built from Release/8.0 branch of Winforms repo, the issue was fixed, test result is same as above.

**Comment by Syareel-Sukeri** [comment]
Verified with .NET SDK 9.0 Preview 2 test pass build, this issue was fixed. Test result is the same as above.
