### ISSUE TITLE
[Loc]The description text is not showing correctly in MultilineStringEditor drop down.

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/winforms#1076]
* .NET Core Version: 3.0.100-preview6-012122 from Master branch
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
The description text is not showing correctly in MultilineStringEditor drop down.

Issues | Description | Affected language
-- | -- | --
Issue#1 | Description text is not showing in MultilineStringEditor drop down. | TRK, CSY, JPN,   FRA, KOR, PTB,PLK, DEU,
Issue#2 | 2 description sentences should be shown in 2 lines, need to wrap. | CHS, CHT, RUS,   ITA, ESN

**Actual behavior:** 
**Issue#1**: Description text is not showing in MultilineStringEditor drop down. 
![Core](https://user-images.githubusercontent.com/49627022/58677215-ae55d980-838d-11e9-8e2a-0d8960b1aa9c.PNG)
**Issue#2**: 2 description sentences doesn't wrap.
![222](https://user-images.githubusercontent.com/49627022/58677405-64b9be80-838e-11e9-80c7-a02e3b3918d7.png)

**Expected behavior:**
Description text should be show in MultilineStringEditor drop down, and 2 description sentences should be wrap.
![Fra](https://user-images.githubusercontent.com/49627022/58677224-b44bba80-838d-11e9-8676-b5e8bb53fd4b.PNG)

**Minimal repro:**
1.Install latest VS & .NET Core 3.0 on loc machine, then open the attached app.
[WindowsFormsApp2.zip](https://github.com/dotnet/winforms/files/3239429/WindowsFormsApp2.zip)
2.Run it and open the MultilineStringEditor drop down of **Text** property.

**Comment by Olina-Zhang** [comment]
According to the commit: https://github.com/dotnet/winforms/commit/023fd3dd300f9aacf7e481f42cdb04138ca18aac for testing, and found this issue.

**Comment by merriemcgaw** [comment]
@zsd4yr Do you know what the loc status is for WinForms resources

**Comment by lukaschal** [comment]
Issue#1 - String "MultilineStringEditorWatermark" is translated correctly in localization repository. See TRK example below.

https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf

Rid="MultilineStringEditorWatermark"
source: Press Enter to begin a new line.\r\nPress Ctrl+Enter to accept Text.</source>
target:Yeni satıra başlamak için Enter tuşuna basın.\r\nMetni kabul etmek için Ctrl+Enter tuşlarına basın.

**Comment by lukaschal** [comment]
Issue#2 - All strings has in a target added multiline by "\r\n" same as represented in a source.

**Comment by weltkante** [comment]
Probably related to dotnet/wpf#977

**Comment by Amy-Li02** [comment]
Verified this issue in .Net Core 3.0.100-preview8-013096 from master branch, the 2 issues were fixed and in 13 local languages it all works well.
![CHSCore](https://user-images.githubusercontent.com/49627022/61107606-eaaf4600-a4b2-11e9-9fd5-9c12b4fab99c.png)
![TRKCore](https://user-images.githubusercontent.com/49627022/61107614-ee42cd00-a4b2-11e9-8bb3-7633366021f6.png)
