### ISSUE TITLE
Error while compiling test app on winforms repo

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#10786]
### .NET version

Latest Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it cannot repro in last week .NET 9.0 E2E testing on wiforms repo.

### Issue description

Clone winforms repo then use start-vs.cmd, cmd output **build succeded**, but **running** WinformsControlTest app **has error**.

Actual result:
Error while running WinformsControlTest app.
![image](https://github.com/dotnet/winforms/assets/94418985/8d7de808-ed49-46ad-810e-a7d35068c757)

Expected result:
Run WinformsControlTest app successfully with no error.

### Steps to reproduce

1. Clone winforms repo: https://github.com/dotnet/winforms.git
2. Run WinformsControlTest app

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team take a look at this ASAP?

**Comment by LeafShi1** [comment]
- This has nothing to do with Winform code changes. This problem occurred after upgrading VS, and it should be related to the compiler version.
- Using the object initializer "new(){}" instead of "[]" when the collection is initialized can be a workaround, but the source of the problem is not here
- The normal VS build that can currently be traced is 34525.185, and the failed build is 34529.241.main

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 - please look up the compiler (csc.exe) versions that work and that don't work. You could find it in the output window in the VS after the build

**Comment by LeafShi1** [comment]
> csc.exe

Normal compiler (csc.exe) version is 4.10.0-1.24061.4
The compiler version that will fail is 4.10.0-1.24076.10

**Comment by MelonWang1** [comment]
Verified this issue in the latest winforms repo from main branch, it was fixed that the test app can run successfully now.
![Screenshot 2024-02-06 094459](https://github.com/dotnet/winforms/assets/94418985/980459f7-cd74-4360-b219-e60ef4591cd4)

**Comment by MelonWang1** [comment]
Verified this issue from release/9.0-preview2 branch of winforms repo, it was fixed. The WinformsControlTest app can run successfully.
