### ISSUE TITLE
CommandSet warning suppression (Code Quality)

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#1079]
`CommandSet` from System.Windows.Forms.Design has a [suspicious code fragment](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs#L224) which apparently does nothing and suppresses warnings so it doesn't show up during code review in VS.

```C#
	IWin32Window parent = null;
	if (obj is IWin32Window)
	{
#pragma warning disable 1717 // assignment to self
		parent = (IWin32Window)parent;
#pragma warning restore 1717
	}
	success = winEditor.EditComponent(obj, parent);
```
The way this is written it does nothing (`parent` is always null regardless of whether `obj` implements the interface or not)

I verified (via ilspy) that Desktop Framework has the same assignment-to-self so this doesn't seem to be a porting mistake.

I'm bringing this up as an issue so someone with access to the Desktop Framework history can try figuring out what the original intent of those lines might have been, before it gets lost during refactoring/cleanup in the github source base.

**Comment by sharwell** [comment]
I'm not understanding how this is different from:

```csharp
IWin32Window parent = obj as IWin32Window;
success = winEditor.EditComponent(obj, parent);
```

**Comment by weltkante** [comment]
While that might have been the original intention the self-assignment `parent = (IWin32Window)parent` instead of `parent = (IWin32Window)obj` means it doesn't do that. The warning suppression hides the bug.

**Comment by RussKie** [comment]
In its current form the whole things can be replaced with `success = winEditor.EditComponent(obj, null);`, which probably isn't what the intention was...
🤔 

/cc: @Tanya-Solyanik @dreddy-work

**Comment by sharwell** [comment]
> While that might have been the original intention the self-assignment `parent = (IWin32Window)parent`

Facepalm. I spent a good five minutes looking at that before and missed it. This time it was immediately obvious. Weird.
