### ISSUE TITLE
The UserControl will not adjust its size when its parent form resets the font.

### ISSUE THREAD

**Issue by hyke123** [dotnet/winforms#10828]
### .NET version

 8.0.100

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NetFramework4.8

### Issue description

There is a Windows form that includes a userControl. The userControl does not change its size when I reset this form's font in .NET 8. However, it works fine in .NET Framework.
here is the code example to reproduce this issue https://github.com/hyke123/winform-/blob/main/Form1.cs
### Steps to reproduce

1. Create a WinForm class.
2. Create a UserControl class.
3. Place the UserControl on the WinForm using the designer.
4. Add a button to the WinForm using the designer.
5. Add an event for resetting the form font to the button in the designer.
6. Print the height of the UserControl during form initialization and when clicking on the button.

**Comment by elachlan** [comment]
Maybe related: #10774?

**Comment by elachlan** [comment]
@Olina-Zhang can your team please have a look?

**Comment by Olina-Zhang** [comment]
> Maybe related: #10774?

No, it is not.

**Comment by hyke123** [comment]
Thank you for your prompt response.

**Comment by hyke123** [comment]
Hi @Olina-Zhang I apologize for reopening this issue. I set the font in the "From init" and then clicked the button to set another font. However, the height of the userControl did not change, which is different from .Net Framework. Could you please explain why? Thank you.
![image](https://github.com/dotnet/winforms/assets/20555703/60c76389-86a0-4a7e-8620-c70ed055de18)

**Comment by Olina-Zhang** [comment]
> Could you please explain why?

Different font sizes, line spacing, and the length of the text content all affect how the text is displayed in the form, which in turn affects the height of the form. Did you try more fonts with different size? I tried some, it works well.

https://github.com/dotnet/winforms/assets/26474449/433763bc-f0ad-4f67-b590-ed6a2283a42a

**Comment by hyke123** [comment]
Yes, some fonts work well. I encountered some layout issues when our product migrated from .NET Framework to .NET 8. I believe I should conduct further investigation to provide more details for you. Thank you for your team's help.
