### ISSUE TITLE
Refactor `DisplayInformation` to use `BitVector32`

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#10825]
`DisplayInformation` has 9 fields which can be refactored into a `BitVector32` to reduce runtime memory usage.

**Comment by elachlan** [comment]
@JeremyKuhne `DisplayInformation.BitsPerPixel` is `short` but `Screen.BitsPerPixel` is `int`. Is this an issue? I imagine it won't get close to the `short.maxvalue`.

**Comment by JeremyKuhne** [comment]
@elachlan There is only one `DisplayInformation`, it doesn't make sense to add any complexity to this.

I believe the largest possible value is `48`.

**Comment by elachlan** [comment]
I'll avoid combining any static bools.
