### ISSUE TITLE
PropertyGrid: dropdown list is empty after expanding properties for the first time

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#1084]
•	.NET Core Version: .NET Core 3.0.100-preview6-012162 from master branch
•	Have you experienced this same bug with .NET Framework?: No

**More info:**

1.	The issue also can reproduce on the latest .NET Core 3.0.100-preview6-12226 from release branch.
2.	The issue can’t reproduce on the .NET Core 3.0.100-preview6-12101 build from master branch.
3.	The issue also can reproduce on the all controls which have the related “dropdown” property.

**Repro Steps:**
1.	Installed the latest .NET SDK 3.0 from: https://github.com/dotnet/core-sdk. 
2.	Build and run the attached application.
[ReproApplication.zip](https://github.com/dotnet/winforms/files/3246776/ReproApplication.zip)
3.	Click the Open button of the “BackColor” property using mouse。
![ReproSteps](https://user-images.githubusercontent.com/38325459/58791241-6dc3bd80-8624-11e9-8e68-af9af4607fe8.gif)

 **Actual behavior:**
The dropdown list of “BackColor” property is empty after first clicking.
![Issue](https://user-images.githubusercontent.com/38325459/58791171-4d93fe80-8624-11e9-9e9d-f694a13eb63c.PNG)

**Expected behavior:**
The dropdown list of “BackColor” property should not be empty and showed as following screenshot.
![ExpectedResults](https://user-images.githubusercontent.com/38325459/58790221-816e2480-8622-11e9-984a-6daab6aaf009.PNG)

**Comment by zsd4yr** [comment]
@Zheng-Li01 is this happening with ForeColor as well or only BackColor? Is this happening for the BackColor of many contols or just a few?

@M-Lipin and @vladimir-krestov do you think any of your recent accessibility work could have impacted this?

@hughbe I don't think you've touched any of this, but can you take a look at this as well to see if I'm mistaken?

**Comment by merriemcgaw** [comment]
@dreddy-work can you see if all of the color editor has been fully ported and if something else obvious needs to be done here? We're missing a lot of functionality.
Or, could this be a side effect of HPDI work that wasn't ported?

**Comment by Zheng-Li01** [comment]
@zsd4yr , the is not only happening with ForeColor, but also happening with BackColor, Dock etc. including  all controls which have the related “dropdown” property.

**Comment by Vino-Wang** [comment]
Verified with latest .NET Core 3.0 Preview 9 3.0.100.14004 build, it’s not reproduced for now.

**Comment by RussKie** [comment]
Awesome! Thank you
