### ISSUE TITLE
Drag/drop Not Working with External Items When Trimming On

### ISSUE THREAD

**Issue by lonitra** [dotnet/winforms#10853]
Drag/drop external items does not work when trimming is turned on. We are expecting the managed object we get on [DropTarget.PrepareOutgoingDropData](https://github.com/dotnet/winforms/blob/f7d1be6c8af5445fe9ad041ad2f8f62ddc4a8ece/src/System.Windows.Forms/src/System/Windows/Forms/OLE/DropTarget.cs#L56) to be either a `System.Windows.Forms.IDataObject` or `System.Runtime.InteropServices.ComTypes.IDataObject`, but the object we get back is neither of these. This is because the object is not a ComWrappers created object and built in com interop is not supported, so we are not getting that automatic wrapping that built in com provides. We need to be wrapping the COM object ourselves.

Repro:
1. Navigate to winforms TrimTest project
2. Edit the .csproj to turn on trimming:
```.csproj
<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PublishTrimmed>true</PublishTrimmed>
    <ImplicitUsings>true</ImplicitUsings>
    <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
  </PropertyGroup>
</Project>
```
3. Run 'dotnet publish' in command line where TrimTest lives
4. Run published TrimTest and drag a string from somewhere external onto the TextBox
5. Observe being unable to drop

**Comment by John-Qiao** [comment]
Verified this issue in the latest .Net 9.0 SDK build: 9.0.100-preview.2.24116.21, it was fixed that we can drag and drop a string from external onto the TextBox now.


https://github.com/dotnet/winforms/assets/45864985/a5d986f6-a977-4787-9f33-81f75b6cfdd4

**Comment by MandiMan** [comment]
Verified this issue with .NET 9 Preview 2 test pass build, it was fixed. Test result is same as above.
