### ISSUE TITLE
Moving multiple contrlols moves nested controls faster?

### ISSUE THREAD

**Issue by janseris** [dotnet/winforms#10852]
### Environment

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.8.5

### .NET version

.NET 8

### Did this work in a previous version of Visual Studio and/or previous .NET release?

I've been developing in .NET Framework for 4 last years and this never happened.
I switched to .NET 8 only because this is a small sample project. 
Otherwise I still use .NET Framework WinForms even for new projects because of fast and no lag designer with DevExpress WinForms controls.

### Issue description

See video

https://github.com/dotnet/winforms/assets/64279914/6299b40c-a6f7-4beb-b159-c288af19df0a

Expected behavior: all controls move in the same speed

### Steps to reproduce

Place some items and move them using keyboard
Using only vanilla WinForms controls.

**Comment by Zheng-Li01** [comment]
There have the same behavior between .NET and .NET Framework when selected all controls which are contained in the container, see below screenshot.
![GH10852](https://github.com/dotnet/winforms/assets/38325459/852e7a73-16ff-4420-b55f-1215961f6ada)

**Comment by JeremyKuhne** [comment]
@Tanya-Solyanik can you confirm whether or not this is a change in behavior?

**Comment by Tanya-Solyanik** [comment]
Confirmed that behavior when moving controls with the keyboard arrows is the same for both designers.

**Comment by merriemcgaw** [comment]
Thanks for filing this @janseris! Given that it's not a behavior change from the in-process .NET Framework designer and it isn't something specifically on our roadmap, I'm going to close this issue. One way I can recommend is for you to report this via VS Feedback / Developer Community as a suggestion. If you do that, other developers can add their votes +1's to the ticket. With enough votes on a Developer Community ticket we would certainly consider how to get it on our VS backlog.
