### ISSUE TITLE
Illegal single file warning suppression

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/winforms#10868]
Noticed this because a PR was touching lines close by:

https://github.com/dotnet/winforms/blob/e13647da8f159e329100697189992282640561a4/src/System.Windows.Forms/src/System/Resources/AssemblyNamesTypeResolutionService.cs#L62-L68

This UnconditionalSuppressMessage is illegal. Accessing `.CodeBase` will throw in single file and the throw is not handled. Author of the suppression might have confused `.CodeBase` with `.Location` (that returns an empty string or null, can't remember which one, but does not throw in single file).

There are  other instances of illegal suppressions for this (I only did a cursory GitHub search so this might not be exhaustive):

https://github.com/dotnet/winforms/blob/e13647da8f159e329100697189992282640561a4/src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs#L447

**Comment by elachlan** [comment]
Related #7308

**Comment by elachlan** [comment]
@Tanya-Solyanik, you talked about 'AssemblyName.CodeBase' in the linked issue around Toolbox scenarios.

**Comment by Tanya-Solyanik** [comment]
Thank you, @MichalStrehovsky , but comment in source says that CodeBase returns an empty string - https://github.com/dotnet/runtime/blob/4765dd1b9f1aa58f16d6922438bcc6cb01b4a666/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs#L86-#L105
```
 [Obsolete(Obsoletions.AssemblyNameCodeBaseMessage, DiagnosticId = Obsoletions.AssemblyNameCodeBaseDiagId, UrlFormat = Obsoletions.SharedUrlFormat)]
        public string? CodeBase
        {
            [RequiresAssemblyFiles("The code will return an empty string for assemblies embedded in a single-file app")]
            get => _codeBase;
```

**Comment by MichalStrehovsky** [comment]
Sorry for the confusion. I saw `CodeBase` and assumed `Assembly.CodeBase`. Looks like `AssemblyName.CodeBase` returns null whereas `Assembly.CodeBase` throws. Doesn't make much sense, but that's not an issue for the WinForms repo.

**Comment by Tanya-Solyanik** [comment]
@MichalStrehovsky  - Thank you!
