### ISSUE TITLE
Web Browser control object creation give me error when application in multi threaded mode

### ISSUE THREAD

**Issue by shishiraltysys** [dotnet/winforms#10870]
### .NET version

.net 7

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Not sure about it

### Issue description

![image](https://github.com/dotnet/winforms/assets/137883104/bfedea78-8ddd-415a-9002-9df25bbeaa72)

If I was creating object inside separate single thread mode, but after creating these object i need to add these control in another window control i.e. (Spilite Container) panel.

### Steps to reproduce

I have 2 thread when open any form, one is main thread that basically a communication thread a Pipe communication and then UI thread responsible for UI forms. Please help me. If you need anything please let me know

**Comment by AArnott** [comment]
@shishiraltysys Please do not mention github user accounts that you don't personally know or that don't work on the repo you're on. I for one do not work on winforms, and I know at least some others you mentioned don't either. It just creates noise for us and there's really nothing we can do to help you here.

**Comment by lonitra** [comment]
@shishiraltysys Can you provide more detailed repro steps so we can understand the scenario a bit more? Ideally a sample project would be helpful here that shows it was working in Framework then moving to .NET 7 it no longer works.
