### ISSUE TITLE
Input of thousand separators are accepted in NumericUpdown components even if ThousandsSeparator is false

### ISSUE THREAD

**Issue by AndersBillLinden** [dotnet/winforms#10908]
### .NET version

8.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

no

### Issue description

We got a bug report about a user entering a comma in a NumericUpDownExt like: 

2,54651

and believed the comma was a decimal separator.

What he/she did not anticipate is that the current locale treats comma (,) as thousand separators.
What he/she should really input would be a period (.).

When the component was blurred, it correctly changed its text to

254651.000

But upon investigation, it turned out that ThousandsSeparator was false for the control.

Would it be possible to not accept the input of the thousand separator if those are turned off anyway?

That would cease the confusion (which led to the bug report).

### Steps to reproduce

Add a NumericUpdown in your form.
Set NumericUpDown.Maximum to a value larger than a thousand
Be sure ThousandsSeparator is false.
You will still be able to enter the thousand separator character.

**Comment by elachlan** [comment]
@AndersBillLinden This might have to be put under an AppContext switch because its a behavior change from .net framework and could break existing applications. That is unless .net framework behavior is different for cultures using "," as a decimal.

What Locale was the user using? Could you provide the `CultureInfo.CurrentUICulture`/CultureInfo.CurrentCulture`?

@Olina-Zhang can you test with a culture with different a decimal point? I can reproduce on my culture, but comma is the thousands separator for it.

**Comment by Zheng-Li01** [comment]
verified the issue on the local machines(fr-fr, de-de, es-es), which are have the same results as ENU languages.
![image](https://github.com/dotnet/winforms/assets/38325459/068948a2-9b43-4553-9bb2-1a6004fe1341)
For  .NET Framework project, the current locale treats period (.) as thousand separators.
![Framework](https://github.com/dotnet/winforms/assets/38325459/70dfdef3-cbab-43e7-bd2d-db47fbe96736)

For .NET project, the current locale treats comma (,) as thousand separators.
![Core](https://github.com/dotnet/winforms/assets/38325459/0e356d12-2506-45ad-b55c-5ddcf5354785)

**Comment by AndersBillLinden** [comment]
![NumericUpDownExt](https://github.com/dotnet/winforms/assets/1017466/51205c88-ece7-41b3-9077-7b3c71992bfa)

**Comment by AndersBillLinden** [comment]
The confusion arised when a swedish consultant of ours was running the application with an english culture and never understood why it behaved like it did.

**Comment by Tanya-Solyanik** [comment]
@Zheng-Li01  - did you test NET8 or NET9?
It sounds like .NET Framework ignores language preferences from the OS settings, and .NET9 displays thousands separator as preferred in the settings. But when ThousandsSeparator is set to false, users could be confused by the result as they might not know what the input locale settings are.

**Comment by Zheng-Li01** [comment]
@Tanya-Solyanik, verified the issue from .NET 6.0 ~ 9.0, which all have the same results that the current locale treats comma (,) as thousand separators.

**Comment by AndersBillLinden** [comment]
@Zheng-Li01 You are showing the difference when ThousandsSeparator is true vs false but it does not seem that you confirm the issue. The issue is that the component accepts the character for thousands separator regardless of the ThousandsSeparator flag.

**Comment by Tanya-Solyanik** [comment]
@AndersBillLinden  - I think the problem is that the control ignores the comma(because it's not a decimal separator) looks for a period, does not find it, and treats all numbers as being to the left of the decimal point.

**Comment by merriemcgaw** [comment]
We should consider adding a quirk so that apps migrating from .NET Framework are allowed to go back to the older behavior and not cause user confusion.

**Comment by AndersBillLinden** [comment]
I would prefer to never see this mistakenly inputted comma.

![one_comma_too_much](https://github.com/dotnet/winforms/assets/1017466/114f64dd-409d-4964-a4ae-0bdd04aca210)

**Comment by elachlan** [comment]
@AndersBillLinden Do you have the time to write a PR to fix this?

**Comment by AndersBillLinden** [comment]
It will rather be the end user getting confused. The software developer is not part of a work around. Are you sure you got the correct details when you came to the conclusion to not fix it?

**Comment by RussKie** [comment]
How does the underlying MFC control behave?
