### ISSUE TITLE
no unicode characters with Application.SetCompatibleTextRenderingDefault(True)

### ISSUE THREAD

**Issue by VaporiZed** [dotnet/winforms#10909]
### .NET version

7.0

### Did it work in .NET Framework?

No

### Issue description

The usage of `Application.SetCompatibleTextRenderingDefault(True)` leads to a wrong presentation of unicode characters.

### Steps to reproduce

- put a button on the form and add a unicode character like a magnifying glass 🔍 to the text of the button
- deactivate the application framework in the project properties
- create a module with an own Sub Main
- set the start object to the module or the Sub Main
- use the following code in the Sub Main:
```
Application.SetCompatibleTextRenderingDefault(True)
Application.EnableVisualStyles()
Application.Run(New YourMainForm)
```
- run the app

expectation: the magnifying glass will be shown as it is intended
fact: a placeholder/rectangle is shown instead

![Result](https://github.com/dotnet/winforms/assets/49878115/adc57ffe-55d0-4e04-8bed-5d7cb9258e50)

[WinFormsNetVB.zip](https://github.com/dotnet/winforms/files/14337379/WinFormsNetVB.zip)

**Comment by elachlan** [comment]
@VaporiZed are you able to not use Compatible Text Rendering? or does that cause more problems?

**Comment by elachlan** [comment]
@JeremyKuhne is this just a symptom of GDI+ text rendering?

**Comment by elachlan** [comment]
Related: #10740

**Comment by VaporiZed** [comment]
@elachlan With `Application.SetCompatibleTextRenderingDefault(False)` it works as expected: The unicode character will be shown as assumed.
(This is my first issue report in GitHub, so I'll know for the future, that I mention the scenario, where it works - if so.)

**Comment by merriemcgaw** [comment]
Thank you for filing this - @elachlan is right, it's very related to #10740 that @KlausLoeffelmann is investigating. We'll keep this open and have it as part of hte collection of issues we want to investigate. I can't promise .NET 9 for sure, given other priorities, but we are definitely planning on a deeper investigation in this space.

**Comment by JeremyKuhne** [comment]
@VaporiZed There isn't much we can do here, the whole point of `Application.SetCompatibleTextRenderingDefault(true)` is to use GDI+ to render as was done in versions of WinForms prior to .NET Framework 2.0. GDI+ text rendering does not have the level of support that more modern APIs do, if we changed behavior here it would no longer render the way it did before.

One really shouldn't enable compatible text rendering unless it is absolutely necessary. If there is some other behavior you're trying to take advantage with enabling this legacy compatibility feature, please let us know.

**Comment by JeremyKuhne** [comment]
Regarding @merriemcgaw's comments: We're looking at providing even better rendering for text for some scenarios, but we would never apply this to the compatible mode as it would change the way text looks. The things we're looking at likely wouldn't even be applied to existing controls without some sort of opt-in parameter, if at all. With all of the extension points in control painting, drawing with Direct2D (DirectWrite for text) is not a trivial thing to accomplish on existing controls as it would break current patterns.
