### ISSUE TITLE
ActiveControl property change To null when control placed in ContainerControl

### ISSUE THREAD

**Issue by GCAronChen** [dotnet/winforms#10912]
### .NET version

8.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

When placed a control in ActiveMdiChild form, click other control out of current mdi form.
`this.ActiveMdiChild.ActiveControl` will be kept and not change to null.
![image](https://github.com/dotnet/winforms/assets/96418485/5ea20a9a-6f5c-44f9-9594-2c58d5fa3111)
![image](https://github.com/dotnet/winforms/assets/96418485/c4c08c39-931d-4a26-9335-9d74f2c54798)
![image](https://github.com/dotnet/winforms/assets/96418485/6a742303-a815-46a8-b809-ce17d9ceeddb)

But when this control is added in container control, click other control out of current mdi form.
`this.ActiveMdiChild.ActiveControl` will be changed to null.
![image](https://github.com/dotnet/winforms/assets/96418485/2caee897-e949-4ea6-a91b-49bd127f68fe)
![image](https://github.com/dotnet/winforms/assets/96418485/02bc5ff2-bffe-43b7-94a9-872420122162)
![image](https://github.com/dotnet/winforms/assets/96418485/96e4989d-6f5b-4517-adf3-0512e53dda33)

Is this a bug?

### Steps to reproduce

Unzip attachment, open "TestActiveControl.sln"

1. Run project "TestActiveControl.csproj"
2. Click the first TextBox, then click button
3. Check TextBox output which represents mid child active control, it's kept
4. Click the second TextBox, then click button
5. Check TextBox output which represents mid child active control, it's changed to null. Only difference is the second TextBox placed in container control

attachment: [TestActiveControl.zip](https://github.com/dotnet/winforms/files/14340302/TestActiveControl.zip)

**Comment by merriemcgaw** [comment]
Thank you for this suggestion, however changing the behavior here we fear would be too breaking of a change. This has been the consistent behavior in the WinForms implementation of MDI children, and if we change it we're concerned that existing applications would suffer breaks.

**Comment by GCAronChen** [comment]
@merriemcgaw Thanks, so it 's a by design right?

**Comment by merriemcgaw** [comment]
@GCAronChen correct.
