### ISSUE TITLE
Review and update THIRD-PARTY-NOTICES.TXT for 3.0

### ISSUE THREAD

**Issue by leecow** [dotnet/winforms#1092]
Review and update repo THIRD-PARTY-NOTICES.TXT as appropriate. Work should be completed for Preview 7.

**Comment by merriemcgaw** [comment]
@leecow can you give us the correct third party notices file to confirm ours is correct?

**Comment by leecow** [comment]
Working on this on another thread with Richard, who originally created the files. Shooting to have an update on this next week.

**Comment by merriemcgaw** [comment]
gentle ping @leecow 😊

**Comment by leecow** [comment]
I've heard rumor of tooling that is supposed to handle this. Closing this issue.

**Comment by weltkante** [comment]
closing issues on rumors before verification that it actually will happen? 😄
