### ISSUE TITLE
The DialogResult of PrintDialog is not correct when setting its UseEXDialog is false and clicking Cancel for dialog

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#10920]
### .NET version

.NET 9.0 SDK build: 9.0.100-preview.2.24116.21

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro previous version: .NET 8.0 SDK build

### Issue description

When setting PrintDialog's UseEXDialog is false and clicking Cancel button for this dialog, the value of DialogResult is OK, not Cancel.

.NET 9.0 Result:

https://github.com/dotnet/winforms/assets/26474449/106af37e-b263-4c70-9970-e216ed183977

.Net 8.0 Result:

https://github.com/dotnet/winforms/assets/26474449/6d69aa7f-b0f1-439b-ae0c-95fbaf136720

### Steps to reproduce

1. Create a Winforms application with a button, textBox and a PrintDialog
2. Double-click button and add following code:
 ```
private void button1_Click(object sender, EventArgs e)
 {
     DialogResult result;

     printDialog1.UseEXDialog = false;
     result = printDialog1.ShowDialog();
     
     textBox1.Text = result.ToString();  
 }
```
or use this sample application: 
[PrintDialogSample.zip](https://github.com/dotnet/winforms/files/14354573/PrintDialogSample.zip)

**Comment by elachlan** [comment]
We can integration test this now. I'll have a look when I have some time.

**Comment by MandiMan** [comment]
Verified this issue in the latest .Net 9.0 SDK build: 9.0.100-preview.3.24128.12, it was fixed. When click Cancel button of this dialog, the value of DialogResult is Cancel. 

https://github.com/dotnet/winforms/assets/108860782/7f8207cb-8582-49ea-a656-08c4a4c2bbdc

**Comment by John-Qiao** [comment]
Verified this issue with .NET 9 Preview 2 test pass build, it was fixed. Test result is same as above.

**Comment by Zheng-Li01** [comment]
Verified this issue with 9.0.0-preview.3.24175.24 test pass build, it was fixed. Test result is same as above.
