### ISSUE TITLE
why are there unsupported target framework options?

### ISSUE THREAD

**Issue by Varorbc** [dotnet/winforms#10938]
https://github.com/dotnet/winforms/blob/b4c9c031e5451208ac12ad2b21ed3196a5c100e6/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json#L32-L41

**Comment by KlausLoeffelmann** [comment]
We still can create V3.1 .NET Core Apps or Libraries, can we not?

![image](https://github.com/dotnet/winforms/assets/9663150/9c73b291-9dcb-49b3-8473-2df4a6d4ff8f)

Why should that be different for WinForms?

**Comment by merriemcgaw** [comment]
I think I'm with @JeremyKuhne here. This is something we should get in the release checklist. @lonitra is adding to our internal docs. @LeafShi1 can your teaam pick up the quick change?

**Comment by LeafShi1** [comment]
@Varorbc  I tried to create other projects, like Asp.net core, unit project,. Their Target options are consistent with Winform, and my SDK version is the latest.
![image](https://github.com/dotnet/winforms/assets/132890443/6bcb470a-cab7-4c45-8b39-c22df0afa448)

The target framework options here depend on whether these .net versions are installed in my VS installer.
After installing .net 5.0, create the Asp.net core project, the result is as shown below
![image](https://github.com/dotnet/winforms/assets/132890443/e25ccce0-3cf2-40e8-8134-d3b1e90ee4a1)

Please correct me if I misunderstood what you meant.

**Comment by Tanya-Solyanik** [comment]
Back to triage - are we sure we don't want to let developers create NET5 app even when NET5 SDK is installed? see investigation here - https://github.com/dotnet/winforms/pull/10971#issuecomment-1975890098

**Comment by KlausLoeffelmann** [comment]
We need to make sure, that developer can still target unsupported Frameworks, for sure.

**Comment by MelonWang1** [comment]
@Tanya-Solyanik Verified this issue on .NET 9.0.100-preview.3.24165.20 with dlls built from winforms repo of main branch, behavior as below. **Please help me confirm that the following behavior is as expected?** Will verified this issue again when the PR https://github.com/dotnet/winforms/pull/11051 inserted in SDK.
1.  The .net core 3.1 and .net 5.0 no longer show up in Framework option even though I installed these two components.
![1](https://github.com/dotnet/winforms/assets/94418985/414ffcf8-d134-4921-99c4-7fa01ff1c77a)

But in cmd, still displays .net core 3.1 and .net 5.0. Can create/build/run/debug .net 5.0 app successfully in VS.
![1-2](https://github.com/dotnet/winforms/assets/94418985/cf71abe6-3c41-4151-a4e4-cecfa0a9c84c)


2. The components not install .net 6.0, control panel not install .net 6.0, the .net 6.0 not display in Framework option.
![2](https://github.com/dotnet/winforms/assets/94418985/217b0205-88af-4087-a17c-95b7c2a25264)

Can create .net 6.0 app successfully, but cannot run in VS.
![2-2](https://github.com/dotnet/winforms/assets/94418985/1e999adf-017e-478c-86b2-c715bb37557f)
![2-3](https://github.com/dotnet/winforms/assets/94418985/7321566b-9778-4603-825a-5ab7527a5a5c)

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - I thought that scenario #1 from Melon's image above, worked correctly for you, do we need the second PR for that? 

@MelonWang1  - yes, please verify again after the second PR gets in. But that should not affect scenario #2. I the second scenario, when you build from the CLI(dotnet build/dotnet run) a NET6 application, what message do you get? If it's a descriptive message, as we get in the VS case, then the overall experience is reasonable.

@merriemcgaw  - I think this is an ok experience 
- NET6 is not installed, NET9 is installed, 
- NET6 application can be created from the CLI (bad), but can't be created in the VS(good)
- When building in the VS, the dev gets a message with the install link - they are unblocked.

**Comment by MelonWang1** [comment]
@Tanya-Solyanik In scenario #2, the components not install .net 6.0, control panel not install .net 6.0, the .net 6.0 not display in Framework option. Can create/build .net 6.0 app successfully by CLI, cannot run.
![Untitled](https://github.com/dotnet/winforms/assets/94418985/5612d260-703d-404f-819b-30333e197e06)

**Comment by Tanya-Solyanik** [comment]
Thank you, @MelonWang1 , this is a reasonable error message, it explains how to get unblocked.

**Comment by LeafShi1** [comment]
> @LeafShi1 - I thought that scenario #1 from Melon's image above, worked correctly for you, do we need the second PR for that?

There is currently no content about netcoreapp3.1 and net5.0 in the repo.
I previously verified myself by following the steps in [readme.md](https://github.com/dotnet/winforms/blob/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/readme.md), the netcoreapp3.1 and net5.0 disappeared after executing `dotnet new -i Q:\source\Folk-winforms\pkg\Microsoft.Dotnet.WinForms.ProjectTemplates\content\WinFormsApplication-CSharp `.
But the latest VS does still contain these two options, which is strange.

**Comment by Tanya-Solyanik** [comment]
@MelonWang1 @Leaf, we discussed these scenarios with the team, this is OK.

**Comment by MelonWang1** [comment]
@Tanya-Solyanik Verified this issue in the latest .NET 9.0 SDK build: 9.0.100-preview.4.24175.11, it contains PR #11051 fixed, test result is same as above.

**Comment by John-Qiao** [comment]
Verified this issue with 9.0.0-preview.3.24175.24 test pass build. Test result is same as above.
