### ISSUE TITLE
The tablelayoutpanel's cloumn2 and datagridview wasn't deleted when drag the DataGridView control to the TableLayoutPanel control and click "Remove Last Column" in the DemoConsole application

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#10931]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, the DataGridView control start support from 9.0.

### Issue description

The tablelayoutpanel's cloumn2 and datagridview wasn't deleted when drag the DataGridView control to the TableLayoutPanel control and click "Remove Last Column" in the DemoConsole application.

https://github.com/dotnet/winforms/assets/94418985/57fc58ed-9226-4b29-9255-6e6fd87d5460

**Expected result:**
After step 5: The tablelayoutpanel's cloumn2 and datagridview was deleted.

https://github.com/dotnet/winforms/assets/94418985/012b6e03-129d-4767-8e21-7b09daa708b4

### Steps to reproduce

1. Run test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo
2. Switch to "TabControl and TableLayoutPanel" tabpage
3. Drag the DataGridView control to the second row and column of the TableLayoutPanel control
4. Select TableLayoutPanel control 
5. Click "Remove Last Column" in smarttag or property commands window(An warning popup "Designer is not initialized")
6. Click "Remove Last Column" again(An warning popup "Designer is not initialized" and DataGridView's cloumn1 was deleted)
7. Select another control and then select TableLayoutPanel control(TableLayoutPanel's row1 was deleted )

**Comment by Zheng-Li01** [comment]
The issue maybe be caused that the DataGridView control cannot be deleted successfully as below GIF, please have a confirm.
 
![10931](https://github.com/dotnet/winforms/assets/38325459/d0fc07b9-24ce-45e9-ac4d-376adc38fd23)

**Comment by merriemcgaw** [comment]
Great find! This is not a common customer scenario, so we're not going to prioritize it at the moment. We'll close the issue, but be sure to reactivate if we get any feedback from customers that this is a problem in their custom designer experience
