### ISSUE TITLE
ComboBox: disabled text color is not contrasting enough with the selection background color

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#10993]
### .NET version

.Net 9.0 SDK: 9.0.100-preview.3.24128.12

### Did it work in .NET Framework?

No
It is working on Windows server 2016 

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

It is not a regression issue, can repro in .Net framework 3.5 to .Net framework 4.8.1 and .Net versions

For ComboBox: disabled text color is not contrasting enough with the selection background color as following screenshot:
![image](https://github.com/dotnet/winforms/assets/26474449/279dab0b-37c6-4555-b2b6-eb45042d10b7)

### Steps to reproduce

1. Create a Winforms .Net application with ComboBox added
2. Set ComboBox's Text property and write some code to disable it and select its Text:
```
comboBox1.SelectionStart = 0;
comboBox1.SelectionLength = comboBox1.Text.Length;
comboBox1.Enabled = false;
```
3. Build and run to observe the ComboBox's Text

Testing sample: 
[ComboBoxSample.zip](https://github.com/dotnet/winforms/files/14492730/ComboBoxSample.zip)

**Comment by Tanya-Solyanik** [comment]
This is a ComCtl bug according to control spy - https://www.microsoft.com/en-us/download/details.aspx?id=4635
![image](https://github.com/dotnet/winforms/assets/15823268/acedc46a-6c95-4ed7-8884-e49078f3c3f4)

CBS_DROPDOWN | CBS_HASSTRINGS | WS_CHILD | WS_DISABLED | WS_OVERLAPPED | WS_VISIBLE

**Comment by merriemcgaw** [comment]
It looks like CommonControls is painting this scenario. It looks like we should be able to set the forecolor. I am going to close this for now unless we hear lots of feedback from customers, and then we'd consider setting the forecolor ourselves. Most situations customers should be able to work around it if this is important to them.
