### ISSUE TITLE
FolderBrowserDialog Allow VirtualFolders through property similar to ShowPinnedPlaces 

### ISSUE THREAD

**Issue by rameshbsupekar** [dotnet/winforms#11001]
### Background and motivation
Regrding FolderBrowserDialog 
For already existing cloud sync engine applications using shell namespace will it be possible to show virtual folders or is there alternative workaround for this?
Is it possible to add property similar to ShowPinnedPlaces for VirtualFolders so developer can choose to show or hide.
In net framework 4.8 FolderBrowserDialog  virtual foders shown but there is no ShowPinnedPlaces.

### API Proposal

```csharp
namespace System.Windows.Forms;

public sealed class FolderBrowserDialog : CommonDialog
{
   public bool ShowVirtualFolders
    {
        get => !GetOption(FOS_HIDESHELLNAMESPACES_VirtualFolders); // I don't know if such winapi available
        set => SetOption((FOS_HIDESHELLNAMESPACES_VirtualFolders, !value); // I don't know if such winapi available
    }
}
```

### API Usage

```csharp
           var dlg = new System.Windows.Forms.FolderBrowserDialog();
            dlg.ShowVirtualFolders = true;
```

### Will this feature affect UI controls?

FolderBrowserDialog will get affected

**Comment by elachlan** [comment]
@lonitra this looks like a well formed API Proposal. Can we move it to "api ready to review"?

**Comment by elachlan** [comment]
@rameshbsupekar can you please link the WinAPI documentation for the flag?

**Comment by rameshbsupekar** [comment]
sorry for confusion I missed adding comment  I don't know if such winapi available any reference where I can check this

**Comment by JeremyKuhne** [comment]
@rameshbsupekar we changed the default dialog to be the modern (Windows Vista+) one in Core. If you want the old one you need to set AutoUpgradeEnabled to false. I don't think there is a way we can make things look the old way with the new dialog.
