### ISSUE TITLE
DataGridView appearance changed in net8.0

### ISSUE THREAD

**Issue by ahdung** [dotnet/winforms#11032]
### .NET version

C:\Users\Administrator>dotnet --info
.NET SDK:
 Version:           8.0.102
 Commit:            64f1bc458e
 Workload version:  8.0.100-manifests.8a11730e

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.102\

已安装 .NET 工作负载:
 Workload version: 8.0.100-manifests.8a11730e
没有要显示的已安装工作负载。

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

C:\Users\Administrator>

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, work well in `net6.0-windows`.

### Issue description

DataGridView appearance changed in net8.0-windows, change to ugly:
header border style is `Raised` (default).
![微信截图_20240312164606](https://github.com/dotnet/winforms/assets/12094247/a28a7dd4-ee5c-4c66-a291-3d4dc48baf52)

### Steps to reproduce

not need.

**Comment by merriemcgaw** [comment]
@elachlan yes, this is done by design for accessibility contrast issues. Good call!

**Comment by ahdung** [comment]
@merriemcgaw Stupid changing. No one normal anymore:
![image](https://github.com/dotnet/winforms/assets/12094247/3bb920db-0e8f-4c96-8f7d-e76adb8bacad)

**Comment by elachlan** [comment]
@ahdung Microsoft has a tool used to assess Accessibility of applications (for people with vision problems such a colorblindness) called "Accessibility tools for Windows". The tool has codified best practices on different UI guidelines for compliance. This change was made to make it compliant.

**Comment by ahdung** [comment]
@elachlan Thanks your explain. For people with vision problem, it's fine, but is it okay to leave a normal choice for normal people?
