### ISSUE TITLE
Pasting from clipboard to MultilineStringEditorUI does not work

### ISSUE THREAD

**Issue by StuYarrow** [dotnet/winforms#11084]
### .NET version

8.0

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Not tested.

### Issue description

Pasting text from the clipboard into `MultilineStringEditorUI` does not work.  Copy and cut work as they should.

### Steps to reproduce

1. Build and run the [MWA](https://github.com/StuYarrow/MultilineStringEditor.Paste.MWA).
2. Select the text in the TextBox (or any other text).
3. Open the editor for the `MyString` property in the PropertyGrid.
4. Click on the dropdown editor UI to position the cursor.
5. Hit ctrl-v.

Expected result: text is pasted into to the editor.

Actual result: nothing happens.

**Comment by elachlan** [comment]
@StuYarrow Winforms does not have a `MultilineStringEditorUI` control. Is that one of your own?

@Olina-Zhang can your team please test?

**Comment by Zheng-Li01** [comment]
This is a regression issue, cannot reproduce form .NET 3.1 to .NET 7.0, can reproduce it on .NET 8.0 & 9.0 that cannot paste the TEXT to dropdown editor.
**Expected7.0:**
![Expected70](https://github.com/dotnet/winforms/assets/38325459/2c40609a-fe1a-45bb-82fa-e8dd55929f60)

**Actual 8.0/9.0**
![Actual](https://github.com/dotnet/winforms/assets/38325459/f68c64b0-f7c5-4683-b8a2-c1fc5cad40dd)

**Comment by StuYarrow** [comment]
@elachlan `MultilineStringEditorUI` is a WinForms class.  It is nested inside `MultilineStringEditor` and is a subclass of `RichTextBox`.

**Comment by elachlan** [comment]
Thanks! Sorry about that.

**Comment by Olina-Zhang** [comment]
Verified it in the latest .Net 9.0 SDK build: 9.0.100-preview.4.24177.8, it was fixed: pasting texts in MultilineStringEditorUI works well.

https://github.com/dotnet/winforms/assets/26474449/0e89e339-c207-45dd-b553-ae39874c1cbe

**Comment by John-Qiao** [comment]
Verified issue on 8.0.300-preview.24203.14 with dlls built from Release/8.0 branch of Winforms repo, the issue was fixed, test result is same as above.

**Comment by John-Qiao** [comment]
Verified with .NET SDK 8.0.5 test pass build, this issue was fixed. Test result is same as above.

**Comment by MelonWang1** [comment]
Verified this issue with 9.0.100-preview.4.24253.11 test pass build, it was fixed. Test result is same as above.
