### ISSUE TITLE
NRE In Unmanaged Code When Pressing Keys In TreeView

### ISSUE THREAD

**Issue by stumper66** [dotnet/winforms#11083]
### .NET version

.Net 8.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

My project started in .Net Framework 4.x. I eventually migrated to .Net Core 3.1, then 5.0, 6.0, 7.0 and finally 8.0.
I can't remember exactly when this issue started but it might've been with .net core 3.1.

### Issue description

I have a TreeView control. I also have various keyboard shortcuts which are handled by a MenuStrip.
I've discovered that randomly when I'm using the arrow keys to move around inside the TreeView control, I will get an exception that doesn't contain any user code at all so I'm unable to handle it.
I've found the exact error spot in the source code and even made my own fork that handles the error graceful with one simple line change.
It appears to be attempting to send a ToolTip to the form despite me not having any ToolTips.

Error line in source: https://github.com/dotnet/winforms/blob/release/8.0/src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs#L1576
In the source it is calling `tool.GetOwnerWindow()` however this returns a null value and the code seems to be expecting a non-null value.

### Steps to reproduce

I've been unable to reproduce this error in a brand new project. It only occurs on my mature project that originally started out in .Net Framework 4.x.
![Net Issue](https://github.com/dotnet/winforms/assets/18266662/20a5fef7-21d5-45aa-b1f8-640afecf3259)

**Comment by stumper66** [comment]
Full callstack:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.GetSafeHandle(IWin32Window window)
   at System.Windows.Forms.ToolTip.TryGetBubbleSize(IKeyboardToolTip tool, Size& bubbleSize)
   at System.Windows.Forms.ToolTip.ShowKeyboardToolTip(String text, IKeyboardToolTip tool, Int32 duration)
   at System.Windows.Forms.KeyboardToolTipStateMachine.ShowToolTip(IKeyboardToolTip tool, ToolTip toolTip)
   at System.Windows.Forms.KeyboardToolTipStateMachine.Transition(IKeyboardToolTip tool, ToolTip tooltip, SmEvent event)
   at System.Windows.Forms.KeyboardToolTipStateMachine.Transit(SmEvent event, IKeyboardToolTip source)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
   at Windows.Win32.PInvoke.DispatchMessage(MSG* lpMsg)
   at System.Windows.Forms.Application.ComponentManager.Microsoft.Office.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at ManageVMs_Core.Program.Main() in C:\Users\buffalo\Documents\Visual Studio 2022\Projects\ManageVMs_Core\ManageVMs_Core\Program.cs:line 29

  This exception was originally thrown at this call stack:
    [External Code]
    ManageVMs_Core.Program.Main() in Program.cs

**Comment by stumper66** [comment]
Here is my fix for it: https://github.com/stumper66/winforms/commit/ae5cd93563c726d24f4d6ccc92aed9db2c9b375b

**Comment by elachlan** [comment]
@stumper66 did you want to submit a PR and provide a test?

@Olina-Zhang Is your team able to reproduce this issue in the test project?

**Comment by stumper66** [comment]
@elachlan I already submitted a PR.
I've been unable to provide a test but I fixed the problem with my own locallly built System.Windows.Forms.dll with the submitted PR: https://github.com/stumper66/winforms/commit/ae5cd93563c726d24f4d6ccc92aed9db2c9b375b

**Comment by stumper66** [comment]
@elachlan  Here is the PR: https://github.com/dotnet/winforms/pull/11092

**Comment by elachlan** [comment]
I think it might be prudent to investigate what kind of tooltip its trying to show and what triggers it?

**Comment by stumper66** [comment]
It is coming from the TreeView itself but I can't seem to stop it. I have not defined any tool tips defined.
When I added debugging inside the function, here is one of the values I logged as I was pressing on the keys.

```
03/19/2024 17:14:50.838  inside TryGetBubbleSize, tool: DataGridViewTextBoxCell { ColumnIndex=0, RowIndex=-1 }
```

**Comment by elachlan** [comment]
@stumper66 could you debug the WinformsControlsTest project and try to reproduce it there? Maybe set a breakpoint and look at the call stack to see what causes the tooltip to be triggered?

**Comment by stumper66** [comment]
There is possibly a trigger for the toolip that shouldn't be there but if you look at my PR it's making a change that should've been there to begin with. It's getting passed a nullable value then assuming it is not null.
By checking if it's not null first it fails the ghost tooltip gracefully.

Since the tooltip is not triggered by any user code it is very hard to pin down. I've been dealing with this bug for years hoping each new .net version would fix it.

**Comment by Olina-Zhang** [comment]
It is a similar with GH issue: https://github.com/dotnet/winforms/issues/7262 with same CallStack, but we cannot reproduce for our created application. Hopefully a repro application provided.

**Comment by merriemcgaw** [comment]
Can we change this PR to .NET 9 main, and we will need to be the ones to cherry-pick it ourselves to take it in servicing. @Tanya-Solyanik to drive this through shiproom and follow the fix.

**Comment by stumper66** [comment]
I've created a new PR targetting main branch.
https://github.com/dotnet/winforms/pull/11134
