### ISSUE TITLE
TextBox.Text accessed when handle is not being created

### ISSUE THREAD

**Issue by madewokherd** [dotnet/winforms#1109]
* .NET Core Version: N/A

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

Due to the addition of the PlaceholderText attribute, the virtual TextBox.Text property is read when handling WM_PAINT.  VMWare infrastructure client, which was designed for .NET 4.x, expects that TextBox.Text is read only when creating the handle for the control. When running with current winforms, this application throws an exception.

Ref: https://bugs.winehq.org/show_bug.cgi?id=25703

Not sure if you actually want this level of compatibility with .NET, but I figured I'd file it just in case. We could fix it for now by checking PlaceholderText before Text (figuring that if an application actually sets PlaceholderText, it's targeting the current version anyway and can expect Text to be accessed), but avoiding similar changes in behavior during future development may be an unreasonable burden.

**Actual behavior:**

System.Exception: get_Text shouldn't be called now
  at SensitiveTextBox.get_Text () [0x0000b] in <38501e67847d405c943d47fcb89757b0>:0 
  at System.Windows.Forms.TextBox.WndProc (System.Windows.Forms.Message& m) [0x0009e] in <b34bc0b1a0ad46edab19a97c25136586>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.OnMessage (System.Windows.Forms.Message& m) [0x00001] in <b34bc0b1a0ad46edab19a97c25136586>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x000b3] in <b34bc0b1a0ad46edab19a97c25136586>:0 
  at System.Windows.Forms.NativeWindow.Callback (System.IntPtr hWnd, System.Int32 msg, System.IntPtr wparam, System.IntPtr lparam) [0x00030] in <b34bc0b1a0ad46edab19a97c25136586>:0 

**Expected behavior:**

No exception.

**Minimal repro:**

```
using System;
using System.Drawing;
using System.Windows.Forms;

class SensitiveTextBox : TextBox
{
    public override string Text {
        get {
            if (!RecreatingHandle)
                throw new Exception("get_Text shouldn't be called now");
            return base.Text;
        }
    }
}

class TextBoxTest : Form
{
    TextBox textbox;

    public TextBoxTest()
    {
        this.textbox = new SensitiveTextBox();
        this.textbox.ClientSize = new System.Drawing.Size(300, 300);
        this.ClientSize = new System.Drawing.Size(300, 300);
        this.Controls.Add(this.textbox);
    }

    public static void Main()
    {
        Application.Run(new TextBoxTest());
    }
}
```

**Comment by weltkante** [comment]
I don't think you can generalize this expectation, client code could easily want to read/write the Text property in the Form constructor before any handles are created.

Being able to read/write the Text before creation is part of the base class features (we definitely use that in our application), as such this particular implementation is not a general purpose TextBox and only works in the first place under very specific circumstances.

**Comment by merriemcgaw** [comment]
@stefanov-stefan do you want to take a look into this issue, or hand off to one of us?

**Comment by stefanov-stefan** [comment]
Hey @merriemcgaw, @petermitkov will take a look at this.
