### ISSUE TITLE
PlaceholderText not virtual

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#1110]
While commenting #1109 I noticed that `TextBox.PlaceholderText` [is not virtual](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs#L909). Is this intentional or an oversight? Other properties like `Text` are virtual, presumably to allow subclasses customization control. Making `PlaceholderText` not virtual means subclasses can't "turn off" this feature and are at the mercy of the caller not trying to set the property.

Might be worth fixing before 3.0 RTM if it is indeed an oversight.

**Comment by merriemcgaw** [comment]
@stefanov-stefan was this an oversight in your work on #96? Would be nice if we can make it consistent.

**Comment by stefanov-stefan** [comment]
Hey @merriemcgaw, @petermitkov will take a look at this.
