### ISSUE TITLE
Possible layout issues after Control.Defaultfont changes

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1113]
**Problem description:**

As a result of the `Control.Defaultfont` changes introduced in #656 we *may* have a possible breaking experience for customer who had pixel-perfect layouts.

**Actual behavior:** 

| .NET 4.7.2 | .NET Core 3.0 |
|---|---|
| ![image](https://user-images.githubusercontent.com/4403806/59082950-a6bba500-8938-11e9-8d07-cdae09a5e24b.png) |  ![image](https://user-images.githubusercontent.com/4403806/59082924-8be93080-8938-11e9-8d98-11eea254bb1f.png) |

If you look closely with the new font we have a greater vertical space requirements.

I have also create a fixed layout test, and it displays a possible issue - some text may get clipped or covered:

| .NET 4.7.2 | .NET Core 3.0 |
|---|---|
| ![image](https://user-images.githubusercontent.com/4403806/59083935-973e5b00-893c-11e9-9c12-395e830d1c60.png) | ![image](https://user-images.githubusercontent.com/4403806/59083909-8261c780-893c-11e9-82ae-ae0476f1b417.png) |

**Expected behavior:**

Few options:
* We could note the new behaviour in release notes and be done with it.
* We could also add some sort of a switch or an opt-in behaviour that would allow customers to retain the original font. 
As discussed with @KlausLoeffelmann in https://github.com/dotnet/winforms/pull/656#issuecomment-499839663 would could add `Application.SetDefaultFont(Font)` method to allow affected customers to set to which ever font works for them.

**Minimal repro:**

Run `WinformsControlsTest` and `WinFormsControlsClassicTests` and compare.

**Comment by merriemcgaw** [comment]
Yep, we felt that this was the only chance we would have to modernize the default font. So this is by design, and a customer can set their Form's default font to whatever they want. We use the default font only when they haven't set anything at all.
