### ISSUE TITLE
The ContextMenu of NotifyIcon Positioning Issue on Multi-Monitor Setup with Differing Scaling Factors

### ISSUE THREAD

**Issue by john-guo** [dotnet/winforms#11167]
### .NET version

C:\Program Files\Microsoft Visual Studio\2022\Community>dotnet --info
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.825c015e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.825c015e
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  7.0.402 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### Did it work in .NET Framework?

No

### Issue description

The WinForm example displays two instances of the same window on two screens, and adds an icon to the notification area that, when right-clicked, pops up a menu for control. However, under different scaling factors at the same resolution, the menu that appears upon right-clicking often becomes incorrect.

This is the resolution and scaling settings for the two monitors, as well as a video demonstrating the issue when clicking on the notification icon.

![image](https://github.com/dotnet/winforms/assets/7485003/b9c106f8-b069-42ff-8133-377559b316f7)
![image](https://github.com/dotnet/winforms/assets/7485003/89b1a9af-252d-4334-afaa-863f59834b3d)

This is the resolution and scaling settings for the two monitors, as well as a video demonstrating the issue when clicking on the notification icon.

https://github.com/dotnet/winforms/assets/7485003/62fced96-700e-403e-976c-0e4920e94f6f

In the video, when I right-click the notification icon of the program, the menu pops up correctly the first time. However, upon clicking for the second time, the menu position becomes completely incorrect.

### Steps to reproduce

Set up two monitors, with scaling rate A set to 100% and B set to 125%. Launch the attached project on monitor A, then right-click on the icon in the system notification area. Repeated clicks will reproduce the issue.

[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/14880691/WinFormsApp1.zip)

**Comment by paul1956** [comment]
I had this issue in FrameWork and all versions of .Net Core and the following workaround was suggested and works. I believe the issue was closed. 

The code below was added to FormShown event. 
![image](https://github.com/dotnet/winforms/assets/12789369/32b52da3-b087-4040-9fb8-afefa31bd4eb)

**Comment by john-guo** [comment]
> This is not a regression issue and can be reproduced in .NET Framework, .NET 6.0 and 9.0. A workaround is to make Form1 lose focus and then regain it.
> 
>  test11167.mp4

If the window is placed on the secondary monitor, then this workaround will not solve the issue.

**Comment by Philip-Wang01** [comment]
@john-guo If the window is placed on the secondary monitor, a better way is to add `<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>` in the csproj file. This works fine in my test environment. Can you try it?
![image](https://github.com/dotnet/winforms/assets/86937911/e9c53e63-512f-42e1-84bc-c3e73bb24d99)

**Comment by john-guo** [comment]
> @john-guo If the window is placed on the secondary monitor, a better way is to add `<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>` in the csproj file. This works fine in my test environment. Can you try it? ![image](https://private-user-images.githubusercontent.com/86937911/320733691-e9c53e63-512f-42e1-84bc-c3e73bb24d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDMyNjQsIm5iZiI6MTcxMjY0Mjk2NCwicGF0aCI6Ii84NjkzNzkxMS8zMjA3MzM2OTEtZTljNTNlNjMtNTEyZi00MmUxLTg0YmMtYzNlNzNiYjI0ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA2MDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYzlhYzljZTZkNDRiYmYwMzA2MDIyOTNhOWNlNmFmNDI1YmFiYTQ0ZjEwODE2NWNlZTFkYTQxZDE2MDZlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X_BREcRuB35KTJvYjz9flweqTbZeZjmgTyQ0oW84ZQ0)

I tried it, and indeed, this configuration solved the problem. Thank you very much.
