### ISSUE TITLE
Microsoft.Windows.Compatibility 8.0.4 references unreleased nuget packages

### ISSUE THREAD

**Issue by JSGInray** [dotnet/winforms#11181]
### .NET version

8.0

### Did it work in .NET Framework?

Not tested/verified

### Issue description

Microsoft.Windows.Compatibility 8.0.4 references System.Drawing.Common 8.0.4 which does not exist.

### Steps to reproduce

reference Microsoft.Windows.Compatibility 8.0.4

**Comment by lonitra** [comment]
Thanks for filing this! I have been unable to reproduce this issue, could you share more details of the steps that are being taken to repro this issue, the error you are seeing and/or sample project that demonstrates error?

**Comment by JSGInray** [comment]
The packages have been published and it is working as expected now.
Maybe the build pipeline can be adjusted to publish Microsoft.Windows.Compatibility and it dependecies at the same time.
