### ISSUE TITLE
TreeView has the incorrect TreeNode Editor dialog in PropertyGrid

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#11198]
### .NET version

9.0.100-preview.4.24210.38

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it still repro in 6.0/7.0/8.0.

### Issue description

**Actual result:**
There's an incorrect **TreeNode Collection Editor** dialog for TreeView control.
![TreeView-Editor-Actual](https://github.com/dotnet/winforms/assets/45864985/45ad249f-28a9-498b-8594-48c571ea87f7)

https://github.com/dotnet/winforms/assets/45864985/8c8e58cb-5156-4f57-ba59-1597ab52c1cd

**Expected result:**
It should be the **TreeNode Editor** dialog for TreeView control.
![TreeView-Editor-Expected](https://github.com/dotnet/winforms/assets/45864985/b84bdf17-394f-4cce-bbb9-525856318228)

### Steps to reproduce

1. Run the test project: [TestApp.zip](https://github.com/dotnet/winforms/files/14943526/TestApp.zip)
2. In **PropertyGrid** control, click the **...** button in **Nodes** property
3. Check the opened dialog

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik let's go ahead and take care of it now - we can ask @LeafShi1 and her team to take care of that.

**Comment by MelonWang1** [comment]
Verified the issue on the latest DemoConsole test app of Winforms repo from main branch, the issue has been fixed that TreeView has the correct TreeNode Editor dialog in PropertyGrid now. Will verify it again once the official .NET SDK version is available.

https://github.com/dotnet/winforms/assets/94418985/3140e202-ea07-4130-9a87-cf44e3240ec3

**Comment by MelonWang1** [comment]
Verified it in the latest .Net 9.0 SDK build: 9.0.100-preview.5.24253.17, it was fixed: TreeView has the correct TreeNode Editor dialog in PropertyGrid now.
![Screenshot 2024-05-06 094138](https://github.com/dotnet/winforms/assets/94418985/4b94cdf9-4432-446b-927e-bea75a576a35)

**Comment by alandryz83** [comment]
Sent from my iPhoneOn May 6, 2024, at 4:45 AM, Melon Wang1 ***@***.***> wrote:﻿
Verified it in the latest .Net 9.0 SDK build: 9.0.100-preview.5.24253.17, it was fixed: TreeView has the correct TreeNode Editor dialog in PropertyGrid now.
Screenshot.2024-05-06.094138.png (view on web)

**Comment by Zheng-Li01** [comment]
Verified the issue on .NET SDK 9.0.100-Preview.4.24253.11 Test Pass build, the issue has been fixed that have the results as above.
