### ISSUE TITLE
[GB18030]Dotnet publish failed with CLI if project output directory with GB18030 provided level3 strings

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#11191]
### .NET version

.NET 9.0 SDK build: 9.0.100-preview.4.24209.30

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it still reproduces in .NET 8.0 SDK: 8.0.204

### Issue description

Dotnet publish failed with CLI for Winforms if project output directory with GB18030 provided level3 strings from
[Level3 GB18030-2022 Testing Data for medium large amount cases-GB18030.txt](https://github.com/dotnet/winforms/files/14929269/Level3.GB18030-2022.Testing.Data.for.medium.large.amount.cases-GB18030.txt)
And dotnet build and Dotnet run with CLI successfully
![image](https://github.com/dotnet/winforms/assets/26474449/97148686-a364-4415-8745-76ccb51c9df8)
Actually that runtimeconfig.json file exists in bin/release/net9.0-windows:
![image](https://github.com/dotnet/winforms/assets/26474449/37a94111-4110-4c60-a845-da4740d859e0)
Publish folder is not a complete one:
![image](https://github.com/dotnet/winforms/assets/26474449/ebb1a68e-8dfa-490b-b184-bc3b2d681471)

It can also repro in Console:
![image](https://github.com/dotnet/winforms/assets/26474449/1e0e8c22-3233-474d-b484-60287db3e825)

### Steps to reproduce

1. Open the provided GB18030 level3 data file using word **(select GB18030 encoding)**, for example to test part of Group1 and Group10
2. Use CLI to create winforms app with -n and -o parameters by copying GB18030 characters
`dotnet new winforms -n "𬉼𠳐G龦龪C啊阿埃挨哎唉D2丂丄丅丆丏丒丟D3狧狪狫㑳狵狶狹繭狾⺁⺄⺈⺋⺌⺗⺧⺪D4、。·ˉD1℅℉D5U1U2U3㐀㐁㐂㐃㐄" -o "𬕂𡎚G鿁鿂C鼬鼯鼹鼷鼽皑D2牘狕狖狘狚丗D3珿㑇㖞㘚㘎䎱䲣䲠䴘狽䴙䶮D4∞ㄆㄍㄠūǘD1〾⿰⿱⿲⿳⿴⿵⿶⿷⿸⿹⿺⿻D5U1U2U3䀅㩶㩷A𤴩𤴪𤴡𤴣𤴫𠀇B𫓯𫍯𫍲𫘦𫘧𪣻𫐐C"`
3. Go to created app folder 
`cd "𬕂𡎚G鿁鿂C鼬鼯鼹鼷鼽皑D2牘狕狖狘狚丗D3珿㑇㖞㘚㘎䎱䲣䲠䴘狽䴙䶮D4∞ㄆㄍㄠūǘD1〾⿰⿱⿲⿳⿴⿵⿶⿷⿸⿹⿺⿻D5U1U2U3䀅㩶㩷A𤴩𤴪𤴡𤴣𤴫𠀇B𫓯𫍯𫍲𫘦𫘧𪣻𫐐C"`
4. Dotnet build
`dotnet build`
6. Dotnet run
`dotnet run`
8. Dotnet publish
`dotnet publish`

**Comment by Olina-Zhang** [comment]
After discussing with @richaverma1, opened a AzDo bug to MSBuild team: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2026853.

**Comment by merriemcgaw** [comment]
I'm going to close this one as duplicate and we'll track it internally with the AzDO item.
