### ISSUE TITLE
PropertyGrid: images are not rendered / ImageEditor not working?

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1119]
**Problem description:**

![image](https://user-images.githubusercontent.com/4403806/59333395-92621880-8d3b-11e9-9d2f-228d5f6be70d.png)

**Expected behavior:**

The rendering should be the same as in .NET Fx

**Minimal repro:**

* build and launch WinFormsControlsClassicTests and WinformsControlsTest
* click `FontNameEditor` button in both and align opened windows side-by-side
* expand any of Font properties

**Comment by RussKie** [comment]
This is still broken in 3.1-Preview1 and 5.0

**Comment by weltkante** [comment]
Probably some `[Editor(...)]` attribute missing which was present in Desktop Framework and `TypeDescriptor.GetEditor` returning null.

**Comment by weltkante** [comment]
Probably needs a line added [here](https://github.com/dotnet/winforms/blob/ab6730e76538c28f598bbac2bb009725e9ab69bc/src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs#L19-L33), see PR #2089 for an example.

**Comment by vladimir-krestov** [comment]
It was fixed in `release/3.1-uitypeeditors` branch.
