### ISSUE TITLE
Porting System.Windows.Forms.DataVisualization to .NET core

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#112]
Creating this issue to track the porting of  System.Windows.Forms.DataVisualization.dll into  Core.

- We have seen multiple reports on  not being able to migrate because of missing the dll in core.
- Porting of this binary may have dependency on System.Data.Oledb.
- Winforms applications using "Chart" control are primary target of this issue.

**Comment by danielabbatt** [comment]
I work on a project which generates charts server side into images and it would be great to get that onto Core as it's the only part of the app which still relies on .NET Framework.

**Comment by davidnmbond** [comment]
Would love to see this - there is no reasonable way to achieve charting in .NET Core without it!

**Comment by weltkante** [comment]
@davidnmbond apparently this is already mostly done, @merriemcgaw commented something along those lines in #510

**Comment by kirsan31** [comment]
We have [DataVisualization](https://github.com/dotnet/winforms-datavisualization) in preview 4 now. And most of sad thing it's considered deprecated :(( 
I posted a [question](https://github.com/dotnet/winforms-datavisualization/issues/9) about it...

**Comment by zsd4yr** [comment]
I have added guidance on using the new ported types to our porting guidelines https://github.com/dotnet/winforms/blob/master/Documentation/porting-guidelines.md#include-the-systemwindowsformsdatavisualization-pack

**Comment by danineuss** [comment]
@zsd4yr 
I am currently trying to port my application to .NET Core 3.x and have stumbled upon the not supported `(...).DataVisualization.Charting` library. Is this fixed today? The URL that you posted on April 19 '19 leads into 404 land ..

Thanks already 🙏🏽

**Comment by weltkante** [comment]
You want to check the [document in the release/3.0 branch](https://github.com/dotnet/winforms/blob/release/3.0/Documentation/porting-guidelines.md#include-the-systemwindowsformsdatavisualization-pack). Its usable for initial porting but generally charting is not supported going forward to newer .NET versions, so you may run into bugs eventually when WinForms changes and this library wasn't updated. You can keep using it if you create your own build and maintain it yourself I assume, or switch to a library with full external support.

**Comment by RussKie** [comment]
The library is no longer supported. 
The docs link: https://github.com/dotnet/winforms/blob/main/docs/porting-guidelines.md#include-the-systemwindowsformsdatavisualization-pack
Here's a package that should help you to migrate to .NET, but it won't in the new designer: https://www.nuget.org/packages/System.Windows.Forms.DataVisualization.

**Comment by danineuss** [comment]
Thanks Igor for your reply! I am having issues installing the nuget
package but in essence this is all I would need to do in order to make
my repo ready for moving it to .NET Core?

On August 13, 2021, radioman85 ***@***.***> wrote:
> The library is no longer supported.
>  The docs link:
> <https://github.com/dotnet/winforms/blob/main/docs/porting-
> guidelines.md#include-the-systemwindowsformsdatavisualization-pack>
>  Here's a package that should help you to migrate to .NET, but it
> won't in the new designer:
> <https://www.nuget.org/packages/System.Windows.Forms.DataVisualization>.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dotnet/winforms/issues/112#issuecomment-898140897>,
or unsubscribe <https://github.com/notifications/unsubscribe-
auth/ADUA746WAXA33DS3566WQDLT4SB5JANCNFSM4GHSYDTA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-
email>.
