### ISSUE TITLE
PropertyGrid: colors are not rendered / ColorEditor not working?

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1120]
**Problem description:**

![image](https://user-images.githubusercontent.com/4403806/59333203-2da6be00-8d3b-11e9-9a39-368bf67df39c.png)
![image](https://user-images.githubusercontent.com/4403806/59333754-5bd8cd80-8d3c-11e9-875d-99fbe68a523f.png)

**Expected behavior:**

The rendering should be the same as in .NET Fx

**Minimal repro:**

* build and launch WinFormsControlsClassicTests and WinformsControlsTest
* click `FontNameEditor` button in both and align opened windows side-by-side
* expand any of Font properties

**Comment by kirsan31** [comment]
Sadly to note, but this and other issues are talking:
WinForms .core will not be ready for production usage for those who use PropertyGrid intensively, at least till 3.1 :(

P.s. I think it's better to wait 3.1 anyway...

**Comment by RussKie** [comment]
This is still broken in 3.1-Preview1 and 5.0

**Comment by weltkante** [comment]
`TypeDescriptor.GetEditor(typeof(Color), typeof(UITypeEditor))` returns null, Desktop Framework used to link the Color type with an `[Editor("System.Drawing.Design.ColorEditor, System.Drawing.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", typeof(UITypeEditor))]` attribute. In .NET Core you'll probably want to extend the TypeDescriptor dynamically to avoid having CoreFX System.Drawing reference WinForms.

**Comment by weltkante** [comment]
Probably needs a line added [here](https://github.com/dotnet/winforms/blob/ab6730e76538c28f598bbac2bb009725e9ab69bc/src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs#L19-L33), see PR #2089 for an example.

**Comment by vladimir-krestov** [comment]
It was fixed in `release/3.1-uitypeeditors` branch.
