### ISSUE TITLE
PropertyGrid: FontEditor not working?

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1121]
**Problem description:**

![image](https://user-images.githubusercontent.com/4403806/59334140-254f8280-8d3d-11e9-8f6d-535cd614e636.png)

**Expected behavior:**

The rendering should be the same as in .NET Fx

**Minimal repro:**

* build and launch WinFormsControlsClassicTests and WinformsControlsTest
* click `FontNameEditor` button in both and align opened windows side-by-side
* expand any of Font properties

**Comment by RussKie** [comment]
This is still broken in 3.1-Preview1 and 5.0

**Comment by weltkante** [comment]
`Font` is missing the `[Editor(...)]` attribute, Desktop had `[Editor("System.Drawing.Design.FontEditor, System.Drawing.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", typeof(UITypeEditor))]` but CoreFX doesn't want the dependency on WinForms anymore. I think you have some TypeDescriptor logic which extends the types in System.Drawing with their WinForms specific designer attributes, but I don't remember where it is located.

**Comment by weltkante** [comment]
Probably needs a line added [here](https://github.com/dotnet/winforms/blob/ab6730e76538c28f598bbac2bb009725e9ab69bc/src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs#L19-L33), see PR #2089 for an example.

**Comment by vladimir-krestov** [comment]
At the moment FontEditor works well, but FontNameEditor doesn't work and will be fixed in the future.

**Comment by weltkante** [comment]
@vladimir-krestov FontNameEditor has #2104 for resolving the technical problem of registering it, I don't think its necessary to keep two issues open.

**Comment by vladimir-krestov** [comment]
@weltkante thank you, I agree.
