### ISSUE TITLE
DataGridView shown on components area, not visual design surface

### ISSUE THREAD

**Issue by deerchao** [dotnet/winforms#11220]
### .NET version

.Net 8.0.1

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No in .Net 6.0.

### Issue description

In DemoConsole application, if we add DataGridView/PropertyGrid to the surface, it won't be visible, or can't be selected clicking, and there would be an additional entry in the invisible component section(like where Timers usually show up).
![Untitled](https://github.com/dotnet/winforms/assets/1029381/f3ed605d-150d-4239-aef1-c34d580b3236)
![Untitled2](https://github.com/dotnet/winforms/assets/1029381/2e8e3903-b95c-427d-967b-1ede223c692c)

### Steps to reproduce

Run DemoConsole application, switch to the 5th tab page.

**Comment by merriemcgaw** [comment]
Thanks @deerchao for reporting this issue. This is a test application, that doesn't necessarily reflect a real-world scenario. We'll keep this open, but it's low priority until we get a user-scenario needing this functionality. 

Can you help us understand your scenario here? Is this blocking a customer facing scenario for you?

**Comment by deerchao** [comment]
I'm developing a low-code platform, with an UI designer included, which is built with WinForms designer facilities.

If the controls doesn't show up on designer visual surface, it would be hard for my users to set up the UI, especially when they are not professional programmers. For my scenario, this has to be solved or worked around, or the GUI design related features would be pointless.

Bad news is that it's not happening for only DataGridView, but also PropertyGrid/FlowLayoutPanel/TrackBar, and other controls.

Good news is if I wrap them within a UserControl, it seems to work, but this would mean much more work to do.

**Comment by LeafShi1** [comment]
`DataGridviewDesigner `was added to 9.0 Preview 3 via this [Commit ](https://github.com/dotnet/winforms/commit/61b929a3570c690623ebea8de4256eafa2b4364c)and it was not backported to .net 8.0 so this issue is correct on 8.0

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - does this repro in main?

**Comment by LeafShi1** [comment]
> @LeafShi1 - does this repro in main?

No, the control can be displayed normally in the main branch
![image](https://github.com/dotnet/winforms/assets/132890443/bf9bb92c-da06-43b8-90cd-9003cecaf3d5)

**Comment by Tanya-Solyanik** [comment]
@deerchao - would it be possible for you to move to NET9 preview for your development?

**Comment by deerchao** [comment]
> @deerchao - would it be possible for you to move to NET9 preview for your development?

OK, I'm going to have a try.
