### ISSUE TITLE
The description for design properties within DemoControl application is not appearing for every control.

### ISSUE THREAD

**Issue by Syareel-Sukeri** [dotnet/winforms#11275]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, still repro in Winforms repo release/8.0

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, the description for design properties is not showing up except "Name" when you click the controls unlike any other sections. 
![Animation](https://github.com/dotnet/winforms/assets/156630333/48ac8c07-9092-43d5-a7df-2d03c10fa9a6)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by elachlan** [comment]
This isn't really a bug. The property just doesn't have a `SRDescription` attribute. I added a `Description` attribute and it added text
![image](https://github.com/dotnet/winforms/assets/2433737/f3fdba93-3fec-42a3-833d-d7f593a68629)

**Comment by elachlan** [comment]
I think #10936 would help find the properties so we can annotate them.

**Comment by Tanya-Solyanik** [comment]
We'll wait for user scenario that requires descriptions for the design time properties.
