### ISSUE TITLE
System.Data.DataColumn serializes some properties with a default value (different from the .NET Framework)

### ISSUE THREAD

**Issue by rmkarasev** [dotnet/winforms#11314]
### Environment

Microsoft Visual Studio 2022
Version 17.9.3

### .NET version

.NET 6 (we use)
.NET 8

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Works in the same Visual Studio 2022 Version 17.9.3 or previous versions, but targeting to .NET Framework 4.8.

### Issue description

We have a custom Component and ComponentDesigner those are used to create/populate multiple DataTable and DataColumn in the design-time.

After migrating to .NET 6 we are experiencing with an issue that each DataColumn serialize some properties to .Designer.cs and .resx files that looks needless and just increase file size and noise.

Previous code:
```c#
this.dataColumn35.ColumnName = "DischargedDate";
this.dataColumn35.DataType = typeof(System.DateTime);
```

Current code:
```c#
dataColumn35.Caption = "DischargedDate";
dataColumn35.ColumnName = "DischargedDate";
dataColumn35.DataType = typeof(System.DateTime);
dataColumn35.DefaultValue = resources.GetObject("dataColumn35.DefaultValue");
dataColumn35.Namespace = "";
```
and .resx
```c#
  <data name="dataColumn35.DefaultValue" mimetype="application/x-microsoft.net.object.binary.base64">
    <value>
        AAEAAAD/////AQAAAAAAAAAMAgAAAEhTeXN0ZW0uUHJpdmF0ZS5Db3JlTGliLCBDdWx0dXJlPW5ldXRy
        YWwsIFB1YmxpY0tleVRva2VuPTdjZWM4NWQ3YmVhNzc5OGUFAQAAAB9TeXN0ZW0uVW5pdHlTZXJpYWxp
        emF0aW9uSG9sZGVyAwAAAAREYXRhCVVuaXR5VHlwZQxBc3NlbWJseU5hbWUBAAEIAgAAAAoCAAAABgMA
        AAAACw==
</value>
  </data>
```

So, ton of Caption, DefaultValue, Namespace properties are added when changing the form design in new Windows Forms Designer..

Is this issue already known? How can be this fixed?

### Steps to reproduce

Minimal project is attached

[DataColumnSerializationIssue.zip](https://github.com/dotnet/winforms/files/15213014/DataColumnSerializationIssue.zip)

**Comment by elachlan** [comment]
@Tanya-Solyanik are we serialising some default values on purpose?

**Comment by Tanya-Solyanik** [comment]
DataColumn.Caption should be serialized on both versions: 
https://source.dot.net/#System.Data.Common/System/Data/DataColumn.cs,345
https://referencesource.microsoft.com/#System.Data/fx/src/data/System/Data/DataColumn.cs,371
If it's not set explicitly, column name is used.

DataColumn.Namespace should be serialized on both versions too:
https://source.dot.net/#System.Data.Common/System/Data/DataColumn.cs,987 
https://referencesource.microsoft.com/#System.Data/fx/src/data/System/Data/DataColumn.cs,1002
It seems that in NET6 version of the app _columnUri is not null. 

DataColumn.DefaultValue should be serialized as a string using the converter -
https://source.dot.net/#System.Data.Common/System/Data/DataColumn.cs,640 
https://source.dot.net/#System.Data.Common/System/Data/DefaultValueTypeConverter.cs,3060fb00499d852e
https://source.dot.net/#System.Data.Common/System/Data/DataColumn.cs,1750
https://referencesource.microsoft.com/#System.Data/fx/src/data/System/Data/DataColumn.cs,1725

So far this looks like designer bug. @Olina-Zhang  - could you please copy it to the designer repo?

**Comment by Philip-Wang01** [comment]
@Tanya-Solyanik Filed a DT issue: https://github.com/microsoft/winforms-designer/issues/5964 to track it.

**Comment by rmkarasev** [comment]
Hi @Tanya-Solyanik - one more questions/issue related to the designer (DataTable specifically or any other collection that have 
AddRange() method.

.NET 6 designer writes all elements on single line against .Net Framework 4.8 writes an each element on separate line.
The single line will have less space, but this lead to complicated reviewing and comparing when any changes are made in the collection.
Is this designer change on purpose or is this unexpected behavior?

Previous code:
`
// 
// dataTable1
// 
this.dataTable1.Columns.AddRange(new System.Data.DataColumn[] {
this.dataColumn1,
this.dataColumn2,
this.dataColumn3,
this.dataColumn4,
this.dataColumn5,
this.dataColumn6,
this.dataColumn7,
this.dataColumn8,
this.dataColumn9,
this.dataColumn10});
this.dataTable1.Constraints.AddRange(new System.Data.Constraint[] {
            new System.Data.UniqueConstraint("Constraint1", new string[] {
                        "PdmId"}, true)});
            this.dataTable1.PrimaryKey = new System.Data.DataColumn[] {
        this.dataColumn1};
`

Current code:
`
// 
// dataTable1
// 
dataTable1.Columns.AddRange(new System.Data.DataColumn[] { dataColumn1, dataColumn2, dataColumn3, dataColumn4, dataColumn5, dataColumn6, dataColumn7, dataColumn8, dataColumn9, dataColumn10 });
dataTable1.Constraints.AddRange(new System.Data.Constraint[] { new System.Data.UniqueConstraint("Constraint1", new string[] { "PdmId" }, true) });
dataTable1.Namespace = "";
dataTable1.PrimaryKey = new System.Data.DataColumn[]
    {
    dataColumn1
    };`

**Comment by Tanya-Solyanik** [comment]
Here is the runtime fix: https://github.com/dotnet/runtime/pull/102780

**Comment by Tanya-Solyanik** [comment]
@rmkarasev  - let us know if the fix works for you

**Comment by Tanya-Solyanik** [comment]
>Is this designer change on purpose or is this unexpected behavior?

This was an intentional change related to designer using the Roslyn-based 
 design time serialization in the recent releases https://github.com/dotnet/winforms/blob/main/docs/designer/modernization-of-code-behind-in-OOP-designer/modernization-of-code-behind-in-oop-designer.md

@Olina-Zhang  - do we have this feedback(https://github.com/dotnet/winforms/issues/11314#issuecomment-2391231377) in the designer repo? Please open a new issue if not.

**Comment by Philip-Wang01** [comment]
@Tanya-Solyanik We haven't had any feedback on this. Filed a new issue: https://github.com/microsoft/winforms-designer/issues/6138 to track it.
