### ISSUE TITLE
Unresponsiveness issue during Real-Time Updates in Winforms DataGridView

### ISSUE THREAD

**Issue by DhivyaBharathi-SF3890** [dotnet/winforms#11335]
### .NET version

.Net 7.0

### Did it work in .NET Framework?

No

### Issue description

In DataGridView, while updating the values like real-time updates, the demo becomes unresponsive. Without using the Refresh() method the values are not updated.

[DataGrid_Refresh.zip](https://github.com/dotnet/winforms/files/15252072/DataGrid_Refresh.zip)

### Steps to reproduce

1.Run the sample.
2.Click the Refresh button.

**Observed Behavior:**
The sample enters into the Not responding state

**Comment by lonitra** [comment]
@KlausLoeffelmann could you take an initial look at this?

**Comment by Zheng-Li01** [comment]
The issue can reproduce both .NET from 6.0 to 90 and  .NET Framework 4.7.2 to 4.8.1 as below screenshot.
![11335](https://github.com/dotnet/winforms/assets/38325459/1a7936b2-b892-4b60-a794-de1dcf523c88)

**Comment by LeafShi1** [comment]
This issue can be reproduced using the following simple code

```
 private void button1_Click(object sender, EventArgs e)
 {
     for (int i = 0; i < 100000; i++)
     {
         dataGridView1.Refresh();
     }
 }
```

[WinFormsApp7.zip](https://github.com/dotnet/winforms/files/15305893/WinFormsApp7.zip)

**Comment by elachlan** [comment]
I don't think this is a bug. You are using thread.sleep in the UI thread. `DataGridView.Refresh` will trigger an invalidation of the whole gridview and repaint it. All of that will end up locking the UI thread.

It would be better to use a separate thread (via a background worker or similar) to report progress to the UI thread. `BackgroundWorker.ReportProgress` allows you to pass an object as well. Which can be your "progress" class.

**Comment by DhivyaBharathi-SF3890** [comment]
We have checked the background worker with our scenario, but it did not help and caused an exception. When we call DataGrid.Refresh for a specific record by passing in the BackgroundWorker.ReportProgress, it also throws an exception. If we call BackgroundWorker.ReportProgress for a certain limit of records, the value only updates for those records. Please find the sample demo in the attachment. Could you please take a look at that sample and suggest a proper way to achieve this?

[DataGrid_Refresh.zip](https://github.com/user-attachments/files/15604221/DataGrid_Refresh.zip)

**Comment by elachlan** [comment]
@DhivyaBharathi-SF3890 `ObservableCollection` is not threadsafe. You can't bind it on the UI thread and then create a separate thread and pass it to it afterwards.

I would avoid using datagrid and instead use a progress bar. Using the background worker report progress to change the progress percentage and some sort of text indicating the number of completed vs total (100/1000). Your dowork event needs to take in parameters, do work (reporting as you go), then return a result. You can't access things on the UI thread in doWork, This is why you pass parameters to it.

**Comment by KlausLoeffelmann** [comment]
I also do not thing, this is bug.
I did a quick test, and it worked fine for me, both from the background worker and with a threading timer.

I would like to see a complete repro scenario using those approaches to assess this as a bug.
Until then, I'll close it with "No Repro".

Feel free to reopen! Thanks!
