### ISSUE TITLE
WinForms fails to build with a nightly SDK

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/winforms#11332]
SDK: 9.0.100-preview.5.24253.16

We had to add a patch to unblock the VMR / source-build: https://github.com/dotnet/sdk/blob/main/src/SourceBuild/patches/winforms/0001-Disable-IL2055-for-a-new-callsite.patch

> IL2055: Call to 'System.Type.MakeGenericType(params Type[])' can not be statically analyzed. It's not possible to guarantee the availability of requirements of the generic type.

cc @JeremyKuhne

**Comment by lonitra** [comment]
There was a dependency flow PR that had this same error. (https://github.com/dotnet/winforms/pull/11305). We had added a suppression to the .csproj since this is not something that can be addressed at the moment. Is there any action item here that needs to be addressed?

**Comment by ViktorHofer** [comment]
Nothing, thanks.
