### ISSUE TITLE
[ARM64]The Form1.cs[Design] page cannot load successfully after installed the latest .NET 9.0 Preview4 or Preview5

### ISSUE THREAD

**Issue by Forgind** [dotnet/winforms#11340]
---
**Issue moved from dotnet/sdk#40786**
- Please respond to @Zheng-Li01.

---

_From @Zheng-Li01 on Thursday, May 9, 2024 8:01:14 AM_

**SDK Versions:**
Bad SDK: dotnet-sdk-9.0.100-preview.5.24258.8-win-arm64 & dotnet-sdk-9.0.100-preview.4.24258.4-win-arm64
Good SDK: dotnet-sdk-9.0.100-preview.3.24204.13-win-arm64

**Visual Studio Versions:**
17.11.0 Preview 1.0 [34908.277.d17.11] & 17.11.0 Preview 2.0 [34908.267.main]

### Describe the bug
The Form1.cs[Design] page cannot load successfully after installed the latest .NET 9.0 Preview4 & Preview5 on the ARM64 machine

### To Reproduce
1. Install the latest .NET 9.0 Preview4 or Preview5 Windows arm 64 from https://github.com/dotnet/installer
2. Create a .NET WinForms project targeting to .NET 9.0
3. Observe the Form1.cs[Design] page

**Expected Result:**
The Form1.cs[Design] page can load successfully after installed the latest .NET 9.0 Preview4 & Preview5 on the ARM64 machine, 
![ExpectedResults](https://github.com/dotnet/sdk/assets/38325459/75a98e7d-7173-449e-9786-c8d047903609)
![ExpectedResults](https://github.com/dotnet/sdk/assets/38325459/c019264f-a36a-43ae-80b0-3fb5ffc56e4e)

**Actual Result:**
**Preview5Results**
The Form1.cs[Design] page cannot load successfully after installed the latest .NET 9.0 Preview4 & Preview5 on the ARM64 machine, and the Visual Studio will not be responding after clicked anywhere. 
![Preview5Results](https://github.com/dotnet/sdk/assets/38325459/d5fbfdee-f958-468f-8aba-ef1df6a356fc)
![ActualResults](https://github.com/dotnet/sdk/assets/38325459/2104e367-a4c0-4391-9600-1fdc0d8a60e0)
**Preview4Results**
![Preview4Results](https://github.com/dotnet/sdk/assets/38325459/b6dcc8e1-1ec5-4ceb-ad6e-a0e7c36ddd3c)

**More info:**
1. The issue cannot reproduce Windows x64 platform with same sdk version.
2. The issue cannot reproduce after installed latest .NET 9.0 Preview3 from https://dotnet.microsoft.com/en-us/download/dotnet on the ARM64 machine
3. The issue also can reproduce on the  .NET 9.0 Preview4.24257.5(arm64) which bring in PR https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/525045,

**Comment by Forgind** [comment]
---
**Issue moved from dotnet/sdk#40786**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Thursday, May 9, 2024 8:01:20 AM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by Tanya-Solyanik** [comment]
dupicate of https://github.com/dotnet/sdk/issues/40694

**Comment by Zheng-Li01** [comment]
https://github.com/dotnet/runtime/issues/102056#issuecomment-2103374962 this workaround working well.

![image](https://github.com/dotnet/winforms/assets/38325459/633497bd-895e-449d-80b7-5347314e3833)
