### ISSUE TITLE
The selected control should have a solid border in the DemoConsole application

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#11353]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this was changed after winform designer PR [5855](https://github.com/microsoft/winforms-designer/pull/5855).

### Issue description

Actual result in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app:
The selected control has a dashed border in the DemoConsole application.
![democonsole](https://github.com/dotnet/winforms/assets/94418985/80368c22-2deb-4210-966f-bbc7f432d529)

Expected result:
The selected control should have a solid border in the DemoConsole application.
![Untitled](https://github.com/dotnet/winforms/assets/94418985/afa4d3b4-82a1-4f03-b36f-f5891d693bc1)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo.

**Comment by Nora-Zhou01** [comment]
Verified this issue in the latest .NET 9.0 SDK build: 9.0.100-preview.5.24265.9 on winforms repo, it was fixed. The selected control has a dashed border in the DemoConsole application.
![image](https://github.com/dotnet/winforms/assets/104609169/36b43ded-bc70-4166-a1fe-b3b006e77e33)

**Comment by Nora-Zhou01** [comment]
Verified the issue on 9.0.100-preview.5.24304.3 Test Pass build, the issue has been fixed that have the same results as above.
