### ISSUE TITLE
Make some internal/private VS designer sdk classes public

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#11428]
### Background and motivation

This is duplicate of https://github.com/microsoft/winforms-designer-extensibility/issues/4 in correct repo.
1. We have two (may be more?) `internal` classes: `Microsoft.DotNet.DesignTools.Client.Proxies.ProxyPropertyDescriptor` and `Microsoft.DotNet.DesignTools.Protocol.PropertyData`. It would very useful to make them `public`, I will explain with a concrete example from [chart](https://github.com/kirsan31/winforms-datavisualization) control (I think it's all clear from comments and code). The code from `protected override void ShowHelp()`. `GetPropValue` is my extension method to get property value with reflection:
```cs
GridItem item = grid.SelectedGridItem;
// Original code:
//_helpTopic = item.PropertyDescriptor.ComponentType.ToString() + "." + item.PropertyDescriptor.Name;

// We have a proxy object (Microsoft.DotNet.DesignTools.Client.Proxies.ProxyPropertyDescriptor) here as PropertyDescriptor.
// So to get real type we need get PropertyData (Microsoft.DotNet.DesignTools.Protocol.PropertyData) from PropertyDescriptor and then ComponentType from it.
// Because Microsoft.DotNet.DesignTools.Client.Proxies.ProxyPropertyDescriptor and Microsoft.DotNet.DesignTools.Protocol.PropertyData are internal we need to use reflection...
if (item.PropertyDescriptor.GetPropValue("PropertyData")?.GetPropValue("ComponentType") is Microsoft.DotNet.DesignTools.Protocol.Types.TypeIdentity typeIdentity)
    _helpTopic = typeIdentity.TypeName + "." + item.PropertyDescriptor.Name;
```
2. In `Microsoft.DotNet.DesignTools.Client.Editors.CollectionEditor` we have two `private` classes: `DefaultCollectionForm` and `DefaultViewModel`. I think it would helpful to make them public or protected with ability to extend/modify. This should make minor modifications to the default behavior easier. I find it very costly due to minimal modification to make your own dialog like in [`BaseUI\DesignableCollectionEditor`](https://github.com/KlausLoeffelmann/NetControlDesigners/tree/main/src/Samples/Previous%20Versions/Sophisticated%20-%20CollectionEditor/TileRepeater.Designer.Client/BaseUI) example.

### API Proposal

- Make `Microsoft.DotNet.DesignTools.Client.Proxies.ProxyPropertyDescriptor` and `Microsoft.DotNet.DesignTools.Protocol.PropertyData` `public`. _This is very easy and helpful change._

- Make `DefaultCollectionForm` and `DefaultViewModel` from `Microsoft.DotNet.DesignTools.Client.Editors.CollectionEditor` `public` or `protected` with some changes allowing to  extend/modify them. _It's just an idea._

### Risks

No.

### Will this feature affect UI controls?

UI controls (with designers) owners will be able to do some things easier.

**Comment by merriemcgaw** [comment]
We will be working on the next iteration of the SDK in the coming months. @KlausLoeffelmann will engage with you to help us understand what is needed here and what we can do.

**Comment by KlausLoeffelmann** [comment]
Also, these are fundamental Infrastructure classes.
We are not going to make them public, sorry.

I am looking forward, though, to discuss for .NET 10 timeframe an alternative approach for whatever domain specific problem you have in mind.
