### ISSUE TITLE
Column Borders Misalignment and Top Row Header Border Disappearance with RightToLeft and VisualStyles not Enabled

### ISSUE THREAD

**Issue by ricardobossan** [dotnet/winforms#11431]
### .NET version

9.0.100-preview.3.24204.13

### Did it work in .NET Framework?

Not tested/verified

### Issue description

During the review of [PR 11345](https://github.com/dotnet/winforms/pull/11345), we identified two issues when `RightToLeft` is set to `Yes` and `VisualStyles` is not enabled:

1. Column borders misalignment between header and body;
2. The top row header's left border disappears when there's a horizontal scrollbar and it is moved to the left.

### Screenshots:

In all images:
-  VisualStyles is not enabled.
- There's 2 DataGridView controls, for comparison purposes: the top one is RTL, the one at the bottom isn't.

#### 1. Column borders misalignment between header and body

The problem only happens on RTL and when VisualStyles is not enabled:

#### 100% Zoom:

![misaligned_visualstyles_off_zoom_100](https://github.com/dotnet/winforms/assets/30190295/ede29685-4710-463d-a0a9-53e414c194e4)

#### 400 Zoom:

![misaligned_visualstyles_off_zoom_400](https://github.com/dotnet/winforms/assets/30190295/caa378c9-bb02-4c81-bc59-a86051479b7a)

#### 2. The top row header's left border disappears when there's a horizontal scrollbar and it is moved to the left

The problem only happens on RTL and when VisualStyles is not enabled.

![disapearing_border_on_scroll](https://github.com/dotnet/winforms/assets/30190295/a045b331-10f2-4a6d-ac73-83ace1a9a928)

#### 3. Also, @Olina-Zhang noticed gaps between row and column lines in the headers and row headers when VisualStyles is not enabled

@Tanya-Solyanik , I don't know if this problem should be addressed in this issue because:

- It is barely visible at 100% Zoom;
- It happens wheter RTL is Yes or No, so I wonder if those gaps exist by design.

#### 100% Zoom:

![visualstyles_off_zoom_100](https://github.com/dotnet/winforms/assets/30190295/020fd6e9-b40f-4ca1-b382-72eaf1e03036)

#### 400% Zoom:

![visualstyles_off_zoom_400](https://github.com/dotnet/winforms/assets/30190295/511f26a7-f457-4912-9ea4-263260f87f7c)

These issues are not regressions from PR 11345. We are opening this new issue to track the column borders misalignment and the top row header border issue.

We will investigate these problems further and work towards a resolution in this new issue.

### Steps to reproduce

Create a new DataGridView form and set it to RightToLeft.Yes and do not enable VisualStyles. Sample project [here](https://github.com/dotnet/winforms/files/15467430/ScratchProject.zip).

**Comment by merriemcgaw** [comment]
We should not be making changes to anything with Visual Styles turned off.
