### ISSUE TITLE
Proposal to add "InvokeRequired" property to prevent invoke errors in some public controls

### ISSUE THREAD

**Issue by hanyoungsoo** [dotnet/winforms#11439]
Hello Framework Team.
 
Currently, I am getting an invoice error when accessing UI controls like TextBox in a C# multithreaded environment.
To prevent this, developers should write their code using InvokeRequired and Invoke methods every time.

To improve this, add the "InvokeRequired" property to the TextBox control,
Setting this property to true enables automatic invoking.
I suggest adding: This makes it simpler for developers to
You will be able to write intuitive code.

Let me show you our source as an example.
   private void logPLUS(string type, string message1, string message2 = "", int eCode = 0) {
         
          if (checkBox1.InvokeRequired) {
             checkBox1.Invoke(new Action(() => {
                if (checkBox1.Checked) { // Access text999 in Invoke
                   string logMessage = $"{Type}{(char)7}{Message1}{(char)7}{Message2}{(char)7}{eCode}" + "\r\n" + text999.Text;
                   text999.Invoke(new Action(() => { text999.Text = logMessage; }));
                }
             }));
          } else {
             if (checkBox1.Checked) {
                string logMessage = $"{Type}{(char)7}{Message1}{(char)7}{Message2}{(char)7}{eCode}" + "\r\n" + text999.Text;
                text999.Text = logMessage;
             }
          }
       }

The content is changed only when checked.
I think it's very inconvenient to have to code this in such a difficult way.
I'm sending it through Google translation, so there may be errors.
Please understand. thank you

**Comment by RussKie** [comment]
@hanyoungsoo your specific example sugests that perhaps there could be deficiencies in your architecture and implementation rather than in the Widnows Forms SDK itself. There is wealth of documentation on how to design and handle background-UI thread transitions and it is something you should consider to study.
You specific example could be rewritten in the following way:

```cs
   private void logPLUS(string type, string message1, string message2 = "", int eCode = 0) {
      if (checkBox1.InvokeRequired) {
         // transition to the UI thread
         checkBox1.Invoke(() => logPLUS(...));
      } else {
         // we're on the UI thread
      }
  }
```

Furhtermore, the check can be perfromed against the host form, which allows the whole pattern to be generalised.

**Comment by merriemcgaw** [comment]
@RussKie is correct. This is not anything that we will be able to do. Please take a look  at the architecture of your application and follow @RussKie 's guidance.
