### ISSUE TITLE
Custom CodeDomSerializer causes casting exception during serialization in Designer

### ISSUE THREAD

**Issue by Jonasmarien** [dotnet/winforms#11430]
### Environment

Version 17.9.7

### .NET version

.NET 8

### Issue description

When I create a custom CodeDomSerializer and specify it on a Component using the DesignerSerializerAttribute, a casting exception occurs whenever serialization is triggered in the Visual Studio Designer.

![image](https://github.com/dotnet/winforms/assets/14920486/3f822ee9-cfa7-4ba7-8ba9-e851598c5ab8)

Project file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

### Steps to reproduce

1. Create a new WinForms project targeting .NET 8

2. Add a WinForms UserControl
![image](https://github.com/dotnet/winforms/assets/14920486/8966cedf-9828-4384-a837-5b87503f978e)

3. Create a new MyComponent class which inherits `System.ComponentModel.Component`
```
internal class MyComponent : Component
{
}
```

4. Create a new MySerializer class which inherits `System.ComponentModel.Design.Serialization.CodeDomSerializer`
```
using System.ComponentModel.Design.Serialization;

public class MySerializer : CodeDomSerializer
{
}
```

5. Explicitly assign MySerializer to MyComponent using the `DesignerSerializerAttribute`
```
using System.ComponentModel;
using System.ComponentModel.Design.Serialization;

[DesignerSerializer(typeof(MySerializer), typeof(CodeDomSerializer))]
internal class MyComponent : Component
{
}
```

6.  Right-click MyControl and select 'View Designer'
![image](https://github.com/dotnet/winforms/assets/14920486/aea1c34b-5278-4e4b-a278-eb3c63bbec7f)

7. Open up Toolbox and drag MyComponent into the Designer view

**Note:** Here's a pre-made solution to start with. Simply start from step 6.
[https://github.com/Jonasmarien/winforms-codedomserializer-issue-reproduction](https://github.com/Jonasmarien/winforms-codedomserializer-issue-reproduction)

### Diagnostics

```text
[09:14:36.547921] fail: Request failures: Sessions/GetUpdatedRootComponentCodeDom.
                        Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: Unable to cast object of type 'WInForms.CustomSerializer.Project.MySerializer' to type 'Microsoft.DotNet.DesignTools.Serialization.CodeDomSerializer'.

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
```

**Comment by elachlan** [comment]
@Olina-Zhang Can your team please test this?

**Comment by Olina-Zhang** [comment]
@Jonasmarien this issue can be resolved using Nuget: [Microsoft.WinForms.Designer.SDK](https://www.nuget.org/packages/Microsoft.WinForms.Designer.SDK/1.9.0-preview.3.24054.5), and need to refactor the namespaces from `System.ComponentModel.Design` to `Microsoft.DotNet.DesignTools.Designers`, referring to blog: https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/

Here is my updated app based on your steps: 
[WinFormsApp22.zip](https://github.com/dotnet/winforms/files/15480686/WinFormsApp22.zip)

Video:

https://github.com/dotnet/winforms/assets/26474449/5e73df26-71fa-4ead-bbcc-7b3b4ae7fc2f

**Comment by Jonasmarien** [comment]
@Olina-Zhang Using the SDK does resolve the casting issue but causes another exception if I add the following to the serializer:

```
public class MySerializer : CodeDomSerializer
{
    public override object Serialize(IDesignerSerializationManager manager, object value)
    {
        SerializeToExpression(manager, value);
        return null;
    }
}
```

![image](https://github.com/dotnet/winforms/assets/14920486/daa94cb5-d4ec-4c29-b4d2-286b613c93e7)

Same happens when I try to call the GetExpression method, even though both are defined in CodeDomSerializerBase. 

Any idea why this exception is thrown?

**Comment by Olina-Zhang** [comment]
@Jonasmarien What about using component item in Winforms app directly?
![image](https://github.com/dotnet/winforms/assets/26474449/b26bc11d-e9d1-4d27-b5a3-7b29408d8ab2)
