### ISSUE TITLE
Visual Studio crashes when disabling form.ShowInTaskbar and calling form.ShowDialog at DesignTime in .Netcore

### ISSUE THREAD

**Issue by ChidanandMurugaiah** [dotnet/winforms#11442]
### Description

In WinForms, there is an issue where Visual Studio crashes when trying to show a form in design time after disabling the `form.ShowInTaskbar` property. I have replicated this issue by creating a custom control with a property. In the property setter, I initialize a new form, disable the `ShowInTaskBar` property, and then call the `ShowDialog` method. When I try to change the value of the property in the property window, Visual Studio crashes.

**Note: - This issue occurs only in .Netcore. It works properly in .NetFramework.**

Sample Link - [CustomControl.zip](https://github.com/dotnet/runtime/files/15434970/CustomControl.zip)

### Reproduction Steps

1.Open the Design page.
2.Drag and Drop the custom control.
3.Open the property window.
4.Change the NativeCheck method value to true.

### Expected behavior

Need to show the form properly.

### Actual behavior

Visual Studio crashes

### Configuration

Sample version - .Net80
Edition -Windows 11 Enterprise
Version - 23H2
OS build - 22631.3593
Experience - Windows Feature Experience Pack 1000.22700.1003.0
Visual Studio version - 17.9.7

**Comment by Tanya-Solyanik** [comment]
Use [DesignMode](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.component.designmode?view=net-8.0) as a starting point

**Comment by ChidanandMurugaiah** [comment]
@Tanya-Solyanik, We are not clear about your explanation regarding using DesignMode as a starting point. Could you please provide an example or a reference to clarify?

**Comment by Tanya-Solyanik** [comment]
Something like this:
if (!DesignMode)
{
    show the form
}

**Comment by ChidanandMurugaiah** [comment]
We need to display the form while interacting with the Designer, so using DesignMode is not a valid solution for our issue. Could you please provide us with an alternative solution?

**Comment by merriemcgaw** [comment]
There is a blog with instructions on how to [create complex WinForms controls for the out-of-process designer](https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/). This should answer your questions.
