### ISSUE TITLE
Drawing a line of thickness 1 issue

### ISSUE THREAD

**Issue by gc-maximloverov** [dotnet/winforms#11461]
### .NET version

8.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

When I draw a line of thickness 1 using the Graphics.DrawLine method, then the length of the line becomes larger by 1.
If I draw a line with a thickness greater than 1 along the same coordinates, then its length will be correct.
Changing property Graphics.SmoothingMode to None does not affect the result.
Also, methods Graphics.DrawPolygon and Graphics.DrawPath have the same issue.
![изображение](https://github.com/dotnet/winforms/assets/103027300/b470bbfe-89c8-4e12-847a-471c18419e21)

### Steps to reproduce

1. Run attached app: 
[DrawLineIssue.zip](https://github.com/dotnet/winforms/files/15500503/DrawLineIssue.zip)
2. Observe incorrect result.

**Comment by merriemcgaw** [comment]
This is how GDI+ is working in these scenarios. This is not something that the WinForms team is able to impact. This is the design of GDI+ and would not be changing given how many applications are designed and working today. Any changes could be extremely breaking.

**Comment by gc-maximloverov** [comment]
Ok.
