### ISSUE TITLE
VisualStudio crashes when calling fileDialog.ShowDialog at DesignTime

### ISSUE THREAD

**Issue by ChidanandMurugaiah** [dotnet/winforms#11468]
### Environment

Edition - Windows 11 Enterprise
Version - 23H2
OS build - 22631.3593
Visual Studio version - 17.10.1

### .NET version

.Netcore 6 , 7, 8

### Did this work in a previous version of Visual Studio and/or previous .NET release?

No it doesn't work on previous netcore releases. 

### Issue description

I am attempting to initialize a `FileDialog` (either `SaveFileDialog` or `OpenFileDialog`) and call the `fileDialog.ShowDialog` method within a custom control's property setter. When I try to change the property value in the property window at **DesignTime**, Visual Studio crashes.

For your reference, I have attached a simple sample that replicates the issue.
Sample - [FileDialog_Crash.zip](https://github.com/user-attachments/files/15518020/FileDialog_Crash.zip)

### Steps to reproduce

1.Drag and Drop the CustomControl from the toolbox.
2.Change the value of the NativeCheck property to true.

Expected Behavior : - FileDialog needs to be open.
Observed Behavior : - VS crashes

**Comment by elachlan** [comment]
Try the `FileNameEditor` https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.design.filenameeditor?view=windowsdesktop-8.0&viewFallbackFrom=net-8.0

**Comment by ChidanandMurugaiah** [comment]
We instWe installed the Microsoft.Winforms.Designer.SDK package in our real-time application. However, FileNameEditor is not available for .NET Core. Additionally, we need to display the file dialog when selecting the DesignerVerb at design time. Is there an alternative way to show the file dialog at design time for .NET Core?

**Comment by elachlan** [comment]
@Olina-Zhang can your team please review this? `FileNameEditor` looks like it exists in main branch. I am unsure if it was added in .net9? 

@ChidanandMurugaiah I think the alternative is to create your own editor based on the code in:
https://github.com/dotnet/winforms/blob/4819717a216a80d82b7d174344e5d0ce69029ccd/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FileNameEditor.cs#L13-L58

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang can your team please review this? `FileNameEditor` looks like it exists in main branch. I am unsure if it was added in .net9?

FileNameEditor doesn't exist yet in .NET 9 SDK.

**Comment by KlausLoeffelmann** [comment]
You always need to make sure, that you call any Editor from the client (so from within Visual Studio).
The server process must not show any dialogs.

Especially Type Editors which show modal Dialogs are a bit tedious to migrate, I get it.
But we have templates which simplify that work.

This blog post helps to ramp you up and provide additional links.
https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/

**Comment by merriemcgaw** [comment]
@Olina-Zhang  please open an issue in the designer repo to track making sure VS doesn't crash when we encounter ShowDialog at design time.
