### ISSUE TITLE
publish single file doesnt seem to work anymore

### ISSUE THREAD

**Issue by gen-angry** [dotnet/winforms#11473]
### .NET version

```
.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.4e5ea2d8
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET 8.0.0 

Compiled at Jan 6, 2024 without issues.

### Issue description

When I try to compile a single file exe, it does not publish anything

In Visual Studio, Build -> Publish, Folder, then target runtime=win-x64, framework dependent, check on 'produce single file'. It will compile the Release build in `/bin/Release` with all DLLs separate from the executable but does not produce a publish folder no matter where I put it or if it exists or not. There's also no errors showing in the output log.

It used to produce a single EXE for all of my projects in `/bin/publish` folder. I have not changed them in months and the last time I compiled them, it created the EXEs just fine. I went to fix a bug in one project, tried to compile it and got this issue. Loaded another project from January 6 that hadn't been touched since and it had the same publishing issue. Created a brand new winforms project, didn't change a thing in the codebase itself, tried to publish that with the same settings and same issue.

Googling around doesn't seem to have any help, all other similar types of issues that I was able to find had some kind of error in the output. As far as I can tell, it compiles just fine, just doesn't actually pack the files.

The only change since last compile was updating VS Community 2022 to 17.10.1.

Running `dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true` via command line does work strangely enough.

### Steps to reproduce

- Create new blank WinForms project.
- Go to build -> publish -> to folder
set configuration to 'release'
target framework to 'net8.0-windows'
deployment tools to 'framework dependent'
target runtime to 'win-x64'
target location doesn't matter, I left it as default 'bin\Release\net8.0-windows\publish\win-x64\'
check on 'produce single file'
- click publish. It will compile then show this in the output
```
Build started at 12:27 AM...
1>------ Build started: Project: WinFormsApp1, Configuration: Release Any CPU ------
1>WinFormsApp1 -> C:\Users\aland\Desktop\New folder\WinFormsApp1\bin\Release\net8.0-windows\WinFormsApp1.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 12:27 AM and took 01.390 seconds ==========
```
It will have the 'release' files under `\bin\Release\net8.0-windows` with all the separate DLLs, but no `publish\win-x64\` folder in there.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this?

**Comment by Olina-Zhang** [comment]
Tested VS: 17.10.1 and the latest VS build. All cannot repro when did publish operation with targeting .NET 8.0 in VS, it has publish\win-x64 folder 
![image](https://github.com/dotnet/winforms/assets/26474449/82d3c18e-928f-47f7-ab7a-ab1158eda898)

**Comment by gen-angry** [comment]
Strange. I just tried it again, same result:

![Screenshot 2024-06-03 171403](https://github.com/dotnet/winforms/assets/39675299/d62c0623-9541-44f9-8dea-988ac71b71ed)

(clicking the folder link after publishing brings up the 'does not exist' error popup)

![Screenshot 2024-06-03 171245](https://github.com/dotnet/winforms/assets/39675299/d6df101c-846d-43a3-86dd-206522dba7c8)

Is there something I can send/run that would help figure this one out?

For now I can just use the command line as that seems to work.

**Comment by Olina-Zhang** [comment]
How about other Target runtime: win-x86, or win-arm64? I tried it in Visual Studio to publish, all works, can find these folders. Can you please try to repair your VS to see if issue can be resolved?
Here is my result:
![image](https://github.com/dotnet/winforms/assets/26474449/e731ded8-7d1f-4883-a03b-c7d1561acbb9)

**Comment by gen-angry** [comment]
Just tried it with win-x86, win-arm, linux-x64. Deleted the Release folder every time to make sure it generates a fresh copy. They all produce a windows x64 executable (according to task manager) in the Release folder and no publish folder. It's like it doesn't matter what 'Target Runtime' says. Strange.

Will try to do a repair and post back.

**Comment by gen-angry** [comment]
Did VS repair then rebooted. It signed me back in after rebooting and set it back up. Same issue with the test project. All versions 'compile' as a win-x64 executable in the end regardless of what I target, and does not create a publish folder.

Generated a brand new winforms project the same way, tried to publish and same issue.

Generated a new project targeting .NET 6.0, same issue for that version.

Generated a new project it in a different location without spaces in path in case that might have been it, same issue. 

Generated another new project on a different drive with no spaces in path, same issue.

Cleaned out older versions of .NET runtimes aside from the latest from each major (I have projects in 6, 7, and 8). Same issue. :(


I'm not sure what else I could try aside from reinstalling Windows entirely which I really don't want to do.

**Comment by merriemcgaw** [comment]
@gen-angry have you tried building and publishing from the command line rather than Visual Studio?

**Comment by gen-angry** [comment]
> @gen-angry have you tried building and publishing from the command line rather than Visual Studio?

Yes, in the initial report

> Running `dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true` via command line does work strangely enough.

**Comment by merriemcgaw** [comment]
Unfortunately, we can't reproduce the problems on our end and since you have a publish working from the command line, there's not much more we can do here. I would report this via VS Feedback because they will collect better telemetry and get it to the correct team.
