### ISSUE TITLE
NativeHost crash for debug version on .Net 8.0

### ISSUE THREAD

**Issue by daliuzhen1** [dotnet/winforms#11482]
### .NET version

Version is .net8.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes. It works fine for .Net 7.0 

### Issue description

NativeHost.exe crash for .net 8.0 debug version.  It works fine for release version on .net 8.0. It also works fine for other .net version
![image](https://github.com/dotnet/winforms/assets/11794711/b8c6315f-40d7-4445-a47c-74b5d060c6a1)

### Steps to reproduce

1. Build NativeHost on release/8.0 branch with debug version.
2. Run it and you will get crash issue

**Comment by raazuregai** [comment]
Not work in .NET 8.0.202

**Comment by elachlan** [comment]
I cannot reproduce this on main branch. Application launches and I can click "button1".

**Comment by elachlan** [comment]
@daliuzhen1 What version of visual studio are you using and how are you launching the winforms project?

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test the release/8.0 branch?

**Comment by Olina-Zhang** [comment]
I can repro it for debug version on release/8.0 branch when running NativeHost project as following, not in Main branch.
![image](https://github.com/dotnet/winforms/assets/26474449/d9e025ef-9e7a-44e9-8115-b5f8948d1e1e)

**Comment by merriemcgaw** [comment]
@daliuzhen1 This is our test application, and we would recommend that you work with main rather than the release branches. This doesn't appear to be an issue in the current builds of Main.
