### ISSUE TITLE
RichTextBox will not redraw the last pixel column on resize

### ISSUE THREAD

**Issue by SteffenSchwaiger** [dotnet/winforms#11485]
### .NET version

.NET 9 Preview 4

### Did it work in .NET Framework?

Yes

### Issue description

When an anchored (or docked) RichTextBox is resized due to the resizing of the parent control, the last column of pixels is sometimes not cleared / redrawn. It appears as if the previously rendered text remains.

![image](https://github.com/dotnet/winforms/assets/5320760/e677b82b-49a0-4047-ae7c-9fecaed7000a)

### Steps to reproduce

Create a new `Form`-Instance with the following constructor code:

```csharp
public Form1()
{
    // Text fits exactly
    Size = new Size(290, 150);

    var rtb = new RichTextBox()
    {
        BorderStyle = BorderStyle.None,
        Dock = DockStyle.Top,
        Font = new Font("Segoe UI", 12),
        ReadOnly = true,
        ScrollBars = RichTextBoxScrollBars.None,
        Text = "Lorem ipsum dolor sit amet, consetetur"
    };

    var btn = new Button()
    {
        Dock = DockStyle.Bottom,
        Text = "Resize"
    };

    btn.Click += (s, e) =>
    {
        // Reduce the size by 1px
        Size = new Size(Size.Width - 1, Size.Height);

        btn.Enabled = false;
    };

    Controls.Add(btn);
    Controls.Add(rtb);
}
```

Initial visialization => OK
Click the resize button once => NOK

![image](https://github.com/dotnet/winforms/assets/5320760/9dbb4252-abc7-4816-ac94-5bbe89fccd4c)

If I diff those two screenshots I get the following image (notice the unchanged tip of the letter "r" on the top right).
![image](https://github.com/dotnet/winforms/assets/5320760/f1b58284-a7e3-4588-8dce-ff631adbf1f9)

I am not sure why the letter "t" also changed, but that would be another issue.
![image](https://github.com/dotnet/winforms/assets/5320760/8d6828cc-94e3-4c60-ac9a-0bd73f4a2306)

**Comment by elachlan** [comment]
Excellent bug report! Thank your for the image diff.

@Olina-Zhang can your team please test this?

**Comment by SteffenSchwaiger** [comment]
@Nora-Zhou01 Interesting! I was not able to reproduce it with .NET Framework 4.5.2 (our current target framework version), but did not try it with .NET Framework 4.8 tho.

It looks like the bug was introduced between .NET Framework 4.5.2 and 4.8.

![image](https://github.com/dotnet/winforms/assets/5320760/855bd882-d6bf-4fdd-829f-4d81d0db994d)

**Comment by merriemcgaw** [comment]
We updated the version of riched20.dll that we wrapped sometime around 4.6 if memory serves. @Tanya-Solyanik do you recall? I wouldn't be surprised if this is more of a Windows/Richedit issue than something WinForms is able to control directly.

**Comment by elachlan** [comment]
Is it something that can be tested with MFC? That would isolate it, wouldn't it?

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team go ahead and test this in MFC?
@KlausLoeffelmann  - you said you were touching the RichTextBox potentially so keep this in mind when you do.

**Comment by John-Qiao** [comment]
@merriemcgaw @elachlan @SteffenSchwaiger we can add below quirk in App.config file to disable richedit30.dll for RichTextBox control when project target to .NET Framework 4.8 or 4.8.1.

```
	<runtime>
		<AppContextSwitchOverrides value="Switch.System.Windows.Forms.DoNotLoadLatestRichEditControl=true"/>
	</runtime>
```
![Framework](https://github.com/dotnet/winforms/assets/45864985/63fa171f-515c-4084-abaf-63911a2c2cc1)

In .NET Project, we can create a new RichTextBox2 class to use the richedit20.dll version. Like below code snippet:

```
    public class RichTextBox2 : RichTextBox
    {
        protected override CreateParams CreateParams
        {
            get
            {
                if (moduleHandle == IntPtr.Zero)
                {
                    moduleHandle = LoadLibrary("Riched20.dll");
                    if ((long)moduleHandle < 0x20) throw new Win32Exception(Marshal.GetLastWin32Error(), "Could not load Riched20.dll");
                }
                var cp = base.CreateParams;
                cp.ClassName = "RichEdit20W";
                return cp;
            }
        }
        private static IntPtr moduleHandle;

        [DllImport("kernel32.dll", CharSet = CharSet.Auto)]
        static extern IntPtr LoadLibrary(string lpFileName);
    }
```
![Core](https://github.com/dotnet/winforms/assets/45864985/02e6dd74-0ce5-4803-a44e-37eaddbf43c6)

**Comment by elachlan** [comment]
@John-Qiao can you please test MFC to verify it is indeed a newer richedit version issue?

**Comment by John-Qiao** [comment]
@elachlan I'm not familiar with MFC project, I will try to create a MFC project and test it, but I'm not sure if it will work.

**Comment by elachlan** [comment]
Maybe @Olina-Zhang can help?

**Comment by merriemcgaw** [comment]
Or @LeafShi1 ?

**Comment by merriemcgaw** [comment]
@SteffenSchwaiger this bug is about which version of the Rich Text Box control is loaded at runtime by WinForms. @John-Qiao has provided instructions above to reference the earlier versions, which may not produce this issue. This is something that would need a fix from the Office team and Windows to take the fix. I would recommend following @John-Qiao's approach instead.
