### ISSUE TITLE
Controls docked to bottom of SplitContainer within another SplitContainer slowly shift off bottom of panel.

### ISSUE THREAD

**Issue by troymac1ure** [dotnet/winforms#11507]
### Environment

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.3

### .NET version

.NET Framework 4.6.1

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Unknown.

### Issue description

If a horizontally split SplitContainer is placed inside another horizontally split SplitContainer and a control is anchored to the bottom when both SplitContainers have a SplitterWidth of 1, it will creep down when the form is saved in Designer mode, the designer is closed and then re-opened again. 

### Steps to reproduce

Add SplitContainer, set Orientation to Horizontal and splitterWidth to 1. Add a second SplitContainer to the top panel, set it's Orientation to Horizontal and splitterWidth to 1 as well. Add a label to the bottom panel of the second SplitContainer, Anchor it to the Bottom Right and place it in the very bottom right corner. Note the height. Save the form and open the code section. Close the designer section. Re-open the designer section and the label will have shifted down 3 pixels.
Note that it seems to be okay if the second Splitcontainer's SplitterWidth is set to 4 or higher.

**Comment by merriemcgaw** [comment]
This looks like an issue with the in-process .NET Framework based designer in Visual Studio. This repo is for the .NET 5+ runtime component of WinForms. Please use VS Feedback to submit this issue as it will get to the right team and provide us with diagnostics.
