### ISSUE TITLE
In .NET code is going to exception section when we are trying to convert a sensitivity label doc file to docx format. Exception is Command failed

### ISSUE THREAD

**Issue by ASHISDEY1998** [dotnet/winforms#11501]
### .NET version

 8.0.104

### Did it work in .NET Framework?

Yes

### Issue description

Here is the code I am currently using 

Microsoft.Office.Interop.Word.Application wordApp = new Microsoft.Office.Interop.Word.Application();
var sourceFile = new FileInfo(path);
try
{
    var document = wordApp.Documents.Open(sourceFile.FullName);
    string newFileName = Path.Combine(Path.GetDirectoryName(sourceFile.FullName), Path.GetFileNameWithoutExtension(sourceFile.FullName) + "_c.docx");
    document.SaveAs2(newFileName, Microsoft.Office.Interop.Word.WdSaveFormat.wdFormatXMLDocument,
                     CompatibilityMode: Microsoft.Office.Interop.Word.WdCompatibilityMode.wdCurrent);

    document.Close();
    GC.Collect();
    wordApp.Quit();
    Marshal.FinalReleaseComObject(wordApp);
    return newFileName;
}
catch (Exception ex)
{
    errorLogger.LogException(ex);
    GC.Collect();
    wordApp.Quit();
    Marshal.FinalReleaseComObject(wordApp);
    return string.Empty;
}

this code I am using to take a doc file and convert it to docx.

its working fine for normal file but when I try to use document with sensitivity label added in it its directly going to exception and giving me ex = {"Command failed"} error.

### Steps to reproduce

Try to upload a doc file which is having sensitivity label its going to exception.

**Comment by merriemcgaw** [comment]
The Office products do not support automation with .NET 5+. You can continue to use .NET Framework for your Office automation needs however.
