### ISSUE TITLE
Define new scopes for AppContext switches for use in tests

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#11536]
1. replace use cases of [SetLocalAppContextSwitchValue](https://github.com/search?q=repo%3Adotnet%2Fwinforms%20SetLocalAppContextSwitchValue&type=code) in tests with custom scope for each switch see [BinaryFormatterScope](https://github.com/search?q=repo%3Adotnet%2Fwinforms%20BinaryFormatterScope&type=code) example.
2. Replace use cases of TestAccessor like this one - https://github.com/dotnet/winforms/blob/29528171490190df28fd4afc89dee271ebfef68b/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Dpi/FormDpiTests.cs#L111 with AppContext switch scopes as well

**Comment by elachlan** [comment]
@Tanya-Solyanik can we resolve this now? I am not sure if the PR covered everything. I thought I got all the usages, but could be wrong.
