### ISSUE TITLE
ShowDialog Intercept Noise

### ISSUE THREAD

**Issue by EVA-SS** [dotnet/winforms#11532]
### .NET version

.NET 6.0
.NET Framework

### Did it work in .NET Framework?

Yes

### Issue description

ShowDialog Clicking on other places will make noise, and I want to intercept the noise and mute it

### Steps to reproduce

ShowDialog();

**Comment by EVA-SS** [comment]
in AntdUI/AntdUI#9 Can it be resolved through `WndProc (ref Message m)`?

**Comment by merriemcgaw** [comment]
StackOverflow may be a better place to find answers to this question. WinForms won't want to enable intercepting this noise from our end for accessibility reasons.
