### ISSUE TITLE
ParentControlDesigner/ComponentDesigner is not instantiated/initialized

### ISSUE THREAD

**Issue by CortiWins** [dotnet/winforms#11531]
### Environment

Version 17.10.2

### .NET version

.Net 8.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Net Framework 4.8 and earlier

### Issue description

I tracked down issues with much more complicated controls (_including crashing visual studio_) to the minimum example attached.
This exact code works in Net4.8 but does not in Net8/7. The designer class derived fromParentControlDesigner is neither instanced nor initialized.

The UserControl
```
[System.ComponentModel.Designer(typeof(TestUserControlDesigner))]
public partial class TestUserControl : UserControl
{
    public TestUserControl()
    {
        InitializeComponent();
    }
    [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
    public Panel ContentPanel => this.pnlContent;
}
```
The Designer
```
public class TestUserControlDesigner : System.Windows.Forms.Design.ParentControlDesigner
{
    public TestUserControlDesigner()
    {
        MessageBox.Show("Create NetCore TestUserControlDesigner");
    }

    public override void Initialize(System.ComponentModel.IComponent component)
    {
        MessageBox.Show("Initialize NetCore TestUserControlDesigner");
        base.Initialize(component);
        if (this.Control is TestUserControl group)
        {
            this.EnableDesignMode(group.ContentPanel, "EditablePanel");
        }
    }
}
```
This solution contains projects for net4.8 and Net8 for a direct comparison
[UserControlDesignerIsNotCalledExample.zip](https://github.com/user-attachments/files/15827196/UserControlDesignerIsNotCalledExample.zip)

### Steps to reproduce

The attached project contains the code to reproduce the discreprancy between net4.8 and Net8.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this?

**Comment by Zheng-Li01** [comment]
@CortiWins  this issue can be resolved using Nuget: [Microsoft.WinForms.Designer.SDK](https://www.nuget.org/packages/Microsoft.WinForms.Designer.SDK/1.9.0-preview.3.24054.5), and need to refactor the namespaces from System.ComponentModel.Design to Microsoft.DotNet.DesignTools.Designers, referring to blog: https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/
![GHIssue11531](https://github.com/dotnet/winforms/assets/38325459/7d44af46-9cb4-466e-9e06-d0ef8faf9174)

**Comment by elachlan** [comment]
@KlausLoeffelmann maybe we should add an analyzer for this?

**Comment by CortiWins** [comment]
Okay, so using Microsoft.WinForms.Designer.SDK solved it for me, but required one more change to the codebase.

And for future searchers and finders of this topic:
While the Assembly containing the System.Windows.Forms.Design.ParentControlDesigner is available during runtime, the assembly that contains Microsoft.DotNet.DesignTools.Designers.ParentControlDesigner is not.

This means, that Reflection that resolves all included Type-dependencies ( like Assembly.GetTypes() ) on the assembly that contains the designer-class will now lead to a "file not found" exception during runtime.

**Comment by merriemcgaw** [comment]
I think we'd want to put this analyzer in our Designer SDK rather than here, so @Olina-Zhang can you please take a moment to create an issue in the designer repo to track the suggestion if we don't have it already?

**Comment by Zheng-Li01** [comment]
@merriemcgaw  filed GH DT https://github.com/microsoft/winforms-designer/issues/6002 to track this.
