### ISSUE TITLE
The DataGridViews overlap after a certain row when they are placed within the FlowLayoutPanel in WinForms

### ISSUE THREAD

**Issue by SwathiDhatchanamoorthi** [dotnet/winforms#11552]
### .NET version

.Net 8.0

### Did it work in .NET Framework?

No

### Issue description

While setting the width and height of the DataGridView based on all its rows and columns and using two DataGridViews in the FlowLayoutPanel, a rendering issue occurred when using more than 1311 records in one of the DataGridViews. It works fine for 1310 records.

![image](https://github.com/dotnet/winforms/assets/102227044/e5a4352b-67d0-402b-9b21-eb6595f2035b)

 
[DataGridView_Overlapping](https://www.syncfusion.com/downloads/support/common/6351/ze/DataGridView_Overlapping_c4d9687f.zip)

### Steps to reproduce

1.Run the sample.
  
Observed Behavior:
The DataGridView overlapped with the other DataGridView, causing a rendering issue.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this?

**Comment by Syareel-Sukeri** [comment]
The attached sample project is currently inaccessible due to a permission issue. Could you kindly resend the sample project so we can accurately reproduce and investigate the issue? Thank you.

**Comment by sethuramkumar** [comment]
@Syareel-Sukeri Please find the sample here:
[DataGridView_Overlapping.zip](https://github.com/user-attachments/files/15924083/DataGridView_Overlapping.zip)

**Comment by Zheng-Li01** [comment]
@sethuramkumar thanks the project provided by you.

@elachlan, the issue can reproduce on both .NET Framework from 4.7 ~ 4.8.1 and .NET from 6.0 ~ 9.0.

For .NET: the issue can reproduce when the data more than 1311 records.
![11552Core](https://github.com/dotnet/winforms/assets/38325459/b7acb32c-2d71-45a7-9a1c-4fa6d837697b)
For .NET Framework: the issue can reproduce when the data more than 1490 records.
![11552Framework](https://github.com/dotnet/winforms/assets/38325459/8b7f4c91-e0c2-427a-80e3-08f3dcd9cba6)

**Comment by merriemcgaw** [comment]
@SwathiDhatchanamoorthi  This is primarily an issue with the layout of the application and there are many ways you can address this in the application. This is not something we will change on the WinForms side.

**Comment by merriemcgaw** [comment]
@SwathiDhatchanamoorthi  This is primarily an issue with the layout of the application and there are many ways you can  address this in the application.

**Comment by merriemcgaw** [comment]
Have you considered a TableLayoutPanel insider the FlowLayoutPanel? You can check on StackOverflow, or use ChatGPT or GitHubCopilot to help you lay things out. Unfortunately, this is not a forum for design and layout questions, so I have to leave this issue closed.
