### ISSUE TITLE
[Accessibility] HC themes: toolStripMenuItem is highlighted in unfocused state when its check property is enabled

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#11550]
### .NET version

.NET 9.0 SDK build: 9.0.100-preview.6.24318.4

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue. Not reproduced on NET 8.0 and earlier versions of NET 9.0 (https://github.com/dotnet/winforms/issues/9166). 

### Issue description

toolStripMenuItem is highlighted in unfocused state when its check property is enabled, this causes the color contrast of indeterminate state icon for toolStripMenuItem is less than 3:1.
![image](https://github.com/dotnet/winforms/assets/86937911/38f9a169-b2ef-4149-b640-90fc5e1c7358)

### Steps to reproduce

Use following test sample application:
[WinFormsApp24.zip](https://github.com/user-attachments/files/15898677/WinFormsApp24.zip)

**Comment by LeafShi1** [comment]
This issue caused by PR #9933

**Comment by MelonWang1** [comment]
Verified this issue on the latest .NET 9.0.100-preview.7.24353.17, it was fixed. The drop-down menu of the toolStripMenuItem is unhighlighted in unfocused state.
![Untitled](https://github.com/dotnet/winforms/assets/94418985/7111f393-2b1a-4c01-b2cb-24b1e55c3f6d)
