### ISSUE TITLE
No 8.0.5 or 8.0.6 release?

### ISSUE THREAD

**Issue by fergusbown** [dotnet/winforms#11580]
### .NET version

.net 8

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

N/A

### Issue description

There are bug fixes that have been made, and merged to the .net 8 branch, but the last two patch release seem to have been skipped.

is there an ETA for when the next 8.0.* release will become available?

Thanks in advance

Fergus

### Steps to reproduce

N/A

**Comment by lonitra** [comment]
Links to .NET 8 releases can be found at https://github.com/dotnet/core/blob/main/release-notes/8.0/README.md and 8.0.7 should be available July 9. Was there a specific bug fix you were looking for?

**Comment by fergusbown** [comment]
Morning


I'm looking for https://github.com/dotnet/winforms/issues/11243
specifically!


Thanks


Fergus

**Comment by lonitra** [comment]
Yep, that fix is in 8.0.7, which should be available July 9 :)
