### ISSUE TITLE
BinaryFormatter error when clicking "Add Tab" command for TabControl in DemoConsole application

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#11607]
### .NET version

.NET 9.0: Main branch of WinForms repo (.NET 9.0.0-preview.7.24326.3)

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue. Not repro on .NET 9.0.0-preview.6.24305.2

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, BinaryFormatter error when clicking "Add Tab" command for TabControl.

![image](https://github.com/dotnet/winforms/assets/86937911/5a6f1340-8cef-4205-901d-f81d8da3a72c)

https://github.com/dotnet/winforms/assets/86937911/f86da6ba-fee0-452b-bb45-ca4cdb663f3f

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

### More Info:
This issue also reproduces on ImageList when clicking the "Add" command.
![image](https://github.com/dotnet/winforms/assets/86937911/b0be0bd0-c88f-45f7-816d-0c37da670bb2)

**Comment by elachlan** [comment]
Related to #9428 and #6267

We had similar issues when BinaryFormatter was marked as obsolete #9416

**Comment by LeafShi1** [comment]
This issue appears after PR #11540

**Comment by LeafShi1** [comment]
This issue disappear after add binary Formatter package (Related PR #11741)

**Comment by John-Qiao** [comment]
Verified the issue on the latest DemoConsole test app of Winforms repo from main branch, it was fixed: no exception occurs when clicking "Add Tab" command for TabControl now.

https://github.com/user-attachments/assets/3a17a452-5ceb-46f0-ae04-8cdacbeda9c5
