### ISSUE TITLE
Form and controls are not scaled well on HDPI primary monitor when setting custom ApplicationDefaultFont

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#11608]
### .NET version

9.0.100-preview.7.24323.5

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it cannot repro in .NET 8.0

### Issue description

When setting custom ApplicationDefaultFont for Winforms .NET 9.0 application, added controls and form are not scaled well on HDPI primary monitor, especially the larger the DPI value, the more pronounced the results look

150%DPI with .NET 9.0:
![image](https://github.com/dotnet/winforms/assets/26474449/129344aa-bb77-4738-9709-4ac85d44fd24)
225%DPI with .NET 9.0:
![image](https://github.com/dotnet/winforms/assets/26474449/d92ae42b-87ea-4d25-9fa7-ceb90fe674b8)
225%DPI with .NET 8.0:
![image](https://github.com/dotnet/winforms/assets/26474449/d6af5b03-d9c7-457c-820e-98df99ede0d7)

### Steps to reproduce

1. Create a Winforms .NET 9.0 app 
2. In .csproj file, add following ApplicationDefaultFont content:
`<ApplicationDefaultFont>Calibri,13pt,style=regular</ApplicationDefaultFont>`
3. Open form designer, add some controls
4. Build and run app on HDPI primary monitor

**Comment by kirsan31** [comment]
I want to add some more details:
1. The bug exist only with `csproj + ApplicationConfiguration.Initialize();`. If instead we set font in `Program.cs` like this: `Application.SetDefaultFont(new System.Drawing.Font("Calibri", 13));` - all work fine.
2. The bug exist  only when you start app in high dpi. When start with 100% and then increase - all work fine.

**Comment by merriemcgaw** [comment]
@kirsan31 - thank you for the details!

**Comment by elachlan** [comment]
Issue was found when testing PR #11206

**Comment by Epica3055** [comment]
This issue is caused by [PR 10525](https://github.com/dotnet/winforms/pull/10525)

**Comment by Syareel-Sukeri** [comment]
Verified this issue in the latest .NET 9.0.100-rc.1.24407.33, it was fixed: Form and controls are scaled well on HDPI primary monitor when setting custom ApplicationDefaultFont. The results are the same as below.

**150% DPI**
![150 DPI](https://github.com/user-attachments/assets/0cd053ee-a175-4965-87a3-38e23072ad9f)

**200% DPI**
![200 DPI](https://github.com/user-attachments/assets/c8dca9fb-dd1c-45a6-9925-dad736e74d8e)

**Comment by John-Qiao** [comment]
Verified this issue with .NET 9.0.100-rc.1.24422.10 test pass build, it has been fixed and the test result is same as above.

**Comment by John-Qiao** [comment]
Verified this issue with .NET 9.0.100-rc.1.24452.12 test pass build, it has been fixed and the test result is same as above.
