### ISSUE TITLE
missing support for complex DataBinding

### ISSUE THREAD

**Issue by VaporiZed** [dotnet/winforms#11616]
### Environment

Microsoft Visual Studio Community 2022 (64-Bit) - Preview, Version 17.11.0 Preview 2.1, german language pack

### .NET version

.NET 7, .NET 8

### Did this work in a previous version of Visual Studio and/or previous .NET release?

not in .NET
only in .NET Framework, e.g. 4.8.1

### Issue description

If I want to use complex DataBinding for ListBoxes or ComboBoxes, I miss the options to select valid possibilities/properties via the smarttag internal ComboBoxes. I have to input the names of the properties manually. Even worse: The property »selected value« can't be used at all. I have to add a databinding code line into the FormX.Designer.VB by myself.
![DesignerIssue](https://github.com/dotnet/winforms/assets/49878115/c089a59f-76ff-4d4a-a6e6-e13f2095b95e)

### Steps to reproduce

1. create a new WinForms project, either with C# or VB.NET
2. open the designer of the only existing form
3. add a ListBox (LB) or a ComboBox (CB) to the form
4. select the LB/CB and click on the [>] to open the smart tag/advanced control options
5. activate »use data bound items«
6. You see just one combobox to select the datasource for the LB/CB. The next three boxes below are just textboxes, which can't be used like the comboboxes in the .NET framework designer to select the databinding-properties of the selected datasource.

**Comment by Zheng-Li01** [comment]
There has a known issue in the designer repro to track https://github.com/microsoft/winforms-designer/issues/1209

**Comment by VaporiZed** [comment]
The mentioned link is dead. 404

**Comment by elachlan** [comment]
@VaporiZed designer repo is currently closed source, so we can't see the linked issues.
