### ISSUE TITLE
BinaryFormatter error when Copy/Cut/Paste menu item in DemoConsole application

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#11617]
### .NET version

.NET 9.0: Main branch

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

n/a

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, BinaryFormatter error when clicking `Copy`/`Cut`/`Paste` commands for Menu Item.

![image](https://github.com/dotnet/winforms/assets/2433737/9c968b5f-88c0-4ef3-afc0-3195344b752c)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

Related: #6267 / #6269

**Comment by LeafShi1** [comment]
After PR#11540, the error` System.PlatformNotSupportedException: 'BinaryFormatter serialization and deserialization have been removed.` appears

Before this PR, executing Copy/Cut/Paste menu item get different error, the error is 
![image](https://github.com/dotnet/winforms/assets/132890443/6c9163a4-ebb3-4156-9756-6c32099d7450)

**Comment by LeafShi1** [comment]
This BinaryFormatter error disappear after add binary Formatter package (Related PR https://github.com/dotnet/winforms/pull/11741)

**Comment by lonitra** [comment]
We're dependent on BinaryFormatter for CodeDomSerialization and adding the package fixes the issue

**Comment by Zheng-Li01** [comment]
Verified the issue on the latest DemoConsole test app of Winforms repo from main branch, it was fixed: no error when Copy/Cut/Paste menu item in DemoConsole application.
![GHIssue11617](https://github.com/user-attachments/assets/4e357ab2-8eb4-4f1d-9426-bd470d446265)
