### ISSUE TITLE
Undo fails to restore deleted TabControl in TableLayoutPanel in DemoConsole application

### ISSUE THREAD

**Issue by Syareel-Sukeri** [dotnet/winforms#11628]
### .NET version

.NET 9.0: Main branch of WinForms repo (.NET 9.0.100-preview.7.24353.17)

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue. Not repro on .NET 9.0.0-preview.5.24306.7

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, undo process of deleting TableLayoutPanel contained TabControl does not work properly. TabControl disappears after clicking Undo a few times

https://github.com/dotnet/winforms/assets/156630333/16d261c4-e642-46bb-a48a-8abd9f0d310f

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

## More Info

1. The issue cannot be reproduced when other controls are in the TableLayoutPanel.
2. When moving controls within TableLayoutPanel and using undo, it takes up to 3 clicks to restore the original state.

https://github.com/dotnet/winforms/assets/156630333/bd7875a6-5189-4776-a27b-d1a4f850eb6b

3. Reproduce the same result when using Ctrl+Z to undo.

**Comment by JeremyKuhne** [comment]
Possibly BinaryFormatter related?

**Comment by lonitra** [comment]
Could also be same root cause as https://github.com/dotnet/winforms/issues/11657

**Comment by LeafShi1** [comment]
This issue disappear after add binary Formatter package in DemoConsole project (Related PR https://github.com/dotnet/winforms/pull/11741)

**Comment by lonitra** [comment]
We're dependent on BinaryFormatter for CodeDomSerialization and adding the package fixes the issue

**Comment by Olina-Zhang** [comment]
Verified this issue on winforms repo from main branch, it was fixed: undo process of deleting TableLayoutPanel contained TabControl successfully.

https://github.com/user-attachments/assets/ca04f7e8-1142-4596-b251-276a7292d962
