### ISSUE TITLE
BinaryFormatter error when changing added DataGridView column to other ColumnType in DemoConsole application

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#11627]
### .NET version

9.0.100-preview.7.24353.17

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, not repro in .NET 8.0 

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo's main branch, BinaryFormatter error when changing added DataGridView column to other ColumnType in DemoConsole application

https://github.com/dotnet/winforms/assets/26474449/d9104168-1a8c-4706-97da-37cd63b761da

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by ricardobossan** [comment]
@LeafShi1 @Tanya-Solyanik Seems this is solved by PR #11614 :

![solved_by_11614](https://github.com/dotnet/winforms/assets/30190295/c33af038-6f4f-4efd-b0df-0d3e3c22c629)

**Comment by LeafShi1** [comment]
This issue disappear after add binary Formatter package (Related PR https://github.com/dotnet/winforms/pull/11741)

**Comment by Philip-Wang01** [comment]
Verified the issue on the latest DemoConsole test app of Winforms repo from main branch, it was fixed: no error message when changing added DataGridView column to other ColumnType now.

https://github.com/user-attachments/assets/58d4e173-09aa-4887-8dd9-31fa3e22463a
