### ISSUE TITLE
Error while running test application on winforms repo 

### ISSUE THREAD

**Issue by MandiMan** [dotnet/winforms#11629]
### .NET version

Latest winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it cannot repro in last week .NET 9.0 E2E testing on winforms repo

### Issue description

Clone winforms repo then use start-vs.cmd, cmd output Build succeded, but running WinformsControlsTest app has error

Actual result:
Error while running WinformsControlsTest app
![image](https://github.com/dotnet/winforms/assets/108860782/6f84bec0-c32d-41d0-8589-2617e63e3408)
Expected result:
Run WinformsControlsTest app successfully with no error

### Steps to reproduce

1. Clone winforms repo: https://github.com/dotnet/winforms.git
2. Run WinformsControlsTest app

**Comment by MandiMan** [comment]
This issue looks like it's related to this PR：https://github.com/dotnet/winforms/pull/11603

**Comment by elachlan** [comment]
@MandiMan are you using the preview version of visual studio?

**Comment by MandiMan** [comment]
> @MandiMan are you using the preview version of visual studio?

Yes, I'm using 17.12.0 Preview 1.0 [35104.6.main].

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team scan Roslyn and runtime repos related to something missing here and see if this is a known issue?

**Comment by LeafShi1** [comment]
This issue occurs from PR #11535
