### ISSUE TITLE
Code coverage locally

### ISSUE THREAD

**Issue by rookie0jnr** [dotnet/winforms#1163]
Hello,

Is it possible to obtain code coverage report locally? If yes, what are the necessary steps (tools) in order to get one (Windows x64, VS 16.2)?

Moreover, the links for [codecov.io](https://codecov.io/gh/dotnet/winforms) on the main page  do not show the "coverage sunburst". They used to be there. Is this a problem with dotnet/winforms project or on codecov.io's end?

Thank you in advance.

**Comment by merriemcgaw** [comment]
@zsd4yr can you help get us some docs here?

**Comment by zsd4yr** [comment]
@sharwell 	are you aware of any regression / intentional break in codecov.io that would result in this loss?

@AdamYoblick 	did you happen to touch any of the files related to codecoverage? I remember you had been asking me about [codecov.yml](https://github.com/dotnet/winforms/blob/master/codecov.yml)

**Comment by AdamYoblick** [comment]
Nope, I didn't touch anything codecov related. All I did recently was remove helix stuff. :)

**Comment by sharwell** [comment]
I've been having some issues with codecov in other projects for a few days. They are working on it.

**Comment by zsd4yr** [comment]
> I've been having some issues with codecov in other projects for a few days. They are working on it.

Is there an issue or set of issues you can link us to in order to track progress?

**Comment by sharwell** [comment]
https://community.codecov.io/t/processing-errors-in-repository-that-was-working-fine/272
