### ISSUE TITLE
The "span multiple rows or columns" and "align a control" links are not working in the DemoConsole application

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#11638]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it doesn't work in .Net 8.0 from Release/8.0 branch of Winforms repo due to the https://github.com/dotnet/winforms/issues/10213

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, open the Column and Row Styles dialog of TableLayoutPanel control, observe the "span multiple rows or columns" and "align a control" links

### Steps to reproduce

**Actual results in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app:**
Issue1: The **"s"** and **"a"** characters is not covered by links
Issue2: The span multiple rows or columns" and "align a control" links is not working 
![image](https://github.com/dotnet/winforms/assets/38325459/3d90cd56-33f6-4016-bb9c-c5ed544997e1)
![ActualResults](https://github.com/dotnet/winforms/assets/38325459/20c8db42-9641-476f-85e0-9cb1d4d013b3)

**Expected results:**
![image](https://github.com/dotnet/winforms/assets/38325459/ffaa7a1e-d73a-420e-ae4f-c53af7a8aa15)
![ExpectedResults](https://github.com/dotnet/winforms/assets/38325459/d533e118-3291-45e3-97f7-7cc45431a07e)

**Steps to reproduce:**
Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by merriemcgaw** [comment]
@Zheng-Li01  if this looks good in the VS IDE can you please close this?

**Comment by Zheng-Li01** [comment]
Yes, the "span multiple rows or columns" and "align a control" links looks good & working well, so closed this issue.
