### ISSUE TITLE
Unable to switch the tabs using mouse. Only switching the tab can be done through TabKey navigation at DesignTime

### ISSUE THREAD

**Issue by Sekar47** [dotnet/winforms#11642]
### Environment

Edition - Windows 11 Enterprise
Version - 23H2
OS build - 22631.3737
Visual Studio version - 17.9.2

### .NET version

.Netcore 6,7,8

### Did this work in a previous version of Visual Studio and/or previous .NET release?

No, it doesn't work on previous NetCore versions.

### Issue description

I'm trying to switch the tabs by using the mouse click at DesignTime but can't be able to switch. But can be able to be switching by using the TabKey.
For your reference, I have attached a simple sample that replicates the issue.
[CustomTabControl_Sample.zip](https://github.com/user-attachments/files/16142154/CustomTabControl_Sample.zip)

### Steps to reproduce

1.Switch the tabs by using the TabKey.
2.Switch the tabs by using the mouse.

Expected Behavior: While switch using the mouse, the selected tab needs to be switched.
Observed Behavior: No tab switches happened.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please confirm?

**Comment by Zheng-Li01** [comment]
@elachlan  there have a known issue in the designer repo to track https://github.com/microsoft/winforms-designer/issues/3201.

**Comment by Sekar47** [comment]
Hi @elachlan ,
I'm facing 404 issue while trying to open the GitHub link you provided.

**Comment by elachlan** [comment]
Hi @Sekar47, the link provided is for the designer repo and it's currently private.

**Comment by merriemcgaw** [comment]
@Sekar47 we're investigating in our internal designer repo. We'll update this when we have an investigation.

**Comment by merriemcgaw** [comment]
@Sekar47  not yet, I'm sorry.

**Comment by Sekar47** [comment]
Hi @merriemcgaw , Is there any update for this issue?

**Comment by merriemcgaw** [comment]
@Sekar47 this is on our backlog, but I don't have an estimate for when we'll have a fix. 

That said, we have confirmed that you can access the desired tab directly if you select it via the PropertyBrowser or DocumentOutline windows in Visual Studio. Given that there are multiple ways to get to any TabPage that you need, it may take us just a little longer to address this specific issue.

**Comment by Tanya-Solyanik** [comment]
@Sekar47  - mouse click is processed by the VisualStudio process and is forwarded to the DesignTOolsProcess as an input message to be processed by the corresponding glyphs.
