### ISSUE TITLE
In .NetCore project, Changes made in the Designer not being Serialized in the Designer.cs file.

### ISSUE THREAD

**Issue by Sekar47** [dotnet/winforms#11664]
### Environment

Edition - Windows 11 Enterprise
Version - 23H2
OS build - 22631.3737
Visual Studio version - 17.10.4

### .NET version

.Net 6,7,8

### Did this work in a previous version of Visual Studio and/or previous .NET release?

No, it's not working in previous versions of netcore

### Issue description

We are attempting to add items to a collection and serialize them in the designer class using the serializer class which inherits from CodeDomSerializer. However, this is not triggering whenever changes are made in the designer, resulting in the modifications not being serialized in the designer.cs file. Is this a limitation, or are there alternative solutions available?
[CustomControl_Tab (2) 1.zip](https://github.com/user-attachments/files/16192692/CustomControl_Tab.2.1.zip)

### Steps to reproduce

1.In the Designer, Drag and Drop the CustomTabControl from ToolBox.
2.Click on AddTabItem option from Smart tag, you can add the tab items but it is not available in designer.cs file.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test?

**Comment by Olina-Zhang** [comment]
I cannot repro it in my side, after clicking AddTabItem in SmartTag, the toolStripTabItems code is available in designer.cs file:
![image](https://github.com/user-attachments/assets/7f82e356-998e-4704-9131-719faaedbde3)

**Comment by Sekar47** [comment]
Hi @Olina-Zhang , But see the toolStripTabItem's doesn't added in any parent control such as Form1 or customTabControl1. this is the issue, Actually, I wanted a case like if I add toolStripTabItem via SmartTag of the customTabControl then it'll need to directly be added in the header of the customTabControl1. is there any solution for achieving this case?

**Comment by Olina-Zhang** [comment]
Hi @Sekar47, created a sample app, please take a look:
[CustomControlSample.zip](https://github.com/user-attachments/files/16408416/CustomControlSample.zip)
![image](https://github.com/user-attachments/assets/e514b7cd-31f2-4079-88b4-0271b52fe3dc)

**Comment by Sekar47** [comment]
Hi @Olina-Zhang ,

Thank you for the sample code provided. in my case, we are using CodeDomSerializer in our CustomTabControlHeaderSerializer class to handle header serialization for the CustomTabControl.

Could you please provide guidance or suggestions on how to properly use CodeDomSerializer in this scenario? Specifically, we are facing issues where changes made to the TabItem via the smart tag support are not reflected in the Designer.cs file.

Is there a recommended approach or best practices for using CodeDomSerializer to ensure that the designer updates correctly and reflects changes made in the UI? Any insights or examples on how to resolve this issue while continuing to use CodeDomSerializer would be greatly appreciated.

Thank you for your assistance.

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 - I took a quick look at the sample project, it seems that DesignerAction panel is implemented correctly, only the serializer is not discovered on
```
    [ToolboxItem(false)]
    [DesignerSerializer(typeof(TabControlHeaderSerializer), typeof(CodeDomSerializer))]
    public class CustomTabControlHeader : ToolStrip, IHeader
```
Could you or your team investigate if anything is missing in the project or if this is a designer bug. If this is a designer bug, please move the issue to the designer repo.

**Comment by Epica3055** [comment]
this is a fragment of your code.
``` c#
    public class ObservableList<T> : IList
    {
        #region Constructors
        public ObservableList()
        {
            list = new ArrayList();
        }
        
        #endregion

        #region Properties
        /// <summary>
        /// 
        /// </summary>
        public int Count
        {
            get { return this.List.Count; }
        }
       
        /// <summary>
        /// 
        /// </summary>
        protected IList List
        {
            get { return this; }
        }
```
I think you might want to replace
``` c#
        protected IList List
        {
            get { return this; }
        }
```
with
``` c#
        protected IList List
        {
            get { return list; }
        }
```

**Comment by SekarSivalingam** [comment]
Hi @Epica3055 ,

Thank you for your response and suggestions. We implemented the recommended change to the ObservableList class, but unfortunately, the issue persists. Adding ToolStripTabItem via the SmartTag does not serialize properly into the Header of customTabControl1 in the Designer.cs file.

We’ve attached an updated sample and a video demonstration for clarity. Could you kindly review and provide further guidance on resolving this issue or suggest alternative approaches to achieve this expecting behavior?
[CustomControl_Tab.2.1 (3).zip](https://github.com/user-attachments/files/17865344/CustomControl_Tab.2.1.3.zip)

**Comment by Epica3055** [comment]
During my investigation, I found another problem that could lead serialization failure.
![Image](https://github.com/user-attachments/assets/2e07135b-936f-4878-b3db-025251f27ed1)



There actually are two System.CodeDom.dll, so there will be a conflict.

During the process, somehow the System.CodeDom.dll referenced by Microsoft.WinForms.Designer.SDK disappeared, and the desired code was generated.
![Image](https://github.com/user-attachments/assets/c89ec899-2002-4d90-9c85-55dbddc3fe7e)


``` c#
            customTabControl1.Header.AddMainItem(toolStripTabItem1);
            customTabControl1.Header.AddMainItem(toolStripTabItem2);
```
But I still don't know why it disappeared.

**Comment by LeafShi1** [comment]
Duplicated with issue #12545
