### ISSUE TITLE
Missing instances of designers in the DemoConsoleApp

### ISSUE THREAD

**Issue by ricardobossan** [dotnet/winforms#11669]
### .NET version

9.0.100-preview.5.24307.3

### Did it work in .NET Framework?

Not tested/verified

### Issue description

We have referenced the items in issue #4908 to verify their presence within the `DemoConsole` app. The results are detailed in [this report](https://github.com/user-attachments/files/16201230/List.of.designers.present.on.DemoConsole.md), which mirrors the items listed in that issue.

This issue is created to track the progress of adding the missing instances to the `DemoConsole` app.

### Missing Instances to Add from the `System.Windows.Forms.Design` namespace:

- [x] ToolStripContainerDesigner (#11678)
- [x] ToolStripPanelDesigner (#11678)
- [x] SplitterPanelDesigner (#11678)
- [x] RichTextBoxDesigner (#11678)
- [x] ScrollableControlDesigner (#11678)
- [x] ComponentDesigner (#11678)
- [x] SplitterDesigner (#11707)
- [x] UpDownBaseDesigner (#11707)
- [x] TextBoxBaseDesigner (#11707)
- [x] ButtonBaseDesigner (#11707)
- [ ] BindingNavigatorDesigner (#11780)
- ~~[ ] UserControlDocumentDesigner~~ [`Needed infrastructure is missing in the DemoConsole app`](https://github.com/dotnet/winforms/pull/11707#issuecomment-2240623391)
- ~~[ ] StatusBarDesigner~~ [`No corresponding control, this designer needs to be deprecated`](https://github.com/dotnet/winforms/pull/11707#issuecomment-2240623391)
- ~~[ ] DataGridViewColumnDesigner~~ [`Control was already instantiated`](https://github.com/dotnet/winforms/issues/11669#issuecomment-2251310995)
- ~~[ ] ParentControlDesigner~~  [`Control was already instantiated`](https://github.com/dotnet/winforms/issues/11669#issuecomment-2251310995)
- ~~[ ] DocumentDesigner~~  [`Control was already instantiated`](https://github.com/dotnet/winforms/issues/11669#issuecomment-2251310995)
- ~~[ ] ToolStripDropDownDesigner~~  [`Control was already instantiated`](https://github.com/dotnet/winforms/issues/11669#issuecomment-2251310995)
- ~~[ ] FormDocumentDesigne~~ [`Control was already instantiated`](https://github.com/dotnet/winforms/issues/11669#issuecomment-2251310995)
- ~~[ ] WebBrowserDesigner~~ [`Not added to the runtime repo`](https://github.com/dotnet/winforms/pull/11707#issuecomment-2240623391)

### Steps to reproduce

Run DemoConsole app and look for missing instances of items mentioned in issue #4908.

**Comment by ricardobossan** [comment]
@Tanya-Solyanik @LeafShi1 @SimonZhao888  As suggested in [#11707](https://github.com/dotnet/winforms/pull/11707#issuecomment-2240623391), I added breakpoints to all designers and debugged `DemoConsole`. All breakpoints were hit, except for `BindingNavigatorDesigner`, indicating that they were already instantiated.

I then instantiated `BindingNavigatorDesigner`, and the breakpoint was hit. However, this caused the whole tab to go blank, as mentioned [here](https://github.com/dotnet/winforms/pull/11707#issuecomment-2237840141).

- **File**: _winforms\src\System.Windows.Forms\tests\IntegrationTests\DesignSurface\DemoConsole\MainForm.cs_:
  ```csharp
  BindingNavigator bindingNavigator = surface.CreateControl<BindingNavigator>(new(0, 0), new(0, 0));
  ```
  ![blank tab](https://github.com/user-attachments/assets/38505027-de22-4bbe-a788-500df1eafd37)

While debugging `BindingNavigatorDesigner`, I found an error that seems to be causing the tab to become blank. However, I am unsure how to resolve it. Could you help me with this?

```
System.InvalidOperationException
HResult=0x80131509
Message=DesignSurfaceExt::CreateComponent - Exception: (see Inner Exception)
Source=DesignSurfaceExt
StackTrace:
at DesignSurfaceExt.DesignSurfaceExt.CreateComponent[TComponent](IDesignerHost& host) in C:\Users\v-rbossan\source\repos\winforms\11669\src\System.Windows.Forms\tests\IntegrationTests\DesignSurface\DesignSurfaceExt\DesignSurfaceExt.cs:line 225
at DesignSurfaceExt.DesignSurfaceExt.CreateControl[TControl](Size controlSize, Point controlLocation) in C:\Users\v-rbossan\source\repos\winforms\11669\src\System.Windows.Forms\tests\IntegrationTests\DesignSurface\DesignSurfaceExt\DesignSurfaceExt.cs:line 164

This exception was originally thrown at this call stack:
System.ComponentModel.Container.ValidateName(System.ComponentModel.IComponent, string) in Container.cs
System.ComponentModel.Container.Add(System.ComponentModel.IComponent, string) in Container.cs
System.ComponentModel.Design.DesignerHost.PerformAdd(System.ComponentModel.IComponent, string) in DesignerHost.cs
System.ComponentModel.Design.DesignerHost.Add(System.ComponentModel.IComponent, string) in DesignerHost.cs
System.Windows.Forms.Design.BindingNavigatorDesigner.SiteItem(System.ComponentModel.Design.IDesignerHost, System.Windows.Forms.ToolStripItem) in BindingNavigatorDesigner.cs
System.Windows.Forms.Design.BindingNavigatorDesigner.SiteItems(System.ComponentModel.Design.IDesignerHost, System.Windows.Forms.ToolStripItemCollection) in BindingNavigatorDesigner.cs
System.Windows.Forms.Design.BindingNavigatorDesigner.InitializeNewComponent(System.Collections.IDictionary) in BindingNavigatorDesigner.cs
DesignSurfaceExt.DesignSurfaceExt.CreateComponent<TComponent>(out System.ComponentModel.Design.IDesignerHost) in DesignSurfaceExt.cs

Inner Exception 1:
ArgumentException: Duplicate component name 'BindingNavigatorSeparator'. Component names must be unique and case-insensitive.
```

**Comment by SimonZhao888** [comment]
> @Tanya-Solyanik @LeafShi1 @SimonZhao888 As suggested in [#11707](https://github.com/dotnet/winforms/pull/11707#issuecomment-2240623391), I added breakpoints to all designers and debugged `DemoConsole`. All breakpoints were hit, except for `BindingNavigatorDesigner`, indicating that they were already instantiated.

I think BindingNavigator is not stand-alone, we can use it by following way:
![image](https://github.com/user-attachments/assets/cf6d94d0-9e2a-430c-a28a-fe283f8ccdc2)

Breakpoints in BindingNavigatorDesigner are also hit normally, and the page runs as normal

**Comment by SimonZhao888** [comment]
Hi @Tanya-Solyanik,

BindingNavigator is not displayed in the designer interface at design time, however, it can be displayed in the runtime interface, can we add the BindingNavigator control to the WinFormsControlsTest project. Is this a better way to test the BindingNavigatorDesigner?

**Comment by SimonZhao888** [comment]
> ```
> System.InvalidOperationException
> HResult=0x80131509
> Message=DesignSurfaceExt::CreateComponent - Exception: (see Inner Exception)
> Source=DesignSurfaceExt
> StackTrace:
> at DesignSurfaceExt.DesignSurfaceExt.CreateComponent[TComponent](IDesignerHost& host) in C:\Users\v-rbossan\source\repos\winforms\11669\src\System.Windows.Forms\tests\IntegrationTests\DesignSurface\DesignSurfaceExt\DesignSurfaceExt.cs:line 225

Hi @ricardobossan ,

This issue is caused by the fact that all 3 separator lines have the same name. 
https://github.com/dotnet/winforms/blob/00b8d566610cf2383763d576c1bdad51cae4d882/src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/BindingNavigator.cs#L161-L163
That's why the program reports an error at
https://github.com/dotnet/winforms/blob/00b8d566610cf2383763d576c1bdad51cae4d882/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BindingNavigatorDesigner.cs#L104

If we update the name of the divider, this problem doesn't occur.
![image](https://github.com/user-attachments/assets/02de675c-fb48-464b-ab5b-d061f64ae0bd)
![image](https://github.com/user-attachments/assets/ecbcbcc4-41c6-4b62-beaa-a745c2f475af)

**Comment by ricardobossan** [comment]
@SimonZhao888 Thanks! I created PR #11780 to address [this](https://github.com/dotnet/winforms/issues/11669#issuecomment-2257902574) and to add the BindingNavigator to the DemoConsole.

**Comment by Tanya-Solyanik** [comment]
> Hi @Tanya-Solyanik,
> 
> BindingNavigator is not displayed in the designer interface at design time, however, it can be displayed in the runtime interface, can we add the BindingNavigator control to the WinFormsControlsTest project. Is this a better way to test the BindingNavigatorDesigner?

If you add BindingNavigator control to the WinFormsControlsTest, its designer will not be created.

**Comment by Tanya-Solyanik** [comment]
@SimonZhao888 , @ricardobossan - This code had always generated the same names for separators - https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/BindingNavigator.cs,171
Why didn't we see a bug in the past? How does this work in the InProc designer? I assume we never hit an unnamed control case in that designer...

**Comment by ricardobossan** [comment]
> @SimonZhao888, @ricardobossan - This code has always generated the same names for separators: [Reference Source](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/BindingNavigator.cs,171). Why didn't we see a bug in the past? How does this work in the InProc designer? I assume we never encountered an unnamed control case in that designer. Instead, the nested `designerHost` generated the control name (handling controls nested inside the parent control, like a separator inside the navigator). This host is probably missing in the demo console.
>
> Also, try to call `AddStandardItems` from the code in a runtime application and see what name is generated in .NET Framework and in .NET 10. I think you have a valid fix for a runtime bug, but I want to confirm that we have a runtime bug.
>
> But for the demo console bug, we probably need the nested host.

@Tanya-Solyanik

### "How does this work in the `InProc` designer?"

In [VS's `BindingNavigatorDesigner`](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsip/Designer/WinForms/System/WinForms/Design/BindingNavigatorDesigner.cs&version=GBmain&line=120&lineEnd=120&lineStartColumn=13&lineEndColumn=87&lineStyle=plain&_a=contents), I found this line: `host.Container.Add(item, DesignerUtils.GetUniqueSiteName(host, item.Name));`. This seems to handle naming items and it's not present in `DemoConsole`.

### "This host is probably missing in the demo console"

True. The `DesignerUtils.GetUniqueSiteName()` from the `VS` repo doesn't exist in `DemoConsole`, nor could I find any similar logic in the `DemoConsole` codebase.

### "Call `AddStandardItems` from code in a runtime application"

I created WinForms apps with `BindingNavigator.AddStandardItems()` on both `.NET Framework` and `.NET 8.0/9.0`. In all cases, the apps work fine and the names of the separators are the same. So, the error complaining about separators having the same name happens only in the surface app (`DemoConsole`).

#### .NET Framework:

![AddStandardItems_NET481](https://github.com/user-attachments/assets/07d4bab2-fcdc-4c13-827e-5dd4b3c71471)

#### .NET 9.0:

![AddStandardItems_NET8 0](https://github.com/user-attachments/assets/8d3669e8-ac92-4408-9a32-5943dfea6b40)

### "For the demo console bug, we probably need the nested host"

Should we create an issue to add this nested host to `DemoConsole`?

**Comment by Tanya-Solyanik** [comment]
Thank you for experiments!

>So, the error complaining about separators having the same name happens only in the surface app (DemoConsole).

This is still a bug even if it's not reported. Let's fix it.

**Comment by Tanya-Solyanik** [comment]
Please create a workitem to add the missing logic to DemoConsole - `DesignerUtils.GetUniqueSiteName(host, item.Name)`. But it will be a low priority one.
