### ISSUE TITLE
The comboBox incorrect display when setting its DropDownStyle as Simple in the DemoConsole application

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#11673]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it doesn't work in .NET 8.0 from Release/8.0 branch of Winforms repo. It has related designer issue [2707](https://github.com/microsoft/winforms-designer/issues/2707).

### Issue description

Actual result in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app:

https://github.com/user-attachments/assets/e3df9627-5b12-43b8-a2b4-161e6a54acd8

Expected result:

https://github.com/user-attachments/assets/d34b47f5-c918-46d3-88cd-073589d9285c

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo.

**Comment by LeafShi1** [comment]
This issue will be fixed in PR #11363

**Comment by Zheng-Li01** [comment]
Verified the issue with winforms repo main branch that the issue has been fixed that the comboBox display correctly when setting its DropDownStyle as Simple in the DemoConsole application as below screenshot.
![image](https://github.com/user-attachments/assets/dd42db46-3dcd-4121-837e-a7f12a04b049)
