### ISSUE TITLE
Refactor `lock` on `object` usage to `System.Threading.Lock`

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#11672]
In .NET9 there is the new `System.Threading.Lock`
https://learn.microsoft.com/en-us/dotnet/api/system.threading.lock?view=net-9.0

> It is recommended to use the [EnterScope](https://learn.microsoft.com/en-us/dotnet/api/system.threading.lock.enterscope?view=net-9.0) method with a language construct that automatically disposes the returned [Lock.Scope](https://learn.microsoft.com/en-us/dotnet/api/system.threading.lock.scope?view=net-9.0) such as the C# using keyword, or to use the C# lock keyword, as these ensure that the lock is exited in exceptional cases. These patterns might also have performance benefits over using Enter/TryEnter and Exit. The following code fragment illustrates various patterns for entering and exiting a lock.

Refactor the `object` used for the lock to `Lock` where appropriate. The new `Lock` class when used with `lock()` will not use `system.threading.monitor`, but instead will use `system.threading.lock`. 

Benchmarks in this blog post suggest a 25% performance improvement in lock operations:
https://steven-giesel.com/blogPost/4cf6d48a-ec9d-4c68-961c-31fd8d8c1340

There are some limitations, I think the team is best positioned to decide whats best here.

**We won't make changes until C# takes the change to the `lock` keyword out of preview.**
https://github.com/dotnet/csharplang/issues/7104

**Comment by elachlan** [comment]
@kirsan31 I saw you commented on the runtime issue. What are your thoughts on this?

**Comment by elachlan** [comment]
@JeremyKuhne you might be able to shoot this down early.

**Comment by elachlan** [comment]
One thing I am wondering is if the heavy usage of `lock (this)` is on purpose?

**Comment by JeremyKuhne** [comment]
We can explore this when the feature leaves preview state.

**Comment by elachlan** [comment]
Related runtime issue: https://github.com/dotnet/runtime/issues/34812

**Comment by kirsan31** [comment]
> @kirsan31 I saw you commented on the runtime issue. What are your thoughts on this?

My thots on this:
1. Need to wait until release.  
2. Need a full sets of benchmarks:  
   - Acquire / release without waiting. _I hope this must be faster then current object lock :)_
   - _Long_ time waiting. _Must be at least not worse then current :)_
   - _Short_ time waiting. _Here the main question because of SpinWait using. In some cases we can get better performance but in some case much worse (many short waiters will eat cpu ) :(_

So if acquire/release without waiting will be faster (_it must_) then we can feel free to replace object locking in those cases where waiting is rare. In other cases some analysis will be needed I think...

**Comment by elachlan** [comment]
The code base locks a lot on `this`. Which usually isn't a good idea. I'd like this issue to review that as well.

**Comment by elachlan** [comment]
I've raised an roslyn-analyzer rule over at: https://github.com/dotnet/roslyn-analyzers/issues/7361

It would make changes like this easier.

**Comment by elachlan** [comment]
@lonitra do you know who we can ask about the new Lock type? I am wondering if we can use it based on this comment:

> If we want to have a lock object type not integrated into Monitor, then there is quite a bit of work required to make sure it integrates with the diagnostics infrastructure and the threading model correctly. (Monitor is an interruptible lock as it uses a COM interruptible wait so that STA frameworks such as WinForms and WPF work correctly. Any other lock that is intended for general use will also need to follow those strictures.)

https://github.com/dotnet/runtime/issues/34812#issuecomment-612531493

**Comment by JeremyKuhne** [comment]
Going to do this in .NET 10. I'm comfortable enough with what I've read to commit to this.
