### ISSUE TITLE
TextBox raises TextChanged event the first time it gets focus when there is an Accessibility client running

### ISSUE THREAD

**Issue by IGMikeS** [dotnet/winforms#1168]
* .NET Core Version: Version:   3.0.100-preview6-012264
* Have you experienced this same bug with .NET Framework?: No

A TextBox control on a form fires the TextChanged event the first time it gets focus, even though the text has not changed. This only happens when there is an accessibility client running. 

To reproduce the issue, create a new NetCore Winforms project and use the following code in the form's constructor after InitializeComponent.

        TextBox tb = new TextBox();
        tb.TextChanged += Tb_TextChanged;
        this.Controls.Add(tb);

And, of course, you need to define the event handler and put a breakpoint in it: 

    private void Tb_TextChanged(object sender, EventArgs e)
    {

    }

Run an accessibility client. For example, show the on-screen touch keyboard in Windows 10. 
Run the application and TextChanged fires. 
In .Net Framework, the event does not fire. And it should not fire in the NetCore version, since the text has not actually changed. 

The call stack seems to point to the new PlaceholderText property as the potential cause of the issue. 

When the TextBox gets focus, TextBox CreateAccessibilityObject gets called and this calling into AccessibleObject.SetValue which sets the Text to the PlaceholderText - which explains why the problem only happens in NetCore, since that property does not exist in the .Net Framework version. 

>	NetCoreApp.dll!Form1.Tb_TextChanged(object sender, System.EventArgs e) Line 25	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.OnTextChanged(System.EventArgs e)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBoxBase.OnTextChanged(System.EventArgs e)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBoxBase.WmReflectCommand(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBoxBase.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBox.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.Control.SendMessage(int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ReflectMessage(System.IntPtr hWnd, ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WmCommand(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.ScrollableControl.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.ContainerControl.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Form.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DefWndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.DefWndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBoxBase.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBox.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.AccessibleObject.Value.set(string** value)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBox.CreateAccessibilityInstance()	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.AccessibilityObject.get()	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.GetAccessibilityObject(int accObjId)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WmGetObject(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBoxBase.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.TextBox.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.ContainerControl.FocusActiveControlInternal()	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Form.Active.set(bool value)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Form.WmActivate(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Form.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.Control.SetVisibleCore(bool value)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Form.SetVisibleCore(bool value)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(int reason, System.Windows.Forms.ApplicationContext context)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.RunMessageLoop(int reason, System.Windows.Forms.ApplicationContext context)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Application.Run(System.Windows.Forms.Form mainForm)	Unknown
 	NetCoreApp.dll!Program.Main() Line 17	C#

**Comment by merriemcgaw** [comment]
@stefanov-stefan are you able to take a look at this by any chance?

/cc @M-Lipin

**Comment by stefanov-stefan** [comment]
Hey @merriemcgaw, @petermitkov will take a look at this.
