### ISSUE TITLE
LinkLabel image display abnormally 

### ISSUE THREAD

**Issue by Liv-Goh** [dotnet/winforms#11680]
### .NET version

.NET 9.0 SDK build: 9.0.100-preview.6.24328.19

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue. Not reproduce on .NET 8.0

### Issue description

**Current Behavior (.NET 9.0):**
- linkLabel does not display the chosen image. 
- linkLabel image change when new component added to the form
- linkLabel display differently in runtime and designer form
- linkLabel display in designer changed after run the project
![linkLabelImageDisplayCurrent](https://github.com/user-attachments/assets/3a47ec41-bbf6-4c78-b991-bc6bf29e7e4a)

**Expected Behavior (.NET 8.0):**
- linkLabel display the chosen image. 
- Adding component to form does not affect the linkLabel image
- linkLabel image is consistent on both runtime and designer
![linkLabelImageDisplayExpected](https://github.com/user-attachments/assets/248a7027-c285-433d-9388-7a375c36d1ca)

### Steps to reproduce

1. Create a WinForms .NET 9.0 project
2. Add a linkLabel component to the form
3. Set the linkLabel font larger (e.g. 20) to observe the issue easier
4. click ... in linkLabel Image property, import an image and click ok
5. Add random component to the form (observe linkLabel behavior)
6. Run the project (observe linkLabel behavior)

**More Info**
linkLabel ImageList property have the similar behavior

**Comment by lonitra** [comment]
@LeafShi1 could you do an initial investigation to see what regressed here?

**Comment by JeremyKuhne** [comment]
Scratch project repro:

``` C#
    private readonly LinkLabel _linkLabel1;

    public Form1()
    {
        InitializeComponent();

        Bitmap bitmap = new Bitmap(100, 100);
        using (Graphics g = Graphics.FromImage(bitmap))
        {
            g.Clear(Color.Red);
        }

        _linkLabel1 = new()
        {
            Font = new Font("Segoe UI", 48F, FontStyle.Regular, GraphicsUnit.Point, 0),
            Image = bitmap,
            Size = new Size(322, 86),
            Text = "linkLabel1"
        };

        Controls.Add(_linkLabel1);
        PerformLayout();
    }
```

Here is the regex I used to find the other mistaken using:

```
^\s*using\s[^\(].*;.$\s*{
```

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .NET 9.0 Preview 7 SDK build, it was fixed: the image for LinkLabel display and refresh correctly in designer and runtime:
![image](https://github.com/user-attachments/assets/ebaf2891-7afd-446d-93da-50a9b968a950)

**Comment by MandiMan** [comment]
Verified the issue with .NET 9.0.100-preview7.24407.12 test pass build that the issue has been fixed, which have the same results as above.
