### ISSUE TITLE
Data Bindings should use `nameof` instead of raw string literals.

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/winforms#11694]
### Background and motivation

Data Bindings should use `nameof` instead of raw string literals.

This would help in tracking the usage references and any renames later.

### API Proposal

```cs
// Before
joinDatePicker.DataBindings.Add(new Binding("Value", employeeViewModelBindingSource, "JoinDate", true));
// After
joinDatePicker.DataBindings.Add(new Binding(nameof(DateTimePicker.Value), employeeViewModelBindingSource, nameof(EmployeeViewModel.JoinDate), true));
```

### API Usage

Designer generated code.

### Will this feature affect UI controls?

I don't think so.

**Comment by elachlan** [comment]
@Olina-Zhang can your team link this to the designer issue? I think this has been raised previously.

**Comment by Olina-Zhang** [comment]
It seems we haven't known issue in designer repo, I will create one for it.

**Comment by elachlan** [comment]
I think its covered in #10153

Some what related: #8350

**Comment by elachlan** [comment]
CC: @KlausLoeffelmann for visibility.

**Comment by Olina-Zhang** [comment]
I filed this specific case in winforms-deisgner repo: https://github.com/microsoft/winforms-designer/issues/6024

**Comment by Tanya-Solyanik** [comment]
This will is not an new API proposal, this is a change to codegen in the designer. We are tracking it in the designer repo.
