### ISSUE TITLE
Update WebBrowser control in .NET Core

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#117]
Copied from https://github.com/dotnet/core/issues/2093  

Since WinForms is moving to .NET Core 3.0, I hope you upgrade the WebBrowser control to use the IE version installed on the user PC. The current WebBrowser control uses IE 7 and causes many problems. There is a workaround to solve this, but doing it in the user's PC needs permissions. See this topic for more details:
https://stackoverflow.com/questions/17922308/use-latest-version-of-internet-explorer-in-the-webbrowser-control?noredirect=1&lq=1

**Comment by poizan42** [comment]
> There is a workaround to solve this, but doing it in the user's PC needs permissions. 

The X-UA-Compatible header method does not: https://stackoverflow.com/a/39534209/1555496 - though it requires you to control the headers or the html. I haven't tried it but maybe it works to just put the actual page inside an iframe on a page with the http-equiv tag.

**Comment by kpreisser** [comment]
> but doing it in the user's PC needs permissions.

You can set the registry key in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION` (rather than `HKEY_LOCAL_MACHINE`) to disable IE7 Compatibility View, which doesn't require elevated permissions; ideally at the top of your `Main()` method before GUI code is invoked.

See: https://github.com/Microsoft/monaco-editor/issues/114#issuecomment-242778649

**Comment by BuraChuhadar** [comment]
I don't think the comments above should be the actual approach. At the end browser control would default itself to IE 11. With a lot new web based applications out there, it impossible support this component. IE 11 doesn't support a lot new web standards as it is getting harder and harder every day to support IE 11's desires. A fundamental change is necessary here. Please consider switching Edge browser. Even if possible use the one that is going to be written with Chromium platform.

**Comment by MohammadHamdyGhanem** [comment]
@BuraChuhadar 
The control should use the highest version available.  Edge is version 12 and above.

**Comment by anirudhagupta** [comment]
@merriemcgaw 
What about Replacing the IE7 with MS Edge (upcoming Edge will be based on chromium), Look like new MS Edge will support Windows 7, so there should not be any issue with Windows 7.

**Comment by merriemcgaw** [comment]
We're going to hold off on doing anything with the current WebBrowser control for Core 3.0, and instead focus on getting the new Edge control supported in Core. That is the way forward and will be tracked as a new issue when the times comes. We will have something exciting to share in the coming months, so stay tuned.

**Comment by Varorbc** [comment]
@merriemcgaw is there any plan to replace IE7 with chromium?

**Comment by RussKie** [comment]
Yes, it is something we are definitely considering. However we do not currently have any set timelines for this feature.

**Comment by Varorbc** [comment]
can you reopen the issue

**Comment by merriemcgaw** [comment]
This work is in progress right now

**Comment by merriemcgaw** [comment]
We'll reply back on this thread when they've got their first preview. We've seen the first draft of the PR that creates the control. But, since we're not doing the work I'm going to close this issue. Nothing says I can't update a closed issue 😃

**Comment by hughbe** [comment]
I've worked on an experimental control based on [ICoreWebView2](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2)

See https://github.com/hughbe/EdgeWebBrowser

Will add screenshot later

**Comment by RussKie** [comment]
The Edgium team is building the new .NET browser control, which we will get at some point in the future.

**Comment by Varorbc** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09515-prerelease
