### ISSUE TITLE
BinaryFormatter error when moving the components control in the Democonsole application

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#11710]
### .NET version

9.0.100-preview.7.24368.5

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, not repro in .NET 8.0, still reproduced in PR [11614](https://github.com/dotnet/winforms/pull/11614)

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo's main branch, BinaryFormatter error when moving the components control in the Democonsole application
![image](https://github.com/user-attachments/assets/4a7b3717-0b34-4ced-a75a-c3035c50b60e)

https://github.com/user-attachments/assets/490d421b-363a-454a-a154-de622080bbfa

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by elachlan** [comment]
I am thinking the fix here will be to add a package reference to binary formatter. 

@JeremyKuhne did the team want the codedomserializer to be binaryserializer only?

**Comment by JeremyKuhne** [comment]
There really isn't much choice but to depend on BinaryFormatter for CodeDomSerializer

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - please add the binary Formatter package to DemoConsole
https://www.nuget.org/packages/System.Runtime.Serialization.Formatters/9.0.0-preview.6.24327.7
https://github.com/dotnet/winforms/blob/cfb1cf0db1fe7932c8f1abeaa38465a7043a3301/src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj#L18

**Comment by Syareel-Sukeri** [comment]
Verified the issue on the latest DemoConsole test app of Winforms repo from main branch, it was fixed. No BinaryFormatter error appears when moving components control in DemoConsole application.

https://github.com/user-attachments/assets/9f503ad1-8d22-43bd-8009-e536e686d336
