### ISSUE TITLE
Mark the Form.OnClosed and OnClosing methods with the ObsoleteAttribute

### ISSUE THREAD

**Issue by geniuszxy** [dotnet/winforms#11727]
### Background and motivation

Since [the document](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.onclosing?view=windowsdesktop-8.0#remarks) mentions that these two methods have been obsolete for years, marking them with the ObsoleteAttribute can help us avoid using them when coding.

### API Proposal

```C#
namespace System.Windows.Forms;

public partial class Form
{
    [System.Obsolete("The OnClosed method is obsolete starting with the .NET Framework 2.0; use the OnFormClosed method instead.")]
    protected virtual void OnClosed (EventArgs e);

    [System.Obsolete("The OnClosing method is obsolete starting with the .NET Framework 2.0; use the OnFormClosing method instead.")]
    protected virtual void OnClosing (System.ComponentModel.CancelEventArgs e);

    [System.ComponentModel.Browsable(false)]
    [System.Obsolete("The Closed event is obsolete in the .NET Framework version 2.0; use the FormClosed event instead.")]
    public event EventHandler? Closed;

    [System.ComponentModel.Browsable(false)]
    [System.Obsolete("The Closing event is obsolete starting with the .NET Framework 2.0; use the FormClosing event instead.")]
    public event System.ComponentModel.CancelEventHandler? Closing;
}
```

### API Usage

No.

### Will this feature affect UI controls?

No.

**Comment by paul1956** [comment]
Does Visual Studio understand Obsolete Attribute? Will it still show up in form DropDown list if they are not used, is it different if they are used?

**Comment by geniuszxy** [comment]
@paul1956 Visual Studio understand ObsoleteAttribute, decorated members  will still appear in the dropdown list, but they will be marked as deprecated.

![ob0](https://github.com/user-attachments/assets/766329e6-1dd1-4117-b439-dd1fba55e6b4)

If you use them, the compiler will also provide warnings.

![ob1](https://github.com/user-attachments/assets/fc549bde-4097-4c6b-ac42-ff33d477dee6)

**Comment by elachlan** [comment]
@geniuszxy would you like to submit a PR?

**Comment by PaulusParssinen** [comment]
> geniuszxy would you like to submit a PR?

I believe making public API surface obsolete requires an API review first? (atleast in runtime)

**Comment by geniuszxy** [comment]
> @geniuszxy would you like to submit a PR?

Can I submit directly? Or is it lonitra who is making this change now?

**Comment by lonitra** [comment]
@geniuszxy Thank you for submitting this issue! If you are interested, please feel free to submit a PR and I can help shuffle this along to API review to get approval.

**Comment by terrajobst** [comment]
* Makes sense to me.
* I suggest also marking the APIs as `[EditorBrowsable(BrowsableState.Never)]` to avoid them showing up in the code editor
* I suggest to a single diagnostic ID to all of them, as they are logically the same obsoletion

```C#
[EditorBrowsable(BrowsableState.Never)]
[Obsolete("The OnClosed method is obsolete starting with the .NET Framework 2.0; use the OnFormClosed method instead.")]
protected virtual void OnClosed (EventArgs e);

[EditorBrowsable(BrowsableState.Never)]
[Obsolete("The OnClosing method is obsolete starting with the .NET Framework 2.0; use the OnFormClosing method instead.")]
protected virtual void OnClosing (CancelEventArgs e);

[Browsable(false)]
[EditorBrowsable(BrowsableState.Never)]
[Obsolete("The Closed event is obsolete in the .NET Framework version 2.0; use the FormClosed event instead.")]
public event EventHandler? Closed;

[Browsable(false)]
[EditorBrowsable(BrowsableState.Never)]
[Obsolete("The Closing event is obsolete starting with the .NET Framework 2.0; use the FormClosing event instead.")]
public event CancelEventHandler? Closing;
```

**Comment by RussKie** [comment]
Does the obsoletion need to be an error - that is, `[Obsolete(..., error: true, ...)]`? Or should it remain as a warning?

**Comment by terrajobst** [comment]
We generally don't obsolete as error as it disrupts the inner loop (developer has to fix errors before they can build/run). So unless there is a strong reason I wouldn't do it here either.

**Comment by Tanya-Solyanik** [comment]
@terrajobst  - we should also add `    [Browsable(false)]` to not show these in the events tab in the property browser, right?

**Comment by Syareel-Sukeri** [comment]
Verified this issue in the latest .NET9.0 SDK build: 9.0.100-rc.2.24420.21 + dlls built from Winforms main branch, the Form.OnClosed and Form.OnClosing methods, as well as their override methods, are now marked with the [Obsolete] attribute.
![Screenshot 2024-08-22 070717](https://github.com/user-attachments/assets/469d4057-9d77-4036-aa4e-e54751ccc7ba)
