### ISSUE TITLE
Target PRs to New feature/10.0 Branch

### ISSUE THREAD

**Issue by lonitra** [dotnet/winforms#11731]
Hi folks, as we are getting closer to the end of .NET 9 cycle, `main` branch will now be reserved for regression fixing and team planned work items specifically for .NET 9. Please target new PRs to `feature/10.0` branch moving forward, which has been created to take changes for .NET 10. Thank you for your cooperation!

**Comment by paul1956** [comment]
@lonitra what should I do with my 2 PR's, tests for Public Members in Visual Basic Runtime and replacement for obsolete WebClient for Public DownloadFile  in VB Runtime. VB UploadFile is still an issue if WebClient goes away,

**Comment by lonitra** [comment]
> what should I do with my 2 PR's, tests for Public Members in Visual Basic Runtime and replacement for obsolete WebClient for Public DownloadFile in VB Runtime. VB UploadFile is still an issue if WebClient goes away,

We will need to take these for .NET 10. I had already gone ahead and retargeted current PRs to feature/10.0. This should not affect any ability to push further commits to them.

**Comment by kirsan31** [comment]
This is really sad and once again confirms the lack of project members :( We have 3+ month pending PRs :(
What to do with PR that's solve .Net9 **regression** (my #11206 for example)?

**Comment by paul1956** [comment]
I would have liked to at least see the tests for the VB Runtime included they have been in the queue 10 months. Someone could cherry pick just the tests, the only issue is resolving 2 versions of the Utils Class that have different implementations and behaviors, the existing PR addresses this.
