### ISSUE TITLE
Add constructor overloads for Binding type that accepts TypeConverter (rather interface based Converter type) as additional parameters

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/winforms#11740]
### .NET version

8.0.303

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, I haven't tried on other frameworks.

### Issue description

Add **constructor overloads for Binding type** that accepts `TypeConverter` (or interface-based `Converter` type) as additional parameters.

The main reason for choosing MVVM is the separation of concerns. Using the `TypeConverter` attribute convention makes sharing code with different UI frameworks hard.

For example, using DateTimeOffset as my VM property, but some frameworks require using DateTime as their type binding control. So, I can't apply TypeConverter on the VM layer. The ideal option would be to use the Converter as a thin layer between View and ViewModel.

### Steps to reproduce

Feature request, it's self-explained.

**Comment by egvijayanand** [comment]
Concerns emerge when the WinForms MVVM Binding infrastructure is not comprehensively evaluated against the established XAML-based MVVM Binding frameworks in production.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann has some thoughts about this and will reply soon.

**Comment by KlausLoeffelmann** [comment]
Yes. 
a) I think this is a duplicate, and we have a suggestion somewhere.
b) I am not sure, if we can solve this via Design Time, without the need for an API change. Keep in mind, that we already have a series of options, to have a Type Converter engaged.

We will have planned to addressing this in .NET 10 (and the respective VS version). I am closing this for now.

**Comment by egvijayanand** [comment]
> I think this is a duplicate, and we have a suggestion somewhere.

There's no link to the duplicate issue or **suggestion somewhere** and I don't think this is how you close an issue.

**Comment by egvijayanand** [comment]
When a feature is being implemented, there's a minimum expectation of how it will integrate.

That too for a highly successful MVVM design pattern being brought into the most acclaimed WinForms framework.
