### ISSUE TITLE
Error trying to update Repo, can't read MissingPropertySerializationConfigurationAnalyzerTest.vb

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#11758]
### .NET version

Microsoft Visual Studio Community 2022
Version 17.11.0 Preview 5.0
VisualStudio.17.Preview/17.11.0-pre.5.0+35118.90
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

### Did it work in .NET Framework?

N/A

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

N/A

### Issue description

unable to create file src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/System/Windows/Forms/Analyzers/MissingPropertySerializationConfiguration/MissingPropertySerializationConfigurationAnalyzerTest.vb: Filename too long

After running below from  ADMIN command prompt
 Start-Process -Verb RunAs "git" "config","core.longpaths","true"

The error changes to
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	IDE1100	Error reading content of source file 
```
'C:\Users\PaulM\Source\Repos\Winforms\src\System.Windows.Forms.Analyzers.VisualBasic\tests\UnitTests\System.Windows.Forms.Analyzers.VisualBasic.Tests\System\Windows\Forms\Analyzers\MissingPropertySerializationConfiguration\MissingPropertySerializationConfigurationAnalyzerTest.vb' -- 'Could not find file 'C:\Users\PaulM\Source\Repos\Winforms\src\System.Windows.Forms.Analyzers.VisualBasic\tests\UnitTests\System.Windows.Forms.Analyzers.VisualBasic.Tests\System\Windows\Forms\Analyzers\MissingPropertySerializationConfiguration\MissingPropertySerializationConfigurationAnalyzerTest.vb'.'.	System.Windows.Forms.Analyzers.VisualBasic.Tests	C:\Users\PaulM\Source\Repos\Winforms\src\System.Windows.Forms.Analyzers.VisualBasic\tests\UnitTests\System.Windows.Forms.Analyzers.VisualBasic.Tests\System\Windows\Forms\Analyzers\MissingPropertySerializationConfiguration\MissingPropertySerializationConfigurationAnalyzerTest.vb	1		
```

### Steps to reproduce

After sync Main repo no longer can commit changes.

Unable to fix using
PS C:\Users\PaulM\Source\Repos\winforms> git fetch origin
PS C:\Users\PaulM\Source\Repos\winforms> git reset --hard origin/master
error: unable to create file src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/System/Windows/Forms/Analyzers/MissingPropertySerializationConfiguration/MissingPropertySerializationConfigurationAnalyzerTest.vb: Filename too long
fatal: Could not reset index file to revision 'origin/master'.

**Comment by elachlan** [comment]
I was able to resolve this issue by adding longpaths = true to my config. prior to that I had enabled long paths in windows via the registry.

**Comment by paul1956** [comment]
@elachlan can you be more explicit as to what config file the line needs to be added to.

**Comment by elachlan** [comment]
Your local git config.

Also you need to enable longpaths in windows:
https://superuser.com/questions/1807770/enable-long-paths-on-win-11-home

**Comment by paul1956** [comment]
@elachlan did all those things and it still didn't work completely. Git works, merge works but Visual Studio Community can't read MissingPropertySerializationConfigurationAnalyzerTest.vb. I moved repo directory to C:\Repo, deleted artifacts directory and then everything worked. **Thanks**, this should be documented if it's not possible to shorten path length.

**Comment by Syareel-Sukeri** [comment]
Verified this on latest winforms repo, the long path issue is fixed.

**Before**
<img width="547" alt="image (1)" src="https://github.com/user-attachments/assets/52fd9fb1-99b8-4920-8c66-eac706088933">
**After**
![Screenshot 2024-08-16 074910](https://github.com/user-attachments/assets/606cfe86-7bb2-4ddc-a4af-db79619b7093)
