### ISSUE TITLE
PropertyGrid.OnPropertyValueSet: NullReferenceException (version 2)

### ISSUE THREAD

**Issue by ulfemsoy** [dotnet/winforms#11768]
@ulfemsoy there is not enough information for us to diagnose this issue. When you have more information on how you encountered this issue, please reopen this bug or create a new one with the details then we'd be happy to help!

_Originally posted by @merriemcgaw in https://github.com/dotnet/winforms/issues/11495#issuecomment-2153146251_

ISSUE:
Please refer to line 2946 in PropertyGrid.cs: 
Type propertyType = changedItem.PropertyDescriptor!.PropertyType;
(https://github.com/dotnet/winforms/blob/bacb9f8821506abd78f18c7f65bcf8d5416064be/src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs#L2946)

The value of "changedItem.PropertyDescriptor" can be null, and will raise a NullReferenceException when requesting the property "PropertyType".

"PropertyDescriptor" is null when "changedItem" is a CategoryGridEntry, SingleSelectRootGridEntry or ArrayElementGridEntry.

Please perform a null test (changedItem.PropertyDescriptor is not null) before requesting the property type.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this to see if it is a preview regression?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang can your team please test this to see if it is a preview regression?

We cannot reproduce it with limited information. From originally posted in GH issue https://github.com/dotnet/winforms/issues/11495, repro in .NET 6.0, it doesn't look like a preview regression. @ulfemsoy can you please test if it reproduces or not in .NET 8.0 or .NET 9.0?

**Comment by ulfemsoy** [comment]
@Olina-Zhang, it is an old issue that happens now and then. In 2 years the specific NullReferenceException has only been raised twice for Asian users. The program is written for .NET 6, so it is hard to reproduce for .NET 8/9. 

It would be nice if you could modify the method to:

```
internal void OnPropertyValueSet(GridItem changedItem, object? oldValue)
    {
        OnPropertyValueChanged(new PropertyValueChangedEventArgs(changedItem, oldValue));

        if (changedItem is null)
        {
            return;
        }

        // Announce the property value change like standalone combobox control do: "[something] selected".
        bool dropDown = false;

        PropertyDescriptor propertyDescriptor = changedItem.PropertyDescriptor;

        if(propertyDescriptor is not null)
        {
                Type propertyType = propertyDescriptor.PropertyType;
                var editor = (UITypeEditor?)TypeDescriptor.GetEditor(propertyType, typeof(UITypeEditor));
                if (editor is not null)
                {
                    dropDown = editor.GetEditStyle() == UITypeEditorEditStyle.DropDown;
                }
                else
                {
                    if (changedItem is GridEntry gridEntry && gridEntry.Enumerable)
                    {
                        dropDown = true;
                    }
                }
        }

        if (IsAccessibilityObjectCreated && dropDown && (_gridView is not null) && !_gridView.DropDownVisible)
        {
            AccessibilityObject.RaiseAutomationNotification(
                Automation.AutomationNotificationKind.ActionCompleted,
                Automation.AutomationNotificationProcessing.All,
                string.Format(SR.PropertyGridPropertyValueSelectedFormat, changedItem.Value));
        }
    }
```

Please notice the null test of "if(propertyDescriptor is not null)", and the additional "(_gridView is not null)" statement. This will avoid any future NullReferenceExceptions.

**Comment by Olina-Zhang** [comment]
@ulfemsoy Thanks for your information. Let's wait for our engineering team's triage and review.
