### ISSUE TITLE
The selected control have no border line in the DemoConsole application

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#11789]
### .NET version

feature/10.0 branch of Winforms repo 

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this was changed after the PR https://github.com/dotnet/winforms/pull/11678

### Issue description

**Actual result in [[DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole)]** test app:
The selected control have no border line in the DemoConsole application, 
![image](https://github.com/user-attachments/assets/f09edba7-2746-4d4c-99bb-60ff2ff1e12e)

**Expected result:**
The selected control should have a solid border or border line in the DemoConsole application, like this issue https://github.com/dotnet/winforms/issues/11353
![image](https://github.com/user-attachments/assets/aba6486c-0e6a-41f2-a0d8-41a17b2726bb)

### Steps to reproduce
Test sample:  [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole)  bases on feature/10.0 branch in Winforms repo.

**Comment by merriemcgaw** [comment]
can your team take the initial investigation?

**Comment by Zheng-Li01** [comment]
Verified the issue on feature/10.0 branch of dotnet/winforms repo that the issue has been fixed as below screenshot.
![image](https://github.com/user-attachments/assets/d2a0f77f-c808-4791-95b7-973d6a00d4bc)

**Comment by LeafShi1** [comment]
> can your team take the initial investigation?

This issue has been fixed in [PR #11822](https://github.com/dotnet/winforms/pull/11822)
