### ISSUE TITLE
The DemoConsole app under the Winforms repo will stop running when delete the RichTextBox control under ToolStripContainer tab

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#11790]
### .NET version

feature/10.0 branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this was changed after the PR https://github.com/dotnet/winforms/pull/11678

### Issue description

**Actual result in [[DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole))]** test app:
The DemoConsole app under the Winforms repo will stop running when delete the RichTextBox control under ToolStripContainer tab with **Debug** mode
![GHIssue1](https://github.com/user-attachments/assets/ebb85c0b-5beb-4696-8eb5-f7151383526d)

**Debug Call Stack:**
![Exceptions](https://github.com/user-attachments/assets/e4306a14-66f4-438c-9120-234b34d2d838)

**Expected result:**
The DemoConsole app under the Winforms repo running well when delete the RichTextBox control under ToolStripContainer tab

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) bases on feature/10.0 branch in Winforms repo on **Debug** mode.

**More info:**
The issue cannot reproduce on **release** mode
![ReleaseMode](https://github.com/user-attachments/assets/8f1e5643-a3a2-47c8-867b-0cabf35f6ec1)

**Comment by LeafShi1** [comment]
This is not a bug. This issue occurs in SplitContainer, when deleting a control from SplitterPanel, it will jump into following Assert of the function GetApplyStateFlags https://github.com/dotnet/winforms/blob/7006c1c2c5515bc4b648e5b3c2ea6a604867e0b9/src/System.Windows.Forms/src/System/Windows/Forms/Rendering/TextRenderer.cs#L635-L638

Stop running when delete the RichTextBox only appears when debug with "Start Without Debugging"

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 @ricardobossan  - please investigate if this is intentional or not to apply the Graphics transforms (clipping / translate) when rendering text to the Graphics. Why are we trying to apply transform but at the same time it's set to none?

```
apply.HasFlag(ApplyGraphicsProperties.Clipping)
false
```

```
at System.Windows.Forms.TextRenderer.GetApplyStateFlags(IDeviceContext deviceContext, TextFormatFlags textFormatFlags) in C:\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Rendering\TextRenderer.cs:line 635
   at System.Windows.Forms.TextRenderer.DrawTextInternal(IDeviceContext dc, ReadOnlySpan`1 text, Font font, Rectangle bounds, Color foreColor, Color backColor, TextFormatFlags flags) in C:\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Rendering\TextRenderer.cs:line 307
   at System.Windows.Forms.TextRenderer.DrawTextInternal(IDeviceContext dc, ReadOnlySpan`1 text, Font font, Point pt, Color foreColor, Color backColor, TextFormatFlags flags) in C:\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Rendering\TextRenderer.cs:line 287
   at System.Windows.Forms.TextRenderer.DrawText(IDeviceContext dc, String text, Font font, Point pt, Color foreColor, TextFormatFlags flags) in C:\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Rendering\TextRenderer.cs:line 75
   at System.Windows.Forms.Design.SplitterPanelDesigner.DrawWaterMark(Graphics g) in C:\winforms\src\System.Windows.Forms.Design\src\System\Windows\Forms\Design\SplitterPanelDesigner.cs:line 193
   at System.Windows.Forms.Design.SplitterPanelDesigner.OnPaintAdornments(PaintEventArgs pe) in C:\winforms\src\System.Windows.Forms.Design\src\System\Windows\Forms\Design\SplitterPanelDesigner.cs:line 212
```

If there are not supposed to be any transforms, then add `SkipAssertFlag` here (I think ?) - https://github.com/dotnet/winforms/blob/3983d447c60fb64f0dac8a6cecad65411f02a5bd/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitterPanelDesigner.cs#L193

**Comment by LeafShi1** [comment]
`SkipAssertFlag` is internal, so it cannot be used in `SplitterPanelDesigner.cs`  
<img width="672" alt="image" src="https://github.com/user-attachments/assets/5702bcf8-2e7a-42d9-8a53-a51742c8f77b">

**Comment by ricardobossan** [comment]
I have submitted PR #11876, applying [Leaf's suggestion](https://github.com/dotnet/winforms/issues/11790#issuecomment-2288199065) for this issue.

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 
>I don't know why it applies the Graphics transforms but sets it to none at the same time

Yes, you are right, we should preserve both transforms.

It seems that we have multiple cases where TextRenderer.DrawText is called with the Default flags. Could you please investigate if we are missing flags in other places in Design namespace? For example any TextRenderer.DrawText calls from the ControlDesigner WM_PAINT message handler.

**Comment by LeafShi1** [comment]
There are 2 places are using TextRenderer.DrawText in Design namespace

1. In class [HelpTextLabel](https://github.com/dotnet/winforms/blob/e4085eb08ceef38d44b0bcdae0bc02e374794979/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingPicker.cs#L1855) and there is the same issue 
![HelpTextLabel](https://github.com/user-attachments/assets/854d3e50-6301-4c0b-af75-55a239bd1ace)
2. In class [SplitButton](https://github.com/dotnet/winforms/blob/e4085eb08ceef38d44b0bcdae0bc02e374794979/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.SplitButton.cs#L233), but there is no SplitButton [with null or empty text](https://github.com/dotnet/winforms/blob/e4085eb08ceef38d44b0bcdae0bc02e374794979/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.SplitButton.cs#L231-L234), so I cannot reproduce this issue

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - for both issues where are we setting transforms? in the ControlDesigner winproc?
For issue2 - perhaps you can set some fake test in the source code for experiment purposes only?

**Comment by LeafShi1** [comment]
> 1. HelpTextLabel

No, the transforms are set in Control [WmPaint ](https://github.com/dotnet/winforms/blob/db069508ed1b2dcc7ebe28a21bcbd3d925c0daa0/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L12084-L12092)

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/0f7f9bc5-69db-4de3-9c32-bc37c49244c0">

**Comment by Tanya-Solyanik** [comment]
>No, for both issues，the transforms are set in Control [WmPaint](https://github.com/dotnet/winforms/blob/db069508ed1b2dcc7ebe28a21bcbd3d925c0daa0/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L12084-L12092)

Thank you, looks like we should fix it.

**Comment by LeafShi1** [comment]
> 
> Thank you, looks like we should fix it. @LeafShi1 @ricardobossan - could you please test HelpTextLable and SplitButton

This issue reproduced in HelpTextLabel, but not reproduce in SplitButton

**HelpTextLabel**:

1. Debug the DemoConsole App
2. Select the DataGridView 
3. Open the smarttag
4. Click the dropdown button of the "Choose Data Source"

![HelpTextLabel](https://github.com/user-attachments/assets/854d3e50-6301-4c0b-af75-55a239bd1ace)

- Track this issue with issue #11925

  

**SplitButton**:

1. Add a data to enable property "ShowSplit" of the SplitButton
    <img width="910" alt="image" src="https://github.com/user-attachments/assets/32fbfc09-d8ec-4491-b78b-153427566cde">
2. Debug the DemoConsole App
3. Select the ContextMenuStrip1 and open the smarttag
4. Click "Edit Items..."
6. The SplitButton can be show successfully and DemoConsole App run normally
   
![SplitButton](https://github.com/user-attachments/assets/72741f83-a336-4cb4-bb11-5a43b8d427b1)

**Comment by Liv-Goh** [comment]
Verified this issue on WinForms release/9.0 repository DemoConsole test app, the issue has been fixed, the app is fine after delete the richTextBox in debug mode
![DemoConsoleDeleteRichTextBoxFixed](https://github.com/user-attachments/assets/361148f1-557b-4b35-84a5-2752bfa0d7ed)

**Comment by Philip-Wang01** [comment]
Verified this issue on WinForms main repository DemoConsole test app, the issue has been fixed, the app is fine after delete the richTextBox in debug mode. The test results are the same as above.
