### ISSUE TITLE
The SplitContainer control cannot be deleted successfully under ToolStripContainer tab 

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#11793]
### .NET version

feature/10.0 branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this was changed after the PR https://github.com/dotnet/winforms/pull/11678

### Issue description

**Actual result in [[DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole)] test app:**
The SplitContainer control cannot be deleted successfully under ToolStripContainer tab 
![image](https://github.com/user-attachments/assets/233b725b-9c5c-4ef6-8e15-b1477e110c0a)
![GHIssue4](https://github.com/user-attachments/assets/34f61fbf-1302-4904-8ccd-b16363096f11)

**Expected result:**
The SplitContainer control can be deleted successfully under ToolStripContainer tab 

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) bases on feature/10.0 branch in Winforms repo.

**Comment by MandiMan** [comment]
Verified on the main branch of the Winforms repo that this issue has been fixed, the SplitContainer control can be deleted successfully under ToolStripContainer tab.

https://github.com/user-attachments/assets/32337eef-6266-46d2-bfa6-bd1a4abbb561
