### ISSUE TITLE
Non-SDK NETFX4.8 project referencing .netstandard2.0 - PlatformNotSupportedException

### ISSUE THREAD

**Issue by calledude** [dotnet/winforms#11817]
### .NET version

.NET Framework 4.8 / netstandard2.0

### Did it work in .NET Framework?

No

### Issue description

Upon calling code in a .netstandard2.0 project which in turn calls into `System.Drawing.Common` from a .net48 project, things like `PrinterSettings.InstalledPrinters` throws a `PlatformNotSupportedException` exception

After installing `System.Drawing.Common` to the non-SDK project, the issue goes away. This should not be needed

### Steps to reproduce

1. Create a non-SDK net48 console app
2. Create a class library
3. Add a reference to `System.Drawing.Common` to the class library
4. Create a method which does something, e.g. `Console.WriteLine(PrintSettings.InstalledPrinters)`
5. Reference the class library from the non-sdk project
6. Call the method created in step 4 from `Main()`
7. Start the console app

**Comment by RussKie** [comment]
System.Drawing.Common (or parts of) are only supported on explicit TFMs that target Windows and not on NS2.0
https://github.com/dotnet/winforms/blob/aef1eaca434a40b51743c2b1ac41ed3a2ea3387c/src/System.Drawing.Common/src/System.Drawing.Common.csproj#L81-L84
https://github.com/dotnet/winforms/blob/aef1eaca434a40b51743c2b1ac41ed3a2ea3387c/src/System.Drawing.Common/src/Special/NotSupported.cs#L3008-L3046

**Comment by calledude** [comment]
> System.Drawing.Common (or parts of) are only supported on explicit TFMs that target Windows and not on NS2.0
> 
> https://github.com/dotnet/winforms/blob/aef1eaca434a40b51743c2b1ac41ed3a2ea3387c/src/System.Drawing.Common/src/System.Drawing.Common.csproj#L81-L84
> 
> 
> https://github.com/dotnet/winforms/blob/aef1eaca434a40b51743c2b1ac41ed3a2ea3387c/src/System.Drawing.Common/src/Special/NotSupported.cs#L3008-L3046

Interesting! This seems to suggest that a non-SDK project resolves the ns2.0 dependency then, whereas a SDK project would resolve whichever dependency closest matches its TFM

Because again, this issue is only present for non-SDK projects

**Comment by RussKie** [comment]
As a possible workaround, try multi-targeting your shared library to NS2.0 and net48. This way, the net48 project will reference the net48 artifacts of the shared library.
