### ISSUE TITLE
Update the PR template with link to Accessibility Insights tool guide

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1183]
**Problem description:**

Update the PR template with a link to a guide on how to use the Accessibility Insights tool.
Requested in https://github.com/dotnet/winforms/pull/1172#discussion_r295874239.

@merriemcgaw will provede the link.

**Comment by merriemcgaw** [comment]
https://accessibilityinsights.io/https://accessibilityinsights.io/

**Comment by merriemcgaw** [comment]
Fixed with #1196
