### ISSUE TITLE
DragDropEffects display incorrectly

### ISSUE THREAD

**Issue by Liv-Goh** [dotnet/winforms#11847]
### .NET version

.NET 9.0 SDK build: 9.0-rc 1.24407.28

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue. Not reproduce on .NET 8.0

### Issue description

The DrapDropEffects can be observer from the cursor icon. When drag the control from the label to the listBox it display incorrectly in .NET 9.0.

**Current Behavior (.NET 9.0)**
![dragDropEffect29 0](https://github.com/user-attachments/assets/5da9c5c2-5faa-4a5d-8fd9-56c09e892adb)

**Expected Behavior (.NET 8.0)**
![dragDropEffect28 0](https://github.com/user-attachments/assets/3077e197-145b-4952-9939-c03b32d77c83)

### Steps to reproduce

1. Create a WinForms .NET Core project
2. Add a label and listBox to the form
3. Set the allowDrop property for both control to True
4. Link the events for the controls as below
```
private void label1_MouseDown(object sender, MouseEventArgs e)
{
    label1.DoDragDrop(label1.Text, DragDropEffects.Copy | DragDropEffects.Move);
}

private void listBox1_DragEnter(object sender, DragEventArgs e)
{
    e.Effect = DragDropEffects.Copy;
}

private void listBox1_DragDrop(object sender, DragEventArgs e)
{
    listBox1.Items.Add(e.Data.GetData(DataFormats.Text).ToString());                
}
```
5. Build and run the project
6. Try to drag the label to the listBox and observe the change of cursor icon

**Comment by lonitra** [comment]
@Olina-Zhang https://github.com/dotnet/winforms/pull/11853 will fix this in main. This regressed back in Preview 1. Could your team do some additional testing around drag/drop for anything else we may have regressed?

**Comment by elachlan** [comment]
@willibrandon might be interested in the drag drop regression.

**Comment by Syareel-Sukeri** [comment]
Verified this issue in the release/9.0, DragDropEffects cursor icon in .NET 9.0 is fixed.

https://github.com/user-attachments/assets/37430cea-470c-4a39-9304-f515f15ce7c1

**Comment by IrinaPykhova** [comment]
For the record, I have exactly the same issue with my WinForms controls. Will wait for RC1 to verify

**Comment by Philip-Wang01** [comment]
Verified the issue with .NET 9.0.100-rc.1.24422.10 test pass build that the issue has been fixed, which have the same results as above.
