### ISSUE TITLE
Port System.Drawing docs for .NET 9 APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/winforms#11858]
@merriemcgaw @JeremyKuhne 

Below is the list of APIs that still show up as undocumented in dotnet-api-docs and were introduced in .NET 9.

Full porting instructions can be found in the [main issue](https://github.com/dotnet/runtime/issues/105974).

This task needs to be finished **the day before the RC2 snap** (September 15th).

RC1 Undoc APIs as of 10/01: https://github.com/dotnet/winforms/issues/11858#issuecomment-2387143098

**Comment by merriemcgaw** [comment]
Thanks for picking this up @lonitra! We also have the new APIs around `DarkMode` and Async to make sure we've documented.

**Comment by carlossanlop** [comment]
P7 Undoc APIs as of 08/20:

| Summary  | Parameters | TypeParameters | ReturnValue | API                                                                                                                                                                                                                                                                                                                 |
|----------|------------|----------------|-------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Bitmap.ApplyEffect(System.Drawing.Imaging.Effects.Effect,System.Drawing.Rectangle)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Bitmap.xml)                                                                                                                            |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Bitmap.ConvertFormat(System.Drawing.Imaging.PixelFormat,System.Drawing.Imaging.DitherType,System.Drawing.Imaging.PaletteType,System.Drawing.Imaging.ColorPalette,System.Single)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Bitmap.xml)                               |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Bitmap.ConvertFormat(System.Drawing.Imaging.PixelFormat)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Bitmap.xml)                                                                                                                                                      |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawBeziers(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.Point})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                          |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawBeziers(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.PointF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                         |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawClosedCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.PointF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                     |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawClosedCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.PointF},System.Single,System.Drawing.Drawing2D.FillMode)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                     |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawClosedCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.Point},System.Single,System.Drawing.Drawing2D.FillMode)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                      |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawClosedCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.Point})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                      |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.PointF},System.Single)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                             |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.Point},System.Int32,System.Int32,System.Single)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                    |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.PointF},System.Int32,System.Int32)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                 |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.PointF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                           |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.PointF},System.Int32,System.Int32,System.Single)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                   |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.Point},System.Single)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                              |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawCurve(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.Point})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                            |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawImage(System.Drawing.Image,System.Drawing.Imaging.Effects.Effect,System.Drawing.RectangleF,System.Drawing.Drawing2D.Matrix,System.Drawing.GraphicsUnit,System.Drawing.Imaging.ImageAttributes)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml) |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawImage(System.Drawing.Image,System.Drawing.Imaging.Effects.Effect)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                              |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawLines(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.Point})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                            |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawLines(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.PointF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                           |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawPolygon(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.Point})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                          |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawPolygon(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.PointF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                         |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawRectangles(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.RectangleF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                  |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawRectangles(System.Drawing.Pen,System.ReadOnlySpan{System.Drawing.Rectangle})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                   |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawRoundedRectangle(System.Drawing.Pen,System.Drawing.Rectangle,System.Drawing.Size)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                              |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.DrawRoundedRectangle(System.Drawing.Pen,System.Drawing.RectangleF,System.Drawing.SizeF)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                            |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.PointF},System.Drawing.Drawing2D.FillMode,System.Single)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                   |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.Point},System.Drawing.Drawing2D.FillMode,System.Single)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                    |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.PointF},System.Drawing.Drawing2D.FillMode)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                 |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.Point},System.Drawing.Drawing2D.FillMode)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                  |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.PointF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                   |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillClosedCurve(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.Point})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                    |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillPolygon(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.PointF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                       |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillPolygon(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.PointF},System.Drawing.Drawing2D.FillMode)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                     |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillPolygon(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.Point},System.Drawing.Drawing2D.FillMode)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                      |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillPolygon(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.Point})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                        |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillRectangles(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.RectangleF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillRectangles(System.Drawing.Brush,System.ReadOnlySpan{System.Drawing.Rectangle})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                                 |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillRoundedRectangle(System.Drawing.Brush,System.Drawing.Rectangle,System.Drawing.Size)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                            |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.FillRoundedRectangle(System.Drawing.Brush,System.Drawing.RectangleF,System.Drawing.SizeF)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                                                                          |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.TransformPoints(System.Drawing.Drawing2D.CoordinateSpace,System.Drawing.Drawing2D.CoordinateSpace,System.ReadOnlySpan{System.Drawing.Point})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                       |
| Missing  | Missing    | NA             | NA          | [M:System.Drawing.Graphics.TransformPoints(System.Drawing.Drawing2D.CoordinateSpace,System.Drawing.Drawing2D.CoordinateSpace,System.ReadOnlySpan{System.Drawing.PointF})](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/Graphics.xml)                                                      |

**Comment by carlossanlop** [comment]
Reopening as there are some RC1 APIs that need to be documented (2024/10/01):

| API                                                                                                                                                                  | Summary  | Parameters | TypeParameters | ReturnValue |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|------------|----------------|-------------|
| [P:System.Drawing.SystemColors.UseAlternativeColorSet](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing/SystemColors.xml)                      | Missing  | NA         | NA             | NA          |
| [N:System.Drawing.Imaging.Effects](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/ns-System.Drawing.Imaging.Effects.xml)                                    | Missing  | NA         | NA             | NA          |
| [M:System.Drawing.Imaging.Effects.Effect.Dispose(System.Boolean)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Drawing.Imaging.Effects/Effect.xml) | Missing  | Missing    | NA             | NA          |
