### ISSUE TITLE
The DemoConsole application in the Winforms repo stops running when opening the control's smarttag

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#11862]
### .NET version

feature/10.0 branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue. Not repro on .NET 9.0 from main branch of WinForms repo.

### Issue description

**Actual result in [[DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole))] test app:**
The DemoConsole application in the Winforms repo stops running when opening the control's smarttag.
![stop running](https://github.com/user-attachments/assets/cb3a88b6-bca9-45c9-9a05-dc2c4b685511)
![Screenshot 2024-08-13 025510](https://github.com/user-attachments/assets/41563b5c-cd41-41fe-9aeb-6fa1a81e82c5)

**Call Stack:**
[log.txt](https://github.com/user-attachments/files/16593931/log.txt)

**Expected result:**
The DemoConsole application in the Winforms repo running well when opening the control's smarttag.

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) bases on feature/10.0 branch in Winforms repo.

**Comment by Epica3055** [comment]
seems that this issue is caused by [this commit](https://github.com/dotnet/winforms/commit/db2224eda6d5345a733fa67de8d2781e30a9a433).

**Comment by Tanya-Solyanik** [comment]
@Epica3055  - you quoted a merge commit, is it possible to narrow down to the specific commit in that merge? On the second thought it might be easier get the callstack and fix this issue rather than searching for the commit.

**Comment by Epica3055** [comment]
@Tanya-Solyanik Sure

**Comment by MelonWang1** [comment]
Verified this issue on winforms repo from main branch, it has been fixed: the DemoConsole application in the Winforms repo running well when opening the co

https://github.com/user-attachments/assets/429a99a5-a476-46e8-8503-cb124673cc28

ntrol's smarttag.
