### ISSUE TITLE
[Loc]The translations of "Categorized", "Alphabetical" and "Property Pages" in Property Grid are not consistent between .Net Core and .Net framework

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/winforms#1188]
* VS: Version 16.2.0 Preview 3 [29020.229.d16.2]
* .NET Core Version: 3.0.100-preview7-012535 from master branch
* Affected Languages: CHT, CSY, DEU, FRA, PTB

**More info:**
This issue cannot reproduce in those local languages:  CHS, RUS, JPN, KOR, PLK, ITA, TRK, ESN

**Steps to reproduce:**

1. Install latest VS & .NET Core 3.0 on loc machine, then open the attached app.
[WindowsFormsApp7.zip](https://github.com/dotnet/winforms/files/3314080/WindowsFormsApp7.zip)
3. Run it and focus on the toolbar of Property Grid using mouse .

**Actual Result:**
The translations of "Categorized", "Alphabetical" and "Property Pages" in Property Grid are not consistent between .Net Core and .Net framework
![Category](https://user-images.githubusercontent.com/49627022/59917177-d2b84980-9453-11e9-9177-ec8973f3f20c.png)

**Expected Result:**
The translations of "Categorized", "Alphabetical" and "Property Pages" in Property Grid should be consistent between .Net Core and .Net framework.

**Comment by lukaschal** [comment]
Fixed on all languages.

0; "PBRSToolTipCategorized"
0; "PBRSToolTipAlphabetic"
0; "PBRSToolTipPropertyPages"

**Comment by RussKie** [comment]
@lukaschal is there anything that need changing in the source?

**Comment by lukaschal** [comment]
@RussKie I think so no change is needed in source.

**Comment by Amy-Li02** [comment]
Verified this issue in .Net Core 3.0.100-preview8-013096 from master branch, the issue were fixed and in 13 local languages it all works well.
![Fixed-PTB](https://user-images.githubusercontent.com/49627022/61107168-d1f26080-a4b1-11e9-840b-ccfd05cfec95.png)
