### ISSUE TITLE
Form's FormBorderColor property value always is Black although has changed it to another color value

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#11897]
### .NET version

.NET SDK 9.0.100-rc.1.24415.1 + build private dll form winforms repo release/9.0 branch

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this is a new feature Dark Mode: https://github.com/dotnet/winforms/pull/11857

### Issue description

Form's FormBorderColor property value always is Black although has changed it to another color value.

**Actual result:**
The value is 'Black' in textbox control.
![FormBorderColor](https://github.com/user-attachments/assets/0277bd16-43f9-4456-af26-7ecfd1d7dedf)

**Expected result:**
The value should be 'Green' in textbox control.

**More info:**
This issue occurs in FormCaptionBackColor and FormCaptionTextColor properties too.

### Steps to reproduce

1. Launch the [FormBorderColor-TestApp.zip](https://github.com/user-attachments/files/16635417/FormBorderColor-TestApp.zip) project in VS and run it.
2. Observe the value in textbox control.

**Comment by John-Qiao** [comment]
Verified this issue on 9.0.100-rc.2.24419.18 with dlls built from winforms repo of main branch, it was fixed: the values all are correct in textbox controls now.

![11897-testresult](https://github.com/user-attachments/assets/6b04cfca-5e5f-4ece-8a95-3f24812bac93)

**Comment by MandiMan** [comment]
Verified this issue in the latest .NET 9 RC1 build: 9.0.100-rc.1.24421.9 from [https://aka.ms/dotnet/9.0.1xx-rc1/daily/dotnet-sdk-win-x64.exe](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fdotnet%2F9.0.1xx-rc1%2Fdaily%2Fdotnet-sdk-win-x64.exe&data=05%7C02%7Cv-melonwang%40microsoft.com%7C0d65c5b4d8b04a97eba108dcc1879c36%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638598035460614309%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=nVdjCoLTpuFD7kgzBgdC%2F3LkvwcZe3KAW7%2Fv9zCJVGU%3D&reserved=0), which partial fixed that can get the expected values "Green" in textbox controls, but FormBorderColor, FormCaptionBackColor, FormCaptionTextColor are not set to green.
![image](https://github.com/user-attachments/assets/408457a3-c2dd-4d69-baa8-f2a5e4da5a57)

**Comment by MandiMan** [comment]
Verified the issue with .NET 9.0.100-rc.1.24422.10 test pass build that the issue partial fixed in constructor and form_load. We can get the expected values "Green" in textbox controls, but FormBorderColor, FormCaptionBackColor, FormCaptionTextColor are not set to green.
![image](https://github.com/user-attachments/assets/e9514bcf-4104-423d-b208-683b32c90a57)


![image](https://github.com/user-attachments/assets/5a9f31c2-95df-409b-89a9-bf67714533d1)

**Comment by Nora-Zhou01** [comment]
Verified this issue in the latest .NET9.0 SDK build: 9.0.100-rc.2.24428.9, write the code in form_load, it was fixed, but in constructor, partial fixed.
![1](https://github.com/user-attachments/assets/a961a43b-49ca-4070-8eae-98c51d6d10c2)
![2](https://github.com/user-attachments/assets/fd7e20dd-98d5-403e-a713-b237727e0f43)

**Comment by MandiMan** [comment]
Verified the issue with .NET 9.0.100-rc.1.24452.12 test pass build that the issue partial fixed in constructor and form_load. We can get the expected values "Green" in textbox controls, but FormBorderColor, FormCaptionBackColor, FormCaptionTextColor are not set to green. Test result is same as https://github.com/dotnet/winforms/issues/11897#issuecomment-2311443014

**Comment by John-Qiao** [comment]
Verified the issue with .NET 9.0.100-rc.2.24474.11 test pass build that the issue partial fixed in constructor and form_load. We can get the expected values "Green" in textbox controls, but FormBorderColor, FormCaptionBackColor, FormCaptionTextColor are not set to green. Test result is same as https://github.com/dotnet/winforms/issues/11897#issuecomment-2311443014

**Comment by John-Qiao** [comment]
Verified this issue with latest .NET 10.0.100-alpha.1.24508.48 from main branch, it was fixed: the values all are correct in textbox controls now.

![Image](https://github.com/user-attachments/assets/71c58053-38be-4d5e-b4e2-9b3b0deb0778)
