### ISSUE TITLE
The FormCaptionTextColorChanged event property of the Form does not work

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#11898]
### .NET version

.NET SDK 9.0.100-rc.1.24415.1 + build private dll form winforms repo release/9.0 branch

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this is a new feature Dark Mode: https://github.com/dotnet/winforms/pull/11857

### Issue description

Form's FormCaptionTextColorChanged event property doesn't work, can't display text color correctly.
**Actual result:**
![11898](https://github.com/user-attachments/assets/588329d5-fb55-4d73-bcb5-859e93c119c7)

**Expected result:**
The FormCaptionTextColorChanged event of the Form should display the text color correctly.

### Steps to reproduce

1. Launch the[FormCaptionTextColorChanged-TestApp.zip](https://github.com/user-attachments/files/16656774/FormCaptionTextColorChanged-TestApp.zip) project in VS and run it.
2. Observe the value in textbox control.

**Comment by Zheng-Li01** [comment]
Verified the issue with .NET SDK 9.0.100-rc.2.24420.21 + private dlls built from winforms repo main branch , the issue has been fixed that the FormCaptionTextColorChanged event property of the Form work working well as below screenshot.
![image](https://github.com/user-attachments/assets/3f9e0baf-e520-48d4-9d07-2e9821601327)

**Comment by Nora-Zhou01** [comment]
Verified this issue in the latest .NET 9 RC1 build: 9.0.100-rc.1.24421.9 from [https://aka.ms/dotnet/9.0.1xx-rc1/daily/dotnet-sdk-win-x64.exe](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fdotnet%2F9.0.1xx-rc1%2Fdaily%2Fdotnet-sdk-win-x64.exe&data=05%7C02%7Cv-melonwang%40microsoft.com%7C0d65c5b4d8b04a97eba108dcc1879c36%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638598035460614309%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=nVdjCoLTpuFD7kgzBgdC%2F3LkvwcZe3KAW7%2Fv9zCJVGU%3D&reserved=0), it was fixed:
![11898](https://github.com/user-attachments/assets/f272ff26-2c52-4d64-9409-c073d6076235)

**Comment by Zheng-Li01** [comment]
Verified the issue with .NET 9.0.100-rc.1.24422.10 test pass build, the issue has been fixed that have the same results as above.

**Comment by John-Qiao** [comment]
Verified this issue in the latest .NET9.0 SDK build: 9.0.100-rc.2.24428.6, it was fixed. Same test result as above.

**Comment by Zheng-Li01** [comment]
Verified the issue with .NET 9.0.100-rc.1.24452.12 test pass build that the issue has been fixed that have the same results as above.

**Comment by Nora-Zhou01** [comment]
Verified the issue with .NET 9.0.100-rc.2.24474.11 test pass build that the issue has been fixed, which have the same results as above.
