### ISSUE TITLE
Form's FormCornerPreference property value cannot back to Default when change it from a non-Default value

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#11895]
### .NET version

.NET SDK 9.0.100-rc.1.24415.1 + build private dll form winforms repo release/9.0 branch

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this is a new feature Dark Mode: https://github.com/dotnet/winforms/pull/11857

### Issue description

Form's FormCornerPreference property value cannot back to Default when change it from a non-Default value.

**Actual result:**
The value is 'Round' in textbox control.
![FormCornerPreference](https://github.com/user-attachments/assets/e1450adc-fa0a-44dd-a33f-50c46930f481)

**Expected result:**
The value should be 'Default' in textbox control.

### Steps to reproduce

1. Launch the [FormCornerPreference-TestApp.zip](https://github.com/user-attachments/files/16635324/FormCornerPreference-TestApp.zip) project in VS and run it.
2. Observe the value in textbox control.

**Comment by John-Qiao** [comment]
Verified this issue on 9.0.100-rc.2.24419.18 with dlls built from winforms repo of main branch, it was fixed: the value is 'Default' in textbox control now.

![11895-testresult](https://github.com/user-attachments/assets/acfc8edf-fa7d-4015-a027-8ed9d8c84c40)

**Comment by MelonWang1** [comment]
@KlausLoeffelmann Verified this issue in the latest .NET 9 RC1 build: 9.0.100-rc.1.24421.39 from [https://aka.ms/dotnet/9.0.1xx-rc1/daily/dotnet-sdk-win-x64.exe](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fdotnet%2F9.0.1xx-rc1%2Fdaily%2Fdotnet-sdk-win-x64.exe&data=05%7C02%7Cv-melonwang%40microsoft.com%7C0d65c5b4d8b04a97eba108dcc1879c36%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638598035460614309%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=nVdjCoLTpuFD7kgzBgdC%2F3LkvwcZe3KAW7%2Fv9zCJVGU%3D&reserved=0), it still repro. The value cannot back to 'Default' in textbox control. 
![image](https://github.com/user-attachments/assets/ef0129d5-07af-47a9-8628-2c96b773763b)

**Comment by MelonWang1** [comment]
Verified the issue with .NET 9.0.100-rc.1.24422.10 test pass build, it still repro, have the same results as above.

**Comment by MandiMan** [comment]
Verified this issue in the latest .NET9.0 SDK build: 9.0.100-rc.2.24428.9, it still repro, have the same results as above.

**Comment by John-Qiao** [comment]
Verified the issue with .NET 9.0.100-rc.2.24474.11 test pass build, it still repro, have the same results as above.

**Comment by John-Qiao** [comment]
Verified this issue with latest .NET 10.0.100-alpha.1.24508.48 from main branch, it was fixed: the value is 'Default' in textbox control now.

![Image](https://github.com/user-attachments/assets/c6a30361-76a6-4ec3-a4a8-28a038110f34)
