### ISSUE TITLE
[DarkMode] Dark Mode breaks Visual Basic App Framework enabled classic VisualStyles

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#11910]
### .NET version

Visual Styles cannot be enabled any longer in .NET 9.

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, in all of them.

### Issue description

By default, (classic) Visual Styles are enabled in the Visual Basic Application Framework. This is also reflected by the Application Framework Project System Property Pages. Enabling or Disabling Visual Styles has no impact for Visual Basic Application Framework Apps.

### Steps to reproduce

* Create a new .NET 9 VB App Framework WinForms App.
* Alternatively, load an existing VB App.
* Make sure in the Project Property Pages, that Visual Styles are activated.
* Confirm, in Application.MyApp that the settings from the UI got applied and the correct code got code-generated.
* Run the App.

**Comment by Syareel-Sukeri** [comment]
Verified this issue in the latest .NET 9 RC1 build: 9.0.100-rc.1.24421.9 from [https://aka.ms/dotnet/9.0.1xx-rc1/daily/dotnet-sdk-win-x64.exe](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fdotnet%2F9.0.1xx-rc1%2Fdaily%2Fdotnet-sdk-win-x64.exe&data=05%7C02%7Cv-melonwang%40microsoft.com%7C0d65c5b4d8b04a97eba108dcc1879c36%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638598035460614309%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=nVdjCoLTpuFD7kgzBgdC%2F3LkvwcZe3KAW7%2Fv9zCJVGU%3D&reserved=0), it was fixed:

![360308689-2e308c53-69eb-4076-ac0e-980086ee4790](https://github.com/user-attachments/assets/20111e07-75f2-4a3b-a116-7e5f3a56206a)

**Comment by MandiMan** [comment]
Verified this issue in the latest .NET9.0 SDK build: 9.0.100-rc.2.24420.21 + dlls built from Winforms main branch, it was fixed:
![image](https://github.com/user-attachments/assets/4ae4ac87-fdb0-4056-b2dd-b48df7a2bbde)

**Comment by Nora-Zhou01** [comment]
Verified the issue with .NET 9.0.100-rc.1.24422.10 test pass build that the issue has been fixed, which have the same results as above.

**Comment by MelonWang1** [comment]
Verified this issue in the latest .NET9.0 SDK build: 9.0.100-rc.2.24428.6, it was fixed. Same test result as above.

**Comment by Nora-Zhou01** [comment]
Verified the issue with .NET 9.0.100-rc.2.24474.11 test pass build that the issue has been fixed, which have the same results as above.
