### ISSUE TITLE
The HelpTextLable cannot be painted in Debug mode

### ISSUE THREAD

**Issue by LeafShi1** [dotnet/winforms#11925]
### .NET version

feature/10.0 branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes

### Issue description

The DemoConsole app under the Winforms repo will stop running when opening the smattag of the DataGridView and click the dropdown button of the "Choose Data Source"

### Steps to reproduce

1. Debug the DemoConsole App
2. Select the DataGridView
3. Open the smarttag
4. Click the dropdown button of the "Choose Data Source"

![HelpTextLabel](https://github.com/user-attachments/assets/854d3e50-6301-4c0b-af75-55a239bd1ace)

**Comment by John-Qiao** [comment]
Verified this issue on winforms repo from main branch, it has been fixed: the dropdown button of the "Choose Data Source" can be clicked successful now.

https://github.com/user-attachments/assets/11c98322-75a1-4d96-8cee-19c9d9d53b14
