### ISSUE TITLE
Cannot get correct value 'NotSet' when setting the ImageLayout value of DataGridViewImage cell with 'NotSet' value

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#11927]
### .NET version

9.0.100-rc.2.24419.18 + private dlls built from winforms repo main branch

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in .Net previous versions and 9.0.100-rc.2.24419.18 SDK build

### Issue description

When setting the ImageLayout value of DataGridViewImageLink cell with **NotSet** value, cannot get **NotSet** value, but **Normal** value. It causes our one automation case failed recently. 

Other ImageLayout values: Normal/Stretch/Zoom work well.

9.0.100-rc.2.24419.18 + private dlls built from winforms repo main branch:
![image](https://github.com/user-attachments/assets/49bb946a-39a2-4266-a55e-52292de50bcd)

9.0.100-rc.2.24419.18: 
![image](https://github.com/user-attachments/assets/05d5285d-b70d-4def-bac7-e056f570118f)

### Steps to reproduce

Test app:
[WinFormsApp22.zip](https://github.com/user-attachments/files/16668567/WinFormsApp22.zip)

**Comment by lonitra** [comment]
@Olina-Zhang could you confirm whether this worked in .NET 8?

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang  - is it possible to get that automation case ported to Unit tests?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang - is it possible to get all automation cases related to property store ported to Unit tests?

Will investigate and try.

**Comment by Liv-Goh** [comment]
Verified this issue on .NET SDK 9.0.100-rc.2.24420.21 + private dlls build from WinForms main repo, the issue has been fixed: ImageLayout "NotSet" value can be retrieved correctly
![ImageLayoutNotSetFixed](https://github.com/user-attachments/assets/c094c065-afdd-4aa8-bac1-80b6fd597c2d)
