### ISSUE TITLE
Moving Clipboard related tests to a new class under collection Sequential 

### ISSUE THREAD

**Issue by LeafShi1** [dotnet/winforms#11948]
Moving the tests that use Clipboard to OriginalFileName.ClipboardTests.cs and [Collection("Sequential")] for it, like PR #11606

**Under Microsoft.VisualBasic.Devices.Tests:**

- [x] ComputerTests.cs
- [x] ClipboardProxyTests.cs

**Under System.Windows.Forms.Tests:**

- [x] ClipboardComTests.cs 
- [x] ClipboardTests.cs 
- [x] TextBoxBaseTests.ClipboardTests.cs 
- [x] RichTextBoxTests.ClipboardTests.cs   #11936
- [x] DataFormatsTests.cs  #11970 
- [x] DataGridViewCellTests.cs  #11936
- [x] DataObjectTests.cs #11970
- [x] DragDropFormatTests.cs  #11970

**Comment by LeafShi1** [comment]
@paul1956 The test under `ComputerTests` needs to verify the state of [Clipboard Properties](https://github.com/dotnet/winforms/blob/a9a317d87a4150f10d57052f117d3745b6ed5ac2/src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/ComputerTests.cs#L18). Since the instance `computer` is only used within this test, it should not be affected by other test cases. Therefore, this file should not need to add [Collection("Sequential")], what do you think?

**Comment by paul1956** [comment]
@LeafShi1 I am pretty sure that there is only one Clipboard, while Computer may be in instance class and it creates a New  instance of ClipboardProxy, eventually you get to the Static System.Windows.Forms.Clipboard and it will not work in parallel. 

```
  <EditorBrowsable(EditorBrowsableState.Never)>
    Public Class ClipboardProxy
       ''' <summary>
        '''  Removes everything from the clipboard.
        ''' </summary>
        Public Sub Clear()
            Clipboard.Clear()
        End Sub
 End Class
```

```
/// <summary>
///  Provides methods to place data on and retrieve data from the system clipboard. This class cannot be inherited.
/// </summary>
public static class Clipboard
```
