### ISSUE TITLE
ContextMenuStrip empties after converting MenuItem to other strip controls and clicking the converted item in DemoConsole application

### ISSUE THREAD

**Issue by Syareel-Sukeri** [dotnet/winforms#11990]
### .NET version

.NET 9.0-rc1 branch of WinForms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this issue also reproduces in the release/9.0 branch of the WinForms repository. In the release/8.0 branch, the ContextMenuStrip item cannot be edited.

### Issue description

Actual result in [[DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole)] test app:
When adding a `MenuItem` and converting it to other strip controls (e.g., `ComboBox`, `Separator`, or `TextBox`), the `ContextMenuStrip` becomes empty after clicking on the converted item.

https://github.com/user-attachments/assets/6a77f80d-8f6f-4fce-a2be-1f222484e620

Expected Result:
The `ContextMenuStrip` remains populated and is not emptied.

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

1. Add a MenuItem to the ContextMenuStrip.
2. Right-click the MenuItem, hover over "Convert to," and select any available control.
3. Click the input field below the converted item.
4. Next, click the converted item.
5. Observe the result.

**Comment by merriemcgaw** [comment]
This is really expanding the capabilities of the demoConsole application. I would consider this low priority and something that we can pick up as time permits.

**Comment by merriemcgaw** [comment]
Upon further consideration, I think we won't get to this in the near future. This is more of replicating VS behaviors and not critical in a test application.
