### ISSUE TITLE
Clipboard Tests still failing

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#12002]
### Test

System.Windows.Forms.Tests.TextBoxBaseTests+ClipboardTests.TextBoxBase_ClearUndo_CanUndo_Success

It's very random as to which tests fail and how many, I have seem between 0 and 6 on GitHub and locally. Even if you just manually run the tests in just 1 class.

### Issue description

Failing Clipboard tests are causing build to fail.

**Comment by LeafShi1** [comment]
The error message of the test [TextBoxBase_ClearUndo_CanUndo_Success](https://github.com/dotnet/winforms/blob/2ac4c4bbe27362c994a2f480535df4aedd774876/src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.ClipboardTests.cs#L12):

```
Assert.Equal() Failure: Strings differ
↓ (pos 0)
Expected: "bcxt"
Actual:   "xt"
↑ (pos 0)

```

It looks like the clipboard is cleared between copy and paste
```
 using SubTextBox control = new()
 {
     Text = "abc",
     SelectionStart = 1,
     SelectionLength = 2
 };
 control.Copy();

 control.Text = "text";
 control.SelectionLength = 2;
 control.Paste();
 Assert.Equal("bcxt", control.Text);
```

**Comment by paul1956** [comment]
@LeafShi1 Yes but what is clearing the clipboard? Shouldn't "Sequential" shop that?

I can run every failing test individually without failure. But if I just run the all the tests in TextBoxBaseTests.ClipboardTests with nothing else going on at least 1 test fails, below you see 3-6 of 10 fail. This file has [Collection("Sequential")] on top.
![image](https://github.com/user-attachments/assets/4de42a88-bc90-45ed-bec3-16457bbd3297)
![image](https://github.com/user-attachments/assets/e78537ba-9444-41ea-8a88-1c344bb15512)

**Comment by LeafShi1** [comment]
> I can run every failing test individually without failure. But if I just run the all the tests in TextBoxBaseTests.ClipboardTests with nothing else going on at least 1 test fails, below you see 3-6 of 10 fail. This file has [Collection("Sequential")] on top. 

Each test case in TextBoxBaseTests.ClipboardTests creates a new SubTextBox instance and operates on it in its own context, with no dependencies between them. I tried adding some new assertions and clearing the clipboard at the end of the test case, hoping that helps.

**Comment by LeafShi1** [comment]
@paul1956 It looks like you can reproduce these failures on your local machine, but I can't reproduce them on my side, I can only see these failures in the CI pipeline. So what machine are you using? What is the configuration of the machine?

**Comment by paul1956** [comment]
> @paul1956 It looks like you can reproduce these failures on your local machine, but I can't reproduce them on my side, I can only see these failures in the CI pipeline. So what machine are you using? What is the configuration of the machine?

8 core, windows 11 Professional, 16 gig memory and SD hard drive.

They don’t happen every time, I sometimes have to run till failure if I am just running 1 test class. If I run all tests I get at least 1 failure every run which talked about 20 minutes.

**Comment by LeafShi1** [comment]
I tried using the "run until failure" feature and the test cases failed after 6~10 iterations on my local machine.

And I did following verification:
```
 control.Text = "text";
 control.SelectionLength = 2;

 control.SelectedText.Should().Be("te");
 Clipboard.GetText().Should().Be("bc");
 control.Paste();
 control.Text.Should().Be("bcxt");
```
