### ISSUE TITLE
The DemoConsole app under the Winforms repo will stop running when click the MaskedTextBox control under Use Grid (Snap to the grid) tab with Debug mode

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#12007]
### .NET version

main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

This is not a regression issue. Repro started adding this control to the DemoConsole application

### Issue description

The DemoConsole app under the Winforms repo will stop running when click the MaskedTextBox control under Use Grid tab (Snap to the grid) with **Debug** mode

https://github.com/user-attachments/assets/2bc44642-4aa0-4197-8a52-493cb1bb2ef9

![image](https://github.com/user-attachments/assets/a4a26778-cb74-4168-a35b-6d6cfa3491e6)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo on **Debug** mode

**More Info:**
The issue cannot reproduce on **release** mode

**Comment by merriemcgaw** [comment]
I'm going to consider this expected behavior - I don't think we have implemented the services it mentions, nor would we in this sample application. Closing as expected.
