### ISSUE TITLE
BindingNavigator control via “Edit Items... “when adding an item, it shows that the "Cannot create an abstract class" in DemoConsole application

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#12006]
### .NET version

main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this was changed after the PR https://github.com/dotnet/winforms/pull/11780

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of WinForms repo, BindingNavigator control via “Edit Items... “when adding an item, it shows that the "Cannot create an abstract class".

![image](https://github.com/user-attachments/assets/b387b032-4ba7-4f48-90bc-533902e738b6)

https://github.com/user-attachments/assets/d7d4d619-0c27-41e3-beae-c054db1c789e

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by merriemcgaw** [comment]
I don't think we really should expect this scenario to work in the designer sample application. @KlausLoeffelmann, would you agree?

**Comment by Tanya-Solyanik** [comment]
@merriemcgaw  - I agree.

**Comment by merriemcgaw** [comment]
Closing this issue as not-planned. This will be an acceptable difference in the test designer app.
