### ISSUE TITLE
ListView does not notify for ItemCheck nor ItemChecked, if StateImageList has 3 or more images

### ISSUE THREAD

**Issue by spiriapbergeron** [dotnet/winforms#12013]
### .NET version

Issue experienced in .NET7, but the code appears unchanged in 8,9,10.

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Probably not.

### Issue description

**THIS PORTION HAS BEEN REWRITTEN TO OFFER A BETTER DESCRIPTION AND SOLUTION THAN IN MY ORIGINAL SUBMISSION**

In a ListView, I wanted to add an Indeterminate state image to the checked state, so I created my own StateImageList with 3 images. 

To my surprise, while I see the images going from one to the other, even my 3rd image, the event handler for ItemCheck and ItemChecked did not fire when going to the Indeterminate state

With 2 images:
Unchecked -> Checked: handler called
Checked -> Unchecked: handler called
Unchecked -> Checked : handler called

With 3 images:
Unchecked (initial state): image 0 shown.
Unchecked -> Checked: image 1 shown, handler called.
**Checked -> Indeterminate : image 2 shown, handler NOT called.**
Indeterminate -> Unchecked: image 0 shown, handler called 

Same if I have more than 3 imags.  If I have 7 images in StateImageList. 
- I see all images cycling correctly (0-1-2-3-4-5-6-0)
- But handler called when going from image (0->1) and (6->0), nothing in between.

I have tracked the problem to ListView.cs, method **WmReflectNotify**, for the cases:

case PInvoke.LVN_ITEMCHANGING:
case PInvoke.LVN_ITEMCHANGED:

There's a comment that says: 

_"Because the state image mask is 1-based, a value of 1 means unchecked, anything else means checked.  We convert this to the more standard 0 or 1"_

But this is incorrect. At the very least, a value of 2 means indeterminate, which is a valid supported CheckedState value and should be supported. But it would be nice if the general case (more than 3 states) could be supported.  

**The solution below aims to do this cleanly without causing any breaking changes.**

_**HOW TO FIX THE PROBLEM**_

**Conceptual reasoning behind solution:** 

As I understand it, the standard Win32 ListView control does not support tri-state checkboxes directly, but can do so easily (even multicheckstate in fact) by passing an imagelist that contains the 3 (or more) states, eg: ImgUnchecked, ImgChecked, ImgIndeterminate0, ImgIndeterminate1, ... ImgIndeterminateN images, etc.

It's probably safe to assume that if a developer supplies a StateImageList and it contains only 2 images, he is simply wanting to override the look of the checked/unchecked look. Sure the images might be a user state (white, black) but still that's close enough to a true/false concept in pratice.

But if the StateImageList contains 3 or more images, then it's probably safe to assume that the state is a not a Checked/Unchecked state, but rather a custom "User-Defined" state.  Sure, we often see a "TriState" checkbox, like we sometimes see in a TreeView, (Unchecked, Checked, Square), but still, strictly speaking, that is not a True/False state, it means AllChildrenOff, AllChildrenOn, SomeChildrenOnOff, which in principle should be considered some kind of "User Defined" state.

So in the general case, it's probably safe to say that if the developer provides a StateImageList of 3 or more images, he means to work in a world where the states are user defined, regardless of the look of the images.

It would have been ideal if the EventArgs would have provided an int instead of a CheckedState enum, but for better or worse, we must keep this to avoid a breaking change. At least, the CheckedState has an Indeterminate state, which we can leverage. Therefore, we can find a way to fix this while not causing compile or breaking changes.

**SOLUTION DESCRIPTION:**

**Augment ItemCheckArgs with 2  new parameters:**
- int: CurrentUserValue, NewUserValue

**Augment ItemCheckedArgs with 1 new parameter:**
- int UserValue

Next, fix the implementation of ListView.OnItemCheck and ListView.OnItemChecked, so that: ...

**If StateImageList not set, or StateImageList.Count <= 2**

ItemCheck handler receives
  Current/NewValue = (Unchecked, Checked),   Current/NewUserValue = (0, 1)
  Current/NewValue = (Checked, Unchecked),   Current/NewUserValue = (1, 0)

**If StateImageList is set and StateImageList.Count >= 3**   

  Current/NewValue = (Unchecked, Checked),   Current/NewUserValue  = (0,1)
  Current/NewValue = (Checked, Indeterminate),   Current/NewUserValue = (1,2)
  Current/NewValue = (Indeterminate, Indeterminate),   Current/NewUserValue = (2,3)
  Current/NewValue = (Indeterminate, Indeterminate),   Current/NewUserValue = (3,4)
  Current/NewValue = (Indeterminate, Unchecked),   Current/NewUserValue = (4,0)

Now, we need to implement the counterpart to this, which is to support what happens when the developer overrides the NewValue and/or NewUserValue in the ItemCheckHandler.

Indeed if we do nothing there exists the possibility to create an inconsistency:

Currently, the developer does the following to override the new state when cicking on it. Let's say he wants to always have the checked state be off...

```
void MyListBox_ItemCheck(object? sender, ItemCheckEventArgs e)
{
     if (e.NewValue == CheckedState.Checked)
             e.NewValue = CheckedState.Unchecked;
}
```

If we stop at the above, the developer could cause an inconsistency if he modifies NewValue, like this:

```
void MyListBox_ItemCheck(object? sender, ItemCheckEventArgs e)
{
     // create an inconsistency:
     if (e.CurrentValue == CheckedState.Unchecked) && (e.NewValue == e.CheckedState.Checked)
             e.NewUserValue = 6;  // what does this mean now? do we override with NewValue or NewUserValue?
} 
```

I think the best solution here is to simply instruct ListView.OnItemCheck to use ItemCheckArgs.NewUserValue when  ItemCheckArgs.NewValue == CheckedState.Indeterminate.  I think this would fix all problems:

```
void MyListBox_ItemCheck(object? sender, ItemCheckEventArgs e)
{
     // enforce consistency:
     if (e.CurrentValue == CheckedState.Unchecked) && (e.NewValue == e.CheckedState.Checked)
     {
            e.NewValue = CheckedState.Indeterminate; // resolve inconsistency by telling caller of the handler to use NewUserValue upon return.
            e.NewUserValue = 6;  
     }
}
```

And because e.NewValue==Indeterminate  would simply mean to use the NewUserValue instad of NewValue, upon coming back from the hander, the developer could even do this without problem:

```
void MyListBox_ItemCheck(object? sender, ItemCheckEventArgs e)
{
     // enforce consistency:
     if (e.CurrentValue == CheckedState.Unchecked) && (e.NewValue == e.CheckedState.Checked)
     {
            e.NewValue = CheckedState.Indeterminate; // use e.NewUserValue instead of e.NewValue
            e.NewUserValue = 0;  // Go to "unchecked" state.
     }
}
```

Which brings us to the last behavior point, shown in the example below: if the developer forgets wants to set e.NewUserValue to 6 but forgets to set e.NewValue to Indeterminate, then e.NewValue will be used, NewUserValue will be ignored, and the state will go back to Checked, just like the old behavior.

```
void MyListBox_ItemCheck(object? sender, ItemCheckEventArgs e)
{
     if (e.CurrentValue == CheckedState.Unchecked) && (e.NewValue == e.CheckedState.Checked)
     {
            **//** e.NewValue = CheckedState.Indeterminate; // developer forgets to write this line, so the image goes "checked".
            e.NewUserValue = 6;  //  this line has no effect.
     }
}
```

With these proposed changes, I think there is a complete and full solution that introduces no breaking changes, only new members in the event args, and the old behavior is completely preserved, with the exception that if we specify an ImageList of more than 2 images, the handlers are called, which is the buggy behavior we wanted to fix in the first place.

**END UDPDATED DESCRIPTION AND SOLUTION**

### Steps to reproduce

See above in the issue description.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team verify if this ever worked? If this is a potential regression, even from Framework, then we will consider making a change here.

**Comment by Olina-Zhang** [comment]
@merriemcgaw  this is not a regression, verified .NET framework 3.5, 4.8.1 and .NET 9, all have same behaviors.

**Comment by JeremyKuhne** [comment]
@spiriapbergeron This is an API proposal. Can you please create a new issue using the API proposal template?

If we do this we'll need to make sure we do not break existing ListView users. The proposal should account for how one opts into the new behavior if any of the current APIs change behavior.

**Comment by spiriapbergeron** [comment]
> @spiriapbergeron This is an API proposal. Can you please create a new issue using the API proposal template?

Sure, if I can somehow find the template.... I may actually have some time to fix this myself now do you accept PRs from the community?  Not saying I will actually fix it, but I may. 

Also, I may fix it by implementing a ListView2.cs file and class, by copy-pasting the contents of ListView.cs, so you can still see the difference, and I'd let your team actually retrofit the fix into your own code. I'd just attach a ZIP file to this ticket. I know it's not the normal way to do things, but why not?

> If we do this we'll need to make sure we do not break existing ListView users. The proposal should account for how one opts into the new behavior if any of the current APIs change behavior.

Actually, I don't think that the existing behavior "changes" at all, except, of course, by firing the event that was always meant to be fired (eg: the actual bug fix).

As far as I'm aware, "opting out" is as easy as simply recompiling your old app and you'd be on your way.  I can't think of what might cause an app to break, but then again, I may not be creative enough to think about all the ways developers will pervert the usage of event handlers, or, what they did to work around this particular issue if they've ever encountered it. My guess? they'd write their own ListView2 class.

In any case, I am proposing essentially 2 easy things:  

(1) actually fire the event that was always meant to be fired to support the "indeterminate" CheckedState (like I said, fix the bug).

and 

(2) handle the general case of firing multiple events if you have more than 3 states as described in your ImageList.  For this, we need to add an int data member to the EventArgs class, but, If a developer has never had a use for this int data member before, he won't have a use for this int in the future.

**Comment by spiriapbergeron** [comment]
By the way are you considering this change for .net9, or 10?  It would be great if didn't have to wait years and years (.net10) for it to appear.

**Comment by JeremyKuhne** [comment]
> By the way are you considering this change for .net9, or 10? It would be great if didn't have to wait years and years (.net10) for it to appear.

This would be considered for .NET 10. .NET 9 dropped the first release candidate yesterday, it's effectively done.

Closing this in favor of the API proposal.
