### ISSUE TITLE
Cannot focus on the BindingNavigator control after clicking “Embed in ToolStripContainer” and then undo in DemoConsole application

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#12015]
### .NET version

main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this was changed after the PR https://github.com/dotnet/winforms/pull/11780

### Issue description

**Actual result in [[DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole))] test app:**
Cannot focus on the BindingNavigator control after clicking “Embed in ToolStripContainer” and then undo in DemoConsole application.

https://github.com/user-attachments/assets/a367492d-d114-4d7f-b6dd-d2f29271cca9

**Expected result:**
After clicking “Embed in ToolStripContainer” in the DemoConsole application and then undoing it, it should automatically focus on the BindingNavigator control.

https://github.com/user-attachments/assets/8f01f5ff-7743-4e21-9fd2-d0d2c660a4e5

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo.

**Comment by merriemcgaw** [comment]
I don't think we've implemented the full undo/redo feature in this sample application, and I think that would be going further than we need for the sample. Let's close this for now as it isn't impacting known end user scenarios.
