### ISSUE TITLE
[Regression] Form title bars are the wrong color (app with its own custom dark theming)

### ISSUE THREAD

**Issue by rickbrew** [dotnet/winforms#12014]
### .NET version

.NET 9.0.0-rc.1.24421.1 (downloaded at https://github.com/dotnet/sdk/blob/main/documentation/package-table.md)

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works fine in .NET 8. This only happens when I change the target framework to 9.

### Issue description

I compiled my app (Paint.NET) for .NET 9-rc1. From my understanding this is the first build with the experimental dark mode functionality. Paint.NET has its own extensive Dark Mode theming with lots of custom painting, setting the right DWM attributes, and even sending a few not-really-documented-but-not-really-undocumented window messages to coerce certain controls to run in Dark Mode. For now I will not be using any of that, I am simply working on getting Paint.NET to boot up correctly in .NET 9 so that I can ship my own beta to the public and get more testing and validation.

This is how PDN should look when booting it up. This is running on .NET 8:
![image](https://github.com/user-attachments/assets/9f249fa8-c9f9-4b9d-94be-2e01fc956c24)

If I make one change, which is to target .NET 9 with this .NET 9-rc1 build, it looks like this:
![image](https://github.com/user-attachments/assets/d3c510e9-efea-4309-957f-b6f72165f303)

Notice how the 4 floating window now have white title bars. This affects _all_ child dialogs. The main window is not affected because I'm doing some very intensive (aka crazy) custom non-client painting in there.

I tracked this down to code in `Control.SetVisibleCore()`. It is calling a `PrepareDarkMode` method which unconditionally calls `DwmSetWindowAttribute` to set the `DWMWA_USE_IMMERSIVE_DARK_MODE` attribute -- even if none of the experimental dark theme flags are enabled!

https://github.com/dotnet/winforms/blob/062b0fef1b471e068e061b31f3b92fd665fa8f09/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L10572 

I can _almost_ work around this by overriding `SetVisibleCore` in the derived class, like so:
```cs
    protected override void SetVisibleCore(bool value)
    {
        base.SetVisibleCore(value);

        // This is my method where I handle all sorts of theming stuff, including calling 
        // `DwmSetWindowAttribute` to set the DWMWA_USE_IMMERSIVE_DARK_MODE 
        // attribute to the appropriate value based on my app's configuration
        RefreshGlass(false); 
    }
```

However, this causes a different problem: when a Form is first shown, you can see the title bar start out as white and then animate towards the correct black color. This does not happen on .NET 8. This is clearly happening because the `DWMWA_USE_IMMERSIVE_DARK_MODE` attribute is being set twice:

https://github.com/user-attachments/assets/79e76e1c-6dfd-493f-b37c-ff3d111ab657

Paint.NET already manages this attribute, so I need WinForms to _not_ manage it at all. I haven't enabled the experimental Dark Theme stuff, so I would expect literally no effect on any of my own custom theming, much of which will -- at least for now -- overlap with the experimental .NET dark theme stuff.

cc @KlausLoeffelmann 

### Steps to reproduce

I can provide access to a Paint.NET build and/or repository for reproducing this, if necessary.

**Comment by rickbrew** [comment]
I'm not sure why this was tagged as `help-wanted` 🤔 This is @KlausLoeffelmann 's area, right? If he's on vacation or something then I can try to take a stab at it, but theming tends to be an area with a lot of delicate dependencies and I think Klaus would be able to figure it out a lot faster and a lot more safely than me.

**Comment by kirsan31** [comment]
@rickbrew may be confusion here is due to topic subject? I think we need something like "[**regression**] .... "

**Comment by rickbrew** [comment]
I guess my point is that this isn't something where I'm trying to use the new Dark Mode experimental features. If that were the case, I'd expect it to have some bugs that could be fixed later.

This is a situation where I'm explicitly _not_ using it, but it's still breaking my app in a way that prevents me from migrating to .NET 9.

**Comment by kirsan31** [comment]
@KlausLoeffelmann @JeremyKuhne @elachlan @merriemcgaw @Tanya-Solyanik 
Someone point this issue to the right (**regression**) direction pls🙏

**Comment by JeremyKuhne** [comment]
Sorry this got tagged incorrectly. Looking at it now.
