### ISSUE TITLE
[Tracking] Extremely long XML comments that need to be wrapped

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#12034]
There are XML comments that far exceed the recommended 120 characters on one line, they should be wrapped to multiple lines. This should probably be done after #12028 to avoid merge conflicts. There length should be agreed upon before work starts, 120 characters seems too long to me.  This is part of #11984.

**Comment by Tanya-Solyanik** [comment]
The team had agreed on 120 or less with some caveats - https://github.com/dotnet/winforms/blob/main/docs/coding-style.md#line-breaks

**Comment by paul1956** [comment]
@Tanya-Solyanik I will volunteer to do this since its only comments.
