### ISSUE TITLE
[Tracking] Decide what to do with Period 2 spaces in quoted strings and Resource Strings

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#12033]
Issue #11984 lists replacing a period followed by 2 spaces as an issue to be fixed but they are also used in quoted string and translated resource strings and changing them there could be breaking or at least will require translation work, so it is separate from PR #12028.

**Comment by Tanya-Solyanik** [comment]
75 hits in the resx files. Sample `<value>Unable to obtain a stream for the log.  Potential file names based on {0} are already in use.</value>`

**Comment by paul1956** [comment]
@Tanya-Solyanik I am afraid to change them without knowing how they might affect tests and customer code, plus how to get the new string translated. Same issue with quoted strings. If the team wants them changed, I have the time and interest in doing it.

If there is a different decision for quoted strings and resx files this issue should be split.

**Comment by Tanya-Solyanik** [comment]
@paul1956  - I was just trying to understand what kind of changes these are. As I see it, these strings are mostly exception messages, and thus user experience will not be drastically improved by such a change. Only 1 string is an actual UI text that could be changed. We'll triage it, but my vote is to won't fix this issue.

**Comment by paul1956** [comment]
@Tanya-Solyanik I think there are 73-75 in Resx files with period space space, that could be changed (I have no opinion because it's additional work and tests, and I don't know how to properly edit Resx files). There are still 34 in .cs files, a few somehow got missed, most are in Debug Asserts (missed intentionally) and the rest in inline comments in code and not Document Comments. I would fix the comments and as you advise move those comments onto previous line as its hard to even see them, I did that for VB already.
 I any case its 1 or more new PR's. Please advise.

**Comment by Tanya-Solyanik** [comment]
We will triage resx files. I personally don't see a benefit in changing the exception messages. 

Smaller PRs dedicated to a single REGEX run are the easiest to review.

That could be a single PR:
>There are also 223 places with multiple spaces between words.

And moving comments above the field declarations would be another dedicaed PR

**Comment by paul1956** [comment]
@Tanya-Solyanik REGEX fixing is very dangerous because Tests have many places with 2 spaces that should not be changed. REGEX is great for finding candidates. As PR is merged, I will tackle another cleanup issue.

1. Fix of 2 spaces between characters
2. Long lines
3. If necessary, move inline comments on property declarations to previous line

**Comment by merriemcgaw** [comment]
Triage consensus is that there's not enough benefit for the re-localization cost that we'd be incurring. Thanks @paul1956 for the issue - it spawned a great discussion!
