### ISSUE TITLE
More efficient access Control.Handle

### ISSUE THREAD

**Issue by CuteLeon** [dotnet/winforms#12084]
### Background and motivation

I have a complex application which has multiple forms and each form runs in a indenpendent STA thread due to heavy UI renderer job, this makes it has to call Invoke() to access other forms' handles. However, Control's Handle only needs to ensure thread safety during creation in reality, is it possible that we only check thread safety when the handle is not created, so that we can safety and efficiently get Control's Handle in other thread after Handle created.
I know Control.Handle is a very basic and widely used member, so I hope we can carefully discuss it.

### API Proposal

```csharp
    public IntPtr Handle
    {
        get
        {
            if (CheckForIllegalCrossThreadCalls && !t_inCrossThreadSafeCall && InvokeRequired)
            {
                throw new InvalidOperationException(string.Format(SR.IllegalCrossThreadCall, Name));
            }

            if (!IsHandleCreated)
            {
                CreateHandle();
            }

            return HandleInternal;
        }
    }
```
Changes to be:
``` csharp
    public IntPtr Handle
    {
        get
        {
            if (!IsHandleCreated)
            {
                if (CheckForIllegalCrossThreadCalls && !t_inCrossThreadSafeCall && InvokeRequired)
                {
                    throw new InvalidOperationException(string.Format(SR.IllegalCrossThreadCall, Name));
                }

                CreateHandle();
            }

            return HandleInternal;
        }
    }
```

### API Usage

```csharp
Task.Factory.StartNew(()=> _ = control.Handle);
```

### Risks

Handle is a very basic and widely used member;

### Will this feature affect UI controls?

no;
Allow to get control's created handle from another thread;
no;

**Comment by elachlan** [comment]
@CuteLeon can you do up a quick PR so we can see if it causes any test failures?

**Comment by elachlan** [comment]
@merriemcgaw is this behavior change a breaking change? It seems less restrictive whilst still keeping the safety.

**Comment by merriemcgaw** [comment]
I would definitely like @JeremyKuhne to weigh in on this.

**Comment by JeremyKuhne** [comment]
I'm not sure we can do this as it would break existing behavior. I believe the answer here is disable `CheckForIllegalCrossThreadCalls` before you make the call.

**Comment by CuteLeon** [comment]
1. A quick PR created: https://github.com/dotnet/winforms/pull/12094
2. Disable `CheckForIllegalCrossThreadCalls`
    1. `CheckForIllegalCrossThreadCalls` is also widely used in structure `MultithreadSafeCallScope`, 
    2. Simply disabling 'CheckForIllegalCrossThreadCalls' will result in Control executes CreateHandle() method duplicately during concurrent access Handle property before Handle creation, i am not sure if it may have a potential impact on InvokeRequired or GetWindowThreadProcessId.

**Comment by JeremyKuhne** [comment]
Changing the behavior of this check will completely change the functionality of this property so it isn't something we can do. (It will no longer complain when you're accessing properties across threads.)

We don't really support multithreaded access. I don't know that we can guard in a way that is dependable. You can check IsHandleCreated before you try to get the handle. You'll still be at the mercy of other threads recreating the handle, but there isn't a lot you can do there.

**Comment by CuteLeon** [comment]
Hi @JeremyKuhne, actually, what I desired is not to make Control supports creating Handle from other threads, but to support to read the value of Handle from other threads after Handled created.
My most used scenario is like: I have multiple forms and bound each's message loop to an indenpendent thread, I hope each form can read all other forms' Handles without calling Invoke(), and I can promise that I have safely created separate Handles in each form's independent thread before doing so.

**Comment by JeremyKuhne** [comment]
@CuteLeon I understand that you don't want to support creating handles from other threads. My point is that there isn't a practical way for us to make any handle access completely thread safe so we can't realistically add guards for reading from another thread. You can do something like the following, but it isn't going to work in all scenarios. If the control gets its handle recreated or freed on another thread there isn't much you can do.

Another (perhaps better) way to do this is just maintain the handle information in your own table by hooking `HandleCreated`.

``` C#
private static object s_crossThreadCheckLock = new();

static nint GetControlHandleFromAnyThread(Control control)
{
    if (!control.IsHandleCreated)
    {
        return 0;
    }

    lock (s_crossThreadCheckLock)
    {
        bool prior = Control.CheckForIllegalCrossThreadCalls;
        try
        {
            Control.CheckForIllegalCrossThreadCalls = false;
            return control.Handle;
        }
        finally
        {
            Control.CheckForIllegalCrossThreadCalls = prior;
        }
    }
}
```

**Comment by CuteLeon** [comment]
Oh I see, I saw a RecreateHandle() method which may recreate handle during running. Currently I am using a workaround like:
``` csharp
public class MyForm : Form
{
    public IntPtr FriendlyHandle { get; protected set; }
    
    protected override void OnHandleCreated(EventArgs e)
    {
        base.OnHandleCreated(e);
        this.FriendlyHandle = this.Handle;
    }

    protected override void OnHandleDestroyed(EventArgs e)
    {
        base.OnHandleDestroyed(e);
        this.FriendlyHandle = default;
    }
}
```

**Comment by JeremyKuhne** [comment]
@CuteLeon your workaround looks good. Closing this as I don't think we have any further action items.
