### ISSUE TITLE
Border of SplitButton of ToolStrip is not contrasting enough in High Contrast theme

### ISSUE THREAD

**Issue by Epica3055** [dotnet/winforms#12083]
### .NET version

10

### Did it work in .NET Framework?

Yes

![image](https://github.com/user-attachments/assets/65947dea-4bf2-44c9-b3d7-f5bf024db08d)

![image](https://github.com/user-attachments/assets/2b0da2ef-324c-4242-b39f-95ea55e2035f)

![image](https://github.com/user-attachments/assets/92766ef4-790c-43e4-8d56-60f75828f403)
![image](https://github.com/user-attachments/assets/25c85585-5679-437a-a57a-d3de8b9bdf3e)

**Comment by Nora-Zhou01** [comment]
Verified this issue in the latest .Net 9.0 RC2 SDK build: 9.0.100-rc.2.24468.2 + binaries built fromWinforms repo main branch, In Win11 application 3 modes: Classic/Dark/System, the SplitButton border of ToolStrip can be adjusted in high contrast theme, the results are as follows:
![HC Aquatic](https://github.com/user-attachments/assets/28bd9c4c-413e-4068-877d-8628a148e469)
![HC Desert](https://github.com/user-attachments/assets/f1327814-243d-44b4-bf68-39b025607bf2)
![HC Dusk](https://github.com/user-attachments/assets/e61b2c9e-891f-4669-b969-ca150e75e3de)
![HC Night sky](https://github.com/user-attachments/assets/5ffa7b84-0a2f-4d1d-acaf-007fd7ae5eec)
