### ISSUE TITLE
Memory leaks when using System.Windows.Forms

### ISSUE THREAD

**Issue by shashidhar-ks** [dotnet/winforms#12096]
### .NET version

.NET 8 (8.0.8)

### Did it work in .NET Framework?

Not tested/verified

### Issue description

Private bytes of the .NET 8 Windows Form application keeps increasing, when we open and close a Form.

The steps to reproduce section has details on how to reproduce it faster in a simpler way.

I used memprofiler to confirm that there are no leaks in the source code I have used. Memprofiler mentioned that there are increase in the types of object as mentioned in the below image.

![image](https://github.com/user-attachments/assets/8e4bdfe2-1dd0-481e-bb5b-8b18f1ea72c7)

Note: We are calling `GC.Collect()` and `GC.WaitForPendingFinalizer()` at regular interval and still the private bytes of the application keeps increasing.

### Steps to reproduce

[WinFormsApp1.zip](https://github.com/user-attachments/files/16942215/WinFormsApp1.zip)

- Build the csproj in the above attachment.
- Execute the output exe and click on the button.
- Using Task Manager, monitor Private Bytes of the application every 3 mins for around 30 mins.
- There will be a steady increase in the Private Bytes of the application

The application is doing the following:
- We have `Form2` that has checkbox, combobox and textbox controls (all from System.Windows.Forms namespace).
- `Form2` has hooked onto Load event in which it creates a Timer which is configured to call a function in one sec.
- Function which Timer calls first stops the Time, Disposes it and closes the Form.
- We have `Form1` that has a button.
- Clicking on the button does the following in an infinite loop
  - Creates instance of `Form2`, calls ShowDialog and disposes the instance when it is done.
  - Calls GC.Collect and GC.WaitForPendingFinalizer

So, clicking on the button will continuously creates and closes new Window Form.
By monitoring Private Bytes of the application, we can see that memory of the application keeps increasing.

**Comment by JeremyKuhne** [comment]
It looks like you have an accessibility tool running (as you're getting ControlAccessibleObjects). Trying this with both .NET 8 and 9 with and without Narrator running I didn't see anything particularly concerning.

.NET 9 RC1 will be out shortly and would be worth comparing. The accessibility interop code has been completely rewritten and may impact what you're observing.

**Comment by merriemcgaw** [comment]
We can't really move forward with this without more data. We aren't seeing this issue with the repro application. If we can get more information to proceed we'd be happy to take a look further, but there isn't enough information here to proceed further.
