### ISSUE TITLE
StringCollectionEditor unable to add - constructor on type System.String not found

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1210]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
  - .NET Core SDK (reflecting any global.json):
  - Version:   3.0.100-preview6-012264
  - Commit:    be3f0c1a03

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

![image](https://user-images.githubusercontent.com/4403806/59983255-c8b76600-9660-11e9-8b96-92d6f445359f.png)

**Expected behavior:**

A user is able to add/edit strings

**Minimal repro:**
1. Install latest VS & .NET Core 3.0 on loc machine, then open the attached app.
[WindowsFormsApp2.zip](https://github.com/dotnet/winforms/files/3239429/WindowsFormsApp2.zip)
2. Run it 
3. Open the `StringCollectionEditor` editor for the `Lines` property
4. Add new item

**Comment by hughbe** [comment]
I don't think we've ported `StringCollectionEditor` yet?

**Comment by weltkante** [comment]
Yes #1115 is updated with more missing editors
