### ISSUE TITLE
ClipboardTests has tests that don't run all data rows

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#12115]
### Test

- Clipboard_Contains_InvokeMultipleTimes_Success
- Clipboard_SetDataObject_NullData_ThrowsArgumentNullException
- Clipboard_NotSta_ThrowsThreadStateException

### Issue description

The type argument Func<bool> is not serializable, which will cause Test Explorer to not enumerate individual data rows. Consider using a type that is known to be serializable.

**Comment by Tanya-Solyanik** [comment]
We can have 4 fact tests instead of a single theory

**Comment by paul1956** [comment]
> We can have 4 fact tests instead of a single theory

@Tanya-Solyanik who is the comment addressed to? I didn’t write these I just see warnings in VS when I open the file. I believe there are multiple solutions and it’s possible to use a Theory test with Boolean parameters I have several, I assume these used to work, what changed and how many more tests are broken because if the same problem is why I opened this issue. It’s unfortunate that XUnit does not flag tests that never (fully) run I have run it similar issues a lot recently on another project.

**Comment by Tanya-Solyanik** [comment]
I don't see that warning, where is it reported?
```
 System.Windows.Forms.Tests.ClipboardTests.Clipboard_Contains_InvokeMultipleTimes_Success
   Source: ClipboardTests.cs line 60

Test has multiple result outcomes
   4 Passed

Results

    1)   System.Windows.Forms.Tests.ClipboardTests.Clipboard_Contains_InvokeMultipleTimes_Success(contains: Func`1 { Method = Boolean ContainsAudio(), Target = null }) 
      Duration: 66 ms

    2)   System.Windows.Forms.Tests.ClipboardTests.Clipboard_Contains_InvokeMultipleTimes_Success(contains: Func`1 { Method = Boolean ContainsFileDropList(), Target = null }) 
      Duration: 3 ms

    3)   System.Windows.Forms.Tests.ClipboardTests.Clipboard_Contains_InvokeMultipleTimes_Success(contains: Func`1 { Method = Boolean ContainsImage(), Target = null }) 
      Duration: 3 ms

    4)   System.Windows.Forms.Tests.ClipboardTests.Clipboard_Contains_InvokeMultipleTimes_Success(contains: Func`1 { Method = Boolean ContainsText(), Target = null }) 
      Duration: 3 ms

```

**Comment by paul1956** [comment]
> I don't see that warning, where is it reported?

@Tanya-Solyanik 

![image](https://github.com/user-attachments/assets/371e3ce6-5ff5-4b15-b01a-0056f44ead94)
See the little dots under Me in image and message
```
The type argument Func<bool> is not serializable, which will cause Test Explorer to not enumerate individual data rows. Consider using a type that is known to be serializable.
```

**Comment by Tanya-Solyanik** [comment]
I see, this is an informational message. Note that tests run as expected, only the tree view in the test explorer can't show the Funcs. We can keep these tests as Theories, but pass in method names instead of funcs and execute hem using TestAccessor.

**Comment by paul1956** [comment]
@Tanya-Solyanik not something I am comfortable taking on.

**Comment by Tanya-Solyanik** [comment]
We have this message in multiple cases of theory data. Adressing them will not improve readability of our tests. I'll close this item since itis only about presentation in the treeview, and all tests run as expected.
