### ISSUE TITLE
PingUri_ShortTimeout_Success fails 5% of the time of server

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#12140]
### Test

Microsoft.VisualBasic.Devices.Tests.Ping_ShortTimeout_Success()

### Issue description

5% of the time the test fails in the server.
The minimum timeout is 1 and sometimes the test completes before the timeout

A workaround would be to ping something other then the local machine but I would need an allowed URL.

**Comment by Tanya-Solyanik** [comment]
@paul1956  - do you have a stack trace?

**Comment by paul1956** [comment]
> @paul1956  - do you have a stack trace?

I am reviewing the test and with 1 (millisecond) as timeout it should not throw when pinging local server. But on test server 5% of the time it takes longer than 1 millisecond. If I use a different ping API I can see it throw every time, it fails on my local machine with a value under 900 microseconds. 
Normally the local ping is under 1 millisecond but on server 5% of the time it's longer.

The easy fix is to increase timeout to a bigger number. Testing the timeout is really the responsibility of system.Net.NetworkInformation.

I need to use the API with the Timeout to test VB code. I don't need to test the throw.

I will do another PR to lengthen the timeout and close the issue.

**Comment by paul1956** [comment]
@Tanya-Solyanik 
#12146 has a fix so the test always passes.

I will close when fix is merged.
