### ISSUE TITLE
Extra Border Color in DataGridView with RightToLeft.

### ISSUE THREAD

**Issue by Syareel-Sukeri** [dotnet/winforms#12187]
### .NET version

.NET 9.0.100-rc2.24468.2

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue. Not reproduce on .NET 8.0.

### Issue description

In .NET 9, when `RightToLeft = Yes`, an extra border color appears on the right side of the first column in the DataGridView. In .NET 8.0, this extra border does not appear, and the column displays correctly without the additional color.

**Current Behavior (.NET 9.0)**
![CoreDGV](https://github.com/user-attachments/assets/cdf3fb85-aeda-45f8-8717-77451fc10c65)

**Expected Behavior (.NET 8.0)**
![NET8DGV](https://github.com/user-attachments/assets/c6fc34ee-8c53-4b55-80e4-80e803ea2d9f)

### Steps to reproduce

1. Create a WinForms .NET Core project with a DataGridView control.
2. Set the `GridColor` property to a bright color for better visibility.
3. Set `RightToLeft` to `Yes`.
4. Observe the result 

### More Info

1. When setting `RightToLeft` to `No` in .NET 9, the issue does not reproduce.

![LTR](https://github.com/user-attachments/assets/5688be0c-a6bd-42b3-b7d4-c29436dc77d4)

**Comment by JeremyKuhne** [comment]
Regressed in #11345, which changed a number of lines the same way. We should validate all of the other changed code paths. We need to reopen the original issue to figure out the right way to fix it.

**Comment by Tanya-Solyanik** [comment]
Moved this bug to NET10 to have a fix for this and https://github.com/dotnet/winforms/issues/5961 done together.

**Comment by Syareel-Sukeri** [comment]
Verified this issue on .NET SDK 9.0.100-rtm.24501.2 + private dlls build from WinForms release/9.0 repo, the issue has been fixed: no extra border color appears on the right side of the first column in the DataGridView.
![Screenshot 2024-10-02 082831](https://github.com/user-attachments/assets/5bb8799a-766c-409e-a36f-9205971f9795)

**Comment by Syareel-Sukeri** [comment]
Verified this issue on .NET SDK 10.0.100-alpha.1.2459.21 + private dlls build from latest WinForms main repo, the issue has been fixed: no extra border color appears on the right side of the first column in the DataGridView
![Image](https://github.com/user-attachments/assets/1e83acaa-31a4-4ce9-9a4f-821a5bb56eaf)

**Comment by Liv-Goh** [comment]
Verified this issue with .NET 9.0 GA test pass .NET SDK 9.0.100 build, the issue has been fixed: no extra border color appears on the right side of the first column in the DataGridView
![Image](https://github.com/user-attachments/assets/7a668022-9f18-4619-a248-a0842107664a)
