### ISSUE TITLE
DataObject contains wrong data for file drop under .Net 9 RC1

### ISSUE THREAD

**Issue by IrinaPykhova** [dotnet/winforms#12190]
### .NET version

.Net 9 RC1

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

it worked correctly in .Net 8, here is what I expect to see:
![image](https://github.com/user-attachments/assets/4c84b508-6646-4e47-9b4d-39a45a175310)

### Issue description

at file drop action DataObject.GetDataPresent method returns wrong value, so, we can't rely on it any more. Here is what I see in debugger:
![image](https://github.com/user-attachments/assets/ab35e9d2-1f6c-456a-bbbe-b5802eae6cca)
You see, it shows single data format Shell IdList Array, but at the same time GetDataPresent return true for any existent or not existent formats I ask

### Steps to reproduce

Create Windows Forms application, set Form AllowDrop property to true and add handler for Form.DragOver event, something like this:

```
private void Form1_DragOver(object sender, DragEventArgs e)
{
    if (e.Data.GetDataPresent(typeof(C1.Schedule.Appointment)))
    {
        C1.Schedule.Appointment app;
        app = (C1.Schedule.Appointment)e.Data.GetData(typeof(C1.Schedule.Appointment));
        app.Subject = "my test dragged appointment";
    }
}
```
You can check for any types which are present in your application instead of Appointment type in this snippet.
Run application, select any file in FileExplorer and drag it over the form. You can set breakpoint in debugger and play with VS Watch window to explore DataObject content. Under .Net 9 you can't see any more that it was a file and you get all wrong information about presented Data.

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .NET 9.0 SDK build: 9.0.100-rc.2.24475.2 + dlls built from Winforms repo **main** branch, it was fixed as following:
![image](https://github.com/user-attachments/assets/ab3f1a90-c68f-4dca-8962-a601c2df278a)

**Comment by Philip-Wang01** [comment]
Verified this issue in the latest .NET 9.0 SDK build: 9.0.100-rc.2.24475.3, it was fixed as following:
![image](https://github.com/user-attachments/assets/a9c51b9d-62ae-43b6-9db8-96941376aeda)

**Comment by Zheng-Li01** [comment]
Verified this issue with .NET 9.0 GA test pass .NET SDK 9.0.100 build, the issue has been fixed as below screenshot.
![Image](https://github.com/user-attachments/assets/1c6f5663-8d70-4d02-95b5-813c93b461cb)
