### ISSUE TITLE
Please add "blank template" as an option for this repo

### ISSUE THREAD

**Issue by richlander** [dotnet/winforms#12218]
Filling out these forms is a pain.

**Comment by RussKie** [comment]
If you remove "choose" from the url, you'll get the blank template
https://github.com/dotnet/winforms/issues/new~/choose~

**Comment by richlander** [comment]
It would be great if you could just enable the blank template like other repos.

**Comment by RussKie** [comment]
It's up to the team.


> It would be great if you could just enable the blank template like other repos.

FWIW, https://github.com/dotnet/aspire/issues/new/choose, https://github.com/dotnet/aspnetcore/issues/new/choose, https://github.com/dotnet/wpf/issues/new/choose, https://github.com/dotnet/maui/issues/new/choose don't have a blank issue template...

**Comment by Zheng-Li01** [comment]
The blank template has been added for this repo as below screenshot.
![Image](https://github.com/user-attachments/assets/b47b9957-d82c-44c2-8f37-b43e2c86323c)
