### ISSUE TITLE
Failing unit test: ListControl Ctor_Default

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/winforms#1222]
See https://dev.azure.com/dnceng/internal/_build/results?buildId=235831&view=ms.vss-test-web.build-test-results-tab&runId=5849926&resultId=100147&paneView=debug

**Comment by hughbe** [comment]
I can’t acess this log can you share?

**Comment by RussKie** [comment]
```
Error message
Assert.Same() Failure\r\nExpected: [Font: Name=Segoe UI, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False]\r\nActual: [Font: Name=Segoe UI, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False]

Stack trace
at System.Windows.Forms.Tests.ListControlTess.Ctor_Default() in <path>\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ListControlTests.cs:line 40
```

**Comment by AdamYoblick** [comment]
Looks like the fonts have the same data but are probably not the same reference. So we either need to compare the font properties one by one or override Font.Equals and change to Assert.Equal.

Not sure I’d override font.equals is an option because of logic implications in the real code, so comparing font properties is probably the safest.

________________________________

**Comment by weltkante** [comment]
> Not sure I’d override font.equals is an option because of logic implications in the real code

`Font` already [overrides](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Advanced/Font.cs,447b844c726afc0f) `Equals` for value equality

**Comment by AdamYoblick** [comment]
Well then changing to Assert.Equal sounds like the appropriate fix here. Thanks @weltkante :)

**Comment by RussKie** [comment]
FWIW, here's an explanation of the cause - https://github.com/xunit/visualstudio.xunit/issues/142

**Comment by hughbe** [comment]
I can repro this occasionally especially in VS. https://github.com/dotnet/winforms/pull/1925 contains a fix

**Comment by RussKie** [comment]
Thank you
