### ISSUE TITLE
Add retry mechanism for clipboard tests

### ISSUE THREAD

**Issue by LeafShi1** [dotnet/winforms#12229]
Refer to PR #12087

In order to confirm that clipboard operation can be executing more stable, we consider add retry mechanism for clipboard tests

**Comment by JeremyKuhne** [comment]
The right way to handle this is to make sure they are all in the same test collection fixture. Sleeping before testing won't help. This is a place we need a retry mechanism.

**Comment by JeremyKuhne** [comment]
`[UISettings(MaxAttempts = )]` should let you do retries. It was added to Xunit.StaFact last year, need [v1.2.46-alpha](https://github.com/AArnott/Xunit.StaFact/releases/tag/v1.2.46-alpha), which we're already consuming.

**Comment by paul1956** [comment]
@JeremyKuhne is there a recommend value to MaxAttempts for clipboard tests. All clipboard test are in at least 4 different classes but all Sequential tests are in the one Collection(“Sequential”), this includes unrelated tests for WebBrowser.

**Comment by JeremyKuhne** [comment]
3 is probably reasonable to start, but we can go higher in this particular case (OLE).

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - could you please verify if all clipboard tests, even from other test assemblies, are using the same mechanism.
