### ISSUE TITLE
Different Resource Names between NetFramework48 and Net8

### ISSUE THREAD

**Issue by CortiWins** [dotnet/winforms#12267]
### .NET version

Net8.0-windows, Net Framework 4.8

### Did it work in .NET Framework?

Yes

### Issue description

While upgrading an application to multitarget of both Net8 and classic Net48, i encountered an issue.
The icon on a form, (_saved as a ressource in the forms resx_)  did load correctly on Net8 but caused an exception on net48.

```
Form.InitializeComponent()
...->
Icon = (Icon)resources.GetObject("$this.Icon");      
...->   
System.Resources.MissingManifestResourceException
```

### Steps to reproduce

I tried to recreate the issue in an example problem but it did not happen, so i used ILSpy to check the ressources in the assembly of the application and noticed that they do have different names between the net48 assembly and the net8 assembly, and the difference is the namespace.

This allowed me to recreate the error in the example application.( see attachment )
[MultitargetRessourceProblem.zip](https://github.com/user-attachments/files/17248539/MultitargetRessourceProblem.zip)

In ILSpy it looks like this.  As you can see, Net8 includes the Namespace into the resource name, while net4 does not.
![grafik](https://github.com/user-attachments/assets/f1215fe1-15ac-46c8-a136-21893abb296a)

With a namespace matching the path in the project, both net48 and net8 can load the resource.

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - could your team please investigate a workaround, I guess we can define resources in the project file explicitly instead of relying on the designer generated code.

**Comment by Epica3055** [comment]
We offer you two options

### 1. 
Remove namespace (.FormsTest) in Form1.cs and Form1.designer.cs
### 2.

Add icon to the project.
![Image](https://github.com/user-attachments/assets/c337ff4d-0df1-4695-8756-c028ae47fe53)
Change the code
![Image](https://github.com/user-attachments/assets/26ed4c99-53a8-423d-a222-ecd0ff52ee60)

**Comment by CortiWins** [comment]
During the last days i created a workaround for us that solves it for us for now. Doing that made me realize that my previous description of net8 including the namespace is not 100% specific.

net8 uses the namespace/formtypename
net 48 uses projectname/foldername/formfilename
![Image](https://github.com/user-attachments/assets/7b084378-b986-4477-aea6-c4afcdd9da3f)

which leads us to two workarounds
1) making projectname, foldername and filename match exactly to namespace and typename.
2) set the form icon in code. from project ressources, from embeddedData or something else.

So as mentioned i made a workaround that works for us.
So this is not a cry for help but just a plain old bug report, with a fancy image so not even that plain.

Have a nice day everyone!

**Comment by LeafShi1** [comment]
This issue doesn't reproduce in Separate NetFramework48 project or Separate Net8 project, it only occurs when set multi target frameworks in a project `<TargetFrameworks>net8.0-windows;net48</TargetFrameworks>`

FYI @Tanya-Solyanik

**Comment by Tanya-Solyanik** [comment]
@merriemcgaw  - multitargeting an important scenario to enable migration to .NET, should we move this issue to the designer repo and investigate further?

**Comment by CortiWins** [comment]
> This issue doesn't reproduce in separate NetFramework48 project or separate Net8 project, it only occurs when set multi target frameworks in a project `<TargetFrameworks>net8.0-windows;net48</TargetFrameworks>`

From my tests, it is not the multitargeting. If i set the project that has the problem in multitarget to  `<TargetFramework>net48</TargetFramework> ` instead of multitarget, the probem still exists.

A new NetFramework48 project still uses the old project file format, while the problem happens in projects with a net SDK project file.

**Comment by Tanya-Solyanik** [comment]
@CortiWins  - what happens when you change the .NET Framework project format to SDK style?

**Comment by CortiWins** [comment]
> [@CortiWins](https://github.com/CortiWins) - what happens when you change the .NET Framework project format to SDK style?

Net SDK style created with 8.0, TargetFramework changed to 4.8  -> error
Net Framework 4.8 Updated via the Update Wizard to 8.0, TargetFramework changed to 4.8 -> error

**Comment by merriemcgaw** [comment]
I'll leave this issue out here for the ongoing discussion, but I agree that multitargeting is getting to be a more and more important scenario. Let's talk in the team meeting about what we want to devote to this area.

**Comment by JeremyKuhne** [comment]
@Olina-Zhang can you open a designer issue for us to track making this less of a hassle in the future?

**Comment by Zheng-Li01** [comment]
Create a [designer issue](https://github.com/microsoft/winforms-designer/issues/6133) to track this, and closed this issue.
