### ISSUE TITLE
 `ImageListDesigner.OriginalImageCollection.Remove()` and `IndexOf()` methods do not handle `ImageListImage` correctly

### ISSUE THREAD

**Issue by ricardobossan** [dotnet/winforms#12291]
### .NET version

9.0.100-rc.1.24452.12

### Did it work in .NET Framework?

Not tested/verified

#### Description

The `Remove(Image value)` and `IndexOf(Image value)` methods in the `ImageListDesigner.OriginalImageCollection` class currently operate incorrectly when interacting with `ImageListImage`. These methods are intended to work with `ImageListImage` objects but only handle the base `Image` class, causing unintended behavior when removing or searching for items in the collection.

#### Expected Behavior

- `Remove()` should remove an `ImageListImage` from the collection if it exists.
- `IndexOf()` should return the correct index of an `ImageListImage` in the collection.

#### Actual Behavior

- `Remove()` does not correctly remove the `ImageListImage` object from the collection, because it only checks for the base `Image` type.
- `IndexOf()` returns `-1` or an incorrect index, because it also checks for the base `Image` type, not `ImageListImage`.

#### Affected Code

```cs 
public int IndexOf(Image? value) => value is Image image ? _items.IndexOf(image) : -1;

public void Remove(Image value)
{
	AssertInvariant();
	_items.Remove(value);
	RecreateHandle();
}
```

Both methods are currently checking for `Image` rather than `ImageListImage`, which leads to issues when working with the collection.

![Captura de tela 2024-10-08 191425](https://github.com/user-attachments/assets/0cfda938-f12d-4db6-b32d-fe065cfe3b93)

#### Suggested Fix

Modify the `Remove()` and `IndexOf()` methods to handle `ImageListImage` objects explicitly.

- For the IndexOf() method:

```cs 
public int IndexOf(ImageListImage? value) => value is ImageListImage imageListImage ? _items.IndexOf(imageListImage) : -1;

int IList.IndexOf(object? value) => value is ImageListImage image ? IndexOf(image) : -1;
```

- For the Remove() method:

```cs 

public void Remove(ImageListImage value)
{
	AssertInvariant();
	_items.Remove(value);
	RecreateHandle();
}

void IList.Remove(object? value)
{
	if (value is ImageListImage image)
	{
			Remove(image);
	}
}
```

### Steps to reproduce

1. Create an instance of `ImageListDesigner.OriginalImageCollection`.
2. Add `ImageListImage` objects to the collection using the `Add` method.
3. Attempt to remove or find an item using the `Remove()` or `IndexOf()` method, passing an `ImageListImage`.

**Comment by Tanya-Solyanik** [comment]
Comparing to the InProc designer, it seems that these methods had never worked. [ImageListDesigner](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsip/Designer/WinForms/System/WinForms/Design/ImageListDesigner.cs). Since they are internal, we can change the signature to match that of the Add and Contains methods.

**Comment by ricardobossan** [comment]
> Comparing to the InProc designer, it seems that these methods had never worked. [ImageListDesigner](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsip/Designer/WinForms/System/WinForms/Design/ImageListDesigner.cs). Since they are internal, we can change the signature to match that of the Add and Contains methods.

@Tanya-Solyanik Addressed in PRs:

  - Runtime: #12282 
  - InProc: [584354](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/584354)
