### ISSUE TITLE
An error dialog pops up if adding new item to project when form designer is "waiting for IntelliSense to finish initializing"

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#12294]
### .NET version

.NET 10 SDK build: 10.0.100-alpha.1.24508.48

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, just repro after installed .NET 10 SDK build to create a .NET 9.0 app

### Issue description

After installed .NET 10 SDK build from [main branch](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md), an error dialog pops up if adding new item: user control/form to project when form designer shows "waiting for IntelliSense to finish initializing". If close this error dialog, the item is added successfully, and build app without any error.
![Image](https://github.com/user-attachments/assets/7b717acf-1536-48ba-8de0-8c11cb194948)

https://github.com/user-attachments/assets/363d3af9-7d7f-4123-9608-4dfe41a2c4cd

If form designer is fully loaded, then to add new item, this issue cannot repro.
If uninstall .NET 10 SDK, this issue doesn't repro.

### Steps to reproduce
0. Install .NET 10 SDK
1. Create a Winforms app with targeting .NET 9.0 in a new instance
2. When form designer shows "waiting for intellisense to finish initializing", Ctrl+Shift+A to add a new item: usercontrol/form quickly

**Comment by Olina-Zhang** [comment]
Not repro in the latest .NET 10.0 SDK build: 10.0.100-alpha.1.24553.6.

**Comment by merriemcgaw** [comment]
.NET 10 SDKs may not have been complete at the time of the first testing. Since it's not reproing we'll go ahead and close it.
