### ISSUE TITLE
Guaranteed InvalidCastException in WebBrowserSiteBase.StartEvents()

### ISSUE THREAD

**Issue by Alefaid** [dotnet/winforms#12330]
### .NET version

.NET 8

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Worked on .NET 6. 

### Issue description

There is currently a bug in WebBrowserSiteBase in the following code:

[_connectionPoint = new AxHost.ConnectionPointCookie(nativeObject, this, **typeof(IPropertyNotifySink));**](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/Controls/WebBrowser/WebBrowserSiteBase.cs#L384C16-L384C118)

typeof(IPropertyNotifySink)) is passed to a ctor of ConnectionPointCookie along with a 'this' pointer.

Inside said constructor you will find this code which throws an exception:
```
 if (sink is null || !eventInterface.IsInstanceOfType(sink))
            {
                if (throwException)
                {
                    throw new InvalidCastException(string.Format(SR.AXNoSinkImplementation, eventInterface.Name));
```

and 'sink' (which is WebBrowserSiteBase in this case) does not implement IPropertyNotifySink. What it does implement now is this:
`IPropertyNotifySink.Interface,`

This appears to be the breaking commit: [
Move most of OLE code to CsWin32](https://github.com/dotnet/winforms/commit/94df74558df86435dccc2d3c302422ca6759eb65#diff-2824a61e214ad0a01e5a097311b262eb5bcbc9466f45ecddd49fefaa110281bc)

So it seems that the interface was moved, the typeof() code compiled just fine and no issues were met in runtime because `ConnectionPointCookie` construction code inside of StartEvents() is wrapped in a try..catch block.

There might be other instances of similar issues since a lot of related code has been moved in several commits.

### Steps to reproduce

This issue can be reproduced in any windows application that uses WinForms WebBrowser control and subscribes to FirstChanceException to observe the exception.

I'm attaching the source code of a sample that can be compiled and ran to see the exception and a stack trace.
[WebBrowserSiteExceptionSample.zip](https://github.com/user-attachments/files/17380174/WebBrowserSiteExceptionSample.zip)

**Comment by JeremyKuhne** [comment]
@Alefaid thanks for the detailed issue. :)

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .NET 10 SDK build: 10.0.100-alpha.1.24510.13 + binaries built from Winforms main branch, it was fixed now, no exception when running provided application.

Before the fix:
![Image](https://github.com/user-attachments/assets/9ea97c16-1aaa-4f9c-b546-79c421f2ef24)

After the fix, now:
![Image](https://github.com/user-attachments/assets/98d3831b-505a-4a28-9b46-3be15b233efd)

**Comment by lonitra** [comment]
Fix will be available in 8.0.11 release.

**Comment by Philip-Wang01** [comment]
Verified this issue in the 9.0.100 SDK build + release/9.0 private dll, it was fixed now, no exception when running provided application.

**Comment by Liv-Goh** [comment]
Verified this issue in the 8.0.11 sdk + release/8.0 private dll, it was fixed now, no exception when running provided application.

**Comment by Syareel-Sukeri** [comment]
Verified this issue with .NET 9.0 GA test pass .NET SDK 9.0.100 build, the issue has been fixed where no exception pops up when running provided application.

**Comment by MelonWang1** [comment]
Verified with .NET SDK 8.0.11 test pass build, this issue was fixed. No exception when running provided application.
