### ISSUE TITLE
In Visual Studio 2019 16.1.4,Winform designer can net be used

### ISSUE THREAD

**Issue by lichen19951127** [dotnet/winforms#1233]
* .NET Core Version:3.0 Preview6
* Have you experienced this same bug with .NET Framework?: No

**Problem description:In Visual Studio 2019 16.1.4,Winform designer can net be used
   I created a winform app
![image](https://user-images.githubusercontent.com/43132899/60159807-95263880-9826-11e9-9c91-79fb4f94f3c5.png)

**Actual behavior:
![image](https://user-images.githubusercontent.com/43132899/60159895-c0a92300-9826-11e9-9fa7-2a563cd47acc.png)

**Expected behavior:**

**Minimal repro:**

**Comment by lichen19951127** [comment]
I created the default app and didn't make any changes

**Comment by RussKie** [comment]
The designer is not currently available.
A designer will be available in 3.0 final.

**Comment by lichen19951127** [comment]
Ok, thank you, I am looking forward to it.

**Comment by RussKie** [comment]
Please refer to https://github.com/dotnet/winforms/blob/master/README.md for a workaround invoking the Classic Framework Designer.

**Comment by RussKie** [comment]
Please refer to https://github.com/dotnet/winforms/blob/master/README.md for a workaround invoking the Classic Framework Designer.
There's also another workaround via `TargetFrameworks` property - please refer to https://github.com/dotnet/winforms/pull/845

**Comment by lichen19951127** [comment]
![image](https://user-images.githubusercontent.com/43132899/60161222-a6bd0f80-9829-11e9-96ba-90942f665a55.png)

<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net472;netcoreapp3.0</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
    
    <Compile Update="Form1.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>
</Project>

**Comment by lichen19951127** [comment]
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net472;netcoreapp3.0</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
    
    <Compile Update="Form1.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>
</Project>

**Comment by lichen19951127** [comment]
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net472;netcoreapp3.0</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" _/>_
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Deployment" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net472' ">
    
    <Compile Update="Form1.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>
</Project>
