### ISSUE TITLE
Accessibility:[Keyboard] The narrator can’t focus on correct item of CheckedBoxList control

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#1235]
* .NET Core Version: 3.0.100 Preview7 12618 from master branch
* Have you experienced this same bug with .NET Framework?: Yes. the bug [918826](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/918826) still can reproduce in framework.

**Repro Steps:**
1.	Open the attached application, build and run.[ReproApplication.zip](https://github.com/dotnet/winforms/files/3329450/ReproApplication.zip)
2.	Open the narrator, and noticed that the scan mode is **scan on**.
3.	Using the down arrow to iterate the items of checkedlistbox control.

**More info:**
1.	The issue can’t repro on when setting the scan mode is **scan off**.
2.	The issue can’t reproduce on the listbox control.

**Actual:**
The dot line still stay on the first item, and the narrator can’t focus on correct item of CheckedBoxList control
![Issue](https://user-images.githubusercontent.com/38325459/60170996-3a97d700-983c-11e9-831c-2d6ecb81f4cf.PNG)

**Expected:**
The narrator should focus on correct item of CheckedBoxList control

**Comment by merriemcgaw** [comment]
@Zheng-Li01 can you verify and close this issue now that it's merged into master? #1027 @vladimir-krestov was that the right PR?

**Comment by vladimir-krestov** [comment]
@merriemcgaw No, this is a separate issue and it is not resolved in #1027.
It began to appear after fixing #1136.
Prior to that, it worked like this in the master branch:
![image](https://user-images.githubusercontent.com/49272759/60318708-b8fb9280-997c-11e9-8e57-c5439eb62e2b.png)
It doesn't reproduce in new version Windows, but reproduces in old versions.
This issue must be solved in other PR.

**Comment by merriemcgaw** [comment]
@vladimir-krestov thanks for the explanation. Do we know which version of Windows it began to break on? If this also repros on classic Framework we should file a Windows issue.

**Comment by vladimir-krestov** [comment]
@merriemcgaw I can't say which version of Windows it began to break on. But this issue reproduces in 10.0.17763.557 Windows version and doesn't reproduce in 10.0.18362.175 Windows version.

(.Net 4.8 old Windows version)
![image](https://user-images.githubusercontent.com/49272759/60805810-ebca3580-a189-11e9-9444-6f6bdda16f06.png)

I checked this issue in .Net 4.8 and it too reproduces in old Windows version but doesn't reproduce in new Windows version.

**Comment by merriemcgaw** [comment]
If it is fixed in the latest Windows builds I don't think we can or should do anything. I'm going to go ahead and close this in that case.
