### ISSUE TITLE
[HDPI] The "document" text in the “Generating Previews” dialog is truncated at >200% DPI

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#12358]
### .NET version

.NET SDK 10.0.100-alpha.1.24510.13

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

This is a regression issue. It reproduces on .NET 9.0.200-preview.0.24520.3 and does not reproduce on .NET 8.0.

### Issue description

The "document" text in the “Generating Previews” dialog is truncated at >200% DPI.

![Image](https://github.com/user-attachments/assets/8e7db4a6-990e-4129-bb1b-eb982bd1c389)

### Steps to reproduce

1. Launch VS instance on the greater than 200% primary screen.
2. Open the [Accessibility_Core_App.zip](https://github.com/user-attachments/files/17455998/Accessibility_Core_App.zip). (Or create an application that has a "Generating Previews" dialog) 
3.  TAB to "Printing_Controls: Testing the controls under Printing Tab" and hit ENTER key.
4. "Generating Previews" popup will appear.
5. Observe the "document" text in the “Generating Previews” dialog.

**Comment by lonitra** [comment]
@LeafShi1 could your team try bisecting to find which commit regressed this?

**Comment by LeafShi1** [comment]
> [@LeafShi1](https://github.com/LeafShi1) could your team try bisecting to find which commit regressed this?

This issue caused by the PR [11523](https://github.com/dotnet/winforms/pull/11523)

**Comment by Tanya-Solyanik** [comment]
This is an internal find, we will service it if we get customer reports about it.,

**Comment by Nora-Zhou01** [comment]
Verified this issue in the latest .NET 10.0 SDK build: 10.0.100-alpha.1.24623.6 + binaries built from the main branch of Winforms repo, it was fixed: "Document" text in the Generate Preview dialog now displays properly at >200% DPI.
![Image](https://github.com/user-attachments/assets/1819fbfa-f0c6-451d-a6f7-f86b3dda476f)
![Image](https://github.com/user-attachments/assets/e6354d9a-ce03-4557-833d-e26d17d332ad)
![Image](https://github.com/user-attachments/assets/2e3cb84a-9381-4715-b4b4-8a2bafe3c485)
![Image](https://github.com/user-attachments/assets/02a69d5e-d8b7-4996-9666-b51ac21e80c7)
