### ISSUE TITLE
[Accessibility] The text "Document does not contain any pages" in printPreviewControl has low color contrast

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#12365]
### .NET version

.NET SDK 10.0.100-alpha.1.24510.13

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, also repro in previous versions

### Issue description

The text "Document does not contain any pages" in printPreviewControl has low color contrast:
 ![Image](https://github.com/user-attachments/assets/4bfcba8b-40ae-416c-89d0-b8a1d283269b)

### Steps to reproduce

Repro steps:
1. Create a Winforms .NET application
2. Add printPreviewControl from toolBox to form designer or call printPreviewDialog to showDialog
3. Build and run
4. Use AccessibilityInsight tool to detect the text's color contrast in printPreviewControl

**Comment by Tanya-Solyanik** [comment]
We will consider servicing this to NET9 if we get customer requests.

**Comment by Nora-Zhou01** [comment]
Verified this issue in the latest .NET 10.0 SDK build: 10.0.100 - alpha.1.24556.12, it was fixed as following:
![Image](https://github.com/user-attachments/assets/be364d05-9225-47ca-99f0-a9f157b9197d)

**Comment by chaowendy** [comment]
Verified the issue on latest .NET SDK 9.0.200-preview.0.24575.35 + private dlls built from dotnet/winforms release/9.0 branch, the issue has been fixed. Test result is same as above.

**Comment by Olina-Zhang** [comment]
Verified it in the 9.0.1 servicing test pass, this issue was fixed with the same results as above.
