### ISSUE TITLE
There have the different behaviors for DGV cell's icon position between RightToLeft=Yes and RightToLeft=No modes when switching DataGridViewHeaderBorderStyle from Single to Raised/Sunken

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#12367]
### .NET version

.NET SDK 10.0.100-alpha.1.24510.13

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, also repro in previous versions

### Issue description

There have the different behaviors for DGV cell's icon position between RightToLeft=Yes and RightToLeft=No modes when switching DataGridViewHeaderBorderStyle from Single to Raised/Sunken.
![Image](https://github.com/user-attachments/assets/e467f4b2-f21e-4e0f-bd09-167b8200c306)
![Image](https://github.com/user-attachments/assets/8a1c7c80-cf0e-4e7f-ba6b-e685b41e0e83)

### Steps to reproduce

1. Open attached reproduce application.
2. Build and run the application.
3. Add some value for DataGridView controls.
4. Change the DataGridViewHeaderBorderStyle from Single to Raised/Sunken.
5. Observer the DGV cell's icon position between RightToLeft=Yes and RightToLeft=No modes.
[ReproApplication.zip](https://github.com/user-attachments/files/17472478/ReproApplication.zip)

**Comment by JeremyKuhne** [comment]
This would require a fair amount of work to do in a compatible way. Without strong customer feedback, we're unlikely to find resources to address this.
