### ISSUE TITLE
Do we need attributes of the style '[OptionalField(VersionAdded = 2)]' ???

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#1237]
What were these ever for? Serialization across versions?

**Comment by weltkante** [comment]
> Specifies that a field can be missing from a serialization stream so that the BinaryFormatter and the SoapFormatter does not throw an exception.

[yes](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.optionalfieldattribute?view=netframework-4.8) they belong to `[Serializable]`/`ISerializable` style serialization (BinaryFormatter/SoapFormatter).

If you remove serialization on the type you can remove those as well. If you keep serialization keeping it depends on which Desktop Framework version you want to be compatible against.

**Comment by RussKie** [comment]
Serialisation requirements were reviewed in https://github.com/dotnet/winforms/pull/1425
