### ISSUE TITLE
The toolbox does not display the bitmap of the tool control installed by a nuget package.

### ISSUE THREAD

**Issue by Perpete** [dotnet/winforms#12403]
### .NET version

.Net 8

### Did it work in .NET Framework?

No

### Issue description

The value of the ToolboxBitmap attribute is not taken into account after installing a nuget package of controls in the toolbox.
This is a problem reported in different forums for a long time without ever finding a solution.
There was no problem when you could choose the dll of the custom control to incorporate into the toolbox.

My current version of visual studio is 17.11.5 with .net 8.
I work in VB.net.

![Image](https://github.com/user-attachments/assets/a616fc94-f7cc-49a9-b94c-8d8ec502cee3)

### Steps to reproduce

Create a user control with an image in the resources and add the ToolboxBitmap attribute as shown in the image.
Create the nuget package with user control.
Install this nuget package in a new solution.
Check the toolbox.

**Comment by Epica3055** [comment]
[MyControlLib.zip](https://github.com/user-attachments/files/17583286/MyControlLib.zip)

You can try this project to see if it works for you. It worked on my machine.

![Image](https://github.com/user-attachments/assets/1938bb06-d49c-411d-b3be-1d0ebd295555)

After you update the nuget package, you can try to restart you vs, I think there may be some cache or something preventing loading  icon, which I encountered.

**Comment by Perpete** [comment]
Hi

Your project also works for me.

I tried to create the same project in vb.
I did not succeed because I did not find the project creation template that you used.

Here is what I did to simulate the program illustrated for the problem.
I created a new windows forms control library project from the provided templates.
I also added a windows form application project to the solution.
I added the ToolboxBitmap attribute in the code and an image in the user control project.

In this way, I find the same problem.
You can try this project.

 [WinFormsControlLibrary.zip](https://github.com/user-attachments/files/17585530/WinFormsControlLibrary.zip)

Thank you for your help

**Comment by Perpete** [comment]
Hello,
I just found the solution.
The image referenced as the value of the ToolboxBitmap attribute and located in the user control project must have the **Build Action** property set to **Embedded Resource**.
This property was set to **none** by default.

![Image](https://github.com/user-attachments/assets/82398eea-7bc5-4b27-85b0-1c459ae39bf3)

Now my image is displayed correctly in the toolbox.

![Image](https://github.com/user-attachments/assets/6a1e99d5-0f58-42cf-9389-c539df73e4de)
