### ISSUE TITLE
Adding the project name to the class of a user control in the toolbox.

### ISSUE THREAD

**Issue by Perpete** [dotnet/winforms#12404]
### .NET version

.net 8

### Did it work in .NET Framework?

Yes

### Issue description

I just noticed that when creating a user control, the project name was added in parentheses after the name of the user control class in the toolbox.
The project name is already used as the name of the tab.
This display mode is identical after installing a nuget package including user controls.
Can't we remove this project name that is not on the other items in the toolbox?
In previous versions of visual studio, the project name was not visible.

After installing the nuget package containing the user controls in a new solution, I was able to rename the elements in the toolbox using a right click on the element and the context menu.
Unfortunately after reloading the solution, the old names reappear in the toolbox.

My current version of visual studio is 17.11.5 with .net 8.
I work in VB.net.

![Image](https://github.com/user-attachments/assets/f5f0e62e-9d8e-461a-a078-1c63c3639b42)

### Steps to reproduce

Create a solution with a user control and a windows form project.
The windows form project must have a dependency with the user control.
Open the windows form project form in design mode.
Check the toolbox

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang  - could you please copy this issue to the designer repo and close this issue? 
@Perpete  - we will update this issue when we resolve the duplicate in the private repo. In the future, please use https://learn.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022 to open designer bugs, that channel is visible to more users who can vote on issues to help us prioritize them.

**Comment by Perpete** [comment]
I'm copying this issue to the designer's repository.

Thanks.

**Comment by Olina-Zhang** [comment]
@Perpete  filed that issue in our internal designer repo: https://github.com/microsoft/winforms-designer/issues/6165. Thanks!
