### ISSUE TITLE
.net8 winform vs hot reaload faild

### ISSUE THREAD

**Issue by dotecxy** [dotnet/winforms#12417]
### .NET version

.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.251308be
 MSBuild version:   17.11.3+0c8610977

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400\

已安装 .NET 工作负载:
配置为在安装新清单时使用 loose manifests。
 [aspire]
   安装源文件: VS 17.11.35312.102
   清单版本:    8.1.0/8.0.100
   清单路径:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   安装类型:        FileBased

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  3.1.418 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download 

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Net8.0+

### Issue description

.csproj (第 1 行): 错误 CS7038: 未能发出模块“xxxx”: 调试过程中不允许更改程序集引用的版本:“System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”版本改为“8.0.0.0”。

![Image](https://github.com/user-attachments/assets/b7cbddd8-3330-4c7b-bcc8-f43870bd1cd6)

![Image](https://github.com/user-attachments/assets/e95904ec-7b63-4421-a572-18c47d4652dc)

### Steps to reproduce

Add code int a=0;
Click on hot reload.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you help us understand the scenario here? We don't have enough information as it is (language barrier and images).

**Comment by dotecxy** [comment]
> [@Olina-Zhang](https://github.com/Olina-Zhang) can you help us understand the scenario here? We don't have enough information as it is (language barrier and images).

The project was originally scheduled for. net4.8, but after upgrading to. net8 using the upgrade assistant, the VS hot reload cannot be used and prompts System Runtime cannot be upgraded from 4.0.0 to 8.0.0

**Comment by Olina-Zhang** [comment]
This issue cannot reproduce in a standalone Winforms .NET 8.0 or .NET framework app, hot reload feature works well, it can apply code change.

@dotecxy  I am not sure how you upgrade application from .NET4.8 to .NET 8.0. Can you try to reference the correct assembly firstly, then see if hot reload works well?

**Comment by dotecxy** [comment]
Update the body to resolve the issue
