### ISSUE TITLE
[Accessibility] Pressing Up/Down keyboard in drop-down list of property collapses drop-down directly

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#12434]
### .NET version

10.0.100-alpha.1.24553.6

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, all versions have this issue

### Issue description

Pressing Up/Down keyboard in drop-down list of property collapses dropdown directly.
![Image](https://github.com/user-attachments/assets/2d68ad2b-a52a-4348-ac19-ab94a99e1597)

**Expand Result**: Drop-down list keeps expanding state when pressing Up/Down keyboard, then pressing Enter can collapse it

### Steps to reproduce

Repro steps:
1.	Find one property with dropdown list in PropertyGrid, for example: **Multiline**
2.	Tab to its value part: **False**, then press Up keyboard  to change value: **True** --- it is necessary step
3.	Press Alt+Down or F4 to expand this property's drop-down list
4.	Press Down keyboard to choose another value: **False**

**Comment by merriemcgaw** [comment]
@LeafShi1  you were working on a related issue with drop downs. Should we make sure fixing this behavior is included in your fix before we service?

**Comment by LeafShi1** [comment]
> [@LeafShi1](https://github.com/LeafShi1) you were working on a related issue with drop downs. Should we make sure fixing this behavior is included in your fix before we service?

This problem occurs in the drop-down box that is expanded by the shortcut key after changing the property value, and this problem occurs in all properties. I am investigating this problem.

We can backport to 9.0 together after this problem is fixed

**Comment by Liv-Goh** [comment]
Verified this issue in the latest .NET 10.0 SDK build: 10.0.100-alpha.1.24611.5 + binaries built from the main branch of Winforms repo, the issue has been fixed: When Pressing Up/Down keyboard in drop-down list of property does not collapses the drop-down list.

https://github.com/user-attachments/assets/4649725f-69c3-4453-a18d-6c937c8390e6
