### ISSUE TITLE
SystemIcons.GetStockIcon with StockIconId.Settings returns an empty, all-black icon

### ISSUE THREAD

**Issue by brondavies** [dotnet/winforms#12447]
### .NET version

8.0.10

Tested on Windows 11 23H2 Build 22631.4391

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

N/A

### Issue description

Get an icon with

`SystemIcons.GetStockIcon(StockIconId.Settings, StockIconOptions.SmallIcon)`

The returned `Icon` is a black empty square - not an empty icon.

This feature was implemented in https://github.com/dotnet/winforms/issues/8802

### Steps to reproduce

See attached project

[WinFormsApp1.zip](https://github.com/user-attachments/files/17670136/WinFormsApp1.zip)

**Comment by Zheng-Li01** [comment]
Get the below results.
![Image](https://github.com/user-attachments/assets/50c5695f-e10f-43dc-af21-16a886e9e5f3)

**Comment by merriemcgaw** [comment]
@Zheng-Li01 did it repro in 9 too?

**Comment by JeremyKuhne** [comment]
This is as expected per the documentation:

https://learn.microsoft.com/windows/win32/api/shellapi/ne-shellapi-shstockiconid#members

There really isn't much we can do here as we're just giving back what Windows gives us. If they choose to put content there in the future we'll get it.

**Comment by brondavies** [comment]
@JeremyKuhne Wow! I had previously tried the API directly as well and got the empty icon too.  I didn't realize it was documented on that page to return nothing!! 😱
Is there a place where we can submit that as an issue?

**Comment by paul1956** [comment]
Looks like Laptop icon is also empty, if anyone is reporting it.

**Comment by JeremyKuhne** [comment]
The Feedback Hub app in Windows is the place to report issues.
