### ISSUE TITLE
Graphics.DrawString result is sometimes (partially) ROT1 shifted

### ISSUE THREAD

**Issue by mnijholt** [dotnet/winforms#12446]
**Description**

We create a Bitmap using a Graphics instance that is setuo like this

```
  Bitmap = new Bitmap(canvasWidth, canvasHeight);
  Bitmap.SetResolution(this.dpi, this.dpi);

  Graphics = Graphics.FromImage(Bitmap);
  Graphics.Clear(Color.White);
```

We then Draw multiple items using the Graphics instance on the image. Most of then are texts using `Graphics.DrawString`. Some of them contain words other numbers or combination of them.

Most of the time the result is correct but sometimes the text that is rendered on the image seems ROT1 decoded.

 ![Image](https://github.com/user-attachments/assets/519ad857-a435-4113-a6b7-377d653e0461)

In the image you can see the result of the following text `08 november 2024`. The numbers are always correct but the letters are (as you can see) randomly correct or shifted one letter in the alphabet. 

```
  var font = LoadFont("Roihu.otf")

  Graphics.DrawString("08 november 2024", new Font(font, 8, FontStyle.Bold), Brushes.Black, 45, 45);

  private FontFamily LoadFont(string fontName)
  {
	PrivateFontCollection collection = new PrivateFontCollection();

	using var fontStream = GetResourceFileStream(fontName);

	int fontStreamLength = (int)fontStream.Length;

	nint data = Marshal.AllocCoTaskMem(fontStreamLength);

	byte[] fontData = new byte[fontStreamLength];
	fontStream.Read(fontData, 0, fontStreamLength);

	Marshal.Copy(fontData, 0, data, fontStreamLength);

	collection.AddMemoryFont(data, fontStreamLength);

	Marshal.FreeCoTaskMem(data);

	return collection.Families[0];
  }
```

I first thought the issue could be related to how the font file was loaded, but when texts are messed up also other texts that are drawn on the image (using the same font) are rendered correct, so that why I assume this isn't the issue. I added this to give a complete picture.

**Configuration**

NET8.0
Azure App Service (windows)

**Comment by Zheng-Li01** [comment]
@mnijholt, Create the project based on your description to reproduce the issue, but get the below error. Could you please modify the attached application or provide reproduce project to help repro this issue?
[12446RepoApplication.zip](https://github.com/user-attachments/files/17675771/12446RepoApplication.zip)
![Image](https://github.com/user-attachments/assets/7667e9a0-25c9-4fae-bb4b-abffb3c936e4)

**Comment by baswarmerdam** [comment]
Hi @Zheng-Li01 

Thank you for looking into this. I am a colleague of @mnijholt . I cannot share the font file publicly. Can I send it by email?

**Comment by Zheng-Li01** [comment]
@baswarmerdam, thanks for your update. please have try to file feedback under https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022, then attached the reproduce application & font file in the feedback to help us to reproduce the issue.

**Comment by baswarmerdam** [comment]
Hi @Zheng-Li01 

I just submitted the feedback with an attached console application to reproduce the issue. See the comments in the feedback for details.
If you have any questions, please let me know.

**Comment by Zheng-Li01** [comment]
@baswarmerdam, got it, thanks for your update, could you please share the feedback link on here.

**Comment by baswarmerdam** [comment]
@Zheng-Li01 Sure, see: https://developercommunity.visualstudio.com/t/In-reference-to-case-https:githubcom/10786734

**Comment by Zheng-Li01** [comment]
As below screenshot that some letters are shifted one letter in the alphabet.
![Image](https://github.com/user-attachments/assets/2a24bd6c-a192-4013-8afc-993f49128f1a)

**Comment by baswarmerdam** [comment]
@Zheng-Li01 Glad you could reproduce. I am curious if this is indeed a bug in the library. Will wait for an update.

**Comment by baswarmerdam** [comment]
It looks like it is related to having multiple fonts. If I just use one font for everything, the issue does not seem to occur.

**Comment by baswarmerdam** [comment]
@Zheng-Li01 Do you perhaps have an update on the issue, and if not, an ETA when there might be?

**Comment by Zheng-Li01** [comment]
@lonitra  @JeremyKuhne, can you please share any ideals for this issue?

**Comment by lonitra** [comment]
@Zheng-Li01 it seems the repro project is no longer attached the feedback ticket. If you still have it, please share with us in an email. Thank you!

**Comment by Zheng-Li01** [comment]
> [@Zheng-Li01](https://github.com/Zheng-Li01) it seems the repro project is no longer attached the feedback ticket. If you still have it, please share with us in an email. Thank you!

Have sent the repro project to you in an email, please have a check.

Thanks
Zheng

**Comment by JeremyKuhne** [comment]
@Zheng-Li01 can you validate this down-level?

**Comment by Zheng-Li01** [comment]
> [@Zheng-Li01](https://github.com/Zheng-Li01) can you validate this down-level?

The issue can reproduce from .NET 6.0 to latest .NET 10.0.

**Comment by JeremyKuhne** [comment]
@Zheng-Li01 Can you validate against .NET Framework as well when checking down-level? It is unlikely that this is something we regressed, but still worth checking.

@baswarmerdam `FontCollection` is a finalizable class, you need to keep it rooted to make sure it isn't collected until you're completely done using all fonts in the collection or the Garbage Collector will free it, which will cause all sorts of unpredictable issues.

**Comment by baswarmerdam** [comment]
@JeremyKuhne Did a quick test and the issue indeed seems to be fixed when I make FontCollection an instance of the class instead of creating it, adding a font and then return that font.

Wouldn't in a million years expect it to display this weird behavior though where characters are shifted by an offset of one. I would expect some exception instead.

Thank you!
