### ISSUE TITLE
[Accessibility] HC themes: The color contrast is less than 4.5:1 for the text "Document does not contain any pages" in printPreviewControl

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#12441]
### .NET version

.NET SDK 10.0.100-alpha.1.24556.12

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, also repro in previous versions

### Issue description

The color contrast is less than 4.5:1 for the text "Document does not contain any pages" in printPreviewControl 

**Win11 Results:**
![Image](https://github.com/user-attachments/assets/e2ddad7f-f191-4de2-82b5-5180efef4777)

**Win10 results:**
![Image](https://github.com/user-attachments/assets/0fc5bafd-bfa7-427f-96f5-f613c38b22aa)

**Framework results:**
![Image](https://github.com/user-attachments/assets/a9711c10-3858-4082-a7b8-ecc75bea6364)

### Steps to reproduce

1. Use attached application:
[RepoApplication.zip](https://github.com/user-attachments/files/17655376/RepoApplication.zip)
2. Set windows to different HC themes
3. build and run application
4. Obserrve the text "Document does not contain any pages" in printPreviewControl by using Accessibility Insight tools.

**Comment by Zheng-Li01** [comment]
Verified the issue on latest .NET SDK 10.0.100-alpha.1.24570.2q, the issue has been fixed on both Windows 11 and Windows 10 as below screenshot.
**Windows11:**
![Image](https://github.com/user-attachments/assets/baf97544-1e32-452f-89cc-40c7d92d88cf)
**Windows10:**
![Image](https://github.com/user-attachments/assets/8c907a9f-9104-40cc-9596-c73078da3cd2)

**Comment by chaowendy** [comment]
Verified the issue on latest .NET SDK 9.0.200-preview.0.24575.35 + private dlls built from dotnet/winforms release/9.0 branch, the issue has been fixed. Test result is same as above.

**Comment by Nora-Zhou01** [comment]
Verified it in the .NET 9.0.1 servicing test pass, this issue was fixed with the same results as above.
