### ISSUE TITLE
When using up/down to toggle property value on edit text box, edit text box loses focus

### ISSUE THREAD

**Issue by LeafShi1** [dotnet/winforms#12440]
### .NET version

10.0.100-alpha.1.24553.6

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, all versions have this issue

### Issue description

The rectangle always back to focus on entire row after using the up/down changed the `AutoSize ` property values directly in the edit textbox

![BeforeChanges](https://github.com/user-attachments/assets/8452b4d2-c08a-4f06-b0b6-4418f5a8a75a)

**Expected result:**
The rectangle in the edit text box always stays in the edit textbox when changing the property value using the up/down buttons 
![AfterChanges](https://github.com/user-attachments/assets/9e53bbd5-6c55-4eb5-bc31-2392c910417e)

### Steps to reproduce

1. Create a Windows Forms App
2. Add a Button to form and focus on it
3. Open the property page
4. Open Inspect
5. Select `AutoSize` property
6. Changing the property value using the up/down buttons in the edit textbox

**Comment by Nora-Zhou01** [comment]
Verified the issue on latest .NET SDK 10.0.100-alpha.1.24570.21, the issue has been fixed The rectangle in the edit text box always stays in the edit textbox when changing the property value using the up/down buttons.

https://github.com/user-attachments/assets/a0ab3423-4721-4489-9bca-d941fe3d8eb0
