### ISSUE TITLE
Custom DataGridViewColumn's property not correctly stored in designer.cs

### ISSUE THREAD

**Issue by ahdung** [dotnet/winforms#12463]
### Environment

VS2022 17.11.5

### .NET version

TFN: net48; net6.0-windows

### Did this work in a previous version of Visual Studio and/or previous .NET release?

I'm sure it works in old time, but not sure which version.

### Issue description

[RadioButtonCellDemo.zip](https://github.com/user-attachments/files/17712536/RadioButtonCellDemo.zip)

After changed `Column3.AllowUncheck` property to `true` in designer, it won't update in `designer.cs` file.

![Image](https://github.com/user-attachments/assets/1e6be7d3-f83b-461b-b7fd-99317967d3b0)

### Steps to reproduce

see `Issue description`

### Diagnostics

```text

```

**Comment by Zheng-Li01** [comment]
There have the same behaviors between .NET Framework project targeting with 4.8.1 and .NET project targeting with .NET Core 3.1 on Dev16 16.11.41 as below screenshot. 
![Image](https://github.com/user-attachments/assets/7aa94f59-e873-4ed0-82f3-6e5213e2146f)

**Comment by ahdung** [comment]
@Zheng-Li01 Thanks, maybe you can try non-sdk style project?

**Comment by merriemcgaw** [comment]
@ahdung .NET  does not support non SDK style projects. Only .NET Framework does.

**Comment by ahdung** [comment]
@merriemcgaw Yes, I mean try `net48` under legacy style project.

**Comment by ahdung** [comment]
legacy project also has issue, so the only problem is VS.

**Comment by LeafShi1** [comment]
Because the newly added property value is not cloned from the original property collection to the edit column page, you can override method `Clone ` to ensure that your property values ​​are cloned to the edit column page.
![Image](https://github.com/user-attachments/assets/d0be94f3-f735-4fd4-b3fb-7db9edda2fa3)

**Comment by ahdung** [comment]
@LeafShi1 Yes, it works, Thank you very much, you're gorgeous.
