### ISSUE TITLE
`ImageCodecInfo.GetImageEncoders()` throws fatal exception in 9.0.0 package.

### ISSUE THREAD

**Issue by bitbound** [dotnet/winforms#12494]
### .NET version

9.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes.  It worked in 8.0.x.

### Issue description

`ImageCodecInfo.GetImageEncoders()` throws a fatal exception in the 9.0.0 version of `System.Drawing.Common`.

## Exception in 9.0

![Image](https://github.com/user-attachments/assets/1138edc7-1acc-41b9-a472-fbf1c6aebb9b)

## Working in 8.0
![Image](https://github.com/user-attachments/assets/01b8842f-5bcd-4ff3-8bb7-0bc11c2a96ed)

**Comment by JeremyKuhne** [comment]
@bitbound you can work around this by getting one of the `Brushes` or `Pens`, etc.

Validation that GDI+ is initialized slipped through in this use case. Need to check other places PInvokes come from the Core assembly.

Will fix and put up for servicing.

**Comment by bitbound** [comment]
@JeremyKuhne   Thanks for the reply.  I'm not sure what you mean about `Brushes`/`Pens`, though.  I'm not seeing how I'd get an `ImageCodecInfo` out of one of them.

If it helps, here's my use case.  This is in a desktop console app (Windows only). Is there another way to adjust encoding quality that'd work around this issue?  Or would you recommend migrating to SkiaSharp?

```
  private readonly ImageCodecInfo _jpegEncoder = ImageCodecInfo
    .GetImageEncoders()
    .First(x => x.FormatID == ImageFormat.Jpeg.Guid);

  public byte[] EncodeJpeg(Bitmap bitmap, int quality)
  {
    using var ms = new MemoryStream();
    using var encoderParams = new EncoderParameters(1);
    encoderParams.Param[0] = new EncoderParameter(Encoder.Quality, quality);
    bitmap.Save(ms, _jpegEncoder, encoderParams);
    return ms.GetBuffer();
  }
```

**Comment by JeremyKuhne** [comment]
Need to service .NET 9.

**Comment by JeremyKuhne** [comment]
Actually, the only method I missed in .NET 9 was GetImageEncoders.

**Comment by Philip-Wang01** [comment]
Verified this issue in the 9.0.0 rc2 build + release/9.0 private dll, it was fixed now. If you call GetImageEncoders before any other System.Drawing code, no error occurs.

Before the fix:
![Image](https://github.com/user-attachments/assets/45bfc98f-e3dc-432c-b316-0a4a7bf89b9e)


After the fix, now:
![Image](https://github.com/user-attachments/assets/99f9b34d-f893-4058-a596-1469e2e785bd)

**Comment by John-Qiao** [comment]
@JeremyKuhne Verified the issue on latest .NET SDK 10.0.100-alpha.1.24570.21, there's no exception in ImageCodecInfo.GetImageEncoders() now. But there's no the Non-Public members node shows in each GetImageEncoders returned item in .NET 10.0, is that the expected result?

.NET 10.0:
![Image](https://github.com/user-attachments/assets/5022685d-4b08-4ef4-b946-4b865afe289a)

.NET 8.0:
![Image](https://github.com/user-attachments/assets/165ae401-e275-499b-a2b8-ffaddfbde141)

**Comment by JeremyKuhne** [comment]
@John-Qiao the debugger issue doesn't have anything to do with my change. Not sure what that would be coming from.

This was serviced back to .NET 9, the first update is in January.

**Comment by gjmv** [comment]
Hi, i have same problem with .net 8.0.400
I applied suggested workaround for now

**Comment by Syareel-Sukeri** [comment]
Verified it in the 9.0.1 servicing test pass, this issue was fixed with the same results as above.
