### ISSUE TITLE
Infinite loop in ToolStripItemCollection.AddRange

### ISSUE THREAD

**Issue by ottoman52** [dotnet/winforms#12495]
### .NET version

.NET 8.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

I dont know

### Issue description

There is an infinite loop in ToolStripItemCollection.cs:

```
public void AddRange(ToolStripItemCollection toolStripItems)
{
	ArgumentNullException.ThrowIfNull(toolStripItems, "toolStripItems");
	if (IsReadOnly)
	{
		throw new NotSupportedException(System.SR.ToolStripItemCollectionIsReadOnly);
	}
	using (new LayoutTransaction(_owner, _owner, "Items"))
	{
		for (int i = 0; i < toolStripItems.Count; i++)
		{
			Add(toolStripItems[i--]);
		}
	}
}
```

for (int i = 0; i < toolStripItems.Count; i++) counts up from 0 but decrements 'i' down in Add(toolStripItems[i--]);

Any call to add items using this override will infinite loop with i going from 0 -> -1 -> 0 -> -1 etc...

### Steps to reproduce

Any call to ToolStripItemCollection.AddRange(ToolStripItemCollection toolStripItems) with items.

**Comment by elachlan** [comment]
@Olina-Zhang can your team test this please?

**Comment by Olina-Zhang** [comment]
> [@Olina-Zhang](https://github.com/Olina-Zhang) can your team test this please?

We can repro this issue from .NET 6.0 to .NET 10 latest build with following testing code and sample application, not .NET 5.0 and .NET framework 4.8.1

```
public Form1()
{
    InitializeComponent();
    // Step 1: Add a ToolStrip to form designer, named mainToolStrip
    // Step 2: Create a second ToolStripItemCollection (you can also create individual ToolStripItems)
    ToolStripItemCollection itemCollection = new ToolStripItemCollection(mainToolStrip, new ToolStripItem[] {
    new ToolStripButton("Button 1"),
    new ToolStripButton("Button 2")});

    // Step 3: Call AddRange with the second collection
    mainToolStrip.Items.AddRange(itemCollection);  // This will cause an infinite loop
}
```
[WinFormsApp26.zip](https://github.com/user-attachments/files/17793592/WinFormsApp26.zip)

**Comment by elachlan** [comment]
@Olina-Zhang since the fix is pretty straight forward. Did your team want to take it on?

**Comment by Olina-Zhang** [comment]
@elachlan Tried to modify **AddRange** method with following, although this issue is resolved, but the issue https://github.com/dotnet/winforms/issues/4454 is not fixed well. Need to investigate further...

```
 public void AddRange(ToolStripItemCollection toolStripItems)
 {
     ArgumentNullException.ThrowIfNull(toolStripItems);

     if (IsReadOnly)
     {
         throw new NotSupportedException(SR.ToolStripItemCollectionIsReadOnly);
     }

     using (new LayoutTransaction(_owner, _owner!, PropertyNames.Items))
     {
         for (int i = 0; i < toolStripItems.Count; i++)
         {
             Add(toolStripItems[i]);
         }
     }
 }
```

**Comment by Olina-Zhang** [comment]
Looks good, it can resolve both of issues.

**Comment by elachlan** [comment]
We should make sure we have test coverage of both issues.

**Comment by Olina-Zhang** [comment]
> for (int i = toolStripItems.Count - 1; i >= 0; i--)
>         {
>             Add(toolStripItems[i]);
>         }

this will cause the order of items is reversed, see following:
![Image](https://github.com/user-attachments/assets/24613df0-7a03-4170-a678-2879a0cca489)

can we do toolStripItems.InnerList.Reverse() firstly?
```
using (new LayoutTransaction(_owner, _owner!, PropertyNames.Items))
    {
        // Iterate in reverse to avoid index shifting issues.
        toolStripItems.InnerList.Reverse();
        for (int i = toolStripItems.Count - 1; i >= 0; i--)
        {
            Add(toolStripItems[i]);
        }
    }
```

**Comment by merriemcgaw** [comment]
Great work @Olina-Zhang ! Feel free to submit the PR 😄

**Comment by Tanya-Solyanik** [comment]
@merriemcgaw  - are we servicing this hung?

**Comment by Zheng-Li01** [comment]
Verified the issues on latest .NET SDK 10.0.100-alpha.1.24573.1 + private dlls built from dotnet/winforms main branch, the https://github.com/dotnet/winforms/issues/12495 and https://github.com/dotnet/winforms/issues/4454 issues have been fixed as below screenshots.

**12495** 
![Image](https://github.com/user-attachments/assets/af7b212a-5631-47be-9028-3d8b6b339640)

**4454**
![Image](https://github.com/user-attachments/assets/81158def-d604-4cf7-9984-55fb6db7031b)

**Comment by MelonWang1** [comment]
Verified the issues on latest .NET SDK 9.0.200-preview.0.24575.35 + private dlls built from dotnet/winforms release/9.0 branch, the [#12495](https://github.com/dotnet/winforms/issues/12495) and [#4454](https://github.com/dotnet/winforms/issues/4454) issues have been fixed. Test result is same as above.

**Comment by Nora-Zhou01** [comment]
Verified this issue in the 8.0.11 sdk + release/8.0 private dll,, the https://github.com/dotnet/winforms/issues/12495 and https://github.com/dotnet/winforms/issues/4454 issues have been fixed. Test result is same as above.

**Comment by Philip-Wang01** [comment]
Verified with .NET SDK 8.0.12 test pass build, the https://github.com/dotnet/winforms/issues/12495 and https://github.com/dotnet/winforms/issues/4454 issues have been fixed. Test result is same as above.

**Comment by John-Qiao** [comment]
Verified with .NET SDK 9.0.1 test pass build, the https://github.com/dotnet/winforms/issues/12495 and https://github.com/dotnet/winforms/issues/4454 issues have been fixed. Test result is same as above.
