### ISSUE TITLE
Trying to use designsurface.cs but have error on line 84 - public ICollection LoadErrors => _loadErrors ?? Array.Empty<object>();

### ISSUE THREAD

**Issue by DaveTallett26** [dotnet/winforms#12514]
I am trying to use the code designsurface.cs.

I am using the c# compiler supplied with the current version of Windows - 

Microsoft (R) Visual C# 2008 Compiler version 3.5.30729.9151
for Microsoft (R) .NET Framework version 3.5

line 84 appears to not compile
 
public ICollection LoadErrors => _loadErrors ?? Array.Empty<object>();

Can you help me please?

DMT

**Comment by paul1956** [comment]
The current C# compiler comes with Visual Studio 2022 it's at least version 12 (not near computer to check). To build WinForms Repo you need to use Visual Studio 2022, build instructions are include.

**Comment by lonitra** [comment]
As @paul1956 mentions, VS 2022 is needed. Docs on machine set up and how to build winforms repo can be found [here](https://github.com/dotnet/winforms/blob/main/docs/developer-guide.md). If you are still running into issues, please let us know, happy to help!
