### ISSUE TITLE
.NET 9.0 project form designer does not load properly after downloading the latest .NET 10.0 sdk in VS main.

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#12524]
### .NET version

.NET SDK 10.0.100-alpha.1.24570.22

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this is a regression issue. It also works fine on .NET 10.0.100-alpha.1.24561.7.

### Issue description

| VS | Default .NET 9.0 version | .NET 10.0 version | Result |
|-------|-------|-------|-------|
| 17.13.0 Preview 2.0 (latest main) | 9.0.200-preview.0.24519.19 | 10.0.100-alpha.1.24570.22(latest sdk) | .NET 9.0 project form designer does not load properly![Image](https://github.com/user-attachments/assets/d06bd8d4-fc2b-428b-9137-dfa5fc7a8edf)|
| 17.13.0 Preview 2.0 (latest main) | 9.0.200-preview.0.24519.19 | **10.0.100-alpha.1.24561.7** | .NET 9.0 Project forms designer loads properly |
| **17.12.1** | **9.0.100** | 10.0.100-alpha.1.24570.22 | .NET 9.0 Project forms designer loads properly |
| **17.13.0 Preview 1.0** | **9.0.100-rc2.24474.11** | 10.0.100-alpha.1.24570.22 | .NET 9.0 project form designer does not load properly ![Image](https://github.com/user-attachments/assets/48124e4c-d2f6-409c-8889-fc33a3deb498) |

**More Info:**
1. [verbose_log.txt](https://github.com/user-attachments/files/17840930/verbose_log.txt)
2. This issue is not reproduced in .NET 6.0 and .NET 8.0 projects.
3. This issue is also reproduced in the WPF project.
![Image](https://github.com/user-attachments/assets/74c9f690-b189-4b59-a9d8-03e8ffb58814)

### Steps to reproduce

1. Install the latest build of VS and the latest build of .NET 10.0.
2. Create a .NET 9.0 WinForms project and observe the results.

**Comment by merriemcgaw** [comment]
@Philip-Wang01 does this impact non WindowsDesktop apps, like console apps?

**Comment by chaowendy** [comment]
Verified this issue on VS latest build: Version 17.13.0 Preview 3.0 [35526.105.main]&17.13 Preview 1, the issue fixed. the form designer&MainWindow.xaml can load properly, so close the issue.
![Image](https://github.com/user-attachments/assets/dcfaf2cf-5cc1-464b-8936-2922055f641d)
![Image](https://github.com/user-attachments/assets/bc22985a-351f-43bf-91ca-e0bca98e9a5d)
![Image](https://github.com/user-attachments/assets/4053667a-afb6-4be6-80b0-663e849c8b25)
