### ISSUE TITLE
WinForms should use System.Runtime.InteropServices.ComTypes

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#1253]
Doing so will significantly reduce the footprint of WinForms and will reduce risk.

**Comment by JeremyKuhne** [comment]
This includes:

```
 ADVF
 BINDPTR
 BIND_OPTS
 CALLCONV
 CONNECTDATA
 DATADIR
 DESCKIND
 DISPPARAMS
 DVASPECT
 ELEMDESC
 EXCEPINFO
 FILETIME
 FORMATETC
 FUNCDESC
 FUNCFLAGS
 FUNCKIND
 IAdviseSink
 IBindCtx
 IConnectionPoint
 IConnectionPointContainer
 IDataObject
 IDLDESC
 IDLFLAG
 IEnumConnectionPoints
 IEnumConnections
 IEnumFORMATETC
 IEnumMoniker
 IEnumSTATDATA
 IEnumString
 IEnumVARIANT
 IMoniker
 IMPLTYPEFLAGS
 INVOKEKIND
 IPersistFile
 IRunningObjectTable
 IStream
 ITypeComp
 ITypeInfo
 ITypeInfo2
 ITypeLib
 ITypeLib2
 LIBFLAGS
 PARAMDESC
 PARAMFLAG
 STATDATA
 STATSTG
 STGMEDIUM
 SYSKIND
 TYMED
 TYPEATTR
 TYPEDESC
 TYPEFLAGS
 TYPEKIND
 TYPELIBATTR
 VARDESC
 VARFLAGS
 VARKIND
```

https://apisof.net/catalog/System.Runtime.InteropServices.ComTypes

Most of these are currently redefined in WinForms. This is a good thing to tackle early in v.Next to give the migration plenty of time to bake. It isn't a huge task, but there is transliteration risk.

Note that a lot of these are defined in WinForms as `tag*`, e.g `tagVARDESC`.

**Comment by AaronRobinsonMSFT** [comment]
cc @jkoritzinsky @jeffschwMSFT

**Comment by RussKie** [comment]
Is there a way we can test the changes to avoid/minimise changes of regressions?

**Comment by RussKie** [comment]
As discussed in https://github.com/dotnet/winforms/pull/1961/files#r327620006 a number of types in System.Runtime.InteropServices.ComTypes have a number of drawbacks, such as not being blittable or use different base types, and thus do not meet the bar.
