### ISSUE TITLE
Non-Public members node does not show for ImageCodecInfo.GetImageEncoders() returned item in debugger

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#12530]
### .NET version

.NET SDK 10.0.100-alpha.1.24571.22

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it's a regression issue, it works in .NET 8.0, but does not work in .NET 9.0 and latest 10.0.

### Issue description

The **Non-Public members** node does not show in each ImageCodecInfo.GetImageEncoders() returned item.

**.NET 10.0**
![Image](https://github.com/user-attachments/assets/d8c74508-5820-447d-998e-7fac4a5c8d9d)

**.NET 8.0**
![Image](https://github.com/user-attachments/assets/b92a00d3-caf5-4e1d-90ba-179a4f8eb1a5)

https://github.com/user-attachments/assets/a8fcabcd-c703-4557-9c12-ffddacbbb3e4

### Steps to reproduce

1. Launch the [TestApp.zip](https://github.com/user-attachments/files/17867502/TestApp.zip) project in VS and run it.
2. Press **F10**.
3. In debugger window, expand the ImageCodecInfo.GetImageEncoders returned item node.
4. Observe the **Non-Public members** node in it.

### More info
This issue occurs in **ImageCodecInfo.GetImageDecoders()** returned items too.

**Comment by Zheng-Li01** [comment]
![Image](https://github.com/user-attachments/assets/c4883914-95db-4696-940b-c6111575ad84)

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team find the commit that may have resulted in this?

**Comment by LeafShi1** [comment]
This should not be a real bug, the changes come from PR [10688](https://github.com/dotnet/winforms/pull/10688), all of the private variables are removed from [ImageCodecInfo.cs](https://github.com/dotnet/winforms/pull/10688/files#diff-00975cd619fa93e01bdd58a73adeded59ddeb9618f96224bfa7b7a9aa99f44eb)

**Comment by JeremyKuhne** [comment]
Yes, this is expected.
