### ISSUE TITLE
.NET 9 WinForms application does not run with the x64 architecture on Windows 10 (version 22H2, OS build 19045.2486).

### ISSUE THREAD

**Issue by ravipoddar10mca** [dotnet/winforms#12546]
Hi,
I created a WinForms application and build it using .NET 9 for the x64 architecture on Windows 10 (version 22H2, OS build 19045.2486).

The application does not run, but when I convert it to x86, it works. Why does a .NET 9 x64 Windows application not run on Windows 10?

I also checked that the x64 .NET 9 application works on Windows 11.

**Comment by Syareel-Sukeri** [comment]
@ravipoddar10mca The scenario was tested on Windows 10 (version 22H2, OS build 19045.5131) using .NET 9 for the x64 architecture, and the issue could not be reproduced. It might be worth upgrading the operating system to this tested version to see if the issue persists. It would also help to know the specific version of .NET 9 used, whether it was installed as a standalone SDK or through Visual Studio, and the Visual Studio version if applicable. Any screenshots or a video showing the issue would also be useful.

![Image](https://github.com/user-attachments/assets/a0f3e265-8e92-4cf1-8418-f77b34851e30)

**Comment by ravipoddar10mca** [comment]
Hi @Syareel-Sukeri 

Thanks for reply

My system configuration is given below [Difference is your os build no: 19045.5131 and my os build no : 19045.2486]

![Image](https://github.com/user-attachments/assets/d5afbb41-b8bc-482d-a22d-84d49ab229cd)

I will check after upgrade the OS

**Comment by Shyam-Gupta** [comment]
@ravipoddar10mca Could you please confirm if you are referencing any x86 assemblies in your application? If that is the case then only x86 architecture will work because x86 assemblies can be loaded in a x86 process only and not in x64.

Also, please share errors logged for your application in Windows EventVwr if any. That will help us get to the root cause. Thanks.

**Comment by ravipoddar10mca** [comment]
@Syareel-Sukeri 

Thanks ,Application is working fine after upgrade the OS ..

![Image](https://github.com/user-attachments/assets/45b6eca1-91e7-4ab5-ad8b-39a8dbd8fcef)
