### ISSUE TITLE
The compiler does not flag the code as an error when missing parentheses for extension methods that embed string interpolation

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#12547]
### .NET version

.NET SDK 10.0.100-alpha.1.24573.1

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it's a regression issue, it works in .NET 5.0, but does not work in .NET 6.0 and latest 10.0.

### Issue description

When miss the parentheses for an extension method that embeds string interpolation, the compiler does not flag the code as an error and the code compiles without errors

**.NET 10.0 (.NET 8.0 and .NET 9.0 with the same results)**

![Image](https://github.com/user-attachments/assets/22185fde-43e4-4dd7-9f72-3c7be64be8e3)

**.NET 7.0 （.NET 6.0 results are the same)**

![Image](https://github.com/user-attachments/assets/34c9ce72-520f-4425-bdb8-7df36929a617)

**.NET 5.0**

![Image](https://github.com/user-attachments/assets/9fb5eb57-94f9-4c12-8b18-190aa3c18743)

### Steps to reproduce

1. Launch the [StringInterpolationFeature.zip](https://github.com/user-attachments/files/17916664/StringInterpolationFeature.zip) project
2. View Test.cs code

**More info:**
The initial feedback ticket is: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2307287

**Comment by jaredpar** [comment]
@JeremyKuhne I can't transfer either. Can we just have the issue be re-opened on roslyn?

**Comment by KlausLoeffelmann** [comment]
@Olina-Zhang, can you please have this issue double-checked and then re-open this in the Roslyn-Repo, as this is not a WinForms issue?

**Comment by Nora-Zhou01** [comment]
Copied the issue into the roslyn repo https://github.com/dotnet/roslyn/issues/76255 to track.
