### ISSUE TITLE
`ToolTip` Appears Partially Off-Screen on Left Border

### ISSUE THREAD

**Issue by ricardobossan** [dotnet/winforms#12556]
### .NET version

sdk: 9.0.100
Microsoft.NET.Sdk.IL: 10.0.0-alpha.1.24577.1

### Did it work in .NET Framework?

No

## Current Behavior
Related to [6151](https://github.com/microsoft/winforms-designer/issues/6151#event-15209033892)

The `ToolTip` width that extends beyond the left border of the screen is cut off.

![Image](https://github.com/user-attachments/assets/c2227b6d-886a-4db9-bd91-8b1910d9499e)

## Expected Behavior

The `ToolTip` should be displayed in full, regardless of its proximity to the left edge of the screen.

### Steps to reproduce

1. Create a .NET 5+ WinForms project
2. Add a `ToolStrip` control
3. Add some buttons to it
4. Set the `ToolStrip`'s `TabStop` property to `true`
5. Run the project
6. Move the form so it aligns with the left edge of the screen, or maximize it.
7. Navigate between the buttons using the arrow keys.

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .NET 10.0 SDK build: 10.0.100-alpha.1.24573.1 + binaries built from the main branch of Winforms repo, it was fixed: toolTip for first item in ToolStrip is fully visible when Form is maximized with RightToLeft Yes/No:
![Image](https://github.com/user-attachments/assets/536fd0b4-ccb0-41a4-b546-c1d346c821a9)
