### ISSUE TITLE
A casting issue error is thrown when passing `ObjectCollection` to the `AddRangeInternal` method of the `DataGridViewComboBoxCell.ObjectCollection` class.

### ISSUE THREAD

**Issue by ricardobossan** [dotnet/winforms#12612]
### .NET version

10.0.100-alpha.1.24573.1

### Did it work in .NET Framework?

Not tested/verified

### Issue description

A casting issue error is thrown when passing `ObjectCollection` to the `AddRangeInternal` method of the `DataGridViewComboBoxCell.ObjectCollection` class.

### Steps to reproduce

- Add a unit test for `DataGridViewComboBoxCell.ObjectCollection` class's `AddRange(ObjectCollection value)`:

  ```csharp
  [WinFormsFact]
  public void ObjectCollection_AddRange_AddsItemsCorrectly()
  {
     DataGridViewComboBoxCell comboBoxCell = new();
     DataGridViewComboBoxCell.ObjectCollection collection = new(comboBoxCell);
     DataGridViewComboBoxCell.ObjectCollection items = new(comboBoxCell) { "Item1", "Item2", "Item3" };

     collection.AddRange(items);

     collection.Count.Should().Be(3);
     collection[0].Should().Be("Item1");
     collection[1].Should().Be("Item2");
     collection[2].Should().Be("Item3");
  }
  ```

- Debug test:

![Image](https://github.com/user-attachments/assets/ffa859d9-b7ed-47bf-bacf-c3acd6879df9)

**Comment by Tanya-Solyanik** [comment]
Introduced in commit 2a92763a5d0a6f258b70f51fef98680265715680

**Comment by Tanya-Solyanik** [comment]
We decided to not service this issue right now, but we will revisit this decision if we get more reports.
