### ISSUE TITLE
`Graphics.DrawRectangle` throws `OutOfMemoryException`

### ISSUE THREAD

**Issue by carlreinke** [dotnet/winforms#12623]
### .NET version

`net9.0-windows`

### Did it work in .NET Framework?

Not tested/verified

### Issue description

When using a certain pen, `Graphics.DrawRectangle` throws `OutOfMemoryException` when drawing a 1x1 rectangle.

### Steps to reproduce

1. Create a new WinFormsApp project.
2. In the form code, add the following:
    ```C#
    protected override void OnPaint(PaintEventArgs e)
    {
        base.OnPaint(e);

        using (var pen = new Pen(Color.Black))
        {
            pen.DashPattern = [4, 4];
            pen.DashOffset = 4;

            e.Graphics.DrawRectangle(pen, 0, 0, 1, 1);
        }
    }
    ```
3. Run the project.

**Comment by John-Qiao** [comment]
This issue occurs from .NET 6.0 to the latest .NET 10.0.100-alpha.1.24610.7 from main branch, and it occurs in .NET Framework project too, it's not a regression issue.
![Image](https://github.com/user-attachments/assets/633aa5df-aacb-4b9c-8d04-2d3e296b904f)


If change DashOffset value to an integer other than 4 or change DashPattern value, this issue does not occur.

**Comment by JeremyKuhne** [comment]
@carlreinke Thanks for reporting this. Unfortunately the general-purpose error (which is what is happening here) that is reported by GDI+ in many cases is "out of memory". It isn't actually out of memory. GDI+ would have to either fix this or give clearer error state as to why this is an invalid starting state. (It appears to be a bug in their logic, this also happens with 8, 8 and 8 and likely others.)

Windows is unlikely to fix something like this for GDI+, but if you want to let them know you can use the feedback hub (type "feedback" in the start menu).

I'm considering whether or not I should make a breaking change in `System.Drawing` that stops throwing `OutOfMemory`. I'd put it behind an `AppContext` switch that can go back to the old behavior.  See #12627.

This is the call stack where this fails. It is pretty deep into the rendering for this call and it isn't clear as to why it gives up in this case. 

```
 GdiPlus.dll!GpPath::CreateDashedPath(const DpPen * dpPen, const GpMatrix * matrix, float dpiX, float dashScale, float needDashCaps, int) Line 4849	C++
GdiPlus.dll!DpDriver::StrokePath(DpContext * context, DpBitmap * surface, const GpRuntime::GpRect * drawBounds, const DpPath * path, const DpPen * pen) Line 381	C++
 [Inline Frame] GdiPlus.dll!GpGraphics::DrvStrokePath(const GpRuntime::GpRect *) Line 1690	C++
 GdiPlus.dll!GpGraphics::RenderDrawPath(RectF * bounds, GpPath * path, GpPen * pen) Line 1733	C++
 GdiPlus.dll!GpGraphics::DrawRects(GpPen * pen, const RectF * rects, int count) Line 1240	C++
 [Inline Frame] GdiPlus.dll!GpGraphics::DrawRect(GpPen *) Line 820	C++
 GdiPlus.dll!GdipDrawRectangle(GpGraphics * graphics, GpPen * pen, float x, float y, float width, float height) Line 9569	C++
 GdiPlus.dll!GdipDrawRectangle(GpGraphics * graphics, GpPen * pen, float x, float y, float width, float height) Line 9561	C++
```

**Comment by carlreinke** [comment]
> Windows is unlikely to fix something like this for GDI+, but if you want to let them know you can use the feedback hub (type "feedback" in the start menu).

If you can't open an internal issue that someone who maintains GDI+ will actually look at then you may as well close this issue as "won't fix" because I have zero confidence that posting a bug report to Feedback Hub is any different than writing it to NUL.

**Comment by JeremyKuhne** [comment]
@carlreinke sorry I can't give you a better answer. Maybe others will find this, and we can eventually build a case that justifies the investment/risk for them.
