### ISSUE TITLE
Freeze of designer when changing the control size when control happens to have a readonly array of structs property

### ISSUE THREAD

**Issue by CortiWins** [dotnet/winforms#12660]
### Environment

Microsoft Visual Studio Professional 2022
Version 17.12.3
VisualStudio.17.Release/17.12.3+35527.113
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

C# Tools   4.12.0-3.24572.7+dfa7fc6bdea31a858a402168384192b633c811fa
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

### .NET version

Net 8.0 Windows

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Did not check.

### Issue description

I made a user control with a public readonly property of type array of structs.

When i try to change the controls size, visual studio and the out of process designer freeze while both staying at roughly 5% CPU use according to task manager.

[Browsable(false)] does not prevent it.

I reproduced the issue in a minimal project. 

No immediate help required because i can just not do that.  Have a good day everyone.

### Steps to reproduce

1. Create new Winforms 8.0 App
2. Use this code
3. Change the size in the designer

```
public partial class MrFreeze : UserControl
{
    public MrFreeze()
    {
        InitializeComponent();
    }

    public TestStruct[] StructArray { get; } = new TestStruct[5000];
}

public struct TestStruct
{
    public int a;
    public string b;
}
```

### Diagnostics

```text

```

**Comment by elachlan** [comment]
@Olina-Zhang can your team please have a look? I think there is some guidance on implementing custom controls and serialization that might help here.

**Comment by MelonWang1** [comment]
@CortiWins Thank you for your feedback on the issue, but unfortunately we did not reproduce the issue based on the steps you provided. Below are the steps we took to reproduce the issue, can you check them?

https://github.com/user-attachments/assets/427e62bf-bcad-4f34-8618-5b1561a149cd

**Comment by elachlan** [comment]
@MelonWang1 can you place the user control on a form and try resizing it? Maybe its that?

**Comment by MelonWang1** [comment]
@elachlan Yes, you are right. This issue cannot repro in .NET Framework project. Repro in VS16.11.42.

**Repro step:**
1. Create a new Winforms .NET Core App
2. Use Ctrl+Shift +A to add a form2
3. Add below code
```
public partial class MrFreeze : UserControl
{
    public MrFreeze()
    {
        InitializeComponent();
    }

    public TestStruct[] StructArray { get; } = new TestStruct[5000];
}

public struct TestStruct
{
    public int a;
    public string b;
}
```
4. Build project
5. Drag the Form2 user control to form1 designer and resize it

https://github.com/user-attachments/assets/f01b27aa-bc7e-4cbb-9018-329282b0347e

**Comment by Tanya-Solyanik** [comment]
@MelonWang1  - could you please copy this issue to the designer repo if we don't already have one like this.

**Comment by MelonWang1** [comment]
Filed it in our internal designer repo: https://github.com/microsoft/winforms-designer/issues/6226 to track, closing this one.
