### ISSUE TITLE
Port System.Windows.Forms.Design.ListControlStringCollectionEditor

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1271]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes/No

**Problem description:**
`ListControlStringCollectionEditor` from System.Windows.Forms.Design is missing

Refer to https://github.com/dotnet/winforms/issues/1115#issuecomment-504798149

**Comment by Lydia-Shi** [comment]
Verified with latest .NET Core 3.1 3.1.100-GA-014700 build, this issue is fixed.
![ObjectString](https://user-images.githubusercontent.com/54019172/68746639-f747d480-0633-11ea-84ef-5aa03be6f823.PNG)
