### ISSUE TITLE
Port System.Windows.Forms.Design.TabPageCollectionEditor

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1281]
**Problem description:**
`TabPageCollectionEditor` from System.Windows.Forms.Design is missing

Refer to https://github.com/dotnet/winforms/issues/1115#issuecomment-504798149

**Comment by zsd4yr** [comment]
closed by https://github.com/dotnet/winforms/commit/5d0a337ee6c856c2877c7731c9db7f4a03751a4d
