### ISSUE TITLE
New VB default font needs to be highlighted in Read Me/Whats New

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#1298]
* .NET Core Version: 3.0 Preview6
* Have you experienced this same ISSUE with .NET Framework?: No
**Problem description:**
The default font for VB Forms has changed and is larger causing layouts to look different
**Actual behavior:**
Controls are not in the same place between Framework and Core
**Expected behavior:**
Things would look the same, but since that is not happening some customer facing visible document of this change
**Minimal repro:**
![image](https://user-images.githubusercontent.com/12789369/60761496-afb69980-9ffe-11e9-9b41-626e1e162558.png)

**Comment by RussKie** [comment]
@paul1956 the default font was changed in #656.

@merriemcgaw @KlausLoeffelmann we need to revisit this.

**Comment by paul1956** [comment]
I am not asking for it to be revisited, it looks great but without a UI designer in Core for VB I had no idea if the port of my application was the issue or why things didn't fit. The request here is documentation and to make it easy to know what the new default font is (because its default its value does not show up in designer.vb).  All I had to do is change the default font in my Framework app to match Core, align everything in Framework and copy the designer.VB file to Core project. Now repeat for every form.

**Comment by RussKie** [comment]
Thank you for the clarification.
We will update the documentation for the v3.0 release, and continue to monitor issues related to the subject. 



> All I had to do is change the default font in my Framework app to match Core, align everything in Framework and copy the designer.VB file to Core project.

If you haven't already, please have a look at https://github.com/dotnet/winforms/blob/master/Documentation/winforms-designer.md, you may find it useful.

**Comment by RussKie** [comment]
The font changes have been documented at https://github.com/dotnet/docs/issues/14143

**Comment by merriemcgaw** [comment]
Nice!
