### ISSUE TITLE
Dependencies are not getting updated

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/winforms#1304]
Dependency updates seem to have stalled on dotnet/winforms. 

The last update was 14 days ago, approximately. See https://github.com/dotnet/winforms/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdotnet-maestro. 

Triggering subscriptions manually doesn't seem to have any effect either. 

/cc @merriemcgaw, @AdamYoblick, @RussKie 
/cc @wtgodbe

**Comment by wtgodbe** [comment]
May be https://github.com/dotnet/core-eng/issues/6868
