### ISSUE TITLE
`ImageCollectionEditor` unable to add an image at runtime 

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1335]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes/No

**Problem description:**

Having ported `ImageCollectionEditor` code from NETFx, it appears impossible to add an image at run-time via `ImageCollectionEditor`.
The error appears in both NET Fx (4.7.2/4.8) and NET Core implementations.

It is however possible to add an image via the editor at design-time.
I've checked the VS implementation and it also appears to be the same as in latest NET Fx.

Relates to #1273 

**Actual behavior:** 

- to a dynamically created `ImageList`:
![ImageCollectionEditor-net472](https://user-images.githubusercontent.com/4403806/60952218-34c2eb00-a33e-11e9-8fe5-b98f1fc4f28d.gif)

- to an `ImageList` created at the design time
![ImageCollectionEditor-net472-designer](https://user-images.githubusercontent.com/4403806/60953292-3ee5e900-a340-11e9-9498-dda666110255.gif)

**Expected behavior:**

It is possible to add an image at run-time

**Minimal repro:**

https://github.com/RussKie/Test-ImageCollectionEditor/issues/1

**Comment by RussKie** [comment]
@merriemcgaw  @dreddy-work 

@Olina-Zhang could you please check whether this ever worked in NET Fx?

**Comment by Olina-Zhang** [comment]
@RussKie I checked all .Net frameworks, behaviors are same, at VS design time, it can add image successfully, and in PropertyGrid runtime, there is an error existed when adding image in ImageCollectionEditor:
![image](https://user-images.githubusercontent.com/26474449/61029524-12e25c00-a370-11e9-95a5-11d2d2e3c377.png)

**Comment by RussKie** [comment]
Thank you, @Olina-Zhang.

It will be fixed in Core. @merriemcgaw what's our appetite getting it fixed in NETFx?

**Comment by merriemcgaw** [comment]
If we have a customer requesting the fix we likely would, but really not until then.
