### ISSUE TITLE
Form.FormBorderStyle == SizeableToolWindow not working.

### ISSUE THREAD

**Issue by IanMarteens** [dotnet/winforms#1338]
* .NET Core Version: Preview 6
* Have you experienced this same bug with .NET Framework?: No

**Problem description:** Setting FormBorderStyle to SizeableToolWindow is not working.

**Actual behavior:** Same caption bar height as a Sizeable form.

**Expected behavior:** The caption bar should be narrower, as in .NET Framework.

**Minimal repro:**: change the property in the main form of a minimal project, change its FormBorderStyle, run and compare.

**Comment by RussKie** [comment]
@IanMarteens  I am unable to repro the issue in Preview9.
It is working as expected:
![image](https://user-images.githubusercontent.com/4403806/64548563-8a644580-d337-11e9-85e9-0ff40b5f994b.png)

Can you please confirm that you still have the issue?

**Comment by IanMarteens** [comment]
Still happens in my PC. Don't know if I have to update my desktop preview. I include installed runtimes below the image:

![image](https://user-images.githubusercontent.com/44820201/64549045-2ab66c00-d330-11e9-9c3c-15dcc2a9634b.png)

C:\Users\Marteens>dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.0-preview9.19424.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.0-preview9-19423-09 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
**Microsoft.WindowsDesktop.App 3.0.0-preview9-19423-09** [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by IanMarteens** [comment]
BTW, I'm running this on a FullHD monitor (1920 x 1080) with no text scaling.

**Comment by RussKie** [comment]
What your screenshot is showing is expected and by design due to the change of the DefaultFont (#656).
More information is here dotnet/docs#14143

**Comment by IanMarteens** [comment]
Ok, thanks.
