### ISSUE TITLE
PlaceholderText API addition to TextBox control

### ISSUE THREAD

**Issue by stefanov-stefan** [dotnet/winforms#134]
With the following PR (https://github.com/dotnet/winforms/pull/96 -> moved to https://github.com/dotnet/winforms/pull/238) we have proposed addition of new property to the TextBox control called PlaceholderText. The property accepts string which will be drawn when the control has no text it in and is not on focus. Quite useful to indicate what is the expected input.

### Rationale 
Currently, in order to provide guidance for the users what input is expected in a text field, the only option is to have a label next to the TextBox control. However, there are cases, where label is not appropriate and it is much more user friendly to have a placeholder text in the TextBox itself, to guide the user as to what input is expected. Think of scenarios for "Enter your username/password"

### Proposed API
`public string PlaceholderText {get; set;}`

### Description
A single public property called `PlaceholderText` is introduced, with no value. When the property is set, AND the `TextBox` has no `Text` set nor focus, the string from the `PlaceholderText` will be drawn in the `TextBox` control, using the `SystemColors.GrayText`. Once the property value is changed the new text will be drawn, if currently visible. Once the user focuses on the control, the text disappears. Different text alignments and `RightToLeft` are taken into consideration when the `PlaceholderText` is being drawn. In addition, it also works in Multiline mode.

In addition `AccessibilityObject` has been implemented to return the `PlaceholderText` when the `Text` is empty, hence screen readers read the `PlaceholderText` value and guide the users to what is expected from them as input.

On the bottom left side of the image you can see a `TextBox` with `PlaceholderText` drawn.
![image](https://user-images.githubusercontent.com/1288402/50692467-a55e1780-103c-11e9-8447-baf771124cd8.png)

**Comment by wjk** [comment]
Is there any reason why we shouldn't just use [the `EM_SETCUEBANNER` message](https://docs.microsoft.com/en-us/windows/desktop/controls/em-setcuebanner) available since Windows Vista to do this? (I know that compatibility with *really* old systems — namely, Windows XP — would be negatively affected were we to do it this way, but I thought we don't support anything before Windows 7 anyway.)

**Comment by Misiu** [comment]
@wjk correct me if I'm wrong, but this won't work if TextBox has Multiline enabled.

**Comment by wjk** [comment]
@Misiu True, but there's no reason we can't use a custom implementation for Multiline text fields, and the system's implementation for single-line text fields. That being said, I don't really care which way we end up doing this. I just wanted to throw that link into the issue.

**Comment by KlausLoeffelmann** [comment]
Not sure, if we wanted to introduce another dependency If we'd not really need one.
@merriemcgaw?

**Comment by Tanya-Solyanik** [comment]
@KlausLoeffelmann , could you please clarify what dependency you mean?

> Not sure, if we wanted to introduce another dependency If we'd not really need one.

**Comment by KlausLoeffelmann** [comment]
@Tanya-Solyanik Well, EM_SETCUEBANNER is a OS specific dependency, which in this case might not be necessary, since for Multiline rendering we'd need the custom rendering anywhere. So, if something goes wrong, we have two potential causes to investigate, instead of one. And should someone ever want to take textbox and port it to another "context", then custom rendering might be also easier portable than relying on the OS specific EM_SETCUEBANNER.

**Comment by jnm2** [comment]
I have a strong preference for keeping the UI OS-native by using EM_SETCUEBANNER.

**Comment by KlausLoeffelmann** [comment]
@jnm2: I would agree with you, if there wasn't the need for custom rendering for MultiLine. Or do you want to abandon support for MultiLine, and only go the EM_SETCUEBANNER road?

**Comment by jnm2** [comment]
Can we start with only support for what can be natively themed (EM_SETCUEBANNER) and then look at simulating it if someone asks for multiline support down the road? It seems rare. (And when we get to the point of someone asking for it, we might be able to do something such as turning off multiline mode when the text is null or empty so that EM_SETCUEBANNER kicks in, to retain native theming.)

**Comment by KlausLoeffelmann** [comment]
I neither think it's rare, nore would I like to have it implemented inconsistently, also since It would hurt accessibility compliance, so I'd say no.

**Comment by jnm2** [comment]
'Rare' is anecdotal (I don't recall noticing it), but Windows doesn't support it natively. It would be interesting to know how relying on EM_SETCUEBANNER hurts accessibility compliance. But all that aside, making it work in multiline mode would be a good thing, so let's do that!

For placeholder text in multiline mode, can we still use EM_SETCUEBANNER and switch to and from ES_MULTILINE based on whether the placeholder text should be showing?

**Comment by KlausLoeffelmann** [comment]
I was referring to accessibility and Multiline. I am sure, if EM_SETCUEBANNER worked for MultiLine, accessibility would be even easier to cover. I am checking the exact requirements for the accessibility scenarios right now.

**Comment by merriemcgaw** [comment]
Hi @stefanov-stefan , can you please follow the instructions in the [API Review Process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) in the Core repo (specifically the speclet and sample usage) so that we can mark this API suggestion as ready for review? I'll make sure to have it on the API board's radar for the next review.

cc @terrajobst ; @KlausLoeffelmann ; @OliaG

**Comment by zsd4yr** [comment]
@stefanov-stefan how is your work providing a speclet and sample usage progressing? We are looking forward to reviewing this in the next API review meeting but we need that information first.

**Comment by Misiu** [comment]
@stefanov-stefan also please add a note that PlaceholderTest should work with multiline and with MaskedTextBox.

**Comment by merriemcgaw** [comment]
@terrajobst when is the next API Review meeting? I believe that we are ready to go with @stefanov-stefan's proposal.

**Comment by jnm2** [comment]
@zsd4yr Shouldn't the color follow the system scheme that EM_SETCUEBANNER does, regardless of how the system colors were picked?

**Comment by zsd4yr** [comment]
> @zsd4yr Shouldn't the color follow the system scheme that EM_SETCUEBANNER does, regardless of how the system colors were picked?

Whenever possible, we should try to rely on system colors. I'm only indicating that we should choose a system color that conforms to this minimum ration compared to the system color for white. I have not checked if this particular case does or does not satisfy the ratio; I am speaking generally.

**Comment by stefanov-stefan** [comment]
> @stefanov-stefan, this is really more of an implementation concern but I would be sure that your color of gray on white for the placeholder text follows [Microsoft recommended coloration guidelines](https://docs.microsoft.com/en-us/style-guide/accessibility/colors-patterns-text-graphics-design) "Choose color combinations with a minimum contrast ratio of 4.5:1"

I have already verified that as Merrie suggested earlier and the selected color is compliant. Thanks for pointing out.

**Comment by stefanov-stefan** [comment]
> @stefanov-stefan also please add a note that PlaceholderTest should work with multiline and with MaskedTextBox.

Thanks for pointing out. Actually, MaskedTextBox will not be affected, as the property is introduced in the TextBox, not the TextBoxBase class. Still, the Multiline is valid and I will indicate that.

**Comment by Misiu** [comment]
@stefanov-stefan as PlaceholderText will only show when TextBox is empty I think it is a valid request to also support it in MaskedTextBox.
I don't know the source code that much, but probably it is possible to add PlaceholderText to TextBoxBase instead of TextBox? This way TextBox and MaskedTextBox will benefit from the new property.

**Comment by terrajobst** [comment]
> @terrajobst when is the next API Review meeting? I believe that we are ready to go with @stefanov-stefan's proposal.

Tomorrow is the next triage session.

**Comment by stefanov-stefan** [comment]
> @stefanov-stefan as PlaceholderText will only show when TextBox is empty I think it is a valid request to also support it in MaskedTextBox.
> I don't know the source code that much, but probably it is possible to add PlaceholderText to TextBoxBase instead of TextBox? This way TextBox and MaskedTextBox will benefit from the new property.

I see MaskedTextBox as a control that always displays a mask to invite the user to fill in the limited desired input (e.g. ________-____-___), hence the mask itself plays the placeholder text, hence no need for additional one, considering the control purpose.

**Comment by Misiu** [comment]
@stefanov-stefan You're right - MaskedTextBox always displays a mask, so Placeholder won't be displayed.

**Comment by terrajobst** [comment]
Presumably `PlaceholderText` will behave like `Text` with respect to handling `null` vs `string.Empty`?

**Comment by Xizario** [comment]
Why not just `Placeholder`

**Comment by KlausLoeffelmann** [comment]
@Xizario: It's PlaceholderText in UWP and WPF, so we'd be consistent to that.

**Comment by zsd4yr** [comment]
:shipit: #238

**Comment by r-aghaei** [comment]
It's really good to see this feature in the framework. I used to use the same approach for my TextBox controls and had shared the approach in [stackoverflow](https://stackoverflow.com/a/36534068/3110834).

**Comment by r-aghaei** [comment]
It would be great if we can have the same for `ComboBox`. I've already shared an example [here](https://stackoverflow.com/a/50972125/3110834).

**Comment by weltkante** [comment]
@r-aghaei assuming you have specific interest in getting it done and this wasn't just a passing comment you probably want to create a new issue for that, its unlikely to be retrofitted into an already completed issue
