### ISSUE TITLE
Move ResXResourceWriter out of System.Windows.Forms

### ISSUE THREAD

**Issue by bricelam** [dotnet/winforms#1342]
In Entity Framework 6, we need to [generate resx files](https://github.com/aspnet/EntityFramework6/blob/6.2.0/src/EntityFramework.PowerShell/Migrations/Utilities/MigrationWriter.cs#L69-L72) at design time.

Now that we're porting to .NET Core, it's infeasible for us to depend on System.Windows.Forms.

Would it be possible to move this type to the existing System.Resources.Writer assembly in corefx or even just its own new package independent of Microsoft.WindowsDesktop.App? (e.g. System.Resources.ResX)

cc @divega @ajcvickers @Pilchie

**Comment by merriemcgaw** [comment]
@ericstj What are your thoughts?

**Comment by ericstj** [comment]
Resources.Writer is for resources format, not resx.  The resx writer does a lot more, including use binary formatted, typeconverter, and system.drawing types which aren’t part of the shared framework.  @bricelam what sort of data types are you putting in ResX?  It may make sense to have something lighter weight like what @rainersigwald did in msbuild.

**Comment by bricelam** [comment]
We just use strings; I’ve unblock myself with a simple implementation.

But it always seemed strange to me that this class was part of WinForms

**Comment by merriemcgaw** [comment]
I'm glad you were able to unblock yourself. I don't think we're considering moving it from where it's historically been at this point, so I'm going to close this issue.

**Comment by bricelam** [comment]
Would you accept a PR?

**Comment by merriemcgaw** [comment]
Where would you suggest having this? I don't think @ericstj would be wanting it in corefx but I could be wrong.

**Comment by ericstj** [comment]
I suspect you’ll receive pushback if you put a type in corefx.  I think it’s better to depend on the format and have a simple writer implemented on top of the xml library of your choice. 

You are welcome to open an issue in corefx for future to have that discussion.

**Comment by bricelam** [comment]
It's just been a pet peeve for years, so I wanted to test how much push back there would be. Doesn't sound like it's worth pursuing.
