### ISSUE TITLE
Replace DpiAwarenessContext enum with Windows DPI_AWARENESS_CONTEXT everywhere in the code

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#1344]
All the P/Invokes for DPI related APIs work with DPI_AWARENESS or DPI_AWARENESS_CONTEXT.
It is incorrect to use our own DpiAwarenessContext enum. 

We need to update P/Invoke headers of all such APIs and update all code invocations appropriately.

For more discussion check: https://github.com/dotnet/winforms/pull/1331

**Comment by merriemcgaw** [comment]
If we get this done sooner, fantastic. But I want to commit to doing it when we are focused squarely on HPDI stuff.

**Comment by JeremyKuhne** [comment]
Here is the main place to start in the discussion https://github.com/dotnet/winforms/pull/1331#discussion_r302679950.
