### ISSUE TITLE
Replace "magic" strings in Cursors.cs with const strings declared at top of file

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#139]
actual:

```c#
public static Cursor HSplit {
            get {
                if (hSplit == null)
                    hSplit      = new Cursor("hsplit.cur", 0);
                return hSplit;
            }
        }

```

expected:

```c#
internal const string HSPLIT_CUR = "hsplit.cur" 

// ...

public static Cursor HSplit {
            get {
                if (hSplit == null)
                    hSplit      = new Cursor(HSPLIT_CUR , 0);
                return hSplit;
            }
        }

```

**Comment by ericstj** [comment]
HSPLIT_CUR doesn't exactly follow our coding guidelines for constants https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

Moreover you may want to close this in preference to #140.

**Comment by willibrandon** [comment]
Hi, first time contributor here and I'm currently learning how to use GitHub.  I've committed the requested changes to my repository and just saw ericstj's comment regarding coding guidelines and possibly closing this issue.  How should I proceed?

**Comment by karelz** [comment]
@willibrandon let's wait on clarification if this change is needed. @zsd4yr @Tanya-Solyanik can you please help clarify if we should close this issue in favor of #140 as suggested above?

**Comment by zsd4yr** [comment]
We’re moving in favor of #140 because it will allow us to take advantage of the high resolution and accessibility complaint cursors in the OS. @willibrandon I’m glad you’re helping out here :) I expect there will be additional entry-level issues soon

Closing this issue in favor of #140

**Comment by Tanya-Solyanik** [comment]
Hi @karelz. I discussed this with @zsd4yr , we hit a race condition opening these 2 issues. Indeed #[140   ](https://github.com/dotnet/winforms/issues/140) is the preferred way to implement this  - we will get all OS improvements(high res and the right system theme) when we access the system cursors :) and will reduce size of our binary somewhat.

**Comment by karelz** [comment]
Thanks!
