### ISSUE TITLE
ComponentDesigner - InitializeNewComponent/InitializeExistingComponent issues

### ISSUE THREAD

**Issue by MrB0nd** [dotnet/winforms#1395]
* .NET Core Version: **3.0.100-preview8-013006**
* Have you experienced this same bug with .NET Framework?: **No**

I have a question about the InitializeNewComponent and InitializeExistingComponent methods of the ComponentDesigner class.
 
In .NET Framework, the InitializeNewComponent method implementation contains some code related to DesignerActionUIService. Also InitializeNewComponent calls the OnSetComponentDefaults method that sets the value of the DefaultProperty for the component. InitializeExistingComponent calls the InitializeNonDefault method that does nothing. 
 
In .NET Core InitializeNewComponent calls the InitializeNonDefault method. InitializeExistingComponent throws NotImplementedException.
 
So, my questions are:
1) Is the InitializeExistingComponent method implementation going to change in .NET Core?
2) Is the Site.Name property going to be assigned as the DefaultProperty value in the .NET Core implementation of the InitializeNewComponent method?

**Comment by MrB0nd** [comment]
@merriemcgaw @RussKie Any updates on this?

**Comment by merriemcgaw** [comment]
Sorry for the delay @MrB0nd . We're looking at the issue, and I think we're going to be able to address it in 3.1 by porting the remaining pieces of ComponentDesigner class to Core. We're unfortunately a bit overloaded to be certain we can get this in 3.0, but we expect that 3.1 is likely.

**Comment by merriemcgaw** [comment]
@MrB0nd can you tell us a bit more about the customer scenario here? If we know what you're trying to enable here we may have better guidance for you.

**Comment by MrB0nd** [comment]
@merriemcgaw 
This comes from our process of porting the DevExpress End-User Report Designer component to .NET Core 3. Our visual report designer has visual report controls inherited from the Component and their designers inherited from the ComponentDesigner class. We have a custom implementation of IDesignerHost and other design time facilities, so the component integrated into an app simulates the Visual Studio design time experience. Now, we see different behavior of our component depending on the target platform (.NET Core 3 and .NET Framework).

We would like to have consistent behavior of our component, regardless of whether it is .NET Core 3 or .NET Framework.

**Comment by merriemcgaw** [comment]
Investigating for 6.0

**Comment by RussKie** [comment]
The ported functionality will be available in .NET 6.0 Preview5. Please raise new issues for any further missing functionality. The sooner we know the higher change we get it addressed before .NET 6.0 GA.
Thanks

**Comment by Marie-Shi** [comment]
Verified this issue with .NET 6.0.100-preview.5.21276.15 from Release/6.0.1XX-preview5 branch of https://github.com/dotnet/installer, it is fixed, now those two methods InitializeNewComponent/InitializeExistingComponent have been implemented in Core.
