### ISSUE TITLE
Use system cursors in System.Windows.Forms.Cursors

### ISSUE THREAD

**Issue by sylveon** [dotnet/winforms#140]
Currently, System.Windows.Forms.Cursors has a few embedded cursors that where added for backwards compatibility with old operating systems that are not supported anymore. They should be replaced to use system cursors.

The following cursors are embedded:
 - [ ] HSplit
 - [ ] VSplit
 - [ ] NoMove2D
 - [ ] NoMoveHoriz
 - [ ] NoMoveVert
 - [ ] PanEast
 - [ ] PanNE
 - [ ] PanNorth
 - [ ] PanNW
 - [ ] PanSE
 - [ ] PanSouth
 - [ ] PanSW
 - [ ] PanWest
 - [ ] Hand (PR opened in #138)

Unit tests for the changes are required.

**Comment by zsd4yr** [comment]
Sorry for the confusion here @sylveon we **do** have a unit test infrastructure using xunit. You can find them under src->System.Windows.Forms->tests->UnitTests

Someone just needs to actually write the xunit tests for these 😄 

I believe @merriemcgaw was refering to our current lack of **functional** tests

**Comment by sylveon** [comment]
Haha, my bad. I'll take a look and try to write some tests later.

**Comment by merriemcgaw** [comment]
@sylveon, I could have been more clear, @zsd4yr is right. We have unit test infra, but we're still porting the functional tests. Would love to see unit tests!

**Comment by zsd4yr** [comment]
@sylveon I've tested just the hand and it looks great :) Works on multiple monitorys with HDPI changes too

**Comment by sylveon** [comment]
Yeah, I've been using that hand for a while now using reflection :sweat_smile: 

```cs
typeof(Cursors).GetField("hand", BindingFlags.NonPublic | BindingFlags.Static)
    .SetValue(null, new Cursor(NativeMethods.LoadCursor(IntPtr.Zero, NativeConstants.IDC_HAND)));
```

**Comment by AdamYoblick** [comment]
Just say no to private reflection! 😉

**Comment by sylveon** [comment]
Hence this pull request :smile:

**Comment by jnm2** [comment]
@sylveon I've been doing the same workaround :D

**Comment by zsd4yr** [comment]
@sylveon what work is remaining here?

**Comment by sylveon** [comment]
This is done. If you have idea for a better way to unit test this class,
feel free to share because I couldn't find one.

**Comment by drewnoakes** [comment]
Relates to https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/19085239-some-system-windows-forms-cursors-values-are-extre

**Comment by zsd4yr** [comment]
@sylveon the only way I can think would be to roll through instantiating all of them and just ensure the right one is being made. Pretty standard constructor unit test stuff.
