### ISSUE TITLE
The chosen menu items in MenuStrip/ContextMenuStrip/ToolStrip have no background color

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#1408]
* .NET Core Version: 3.0 Preview7 012821 from Release branch
* Have you experienced this same bug with .NET Framework?: No

**Minimal repro:**
1. Open attached Winforms .Net Core app and run it
[WindowsFormsApp5.zip](https://github.com/dotnet/winforms/files/3400833/WindowsFormsApp5.zip)
2. Use mouse or keyboard accelerators(after GitHub issue ![image](https://user-images.githubusercontent.com/26474449/61359933-4589ca00-a832-11e9-9f5b-2a3f18966ccd.png) fixed) to choose the drop-down menu Items in MenuStrip/ToolStrip/ContextMenuStrip controls

**More Info:**  This issue cannot repro in StatusStrip in Core app.

**Actual behavior:** 
These chosen menu items have no background color, see following screenshots for MenuStrip/ToolStrip/ContextMenuStrip:
MenuStrip:
![image](https://user-images.githubusercontent.com/26474449/61360346-22134f00-a833-11e9-9603-9cd7147e6d75.png)
ContextMenuStrip:
![image](https://user-images.githubusercontent.com/26474449/61360416-3eaf8700-a833-11e9-8724-fdf256df2074.png)
ToolStrip:
![image](https://user-images.githubusercontent.com/26474449/61360481-5e46af80-a833-11e9-9834-fd2526c3538f.png)

**Expected behavior:**
These chosen menu items have background color, like .Net framework's behavior:
MenuStrip:
![image](https://user-images.githubusercontent.com/26474449/61360583-93eb9880-a833-11e9-9cf6-b07198d33e11.png)
ContextMenuStrip:
![image](https://user-images.githubusercontent.com/26474449/61360623-abc31c80-a833-11e9-93b7-19b368d1b642.png)
ToolStrip:
![image](https://user-images.githubusercontent.com/26474449/61360672-c2697380-a833-11e9-9980-d104f85e15d6.png)

**Comment by merriemcgaw** [comment]
Regression related to the work in #1021

**Comment by merriemcgaw** [comment]
@vladimir-krestov can you take a look?

**Comment by vladimir-krestov** [comment]
@merriemcgaw Yes, assigned to me.

**Comment by merriemcgaw** [comment]
Nice!
