### ISSUE TITLE
SnapLine is not implemented

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/winforms#1412]
None of the APIs on `SnapLine` are implemented, which affects the WinForms designer.

**Comment by merriemcgaw** [comment]
Need to port this from the Framework sources into Core if we want the SnapLines feature in VS to work in the new Core Designer.

**Comment by DustinCampbell** [comment]
It's exactly a panic. I've worked around it in the new designer.

**Comment by merriemcgaw** [comment]
@RussKie will take a look and start porting as soon as he can.

**Comment by RussKie** [comment]
@DustinCampbell do I correctly understand we need to port [this class](https://referencesource.microsoft.com/#System.Design/System/Windows/Forms/Design/Behavior/SnapLine.cs,8ddcdcf6a72917bd)? Is there something else we need to port along?

**Comment by DustinCampbell** [comment]
> It's exactly a panic. I've worked around it in the new designer.

Ugh! I introduced a typo here! I meant, "it's *not* exactly a panic" 😦
