### ISSUE TITLE
SR.Designer.cs is public API

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/winforms#1413]
src\System.Windows.Forms.Design\src\Resources\SR.Designer.cs contains the strings for Winforms implementation, but it is currently a public class which means we would be shipping it as public API and need to document it, not break it, etc.

It should be internal like similar classes in CoreFX (although in CoreFX it's generated in the build)

```c#
namespace System.Windows.Forms.Design.Resources {
    using System;
...
    public class SR {
```

**Comment by danmosemsft** [comment]
This is showing up as "must be documented" in our tooling which is why I noticed it

**Comment by merriemcgaw** [comment]
Thanks @danmosemsft . I'll have @RussKie take a look. That spreadsheet scared me!

**Comment by weltkante** [comment]
@merriemcgaw I don't think that SR should be documented, it should be made internal like @danmosemsft suggested. All the SR classes are internal in Desktop Framework too, I don't see why they should start to be public.

**Comment by RussKie** [comment]
@weltkante I think you may have misread Merrie's response.
We're turning it internal like everything else.

**Comment by weltkante** [comment]
I was referring to the 'documentation' tag.

**Comment by danmosemsft** [comment]
thanks @RussKie 

cc @carlossanlop
