### ISSUE TITLE
Support Class Library project templates

### ISSUE THREAD

**Issue by jmarolf** [dotnet/winforms#1414]
This is to bring us to experience parity with desktop for WPF on .NET Core 3.0.

On desktop today you can add a class library project to your existing Winforms solution and everything will just work. Due to complexities in how Framework References work this will not light up automatically. Instead we will need a Winforms Class library template that has the correct framework references.

**Comment by jmarolf** [comment]
cc: @OliaG

**Comment by John-Qiao** [comment]
Verified in .NET Core 3.0.100-preview9-014004, issue has been fixed.

![TR2](https://user-images.githubusercontent.com/45864985/63755158-a653fa00-c8e8-11e9-8091-95547d3fd07c.png)

**Comment by RussKie** [comment]
Thank you!
