### ISSUE TITLE
Remove the word hack from repo comments

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#143]

**Comment by KlausLoeffelmann** [comment]
Actually, in some if not every cases, I think the notion of some "Workaround" or "Ad-Hoc-Solution" (cannot think of better Eupimisms in this context) would still be useful, especially in the area of rendering and layouting when we need to come back to those things for HighDPI improvements. Thoughts?

**Comment by zsd4yr** [comment]
That's the case but we missed some; we'll have it in the history in case we need it
