### ISSUE TITLE
If possible, want the Ribbon control.

### ISSUE THREAD

**Issue by maikebing** [dotnet/winforms#1436]
Existing open source projects
https://github.com/RibbonWinForms/RibbonWinForms

MFC's Ribbon Designer 
https://docs.microsoft.com/en-us/cpp/mfc/ribbon-designer-mfc?view=vs-2019

So, I think winforms should have Ribbon.

**Comment by merriemcgaw** [comment]
Thank you so much for the suggestion. Currently this isn't in our roadmap for 3.0/3.1. We may want to re-evaluate for .NET 5.

Right now we're working on a suggestion for .NET Core 3 that is going through the full process to be accepted into WinForms. The discussions in #146 and the PR #1133 are a good example of what we need to do to get a new feature into the WinForms runtime. If you're interested in providing the Ribbon control to WinForms this is a good example of how to do it.

**Comment by andersforsgren** [comment]
> We may want to re-evaluate for .NET 5.

Please reevaluate for vNext
