### ISSUE TITLE
Accessibility: PrintPreviewDialog's PageNumericUpDown spinner Accessible name is not correct

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#1470]
Accessible name of the PrintPreviewDialog PageNumericUpDown spinner is incorrect: it is empty or shows 1/2/3/4 but should have 'PageNumericUpDown' accessible name's text.

![image](https://user-images.githubusercontent.com/23213980/61881334-21e41500-aeff-11e9-9c96-23e440409fcc.png)

**Comment by John-Qiao** [comment]
Verified in .NET Core 3.0.100-preview9-014004, issue has been fixed.

![TR1](https://user-images.githubusercontent.com/45864985/63753415-9edf2180-c8e5-11e9-877d-f8286f28b5a7.png)

**Comment by RussKie** [comment]
Thank you!
