### ISSUE TITLE
Dual monitor dialog resize issue

### ISSUE THREAD

**Issue by koszeggy** [dotnet/winforms#1504]
> **Note**: Considering my last bug report for the .NET Framework at the [developer community](https://developercommunity.visualstudio.com/content/problem/651699/wpf-bindinglistcollectionview-ignores-item-replace.html) has been migrated to the corresponding .NET Core project I report this issue directly here. Please note though that .NET Framework is also affected.

**Issue reproduction steps:**

1. Make sure your secondary display is left or above of your primary display (so it has negative relative coordinates)
2. Create a new Windows Forms Application and display a form by `ShowDialog` so the resize grip is visible.
3. Execute the application and drag the form to the secondary display.
4. Now as its coordinates are in the negative range, move the mouse along the border and see that the diagonal resize cursor appears all around the form. The issue is not just the displayed cursor but also the resizing behavior behavior: _even clicking the top border the bottom-right corner will be resized_

See also the screenshot below (the cursor is indicated by me).

![image](https://user-images.githubusercontent.com/27336165/62005446-9bfcdf80-b133-11e9-8fe5-ce40719fbe89.png)

**Proposed fix:**

The root cause lies in the [`Form.WmNCHitTest`](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L7033) method. `m.LParam` contains two `short` values but the way of converting them to integers is wrong.

Original code:
```cs
// This is wrong for negative values. For example, -500 will be interpreted as 65036
int x = NativeMethods.Util.LOWORD(m.LParam);
int y = NativeMethods.Util.HIWORD(m.LParam);
```

Fixed code:
```cs
// LParam contains two shorts. Without the cast negative values turn positive ints
int x = (short)(m.LParam.ToInt32() & 0xFFFF);
int y = (short)((m.LParam.ToInt32() >> 16) & 0xFFFF);
```

**Comment by 0xd4d** [comment]
The minimal fix can just add a `(short)` cast to the original code.

Did you check if there are similar bugs in other parts of the code?

**Comment by koszeggy** [comment]
The other parts seem to be ok. I discovered this some years ago and I did not experience other issues (I use an "overridden" hittest in my projects).

**Comment by 0xd4d** [comment]
Here's one possible bug:

https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Control.cs,16568

msg is WM_MOUSEFIRST = 0x0200 to WM_MOUSELAST = 0x020A which includes eg. WM_LBUTTONDOWN = 0x0201 and according to [the docs](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-lbuttondown), you should use GET_X_LPARAM or GET_Y_LPARAM to get x/y since they're signed.

Similar bugs could be in the WPF repo too.

**Comment by RussKie** [comment]
@Olina-Zhang I understand this relates to the email thread we had.
Could you please confirm the bug?

**Comment by Olina-Zhang** [comment]
@RussKie I can repro this issue on 2 monitors with above setting: secondary display is left or above of your primary display.

Tested .Net Core app: 
[WindowsFormsApp5.zip](https://github.com/dotnet/winforms/files/3441439/WindowsFormsApp5.zip)

**Comment by merriemcgaw** [comment]
Let's see if we can get this in to 3.1, but if not we're planning on doing some Per Monitor and HDPI work in 5.0

**Comment by merriemcgaw** [comment]
@koszeggy if you'd like to submit a PR we'll be happy to review and accept it. Otherwise, it will be a while longer before we get to it.

**Comment by koszeggy** [comment]
@merriemcgaw, thank you for your trust, but as the repo requires .NET Core 5.0.100-alpha1-013788 to build, which is publicly not available (at least I could not find anything newer than 3.0.100) it is alright to me to wait for it. I have my own workaround since .NET 3.5 anyway.

**Comment by weltkante** [comment]
@koszeggy the [daily build](https://github.com/dotnet/core/blob/master/daily-builds.md) page doesn't mention it but if you click the link the actual download section has [5.0 daily builds](https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries)

**Comment by koszeggy** [comment]
I added the StatusBar fix to the PR.
I didn't change the [ActiveX-related code](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Control.cs,16568) found by @0xd4d though. Its test is a bit more complex and I think that would require another version of the `MAKELPARAM` method as well.
