### ISSUE TITLE
Cannot use System.Windows.Forms in preview7

### ISSUE THREAD

**Issue by cadesalaberry** [dotnet/winforms#1515]
# Cannot use `System.Windows.Forms` in `3.0-preview7`

When upgrading from 3.0 preview6 to 3.0-preview7 I get stuck with:

```
Error   CS0234  The type or namespace name 'Forms' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)
```

# General

I realised that the error was coming from the version of dotnet Core after uninstalling ALL available SDKs but the `3.0-preview6` version. I then executed `dotnet --version` and realised it was still using `3.0-preview7` which made no sense.

This makes me think the uninstaller must also be broken.

**Comment by weltkante** [comment]
Do you have a `<UseWindowsForms>true</UseWindowsForms>` in the project file?

**Comment by RussKie** [comment]
@cadesalaberry can you please post the content of your csproj file?



> Seems going have to wait for Preview 8.

P8 is yet to be cut, so it won't be released for another month or so.

> It looks like MS is behind with there Releases. We were suppose to be getting RC Build this month, so far nothing.

As far as our schedule goes, we're on track with our releases.

**Comment by cadesalaberry** [comment]
Here is my `.csproj`. I am not `<UseWindowsForms>true</UseWindowsForms>` as I haven't seen it documented anywhere. I will give it a try.

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="icon.ico" />
    <None Remove="stylecop.json" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.5.4" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Json" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.5.4" />
    <PackageReference Include="System.Json" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitVersionTask" Version="5.0.0-beta5.50">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

**Comment by cadesalaberry** [comment]
The build is now successful, I was missing the `< UseWindowsForms >` option to make it all work.

Thanks for the help !

**Comment by RussKie** [comment]
> ```
> <UseWPF>true</UseWPF>
> ```

Your project was targeting WPF stack.
To target WinForms (or more officially Windows Forms) you need to use `<UseWindowsForms>true</UseWindowsForms>` as @weltkante suggested.

AKAIK you can target both stacks simultaneously too, e.g. use both switches:
```
<UseWindowsForms>true</UseWindowsForms>
<UseWPF>true</UseWPF>
```

**Comment by cadesalaberry** [comment]
Yes, I ended up using both simultaneously.

Thanks for your suggestions !
