### ISSUE TITLE
[HDPI] CheckListBox with multi-items is not scaled well

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#1522]
* .NET Core Version: 3.0.100-preview8-013334
* Have you experienced this same bug with .NET Framework?: Yes

**Repro Steps:**
1. Set Windows DPI as 100%, then create a Winforms .Net Core application
2. Add CheckListBox control to form designer, and add 4 lines items to this control, ensure all items are shown without scrollbar and no extra empty line --- use .Net framework app designer code to workaround since .net core designer is not fully supported so far
3. In program.cs file, add one code line to support HDPI: SystemAware mode:
          Application.SetHighDpiMode(HighDpiMode.SystemAware);
4. Build and run this application 
5. Set Windows DPI as 300%, and run this application again

**Actual behavior:** 
On 300%DPI, CheckListBox is not scaled well, there has one extra empty line shown. This issue also repro in 150%, 250%DPI.
![image](https://user-images.githubusercontent.com/26474449/62038152-0fd9cf00-b1aa-11e9-80e9-3760170b84b6.png)

**Expected behavior:**
On 300%DPI, it should have 4 lines items shown on form designer in runtime, as same as 100%DPI
Here is the 100% screenshot
![image](https://user-images.githubusercontent.com/26474449/62038091-f042a680-b1a9-11e9-80b8-f68b975e2ec1.png)

**Comment by vladimir-krestov** [comment]
Hi @Vino-Wang, could you please check this point? I guess CheckListBox works well now.

Result:
![yUpL1B5L5k](https://user-images.githubusercontent.com/49272759/69978373-65016500-153d-11ea-9a98-f79bacb43386.gif)

Environment:
- .NET Core SDK [5.0.100-alpha1-015748]
- Microsoft Windows [Version 10.0.18363.476]

**Comment by RussKie** [comment]
⚠️ We are currently blocked from flowing through to .NET5 setup (https://github.com/dotnet/wpf/pull/2118), so there only way to test this would be via private binaries.

**Comment by dreddy-work** [comment]
@Olina-Zhang , if this doesn't repro in latest , please close it.

**Comment by kirsan31** [comment]
Can't repro this with .net 5.0.3. on Win10 20H2.

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang , if this doesn't repro in latest , please close it.

It also cannot repro in the latest 6.0 SDK build.
