### ISSUE TITLE
WinForm RichTextBox SelectionChanged event fails when set SelectionFont

### ISSUE THREAD

**Issue by KaneLeung** [dotnet/winforms#1544]
* .NET Core Version:3.0.100-preview7-012821
* Have you experienced this same bug with .NET Framework?: No

**Problem description:WinForm RichTextBox SelectionChanged event fails when set SelectionFont

**Actual behavior:** 

**Expected behavior:**

**Minimal [repro:RichTextboxBugTest](https://github.com/KaneLeung/RichTextboxBugTest)

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team try to repro this and see if there is a workaround.
@KaneLeung what OS are you running this on?

**Comment by Amy-Li02** [comment]
@merriemcgaw Verified this issue with Win10 RS6 + latest .NET Core 3.0.100-preview8-013624 from release branch, this issue can repro. But in Win10 RS6 + latest .NET 4.8.03947 from NetFxDev1 branch, this issue cannot repro. 
Hope it can serve as a **workaround**: Set SelectionFont in SelectionChanged event of RichTextBox.

**Comment by KaneLeung** [comment]
My OS is Win10 home 1803 17134.829 and .NET Framework version is 4.7.2,thanks.

**Comment by merriemcgaw** [comment]
@dreddy-work - did we do a RichTextBox change in 4.8 that still needs to be ported?

**Comment by RussKie** [comment]
@Amy-Li02 could you please check if the issue still repros on the latest 3.0?
I have tried it locally against release/3.0 branch and I could not repro it.

**Comment by Amy-Li02** [comment]
@RussKie Verified this issue with latest .NET Core 3.1.100-preview2-014473 from release branch & .NET Core 3.0.100-rc1-014190, this issue all cannot repro.

@KaneLeung could you please verify if the issue has been resolved on the latest 3.0?

**Comment by KaneLeung** [comment]
I have tried it in Win10 1909 Home Edition + .Net Core 3.0.100 ,this issue cannot repro.Thanks a lot.
