### ISSUE TITLE
System.Windows.Forms and S.W.F.Design should test round trip between framework versions

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#1549]
Existing tests verify:
1. integration scenarios where resources that are generated on .Net framework are read on Core
2. test for presence of Serializable attribute on the known types and only on the known types
3. roundtrip within Core 3.0 and compare resulting blob against .Net

The missing test is to deserialize hardcoded Core content on  .Net Framework.
The existing round-trip test should be extracted into a new multi-targeted assembly and tests should run once on Core and once on .Net. Similar issue will be applicable when we have multiple version of Core framework

**Comment by JeremyKuhne** [comment]
The `BinaryFormatter` work and tests is giving us additional coverage. The risk is low that we'll break serializing for .NET Framework so this isn't worth pursuing.
