### ISSUE TITLE
Referencing mshtml.dll in a .NET Core 3 WinForms project

### ISSUE THREAD

**Issue by MatthewBeardmore** [dotnet/winforms#1559]
* .NET Core Version: 3.0 Preview 7
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

I am having an issue with adding Microsoft.mshtml to my converted (net471) .NET Core 3 project.  With .NET Framework, I was able to go into Reference Manager -> Assemblies tab -> Extensions sub tab, then find Microsoft.mshtml. ![Capture](https://user-images.githubusercontent.com/808932/62386440-d98fad00-b525-11e9-8fc4-66706d773fb7.PNG) As the assemblies tab does not exist in .NET Core 3 projects, I looked for a package on NuGet, but was unable to find anything from Microsoft (I tried https://www.nuget.org/packages/Unofficial.Microsoft.mshtml/, which compiles, but fails at runtime).

**Actual behavior:** 
Expect to be able to find a NuGet package (or another manner of adding the reference) for Microsoft.mshtml.

**Expected behavior:**
Unable to find a way to add Microsoft.mshtml to a .NET Core 3 application.

**Minimal repro:**
N/A.

**Comment by merriemcgaw** [comment]
Can you tell us a bit more about your scenario? Perhaps we can find some existing options.

**Comment by MatthewBeardmore** [comment]
I am attempting to add events on a WinForms WebBrowser to attach to mouse wheel events, which isn't possible via the normal C# WebBrowser events. So in the past with .NET Framework, I'd do something like the following:

mshtml.HTMLDocumentEvents2_Event docEvents = (mshtml.HTMLDocumentEvents2_Event)webBrowser.Document.DomDocument;
docEvents.onmousewheel += docEvents_onmousewheel;

to attach to any events I needed to hook into. Since I can't reference Microsoft.mshtml (or can't find out how to reference it), I am unable to do so.

**Comment by r-aghaei** [comment]
@MatthewBeardmore You can use [`tlbimp.exe`](https://docs.microsoft.com/en-us/dotnet/framework/tools/tlbimp-exe-type-library-importer) to export the type definitions of `mshtml.tlb` into equivalent definitions in .net assembly.
Then add a reference to the exported dll and in Visual Studio, in the properties of the reference, set `Embed Interop Types` to `Yes`.

I've shared all the steps here in this post: [Use COM type libraries in .NET CORE Windows Forms Project](http://www.reza-aghaei.com/use-com-type-libraries-in-net-core-windows-forms-project/)

**Comment by MatthewBeardmore** [comment]
Thanks for the writeup - that is super useful.

**Comment by RussKie** [comment]
@MatthewBeardmore in the original screenshot there is COM tab. 
Is there a reason you can't use it?

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/62960878-519e8280-be04-11e9-94da-c2945e9f1a58.png)


I think this is the same COM object as you get by running tlbimp.

**Comment by r-aghaei** [comment]
This is how I get *Reference Manager* window when I try to add reference to a .NET Core Class Library or Windows Forms project in VS 2019 16.2.1:

![ReferenceManager](https://user-images.githubusercontent.com/25272166/62961296-15cce280-be2f-11e9-8b69-934aedfda8a2.png)

@RussKie Which version of VS/NET Core/Project Template does the screenshot belongs to?

**Comment by RussKie** [comment]
I'm on an internal build, so I presume you will get the same functionality in the next version of VS.

**Comment by MatthewBeardmore** [comment]
@r-aghaei  You need VS 2019 16.3 preview to get the COM menu with .NET Core 3 projects I believe.

@RussKie You are correct. I saw that, tried it, and moved on as it didn't have the same namespace. The one that I had added in the .NET Framework picture added the namespace as "mshtml", while the one you showed adds it as "MSHTML". We can close this as it just requires modifying the namespace.
