### ISSUE TITLE
Adding new field to CloseReason Enum

### ISSUE THREAD

**Issue by AlexYurkin** [dotnet/winforms#1570]
Link to article:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.closereason?redirectedfrom=MSDN&view=netframework-4.8

Problem:
When you describe the fields of this Enumeration you state that the 'UserClosing' happens when: "The user is closing the form through the user interface (UI)". But this also happens when you use 'Close' method for a form in your code.
It would be great to distinguish the UI Closing from the code closing. 

Link to previous conversation about this issue: https://github.com/dotnet/dotnet-api-docs/issues/2844

**Comment by merriemcgaw** [comment]
We're past the point where we can add this for 3.0/3.1 so I'm putting it in 5.0. This is an interesting idea to consider.

**Comment by dreddy-work** [comment]
@AlexYurkin, apologize for the delayed response here but given that doc is updated to account for this difference, Is there a use case that make this suggestion to be prioritized?

**Comment by dreddy-work** [comment]
Thanks @AlexYurkin for this proposal. Given documentation is updated to include this event and have not seen any business case here, we will be closing this proposal as low pri.
