### ISSUE TITLE
Consider enabling some xunit analyzers

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/winforms#1577]
We have done this in corefx and it's helped find some incorrect use of asserts and xunit attributes. Might be something the community is interested in doing - enabling one rule at a time as we have been doing.

original change https://github.com/dotnet/corefx/pull/38676
subsequent enablings https://github.com/dotnet/corefx/commits/master/src/CodeAnalysis.ruleset
more pending https://github.com/dotnet/corefx/pull/40079

**Comment by RussKie** [comment]
Thank you Dan.

We have the analysers installed:
![image](https://user-images.githubusercontent.com/4403806/62952596-a3d7a780-bdf4-11e9-8be2-181c728446f8.png)

I assume we have them enabled by default as we have no suppressions for them. I tried writing some "bad" code and it triggered the analysers.

Please let me know, if there is more to do.
Closing for now.
