### ISSUE TITLE
Linux 3.0 issue

### ISSUE THREAD

**Issue by navneetccna** [dotnet/winforms#159]
* .NET Core Version: 3.0 Preview1
* Have you experienced this same bug with .NET Framework?: Yes/No
No

**Problem description:**
I am running 3.0 winform application on linux with following command
dotnet run
But getting error

/home/owner/dotnet/sdk/3.0.100-preview-009812/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.NET.Sdk.WindowsDesktop.targets(14,2): error MSB4019: The imported project "/home/owner/dotnet/sdk/3.0.100-preview-009812/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.WinFX.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/home/owner/projects/dotnet3/dotnet3.csproj]

The build failed. Please fix the build errors and run again.

I checked my path variable as well as the Microsoft.WinFX.targets exist in the path

**Comment by KlausLoeffelmann** [comment]
Hey @navneetccna,

as stated in the [README](https://github.com/dotnet/winforms/blob/master/README.md), WinForms is not supported on other OS than Windows.

Klaus

**Comment by raffaeler** [comment]
I would also add the [contributing guide](https://github.com/dotnet/winforms/blob/master/Documentation/contributing.md):
```
For example, we do not intend to create an implementation of the Windows registry for Linux or an implementation of the macOS keychain for Windows. We also do not intend to accept contributions that provide cross-platform implementations for Windows Forms or WPF.
```

**Comment by navneetccna** [comment]
Oh, that is very sad. I though .net core 3.0 provide cross platform implementation for windows application as well

**Comment by raffaeler** [comment]
@navneetccna This project is just the original winforms project which has been released open source. Porting it cross platform would be a (very big) new feature.
Any UI platform have direct dependencies on the OS, as there are no common standards defined for windowing.

I can imagine that before or later someone will fork this project and "transplant" it to Wine as it was done many years ago on Mono.

**Comment by navneetccna** [comment]
I can understand the pain of the cross platform dependencies. So we still need to use need to  JAVAFX or QT5 for cross platform windows application.

**Comment by raffaeler** [comment]
@navneetccna there are for sure multiple strategies to do that, but this is clearly not the goal of this repository. And IMHO for good and understandable reasons.

**Comment by navneetccna** [comment]
Thanks for prompt response. Hope some day dotnet provide cross platform solution as well.

**Comment by RogerHardiman** [comment]
I would direct users to the Mono project and the WINE project. Both offer a WinForms emulation for Linux and MacOS. It was written years ago and us mostly complete.

**Comment by KamranShahid** [comment]
Very Disappointing to understand this. Were thinking that .net core 3.0 support for winform/wpf will resolve cross platform development desktop app in .net.
It's seem no use to even touch winform in .net core 3.0 as old .net framework base WPF and winform are quite matured

**Comment by Rombersoft** [comment]
Windows is dead. I like Linux
