### ISSUE TITLE
Update templates to set DPI Awareness to System Aware by default

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#1593]
.NET Core apps are more likely than not to run on more modern hardware with a higher pixel density. Given that, we should default all new apps to be System Aware. We'll update this in the templates using  `Application.SetHighDpiMode(HighDpiMode.SystemAware);` in program.cs file and the equivalent in VB.

@OliaG to make porting of apps smoother and work well in the new designer we should also update porting guides to include calling that method in Main(). 
- [x] c#
- [x] vb

**Comment by zsd4yr** [comment]
@KlausLoeffelmann is doing the vb one

**Comment by KlausLoeffelmann** [comment]
Added the VB area label since it only applies to VB now.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann getting this one back on your radar.

**Comment by KlausLoeffelmann** [comment]
Will be done in the upcoming Application Framework templates for VB.

**Comment by KlausLoeffelmann** [comment]
Will be done by #3893. Closing this.

**Comment by weltkante** [comment]
Why are issues closed before they are done? Makes tracking things hard if the PR is rejected for whatever reason ...
