### ISSUE TITLE
MenuBar checkbox color is different between .NET Core 3 and .NET Framework

### ISSUE THREAD

**Issue by MatthewBeardmore** [dotnet/winforms#1597]
* .NET Core Version: 3.0 Preview 7
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
MenuBar's MenuItem has a different color when it is checked (with no mouse hovering) between .NET Framework and .NET Core 3. The color for .NET Core 3 appears to be a bug, as I wouldn't have expected it to have the solid blue background, nor a different checkmark, as shown below.

**Actual behavior:** 
.NET Core 3:
![NetCoreApp3 0-Issue](https://user-images.githubusercontent.com/808932/62789153-57a80280-ba96-11e9-9a1f-7ca244353854.PNG)

**Expected behavior:**
.NET Framework
![Net471-NoIssue](https://user-images.githubusercontent.com/808932/62789167-61316a80-ba96-11e9-8a63-d187a3efe792.PNG)

**Minimal repro:**
[Repo.zip](https://github.com/dotnet/winforms/files/3486911/Repo.zip)

**Comment by merriemcgaw** [comment]
This is expected - we updated icons to a more modern look for .NET Core 3.

**Comment by MatthewBeardmore** [comment]
Alright, I'll go ahead an close it now. Honestly, I thought it was a mistake because of how out of place it looked. Thanks.

**Comment by mikedn** [comment]
> we updated icons to a more modern look

This is baffling. Not only that the new icon looks completely out of place with the default `ToolStrip` render style but there's absolutely nothing modern about it. If anything, this looks like something from a badly designed UI from the '90 or as a rendering bug, the kind of bug that you get when you don't handle the transparency color correctly.

**Comment by MatthewBeardmore** [comment]
It really does look like a transparency color issue, which is why I reported it in the first place.

**Comment by weltkante** [comment]
Have to agree with @mikedn, WinForms shouldn't change UI style by itself, makes it look out of place with the rest of Windows UI. In particular since WinForms is mostly about wrapping native controls. In our application we are mixing technologies and now the WinForms windows are going to stand out annoyingly compared to the native and WPF windows.

**Comment by merriemcgaw** [comment]
Thank you all for your feedback! It's absolutely appreciated and we will take another look at this particular icon. If you notice any others that look badly in the new format, please reach out. @dreddy-work please work with the UX team to find something more inline with the default MenuStrip style.

**Comment by kirsan31** [comment]
@MatthewBeardmore 
> It really does look like a transparency color issue, which is why I reported it in the first place.

I think same. It's looks different with visual styles on/off on .net core (and with v.s. off, it's look ok :)). When ,net version looks the same in both cases.
![Snipaste_2019-08-11_02-05-49](https://user-images.githubusercontent.com/17767561/62827691-140be080-bbdd-11e9-9d34-84bb3e548c72.png)

```c#
// enable visual styles (default behavior):
Application.EnableVisualStyles();
```
```c#
// disable visual styles:
Application.VisualStyleState = System.Windows.Forms.VisualStyles.VisualStyleState.NoneEnabled;
//Application.EnableVisualStyles();
```

**Comment by merriemcgaw** [comment]
This is not blocking any functionality so we're marking this as 3.1.

**Comment by MatthewBeardmore** [comment]
It isn't blocking anything, but it looks ugly and does not match the previous behavior. It also conversion to .NET Core harder as I now have to reskin these to something more appropriate, just for it to be changed again in 3.1.

**Comment by dreddy-work** [comment]
I see two opinions here.  
1. Changing Icons to match the Framework version ( legacy Icons)
2. Match the behavior when VisualStyle is ON /OFF with framework but keep the new Icon.

Will take a look if we can  match the behavior when VisualStyle is ON/OFF  with framework but try to keep new Icons. We adopted VisualStudio formats in core. @MatthewBeardmore, please respond if you disagree.

**Comment by MatthewBeardmore** [comment]
I think the new icons are fine in most places (and even in this place), but the transparency behind the VisualStyle On looks very out of place. If that was fixed, I think it would match well enough with the previous style and previous behavior that (for me) would work fine.

**Comment by MatthewBeardmore** [comment]
Thanks for investigating this further!

**Comment by dreddy-work** [comment]
Closing and PR merged.

**Comment by Zheng-Li01** [comment]
Verified this bug with .Net core 3.0.100-rc1-014190 from release branch, the issue has been fixed.

![bug](https://user-images.githubusercontent.com/38325459/64595045-bf2dd680-d3e3-11e9-9fde-5607f0a5bfd6.PNG)
