### ISSUE TITLE
Scrollable MessageBox

### ISSUE THREAD

**Issue by Gigas002** [dotnet/winforms#1600]
The problem's pretty much obvoius: sometimes standard messageboxes are just too short for the contents:

![image](https://user-images.githubusercontent.com/24297712/62801559-b13c1b80-baee-11e9-9891-7862c678944a.png)

There was already good and working solution of this problem. More info:
https://www.codeproject.com/Articles/601900/FlexibleMessageBox-A-Flexible-Replacement-for-the

The mentioned FlexibleMessageBox class works well on .NET Core 3 WinForms application, but probably that behaviour of MessageBox should be default?

**Comment by RussKie** [comment]
Thank you for the link.

It appears that in the give scenario a message box was incorrectly chosen as a medium to present the data to a user. Making a message box scrollable would not address the underlying UX issue.
Please refer to the Windows Desktop UI guidelines for messages - https://docs.microsoft.com/en-us/windows/win32/uxguide/messages

In the current scenario a progress bar (purely informational) or a list control of some kind (interactive) would be a significantly better solution.

**Comment by weltkante** [comment]
I would also like to add that WinForms merely exposes the underlying Windows MessageBox, it cannot modify the implementation. It would have to create a completely new implementation from scratch, which is a significant investment.

So besides UX considerations mentioned above any feature request has to be weighted against the required work for rewriting existing behavior from scratch, not just the work for adding the feature.
