### ISSUE TITLE
AccessViolationException with MenuStrip and VisualStyleState.NoneEnabled

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#1602]
* .NET Core Version: .NET Core Version: 3.0.0-preview7-27912-14
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
When you disable visual stiles:
```c#
            Application.VisualStyleState = System.Windows.Forms.VisualStyles.VisualStyleState.NoneEnabled;
//          Application.EnableVisualStyles();
```
The winForms mdi app with MenuStrip ans submenus are crushed with AccessViolationException, after you open sub menu and live it (move cursor out of the menu - see gif below). Windows 7 pro x64.

**Actual behavior:**

<details><summary><b>Exception, Event logs, Gif of the error</b></summary>

![nc](https://user-images.githubusercontent.com/17767561/62825179-43582880-bbb0-11e9-9f4a-52489d518be8.gif)

`AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

```
Application: WinFormsCoreTest.exe
CoreCLR Version: 4.700.19.32702
.NET Core Version: 3.0.0-preview7-27912-14
Description: The process was terminated due to an internal error in the .NET Runtime at IP 000007FEC76FA8D4 (000007FEC7540000) with exit code c0000005.
```

```
Faulting application name: WinFormsCoreTest.exe, version: 1.0.0.0, time stamp: 0x5d29536d
Faulting module name: coreclr.dll, version: 4.700.19.32702, time stamp: 0x5d155e43
Exception code: 0xc0000005
Fault offset: 0x00000000001ba8d4
Faulting process id: 0x248c
Faulting application start time: 0x01d54f9f444a10b0
Faulting application path: D:\save\projects\WinFormsCoreTest\bin\Debug\netcoreapp3.0\WinFormsCoreTest.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview7-27912-14\coreclr.dll
Report Id: b32877c1-bb92-11e9-8c38-40b0760b80f2
```
</details>

**Expected behavior:** No AccessViolationException.

**Minimal repro:** 
[WinFormsCoreTest.zip](https://github.com/dotnet/winforms/files/3489165/WinFormsCoreTest.zip)

**Comment by RussKie** [comment]
I couldn't repro it in 3.0.0-preview8-28380-08 on W10.

@olina could you please see if you can repro the issue on W7 in preview7 and preview8 releases.
Thank you

**Comment by RussKie** [comment]
I couldn't repro it in 3.0.0-preview8-28380-08 on W10.

@Olina-Zhang  could you please see if you can repro the issue on W7 in preview7 and preview8 releases.
Thank you

**Comment by kirsan31** [comment]
@RussKie It's 100% reproducible on my system with preview5 - preview7.  Where  I can get preview8 binary to try it out?

**Comment by weltkante** [comment]
I don't know how to get specific versions but there is [nightly builds](https://github.com/dotnet/core/blob/master/daily-builds.md) to get the latest available.

**Comment by Olina-Zhang** [comment]
@RussKie  I can repro this issue on Win10 machine with Preview8 release build using above attached app. Please see above gif from kirsan31, run app and do actions, then put mouse in background code, the exception pops up.

**Comment by RussKie** [comment]
Thank you, I retract my comment. I can actually reproduce it too.

**Comment by RussKie** [comment]
I did a quick investigation, here's where it fails:
![image](https://user-images.githubusercontent.com/4403806/62864241-d65da380-bd13-11e9-857f-a95c76957d6b.png)

Further investigation is required to understand the root cause.

**Comment by merriemcgaw** [comment]
@kirsan31 - can you tell us a little more about why your app needs to use the VisualStyles that you use? This will help us to figure out a priority for addressing this issue as we get so close to shipping 3.0 GA.
@JeremyKuhne - can you help @RussKie with this investigation by any chance?

**Comment by merriemcgaw** [comment]
@M-Lipin can you take a look? Callstack shows Keyboard tooltip which is suspicious that perhaps removing the quirk for Keyboard ToolTip support might have uncovered something here.

**Comment by JeremyKuhne** [comment]
I'll take a look at the defines here.

**Comment by JeremyKuhne** [comment]
I've got the repro going, I'll figure out what is going on.

**Comment by JeremyKuhne** [comment]
I'm pretty sure I know what this is. I'll update once I've finished investigating.

**Comment by JeremyKuhne** [comment]
It does, in fact, repro on 4.8 if you enable the new keyboard state machine. In the app.config you can add:

```
  <runtime>
    <AppContextSwitchOverrides value="Switch.UseLegacyAccessibilityFeatures=false;Switch.UseLegacyAccessibilityFeatures.2=false;Switch.UseLegacyAccessibilityFeatures.3=false;Switch.System.Windows.Forms.UseLegacyToolTipDisplay=false"/>
  </runtime>
```

The basic problem is that we're trying to get the size of the tooltip bubble when it isn't active. Windows unfortunately doesn't guard well here, and AVs when there isn't an active tooltip window.

We should follow up on the repro crash for 4.8. I'll tag where the specific fix is.

**Comment by RussKie** [comment]
Thank you @JeremyKuhne for the thorough investigation 👍

**Comment by weltkante** [comment]
@RussKie I'd still consider it a regression if in 4.8 it needs special app compat flags to trigger and in .NET Core the AV always happens (just mentioning it in case you overlooked that detail)

**Comment by RussKie** [comment]
@JeremyKuhne all these switches are set to `false`, are they set to `true` by default?

**Comment by kirsan31** [comment]
@merriemcgaw 

> @kirsan31 - can you tell us a little more about why your app needs to use the VisualStyles that you use? This will help us to figure out a priority for addressing this issue as we get so close to shipping 3.0 GA.

As we now know that visual stiles is not the root of the problem. But I answer your question any way.

We have several exchange trading apps. That running on the servers within exchange data-space. 
Traders connecting to them by RDP.  All were good until a new trader come in. Our apps become randomly crushes on user login to rdp. After investigation we have figure out that new trader have low internet connection and therefor he disabled visual stiles in rdp settings (all others have v.s. on).
When users connecting to rdp with different v.s. options (on/off) the app can crush with:
`System.InvalidOperationException: Visual Styles-related operation resulted in an error because no visual style is currently active.` Inside GroupBox control :)
So, to overcome this we disabled visual styles on application level.

**Comment by RussKie** [comment]
> When users connecting to rdp with different v.s. options (on/off) the app can crush with:
> `System.InvalidOperationException: Visual Styles-related operation resulted in an error because no visual style is currently active.` Inside GroupBox control :)

Can you please raise a new issue providing as much information as possible so we can address this in Core.
Thank you

**Comment by kirsan31** [comment]
@RussKie 
> Can you please raise a new issue providing as much information as possible so we can address this in Core.
I need a bit of free time for experiments on this, then I will try.

**Comment by RussKie** [comment]
No hurry, it won't make 3.0; depending on severity it may make in 3.1, but most likely won't get addressed until 5.0.

**Comment by Jessie-Zhang01** [comment]
Verified this bug in .Net Core SDK 3.0.100-Preview 9-13959 build from release branch. This bug is fixed. Please see following screenshot:
![image](https://user-images.githubusercontent.com/45864649/63499634-cf484980-c4fa-11e9-883b-43aa228b39fb.png)

**Comment by RussKie** [comment]
Thank you @Jessie-Zhang01
