### ISSUE TITLE
Accessibility: [High Contrast] - Tooltips are not enough contrasted in HC mode

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#1615]
.NET Core Version: 3.0.100 Preview8 13316 from master branch
Have you experienced this same bug with .NET Framework?: Yes.

**Repro Steps:**
Open control panel and select the respective high contrast theme.
Create WinForms application with some control and add tooltip for this, build and run the app.
Mouse-over the control and wait until ToolTip appears.

**Actual:**
Tooltip is not enough contrasted and its color theme differs from Explorer's Tooltip color theme:

![image](https://user-images.githubusercontent.com/23213980/62955258-675a7a80-bdf9-11e9-9fde-c3d6798a90c5.png)

**Expected:**
Tooltip background and foreground colors should have maximum contrast in HC mode:
![image](https://user-images.githubusercontent.com/23213980/62955398-ac7eac80-bdf9-11e9-8e12-5ee4d8852d93.png)

**Comment by Zheng-Li01** [comment]
Verified this bug with .Net core 3.0.100-rc1-014190 from release branch, the issue has been fixed.
![bug](https://user-images.githubusercontent.com/38325459/64594019-c522b800-d3e1-11e9-814f-3203ff81c862.PNG)
