### ISSUE TITLE
Port Microsoft.VisualBasic.{ApplicationServices,Devices,MyServices}

### ISSUE THREAD

**Issue by cston** [dotnet/winforms#1632]
dotnet/winforms should generate a Microsoft.VisualBasic.dll assembly that contains the types from the VB runtime that have dependencies on System.Windows.Forms. (The remaining types from VB runtime that do not depend on System.Windows.Forms should be type-forwarded to Microsoft.VisualBasic.Core.dll from dotnet/corefx.)

The types in the namespaces Microsoft.VisualBasic.{ApplicationServices,Devices,MyServices} generally depend on System.Windows.Forms and should be ported to the dotnet/winforms Microsoft.VisualBasic.dll assembly.

See https://github.com/dotnet/corefx/pull/39972 for related issue.
See https://github.com/Microsoft/referencesource/tree/master/Microsoft.VisualBasic/runtime/msvbalib for the reference source.

**Comment by zsd4yr** [comment]
@cston please be more verbose? What is the work to be done here?

**Comment by cston** [comment]
@zsd4yr, I've updated the description.
