### ISSUE TITLE
Investigate if FolderBrowserDialog.AutoUpgradeEnabled property is obsolete on win7+

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#1643]
* .NET Core Version: 3.0
* Have you experienced this same bug with .NET Framework?: N/A

As far as I understand, this property auto-upgrades the XP dialog to the Vista dialog. We need to double check if this is relevant on the OSs that Core ships on.
Once this is understood, we need to update the docs - https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/FolderBrowserDialog.xml and consider making this property obsolete.

Supported OSs: https://github.com/dotnet/core/blob/master/release-notes/3.0/3.0-supported-os.md

OS | Version | Architectures | Notes
-- | -- | -- | --
Windows Client | 7 SP1+, 8.1 | x64, x86 |  
Windows 10 Client | Version 1607+ | x64, x86 |  
Nano Server | Version 1803+ | x64, ARM32 |  
Windows Server | 2012 R2 SP1+ | x64, x86 |

**Comment by RussKie** [comment]
Related https://github.com/dotnet/winforms/issues/1640
