### ISSUE TITLE
Resource file: Form1.resx in Winforms .Net Core project is missing

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#1665]
* .NET Core Version: (.Net Core SDK 3.0.100.13959 build from release branch)
* Have you experienced this same bug with .NET Framework?: No

**Steps to reproduce:**

1. Install latest .NET Core 3.0 SDK Preview 9 from release branch by link: https://github.com/dotnet/core-sdk.
2. Create a new Windows Forms App(.NET Core), then expand the Form1.cs.

**Actual:**
Resource file: Form1.resx in .Net Core project is missing.
![image](https://user-images.githubusercontent.com/45864649/63328544-ece2ab00-c362-11e9-8ab5-4844dc48765b.png)

**Expected:**
Resource file: Form1.resx exists under Form1.cs node in .Net Core project.
![image](https://user-images.githubusercontent.com/45864649/63328474-cf154600-c362-11e9-8871-861c517bf1ec.png)

**Comment by weltkante** [comment]
This is intentionally removed (see #1479) because it is not used by the template. It is a designer generated file which will be generated automatically if required. Deploying an empty file by default through the template makes not much sense.

**Comment by RussKie** [comment]
Resx's were removed in https://github.com/dotnet/winforms/pull/1573
