### ISSUE TITLE
remove ` /// <include file='` an `///<internalonly/>` comments

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#167]
Comments like the following are no longer used:

 `  /// <internalonly />`

`/// <include file='doc\SystemInformation.uex' path='docs/doc[@for="SystemInformation.TerminalServerSession"]/*' />`

**Comment by hughbe** [comment]
Internal only now gone. Include file gone in https://github.com/dotnet/winforms/pull/938
