### ISSUE TITLE
[Keyboard][Accessibility]: WinForm DataGridView's CellErrorTextNeeded tooltip data isn't accessible to customers only using the keyboard

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#1680]
* .NET Core Version: 3.0.100-preview9-013722
* Have you experienced this same bug with .NET Framework?: Yes

**Original bug:**
- [Bug 528682:](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/528682) Accessibility: WinForm DataGridView's CellErrorTextNeeded tooltip data isn't accessible to customers only using the keyboard

**Problem description:**
- A user can't get a tooltip text or tooltip error text of DataGridView cell when he/she navigates with only a keyboard
- There is no way to activate a tooltip using Control+Shift+F10 hotkeys (like as WPF hotkeys)

**Actual behavior:** 
- There is no way to activate a tooltip using a keyboard

**Expected behavior:**
- A cell activates a tooltip when getting a keyboard focus (It may turn on/off)
- Control+Shift+F10 hotkeys activate/deactivate a cell tooltip 

**Minimal repro:**
- Create .Net Core test app
- Add a DataGridView control
- Add cells to the DataGridView
- Implement CellErrorTextNeeded event handling
- Run the app and try to get a cell tooltip with using a keyboard (Tab/arrow navigation, hotkeys)

**Comment by Lydia-Shi** [comment]
Verified this bug with .Net core 3.0.100-rc1-014190 from release branch, the issue has been fixed.  Get a tooltip text or tooltip error text of DataGridView cell successfully when navigates with only using a keyboard, like below gif:
![toolTip](https://user-images.githubusercontent.com/54019172/65830249-61a0f180-e2e0-11e9-898f-7813bd3c1bc0.gif)

**Comment by merriemcgaw** [comment]
Closing as fixed. Thanks all!

**Comment by merriemcgaw** [comment]
mention the behavior change noticed in #2048

**Comment by RussKie** [comment]
Documented in https://github.com/dotnet/docs/issues/15361
