### ISSUE TITLE
[Accessibility]: The AccessibleName property of a ToolStripComboBox edit element is null.

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#1691]
* .NET Core Version: 3.0.100-rc1-014015
* Have you experienced this same bug with .NET Framework?: Yes

**Original bug:**
- [Bug 956710:](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/956710) ToolbarStripContainer: (CoreTesting/edit '') The Name property of a focusable element must not be null.

**Problem description:**
- ToolStripComboBox edit element has an incorrect AccessibleName property value.

**Actual behavior:** 
The AccessibleName property of a ToolStripComboBox edit element is null.
![image](https://user-images.githubusercontent.com/49272759/63685108-33268700-c807-11e9-964c-2cfd5616ed39.png)

**Expected behavior:**
The AccessibleName property of a ToolStripComboBox edit element must not be null
![image](https://user-images.githubusercontent.com/49272759/63685307-a5976700-c807-11e9-9cdf-5b9bc4996c8a.png)

**Minimal repro:**

1. Create .Net Core app
2. Add ToolStrip/MenuStrip to the app
3. Add a ComboBox item to the menu
4. Run the app and check ComboBox edit element AccessibleName using Inspect tool

**Comment by Vino-Wang** [comment]
Verified with .NET Core 3.0 RC1 build 3.0.100-rc1-014190, this issue is fixed now. So close it.

Fixed:
![Fixed](https://user-images.githubusercontent.com/18568603/64598689-b8ef2880-d3ea-11e9-9086-9f55f61e45d5.png)
