### ISSUE TITLE
Remove VB WinForms templates from .NET Core 3.0

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/winforms#1698]
Remove VB WinForms templates because .NET Core 3.0 has limited support for Visual Basic.NET WinForms and it is not currently possible to build apps in the Visual Basic.NET WinForms style (ApplicationBase classes are not available at this time).

**Comment by RussKie** [comment]
/cc: @cston 

I suppose https://github.com/dotnet/winforms/pull/1675 will now be targeting 5.0

**Comment by prayaas-a** [comment]
So is VB support planned only for 5.0 or could we be seeing it in 3.1?

**Comment by merriemcgaw** [comment]
@KathleenDollard what can you share about our VB plans?
