### ISSUE TITLE
Accessibility: DataGridView cell of type ComboBox must support the ExpandCollapse pattern

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#1703]
DataGridView ComboBoxCell has ComboBox control type. UI elements which have ComboBox control type in corresponding accessibility property should provide ExpandCollapse pattern and all related functionality.

DevDiv issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/956708

**Comment by Vino-Wang** [comment]
Verified with .NET Core 3.0 GA build, this issue is fixed now.

After:
![Fixed](https://user-images.githubusercontent.com/18568603/65021498-cfa0fc80-d961-11e9-9a27-9969c4121b76.png)
