### ISSUE TITLE
Accessibility: PropertyGridView should support Table and Grid accessibility patterns

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#1705]
PropertyGridView element of the PropertyGrid control has Table control type (control type accessibility property) but does not provide Table and Grid accessibility patterns and related properties (information about rows, columns and so on).

**Comment by Lydia-Shi** [comment]
Verified this bug with .NET Core Version: (3.0.100-rc2-14256) from Release/3.0.1XX branch. This bug is fixed. As below screenshot:
![image](https://user-images.githubusercontent.com/54019172/65028100-13016800-d96e-11e9-88a1-9c64b95de9ed.png)
