### ISSUE TITLE
Enable lazy loading for tree view

### ISSUE THREAD

**Issue by Joelius300** [dotnet/winforms#1712]
Will there ever be support for lazy loading in `TreeView`?  

I have tried to implement it myself by extending `TreeNode` but I wasn't successful because `Nodes` isn't marked as `virtual`. I'm no expert so I don't want to say anything wrong but wouldn't this be a rather small change?  
The backing field would be null if the nodes aren't loaded yet and on the first access you could execute the passed in `Func<TreeNode>` which will load the nodes. This also wouldn't interfere with just directly adding them without any lazy loading since you could just pass the nodes directly instead of the delegate.  
Some more things to do would be: 
- in `TreeView` you'd still have to show the plus-sign when `Nodes` is null but the node-selector isn't (change in other class)
- `GetNodeCount` would have to either throw or load the nodes (decision)

Again, I'm not qualified to tell you what you should change at all and I've probably also missed a lot of important points but I like to throw everything out there that I think might help.  

Is there any interest of extending `TreeView` to make it more performant? It's really slow when you want to visualize the whole C-drive for example.

**Comment by mikedn** [comment]
> Is there any interest of extending TreeView to make it more performant? It's really slow when you want to visualize the whole C-drive for example

Traditionally this is done by adding a dummy child node to folder nodes and then replacing it with actual nodes in the `BeforeExpand` event. It may not be the most elegant way to do this but it works pretty well in practice and AFAIR the underlying Win32 TreeView control doesn't have any kind of lazy loading functionality, apart perhaps from retrieving the node text/image on the fly.

**Comment by weltkante** [comment]
@Joelius300: WinForms is only a wrapper around native win32 controls, in most cases WinForms does not implement the control itself. As such improvements are very limited, short of rewriting the entire control.

Setting @mikedn s answer a bit in relation, having an event which fires when the node is expanded but before its children are evaluated is pretty much all that is to virtualization or lazy loading. At this point you could just argue about naming and the form of the API, you don't get any big architectural improvements.

> It's really slow when you want to visualize the whole C-drive for example.

The usual answer will be, it depends on what you want to do whether it is the right control. If you want to show the whole drive in an expanded tree, no, the TreeView isn't the right control in the first place. If you want to expand dynamically like explorer does, lazy loading as the nodes are expanding is probably going to be fine.

**Comment by mikedn** [comment]
> lazy loading as the nodes are expanding is probably going to be fine.

Of course, after the explorer itself uses the same Win32 TreeView control :smile:

**Comment by Joelius300** [comment]
Thank you, I think that's enough information. I knew about doing it manually and I didn't think about the underlying implementation so that's solved :)  

I'll close the issue and implement it with the event.
