### ISSUE TITLE
ListView headers are not keyboard-accessible

### ISSUE THREAD

**Issue by ChrisSires** [dotnet/winforms#1726]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes/No
.Net Framework 4.7.2

**Problem description:**
The ListView control contains column headers that can be clicked in order to perform sort actions on its contents.  There is currently no way to navigate through those column headers using a keyboard, nor can they be activated using a keyboard.  

**Actual behavior:** 
Non-keyboard-accessible column headers in ListView objects

**Expected behavior:**
ListViews should support basic accessibility guidelines such as keyboard navigability.

**Minimal repro:**

[Form1.cs.txt](https://github.com/dotnet/winforms/files/3557703/Form1.cs.txt)
[Form1.Designer.cs.txt](https://github.com/dotnet/winforms/files/3557704/Form1.Designer.cs.txt)

**Comment by hughbe** [comment]
Related #2654

**Comment by RussKie** [comment]
ListView footers will need to be made accessible as well (see #2653)

**Comment by RussKie** [comment]
This is a bug in the underlying ComCtl32 library, https://microsoft.visualstudio.com/OS/_workitems/edit/12191319.
If/when DEP team fixes this bug we don't have a competing fix in our codebase.
