### ISSUE TITLE
WinForms designer throws InvalidCastException on save

### ISSUE THREAD

**Issue by wjk** [dotnet/winforms#1744]
* .NET Core Version: 3.0.100-preview9-013709
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**

When I put a control on a form in the VS Windows Forms designer and try to save the file, I get a dialog saying "The specified cast is not valid". I cannot successfully save any form with a control on it, ever. Due to #147, this only applies to the .NET Framework version of Windows Forms, as the .NET Core version doesn't support the designer yet. However, I suspect that even if the .NET Core designer worked, I would still run into this problem.

**Actual behavior:**

I get a dialog saying "The specified cast is not valid" whenever I try to save a form that has a control on it.

**Expected behavior:**

I am able to save my changes!

**Minimal repro:**

1. Install VS 16.3.0 Preview 2.0. (This is the version I am currently using; though IIRC this problem also occurred on 16.2.1.)
2. `dotnet new winforms -o reprotest`; open reprotest.sln
3. Retarget to net45 (to enable Designer support)
4. Open Form1.cs in the Designer, place a button on the form.
5. Attempt to save the form, and observe the error dialog.

**Comment by kirsan31** [comment]
Yea, was reported [here](https://github.com/dotnet/winforms/issues/147#issuecomment-520120591), but no answer...

**Comment by RussKie** [comment]
> 3\. Retarget to net45 (to enable Designer support)

How do you retarget?

**Comment by kirsan31** [comment]
@RussKie 
As was mentioned [here](https://github.com/dotnet/winforms/issues/147#issuecomment-520164079), I did it exactly as in [Option 1](https://github.com/dotnet/winforms/blob/master/Documentation/winforms-designer.md).

**Comment by RussKie** [comment]
Do you have a resx file?

**Comment by RussKie** [comment]
I just followed the Option 1, and our docs were outdated - we have removed a default resx from the template in Preview9. A resx is generated by the designer after a first design change.

To fix your issue you only need to add the following to the csproj file:
```xml
 <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
   <Compile Update="Form1.cs">
     <SubType>Form</SubType>
   </Compile>
   <Compile Update="Form1.Designer.cs">
     <DependentUpon>Form1.cs</DependentUpon>
   </Compile>
 </ItemGroup>
```

I have updated the docs.

**Comment by kirsan31** [comment]
> Do you have a resx file?

Yes, and I have done 3. this step (_Add for any and every form file you have in this ItemGroup_).
Same error with or without step 3.

------Upd------
Will try without _resx_...

**Comment by kirsan31** [comment]
@RussKie 
> I just followed the Option 1, and our docs were outdated - we have removed a default resx from the template in Preview9. A resx is generated by the designer after a first design change.

Dose it mean that this workaround will work only in Preview9?

**Comment by RussKie** [comment]
> Dose it mean that this workaround will work only in Preview9?

It should work for earliers too, but I don't have them available to test.

**Comment by kirsan31** [comment]
Not working (with or without _resx_) with Preview7 and VS 16.2.3.
![image](https://user-images.githubusercontent.com/17767561/64156369-4d7ee700-ce3d-11e9-9fa0-fa0cb5228a10.png)

**Comment by RussKie** [comment]
I followed the steps in the guide:
![designe-resx](https://user-images.githubusercontent.com/4403806/64157356-435de800-ce3f-11e9-993c-133622e6c088.gif)

I further discovered that adding each form isn't necessary (at least not in Preview9):
![designe-resx2](https://user-images.githubusercontent.com/4403806/64158514-4b1e8c00-ce41-11e9-80b4-71b66bc811ec.gif)

NB: you will have to restart the IDE if modify the target framework.

**Comment by kirsan31** [comment]
@RussKie 
It's good news.  What VS version you using? it's 100% not working (new project from scratch as in your post) on 16.2.3 and Preview7.
Overall, I think we need to wait until Preview9 released...

**Comment by weltkante** [comment]
@kirsan31 you can install a [nightly build](https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries) if you don't want to wait

**Comment by RussKie** [comment]
Thank you Tobias, I was looking for that link 👍

**Comment by kirsan31** [comment]
Not working with Preview9 on VS 16.2.3. So I think VS version is the case...
