### ISSUE TITLE
`PictureBox` to use `HttpClient` instead of using `WebRequest`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1756]
* .NET Core Version: 3.0 

**Problem description:**

`PictureBox` uses an instance of `WebRequest` to load images. 
It needs to be replaces with a cached instance of `HttpClient` as suggest in https://github.com/dotnet/winforms/pull/1696#discussion_r320565246

**Expected behavior:**

**Minimal repro:**

https://github.com/dotnet/winforms/blob/release/3.0/src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs#L558-L564

**Comment by flerka** [comment]
@neldridg @RussKie is it still available? May I take it?

**Comment by RussKie** [comment]
@flerka it is still up for grabs, so you're welcome to have a go at it.
You may find discussions in #1952 useful.
Thank you

**Comment by kant2002** [comment]
@RussKie I see value for ILLink/NativeAOT scenario to be able to disable reading data from the web streams. I agree that this feature allow load data from URLs but this feature bring additional dependency which may be not wanted. Is it possible to put this feature (loading images from remote addresses) behind AppContext switche similar to how it is proposed here https://github.com/dotnet/aspnetcore/issues/31561#issuecomment-826619909 
I hope that allow to have WinForms to be more pay for play

**Comment by RussKie** [comment]
> Is it possible to put this feature (loading images from remote addresses) behind AppContext switche similar to how it is proposed here [dotnet/aspnetcore#31561 (comment)](https://github.com/dotnet/aspnetcore/issues/31561#issuecomment-826619909)

We can certainly consider this.
If you have any deeper thoughts on this subject and proposals - please feel free to share. We also accept pull requests ;)
