### ISSUE TITLE
System.ComponentModel.Design.CollectionEditor is missing in preview 1

### ISSUE THREAD

**Issue by lextm** [dotnet/winforms#177]
It is a commonly used type when WinForms PropertyGrid control is in use, as custom collection editor is needed to edit custom collection types.

It is not yet available in .NET Core 3.0 Preview 1.

**Comment by jnm2** [comment]
See https://github.com/dotnet/core-sdk/issues/79#issuecomment-422492997 for an in-depth explanation of why we need to ship these types for our end users to use at runtime.

**Comment by merriemcgaw** [comment]
@dreddy-work, can you please take a look?

**Comment by damageboy** [comment]
Same here...
Trying to test our WinForms stuff in .NET Core 3.0 and hitting up on these missing APIs as part of property-grid related runtime support.

In my case the missing types are:
* `CollectionEditor`
* `ObjectSelectorEditor`

**Comment by dreddy-work** [comment]
Sure. Editors were ported as prioritized. We will get these ported as soon as possible.

**Comment by zsd4yr** [comment]
@AmalRajUmapathySelvam ported on new master; please allow a few days for this to propagate to the SDK at https://github.com/dotnet/core-sdk/#installers-and-binaries
