### ISSUE TITLE
update codegen naming rules to be complaint with current guidelines

### ISSUE THREAD

**Issue by Varorbc** [dotnet/winforms#178]
When I double-click a button on the form, vs automatically adds a click method, such as `button1_click`, but this naming is currently suggested and is not meet specifications.

**Comment by jnm2** [comment]
Duplicate of https://github.com/dotnet/roslyn/issues/20999?

**Comment by zsd4yr** [comment]
@Tanya-Solyanik is this code gen? Does this live in the runtime?

**Comment by KlausLoeffelmann** [comment]
It is related to the Classic Framework Designer, I assume

**Comment by zsd4yr** [comment]
@klausloeffelmann does code gen live in design time? I think it isn’t in the runtime

**Comment by KlausLoeffelmann** [comment]
The CodeDomSerializer lives in the Core runtime, I think, but is triggered by the designtime, but Tanya should confirm.

**Comment by zsd4yr** [comment]
perhaps @JuditRose could take this issue on? It sounds familiar

**Comment by Tanya-Solyanik** [comment]
Duplicate of an issue from Developer community:
https://developercommunity.visualstudio.com/content/problem/286625/naming-rule-violation-these-words-must-begin-with-1.html
Please monitor status there.
