### ISSUE TITLE
We need tests for calling COM interface methods from c++

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#1817]
We need tests for various interfaces implemented by managed classes (e.g. IOleControlSite etc)

The best way to test this would be to implement tests in c++ and PInvoke them passing the managed class as an interface as an a IntPtr to unmanaged code. We’d then call functions from c++ and test things like HRESULTS etc

I have a prototype but not sure how to integrate a test c++ dll  into the product infrastructure

**Comment by JeremyKuhne** [comment]
We can and now do this in-situ by leveraging the `ComHelpers` class and direct native access through our CsWin32 generated COM structs.
