### ISSUE TITLE
Port accessibility fixes from framework runtime to core runtime 

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#182]

**Comment by zsd4yr** [comment]
@bryukov @M-Lipin Would you guys mind creating a check-list here so that the community can track on-going work on these ports?

**Comment by M-Lipin** [comment]
https://github.com/dotnet/winforms/pull/400 includes the following fixes:
* Announcing the ComboBox selected value changes without expanding/collapsing drop-down list.
* Announcing DataGridView cell navigation and DataGridView editing control input's state and expanding/collapsing actions.
* Updated accessible hierarchy tree of PropertyGrid control: all editing controls are the children of corresponding property items and all items are the children of corresponding categories if PropertyGrid is in Category view.

**Comment by M-Lipin** [comment]
#180 includes the following fixes:
* Keyboard tooltips fixes - user can see the control tooltip when navigating using keyboard.
* Showing keyboard tooltip for the menu items even if there is no ToolTip property for the parent control.
* Setting the ToolTip for the control (via SetToolTip) does not lead to throwing NullReferenceException.
* Navigating the strip controls (ToolStrip, MenuStrip) with accessibility client app or Inspect does not lead to throwing NonComVisibleBaseClass exception.

**Comment by M-Lipin** [comment]
Need to port the fixes related to accessibility changes in the Chart controls.

**Comment by M-Lipin** [comment]
Ported the changes related to Chart control accessibility: please see the issue in DataVisualization repo.

**Comment by merriemcgaw** [comment]
@M-Lipin are there any other Accessibility fixes that need porting? If not, please feel free to close this issue and thanks for all the ports!!

**Comment by merriemcgaw** [comment]
@M-Lipin Can I close this issue?

**Comment by zsd4yr** [comment]
dotnet/winforms-datavisualization#6
