### ISSUE TITLE
Two nodes  ‘WPF’ and ‘.NET Core’ are missing on C# winforms core application

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/winforms#1822]
* .NET Core Version: .NET Core 3.0.100-rc1-014181
* VS: 16.4.0 Preview1.0 [29304.142.master]
* Have you experienced this same bug with .NET Framework?: No

**More info:**
This is a regression issue from d16.3 P3.

**Minimal repro:**
1. Create a C# winforms core application.
2. Right-click the project in solution Explorer window, then click 'Add' to open the "Add New item" page.

**Actual behavior:** 
Two nodes  ‘WPF’ and ‘.NET Core’ are missing on Add New item window.

![Actual](https://user-images.githubusercontent.com/49627022/64510977-dbfbd880-d315-11e9-9da7-47efd0ece59c.PNG)

**Expected behavior:**
These two nodes are showing correctly on Add New item window.

![Expected](https://user-images.githubusercontent.com/49627022/64510930-c4bceb00-d315-11e9-843e-8e4ef30dc1bc.PNG)

**Comment by RussKie** [comment]
@Amy-Li02 our template "Windows Forms" is present in your screenshot. We do not maintian "WPF" and ".NET Core" templates.

**Comment by merriemcgaw** [comment]
@livarcocc , @vatsan-madhavan , @rladuca  - this is a regression in the "Add New Item" dialog 16.4 P1 - which repo should take this issue (WinForms is there but nothing else)
/cc @zsd4yr

**Comment by vatsan-madhavan** [comment]
@chabiss, @diverdan92, @OliaG  - can you help? I don't think IDE experience issues are tracked in any repo. 

Should this issue be re-opened?

**Comment by diverdan92** [comment]
@jjmew @jmarolf  did something change in the project system?

**Comment by jjmew** [comment]
They are not supposed to show. See https://github.com/dotnet/project-system/issues/573

**Comment by weltkante** [comment]
I can see at least two mistakes here:
* WinForms projects are also .NET Core projects, sou you should show WinForms and .NET Core items
* WPF can be removed unless UseWPF is actually true, but if it is true then you need to show WPF items, projects hosting both WPF and WinForms are a thing!

**Comment by weltkante** [comment]
@davkean WPF does work in WinForms, always has been

**Comment by davkean** [comment]
@weltkante I'm aware of how this works, I work on the project-system. I'm not against having the templates show up, its just that the underlying VS pieces haven't landed to make it work. You will see that if both WPF and WinForms properties are turned on, all the templates show up.
