### ISSUE TITLE
Create an extensible functional UI testing solution

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#183]
This issue is to track our current progress porting our existing functional testing suite as well as to encourage a discussion for a more long-term solution to functional UI testing solution.

Our current suite uses Maui as well as a wrapper library (made by the windows forms team), which are fired by xunit tests.

**Comment by karelz** [comment]
@zsd4yr I recommend to use only 1 issue type label ...

**Comment by zsd4yr** [comment]
:) works for me

**Comment by sharwell** [comment]
I've done a bit of work on this in GitExtensions. If the approach is desirable I could implement a more generalized solution here. Would the goal be to just support tests within this repository, or to go a step further and recommend a practice for external Windows Forms developers to create their own tests for applications?

**Comment by zsd4yr** [comment]
@sharwell --currently looking for something 1) we can run as part of a daily / as-often-as-we-want build (so it needs to be parallelizable; think running many different tests); 2) easy to write, and 3) easy to extend. 

The current thinking is to support tests within this repository to create greater confidence in the builds and extensive PRs.

**Comment by zsd4yr** [comment]
Our current solution is --IMHO-- neither easy to write / edit; nor intuitive to contributors; which is why I wanted to open the discussion to the community 😄

**Comment by sharwell** [comment]
My preferred approach has the goal of looking close to this:

```
async Task TestSomething(TControl control)
{
  // At this point the control is created and the current method
  // is executing on the UI thread.

  await SomeOperation();

  // The synchronization context is pre-configured so this code
  // continues executing on the UI thread after SomeOperation
  // and any asynchronous work started by it completes.
  Assert.SomethingAboutState();
}
```

This addresses two early concerns:

1. Easy to reason about the test purpose
1. Test reliability (specifically avoiding cases where asserts run too early)

**Comment by RussKie** [comment]
> I've done a bit of work on this in GitExtensions.

E.g. here
https://github.com/gitextensions/gitextensions/tree/master/UnitTests/GitUITests/CommandsDialogs/CommitDialog
