### ISSUE TITLE
DataGridView InvalidOperationException: This operation cannot be performed while an auto-filled column is being resized.

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#1830]
* .NET Core Version: 3.0 Preview9
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
[stackoverflow](https://stackoverflow.com/questions/34344499/invalidoperationexception-this-operation-cannot-be-performed-while-an-auto-fill)
DataGridView with AutoSizeMode == Fill and ColumnHeadersHeightSizeMode == AutoSize. The problem is that if the mouse cursor accidentally hovers the upper left cell of the grid when the form loads, the application throws an InvalidOperationException.

The code is trying to access dataGridView.TopLeftHeaderCell, which when happens for the first time actually creates that cell and triggers some layout actions not expected at that moment.
Fix: We need to make sure that the TopLeftHeaderCell is created before DataGridView handle.

**Actual behavior:**
InvalidOperationException: This operation cannot be performed while an auto-filled column is being resized.

**Expected behavior:**
No Exception.

**Minimal repro:**
[DataGridViewTest.zip](https://github.com/dotnet/winforms/files/3590612/DataGridViewTest.zip)

**Comment by kirsan31** [comment]
It's strange but I can't repro this issue any more with .net core 3.1 and .net5.0 :astonished: It's even not repro with old 3.0 Preview9 binary and 3.1.9 runtime. And it's stably reproducible on net472.
Besides runtime change, old test was on Windows7 and now  I am testing on Win10 (2004)... Any thoughts?:thinking:

**Comment by RussKie** [comment]
If we can't repro this on .NET 5.0 then I think we can close it. If this comes back we can reopen and investigate then.

**Comment by kirsan31** [comment]
Just tested this on Windows7 and .Net5.0 runtime - no exception 👍
