### ISSUE TITLE
Move common tests helpers out of its own binary and into a new Common folder with common src and common test files

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#187]

**Comment by Tanya-Solyanik** [comment]
Is this applicable to unit tests or to functional tests?

**Comment by zsd4yr** [comment]
it's applicable to all shared; both src and test code

**Comment by AdamYoblick** [comment]
Yeah this is basically doing two things at once - creating $(repoRoot)\Common\src and tests and moving the common testhelper files to that common tests folder. The Common src folder can be used for whatever other common files we have.
