### ISSUE TITLE
MonthCalendar control - Narrator focus is not moving in proper logical order when user is navigating using caps + arrow keys

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#1908]
**Repro Steps:​**
1. Launch .NETCore WinForms app with MonthCalendar control.
2. Start Narrator.
3. Verify that narrator focus is moving in proper logical order or not when user is navigating using caps + arrow keys within the MonthCalendarl control child elements.

**Actual:**
Narrator focus is not moving in proper logical order when user is navigating using caps + arrow keys.
When users press caps + right arrow key Narrator focus is moving to the MonthCalendar control and then right away goes to the next control.

**Expected:**
Narrator focus should move from left to right and top to bottom when user is navigating thru the MonthCalendar control children using caps + arrow keys.  
When users press caps + right arrow key Narrator focus should move from left to right and top to bottom.

**User Impact:**
Screen reader users will face difficulty navigating MonthCalendar control using Narrator (caps + arrow keys)

DevDiv issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/956421

**Comment by M-Lipin** [comment]
The scope of the issue is the correct navigation within the MonthCalendar control hierarchy.

**Comment by M-Lipin** [comment]
Resolving this issue as the fixing PR #2090 is merged to release/3.1.

**Comment by Amy-Li02** [comment]
**Workaround:** 
Add the form controls to the form with the order corresponding to their (controls') tab index:
![Verify](https://user-images.githubusercontent.com/49627022/68750925-a936cf00-063b-11ea-9be7-e1e129381803.png)
