### ISSUE TITLE
MonthCalendar control should support Grid and Table patterns accordingly to table control type

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#1909]
**Issue Details**
1. Make sure the MonthCalendar control element has the appropriate ControlType property - table.
Element path: table 'MonthCalendar'
2. Start AccessibilityInsights tool and inspect the element.
3. Observe that the MonthCalendar control does not support Table and Grid patterns.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information & download this tool at https://accessibilityinsights.io/

DevDiv issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/956702

**Comment by M-Lipin** [comment]
Resolving this issue as the fixing PR #2090 is merged to release/3.1.

**Comment by Vino-Wang** [comment]
Verified with latest .NET Core 3.1 3.1.100-GA-014700 build, this issue is fixed. The controlType of MonthCalendar is table once there is a label in front of it, otherwise, it will be calendar.
