### ISSUE TITLE
UAC shield icon no longer shows in preview 1

### ISSUE THREAD

**Issue by lextm** [dotnet/winforms#192]
The shield button is required to indicate a task requires elevation.

On .NET Framework it is possible to use Windows message to manipulate a button, for example
```c#
        [DllImport("user32")]
        public static extern uint SendMessage(IntPtr hWnd, uint msg, IntPtr wParam, IntPtr lParam);

        internal const int BCM_SETSHIELD = (0x1600 + 0x000C); //Elevated button

        private static void AddShieldToButton(Button b)
        {
            b.FlatStyle = FlatStyle.System;
            SendMessage(b.Handle, BCM_SETSHIELD, IntPtr.Zero, (IntPtr)1);
        }
```
This does not work on Preview 1, and no shield icon is displayed.

**Comment by nsivov** [comment]
BCM_SETSHIELD will only work for comctl32 v6, so first thing to check is that correct manifest/context is enabled.

**Comment by lextm** [comment]
@nsivov Thanks for the hint. Added the following to application manifest and used SysInternals sigcheck to confirm, and then the shield icon started to show up,
```
  <!-- Enable themes for Windows common controls and dialogs (Windows XP and later) -->
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
          type="win32"
          name="Microsoft.Windows.Common-Controls"
          version="6.0.0.0"
          processorArchitecture="*"
          publicKeyToken="6595b64144ccf1df"
          language="*"
        />
    </dependentAssembly>
  </dependency>
```

However, on .NET Framework/Windows, the manifest section can be commented out while shield buttons still appear. So there is still a compatibility issue (or breaking change) here.

Microsoft should either change the .NET Core 3.0 default behavior to match .NET Framework, or improve documentation to warn the developers.

**Comment by zsd4yr** [comment]
> Microsoft should either change the .NET Core 3.0 default behavior to match .NET Framework, or improve documentation to warn the developers.

@karelz what are your thoughts here?

**Comment by lextm** [comment]
@danmosemsft Yes. Sure. I summarize the key points below,

On .NET Framework, my test app uses the following manifest,

https://github.com/jexuswebserver/JexusManager/blob/v12.0.68.0/JexusManager/app.manifest

You can see that the section of `<!-- Enable themes for Windows common controls and dialogs (Windows XP and later) -->` is commented out.

This test app does show UAC shield icons correctly.

On .NET Core, I found that UAC shield icons did not show up, unless this section is uncommented,

https://github.com/jexuswebserver/JexusManager/blob/netcoreapp30/JexusManager/app.manifest

So what I am asking right now, is that Microsoft should try to make UAC shield icons shown by default, just like what I observed on .NET Framework.

Of course, if that's not possible/desired, I can accept the workaround of uncommenting the section. Then the related documentation should be updated to warn users of such issues.

**Comment by nsivov** [comment]
It's also possible to activate context dynamically of course. Maybe that's what .NET Framework is doing.

**Comment by lextm** [comment]
@zsd4yr 

On Windows/.NET Framework, the following section can be commented out, and the UAC shield icon still appears,

```
  <!-- Enable themes for Windows common controls and dialogs (Windows XP and later) -->
  <!--
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
          type="win32"
          name="Microsoft.Windows.Common-Controls"
          version="6.0.0.0"
          processorArchitecture="*"
          publicKeyToken="6595b64144ccf1df"
          language="*"
        />
    </dependentAssembly>
  </dependency>
  -->
```

On Windows/.NET Core 3.0 Preview 1, however, this section must be uncommented for the shield icons to appear.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team take a look and see if this still repros?

**Comment by Jessie-Zhang01** [comment]
Verified this bug in .Net Core 3.0 preview 4 3.0.100.11022 build from master branch + Dev16.0 Preview 5.0 [28729.10.d16.0], UAC shield icon can be shown in .Net Core 3.0 using the provided code at the top, same as .Net framework. Please see following screenshot:
![image](https://user-images.githubusercontent.com/45864649/55320626-2137f680-54aa-11e9-81d1-70688abbc54f.png)

**Comment by lextm** [comment]
Thanks for the hard work, guys. I just tested and it was also resolved in preview 3, so I am closing this issue now.
