### ISSUE TITLE
Problems building on my Windows machine

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#1933]
My heart breaks :(

```cmd
cd Documents/GitHub
git clone https://github.com/dotnet/winforms.git
cd winforms
build.cmd
```

Output:
```cmd
Microsoft Windows [Version 10.0.17763.737]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\hughbe>cd Documents/GitHub

C:\Users\hughbe\Documents\GitHub>git clone https://github.com/dotnet/winforms.git
Cloning into 'winforms'...
remote: Enumerating objects: 161, done.
remote: Counting objects: 100% (161/161), done.
remote: Compressing objects: 100% (124/124), done.

Receiving objects: 100% (32729/32729), 34.59 MiB | 12.28 MiB/s, done.
Resolving deltas: 100% (25399/25399), done.
Updating files: 100% (2959/2959), done.

C:\Users\hughbe\Documents\GitHub>cd winforms

C:\Users\hughbe\Documents\GitHub\winforms>build.cmd
Processing C:\Users\hughbe\Documents\GitHub\winforms\eng\..\global.json
File 'C:\Users\hughbe\.netcoreeng\native\temp\dotnet-api-docs_netcoreapp3.0-0.0.0.1-win64-x64.zip' already exists, skipping download
dotnet-api-docs_netcoreapp3.0 was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: dotnet-api-docs_netcoreapp3.0 was not found in .
Processing C:\Users\hughbe\Documents\GitHub\winforms\global.json
dotnet-api-docs_netcoreapp3.0 was not found in .
Microsoft.PowerShell.Commands.WriteErrorException: dotnet-api-docs_netcoreapp3.0 was not found in .
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha1-013788/dotnet-sdk-5.0.100-alpha1-013788-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha1-013788/dotnet-sdk-5.0.100-alpha1-013788-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\Users\hughbe\Documents\GitHub\winforms\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
Downloading vswhere
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe /nologo /bl:C:\Users\hughbe\Documents\GitHub\winforms\artifacts\log\Debug\ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /m /nr:True /p:ContinuousIntegrationBuild=False /p:TreatWarningsAsErrors=true /p:__ToolsetLocationOutputFile=C:\Users\hughbe\Documents\GitHub\winforms\artifacts\toolset\1.0.0-beta.19463.3.txt /t:__WriteToolsetLocation /v:minimal /warnaserror C:\Users\hughbe\Documents\GitHub\winforms\artifacts\toolset\restore.proj
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe /nologo /bl:C:\Users\hughbe\Documents\GitHub\winforms\artifacts\log\Debug\Build.binlog /clp:Summary /m /nr:True /p:ContinuousIntegrationBuild=False /p:TreatWarningsAsErrors=true /p:Configuration=Debug /p:RepoRoot=C:\Users\hughbe\Documents\GitHub\winforms /p:Restore=True /p:DeployDeps=False /p:Build=True /p:Rebuild=False /p:Deploy=False /p:Test=False /p:Pack=False /p:IntegrationTest=False /p:PerformanceTest=False /p:Sign=False /p:Publish=False /v:minimal /warnaserror C:\Users\hughbe\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19463.3\tools\Build.proj
C:\Users\hughbe\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19463.3\tools\Tools.proj : error : Unable to loc
ate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the in
stalled version.
C:\Users\hughbe\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19463.3\tools\Tools.proj : error MSB4236: The SD
K 'Microsoft.NET.Sdk' specified could not be found.

Build FAILED.

C:\Users\hughbe\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19463.3\tools\Tools.proj : error : Unable to loc
ate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the in
stalled version.
C:\Users\hughbe\.nuget\packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19463.3\tools\Tools.proj : error MSB4236: The SD
K 'Microsoft.NET.Sdk' specified could not be found.
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.37
Build failed.
See log: C:\Users\hughbe\Documents\GitHub\winforms\artifacts\log\Debug\Build.binlog

C:\Users\hughbe\Documents\GitHub\winforms>
```

I can share the remote desktop VM file with anyone by email if you'd like - its a VM in Azure that I use for winforms development

My Visual Studio installation has
- .NET Desktop Development
- Desktop Development with C++
- .NET Core Cross Platform Development

**Comment by hughbe** [comment]
Binlogs here: 

[Archive.zip](https://github.com/dotnet/winforms/files/3627152/Archive.zip)

**Comment by zsd4yr** [comment]
If you go to `https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-alpha1-013788/dotnet-sdk-5.0.100-alpha1-013788-win-x64.exe` (the download location of the SDK run in your output above but with the zip swapped to an exe) and download the SDK to your machine, does that solve the issue?

**Comment by zsd4yr** [comment]
@livarcocc this is similar to the issue I was seeing when trying to rev to the 3.0 GA SDK

**Comment by livarcocc** [comment]
I wonder if this is some incompatibility between arcade and .net 5 SDK for now. Why are you using the 5.0 SDK? Could you stick to 3.0 GA.

5.0 is super early at this point.

**Comment by zsd4yr** [comment]
> Why are you using the 5.0 SDK?

I think we made this change when switching to the 5.0 TFM https://github.com/dotnet/winforms/commit/f71a59f1ca0381179ac3faeaceee0649072dda88 @RussKie may know more

> I wonder if this is some incompatibility between arcade and .net 5 SDK for now. 

/cc @MattGal @Chrisboh in case there is some incompatibility

**Comment by livarcocc** [comment]
Ah, ok. This is master. Is this reproducible? Could I repro this if I tried? Not sure why this would happen inconsistently though.

**Comment by MattGal** [comment]
I can't repro it locally, but when I run it I end up with `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\\MSBuild\Current\Bin\MSBuild.exe`, not `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\msbuild.exe`

**Comment by MattGal** [comment]
... and I CAN reproduce this with my current VS 2019 16.2.5 - updating to the latest public preview or the version of community that comes out soon should fix it.

**Comment by livarcocc** [comment]
This makes a bunch of sense. Much like 3.0 requires 16.3, so does 3.1 and 5.0. If you have only 16.2, then msbuild 16.2 won't find the 3.0 SDK (or 5.0 for that matter).

**Comment by zsd4yr** [comment]
@livarcocc I am not sure why this repo is not using the version of msbuild supplied by the SDK, but the above certainly explains the aftermath.

**Comment by livarcocc** [comment]
Does your build use full framework msbuild? That's what looks like here. It would use the SDK's msbuild if you were building with dotnet.exe and not msbuild.exe.

**Comment by MattGal** [comment]
> Does your build use full framework msbuild? That's what looks like here. It would use the SDK's msbuild if you were building with dotnet.exe and not msbuild.exe.

Yes that's the thing that made me catch the issue in the log, but it should go away by updating community edition.

**Comment by zsd4yr** [comment]
> Does your build use full framework msbuild? That's what looks like here. It would use the SDK's msbuild if you were building with dotnet.exe and not msbuild.exe.

It looks like because we require a minimum version of vs in our global.json and do not give an msbuildEngine to Arcade, that we end up using the msbuild from VS https://github.com/dotnet/winforms/blob/4e9e4bca3353a5aa604eebaff3b4192fd73d883d/eng/common/tools.ps1#L399

**Comment by hughbe** [comment]
> @livarcocc I am not sure why this repo is not using the version of msbuild supplied by the SDK, but the above certainly explains the aftermath.

I would expect to use the msbuild found in `<repo root>/.dotnet`. I believe this is what corefx does?

**Comment by RussKie** [comment]
@hughbe are you still having troubles?
