### ISSUE TITLE
Pressing UpButton/DownButton should jump to the matching item when setting a part of text , which similar to one of DomainUpDown collection

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#195]
Background: recently, we updated the testcase project's targeting pack to .Net 4.7.3, found this regression issue from .Net 4.7.2

Repro Steps:

1.     Create a Winforms application with targeting latest .net 4.7.3 and add a DomainUpDown to form designer
2.      Add and setting to UseLegacyScrolling quirk value to ‘true’ from default value ‘false’ in app.config file
     <runtime>
          <AppContextSwitchOverrides value="Switch.System.Windows.Forms.DomainUpDown.UseLegacyScrolling=true"/>
     </runtime>
3.     Copy following code to from1.cs file behind the InitializeComponent()
     domainUpDown1.Items.Add("foo1");
     domainUpDown1.Items.Add("foo2");
     domainUpDown1.Items.Add("foo3");
     domainUpDown1.Items.Add("Cowman");
     domainUpDown1.Items.Add("foo4");
     domainUpDown1.SelectedIndex = 0; //Set SelectedIndex to a valid value
4.     Run application
5.     Input a text “Cow” in DomainUpDown, then click UpButton/DownButton

Actual:
Pressing UpButton, it jumps to foo3 item; Pressing DownButton, it jumps to foo4 item.

Expected:
Pressing UpButton/DownButton, they all jump to matching item: Cowman in DomainUpDown item. It means UpButton/DownButton jumps to the item's index.

Related internal bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/590429

**Comment by karelz** [comment]
Nit: There is no 4.7.3. Do you mean 4.8?

**Comment by merriemcgaw** [comment]
Yep, that's what was meant. :)
