### ISSUE TITLE
Conditional order of precedence bug in ScrollableControl.SetDisplayRectLocation

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#1955]
From the code in https://github.com/dotnet/winforms/blob/3f564803ff268bab776fea7df9970d37760ed4da/src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs#L786-L798

The conditional check `if (xDelta != 0 || yDelta != 0 && IsHandleCreated)` has incorrect bracketing and order of precedence.

It should be `if ((xDelta != 0 || yDelta != 0) && IsHandleCreated)`.

This has observable differences in behaviour - see #1920 (https://dotnetfiddle.net/EVSyDY)

Fixing this bug would have the following implications
- We don't create a `Handle` if `xDelta != 0` and `IsHandleCreated == true`

**Comment by RussKie** [comment]
@sharwell any thoughts?

**Comment by sharwell** [comment]
@RussKie SA1408 should report this, yes. Is the rule disabled?

**Comment by sharwell** [comment]
https://github.com/dotnet/winforms/blob/8ecc2b49acfd44f607d4ad9b7add1e80dcb3d88d/eng/Shipping.ruleset#L99

I believe you can also get this behavior from a built-in rule:

```
dotnet_style_parentheses_in_arithmetic_binary_operators = always_for_clarity:warning
dotnet_style_parentheses_in_other_binary_operators = always_for_clarity:warning
dotnet_style_parentheses_in_relational_binary_operators = always_for_clarity:warning
```

**Comment by RussKie** [comment]
Thank you Sam.
Any other rules we should enable?

**Comment by sharwell** [comment]
@RussKie That's entirely up to the individual project. If you have any questions about the applicability of specific rules I'm happy to help 👍

**Comment by RussKie** [comment]
It is easy to break `SetDisplayRectLocation_InvokeWithoutHandle_Success` test by adding an `Debug.Assert(IsHandleCreated, "Handle is not created")` in the condition.
So it is a 🐛

**Comment by hughbe** [comment]
Aye.. I can fix this once https://github.com/dotnet/winforms/pull/1920 is merged

**Comment by RussKie** [comment]
I'm looking at all violations of SA1408, so leave this with me.

**Comment by RussKie** [comment]
Looking further at the code I'm wondering - would a child control have its handle created if its parent control doesn't have a handle? Is it a valid scenario?
If not, we can optimise `SetDisplayRectLocation` method to fast exit if `IsHandleCreated` isn't created:
https://github.com/dotnet/winforms/blob/3f564803ff268bab776fea7df9970d37760ed4da/src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs#L786-L808

@JeremyKuhne @Tanya-Solyanik @dreddy-work what do you think?

**Comment by weltkante** [comment]
> would a child control have its handle created if its parent control doesn't have a handle? Is it a valid scenario?

In Desktop Framework this apparently was possible and there is [code to deal with that](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Control.cs,1879), so I'd assume this is still possible in Core.

Basically, if some user code forces the child window handle to be created it will be created hidden and parented to a "parking window". Later when the real parent is actually created the child will be moved over. I don't know if the comment is correct but thats how I read it.

**Comment by RussKie** [comment]
Thank you Tobias.
