### ISSUE TITLE
Reference (not using) windows forms in cross platform class library or application.

### ISSUE THREAD

**Issue by baehny** [dotnet/winforms#1959]
Hi,
I am working on a cross platform application that uses windows forms on windows.
So my csproj contains the following lines:
```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    ...
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    ...
```

The problem with this is that I am now unable to build the application with Visual Studio Mac because of the missing Microsoft.NET.Sdk.WindowsDesktop.
I'm completely aware of the fact that windows forms will not work on other platforms but does this mean I'm forced to setup up multiple projects if the application only uses windows forms on windows but still needs to reference the binaries for the build ?
Using the "Microsoft.NET.Sdk.WindowsDesktop" means that every binary that references windows forms (even without using it) cannot be references in a cross platform application/library.

Is there any recommended way to do this ? Most information only talk about porting windows apps to .net core. 

Otherwise I'm now forced to split one application and one class library into 2 applications  and 2 class libraries. (with and without windows forms)

**Comment by weltkante** [comment]
You cannot build WinForms projects on non-Windows because it needs to execute WinForms code during the build (at least once they finish porting licx resources for licensing, which currently is not completed). There may also be code execution going on with resx resources though I'm not entirely sure of that, might be just in the designer.

**Comment by RussKie** [comment]
Please follow the issues referenced above.
It is for the most part outside our control.
