### ISSUE TITLE
[CI] Windows Debug Build Occasionally Hangs

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#1962]
I've observed that the Windows Debug Build sometimes times out at 60 minutes in CI and fails to report any results

No diagnosis

**Comment by hughbe** [comment]
See https://github.com/dotnet/winforms/pull/1971 
(https://dev.azure.com/dnceng/public/_build/results?buildId=365473&view=logs&jobId=1f132584-ab08-5fbf-e5d0-5685de454342)

Here are the logs
[logs_365473.zip](https://github.com/dotnet/winforms/files/3652708/logs_365473.zip)

```
The process cannot access the file 'd:\a\1\s\artifacts\log\Debug\System.Windows.Forms.Tests_netcoreapp5.0_x64.log' because it is being used by another process.
```

**Comment by RussKie** [comment]
I've raised the issue to the infra team

**Comment by hughbe** [comment]
Can't seem to repro anymore - should i close?
