### ISSUE TITLE
The template C# Windows Forms Controls Library(.NET Core) is missing

### ISSUE THREAD

**Issue by Amy-Li02-zz** [dotnet/winforms#1970]
* .NET Core Version: .NET Core 3.1.100-preview1-014066
* Have you experienced this same bug with .NET Framework?: No

**More info**
In CLI dialog, there also doesn't exist C# Windows Forms Controls Library(.NET Core) template.
![image](https://user-images.githubusercontent.com/49627022/65577269-11efbc80-dfa6-11e9-9403-48f79ca1c8f1.png)

**Minimal Reproduction Steps**
1. Launch VS and click the "New Project", the **Create a new project** dialog will show up.

**Expected Behavior**
There should exist  C# Windows Forms Controls Library(.NET Core) template in Create a new project dialog.

**Current Behavior**
There doesn't exist C# Windows Forms Controls Library(.NET Core) template, only exist C# Windows Forms Controls Library(.NET Framework) template in Create a new project dialog.

![image](https://user-images.githubusercontent.com/49627022/65576201-131fea00-dfa4-11e9-9d59-fbc276c5c1fe.png)

**Comment by RussKie** [comment]
We will tackle it for .NET 5.0

**Comment by Amy-Li03** [comment]
Verified this issue with the latest .NET SDK 5.0.100-rc.1-20426.12 build, now the Windows Forms Control Library(.NET Core) template can be found and created from CLI, but it still cannot be found from VS.

**Comment by merriemcgaw** [comment]
This will be inserted to VS in the next couple of days. @Amy-Li03 can you check it next week?

**Comment by Amy-Li03** [comment]
@merriemcgaw I will check it next week.

**Comment by Amy-Li03** [comment]
@merriemcgaw verified with 16.8 P4 latest build [30510.5.main] + .NET SDK 5.0 rc2 latest build 5.0.100-rc.2-20459.24, the Windows Forms Control Library(.NET Core) template still **cannot** be found from VS.

**Comment by merriemcgaw** [comment]
@marcpopMSFT do you know when we'll start to see this in builds of VS?

**Comment by marcpopMSFT** [comment]
@merriemcgaw it's in the CLI dotnet new templates from what I can see so it's in the SDK.  I'm not familiar with how things show up in the new project UI so adding @jjmew @wli3 @KathleenDollard @donJoseLuis for comment.

**Comment by Amy-Li03** [comment]
After **checked** the preview flag from Tools -> Options -> Preview Features -> **Show all .NET Core templates in the New project dialog**, we can find the Windows Forms(WinForms) Control Library(C#) & Windows Forms(WinForms) Control Library(Visual Basic) templates from VS and they can be created successfully.
![c#](https://user-images.githubusercontent.com/62929087/93172787-18021e80-f75e-11ea-95e0-8a493c644fa1.gif)

**Comment by marcpopMSFT** [comment]
@jjmew Do we have shareable information on when the new New Project dialog will be live and will it include all CLI templates?

**Comment by jjmew** [comment]
That is @vijayrkn  and @donJoseLuis

**Comment by vijayrkn** [comment]
@marcpopMSFT @jjmew - VS integration for .NET Core project templates is handled by my team. The above preview feature will ship in 16.8 & will list all CLI templates. 

@KathleenDollard

**Comment by DenisBabarykin** [comment]
Microsoft Visual Studio Enterprise 2019 Version 16.8.2, .NET 5.0 is already released, but I still can't find template of **Windows Forms Control Library (.NET)**. When this feature finally will be done? :( 
@vijayrkn

**Comment by DenisBabarykin** [comment]
Okay, I did what @Amy-Li03 suggested and it have solved my problem. But this is still a bit confusing.
![изображение](https://user-images.githubusercontent.com/10895923/101807849-a5b79500-3b26-11eb-9254-eeb45d42c2fe.png)
