### ISSUE TITLE
Strange Encoding Issues

### ISSUE THREAD

**Issue by carlowahlstedt** [dotnet/winforms#198]
When cloning and opening the code base for the first time, on macOS 10.14.1, strange encoding issues appear. A few were fixed in another PR, but here's a list of the others I found.

<img width="333" alt="screen shot 2018-12-06 at 9 56 24 am" src="https://user-images.githubusercontent.com/2687687/49625373-422c8700-f9a3-11e8-91b8-18808f574e87.png">

#155 @Tanya-Solyanik

**Comment by karelz** [comment]
I am curious what is the unicode char that causes the trouble. I doubt it is "normal" apostrophe, or backtick. Those should IMO just work everywhere.

**Comment by AdamYoblick** [comment]
Maybe the special curved single a double quotes that Word uses for example?


________________________________

**Comment by karelz** [comment]
Maybe, although I wonder how they got from Word to code :)

**Comment by jnm2** [comment]
I type `’` on purpose because I like it (Alt+0146).
UTF8 (no BOM) all the things! Tooling shouldn’t be enforcing restrictions like this on us at this point. I've yet to see issues with out-of-the-box Git setup and curly quotes.

**Comment by merriemcgaw** [comment]
Is this happening on Windows? Or any other OS beyond MacOS?

**Comment by zsd4yr** [comment]
Does anyone know of a way to simply replace these at commit / push time? can .gitattributes do something to help us here?

I do not think each developer should have to fix these; we should just to something automatic to ensure all chars in comments are unicode readable.

**Comment by jnm2** [comment]
Were all the files added in https://github.com/dotnet/winforms/commit/195f89af79d550c2da1711c45c379efd63519ac1 saved as UTF8 without BOM?

Once all files are on UTF8, .editorconfig's `charset = utf-8` can ensure that encodings aren't accidentally mixed. I usually do:

```ini
root = true

[*]
indent_style = space
charset = utf-8
end_of_line = crlf
insert_final_newline = true
trim_trailing_whitespace = true
```

**Comment by zsd4yr** [comment]
We should be able to add it and then locally take all out and put all back in liek you would if you updated the gitignore.

**Comment by zsd4yr** [comment]
actually I forgot that we do not currently wish to change all the files like that but I've made this change @jnm2 so that all new files will not suffer 😄 

#205

**Comment by jnm2** [comment]
> but I've made this change @jnm2 so that all new files will not suffer 😄

My only caution about doing the .editorconfig without normalizing existing files would be that you might see invisible (whitespace) changes on the first line of each modified file in a PR for files changing from UTF8-BOM to UTF8. It doesn't seem too bad, but ymmv and it might bug you.

**Comment by zsd4yr** [comment]
Is this still an issue?

**Comment by RussKie** [comment]
I found one more, #482
