### ISSUE TITLE
Interop.User32.PostMessageW has wrong return type

### ISSUE THREAD

**Issue by kpreisser** [dotnet/winforms#1981]
* .NET Core Version: `master` (7019e1414309d820bc377e987cd1efcf9c17a12d)
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
Hi, while adjusting the task dialog code in #1133 for recent interop changes and changing the usage of `UnsafeNativeMethods.PostMessage()` to `Interop.User32.PostMessageW()` (introduced with #1764), I noticed it has a return type of `IntPtr` (meaning 4 byte on 32-bit and 8 byte on 64-bit):
https://github.com/dotnet/winforms/blob/7019e1414309d820bc377e987cd1efcf9c17a12d/src/Common/src/Interop/User32/Interop.PostMessageW.cs#L13-L18

However, `PostMessageW` is defined in `WinUser.h` to return a `BOOL`, which is a C `int` (4 byte on Windows):
```cpp
WINUSERAPI
BOOL
WINAPI
PostMessageW(
    _In_opt_ HWND hWnd,
    _In_ UINT Msg,
    _In_ WPARAM wParam,
    _In_ LPARAM lParam);
```

Therefore, I think using `IntPtr` as return type is not correct, as it could lead to too many bytes being read. Instead, it should be e.g. a `bool` (marshalled as the 4-byte `BOOL`), `Interop.BOOL` or `int`.

**Actual behavior:** 
```c#
public static extern IntPtr PostMessageW(...)
```

**Expected behavior:**
```c#
public static extern bool PostMessageW(...);
// or
public static extern Interop.BOOL PostMessageW(...);
```

Thank you!

**Comment by RussKie** [comment]
The method you need is still available: 
https://github.com/dotnet/winforms/blob/7019e1414309d820bc377e987cd1efcf9c17a12d/src/Common/src/UnsafeNativeMethods.cs#L488-L492

It hasn't been ported/cleaned up yet.

**Comment by weltkante** [comment]
The already ported version still needs to be fixed though, considering it is incompatible with the native API (its probably a copy/paste error because the other similarly named methods do return IntPtr)

/cc @JeremyKuhne

**Comment by JeremyKuhne** [comment]
Yes, this should be `Interop.BOOL`.
