### ISSUE TITLE
Reference Source for repository

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#1982]
[Roslyn](http://source.roslyn.io) and [CoreFX](https://source.dot.net/) have online browsable source for their repositories, we should have that for WPF and WinForms as well. I'm still using [Desktop Reference Source](https://referencesource.microsoft.com/) but WinForms is already moving apart due to the refactoring. Having online browsable source would be very useful for quick research during code reviews. (corresponding issue for WPF dotnet/wpf#1967)

**Comment by RussKie** [comment]
@ericstj @danmosemsft any hints how we could set the same?
/cc: @vatsan-madhavan

**Comment by ericstj** [comment]
@KirillOsenkov do you know who manages the set of repos that contribute to source.dot.net?  It'd be nice to add WinForms and WPF.

**Comment by KirillOsenkov** [comment]
@alexperovich is the man!

**Comment by KirillOsenkov** [comment]
Hmm I think WinForms is already being indexed:
https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/Button.cs,cb5c00483936b8f7

https://github.com/dotnet/source-indexer/blob/9bff716508ba262c9583ad86c30ada7b1a07e8c8/src/index/repositories.props#L17-L28

**Comment by weltkante** [comment]
Thats great, thanks, wasn't aware that multiple repositories can go into the same site. Looks like WPF is there too.
