### ISSUE TITLE
Tests deadlock

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1999]
* .NET Core Version: 5.0

**Problem description:**

Running tests from the master branch locally I got tests hung. I have attached a debugger and there was a dozen of hung threads.

9 threads were stuck unable to acquire the lock in `NativeWindow.CreateHandle()` method (originating stacks were slightly different, but they all ended in the same critical section):
![image](https://user-images.githubusercontent.com/4403806/65936205-37297280-e45f-11e9-88f1-bceed2dee9a7.png)

1 thread was stuck restoring the default trace listener:
![image](https://user-images.githubusercontent.com/4403806/65936554-570d6600-e460-11e9-9c15-77b331d5fe41.png)

2 thread were stuck while writing a trace:
![image](https://user-images.githubusercontent.com/4403806/65936617-7e643300-e460-11e9-85b9-c80a33254db5.png)
![image](https://user-images.githubusercontent.com/4403806/65936653-9cca2e80-e460-11e9-9661-8eb754b89cff.png)

What appears to have happened is that one test was in a middle of creating a handle and attempted to add a trace, which was locked by another thread, that was restoring the default trace listener:
![image](https://user-images.githubusercontent.com/4403806/65937120-25959a00-e462-11e9-8900-9984cb95047a.png)

**Expected behavior:**

No deadlock

**Minimal repro:**

This is very intermittent...

**Comment by RussKie** [comment]
Few questions here:
- do we need to lock in `NoAssertContext`? Can we make `s_defaultListener` volatile or use `Interlocked` object?
- should all out tests dealing with UI (e.g. instantiating controls) be decorated with `StaFactAttribute` or [`WinFormsFactAttribute`](https://github.com/AArnott/Xunit.StaFact/blob/master/src/Xunit.StaFact/WinFormsFactAttribute.cs)

/cc: @hughbe

**Comment by weltkante** [comment]
Creating a control handle on a non-STA thread is a bad idea, it turns the thread pool thread into a UI thread by allocating a message queue etc. but without telling COM that the thread is STA, so controls using COM internally (e.g. RichTextBox) will be pretty confused, if working at all.

**Comment by JeremyKuhne** [comment]
> Should all out tests dealing with UI (e.g. instantiating controls) be decorated with StaFactAttribute or WinFormsFactAttribute

I think `WinFormsFactAttribute` is the right response here

**Comment by weltkante** [comment]
@JeremyKuhne do you know if `WinFormsFactAttribute` will lead to `OleInitialize` being called? I suspect some of the test failures are due to calling OLE functions on non-STA threads, but STA alone may not be enough for OLE, you probably need to call `OleInitialize` on the thread as well.

**Comment by RussKie** [comment]
/cc: @AArnott any thoughts on the subject?

**Comment by hughbe** [comment]
Could it be that we don’t dispose any controls in the unit tests?

**Comment by weltkante** [comment]
I think there are multiple concerns here

The deadlock @RussKie shows is a plain bug in the NoAssertListener, the TraceListenerCollection [has its own lock](https://referencesource.microsoft.com/#System/compmod/system/diagnostics/TraceListeners.cs,db564f838f2411e4) and you got a lock inversion with the NoAssertListeners lock: one path takes them in order A B the other code path takes them in order B A, leading to a deadlock.

Then there is the whole concern of running tests involving window handles and OLE interop on non-STA threads, which technically is not part of this issue, I just was asking here because people already were discussing the test attributes.

Not disposing a control may be a problem, but its not directly related to the deadlock. Sorry for leading the discussion astray.

**Comment by AArnott** [comment]
The `WinFormsFactAttribute` executes the test on an STA thread and sets up `WinFormsSynchronizationContext` on that thread. It does nothing else. If `OleInitialize` or some other code should be run as well before the test starts, I'm happy to oblige. Please file an issue at https://github.com/AArnott/Xunit.StaFact/issues

**Comment by weltkante** [comment]
While looking at the lock inversion I found another bug in NoAssertContext/NoAssertListener, when installing the listener secondary threads won't wait for the primary thread to actually finish installation of the listener, which can cause them to pass through and kill the process via assert even though they think they are within an NoAssertContext.

I think I'll create a PR rewriting the NoAssertListener, it doesn't look too complicated. Will add plenty comments to document the fixed race conditions and lock issues so they aren't reintroduced later.

/CC @JeremyKuhne
