### ISSUE TITLE
Flaky test: `AxHost_GetIFontFromFont_InvokeSimpleStyle_Roundtrips`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#2003]
* .NET Core Version: master @ 3750c43d5d9b5161be967e39fd848c89d6479ff5

**Problem description:**

`AxHost_GetIFontDispFromFont_InvokeSimpleStyle_Roundtrips` test fails locally from cli and VS:

```
  Message: 
    Assert.Equal() Failure
    Expected: 0
    Actual:   254
  Stack Trace: 
    AxHostTests.AxHost_GetIFontFromFont_InvokeSimpleStyle_Roundtrips() line 1083
```

**Expected behavior:**

The test pass

/cc: @hughbe

**Comment by weltkante** [comment]
One thing I notice is that the port of `IFont` is missing two interface methods (added annotations in the original PR) - but I don't think those can be responsible here because they come after the method reading the charset property
