### ISSUE TITLE
Ensure ErrorProvider supports all accessibility requirements.

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#2016]
Per: https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/errorprovider-component-overview-windows-forms The ErrorProvider doesn't support accessibility clients. We should add that because apps that depend on it may not be fully accessible for their users.

**Comment by RussKie** [comment]
This may be handy as well https://blogs.msdn.microsoft.com/winuiautomation/2017/09/14/let-your-customers-know-of-important-status-changes-in-your-winforms-app/

**Comment by vladimir-krestov** [comment]
@merriemcgaw, @RussKie, @Tanya-Solyanik, could you please say if I got it correctly? 
I have implemented UIA supporting for ErrorProvider.ErrorWindow and ErrorProvider.ErrorWindowAccessibleObject.
Now we can change ErrorProvider AccessibleObject properties. But I couldn't find any same implementation, so **I need your suggestion** for how we'll implement ErrorProvider AccessibleObject properties.
At the moment, I have implemented it like this:
![image](https://user-images.githubusercontent.com/49272759/68755698-ea1dec00-0619-11ea-80a2-a76bc562b26b.png)

I found the following bug:
- There is one error icon
![image](https://user-images.githubusercontent.com/49272759/68757204-9660d200-061c-11ea-8549-23e6fd11553c.png)

- There are two error icons
![image](https://user-images.githubusercontent.com/49272759/68757233-ab3d6580-061c-11ea-99d4-1dac54e3d983.png)

Both icons have one ErrorWindow and one AccessibleObject.
It isn't a regression, it reproduces in the release branch.
**Do we need to create a separated bug to fix it?**

Now Narrator can announce an error icon AccessibleObject if a user uses CapsLock + keyboard arrows:
![image](https://user-images.githubusercontent.com/49272759/68756787-d7a4b200-061b-11ea-8189-c581a98bcb5c.png)

**Comment by vladimir-krestov** [comment]
Quick fix. I can make like this:
![image](https://user-images.githubusercontent.com/49272759/68785796-beb5f400-064f-11ea-8f31-616cf948bd10.png)
![image](https://user-images.githubusercontent.com/49272759/68786572-0b4dff00-0651-11ea-8e8f-ae2de4198837.png)

**Comment by vladimir-krestov** [comment]
When hovering by mouse you get icon AccessibleObject:
![image](https://user-images.githubusercontent.com/49272759/68856511-ba421780-06f1-11ea-8874-916056c4c4b8.png)

Narrator works well using CapsLock + keyboard arrows combination:
![Sc48e41fpi](https://user-images.githubusercontent.com/49272759/68856733-4ce2b680-06f2-11ea-9449-28ba70c4c763.gif)

@merriemcgaw, @Tanya-Solyanik, @RussKie, could you please confirm my solution?

**Comment by vladimir-krestov** [comment]
For details please see #2381.
