### ISSUE TITLE
Port `System.Drawing.Design.ContentAlignmentEditor`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#2018]
**Problem description:**

`ContentAlignmentEditor` from System.Drawing.Design is missing.

Refer to https://github.com/dotnet/winforms/issues/1115#issuecomment-501115599

**Comment by zsd4yr** [comment]
closed by https://github.com/dotnet/winforms/commit/42194cd32102c79bdeeef7012c1fec34f55492d7
