### ISSUE TITLE
[Port] Regressions in custom DataGridView cell editing controls 

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#2036]
* .NET Core Version: 3.0
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
Port fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/989913 (repro app is attached to the VSO bug)
Steps to reproduce: A customer has reported this in the forums.
1. Install Windows Server 2019 Standard with Desktop Experience from an ISO. 
2. Install Failover Cluster Services.
3. Create new cluster, on the 4th screen, add the current server name. This is what it shows: See step3 screenshot.
4. Install .NET 4.8 from an offline installer. (KB4486153) and reboot.
5. Go back to the same screen of the same Create Cluster Wizard and now it looks different: See step5 screenshot.
6. Now we are unable to type in a 3 digit IP in any of the octet fields. It accepts a maximum of two characters.

**Comment by merriemcgaw** [comment]
@M-Lipin will we be able to get this for 3.1? The bug makes the MaskedTextBox relatively unusable.

**Comment by M-Lipin** [comment]
Yes, I'll fix this. Plan to send for testing asap.

**Comment by M-Lipin** [comment]
Fix PR #2248 has been merged to release/3.1 branch. So closing the issue as resolved.

**Comment by Ashley-Li** [comment]
Verified this bug with .NET Core 3.1.101-servicing-014846 build validation, the issue has been fixed.
