### ISSUE TITLE
Verb runas does not trigger UAC elevation in preview 1

### ISSUE THREAD

**Issue by lextm** [dotnet/winforms#204]
* .NET Core Version: (3.0 Preview1)
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
It is very common to call another executable using `Process` class and pass `"runas"` as verb to trigger UAC prompt, so that the executable to call is launched as elevated.

**Actual behavior:** 
No UAC prompt. The executable is launched but not elevated.

**Expected behavior:**
UAC prompt should show. The executable should be launched and elevated.

**Minimal repro:**
Will attach later.

**Comment by lextm** [comment]
Here is the sample project. 
[uac-elevation-test.zip](https://github.com/dotnet/winforms/files/2658884/uac-elevation-test.zip)

1. Open WindowsFormsApp1.sln in Visual Studio 2019 Preview 1.
1. Compile all projects.
1. Go to TriggerElevation\bin\Debug to launch TriggerElevation.exe.
1. Click the button.

Because this is a WinForms app on .NET Framework, UAC prompt should appear, and after that a message box saying "Elevated" is displayed (by NeedElevation.exe).

1. Go to TriggerElevationNetCore\bin\Debug\netcoreapp3.0 to launch TriggerElevationNetCore.exe.
1. Click the button.

Because this is a WinForms app on .NET Core, UAC prompt does not appear, and a message box saying "Not elevated" is displayed (by NeedElevation.exe).

**Comment by wjk** [comment]
@lextm Two thoughts;

1. Are you certain `UseShellExecute` is true? If not, the verb will be ignored.
2. You might want to test to see if this bug also reproduces with a console application as well as a Forms app, because the `Process` class actually exists in [corefx](https://github.com/dotnet/corefx), which is not Forms-specific. If so, you  might want to move this bug there.

**Comment by lextm** [comment]
Thanks. It seems that the default value of `Process.UseShellExecute` has been changed to `false` on .NET Core, which is the cause of this issue. Close it now.

**Comment by lextm** [comment]
Related to https://github.com/dotnet/docs/issues/3111
