### ISSUE TITLE
The color of the Linklabel is black in runtime when targeting .NET Core 5.0

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#2052]
* .NET Core Version: (.NET Core SDK 5.0.100 - alpha1 5.0.100.14858)
* Have you experienced this same bug with .NET Framework?: No

**More info:**
This issue cannot reproduce when targeting .NET Core 3.0.

**Actual behavior:** 
The color of the Linklabel text is black and user cannot distinguish between clicking and no clicking.
![Issue](https://user-images.githubusercontent.com/18568603/66445983-415cf980-ea7b-11e9-8856-69365774c4b1.png)

**Expected behavior:**
The color of the Linklabel text is blue.
![Expected_NET3 0](https://user-images.githubusercontent.com/18568603/66445986-4457ea00-ea7b-11e9-8558-17c102b2614c.png)

**Minimal repro:**
1.	Install .NET Core 5.0 from Master branch + latest VSIX package.
2.	Create a new .NET Core application with modifying the <TargetFramework> to netcoreapp5.0
3.	Add a linklabel to the form designer.
4.	Run the app.

**Comment by vladimir-krestov** [comment]
@Vino-Wang, could you please retest this issue? It seems to have been fixed after the master merging.

**Comment by Vino-Wang** [comment]
Verified with latest .NET 5.0 + VS2019, the issue is fixed now. The color of linklabel is correct right now.

After Fix:
![image](https://user-images.githubusercontent.com/18568603/78873974-3f9dde00-7a7e-11ea-86a9-e27d5b30fb16.png)
