### ISSUE TITLE
[Question]: Overriding Scrollbars

### ISSUE THREAD

**Issue by Wagnerp** [dotnet/winforms#2054]
Hi,

I'm the developer for the `Krypton Toolkit Suite` projects hosted here on GitHub, and I was wondering if there was a way to override the default scrollbars for controls with some custom made scrollbars as seen below?

![image](https://user-images.githubusercontent.com/949607/66474563-74a68500-ea89-11e9-8f30-1714520af7f3.png)

**Comment by weltkante** [comment]
Is this the same feature request as #2040?

**Comment by Wagnerp** [comment]
@weltkante 

Thanks for pointing this out. Hopefully a API for this stuff can be added soon!
