### ISSUE TITLE
NotifyIcon ContextMenuStrip is shown above taskbar

### ISSUE THREAD

**Issue by 0x084E** [dotnet/winforms#2058]
* .NET Core Version: 3.0.100
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
A NotifyIcons ContextMenuStrip is shown above the taskbar and not within.

I think the reason for this is that ToolStripDropDown.WorkingAreaConstrained is always returning true in .NET Core ([Net.Core Source](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/ToolStripDropDown.cs,8513f6aa3e2a13ef,references) / [.NET Framework Source](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ToolStripDropDown.cs,8513f6aa3e2a13ef,references))

.NET Core 3
![image](https://user-images.githubusercontent.com/7345141/66543472-c278c700-eb35-11e9-9591-631ff7c0e034.png)

.NET Framework 4.8
![image](https://user-images.githubusercontent.com/7345141/66543527-e805d080-eb35-11e9-867c-3989e5ebc640.png)

**Actual behavior:**
ContextMenu is shown above the taskbar.

**Expected behavior:**
ContextMenu should be shown within the taskbar.

**Minimal repro:**
Create a NotifyIcon, set ContextMenuStrip property, show the icon and right click.

**Comment by weltkante** [comment]
@0x084E but Desktop also always returns true, unless you are running with restricted rights, which is no longer supported. So this code path looks identical between Core and Desktop to me.

**Comment by sneusse** [comment]
I got the same issue in .Net Core 3.1

Here is a hacky workaround - maybe you'll need additional bounds checks, maybe also RTL will be broken, who knows. I'ts good enough for my use-case so I thought I'll share it here. 

The behaviour will be a bit different as the submenu will always open at the cursor location (actually I like this behaviour more :) ). Be sure to use the provided extension method when creating submenus, otherwise you'll have the same problem again.

```csharp
    public static class ToolStripDropDownItemExtensions
    {
        public static T CreateSubmenu<T>(this T item) where T : ToolStripDropDownItem
        {
            item.DropDown = new TrayMenu();
            return item;
        }
    }

    public class TrayMenu : ContextMenuStrip
    {
        [DllImport("user32.dll", SetLastError = true)]
        private static extern bool SetWindowPos(IntPtr hWnd, IntPtr hWndInsertAfter, int x, int y, int cx, int cy,
            uint uFlags);

        protected override void SetBoundsCore(int x, int y, int width, int height, BoundsSpecified specified)
        {
            var wmax = SystemParameters.VirtualScreenWidth;
            var hmax = SystemParameters.VirtualScreenHeight;

            var pos = Cursor.Position;
            x = pos.X;
            y = pos.Y;

            if (x + width > wmax) x -= width;
            if (y + height > hmax) y -= height;

            SetWindowPos(Handle, IntPtr.Zero, x, y, width, height, 0);
        }
    }
```

**Comment by 0x084E** [comment]
II'll need a little more logic, but overriding SetBoundsCore was a nice hint. Thanks for sharing!
