### ISSUE TITLE
.NET Core project template doesn't have a manifest file

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#2059]
* .NET Core Version: 3.1.0-preview1.19458.7
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
- It needs to add a manifest file to Core project template in order for the new app to opt-in into all the latest fixes from Windows. 

**Actual behavior:** 
- Core project template doesn't have a manifest file

**Expected behavior:**
- Core project template must have a manifest file

**Minimal repro:**
- Create new .Net Core app

**Manifest file:**
- [ManifestFile.zip](https://github.com/dotnet/winforms/files/3708508/ManifestFile.zip)

**Comment by merriemcgaw** [comment]
User can add a manifest easily to their project (add new item dialog).

**Comment by RussKie** [comment]
Apps get the default manifests
![image](https://user-images.githubusercontent.com/4403806/66622002-c427b500-ec31-11e9-83af-fb7a7a5c16a9.png)

Is our default manifest missing features?

**Comment by vladimir-krestov** [comment]
@Tanya-Solyanik could you please explain this point?

**Comment by weltkante** [comment]
@vladimir-krestov by default VS embeds a default manifest

@RussKie the default manifest does not include the `<supportedOS Id="..."/>`tags to enable Windows 7, 8, 8.1 or Windows 10 support, so .NET Core 3 applications will be switch into a compatibility mode for older OS versions, which is what @vladimir-krestov is meaning when he says the manifest does not opt-in to the latest fixes

I agree that either the default manifest needs an upgrade, or the template should include the `app.manifest` template from VS. The first thing I do in every new application is to add a manifest to enable Windows 10 support.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity version="1.0.0.0" name="MyApplication.app"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
```

**Comment by vladimir-krestov** [comment]
Thank you!

**Comment by RussKie** [comment]
@ericstj do you know who owns the default manifest? Is this change something we can entertain to it?

**Comment by RussKie** [comment]
Thank you @weltkante 👍
