### ISSUE TITLE
Enable Roslyn Analyzers

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/winforms#2067]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes/No

**Problem description:**
Port the fixes for Roslyn Analyzer violations from the VS source to the winforms source. See https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/206917 for details.

**Actual behavior:** 

**Expected behavior:**

**Minimal repro:**

**Comment by merriemcgaw** [comment]
@AdamYoblick do we still need to port the changes you describe in the linked AzDO bug?

**Comment by AdamYoblick** [comment]
I believe so, I don't think it ever got done. Very low Pri though.

**Comment by merriemcgaw** [comment]
Sync with @RussKie about what else should be added.

**Comment by elachlan** [comment]
Currently I am undertaking this in #7887 to be on par with runtime.
