### ISSUE TITLE
translate winforms to use native calls on mac and linux?

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/winforms#2076]
right now winforms is the easiest to use but doesn't look native on other platforms.
I think if someone with the know how was willing to support other platforms natively it would be a better alternative for cross platform development then say xwt and eto.

I dislike the idea of anything related to wpf since its not native looking even on windows and is harder to use.

**Comment by weltkante** [comment]
> right now winforms is the easiest to use but doesn't look native on other platforms

Projects referencing WinForms don't even build on other platforms, much less running on them, so what exactly are you talking about?

If you try to run WinForms applications via an emulation layer then any request to modernize the look and feel would need to be done against that emulation layer, WinForms itself is mostly a wrapper around the win32 API, it doesn't provide its own theming or control implementations, so it has no influence on the look and feel.

**Comment by Shadowblitz16** [comment]
I thought winforms ran on mac and linux on mono and .netcore?
My suggestion is simply if it does or if it will it would be a good idea to translate it to native widgets on linux and mac.

that way people can use winforms for cross platform development and not have it look like shit on other platforms.

**Comment by RussKie** [comment]
Apps built on Windows Forms on .NET Framework and .NET Core 3.0 run on Windows. 
It is also possible to run Windows Forms on .NET Framework under Mono runtime on Linux (NB: it isn't 100% like-for-like though).

There are no immediate plans to run Windows Forms .NET Core 3.0/.NET 5.0 on non-Windows platforms. 
We are actutely aware of our consumers' desire to have a x-plat story, however there is nothing we can share or promise at this stage.

**Comment by xiangzhai** [comment]
:linux-interest

**Comment by Rombersoft** [comment]
Windows is dead. Give me Linux

**Comment by RussKie** [comment]
@Rombersoft consider yourself warned for spam.
