### ISSUE TITLE
Incorrect position of controls when layout is suspended

### ISSUE THREAD

**Issue by jmarolf** [dotnet/winforms#2084]
* .NET Core Version: 3.0 RTW
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

When a controls layout is suspended, if anchors are specified, changing the location of that control will cause incorrect positions to occur when layout is resumed

**Actual behavior:**

![](https://user-images.githubusercontent.com/9663150/65137205-32999e80-da09-11e9-80f8-852861f4f392.gif)

**Comment by RussKie** [comment]
Is this a designer or a runtime issue?

**Comment by jmarolf** [comment]
This is happening in the designer process so I believe it is a runtime issue.

**Comment by jmarolf** [comment]
I think this is a designer issue.  I will re-open with more info if this is not the case
