### ISSUE TITLE
 [loc][Query][winforms] Localizability of 0; "columnHeader1.Text"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/winforms#2087]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
ColumnHeader1

File Name:
System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\xlf\ListViewTest.xlf

==========================================
Query:
Is this entry translatable? Same for following strings:
ColumnHeader2 0; "columnHeader2.Text"
TableLayoutPanels 0; "$this.Text"

**Comment by RussKie** [comment]
Anything under "test" namespace/path are safe to ignore: System.Windows.Forms\**tests**\IntegrationTests\WinformsControlsTest\xlf\ListViewTest.xlf

**Comment by RussKie** [comment]
We are in a process of removing xlf from the test apps to reduce the confusion and the maintenance overhead.
