### ISSUE TITLE
Duplicatated `DpiHelper` implementations

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#2120]
**Problem description:**

* `System.Windows.Forms` uses the common implementation of `DpiHelpers` from https://github.com/dotnet/winforms/blob/master/src/Common/src/DpiHelper.cs
* `System.Windows.Forms.Design` uses the common implementation of `DpiHelpers` from https://github.com/dotnet/winforms/blob/master/src/Common/src/DpiHelper.cs
* `System.Windows.Forms.Design.Editors` has own implementation in https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms.Design.Editors/src/Misc/DpiHelper.cs

**Expected behavior:**

`System.Windows.Forms.Design.Editors` uses the common implementation instead of maintaining own copy.

**Comment by archery2000** [comment]
Hi, can I try this issue?

**Comment by archery2000** [comment]
Just to clarify, if I can work on this issue, is the following the things that are needed?

- Edit src\DpiHelper.cs to also provide the functionality of misc\DpiHelper.cs (this is just a difference of 1 function)
- Edit the .csproj file to use src\DpiHelper.cs instead
- Ensure that all code depending on the file can function properly without any need for changes

Apologies, I am still quite new to this.

**Comment by RussKie** [comment]
Thank you for the interest, but the issue is already being worked on by @hughbe in #2131.
