### ISSUE TITLE
.net core forms doesn't open designer

### ISSUE THREAD

**Issue by campelo** [dotnet/winforms#2147]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
.net core 3.0
* Have you experienced this same bug with .NET Framework?: Yes/No
No

**Problem description:**
I have created a new windows forms app (.net core) project. When I tried open Form1's designer view and VS2019 shows only the code view. I have also tried to click on Form1.cs with right-button and choose C# windows forms but nothing happens.

**Actual behavior:** 
Impossible to open designer view of desktop forms (.net core)

**Expected behavior:**
Open designer view of desktop forms.

**Minimal repro:**
Install Visual Studio 2019 Community edition (16.3.5) and .net core 3.0 ultimate version. Create a new Windows Forms App (.Net Core). It's impossible to open Form1's designer view.

**Comment by weltkante** [comment]
Did you install the designer preview? Front page has a link to the [designer documentation](https://github.com/dotnet/winforms/blob/master/Documentation/winforms-designer.md) which states it is not done. You can install a preview as extension package.

**Comment by merriemcgaw** [comment]
@campelo does following the instructions to install the VSIX for the installer work for you?

**Comment by campelo** [comment]
Yes, I thought this feature was already available on the latest VS 2019 update. Everything works fine now.
Thanks

> Did you install the designer preview? The front page of the repository has a link to the [designer documentation](https://github.com/dotnet/winforms/blob/master/Documentation/winforms-designer.md) which states it is not done, you can install a preview as extension package.
