### ISSUE TITLE
Broken types

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#2153]
* .NET Core Version: **3.0+**
* Have you experienced this same bug with .NET Framework?: **Yes**

**Problem description:**

Preparing API compat reports https://github.com/dotnet/winforms/pull/2092 we stumbled upon several types that are declared as `public abstract` but contain `internal abstract` members.
This meas these types can't be used outside the framework's codebase and, thus, are useless to our consumers:
![image](https://user-images.githubusercontent.com/4403806/67345669-93c40d00-f587-11e9-8709-54977e78f6c5.png)

The types in questions:
* [`System.Windows.Forms.BindingManagerBase`](https://github.com/dotnet/winforms/blob/release/3.0/src/System.Windows.Forms/src/System/Windows/Forms/BindingManagerBase.cs)
* [`System.Windows.Forms.ScrollProperties`](https://github.com/dotnet/winforms/blob/release/3.0/src/System.Windows.Forms/src/System/Windows/Forms/ScrollProperties.cs)

**Expected behavior:**

TBD

**Minimal repro:**

Try subclass any of the above types

**Comment by weltkante** [comment]
For what its worth `internal abstract` used to be a common way to prevent user-defined subclasses outside the assembly (before `private protected` being added, which is more clear regarding intentions) - so being not subclassable may have been intended or desireable.

I think you should question whether you want user defined subclasses for each of these cases, e.g. for BindingManagerBase I don't think it is useful and it would probably harm the assumptions in the binding system.

**Comment by merriemcgaw** [comment]
I agree with @weltkante  - I don't see a huge reason to have either of these allow user defined sub classes.

**Comment by KlausLoeffelmann** [comment]
Well, I can use `BindingManagerBase` to write generic code for its derived classes, can I not (`CurrencyManager`, `PropertyManager`)? (Or am I missing the point?)
The docu shows this as well. I am closing this issue for now.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.bindingmanagerbase?view=netframework-4.8

**Comment by weltkante** [comment]
Yes you are missing the point, why do you need to subclass BindingManagerBase to write code handling derived classes?

That said I don't think there's much to do in response to this issue, except maybe using the new `private protected` modifier to more clearly describe the intent instead of making things `internal abstract`
