### ISSUE TITLE
Icon paint a little dim after migrate to .NET Core

### ISSUE THREAD

**Issue by TempeBrennan** [dotnet/winforms#2155]
* .NET Core Version: 3.0 Preview1
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
We use this code to paint icon in form.
```
public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Paint(object sender, PaintEventArgs e)
        {
            e.Graphics.DrawIcon(new Icon("Image.ico"), 0, 0);
        }
    }
```
When use .NET Core, image bit depth decreased. Is this design?
Would you like to share some workaround? Thanks a lot.

**Actual behavior:** 
![Image 156](https://user-images.githubusercontent.com/51563666/67354483-cf5ed700-f587-11e9-9e6f-cebadccd1b85.png)
**Expected behavior:**
![Image 157](https://user-images.githubusercontent.com/51563666/67354476-ca9a2300-f587-11e9-92f2-fe3df11094b8.png)

**Minimal repro:**
[WindowsFormsApp1.zip](https://github.com/dotnet/winforms/files/3759950/WindowsFormsApp1.zip)

**Comment by RussKie** [comment]
I suspect this is a duplicate of #1825.
Could you please check 3.1 and see if it fixed in it? https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries

**Comment by TempeBrennan** [comment]
@RussKie I tested by lastest version installer and confirmed it's fixed indeed.
Sorry to brother you. Thanks a lot again.

**Comment by RussKie** [comment]
No worries at all, hopefully it won't inconvenience you too much.
3.1 will be released pretty soon.
