### ISSUE TITLE
System.Resources.Resx code readability and style issues

### ISSUE THREAD

**Issue by Liminiens** [dotnet/winforms#216]
**Problem description:**

Currently there is an issue with code style consistency in `System.Resources.Resx...` family (like using BCL types instead of keywords), and in some places the readability of the code could be improved. For example, use  `foreach` instead of `for`, or remove redundant else conditions. Also some patterns like `str != null && str.Length > 0`, or `.Equals` can be simplified.

**Comment by KlausLoeffelmann** [comment]
Absolute. I would even go so far to say: Before we would accept PRs which 'optimize' code in terms of standards/readability, we'd need benchmark proof that the modification doesn't hurt performance.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zsd4yr** [comment]
> Absolute. I would even go so far to say: Before we would accept PRs which 'optimize' code in terms of standards/readability, we'd need benchmark proof that the modification doesn't hurt performance.

@KlausLoeffelmann I think that should not be necessary for this **particular** PR, as I've gone through it manually and can guarantee the benefit here. However, I agree that we absolutely need bench marking of our current performance. We have this anecdotally on a few applications but not anywhere approaching the law of large numbers nor with any real confidence about the most important / frequently-hit code paths
