### ISSUE TITLE
The return value of UnsafeNativeMethods.SetParent should be properly checked

### ISSUE THREAD

**Issue by chenxinyanc** [dotnet/winforms#2163]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`) N/A
* Have you experienced this same bug with .NET Framework?: Yes (.NET Framework 4.6/4.7)

**Problem description:**
I couldn't find a place to post the WinForm issue on .NET Framework, but since we have WinForm on Core CLR, and the subjected code are the same, so…

We've observed failures of `SetParent` when trying to set our WinForm control (`Panel`) as a child of another `Panel`. It seems that [native `SetParent` can fail if the controls somehow are under different DPI-awareness setting since Windows 10 1703](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setparent#remarks).

https://github.com/dotnet/winforms/blob/b34582761bea089eb0d19aba8e43c4b90d90c98e/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L11043

I think we should check for the return value, and call something like `Marshal.ThrowExceptionForHR` if `SetParent` failed, so the users may track this kind of failure more easily.

**Actual behavior:** 
No Exception raised even if `SetParent` returned 0 and `GetLastError` returned `ERROR_INVALID_STATE`.

**Expected behavior:**
We should throw some sort of Win32Exception telling user `SetParent` failed.

**Minimal repro:**
For now I cannot provide a clean repro for this, but I can work out one if this is really needed.

**Comment by weltkante** [comment]
Note that just throwing an exception may not be sufficient, it could leave the control in an inconsistent state since the logic was not written with the awareness that parenting can fail. The calling logic needs to be audited so it can roll back state changes properly.

**Comment by merriemcgaw** [comment]
Do note that we'd be taking this fix in .NET Core 5.0, and it won't go back to .NET Framework. If it's blocking your .NET Framework app please submit feedback via the VS Developer Community. That said, we're generally only taking security fixes in .NET Framework so the bar is very high.

**Comment by chenxinyanc** [comment]
Thanks, @merriemcgaw ! We are still trying to address the root cause for the failure of `SetParent`. The issue here is just likely to be a pitfall for the debugging. However, I hope the check is introduced to the next version of .NET as soon as possible 😄

**Comment by RussKie** [comment]
> For now I cannot provide a clean repro for this, but I can work out one if this is really needed.

A repro would be very helpful, it will make evaluating the issue easy.
Thanks

**Comment by chenxinyanc** [comment]
Sure. See https://github.com/chenxinyanc/WinFormSetParentTest .
