### ISSUE TITLE
TypeConverter Attribute over DataGridViewColumn.DataPropertyName should resolve to System.Design

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#2171]
https://github.com/dotnet/winforms/blob/b34582761bea089eb0d19aba8e43c4b90d90c98e/src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs#L186-L194

This attribute was changed to resolve to the new assembly of this type in #1545 but as pointed out in https://github.com/dotnet/winforms/pull/2078#discussion_r337787642 this is not the approach we should take.

For a fix, we need to:
* change the `AssembleRef` back to `SystemDesign`
* manually add a TypeForwardTo for this internal type
* test

**Comment by RussKie** [comment]
In case you missed it - https://github.com/dotnet/winforms/pull/2154

**Comment by merriemcgaw** [comment]
@RussKie what is left on this one?
