### ISSUE TITLE
Necessary CodeDomSerializers not ported to WinForms

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/winforms#2185]
The follow `CodeDomSerializer`s have not been ported to .NET Core WinForms, and are needed for designer scenarios:

* `System.ComponentModel.Design.Serialization.LocalizationCodeDomSerializer`
* `System.Windows.Forms.Design.ControlCodeDomSerializer`
* `System.Windows.Forms.Design.DataGridViewRowCollectionCodeDomSerializer`
* `System.Windows.Forms.Design.TableLayoutPanelCodeDomSerializer`
* `System.Windows.Forms.Design.TableLayoutControlCollectionCodeDomSerializer`
* `System.Windows.Forms.Design.ToolStripMenuItemCodeDomSerializer`

Everything in WinForms that has a `DesignerSerializerAttribute` should be audited to ensure that the type specified by the attribute actually exists.

cc @merriemcgaw

**Comment by merriemcgaw** [comment]
We need to get this one in for 3.1 if at all possible. @M-Lipin can you and @vladimir-krestov take a look as your next priority?

**Comment by vladimir-krestov** [comment]
Thanks!
Ok, we'll take a look at this.

**Comment by weltkante** [comment]
`System.Windows.Forms.Design.ToolStripCodeDomSerializer` is also missing. Otherwise your list seems complete with regard to `System.Windows.Forms.dll` in `3.1.0-preview1.19506.1`

> Everything in WinForms that has a DesignerSerializerAttribute should be audited to ensure that the type specified by the attribute actually exists.

<details><summary>code I used to look for missing types</summary>

```C#
var map = new Dictionary<string, List<Type>>();

foreach (var type in typeof(Control).Assembly.DefinedTypes)
{
    foreach (var attr in type.GetCustomAttributes<DesignerSerializerAttribute>())
    {
        if (Type.GetType(attr.SerializerTypeName) == null)
        {
            if (!map.TryGetValue(attr.SerializerTypeName, out var list))
                map.Add(attr.SerializerTypeName, list = new List<Type>());

            list.Add(type);
        }
    }
}

foreach (var pair in map.OrderBy(x => x.Key))
{
    Debug.WriteLine($"- {pair.Key}");
    foreach (var type in pair.Value.OrderBy(x => x.FullName))
        Debug.WriteLine($"  - {type.FullName}");
}
```

</details>

**Comment by RussKie** [comment]
> (probably should be turned into a unit test or something)

Would you like to send a PR? 😉

**Comment by weltkante** [comment]
> Would you like to send a PR?

If you just want to make sure all existing attributes can resolve then I can of course translate the above code into a PR. If you want to diff against Desktop to make sure there are no attributes missing, thats outside my expertise and I don't really understand how to do that. Basically it comes down to what exactly you want to have tested.

**Comment by RussKie** [comment]
> If you just want to make sure all existing attributes can resolve then I can of course translate the above code into a PR

^^^ This will be much appreciated
