### ISSUE TITLE
Serious Bug in .NET Core Windows Forms Designer Preview 1

### ISSUE THREAD

**Issue by zydjohnHotmail** [dotnet/winforms#2231]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes/No
No

**Problem description:**
When I created a "Hello World" simple Windows Form App on .NET Core 3.0 using .NET Core Windows Forms Designer Preview 1, it works on some simple things, like: drag a button onto the Form1 and run.  But a little more complicated things, like: created 3 buttons and "format" them with the same spacing, the .NET Core Windows Forms Designer Preview 1 make Visual Studio 2019 (Version 16.3.6) reboot itself.
However, the most serious bug is: after saving and reopen a .NET Core project created by .NET Core Windows Forms Designer Preview 1, the total job done were deleted by the Windows Forms Designer, you have to do all the jobs from scratch, it is not acceptable.

**Actual behavior:** 
Even for the most simple task, like drag a button and drop on "Form1" with .NET Core Windows Forms Designer Preview 1, it can work, but if you save the C# project, and re-open it, all the jobs done were totally wiped out.

**Expected behavior:**
I should be able to create any .NET Core Windows App, and save my project, then later on, I can open my project and continue edit my job, and debug my project.

**Minimal repro:**
I want to try to use .NET Core Windows Forms Designer Preview 1 in my C# .NET Core project.
I am using Visual Studio 2019 Version 16.3.6 with .NET Core Windows Forms Designer Preview 1.
I simply created a simple "Hello Word" C# project using "Windows Forms App (.NET Core)", I added 3 buttons by copy and paste, to make them equal size, when I tried to use "format" tools to make them center in the form, then
VS 2019 reboots itself, then I found all the buttons were gone, the project went back to its original form.
After this, I did more basic things: I created a simple "Hello Word" C# project using "Windows Forms App (.NET Core)", I dragged one button from toolbox and put it on the form, and run it, it works. Then I saved all the project files, and closed the project.
After I closed the project, I opened it again, and I found all the jobs in Form1 were gone, the button is missing, the form looks exactly from scratch.
I know .NET Core Windows Forms Designer is still in Preview, but the basic saving and opening causing all the jobs lost seem not a good experience for any user.
This issue was confirmed by a Microsoft engineer, for details, refer to C# forum thread:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/89bbe1e1-f9b8-4cf5-b3fb-b47996bc58b8/net-core-windows-forms-designer-preview-1-not-saving-form-designer?forum=winforms

**Comment by merriemcgaw** [comment]
We have made many improvements in the WinForms designer over the past year and you should be able to complete the tasks you describe. Please try again with the 16.8 GA release when it is available soon. We are still in Preview with lots of pieces still to rearchitect for the new .NET, but it's much more usable now. Please file VS Feedback tickets with any specific issues you run into and feel free to link them in here to get my quicker attention.
