### ISSUE TITLE
Test failures can cause hangs by calling `OnThreadException` resulting in dialog

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2234]
E.g. in https://github.com/dotnet/winforms/pull/2141
See https://github.com/dotnet/winforms/pull/2141#issuecomment-547281156 and https://github.com/dotnet/winforms/pull/2141#issuecomment-547328796

We either need to override `_threadExceptionHandler` (i.e. `Application.ThreadException`) to simply throw the exception or to disable `SystemInformation.UserInteractive`

**Comment by RussKie** [comment]
Should we fix `OnHandleCreated` logic instead?
As per discussions in https://github.com/dotnet/winforms/pull/2141#issuecomment-547339010 and https://github.com/dotnet/winforms/pull/2141#issuecomment-547348971?

**Comment by weltkante** [comment]
@RussKie we got #2235 for OnHandleCreated

**Comment by weltkante** [comment]
> We either need to override _threadExceptionHandler (i.e. Application.ThreadException) to simply throw the exception or to disable SystemInformation.UserInteractive

From what I've seen running tests locally you do have tests which test user interaction, disabling `UserInteractive` flag may lead to altering the tested code which is not ideal.

I'd prefer "disarming" the OnThreadException code path to prevent showing UI on errors. If you can get hold of the test framework you could report test failure directly if anything enters OnThreadException unintentionally. To me that looks like it would be the ideal solution.

**Comment by hughbe** [comment]
So basically what we could do is, before every test (I.e. in setup for WinFormsFact) add a thread exception handler

```
void handler(object sender, ThreadExceptionEventArgs e)
{
    ExceptionDispatchInfo.Throw(e.Exception);
}
Application.ThreadException += handler;

// Do test

Application.ThreadException -= handler;
```

Alternatively `Application.SetUnhandledExceptionMode(UnhandledExceptionMode.ThrowException)` may work for exceptions arising out of `NativeWindow`

**Comment by RussKie** [comment]
IIRC, in xUnit a ctor is run before each test, so we can achieve the above in the following way:

```cs
public class MyTests : IDisposable
{
	public MyTests()
	{
		void handler(object sender, ThreadExceptionEventArgs e)
		{
		    ExceptionDispatchInfo.Throw(e.Exception);
		}
		Application.ThreadException += handler;
	}

	public Dipspose() 
	{
		Application.ThreadException -= handler;
	}
}
```

We could probably put it in a base class too, and inherit tests from it; but inheritance makes me uneasy as I've seen it abused in horrible ways.

**Comment by weltkante** [comment]
> We could probably put it in a base class too, and inherit tests from it

Not sure what your concerns on base classes are, but an alternative is using [fixtures](https://github.com/xunit/samples.xunit/tree/master/ClassFixtureExample) instead of a base class. It is not required passing the fixture to the constructor and you are more composable than base classes because you can have any number of fixtures on a test.

<details><summary>example code</summary>

```csharp

public class UnitTest1 : IClassFixture<ThreadExceptionFixture>, IClassFixture<SomeOtherFixture>
{
    [Fact]
    public void Test1()
    {
        Assert.True(true);
    }
}

public class ThreadExceptionFixture : IDisposable
{
    public ThreadExceptionFixture()
    {
        Application.ThreadException += application_ThreadException;
    }

    public void Dispose()
    {
        Application.ThreadException -= application_ThreadException;
    }

    private void application_ThreadException(object sender, ThreadExceptionEventArgs e)
    {
        ExceptionDispatchInfo.Throw(e.Exception);
    }
}

public class SomeOtherFixture : IDisposable
{
    public SomeOtherFixture()
    {
    }

    public void Dispose()
    {
    }
}

```

</details>

Alternatively, if you always want this behavior and not have to annotate every test, you maybe could do something like in the [AssemblyFixture example](https://github.com/xunit/samples.xunit/tree/master/AssemblyFixtureExample)

**Comment by hughbe** [comment]
Oh that is actually awesome! I shall do a little digging into it and see if we can update once #2457 is in

**Comment by RussKie** [comment]
I will reopen the ticket, if it becomes necessary.
