### ISSUE TITLE
Port LinkAreaEditor

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#2284]
Porting the missing UITypeEditors
Related to #1115

**Comment by Rise-Yang** [comment]
Verified the issue with .NET Core 3.1.100.14727 build, the issue has been fixed, there is the … (ellipsis) button next to the LinkArea property name and we can edit LinkArea (LinkLabel property) via LinkAreaEditor.
![image](https://user-images.githubusercontent.com/56662732/69035891-a6632200-0a1f-11ea-8d70-4a614b71cb2d.png)
![image](https://user-images.githubusercontent.com/56662732/69036927-c98ed100-0a21-11ea-8bd2-fdf73c51d64e.png)
