### ISSUE TITLE
Visual Studio becomes unresponsive when debugging DateTimePicker ValueChanged event

### ISSUE THREAD

**Issue by riv1** [dotnet/winforms#2393]
* .NET Core Version: 3.0.100
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
Setting a breakpoint on the **first** line of code inside the ValueChanged event handler causes Visual Studio to become unresponsive, when the breakpoint is hit.

**Actual behavior:** 

**Expected behavior:**

**Minimal repro:**
1. Create WinForms .Net Core app and add a DateTimePicker control to the form.
2. Add the ValueChanged event handler to the control.
3. On ValueChanged, add code to show a messagebox.
4. Place a breakpoint on the line of code.
5. Debug the app. When the breakpoint is hit, Visual Studio will become unresponsive and cannot continue.
```
private void dateTimePicker1_ValueChanged(object sender, EventArgs e)
        {            
            MessageBox.Show("hello world"); //breakpoint here             
        }
```

**Comment by RussKie** [comment]
@Vino-Wang could you please triage it.
