### ISSUE TITLE
OleDragDropHandler class is not implemented

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2400]
Means that calling things like
`if (OleDragDropHandler.FreezePainting)` throws `NotImplementedException`

See https://github.com/dotnet/winforms/pull/2398
```cs
        [WinFormsFact]
        public void ControlDesigner_WndProc_InvokePaint_Success()
        {
            var designer = new SubControlDesigner();
            var m = new Message
            {
                Msg = (int)User32.WindowMessage.WM_PAINT
            };
            designer.WndProc(ref m);
        }

        private class SubControlDesigner : ControlDesigner
        {
            public new void WndProc(ref Message m) => base.WndProc(ref m);
        }
```

This test is expected to pass but throws `NotImplementedException` in .NET Core

**Comment by weltkante** [comment]
> This test is expected to pass but throws NotImplementedException in .NET Framework

I can't quite follow, looking at .NET Framework assemblies with ILSpy it looks like `OleDragDropHandler.FreezePainting` is implemented and doesn't throw.

**Comment by hughbe** [comment]
sorry!! I meant > This test is expected to pass but throws NotImplementedException in .NET Core

**Comment by RussKie** [comment]
Looks like we haven't ported `OleDragDropHandler`
https://github.com/dotnet/winforms/blob/7aeb736b075b102efb4d3fc4df6add660177d032/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs

@merriemcgaw what are our priorities around this?

**Comment by merriemcgaw** [comment]
@OliaG FYI. Let me chat with PM. There has to be a reason it wasn't ported in the first place.

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik popping this on your radar to so we can chat about it.

**Comment by Tanya-Solyanik** [comment]
We don't need this class for the core designer because user input is handled in the VS. I would wait for a customer request before porting this class.

**Comment by RussKie** [comment]
In this case, I'm closing it for now. We can re-open it in the future, if that becomes necessary.
