### ISSUE TITLE
Narrator does not announce Up/Down buttons when targeting .NET Core 5.0

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#2406]
* .NET Core Version: (.NET Core SDK 5.0.100 – alpha1 – 5.0.100.15753)
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
In .Net Core 5.0 apps Narrator doesn't announce Up/Down buttons if a user uses CapsLock + kreyboard arrows combination. It works well in .Net 4.8 & .Net Core 3.1.

**More Info:**
This is a regression issue, it cannot reproduce in .Net Core 3.1.

**Actual behavior:** 
Narrator does not announce Up/Down buttons.
![Actual(targeting5 0)](https://user-images.githubusercontent.com/18568603/69301072-fd4f3e00-0c4f-11ea-8c63-af9eeaebc462.gif)

**Expected behavior:**
Narrator should announce Up/Down buttons.
![Expected(targeting3 1) gif](https://user-images.githubusercontent.com/18568603/69301078-004a2e80-0c50-11ea-8339-81571a089acd.gif)

**Minimal repro:**
1.	Download the attached .Net Core 5.0 app.
[UpDownButtons.zip](https://github.com/dotnet/winforms/files/3872649/UpDownButtons.zip)

2.	Run it and launch the Narrator and press possible arrows combination to observe the announcement.

**Comment by RussKie** [comment]
@Vino-Wang please note that the latest .NET 5.0 does not contain the latest version of WinForms.
Please check what version of WinForms you have installed in C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\5.0.0-alpha1.???\System.Windows.Forms.dll
![image](https://user-images.githubusercontent.com/4403806/69305431-09e78c80-0c78-11ea-8af2-39871feaaf3a.png)

If the assembly is generated prior to 13 Nov, it won't have changes from 3.1.

**Comment by vladimir-krestov** [comment]
This is my request to create the new Issue.
I checked this on the latest version of **master** branch.

**Comment by RussKie** [comment]
Right, all good then.
Just making sure we're not filing unnecessary tickets.

Thank you

**Comment by Vino-Wang** [comment]
Verified with latest .NET 5.0 + VS 2019, this issue is fixed now. Narrator can read the Up/Down button like below:
![image](https://user-images.githubusercontent.com/18568603/78873605-b5557a00-7a7d-11ea-9c8e-cf079b184795.png)
