### ISSUE TITLE
DesignerAttributes referencing nonexisting classes

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#2411]
* .NET Core Version: 5.0 master
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
Regression in many (but not all) `DesignerAttribute` annotations, all attributes have been ported from .NET Framework but a lot of Designer classes they are referencing have not been ported. Discovered during implementation of PR #2230 which is testing the consistency of attribute annotations.

**Actual behavior:**
`[DesignerAttribute]` referencing a type which does not exist

**Expected behavior:**
One of these options needs to be chosen for each designer:
- remove the DesignerAttribute and provide no designer
- remove the DesignerAttribute in WinForms, but port the Designer within VS and add the attribute dynamically in the VS Designer environment
- port the Designer class into WinForms

Which choice to make should be primarily driven by whether you want to support that control being used in a 3rd party designer (requires option 3)

**Minimal repro:**
PR #2230 test failures when removing skipped entries

**List of classes failing the test:**

- [AxDesigner](https://github.com/dotnet/winforms/search?q=AxDesigner&unscoped_q=AxDesigner)
- [AxHostDesigner](https://github.com/dotnet/winforms/search?q=AxHostDesigner&unscoped_q=AxHostDesigner)
- [BindingNavigatorDesigner](https://github.com/dotnet/winforms/search?q=BindingNavigatorDesigner&unscoped_q=BindingNavigatorDesigner)
- [BindingSourceDesigner](https://github.com/dotnet/winforms/search?q=BindingSourceDesigner&unscoped_q=BindingSourceDesigner)
- ~[ButtonBaseDesigner](https://github.com/dotnet/winforms/search?q=ButtonBaseDesigner&unscoped_q=ButtonBaseDesigner)~ #4860
- ~[ComboBoxDesigner](https://github.com/dotnet/winforms/search?q=ComboBoxDesigner&unscoped_q=ComboBoxDesigner)~ #4860
- [DataGridViewColumnDesigner](https://github.com/dotnet/winforms/search?q=DataGridViewColumnDesigner&unscoped_q=DataGridViewColumnDesigner)
- [DataGridViewComboBoxColumnDesigner](https://github.com/dotnet/winforms/search?q=DataGridViewComboBoxColumnDesigner&unscoped_q=DataGridViewComboBoxColumnDesigner)
- [DataGridViewDesigner](https://github.com/dotnet/winforms/search?q=DataGridViewDesigner&unscoped_q=DataGridViewDesigner)
- ~[DateTimePickerDesigner](https://github.com/dotnet/winforms/search?q=DateTimePickerDesigner&unscoped_q=DateTimePickerDesigner)~ #8549 
- [FlowLayoutPanelDesigner](https://github.com/dotnet/winforms/search?q=FlowLayoutPanelDesigner&unscoped_q=FlowLayoutPanelDesigner)
- [FolderBrowserDialogDesigner](https://github.com/dotnet/winforms/search?q=FolderBrowserDialogDesigner&unscoped_q=FolderBrowserDialogDesigner)
- ~[GroupBoxDesigner](https://github.com/dotnet/winforms/search?q=GroupBoxDesigner&unscoped_q=GroupBoxDesigner)~ #4860
- [ImageListDesigner](https://github.com/dotnet/winforms/search?q=ImageListDesigner&unscoped_q=ImageListDesigner)
- ~[LabelDesigner](https://github.com/dotnet/winforms/search?q=LabelDesigner&unscoped_q=LabelDesigner)~ #4860
- ~[ListBoxDesigner](https://github.com/dotnet/winforms/search?q=ListBoxDesigner&unscoped_q=ListBoxDesigner)~ #4860
- ~[ListViewDesigner](https://github.com/dotnet/winforms/search?q=ListViewDesigner&unscoped_q=ListViewDesigner)~ #4860
- [MonthCalendarDesigner](https://github.com/dotnet/winforms/search?q=MonthCalendarDesigner&unscoped_q=MonthCalendarDesigner)
- [NotifyIconDesigner](https://github.com/dotnet/winforms/search?q=NotifyIconDesigner&unscoped_q=NotifyIconDesigner)
- ~[PanelDesigner](https://github.com/dotnet/winforms/search?q=PanelDesigner&unscoped_q=PanelDesigner)~ #4860
- ~[PictureBoxDesigner](https://github.com/dotnet/winforms/search?q=PictureBoxDesigner&unscoped_q=PictureBoxDesigner)~ #4860
- [PrintDialogDesigner](https://github.com/dotnet/winforms/search?q=PrintDialogDesigner&unscoped_q=PrintDialogDesigner)
- [PropertyGridDesigner](https://github.com/dotnet/winforms/search?q=PropertyGridDesigner&unscoped_q=PropertyGridDesigner)
- ~[RadioButtonDesigner](https://github.com/dotnet/winforms/search?q=RadioButtonDesigner&unscoped_q=RadioButtonDesigner)~ #4860
- ~[RichTextBoxDesigner](https://github.com/dotnet/winforms/search?q=RichTextBoxDesigner&unscoped_q=RichTextBoxDesigner)~ #4860
- [SaveFileDialogDesigner](https://github.com/dotnet/winforms/search?q=SaveFileDialogDesigner&unscoped_q=SaveFileDialogDesigner)
- [SplitContainerDesigner](https://github.com/dotnet/winforms/search?q=SplitContainerDesigner&unscoped_q=SplitContainerDesigner)
- [SplitterDesigner](https://github.com/dotnet/winforms/search?q=SplitterDesigner&unscoped_q=SplitterDesigner)
- [SplitterPanelDesigner](https://github.com/dotnet/winforms/search?q=SplitterPanelDesigner&unscoped_q=SplitterPanelDesigner)
- [StatusBarDesigner](https://github.com/dotnet/winforms/search?q=StatusBarDesigner&unscoped_q=StatusBarDesigner)
- [TabControlDesigner](https://github.com/dotnet/winforms/search?q=TabControlDesigner&unscoped_q=TabControlDesigner)
- [TabPageDesigner](https://github.com/dotnet/winforms/search?q=TabPageDesigner&unscoped_q=TabPageDesigner)
- [TableLayoutPanelDesigner](https://github.com/dotnet/winforms/search?q=TableLayoutPanelDesigner&unscoped_q=TableLayoutPanelDesigner)
- ~[TextBoxDesigner](https://github.com/dotnet/winforms/search?q=TextBoxDesigner&unscoped_q=TextBoxDesigner)~ #4860
- [ToolStripContainerDesigner](https://github.com/dotnet/winforms/search?q=ToolStripContainerDesigner&unscoped_q=ToolStripContainerDesigner)
- [ToolStripContentPanelDesigner](https://github.com/dotnet/winforms/search?q=ToolStripContentPanelDesigner&unscoped_q=ToolStripContentPanelDesigner)
- [ToolStripPanelDesigner](https://github.com/dotnet/winforms/search?q=ToolStripPanelDesigner&unscoped_q=ToolStripPanelDesigner)
- [TrackBarDesigner](https://github.com/dotnet/winforms/search?q=TrackBarDesigner&unscoped_q=TrackBarDesigner)
- ~[TreeViewDesigner](https://github.com/dotnet/winforms/search?q=TreeViewDesigner&unscoped_q=TreeViewDesigner)~ #4860
- ~[UpDownBaseDesigner](https://github.com/dotnet/winforms/search?q=UpDownBaseDesigner&unscoped_q=UpDownBaseDesigner)~ #4860
- ~[UserControlDocumentDesigner](https://github.com/dotnet/winforms/search?q=UserControlDocumentDesigner&unscoped_q=UserControlDocumentDesigner)~ #4860
- [WebBrowserDesigner](https://github.com/dotnet/winforms/search?q=WebBrowserDesigner&unscoped_q=WebBrowserDesigner)

**Comment by merriemcgaw** [comment]
This was missed, thank you for bubbling it back up! @KlausLoeffelmann  - do you think we're probably good here, in that we have Core copies in the Designer itself, and can prioritize these attributes later?

**Comment by merriemcgaw** [comment]
@RussKie to review which ones we have and don't have as of now.

**Comment by RussKie** [comment]
@merriemcgaw it doesn't look like the list has changed since @weltkante has collated it.

**Comment by weltkante** [comment]
The question is mainly whether these are supposed to be in WinForms runtime, or if the designer now has its own copy of these designers and doesn't need the attribute hints. If the designer has its own copy then these attributes probably can just be removed? At the moment they contain invalid information.

**Comment by merriemcgaw** [comment]
@weltkante that's exactly the discussion we want to have. It depends on whether we see partners developing their own designers for their customers to create things like reports and to what degree. Once we've made some business calls on this, we'll remove all the invalid info.

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - please compare this list with https://github.com/dotnet/winforms/issues/4908 and consolidate missing designers into 4908 to simplify tracking, then close this issue.

**Comment by Tanya-Solyanik** [comment]
We can't remove these attributes because the Out Of Process designer relies on them, it remaps them to appropriate types.

**Comment by weltkante** [comment]
TypeDescriptor API lets you add/modify those attributes dynamically at runtime without modifying the WinForms library, the old VS Designer platform was already doing that to override metadata attributes e.g. for swapping out the designer behavior of bitmap properties. I don't see any reason why the WinForms library has to contain invalid metadata, but I'm not insisting on anything, just wanted to make sure it gets mentioned.
