### ISSUE TITLE
ControlBindingsConverter missing

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#2412]
* .NET Core Version: 5.0 master
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
WinForms [is referencing](https://github.com/dotnet/winforms/search?q=ControlBindingsConverter&unscoped_q=ControlBindingsConverter) `ControlBindingsConverter` but not providing an implementation for it.

**Actual behavior:**
The implementation of `ControlBindingsConverter` is not available

**Expected behavior:**
Either
* remove the reference via attribute and provide no replacement
* remove the reference via attribute but provide a replacement within the VS Designer environment
* port the converter to WinForms

The third option is required if the converter is supposed to be supported in 3rd party designers.

**Minimal repro:**
PR #2230 test failure when removing skip entry

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann can you see if there's anything urgent we need for data stuff in the designer?

**Comment by KlausLoeffelmann** [comment]
Closing this as per the discussion in #3444.
