### ISSUE TITLE
Question: Application.RenderWithVisualStyles is always false - how can we set it to true?

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2453]
Basically I want to test some code that is conditional on `Application.RenderWithVisualStyles`

The issue is that `Application.RenderWithVisualStyles` is always false

The docs (https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.application.renderwithvisualstyles?view=netframework-4.8 say
![image](https://user-images.githubusercontent.com/1275900/69901708-ed84d780-137c-11ea-9a89-c7f8f5654cf5.png)

Doing research, I found that `VisualStyleInformation.IsEnabledByUser` is always `false`

`VisualStyleInformation.IsEnabledByUser` is implemented as
```
/// <summary>
///  Returns true if a visual style has currently been applied by the user, else false.
/// </summary>
public static bool IsEnabledByUser => UxTheme.IsAppThemed().IsTrue();
```

Is there a way to make `UxTheme.IsAppThemed` return `true` when running tests from `dotnet test`? When we call `dotnet run`, this works!

**Comment by merriemcgaw** [comment]
@sharwell - do you happen to have any thoughts on this one?

**Comment by hughbe** [comment]
See https://github.com/dotnet/winforms/pull/2555#issuecomment-568297567. It seems like (at least our test projects) don't support ComCtl version 6.0

**Comment by hughbe** [comment]
Further investigation: #2564

Looks like theres a caching problem with `ComCtlSupportsVisualStyles` and `Application.UseVisualStyles`. See the PR for more details

**Comment by merriemcgaw** [comment]
@hughbe have you been able to resolve this? @RussKie thinks you may have, but I want to confirm
