### ISSUE TITLE
Microsoft.VisualBasic.PowerPacks doesn't work with .Net Core 3.1

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/winforms#2464]
* .NET Core Version: 3.1
* Have you experienced this same bug with .NET Framework?: YeNo

.Net Core 3.1 removed ContextMenu, but the Microsoft.VisualBasic.PowerPacks (https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/windows-forms/power-packs-controls)
Making it possible to create but not dispose them.

**Actual behavior:** 
```
System.TypeLoadException: Could not load type 'System.Windows.Forms.ContextMenu' from assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Microsoft.VisualBasic.PowerPacks.Shape.set_ContextMenu
   at Microsoft.VisualBasic.PowerPacks.Shape.Dispose(Boolean disposing)
```

**Expected behavior:**
Dispose should work

**Minimal repro:**
1. Download and reference Microsoft.VisualBasic.PowerPacks from the line above.
2. Create a LineShape and Dispose it again.

or sample .csproj
```<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic.PowerPacks">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\VBPowerPacks\v12.0\Microsoft.VisualBasic.PowerPacks.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
```

Program.cs:
```cs
			try
            {
                var sc = new Microsoft.VisualBasic.PowerPacks.ShapeContainer();
                sc.Dispose();
                var sc2 = new Microsoft.VisualBasic.PowerPacks.ShapeContainer();
                sc2.Shapes.Add(new Microsoft.VisualBasic.PowerPacks.LineShape());
                sc2.Dispose();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                throw;
            }
```

**Comment by RussKie** [comment]
If I understand it correctly Visual Basic Power Packs was made available during VS 2013 time. And it was offered as-is with no support:
    ![image](https://user-images.githubusercontent.com/4403806/70196719-c3a52980-175d-11ea-9fef-2fc8fc2f59d9.png)

So I don't think it is totally unreasonable that the library may not be 100% compatible with .NET Core.

@merriemcgaw @OliaG @KathleenDollard do you know anything about Microsoft.VisualBasic.PowerPacks or who may be an owner?
