### ISSUE TITLE
winform designer do not work after update into vs2019 v16.4.0 

### ISSUE THREAD

**Issue by valoni** [dotnet/winforms#2467]
* .NET Core Version: (e.g. 3.0 rtm and 3.1 rtm)

**Problem description:**
i did update of VS2019 to v16.4.0 from 16.3x (after update Windows form designer do not work)

after this i did unistalled vsix to reinstall again but now it show me message :

The extension  is already installed to all applicable products.????

**Comment by Westernstandard** [comment]
Getting the same error on two different machines in different environments.

**Comment by RussKie** [comment]
Can you try VS 16.5 P1? https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.5.0-pre.1.0
As per @OliaG's blog post https://devblogs.microsoft.com/dotnet/updates-to-net-core-windows-forms-designer-in-visual-studio-16-5-preview-1/ VS 16.5 P1 is required for the designer to work with 3.1.

**Comment by valoni** [comment]
@RussKie  we want existing (at least .NET Core 3.0 Windows Forms Desinger  to work on v16.4.0 no to install preview of visual studio completely since we are not allowed to use preview version of Visual Studio only extensions - because of ability to unistall them)

**Comment by SFC-Sarge** [comment]
Same issue for me and in VS 16.5 P1 I create a new Windows Forms Net Core 3.1 solution and when you right click on the form and select view designer, VS displays message that it is opening the file and never stops and VS Memory increases continuously. After 5 minutes It finally opens with blank Windows Forms (Empty as expected since it is a new solution.) My issue is why does it take so long to open a blank windows Form in the designer.

![vs Winform Message](https://user-images.githubusercontent.com/40568693/70624202-cd131380-1bed-11ea-82b7-13e59269294a.png)

**Comment by SFC-Sarge** [comment]
Update:  Once the first time the opening file took 5 minutes. Same and other solutions no-longer have this issue.

**Comment by merriemcgaw** [comment]
@SFC-Sarge if you continue to experience problems, please do file a VS Feedback item. That will help give us the telemetry that might help us figure out what the issue is.

**Comment by SFC-Sarge** [comment]
After repairing VS 2019 preview it now works loads slow the first time but then is find after the initial load. Just waiting for full functionality to be added. I only use it because WinPE does not support WPF applications, so limited to Windows Forms for workstation provisioning solutions.

**Comment by sgf** [comment]
winforms designer is very slow in vs 2019
normally not responding

**Comment by RussKie** [comment]
@sgf  please use VS Feedback (top right hand corner in VS) to report VS related issues.

**Comment by sgf** [comment]
> @sgf please use VS Feedback (top right hand corner in VS) to report VS related issues.

ok,tks
