### ISSUE TITLE
Code coverage appears to be broken

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2471]
Looks like reports are missing a “base” and we don’t have anything popping up on PRs

**Comment by RussKie** [comment]
Indeed! 

Looking at [Codecov](https://codecov.io/gh/dotnet/winforms), all is good:
![image](https://user-images.githubusercontent.com/4403806/70287906-ba32c480-1824-11ea-85ff-43b36f5a6fcf.png)

So I would speculate reports are not sent back to us. Perhaps something is broken at the org level.

@terrajobst any ideas?

**Comment by terrajobst** [comment]
@hughbe @RussKie I don't follow. Where is the base missing?

@sharwell knows more about CodeCov than I do.

**Comment by sharwell** [comment]
Yep I can look in the morning

**Comment by sharwell** [comment]
I submitted #2480 to fix this.
