### ISSUE TITLE
Windows.Forms.MonthCalendar control throws NullReferenceException

### ISSUE THREAD

**Issue by coderesx** [dotnet/winforms#2475]
Windows.Forms.MonthCalendar controls throws NullReferenceException when the user clicks to change the date

# General

This is a new issue in  .NET Core 3.1. It worked fine in .NET Core 3.0
Operating System is Windows 10 Pro.
This happens if the MinDate and MaxDate are set.

I attached a sample to reproduce the issue.

[WindowsFormsCoreApp1.zip](https://github.com/dotnet/core/files/3927891/WindowsFormsCoreApp1.zip)

I should have posted this to dotnet/winforms. Sorry about that.

**Comment by RussKie** [comment]
@M-Lipin @vladimir-krestov could you have a look, it may be related to some work done recently

**Comment by RussKie** [comment]
Fixed in #3041
