### ISSUE TITLE
WebBrowser.ObjectForScripting doesn't work

### ISSUE THREAD

**Issue by albahari** [dotnet/winforms#248]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
Microsoft.WindowsDesktop.App 3.0.0-alpha-27128-4

* Have you experienced this same bug with .NET Framework?: No

**Problem Description**

When you set the ObjectForScripting property on a WebBrowser control and then click a link that calls a method on the ObjectForScripting, it displays a script error dialog instead of calling the specified method.

**Actual behavior:** 

Script error dialog - "An error has occurred in the script on this page. Unexpected call to method or property access"

**Expected behavior:**

It should call the specified method on ObjectForScripting as it does in .NET Framework

**Minimal repro:**

[ObjectForScripting.zip](https://github.com/dotnet/winforms/files/2684303/ObjectForScripting.zip)

**Comment by AaronRobinsonMSFT** [comment]
This issue can be closed as it is a bug in coreclr and fixed by https://github.com/dotnet/coreclr/pull/22930.

**Comment by AaronRobinsonMSFT** [comment]
@albahari This has been fixed in coreclr. Feel free to check this out in the next nightly - https://github.com/dotnet/core-sdk#installers-and-binaries. Thanks for finding this!
