### ISSUE TITLE
The value of SplitterWidth cannot be set successfully after changing the SplitterConatiner .SplitterWidth

### ISSUE THREAD

**Issue by Marie-Shi** [dotnet/winforms#2490]
.NET Core Version: .NET Core 3.1.101-servicing-014750 from Release branch + the VSIX Inserted into Dev16 16.5.0 Preview 2.0 [29605.132.master]
Have you experienced this same bug with .NET Framework?: Yes

**More Info:**
1.	This issue can reproduce with .Net Framework project from .Net4.0 to latest .Net4.8.
2.	This issue cannot reproduce if SplitterConatiner isn’t within panel container.

**Steps to reproduce:**
1.	Launch VS and create a .Net Framework project.
2.	Add a Panel to the form, and drag and drop a SplitterConatiner to Panel.
3.	Set SplitterWidth property of SplitterConatiner in property browser window to 8 (or something other than 4).
4.	In Form1_Load event add this.splitContainer1.SplitterWidth.ToString();
5.	Migrate the code of Framework app to Core app, and run the core app.
[SplitterContainer_SplitterWidth.zip](https://github.com/dotnet/winforms/files/3937691/SplitterContainer_SplitterWidth.zip)

**Actual Result:**
SplitContainer1.SplitterWidth return 4 not 8 after running the app.
![SplitterWidth_Core](https://user-images.githubusercontent.com/45864017/70403677-89e06580-1a72-11ea-95ad-a7d5218c3860.png)

**Expected Result:**
SplitContainer1.SplitterWidth should return 8 after running the app.
![SplitterWidth_Expected](https://user-images.githubusercontent.com/45864017/70403682-8cdb5600-1a72-11ea-944f-bf757a672777.png)

**Comment by John-Qiao** [comment]
In my testing result, this issue still can repro in .NET Core 3.1 and .NET 5.0, but it cannot repro in .NET 6.0 and .NET 7.0 now.
