### ISSUE TITLE
迁移到.NetCore3.1后窗口变形严重

### ISSUE THREAD

**Issue by 199621616** [dotnet/winforms#2503]
将基于.Net Framework 4.6.1的WinForm迁移到.Net Core 3.1后窗口变形严重。是我错过了什么，还是.Net Core 3.1本是如此？需要我们根据.Net Core 3.1再调整，还是需要你们修复？
下图左右两个窗口差距很大，代码没有任何变动。
![image](https://user-images.githubusercontent.com/25498672/70848165-61a89a80-1ea8-11ea-9037-ccf53c4c399a.png)

**Comment by 199621616** [comment]
![image](https://user-images.githubusercontent.com/25498672/70848077-5a34c180-1ea7-11ea-8f9d-bbfead0b9425.png)

**Comment by RussKie** [comment]
@199621616 please write in English if you require assistance.

@Olina-Zhang is this something you can read?

**Comment by maikebing** [comment]
@199621616    add   `  Application.SetHighDpiMode(HighDpiMode.SystemAware); ` to  
 static void Main(string[] args)

**Comment by 199621616** [comment]
After migrating WinForm based on. Net framework 4.6.1 to. Net core 3.1, the window is seriously deformed. What did I miss, or did. Net core 3.1 originally? Do we need to readjust according to. Net core 3.1, or do you need to fix it?

The left and right windows in the figure below are quite different, and the code has no change.

**Comment by 199621616** [comment]
add Application.SetHighDpiMode(HighDpiMode.SystemAware); to
static void Main(string[] args)
No change.

**Comment by Vino-Wang** [comment]
@199621616 @RussKie, maybe this is caused by issue https://github.com/dotnet/winforms/issues/1122. And this is a by design issue, the default Font size is changed in Core project,

**Comment by RussKie** [comment]
@199621616, yes this is the most likely reason, depending on values of `AutoScaleDimensions`and `AutoScaleMode` properties of the form.

Please have a look at the docs that detail breaking and other notable changes:
* docs.microsoft.com/en-us/dotnet/core/porting/winforms-breaking-changes
* docs.microsoft.com/en-us/dotnet/core/compatibility/winforms

**Comment by 199621616** [comment]
@Thank you very much to vino Wang and @ russkie. After setting the default font to font = new font (New fontfamily ("Microsoft sans serif"), 8F), the problem has been resolved. This issue is closed.
