### ISSUE TITLE
FileDialog/FolderBrowserDialog should fall back to legacy dialog on COMException

### ISSUE THREAD

**Issue by kpreisser** [dotnet/winforms#2506]
* .NET Core Version: `master` (7dee30995829711ac3a486f672cede1171ab4eb1)
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**

When [`FileDialog.AutoUpgradeEnabled`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog.autoupgradeenabled?view=netcore-3.1)/[`FolderBrowserDialog.AutoUpgradeEnabled`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.folderbrowserdialog.autoupgradeenabled?view=netcore-3.1) is `true` (the default), the newer COM-based Vista File Dialog will be shown instead of the legacy file dialog.

However, on Windows Server that was installed using the "Server Core" option, these COM components may not available. While Server Core normally isn't suited to run GUI applications, you can install the [**Server Core App Compatibility Feature on Demand (FOD)**](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19) package that improves compatibility for GUI applications by installing additional components, including `explorer.exe` (as file browser). E.g., SQL Server Management Studio is fully functional on Server Core with the App Compatibility FOD installed.

While that package normally also installs the COM components required to show the Vista file dialog, in some cases (e.g. after installing certain Windows Updates) these components can become unavailable again, and the Vista File Dialog will no longer work. 

**Actual behavior:** 
When the COM components required for the Vista file dialog are not available, calling `OpenFileDialog.ShowDialog()` results in a **`COMException`** (`CLASS_E_CLASSNOTAVAILABLE`):

```
System.Runtime.InteropServices.COMException (0x80040111): Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
   at System.Windows.Forms.OpenFileDialog.CreateVistaDialog()
   at System.Windows.Forms.FileDialog.RunDialogVista(IntPtr hWndOwner)
   at System.Windows.Forms.FileDialog.RunDialog(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.CommonDialog.ShowDialog()
```

A similar stack occurs for `FolderBrowserDialog.ShowDialog()`:
```
System.Runtime.InteropServices.COMException (0x80040111): Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
   at System.Windows.Forms.FolderBrowserDialog.RunDialogVista(IntPtr owner)
   at System.Windows.Forms.FolderBrowserDialog.RunDialog(IntPtr hWndOwner
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.CommonDialog.ShowDialog()
```

**Expected behavior:**
When instantiating the COM object fails, I think the dialog should automatically fall back to the legacy file dialog, which seems to be done by most native applications like `notepad.exe` (see repro steps).
This will allow WinForms applications using a `FileDialog` or `FolderBrowserDialog` to work correctly on Windows Server Core with App Compatibility FOD installed, instead of crashing due to the `COMException`.

**Minimal repro:**
* Install Windows Server 2019 (using ISO image from [MS Evaluation Center](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019)), using option `Windows Server 2019 Standard Evaluation` (not with "Desktop Experience").
* After installation is finished, install the [Server Core App Compatibility FOD](https://docs.microsoft.com/en-us/windows-server/get-started-19/install-fod-19) in Powershell with `Add-WindowsCapability -Online -Name ServerCore.AppCompatibility~~~~0.0.1.0`, and then restart the machine.
* On another machine, create a new WinForms app with `dotnet new winforms` and use the following code in `Program.cs`:
```c#
using System;
using System.Windows.Forms;

class Program
{
    [STAThread]
    static void Main()
    {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);

        var dialog = new OpenFileDialog();
        dialog.ShowDialog();
    }
}
```
* Publish the app with `dotnet publish -f netcoreapp5.0 -r win-x64`.
* Copy the published app to the Windows Server machine and run it.
* Notice the file dialog is correctly shown using the Vista file dialog. Also, when you start `notepad.exe` and select `File`->`Open`, it shows the Vista file dialog:
![grafik](https://user-images.githubusercontent.com/13289184/70863732-5b1f2f00-1f4b-11ea-9486-b974fc86f084.png)
* Now download and install [`2019-12 Cumulative Update for Windows Server 2019 for x64-based Systems (KB4530715)`](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4530715), and restart the machine.
* Run the app again. Notice it fails with a **`COMException`** (see stacktrace above).
* When running `notepad.exe` and selecting `File`->`Open`, you can see that the legacy file dialog is shown:
![grafik](https://user-images.githubusercontent.com/13289184/70863741-8d309100-1f4b-11ea-92cb-b5a6d9cda9cc.png)

**Workaround**

You can work around the issue by catching `COMException` and disabling `AutoUpgradeEnabled`:
```c#
        try
        {
            dialog.ShowDialog();
        }
        catch (COMException) when (dialog.AutoUpgradeEnabled)
        {
            dialog.AutoUpgradeEnabled = false;
            try
            {
                dialog.ShowDialog();
            }
            finally
            {
                dialog.AutoUpgradeEnabled = true;
            }
        }
```

**Comment by RussKie** [comment]
Thank you for the very detailed report!
I think it is a sensible proposal. @merriemcgaw @JeremyKuhne any objections?

@Vino-Wang we'll need to test this scenario. Could you please set up a test environment, I'll provide you with private binaries with a fix,

**Comment by merriemcgaw** [comment]
I think this is a very logical proposal and would support a PR that implements it.

**Comment by Vino-Wang** [comment]
@RussKie, I have send the result about setting up the repro environment in email, please check it.
