### ISSUE TITLE
'PermissionSet' could not be found.

### ISSUE THREAD

**Issue by pottereric** [dotnet/winforms#252]
I just cloned the repo last night. When I try to build the application, I get 4 errors that say:
"The type or namespace name 'PermissionSet' could not be found".

I have the latest preview of the SDK installed. (3.0.100-preview-009812)

Is there something else that I need?

**Comment by AdamYoblick** [comment]
Hi there,

I just pulled master and I'm not able to repro this. Are you referring to building a winforms application, or building the winforms source?

**Comment by pottereric** [comment]
I am trying to build the WinForms source. More specifically, I am trying to build the Winforms.sln in the root of this repository.

**Comment by AdamYoblick** [comment]
Are you building through Visual Studio or command line? Does this repro when you run .\build.cmd?

**Comment by pottereric** [comment]
I tried building in Visual Studio 2017. I tried building with the "dotnet build" cli. I tried building with build.cmd. I got the same thing every time.

**Comment by AdamYoblick** [comment]
There are some other pre-reqs you need installed in order to build this source, did you follow the steps at https://github.com/dotnet/winforms/blob/master/Documentation/developer-guide.md ?

**Comment by pottereric** [comment]
I had been missing the C++ workload and components. But now I have them installed. When I execute build.cmd, I still get the same 4 build errors related to missing the PermissionSet type.

**Comment by zsd4yr** [comment]
Is this related to https://github.com/dotnet/corefx/pull/33379 ?

**Comment by AdamYoblick** [comment]
hi @pottereric I believe this is resolved with the latest sdk  (3.0.100-preview-009844.), can you confirm?

**Comment by AdamYoblick** [comment]
Glad we could get it fixed quickly. Thanks for reporting this :)
