### ISSUE TITLE
An exception pops up when executing these methods: ImageList.Images.Clear() and ListViewItem.ImageList.Image.Clear()

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#2522]
* .NET Core Version: (.NET Core 5.0 5.0.100.15949 5.0.0-alpha.1.19617.3 )
* Have you experienced this same bug with .NET Framework?: No

**More Info**
1. This issue cannot reproduce with Framework app.
2. This issue cannot reproduce when targeting .NET Core 3.1.

**Problem description:**
An exception pops up when the cases implement the following affected methods: ImageList.Images.Clear() and ListViewItem.ImageList.Image.Clear()

**Actual behavior:** 
An exception pops up.
![Actual](https://user-images.githubusercontent.com/18568603/71078995-5ebdea80-21c5-11ea-8024-6792c37e2e46.PNG)

**Expected behavior:**
There should no any exception popping up.

**Minimal repro:**
1.	Run the attached project. 
[ImageClearIssue.zip](https://github.com/dotnet/winforms/files/3977900/ImageClearIssue.zip)

2.	Click the any of the buttons on the form, then wait seconds.

**Comment by hughbe** [comment]
I have a fix

**Comment by Amy-Li02** [comment]
Verified this issue with .Net Core 5.0.100-alpha.1.20064.2 from Master branch + Dev16 16.5.0 Preview 3 [29713.105.master], this issue is fixed. There is no exception thrown when executing methods: ImageList.Images.Clear() and ListViewItem.ImageList.Image.Clear().
