### ISSUE TITLE
Winforms controls’ ProductName property should have a meaningful description in .Net Core, compared to .Net Framework

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#254]
**OS:** RS5/RS6 
**VS:** 16.0.0.0 Preview 2.0 [28416.104.d16.0stg] + .Net Core 3.0 latest build

**Steps to Reproduce:**
1. Create a Winforms .Net Core application by command: dotnet new winforms –o “xxx”
2. Write code to check any Winforms control’s productName property
	_System.Windows.Forms.Button button = new Button();
       string productName = button.ProductName;_

**Actual:** 
 In .Net Core, it should have a meaningful description for controls’ ProductName property, not just “System.Windows.Forms”
![netcore](https://user-images.githubusercontent.com/26474449/50150409-b8b66800-0272-11e9-841d-9a2205e7f1ba.png)

**Expected:**
In .Net framework, the controls’ ProductName is “Microsoft® .NET Framework”.
![netframework](https://user-images.githubusercontent.com/26474449/50150428-d1268280-0272-11e9-872d-f22730928afd.png)

**Comment by zsd4yr** [comment]
@Tanya-Solyanik is this due to 

```cs
                        // fake it with namespace
                        // won't work with MC++ see GetAppMainType.
                        if (productName == null || productName.Length == 0) {
                            Type t = GetAppMainType();

                            if (t != null) {
                                string ns = t.Namespace;

                                if (!string.IsNullOrEmpty(ns)) {
                                    int lastDot = ns.LastIndexOf(".");
                                    if (lastDot != -1 && lastDot < ns.Length - 1) {
                                        productName = ns.Substring(lastDot+1);
                                    }
                                    else {
                                        productName = ns;
                                    }
                                }
                                else{
                                    // last ditch... use the main type
                                    //
                                    productName = t.Name;
                                }
                            }
                        }
```

in the get for System.Windows.Forms.Application.ProductName?

**Comment by zsd4yr** [comment]
Actually, I think it's more likely to be the get for ProductName in the ControlVersionInfo class in Control.cs since this is about a button.

```cs
                        if (productName == null || productName.Length == 0) {
                            string ns = owner.GetType().Namespace;

                            if (ns == null) {
                                ns = String.Empty;
                            }
                            int firstDot = ns.IndexOf(".");
                            if (firstDot != -1) {
                                productName = ns.Substring(firstDot+1);
                            }
                            else {
                                productName = ns;
                            }
                        }
```

The code appears very similar.

**Comment by OliaG** [comment]
Might be helpful to look at the old FX code to see how it worked

**Comment by merriemcgaw** [comment]
@OliaG we need to decide what ProductName to display, and make it consistent with WPF on .NET Core. Can you please tell us what name we want to use?

**Comment by merriemcgaw** [comment]
@oliag to confirm ".NET Core" or ".NET Core Desktop Shared Framework" or something

**Comment by zsd4yr** [comment]
@OliaG 🙏

**Comment by zsd4yr** [comment]
related to #485

**Comment by merriemcgaw** [comment]
Let's go with ".NET Core."

**Comment by merriemcgaw** [comment]
On second thought, let's do "Microsoft .NET"

**Comment by OliaG** [comment]
Yes, I believe we are keeping the trademark next to "Microsoft", so "Microsoft® .NET"

**Comment by RussKie** [comment]
A quick test, the product name comes from `AssemblyProductAttribute`:
![image](https://user-images.githubusercontent.com/4403806/59899709-12be0300-9439-11e9-942a-e740faa71ffc.png)

That is set at the project level:
![image](https://user-images.githubusercontent.com/4403806/59899761-3e40ed80-9439-11e9-8d48-49d549caa4f8.png)
