### ISSUE TITLE
Fix MenuStrip hover & click behavior in unfocused windows

### ISSUE THREAD

**Issue by chylex** [dotnet/winforms#2544]
(split off from #2476)

This issue addresses two differences between native MainMenu and MenuStrip controls when the window is unfocused.

### Issue 1 : Hovering menu items highlights them in an unfocused window
Native control on the right side only highlights hovered items when the window is focused. This also causes confusion with issue 2.

![unfocused](https://user-images.githubusercontent.com/3685160/71302833-64c3ef00-23b0-11ea-9846-001262d4af04.png)

### Issue 2 : Clicking a menu item in unfocused window does not open it
To reproduce, open the test project which opens 2 windows as seen on the screenshot above, click the taskbar or another window to unfocus them, and then click **Item 1** in each window. You will see that:

* In the **FormStripSystem** window which uses a MenuStrip, clicking highlights the window but does not open the menu. State after clicking:
![focusedstrip](https://user-images.githubusercontent.com/3685160/71302930-b1f49080-23b1-11ea-98b8-6b62a38c3c4e.png)

* In the **FormNative** window which uses a native MainMenu, clicking both highlights the window and immediately opens the menu. State after clicking:
![focusednative](https://user-images.githubusercontent.com/3685160/71302939-d3ee1300-23b1-11ea-8859-78f97636a412.png)

The behavior of MenuStrip should be changed to match the native control.

As I said in https://github.com/dotnet/winforms/issues/2476#issuecomment-567316912, I tested several applications with both native MainMenu and completely custom menu controls, all of which follow the native Windows behavior, so the non-standard behavior of MenuStrip is likely confusing to Windows users.

### Test Project

[winforms.zip](https://github.com/dotnet/winforms/files/3990977/winforms.zip)

**Comment by elachlan** [comment]
@chylex please see #9288

**Comment by elachlan** [comment]
@merriemcgaw this shouldn't be stale. Waiting on team to do API/PR review.

**Comment by merriemcgaw** [comment]
Thanks @elachlan! I'll mark it as waiting on team and we'll take care of it soon.

**Comment by Nora-Zhou01** [comment]
Verified this issue on 9.0.100-preview.7.24360.15 with dlls built from winforms repo of main branch, focused and unfocused windows now behave in the same way, highlighting the hovered item and clicking on the window's menu item immediately opens it.

https://github.com/dotnet/winforms/assets/104609169/bf522a4d-c635-4666-b770-bb3f34ab875a

**Comment by John-Qiao** [comment]
Verified the issue with .NET 9.0.100-preview7.24402.8 test pass build, it has been fixed and the test result is same as above.
