### ISSUE TITLE
Can test WinForms under Visual Studio

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#2580]
* .NET Core Version: (Microsoft.WindowsDesktop.App 5.0.0-alpha.1.19625.3)
* Have you experienced this same bug with .NET Framework?: Yes/No
N/A
**Problem description:**
Following instructions on testing https://github.com/dotnet/winforms/blob/master/Documentation/testing-in-vs.md
very bottom Solution 2 does not work and you get the error below
**Actual behavior:**
```
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0-alpha1.19514.1&arch=x64&rid=win10-x64
. Please check the diagnostic logs for more information.
```
**Expected behavior:**
Expect tests to run or there is a place to download the required framework.
**Minimal repro:**
Clone Winform Repo
Run .\build-local.ps1
Open VB 2019 16.5.0 Preview 1
Run any test and in the Output/Test Window you will see error above and test does not run

**Comment by paul1956** [comment]
This issue can't be reproduced under current daily build of .NET Core SDK version 
![image](https://user-images.githubusercontent.com/12789369/71497148-c4d0f000-280b-11ea-8ac3-ff4ee53897c7.png)

**Comment by RussKie** [comment]
Daily .NET 5 builds can be incoherent, and sometimes may not work.

**Comment by paul1956** [comment]
@RussKie yes I notices, they depend on a daily build of Core and changes to WinForm Master and unless they match things break, the Command Line build always seems to work. Testing and Building under Visual Studio is where I see issues.  That is why I close this issue.

**Comment by RussKie** [comment]
We have a `build-local.ps1` script that creates a sym-link from the repo's .dotnet folder to the global one, tricking VS to use the dev version. However it may fail if the bundle's internal versions don't match. It can typically can be worked around by renaming folders to match...
I have also updated the global.json bumping the sdk version.

**Comment by paul1956** [comment]
@RussKie Yes,  I run that script and it does sometimes require that I rename (or copy) the new Core folder to the name the script wants (easy workaround).  That is not the issue, after the script runs **successfully** sometimes when you try to run a test VS complains it can't find a framework on the Web as shown in the error above. Upgrading Core Daily build and/or WinForms build makes it go away until another upgrade or pull, I closed because I think that is the nature of working with daily builds and I don't have a suggestion on keeping them in sync.
