### ISSUE TITLE
VB Core projects allow adding About.vb and SplashScreen.vb which are not core compatible

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#2608]
I was asked to file this as a place holder for what is needed in new About and SplashScreen Templates for .Net Core and maybe to prevent the current forms from being added to a Core project
* .NET Core Version:
```
Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
* Have you experienced this same bug with .NET Framework?: No
**Problem description:**
In a VB project ported to core with a SplashScreen or About form or where one is add by Visual Studio Add New Item, the forms added are not compatible with Core.
**Actual behavior:** 
There are 8 errors about My.Application is not a member of ..
**Expected behavior:**
Either the default form has not errors are they are disabled and core compatible Forms are available.
**Minimal repro:**

**Comment by merriemcgaw** [comment]
Can @KlausLoeffelmann or @KathleenDollard  post an update here?

**Comment by KlausLoeffelmann** [comment]
@KathleenDollard: Let's discuss this.

**Comment by paul1956** [comment]
@KlausLoeffelmann @KathleenDollard This is fixed in 5.0.0-rc.2.20466.10, the Framework forms are now source compatible with Core and they just work without required changes. (Ignoring the new default font which effects every Form) and a very minor issue below.

In Framework My.Application.Info.Title "Application" is REQUIRED, in .NET "Application" is not needed IDE0002.

I will not close but IMO it should be closed as fixed.

**Comment by KlausLoeffelmann** [comment]
That, @paul1956. I will also take a closer look at this again this week.

**Comment by John-Qiao** [comment]
Verified with 7.0.100-preview.6.22316.8 from main branch, the VB Core project can be built successfully without any error after added AboutBox and SplashScreen forms, so closed this issue now.
![TestResult5](https://user-images.githubusercontent.com/45864985/174552079-e2394931-54e0-440f-9af8-e738ccac5dd1.png)
