### ISSUE TITLE
The winforms .NET Core app build error after installed .NET Core 5.0 SDK

### ISSUE THREAD

**Issue by Amy-Li02** [dotnet/winforms#2613]
* .NET Core Version: .NET Core SDK 5.0.100 - alpha1 5.0.100.16134
* Have you experienced this same bug with .NET Framework?: No

**More info:**
1. The winforms .NET Core app build error after installed .NET Core 5.0 SDK, no matter targeting .NET Core 3.1 or .NET Core 5.0.
2. The WPF .NET Core app also reproduce this issue.
3. The Console .NET Core app cannot reproduce this issue.

**Actual behavior:** 
After build the winforms .NET Core app, some error message pops up. [ErrorMessage.txt](https://github.com/dotnet/winforms/files/4014769/ErrorMessage.txt)
![Error](https://user-images.githubusercontent.com/49627022/71648977-d4899080-2d45-11ea-8925-0abe02fbdb63.PNG)

**Expected behavior:**
The winforms .NET Core app should build successfully.

**Minimal repro:**
1. Install .NET Core 5.0 SDK latest build from here:  https://github.com/dotnet/core-sdk.
2. Create a winforms .NET Core app.
2. Build this app.

**Comment by RussKie** [comment]
This isn't WinForms specific, and should be filed in https://github.com/dotnet/windowsdesktop

@dagood any thoughts on this?

**Comment by eriawan** [comment]
@Amy-Li02 

As far as I know, current .NET Core 5.0 SDK aren't integrating WinForms /WPF component yet and until now there's no VS 2019 for .NET Core 5.0 SDK. (NOTE: Feel free to correct me if I'm wrong about this, @RussKie )

For now you should use `global.json` to enforce compilation with SDK that are released, such as 3.0.x or 3.1.x.
On your folder of the solution file, add global.json file, create new global.json that use .NET Core 3.0 or 3.1 SDK.

Open command prompt and do this:

```
dotnet new global.json --sdk-version 3.1.100
```

You can also replace the SDK version with released 3.0.x, such as 3.0.100 or 3.0.101 as long as these SDKs are already installed on your machine. 
Then the next build/compile will use the .NET SDK of your choice.

**Comment by RussKie** [comment]
Windows Forms and WPF are bundled into the nightly SDK setup, and are available for download from https://github.com/dotnet/core-sdk.
	![image](https://user-images.githubusercontent.com/4403806/71702649-d37b6080-2e24-11ea-9b3d-57d99c88a47b.png)
	![image](https://user-images.githubusercontent.com/4403806/71702700-12111b00-2e25-11ea-9e48-4372237d6883.png)


However because of fluent nature of development builds not all bundles are coherent and may contain invalid references or missing files.

**Comment by dagood** [comment]
> This isn't WinForms specific, and should be filed in https://github.com/dotnet/windowsdesktop
> 
> @dagood any thoughts on this?

The package is built in dotnet/wpf, not dotnet/windowsdesktop, so I'd argue it belongs there: https://github.com/dotnet/wpf/tree/master/packaging/Microsoft.NET.Sdk.WindowsDesktop. However, there might be some other problem causing the zip to end up wrong in dotnet/core-sdk or dotnet/toolset.

**Comment by Amy-Li02** [comment]
Filed a new issue here: https://github.com/dotnet/wpf/issues/2400

**Comment by RussKie** [comment]
The issue is reported as fixed in https://github.com/dotnet/wpf/issues/2363
