### ISSUE TITLE
What happened to ContextMenu/MenuItem UI classes?

### ISSUE THREAD

**Issue by speed2048** [dotnet/winforms#2614]
.Net core 3.1.1000

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

When I updated to .net core 3.1 and ran my windows application I get the following exception.

System.TypeLoadException: Could not load type 'System.WIndows.Forms.ContextMenu' fro assembly 'System.Windows.Forms', Version 4.0.0 ....

There are no compile / link errors.

Had to switch to ContextMenuStrip and ToolStripMenuItem UI classes to get rid of the exception errors.

Would like there to be documentation or deprecation notifications for these classes.

**Comment by RussKie** [comment]
`ContextMenu` and `ToolStrip` controls as well as few others have been deprecated in .NET Core 3.1 (see https://github.com/dotnet/winforms/pull/2157).

Their removal has been [documented](https://docs.microsoft.com/en-us/dotnet/core/porting/winforms-breaking-changes#net-core-31) and [announced in a .NET Core 3.1 blog post](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/).

**Comment by speed2048** [comment]
Thank you, however the following link still has references to net core 3.1.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.menu?view=netframework-4.8


Also I found out that although I had 3.1 installed the Target Framework in VS was set to 3.0 hence no errors at compile / link time.

**Comment by RussKie** [comment]
> Thank you, however the following link still has references to net core 3.1.

Thank you for bringing this to our attention, I've raised it to the docs team.

**Comment by chucker** [comment]
@RussKie can we make it so the .NET Core 3.0 docs show it as deprecated, so it's a little clearer why it disappears in 3.1? This text isn't clear enough, I think:

>Although ToolStripDropDown and ToolStripDropDownMenu replace and add functionality to the Menu control of previous versions, Menu is retained for both backward compatibility and future use if you choose.

(Maybe change it to "_was_ retained _up until .NET Core 3.0_" or something?)

Also, I don't know if you can ping someone about https://apisof.net/catalog/System.Windows.Forms.MenuItem, because that, too, suggests that .NET Core 3.1 should have the API.

**Comment by RussKie** [comment]
> can we make it so the .NET Core 3.0 docs show it as deprecated, so it's a little clearer why it disappears in 3.1? This text isn't clear enough, I think:
> 
> > Although ToolStripDropDown and ToolStripDropDownMenu replace and add functionality to the Menu control of previous versions, Menu is retained for both backward compatibility and future use if you choose.
> 
> (Maybe change it to "_was_ retained _up until .NET Core 3.0_" or something?)

@gewarren is this something we can do?

> ping someone about [apisof.net/catalog/System.Windows.Forms.MenuItem](https://apisof.net/catalog/System.Windows.Forms.MenuItem), because that, too, suggests that .NET Core 3.1 should have the API.

@OliaG @terrajobst is that something you maintain?

**Comment by gewarren** [comment]
> @gewarren is this something we can do?

I'm cleaning the docs up now.
