### ISSUE TITLE
Cannot open the Winforms .Net Core application in d15.9 version of VS

### ISSUE THREAD

**Issue by Botao-Liu** [dotnet/winforms#262]
**OS**: RS5 X64
**VS**: Dev15 d15.9 28307.253 + .Net Core 3.0.100-Preview-009844

**More Info**: This issue cannot repro in Dev16 d16.0stg latest build.

**Steps to Reproduce**:
1. install d15.9 version of VS and .net core 3.0
2. Create a Winforms NETCore template application using command: dotnet new winforms -o MyWinformsApp
3. open the application using VS.

**Actual:**
VS cannot open the Winforms .Net Core application, and receive following error:
![11121121](https://user-images.githubusercontent.com/45864989/50259842-c6214d00-0440-11e9-8b30-3db58bad5552.png)

**Expected:**
VS can open the Winforms .Net Core application successfully.

**Comment by merriemcgaw** [comment]
You should use the latest Preview releases of Visual Studio 2019. Closing this issue

**Comment by DmitryGaravsky** [comment]
To work with the WinForms .Net Core3 projects in VS2017 you should enable the "Use previews of the .Net Core SDK" option in Visual Studio options. 
To accomplish this task open the Options window (Menu->Tools->Options...) and type the ".net core" in the search box:
![vs2017 netcore](https://user-images.githubusercontent.com/8652582/50328424-1b726280-0504-11e9-8742-0d76435df970.png)
