### ISSUE TITLE
VB AssemblyInfo.Info.Title is not the same in Framework and Core

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#2637]
* .NET Core Version: Master
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
In Framework the Title is a human readable string set in Visual Studio/Project/Application/Assembly Information Title property. In Core it is AssemblyTitleAttribute which comes from the Assembly name and not something the user can change (without effecting the application)
**Actual behavior:**
You get "WindowsApp2Framework"
![image](https://user-images.githubusercontent.com/12789369/71793202-b2676b00-2ff0-11ea-8a95-343569758112.png)
**Expected behavior:**
"Windows App 2 Framework"
Something the user enters in a Title field. This filed is what is displayed by About and Splash Screens. There is a Product field already which may have the correct information but not used in existing Form templates.
**Minimal repro:**

**Comment by merriemcgaw** [comment]
fyi @KathleenDollard

**Comment by Thraka** [comment]
I cannot reproduce this. I added `<Assembly: AssemblyTitle("This is the title")>` to the `AssemblyInfo.vb` file and it worked file. I then deleted the `AssemblyInfo.vb` and added `<AssemblyTitle>This is a title for fun!</AssemblyTitle>` to the project file and that also worked.

**Comment by paul1956** [comment]
I have never manually created an <AssemblyTitle> and there is no Core AssemblyInfo.vb file (yet) and if you copy it from an Framework project and go through all the workarounds it a static file without title. The information for everything except Title comes from Visual Studio in a new location. I now learned that I can edit a core project file and add a title manually, this should be documented. VS should be filling the title in the "project" file like it did in Framework in AssemblyInfo.vb.

**Comment by weltkante** [comment]
I think the point is that when you edit the title in the VS project UI it doesn't arrive in the compiled output? As far as I understand the OP issue description the VS project UI has a field where you can enter the assembly title and in classic projects it gets stored (by VS) in AssemblyInfo, but in .NET Core it doesn't work.

Or maybe I also misunderstood and this is only a documentation problem?

**Comment by paul1956** [comment]
@weltkante Very close, there is no place (I can find) to enter a title in a Core project in the VS UI. So most code including Core 5.0 defaults to something that is not something that can be changed from the UI and is generally not what the developer wants.

**Comment by Thraka** [comment]
When I created a new project for .NET Framework, assembly title is in the `AssemblyInfo.vb` file (which is hidden from you in visual studio unless you toggle the **Show all files** button in **Solution Explorer**. When you port the project (using **try-convert**) the assembly info file remains.

Correct though, Visual Studio doesn't have UI to edit these fields. You can see the fields and the associated attribute they replace here: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#properties-per-attribute It sounds more like your issue is related to the lack of this dialog in Visual Studio. I tried searching https://developercommunity.visualstudio.com/spaces/8/index.html for an existing bug/feature request related to this, but I didn't find one. I think that would be the appropriate place to create it.

**Comment by paul1956** [comment]
@Thraka Yes that is the issue, not where I started since I was describing the issue from a user prospective. So it looks like this is a VS Issue not a WinForms issue. I will close this and send feedback there.

**Comment by paul1956** [comment]
For Completeness VS has a UI for all properties EXCEPT Title, they are just entered in a different place.

**Comment by Thraka** [comment]
Where are those? I can't find them. AFAIK there is no place to enter this info in Visual Studio for .NET Core. You must edit the project file directly.

**Comment by paul1956** [comment]
They are under Project Properties/Package and they end up in the Project File.

**Comment by paul1956** [comment]
@Thraka 
![image](https://user-images.githubusercontent.com/12789369/73531113-9c21b480-43ce-11ea-9ae1-c53d7a9f7393.png)
![image](https://user-images.githubusercontent.com/12789369/73531180-c2dfeb00-43ce-11ea-9503-57a9151a6f0f.png)
