### ISSUE TITLE
Null reference types for the Windows Forms API surface

### ISSUE THREAD

**Issue by Logerfo** [dotnet/winforms#2643]
I think this isn't tracked yet. Any projections or concerns?

**Comment by hughbe** [comment]
https://github.com/dotnet/winforms/issues/1107

**Comment by RussKie** [comment]
It is worth noting that enabling nullable decorations does not prevent NREs, they are only hints for the compiler.

The team doesn't have any immediate or medium term plans to retrofit existing APIs with decorations. However we will accept PRs from anyone who's keen on working on it.

Please continue further discussions in #1107.
