### ISSUE TITLE
Add support for footers to ListViewGroup

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2653]
- You can set the `LVGF_FOOTER` flag on `mask` and set `pszFooter` to a valid string and `cchFooter` to the length of the string
- You can set the `LVGF_ALIGN` flag on `mask` and set the `uAlign` to a valid `LVGA_FOOTER_CENTER` value

## Proposed API
This would add the following APIs to `ListViewGroup`:
```cs
public class ListViewGroup
{
    ...
    public string Footer { get; set; }
    public HorizontalAlignment FooterAlignment { get; set; }
    ...
}
```

## Example

```cs
var group = new ListViewGroup
{
     Footer = "NewFooter",
     FooterAlignment = HorizontalAlign.Center
};
```

![image](https://user-images.githubusercontent.com/1275900/71745879-66d38680-2e63-11ea-82f7-5381a58bd045.png)

**Comment by RussKie** [comment]
The team had some preliminary discussions about enhancing the control. 
Could you spare few minutes and provide answers to the following questions so we can take it to the next level:

- Will VS Designer need to support the feature? If yes, describe _how_ you expect it to funсtion.
- What impact will it have on accessibility?
- Will this feature need to be localized or be localizable?

**Comment by hughbe** [comment]
> Will VS Designer need to support the feature? If yes, describe how you expect it to function.

Yes. I would expect "Footer" and "FooterAlignment" to appear in the following editor (same as "Header" and "HeaderAlignment"
![image](https://user-images.githubusercontent.com/1275900/74034706-bb14dd80-49b0-11ea-9ab2-d63bf9c2307e.png)

> What impact will it have on accessibility?

I don't think `ListViewGroup`s header is currently accessible at all? So I'm not really sure what we actually expect from accessibility here
![image](https://user-images.githubusercontent.com/1275900/74035253-daf8d100-49b1-11ea-8a16-cc961955f28b.png)

> Will this feature need to be localized or be localizable?

I would expect the user to need to localise the footer string, but I think (?) this is the responsibility of the user. Any documentation will need to be localized.

**Comment by weltkante** [comment]
>  I would expect "Footer" and "FooterAlignment" to appear in the following editor (same as "Header" and "HeaderAlignment"

> I would expect the user to need to localise the footer string

Probably both will just work by itself if the new properties are annotated correctly with metadata attributes. Since there is precedence with existing `Header` and `HeaderAlignment` the new properties would basically want the same treatment as the existing properties.

If VS feels the need to do anything special about the existing properties it would have to do the same for the new properties (ideally it shouldn't need to but you never know if VS designer puts an override onto a TypeDescriptor to implement some workaround, you can only know if you have access to the VS designer source).

**Comment by hughbe** [comment]
In terms of accessibility, see #1726
