### ISSUE TITLE
Add support for subtitles in ListViewGroup

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2655]
- You can set the `LVGF_SUBTITLE` flag on `mask` and set `pszSubtitle` to a valid string and `cchSubtitle` to the length of the string

## Proposed API
This would add the following API to `ListViewGroup`:
```cs
public class ListViewGroup
{
    ...
    public string Subtitle { get; set; }
    ...
}
```

# Example
```cs
var group = new ListViewGroup
{
     Subtitle = "Subtitle"
};
```

E.g.
![image](https://user-images.githubusercontent.com/1275900/71746055-d6497600-2e63-11ea-95ab-77cbcdc742cf.png)

**Comment by RussKie** [comment]
The team had some preliminary discussions about enhancing the control. 
Could you spare few minutes and provide answers to the following questions so we can take it to the next level:

- Will VS Designer need to support the feature? If yes, describe _how_ you expect it to funсtion.
- What impact will it have on accessibility?
- Will this feature need to be localized or be localizable?

With the regards to this specific feature the first question is where I expect most questions.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Windows.Forms
{
    public partial class ListViewGroup
    {
        public string Subtitle { get; set; }
    }
}
```

**Comment by weltkante** [comment]
@RussKie forgot to remove waiting-author-feedback caused bot to mark this as stale even though it had been accepted as proposal?

**Comment by RussKie** [comment]
Still waiting for answers from Hugh 😕

There are several layers of bureaucracy, The API review is one of them.

**Comment by weltkante** [comment]
Ah alright, there's still the issue of the bot applying PR rules against issues then. (If its intended then the bot text needs to be adjusted, in the WPF repo its correctly speaking of 'issues' not 'pull requests')

**Comment by RussKie** [comment]
Hopefully @hughbe finds some time to fill the missing blanks in.
