### ISSUE TITLE
Winforms application for .Net Core 3.0 cant run in OSX

### ISSUE THREAD

**Issue by zangxx66** [dotnet/winforms#267]
* .NET Core Version: 3.0 Preview1
* Have you experienced this same bug with .NET Framework?: No

**Problem description:** cant work

**Actual behavior:** exceptions 

**Expected behavior:** Could not load file or assembly "System.Windows.Forms" The System cannot the file specified

**Comment by zangxx66** [comment]
> It's depend on user32 and GDI+ library which make it failed. As clearified earlier, Winforms is not going to support MacOS and Linux.

Will it support in the future?

**Comment by anirudhagupta** [comment]
Few days ago I read here that this repository will not take pull request to make it work on Linux and Mac so it certainly not work on other plateform.

**Comment by merriemcgaw** [comment]
@anirudhagupta is correct. We are not looking to make WinForms cross plat at this time. Closing this issue.

**Comment by engineersvision** [comment]
Is it still an active issue? 
I tried to run winforms in <b>mac OS</b> with .net core 3.0, I am having this error: 

> The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core

If it is, is there anyway we can run winforms in Mac OS or Linux?

**Comment by jnm2** [comment]
@engineersvision 

> Is it still an active issue?

No, see the comment that is just above your comment.

> If it is, is there anyway we can run winforms in Mac OS or Linux?

Not without a huge effort which the Windows Forms team is consistently saying is not in their plans. Windows Forms is tightly coupled to native Windows APIs.

See this issue for more: https://github.com/dotnet/winforms/issues/159

**Comment by KamranShahid** [comment]
> @engineersvision
> 
> > Is it still an active issue?
> 
> No, see the comment that is just above your comment.
> 
> > If it is, is there anyway we can run winforms in Mac OS or Linux?
> 
> Not without a huge effort which the Windows Forms team is consistently saying is not in their plans. Windows Forms is tightly coupled to native Windows APIs.
> 
> See this issue for more: #159

What's the advantage of building winform application in .net core rather then old .net framework

**Comment by weltkante** [comment]
> What's the advantage of building winform application in .net core rather then old .net framework

Its the way forward, Desktop framework not getting any more updates means you won't be able to use new language features like Span and IAsyncEnumerable. As long as you don't need them (and don't need any library that uses them) you are fine to remain on Desktop framework.

**Comment by KamranShahid** [comment]
Agreed about language related things and framework getting some more libraries e.g. Json builtin support in 3.0 and plus. But it will take time to mature this .net core base desktop framework .
