### ISSUE TITLE
HashTable Refrences to control Unable to be Cleared in HelpProvider.CS/ Documentation error

### ISSUE THREAD

**Issue by TendyTree** [dotnet/winforms#2680]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
**Framework 4.5**
* Have you experienced this same bug with .NET Framework?: Yes/No
Yes

**Problem description:**
I have a form with a single instance of a help provider. On this form I dynamical create and destroy buttons, which on creation I assign a it a SetHelpString and add it to a flow layout panel. On a deletion of a buttons I have no way to remove the control from the hash table reference on the help provider even with calling ResetShowHelp, leading to the hash table growing in memory, specifically _helpStrings( This could also affect the other hash tables as well)
**Actual behavior:** 
Calling ResetShowHelp does not clear the control from all the hash tables, leading to the hash table growing in memory, specifically _helpStrings( This could also affect the other hash tables as well)
**Expected behavior:**
According to the .Net Docs

`ResetShowHelp(Control) | Removes the Help associated with the specified control.` 

This only remove the the control from the _showHelp Hashtable, shown in the code bellow. The expected out come would be that it to removes all references to that HelpProvider for that specific control

**Minimal repro:**
HelpProvider.cs

        private readonly Hashtable _helpStrings = new Hashtable();
        private readonly Hashtable _showHelp = new Hashtable();
        private readonly Hashtable _boundControls = new Hashtable();
        private readonly Hashtable _keywords = new Hashtable();
        private readonly Hashtable _navigators = new Hashtable();

        public virtual void ResetShowHelp(Control ctl)
        {
            if (ctl == null)
            {
                throw new ArgumentNullException(nameof(ctl));
            }

            _showHelp.Remove(ctl);
        }

**Comment by RussKie** [comment]
This repo is for Windows Forms on .NET Core/.NET. Please report all .NET Framework related issues via VS Feedback (there's an icon at the top right hand side of VS).

If you provide a small repro project targeting .NET Core/.NET that exhibits the observed behavior we can have a look at it.
You can also pull the source down and send a fix in 😉

**Comment by TendyTree** [comment]
Alright, thank you for pointing me in the right direction. Hopefully I'll get to it in the next couple of hours

**Comment by merriemcgaw** [comment]
closing due to no followup (hope you got it figured out😊 open if you need to)
