### ISSUE TITLE
Incorrect menu checkbox bounds

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#2698]
* .NET Core Version: 
latest master @ 6566ad15762fb14bd4fa4f8253205a01af5e9986

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

![image](https://user-images.githubusercontent.com/4403806/72238602-5032e980-3632-11ea-9a92-d7a5e7e57c13.png)

**Expected behavior:**

The checkbox bounds scaled correctly

**Minimal repro:**

1. `build`
2. Run \winforms\artifacts\bin\WinformsControlsTest\Debug\netcoreapp5.0\WinformsControlsTest.exe
3. Run "Menus" test
4. Expand [Project] menu

@hughbe @gpetrou it is likely we regressed in our latest refactors. Could you please have a look?

**Comment by hughbe** [comment]
Investigating the code, there's only one place where we draw the check box:
```cs
if (CheckState != CheckState.Unchecked && menuItemInternalLayout.PaintCheck)
{
    Rectangle checkRectangle = menuItemInternalLayout.CheckRectangle;
    if (!menuItemInternalLayout.ShowCheckMargin)
    {
        checkRectangle = menuItemInternalLayout.ImageRectangle;
    }
    if (checkRectangle.Width != 0)
    {
        renderer.DrawItemCheck(new ToolStripItemImageRenderEventArgs(g, this, CheckedImage, checkRectangle));
    }
}
```

Under the debugger, `menuItemInternalLayout.CheckRectangle` is `{5,4,16,16}`. `menuItemInternalLayout.ShowCheckMargin` is `false`, so we then set `checkRectangle` to `menuItemInternalLayout.ImageRectangle`

Now: `checkRectangle` is `{-5,-5,32,32}`. Seems like there's a size discrepancy here that may be causing the bug.

Note that this doesn't seem like a recent regression - I can repro resetting to about 3-4 months ago. Can't go any further than that because of missing packages

**Comment by RussKie** [comment]
Thank you for the investigation.

**Comment by merriemcgaw** [comment]
@Vino-Wang can you try to repro this in 3.0/3.1 to see if it was introduced back in those builds?

**Comment by Vino-Wang** [comment]
@merriemcgaw, verified with .NET Core 3.1, this issue can reproduce and verified with .NET Framework 4.8. it's also can reproduce. Here is the screenshot of .NET Framework app.
![image](https://user-images.githubusercontent.com/18568603/72958854-6afc1f80-3de3-11ea-8175-e312c1bd4bc2.png)

**Comment by kpreisser** [comment]
It seems the issue even reproduces on .NET Framework 2.0:

![XP-Net20](https://user-images.githubusercontent.com/13289184/73161148-23c7a480-40eb-11ea-8df8-ad2fa569d6ce.png)

**Comment by RussKie** [comment]
Wow! It has been working for us for years, no wonder I have never noticed it (net461):
![image](https://user-images.githubusercontent.com/4403806/73253259-4a333000-4210-11ea-8ed1-f7eabbc49eae.png)

**Comment by RussKie** [comment]
The bug appears to be related to the calculation of `ImageRectangle`:
https://github.com/dotnet/winforms/blob/b666dc7a94d8ac87a7d300cfb4fa86332fb79bae/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs#L1614-L1641
...and specifically this line:
https://github.com/dotnet/winforms/blob/b666dc7a94d8ac87a7d300cfb4fa86332fb79bae/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs#L1635

Further the bug primarily affects the `ProfessionalRenderer` because the checkbox's background is painted.
Under `SystemRenderer` the checkbox's background is transparent, so the issue is not as prominent:
![image](https://user-images.githubusercontent.com/4403806/73718332-4bb0ab00-4770-11ea-9f46-0125bc7011e9.png)

Although you can see the `ImageRectangle` isn't calculated correctly either:
![image](https://user-images.githubusercontent.com/4403806/73717955-4f8ffd80-476f-11ea-9f6f-02ee45242b7c.png)

**Comment by merriemcgaw** [comment]
@dreddy-work - making sure this gets on your radar.
