### ISSUE TITLE
Use  Microsoft.CodeAnalysis.PublicApiAnalyzers

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#2705]
**Is your feature request related to a problem? Please describe.**

As suggested in https://github.com/dotnet/winforms/pull/2678#issuecomment-573486921, it will be beneficial to use [Microsoft.CodeAnalysis.PublicApiAnalyzers](https://github.com/dotnet/roslyn-analyzers#microsoftcodeanalysispublicapianalyzers).
The analyser will produce a list of public APIs ([example](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/PublicAPI.Shipped.txt)), and any breaking changes to the API will be easy to spot.

This feature is a pre-req for all NRT work (e.g. https://github.com/dotnet/winforms/pull/2702).

**Will this feature affect UI controls?**
* No

**Comment by RussKie** [comment]
Fixed in ad8ff382e89266a88f5a7ef3b0f92c495d9a5ac9

**Comment by hughbe** [comment]
Is there a way of forcing the file to regenerate? Want to add new APIs in https://github.com/dotnet/winforms/pull/2654

**Comment by Logerfo** [comment]
@hughbe the analyzer is supposed to throw a diagnostic warning you that the new API surface is unknown to the respective files. The diagnostic should contain a code-fix to add the missing member to the "unshipped" file. If you're shipping it, you can edit the files and move the member from one to another.
