### ISSUE TITLE
[Accessibility] TabPage has no keyboard tooltip

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#2717]
* .NET Core Version: 5.0

* Have you experienced this same bug with .NET Framework?: Yes

**Original bug:**
* [Bug 604799:](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/604799) [Accessibility] TabPage has no keyboard tooltip

**Problem description:**
- TabPage has no keyboard tooltip when pressing the right/left arrow or Tab button to navigate to a TabPage which got the keyboard focus

**Expected behavior:**
- TabPage has a keyboard tooltip

**Minimal repro:**
- Create .Net Core 5.0 app
- Add a TabControl to the app
- Add pages to the TabControl
- Set tooltips for TabPages
- Run the app and try to get a page tooltip using a keyboard navigation

**Comment by Zheng-Li01** [comment]
Verified the issue with .Net SDK 6.0.100-preview.3.21169.6, this issue is fixed. TabPage has a keyboard tooltip for now.
