### ISSUE TITLE
6.4.2 .net Core with WinForms doesn't allow MainMenu

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#2723]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/883311/642-net-core-with-winforms-doesnt-allow-mainmenu.html)._

---
[regression] [worked-in:6.4.0]
I have tried porting old WinForms code to .net Core and it was working before I upgraded to 6.4.2 (I think I was using 6.4.1 before) but it might have been 6.4.0).

Now when I try to run my program, I get the error:
System.TypeLoadException: 'Could not load type 'System.Windows.Forms.MainMenu' from assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxx'.'

Both MainMenu and MenuItem create the same basic error.

If I comment out my menu and make my selections with procedure calls, I can get the program to run, so it is only the MainMenu class items that seem to have broken.

---
#### Visual Studio Feedback System on 1/14/2020, 03:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by merriemcgaw** [comment]
Note that this is by design. In .NET Core 3.1 we removed a series of controls, which included the MainMenu control. Please take a look at our documentation which describes the appropriate replacements you can make in your code: https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms#removed-controls​

~Merrie
