### ISSUE TITLE
 [loc][Query][winforms] Localizability of  0; "ErrorResourcePerStoreLimitReached"

### ISSUE THREAD

**Issue by PDostalek** [dotnet/winforms#2725]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
The store has reached its limit of '{0}' resources.

ID & File Name:
 0; "ErrorResourcePerStoreLimitReached"
build___test___sign\outputs\build\loc\en\src\Microsoft.Azure.AppConfiguration.Rp\Resources\Localization.Strings

Query:
Would you please clarify the placeholder? Is it a numeric value or a resource name?

Other affected resource ids:
".resx", 0; "ErrorSkuDowngradeNotAllowed"
".resx", 0; "ErrorSkuPerSubscriptionLimitReached

**Comment by RussKie** [comment]
This path `build___test___sign\outputs\build\loc\en\src\Microsoft.Azure.AppConfiguration.Rp\Resources\Localization.Strings` does not suggest it belong to us, rather to Azure folks. So I'd think you may have mis-directed the question.
