### ISSUE TITLE
Possible porting bug: ScrollBar.ScaleScrollBarForDpiChange is unused in .NET Core

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2742]
In .NET Framework, if `ScaleScrollBarForDpiChange` then the scroll bar's size does not change if DPI is rescaled.

E.g. https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ScrollBar.cs,218

We're missing this check in .NET Core

**Comment by merriemcgaw** [comment]
@dreddy-work can you take a peek?
