### ISSUE TITLE
WindowsForms support to .vcxproj

### ISSUE THREAD

**Issue by bairog** [dotnet/winforms#2746]
I'm trying to port my C++/CLI project from .NET Framework 4.8 to .Net Core 3.1.
But compiler (latest Visual Studio 2019 16.4.3) doesn't see `System::Windows::Forms` namespace.
Adding the following line changes nothing:
`<UseWindowsForms>true</UseWindowsForms>`
I also couldn't find any reference or tutorial explaing how to add WindowsForms support to .vcxproj.

**Comment by bairog** [comment]
Could be related to [https://github.com/dotnet/wpf/issues/2117](https://github.com/dotnet/wpf/issues/2117)

**Comment by vatsan-madhavan** [comment]
Add this in your project and try again: 

```xml
<ItemGroup>
  <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
</ItemGroup>
```

**Comment by bairog** [comment]
It's working now, thank you.

BTW: Is there any documentation or tutorial explaining this technique?
It woldbe better to automate this (I mean enabling WinForms/WFP support for C++/CLI project) instead of editing vcxproj file manually. Maybe checkboxes in Visual Studio. Thank you in advance.

**Comment by vatsan-madhavan** [comment]
@diverdan92 ?

**Comment by tgani-msft** [comment]
@wli3 @nguerrera
