### ISSUE TITLE
Discussion/proposal: Add support to ProgressBar to display Text  AND Bars

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#2760]
**Is your feature request related to a problem? Please describe.**

In Framework there any may questions about adding Text over the progress bar some can be found here https://www.bing.com/search?q=vb.net+progressbar+with+text&form=ANNNB1&refig=5a465b1ab56d4a68c2a248e29778a674&sp=2&qs=RI&pq=vb.net+progressbar+text&sk=PRES1SC1&sc=2-23&cvid=5a465b1ab56d4a68c2a248e29778a674 and they involve adding a few lines of code, while the solution works it is very hard to read and very repetitive to have every developer repeat the solution.

**Describe the solution you'd like**
A Text Option that displays either user provided text or localized "x of Y" automatically on top of the Continuous bar that is updated at a rate that allows it to be read (if possible).

**Describe alternatives you've considered**
Every user doing it themselves using something like
```VB
pb.Invalidate() ' Something frequently left out of online examples
Using g As Graphics = pb.ProgressBar.CreateGraphics()
    'Switch to Anti-aliased drawing for better (smoother) graphic results
    g.PixelOffsetMode = PixelOffsetMode.HighQuality
    g.SmoothingMode = SmoothingMode.AntiAlias
    g.DrawString(Text, _defaultFont, Brushes.Black, New PointF(pb.Width \ 2 - (g.MeasureString(Text, _defaultFont).Width / 2.0F), pb.Height \ 2 - (g.MeasureString(Text, _defaultFont).Height / 2.0F)))
End Using
```
**Will this feature affect UI controls?**
    Yes

If yes, please describe the following:
- Will VS Designer need to support the feature?  Simplest solution is and additional Option for System.Windows.Forms.ProgressBarStyle (TextOverlay) and possibly any text properties if the developer can set the message. 
- What impact will it have on accessibility?If AccessibleDescription already works automatically it would not have an impact. If it requires developer to constantly change it on every increment then this might be where to get the text to display.
- Will this feature need to be localized or be localizable? If the string is "x of Y" yes, if it is provided the user will need to deal with that. The text should be centered so Right to Left shouldn't matter.

**Comment by RussKie** [comment]
Thank you.

Do you think you could elaborate further and provide your thoughts on the new API to accommodate the request?
For example here's a list of questions from a top of my head:
* Do you expect users to use `Text` property? 
* Do we need to allow customisation of "X of Y" text?
* Do we need to support displaying percent complete mode (e.g. "X%" text)?
* How will it work with marquee mode?
* What about text placement?
* What about text size? How do we deal with text overflow?

**Comment by paul1956** [comment]
I see a few options
1. Users uses Text property and set the whole string. The control just displays whatever is there user on top of the color bar. User handles internationalization (the same way they do with normal text boxes)
2. It is always in the form "X of Y"? The control handles internationalization and the string is fixed
3. X of Y is specified as a format, not sure how internationalization works. 
Do we need to support displaying percent complete mode (e.g. "X%" text), it is an alternative that I hadn't thought about and could be an acceptable alternative.
How will it work with marquee mode? It wouldn't that is a different mode, it would not replace the 3 existing modes, it would be an additional mode with text AND a solid bar.
What about text placement? Always centered (keeps it simple)
What about text size? Font could be settable but then you need all the additional font parameters. All examples I have seen use a default font.
How do we deal with text overflow?There is a AutoSize in the designer but don't see documentation on what it does. We could require a min size to hold (RoundUp(Maximium/10) characters * 2) + 4 + padding, so for example 999 of 999 would require 10 max characters widths in the Font being used plus some padding. Of it if doesn't fit don't display text or throw exception if we want to complicate it.

**Comment by merriemcgaw** [comment]
I don't believe this fits into our roadmap of features we're looking to add to the runtime. We're trying to make sure features we implement having the look/feel of Native Windows apps. It also presents a large number of challenges around usability and accessibility. I'm going to close this as today - but if we have more requests for controls like this we'd be happy to reconsider.
