### ISSUE TITLE
DataGridView Tip is not normal

### ISSUE THREAD

**Issue by 15092368540** [dotnet/winforms#2812]
Only .NET Core Version,  .NET Framework Version is right.

DataGridView cell content is not truncated, but still show with content tips

**Comment by 15092368540** [comment]
Screenshots and examples

![D1](https://user-images.githubusercontent.com/49462433/73927653-b991d980-490c-11ea-8096-4fe5571ccee5.png)

[DGV.zip](https://github.com/dotnet/winforms/files/4164488/DGV.zip)

**Comment by merriemcgaw** [comment]
@merriemcgaw to review with the accessibility team.

**Comment by Vino-Wang** [comment]
@merriemcgaw Yes, this is a real difference between .NET Core and Framework when the cell context is not truncated. Before we did a private testing for issue #1680 (original VS bug 528682, fixed in core instead of framework), it fixed the keyboard tooltip of the DataGridView cells in core. – Every type empty cell has the default tooltip no matter the cell context truncated or not truncated. For the test details, you can found them in Teams test result OneNote by searching the issue ID #1680.

In addition, for the tooltip Narrator reading issue, here is a similar Narrator issue #2538.

**Comment by merriemcgaw** [comment]
@M-Lipin @vladimir-krestov  - do you guys think we can use a keyboard command to enable tooltip on tab, and then just have tooltips behave as they used to before #1680 where tooltips only show for truncated content?

**Comment by vladimir-krestov** [comment]
I think, yes, we can. We can use some hotkey to enable/disable keyboard tooltips. Just as a hotkey of activating/deactivating a cell tooltip was implemented (Control+Shift+F10, please see #1681)
@merriemcgaw, _what combination should we use to enable/disable keyboard tooltips?_

Also, we can show tooltips only for truncated TextBox content if a custom tooltip text wasn't set.
But what do we need to do for other cell types? 
A button cell shows "Button" tooltip by default
An image cell shows "Image" tooltip by default
_Should we show tooltips only for truncated content of other type cells?_ (Link, ComboBox cells and other)

**Comment by merriemcgaw** [comment]
>_Should we show tooltips only for truncated content of other type cells? (Link, ComboBox cells and other)_

Yeah, I think that's a good plan, just show truncated text tooltips for text based controls.
I want to keep things simple If the user does Ctrl+Shift+F10 to enable we do keyboard tooltips for all tooltips (across the app, no matter what the control and regardless of truncation maybe?).
If the user does not enable accessible tooltips (as I'm starting to call them now with all the WCAG2.1 requirements) then the behavior would be as in the Classic Framework 4.x in that the tooltip would show on truncated text content only (or the old defaults they for Button and Image). Make sense?

**Comment by merriemcgaw** [comment]
This is redundant but with the new ToolTip on Tab requirements from accessibility we are going to need to show these even for shorter strings. Please let us know if this is a major blocking issue for your customers. We'd recommend disabling tool tips on tab and just use mouse tool tips in that case.
