### ISSUE TITLE
 Invoke PrintDialog.ShowDialog() does not show Print dialog successfully

### ISSUE THREAD

**Issue by Thea-Zhao** [dotnet/winforms#2814]
* .NET Core Version: .NET Core SDK 5.0.100-preview.1.20106.1 + the VSIX Inserted into Dev16 16.5.0 [29803.141.master]

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
 Invoke PrintDialog.ShowDialog() does not show Print dialog successfully.

**More Info:**
1. This is a regression issue, it's not reproducing when targeting .NET Core 3.1.
2. This issue also cannot reproduce with Framework project.

**Actual behavior:**
No expected Print dialog shown.
.NET Core 5.0 screenshot:
![PrintDialogIssue5 0](https://user-images.githubusercontent.com/53589182/74011630-291fbd00-493d-11ea-9879-f54897d6b34a.gif)

**Expected behavior:**
The Print dialog should be shown successfully.
.NET Core 3.1 screenshot:
![PrintDialogIssue3 1](https://user-images.githubusercontent.com/53589182/74011467-c3cbcc00-493c-11ea-9b47-81ecb1128738.gif)

**Minimal repro:**

1. Create a Winforms Core application.
2. Drag and drop a button to the form.
3. Double click the button1 to generate the button1_click event, then add following code to it:
PrintDialog pdlg = new PrintDialog();
pdlg.ShowDialog();
4. Build and run.
5. Click the button1 to see whether the Print dialog is popping up.
[PrintDialogIssue.zip](https://github.com/dotnet/winforms/files/4169604/PrintDialogIssue.zip)

**Comment by RussKie** [comment]
I haven't bisected, but looking at the history we probably disturbed it in https://github.com/dotnet/winforms/pull/2594.
Guessing these classes, having one of the fields modified, caused some misalignment, and caused the call to `UnsafeNativeMethods.PrintDlg(data)` fail.

/cc: @gpetrou

**Comment by weltkante** [comment]
@RussKie the PR you linked moved the `int m_Flags;` field which broke the binary layout. I'm adding comments to the PR to highlight the mistakes.

**Comment by RussKie** [comment]
Thank you @weltkante 👍  somehow I failed to see it myself

**Comment by Thea-Zhao** [comment]
Verified with latest Dev16 16.6.0 Preview 2.0 [29904.160.master] + latest .NET Core 5.0 5.0.100-preview.1.20154.12 build, this issue is fixed now.
![2814Expected](https://user-images.githubusercontent.com/53589182/75963355-2ea7ee80-5e7a-11ea-9b60-d8d1786c9a9d.png)

**Comment by RussKie** [comment]
Thank you

**Comment by sandeep200321** [comment]
Hi, 
above code doesn’t work in windows 8.1 and when you click on print,window freezes hangs. Tested this in .net 5.0 preview as well but no luck. It just works fine in windows 10. Can you please address this.

**Comment by RussKie** [comment]
Please raise a new issue and provide more details about your setup.

**Comment by sandeep200321** [comment]
Thanks. New issue is raised here with details.
https://github.com/dotnet/wpf/issues/2971
