### ISSUE TITLE
'StatusBar' class could not be found in System.Windows.Forms

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#2852]
* .NET Core Version: 5.0.100-preview.1.20112.13

* Have you experienced this same bug with .NET Framework?: No 

**Problem description:**
Cannot create the System.Windows.Forms.StatusBar class object in .NET Core 5.0 project.
![StatusBar-5 0](https://user-images.githubusercontent.com/45864985/74408964-b0ef5500-4e70-11ea-8ee0-1f30406fd6ab.png)

**More info:**
1. This issue cannot repro in the latest NET Core 3.1 project.
2. The System.Windows.Forms.StatusBarPanel class object cannot be created too.

**Expected behavior:**
Can create the System.Windows.Forms.StatusBar class object in .NET Core 5.0 project successfully.
![StatusBar-3 1](https://user-images.githubusercontent.com/45864985/74408977-b9e02680-4e70-11ea-9b2b-39fbea868fd5.png)

**Minimal repro:**
1. Create a Winforms Core application.
2. Open Form1.cs file and add the following code in Form1 class. 
        StatusBar ss = new StatusBar();
3. Build the application.

**Comment by John-Qiao** [comment]
That's by design and described in there: https://github.com/dotnet/docs/issues/17008

**Comment by RussKie** [comment]
Relates to #2798
