### ISSUE TITLE
An error dialog pops up after right click selected text

### ISSUE THREAD

**Issue by Marie-Shi** [dotnet/winforms#2872]
* .NET Core Version: 
.Net Core 3.1.200-preview-014986 from 3.1 Release branch + VISX inserted in the Dev16 16.6.0[29817.27.master]

* Have you experienced this same bug with .NET Framework?: 
Yes

**More Info:**
1.	This issue can also reproduce with Framework project and WPF project.
2.	This is a regression issue, it can reproduce from Dev16 16.0[29816.11.master] to latest master branch build, it cannot reproduce on release branch.

**Steps to reproduce:**
1.	Create a Winforms Core application.
2.	Selected "InitializeComponent" in Form1.cs, and right click it.

**Actual behavior:**
An error dialog pops up after right click selected text. After clicking "OK" button, VS crash.
![VS_crash_rightclick_selected_text](https://user-images.githubusercontent.com/45864017/74730547-4760b380-5281-11ea-9a28-75330cdf8d88.png)

**Expected behavior:**
There is no error dialog pops up after right click selected text. The behavior should be like below:
![VS_expected_rightclick_selected_text](https://user-images.githubusercontent.com/45864017/74731052-42503400-5282-11ea-90f0-d5cdf0836ddd.png)

**Comment by RussKie** [comment]
If you suspect this is a VS issue it shouldn't be raised here, but via VS Feedback tool.
________________________________

**Comment by Marie-Shi** [comment]
Verified this bug with Dev16 16.0[29818.127.master], this bug is fixed now. There is no error dialog pops up after right click selected text. So closed it.
![无标题](https://user-images.githubusercontent.com/45864017/74796921-e7abec00-5304-11ea-8f63-de859418b67d.png)
