### ISSUE TITLE
Typo in winforms designer doc

### ISSUE THREAD

**Issue by dehghani-mehdi** [dotnet/winforms#2931]
At [winforms-designer](https://github.com/dotnet/winforms/blob/master/Documentation/winforms-designer.md#option-1)

Doc says:

```
<TargetFrameworks>net472;netcoreapp5.0</TargetFrameworks>
```

But in picture below it, the value of `TargetFrameworks` is `net472;netcoreapp3.0`.

**Comment by merriemcgaw** [comment]
We'll be happy to accept a PR if it's problematic, but we're not going to update the screenshot.

**Comment by dehghani-mehdi** [comment]
[Done](https://github.com/dotnet/winforms/pull/2953)

**Comment by weltkante** [comment]
Not sure if downgrading to 3.0 in the master docs is the right solution, given that this branch is working on 5.0 already and when you'll release 5.0 both docs and screenshot say to use 3.0 ...
