### ISSUE TITLE
ToolStripDropDownMenu.ico is missing from embedded resources

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/winforms#2939]
The `ToolStripDropDownMenu.ico` is correctly included in the winforms repo: https://github.com/dotnet/winforms/blob/b666dc7a94d8ac87a7d300cfb4fa86332fb79bae/src/System.Windows.Forms/src/Resources/System/Windows/Forms/ToolStrip/ToolStripDropDownMenu.ico.

However, it was apparently missed when resources for ToolStrips were added to `System.Windows.Forms.csproj`. It should be included in this block of embedded resources:

https://github.com/dotnet/winforms/blob/804091a825f723579f18fcd1b82b7b86cb001c04/src/System.Windows.Forms/src/System.Windows.Forms.csproj#L554-L565

This is observable when the `ToolStripCollectionEditor` is used to edit the drop down items of a `MenuStrip`. This appears in the new WinForms designer and likely appears in the .NET Core `PropertyGrid` when used to edit a `MenuStrip`.

Compare the images in https://github.com/dotnet/winforms-designer/issues/1427 to see the effect.

cc @merriemcgaw

**Comment by merriemcgaw** [comment]
@JuditRose can you get this in for 5.0p2?

**Comment by Tanya-Solyanik** [comment]
@DustinCampbell  -  screenshots in the bug show that the classic dialog has a list of control names, while the Core designer has a list of type names. Is this a separate issue?

**Comment by RussKie** [comment]
Perhaps a better solution would be to glob resources, e.g.:
```xml
  <ItemGroup>
    <EmbeddedResource Include="Resources\System\Windows\Forms\**\*.ico">
      <LogicalName>$(AssemblyName).$([System.IO.Path]::GetFileNameWithoutExtension('%(Identity)'))</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
```.

However we will need to update file names to match the desired logical names. Would there be any problems with that?

**Comment by DustinCampbell** [comment]
> Perhaps a better solution would be to glob resources, e.g.:
> 
> ```
>   <ItemGroup>
>     <EmbeddedResource Include="Resources\System\Windows\Forms\**\*.ico">
>       <LogicalName>$(AssemblyName).$([System.IO.Path]::GetFileNameWithoutExtension('%(Identity)'))</LogicalName>
>     </EmbeddedResource>
>   </ItemGroup>
> ```.
> 
> However we will need to update file names to match the desired logical names. Would there be any problems with that?
> ```

IMO, it'd be better to write that like this:

```XML
<ItemGroup>
  <EmbeddedResource Include="Resources\System\Windows\Forms\**\*.ico"> 
   <LogicalName>%(AssemblyName).%(Filename)</LogicalName>
  </EmbeddedResource>
</ItemGroup>
```
