### ISSUE TITLE
Replace resource embedding with globs in csproj files

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#2949]
In the `csproj` files we have a lot of `ico` files as embedded resources defined for all resource files for all the components. 

e.g.:
```
<EmbeddedResource Include="Resources\System\Windows\Forms\ToolStrip\ToolStripDropDownMenu.ico">
      <LogicalName>System.Windows.Forms.ToolStripDropDownMenu</LogicalName>
    </EmbeddedResource>
```

It would be nicer to replace them with something like this:

 ``` 
<ItemGroup>
    <EmbeddedResource Include="Resources\System\Windows\Forms\**\*.ico">
      <LogicalName>$(AssemblyName).$([System.IO.Path]::GetFileNameWithoutExtension('%(Identity)'))</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
```

Relates to https://github.com/dotnet/winforms/issues/2939

**Comment by weltkante** [comment]
Small nit on issue title: it got nothing to do with regex, this is msbuild pattern matching. Just mentioning to avoid future misunderstandings.

**Comment by RussKie** [comment]
We will need to update file names to match the desired logical names.

**Comment by elachlan** [comment]
@dreddy-work I completed the globing work recently see: #49
