### ISSUE TITLE
Microsoft.Common.WinForms does not support framework `netcoreapp3.0`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#2981]
* .NET Core Version: 3.x / 5.0

**Problem description:**

After installing 5.0 with 3.0/3.1 already installed, the 3.0/3.1 templates are no longer available to Visual Studio because the Winforms template pack for 5.0 does not support 3.1 or 3.0 in the template.json for the carried templates.

**Expected behavior:**

It is possible to create Windows Forms apps targeting 3.x and 5.0, e.g.
```powershell
dotnet new winforms -f netcoreapp3.0
dotnet new winforms -f netcoreapp3.1
dotnet new winforms -f netcoreapp5.0
dotnet new winformslib -f netcoreapp3.0
dotnet new winformslib -f netcoreapp3.1
dotnet new winformslib -f netcoreapp5.0
```

**Minimal repro:**

```powershell
PS> dotnet new winforms -f netcoreapp3.1

Couldn't find an installed template that matches the input, searching online for one that does...
Usage: new [options]

Windows Forms (WinForms) Application (C#)
Author: Microsoft
Description: A project for creating a .NET Core Windows Forms (WinForms) Application
Error: Invalid parameter(s):
-f netcoreapp3.1
    'netcoreapp3.1' is not a valid value for -f (Framework).

```

**Comment by RussKie** [comment]
@phenning @merriemcgaw two questions:

1. Do we need to support netcoreapp3.0 at all? It has reached its EOL, and is no longer supported. 
2. Do we need to patch v3.1?

**Comment by nth-block** [comment]
This is true for `netcoreapp3.1` also.
