### ISSUE TITLE
Enable PickFolders in OpenFileDialog

### ISSUE THREAD

**Issue by HermanEldering** [dotnet/winforms#2993]
Sometimes I need the user to select a folder. The OpenFileDialog can be used to select files but currently doesn't expose the functionality to select folders. Developers now need to include custom common dialog interop, for instance from the Windows API Code Pack which hasn't been maintained for many years or Okii Dialogs.

The solution I suggest is to add a property IsFolderPicker to set the FOS_PICKFOLDERS flag in the dialog options and changing the GetOptions() method to allow the flag. This seems to be a relatively minor change, especially if only Vista or later Windows version are supported.

One alternative to this change is to have each project duplicate the entire OpenFileDialog interop either within their source code or by referencing a nuget package, merely to toggle a single bit. A second alternative is [using reflection to toggle the bit in the private field](https://github.com/Willy-Kimura/BetterFolderBrowser). Yet another alternative is to use the FolderBrowserDialog class, but that option uses another UI.

I is also possible to add a property to FolderBrowserDialog so that it will use the Vista OpenFileDialog folder picker, but that deviates more from the underlaying Windows API.

There seems to be an edge case where the Vista file dialog is not available (https://github.com/dotnet/winforms/issues/2506), that might need to be taken into account. It could perhaps fall back to FolderBrowserDialog in that case.

**Comment by RussKie** [comment]
This seems counter intuitive to use `OpenFileDialog` to select folders. We have `FolderBrowserDialog`, is there any reason you can't use it?

**Comment by RussKie** [comment]
This seems counter intuitive to use `OpenFileDialog` to select folders. We have `FolderBrowserDialog`, is there any reason you can't use it?

> but that option uses another UI.

We have updated the `FolderBrowserDialog` in .NET Core 3.0. 
Have you seen this: https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms#modernization-of-the-folderbrowserdialog ?

**Comment by HermanEldering** [comment]
Thanks RussKie. I wasn't aware that the FolderBrowserDialog was already updated, so disregard my original post.
