### ISSUE TITLE
BC30562: '“MsgBox” is ambiguous between declarations in Modules “Microsoft.VisualBasic.Interaction, Microsoft.VisualBasic._Interaction”

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/winforms#2997]
* .NET Core Version: 
5.0.100-preview.1.20155.7

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

Unable to use `MsgBox`, `Shell` and `InputBox` without qualifying them with `Interaction.`
BC30562: '“MsgBox” is ambiguous between declarations in Modules “Microsoft.VisualBasic.Interaction, Microsoft.VisualBasic._Interaction”

**Expected behavior:**
`MsgBox("")` should not have BC30562 compilation error .
Microsoft.VisualBasic._Interaction should be `Friend` instead of `Public` .

**Minimal repro:**
```cmd
dotnet new winforms -lang vb
```

Edit Form1.vb
```vb
Private Sub Form1_Load() Handles Me.Load
    MsgBox("")
End Sub
```

**Comment by Nukepayload2** [comment]
Workaround: Insert the following code into each UI-related VB code file.
```vb
Imports Microsoft.VisualBasic.Interaction
```

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann - what are your thoughts?
