### ISSUE TITLE
Proposal: add "AutoSaveAndRepaint" property to PictureBox control.

### ISSUE THREAD

**Issue by ygc369** [dotnet/winforms#3000]
PictureBox current behavior:
    If you paint something on the picturebox, and minimize the application that uses the picturebox, and then restore the application, you will find that what you have painted disappears. 

This is a common problem that many people meet. So I hope that PictureBox control can have an "AutoSaveAndRepaint" property, if it is set as true, anything painted on the picturebox would be saved automatically and would not disappear when the picturebox is refreshed or repainted.

**Comment by weltkante** [comment]
How do you paint on the PictureBox? Are you using the OnPaint event? Then you are not actually painting on the PictureBox and could just use any other control.

The whole point of using a PictureBox is that you put an `Image` object in it, when you paint into the PictureBox you need to do `Graphics.FromImage` on that image and then your changes will be persisted as desired. (You also get free scaling support if the image isn't the same size as the control.)

**Comment by RussKie** [comment]
Thank you fro the suggestion, but this isn't something we will add or accept.

As @weltkante explained, you need to modify an image that is displayed in a `PictureBox` instance rather than painting over the `PictureBox` itself.
