### ISSUE TITLE
build.sh failed with "Execution Failed: no install script" message 

### ISSUE THREAD

**Issue by SergeyMatsiupa** [dotnet/winforms#3018]
* .NET Core Version: 3.0.103 (Commit:  b7ef045669)
* Platform/OS: ubuntu linux 18.04-x64
* Winforms branch version (date): Thu Mar 26 07:37:13 2020 -0700

**Problem description:**
I cloned the current version of Winforms and tried to build it local, and I got error message (below with the command):
```
maestro@mmeniac:~/.vscode/extensions/WinForms/winforms$ ./build.sh
/home/maestro/.vscode/extensions/WinForms/winforms/eng/common/native/install-dotnet-api-docs_netcoreapp3.0.sh --baseuri https://netcorenativeassets.blob.core.windows.net/resource-packages/external --installpath /home/maestro/.netcoreeng/native//bin --version 0.0.0.1
Execution Failed: no install script
```
Before I updated file global.json with my actual dotnet versions in such way:

_{
  "tools": {
    "dotnet": "3.0.103",
    "runtimes": {
      "dotnet": [
        "$(MicrosoftNETCoreAppPackageVersion)"
      ]
    }
  },
  "sdk": {
    "version": "3.0.103"
  },
  "msbuild-sdks": {
    "Microsoft.DotNet.Arcade.Sdk": "5.0.0-beta.20171.1",
    "Microsoft.DotNet.Helix.Sdk": "5.0.0-beta.20171.1",
    "FIX-85B6-MERGE-9C38-CONFLICT": "1.0.0",
    "Microsoft.NET.Sdk.IL": "5.0.0-alpha1.19513.3"
  },
  "native-tools": {
    "dotnet-api-docs_netcoreapp3.0": "0.0.0.1"
  }
}_

Probably I should make some other changes in global.json?
(but there is no explanations in corresponding documentation file about its parameters)

**Comment by RussKie** [comment]
@SergeyMatsiupa on Windows `dotnet-api-docs_netcoreapp3.0` emits a warning too:

```
Processing C:\Development\winforms\eng\..\global.json
dotnet-api-docs_netcoreapp3.0 was not found in .
Native tools bootstrap failed	
```

In the interim, remove this line and try without it:
```diff
  "native-tools": {
-    "dotnet-api-docs_netcoreapp3.0": "0.0.0.1"
  }
```


@chcosta this looks like an issue you fixed in https://github.com/dotnet/arcade/issues/4482. Though your fix applied to ps1 scripts, would the same fix need to be applied to sh scripts too?

**Comment by RussKie** [comment]
There are few other issues here that I feel worth calling out:

1. You haven't provided what commit you tried building. There was a change across our infra last week that moved us to new NuGet feeds, see #3011, this may be related.
2. I do not believe you can have `sdk: version: 3.0.103`, the version is too low. You should get an error:
    ```
    \winforms\.dotnet\sdk\3.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(127,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 5.0.  
    Either target .NET Core 3.0 or lower, or use a version of the .NET SDK that supports .NET Core 5.0.
    ```
1. And lastly, we don't support Windows Forms built outside Windows, so you're in uncharted territories here. I'm not saying it can't be done (@hughbe is building on a Mac afaik), but no official support.

**Comment by SergeyMatsiupa** [comment]
> ```diff
>   "native-tools": {
> -    "dotnet-api-docs_netcoreapp3.0": "0.0.0.1"
>   }
> ```
oh yes, it helped well! thanks :)

**Comment by SergeyMatsiupa** [comment]
>     2\. I do not believe you can have `sdk: version: 3.0.103`, the version is too low.
yes, I had to install net core sdk 5.0 preview, but... isn't too strange to link stable version (as I said I cloned master branch of winforms) - to preview-version of net core sdk? 0o 
anyway, I built it on my Ubuntu-PC)

**Comment by SergeyMatsiupa** [comment]
also I got some other errors during the build process:

Build FAILED.
CSC : error CS1566: Error reading resource 'System.Windows.Forms.Design.professional1' -- 'Could not find file '/home/maestro/.vscode/extensions/WinForms/winforms/src/System.Windows.Forms.Design/src/Resources/System/WinForms/Design/professional1.ico'.' [/home/maestro/.vscode/extensions/WinForms/winforms/src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj]
    0 Warning(s)
    1 Error(s)
CSC : error CS1566: Error reading resource 'System.Windows.Forms.Design.professional2' -- 'Could not find file '/home/maestro/.vscode/extensions/WinForms/winforms/src/System.Windows.Forms.Design/src/Resources/System/WinForms/Design/professional2.ico'.' [/home/maestro/.vscode/extensions/WinForms/winforms/src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj]
    0 Warning(s)
    1 Error(s)
CSC : error CS1566: Error reading resource 'System.Windows.Forms.Design.Behavior.leftopen' -- 'Could not find file '/home/maestro/.vscode/extensions/WinForms/winforms/src/System.Windows.Forms.Design/src/Resources/System/WinForms/Design/Behavior/leftopen.ico'.' [/home/maestro/.vscode/extensions/WinForms/winforms/src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj]
    0 Warning(s)
    1 Error(s)
CSC : error CS1566: Error reading resource 'System.Windows.Forms.Design.Behavior.leftclose' -- 'Could not find file '/home/maestro/.vscode/extensions/WinForms/winforms/src/System.Windows.Forms.Design/src/Resources/System/WinForms/Design/Behavior/leftclose.ico'.' [/home/maestro/.vscode/extensions/WinForms/winforms/src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj]
    0 Warning(s)
    1 Error(s)

_(I found a workaround by renaming the appropriate files to the appropriate folder)_

**Comment by weltkante** [comment]
> isn't too strange to link stable version (as I said I cloned master branch of winforms) - to preview-version of net core sdk?

Master branch isn't the stable version, its the working branch where all the latest changes go into.

**Comment by RussKie** [comment]
> Master branch isn't the stable version, its the working branch where all the latest changes go into.

The master is our "dev" branch, we don't release form it.

> also I got some other errors during the build process:

If you don't mind, please send a PR with the renames. Thank you

**Comment by SergeyMatsiupa** [comment]
> If you don't mind, please send a PR with the renames. Thank you

I don't mind but it's not make a big sence :)
as I said I solved this throughout some brutal workaround (by renaming 3 *.ico-files, all are in my comment above), so better find them in System.Windows.Forms.Design.csproj and rename with correct case (problem was with inconsistency with case in names)

**Comment by hellmoney888** [comment]
good [footballincups.com](url)

**Comment by hughbe** [comment]
i think https://github.com/dotnet/arcade/pull/3496 may contribute to this
