### ISSUE TITLE
Hosting Blazor Introduces WinForm to the Internet

### ISSUE THREAD

**Issue by 199621616** [dotnet/winforms#302]
At present, a large number of traditional WinForm desktop applications urgently need to be transformed into Internet applications. The emergence of Blazor provides conditions for these traditional applications to enter the Internet. WinForm + Blazor + WebApi, a new way to build C # stack development.

**Comment by merriemcgaw** [comment]
@199621616 what are you suggesting that WinForms does in its code base to make it easier for people to transform their apps? This is usually something that app owners would need to do not the WinForms technology.

**Comment by 199621616** [comment]
@merriemcgaw 能否开发一个WinForm版的、类似Electron那样的 可托管JavaScript、TypeScrip或者Blazor的客户端软件?

**Comment by karelz** [comment]
Thanks for the translation @AdamYoblick!

Turning WinForms into Electron to host other languages and runtimes is outside of the scope of this repo.
WinForms as technology is tied to .NET. .NET supports dozens of programming languages and they can be equally used, .NET != C#. Mixing other runtimes is more interop story and there are currently not clear compelling scenarios to do that.

Closing as "out of scope".
If you think I misunderstood anything, please let me know. Thanks!
