### ISSUE TITLE
Updating Form.MinimumSize causes form activation/focus

### ISSUE THREAD

**Issue by MikeRoz** [dotnet/winforms#3020]
* .NET Core Version: 

3.0+
* Have you experienced this same bug with .NET Framework?: 

Yes
**Problem description:**

Changing `Form.MinimumSize` property if handle is created activates Form (focus). 
It could be reproduced with PerMonitor/WM_DpiChanged or with standard dpi if you update `MinimumSize` property via code.

Current implementation of `Form.MinimumSize` setter uses `SetWindowPos` without `SWP.NOACTIVATE` flag which causes shifting application focus to target form:
`User32.SetWindowPos(new HandleRef(this, Handle), User32.HWND_TOP, Location.X, Location.Y, Size.Width,Size.Height, User32.SWP.NOZORDER);`

**Expected behavior:**
Changing Form.MinimumSize shouldn't affect active window.

**Minimal repro:**

**Comment by merriemcgaw** [comment]
This would be a behavioral change that we should evaluate whether this will break too many existing apps being ported.

**Comment by merriemcgaw** [comment]
@MikeRoz if you could tell us a bit more about your scenario we can better figure out how to prioritize this.

**Comment by MikeRoz** [comment]
I don’t see how fixing this issue could break any existing application. I believe issue only exists because in initial implementation NOACTIVATE was missed by mistake.
In my case I faced issue when implementing per-monitor support – WM_DPICHANGED message leads to  MinimumSize update and forces activation of wrong form.

**Comment by merriemcgaw** [comment]
I don't think we're going to get to this issue, and I'd worry about breaking anyone that may have found a workaround would be broken.
