### ISSUE TITLE
Form icon can not be (properly) hide.

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#3022]
* .NET Core Version: 3.0, 3.1.2

* Have you experienced this same bug with .NET Framework?: **No**

**Problem description:**

In WinForms core app run `this.ShowIcon = false;` Icon is hiding, but default app. icon appear:
![core](https://user-images.githubusercontent.com/17767561/78015507-2a280600-7352-11ea-82e4-7bfa7be2599d.png)

**Expected behavior:**
Icon is hiding:
![net](https://user-images.githubusercontent.com/17767561/78015572-3f049980-7352-11ea-9a4c-dbb83cf8fb66.png)

Windows 7 x64.

**Minimal repro:**
[WinFormsCoreTest1.zip](https://github.com/dotnet/winforms/files/4419602/WinFormsCoreTest1.zip)

**Comment by kirsan31** [comment]
This is not MDI related problem, it's a problem of every form. 100% regression from .net :(
I've updated 1 post,

**Comment by weltkante** [comment]
I think this is caused by swapping the condition under which `UpdateStyle` is called:
* [DesktopFramework](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Form.cs,2321) calls `UpdateStyle` when `ShowIcon` switches to false
* [.NET Core](https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/Form.cs,1933) calls `UpdateStyle` when `ShowIcon` switches to true

**Comment by kirsan31** [comment]
@weltkante 

> I think this is caused by swapping the condition under which UpdateStyle is called:
> 
> DesktopFramework calls UpdateStyle when ShowIcon switches to false
> .NET Core calls UpdateStyle when ShowIcon switches to true

Yea, I saw it and tried this: 
```cs
ShowIcon = false;
UpdateStyles();
```
 with no luck. May be it's critical that `UpdateStyles();` must be called before `UpdateWindowIcon(true);` ? ...

**Comment by weltkante** [comment]
Yeah, calling UpdateWindowIcon with incorrect styles messes something up that doesn't repair itself. I tried calling `UpdateWindowIcon(true)` via reflection after doing `UpdateStyles` but that doesn't help, yet this works (replicated ShowIcon=false via reflection):
```csharp
var value = !ShowIcon;
var vectorField = typeof(Form).GetField("formStateEx", BindingFlags.Instance | BindingFlags.NonPublic);
var vector = (BitVector32)vectorField.GetValue(this);
var section = (BitVector32.Section)typeof(Form).GetField("FormStateExShowIcon", BindingFlags.Static | BindingFlags.NonPublic).GetValue(this);
vector[section] = value ? 1 : 0;
vectorField.SetValue(this, vector); // struct field needs explicit update
if (!value) UpdateStyles();
typeof(Form).GetMethod("UpdateWindowIcon", BindingFlags.Instance | BindingFlags.NonPublic).Invoke(this, new object[] { true });
```

**Comment by RussKie** [comment]
I can certainly understand this is an annoying bug. 
Is this a blocker? If so, what's the impact? We need to have a good justification for servicing to accept a fix.

**Comment by Vino-Wang** [comment]
@RussKie Maybe this is a known issue in core designer.

**Comment by Vino-Wang** [comment]
1.	There is no icon shown in runtime when setting the Form’s ShownIcon property to false in property browser(press F4 when focus on the form) or setting it in InitializeComponent() part.
 ![PropertyBrowser](https://user-images.githubusercontent.com/18568603/78322193-9dbf5280-75a0-11ea-8347-3c378c67be9e.png)
![InitializeComponent](https://user-images.githubusercontent.com/18568603/78322204-a44dca00-75a0-11ea-9a6f-f3ca6c5dbe98.png)

 2.	The icon is still shown when setting the Form’s ShownIcon property to false by adding code in Form_Load or Button_Click events.
 ![Events](https://user-images.githubusercontent.com/18568603/78322208-a748ba80-75a0-11ea-8988-08c5b35eb63e.png)

**Comment by kirsan31** [comment]
> I can certainly understand this is an annoying bug.
> Is this a blocker? If so, what's the impact? We need to have a good justification for servicing to accept a fix.

In our app we have _worker_ forms, each of them have 3 states differ (to the user) by form icon:

- Not working - stop icon.
- Working in demo mode - demo icon.
- Working - no icon.

This is a key point and users are used to it. So, yes this is a blocker :(

@Vino-Wang Yes, I think this is related to [this](https://github.com/dotnet/winforms/issues/3022#issuecomment-608007973) and 2 posts down.

**Comment by RussKie** [comment]
> * Working - no icon.
> 
> This is a key point and users are used to it. So, yes this is a blocker :(

As a workaround could you not set an empty transparent icon?

**Comment by RussKie** [comment]
Another workaround is to performing an interop call to hide the icon before hiding the icon:

```cs
if (myform.ShowIcon)
{
    int extendedStyle = (int)User32.GetWindowLong(myform.Handle, User32.GWL.EXSTYLE);
    User32.SetWindowLong(myform.Handle, User32.GWL.EXSTYLE, (IntPtr)(extendedStyle | (int)User32.WS_EX.DLGMODALFRAME));
}

myform.ShowIcon = false;
```

**Comment by kirsan31** [comment]
@RussKie Yes, thank you. Of course we can do such a workarounds, but if this was the only problem. As I mentioned in this [post](https://github.com/dotnet/winforms/issues/3036), we are stopped our migration to core process, so no workarounds (for us) currently needed :(

**Comment by merriemcgaw** [comment]
This is a very simple fix per @Tanya-Solyanik , I'd be willing to take it to Servicing shiproom if @kirsan31 would be able to continue the migration exercise, even though it's possible to work around the issue.

**Comment by merriemcgaw** [comment]
Let's mark this a known issue for 3.1 including the workaround.

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .NET Core SDK 5.0,  the issue has been fixed that hide the icon of the form successfully in running.
![3022GitHubIssue](https://user-images.githubusercontent.com/38325459/79303540-b6752400-7f21-11ea-91b8-51ea33e08155.gif)
