### ISSUE TITLE
Always pops up the error(run application failure and advise user to install the .NET Core, in fact, .NET Core 3.1 was installed) whether it's win7 or win10

### ISSUE THREAD

**Issue by 199621616** [dotnet/winforms#3028]
![image](https://user-images.githubusercontent.com/25498672/78208226-713f0400-74d6-11ea-91c1-971bdd937c8f.png)

从.NetFramework 4.6.1迁移到.Net Core 3.1后，经常有用户反馈出现此问题。而事实上.NetCore3.1已经安装并能正常使用。如何解决此问题？

After migrating from. Netframework 4.6.1 to. Net core 3.1, users often report this problem. In fact. NETCORE 3.1 is installed and working properly. How to solve this problem?

**Comment by maikebing** [comment]
可以参考一下 
 https://blog.magnusmontin.net/2019/09/22/single-file-exes-in-net-core/
https://www.cnblogs.com/jRoger/p/create-trimmed-self-contained-executable-in-net-core-3-0.html

**Comment by Vino-Wang** [comment]
@199621616, 你好，你可以把出现这个问题的具体步骤提供一下吗？ 也可以提供一下出现问题的工程等等信息。
有个问题希望您可以解答一下：是否是单纯的迁移工程然后运行出现的问题，还是迁移完成紧接着进行publish之后的安装程序不能正常安装？

-

**Comment by RussKie** [comment]
Please write in English.

**Comment by 199621616** [comment]
是发布为单文件exe,然后安装包打包安装的。这个情况，并非每次都必然出现。有时一台电脑，安装了两个不同名称的软件，其中一个可正常运行，另一个出现这样的提示。与迁移过程，似乎没有关系。迁移到3.1.0后就有这个情况。目前使用3.1.2仍然有这个情况
It is published as a single file exe, and then the installation package is packaged and installed. This situation is not inevitable every time. Sometimes a computer has two different names of software installed, one of which can run normally, and the other shows such a prompt. It doesn't seem to have anything to do with the migration process. This is the case after migrating to 3.1.0. This is still the case in 3.1.2

**Comment by 199621616** [comment]
我们也没能够复现这个情况。有的是同一个安装包，在一台电脑上没问题，而在另一台电脑上出现这个情况。也有的是一台电脑上同时安装有两个不同名称的软件，其中一个没问题，另一个出现这个提示。似乎它的发生是偶然的，但出现的频率又比较高。
We haven't been able to replicate that either. Some are the same installation package, no problem on one computer, but this situation occurs on another computer. There are also two software with different names installed on one computer at the same time, one of which is OK, and the other shows this prompt. It seems that it happened by chance, but the frequency of its occurrence is relatively high.

**Comment by RussKie** [comment]
> It is published as a single file exe, and then the installation package is packaged and installed.

_Single file_ or _self-contained_? These are two different things.
["Single file"](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables) means all your app's files are bundled together, but it requires the SDK to be physically installed on a client's workstation.
["Self contained"](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained) means the app and the required SDK's files are bundled together. And the app can be run on a client's workstation without the SDK installed.

**Comment by 199621616** [comment]
单文件，并且安装了桌面运行时：
Single file with desktop runtime installed:
https://download.visualstudio.microsoft.com/download/pr/7cd5c874-5d11-4e72-81f0-4a005d956708/0eb310169770c893407169fc3abaac4f/windowsdesktop-runtime-3.1.3-win-x86.exe

**Comment by RussKie** [comment]
To summarise, you have a working app that starts one day and then the next day you get the prompt without modifying your app?
In that case I'm not sure what we can do. It is likely something with your system, and not with our runtime.

**Comment by 199621616** [comment]
它已经常导致用户被迫中止应用。对最终用户伤害很大。
