### ISSUE TITLE
Overall thoughts on situation with WinFroms (3.1)

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#3036]
Hi all. I want to present a brief report of migration WinForm project from .net to core. I thought for a long time to write this post or not, and still decided to write, because we spent a time and effort on the migration process. If it's out of place here - I apologize :(
Maybe for someone it will be useful...

Exchange trading app - mix of automation and user mode.
Solution: 3 c# projects and one native c++ project. About 36000 Lines of Executable code.

**Migration process.**

- No official automation. Other tools like ([try-convert](https://github.com/dotnet/try-convert) and [CsprojToVs2017](https://github.com/hvanbakel/CsprojToVs2017)) are more interfere than help for real projects.
- Bad documented. Again, all available articles about conversion are about simple (not real) projects. Lack of documentation about things that change/gone in core. For example: `legacyCorruptedStateExceptionsPolicy` support removed from app.config. Replaced by `COMPlus_legacyCorruptedStateExceptionsPolicy` environment variable, that must be set **before** app start, and furthermore behave [differently](https://github.com/dotnet/runtime/issues/13805). [Debug.Listeners](https://github.com/dotnet/runtime/issues/26781#issuecomment-605615442) and so on...
- No designer support in VS, it makes us use multi-targeting which further complicates the migration process.

**Current (3.1) state of WinForms.**

The fact that, in **one day of simple overview after conversion**, we found 4 critical bugs (https://github.com/dotnet/winforms/issues/3022, https://github.com/dotnet/winforms/issues/3032, https://github.com/dotnet/winforms/issues/3033, https://github.com/dotnet/winforms/issues/3034) in **released** version of .net core!  Yes, I think all of them critical, for 15 years using .net, we never saw anything like this. Tells us about 2 things:

1. WinForms core is not usable, at least at prod :( 
2. Nobody seriously uses it. I can not explain in a different way a non-working dataGridView :( This is very  frequently used control in .net, and we have not seen reports that it broken to this point... May be it's due to long and complicated migration process and/or Lack of designer in VS? 

At the moment, our transition process is stopped until better times :(

**Comment by merriemcgaw** [comment]
Thank you for your feedback @kirsan31, we find it critical in making sure our port of WinForms to Core is ultimately successful. We're very interested in taking fixes that are actively blocking migrations for customers. I'd say the issues arise from a variety of sources - underlying runtime changes, refactoring going awry and some outright regressions. All of these warrant fixing in the next release, but if they're blocking the migration to 3.1 we would definitely take them to be considered for servicing of our LTS release.  Have you gotten far enough to feel like these are the major blockers for your apps? 

We're actively working on the designer and we'll be releasing some significant updates in future previews. We're hoping that we will be in a state people can start using the new designer for most of their development in these upcoming previews so that we can capture your feedback from that experience as well.

/cc: @OliaG for feedback especially re: docs and porting samples.

**Comment by kirsan31** [comment]
@merriemcgaw 

> Have you gotten far enough to feel like these are the major blockers for your apps?

Technically Yes. But the main reason of stopping is:
The fact that we are faced with 4 serious problems (one of them can be easily workaround, but still) right after the first launch, without even starting testing!
Bosses decided that in this state of WinForms further investment in migration is simply unreasonable and even dangerous. And I agree with them, but will continue to research in this area on my own )

**Comment by OliaG** [comment]
Thanks for the feedback @kirsan31! We are working on updating our docs right now and I've included your feedback there. Please let us know if you faced any other issues in future, appreciate your participation!

As for the general experience, I completely agree that it is not full without the designer. We are working on it, the preview version is already available in Visual Studio Preview channel but it is not stable yet. We hope to get a more mature version in the middle of May and we'll keep improving it. By .NET 5 I'd recommend to give it another shot and  I hope most of the problems will be resolved.

**Comment by merriemcgaw** [comment]
We're working on those issues. Thank you so much for filing them and providing the detailed feedback. We're working hard on getting the designer ready for prime time and also appreciate when contributors exercise our product. Given that there's no specific action to follow up here, I'll close this issue and we'll track in the individual ones above.
