### ISSUE TITLE
Fix and re-enable tests disabled by #3045

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/winforms#3046]
https://github.com/dotnet/winforms/pull/3045 has disabled two tests. 

Some exception types seem to be thrown unwound - so instead of receiving `TargetInvocationExeption` the inner-exception type is directly observed. 

These tests need to be investigated, fixed and re-enabled. 

/cc @RussKie, @AdamYoblick, @merriemcgaw, @dotnet/dotnet-winforms

**Comment by merriemcgaw** [comment]
Thanks @vatsan-madhavan!
