### ISSUE TITLE
Improved dpi scaling and support for logical coordinates

### ISSUE THREAD

**Issue by lhak** [dotnet/winforms#305]
This issue is created as requested for PR #279 to discuss the proposed improvements and new APIs.

# Current status of dpi scaling
Here is some of the insight I have gained into the current dpi scaling implementation by going throught the current codebase. Please correct me if I got something wrong:

- The Control class contains a DeviceDpi property. This returns the system dpi by default and will be updated during handle creation to the monitor dpi
- The Scale() method in the Control class provides a generic way to scale the size and position of a control with a specified factor
- ContainerControls support an AutoScaleMode property. If this is set to dpi, it will call the Scale() method of its children during the layout pass. The scaling factor is calculated as (system) dpi divided by the AutoScaleDimensions property (e.g. 96dpi). If AutoScaleMode is set to font, the factor will be (font size at system dpi)/AutoScaleDimensions
- The Form control can receive a DPI_CHANGED message during dpi changes. It will update its deviceDpi value, create a scaled copy of its font and then call the Scale() method of its children.
- Each control (except the toplevel control) can receive a DPI_CHANGED_BEFORE_PARENT (and DPI_CHANGED_AFTER_PARENT) if per monitor dpi awareness v2 is enabled. This will update the deviceDpi value and create a scaled copy of its font (only is one is directly associated with it). It will also call the RescaleConstantsForDpiChange() method that can be implemented by controls.
- Fonts specified in point units will always be drawn with the system dpi scaling factor applied.

- The inbox controls have different levels of dpi awareness support. Some only check for the system dpi value in their constructor, while a few implement the RescaleConstantsForDpiChange() method to rescale to a new dpi value dynamically.

# Issues with the current implementation
The biggest flaw is that the code (and the APIs) are based on physical pixels instead of logical coordinates/effective pixels. Thus, each control and application needs to do the coordinate transformation itself, which is challenging and prone to errors. Unfortunately, there is not really a low-level visual positioning and rendering layer where this transformation could be done. Instead, a lot of code directly calls into the win32 (pixel based) functions. Therefore, improvements of the current implementation seems to be the most reasonable approach. The next big issues I have encountered is that there is currently no way to know to which dpi a control is actually scaled to. There is the DeviceDpi property, but this one is for example completely unrelated to the scaling initiated by the AutoScaleMode pass. Setting one of the properties of a control (e.g. the width) can have a completely different result depending on where it is done in the code. 

### Some additional issues:

- The current code assumes in my places that the initial dpi is always the system dpi. This is certainly not always the case. In fact, the system dpi value might not correspond to any of the monitor dpi values. Therefore, the initial scaling of the control positions and fonts can be wrong.
- A lot of the per monitor dpi support is limited to the v2 version, even though the v1 version for older Windows versions also supports the required functionality.

# Improvements of the general scaling mechanism
 
The PR adds a new code path that can be enabled for a single control with the LogicalDpiScaling property or by default with the Application.SetLogicalDpiScalingDefault() method. The basic idea is that each control keeps track on the dpi value it is currently scaled to and rescales itself if necessary (and ignores AutoScale changes):

- A new field lastScaleDpi is added to the Control class that defaults to 96dpi as a baseline. Its value can be retrieved with the new CurrentDpi property.
- During handle creation (or if its parent control changes), the new UpdateDpiScalingFactor() method of the control will retrieve the new dpi value and compare it with lastScaleDpi. If it has changed, it will scale its associated font if present, call its Scale() method and finally update the lastScaleDpi value. It will also call the RescaleConstantsForDpiChange() method to take advantage of already implemented dpi support in the controls.
- As an optimization, the ContainerControl() overrides the UpdateDpiScalingFactor() method and provides the retrieved dpi value to all of its child controls. This basically allows to scale all child controls in one go with layout suspended.
- The DPI_CHANGED message handling in the Form control is slightly updated to give the controls a chance to update their lastScaleDpi value. Additionally, if per monitor v1 mode is enabled, it will raise the DpiChangedBeforeParent and DpiChangedAfterParent events manually to emulate the v2 functionality (update the deviceDpi value, scale font and call the RescaleConstantsForDpiChange() method)

These changes should especially improve the initial positioning of the controls and sizes of the fonts. Additionally, per monitor v1 support is now basically on-par with the v2 version (except for its fundamental limitations). Because the dpi value for each control is always known, new APIs can be added that transform between logical and pixel coordinates in a reliable way.

# New APIs for logical coordinates
The new APIs in the Control class are supposed to be used in applications and new controls. The final goal is that they can always stay in the logical coordinate space and do not have to worry about dpi scaling. The positioning APIs should also be usable with existing controls.

##### Positioning
- New properties LogicalBounds, LogicalLocation,LogicalWidth, LogicalHeight, LogicalSize, LogicalMaximumSize, LogicalMinimumSize, LogicalMargin and LogicalPadding provide the transformation to- and from their pixel based counterparts.

- GetPreferredLogicalSize() can be implemented by controls to enable auto sizing
##### Drawing
- PaintEventArgs provides a ApplyDpiScalingTransformation() that uses the PageScale property of the Graphics class to setup a render transformation. Thus, drawing can now be done with logical coordinates.

- FontWithLogicalSize provides a way to set a font to a control which will then be rescaled to the correct dpi value and passed to the Font property. The unscaled version is kept for text drawing with the render transformation applied. Unfortunately, the Graphics class seems to ignore the PageScale factor if a Font in point units is rendered. Thus, a copy of the font with its size converted to pixel units is created in this case.

- InvalideLogicalRect() as the counterpart to Invalidate()

##### Other
- MouseEventArgs can return the position in logical coordinates

##### Bitmaps (not in the PR)
Unlike vector graphics and font rendering, bitmaps are inherently pixel based. It would be great if there would be APIs for the application to provide bitmaps in different sizes and the best fit for the current dpi would automatically be picked.

# Summary
I hope the proposed changes provide valuable improvements of the current dpi scaling mechanism that can be easily integrated into existing applications. In addition, they are compatible with the already present dpi support code in the various controls. The added APIs can be leveraged to write new code in a dpi independent way.

**Comment by merriemcgaw** [comment]
This is a large feature request and not fully in scope for the 3.0 release. However we are actively investigating ways we can improve Per Monitor support for all of our controls. I added the API suggestion tag because we will need to also discuss options around adding to the API and whether that's a good option or not. Thanks @lhak for kicking off the discussions.

**Comment by wjk** [comment]
@lhak Given what @merriemcgaw said regarding how this change is not likely to be merged any time soon, I have a question for you. Is there any way I can glue your changes on top of an otherwise-unmodified copy of winforms (via subclassing, extension methods, etc.)?

I have had to jury-rig a custom `ToolStripRenderer` to draw correctly under high-DPI scenarios in the past, and it was not easy. More importantly, what the user sees at 200% DPI is not an exact replica of what the user sees at 100% DPI. I am very interested in improving both the UI and my development experience for that code, and I think your changes would be helpful in doing so. Any assistance would be appreciated. Thanks!

**Comment by merriemcgaw** [comment]
@wjk  you should work with @KlausLoeffelmann , he's been working on the ToolStrip and I'm pretty sure he ported some fixes into .NET Core rather recently (or it's in the works :)).
@lhak , one thing I'd like to understand is what kind of testing you've done and you would propose around this new feature. We're looking at perhaps creating an all new setting somewhere higher in the stack (form or application level perhaps) that flags going down a new code path similar to what you're describing. Testing such a complex space has always posed challenges because every HDPI fix in one area has ripple effects throughout the codebase. Before we go far down any path I'd like to plan out our testing strategy so we don't inadvertently regress things. HDPI testing is absolutely a bear to automate.

**Comment by KlausLoeffelmann** [comment]
Yes, the Toolstrip is in the works - actually, it is ready, but for easier testing, we should have the HighDpiMode API extension in, before we PR the toolstrip.

Also, without having taken a look at the correlating PR yet - if we really want to approach a big change like the proposed, let's think about having appropriate analyzers to guarantee consistency in the changes. Tests alone would not be enough for me to let me sleep OK at night.

Thoughts?

**Comment by lhak** [comment]
@wjk The toolstrip controls (without the upcoming changes) all seem to be  system dpi aware, so they should scale in (many) static scenarios. However, I have seen in the code that some values are not scaled (e.g. the number of dots in the grip will change, but not their sizes). Are these the kind of differences you have mentioned? The changes in the PR will not magically fix this, but they should make it easier to write code that achieves what you are asking for (i.e. the rendering at different dpi values basically looks the same, just sharper).

**Comment by wjk** [comment]
@lhak Please see the attached project. At 100% scaling/96 DPI, the custom ToolStripRenderer draws _exactly_ as I desire it to. If you run this code at any higher scaling value, while most of the custom drawing is correct, things like rounded corners and arrow glyphs are incorrectly scaled. My goal with this code is to have the custom drawing _look_ identical at 100% scaling and higher, even if the _code_ used to generate it is different.

In another version of this code (not attached, sorry) I attempted to use the `DpiScaleConstant()` function (in `Windows7Renderer.cs`) to scale all manually specified coordinates, margins, and thicknesses, and it worked somewhat, but the end result is not completely identical (some lines, for example, were thicker than they should be). If you can give me any recommendations on how to better accomplish this goal, I would be most appreciative. Thanks!

[Windows7Renderer](https://github.com/dotnet/winforms/files/2775858/Windows7Renderer.zip)

**Comment by zsd4yr** [comment]
@lhak I'd like to followup here and try to better understand your testing strategy for this feature.

**Comment by lhak** [comment]
@wjk I looked briefly at the code and at least the rendering code that calculates the arrow (see CreateArrowPath()) does not scale its size at all.

**Comment by lhak** [comment]
@merriemcgaw  So far I have mostly tested the changes with the controls test app included in this project. The testing has basically been done manually so far by changing the windows dpi settings before/after launch. This includes the dpi value itself but also the "fix blurry apps" setting. Especially changing the dpi before launch and setting "fix blurry apps" to false (therefore looking at the case where the system dpi value is not the per monitor dpi) has uncovered the most issues with the current implementation. Additionally, I also have an (internal) application that currently uses a small third-party library (and some additional hacks) to handle the dpi scaling. This was also the main reason to contribute to this project, because in my experience this library still achieves better results than the official implementation while doing similar things. I agree that some automated test tool to test static and dynamic scaling, maybe based on an extended version of the controls test app, would be very useful as manual testing can be quite exhausting. The question is if an automated comparison of screenshots at different dpi settings can be a reliable method for spotting issues.

I would also like to add a few general comments: I really hope that these issues can be sorted out before the first stable release. To be honest, it is really disappointing that (fundamental) dpi scaling issues in this library still have to be discussed today. Most of these issues could have been fixed by Microsoft years ago with the APIs that have been available since Windows 8.1. Additionally, Microsoft's own products have been shipping with high-dpi displays since that time. So I think these issues should be finally sorted out now (no matter if the actual changes will contain any changes from the proposed PR or if it is a completely different approach) before the first release on .net core. It is certainly easier to fix issues with existing application code due to changed scaling behavior when code is being ported from .net framework to .net core than later.

**Comment by KlausLoeffelmann** [comment]
@lhak, the most work is not to be done for SystemAware. WinForms can deal with SystemAware pretty well, espacially when Forms have been designed in 96Dpi - which is the reason we came up with the HighDpi Infobar in VS. 

The biggest issue is PerMonitorV2. And that has been introduced only in Windows 10 1703:
https://blogs.windows.com/buildingapps/2017/04/04/high-dpi-scaling-improvements-desktop-applications-windows-10-creators-update/

**Comment by zsd4yr** [comment]
> I agree that some automated test tool to test static and dynamic scaling, maybe based on an extended version of the controls test app, would be very useful as manual testing can be quite exhausting.

I feel you, brother 😴 This is a long time coming; we're exploring solutions.

**Comment by merriemcgaw** [comment]
We will be tackling dpi scaling as a major feature area in the next release, but we're not ready to take something like this for .NET Core 3.0, where our focus is ensuring that we have parity with .NET Framework and have some better test coverage.  Right now, we should close this issue and have a community wide discussion when we're ready to tackle the issue.
