### ISSUE TITLE
.NetCore support System.Runtime.Serialization.Formatters.Soap?

### ISSUE THREAD

**Issue by Naganathan** [dotnet/winforms#306]
I am facing below exception while serialize/deserialize my project.

Could not load file or assembly 'System.Runtime.Serialization.Formatters.Soap, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.'

Please confirm whether .Netcore support "System.Runtime.Serialization.Formatters.Soap" serialization and any other functionality available intead of?

**Comment by karelz** [comment]
That namespace is not supported in .NET Core: https://apisof.net/catalog/System.Runtime.Serialization.Formatters.Soap
However, SOAP serialization should work: https://github.com/dotnet/corefx/issues/10676

[CoreFX repo](https://github.com/dotnet/corefx) would be better place to file issues/questions regarding general .NET Core capabilities, not tied to WinForms, if you have further follow ups. Thanks!
