### ISSUE TITLE
Add Collapse Support to ListViewGroup

### ISSUE THREAD

**Issue by lonitra** [dotnet/winforms#3067]
**Is your feature request related to a problem? Please describe.**

As of now, there's not an option for a user to hide items under a `ListViewGroup` that they aren't interested in seeing at the time, similar to what windows like File Explorer provide. This could result in endless scrolling if there are many ListViewGroups and many items under each group. As #2623 suggested, a collapsible/collapse property would be a nice touch to give users flexibility and can especially be useful for clutter management purposes.

**Describe the solution you'd like**

Add the ability for users to make items in a group collapsible.

API:
```cs
public class ListViewGroup 
{
    public bool Collapsible { get; set; }
    public bool Collapsed { get; set; }
}
```

Example:
```cs
var lvGroup = new ListViewGroup 
{
    Collapsible = true,
    Collapsed = false
};
```
An excellent visualization of what this might look like from the original issue:
![image](https://user-images.githubusercontent.com/1275900/71746568-2a088f00-2e65-11ea-9b9d-8f91815c5a8f.gif)

**Will this feature affect UI controls?**

Yes. 

**Will VS Designer need to support the feature?**
It would be nice. I would imagine the Designer would have an area carved out in the ListViewGroup Collection Editor where Collapsible/Collapsed can be toggled. Something like so:
![designerex](https://user-images.githubusercontent.com/30007367/79377765-0d263200-7f11-11ea-8a98-965984c03343.png)

I also imagine that the changes would immediately visible to the user in the designer, again similar to what is shown in the original issue.

**What impact will it have on accessibility?**
 I'm not quite sure here. 

**Will this feature need to be localized or be localizable?**
Aside from some work relating to accessibility namely perhaps what a talkback would use to describe the property, no I do not think this needs to be localized/localizable.

-----------------------------------------------------------------------------------------------------------
**Update**
After implementing Collapsible/Collapsed property for ListViewGroup as done so in #3155 , we realize that this will be an issue with the design-time serializer, which orders properties assignment statement alphabetically. This means that `Collapsed` will come before `Collapsible`. 
Suppose a user wanted to set the properties like so in designer:
![image](https://user-images.githubusercontent.com/30007367/81878121-ec66f180-953b-11ea-8305-8693159527be.png)
The serializer will generate:
```cs
this.listViewGroup1.Collapsed = true;
this.listViewGroup1.Collapsible = true;
```

Since Collapsed is no-op when `Collapsible = false` (which is the default), the end result will be `Collapsed = false` and `Collapsible = true` , not what the user intended.

**Suggestion**
Upon discussion with the team, we came to the idea to merge the two properties into one. The new API will be as follows:
```cs
public class ListViewGroup 
{
    public enum State 
    {
        DEFAULT,
        EXPANDED,
        COLLAPSED
    }

    public State CollapseState { get; set; }
}
```
Along with this there will be a visualizer in designer to show what each of these states mean, something similar to:
![image](https://user-images.githubusercontent.com/30007367/81880303-0efc0900-9542-11ea-9735-288694ea9083.png)

**Comment by weltkante** [comment]
> What impact will it have on accessibility?

It will be needed to be presented though accessibility API that you can toggle the collapsed state of a group.

**Comment by merriemcgaw** [comment]
We'll need to see if we can expose the UIA Expand/Collapse pattern. You can chat with @M-Lipin for suggestions when you're at that point.

**Comment by RussKie** [comment]
I've scanned the neighbouring API and the `ListView` API have the following public surface:
* [`bool ListView.AutoArrange`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.autoarrange?view=netcore-3.1)
* [`bool ListView.CheckBoxes`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.checkboxes?view=netcore-3.1)
* [`bool ListView.LabelWrap`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.labelwrap?view=netcore-3.1)
* [`bool ListViewItem.Checked`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listviewitem.checked?view=netcore-3.1)
* [`bool ListViewItem.Focused`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listviewitem.focused?view=netcore-3.1)
* [`bool ListViewItem.Selected`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listviewitem.selected?view=netcore-3.1)

so the proposal to add the following fits right in:
* `bool ListViewGroup.Collapsible`
* `bool ListViewGroup.Collapsed`.


It should be noted that `TreeNode` appears to favour `IsXyz` naming convention, that feels inconsistent for the current context:
* [`bool TreeNode.IsEditing`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.treenode.isediting?view=netcore-3.1)
* [`bool TreeNode.IsExpanded`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.treenode.isexpanded?view=netcore-3.1)
* [`bool TreeNode.IsSelected`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.treenode.isselected?view=netcore-3.1), etc.

I believe we should follow the former naming than the latter.

**Comment by terrajobst** [comment]
> After implementing Collapsible/Collapsed property for ListViewGroup as done so in #3155 , we realize that this will be an issue with the design-time serializer, which orders properties assignment statement alphabetically.

When we approved it, I wrote this in email:

> Please don’t throw exceptions when `Collapsible == false` and `Collapsed` is set. Properties should be settable independently. Ideally, `Collapsed` is a no-op when `Collapsible` is `false`, **but as soon as `Collapsible` is set to `true`**, the state currently stored in `Collapsed` is respected.

The mental model I had in mind was something simple like this:

```C#
public bool Collapsible 
{
    get => _collapsible;
    set
    {
        if (_collapsible != value)
        {
            _collapsible = true;
            UpdateGroupState();
        }
    }
}

public bool Collapsed
{
    get => _collapsed;
    set
    {
        if (_collapsed != value)
        {
            _collapsed = true;
            UpdateGroupState();
        }
    }
}

private void UpdateGroupState()
{
    // Use _collapsed && _collapsible
}
```

**Comment by RussKie** [comment]
> The mental model I had in mind was something simple like this:
> 
> ```cs
> public bool Collapsible 
> {
>     get => _collapsible;
>     set
>     {
>         if (_collapsible != value)
>         {
>             _collapsible = true;
>             UpdateGroupState();
> ```

Yes, it is something I had in mind too.
However as we started exploring the designer story we come to realisation that correlated properties pose challenge to the designer. It was also uncovered that we completely overlooked the events associated with the properties.



The new proposal is to meld the two properties into one, thus reducing the API surface and make it easier for a developer:
```cs
public enum CollapsedState 
{
    None = 0,
    Expanded,    // collapsible
    Collapsed,   // collapsible | collapsed
}

public CollapsedState CollapsedState
{
    get => _collapsedState;
    set
    {
        if (_collapsedState!= value)
        {
            _collapsedState = value;
            OnCollapsedStateChanged(value);
            UpdateGroupState();
        }
    }
}

public EventHandler<ListViewGroupCollapsedStateArgs> CollapsedStateChanged(ListViewGroupCollapsedStateArgs e);
```
