### ISSUE TITLE
Winform Designer is not available

### ISSUE THREAD

**Issue by Yoopex** [dotnet/winforms#3068]
* .NET Core Version: 3.1

* Have you experienced this same bug with .NET Framework?: 
 No

**Problem description:**

VS version:16.15.4 Community

-----

When I update vs to 16.15.1, the winform designer runs normally.

After a few days, I found it's not available when I try to create a new winform project or open a exist winform project. When I click the "Show Designer Shift+F7", it always show me the codes, even if the codes is opened yet.

I just wanna know if there is a bug or i made a wrong configuration, and how to solve it?

Thanks

**Comment by RussKie** [comment]
Please raise issues with the Designer via VS Feedback:
![image](https://user-images.githubusercontent.com/4403806/79415727-6bc2dd00-7ff1-11ea-9377-c5b33bc49e00.png)

There is an open ticket about the similar issue, that you may wish to check out: https://developercommunity.visualstudio.com/content/problem/842375/windows-forms-designer-net-core-is-not-showing-aft.html
