### ISSUE TITLE
TableLayoutPanelDesigner and friends (FlowLayoutPanelDesigner, etc.) have not been ported to the WinForms runtime

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/winforms#3070]

**Comment by merriemcgaw** [comment]
See if you can identify any other missing designers or editors that we didn't get in.

**Comment by weltkante** [comment]
@merriemcgaw there's a whole bunch in #2411, it also includes the ones listed here, this can probably be closed as duplicate

**Comment by DustinCampbell** [comment]
Closing since there's already an uber issue.
