### ISSUE TITLE
System.Windows.Forms.Design.ImageListCodeDomSerializer appears to be missing in the list of System.Design type forwards

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/winforms#3073]
https://github.com/dotnet/winforms/blob/139ad6f018b334a12fdd30104bc9776b79466295/src/System.Design/src/System.Design.Forwards.cs#L28-L33

**Comment by weltkante** [comment]
This is present in the binaries on current master branch as far as I can tell?

Note that type forwards are sometimes generated automatically, I can't recall the exact condition, but the cs files only list the ones not covered by the automatic generation rules.

![grafik](https://user-images.githubusercontent.com/5845814/79792740-b4f79180-834f-11ea-9ef4-45176c906c10.png)

**Comment by RussKie** [comment]
> Note that type forwards are sometimes generated automatically, I can't recall the exact condition, but the cs files only list the ones not covered by the automatic generation rules.

The magic is performed by `ResolveMatchingContract` in FacadeAssemblies.prop
https://github.com/dotnet/winforms/blob/bb5b5cecf9538eeac6c99a0c4a0d4e41b9295737/eng/FacadeAssemblies.props#L15-L49
Type forwards for public types are generated automatically, internal types must be forwarded manually.

For non-facade projects we must define forwards explicitly (e.g. System.Windows.Forms -> System.Windows.Forms.Primitives).


@DustinCampbell please let me know if you're having issues, and I'll re-open this.
