### ISSUE TITLE
It doesn't look like `IClassFixture<ThreadExceptionFixture>` is working

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#3090]
See https://github.com/dotnet/winforms/pull/3089

Test failures are hanging... Adding the code from `ThreadExceptionFixture` directly into the test class prevents the hang

/cc @weltkante

**Comment by RussKie** [comment]
I'm been trying to figure what's been happening with our public builds. They have been very unstable for the past 3 or so weeks randomly hanging.
My work in https://github.com/dotnet/winforms/pull/3064 is related to this.

I'm happy to consider creating a base class for all our tests that contains the necessary error handling plumbing, if this would help us in tracking the culprit. (I don't want it to be used for any other purpose!)

**Comment by weltkante** [comment]
Fixtures seem to work without problem for me. Tried executing tests locally from console but they are not hanging either. Is it possible to get stack traces of the hangs? If not it would be really useful if the CI infrastructure started doing that, even more so than taking screenshots. If this is not available maybe [dotnet-dump](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) can be used to extract stacktrace of the hanging process before killing it.

**Comment by weltkante** [comment]
I got a random deadlock when executing tests locally, created #3095 and will be root causing it there - should be adressed before further investigations because it will just disturb looking for other kinds of deadlocks.

**Comment by hughbe** [comment]
I'm going to close this as we have a bunch of other open issues that cover the same thing
