### ISSUE TITLE
Revisit facade versioning for 5.0

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#3108]
**.NET Core Version:**
master branch / 5.0 preview releases

**Have you experienced this same bug with .NET Framework?:**
No

**Problem description:**
WinForms versions its facade assemblies as 5.0 while the dotnet runtime repository versions its facade assemblies as 4.0. This means depending on the selected SDK you'll either compile against a 4.0 or a 5.0 version of `System.Drawing`, even though the WinForms facade is supposed to replace the dotnet runtime version.

In #2413 the guidance was [to not version facades](https://github.com/dotnet/winforms/issues/2413#issuecomment-615273450):
> For desktop compat shims don’t change the assembly version. Don’t remove types, maintain APICompat with previous release. APICompat should catch problems where you remove type forwards.
>
> .NETCore does allow newer assembly versions to automatically satisfy older references, but there is no good reason to version the compat shims since they have no types.

Since #2413 was fixed without resolving the versioning discussion I'm opening this follow-up issue.

**Expected behavior:**
WinForms and dotnet runtime should agree about versioning facades.

**Minimal repro:**
* Build a project against `Microsoft.NET.Sdk` and you get `System.Drawing` in version 4.0 from `Microsoft.NetCore.App`
* Build a project against `Microsoft.NET.Sdk.WindowsDesktop` and you get `System.Drawing` in version 5.0

**Comment by weltkante** [comment]
@merriemcgaw this needs to be resolved before 5.0 is released, its a binary compatibility problem, if you let it slip into 5.0 release you would make it a permanent problem because you cannot downgrade assembly versions without breaking someone.

**Comment by merriemcgaw** [comment]
@JeremyKuhne @RussKie  let's discuss again in our meeting Thursday.

**Comment by weltkante** [comment]
ping. needs to be resolved before 5.0 is released, preferably before it enters the final preview phase

**Comment by JeremyKuhne** [comment]
@ericstj do you know the right thing to do here or can you tag the right person to help make sure we're doing the right thing?

**Comment by ericstj** [comment]
So we consider `System.Drawing` a .NETFramework compatibility facade.  As with all of these we build in dotnet/runtime we freeze their version at the version of .NETFramework.  

It contains only typeforwards, so technically you can never observe that it has a specific version, so I don't think it's problematic that you're building a higher version.  That version will never get recorded in any other binary.  You also need your version to win out over the one from MS.NETCore.App, so giving it a higher assembly version is a convenient way to do that (in 3.x we relied on a file version hack).

The places you have to be careful about are changing type strings that would list that version.  So anywhere in source that might say `TypeForwardedFrom` or call out System.Drawing in a fully-qualified type name.  These should stay at 4.0.0.0.  So long as that's the case I'd say leave it so you have one less special case.

**Comment by merriemcgaw** [comment]
To confirm @ericstj, there's no immediate action needing to be taken in the WinForms repo?

**Comment by ericstj** [comment]
I believe I answered @JeremyKuhne's question.  Not sure what you're asking me to do here?

**Comment by merriemcgaw** [comment]
Sorry @ericstj I was confirming that so long as we meet the criteria you laid out we wouldn't have additional action. @JeremyKuhne can you scrub our source to make sure we're doing things right?

**Comment by RussKie** [comment]
We have discussed it offline, and we don't think there is a problem.
Happy to re-open, if we have user scenario where it doesn't work as expected at runtime.
