### ISSUE TITLE
Fix VB InputBox issues

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#3117]
**.NET Core Version:**
.NET Core 5.0 preview / current master branch

**Have you experienced this same bug with .NET Framework?:**
Yes

**Problem description:**
Since it was decided against providing a generalized InputDialog in #2891 and people who need it should be using the [InputBox](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction.inputbox?view=net-5.0) method from VB assemblies also in C# (it's available out of the box without adding references). I'm opening this follow-up issue for things that were brought up in discussion that need to be fixed.

Issues with the existing input form:
- As you can see for example on a german OS the cancel button doesn't fit its label and is cut off (should spell 'Abbrechen') - see screenshot below
- Accessibility should be checked to match the quality requirements of WinForms if guidance for C# users is to use the VB input form
- The current button layout is probably from a previous era (Windows 3.11 used this layout), you usually have ok/cancel buttons at the bottom of the dialog these days. I don't know if Microsoft still has general guidelines how the layout of simple dialogs should look like, but if in doubt I'd say keep it as similar to a message box as possible.

If you think updating the button layout is out of scope feel free to drop it from the issue and just ensure localization/accessibility (which I do think are important).

![image](https://user-images.githubusercontent.com/5845814/75037525-a8bc9880-54b4-11ea-8e1b-555a42d71fcd.png)

The underlying form for inspection can be found [here](https://github.com/dotnet/winforms/blob/master/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/VBInputBox.vb). Note that the designer part (InitializeComponent) is inline and not in a .designer.vb file, it still is intended to be edited with the VS designer. If this is currently not possible and it needs to be edited manually then you may want to remove InitializeComponent in order to not have future designers break the form.

**Expected behavior:**

* no cutoff in any localization provided out of the box
* accessibility should match quality requirements
* dialog button layout should match modern win32 dialogs like MessageBox and SaveFileDialog

**Minimal repro:**
Call [`Interaction.InputBox`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.interaction.inputbox?view=net-5.0)

**Comment by merriemcgaw** [comment]
I wonder if there's a more modern Win32 dialog that already exists that we can pull in instead of working on this particular dialog?

**Comment by merriemcgaw** [comment]
@KathleenDollard what are your thoughts?

**Comment by RussKie** [comment]
This API is being deprecated (see https://github.com/dotnet/runtime/pull/73838) because it doesn't meet the current accessibility standards and the Windows UI guidelines. It is recomended for projects that require an input box roll their own implementation.
