### ISSUE TITLE
The Editing Rectangle of TreeNode is truncated by the border of TreeView control

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#3118]
* .NET Core Version: 
5.0.100-preview.5.20221.6

* Have you experienced this same bug with .NET Framework?: 
Yes

**More info:**
1. This issue is a not regression issue, also can reproduce with VS2015, VS2017 and VS2019 from .NET framework 3.5 to 4.8.
2. This issue also reproduce with .NET Core 3.1.

**Problem description:**
The Editing rectangle of the first Node is truncated.
![Actual](https://user-images.githubusercontent.com/18568603/79964200-f22d6200-84bc-11ea-9776-369e989cecf3.png)

**Expected behavior:**
There should no truncation.
![Expected](https://user-images.githubusercontent.com/18568603/79964223-fa859d00-84bc-11ea-9887-ec06467ee48b.png)

**Minimal repro:**
1.	Create a .NET Core winforms project.
2.	Drag a TreeView control, set the LabelEdit property to True.
3.	Click the smart tag in the top-right corner to show the TreeView Tasks window.
4.	Click the ‘Edit Nodes…’, add 2 Root Nodes with default name: Node0 & Node1.
5.	Build and run it, double click on the Nodes to edit.

Or 
1.	Run the attached project.
[TreeViewEditingRectangleTruncated.zip](https://github.com/dotnet/winforms/files/4515070/TreeViewEditingRectangleTruncated.zip)
2.	Click the Node0, then click button1.

**Comment by weltkante** [comment]
If I'm not mistaken node renaming (and thus this bug) is implemented in the native control and not in WinForms

**Comment by merriemcgaw** [comment]
Yeah, it's going to be tricky to get the Win32 control to take on the risk of regression doing a fix there would introduce. This doesn't have the impact to me where I would consider reimplementation on the WinForms side. We'll chat in Triage this week and decide what we do with this one.

**Comment by merriemcgaw** [comment]
I'm going to have to close this as external. This really belongs to Win32, if they don't fix it I don't think WinForms is the right place to make the fix - we do enough custom drawing already 😀.
