### ISSUE TITLE
Some tests depend on machine specifics

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#3121]
**.NET Core Version:**
5.0 master branch

**Have you experienced this same bug with .NET Framework?:**
not applicable

**Problem description:**
After removing culture-specific test failures (tracked by #2734) there are a few more tests failing for me which I believe happen due to relying on machine specific conditions.

<details><summary>list of failed tests</summary>

```
* System.Windows.Forms.Tests.CursorTests.Cursor_Clip_Set_GetReturnsExpected
Assert.Equal() Failure
Expected: {X=0,Y=0,Width=3456,Height=1080}
Actual:   {X=0,Y=0,Width=3840,Height=1080}
   at System.Windows.Forms.Tests.CursorTests.Cursor_Clip_Set_GetReturnsExpected() in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\CursorTests.cs:line 176

* System.Windows.Forms.Tests.ListViewTests.ListView_GetItemRect_InvokeWithHandle_ReturnsExpected
Assert.True() Failure
Expected: True
Actual:   False
   at System.Windows.Forms.Tests.ListViewTests.ListView_GetItemRect_InvokeWithHandle_ReturnsExpected() in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ListViewTests.cs:line 3680

* System.Windows.Forms.Tests.ListViewTests.ListView_GetItemRect_InvokeWithoutHandle_ReturnsExpectedAndCreatedHandle
Assert.True() Failure
Expected: True
Actual:   False
   at System.Windows.Forms.Tests.ListViewTests.ListView_GetItemRect_InvokeWithoutHandle_ReturnsExpectedAndCreatedHandle() in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ListViewTests.cs:line 3645

* System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_CalendarDimensions_SetAreaOfTwelve_GetReturnsExpected(width: 12, height: 1)
Assert.True() Failure
Expected: True
Actual:   False
   at System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_CalendarDimensions_SetAreaOfTwelve_GetReturnsExpected(Int32 width, Int32 height) in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\MonthCalendarTests.cs:line 586

* System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_CalendarDimensions_SetWithHandleAreaOfTwelve_GetReturnsExpected(width: 12, height: 1)
Assert.True() Failure
Expected: True
Actual:   False
   at System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_CalendarDimensions_SetWithHandleAreaOfTwelve_GetReturnsExpected(Int32 width, Int32 height) in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\MonthCalendarTests.cs:line 644

* System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_SingleMonthSize_GetWithHandle_ReturnsExpected
Assert.True() Failure
Expected: True
Actual:   False
   at System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_SingleMonthSize_GetWithHandle_ReturnsExpected() in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\MonthCalendarTests.cs:line 2338

* System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Ctor_Default
Assert.Equal() Failure
Expected: 2
Actual:   79
   at System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Ctor_Default() in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ToolStripDropDownTests.cs:line 142

* System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Location_Set_GetReturnsExpected(value: {X=-1,Y=-2}, expected: {X=0,Y=0}, expectedLocationChangedCallCount: 0)
Assert.Equal() Failure
Expected: 0
Actual:   77
   at System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Location_Set_GetReturnsExpected(Point value, Point expected, Int32 expectedLocationChangedCallCount) in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ToolStripDropDownTests.cs:line 1966

* System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Location_Set_GetReturnsExpected(value: {X=0,Y=2}, expected: {X=0,Y=2}, expectedLocationChangedCallCount: 1)
Assert.Equal() Failure
Expected: 0
Actual:   77
   at System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Location_Set_GetReturnsExpected(Point value, Point expected, Int32 expectedLocationChangedCallCount) in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ToolStripDropDownTests.cs:line 1966

* System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Location_Set_GetReturnsExpected(value: {X=1,Y=0}, expected: {X=1,Y=0}, expectedLocationChangedCallCount: 1)
Assert.Equal() Failure
Expected: 1
Actual:   77
   at System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Location_Set_GetReturnsExpected(Point value, Point expected, Int32 expectedLocationChangedCallCount) in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ToolStripDropDownTests.cs:line 1966

* System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Location_Set_GetReturnsExpected(value: {X=1,Y=2}, expected: {X=1,Y=2}, expectedLocationChangedCallCount: 1)
Assert.Equal() Failure
Expected: 1
Actual:   77
   at System.Windows.Forms.Tests.ToolStripDropDownTests.ToolStripDropDown_Location_Set_GetReturnsExpected(Point value, Point expected, Int32 expectedLocationChangedCallCount) in D:\projects\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ToolStripDropDownTests.cs:line 1966
```

</details>

There is a compromise to make between developer convenience and how exactly you require tests matching their OS environment, if they are too strict developers can run tests only in a VM.

So far I could identify:
- Some MonthCalendar tests generate a _huge_ control and rely on the OS cutting them off. If you actually have a big work area (e.g. two screens) this leads to test failures since the controls are no longer cut off and are larger than the test expects.
- Some tests mix up coordinate spaces and do not consider the fact that the taskbar is not necessarily at the bottom. When the OS ensures the taskbar is not covered some tests fail because the forms/controls are not at the location they expect them to be. This is easily worked around by considering the work area inside the test, not the virtual screen space.

I'll put together a PR, so you can then decide which of the changes are reasonable enough to take.

**Expected behavior:**
Tests are (within reason) coded to be independent of machine characteristics.

**Minimal repro:**
Having either of these characteristics will fail some tests:
* Set the taskbar to the left side of the monitor (instead of default bottom) and run the tests
* Use a multi-screen machine and run the tests (very wide or very high work area)

**Comment by hughbe** [comment]
I would emphasise getting tests passing on ANY machine over specific VMs as it reduces the contribution burden

**Comment by weltkante** [comment]
There are a lot of global knobs to turn in Windows, I would not expect tests to accomodate for all of them. Some things may even be impossible to test on some machines. Like theming may be turned off globally, it'd be hard to get those tests running sucessfully, the best you can do is to detect this and skip them.

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/80341269-7315a080-88a5-11ea-860e-a9b7c759144b.png)

Yes, our tests should be runnable on a typical developer workstations, that I'd presume be a default W10 machine (default theme, primary HD or 4K monitor, several monitors as an option).
The default locale shouldn't cause issues, out tests should configure en-US where necessary.

**Comment by RussKie** [comment]
Reopening since we still have few tests that appear to be machine specific:

```
    System.Windows.Forms.Tests.AxHostTests.AxHost_GetIFontDispFromFont_InvokeSimpleStyle_Roundtrips [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   254
      Stack Trace:
        C:\Development\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\AxHostTests.cs(1423,0): at System.Windows.Forms.Tests.AxHostTests.AxHost_GetIFontDispFromFont_InvokeSimpleStyle_Roundtrips()
    System.Windows.Forms.Tests.AxHostTests.AxHost_GetIFontFromFont_InvokeSimpleStyle_Roundtrips [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   254
      Stack Trace:
        C:\Development\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\AxHostTests.cs(1515,0): at System.Windows.Forms.Tests.AxHostTests.AxHost_GetIFontFromFont_InvokeSimpleStyle_Roundtrips()
    System.Windows.Forms.Tests.MonthCalendarTests.MonthCalendar_Handle_GetWithDefaultFirstDayOfWeek_Success [FAIL]
      Assert.Equal() Failure
      Expected: 6
      Actual:   0
```

**Comment by weltkante** [comment]
On first glance both failures seem to be related to culture, which was not subject of the fixes here (have a separate issue for that). 

> MonthCalendar_Handle_GetWithDefaultFirstDayOfWeek_Success

First day of week is a machine wide culture setting, expected value should come from CultureInfo or the test should run with the default en-US culture without user customizations.

> AxHost_GetIFontDispFromFont_InvokeSimpleStyle_Roundtrips 
> AxHost_GetIFontFromFont_InvokeSimpleStyle_Roundtrips 

The `iFont.Charset` depends on the machines locale, since you said somewhere else you had utf8/cyrillic setup thats probably the cause for the failure. I don't know if that goes away by switching to en-US culture, might require making the test more flexible.

**Comment by RussKie** [comment]
Debugged into `MonthCalendar_Handle_GetWithDefaultFirstDayOfWeek_Success` failure:

![image](https://user-images.githubusercontent.com/4403806/84486496-d38b6080-ace0-11ea-80bb-a185fe75ac3d.png)

There is a misalignment between values in `Day` and `DayOfWeek` enums, which causes incorrect expectations in my case.

**Comment by weltkante** [comment]
> There is a misalignment between values in Day and DayOfWeek enums, which causes incorrect expectations in my case.

So what did SendMessage actually return? Native code uses `LOCALE_IFIRSTDAYOFWEEK` for `Day.Default` so it certainly won't have returned 7, that would fail independent of machine settings.

Maybe this test failure detected an actual mismatch between the locale MonthCalendar uses and the CurrentCulture locale?

(Note the +6 mod 7 in the test code is to correct the misalignment between `Day` and `DayOfWeek` so the code is already aware of the difference.)

**Comment by RussKie** [comment]
> So what did SendMessage actually return?

![image](https://user-images.githubusercontent.com/4403806/84624235-56502d80-af24-11ea-969e-5e074ec73a57.png)

If I make the following change than the test pass:
```diff
-            int expected = (int)CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek + 6;
+            int expected = (int)CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek; 
```

**Comment by RussKie** [comment]
Actually it gets interesting.

Here's my Windows settings:
![image](https://user-images.githubusercontent.com/4403806/84625243-3883c800-af26-11ea-80aa-fc4564cdfc72.png)

Here's the `CultureInfo.CurrentCulture` instance:
![image](https://user-images.githubusercontent.com/4403806/84625398-84367180-af26-11ea-9710-58d5cfd81689.png)
..and expanded `DateTimeFormat` instance:
![image](https://user-images.githubusercontent.com/4403806/84625549-cc559400-af26-11ea-80a9-6d1cd6fd130e.png)

**Comment by weltkante** [comment]
> If I make the following change than the test pass:
> 
> ```diff
> -            int expected = (int)CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek + 6;
> +            int expected = (int)CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek; 
> ```

Definitely wrong, the docs of `MCM_GETFIRSTDAYOFWEEK` and the `Day` enum have different numeric values than `FirstDayOfWeek`. Changing it this way would break it for everyone else.

I think the key here is figuring out why your locale and CurrentCulture differ, might be a bug in the .NET Core runtime? Maybe check with Desktop Framework if it differs there as well?

Normally (on Desktop Framework) CurrentCulture has the Windows locale settings applied over it (it doesn't roundtrip, if you were to ask for `en-AU` you don't get the same culture back, `CurrentCulture` used to be special in that way)

**Comment by RussKie** [comment]
I tested further, I changed my Windows' first day of the week to be "Saturday".
`CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek` hasn't changed and remained `Sunday`.
`User32.SendMessageW(control.Handle, (User32.WM)ComCtl32.MCM.GETFIRSTDAYOFWEEK, IntPtr.Zero, IntPtr.Zero)` however returned `5`, which stands for `Saturday` in our `Day` enum:
https://github.com/dotnet/winforms/blob/100762af36a2d0caf6adc1e46f6d6b9ca1e6a8c0/src/System.Windows.Forms/src/System/Windows/Forms/Day.cs#L37-L40

So I can infer two things here:
1. We shouldn't use `CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek`, and/or
2. `CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek` is wrong.

@tarekgh @safern do you think you could demystify the purpose of `CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek` for me? I expect it (perhaps naively) to align with my Windows settings.

**Comment by RussKie** [comment]
Created a net472 app, and it starts looking like a bug in .NET runtime... 🤯 

![image](https://user-images.githubusercontent.com/4403806/84629560-dcbd3d00-af2d-11ea-97f1-aaa9313176da.png)

I created a standalone multi-targeting console app and ran it testing different start days (Sat and Wed):
```
PS C:\Development\!Tests\ConsoleApp-CultureInfo> dotnet run -f net472
Running: .NET Framework 4.8.4180.0
CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek: Saturday

PS C:\Development\!Tests\ConsoleApp-CultureInfo> dotnet run -f net48
Running: .NET Framework 4.8.4180.0
CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek: Saturday

PS C:\Development\!Tests\ConsoleApp-CultureInfo> dotnet run -f netcoreapp3.1
Running: .NET Core 3.1.2
CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek: Saturday

PS C:\Development\!Tests\ConsoleApp-CultureInfo> dotnet run -f net5.0
Running: .NET 5.0.0-preview.4.20213.10
CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek: Saturday

PS C:\Development\!Tests\ConsoleApp-CultureInfo> dotnet run -f net472
Running: .NET Framework 4.8.4180.0
CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek: Wednesday

PS C:\Development\!Tests\ConsoleApp-CultureInfo> dotnet run -f net48
Running: .NET Framework 4.8.4180.0
CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek: Wednesday

PS C:\Development\!Tests\ConsoleApp-CultureInfo> dotnet run -f netcoreapp3.1
Running: .NET Core 3.1.2
CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek: Wednesday

PS C:\Development\!Tests\ConsoleApp-CultureInfo> dotnet run -f net5.0
Running: .NET 5.0.0-preview.4.20213.10
CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek: Wednesday
```

Then I pointed to winforms/.dotnet and.... 💥 
```
PS C:\Development\!Tests\ConsoleApp-CultureInfo> $env:PATH="C:\Development\winforms\.dotnet;$env:PATH"
PS C:\Development\!Tests\ConsoleApp-CultureInfo> powershell
PS C:\Development\!Tests\ConsoleApp-CultureInfo> dotnet run -f net5.0
Running: .NET 5.0.0-preview.6.20264.1
CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek: Sunday
```

**Comment by tarekgh** [comment]
> @tarekgh @safern do you think you could demystify the purpose of CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek for me? I expect it (perhaps naively) to align with my Windows settings.

We have a bug in .NEt 5.0 which currently @safern working on fixing it. https://github.com/dotnet/runtime/issues/37121

**Comment by RussKie** [comment]
Some more locale-specific tests
```
    System.Windows.Forms.Tests.Interop.Kernel32.FILETIMETests.FILETIME_ToDateTime_Invoke_ReturnsExpected [FAIL]
      Assert.Equal() Failure
      Expected: 2020-05-13T13:03:12.0000000
      Actual:   2020-05-13T23:03:12.0000000+10:00
      Stack Trace:
        C:\Development\winforms\src\System.Windows.Forms.Primitives\tests\UnitTests\Interop\Kernel32\FILETIMETests.cs(46,0): at System.Windows.Forms.Tests.Interop.Kernel32.FILETIMETests.FILETIME_ToDateTime_Invoke_ReturnsExpected()
    System.Windows.Forms.Tests.Interop.Kernel32.FILETIMETests.FILETIME_Ctor_DateTime [FAIL]
      Assert.Equal() Failure
      Expected: 3680495616
      Actual:   162781184
      Stack Trace:
        C:\Development\winforms\src\System.Windows.Forms.Primitives\tests\UnitTests\Interop\Kernel32\FILETIMETests.cs(34,0): at System.Windows.Forms.Tests.Interop.Kernel32.FILETIMETests.FILETIME_Ctor_DateTime()
    System.Windows.Forms.Tests.Interop.Oleaut32.VARIANTTests.VARIANT_ToObject_DateFromFILETIME_Success [FAIL]
      Assert.Equal() Failure
      Expected: 2020-05-13T13:03:12.0000000
      Actual:   2020-05-13T03:03:12.0000000
      Stack Trace:
        C:\Development\winforms\src\System.Windows.Forms.Primitives\tests\UnitTests\Interop\Oleaut32\VARIANTTests.cs(6034,0): at System.Windows.Forms.Tests.Interop.Oleaut32.VARIANTTests.<>c__DisplayClass299_0.<AssertToObjectEqual>b__0(Object actual)
        C:\Development\winforms\src\System.Windows.Forms.Primitives\tests\UnitTests\Interop\Oleaut32\VARIANTTests.cs(6049,0): at System.Windows.Forms.Tests.Interop.Oleaut32.VARIANTTests.AssertToObject(VARIANT variant, Action`1 action)
        C:\Development\winforms\src\System.Windows.Forms.Primitives\tests\UnitTests\Interop\Oleaut32\VARIANTTests.cs(6034,0): at System.Windows.Forms.Tests.Interop.Oleaut32.VARIANTTests.AssertToObjectEqual(Object expected, VARIANT variant)
        C:\Development\winforms\src\System.Windows.Forms.Primitives\tests\UnitTests\Interop\Oleaut32\VARIANTTests.cs(884,0): at System.Windows.Forms.Tests.Interop.Oleaut32.VARIANTTests.VARIANT_ToObject_DateFromFILETIME_Success()
```

**Comment by RussKie** [comment]
I think this issue has resolved. I'm no longer getting any locale specific failures.
Holler if you still do, and we can reopen it.
