### ISSUE TITLE
Support creating "single instance" applications

### ISSUE THREAD

**Issue by cston** [dotnet/winforms#3131]
Consider support for creating "single instance" applications similar to the [VisualBasic Application Model](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/development-with-my/overview-of-the-visual-basic-application-model?view=netframework-4.8#uses-for-the-application-model).

In the VisualBasic model, an application opts-in by setting `WindowsFormsApplicationBase.IsSingleInstance = True`.

When a second instance of the application is launched, the first instance fires a `WindowsFormsApplicationBase.StartupNextInstance` event, and the second instance terminates.

**Comment by RussKie** [comment]
Thinking out loud here.

If we had an API that facilitated inter-process communications, e.g. (I've taken this from the email thread, and slightly tweaked):

```cs
namespace System.Windows.Forms
{
	public class SingleInstanceService
	{
        /// <summary>
        /// Create a named pipe or null if already exists.
        /// </summary>
        public NamedPipeServerStream CreateServer(string pipeName);
 
        /// <summary>
        /// Handle client connections asynchronously.
        /// </summary>
        public void WaitForClient(NamedPipeServerStream pipeServer, Action<string[]> callback);
 
        /// <summary>
        /// Send command-line arguments to first instance.
        /// </summary>
        public bool SendSecondInstanceArgs(string pipeName, int timeout, string[] args);
	}
}
```

Also have a similar event arguments to the VB:

```cs
namespace System.Windows.Forms
{
	public class StartupNextInstanceEventArgs : EventArgs
	{
		public StartupNextInstanceEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> commandLine, bool bringToForeground);

		public bool BringToForeground { get; }
		public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
	}
}
```

We could expose it via `System.Windows.Forms.Application` and provide a "run only once" kind of method (i.e. a user may not be allowed to invoke it once an app has started):

```cs
namespace System.Windows.Forms
{
    public partial class Application
    {
        /// <summary>
        /// Send command-line arguments to first instance.
        /// </summary>
        /// <param name=uid">System-wide unique identifier of the app.</param>
        public void SetSingleInstance(string uid, Action<StartupNextInstanceEventArgs> handler);
    }
}
```

### API Usage

```C#
class Program
{
    [STAThread]
    static void Main()
    {
        Application.SetHighDpiMode(HighDpiMode.SystemAware);
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);

        Application.SetSingleInstance("my super awesome single instance app", 
				(args, bringToForeground) => { ... });

        Application.Run(new Form1());
    }
}
```

On the VB side we could then reuse `System.Windows.Forms.SingleInstanceService` and fulfil the existing API contract. 
And I think we can jam one level on inheritance into `Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs` to be (sorry I'm not good at writing VB code):
```cs
namespace Microsoft.VisualBasic.ApplicationServices 
{
	public class StartupNextInstanceEventArgs : System.Windows.Forms.StartupNextInstanceEventArgs 
	{
	}
}
```


What do you think?

**Comment by cston** [comment]
@RussKie, the approach sounds reasonable. A couple of comments:

Do we need a `SingleInstanceService` class, or would a set of `static` helper methods be sufficient? If a service is needed, how would an application obtain an instance of the service?

`Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs` shouldn't need to inherit from `System.Windows.Forms.StartupNextInstanceEventArgs` since the event args are only used in the application classes, not in the service. For instance, the VB implementation could use:
```VB
service.WaitForClient(pipeServer,
    Sub(args As String())
        MainForm.Invoke(
            Sub()
                OnStartupNextInstance(New StartupNextInstanceEventArgs(
                    New ReadOnlyCollection(Of String)(args)))
            End Sub)
    End Sub)
```

**Comment by RussKie** [comment]
> Do we need a `SingleInstanceService` class, or would a set of `static` helper methods be sufficient? If a service is needed, how would an application obtain an instance of the service?

IMO static helper methods tend to cause a lot of headache especially when testing. In general I prefer instance-based classes.
Also in this case without a containing class I feel we lose cohesion between the API.

> how would an application obtain an instance of the service?

Via `new()`.
I don't expect developers newing the manager in their code, I expect us to provide required API through `System.Windows.Forms.Application` type or the VB counterpart (`WindowsFormsApplicationBase` right?). `Application` will instantiate a copy of the manager to provided the desired functionality.

> `Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs` shouldn't need to inherit from `System.Windows.Forms.StartupNextInstanceEventArgs` since the event args are only used in the application classes, not in the service.

Even better 👍 
I wasn't sure how it is meant to be used.

**Comment by paul1956** [comment]
The algorithm VB uses for uid is a little complex to be compatibility with Framework so it would need to be past in on startup.

**Comment by weltkante** [comment]
> IMO static helper methods tend to cause a lot of headache especially when testing.

Static methods are best handled via profiler based mocking, which easily can replace any methods implementation. Unfortunately there is no non-commercial ready-to-use implementation available.

I've started working on a mocking helper based on https://github.com/microsoft/CLRInstrumentationEngine that can be used for both mocking and overriding implementations for testing purposes - it still needs a bit of time and some place to put once done but I personally wouldn't let testing considerations prevent designing a proper public API.

**Comment by RussKie** [comment]
> I personally wouldn't let testing considerations prevent designing a proper public API.

Testability is a consideration when we design public API, but it isn't a driving factor. There are other downsides to static types in my books such as don't work with DI, often cause to process-wide side effects, etc. And we hit few issues as part of our testing efforts. That's not to say our tests were always correct, but it indicates that static types can be easily misused.
There is certain value to having extension methods, but as any powerful tool those should be used with reason.

In Git Extensions we use hooks to intercept interop calls to handle theming. This is really black magic.

**Comment by weltkante** [comment]
Yeah I'm mostly just saying there are established ways in some frameworks to override static methods, non virtual methods, sealed classes etc. for testing purposes - and with CLRIE its not too far off to make something available in the open source space as well.

If you want to take the opportunity and see how you can make WinForms more DI friendly or composable, I'm not arguing against that.
