### ISSUE TITLE
PropertyGridView DropDownHolder is not covered by unit tests

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#3136]
* .NET Core Version: 

.NET Core 5.0

* Have you experienced this same bug with .NET Framework?: 

Yes

**Problem description:**

DropDownHolder control implementation is not covered by unit tests.

**Comment by LeafShi1** [comment]
Added unit tests for method SetDropDownControl, other public methods operate on private variables, so there is no need to add tests for them, so close this bug.
