### ISSUE TITLE
An error dialog pops up after clicking Add button in ToolStripItem Collection Editor

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#3142]
* .NET Core Version: 
5.0.100-preview.5.20226.6

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
An error dialog is occurring after clicking the Add button.
![Error](https://user-images.githubusercontent.com/18568603/80338361-badcfd80-888e-11ea-9040-8715186848eb.png)

**Expected behavior:**
The items can be added successfully without any error/warning popping up.

**More info:**

1. This issue also can reproduce with BindingNavigator/ContextMenuStrip/MenuStrip/StatusStrip/ToolStrip controls
2. This issue also can reproduce with .Net Core 3.1.

**Minimal repro:**
1.	Create a winforms core project.
2.	Add a propertyGrid control to form.
3.	Add a MenuStrip control to form.
4.	Add this code in form initializeComponent part: propertyGrid1.SelectedObject = menuStrip1;
5.	Find the Items property of MenuStrip, click the Browser button to show the ToolStripItem Collection Editor.
6.	Click the Add button.

Or 
1.	Run the attached project.
[System.ToolStripItem.zip](https://github.com/dotnet/winforms/files/4537729/System.ToolStripItem.zip)
2.	Run it, and do the above step 5-6.

**Comment by JeremyKuhne** [comment]
This is likely a missing attribute. @lonitra can you tag in links to the similar fix you did?

**Comment by lonitra** [comment]
If we have a specific editor for ToolStripItem then the fix will likely be similar to #3120 to pop up the correct editor, otherwise we may have to do something like #3111 to keep from throwing an error on the generic editor.

**Comment by merriemcgaw** [comment]
@lonitra feel free to add a PR for this fix 😁

**Comment by RussKie** [comment]
@Vino-Wang is this sill an issue?
