### ISSUE TITLE
[loc][Query][winforms] Localizability of strings

### ISSUE THREAD

**Issue by PDostalek** [dotnet/winforms#3146]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Thanks in advance for the reply

Id | File Name Live Page Extended | String Resource ID | Full Source String | Query: | Answer:
-- | -- | -- | -- | -- | --
49,502 | System.Windows.Forms\src\Resources\xlf\SR.xlf | 0;   "TaskDialogCannotUpdateAfterNavigation" | Cannot manipulate the task   dialog immediately after navigating it. Please wait for the {0} event of the   next page to occur. | Could you please explain what   exactly you mean by 'navigating a dialog'? How is it different from   manipulating a dialog? Normally we'd understand 'to navigate' to mean when   the user is working with the dialog, clicking buttons etc. But here the   meaning is apparently very different.          Affected ResourceIDs:     0; "TaskDialogCannotNavigateClosedDialog"     0; "TaskDialogCannotNavigateWithinNavigationEventHandler"     0; "TaskDialogCannotNavigateWithinRadioButtonCheckedChanged"     0; "TaskDialogCannotNavigateWithoutDialog"     0; "TaskDialogCannotUpdateAfterNavigation"     0; "TaskDialogNavigationNotCompleted" |  
49,503 | System.Windows.Forms\src\Resources\xlf\SR.xlf | 0;   "TaskDialogCollectionAlreadyBound" | One of the collections of this   {0} is already bound to a {1} instance. | Please provide the meaning of   placeholder {0} in the below ResourceIDs:          0; "TaskDialogCollectionAlreadyBound"     One of the collections of this {0} is already bound to a {1}   instance.          0; "TaskDialogControlAlreadyBound"     One of the controls of this {0} is already bound to a {1} instance. |  
49,513 | System.Windows.Forms\src\Resources\xlf\SR.xlf | 0;   "TaskDialogCollectionAlreadyBound" | One of the collections of this   {0} is already bound to a {1} instance. | Please confirm that placeholder   0 is referred to task dialog |

**Comment by RussKie** [comment]
@kpreisser could you please help?

**Comment by kpreisser** [comment]
Hi,

> Id 49,502
> 0; "TaskDialogCannotUpdateAfterNavigation"
> Could you please explain what exactly you mean by 'navigating a dialog'? How is it different from manipulating a dialog? Normally we'd understand 'to navigate' to mean when the user is working with the dialog, clicking buttons etc. But here the meaning is apparently very different. Affected ResourceIDs: 0; "TaskDialogCannotNavigateClosedDialog" 0; "TaskDialogCannotNavigateWithinNavigationEventHandler" 0; "TaskDialogCannotNavigateWithinRadioButtonCheckedChanged" 0; "TaskDialogCannotNavigateWithoutDialog" 0; "TaskDialogCannotUpdateAfterNavigation" 0; "TaskDialogNavigationNotCompleted"

"Navigating a dialog" here is used under the "definition" that a task dialog displays a page (`TaskDialogPage`). Navigating the dialog means navigating to a different page (so all of the dialog's contents are replaced with the contents from the new page), similar to a web browser that navigates to a different page.
(Navigation is a bit of heavy-weight operation, it takes some time to complete.)

"Manipulating a dialog" in the resources here refers to light-weight updates of the dialog (e.g. change its text, icon, progress bar value, where the update operation completes immediately).

> Id 49,503
> 0; "TaskDialogCollectionAlreadyBound"
> Please provide the meaning of placeholder {0} in the below ResourceIDs: 0; "TaskDialogCollectionAlreadyBound" One of the collections of this {0} is already bound to a {1} instance. 0; "TaskDialogControlAlreadyBound" One of the controls of this {0} is already bound to a {1} instance.

> Id 49,513
> 0; "TaskDialogCollectionAlreadyBound"
> Please confirm that placeholder 0 is referred to task dialog

In these strings, placeholder `0` is `TaskDialogPage`, placeholder `1` is `TaskDialog`.

Hope this helps! Thank you!

**Comment by RussKie** [comment]
@PDostalek is this resolved? Can we close the issue?

**Comment by PDostalek** [comment]
Thank you @RussKie
