### ISSUE TITLE
Code coverage is a bit useless right now, appears broken

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#3160]
* .NET Core Version: 
Master

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
We have a lot of errors such as "File not found in report"

E.g. https://codecov.io/gh/dotnet/winforms/pull/3089/changes
![image](https://user-images.githubusercontent.com/1275900/80572554-618fde00-89f6-11ea-9cd9-9ec66a9dacd2.png)

Also, a lot of PRs say "-36%" coverage, which is obviously wrong

![image](https://user-images.githubusercontent.com/1275900/80572593-6f456380-89f6-11ea-9702-0b695565d972.png)

**Comment by RussKie** [comment]
Presume fixed
