### ISSUE TITLE
Controls (with Anchor Right) scaling bugs inside splitContainer

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#3168]
* .NET Core Version: **3.1.3**

* Have you experienced this same bug with .NET Framework?: **Yes**

**Problem description:**

Controls, that placed inside splitContainer and have in Anchor  property `Right` (may be `Bottom` too) flag make their size and position wrong with other dpi or font.

Designer (Win7 100% dpi):
![Designer](https://user-images.githubusercontent.com/17767561/80703477-8914a280-8aeb-11ea-8228-8a04b01f4d36.png)

Win7 auto Font 100% dpi (problems with core due to default font changed):
![W7_100_AF](https://user-images.githubusercontent.com/17767561/80703188-01c72f00-8aeb-11ea-8c47-16d2b82e7a8d.png)

Win7 auto Font 100% and 125% dpi (problems due to dpi change). No core here because with auto font it's mess even with 100% dpi:
![W7_100+125_AF](https://user-images.githubusercontent.com/17767561/80703340-40f58000-8aeb-11ea-82a0-f745ba88d8f4.png)

Win7 fixed Font 100% dpi (all ok):
![W7_100_DF](https://user-images.githubusercontent.com/17767561/80703581-b2353300-8aeb-11ea-815e-22de9cd2e804.png)

Win7 fixed Font 125% dpi (problems due to dpi change):
![W7_125_FF_net](https://user-images.githubusercontent.com/17767561/80749280-e2ea8c00-8b2e-11ea-9f0a-24d505190269.png)
![W7_125_FF_core](https://user-images.githubusercontent.com/17767561/80749292-e716a980-8b2e-11ea-8ac4-b777e8f57bc4.png)

All screens from attached project.
This bug only valid when dpi > 100% (system font size?), so all screenshot where you see _font set in designer_ - not affected, because of 100 dpi.

Some notes:

Removing fixed panel from splitContainer lead to different behavior (still wrong).

Due to WinForms designer/dpi scaling logic bug, font for the form must be set manually - in `Form1.Designer.cs` **before** `AutoScaleDimensions` set, or in form constructor **before** `InitializeComponent();`
Designer puts font settings **after** scale logic, **that completely break it**:
![Snipaste_2020-04-30_19-18-56](https://user-images.githubusercontent.com/17767561/80750055-1a0d6d00-8b30-11ea-9fc4-5017e9b06fd3.png)
I have opened a [new issue](https://github.com/dotnet/winforms/issues/3202) for this.

[Blog post](http://blog.davidegrayson.com/2013/04/unusable-ui-caused-by-windows-forms.html) about scaling problems with `Anchor Right/Bottom`.

**Expected behavior:**
Same position and proportional size change.

**Minimal repro:** 
[WinFormsCoreTest_dpi.zip](https://github.com/dotnet/winforms/files/4557769/WinFormsCoreTest_dpi.zip)

------------------------------------------------------------------------------------------

And for last - Seems a regression in Win10 .net runtime? On win 7 working good both on .net and core, on Win10 only on core.
![W10_100_DF](https://user-images.githubusercontent.com/17767561/80704410-2fad7300-8aed-11ea-8fd7-5a67d921b174.png)
On win10 I can't achieve normal result even with 100% dpi (no matter auto font, or manual set).
I understand that this is wrong place for .net bugs, but may be you transfer it to .net team?
Win10 pro 1809/1909.

**Comment by kirsan31** [comment]
At first look, problems can be solved with this:
![image](https://user-images.githubusercontent.com/17767561/80963118-035c6400-8e17-11ea-8db2-2672732b94e2.png) 
:scream:
![Snipaste_2020-05-04_14-49-42](https://user-images.githubusercontent.com/17767561/80963262-40c0f180-8e17-11ea-9ad3-ab6e86e2a159.png)


But only with: `this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;` With other docking this addition breaks even 100% dpi look :(

So, problems definitely relays with nesting containers initialization, and may be with https://github.com/dotnet/winforms/issues/3202.

**Comment by tewarid** [comment]
Setting 

```c#
Application.SetHighDpiMode(HighDpiMode.DpiUnawareGdiScaled); 
```

seem to produce somewhat better results. SplitContainer is seriously broken when orientation is System.Windows.Forms.Orientation.Horizontal.

**Comment by RussKie** [comment]
> Due to WinForms designer/dpi scaling logic bug, font for the form must be set manually - in `Form1.Designer.cs` **before** `AutoScaleDimensions` set, or in form constructor **before** `InitializeComponent();`
> Designer puts font settings **after** scale logic, **that completely break it**:

This shouldn't be necessary with the new [`SetDefaultFont` API](https://docs.microsoft.com/dotnet/api/system.windows.forms.application.setdefaultfont). The [simplified app bootstrap](https://github.com/dotnet/winforms/pull/5035) will also make the designer render the forms and controls with the desired font metrics (VS 17.0p3+).
This obviously is not a solution, but can help in certain scenarios.

**Comment by Philip-Wang01** [comment]
Verified this issue on latest .NET 8.0.100-alpha.1.225559.18 build, most scaling issues have been fixed, found a new issue and tracked it with [8157](https://github.com/dotnet/winforms/issues/8157).
