### ISSUE TITLE
Can't publish app for linux-arm64 or ubuntu-arm64

### ISSUE THREAD

**Issue by KhArtNJava** [dotnet/winforms#3179]
Steps to produce:

- Create a project from Windows Forms App (.Net core) template in visualstudio 2019 with .Net Core 5.0 or with .Net Core 3.1 .
- Click on build -> publish
- Change deployment mode to: Self-contained
- Change target framework to: linux-arm64 or ubuntu-arm64

Actual result: the screen display this error:
![image](https://user-images.githubusercontent.com/757085/80839464-f61b5b80-8c03-11ea-9f87-512d71d9a25b.png)

Build output is:
```
1>------ Build started: Project: test4, Configuration: Release Any CPU ------
1>You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>test4 -> C:\Projects\test4\bin\Release\net5.0\test4.dll
2>------ Publish started: Project: test4, Configuration: Release Any CPU ------
2>Determining projects to restore...
2>Restored C:\Projects\test4\test4.csproj (in 275 ms).
2>There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'linux-arm64'.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

```

Expected result: Publish successfull

Is it possible to compile .Net Core WinForms app compile for ARM64 (linux-arm64 or ubuntu-arm64)?

**Comment by kirsan31** [comment]
No. WinForms and WPF are windows only.

**Comment by KhArtNJava** [comment]
So, I have to use .Net Framework WinForms app with Mono?

**Comment by RussKie** [comment]
Correct. Refer to https://github.com/dotnet/winforms/blob/master/README.md
![image](https://user-images.githubusercontent.com/4403806/80944986-1dee0780-8e2e-11ea-8836-c832df368fb3.png)
