### ISSUE TITLE
GroupBoxAccessibleObject class definition should be in a separate file

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#3229]
* .NET Core Version: 

.NET Core 5.0
Version: 5.0.100-alpha.1.20073.10
Commit: 29f4d693a9
Runtime Environment:
OS Name: Windows
OS Version: 10.0.18363
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\5.0.100-alpha1-05536
Host (useful for support):
Version: 5.0.0-alpha.1.20072.3
Commit: c3dc1fdfdc

**Problem description:**

GroupBoxAccessibleObject class definition is located in the same file as a GroupBox control definition.

**Expected behavior:**

GroupBoxAccessibleObject class should be in a separate file and GroupBox class should be partial.

**Comment by hughbe** [comment]
Not sure if there's a policy I missed but I don't think changes like this need an issue :))

**Comment by RussKie** [comment]
Technically it is good to have an issue that discusses an underlying problem and all that comes with it. But for mundane refactors like this we can just send a PR.
