### ISSUE TITLE
Unnecessary instances of ToolStripDropDownMenu

### ISSUE THREAD

**Issue by filipnavara** [dotnet/winforms#3248]
* .NET Core Version: 3.1.200, 5.0

* Have you experienced this same bug with .NET Framework?: Haven't tried.

**Problem description:**

Unnecessary tooltip drop-downs are instantiated from the keyboard hook:

``` 	System.Windows.Forms.dll!System.Windows.Forms.ToolStripDropDownMenu.ToolStripDropDownMenu(System.Windows.Forms.ToolStripItem ownerItem, bool isAutoGenerated) (IL=0x00B4, Native=0x21319D68+0x1C7)
 	System.Windows.Forms.dll!System.Windows.Forms.ToolStripMenuItem.CreateDefaultDropDown() (IL=0x0007, Native=0x21319D18+0x37)
 	System.Windows.Forms.dll!System.Windows.Forms.ToolStripDropDownItem.DropDown.get() (IL≈0x0008, Native=0x21319C30+0x4D)
>	System.Windows.Forms.dll!System.Windows.Forms.ToolStripDropDownItem.OnKeyboardToolTipHook(System.Windows.Forms.ToolTip toolTip) (IL≈0x000C, Native=0x21319B98+0x3F)
 	System.Windows.Forms.dll!System.Windows.Forms.ToolStripItem.System.Windows.Forms.IKeyboardToolTip.OnHooked(System.Windows.Forms.ToolTip toolTip) (IL=0x0007, Native=0x21319B58+0x2B)
 	System.Windows.Forms.dll!System.Windows.Forms.KeyboardToolTipStateMachine.Hook(System.Windows.Forms.IKeyboardToolTip tool, System.Windows.Forms.ToolTip toolTip) (IL=0x0017, Native=0x213199C0+0x48)
 	System.Windows.Forms.dll!System.Windows.Forms.ToolStrip.OnItemAddedInternal(System.Windows.Forms.ToolStripItem item) (IL=0x0019, Native=0x21319910+0x62)
 	System.Windows.Forms.dll!System.Windows.Forms.ToolStripItemCollection.Add(System.Windows.Forms.ToolStripItem value) (IL=0x0036, Native=0x21318418+0x8A)
 	System.Windows.Forms.dll!System.Windows.Forms.ToolStripItemCollection.AddRange(System.Windows.Forms.ToolStripItem[] toolStripItems) (IL≈0x003C, Native=0x21318280+0x101)
```

`ToolStripDropDownItem.OnKeyboardToolTipHook` is creating instances of `ToolStripDropDownMenu` even if there is no submenu used. It should probably first check for the existence of the drop-down menu like the other code in the class does.

Additionally, the `ToolStripDropDownMenu` objects are not properly disposed with the rest of the control tree:

![image](https://user-images.githubusercontent.com/1764393/81475674-fcb26000-920d-11ea-92fe-baa46789cb3d.png)

This is a screenshot from a memory profiler after a `Form` with couple of controls was closed. Note that all the objects eventually get finalized but the `ControlNativeWindow` linked to the `ToolStripDropDownMenu` objects has `suppressedGC = false` property so it likely was not destroyed properly.

**Expected behavior:**

No additional `ToolStripDropDownMenu` allocations for toolstrip menu items that have no submenus.

**Minimal repro:**

No repro at the moment, will update the issue if I can come up with small sample.

**Comment by filipnavara** [comment]
Attempted fix (against release/3.1): https://github.com/filipnavara/winforms/tree/ToolStripDropDownItem_hook_3.1

**Comment by JeremyKuhne** [comment]
@filipnavara Could you make a PR against master?

**Comment by filipnavara** [comment]
Sure. Will do it tomorrow.

**Comment by filipnavara** [comment]
The branch is here: https://github.com/filipnavara/winforms/tree/ToolStripDropDownItem_hook

I'll do some local tests with memory profiler before opening a PR. Not exactly sure how to unit test it though.

**Comment by DalekBaldwin** [comment]
Are you able to suggest a workaround as well?

It sounds like this might be the underlying reason we've had trouble porting a WinForms app from Framework to Core, with this stack trace occurring in several places when attempting to close tabs:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.ToolStripControlHost.OnKeyboardToolTipUnhook(ToolTip toolTip)
   at System.Windows.Forms.ToolStripItem.System.Windows.Forms.IKeyboardToolTip.OnUnhooked(ToolTip toolTip)
   at System.Windows.Forms.ToolStrip.OnItemRemovedInternal(ToolStripItem item)
   at System.Windows.Forms.ToolStripItemCollection.OnAfterRemove(ToolStripItem item)
   at System.Windows.Forms.ToolStripItemCollection.Remove(ToolStripItem value)

**Comment by DalekBaldwin** [comment]
Actually, this seems to be an order-of-disposal issue on our end that should have caused the same problem on the old .Net Framework builds, but for some reason it never did.
