### ISSUE TITLE
DataGridViewCell ComboBox causes application crash in some circumstances

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#3251]
* .NET Core Version: 

.NET Core 5.0
Version: 5.0.100-alpha.1.20073.10
Commit: 29f4d693a9
Runtime Environment:
OS Name: Windows
OS Version: 10.0.18363
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\5.0.100-alpha1-05536
Host (useful for support):
Version: 5.0.0-alpha.1.20072.3
Commit: c3dc1fdfdc

* Have you experienced this same bug with .NET Framework?: 

Yes

**Problem description:**

Sometimes DataGridViewComboBox cell causes application crash when changing ComboBox selected values.

**Expected behavior:**
No crash.

**Minimal repro:**
- Create WinForms app with the DataGridView control and ComboBox cell and other cells with different control types.
- Run app and change ComboBox cell selected value.

**DevDiv issue:**
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1071695

**Comment by RussKie** [comment]
@merriemcgaw if it is being serviced in .NET Framework, will we be servicing .NET Core 3.1 as well?

**Comment by merriemcgaw** [comment]
We absolutely should service it in 3.1. For some reason I thought we had done this or something very like it in 3.1 servicing. Am I imagining things 😂

**Comment by Jenna-Zheng** [comment]
Verified with .NET Core 5.0.100-preview.5.20269.19 build, this issue is fixed, now DataGridViewCell Combox not causes application crash.
![3251-TestResult](https://user-images.githubusercontent.com/64949616/82430229-a40d7d80-9abf-11ea-8d85-10c944f058c0.gif)
