### ISSUE TITLE
Support Legacy Windows Forms Designer with SDK-Style projects

### ISSUE THREAD

**Issue by ben-page** [dotnet/winforms#3262]
**Visual Studio Version**:
16.5.4
**Summary**:
I have a large enterprise application based on Windows Forms. It's made up of four assemblies.

1. DataAndBusinessLogic
2. WinFormsSupport - references DataAndBusinessLogic
3. ApplicationDataAndBusinessLogic - references DataAndBusinessLogic
4. ApplicationUI - references DataBusinessLogic,WinFormsSupport, & ApplicationDataAndBusinessLogic 

We'd like to add a fifth: a .NET Core Blazor project:
5. ApplicationWebUi - references ApplicationDataAndBusinessLogic & DataAndBusinessLogic

We want to maintain the WinForms UI while developing the Blazor UI. And we want them to share the same Data and BI libraries.

We made this work (or build at least). But we can't get the Windows Forms Designer to work at all.

**Steps to Reproduce**:
I converted the supporting libraries (1 & 3) to SDK-Style projects and had compile both .NET Framework and .NET Core assemblies.
```
<TargetFrameworks>net48;netcoreapp3.1</TargetFrameworks>
```
In the ApplicationUI project, the Windows Forms designer works for simply forms. But if that form references anything from the other assemblies, the Designer will load.

I also tried converting the other projects to SDK-Style projects, but still targeting only the .NET Framework. I was also able to get this to compile, but it's now trying to use the .NET Core Windows Forms Designer, which obviously wont work.

**Comment by ben-page** [comment]
@jjmew, is closing issues without comment Microsoft policy? I but a lot of effort to clearly report this problem. You could at least say that Microsoft doesn't care about this.

Additionally, I don't think this issues should have been transferred here. This is the .NET Core Windows Forms repository, correct?

I'm trying to use the .NET Framework Window Forms designer in a project that references a library that uses a SDK style project file and targets multiple framework. This arrangement compiles and works. It's just that the Windows Forms designer does not. My problem is primarily a Visual Studio issue.

**Comment by jjmew** [comment]
@ben-page  I am sorry. The intent was to move the issue to dotnet/winforms and to close the one ne in Project-System. It seems like I had a misunderstanding of how to use the "Transfer Issue" feature in GitHub . When I closed the one in project system it propagated.  

The WinForms team is the one that will have to triage this issue

**Comment by RussKie** [comment]
@ben-page I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.

Given that you have a complex solution structure targeting different runtimes it is nearly impossible for us to simulate your scenario without a small clean repro solution provided by you. (And even then there is a chance that it may not repro, because there are way too many variable factors involved.)

**Comment by ben-page** [comment]
I really appreciate both responses.

And I'm happy to create a project that demonstrates the problem. I'll post the file here and use the VS Feedback tool on that project.

**Comment by merriemcgaw** [comment]
That would be wonderful @ben-page, thank you!
