### ISSUE TITLE
Use same application id for WindowsFormsApplicationBase.IsSingleInstance for same major.minor version number

### ISSUE THREAD

**Issue by cston** [dotnet/winforms#3296]
In .NET Framework, `WindowsFormsApplicationBase.IsSingleInstance` behavior uses an application id that is consistent for the same { major, minor } version numbers.

In dotnet/winforms, the `ModuleVersionID` is used for the application id which is distinct for each build. Consider matching .NET Framework by using an id that is consistent for { major, minor } version.

See [reference source](https://github.com/microsoft/referencesource/blob/master/Microsoft.VisualBasic/runtime/msvbalib/ApplicationServices/WindowsFormsApplicationBase.vb#L1502).

**Comment by RussKie** [comment]
@cston could you please clarify the request - is this a bug or new API request? 
Is this something you're planning to work on, or something up-for-grabs?

**Comment by cston** [comment]
@RussKie, this is a change in behavior from .NET Framework. I've updated the description to clarify. 

The issue is up for grabs.

**Comment by cston** [comment]
cc @KathleenDollard

**Comment by paul1956** [comment]
In framework Visual Studio creates a new GUID for every new project that never changes. There was a function in Framework GetTypeLibGuidForAssembly that got this GUID and then code here appended Major and Minor version strings and that was the string used to define a single instance. GetTypeLibGuidForAssembly no longer exists in Core and Visual Studio no longer creates the GUID but existing Framework applications will have it. The comment in the reference source recommended making the function that created the complete string Overrideable which would allow the developer to pick an algorithm that worked for them. The current function creates a new string on every build and they are different even with unchanged code and between debug and release.

**Comment by paul1956** [comment]
The AssembyInfo being add in #3352 has the GUID needed to make SingleInstance compatible with Framework.

**Comment by paul1956** [comment]
As soon as #3352 is checked in I will do a PR to address this in a way that will work when GUID is present and work as is when its not.
