### ISSUE TITLE
Extract stack traces of hanging CI test runs

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#3298]
**Is your feature request related to a problem? Please describe.**
Hangs in CI build are hard to diagnose, especially if they are not reproducable locally or do not happen deterministically.

**Describe the solution you'd like and alternatives you've considered**
[`dotnet-dump`](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) allows collecting dumps of a process and analyze them

PR #3056 started taking screenshots of hanging CI test runs, I think it would be even better if we used `dotnet-dump` to take dumps

**Will this feature affect UI controls?**
No, test infrastructure only

**Comment by weltkante** [comment]
Give the testing process id can be figured out, following powershell script takes a minidump (so storage size should be no concern) and extracts the stack traces. I also include the thread summary because it mentions apartments and lock counts.

```powershell
dotnet-dump collect --process-id $TargetProcessId --type mini --output hangdump
"clrthreads`nclrstack -all`nexit`n" |& dotnet-dump analyze hangdump > hangdump.txt
```

The CI build may also need to install dotnet-dump if arcade doesn't do that yet, see linked doc page.

**Comment by RussKie** [comment]
I've been mulling over how we can get a memory dump. Your proposal is one of several ways, assuming dotnet-dump is installed, or it can be installed as part of a build run.

We'll need to look at this in conjunction with https://github.com/dotnet/arcade/issues/5398.

**Comment by RussKie** [comment]
Closing as we can get crash dumps.

**Comment by weltkante** [comment]
@Russkie do we actually get dumps from hangs? The OS will only create them for crashes. I guess its no priority anymore since there are no known hangs remaining and we hopefully won't add new ones ;-)

**Comment by RussKie** [comment]
We can revisit it, if necessary. Keeping my 🤞 that we won't need this.

**Comment by RussKie** [comment]
FYI I'm working on this, I have a prototype that works locally, trying to sort out the CI leg
https://github.com/dotnet/winforms/commit/4310c3cbedc9f75ae5fea658c7fec478aec75b49
