### ISSUE TITLE
An error pops up when adding reference to Winforms .net core application

### ISSUE THREAD

**Issue by Marie-Shi** [dotnet/winforms#330]
**OS:** RS4 x64
**VS:** 16.0.0 Preview 3.0 [28516.179.d16.0stg]
**.NET SDK:** .NET Core 3.0.100-preview-010110

**More info:** This issue cannot repro on Console and Class library .net core applications.

**Steps to Reproduce:**

1.	Install .NET Core 3.0 SDK available from https://github.com/dotnet/core-sdk.
2.	Create a Winforms .Net Core application by command: dotnet new winforms –o “xxx”.
3.	Open the project and right click ‘Dependencies’ to choose ‘Add Reference’.
4.	Click ‘Browser’ button to choose *.dll(e.g.: System.Windows.Forms.dll) from C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-preview-27315-14, then click ‘OK’ button.

**Actual:**
An error pops up. Please see the below screenshot:
![image](https://user-images.githubusercontent.com/45864017/51307148-efea8580-1a79-11e9-8cfe-a71fc641e2ec.png)
Exception log:
[Add_Reference_CallStack.txt](https://github.com/dotnet/winforms/files/2767980/Add_Reference_CallStack.txt)

**Expected:**
System.Windows.Forms.dll can be added successfully.

**Comment by OliaG** [comment]
If this is reproducible only for Microsoft.WindowsDesktop.App, the expected result is to tell the user that this dll is already in the project. It should though allow to add other dependencies without an error.

**Comment by OliaG** [comment]
This issue was moved to dotnet/project-system#4487
