### ISSUE TITLE
Design Mode check

### ISSUE THREAD

**Issue by oggy22** [dotnet/winforms#3300]
* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
Hi Winforms team,

I’d like to raise an issue with Winforms about the way to check if the current code is run by designer or not. It’s rather confusing and I think there is room for improvement. The ways and suggestions I found from multiple sources (Stackoverflow and few of your team mates) are:
•	DesignMode property is flag, but it doesn’t seem to be reliable. Some suggest its value is correct only in ctr after InitializeComponents. Others suggest walking the parents up and checking the property.
•	LicenseManager.UsageMode == LicenseUsageMode.Designtime; This is also not reliable enough, at least from my experience, it Is sometimes false whereas it should be true.
•	System.Diagnostics.Process.GetCurrentProcess().ProcessName == "devenv" This seems clunky but seems to work for me (PR). However, if Visual Studio changes its process name it’ll stop working.
•	Various sources suggest the combinations of the previous 3.

I am not blaming anyone (I guess that’s clear?), I am just pointing to something which would be beneficial to improve on. Ideally:
-	We won’t have both DesignMode and LicenceManager.UsageMode, but only one of these two. Having both is confusing already.
-	It will be always reliable, not only from constructor.
-	It will be in in the next .NET platform (core net 5?)
-	If for any reason this won’t/can’t be done, please have the comments on these two properties (DesignMode and LicenceManager.UsageMode) explain all the caviats and details.

Thanks, Ogi!

**Expected behavior:**
Ideally I would have a Property on the System.ComponentModel.Component which would be completley reliable regardless of if it's used from constructor or not

**Minimal repro:**
1. Create a simple WinForms control and a WinForms app using it
2. Try all 3 forementioned ways of checking if in the design mode
3. Observe that none of them is 100% reliable

**Comment by weltkante** [comment]
> Observe that none of them is 100% reliable

They are reliable for what they are designed, but you want to use them for something they are not designed for.

If I remember right it works like this:
* LicenseManager is setup for the duration of the constructor call.
* DesignMode is setup after the control has been added to the design surface, but only for controls the user is actually currently designing (i.e. not their child controls if they weren't placed by the user)

None of those APIs will tell you whether you are running in a design-time environment, that is not their purpose.
* LicenseManager.UsageMode is supposed to tell you whether you need to check for the development or runtime license in the constructor.
* DesignMode is supposed to control design-time user interactions

In particular if a control has child-controls neither is guaranteed to be set, the API is designed for the direct user interaction. If you have a composite control the child controls are supposed to act as if they were hosted in a normal application.

I understand that devs may want to have more fine grained distinction so I suggest a new API to be added to detect whether you are currently running in a design time process.

**Comment by oggy22** [comment]
> They are reliable for what they are designed, but you want to use them for something they are not designed for

Going through the documentation of [LicenceManager](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.licensemanager.usagemode?view=netcore-3.1) and [DesignMode](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.component.designmode?view=netcore-3.1) I don't see any mentioning about the caveat about constructor. So at least the documentation should be improved explaining which one works when.

> None of those APIs will tell you whether you are running in a design-time environment, that is not their purpose.

Hm, I thought `DesignMode` purpose is exactly that, solely judging on the name.

>  I suggest a new API to be added to detect whether you are currently running in a design time process.

I definitely agree. I would really like to see a single reliable API for that.

**Comment by SenthilKumaranRajan** [comment]
Hi @JeremyKuhne ,

UserControl.DesignMode also return false in design mode. Please check this condition in design mode in net core project. 

Replication steps:
1) Close the designer 
2) Rebuild the application and open the designer and check the design mode condition.

DesignMode is false.

**Comment by RussKie** [comment]
If your user control is unsited, it would be false:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.Primitives/src/System/ComponentModel/Component.cs#L95-L101

**Comment by wagenheimer** [comment]
Is there some workaround for this?

I cannot edit any Form on a WinForms Application that does uses Syncfusion Components because of this bug!

**Comment by RussKie** [comment]
So is it a bug with Syncfusion components?

**Comment by SenthilKumaranRajan** [comment]
Hi @RussKie ,

No, the bug is due to the designer mode condition is not working for NetCore projects. 

Just suggest us the way to find the designmode condition as like in .NetFramework.

**Comment by RussKie** [comment]
> No, the bug is due to the designer mode condition is not working for NetCore projects.
> 
> Just suggest us the way to find the designmode condition as like in .NetFramework.

Can you please provide more information?

The behaviour hasn't changed since .NET 1.1: https://docs.microsoft.com/dotnet/api/system.componentmodel.component.designmode?view=netframework-1.1#remarks

**Comment by SenthilKumaranRajan** [comment]
> > No, the bug is due to the designer mode condition is not working for NetCore projects.
> > Just suggest us the way to find the designmode condition as like in .NetFramework.
> 
> Can you please provide more information?
> 
> The behaviour hasn't changed since .NET 1.1: https://docs.microsoft.com/dotnet/api/system.componentmodel.component.designmode?view=netframework-1.1#remarks

We have a problem with finding the design time in NetCore project.  I have prepared the simple example for this.

`  public class MyControl : Control
    {
        public MyControl()
        {
            if (LicenseManager.UsageMode == LicenseUsageMode.Designtime)
            {
                MessageBox.Show("Design");
            }
            else
            {
                MessageBox.Show("Runtime");
            }

        }
    }
`
Follow the below steps:

•	Add the “MyControl” in the Form1.Designer and close the designer.
•	Rebuild the project and open the designer
Observed result:
                In Framework project it shows the MessageBox as “Design”
                But in .NetCore project it shows the MessageBox as “Runtime” even in designer.

Also I have tried to check the design mode by using below code example. The below code also shows the same error like above scenario. 

`if ((bool)DesignerProperties.IsInDesignModeProperty.GetMetadata(typeof(System.Windows.DependencyObject)).DefaultValue)
            {
                MessageBox.Show("Design");
            }
            else
            {
                MessageBox.Show("Runtime");

            }
`
[WFDeignMode_NetCore.zip](https://github.com/dotnet/winforms/files/5281167/WFDeignMode_NetCore.zip)

**Comment by SenthilKumaranRajan** [comment]
HI Team,

Any updates.?

**Comment by RussKie** [comment]
> We have a problem with finding the design time in NetCore project. I have prepared the simple example for this.
> 
> ```cs
>   public class MyControl : Control
>   {
>         public MyControl()
>         {
>             if (LicenseManager.UsageMode == LicenseUsageMode.Designtime)
>             {
>                 MessageBox.Show("Design");
>             }
>             else
>             {
>                 MessageBox.Show("Runtime");
>             }
> 
>         }
>     }
> ```
> 
> Follow the below steps:
> 
> * Add the “MyControl” in the Form1.Designer and close the designer.
> * Rebuild the project and open the designer
> 
> Observed result:
> * In Framework project it shows the MessageBox as “Design”
> * But in .NetCore project it shows the MessageBox as “Runtime” even in designer.

@ericstj @AaronRobinsonMSFT it looks like `LicenseManager` has undergone some makeover, specifically the current implementation of [`LicenseInteropHelper`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/LicenseManager.LicenseInteropHelper.cs) looks different from [.NET Framework version](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/LicenseManager.cs,378).

Would you know why the .NET version could return an incorrect state?

**Comment by weltkante** [comment]
I think the interop licensing is for AxHost, for .NET controls this should not require any interop. Might be more of a problem of the new designer not setting up a design-time license context (considering that licx licensing story is no longer supported). The designer may have to setup a dummy license context just to support design mode detection - or just provide a new API instead.

**Comment by SenthilKumaranRajan** [comment]
> > We have a problem with finding the design time in NetCore project. I have prepared the simple example for this.
> > ```cs
> >   public class MyControl : Control
> >   {
> >         public MyControl()
> >         {
> >             if (LicenseManager.UsageMode == LicenseUsageMode.Designtime)
> >             {
> >                 MessageBox.Show("Design");
> >             }
> >             else
> >             {
> >                 MessageBox.Show("Runtime");
> >             }
> > 
> >         }
> >     }
> > ```
> > 
> > 
> > Follow the below steps:
> > 
> > * Add the “MyControl” in the Form1.Designer and close the designer.
> > * Rebuild the project and open the designer
> > 
> > Observed result:
> > 
> > * In Framework project it shows the MessageBox as “Design”
> > * But in .NetCore project it shows the MessageBox as “Runtime” even in designer.
> 
> @ericstj @AaronRobinsonMSFT it looks like `LicenseManager` has undergone some makeover, specifically the current implementation of [`LicenseInteropHelper`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/LicenseManager.LicenseInteropHelper.cs) looks different from [.NET Framework version](https://referencesource.microsoft.com/#System/compmod/system/componentmodel/LicenseManager.cs,378).
> 
> Would you know why the .NET version could return an incorrect state?

Yes, I like to know whey the .NET version could return an incorrect state. Also suggest me is there any other way to find the Design mode in NET core projects.

**Comment by weltkante** [comment]
> Also suggest me is there any other way to find the Design mode in NET core projects.

See my [explanation](https://github.com/dotnet/winforms/issues/3300#issuecomment-630434292) above. You are supposed to wait for your control to placed in the designer and then can check its `DesignMode` mode property (after the `Site` has been assigned to the control). If you are on a UserControl, and the containing UserControl is placed in the designer, you are not supposed to show design-time UI (the user is placing his UserControl and not your control).

The LicenseManager.UsageMode only existed for checking design-time licensing, and the licensing story has been completely reworked. I don't know how you currently are supposed to write licensed controls.

**Comment by The-MAZZTer** [comment]
The Site workaround works for design-only code. (Keep in mind it gets set twice... once when you close the design surface, too!)

However this doesn't help for running runtime-only code since Site is never assigned. A use case is if you want to do further initialization in the constructor but don't want these changes serialized in the designer (or the code throws an exception in design mode for any number of reasons). A workaround could be to explicitly call a method on your form or control at runtime (which won't happen in the designer) to perform the additional initialization.

I also came up with this code snippet which works. This is specifically for the case where you want to run code in runtime, and not when a control is constructed by the designer, regardless of whether or not it can be edited (which is what DesignMode is for, TIL).

> 		private bool isDesignTime;
> 		public override ISite Site {
> 			get => base.Site;
> 			set {
> 				base.Site = value;
> 
> 				this.isDesignTime = true;
> 			}
> 		}
> 
> 		private bool init = false;
> 		protected override void OnLoad(EventArgs e) {
> 			base.OnLoad(e);
> 
> 			if (this.isDesignTime || this.init) {
> 				return;
> 			}
> 			this.init = true;
> 
> 			// Do dangerous stuff here
> 		}

OnLoad seems to fire after Site is assigned (or not assigned) so this works.

**Comment by weltkante** [comment]
Your approach looks equivalent to checking the existing `DesignMode` property, including the fact that it will not detect if the parent control is placed in the designer (OnLoad will be called in this case without a site being set, since the child control is not being designed)

**Comment by TempeBrennan** [comment]
@weltkante I tried override "Site" property.
When double click "form.cs", first will execute control constructor then will apply value to "Site"
Then when user close "form.cs" file, "Site" will be set again.

So if I want to get design time or run time in constructor, this property can not help me indeed. But I can not find other good way.

> I suggest a new API to be added to detect whether you are currently running in a design time process.
Before this API added, do we have other recommended way to get same effect? Thanks

**Comment by weltkante** [comment]
@TempeBrennan my recommendations were based on the Desktop Framework designer, but by now it became apparent that the WinForms team is not interested in maintaining compatibility with Desktop Framework designer APIs. The new designer SDK is not released yet (only accessible under NDA) so I cannot give any recommendations how to write design time code. If you develop controls you may want to reach out to Microsoft to get in to the NDA in order to develop .NET Core controls with design time support.

**Comment by RussKie** [comment]
Here's a distilled sample: https://github.com/RussKie/IsDesignMode

net472:
![image](https://user-images.githubusercontent.com/4403806/128665636-5f99dc03-5fed-4f4c-930f-cf0f15e60e4b.png)

net6.0:
![image](https://user-images.githubusercontent.com/4403806/128665585-6c2ca52c-6200-4ca2-8050-ff4187fdb2e5.png)

**Comment by RussKie** [comment]
Resolved by #5375

**Comment by TobiasKnauss** [comment]
> @TempeBrennan my recommendations were based on the Desktop Framework designer, but by now it became apparent that the WinForms team is not interested in maintaining compatibility with Desktop Framework designer APIs. The new designer SDK is not released yet (only accessible under NDA) so I cannot give any recommendations how to write design time code. If you develop controls you may want to reach out to Microsoft to get in to the NDA in order to develop .NET Core controls with design time support.

Is the "new designer SDK" part of VS 2022? If so, then it would have been released?

**Comment by TobiasKnauss** [comment]
I can also provide a full solution with nested and inherited controls, that works well in .Net Framework 4.8, but fails to work in .Net 5:
[WinformsDesignerActive.zip](https://github.com/dotnet/winforms/files/7926819/WinformsDesignerActive.zip)

**Comment by RussKie** [comment]
> Is the "new designer SDK" part of VS 2022? If so, then it would have been released?

[Winforms Designer Extensibility SDK](https://www.nuget.org/packages/Microsoft.WinForms.Designer.SDK) has been published. Please note it is a prerelease version. We expect a blog post about this finalized around start of February. Around then, we will also publish the first final 1.0 release of this SDK.

**Comment by KlausLoeffelmann** [comment]
> We expect a blog post about this finalized around start of February.

```start >= 2/9```. Sorry, not earlier.
