### ISSUE TITLE
Add Support for Title Image to ListViewGroup

### ISSUE THREAD

**Issue by lonitra** [dotnet/winforms#3301]
**Is your feature request related to a problem? Please describe.**

Our ListViewGroup does not have support for Title Images (or icons next to the group header) while LVGROUP does (https://docs.microsoft.com/en-us/windows/win32/api/commctrl/ns-commctrl-lvgroup)

**Describe the solution you'd like and alternatives you've considered**

Add support for adding images to ListViewGroup headers.

I am basing the API off of how it works to add images to `ListViewItem`:
```cs
public class ListViewGroup 
{
    public int TitleImageIndex { get; set; }
    public string TitleImageKey { get; set; }
}

public class ListView
{
    public ImageList GroupImageList { get; set; }
}
```

Example:
```cs
ImageList imageList = new ImageList();
imageList.Images.Add(<SOME_IMAGE>);
ListView listView = new ListView
{
    GroupImageList = imageList;
};

ListViewGroup lvgroup = new ListViewGroup();
listView.Groups.Add(lvgroup);
lvgroup.TitleImageIndex = 0;
// or
lvgroup.TitleImageKey = "<SOME_IMAGE_NAME>";
```

**Will this feature affect UI controls?**
Yes it will end up looking like this: 
![image](https://user-images.githubusercontent.com/30007367/82271130-ccfd0980-992b-11ea-9e87-91f3c40f0d27.png)

- Will VS Designer need to support the feature?
Yes. I am expecting it to look similar to 
![image](https://user-images.githubusercontent.com/30007367/82273010-23207b80-9931-11ea-8b38-784c93067e0b.png)

- What impact will it have on accessibility?
Based off of looking at some ListViewItems that have an icon next to them, doesn't seem like this will affect accessibility, but I could be wrong here.

- Will this feature need to be localized or be localizable?
It looks like `ListViewItem.ImageIndex` is localizable so I'm assuming yes.

**Comment by hughbe** [comment]
As per the API 
```cs
    // Returns the ListViewGroup's currently set title image index
    public int TitleImage { get; set; }
```

I would suggest we follow the pattern across winforms of having `int TitleImageIndex` and `string TitleImageKey`

**Comment by RussKie** [comment]
> I would suggest we follow the pattern across winforms of having `int TitleImageIndex` and `string TitleImageKey`

I agree, this way we have consistent API.

**Comment by merriemcgaw** [comment]
This works for me to continue to get the ListView fully supported.

**Comment by terrajobst** [comment]
Discussed over email. Looks good as proposed!
