### ISSUE TITLE
Should we move System.Windows.Forms.Padding back to the System.Windows.Forms assembly

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#3306]
While investigating a bug in the WinForms Core Designer, namely in the context of serialization of Resource files, I noticed that from 3.1 to 5.0 the `Padding` struct has moved from the `System.Windows.Forms` assembly to `System.Windows.Forms.Primitives`. This is the reason, at least from the perspective of deserializing resource files in the Core Designer, we can not retarget a WinForms 5.0 Core App back to 3.1. The type resolution service in the ResXDataNode processor, which is already version tolerant, cannot handle the new type name (at least not without introducing some black magic).

So, while this resources issues might be principally resolvable, my concern is that the `Padding` struct of all WinForms structs gets serialized and deserialized in typical Customer in mixed version scenarios (where e.g. 100 clients write some custom serialized files back to a server still running 3.1, and others already 5.0), which could cause real problems.

So, for that reason, I would propose to move the `Padding` struct back to the `System.Windows.Forms` namespace, or at least discuss the seriousness of my concern.

**Comment by merriemcgaw** [comment]
I'm on board with this.

**Comment by RussKie** [comment]
Closing in favour of dotnet/winforms-designer#1837 and https://github.com/dotnet/winforms/issues/4528
