### ISSUE TITLE
An error pops up when adding new items(Form, Winforms UserControl…) to Winforms .net core application

### ISSUE THREAD

**Issue by Marie-Shi** [dotnet/winforms#331]
**OS:** RS4 x64
**VS:** 16.0.0 Preview 3.0 [28516.179.d16.0stg]
**.NET SDK:** .NET Core 3.0.100-preview-010110

**More info:** This issue cannot repro on Winforms .net Framework application.

**Steps to Reproduce:**
1.	Install .NET Core 3.0 SDK available from https://github.com/dotnet/core-sdk.
2.	Create a Winforms .Net Core application by command: dotnet new winforms –o “xxx”.
3.	Open the project and right click project to choose ‘Add’, then click ‘New Item’ to choose Windows Form/Winforms User Control..

**Actual:**
An error pops up. Please see the below screenshot:
![image](https://user-images.githubusercontent.com/45864017/51308762-d2b7b600-1a7d-11e9-94b6-2e3a9e375af9.png)
Exception log:
[Add_Form_CallStack.txt](https://github.com/dotnet/winforms/files/2767970/Add_Form_CallStack.txt)

**Expected:**
A new form/User Control can be added successfully in this project.

**Comment by OliaG** [comment]
This issue was moved to dotnet/project-system#4486
