### ISSUE TITLE
Controls declared without WithEvents clause in Winforms Designer

### ISSUE THREAD

**Issue by Padanian** [dotnet/winforms#3312]
* .NET Core Version: 
 5.0.100-preview.4.20258.7

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Declaration of controls on a form by dragging control onto it does not include "WithEvents" clause.
As such, event handlers methods are created without "Handles" clause.

**Expected behavior:**
Dragging and dropping controls on form shall correctly declare and instatiate controls WithEvents

**Minimal repro:**
Create form, drag TextBox or NumericUpDown from toolbox onto form, double click on control.
Method is created without Handles clause.
Adding Handles clause manually ends up in complaining the control is declared without WithEvents clause.

**Comment by merriemcgaw** [comment]
This is VB support that currently have on the backlog to implement within the next couple of Previews. @KlausLoeffelmann will be working on this coming soon. He will keep you posted on our progress.

**Comment by KlausLoeffelmann** [comment]
Yes, that is correct!

**Comment by KlausLoeffelmann** [comment]
This is a Designer specific problem, and will be fixed in 16.8 Preview 4. Closing this.
