### ISSUE TITLE
NumericUpDown: unable to evaluate its properties at runtime

### ISSUE THREAD

**Issue by Padanian** [dotnet/winforms#3313]
* .NET Core Version: 
 5.0.100-preview.4.20258.7

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Runtime evaluation of NumericUpDown properties fails with <Internal evaluation error of expression> for properties .Value, .Min and .Max 
NOTE = actual error message may be different because of translation from my locale
NOTE 2 = Multiple different errors are shown in the inspect object properties pane
NOTE 3 = Textbox property is present in the inspect object properties pane, but NumericUpDowns don't inherit any TextBox property

**Expected behavior:**
NumericUpDown.Value , .Min and .Max shall be evaluatable at runtime

**Minimal repro:**
Drag a NumericUpDown onto a form, create a ValueChanged event handler and inspect properties of control

**Comment by Tanya-Solyanik** [comment]
Issue related to the textbox property had been fixes in the .NET Core designer a couple days back, it is not yet available in the Preview channel. If everything goes as expected, it would be in 16.7.0 Preview2.

**Comment by Tanya-Solyanik** [comment]
@Padanian, could you please share screenshot of PropertyBrowser showing error that you see. We had fixed several bugs in this area, I would like to see if they were the same as your issue. Trying out your steps, I don't see are errors on the Preview channel build of the VS.

**Comment by Padanian** [comment]
![image](https://user-images.githubusercontent.com/7769348/82636968-16877600-9c04-11ea-9dd0-62296c9339c5.png)

**Comment by Padanian** [comment]
As you see above, there's even a VScroll property which should be there. It's kinda all mixed up.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann can you take a quick look?

**Comment by KlausLoeffelmann** [comment]
Sure. And I cannot really repro this bug. Taking a look at `sender` in the above sample shows up like this:

![image](https://user-images.githubusercontent.com/9663150/84578048-5c081080-ad76-11ea-95bc-7b0e01e1ed5e.png)

I am going to close it for now, and should it still persists on your machine after the next update (please also try to update the Net5 SDK!), then please reopen it! Thanks!
