### ISSUE TITLE
Winforms Designer in Version 16.7.0 Preview 1.0 Not Working with Visual Basic

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#3318]
* .NET Core Version: 
3.1

* Have you experienced this same bug with .NET Framework?: 
No also not with Visual Studio 16.6.0

**Problem description:**
Attempting to open any VB form in designer by clicking on any Visual Basic Windows Form you will see the 2 error dialogs at the bottom 
 A sample project you can use is https://github.com/kpreisser/TaskDialogDemo.git  and it has a C# and VB identical project the C# one works and the VB one does not.

Any forms operation after this will return just the second error.

**Expected behavior:**

![image](https://user-images.githubusercontent.com/12789369/82511140-5b56c400-9ac1-11ea-9519-49378f117fb6.png)

**Minimal repro:**

![image](https://user-images.githubusercontent.com/12789369/82510834-7543d700-9ac0-11ea-8f3e-2f78445fc88b.png)
![image](https://user-images.githubusercontent.com/12789369/82510869-8987d400-9ac0-11ea-84f5-932471f50d72.png)

**Comment by RussKie** [comment]
Can you please submit the feedback via the VS Feedback tool, it collects logs, stack traces and other important information that help in debugging issues, such as the NRE you're seeing.

**Comment by paul1956** [comment]
I did that also

**Comment by Tanya-Solyanik** [comment]
Hi @paul1956, I had tried out the task dialog demo in VB, but did not see this error dialog. The designer loaded fine.  Did you start seeing this error once you upgraded the VS? Do you have 5.0 version of the SDK installed? Can you load the designer for the CS task dialog demo? Can you build both successfully?

**Comment by paul1956** [comment]
@Tanya-Solyanik it only happens in 16.7 Preview 1, yes I have 5.0 installed but not using on this project branch. I have never seen it fail under C#, but it seems related to system load. When I restart and there is lots of activity (stuff starting up, Virus scanner busy..) and CPU is ~100 busy it always fails to start. If I restart VS when CPU load is low I can't reproduce it on VB or C# and once it works once, it works until I restart VS under heavy load.
