### ISSUE TITLE
TableLayoutPanel memory leak

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#3319]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/681591/tablelayoutpanel-memory-leak.html)._

---
TableLayoutPanel has a memory leak when dynamically filled with controls, controls cleared (with dispose), and reloaded with the same data source. This will eventually cause a parameter error somewhere in system code. The memory leak is equivalent to what has been loaded. So if I load 1GB of controls; dispose and clear the panel.controls, and load 1GB of controls from the same data source, I will end up with a memory use of 2GB. If I dispose of the panel before recreating it and loading it, the memory leak disappears.

---
#### Visual Studio Feedback System on 8/8/2019, 06:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### mbarnet on 8/9/2019, 06:49 AM: 

(private comment, text removed)
#### Visual Studio Feedback System on 10/8/2019, 05:23 PM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by RussKie** [comment]
Waiting for a repro project that has been requested on the VS Feedback site.
