### ISSUE TITLE
Support generic base class in designer

### ISSUE THREAD

**Issue by nawfalhasan** [dotnet/winforms#3328]
**Is your feature request related to a problem? Please describe.**
Problem: Unable to open up a form that inherits from a generic form class without building project.

**Description:**
When a form inherits from a common base class like `FormBase<T>`, the designer of the more derived type cant be opened without building the project in VS.

**Example:**

    public class FormBase<T> : Form
    {
        protected FormBase()
        {
        }
    }

    public class FormDerived : FormBase<DerivedViewModel>
    {
        public FormDerived()
        {
        }
    }
 
Now `FormDerived` in the designer wouldn't open up easily. Sometimes building VS is required to open up the designer, sometimes restarting VS and building is required. 

**Error when I try today:**
From the designer: 
> The designer could not be shown for this file because none of the classes within it can be designed. The designer inspected the following classes in the file: FormDerived --- The base class 'Xxx.Common.Presentation.Mvvm.FormBase`1' could not be loaded. Ensure the assembly has been referenced and that all projects have been built. 

Call stack:

> at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.EnsureDocument(IDesignerSerializationManager manager)
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
at System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost host) 

**Solution I would like**: 
Opening up the form designer should work any time from VS. Just like it opens up if base class is a regular class.

**Related info:**
1. Here MS staff confirms this feature is on the roadmap. I am here trying to create a github issue for tracking. https://devblogs.microsoft.com/dotnet/windows-forms-designer-for-net-core-released/#comment-5898

2. Similar thread before https://github.com/dotnet/roslyn/issues/4987

**Comment by nawfalhasan** [comment]
This is a feature request, not an api-suggestion. Seems I cant add appropriate label.

**Comment by nawfalhasan** [comment]
The same applies for user controls as well

**Comment by weltkante** [comment]
what type `T` would you expect the designer to display? the designer needs a live instance to run against, so it has to chose a generic type parameter.

**Comment by nawfalhasan** [comment]
The designer for `FormDerived : FormBase<DerivedViewModel>` should resolve T as DerivedViewModel. If not, at the very least it should open up the designer of `Form` (i.e. first proper base it can design)

Designer need not verify generic constraints, but if it does that is fine as well (it would be more correct). I am not sure what is the complexity here. The base here is bound and closed generic type.

**Comment by weltkante** [comment]
> Designer need not verify generic constraints

The designer doesn't have a choice, the runtime does that when you instantiate an instance. You cannot create an instance of an invalid type or an open generic type (without specifying `T`). The designer doesn't contain a compiler, it just creates an instance off your last build and runs it.

> The designer for `FormDerived : FormBase<DerivedViewModel>` should resolve T as DerivedViewModel. 

Right, that works when your derived class is not generic anymore, I was also thinking of the case `FormDerived<T> : FormBase<T>` - maybe that doesn't need to be supported?

**Comment by nawfalhasan** [comment]
> I was also thinking of the case FormDerived<T> : FormBase<T> - maybe that doesn't need to be supported?

As a first step not. But it can be implemented too if MS let us specify a TypeDescriptionProvider (which controls which instance should  designer design).

**Comment by TimBakkerVBH** [comment]
This issue is still in the .NET Core designer. With .Net Framework it's fixed. Is there an ETA on this?

**Comment by RussKie** [comment]
I am afraid, no. The support for the generic/abstract forms/user controls is on the team's backlog, however, it's not very high on the priority list.

**Comment by TimBakkerVBH** [comment]
can you maybe provide a workaround for this? I know this was a long standing issue with .net framework as well.

**Comment by OJacot-Descombes** [comment]
Now that we have [Generic Attributes](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/generic-attributes) in C# 11, we could specify types used in the designer with an attribute
``` c#
[DesignerFormType<MyViewModel, <MyDataModel>]
public class MyForm<TViewModel, TDataModel> : Form
```

**Comment by IngoBleile** [comment]
> what type `T` would you expect the designer to display? the designer needs a live instance to run against, so it has to chose a generic type parameter. What would be the choice if the generic type has constraints? Would you expect it to be supported to have interface constraints and how would you pick the `T` for them?
> 
> `public class FormBase<T> : Form where T: IDisposable, ISomeOtherInterface`

It worked in .NET Framework, so how did you do it there? Even the generic base form could be opened as you might have controls on it.

**Comment by weltkante** [comment]
> It worked in .NET Framework, so how did you do it there? Even the generic base form could be opened as you might have controls on it.

Nah, some scenarios worked, others worked sometimes, some never. The situation changed in the past too, when the compiler backend was changed to Roslyn, as mentioned and linked in the original post. It mostly depends on whether the designer is able to instantiate an instance. As far as I understand the other comments (including in the linked threads) generics were not a scenario the designer was coded for and the cases that worked only worked by chance.

Overall I'm the wrong person to argue with anyways, my response you quoted was just trying to explain why these things are problematic. It doesn't really matter what the old designer did, as the new designer is completely different (a rewrite not a port) and a lot of things that used to work no longer work or work differently. If you want something to work that currently doesn't you have to ask the team to support it and if enough people do maybe they will.

**Comment by n-ate** [comment]
In my case, the generic type argument would have no bearing on the designer rendering. I use it for other concerns. Why not construct the UserControl<T> with default(T)?

Another option would be to give us a place to enrich the design processes to do explicit construction. Perhaps an interface (IWinformsDesignerInfo) that we can implement that your library can find and construct with reflection. Give us a method to implement like one of the following: 
  UserControl GetUserControlInstance(Type type) 
  TControl GetUserControlInstance<TControl>()

This way we can provide the constructed object of the needed type.

**Comment by weltkante** [comment]
> Why not construct the UserControl with default(T)?

Because `MyUserControl<default<T>>` is not a valid type signature - you need to put in a _Type_ for `T` not a _value_. But yes, it'd be "relatively easy" to provide a workaround for some scenarios in the new designer implementation if they desired to support that scenario.

**Comment by n-ate** [comment]
In my case, I am inheriting from a base User controller that exposes helpful methods and a "Model" property. The inheriting user controllers specify the type argument when inheriting which results in Model being the correct property and all of the inherited methods taking the correct types.

**Comment by merriemcgaw** [comment]
The WinForms designer is based on the concept of instantiating an instance of the form, and implementing this is not on our current radar.

**Comment by phoge110** [comment]
Hello!

I am developing a Winforms .NET 8 app using VS 2022(17.11.5). 
I am getting the same error even when building a Form. 

I am creating a Generic form inheriting from the main System.Windows.Forms.Form class
![Image](https://github.com/user-attachments/assets/c5bcf030-5a1f-4eaa-9438-93bd43e3402e)

I am getting this error when trying to view the designer page
![Image](https://github.com/user-attachments/assets/ce86cab5-b06f-4567-a76c-9466fe2cfb20)

I have tried Cleaning/Building the solution and deleting temp folders and cache. 
I have this code running on another solution running .NET Framework and the designer works fine in VS2022.
It seems to have an issue with .NET 8 and VS2022.

Please let me know if there is a work around for this, need more info, and if I should submit another issue.

Thanks!

**Comment by WolfgangHG** [comment]
@phoge110 This still possible, but with a lot of workarounds. And you might get stuck somewhere...

Attached is a small sample with a generics form, which reports the same error when opening it in designer.
[GenericsDesigner.zip](https://github.com/user-attachments/files/17879311/GenericsDesigner.zip)

To open the "FormGeneric" in my sample, three steps are necessary:

1. In the main form file, replace this:
    ```c#
    public partial class FormGeneric<TClass> : Form
      where TClass : BaseClass
    ```
   with this:
    ```c#
   public partial class FormGeneric : Form
    ```
2. In the ".Designer.cs" file, replace
    ```c#
    partial class FormGeneric<TClass>
    ```
    with this:
    ```c#
    partial class FormGeneric
    ```
3. In "InitializeComponent", there might be this line:
    ```c#
    System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormGeneric<TClass>));
    ```
    Replace it with
    ```c#
    System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormGeneric));
    ```

Of course, my sample project will not compile after this change. Ignore the compilation error and open the form in designer - it should work. 

I added a PictureBox with an image from a resx.file to demonstrate an additional step: whenever a designer modification modifies "FormGeneric.resx", you have to copy the content to an additional file "FormGeneric`1.resx", where the resource it is loaded at runtime.
And this file will break the designer again. Will create a followup comment...


All this is just the first step. You will run into further problems if you want to create subclasses of your form.

**Comment by WolfgangHG** [comment]
After having added a  "FormGeneric`1.resx" to my project, the designer will fail to load:

```
Value cannot be null. (Parameter 'baseName') 

at StreamJsonRpc.JsonRpc.d__154`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.Host.ServerHost.d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<>c__DisplayClass25_1.<<-ctor>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.d__27.MoveNext() 
```

This is caused by the grave accent in the filename - the .NET6 winforms designer dislikes it.

To work around this:

1. remove **all** files with a grave accent from the current project or rename them.
2. Restart Visual Studio. The designer will continue to report the error otherwise.

We reported this issue to Microsoft when we were first hit by it, but it seems the support people did not even understand the issue...

**Comment by WolfgangHG** [comment]
I created a github repository which describes some workarounds for using the WinForms designer with generics: https://github.com/WolfgangHG/WinFormsDesignerGenerics
I will update it with further samples - I think there are still more problems to solve ;-)

Create issues in this repo in case of questions or errors in my documentation.
