### ISSUE TITLE
Initializing and immediately adding an image as a resource fails until you close and reopen.

### ISSUE THREAD

**Issue by DualBrain** [dotnet/winforms#3332]
* .NET Core Version: 

3.1 in VS 16.6 (release version)

* Have you experienced this same bug with .NET Framework?: 

No

**Problem description:**

When initialize the resource file, switch to the image tab (without first closing), add an item (without first closing) and it is added to the resources folder but disappears from the actual resource list.  Have to reopen and re-add the item - after this takes place things are working as expected.

NOTE: I don't know if this is a VB only behavior; I haven't tried this in C#.

**Expected behavior:**

Initialize the resource, switch to the image tab, add an item and it actually work.

**Minimal repro:**

1. Create a Console application (VB).  Change the project so that it is as follows:
```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
```

2. Modify Program.vb...
```vb
Imports System.Windows.Forms

Module Program
  <STAThread>
  Sub Main()
    Application.SetHighDpiMode(HighDpiMode.SystemAware)
    Application.EnableVisualStyles()
    Application.SetCompatibleTextRenderingDefault(False)
    Application.Run(New Form1())
  End Sub
End Module
```

3. Unload project, reload project.

4. Open project properties, click on Resources.  Click on the "link" to create resources... switch to images, drag an image to the list and close.

The image is placed in the Resources folder; however, it disappears from the actual resources list.  I've tried this several different ways and it does seem to be only associated with the initial creation of the resources and immediately adding an image (resource).  If you create the resources, close (save) and then reopen before adding the initial image... things appear to work.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann - have you seen this issue internally yet?
@DualBrain  - we're still working on VB.NET Support (as well as resources support) so stay tuned.

**Comment by DualBrain** [comment]
Completely understand...

I'll add that this *might* be an artifact of converting from a Console application to a WinForms application - which, right now, is the only way that I can create a WinForms project for VB (understanding that I'm playing on the razors edge here).  I suspect that if the templates existed and I were to create a WinForms project directly, the resources would probably be "init'd" properly by the time I were to open the dialog "for the first time".  Admittedly this probably isn't something that will happen very often (even after WinForms is released); with that said, I can see it definitely happening *rarely* as there are certainly circumstances where someone might start with a Console application and evolve that into a WinForms project over time...

**Comment by KlausLoeffelmann** [comment]
I'll check this. This shouldn't be language specific, so I suspect this might be a general designer issue in the area of resources.

Cory, one of the reasons the templates don't exist yet for VB is, that we did not have the Application Framework support earlier (`WindowsFormsApplicationBase` for example). And without that, templates are impacted.

**Comment by DualBrain** [comment]
Thanks.

Regarding why the templates don't currently exist; I figured it was a combination of this and the fact that things are clearly changing with the project format along the way to .NET 5 - so completely understandable.

**Comment by KlausLoeffelmann** [comment]
@Olina-Zhang : Could you please check if this is a general resources problem and not VB related? Thanks!

**Comment by Olina-Zhang** [comment]
@KlausLoeffelmann Yes, it is not VB related. But it cannot repro in the latest VS build, there is the verification screenshot for the latest VS and 16.6 as above repro steps:
![image](https://user-images.githubusercontent.com/26474449/92677916-73e03800-f357-11ea-9a18-168759a4b476.png)

**Comment by RussKie** [comment]
Closing as fixed in VS.
