### ISSUE TITLE
Inherited forms don't work in the designer for .NET Core

### ISSUE THREAD

**Issue by ekolis** [dotnet/winforms#3338]
* .NET Core Version: 
3.1

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

1. Create a .NET Core WinForms app.
2. Create a form.
3. Create a second form.
4. Edit the second form's code behind to make it inherit from the first form.
5. Open the visual designer for the second form.

The designer will then crash with this error: 

> The designer could not be shown for this file because none of the classes within  it can be designed. The designer inspected the following classes in the file:  The designer could not be shown for this file because none of the classes within  it can be designed. The designer inspected the following classes in the file:  \r\n Form2 --- The base class 'BrokenFormsInheritance.Form1' could not be  loaded. Ensure the assembly has been referenced and that all projects have been  built. | The designer could not be shown for this file because none of the classes within  it can be designed. The designer inspected the following classes in the file:  The designer could not be shown for this file because none of the classes within  it can be designed. The designer inspected the following classes in the file:  \r\n Form2 --- The base class 'BrokenFormsInheritance.Form1' could not be  loaded. Ensure the assembly has been referenced and that all projects have been  built.
-- | --
The designer could not be shown for this file because none of the classes within  it can be designed. The designer inspected the following classes in the file:  The designer could not be shown for this file because none of the classes within  it can be designed. The designer inspected the following classes in the file:  \r\n Form2 --- The base class 'BrokenFormsInheritance.Form1' could not be  loaded. Ensure the assembly has been referenced and that all projects have been  built.

6. Build the project as the error indicates.

The error will remain regardless of if I build the project.

**Expected behavior:**

The designer opens.

**Minimal repro:**

see attached

[BrokenFormsInheritance.zip](https://github.com/dotnet/winforms/files/4674071/BrokenFormsInheritance.zip)

**Comment by kirsan31** [comment]
It's not done yet, see: https://devblogs.microsoft.com/dotnet/windows-forms-designer-for-net-core-released.

**Comment by merriemcgaw** [comment]
Yep, we've got an [internal item ](https://github.com/dotnet/winforms-designer/issues/1135)on our backlog for this issue.'

**Comment by ekolis** [comment]
Great, thanks!

**Comment by kirsan31** [comment]
Any eta? Will this and all .net controls be ready to 5.0?

**Comment by merriemcgaw** [comment]
This is a designer specific feature, and we've got it on the agenda. We likely won't have it for 16.8 but hopefully in the next VS release. Which control(s) do we not have runtime support for? We've still got a couple of controls to get designer support for as we continue to implement features, and there are a handful of designers that are very specific to our controls and we've gotten most of these into our designer or will have shortly.

**Comment by kirsan31** [comment]
> Which control(s) do we not have runtime support for?

`DataGridView` :yum:

**Comment by merriemcgaw** [comment]
@kirsan31 we've ported the DataGridView control to Core a long time ago. @RussKie is working on #3875 as we speak. I'm hopeful we can get it approved for 5.0. Are you facing other issues?

cc: @dreddy-work

**Comment by kirsan31** [comment]
I am sorry for misleading, by _all .net controls be ready to 5.0_ I mean new designer will be handle them.

**Comment by dreddy-work** [comment]
@kirsan31 , we did port large portion of the designers for those controls as well. There are very few designers that were low in our priority list based on their usage and are on our list to port as we progress. If you see a specific control that its designer is not working or not available, please let us know.

**Comment by kirsan31** [comment]
@dreddy-work as I mentioned above - `DataGridView`. It's not usable in designer because of not working styles editors (all of them).
Quick look at `ListView` bring that item editor not shoeing color selection dialog. Changing color by double click - immediately apply it to the code regardless if I will press cancel on the edit dialog...

P.s. I think this is a bit off topic here - do we need create new issue or something?

**Comment by RussKie** [comment]
> do we need create new issue or something?

Please raise these issues via the VS Feedback tool, as it captures necessary telemetry such as versions of components, etc.

**Comment by kirsan31** [comment]
@RussKie Done: [Issue1](https://developercommunity.visualstudio.com/content/problem/1186689/winforms-designer-not-show-properties-when-target.html), [Issue2](https://developercommunity.visualstudio.com/content/problem/1186903/new-net-winforms-designer-datagridview-styles-edit.html), [Issue3](https://developercommunity.visualstudio.com/content/problem/1186904/new-net-winforms-designer-listview-item-editor-bug.html).

**Comment by kirsan31** [comment]
@Shyam-Gupta 

> Regarding inherited Forms: They should work after the application is built. If not then let me know and we can discuss it on the other issue.

I've  modified [original repro](https://github.com/dotnet/winforms/issues/4026#issue-711529348) a bit: [DesignerInheritence.zip](https://github.com/dotnet/winforms/files/5325573/DesignerInheritence.zip)
V.S. 16.8 P. 3.2:

![vsi](https://user-images.githubusercontent.com/17767561/95046571-19838e80-06ed-11eb-8e55-6f55b8613d7e.gif)


> System.InvalidOperationException: 'Site' must not be null in order to access a required service.
>    at WinFormsSurface.Designers.ComponentDesigner.GetRequiredService[T]()
>    at WinFormsSurface.Designers.ControlDesigner.SetUnhandledException(Control owner, Exception exception)
>    at WinFormsSurface.Designers.ControlDesigner.DesignerWindowTarget.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by kirsan31** [comment]
V.S. 16.8 P. **4** - [same behavior](https://github.com/dotnet/winforms/issues/3338#issuecomment-703426718).

**Comment by dreddy-work** [comment]
Inheritance in general was working fine when you build and open the designer. In this sample app, issue was because of a bug in the DataGridView designer code. This issue fixed today in the designer repo and will be available in the VS 16.9 preview2.

**Comment by dreddy-work** [comment]
Also, original issue was about the inheritance, I think we can close this issue. Let me know if you disagree @kirsan31.

**Comment by kirsan31** [comment]
@dreddy-work I've checked our big project and with visual inheritance seems all is ok...
But there were other problems about the new designer. Where to report them? V.S. report tool?

**Comment by dreddy-work** [comment]
> @dreddy-work I've checked our big project and with visual inheritance seems all is ok...
> But there were other problems about the new designer. Where to report them? V.S. report tool?

You can always report them via VS feedback tool. And that is preferred way for now for designer related issues. But if you end up reporting here, we might transfer the issue t designer repo ( which is not public) and it would be hard to track the status for you.

**Comment by dreddy-work** [comment]
As you opened #4139 , closing this issue.
