### ISSUE TITLE
User control designer does not work for .NET Core

### ISSUE THREAD

**Issue by ekolis** [dotnet/winforms#3339]
* .NET Core Version: 
3.1

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

1. Create a WinForms project.
2. Add a user control to the project.
3. Open the designer for the user control.

I get this error:

> Expected a proxy type,  Microsoft.VisualStudio.WinForms.RemoteClient.Proxies.ComponentProxy.

**Expected behavior:**
 The control designer opens.

**Minimal repro:**
see attached
[BrokenUserControlDesigner.zip](https://github.com/dotnet/winforms/files/4674080/BrokenUserControlDesigner.zip)

**Comment by kirsan31** [comment]
What V.S. version are you using? User controls in designer are [only available from 16.7 Preview](https://devblogs.microsoft.com/dotnet/windows-forms-designer-for-net-core-released/).

**Comment by ekolis** [comment]
Oh I see. I was using 16.6.0. Thanks!

**Comment by KingFisher7** [comment]
I have encountered the same problem and followed the helpful instructions provided here. The designer now works (VS 2019 16.7 Preview 3.1), but VS seems unable to compile a .dll file from it, nor does it show in my toolbox after creating the control. I have already checked, that AutoPopulate for Toolbox is activated.
Anyone stuck at the same point?

**Comment by paul1956** [comment]
@KingFisher7 User controls in forms are not support yet, and if you manually install them in a form the designer will delete them and there is an issue with NameSpaces deleted as well so MyControl.Name becomes Name. The only workaround is to close the Form in designer mode, manually add the user control in the form and build. If you open the Form Designer with your form again it will undo some or all of what you have done.
