### ISSUE TITLE
Add support for TMT_FONT

### ISSUE THREAD

**Issue by wjk** [dotnet/winforms#3340]
To make my app look more like native Windows components, while still supporting High Contrast themes, I use VisualStyleRenderer to draw "instruction text" (like the TaskDialog uses). In the default theme, this is 12-point Segoe UI, foreground color `#003399`. To do this, I use the class `TEXTSTYLE`, part 1, and state 0 (these values come from `vsstyle.h` in the Windows SDK).

However, when I attempt this, `VisualStyleRenderer.GetFont(FontProperty.GlyphFont)` returns null. Investigation using a tool that dumps aero.msstyles reveals that the above class/part/state combination defines `TMT_FONT`, but not `TMT_GLYPHFONT`, which is the only valid FontProperty in Windows Forms. Therefore, I must manually P/Invoke into uxtheme.dll every time I want to accomplish this task. I wish to avoid having to do this.

Proposed API is as follows:

```diff
 enum FontProperty {
+    TextFont = (int)Interop.TMT.FONT,
     GlyphFont = (int)Interop.TMT.GLYPHFONT
 }
```

I would also need to update the VisualStyleRenderer class to accept this FontProperty value. This feature does not need VS designer support, should not impact accessibility, and does not need to be localized. Thanks!

**Comment by RussKie** [comment]
> using a tool that dumps aero.msstyles

Out of curiosity, what tool are you using?

**Comment by wjk** [comment]
I'm using [PresentationTheme.Aero’s ThemeBrowser](https://github.com/gix/PresentationTheme.Aero/tree/master/Source/ThemeBrowser). Works great.

**Comment by RussKie** [comment]
Noice!

Providing a better theming experience is on our future roadmap, so fixes and enhancements in this area are quite welcome.

**Comment by hughbe** [comment]
Good idea. I was just looking at the docs and it seems like there are others that we could (should)? be supporting:
From https://docs.microsoft.com/en-us/windows/win32/controls/property-typedefs
ID | Notes
-- | --
TMT_BODYFONT |  
TMT_CAPTIONFONT |  
TMT_GLYPHFONT | The font that the glyph associated with this part will be drawn with, if font-based glyphs are used.
TMT_HEADING1FONT |  
TMT_HEADING2FONT |  
TMT_ICONTITLEFONT |  
TMT_MENUFONT |  
TMT_MSGBOXFONT |  
TMT_SMALLCAPTIONFONT |  
TMT_STATUSFONT

**Comment by wjk** [comment]
@hughbe I would like to disagree. Most of the other IDs you listed correspond to fonts that can already be retrieved using the `SystemFonts` class. The rest (ICONTITLEFONT, HEADING1FONT, HEADING2FONT) I have never seen used, even when using my msstyles-dumping tool.

**Comment by hughbe** [comment]
Alrighty thats fine then :)
