### ISSUE TITLE
Cannot rename ToolStripMenuItem in Items Collection Editor

### ISSUE THREAD

**Issue by docfresh** [dotnet/winforms#3342]
* .NET Core Version: 
3.1

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
I cannot rename toolStripMenuItems in the Items Collection Editor.

**Expected behavior:**
The item should be renamed.

**Minimal repro:**

1. Create a MenuStrip in a .NET Core Winforms app
2. Add a few items in the Items Collection Editor
3. Try to rename an item in the property grid under (Name)
4. Item does not rename, reverts to the default name

![image](https://user-images.githubusercontent.com/8064022/82780814-f03d2280-9e1d-11ea-950f-99b16162ebac.png)

**Comment by Vino-Wang** [comment]
@docfresh This issue has been fixed in preview release build. You can try to install the VS form here https://visualstudio.microsoft.com/vs/preview/ and try to rename your MenuStrip again.

**Comment by docfresh** [comment]
The preview build resolved it, but another bug:  After renaming the menu item, circled items do not update the name until you close and reopen the editor.
Thanks

![image](https://user-images.githubusercontent.com/8064022/82848973-807d7500-9ebb-11ea-9130-63a0c891a8a5.png)

**Comment by Vino-Wang** [comment]
@docfresh @RussKie The second issue has been filed in core designer area and it's still under investigation.

**Comment by merriemcgaw** [comment]
Thanks Vino! 
[Designer Issue](https://github.com/dotnet/winforms-designer/issues/1810)

**Comment by claudewill1** [comment]
I have this issue in the current version for VS2019e as of October 27th.

**Comment by RussKie** [comment]
@Vino-Wang can you please if this still repros? If not - please close.

**Comment by Cassie-Li01** [comment]
This bug fixed on Version 17.2.0 Preview 2.1 download from: https://visualstudio.microsoft.com/vs/preview/. 
And the related bug https://github.com/dotnet/winforms-designer/issues/1810 also has been fixed, so close this bug.
![fixed](https://user-images.githubusercontent.com/96758262/162112530-f0881690-9c71-480e-8110-38babfed0fbc.gif)
.
