### ISSUE TITLE
The version of System.Windows.Forms.dll is incorrect

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#3343]
* .NET Core Version: 
.NET Core 3.1.300

* Have you experienced this same bug with .NET Framework?: 
No

**More info:** 

1. This issue occurs in other Winforms .NET Core 3.1 dlls too.  
2. This issue occurs in the latest .NET Core 3.1 dlls too.
3. This issue does not occur in .NET Core 5.0
![Core5 0](https://user-images.githubusercontent.com/45864985/82801858-8e79c880-9eb0-11ea-9a09-9e747da7d1ce.png)

**Problem description:**
The version of .NET Core 3.1 System.Windows.Forms.dll is incorrect.
![Core3 1](https://user-images.githubusercontent.com/45864985/82801878-96396d00-9eb0-11ea-8b92-a3a15487018f.png)

**Expected behavior:**
The version of System.Windows.Forms.dll should be consistent with .NET Core version. 

**Minimal repro:**

1. Download and install VS 2019 from here: https://visualstudio.microsoft.com/downloads/
2. Open the C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.4 folder and check the version of System.Windows.Forms.dll in it.

**Comment by RussKie** [comment]
This is by design. Windows Forms .NET Core can't have a version less than .NET Framework (which is v4.8)
