### ISSUE TITLE
Remember Property Grid display style choice in Menu Items Collection Editor

### ISSUE THREAD

**Issue by docfresh** [dotnet/winforms#3345]
A MenuStrip's Items Collection Editor shows the MenuItems, and the properties for them in a property grid.

The property grid can be displayed 1 of 2 ways: Categorized, or Alphabetized. 

Unfortunately, it does not remember my preference.  I always prefer to see the grid alphabetized, but every time I go back into the Items Collection Editor, the property grid is displayed "Categorized"

![image](https://user-images.githubusercontent.com/8064022/82849403-6c3a7780-9ebd-11ea-97f6-f62a47dccb2a.png)

Tested in 16.7 Preview 1

**Describe the solution you'd like and alternatives you've considered**

Remember whether the User last selected Categorized or Alphabetized.

Or remember the setting based on the type of Items being edited in the Collection Editor. For example, maybe I want to see properties of ListView Columns in a categorized view, but I want to see ListView Items in an Alphabetized view.

**Will this feature affect UI controls?**
No

**Comment by RussKie** [comment]
Just to confirm, you're talking in a context of Visual Studio, where you'd like your choice to be remembered, right?

**Comment by docfresh** [comment]
Yes, that is correct.

**Comment by merriemcgaw** [comment]
Thanks for the suggestion! I can raise this issue on the designer side and if there are enough people requesting the feature then we can look at getting something in the designer. One question - are you referring to the Core Designer or the .NET Framework Designer?

**Comment by docfresh** [comment]
Core Designer.    It'd also be nice in .NET Framework Designer, but if I have to pick one, Core.

**Comment by RussKie** [comment]
Closing due to the age and the lack of interest from other members of the community.
