### ISSUE TITLE
Net5.0Preview4 Title blur when window is maximized

### ISSUE THREAD

**Issue by 199621616** [dotnet/winforms#3347]
.NET Core Version: 5.0.0-previcw4
 Title blur when window is maximized

Not is maximized,Display normal

Using components
DevComponents.DotNetBar2

![0](https://user-images.githubusercontent.com/25498672/82852754-5ae18180-9f36-11ea-9cf6-ac48f7fbe1cd.jpg)
![1](https://user-images.githubusercontent.com/25498672/82852771-68970700-9f36-11ea-89c3-e7d811faafbf.PNG)

**Comment by RussKie** [comment]
Please fill in all required information and ping us back to re-open.
