### ISSUE TITLE
The ImageIndex value is not automatically set to -1 after set the ImageKey property to an empty string.

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#3353]
* .NET Core Version: 
.NET 5.0.100-preview.6.20276.4 from master branch

* More info: 
This is a regression issue, this issue cannot reproduce in .NET 5.0.100-preview.5.20272.9 build.

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
The ImageKey and ImageIndex properties are mutually exclusive, meaning if one is set, the other is ignored. But now if set the ImageKey property to an empty string, the ImageIndex property is **not** automatically set to -1.

**Current behavior:**
The ImageIndex value is not automatically set to -1 after set the ImageKey property to an empty string.

**Expected behavior:**
The ImageIndex value should be automatically set to -1 after set the ImageKey property to an empty string.

**Minimal repro:**
1. Run the attached project. 
[TestApp.zip](https://github.com/dotnet/winforms/files/4688068/TestApp.zip)
2. Click the button1, then observe the value displayed in the message Box.

**Comment by weltkante** [comment]
Sounds like a regression with the recent PRs of making properties ignore setters if the value didn't change. For setters which had side effects outside the property they were setting (like here where it clears another property) this is a breaking change.

@hughbe @RussKie The PRs making setters idempotent (e.g. #3314 and #3126, maybe more?) may need another review to make sure the setters were not having observable side effects that are now suppressed.

It is common practice to set a property to the current value just to observe the side effects. Think of it as a form of 'refresh' behavior, in particular when the property assigns a mutable object and you want to force reevaluation of the object after changing its state.

**Comment by hughbe** [comment]
This was a deliberate impact of that PR that we documented. I don't have any complaints about fixing this though. I would argue that that, however, code should really be doing
```cs
control.ImageIndex = -1;
```

Rather than setting
```cs
control.ImageKey = "";
```

**Comment by weltkante** [comment]
What about the symmetric failure case where you set ImageIndex=-1 when an ImageKey is in use, does that properly reset the image or also fail? Do we require people to set both ImageIndex and ImageKey to remove an image reliably?

**Comment by weltkante** [comment]
@Amy-Li03 Also, about what ImageIndex/ImageKey are we talking here?

I remember one PR discussion mentioning that a goal was to have all implementations behave the same. So before deciding what to do here its important to keep in mind how other controls behaved before the regressing PRs.

**Comment by Amy-Li03** [comment]
@weltkante I talked in the issue is treeNode's ImageIndex/ImageKey property, and listView control doesn't exist this issue.

**Comment by RussKie** [comment]
Thank you @Amy-Li03.

@hughbe looking through the code I think this is a regression introduced in #3126 here:
![image](https://user-images.githubusercontent.com/4403806/83116127-b0708680-a10e-11ea-981a-5b2af52dfe9b.png)

By default `ImageKey == ""` not `null`, so previously when `ImageKey = ""` it would go and reset the `ImageIndex = -1`, now we're bailing out and the `ImageIndex` is not reset...

**Comment by Ashley-Li** [comment]
Verified this issue with .NET 5.0.100-preview.6.20276.4,this issue has been fixed. Run the attached project and click the button1,the ImageIndex value is automatically set to -1 after set the ImageKey property to an empty string.Please check below result：
![image](https://user-images.githubusercontent.com/56664234/84359696-97320480-abfb-11ea-8bba-ede361f6071d.png)
