### ISSUE TITLE
Control derived from ComboBox causes application crash with System.ArgumentOutOfRangeException when override OnMeasureItem method

### ISSUE THREAD

**Issue by gc-deniszmitrichenko** [dotnet/winforms#3354]
* .NET Core Version: 

.NET SDK 5.0.100-preview.4.20258.7

* Have you experienced this same bug with .NET Framework?: 

No
It is also not reproducible with .Net Core 3.1.

**Problem description:**

In derived from ComboBox class when sets ComboBox.DrawMode = DrawMode.OwnerDrawVariable and override OnMeasureItem method there is a call of OnMeasureItem method with MeasureItemEventArgs which Index property equals to -1.
Trying to access the ComboBox item by this index leads to System.ArgumentOutOfRangeException.

``` c#
    public class DerivedComboBox : ComboBox
    {
        public DerivedComboBox()
        {
            DrawMode = DrawMode.OwnerDrawVariable;
        }

        protected override void OnMeasureItem(MeasureItemEventArgs e)
        {
            var itemText = Items[e.Index].ToString(); // System.ArgumentOutOfRangeException
            var measuredSize = TextRenderer.MeasureText(e.Graphics, itemText, Font);
            e.ItemWidth = measuredSize.Width;
            e.ItemHeight = measuredSize.Height;

            base.OnMeasureItem(e);
        }
    }
```

![ComboBoxOnMeasureItemExceptionNet5](https://user-images.githubusercontent.com/61823719/83012574-4085d180-a024-11ea-8119-28af9177ae81.png)

**Expected behavior:**
Not to call OnMeasureItem with MeasureItemEventArgs.Index == -1.

**Minimal repro:**

1. Run attached app:
[DerivedComboBoxTestApp.zip](https://github.com/dotnet/winforms/files/4688368/DerivedComboBoxTestApp.zip)
2. Observe thrown System.ArgumentOutOfRangeException.

**Comment by RussKie** [comment]
This looks like may be a regression introduced in https://github.com/dotnet/winforms/pull/1837 (https://github.com/dotnet/winforms/pull/1837/commits/d503ac3d2f5c5e96329ed7252443be1833d743b9)
![image](https://user-images.githubusercontent.com/4403806/83098460-100a6a00-a0ee-11ea-94f5-fb523d61a48a.png)

Here's the state from 3.1:
![image](https://user-images.githubusercontent.com/4403806/83098398-dafe1780-a0ed-11ea-9f48-c3260dea5b53.png)


/cc: @hughbe

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .NET Core SDK 5.0.100-preview6.20302.5, the crash issue has been fixed that the project provided by customer can build & run successfully. See below GIF.
![UpdateCoreIssue](https://user-images.githubusercontent.com/38325459/83601844-fe203f80-a5a3-11ea-99e7-bdf08741f629.gif)

**Comment by RussKie** [comment]
Thank you @Zheng-Li01
