### ISSUE TITLE
Button component not available in Toolbox

### ISSUE THREAD

**Issue by DualBrain** [dotnet/winforms#3356]
* .NET Core Version: 
3.1 release in VS 16.6

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The Button component is missing from the VS Toolbox... Label (and many others are there), but no Button.

**Expected behavior:**

The Button component would be available (visible) in the Toolbox.

**Minimal repro:**

Other than it is happening "on my machine", I'm not sure how to repro - I'm also not aware of any way to *reset* the Toolbox.

(NOTE: I am working with WinForms in Visual Basic... so not sure if this might be related.)

**Comment by paul1956** [comment]
A lot of people are having this issue, From Feedback you need to reset Toolbox and when that doesn't work
Delete
```
privateregistry.bin
```
and when that doesn't work, delete files below (these will reset some VS settings).
```
privateregistry.bin.LOG1
privateregistry.bin.LOG2
toolbox.tbd
toolboxIndex.tbd
toolboxIndex_reset.tbd
toolbox_reset.tbd
ToolboxItemDiscoveryCache.7036b125-fa82-3aba-acb8-bdbc97782a06.dat
```

**Comment by RussKie** [comment]
Thank you @paul1956

**Comment by DualBrain** [comment]
Had to delete the files (and, thus, reset my UI prefs).

**Comment by paul1956** [comment]
@DualBrain I did too but I did see messages from others where the first or second option worked.

**Comment by paul1956** [comment]
@RussKie for completeness there are actually many buttons missing {some I sent via feedback) compared to what you get after reset. The most frequently used/noticed is the Button.

**Comment by RussKie** [comment]
@merriemcgaw FYI

**Comment by DualBrain** [comment]
To confirm, I tried the first suggestion and after it didn't resolve the problem, I then had to proceed to removing the batch of files.  Upon doing so, was able to see the controls.

**Comment by merriemcgaw** [comment]
@dreddy-work is working on figuring out why our designer install is corrupting the ToolBox. We're taking a look and it's a priority.

**Comment by dreddy-work** [comment]
@paul1956 , I am trying to repro this scenario locally, Can you please add the details on how you entered in this state of missing controls?  A straight winforms netcore 3.1 application is working just fine. I will also be looking into feedback tickets around this issue to see if i can get more details on repro scenario.

**Comment by paul1956** [comment]
@dreddy-work I did not do anything except try to add a Button to a Core 3.1 VB form and noticed it was missing (along with CheckBox and a few others), then checked C# Form and it was also missing and once it is fixed (which has different solutions for different people) it hasn't happened again. I also noticed it missing in 16.6 and needed to fix it there as well. The Form Designer has not really worked well for VB since it was first introduced as a VSIX so I don't know what release the items started being missing I only started using it with existing forms in 16.6.

**Comment by DualBrain** [comment]
I don't know if it helps or not, but I recently started fresh with a new machine.  Prior to v16.6 update, it was a fresh install with the only real addition related to VS is that of the latest DevExpress component install.  I then updated to 16.6.  Also, .NET WinForms projects are also still actively being developed on this same machine.

**Comment by paul1956** [comment]
I have never installed DevExpress component (I do have 2 project local components that I wrote). Since I and others used feedback to initially report you should be able to see what add-ons are installed.

**Comment by merriemcgaw** [comment]
Thanks for the suggestions and data points all! We're prioritizing this issue because it's not a fun way to start trying to work with WinForms Core apps!

**Comment by dreddy-work** [comment]
This should not be an issue anymore. This was an issue during an upgrade from VS 16.5 preview to next upgradable versions.  After that, we shouldn't be seeing it.  Closing this bug as fixed. Feel free to reopen if anyone see this issue in the latest VisualStudio version.
