### ISSUE TITLE
Not updating Minimum or Maximum property of NumericUpDown

### ISSUE THREAD

**Issue by Jean-Enrick** [dotnet/winforms#3379]
* .NET Core Version: 
3.1

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
When changing the value of the Minimum or the Maximum property for a NumericUpDown control from the Properties menu, the designer file is not updated. When building the project, the properties will keep their default values of 0 and 100.

**Expected behavior:**
If the value Minimum or Maximum property is changed from the default value, a new line is added to the designer file, setting the value to the one entered in the Properties menu.

**Minimal repro:**
Create a Windows Forms .NET Core app. In the design view for the default form, add a NumericUpDown control, change the value of the Minimum or Maximum property and build the project.

**Comment by Marie-Shi** [comment]
@Jean-Enrick There is a [Designer Issue](https://github.com/dotnet/winforms-designer/issues/1652) to track it and it has been fixed in preview release build. You can try to install the VS from here https://visualstudio.microsoft.com/vs/preview/ and try again.

**Comment by RussKie** [comment]
Fixed in VS 16.6P4
