### ISSUE TITLE
Whether  can reconsider supporting cross-platforms? 

### ISSUE THREAD

**Issue by maikebing** [dotnet/winforms#3383]
Whether  can reconsider supporting cross-platforms, whether  can consider implementing mono/winforms under Linux and macos ?
Or  rename mono/winform to Microsoft.NET.Sdk.LinuxDesktop  and   packe in to  .net core sdk !

**Comment by weltkante** [comment]
You cannot easily implement WinForms on different platforms, it just forwards most of its controls to the Windows OS and thus is highly specific to how Windows works.

As far as I'm aware the official response to the multiplatform requests is [MAUI](https://github.com/dotnet/maui).

**Comment by RussKie** [comment]
Cross-platform support is not on our roadmap in the foreseeable future, sorry. 
There are numerous technical challenges, some of which @weltkante mentioned above, that added together don't make a compelling business case.
