### ISSUE TITLE
Winforms child window is not scaled according to the DPI of the moitor.

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#3390]
* Have you experienced this same bug with .NET Framework?: 

Yes

**Problem description:**

Winfrom application is unable to render the child window appropriately according to the current monitor DPI when it's DpiAwareness is set to PermonitorV2. Also, when the application is dragged from one monitor to another with different DPI setting and then a new child window is opened, the child window is not rendered according to the monitor's DPI.

Same behavior is experienced if  the scaling of the monitor is changed and  then a new child window is opened, the child window is not rendered according to current monitor's DPI. Below is a screenshot clicked after dragging the application from one monitor to another and the front window was opened after dragging the application to second 

![image](https://user-images.githubusercontent.com/36968667/83702640-1bfc9d00-a5c2-11ea-8846-a457b15621a9.png)

**Expected behavior:**

Scaling of the parent and child forms should be consistent and according to the monitor DPI that they are rendered.

**Minimal repro:**

[WindowsFormsApplication (2).zip](https://github.com/dotnet/winforms/files/4726860/WindowsFormsApplication.2.zip)

**Comment by Ashley-Li** [comment]
Verified this issue with .NET 5.0.100-preview.7.20319.6 build, this issue has been fixed. Scaling of the parent and child forms are consistent and according to the monitor DPI that they are rendered.

**Comment by boilface** [comment]
It looks like the fixed code only applies to ShowDialog, when the problem also affects Forms shown normally, with Show.

**Comment by merriemcgaw** [comment]
@dreddy-work can you comment?
