### ISSUE TITLE
The MDI Child form does not render correctly at High DPI

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#3395]
* .NET Core Version: 
.NET 5.0.100-preview.6.20302.5

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
When  keeping the app running and changing the DPI from 100% to 175% or higher, the header of this maximized Mdi child windows shoule not be visible and label control in MDI child window should not be cropped.
But if we running the app on 100% DPI, then stop the running app and change the DPI from 100% to 175%, run this project again, this issue cannot reproduce.

![175%](https://user-images.githubusercontent.com/62929087/83830614-26c94600-a718-11ea-821b-06392aed3615.PNG)

**Expected behavior:**
The MDI child form should show correctly at high DPI as it was at 100%.

![100%](https://user-images.githubusercontent.com/62929087/83830568-11541c00-a718-11ea-92ab-66947226c7a9.PNG)

**Minimal repro:**
1. Run the test app with display at 100%. 
[MdiHighDpiTest-master.zip](https://github.com/dotnet/winforms/files/4733616/MdiHighDpiTest-master.zip)
2. Keep the app running and change the display to 175% or higher. (there is no sign out)

**Comment by kirsan31** [comment]
Currently .net HDPI support is not the best one, and will be completely [overhaul](https://github.com/dotnet/winforms/issues/3202#issuecomment-626072014) (I hope :) ).
And statement above is about system DPI (you need restart app on W10 and logout/login on W7). All other HDPI support version is nearly not working at all (At least for MDI) :(

**Comment by merriemcgaw** [comment]
@Amy-Li03, did you turn on PerMonitor awareness for this test. @dreddy-work - was this covered in your recent fix?

**Comment by Zheng-Li01** [comment]
@merriemcgaw, the issue reproduce on PerMonitroV2 as the screenshot in the above reproduce steps, and the text is blur with SystemAware, and the text is not scaled well with PerMonitor, please see below screenshots.

**PerMonitorV2:**
![PerMonitroV2](https://user-images.githubusercontent.com/38325459/84461615-77ecb300-ac9f-11ea-841a-9c0b977f3f4c.PNG)
**PerMonitor:**
![PerMonitor](https://user-images.githubusercontent.com/38325459/84461622-7c18d080-ac9f-11ea-9a86-b5cd8537d1ba.PNG)
**SystemAware**
 ![SystemAware](https://user-images.githubusercontent.com/38325459/84461626-7f13c100-ac9f-11ea-8bf6-30a6cef825e6.PNG)

**Comment by kirsan31** [comment]
@Zheng-Li01 

> the text is blur with SystemAware

If app was launch after DPI change and this setting is on: 

![image](https://user-images.githubusercontent.com/17767561/84484995-301c5a80-aca4-11ea-8d5d-ee1ef64bd1db.png)

the text will (must) not be blur.

@merriemcgaw does the activity in this thread mean that we need to report  PerMonitorV2 dpi problems?
As I mentioned above, on our app, combination of  mdi+PerMonitorV2+rdp was completely unusable :-( And we switched to SystemAware.

**Comment by webfoot** [comment]
If it's helpful, I grabbed an MDI C++ sample project from Microsoft and modified it to show the issue. What is the best way to communicate with the Microsoft team that will be working on this? Thanks!
https://github.com/webfoot/HighDpiMdiTest-cpp

![HighDefMdiChildIssue](https://user-images.githubusercontent.com/713740/84528056-d14ee500-ac93-11ea-8bc3-a40e3d5b24d6.JPG)

**Comment by merriemcgaw** [comment]
@webfoot I'd file feedback using the Windows Feedback tool. You can mark it as a bug and someone should take a look. There are so many submissions that bots try to find duplicates to make things easier so you might need to be a bit persistent. This looks like it's an underlying Windows issue if it's reproing in C++

@kirsan31 - we're testing PMA to see where our debt is and help us plan what future work we want to do. As much as I'd love to get it for .NET 5 I think we have to focus on the designer first. Once we've got that in good shape PMA will be high on the list of WinForms runtime priorities for .NET 6 or so. I can't promise timelines, but I can tell you that we're dying to sink our teeth into this problem because it's been something we've wanted to work out for years.

**Comment by dreddy-work** [comment]
This could be native issue. Tracking here: https://microsoft.visualstudio.com/OS/_queries/edit/33699482/

**Comment by dreddy-work** [comment]
To get the attention of the Windows team for issues related to MDI theming, Customers should raise them via Windows Feedback. The tracking of OS bugs linked above is not a high priority for the team, but they may prioritize it if they receive direct feedback with business justification.
