### ISSUE TITLE
WinForms needs to remove System.Drawing.Design.Primitives

### ISSUE THREAD

**Issue by ericstj** [dotnet/winforms#340]
**Problem description:**
https://github.com/dotnet/corefx/pull/33452 removed the System.Drawing.Design.Primitives assembly from CoreFx with the POR that the types would be added to WinForms.  When this happened it was too close to Preview1 so we delayed these moves.   It looks like that work was never resumed after Preview1.

**Actual behavior:** 
Old copy of System.Drawing.Design.Primitives.dll in the desktop shared framework.

**Expected behavior:**
No old copy of System.Drawing.Design.Primitives.dll in the shared framework.

**Minimal repro:**
Install latest SDK and examine "C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-preview-27318-3\System.Drawing.Design.Primitives.dll"

The fix for this should be to add the API for this assembly to WinForms, remove all uses of System.Drawing.Design.Primitives in this repository, then remove the redistribution of that dll from dotnet-trusted once WinForms change flows in.

/cc @dreddy-work @AdamYoblick

**Comment by dreddy-work** [comment]
PR against dotnet trusted repro is here: https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted/pullrequest/151285?_a=overview . We need to port thsi PR along with tests ( tests then was excluded).

**Comment by AdamYoblick** [comment]
@dreddy-work I'll take a shot at porting the PR if you have other things on your plate

**Comment by dreddy-work** [comment]
@AdamYoblick  , I just started on it as i was not able to remote log-in to my work machine. this is isolated one i can work from home today.

**Comment by dreddy-work** [comment]
sources are already in winforms repo now.  Some tests and cleanup  willmake this task complete. planned to finish this week.
