### ISSUE TITLE
Child items of System.Windows.Forms.StatusStrip are not added to the strip (designer issue)

### ISSUE THREAD

**Issue by mlsomers** [dotnet/winforms#3402]
ToolStripStatusLabel's (and maybe other items, not tested) are not visible, nither in the designer nor in runtime. It turns out they are never assigned to the strip's Items collection. A workaround (that only works in runtime) is to add them manually after `InitializeComponent`:
```
public Form1()
{
    InitializeComponent();
    this.statusStrip1.Items.AddRange(new []{ toolStripStatusLabel1, toolStripStatusLabel2, toolStripStatusLabel3, toolStripStatusLabel4 });
}
```

Related artifacts:
- Items need to be added using the Items property via the PropertyGrid (not a big issue).
- Come back to the designer later and all previously added items have disappeared! (PANIC!) but hit Cancel and they are still in the code-behind (Whew!)
- The Items designer does not allow renaming items, after changing the name and leaving the field the name jumps back to "toolStripStatusLabelx". Workaround is to refactor that in form.Designer.cs.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can we get an copy of this issue in the designer repo? It looks like the designer hasn't generated the code for this. If you can take a close look at the control and file any related issues (with the code generated) that would be super helpful.

**Comment by Olina-Zhang** [comment]
@merriemcgaw, added items by PropertyBrowser are still in form designer and runtime, no disappearing:
![image](https://user-images.githubusercontent.com/26474449/84460204-edef1b00-ac9b-11ea-9382-b56458c6f120.png)

Here are related existing Designer Issues: 1. [In-situ editing support](https://github.com/dotnet/winforms-designer/issues/380), 2. [Rename item cannot be refreshed](https://github.com/dotnet/winforms-designer/issues/1810) in time in ItemCollectionEditor for ContextMenuStrip/MenuStrip/StatusStrip/ToolStrip controls.

**Comment by merriemcgaw** [comment]
Thanks so much @Olina-Zhang!!

**Comment by RussKie** [comment]
@Olina-Zhang can you please check if this still repros? If not - please close.

**Comment by Olina-Zhang** [comment]
Verified in Visual Studio 2022, all related issues are fixed. Closing this issue now.
