### ISSUE TITLE
Winforms child window is not scaled according to the DPI of the monitor on signal monitor

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#3411]
* Have you experienced this same bug with .NET Framework?:
Yes

* .NET Core Version: 
Latest .net core sdk 5.0 preview7 20307.3

**More info:**
The issue also can reproduce when changing the Display Scale and Layout settings from 300% to 100% of the monitor in which the application is running.

**Problem description:**
Winform application is unable to render the child window appropriately according to the current monitor DPI when it's DpiAwareness is set to PermonitorV2.

**Expected behavior:**
Scaling of the parent and child forms should be consistent and according to the monitor DPI that they are rendered.

**Minimal repro:**
1. Open the solution in Visual Studio 2019 and run the application on 100% monitor.(
[CoreProject.zip](https://github.com/dotnet/winforms/files/4744799/CoreProject.zip))
2. Change the Display Scale and Layout settings from 100% to 300% of the monitor in which the application is running.
	**Note: Do not stop the running application**
3. Open child window by clicking on the "Open" button in the Main Form
![Coew_300_to_100](https://user-images.githubusercontent.com/38325459/84010824-c8b29200-a9a7-11ea-8efc-e476a243e0af.PNG)

**Comment by merriemcgaw** [comment]
@dreddy-work - FYI

**Comment by Olina-Zhang** [comment]
@dreddy-work It seems a dup of #3390, verified this issue in the latest .Net 7.0 SDK build, it doesn't reproduce when opening child window in secondary screen directly or changing DPI when app is running on single monitor.
