### ISSUE TITLE
No exception setting an invalid value for `ListViewGroupCollapsedState`

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#3424]
* .NET Core Version: 
.NET SDK 5.0.100-preview.6.20309.18

* Have you experienced this same bug with .NET Framework?: 
No

**More Info:**
This is a new supported property(new API: CollapsedState) in .NET 5.0 Preview 6, here is the pull: https://github.com/dotnet/winforms/pull/3155

**Problem description:**
No exception is thrown when setting an invalid value(e.g. -1, 3, 100) for Enum type ‘ListViewGroupCollapsedState’.
![Actual](https://user-images.githubusercontent.com/18568603/84351612-5089dd80-abee-11ea-9032-9661e355ebcb.PNG)

**Expected behavior:**
There should be an exception occurring: System.ComponentModel.InvalidEnumArgumentException: ‘The value of argument ‘value’ (-1) is invalid for Enum type ‘ListViewGroupCollapsedState’. (Parameter ‘value’)’
![Expected_FooterAlignment](https://user-images.githubusercontent.com/18568603/84351513-1c162180-abee-11ea-9dab-b86a7d04cb79.PNG)
**Minimal repro:**
1.	Create a winforms core project.
2.	Drag and drop a ListView control to Form designer.
3.	Add a ListViewGroup to it by clicking Edit Groups…
4.	Add following code to Form_Load event.
listView1.Groups[0].CollapsedState = (ListViewGroupCollapsedState)(-1);
textBox1.Text = listView1.Groups[0].CollapsedState.ToString();
5.	Build and run.

Or 
1.	Download the attached project. [ListViewGroup_CollapsedStateIssue.zip](https://github.com/dotnet/winforms/files/4762927/ListViewGroup_CollapsedStateIssue.zip)
2.	Extract it and run it.

**Comment by Ashley-Li** [comment]
Verified this issue with .NET 5.0.100-preview.7.20327.2 build,this issue has been fixed. After run the attached project,there's an exception occurring: System.ComponentModel.InvalidEnumArgumentException: ‘The value of argument ‘value’ (-1) is invalid for Enum type ‘ListViewGroupCollapsedState’. (Parameter ‘value’)’

**Comment by Jenna-Zheng** [comment]
Verified this issue with .NET 5.0.100-preview.8.20329.10 build,this issue has been fixed. After run the attached project,there's an exception occurring: System.ComponentModel.InvalidEnumArgumentException: ‘The value of argument ‘value’ (-1) is invalid for Enum type ‘ListViewGroupCollapsedState’. (Parameter ‘value’)’.Please check below result:
![image](https://user-images.githubusercontent.com/64949616/86088453-f6878400-bad8-11ea-896b-33d74587dcae.png)
