### ISSUE TITLE
The SelectedImageIndex value is not automatically set to -1 after set the SelectedImageKey property to an empty string

### ISSUE THREAD

**Issue by Ashley-Li** [dotnet/winforms#3425]
*  .NET Core Version: 
.NET 5.0.100-preview.6.20309.18 from master branch

* .More info
This is a regression issue, this issue cannot reproduce in .NET 5.0.100-preview.5.20272.9 build.
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
The SelectedImageKey and SelectedImageIndex properties are mutually exclusive; if one is set, the other is ignored. But now if set the SelectedImageKey property to an empty string, the SelectedImageIndex property is not automatically set to -1.

**Current behavior:**
The SelectedImageIndex value is not automatically set to -1 after set the SelectedImageKey  property to an empty string.

**Expected behavior:**
The SelectedImageIndex value should be automatically set to -1 after set the SelectedImageKey  property to an empty string.

**Minimal repro:**
1. Run the attached project.
[TestApp.zip](https://github.com/dotnet/winforms/files/4763082/TestApp.zip)
2. Click the button1, then observe the value displayed in the message Box.

**Comment by weltkante** [comment]
Related to #3353 just another property?

**Comment by Ashley-Li** [comment]
@weltkante The two issues have the same phenomenon but different properties, #[3353 ](https://github.com/dotnet/winforms/issues/3353)about ImageIndex and this issue about SelectedImageIndex.

**Comment by Ashley-Li** [comment]
Verified this issue with .NET 5.0.100-preview.7.20327.2 build,this issue has been fixed. Run the attached project and click the button1,the ImageIndex value is automatically set to -1 after set the ImageKey property to an empty string.

**Comment by Jenna-Zheng** [comment]
Verified this issue with .NET 5.0.100-preview.8.20329.10 build,this issue has been fixed. Run the attached project and click the button1,the ImageIndex value is automatically set to -1 after set the ImageKey property to an empty string.
