### ISSUE TITLE
numericUpDown goes to default parameters in the time of building

### ISSUE THREAD

**Issue by PasaOpasen** [dotnet/winforms#3428]
* .NET Core Version: 
.NET Core 3.1

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

numericUpDown parameters (Value exactly) go to default in the time of building. I choose current params, but after building there are default params and after closing of application there are same params in constuctor

To reproduce 
1. clone [this repository](https://github.com/PasaOpasen/Wave-animation-from-svd), 

2. open the [solution](https://github.com/PasaOpasen/Wave-animation-from-svd/tree/master/Svd_to_animation), 

3. comment 22-74 lines in [this file](https://github.com/PasaOpasen/Wave-animation-from-svd/blob/master/Svd_to_animation/Svd_to_animation/ScrollForm.cs)

4. uncomment 30 line in [this file](https://github.com/PasaOpasen/Wave-animation-from-svd/blob/master/Svd_to_animation/Svd_to_animation/Form1.cs)

5. set not default parameters for numericUpDown1 (by construcor!!!) into ScrollForm and build. 

U can set Value as 30, but after build it will be 0 (default)

**Comment by RussKie** [comment]
@KlausLoeffelmann could you please check this one.

**Comment by KlausLoeffelmann** [comment]
Sure. 

Hey @PasaOpasen, I took a look at the repo, and it has a lot of other stuff in it (even in the WinForms demo). Did you try if that bug reproduces in a minimal repo? And if yes, could you provide that demo here? Thanks!

**Comment by PasaOpasen** [comment]
@KlausLoeffelmann I did: https://github.com/PasaOpasen/__bagNumericUpDown_NETCore

**Comment by merriemcgaw** [comment]
@Olina-Zhang, can your team validate this scenario is working and close the issue if so? If it's not working please get a designer repo issue filed and link to the repo @PasaOpasen provides.

**Comment by Olina-Zhang** [comment]
Verified NumericUpDown's Value property worked well in the latest VS, it is a known issue in Winforms designer repo: [1652](https://github.com/dotnet/winforms-designer/issues/1652), which was fixed.

So close this issue now.
