### ISSUE TITLE
System.Windows.Forms.ListView.HideSelection issue with net48 migration

### ISSUE THREAD

**Issue by snhg** [dotnet/winforms#3430]
* .NET Version: 
.NET 4.8

**Problem description:**

Migrated winforms project from net472 to net48 and found that one of the control using System.Windows.Forms.ListView was not looking good. found that the HideSelection was set to False even though anywhere in my code its not set and left default to "true".

**Expected behavior:**
when the property not set in Designer it should be by default "true" not "false" as its happening in net48.

**Minimal repro:**

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik can you check to see if there was something with an Accessibility fix which could impact that?

**Comment by merriemcgaw** [comment]
@snhg Could you confirm whether this is back to the right value when you set the target back to 4.7.2?

**Comment by snhg** [comment]
Tried some tests on on my VS:
Microsoft Visual Studio Professional 2019
Version 16.6.2

1. create a Winform Application with target framework net48
2. drag and drop the listview control onto form
3. check the HideSelection property, Its "False"

1. create a Winform Application with target framework net472
2. drag and drop the listview control onto form
3. check the HideSelection property, **Its "False"**

This is strange!

Seeing same behavior with net2 also!

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/84460398-277c5200-acad-11ea-9609-7db8a20414c9.png)
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ListView.cs,238

I think `HideSelection` was put excluded with `AccessibilityImprovements.Level3` (introduced in net48). The docs have a remark suggesting that the setting should be turned off to meet accessibility requirements:
![image](https://user-images.githubusercontent.com/4403806/84460521-7de99080-acad-11ea-9036-520147b71d10.png)
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.hideselection?view=netframework-4.8#remarks


NB: in .NET Core / .NET this setting is turned off by default. We need to update the docs.

**Comment by snhg** [comment]
Thanks for the information

**Comment by RussKie** [comment]
@snhg thanks again for alerting us. I've raised https://github.com/dotnet/docs/issues/18952. 
@Tanya-Solyanik please feel to correct or provide more info, if necessary. 
@gewarren for visibility.
