### ISSUE TITLE
Setting a TreeNode to a certain position in a TreeNodeCollection is inserting it rather than replacing the existing one.

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#3437]
**.NET Core Version:**
All Versions from NetFx2.0 to CoreFx5.0

**Have you experienced this same bug with .NET Framework?**
Yes

**Problem description:**
Assigning a TreeNode object to the TreeNodeCollection Index property inserts it to the underlying Windows TreeView control rather than updating the existing, and causes the .NET Nodes collection no longer to be in sync with the Windows TreeView control.

**Expected behavior:**
Node should be updated.

**Minimal repro:**
* Create a new WinForms App
* Insert a TreeView on the Form.
* Insert the folloing code in the Form_Load event handler.

```
       private void Form1_Load(object sender, EventArgs e)
        {
            treeView1.Nodes.Clear();

            treeView1.Nodes.Add(new TreeNode("Item1"));
            treeView1.Nodes.Add(new TreeNode("Item2_node"));
            treeView1.Nodes.Add(new TreeNode("Item3"));
  
            var node = treeView1.Nodes[1];
            treeView1.Nodes[1] = node;
        }
```  
After running this code, the TreeView shows:

![image](https://user-images.githubusercontent.com/9663150/84449995-cc425500-ac03-11ea-95fc-32a22e0517c5.png)

**Comment by manuelvalenzuela** [comment]
Hello, I think there is a case that we could address separately:

Verify that the TreeNode does not previously exist in the TreeView, to be consistent with the methods: `Insert(int index, TreeNode node)` and `Add(TreeNode node)`.
I cannot assume that breaking changes will not be introduced, however allowing that case implies a state of inconsistency.

**Comment by RussKie** [comment]
> Verify that the TreeNode does not previously exist in the TreeView, to be consistent with the methods: `Insert(int index, TreeNode node)` and `Add(TreeNode node)`.

👍

**Comment by manuelvalenzuela** [comment]
Thank you, I just added a new Issue to address this
https://github.com/dotnet/winforms/issues/4293
