### ISSUE TITLE
Repositioning a Label control with Autosize TRUE and Anchor Bottom Left failed

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#3438]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1070453/error-en-reposicionamiento-de-un-control-label-con.html)._

---
He detectado el siguiente funcionamiento anómalo:
Tengo una pantalla con varios controles, entre ellos un TabControl y un DataGridview. Enmedio de los dos hay dos Labels.
Al cargar la pantalla, esos dos Labels que tienen sus propiedades Autosize=TRUE y Anchor=Bottom,Left, se colocan en una posición no correcta, que debería ser entre el DataGridView y el TabControl.
He visto que si cambio la propiedad Autosize a FALSE, ese mal comportamiento se arregla.

Translation from Bing:
I have detected the following abnormal operation:
I have a screen with several controls, including a TabControl and a DataGridview. In the middle of the two there are two Labels.
When loading the screen, those two Labels that have their Autosize-TRUE and Anchor-Bottom,Left properties are placed in an unsweeered position, which should be between the DataGridView and the TabControl.
I've seen that if I change the Autosize property to FALSE, that bad behavior is fixed.

---
#### Visual Studio Feedback System on 6/10/2020, 00:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### John Qiao [MSFT] on 6/10/2020, 02:27 PM: 

<p>Hi Maria,</p>
<p>Thanks for your feedback.</p>
<p>If you can reproduce this issue in a new simple project, please share your sample project here, we will test and check this scenario using your sample project on our side, that can help us provide the better response to you.</p>

#### maria.garbero on 6/10/2020, 03:38 PM: 

(private comment, text removed)
#### John Qiao [MSFT] on 6/10/2020, 05:28 PM: 

(private comment, text removed)
#### maria.garbero on 6/10/2020, 05:36 PM: 

<p>Sorry, but I need to change cbAño.SelectedIndex on Form_Load because I need that when I show form, DataGrid already has rows.</p><p>If I use Form Shown events, user can be how datagrid is filled.</p><p>I don't understand why it fails when autosize is True... Because height is the same, only width changes on text fills.</p><p>I think that is a bug of Visual Studio WinForms.</p>

#### John Qiao [MSFT] on 6/11/2020, 02:15 PM: 

(private comment, text removed)
#### maria.garbero on 6/11/2020, 02:23 PM: 

<p>Sorry but I can't remove RellenaFicha from RecuperaPagos because I use it on another part of code (I only sent you a part of code of a complex form).</p><p>If you disable Autosize property of labels, the problem has resolved.</p><p>I think that is a bug of Visual Studio. Could you report to support developer team? Thanks.</p>

#### John Qiao [MSFT] on 6/11/2020, 04:12 PM: 

<p>Hi Maria,</p><p>Thanks for your reply. </p><p>So, could you use below codes to showing the fPago form? That will resolve the label display issue. </p><pre>    Private Sub fMDI_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim fPago As New fPagos
        'fPago = New fPagos With {
        '    .MdiParent = Me,
        '    .Dock = DockStyle.Fill
        '}
        fPago.TopLevel = False
        fPago.Parent = Me
        fPago.Dock = DockStyle.Fill
        fPago.Show()
        fPago.Select()
    End Sub
<br></pre>

#### maria.garbero on 6/11/2020, 04:51 PM: 

<p>Sorry, but your code is not valid because parent is a MDIForm.</p>

#### John Qiao [MSFT] on 6/11/2020, 05:08 PM: 

(private comment, text removed)

---
#### maria.garbero solved on 6/11/2020, 05:15 PM, 0 votes: 

<p>Sorry, but I have problems with upper panel that I have in the original app.</p><p>I attach new project edited.</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/141051-errorlabelautosize.zip">errorlabelautosize.zip</a></p>

**Comment by John-Qiao** [comment]
* .NET Core Version: 
5.0.100-preview.7.20308.6

* Have you experienced this same bug with .NET Framework?: 
Yes

**More info:**
1. It’s not a regression issue.
2. If set the AutoSize property = **False** for that two Label controls, this issue will be fixed.
3. If move the edit label control text codes from Form_Load event to Form_Shown event, this issue will be fixed.
`        private void Form2_Load(object sender, EventArgs e)
        {   
        }

        private void Form2_Shown(object sender, EventArgs e)
        {
            label1.Text = "--";
            label2.Text = "--";
        }`
**Problem description:**
Label is not displayed correctly in form.
![Actual](https://user-images.githubusercontent.com/45864985/84460162-cdbf5c00-ac9b-11ea-8f78-46b13836f87d.png)

**Expected behavior:**
Label should be displayed correctly in form. 
![Expected](https://user-images.githubusercontent.com/45864985/84460166-d2841000-ac9b-11ea-9e1a-e63b760c1225.png)

**Minimal repro:**
1. Launch the attached project in VS.
2. Run this project.
[TestApp-Core.zip](https://github.com/dotnet/winforms/files/4768552/TestApp-Core.zip)

**Comment by merriemcgaw** [comment]
Given this is not a regression, we will move it to future.  @John-Qiao did you provide the workaround to the customer in VS Feedback as well.

**Comment by John-Qiao** [comment]
@merriemcgaw yes, I have provided the workarounds to customer in feedback.

**Comment by dreddy-work** [comment]
Should be addressed by https://github.com/dotnet/winforms/pull/7956. No repro with latest bits.
