### ISSUE TITLE
Port missing DesignBindingConverter

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#3443]
The `DesignBindingConverter`, which converts data bindings for use in the Design-Time environment, has not been ported yet from NetFx and is missing.

**Comment by weltkante** [comment]
Is this actually consumed anywhere in the WinForms runtime? Could be provided by the VS design time if its not needed at runtime, the API is not public.

In fact I didn't come across this as missing converter when I tested all metadata annotations, which may be indication that its (currently) not needed. Probably depends on the decision on where to put #3445

**Comment by KlausLoeffelmann** [comment]
See comments for #3444.
