### ISSUE TITLE
Port missing ControlBindingsConverter

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#3444]
The `ControlBindingsConverter`, which provides the `DesignBindings` and the `AdvancedBinding` for the `ControlBindingsCollection` in a Design-Time environment, has not been ported yet from NetFx and is missing.

**Comment by KlausLoeffelmann** [comment]
Still considering, though, if it makes sense to have it in the runtime.
We'd need a copy of `DesingBinding` and the Design-Binding-related Editors in the Core Designer anyway.

**Comment by weltkante** [comment]
Duplicate of #2412

**Comment by KlausLoeffelmann** [comment]
Ha! Thanks for pointing that out.

> as far as alternatives go you could provide the converter in the VS design time enviornment only.

Yes, this is how I implemented it right now, as I mentioned. I am still asking myself, if it's needed for other applications, anyway.

**Comment by weltkante** [comment]
Previously the "official" strategy was to port those by a on-demand basis. Custom hosted report designers usually have their own data binding system so I doubt this is necessary.

**Comment by KlausLoeffelmann** [comment]
Just to make everyone understand and for completeness. This would fail in Core. But I think you're correct. And who would do this and what for? 😄 So, Closing those.

```
public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            textBox1.DataBindings.Add(
                nameof(TextBox.Text),
                new Foo(),
                nameof(Foo.Bar));
        }

        private void button1_Click(object sender, EventArgs e)
        {
            var controlBindingsConverter = TypeDescriptor.GetConverter(textBox1.DataBindings);
            var bindings = controlBindingsConverter.GetProperties(null, textBox1.DataBindings, null);
            foreach (PropertyDescriptor designBindingPropertyDescriptor in bindings)
            {
                var designBinding = designBindingPropertyDescriptor.GetValue(textBox1.DataBindings);
                var designBindingConverter = designBindingPropertyDescriptor.Converter;
                Debug.Print(designBindingConverter.ConvertToString(designBinding));
            }
        }
    }

    public class Foo
    {
        public string Bar { get; set; }
    }
```

**Comment by weltkante** [comment]
Might want to comment on #2412, if I understand you correctly you have this in the VS designer and the broken attribute inside WinForms can be removed?

**Comment by KlausLoeffelmann** [comment]
I want to discuss this internally a bit further before making this call. But yes, I think that would make sense.

**Comment by KlausLoeffelmann** [comment]
Could you create an issue for that under which we can discuss?

**Comment by weltkante** [comment]
#2412 was actually the issue I created for fixing the WinForms attribute, the original description mentioned that as one of the options besides porting.

**Comment by KlausLoeffelmann** [comment]
I would rather have a dedicated issue for removing the Attributes, just for clarity.
Me missing what you just pointed out explains why. 😏
