### ISSUE TITLE
Port missing DesignBinding Class

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#3445]
The `DesignBinding` class, which is used in the Design-Time Environment to support Data Binding, has not been ported yet from NetFx.

**Comment by weltkante** [comment]
Is this actually consumed anywhere in the WinForms runtime? Could be provided by the VS design time if its not needed at runtime, the API is not public.

**Comment by KlausLoeffelmann** [comment]
See comments for #3444.
