### ISSUE TITLE
Replace `== null` and `!= null` with `is null` and `is not null`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#3459]
**Expected behavior:**

Scrub the codebase to replace all instances:
1. ~`== null` with `is null`, and~ done
1. `!= null` with `is not null` (**when C# 9.0 is generally available**)

**Expectations:**

1. Scrubs are done on per-project basis, one PR per project
2. PRs must not contain any other changes

**Comment by sashatankov** [comment]
Hey, I'd like to work on this one

**Comment by RussKie** [comment]
Awesome! Let's do it gradually, per project, to reduce churn and conflicts.

**Comment by sashatankov** [comment]
Do you want me to do any particular project? if not, then I randomly choose one

**Comment by weltkante** [comment]
You might want to fill out your template in the PR #3469 

Also it would be good to get confirmation that potential precedence changes between `==` and `is` operators do not have edge cases that require adding braces.

**Comment by RussKie** [comment]
No preference on a project, but `== null` -> `is null` for now until C# 9.0 is generally available.

**Comment by Youssef1313** [comment]
@RussKie A regex search in the whole repo with `==\s*null` shows only 3 results. Two of them are comments, and one is an assertion message string.

**Comment by elachlan** [comment]
@Youssef1313 do you know of an analyzer that handles this?

**Comment by Youssef1313** [comment]
@elachlan On Roslyn side, there is an open request for it in https://github.com/dotnet/roslyn/issues/56859. There is https://github.com/AArnott/CSharpIsNull though.

**Comment by elachlan** [comment]
@RussKie is the winforms team comfortable using the analyzer written by @AArnott at https://github.com/AArnott/CSharpIsNull?

**Comment by RussKie** [comment]
Yes, we know where to find him :) 
As a matter of fact we already using another package of his:
https://github.com/dotnet/winforms/blob/9538742d94b721c7af4b1b88e343eab7934d9d16/eng/Versions.props#L70

**Comment by elachlan** [comment]
[CSharpIsNull](https://github.com/AArnott/CSharpIsNull) has landed in winforms. So anyone wanting to refactor, it should now be a lot easier.

**Comment by elachlan** [comment]
@AArnott is this a false negative? `_priorWindowProcHandle` is a `void*`.
https://github.com/dotnet/winforms/blob/be03f45ccd99fded5a317daf825dc8bb6bbabb5c/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs#L513

Also `ppRetValOut` is an `IntPtr*` and has an `== null`
https://github.com/dotnet/winforms/blob/be03f45ccd99fded5a317daf825dc8bb6bbabb5c/src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs#L757-L762

**Comment by AArnott** [comment]
@elachlan regarding `_priorWindowProcHandle`, it looks to me like `void*` [*can* use `is null`](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGAzAATakDCpA3oaQ6QK4B2AzgIYBmM5KpAWQAUASlr1GkjCgBUpAG6kAvKRZMANuoDcEyQwCWXUkMX62qjerE09t0rr0BfB84KOgA==), so the analyzer suggesting using `is null` syntax doesn't appear to be a mistake. Or are you saying that the analyzer *didn't* pick up on it and you think it should?

Same observation/question for the second. I guess the confusion is what you mean by a false negative. If you mean no warning is produced and you think there should be, can you file a bug at https://github.com/AArnott/CSharpIsNull/issues?

**Comment by elachlan** [comment]
No warning is produced. I'll file a bug. Thanks :)

**Comment by elachlan** [comment]
The issue I filed: https://github.com/AArnott/CSharpIsNull/issues/30
