### ISSUE TITLE
The icon is the same for both ListBox & CheckedListBox controls in Toolbox window

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#3460]
* .NET Core Version: 
5.0 Preview 7 5.0.100-preview.7.20316.3

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
The icon is the same for ListBox & CheckedListBox controls.
![Same](https://user-images.githubusercontent.com/18568603/84849160-4b61de00-b087-11ea-98a8-75df217ad0c7.png)

**Expected behavior:**
The icon should not be the same.
![NotSame](https://user-images.githubusercontent.com/18568603/84849163-4dc43800-b087-11ea-8750-c8d46bd7c09f.png)

**Minimal repro:**
1. Create a winforms core project.
2. Type 'listBox' words in Toolbox's search box.
3. Observe the controls' icon.

**Comment by Vino-Wang** [comment]
> Interestingly, this is a runtime bug... see https://raw.githubusercontent.com/dotnet/winforms/master/src/System.Windows.Forms/src/Resources/System/Windows/Forms/ListBox.ico
> 
> @dreddy-work - do you happen to have the original icons you got from the designer?



> They are here: https://devdiv-design.visualstudio.com/DevDiv%20Design/_workitems/edit/1787

**Comment by RussKie** [comment]
I've checked devdiv-design.visualstudio.com/DevDiv%20Design/_workitems/edit/1787, and the attached zip doesn't contain the expected icon.
@dreddy-work could you point me where I can get the right icon.

**Comment by dreddy-work** [comment]
@RussKie , It seems we got same Icons for both of them. its in the attached zip folder. We will have to reach out to the Icon design team to get the right one.

**Comment by dreddy-work** [comment]
Here is the work item to get the Icon updated: https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/12521,

**Comment by merriemcgaw** [comment]
I'm moving this to 6.0. I don't think this is important enough to get in here in the end game.

**Comment by merriemcgaw** [comment]
Let's keep this in master so we don't inadvertently get odd behavior with one icon out of all of ours that isn't consistent with the rest.
