### ISSUE TITLE
An error dialog pops up after left-double-click "NETCoreTest" project to check the .csproj file

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#347]
**OS:** RS4 x64
**VS:** 16.0.0 Preview 2.0 [28522.59.d16.0]
**.NET SDK:** .NET Core 3.0.100-preview-010143
 
**More info:**
1.	This issue also can reproduce on Console and Class library .net core applications.
2.	The issue can’t reproduce on 16.0.0 Preview 1.1 [28408.50.d16.0] + latest NET Core 3.0.100-preview-010143.
 
**Steps to reproduce:**
1.	Install .NET Core 3.0 SDK available from https://github.com/dotnet/core-sdk.
2.	Create a Winforms .Net Core application by command: dotnet new winforms –o “NETCoreTest”.
3.	Open the project and left-double-click "NETCoreTest" project to check the .csproj file.
 
**Actual:**
An error dialog pops up. 
![image](https://user-images.githubusercontent.com/38325459/51594368-3edb6380-1f2f-11e9-9ed9-cf6d1ec8fcdd.png)
**Getting more info from here:**
[\\\trinlab2\BAQAFiles\v-zhgl\New folder\ActivityLog.xml](url)
 
**Expected:**
No error dialog pops up.

**Comment by OliaG** [comment]
This issue was moved to dotnet/project-system#4491
