### ISSUE TITLE
Controls can't be dragged with mouse while in TabControl

### ISSUE THREAD

**Issue by KoB-Kirito** [dotnet/winforms#3475]
* .NET Core Version: 
3.1

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Controls can't be dragged around while they are in a TabControl.
TabControl is in general quite buggy. I can also not drag anything into a tab, but the first, because it always switches back to the first tab.

**Expected behavior:**
To be able to drag controls around like outside of TabControls.

**Minimal repro:**
- Create a new Windows Forms App (.NET Core)
- Go in designer-view
- Add a TabControl
- Put something in the TabControl
- Try to drag it with the mouse

**Comment by selviktoria6** [comment]
I just reproduced that.

**Comment by merriemcgaw** [comment]
Thank you for reporting this issue. Can you tell me what version of VS you're encountering this is? We've fixed it in a recent 16.7 Preview, so you should be seeing it shortly in the Preview channel.

**Comment by KoB-Kirito** [comment]
I'm on 16.6.2.
Thank you!

**Comment by merriemcgaw** [comment]
In that case you should see the fix in the next 16.7 Preview. It works perfectly for me there.

**Comment by KoB-Kirito** [comment]
Yes, I tried it with the preview and it works!

But another thing I forgot, and I don't know if I should open a new issue, but the document outline does not work. Neither in 16.6.2, nor in 16.7 Preview.

You can't move items there. Not with mouse, and not with the four arrow-buttons (they are grayed out).

Workaround: Select an item, right click, put in foreground -> Moves the item to the top. But you have to do it with everything.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team confirm this is now working in 16.8? I think we've had this ability for a while now. Please close this issue when you confirm it's working.

**Comment by Olina-Zhang** [comment]
Verified in 16.8, dragging controls with mouse in TabControl is working well. 
@KoB-Kirito the issue in Document Outline Window is known, will fix it later.
So, close this issue now.
