### ISSUE TITLE
Cursor(Stream) bugs

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#3492]
**.NET Core Version:**
master

**Have you experienced this same bug with .NET Framework?:**
probably

**Problem description:**
As noted [here in a PR](https://github.com/dotnet/winforms/pull/3476#discussion_r443216116) the constrcutor of `Cursor` taking a `Stream` is broken

```cs
public Cursor(Stream stream)
{
    if (stream == null)
    {
        throw new ArgumentNullException(nameof(stream));
    }

    int length = checked((int)stream.Length);
    _cursorData = new byte[length];
    stream.Read(_cursorData, 0, length);
    LoadPicture(
        new Ole32.GPStream(new MemoryStream(_cursorData)),
        nameof(stream));
}
```

- if the stream position isn't at zero the buffer would be allocated too large (suboptimal)
- if the stream doesn't know its length this would throw even though it doesn't have to (bug)
- `Read` is allowed to read less then `length` bytes so cursor data may be incomplete (bug)

Users can work around those bugs by wrapping their stream, but really the code should do a `stream.CopyTo(MemoryStream)` to let it do the heavy lifting and be more compatible to passing in arbitrary streams.

Note the current code doesn't throw, it just over-allocates and then reads less bytes than requested, which is fine if the cursor data is still represented completely at the current position.

**Expected behavior:**
- streams which don't expose their length can still be read
- streams which provide data in chunks still can be loaded

**Minimal repro:**
provide a custom stream

**Comment by rickbrew** [comment]
Looks like this bug is being triggered by the latest Win11 Insider "Dev" build 10.0.22567.0 and is causing a lot of crashes now https://github.com/dotnet/winforms/issues/6798

**Comment by weltkante** [comment]
@rickbrew I'd call this a an external regression, this bug is really about custom streams, file streams were always "implicitly guaranteed" to read as much as possible on Windows, too much code relied on that behavior historically to change it, I'd be surprised if .NET team came to a different conclusion now and decided to break people.

I think the other issue acknowledged it being an external regression.

**Comment by elachlan** [comment]
Would something like this do it?  
```csharp
public Cursor(Stream stream)
{
    ArgumentNullException.ThrowIfNull(stream);
    MemoryStream memoryStream = new();
    stream.CopyTo(memoryStream);
    memoryStream.Position = 0;
    _cursorData = memoryStream.ToArray();
    LoadPicture(
        new Ole32.GPStream(memoryStream),
        nameof(stream));
}
```

> if the stream position isn't at zero the buffer would be allocated too large (suboptimal)
I don't think this fixes that.

.NET 7 has added `ReadAtLeast` and ReadExactly. Which may help solve it another way.
https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.readatleast?view=net-7.0
https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.readexactly?view=net-7.0

**Comment by weltkante** [comment]
> Would something like this do it?

Yes, this is what I suggested in the OP

> .NET 7 has added ReadAtLeast and ReadExactly. Which may help solve it another way.

ReadAtLeast/ReadExactly don't help here as they don't adress all the issues I mentioned in the OP. Really all that is necessary is to copy into the MemoryStream like mentioned, since its needed anyways to pass into the interop layer.
