### ISSUE TITLE
ListView attaches lifetime to ImageList

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#3494]
**.NET Core Version:**
3.1 and master

**Have you experienced this same bug with .NET Framework?:**
yes

**Problem description:**

When a ListView is assigned an ImageList it subscribes on events. This attaches the lifetime of the ListView to the ImageList, i.e. the ListView cannot be collected before the ImageList. If the ImageList outlives the ListView then the ListView (and everything attached to it) is leaked.

Other controls like TreeView solve this by unsubscribing during disposal.

original article here: https://blog.ramondeklein.nl/2009/05/18/listview-may-leak-with-imagelists/

**Expected behavior:**
ListView lifetime should be independent of ImageList lifetime. Implementation should be similar to TreeView which apparently already solves this problem.

**Minimal repro:**
* create a ListView
* assign it an ImageList
* clear reference to ListView but keep reference to ImageList
* observe ListView not getting collected

(for details see linked article)

**Comment by Amy-Li03** [comment]
Verified this issue with latest .NET 5.0.100-preview.8.20329.10 build, issue was fixed. ListViews can be collected when you don’t reset the imageList yourself.
