### ISSUE TITLE
Printing from ASP.NET Core Razor Pages through Windows Forms Library

### ISSUE THREAD

**Issue by jlchavez** [dotnet/winforms#3500]
**Is your feature request related to a problem? Please describe.**
I'm using Syncfusion.PdfViewer.Windows for printing a Pdf through the .NET Core 3.1 App with the WindowsForms SDK without starting the Form, the test worked fine. Syncfusion's library works perfect for printing the Pdf.

Yes I can make it a .NET Framework 4.8 Windows Service, but I would have to create a complete set of tools to manage thist printing service, will I could just add pages to the Hosted Service and run integrated, without having to make APIs, authentication, using tooling that is old as Microsoft has no out-of-the-box solutions as we used to have with Remoting or WCF or ASP.NET WebServices, so we have to reinvent the wheel with gRPC or SignalR or WebSockets. Yes this would be done to interact in another stage,

Calling the "Console App" wouldn't be a problem with Process.Start, but It's just a workaround.

I tried referencing the System.Windows.Forms, library, but it's a Reference Assembly, I added it from the SDK, and a couple more assemblies, but it required a native dll. So the binding are the one that are missing so that it can be used the references assembly. 

Some printing is done manually through PrintDocument so this would be easier for any one to print.

**Describe the solution you'd like and alternatives you've considered**
I Would like to print it through a Hosted Service App running as a Windows Service in .NET Core 3.1. I know it's not a expected thing to be integrated into a ASP.NET WebForms App, you could separate the Printing API, if you wish. 

A SDK or something that let's us reference this from the Microsoft.NET.Sdk.Web SDK, or a way to add it would be great.

**Will this feature affect UI controls?**
NO

**Comment by RussKie** [comment]
Apologies I'm having troubles parsing what you're asking for.

Windows Forms is an SDK for building Windows desktop apps. Other tech you mention are web stacks, that have nothing to do with Windows desktop.
Printing is typically a user interactive action, where a user is presented with a print dialog, etc. Printing from a web should be handled by a browser app.

If you need to generate PDFs from your web apps then I don't think use of Windows Forms is appropriate, and you should look at functionality provided by the [.NET runtime printing](https://github.com/dotnet/runtime/tree/master/src/libraries/System.Drawing.Common/src/System/Drawing/Printing).
