### ISSUE TITLE
Move validation steps to post-build

### ISSUE THREAD

**Issue by mmitche** [dotnet/winforms#3505]
Winforms should opt-in to post-build validation for SDL, NuGet validation, etc.,

To enable the nightly validation runs, you add repo entries here: https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=%2Feng%2Fpipeline%2Ftools%2Frepos-to-validate.txt and this file a version of https://github.com/dotnet/aspnetcore/blob/master/eng/sdl-tsa-vars.config into your repo under the eng folder. Then the validation steps can be disabled in your azure pipeline as they have been in runtime’s build https://github.com/dotnet/runtime/blob/master/eng/pipelines/official/stages/publish.yml#L30-L49

**Comment by AdamYoblick** [comment]
Closing this out as Matt already did the work for us :)
