### ISSUE TITLE
Make the designer experience of the ToolStrip controls identical to the classic controls

### ISSUE THREAD

**Issue by raffaeler** [dotnet/winforms#3506]
This is  a suggestion to consider making the designer experience identical regardless the control being used on the form.

The latest generation controls (Toolstrip related) have a different designer-experience in comparison to all the others.
While using the designer you often have to use dialogs to configure the properties of the toolstrip buttons, combos, etc.

Of course this suggestion is not meant to change any runtime experience or behavior, neither the designer generated code. It is just a matter of the designer experience.

**Comment by merriemcgaw** [comment]
The VS Designer experience for each control is created separately, so do you have any specific suggestions that you can describe? Screenshots are also super helpful.

**Comment by merriemcgaw** [comment]
Hah! I misunderstood. We are working on the feature to allow what we call in-situ editing (in designer surface) of the ToolStrips. It should be coming in the not too distant future. 😊

**Comment by Tanya-Solyanik** [comment]
@raffaeler - Please download the recent preview build [Visual Studio 2019.11 preview 3](https://visualstudio.microsoft.com/vs/preview/) In situ toolstrip editing experience should be available there. Please use vs feedback channel (feedback button in the VisualStudio) to file more designer-related bugs.

**Comment by raffaeler** [comment]
Thank you @Tanya-Solyanik 
Apparently this change started passing index == 0 to `OnMeasureItem` (previously the value was -1) which caused my code to throw and crashed VS. I fixed this in my code by preventing the unexpected index, but I just want to let you know that designer code can crash VS.

In addition to that, there is something else that is preventing to load the designer:
```
---------------------------
Microsoft Visual Studio
---------------------------
The designer cannot be shown because the document for it was never loaded.
---------------------------
OK   
---------------------------
```
I will make some further investigation before reporting through VS feedback. I would anyway suggest to be more specific in the error. Whatever is the cause, it's clueless.

Thank you

**Comment by raffaeler** [comment]
No way to reproduce it. I just closed and reopened the form multiple times and now it loaded.
Literally no other changes, not even rebuilding. Looks like a VS (caching?) issue.

**Comment by raffaeler** [comment]
@Tanya-Solyanik The behavior is weird. Even the code editor screws up.
I tried to give all the details here:
https://developercommunity.visualstudio.com/t/cannot-load-windows-forms-designer-in-vs-16110-pre/1496506

HTH

**Comment by raffaeler** [comment]
@Tanya-Solyanik 
As usual, the first-level support marked as "need more info" the issue I opened.
Frankly, I don't know what could I provide more than I already did.
If you can do something with the feedback, your are welcome, otherwise I will let them close it.
