### ISSUE TITLE
FileDialog.InitialDirectory does not work

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#3513]
**.NET Core Version:**
master

**Have you experienced this same bug with .NET Framework?:**
yes

**Problem description:**
`FileDialog.InitialDirectory` doesn't seem to work? It works for the classic dialog, but modern dialogs seem to ignore it, even though there is source code handling it. Debugging the source seems to throw `FileNotFoundException` when calling `GetShellItemForPath`. Might be an interop mistake?

**Expected behavior:**
`FileDialog.InitialDirectory` should actually set the directory.

**Minimal repro:**
Create and show an `OpenFileDialog` with a non-empty `InitialDirectory` (make sure you get the modern version of the dialog)

**Comment by weltkante** [comment]
When fixing this, there is also desire to support special shell paths like "my computer". Might want to make sure that the fixed code understands these special paths when passing the string to shell API for translation, otherwise new API would be required to support them.

Also see #3512 for adding `InitialDirectory` to `FolderBrowserDialog`, in case the API suggestion gets accepted before this is fixed both can be done together.

**Comment by kirsan31** [comment]
From yesterday rc2 [blog post](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-2/#comment-7635):

System.Windows.Forms.OpenFileDialog. Setting a value for the “InitialDirectory” property has no effect when running ShowDialog. **Works fine with .NET Core 3.1.**

**Comment by weltkante** [comment]
Might want to reclassify as regression then, my own test above already was against master. Must be some mistake in COM interop.

**Comment by kirsan31** [comment]
Yes, it's **regression** from 3.1. Repro (3.1 works, 5.0 - not): [OpenFileDialog.zip](https://github.com/dotnet/winforms/files/5376862/OpenFileDialog.zip)
Good to be fixed before 5.0 release. @RussKie ?

**Comment by RussKie** [comment]
> Good to be fixed before 5.0 release.

Sorry, .NET 5.0 is complete. This _may_ meet a servicing bar for 5.0.x. /cc: @merriemcgaw

**Comment by kirsan31** [comment]
> Sorry, .NET 5.0 is complete. This _may_ meet a servicing bar for 5.0.x.

_Complete_ for **regression** fixes on rc?
I am not sure about modern\classic dialogs, but simple using of `OpenFileDialog` produces same dialog look on Win10 for `netcoreapp3.1`, `net5.0-windows` and `net472`. And `InitialDirectory` not working only in net5 :( So this is pure regression from .net framework and .net core...

**Comment by merriemcgaw** [comment]
I'm going to have someone take another look at this ASAP. I can't promise we can get it into 5.0 GA simply because we're very close to locked down. Once we know what the root cause is and the risk of a fix we can determine if we can get it through in time for GA. If we can't, we can certainly look to it for servicing.

**Comment by kirsan31** [comment]
> I'm going to have someone take another look at this ASAP. I can't promise we can get it into 5.0 GA simply because we're very close to locked down. Once we know what the root cause is and the risk of a fix we can determine if we can get it through in time for GA. If we can't, we can certainly look to it for servicing.

Thank you. Let's hope, because only this bug alone is enough (for us) to not switch to 5.0 :(
P.s. Need to correct labels...

**Comment by JeremyKuhne** [comment]
Investigating

**Comment by RussKie** [comment]
> _Complete_ for **regression** fixes on rc?

Tthere is a release process, and we're just one of the outer nodes on the graph. It takes weeks to prepare a public release, so we do have hard deadlines after which no change is accepted, and go into a subsequent servicing release.

**Comment by Amy-Li03** [comment]
Verified issue on .Net 5.0.202 & .Net 6.0 latest build: 6.0.100-Preview.4.21181.20, this issue all fixed now. FileDialog.InitialDirectory works correctly.
