### ISSUE TITLE
In windows 2004, IME in DataGridView has some problem

### ISSUE THREAD

**Issue by TempeBrennan** [dotnet/winforms#3547]
* .NET Core Version: 

 Version: 5.0.0-preview.2.20160.6

* Have you experienced this same bug with .NET Framework?: 

Yes

**Problem description:**

use this code to create a DataGridView
```
            var dataGridView1 = new DataGridView();
            dataGridView1.Width = 500;
            dataGridView1.Columns.Add(new DataGridViewTextBoxColumn());
            dataGridView1.Columns.Add(new DataGridViewTextBoxColumn());
            dataGridView1.Columns.Add(new DataGridViewTextBoxColumn());
            this.Controls.Add(dataGridView1);
```

1. double click one cell, use jp hiragaga and press k and then press i
candidate show like this:
![image](https://user-images.githubusercontent.com/51563666/87009646-0baa9400-c1f8-11ea-8c14-56443ce640ad.png)
2. click other cell, not double click, press k and i directly.
candidate change like this:
![image](https://user-images.githubusercontent.com/51563666/87009780-3d235f80-c1f8-11ea-8673-0794375b9e1c.png)

I can confirm this issue is fine before windows update

version:
os need windows 2004

**Expected behavior:**
both two case show same candidate

**Minimal repro:**
both two case show different candidate

Could MS told us this is new IME startegy in DataGridView or will fix it in the next version?

**Comment by TempeBrennan** [comment]
Is there any pbody else meet this issue?
Using DataGridView

**Comment by RussKie** [comment]
@Olina-Zhang could you please verify?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang could you please verify?
@RussKie we can repro this issue on 2004 OS, and cannot repro it on 1909 OS. Please see following gif:
2004 gif:
![2004](https://user-images.githubusercontent.com/26474449/88642770-7b26eb80-d0f3-11ea-8f83-5d0ad0860240.gif)
1909 gif:
![1909](https://user-images.githubusercontent.com/26474449/88642683-60ed0d80-d0f3-11ea-8863-7113c5487ef7.gif)

**Comment by Tanya-Solyanik** [comment]
@TempeBrennan, since this regression is associated with the new windows release, please report it on the windows support site - https://answers.microsoft.com/en-us/windows/
