### ISSUE TITLE
ComboBox.DisplayMember property should be used as an accessible name for combobox items

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#3549]
* .NET Core Version: 
.NET 5.0

* Have you experienced this same bug with .NET Framework?: 
works correctly in 4.7.2, does not work in 4.8

**Problem description:**
AT user does not know what items are available for selection 

**Expected behavior:**
DisplayMember property is used to access name

**Minimal repro:**
	1. Create a new winforms application targeting Core
	2. Add a class with at least one string property (Name in this case)

```
	    public class Person
	    {
	        public Person(int id, string name)
	        {
	            Id = id;
	            Name = name;
	        }
	
	        public int Id { get; set; }
	        public string Name { get; set; }
	    }
```
	
3. Add a combobox to the form
4. Create a collection of "Persons"( type created in step 2) 
5. Set combobox's DataSource property to collection created in step3 and DisplayMember property to the name of the string property in the class from step 2 

```
	        private void Form1_Load(object sender, EventArgs e)
	        {
	            List<Person> persons = new List<Person>();
	
	            persons.Add(new Person(1, "Name 1"));
	            persons.Add(new Person(2, "Name 2"));
	            persons.Add(new Person(3, "Name 3"));
	            persons.Add(new Person(4, "Name 4"));
	            persons.Add(new Person(5, "Name 5"));
	
	            comboBox1.DataSource = persons;
	            comboBox1.DisplayMember = "Name";
	       }
```
6. Run this application under the inspect tool
**Result**: type name is used as accessible name for the combobox list items, because a object.ToString is called:
![image](https://user-images.githubusercontent.com/15823268/87098832-1582c600-c1fd-11ea-93e1-df9b5980ebcf.png)

Expected:
Accessible tree should show the same strings as the drop down shows

![image](https://user-images.githubusercontent.com/15823268/87098581-7d84dc80-c1fc-11ea-9c63-6a1652576143.png)

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .Net 5.0.100-rc.1.20378.13, the issue has been fixed that the "Name" of list items for ComboBox control displayed correctly.
![UpdateCoreIssue](https://user-images.githubusercontent.com/38325459/88762029-eb407a80-d1a2-11ea-839c-184915fb4d9c.PNG)
