### ISSUE TITLE
[Accessibility] There is no ability to set custom Accessible Name, Role, Description to some AccessibleObjects

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#3560]
* Original [Bug 1108206](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1108206)

* .NET Core Version: **5.0**

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
- A customer can't set a custom Name, Role and Description for the following AccessibleObjects:       
  
1. ToolStrip (Name)
2. ToolStripItems (Role and Description of some)
3. StatusStrip (Name)
4. StatusStripItems (Role and Description of some)
5. MenuStrip (Name)
6. MenuItems (Role and Description of some)

**Expected behavior:**
- A customer can set the custom values of AccessibleName/Role/Description for any AccessibleObjects

**Minimal repro:**
- Create a Core 5.0 app
- Add a control from the list above to the form
- Set AccessibleName/Role/Description for it
- Run the app and check the control's AccessibleObject UIA properties using Inspect

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .NET 6.0.100-alpha.1.20420.20 that the issue has been fixed that the customer Accessibility Name/Role/Description can be seen in the inspect tool.
![UpdateCoreIssue](https://user-images.githubusercontent.com/38325459/90868008-cd90ba80-e3c8-11ea-86e5-2554c8c403fd.gif)

**Comment by merriemcgaw** [comment]
@RussKie, @SergeySmirnov-Akvelon do we have a PR for this that goes to .NET 5? This would be nice to have by GA.

**Comment by RussKie** [comment]
@merriemcgaw this is already in RC1
![image](https://user-images.githubusercontent.com/4403806/93411908-7c98b700-f8df-11ea-9e4e-285aa5c70d88.png)
