### ISSUE TITLE
Missing `AutoUpgradeEnabled` property description

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#3573]
## Version info:
Dev16 16.8.0 Preview 1.0 [30307.178.master] + .NET 5.0 Preview8.20363.2

## Have you experienced this same bug with .NET Framework?
No

## More info:
1.This is not a regression issue that can repro in Dev16 16.6.3.
2.The '‘UserDescriptionForTitle’ & ‘AutoUpgradeEnabled’ properties are new added for core project, not appear in the property browser window in the Framework project.

## Minimal Reproduction Scenario
1. Create a winforms .NET Core project with a FolderBrowserDialog control.
2. Select the ‘AutoUpgradeEnabled’ property of folderBrowserDialog1 in the property browser window.
3. Observe the description for ‘AutoUpgradeEnabled’ property in the description pane.

## Expected Behavior
Have the description for ‘AutoUpgradeEnabled’ property in the description pane.

## Current Behavior
1. Missing the description for ‘AutoUpgradeEnabled’ property in the description pane.
2. For the ‘UserDescriptionForTitle’ of FolderBrowserDialog control, the description is inaccurate.(SaveFileDialog/OpenFileDialog are not having the property).

![Core](https://user-images.githubusercontent.com/38325459/87373785-ebdeeb80-c5bc-11ea-8a45-97e3627d01c2.PNG)

**Comment by RussKie** [comment]
`AutoUpgradeEnabled` has never had a description, so it is not a regression
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/FileDialog_Vista.cs,344

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .NET 6.0.1000-alpha.1.20506.3, the issue has been fixed that the description for  ‘UserDescriptionForTitle’ property is correct, and for 'AutoUpGradeEnable' property, the current behavior that missing the description is by design following RussKie's comments.
![IssueVerificationUpdate](https://user-images.githubusercontent.com/38325459/95647963-4e854c00-0b06-11eb-99ab-9d89c2f86728.PNG)
