### ISSUE TITLE
Default values are not shown after setting SelectedObject property for PropertyGird control 

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/winforms#3580]
* .NET SDK Version: 
5.0.100-preview.8.20363.2

* Have you experienced this same bug with .NET Framework?
No

**Problem description:**
Default values are not shown after setting SelectedObject property for PropertyGird control.
![image](https://user-images.githubusercontent.com/54019172/87515885-190bc680-c6af-11ea-9c7f-f8a784a11429.png)

**Expected behavior:**
After setting the SelectedObject property for the PropertyGird control, it should display correct default values.
![image](https://user-images.githubusercontent.com/54019172/87515918-26c14c00-c6af-11ea-894f-815622d329c3.png)
**More info:**
1.	This is a regression issue,  and it can repro from 5.0.100-preview.8.20360.10 to latest .NET SDK, it cannot repro on .Net Core 5.0.100-preview.8.20359.5, below is the the version number of System.Windows.Forms.dll in 5.0.100-preview.8.20359.5:
![image](https://user-images.githubusercontent.com/54019172/87527238-69d6eb80-c6be-11ea-9953-e1ab724b7e8e.png)

2.	This issue cannot repro with .NET Core 3.1.
3.	This issue also occurs in design time.
![image](https://user-images.githubusercontent.com/54019172/87516035-54a69080-c6af-11ea-8554-2b5fbefc74ba.png)

**Minimal repro:**
1.	Create a WinForms .Net Core application
2.	Add a PropertyGird control to Form
3.	Press F4 to go to the Property Browser Window, set its SelectedObject property to Form1
4.	Build and run the application, observe the PropertyGrid

 Or 
1.	Extract the attached project and open it
[PropertyGirdDefaultValue.zip](https://github.com/dotnet/winforms/files/4923535/PropertyGirdDefaultValue.zip)
2.	Build and run this application, observe the PropertyGrid

**Comment by RussKie** [comment]
This is a regression introduced in https://github.com/dotnet/winforms/pull/3532 (e45b38a61c4adac3975c8d1b8b961843d70798b8).

**Comment by JeremyKuhne** [comment]
Investigating

**Comment by Ashley-Li** [comment]
Verified this issue with .Net 6.0.100-alpha.1.20420.20 from Master branch, this issue is fixed that after setting the SelectedObject property for the PropertyGird control, it can display correct default values.This issue cannot reproduce in design time.
![image](https://user-images.githubusercontent.com/56664234/90871123-6be03a00-e34f-11ea-8ad8-684edfdd3cad.png)
