### ISSUE TITLE
'File name' ComboBox in SaveFileDialog is truncated by default after clicking 'Hide Folders'

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#3581]
* .NET Core Version: 
5.0.100-preview.8.20363.2 from master branch

* Have you experienced this same bug with .NET Framework?: 
Yes

* More info: 
This is not a regression issue, can repro in .Net Core previous version and .Net framework

**Problem description:**
'File name' ComboBox in SaveFileDialog is truncated by default after clicking 'Hide Folders'. After resizing this dialog, truncation will be resolved. See following screenshot:
![image](https://user-images.githubusercontent.com/26474449/87520639-d4cff480-c6b5-11ea-8245-e2b9d41747b3.png)

**Expected behavior:**
No truncation in SaveFileDialog

**Minimal repro:**
1.	Create a Winforms .Net Core app
2.	Add a SaveFileDialog to the form designer
3.	Write one line code to show SaveFileDialog when running app
4.	Build and run this app
5.	In SaveFileDialog, click 'Hide Folders', and then observe 'File name' comboBox
 
Or 
1.	Extract following attached project and open it
[WindowsFormsApp20.zip](https://github.com/dotnet/winforms/files/4923791/WindowsFormsApp20.zip)
2.	Build and run this app, in SaveFileDialog, click 'Hide Folders', and then observe 'File name' comboBox

**Comment by Tanya-Solyanik** [comment]
This is a native dialog, this overlap repros in notepad as well:
![image](https://user-images.githubusercontent.com/15823268/87561306-56e9fa00-c671-11ea-8bf8-ef4ab7c4fa9d.png)

**Comment by RussKie** [comment]
@Olina-Zhang this is a Windows dialog, we don't own it. I suppose you can raise an AzDO ticket to the Windows team.
