### ISSUE TITLE
At times System.Windows.Forms.ToolStripDropDown.Show Method gives StackOverFlowException

### ISSUE THREAD

**Issue by PranavSah** [dotnet/winforms#3585]
.NET Framework : 4.6.2

**Problem description:**
When switching from one window to another using context menus it has come to my notice that most of the times the application crashes due to StackOverFlowException. On debugging the stack is filled with calls of "System.Windows.Forms.ToolStripDropDown.get_RightToLeft()". My ToolStripMenuItem is added to the ContextStrip of the form.

**Minimal repro:**
When switching from one window to another using context menus ("_The click event of the menuitems is linked to Reflection code that opens the other window._")

**Debugging and Analysis of Crash Dump**
Attached crash dump analysis report. Analysis done using WinDbg tool.  To my understanding something goes for a toss in ToolStripDropDown.cs Show(Control control, Point position) method while either setting Location or when calling ShowCore() method.
I have also tried setting Overflow  property of ToolStripMenuItem to  ToolStripItemOverflow.AsNeeded but of no use.

[CrashDumpAnalysis1.txt](https://github.com/dotnet/winforms/files/4926511/CrashDumpAnalysis1.txt)
[CrashDumpAnalysis2.txt](https://github.com/dotnet/winforms/files/4926512/CrashDumpAnalysis2.txt)

**Comment by RussKie** [comment]
Thank you for the report.
Can you please provide a simple repro?
