### ISSUE TITLE
[Accessibility] Keyboard tab focus is invisible and Keyboard shortcut key is unavailable to access any items in the Print preview dialog after pressing 'Enter' on any button (One page, Two Page...)

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#3598]
* .NET Core Version: 
.NET SDK 5.0.100-rc.1.20366.7

* Have you experienced this same bug with .NET Framework?: 
Yes

**More Info:**

1. This issue can also repro on Framework project.
2. There are 2 similar bugs: [1156779](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1156779), [1156785 ](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1156785)in VSO.

**Minimal repro:**
1. Extract “[WindowsFormsApp3.zip](https://github.com/dotnet/winforms/files/4936772/WindowsFormsApp3.zip)” and open it in VS.
2. Build and run the project.
3. Using Tab key to navigate to Preview button, then press Enter key to show Print preview dialog.
4. Using Tab key to navigate page button(One Page, Two Page...), then press Enter key.            
5. Try to use Tab key to navigate any items in the Print preview dialog.

**Expected behavior:**
Keyboard tab focus is visible and Keyboard shortcut key is available to access any items in the Print preview dialog.

**Actual behavior:**
Keyboard tab focus is invisible and Keyboard shortcut key is unavailable to access any items in the Print preview dialog.
![steps](https://user-images.githubusercontent.com/45864649/87767155-cd8f1f00-c84c-11ea-967c-f17039f88e81.gif)

**Comment by SergeySmirnov-Akvelon** [comment]
CTI approved

**Comment by merriemcgaw** [comment]
@RussKie if this one is ready, let's get it approved for RC2. This is a very isolated fix.

**Comment by Jessie-Zhang01** [comment]
Verified this issue with .Net SDK 5.0.100-rc.2.20459.18, this issue is fixed. The focus is still visible after pressing 'Enter' or 'Space' keyboard on all toolStripButtons in PrintPreviewDialog.
![steps](https://user-images.githubusercontent.com/45864649/92675840-e995d500-f352-11ea-8064-0c489d8d5d56.gif)
