### ISSUE TITLE
Application.Exit raises FormClosing and FormClosed events in wrong order for MDI application

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#3606]
* .NET Core Version: **Any**

* Have you experienced this same bug with .NET Framework?: **Yes**

**Problem description:**

In [docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.formclosing?view=netcore-3.1): 

> If the form is a multiple-document interface (MDI) parent form, the FormClosing events of all MDI child forms are raised before the MDI parent form's FormClosing event is raised. Likewise, the FormClosed events of all MDI child forms are raised before the FormClosed event of the MDI parent form is raised

But in `Application.Exit `those events raised in unpredictable order: https://github.com/dotnet/winforms/blob/a6a308fa452770caafca55ee4d8ac54d1ee1015d/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs#L872-L889

**Expected behavior:**
Events raised in correct order - first for MDI child windows and for MDI parent last. I think the fix is really simple.

-----------------------------

Also during this, it will be nice to eliminate `foreach` loop on `OpenForms (s_forms)` when rising `FormClosing`. To fix this old nasty behavior of `Application.Exit`: 

> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

when user puts some other forms opening / closing logic in form's `FormClosing` event. 
This behavior raises many questions:
[stackoverflow](https://www.google.com/search?q=%22Application.Exit%22+System.InvalidOperationException:+Collection+was+modified;+enumeration+operation+may+not+execute.+site:stackoverflow.com&newwindow=1&sxsrf=APwXEdf2lCCdiQNRv6Re84vcbCT5L0C5cQ:1682167857550&sa=X&ved=2ahUKEwiZ7-fMw73-AhUbh_0HHSChDscQrQIoBHoECA8QBQ)
[msdn](https://www.google.com/search?q=%22Application.Exit%22+System.InvalidOperationException:+Collection+was+modified;+enumeration+operation+may+not+execute.+site:social.msdn.microsoft.com&newwindow=1&sxsrf=APwXEdf2lCCdiQNRv6Re84vcbCT5L0C5cQ:1682167857550&sa=X&ved=2ahUKEwiZ7-fMw73-AhUbh_0HHSChDscQrQIoBHoECAwQBQ)

**Comment by merriemcgaw** [comment]
Since this behavior is consistent with .NET Framework (and hence have customers depending on this unexpected behavior) we're going to mark it for future so we can take the time this needs for a significant investigation.

**Comment by kirsan31** [comment]
@merriemcgaw 

> Since this behavior is consistent with .NET Framework (and hence have customers depending on this unexpected behavior) we're going to mark it for future so we can take the time this needs for a significant investigation.

There are 2 problems here:
1. The **bug**, that `Application.Exit` currently cannot be used in most of MDI apps. And I think no customers can depend on it. This bug can be easily fixed (see below).
2. _Behavior_ that users can't  use `Application.Exit` when they are have some forms closing/opening code in `FormClosing`. And this is other story. I'm not even sure if it's worth taking on this ...

The bug can be fixed for example like this:
```cs
foreach (Form f in s_forms.OrderBy( form => form.IsMdiContainer )) // MdiContainer (if any) will be last
{
    if (f.RaiseFormClosingOnAppExit())
    {
        // A form refused to close
        if (e != null)
        {
            e.Cancel = true;
        }
        return;
    }
}

int i = 1;
while (s_forms.Count > 0)
{
    if (s_forms.Count > 1)
    {
        if (!s_forms[s_forms.Count - i].IsMdiContainer)                        
            s_forms[s_forms.Count - i].RaiseFormClosedOnAppExit(); // OnFormClosed removes the form from the FormCollection.
        else // only 1 MdiContainer per App - skip it
            i = 2; // skipping mdiContainer on further steps
    }
    else
        s_forms[0].RaiseFormClosedOnAppExit();
}
```

- MDI apps now can safely use `Application.Exit`.
- No changes for non MDI apps.

**Comment by merriemcgaw** [comment]
Given that we're at the very end of .NET 5, and this is the behavior (bad as it is) in .NET Framework, I think we'll leave this in the future bucket. We can pick it back up in 6 and do some deeper analysis of any side effects. Thanks!
