### ISSUE TITLE
Add template for WinForms Control Library

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#3608]
* .NET Core Version: 
.NET 5.0

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

In .NET Framework we had a VS template for WinForms Control Library, but in Core we have to modify the class library project file to create a control library.

WinForms Control Library is simply a Class Library with a reference to Winforms added by default. So to create it you can just create a Class Library from VS template and add `<UseWinforms>true</UseWinforms>` in the project file.

**Expected behavior:**
Add new project in VS:
![image](https://user-images.githubusercontent.com/15823268/87967003-001a6100-ca73-11ea-8209-bf8202d04c9f.png)

**Comment by Zheng-Li01** [comment]
@TanayParikh, @RussKie, verified the issue with latest .NET SDK 5.0.100-rc.1-20426.12 . for now the  Winforms Control Library(Core) templated can be found & created using CLI, however, still can't find the template in the Visual Studio.
if it is expected for now?
In addition, find a new issue related  Winforms Control Library(Core) project, have filed a new issue [3790 ](https://github.com/dotnet/winforms/issues/3790)to track it.
![Update](https://user-images.githubusercontent.com/38325459/91417269-1d68f900-e883-11ea-9c05-085d6f869ea1.PNG)
