### ISSUE TITLE
NativeWindow depends on WndProc delegates functioning during finalization

### ISSUE THREAD

**Issue by madewokherd** [dotnet/winforms#3610]
This is an issue I found in Wine Mono while running regression tests, which might theoretically affect .NET Core as well. I don't know for sure if it does, but I wanted to let you know so you can review it.

Wine Mono uses a fork of .NET Core winforms running under Mono. When I most recently merged upstream Mono, I found that it introduced crashes running MonoTests.System.Windows.Forms.TimerTest from Mono's unit tests. This happens when the NativeWindow class is finalized. It turns out that when the _windowProc delegate is only referenced by objects that are being finalized, calling it from native code can crash, or it can result in the instance method being called with this == NULL.

I don't know if there's an easy way to run this test in .NET Core, I've only built it to run in .NET Framework.

I am working around this by ensuring that any active WndProc delegates have a static reference to them. That change is https://github.com/madewokherd/winforms/commit/a0bc4ebd64afbac01116a8dee0551250fc56202b but I didn't write it with the intention of sending it upstream.

Does the .NET Core runtime provide the needed guarantees that a delegate will function while it is referenced by a cycle that includes objects being finalized? If not, then you should ensure there is a live reference to all WNDPROC objects for as long as they are required by a user32 window object.

**Comment by hughbe** [comment]
Can you share how you are running .NET Core winforms on wine? I've been trying and trying but haven't managed to figure it out!

Major stump is that I can't seem to build dotnet/winforms as can't get powershell working on wine

**Comment by madewokherd** [comment]
As far as I know, .NET Core runs just fine on Wine, it just doesn't build there. I am not building or running .NET Core on Wine.

I'm running a modified version of dotnet/winforms with its own build system, and a modified version of the Mono runtime, as part of https://github.com/madewokherd/wine-mono.

**Comment by weltkante** [comment]
How would a finalizable object prevent finalization of delegates? Sounds like a bug in the mono runtime, otherwise those callback-delegates would be inherently unsafe and always would have to be put into static collections, which feels like a design flaw.

I don't have in depth knowledge of the runtime specs and winforms repo is probably the wrong place to clarify this, but to me it sounds like callback delegates can't be implemented with finalization and need special runtime magic to survive other special scenarios like long weak references and resurrection. Mono using plain finalization rules to implement callback delegates doesn't sound right.

**Comment by madewokherd** [comment]
I don't know the details, but I was told by mono devs that yes, they would have to be put in static collections.

**Comment by weltkante** [comment]
> I don't know the details

Its the normal rule of finalizable objects. Managed objects cannot depend on order of finalization, the GC collects all collectible objects as one group and if they are finalizable executes their finalizer in arbitrary order. It sounds like mono revokes callback delegates under these finalizer rules, so depending on finalization order it may crash.

That said, it probably is worth inspecting your crashes closer, as in fact WinForms timers [are already rooted](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs#L119) while enabled. (Not properly disposing/disabling timers has been the cause of memory leaks for me in in the past so I know they are definitely rooted while running, and timers that aren't running have their handle destroyed so really shouldn't receive any callbacks.)

**Comment by madewokherd** [comment]
Just looking at the code you linked, they would need to be rooted for as long as the hwnd exists, not just when enabled. In the cross-thread case, the hwnd is destroyed via PostMessage, so StopTimer may return and destroy the root while the hwnd still exists.

**Comment by JeremyKuhne** [comment]
As mentioned, finalization order is never guaranteed so there isn't much we can do without some significant refactoring. We'd be reluctant to take a large change here for a non-Windows scenario.
