### ISSUE TITLE
Tracking issue: remove calls to obsoleted CAS and CER APIs

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/winforms#3612]
In https://github.com/dotnet/winforms/pull/3611, a bunch of calls to CAS and CER APIs were surrounded by pragmas to suppress newly-introduced warnings in 5.0.

The CAS and CER infrastructure does not exist in .NET 5.0. Hence the obsoletions. :)
Since WinForms targets 5.0 exclusively, these call sites should be removed rather than suppressed.

**Comment by weltkante** [comment]
Just to be clear, the linked PR also suppressed warnings on BinaryFormatter. Those probably need to remain suppressed and cannot be removed until a replacement strategy has been presented and implemented (see https://github.com/dotnet/designs/pull/141/files)

**Comment by JeremyKuhne** [comment]
The CAS stuff was removed in #3972.
