### ISSUE TITLE
Designer loading should not fail due to NuGet Package Manager dropdown being set to an internal feed

### ISSUE THREAD

**Issue by jnm2** [dotnet/winforms#3620]
If the NuGet Package Manager UI happens to have the 'Package source' dropdown set to anything other than nuget.org or All, and you try to open a designer that depends on types defined in packages.

![image](https://user-images.githubusercontent.com/8040367/88113523-ec105580-cb7f-11ea-9f17-a3549ee360a0.png)

This is in spite of the fact that building the solution succeeds. Given that building succeeds, there should be no reason that the designer can't load the types.

If you open up the package manager UI and switch the dropdown, then try to reopen the designer, it works.

The 'Package source' option gets reset all the time due to git cleans or fresh clones. If you open a project in a repository that has a nuget.config file, the package source defaults to the first entry in the repo's nuget.config file. This is usually not the nuget.org feed.

This is .NET Core SDK 3.1.302 and VS 16.6.5. I'll get you a repro if that is helpful.

**Comment by merriemcgaw** [comment]
@Vino-Wang can you see if you can repro this without the designer. @RussKie has seen it in general. We can then file an issue for VS Nuget Package Manger team.

**Comment by merriemcgaw** [comment]
@jnm2 - if you could file a VS feedback ticket we will be able to investigate and route to the correct team more quickly. We are able to get your diagnostic information and can find out much more about the problem that way.

**Comment by Vino-Wang** [comment]
> @Vino-Wang can you see if you can repro this without the designer. 

@merriemcgaw Unable to reproduce it using this NuGet Packages: [139719-samplenugetandproject (1).zip](https://github.com/dotnet/winforms/files/4970350/139719-samplenugetandproject.1.zip), the form designer loaded successfully by following steps:
1.	Go to Tools | Options | NuGet Package Manager | Package Source to add this NuGet package source.
2.	Then install the controls under Browse tab.
3.	Build and drag the new control to form.
4.	Change the Package source to the new added packages.
5.	Reopen the form designer again.
![NotRepro_NugetPackage](https://user-images.githubusercontent.com/18568603/88364555-dab08e80-cdb5-11ea-86b2-304e221fb5db.gif)

In addition, I see the ‘DevExpress.XtraEditors.XtraForm’ information mentioned in the error message, is this problem with a specific NuGet package?

**Comment by RussKie** [comment]
I vaguely remember having similar woes with VS and Package Manager, but not related to the Designer. Few years ago when I worked on ASP.NET and ASP.NET Core projects restoring packages at the solution level (i.e. right click->Restore on a solution in the Solution Explorer) could fail if the Package Manager would have other than "all" feed selected despite the solution having its nuget.config present.

**Comment by jnm2** [comment]
I'm sorry. It was happening the evening I filed this, but now I can't repro the designer error. Instead, I get an "Intellisense is loading... you can continue working" message for a bit, than an "opening file" popup window, then the designer opens properly.

I wonder if it could be a timing issue. Sometimes our internal feeds are slow. If it comes back, I will fill a VS feedback item as soon as I see it.

**Comment by jnm2** [comment]
It's also worth pointing out that I'm not reproing https://github.com/dotnet/winforms/issues/3619 in any of our projects now either, even though I'm on the same commit that reproduced it a few days ago. It was in search of a fix for https://github.com/dotnet/winforms/issues/3619 that I encountered this issue. (Think I had pasted `<Compile Update="**\*View.cs" SubType="Form" />` as a quick workaround to force the designer to show.)

**Comment by jnm2** [comment]
Never mind, just reproduced it. Guess it just takes a bit more patience. Filing feedback item.

![image](https://user-images.githubusercontent.com/8040367/88406355-9239a680-cd9e-11ea-9be0-7d15155e83a6.png)

**Comment by jnm2** [comment]
Not actually sure if the last screenshot was the same issue. I built the solution and now get this:
![image](https://user-images.githubusercontent.com/8040367/88406850-3de2f680-cd9f-11ea-8a2d-60ba4c582519.png)

At least #3619 is reproing at this point, so the only forms with icons in Solution Explorer are the ones I'm manually setting SubType on.
