### ISSUE TITLE
Clean up VB Template feedback

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#3622]
We need to do a cleanup of our VB Template to address the open feedback in #3352

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann is this on track for RC2? If not, we may need to move into a later release as a clean up item.

**Comment by KlausLoeffelmann** [comment]
Well, this one is in, so I am closing this. I will add another PR today, with the new template project (not: project template), which will replace the previous one. That new one has already been (peer) reviewed by @JeremyKuhne, @KathleenDollard and @RussKie . I will close this, after I link this to the new PR.

**Comment by KlausLoeffelmann** [comment]
Replaced by #3893. Closing.
