### ISSUE TITLE
[Regression] CheckedListBox selected item has an incorrect color

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#3628]
* Regression from a6a308fa452770caafca55ee4d8ac54d1ee1015d
* .NET Core Version: 5.0
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
- If to select some CheckedListBox item it will have an incorrect background color.
![image](https://user-images.githubusercontent.com/49272759/88175999-5207e600-cc2f-11ea-92de-6ec9e61e3c35.png)

**Expected behavior:**
- CheckedListBox selected item has a color as before
![image](https://user-images.githubusercontent.com/49272759/88176472-00139000-cc30-11ea-978f-bf3e2f8fe926.png)

**Minimal repro:**
- Create a .Net 5.0 app using the latest master branch dlls (Or just run WinformsControlsTest project - MultipleControls form)
- Add a CheckedListBox with items to the form
- Run the app and select some item

**Comment by vladimir-krestov** [comment]
@JeremyKuhne, could you please take a look at this regression bug? It was added in a6a308fa452770caafca55ee4d8ac54d1ee1015d (PR #3350 
I think you know how to fix it. Could you please assign it to you and fix it?

@Vino-Wang, could you please test it using the latest master branch dlls if it possible and approve this bug?

FYI: @SergeySmirnov-Akvelon, @RussKie

**Comment by JeremyKuhne** [comment]
I'll fix it shortly

**Comment by vladimir-krestov** [comment]
Thank you so much for the hotfix. It works well now. 👍

**Comment by Jessie-Zhang01** [comment]
Verified this issue with .Net 6.0.100-alpha.1.20420.20 from Master branch, this issue is fixed. CheckedListBox selected item has a color as before.
![image](https://user-images.githubusercontent.com/45864649/90848744-3152bd80-e3a0-11ea-8b20-8b6193f87eda.png)
