### ISSUE TITLE
RichTextBox no longer renders links

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#3632]
* .NET Core Version: 
   - .NET Core 3.1 - doesn't
   - .NET 5.0 RC1 - doesn't

* Have you experienced this same bug with .NET Framework?: 
    - .NET 4.6.1 - **works**
    - .NET 4.7.2+ - doesn't

This is blocking a [migration of Git Extensions to .NET Core / .NET 5.0](https://github.com/gitextensions/gitextensions/pull/7162).

**Problem description:**

`RichTextBox` control doesn't respond to `EM_SETCHARFORMAT` with `lParam: SCF_SELECTION, wParam: CHARFORMAT2W(dwMask: CFM.LINK, dwEffects: CFE.LINK)`.

The text put in the RTB is as follows:
```
"Related links: <a href='https://github.com/gitextensions/gitextensions/commit/2c0698453e29dc243bfbc817ef74581c0cbfc830'>View on GitHub</a>, <a href='https://github.com/gitextensions/gitextensions/issues/8333'>Issue 8333</a>"
```

* .NET 4.6.1:
    ![image](https://user-images.githubusercontent.com/4403806/88283735-5e736800-cd2f-11ea-9ab4-6453970293a5.png)
* .NET 4.7.2:
    ![image](https://user-images.githubusercontent.com/4403806/88283770-6f23de00-cd2f-11ea-8f2c-4e88eda6a76a.png)
* .NET 5.0:
    ![image](https://user-images.githubusercontent.com/4403806/88283831-911d6080-cd2f-11ea-88f8-c586d3422438.png)

As pointed in https://github.com/dotnet/winforms/issues/3399#issuecomment-661024452 in .NET 4.7.2 there was a change of version of the underlying native control (i.e. RichEdit 4.1 from Msftedit.dll), which is probably the underlying reason of the problem.

**Minimal repro:**

[ge-rtb-links.zip](https://github.com/dotnet/winforms/files/4965681/ge-rtb-links.zip)

**Comment by merriemcgaw** [comment]
Adoption Blocker for GitExtensions, because they depend on links in RichEdit. Can we provide an option to go back to the old one? Or we may need to update how we interact.

**Comment by merriemcgaw** [comment]
@dreddy-work - can you reach out to your contact from back when we switched?

**Comment by RussKie** [comment]
Tested it locally, and unfortunately #3726 doesn't fix the issue.

**Comment by kirsan31** [comment]
Just to note, that this is [blocker](https://github.com/NLog/NLog.Windows.Forms/pull/42#issuecomment-521434661) for NLog.Windows.Forms for moving from .Net Framework too.

**Comment by weltkante** [comment]
I've executed the repro in the original issue in .NET 4.6.1 and it renders links. I saved the RTF markup to a file and wordpad does not render the links, so I would conclude that the RTF generated is nonstandard and not supported by modern Windows. In this case there is nothing WinForms can do, the code to generate the RTF should conform to the RTF specification.

In fact, I strongly suspect the RTF generated was relying on unspecified behavior, as it looks nothing like the [officially documented](https://docs.microsoft.com/en-us/archive/blogs/murrays/richedit-friendly-name-hyperlinks) format for RTF hyperlinks. When I generate the hyperlink in the documented format it works in all versions I tested (.NET 4.6.1, .NET 4.7.2, .NET Core 3.1, .NET 5)

**Comment by weltkante** [comment]
While looking into NLog.Windows.Forms I noticed they use the same RTF trickery to hide a URL in hidden text and mark everything as a link - with the difference that it actually still works for them after updating their code to .NET 5 (their problem was another bug that already has been fixed)

Its still unclear what the difference is to the repro code from this PR, I'll dig a bit deeper. I'd still recommend just using the official hyperlink markup, but this does cause problems with the LinkClicked handler because it can no longer retrieve the URL of the clicked hyperlink. I'll open a separate issue about the LinkClicked event because its unrelated to the rendering of links discussed here.

**Comment by weltkante** [comment]
You apparently have to set `RichTextBox.DetectUrls = false;` to be able to set links at runtime via `CFE_LINK` interop. Setting this property makes the repro in the original post work. Opening a separate issue for the LinkClicked handler not seeing hidden text. I think this issue can be closed?

**Comment by RussKie** [comment]
Thank you so much!

**Comment by Zheng-Li01** [comment]
After setting the RichTextBox.DetectUrls = false that RichTextBox  can detect the url for now, please see below screenshot.
![Update3632](https://user-images.githubusercontent.com/38325459/104533717-e5a1f880-564d-11eb-805a-49fc6f537b00.PNG)
