### ISSUE TITLE
Periodic NRE in GdiCache.GetHFONT method

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#3634]
* .NET Core Version: 5.0
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
- We can get `NullReferenceException` sometimes (about 10-15% chance) in `GdiCache.GetHFONT` method. (**`s_fontCache`** is null)
![image](https://user-images.githubusercontent.com/49272759/88325491-de003780-cd2d-11ea-876f-a9937edd0539.png)

- It seems this method is called before **`s_fontCache`** initializing in `ScreenDcCache`.
![image](https://user-images.githubusercontent.com/49272759/88325715-05ef9b00-cd2e-11ea-946b-92aacad2de0a.png)

**Expected behavior:**
- There are no NREs

**Minimal repro:**
- Run Inspect (The issue reproduces only if inspect is already running)
- Run the internal WindowsControlsTest project
- Get NRE sometimes before loading the main test form

**Comment by JeremyKuhne** [comment]
Looking into this. Might be some weirdness about hitting this from separate threads.

**Comment by weltkante** [comment]
You probably figured this out already yourself, but `ScreenDcCache` does a reentrant wait, allowing other random window messages to arrive and processed while still being in the static constructor.

Maybe you can do something simliar to vs-threading which temporarily switches the SC for wait operations to [an implementation](https://github.com/microsoft/vs-threading/blob/master/src/Microsoft.VisualStudio.Threading/NoMessagePumpSyncContext.cs) declaring that it wants to be notified for blocking waits and then performs a non-pumping wait.

**Comment by RussKie** [comment]
@vladimir-krestov @JeremyKuhne was this fixed?

**Comment by vladimir-krestov** [comment]
@RussKie, I can't reproduce this bug anymore. 
So we can close this bug as not repro
@JeremyKuhne FYI

**Comment by weltkante** [comment]
I think this is because the threaded ScreenDcCache was removed? At least the file I linked above as causing the bug doesn't exist anymore.

**Comment by JeremyKuhne** [comment]
@weltkante I moved it to a thread local for this release. I'll deal with the underlying issue in the next version.
