### ISSUE TITLE
Properties window is blank

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#3636]
* .NET Core Version: 
5.0.100-rc.1.20373.1

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Properties window is blank, we cannot see any properties for form or added controls, and no properties and events toolbar in Properties window.
**This is a regression issue**. It cannot repro .Net 5.0 SDK build: 5.0.100-rc.1.20371.1
![image](https://user-images.githubusercontent.com/26474449/88374127-cd060380-cdcb-11ea-92a4-3030a4fb1db2.png)

**Expected behavior:**
All properties and events are in Properties window
![image](https://user-images.githubusercontent.com/26474449/88374167-de4f1000-cdcb-11ea-8eba-427f9de52512.png)

**Minimal repro:**
The repro step is very simple, just create an empty app 
1.	Create a WinForms .Net Core application
2.	Focus on Form designer, and go to Properties window or press F4
3.	Observe Properties window

**Comment by RussKie** [comment]
This looks like a duplicate of https://github.com/dotnet/winforms/issues/3580

**Comment by Olina-Zhang** [comment]
> This looks like a duplicate of #3580

This issue just repro today 5.0 build, not repro those builds yesterday and last week.

**Comment by JeremyKuhne** [comment]
Should investigate with #3639 in the designer repo.

**Comment by Tanya-Solyanik** [comment]
Looks like TypeEditor caches don't initialize in the designer.
![image](https://user-images.githubusercontent.com/15823268/88453381-33fed900-ce1b-11ea-9e19-69443bfb31a7.png)

**Comment by Olina-Zhang** [comment]
Verified in the latest .Net 5.0 SDK build: 5.0.100-rc.1.20377.7 today, this issue can't repro.
![image](https://user-images.githubusercontent.com/26474449/88625217-e57f6200-d0da-11ea-9b9b-cbc4aa367bde.png)
Here is the version of System.Windows.Forms.dll:
![image](https://user-images.githubusercontent.com/26474449/88625330-211a2c00-d0db-11ea-86d3-bbe0fd3496ff.png)

**Comment by Olina-Zhang** [comment]
Checked in today's new build, it cannot repro. Closing this issue now.
