### ISSUE TITLE
Some properties are grey with black rectangle in Properties window after choosing more controls

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#3639]
* .NET Core Version: 
5.0.100-rc.1.20373.1

* Have you experienced this same bug with .NET Framework?: 
 No

**Problem description:**
Some properties are grey with black rectangle in Properties window after choosing more controls. Please see following screenshot:
**This is a regression issue.** It cannot repro .Net 5.0 SDK build: 5.0.100-rc.1.20371.1
![image](https://user-images.githubusercontent.com/26474449/88373072-bc548e00-cdc9-11ea-8df2-6b462c448218.png)

**Expected behavior:**
They are enabled properties after choosing more controls. Please see following screenshot:
![image](https://user-images.githubusercontent.com/26474449/88373191-f887ee80-cdc9-11ea-8299-9eb365155e21.png)

**Minimal repro:**
1. Create a WinForms .Net Core application
2. Add a button and a checkedListBox to form designer
3. Choose these 2 controls, then go to VS properties window to observe all properties
If properties window is blank, close it and re-open

**Comment by RussKie** [comment]
> It cannot repro .Net 5.0 SDK build: 5.0.100-rc.1.20371.1

@Olina-Zhang can you please share the version of System.Windows.Forms.dll as well, so we can bisect and find the offending commit?

**Comment by Olina-Zhang** [comment]
@RussKie  See following screenshot:
![image](https://user-images.githubusercontent.com/26474449/88374551-7baa4400-cdcc-11ea-947d-724bfa3c4aa9.png)

**Comment by JeremyKuhne** [comment]
I did change a lot of private fields, but I don't think that would impact this? Should move to the designer repo to investigate further.

**Comment by Tanya-Solyanik** [comment]
The look of the property browser window suggests this is a bug in the designer, but the fact that it repros only when we change the Core SDK version suggests s.w.f.dll as the cause. Cool bug!

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang , I'm not getting PropertyBrowser loaded for any control on the combination of the latest SDK and latest designer from our master + Int preview Version 16.8.0 Preview 1.0 [30324.13.master
![image](https://user-images.githubusercontent.com/15823268/88453299-8390d500-ce1a-11ea-828d-a7336e12200a.png)

What version of VS did you run?

**Comment by Olina-Zhang** [comment]
Latest 16.8 preview 1 master build or 16.7 preview 6 test pass build

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Tanya-Solyanik** [comment]
On machine with the new Core 5 SDK, I don't have the S.W.F.Editors.dll façade installed. I have it on the machine with an older SDK  that works.

**Comment by Olina-Zhang** [comment]
Verified in the latest .Net 5.0 SDK build: 5.0.100-rc.1.20377.7 , this issue can't repro.
![image](https://user-images.githubusercontent.com/26474449/88625391-3ee79100-d0db-11ea-9319-dafcfcc8cb54.png)

Here is the version of System.Windows.Forms.dll:
![image](https://user-images.githubusercontent.com/26474449/88625344-25dee000-d0db-11ea-821e-e3a6e153a122.png)

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang - I'm curious, why did not you close this issue?

**Comment by Olina-Zhang** [comment]
I am not sure if anyone had pull request or did some change for it. Didn't see any update in this issue. And we want to check several builds to verify, then close it.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by RussKie** [comment]
@JeremyKuhne has been iterating over the responsible/affected code, so likely he has fixed it without targeting this issue specifically.

**Comment by Olina-Zhang** [comment]
Checked in today's new build, it cannot repro. Closing this issue now.
