### ISSUE TITLE
ListViewSubItemCollection.Add(null) throws NRE should throw ANE

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#364]

**Comment by KlausLoeffelmann** [comment]
Doesn't this contradict #363? 
Or am I missing something?

**Comment by hughbe** [comment]
My bad - I incorrectly typed out the description

**Comment by zsd4yr** [comment]
https://github.com/dotnet/winforms/issues/392#issuecomment-459063843

**Comment by zsd4yr** [comment]
approved
