### ISSUE TITLE
TextBox.PlaceholderText uses BackColor even when TextBox.Enabled = false

### ISSUE THREAD

**Issue by DragoonAethis** [dotnet/winforms#3642]
* .NET Core Version: 3.1.6
* Have you experienced this same bug with .NET Framework?: No (PlaceholderText not available)
* Visual Studio version: 2019 16.7 Preview 5

**Problem description:**

When PlaceholderText is set and displayed, it's always drawn with the BackColor as the background, regardless of the Enabled value. This causes minor graphical issues as presented below.

![image](https://user-images.githubusercontent.com/1546665/88445020-56472580-ce20-11ea-8c81-ef1983395eff.png)

The issue is most likely [here](https://github.com/dotnet/winforms/blob/b12ba3357e6f2246b5af3c506b8b6e05b8ce1cae/src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs#L900) - renderer for the Text itself [draws the appropriate background color first, then the text without any background](https://github.com/dotnet/winforms/blob/b12ba3357e6f2246b5af3c506b8b6e05b8ce1cae/src/System.Windows.Forms/src/System/Windows/Forms/TextBoxRenderer.cs#L91).

**Expected behavior:**

When PlaceholderText is set and TextBox is disabled, the background color is rendered properly across the entire control.

**Minimal repro:**

```csharp
using System;
using System.Drawing;
using System.Windows.Forms;

namespace BrokenPlaceholder {
    class PlaceholderForm : Form {
        private TextBox textBox1;
        private TextBox textBox2;
        private TextBox textBox3;

        public PlaceholderForm() {
            SuspendLayout();

            textBox1 = new TextBox {
                Name = "textBox1",
                Size = new Size(226, 23),
                Location = new Point(33, 25),
                Text = "Some perfectly fine Text"
            };

            textBox2 = new TextBox {
                Name = "textBox2",
                Size = new Size(226, 23),
                Location = new Point(33, 54),
                PlaceholderText = "PlaceholderText"
            };

            textBox3 = new TextBox {
                Name = "textBox3",
                Size = new Size(226, 23),
                Location = new Point(33, 83),
                PlaceholderText = "Disabled PlaceholderText",
                Enabled = false
            };

            ClientSize = new Size(293, 138);
            Controls.Add(this.textBox1);
            Controls.Add(this.textBox2);
            Controls.Add(this.textBox3);
            Name = "PlaceholderForm";
            Text = "PlaceholderForm";
            ResumeLayout(false);

            PerformLayout();
        }
    }

    static class Program {
        [STAThread]
        static void Main() {
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new PlaceholderForm());
        }
    }
}
```

**Comment by yvz5** [comment]
@RussKie  may I get this issue as well ?

**Comment by RussKie** [comment]
Sure!
Holler if you get stuck

**Comment by Zheng-Li01** [comment]
Verified the issue with latest NET SDK 6.0.100-alpha.1.20557.2, the issue has been fixed that TextBox.PlaceholderText display normal when TextBox.Enabled = false. see below screenshot.
![Update](https://user-images.githubusercontent.com/38325459/98516121-0abd6800-22a7-11eb-8b78-6f890351464b.PNG)
