### ISSUE TITLE
The information in the warning dialog is different from the .Net Framework when the EnableRaisingEvents property of FileSystemWatcher is changed to true

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#3649]
* .NET Core Version: 
.Net 5.0.100-rc.1.20376.1 from 5.0 master branch

* Have you experienced this same bug with .NET Framework?: 
No

**Minimal repro:**

1. Open the attached ‘[WindowsFormsApp5.zip](https://github.com/dotnet/winforms/files/4980950/WindowsFormsApp5.zip)’ application in VS, then build and run it.
2. Change the EnableRaisingEvents property to true.
3. A warning dialog will pop-up, then click the "Details" button.
4. Observe the information in the details.
5. Click the "OK" button and observe whether the EnableRaisingEvents property is changed to true.

**Expected behavior:**
In step4, the information in the warning dialog should be the same as .Net Framework.
In step5, the EnableRaisingEvents property should be changed to true.

**Actual behavior:**
In step4, the information in the warning dialog is different from the .Net Framework.
![image](https://user-images.githubusercontent.com/45864649/88522240-abee1e80-d028-11ea-8641-a50e8824cb28.png)
In step5, the EnableRaisingEvents property has not been changed to true.
![Issue1](https://user-images.githubusercontent.com/45864649/88523335-5c105700-d02a-11ea-872f-abcd379a77df.gif)

Framework project: [WindowsFormsApp6.zip](https://github.com/dotnet/winforms/files/4980954/WindowsFormsApp6.zip)

**Comment by RussKie** [comment]
`System.IO.FileSystemWatcher` is part of the BCL, we don't own it. The error message is also supplied by the BCL.

@JeremyKuhne may provide additional information.
