### ISSUE TITLE
No warning dialog pops up when changing the value of the NotifyFilter property of FileSystemWatcher

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#3650]
* .NET Core Version: 
.Net 5.0.100-rc.1.20376.1 from 5.0 master branch

* Have you experienced this same bug with .NET Framework?: 
No

**More Info:**
In the framework project, change the value of the NotifyFilter property from the Property browser, no warning box pops up.
Framework project: [WindowsFormsApp6.zip](https://github.com/dotnet/winforms/files/4981019/WindowsFormsApp6.zip)

**Minimal repro:**

1. Open the attached ‘[WindowsFormsApp5.zip](https://github.com/dotnet/winforms/files/4981020/WindowsFormsApp5.zip)’ application in VS, then build and run it.
2. Change the NotifyFilter property to FileName.

**Expected behavior:**
A warning dialog should pop up when changing the value of the NotifyFilter property.
The following screenshot is from the .Net framework PropertyGrid:
![image](https://user-images.githubusercontent.com/45864649/88524187-99291900-d02b-11ea-89bb-9e00cbcdc42c.png)

**Actual behavior:**
No warning dialog pop up when changing the value of the NotifyFilter property.
![Issue2](https://user-images.githubusercontent.com/45864649/88524093-80b8fe80-d02b-11ea-9482-ccd10967df57.gif)

**Comment by RussKie** [comment]
@KlausLoeffelmann does this ring any bells?

**Comment by RussKie** [comment]
@Jessie-Zhang01 could you please revalidate in the latest dotnet/runtime + dotnet/winforms builds?

**Comment by Jessie-Zhang01** [comment]
@RussKie we try to build those dlls from dotnet/runtime + dotnet/winforms, but it failed when building the project. So could you provide those dlls for us? And we will also continue to try it again.

**Comment by Jessie-Zhang01** [comment]
@RussKie Verified this issue with latest .Net SDK 6.0.100-alpha.1.20455.1 + build [dlls ](\\mlangfs1\public\Winforms\v-ruizha\Private\3650)from dotnet/winforms, this issue still reproduce. No warning dialog pop up when changing the value of the NotifyFilter property.

In addition, dotnet/runtime still fails to build, following is failed information:
![image](https://user-images.githubusercontent.com/45864649/92361864-a7d21800-f121-11ea-96e4-f0e463955465.png)
![image](https://user-images.githubusercontent.com/45864649/92361809-9426b180-f121-11ea-8550-d4136dd4c679.png)

**Comment by RussKie** [comment]
> In addition, dotnet/runtime still fails to build, following is failed information:

Do you have python installed?

**Comment by Jessie-Zhang01** [comment]
@RussKie building dotnet/runtime repo still failed after installed python, but we found that System.IO.FileSystem.Watcher.dll had been updated in the corresponding path, so we tested with the generated [dll](https://github.com/dotnet/winforms/files/5192392/dll.zip), this issue still repro.

**Comment by RussKie** [comment]
@Jessie-Zhang01 can you please check whether 3.1 is affected too?

**Comment by RussKie** [comment]
From a high level this looks like this related to changed in System.IO in .NET 2.1, and the current behaviour is now by design.

NB: @JeremyKuhne has more info, because he is the one who did this :D
https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek
