### ISSUE TITLE
Lexicographical order designer code

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#3652]
**Is your feature request related to a problem? Please describe.**
Historically winforms designer code has been a bit of a pain when merging code changes. The ordering often seems random, although there is basic ordering to make sure dependencies work.

The current fix to avoid merge conflicts is to make sure developers don't make changes to designer files unnecessarily, and to make sure no body is working on forms/controls at the same time. This is obviously really unproductive.

**Describe the solution you'd like and alternatives you've considered**
My suggestion is to add more smarts to the designer to make sure the ordering is consistent, lexicographical order seems the most appropriate. Obviously this will need to take into account dependencies as it currently does, but hopefully the random changes are reduce. Especially when opening the designer to "view" the form and making no changes.

Other changes to reduce variability in generated code would also be welcome.

**Will this feature affect UI controls?**
Yes.

**Comment by elachlan** [comment]
It would be nice to have similar ordering on licx files as well. I wasn't sure if this is the right place to raise it.

**Comment by weltkante** [comment]
> It would be nice to have similar ordering on licx files as well.

licx is no longer supported (in fact it was never ported to .NET Core). Last we were told they were working on a different way to implement licensed controls (#1462)

**Comment by elachlan** [comment]
Could someone point me to where I can find the code that generates the output designer code? I am happy to begin investigating. But there isn't much information on the role of each of the projects.

**Comment by weltkante** [comment]
Only the runtime is open sourced, designer and VS integration is closed source as far as I know.

**Comment by merriemcgaw** [comment]
@weltkante is correct, we haven't open sourced our designer code. That said, we take the issues filed here and get them copied into our internal repo so that we can track the issue there. I wouldn't expect a change like this right away though, we're still working on some other high priority work getting the designer to support .NET Core projects.

**Comment by elachlan** [comment]
> @weltkante is correct, we haven't open sourced our designer code. That said, we take the issues filed here and get them copied into our internal repo so that we can track the issue there. I wouldn't expect a change like this right away though, we're still working on some other high priority work getting the designer to support .NET Core projects.

Thanks for the explanation. Exciting times, I am looking forward to .NET 6 with Winforms.

**Comment by RussKie** [comment]
Thank you for the suggestion. We create a tracking issue in the designer repo, and it has sparked several team conversations, and we generally recognise the importance of this proposal.
Unfortunately the proposal is not immediately actionable, and there are no ETA of when this feature may land.
