### ISSUE TITLE
An exception dialog pops up after resized the PropertyGrid Control more one times

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#3662]
* .NET Core Version: 
.Net SDK 5.0.100-rc.1.20378.13

* Have you experienced this same bug with .NET Framework?: 
No

**More info:**
1. The issue is a **regression** issue, can't repro on 5.0.100-rc.1.20377.3 build.

**Minimal repro:**
1. Create a .NET Core winforms application with a PropertyGrid control.
2. Resize the propertyGrid1 control more one times.

**Expected behavior:**
The propertyGrid1 can be resized successfully.
 
**Actual behavior:**
An exception dialog pops up after resized the PropertyGrid Control more one times.
![Exception](https://user-images.githubusercontent.com/38325459/88777819-403bbb00-d1ba-11ea-86db-b606b9e09900.gif)
![Exception](https://user-images.githubusercontent.com/38325459/88777832-4467d880-d1ba-11ea-9357-881cbd00fe15.PNG)

**Comment by JeremyKuhne** [comment]
Hmm. I don't think this is actually out of memory- but clearly an error.  Looking.

**Comment by JeremyKuhne** [comment]
Yeah, if you call `Graphics.FromHdcInternal(IntPtr.Zero)`, this is what you get.

**Comment by JeremyKuhne** [comment]
It appears that WinFormsSurface.Designers.ControlDesigner.WmPaint is either passing an invalid HDC or one that GDI+ can't get the type for (via `GetDCType(hdc)`);

**Comment by JeremyKuhne** [comment]
I can't get  a repro for this. I added asserts in the debug build to check the handle type, which is the most likely scenario here. Call stacks would be most helpful if this is still happening.

Closing for now, please reactivate if you can still repro.

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .NET 5.0.100-rc2.20459.18 that the issue not repro for now.
![VerifyGitHubIssue](https://user-images.githubusercontent.com/38325459/92696545-9b95c700-f37c-11ea-8f7b-ad43bd3f4ee8.gif)
