### ISSUE TITLE
[Accessibility] The Name property must not include the element's control type for toolStripProgressBar

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#3680]
* .NET Core Version: 
5.0.100-rc.1.20379.16

* Have you experienced this same bug with .NET Framework?: 
 Yes
* Problem description:
Name property must not include the element's control type for toolStripProgressBar in ToolStrip and StatusStrip controls

**Minimal repro:**
1. Extract following attached app and open it in VS.
[WindowsFormsApp48.zip](https://github.com/dotnet/winforms/files/5004631/WindowsFormsApp48.zip)
2. Build and run the project.
3. Open Accessibility Insights For Windows tool, select focus on form and view result.

**Actual behavior:**
Get 2 errors for toolStripProgressBar in ToolStrip and StatusStrip controls
![image](https://user-images.githubusercontent.com/26474449/88992833-ebfa1d80-d316-11ea-9be8-20f52d517b25.png)
![image](https://user-images.githubusercontent.com/26474449/88992949-311e4f80-d317-11ea-907f-36e5586bdf70.png)

**Expected behavior:**
No error

**Comment by merriemcgaw** [comment]
@Olina-Zhang is the AccessibleName property available for this control? Can you set that in the sample app and see if that resolves the problem?

**Comment by Olina-Zhang** [comment]
@merriemcgaw Yes, it has. We can set it in sample app to resolve it. Updated this info in bug: **https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1159873**
![image](https://user-images.githubusercontent.com/26474449/93550575-4706d300-f99e-11ea-8598-e939603ae35d.png)
![image](https://user-images.githubusercontent.com/26474449/93550514-20e13300-f99e-11ea-85b7-18932fca2e01.png)
Do we keep this bug opening to update default name property or resolve it with custom  AccessibleName property by developer?

**Comment by merriemcgaw** [comment]
@Olina-Zhang please do that, it will close out another issue for us. Thanks so much!

**Comment by Olina-Zhang** [comment]
@merriemcgaw What about this Github issue?

**Comment by merriemcgaw** [comment]
If you've fixed the issue in the sample app, please do close this one. Thanks!

**Comment by Olina-Zhang** [comment]
> If you've fixed the issue in the sample app, please do close this one. Thanks!

Yes, we have updated the AccessibleName for toolStripProgressBar in sample app from GH winforms repo, so close this issue.

**Comment by vladimir-krestov** [comment]
@merriemcgaw, should we move this to "Done" in our project?

**Comment by merriemcgaw** [comment]
@Olina-Zhang has the underlying AzDO bug been closed?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang has the underlying AzDO bug been closed?

Yes, it is closed.
