### ISSUE TITLE
[Accessibility] An element of the given ControlType must support the Text pattern for PropertyGrid: Text tree items

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#3683]
* .NET Core Version: 
5.0.100-rc.1.20379.16

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
An element of the given ControlType must support the Text pattern for PropertyGrid: Text tree items

**Minimal repro:**
1. Extract following attached app and open it in VS.
[WindowsFormsApp50.zip](https://github.com/dotnet/winforms/files/5005553/WindowsFormsApp50.zip)

2. Build and run the project.
3. Open Accessibility Insights For Windows tool, select and focus on PropertyGrid control

**Actual behavior:**
An error is about PropertyGrid Text tree items: An element of the given ControlType must support the Text pattern.
![image](https://user-images.githubusercontent.com/26474449/89008199-d5ff5380-d33c-11ea-9a75-d19cefa15b71.png)

**Expected behavior:**
No error

**Comment by merriemcgaw** [comment]
@vladimir-krestov do labels show that they support the text pattern? In this case I think they're referring to the group labels, and if that's the case I don't see why test pattern is needed.

**Comment by Olina-Zhang** [comment]
Verified in Net 6.0 SDK build, this issue is fixed:
![image](https://user-images.githubusercontent.com/26474449/95648665-b9855180-0b0b-11eb-9136-72dba7443037.png)
