### ISSUE TITLE
Cannot build project successfully

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#3684]
* .NET Core Version: 
5.0.100-rc.1.20380.12

* Have you experienced this same bug with .NET Framework?: 
No

**More info:**
This issue does not occur in 5.0.100-rc.1.20378.11, it's a regression issue. 

**Problem description:**
Cannot build project successfully, and received the below error:
![Actual](https://user-images.githubusercontent.com/45864985/89022271-52e9f780-d354-11ea-979c-1054017c2ca0.png)

**Expected behavior:**
Can build project successfully.

**Minimal repro:**

1. Create a new .NET Core Winforms project and target to .NET 5.0.
2. Build this project. 
[WindowsFormsApp1.zip](https://github.com/dotnet/winforms/files/5006262/WindowsFormsApp1.zip)

**Comment by RussKie** [comment]
It is not something we control. 

Having said that, I think the error is self explanatory:
```
C:\Program Files\dotnet\sdk\5.0.100-rc.1.20403.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(369,5): warning NETSDK1137: It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Microsoft.NET.Sdk can be used instead. [C:\Users\igveliko\Downloads\WindowsFormsApp1\WindowsFormsApp1\WindowsFormsApp1.csproj]
```

![image](https://user-images.githubusercontent.com/4403806/89180976-2218f500-d5d6-11ea-8206-bdfb1fe505cf.png)

To fix remove ".WindowsDesktop":
```diff
-<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
+<Project Sdk="Microsoft.NET.Sdk">
```

**Comment by RussKie** [comment]
From @jmarolf elsewhere:  
> _"The fix on the VS side went in this morning. I reccommend setting `<AnalysisLevel>4</AnalysisLevel>` in the project file until the next SDK and VS previews actually go out"_
