### ISSUE TITLE
Adding Windows Form to Class Library project doesn't work

### ISSUE THREAD

**Issue by tomrus88** [dotnet/winforms#3714]
* .NET Core Version: 5.0 Preview 7

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
I'm unable to add Windows Form to Class Library project (.NET 5.0), it is missing in Add -> New Item VS dialog.

And even if I do workaround, for example add Windows Form to Windows Form project and then drag&drop it to ClassLibrary project, in this case i'm unable to use Windows Form designer (it shows an error: Microsoft Visual Studio - Timed out waiting for the design tools server process launch to complete) and form added this way doesn't even compile...

**Expected behavior:**
I should be able to add Windows Form to class library project using VS and be able to use Windows Forms designer for editing Windows Forms in Class Library projects, just like it works with .NET Framework projects.

**Minimal repro:**
[WindowsFormsApp8.zip](https://github.com/dotnet/winforms/files/5050353/WindowsFormsApp8.zip)

**Comment by RussKie** [comment]
Class libraries are cross-platform projects and can't have Windows-only artifacts like `Form`. You need to create a Windows Forms class library:
https://github.com/dotnet/winforms/blob/7bb9a8b2d633d508bbc1cbb09dd7cb8a4b9e4a31/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/Company.ClassLibrary1.csproj#L8

![image](https://user-images.githubusercontent.com/4403806/89848516-9d2b6e00-dbc9-11ea-8a68-475f3a78e41c.png)

**Comment by weltkante** [comment]
You also need to change `<Project Sdk="Microsoft.NET.Sdk">` to `<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">` I think. This will add the proper references while `<UseWindowsForms>true</UseWindowsForms>` opts-in to WinForms (theres a different flag for WPF, both sharing the same SDK)

**Comment by RussKie** [comment]
> You also need to change `<Project Sdk="Microsoft.NET.Sdk">` to `<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">` I think.

Yes, thank you. It is necessary for 3.x and early 5.0, but no longer necessary with the .NET 5.0 RC1.


We have added Windows Forms class library recently, so it should be available in VS soon(ish?).

**Comment by tomrus88** [comment]
Good to see proper template being added to address his issue. But that template should have been added at same time as Windows Forms support for .NET Core.
