### ISSUE TITLE
[Tests] There are unobvious fail reasons for several tests for a specific commit

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#3716]
* .NET Core Version: 5.0
* Related to PR #2701

**Problem description:**
- The following tests have an unexpected result and unobvious fail reasons for 9d7af3d91733bf95eca155a79f8d34abd23160be commit:
1. TabPageCollection_Remove_InvokeValueWithoutHandleOwnerWithHandle_Success
2. TextBoxBase_WndProc_InvokeSetFontWithoutHandle_ReturnsExpected
3. MonthCalendar_SingleMonthSize_GetWithHandle_ReturnsExpected
4. RichTextBox_SelectionFont_SetWithHandle_GetReturnsExpected
5. RichTextBox_SelectionFont_Set_GetReturnsExpected
6. RichTextBox_Font_GetCharFormat_Success
7. TextBoxBaseUiaTextProvider_GetLineIndex_ReturnsCorrectValue

**Expected behavior:**
- All tests pass

**Minimal repro:**
- Run the tests in multithreaded mode using a console (9d7af3d91733bf95eca155a79f8d34abd23160be)

**Comment by weltkante** [comment]
Can you add more info about the failures or details how to reproduce?

**Comment by vladimir-krestov** [comment]
Sure.
The latest commit with the reproduced issue: eedf3c01715bd17c8a97cdc534ab06c86b319b46
For example: `TextBoxBaseUiaTextProvider_GetLineIndex_ReturnsCorrectValue` unit test in #2701:
![image](https://user-images.githubusercontent.com/49272759/90105293-53b85b80-dd4e-11ea-8c32-ffd52f9bea01.png)
If to run this test in VS test explorer you will have successful result for all test cases. But if to use command line console (`build -test` command) this test will fail for 3th case (`Size(50, 50)`). `GetLineIndex` will return 15 instead expected 19.
Here GetLineIndex implementation:
![image](https://user-images.githubusercontent.com/49272759/90105678-fa9cf780-dd4e-11ea-8c67-74f9ea86c274.png)
You can see that we have different `SendMessageW` results for **VS** and **cmd** testing on one local machine. I don't really know reasons for it.

Second case: `MonthCalendar_SingleMonthSize_GetWithHandle_ReturnsExpected`
I didn't make any changes related to `MonthCalendar` in #2701.
This test passes every time in **VS** but fails in **cmd**.
![image](https://user-images.githubusercontent.com/49272759/90106410-09d07500-dd50-11ea-8a0b-6ac4df9ffdb2.png)
2434 line returns different results every time. `size.Width` may be 150 or 109 or 96 etc. `size.Height` too.
Here is `SingleMonthSize` implementation:
![image](https://user-images.githubusercontent.com/49272759/90106618-5c119600-dd50-11ea-9931-9c0542ddd3f0.png)
As you can see `SendMessageW` works here only and returns unexpected results for a **cmd** test run. I don't know why it happens only in #2701. It works well in the master branch.

The same for other tests from the list. All of them work well in **VS** test run. But fail in **cmd**.

**Comment by weltkante** [comment]
There may be multiple issues here, so I'll starting with the one that is easiest since it previously was working.

> Second case: MonthCalendar_SingleMonthSize_GetWithHandle_ReturnsExpected
> I didn't make any changes related to MonthCalendar in #2701.

If I disable your tests then the MonthCalendar test succeeds again. Something in your tests is either modifying a global setting or simply breaking the whole process. I'll try to figure out which of your tests breaks MonthCalendar.

**Comment by weltkante** [comment]
Following repro fails both in VS and also in console. Seems to be something in TextBox API breaks MonthCalendar. Can't tell if its related to other failures, but basically adding more TextBox tests that run before MonthCalendar tests will break MonthCalendar.

For the repro code I mixed one of the PR tests triggering the bug with the MonthCalendar test. Before the TextBox code runs the MonthCalendar returns a different size, afterwards its broken.

I've taken a look a `TextBox.GetPositionFromCharForUpperRightCorner` and its basically just doing native interop, so this probably needs to be looked at by someone with access to the native source? I couldn't figure out anything wrong at a first look.

PS: made `TextBox.GetPositionFromCharForUpperRightCorner` public because I couldn't remember the right syntax for the dynamic call helper, adjust the test code if you know how to call it correctly.

<details><summary>repro code</summary>

```csharp
        public static IEnumerable<object[]> ReproTestData()
        {
            yield return new object[] { new Size(50, 20), "", false, 0, new Point(0, 0) };
            yield return new object[] { new Size(50, 20), "Some test text", false, 100, new Point(0, 0) };
            yield return new object[] { new Size(50, 20), "Some test text", false, -1, new Point(0, 0) };
            yield return new object[] { new Size(50, 20), "Some test text", false, 12, new Point(71, 0) };
            yield return new object[] { new Size(50, 20), "Some test text", true, 12, new Point(19, 30) };
            yield return new object[] { new Size(100, 60), "Some test \n text", false, 10, new Point(56, 0) };
            yield return new object[] { new Size(100, 60), "Some test \n text", true, 10, new Point(59, 1) };
            yield return new object[] { new Size(100, 60), "Some test \r\n text", false, 10, new Point(56, 0) };
            yield return new object[] { new Size(100, 60), "Some test \r\n text", true, 10, new Point(59, 1) };
            yield return new object[] { new Size(100, 60), "Some test \r\n text", false, 12, new Point(60, 0) };
            yield return new object[] { new Size(100, 60), "Some test \r\n text", true, 12, new Point(7, 16) };
            yield return new object[] { new Size(100, 60), "Some test \t text", false, 10, new Point(57, 0) };
            yield return new object[] { new Size(100, 60), "Some test \t text", true, 10, new Point(60, 1) };
            yield return new object[] { new Size(40, 60), "Some test \t text", true, 12, new Point(8, 46) };
        }

        [WinFormsTheory]
        [MemberData(nameof(ReproTestData))]
        public void ReproTest(Size size1, string text, bool multiline, int charIndex, Point expectedPoint)
        {
            Size size0 = default;

            {
                using var control = new MonthCalendar();
                Assert.NotEqual(IntPtr.Zero, control.Handle);
                int invalidatedCallCount = 0;
                control.Invalidated += (sender, e) => invalidatedCallCount++;
                int styleChangedCallCount = 0;
                control.StyleChanged += (sender, e) => styleChangedCallCount++;
                int createdCallCount = 0;
                control.HandleCreated += (sender, e) => createdCallCount++;

                size0 = control.SingleMonthSize;
                Assert.True(size0.Width >= 169);
                Assert.True(size0.Height >= 153);
                Assert.Equal(size0, control.SingleMonthSize);
                Assert.True(control.IsHandleCreated);
                Assert.Equal(0, invalidatedCallCount);
                Assert.Equal(0, styleChangedCallCount);
                Assert.Equal(0, createdCallCount);
            }

            {
                using var textBox = new TextBox() { Size = size1, Text = text, Multiline = multiline };
                textBox.CreateControl();
                Assert.True(textBox.IsHandleCreated);
                textBox.GetPositionFromCharForUpperRightCorner(charIndex, text); // triggers the bug
            }

            {
                using var control = new MonthCalendar();
                Assert.NotEqual(IntPtr.Zero, control.Handle);
                int invalidatedCallCount = 0;
                control.Invalidated += (sender, e) => invalidatedCallCount++;
                int styleChangedCallCount = 0;
                control.StyleChanged += (sender, e) => styleChangedCallCount++;
                int createdCallCount = 0;
                control.HandleCreated += (sender, e) => createdCallCount++;

                Size size2 = control.SingleMonthSize;
                Assert.Equal(size0, size2); // observes the bug, size differs before and after the TextBox API call
                Assert.True(size2.Width >= 169);
                Assert.True(size2.Height >= 153);
                Assert.Equal(size2, control.SingleMonthSize);
                Assert.True(control.IsHandleCreated);
                Assert.Equal(0, invalidatedCallCount);
                Assert.Equal(0, styleChangedCallCount);
                Assert.Equal(0, createdCallCount);
            }
        }
```

</details>

**Comment by weltkante** [comment]
[Identified the cause](https://github.com/dotnet/winforms/pull/2701#discussion_r469915943). Might also fix some of the other failures, didn't test.

**Comment by vladimir-krestov** [comment]
Thank you so much, @weltkante, for the investigation!
The issue was resolved in another way. There were found incorrect code lines wich crash the tests in #2701
