### ISSUE TITLE
[Loc] The PrintPreview dialog is not translated

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#3747]
* .NET Core Version: .Net SDK 5.0.100-rc.1.20419.9
* Affected Languages: CHS, CHT

* Have you experienced this same bug with .NET Framework?: 
No

**Minimal repro:**

1. Create a Winforms .Net Core application
2. Drag and drop button and PrintPreviewDialog to Form designer.
3. Double-click the button to generate the click event, then enter code "printPreviewDialog1.ShowDialog();" in this event.
4. Build and run this project, then click button.
5. Observe the PrintPreview dialog that pops up.

**Expected behavior:**
The PrintPreview dialog should be translated.
![image](https://user-images.githubusercontent.com/45864649/90732031-10855c00-e2fd-11ea-9504-c147b6038076.png)

**Actual behavior:**
The PrintPreview dialog is not translated.
![image](https://user-images.githubusercontent.com/45864649/90732100-2bf06700-e2fd-11ea-9050-8fdd2f32282a.png)

**Comment by cristianosuzuki77** [comment]
I'm the loc pm. The strings for this form seems to be coming from https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.zh-Hant.xlf and they are localized in the master branch.

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net 7.0 build: 7.0.100-preview.6.22316.8 on CHS OS, it doesn't repro. So close this issue now.
![image](https://user-images.githubusercontent.com/26474449/174519327-f49e0972-082e-4f42-8842-1c9d123d03ce.png)
