### ISSUE TITLE
Property only has get method but its CanWrite is true

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/winforms#3756]
* .NET Core Version: 
.Net SDK 6.0.100-alpha.1.20420.20

* Have you experienced this same bug with .NET Framework?: 
No

**Minimal repro:**
1. Extract “[WindowsFormsApp1.zip](https://github.com/dotnet/winforms/files/5107956/WindowsFormsApp1.zip)” and open it in VS.
2. Put a breakpoint at the end of the Form1_Load method
3. Build and run the project.

**More info:**
This is a regression issue and it can repro on .Net SDK 6.0.100-alpha.1.20420.20.
The version of System.Windows.Forms.dll:
![image](https://user-images.githubusercontent.com/54019172/90878157-cc1abe80-e3d7-11ea-91a1-4ef1a3d332f9.png)

**Problem description:**
The DatagridView.SortOrder property has only one get method, but its CanWrite is true.
![Actual](https://user-images.githubusercontent.com/54019172/90874755-b8208e00-e3d2-11ea-9a78-58eeabc8197b.PNG)
![Actual2](https://user-images.githubusercontent.com/54019172/90874760-b951bb00-e3d2-11ea-8da5-b790b47dce91.PNG)

**Expected behavior:**
The DatagridView.SortOrder property has only one get method, so its CanWrite should be false.
![Expected](https://user-images.githubusercontent.com/54019172/90874763-bb1b7e80-e3d2-11ea-9f85-4172625da8ff.PNG)

**Comment by Lydia-Shi** [comment]
@RussKie When running our .Net core RT cases in latest build, 2 cases failed, After debugging we found the CanWrite value of SortOrder property is changed from false to true. As @Amy-Li02-zz also replied to you in the email.

**Comment by RussKie** [comment]
We provide no guarantee of
