### ISSUE TITLE
a container like QStackedWidget in Qt and StackPane in JavaFx

### ISSUE THREAD

**Issue by ismlsmile** [dotnet/winforms#3759]
a container like QStackedWidget in Qt and StackPane in JavaFx

**Comment by RussKie** [comment]
Thank you for stopping by. 

I'm closing this for the lack of consideration provided, as you decided to ignore the provided API suggestion template, and failed to provide all necessary information including but no limited to: 
- what exactly is that you require (including screenshots, documentation, etc.),
- what benefits the new control provide and what use cases it will address, 
- what underlying Windows control/functionality it will map to, 
- the API surface,
- designer requirements, and
- accessibility requirements.
