### ISSUE TITLE
Calling ColumnHeaderCollection.RemoveAt for an empty collection throws NRE; should throw AOoRE

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#377]

**Comment by hughbe** [comment]
There's a real actual bug here that should be fixed. We should simply return and `nop`. Obvious win, no argument validation added

**Comment by weltkante** [comment]
nopping on a RemoveAt sounds contrary to what usually happens, since Count would be zero you'd get an ArgumentOutOfRangeException in other collections.

**Comment by hughbe** [comment]
Sorry. It should throw AORE and in fact my bug fix makes it do that: https://github.com/dotnet/winforms/pull/365/files#diff-f1682a53fa77d489064b2919146270edR7859

**Comment by zsd4yr** [comment]
approved
