### ISSUE TITLE
The BackColor & MouseOverBackColor property of Button doesn't work

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#3770]
* .NET Core Version: 
.Net SDK 6.0.100-alpha.1.20421.6

* Have you experienced this same bug with .NET Framework?: 
No

* More info: 
This is a regression issue, it cannot reproduce on .Net SDK 5.0.100-preview.8.20417.9

**Problem description:**
The BackColor of Button doesn't work when Button's FlatStyle is Flat or Popup .
The MouseOverBackColor of Button doesn't work when Button's FlatStyle is Flat.
![Actual](https://user-images.githubusercontent.com/62929087/91145995-db0bb480-e6e8-11ea-9c36-6fbf1b51a5f2.gif)

**Expected behavior:**
After run the project, the Button's BackColor should be YellowGreen;
When mouse over on the button, Button's BackColor should be Firebrick.
![Expected](https://user-images.githubusercontent.com/62929087/91146004-df37d200-e6e8-11ea-90f4-17199a8001d6.gif)

**Minimal repro:**  [DemoApp.zip](https://github.com/dotnet/winforms/files/5122064/DemoApp.zip)
1. Create a new winforms .NET core project and target to .NET 5.0.
2. Add a Button to the form designer.
3. Add the following code to the structure method of Form1.
    _button1.FlatStyle = FlatStyle.Flat;
    button1.BackColor = Color.YellowGreen;
    button1.FlatAppearance.MouseOverBackColor = Color.Firebrick;_
4. Build and run the project.
5. Observe the BackColor of Button, then mouse over on the button and observe the BackColor of Button.

**Comment by RussKie** [comment]
The regression was introduced in 99be98a67e9a0e80a941f315593316fa97420559

**Comment by Jessie-Zhang01** [comment]
Verified this issue with .Net SDK 5.0.100-rc.2.20459.18, this issue is fixed. After running the project, the Button's BackColor is YellowGreen; When mouse over on the button, Button's BackColor is Firebrick.
![steps](https://user-images.githubusercontent.com/45864649/92701637-ce42be00-f382-11ea-8a3c-59598ca125b6.gif)
