### ISSUE TITLE
Cannot get the expected result when set "\r\n" to RichTextBox.Text property

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#3778]
* .NET Core Version: 
5.0.0-rc.1.20425.1

* Have you experienced this same bug with .NET Framework?: 
No

**More info:**

1. This issue does not occur in .NET Framework.
2. This issue does not occur in .NET Core 3.1 and .NET 5.0 Preview 8. It's a regression issue in 5.0.0-rc.1.20425.1.  
3. It maybe caused by this PR: [3726](https://github.com/dotnet/winforms/pull/3726)

**Problem description:**

Cannot get the expected result in RichTextBox.Text property when included the "\r\n" in it.
![image](https://user-images.githubusercontent.com/45864985/91247890-efea5580-e785-11ea-8b59-6b046eb4d8a1.png)

**Expected behavior:**
Should get the below value from RichTextBox.Text property. Like it works in .NET Framework and previous version of .NET Core SDK.
![image](https://user-images.githubusercontent.com/45864985/91247920-02fd2580-e786-11ea-866b-142eae4ae63f.png)

**Minimal repro:**

1. Launch the attached project in VS.
2. Run it and observe the value for richTextBox1.Text in debugging. 
[Issue1-TestApp.zip](https://github.com/dotnet/winforms/files/5127204/Issue1-TestApp.zip)

**Comment by merriemcgaw** [comment]
We may need to revert #3726 if we can't find a better solution.

**Comment by RussKie** [comment]
@JeremyKuhne I think this is the expected RichEdit behaviour, the [docs](https://docs.microsoft.com/windows/win32/api/richedit/ns-richedit-gettextex#members) state that the default flag does not translate `\r` -> `\r\n`:
![image](https://user-images.githubusercontent.com/4403806/91932768-7674d900-ed2a-11ea-8e6e-a7a996728c92.png)


The original implementation went like this:
`get_Text -> StreamOut(SF.TEXT | SF.UNICODE) -> StreamOut(..., includeCrLfs: false)` which would normalise EoL to `\n`.

In fact, while setting `Text` we're normalising EoL to `\n`:
* https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/RichTextBox.cs,3052
* https://github.com/dotnet/winforms/blob/6d1700bfaa99dad3a903df693d1f7b00dca18acc/src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs#L3007

I suppose we have few options:
1. use the `GT_USECRLF` flag to convert from `\r` to `\r\n`, and document the new behavior (and stop here); or
2. in addition to the above, replace `\r\n` -> `\n`.

**Comment by John-Qiao** [comment]
Verified in .NET 5.0.100-rc.2.20459.18 SDK, this issue is not reproduced in it. Please check below screenshot:
![3778-TestResult](https://user-images.githubusercontent.com/45864985/92677112-9f622300-f355-11ea-929d-551cd152e08e.png)

**Comment by merriemcgaw** [comment]
waiting to port into 6.0p1
