### ISSUE TITLE
An error appeared after reference the Winformscontrollib project in the winforms core project

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#3790]
## Version info
Latest .NET SDK 5.0.100-rc.1-20426.12 + Dev16 16.8.0 Preview 2.0

## More info
1. The issue also can reproduce on Windows Forms(Winforms) Class Library project.
2. The UserControl also can reproduce on ToolBox window for UserCOntrol1 designer, have a same issue to track it:[1840](https://github.com/dotnet/winforms-designer/issues/1840)

## Minimal Reproduction Scenario
1. Create a winformcontorllib project.(Only can created using CLI https://github.com/dotnet/winforms/issues/3608).
2. Add some controls on the UserControl1 designer, then build the project.
3. Add a winforms core project in the same solution.
4. Reference the winformcontorllib project in the winforms core project.
5. Build the winforms core project.
6. Changed the Target Framework from net5.0-windows to net5.0 of winformcontorllib project.
7. Reference the winformcontorllib project in the winforms core project again, then build the winforms core project.

## Expected Behavior
After steps5: build the winforms project successfully.
![GitHubIssueFramework](https://user-images.githubusercontent.com/38325459/91415430-9d419400-e880-11ea-8bae-56a9c5272c6f.gif)

## Current Behavior
[ContorlLib.zip](https://github.com/dotnet/winforms/files/5134999/ContorlLib.zip)
After steps5: An error appeared. however the UserControl1 can drag & drop successfully.
Note: The error seems related the change from: https://github.com/dotnet/winforms/pull/3631/files#diff-6cb9871f2e55c4449d99393fcefb1c3c.
![GitHubCoreIssue](https://user-images.githubusercontent.com/38325459/91415443-a2064800-e880-11ea-82ba-8bb602ce52dd.gif)

**Comment by merriemcgaw** [comment]
@Zheng-Li01 can you check this again with the most recent int Preview build of VS and the very latest most recent SDK and their changes? Let us know warnings too.

**Comment by Zheng-Li01** [comment]
@merriemcgaw, verified the issue with latest 16.8.0 Preview 3.0 [30431.218.main] from Int Preview branch + .NET 5.0.100.rc.1.20452.10, the issue can't reproduce that the core project build successfully with no error; and the issue also can't reproduce on 16.8.0 Preview 3.0 [30501.256.main] from main branch + .NET 5.0.100.rc.1.20452.10 for now.
![UpdateGitHubIssue](https://user-images.githubusercontent.com/38325459/91938740-1c264900-ed27-11ea-9fd0-005d19a677be.gif)
