### ISSUE TITLE
The GridColor property of DataGridView doesn't work

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/winforms#3829]
* .NET Core Version: 
.Net 5.0.100-rc.1.20452.10

* Have you experienced this same bug with .NET Framework?: 
No

* More info: 
This is a regression issue, it cannot reproduce on .Net SDK 5.0.100-preview.8.20417.9

**Problem description:**
The GridColor property of DataGridView doesn't work.
![image](https://user-images.githubusercontent.com/54019172/92094946-9e863a00-ee07-11ea-9f04-de81390207b3.png)
![GridColor](https://user-images.githubusercontent.com/54019172/92095432-413eb880-ee08-11ea-88f3-9b3bf37f4243.gif)

**Expected behavior:**
After run the project, the color of the grid lines separating the cells should be red.
![Expected](https://user-images.githubusercontent.com/54019172/92095874-d0e46700-ee08-11ea-84be-e325cdf38f93.gif)

**Minimal repro:**  [GridColorTest.zip](https://github.com/dotnet/winforms/files/5167490/GridColorTest.zip)

1.	Create a new winforms .NET core project and target to .NET 5.0
2.	Add a DataGridView control to the form designer and add two columns for DataGridView
3.	Add the following code to the structure method of Form1
   
> dataGridView1.GridColor = Color.Red;

4.	Build and run the project
5.	Observe the color of the grid lines separating the cells of the DataGridView

**Comment by JeremyKuhne** [comment]
Investigating...

**Comment by Lydia-Shi** [comment]
Verified this issue in Net Core 5.0.100-rc.2.20460.27, this issue is fixed. The color of the grid lines separating the cells is red after running the attachment project.
![image](https://user-images.githubusercontent.com/54019172/92843523-6b4f3680-f417-11ea-8303-a09caa71950a.png)
