### ISSUE TITLE
Links in README.md broken

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#3833]
Several  links in https://github.com/dotnet/winforms/blob/master/README.md go to 404
https://github.com/dotnet/winforms/blob/master/Documentation/winforms-designer.md
https://github.com/dotnet/winforms/blob/master/Documentation/getting-started.md
https://github.com/dotnet/winforms/blob/master/Documentation/contributing.md
https://github.com/dotnet/winforms/blob/master/Documentation/porting-guidelines.md

I stopped checking the rest

**Comment by eduherminio** [comment]
All links seem fixed now.

**Comment by RussKie** [comment]
Thanks for checking. Closing.
