### ISSUE TITLE
Microsoft.VisualBasic.ApplicationServices.User doesn't work the same as Framework

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#3845]
* .NET Core Version: 
5.0.0-preview.8.20411.6

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
User.Name gives BC30469 Reference to a non-shared member requires an object reference

**Expected behavior:**
No error

**Minimal repro:**
```
Dim s As String = "Current user: " & User.Name
```
or
```
Dim s As String = "Current user: " & My.User.Name
```

**Comment by JeremyKuhne** [comment]
@KlausLoeffelmann can you update this please? Thanks!

**Comment by KlausLoeffelmann** [comment]
@paul1956, this behaves exactly like in Framework:

![image](https://github.com/dotnet/winforms/assets/9663150/d29dfdb6-c9b2-4258-a3e5-b434fe7f4039)

If I am not using My as a prefix in a 4.7.2 VB Framework App, I am of course seeing this error:

![image](https://github.com/dotnet/winforms/assets/9663150/593eb998-c99c-4cc2-be36-ae435d4af3b0)

Closing this as non-repro.
Feel free to reopen, if you want to further discuss this!

Thanks!

**Comment by paul1956** [comment]
@KlausLoeffelmann This was a Template issue and "My" is the answer, the Template did not have the "My".
