### ISSUE TITLE
TableLayoutStyleCollection.Insert/Add/ItemSet(null) throws NRE should throw ANE

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#385]

**Comment by hughbe** [comment]
And Remove(null) should be a nop

**Comment by hughbe** [comment]
Remove is an obvious win - now nop whereas used to throw. Other consideration of changing exception may need more discussion

**Comment by zsd4yr** [comment]
https://github.com/dotnet/winforms/issues/392#issuecomment-459063843

**Comment by zsd4yr** [comment]
approved
