### ISSUE TITLE
WinForms Core default project name/solution name should not be “ConsoleAppXXX” in Visual Studio

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#386]
**VS**: 16.0.0 Preview 4.0 [28526.15.d16.0stg]
**.NET SDK**: .NET Core 3.0.100-preview-010184

**Steps to Reproduce:**
1. Launch Dev16, click “Create a new project”, then choose “Windows Forms App (.Net Core)” template, then click Next
2. In “configure your new project” dialog, check the project name and solution name

**Actual:**
The Project name and Solution name for Winforms .Net Core app are not correct, should not be “ConsoleAppXXX”. See following screenshot:
![corecreating](https://user-images.githubusercontent.com/26474449/51823921-a5e17b00-2295-11e9-8881-593939e31043.png)

**Expected:**
The default Project name and Solution name are same as Winforms Framework app when creating.

**Comment by zsd4yr** [comment]
@merriemcgaw should this be rerouted to the template folks? 😄

**Comment by merriemcgaw** [comment]
@Pilchie does this belong in your repo?

**Comment by Pilchie** [comment]
@jmarolf - where do these live again?

**Comment by rido-min** [comment]
This PR https://github.com/dotnet/templates/pull/75 has the fix, tracked internally by [#779597](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/779597).
