### ISSUE TITLE
[Accessibility] ToolStripTextBox must support Text pattern

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#3860]
- Original Bug: [1155254](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1155254)
* .NET Core Version: 5.0.0-rc.1.20431.5

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
- ToolStripTextBox doesn't support Text pattern
- A ScreenReader can't announce separate navigated, selected, or added characters in ToolStripTextBox 

**Expected behavior:**
- ToolStripTextBox must support Text pattern (may be checked using Inspect)
- A ScreenReader announces separate navigated, selected, or added characters in ToolStripTextBox 

**Minimal repro:**
- Create a .Net 5.0 app
- Add a ToolStrip with a ToolStripTextBox item
- Run the app and check ToolStripTextBox using Inspect or Narrator

**Comment by merriemcgaw** [comment]
@vladimir-krestov can this be closed now?

**Comment by Zheng-Li01** [comment]
Verified the issue with .NET SDK 5.0.100-rtm.20513.7 that the issue has been fixed that the ToolStripTextBox support Text Patter for now. see below screenshot.
![ToolStripTextBox](https://user-images.githubusercontent.com/38325459/95952938-a7692300-0e2b-11eb-9bcd-12c786672d7c.PNG)
