### ISSUE TITLE
The text of the selected Button in the VB project is invisible

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#3863]
* .NET Core Version: .Net SDK 6.0.100-alpha.1.20455.1

* Have you experienced this same bug with .NET Framework?: 
No

**More Info**
This is a regression issue, it cannot reproduce on 6.0.100-alpha.1.20431.8.

**Minimal repro:**

1. Open the attached [Test1.zip](https://github.com/dotnet/winforms/files/5193850/Test1.zip) application in VS, then build and run it.
2. Observe the selected button.

**Expected behavior:**
The selected button should display its own text.
![image](https://user-images.githubusercontent.com/45864649/92576254-e3084e80-f2bb-11ea-9941-4818e1fd706b.png)

**Actual behavior:**
The text of the selected Button in the VB project is invisible.
![image](https://user-images.githubusercontent.com/45864649/92576748-7477c080-f2bc-11ea-979b-0d25f226fc20.png)

**Comment by weltkante** [comment]
The visuals differ more than just text not being present. Is this an artifact of how the screenshots are taken (like running different code for the other screenshot) or are there also regressions how the button border/background is rendered?

**Comment by JeremyKuhne** [comment]
The master branch doesn't have this problem, but oddly I get the following when I do `dotnet run` with the 6.0.100-alpha.1.20459.19 installed so I'm not able to repro.

![image](https://user-images.githubusercontent.com/8184940/92681233-f5957e80-f2e1-11ea-97de-4ee73f581aa9.png)

The problem you're seeing appears to be one of the regressions I did fix a while ago: https://github.com/dotnet/winforms/pull/3657

**Comment by RussKie** [comment]
@Jessie-Zhang01 can you please confirm this doesn't affect 5.0-RC2 branch?

**Comment by Jessie-Zhang01** [comment]
@RussKie This issue cannot reproduce on 5.0.100-rc.2.20463.1.
![image](https://user-images.githubusercontent.com/45864649/93057021-d7dc6680-f69f-11ea-819c-b8b21ae57372.png)
