### ISSUE TITLE
The Winforms controls are displayed in V5 mode in the running Core VB application

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#3864]
* .NET Core Version: .Net SDK 6.0.100-alpha.1.20455.1

* Have you experienced this same bug with .NET Framework?: 
No

**More Info**
This is a regression issue, it cannot reproduce on 6.0.100-alpha.1.20431.8.

**Minimal repro:**
1. Open the attached [Test2.zip](https://github.com/dotnet/winforms/files/5193983/Test2.zip) application in VS, then build and run it.
2. Observe the controls on the Form

**Expected behavior:**
The Winforms controls should display as V6 mode, like Winforms framework app by default.
![image](https://user-images.githubusercontent.com/45864649/92579674-0f25ce80-f2c0-11ea-902d-54df0caa137b.png)

**Actual behavior:**
The Winforms controls are displayed in V5 mode in the running Core VB application.
![image](https://user-images.githubusercontent.com/45864649/92579735-2369cb80-f2c0-11ea-9649-e4eb46224e0e.png)
In addition, the created VB project is missing the Program.vb file compared to the previous build.
![image](https://user-images.githubusercontent.com/45864649/92579991-76438300-f2c0-11ea-8836-7ded6a3e08b0.png)

**Comment by RussKie** [comment]
@Jessie-Zhang01 can you please confirm this doesn't affect 5.0-RC2 branch?

**Comment by Jessie-Zhang01** [comment]
@RussKie This issue also can reproduce on 5.0.100-rc.2.20463.1.
![image](https://user-images.githubusercontent.com/45864649/93056724-6997a400-f69f-11ea-8c15-3e79e4b92ce4.png)

**Comment by RussKie** [comment]
@merriemcgaw @KlausLoeffelmann we may need to have it resolved for 5.0

**Comment by RussKie** [comment]
@merriemcgaw @KlausLoeffelmann @KathleenDollard  we may need to have it resolved for 5.0

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann you're working on enabling Visual Styles, right?

**Comment by KlausLoeffelmann** [comment]
Yes, this is purely a template issue.
Once this is in, we're OK.

https://github.com/dotnet/winforms/pull/3894

**Comment by RussKie** [comment]
@Jessie-Zhang01 could you please re-test on the latest RC2?

**Comment by Jessie-Zhang01** [comment]
@RussKie Verified this issue with .Net 5.0.100-rc.2.20466.4, this issue doesn't repro on this build.
![image](https://user-images.githubusercontent.com/45864649/93548956-ecb84300-f99a-11ea-8806-abd32e42100b.png)
