### ISSUE TITLE
[LOC] Assistance with query

### ISSUE THREAD

**Issue by cristianosuzuki77** [dotnet/winforms#3868]
String Resource ID | 0; "DataGridViewCheckBoxCellCheckedStateDescription"
-- | --
Source String | {0} check box checked
Filename | System.Windows.Forms\src\Resources\xlf\SR.xlf
Question | What will {0} be? Will it be the nubmer of checkbxes or name? Same with 0; "DataGridViewCheckBoxCellUncheckedStateDescription"

**Comment by RussKie** [comment]
The placeholder will contain the name of a cell.
@SergeySmirnov-Akvelon can you please provide an example?

**Comment by SergeySmirnov-Akvelon** [comment]
Hi @cristianosuzuki77. This placeholder contains address of cell in DataGridView (for example "Test Column Row 1")

**Comment by RussKie** [comment]
@cristianosuzuki77 is there anything else pending here?

**Comment by cristianosuzuki77** [comment]
Thank you!
