### ISSUE TITLE
ListBindingHelper.GetListItemType(new IEnumerableWrapper(null)) throws NRE should return typeof(object)

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#389]
```cs
ListBindingHelper.GetListItemType(new IEnumerableWrapper(null));

private class IEnumerableWrapper : IEnumerable
{
    public IEnumerableWrapper(IList list)
    {
        List = list;
    }

    private IList List { get; }

    public IEnumerator GetEnumerator() => List?.GetEnumerator();
}
```

**Comment by hughbe** [comment]
So this is an example where there's a real actual bug. We should simply return `typeof(object)` instead of null refing - instead of throwing, we now return a meaningful value. This is breaking, but acceptable. This obviously differs from the other cases where we should throw ANE not NRE

**Comment by zsd4yr** [comment]
approved
