### ISSUE TITLE
Modify Visual Basic CLI templates for the Visual Basic Application Framework

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#3893]
From Visual Studio 16.8 Preview 4 on, we will have the Application Framework for Visual Basic WinForms App available. The AppDesigner for the Visual Basic Project properties will look about this and will have (almost) parity to NetFx:

![image](https://user-images.githubusercontent.com/9663150/93021840-fa845780-f599-11ea-8e57-b3be8a499191.png)

To make sure that Visual Basic WinForms App will be starting in the `SystemAware` HighDpiMode, we will be introducing a new Application Event named `ApplyHighDpiMode`. For the time being (net5 to net6), this event will be introduced over the Visual Basic Application Framework templates, in net6.0 it will become part of `WindowsFormsApplicationBase` (and the Application Framework template will be changed to accommodate net6.0 accordingly - also see #3861)

![image](https://user-images.githubusercontent.com/9663150/93022051-8e0a5800-f59b-11ea-8125-8865ca826b4d.png)

NOTE: The Visual Basic Application Framework will not be available for .NET Core 3.1, ONLY for >= net5.0. Note also, that the Settings feature will not be available in the 16.8 time frame.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann can this be closed now?

**Comment by KlausLoeffelmann** [comment]
Yes. Fixed with #3940.
