### ISSUE TITLE
An error pops up that 'Focusable sibling elements must not have the same Name and LocalizedControlType' for sub-item 'combobox' of ContextMenuStrip control

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#3895]
* .NET Core Version: 
.NET 6.0.100-alpha.1.20463.4 

* More info
1. The issue also can reproduce on .NET SDK 3.1 & .NET 5.0.
2. The issue can't reproduce on sub-items 'combbBox Edit' of MenuStrip & ToolStrip controls & standalone ComboBox control.

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
An error pops up when focus on sub-item combobox's edits part in Accessibility Insight tool.

**Expected behavior:**
No error pops up.

**Minimal repro:**
1. Open attached app, build & run it.([PrivateCoreProject.zip](https://github.com/dotnet/winforms/files/5217078/PrivateCoreProject.zip))
2. Right click the button1 to call the contextmenustrip.
3. Run the Accessibility Insight tool.
4. Only focus on the sub-item 'ComboBox Edit' part using Accessibility Insight tool.
5. Observe the results.
![CoreNewIssue](https://user-images.githubusercontent.com/38325459/93061955-d8c4c680-f6a6-11ea-9acc-e92ed63b79cd.gif)
![CoreIssue](https://user-images.githubusercontent.com/38325459/93061966-dc584d80-f6a6-11ea-9820-284811b4d806.png)

**Comment by merriemcgaw** [comment]
Is AccessibleName available for the child elements of the ToolStrip and StatusStrip? If you can set up the appropriate names in the sample app, that is what I'd recommend.

**Comment by Zheng-Li01** [comment]
@merriemcgaw, the AccessibleName is available for the child elements of the ToolStrip and StatusStrip for now, see as below screenshot, and have updated the app.
[UpdateApp.zip](https://github.com/dotnet/winforms/files/5280317/UpdateApp.zip)
![UpdateCoreIssue](https://user-images.githubusercontent.com/38325459/94221631-15ea4d80-ff1e-11ea-8080-78d3f37c29d3.PNG)

**Comment by RussKie** [comment]
@Zheng-Li01 so is there any action in the runtime expected?

**Comment by Zheng-Li01** [comment]
Just modified the app based on Merrie's suggestion, and It won't stop the original problem from happening that the error still appeared.

**Comment by merriemcgaw** [comment]
Then it looks like we have at least an investigation. I'll keep it open and get it prioritized in our Accessibility project.

**Comment by SergeySmirnov-Akvelon** [comment]
Hi, @Zheng-Li01. Thank you for providing information about this issue. During investigation of it we found that issue is reproduced because ContextMenuStrip disappears when Accessibility Insights start to test it. Disappearance during a loss of focus is default behavior for the ContextMenuStrip. If to change behavior of ContextMenuStrip  and keep it displayed after losing focus then tests will pass successfully. We think that it is an edge case in a user scenario and an attempt to fix this bug can lead to new more complex issues. Also this issue is reproduced for NET Framework 4.7.2
