### ISSUE TITLE
[Accessibility] Incorrect ScreenReader blue rectangle for a new character in TextCompoments

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#3897]
Related issues: 
- #1588 
- #3683
- #2786 
- #3860 

The issue reproduces only in a context of Text pattern implementation

-----

* .NET Core Version: 5.0.0-rc.1.20431.5

* Have you experienced this same bug with .NET Framework?: No (Text pattern is not implemented)

**Problem description:**
- ScreenReader doesn't show the blue rectangle around an added character when typing a text in `ToolStripTextBox`, `DataGridViewTextBoxCell`, `PropertyGridView.GridViewEdit`

   ![TT bug](https://user-images.githubusercontent.com/49272759/93136223-3aefec80-f6e4-11ea-9395-2324ac13630b.gif)

**Expected behavior:**
- ScreenReader should show the blue rectangle for a new character like in `TextBox`
![T](https://user-images.githubusercontent.com/49272759/93136212-37f4fc00-f6e4-11ea-8825-df0b94136210.gif)

**Minimal repro:**
- Create .Net 5.0 app
- Add `ToolStripTextBox`, `DataGridViewTextBoxCell`, `PropertyGridView.GridViewEdit` to the app
- Run the app and Narrator
- Try to type a text in a text field

**Comment by merriemcgaw** [comment]
@vladimir-krestov is this a regression for TextBoxes as well? Do we have a theory as to what we're not updating for Narrator to recognize the new characters are happening. I'm reluctant to push this in so late in 5.0, but I can chat with @guybark to see what his thoughts are about the urgency of this issue.

**Comment by vladimir-krestov** [comment]
@merriemcgaw I prepared the fix (#3969), we need to raise `Text_TextChangedEvent` only to Narrator shows the blue rectangle correctly like in RichTextBox.
I think we can add this to .Net 5.0 as part of adding Text pattern
