### ISSUE TITLE
Remove unused managed defines from S.W.F code

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#39]
There are a few pre-processor directives in S.W.F code which might not be required.
Scrub the code and keep only those which are required.

**Comment by RussKie** [comment]
Is it possible to clarify the requirements and the acceptance criteria?

**Comment by danmosemsft** [comment]
These are the remaining defines, after #838. 
Those that are defined anywhere (either in code or csproj) are marked `[DEFINED]`
If we can determine which of these are defunct - I'm assuming most of them - it is trivial to delete them, either retaining or discarding the included code as appropriate. (Mostly discarding, considering they mostly aren't defined)

- [ ] `__APPLE__`
- [ ] `ACTIVEX_SOURCING`
- [ ] `CLICKONCE`
- [ ] `Codemarkers_IncludeAppEnum`
- [ ] `Codemarkers_NoCodeMarkerStartEnd`
- [ ] `CPP_DEFINITIONS`
- [ ] `DEBUG`
- [ ] `DEBUG_HANDLECOLLECTOR`
- [ ] `DEBUG_LAYOUT`
- [ ] `DEBUG_ONLY_APIS`
- [ ] `DEBUG_PAINT`
- [ ] `DEBUG_PAINT_ANCHOR`
- [ ] `DEBUG_PREFERREDSIZE` `[DEFINED]`
- [ ] `DEBUG_UPDOWN`
- [ ] `DEBUGGING`
- [ ] `DEPLOYMENT_NAMESPACE`
- [ ] `DGV_GDI`
- [ ] `DONT_SUPPORT_ADD_EVENT_HANDLER`
- [ ] `DRAWING_DESIGN_NAMESPACE` `[DEFINED]`
- [ ] `DRAWING_NAMESPACE`
- [ ] `EVERETTROLLBACK`
- [ ] `FALSE`
- [ ] `false`
- [ ] `FEATURE_PAL`
- [ ] `FINALIZATION_WATCH`
- [ ] `GDI_FINALIZATION_WATCH`
- [ ] `GDI_FONT_CACHE_TRACK` `[DEFINED]`
- [ ] `GRAYSCALE_DISABLED` `[DEFINED]`
- [ ] `LAYOUT_PERFWATCH`
- [ ] `LEGACY`
- [ ] `MAGIC_PADDING`
- [ ] `Marshal_IsTypeVisibleFromCom`
- [ ] `OPTIMIZED_MEASUREMENTDC` `[DEFINED]`
- [ ] `PARENT_LINKS`
- [ ] `PBRS_PAINT_DEBUG`
- [ ] `PLATFORM_UNIX`
- [ ] `REMOTING`
- [ ] `SELECTEDCHANGED`
- [ ] `SILVERLIGHT`
- [ ] `TRACK_HDC` `[DEFINED]`
- [ ] `TRACK_HFONT`
- [ ] `true`
- [ ] `WGCM_TEST_SUITE`
- [ ] `WINFORMS_PUBLIC_GRAPHICS_LIBRARY`
- [ ] `WINGRAPHICS_FINALIZATION_WATCH`

@zsd4yr

**Comment by zsd4yr** [comment]
Thanks @danmosemsft ! This should help out @Shyam-Gupta enormously
