### ISSUE TITLE
ListBindingHelper.GetListItemProperties(x, new PropertyDescriptor[] { null }) throws NRE should return empty

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#390]

**Comment by hughbe** [comment]
So this is an example where there's a real actual bug. We should simply return `new PropertyDescriptor[0]` instead of null refing - instead of throwing, we now return a meaningful value. This is breaking, but acceptable. This obviously differs from the other cases where we should throw ANE not NRE

**Comment by zsd4yr** [comment]
approved
