### ISSUE TITLE
The Icons for .Net Core VB and C# Windows Forms Control Library are not correct in 'Create a New Project' dialog

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#3904]
* .NET Core Version: 5.0.100-rc.2.20464.10
* Have you experienced this same bug with .NET Framework?: No

**Minimal repro:**
1.	Check the preview feature "Show all .Net Core templates in the New project dialog(required restart)" in VS: Tools->Options->Environment->Preview Features
2.	Launch VS and click 'New Project'
3.	In 'Create a new project' dialog, search 'Winforms control library' 
4.	Observe the icons for .Net Core VB and C# Windows Forms Control Library

**Actual behavior:**
The Icons for .Net Core VB and C# Windows Forms Control Library are not correct.
![image](https://user-images.githubusercontent.com/26474449/93173398-08370a00-f75f-11ea-82f5-acba2559457e.png)

**Expected behavior:**
The icons for them should be same as .Net frameworks'

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you test with the most recent template changes (latest SDK).
@phenning , can you provide guidance for how we get these to have the correct icons?

**Comment by Olina-Zhang** [comment]
@merriemcgaw  Verified in the latest .Net 5.0 RC2 build: 20474.11, this issue is fixed. Correct icon is displayed for .Net Core VB and C# Windows Forms Control Library templates in 'create a new project' dialog, see following screenshot, we can close this issue now.
![image](https://user-images.githubusercontent.com/26474449/94222643-872b0000-ff20-11ea-86c7-f33cb7b78f71.png)
