### ISSUE TITLE
A syntax error in description of .Net Core VB and C# Windows Forms Control Library templates

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#3905]
* .NET Core Version: 5.0.100-rc.2.20464.10
* Have you experienced this same bug with .NET Framework?: No

**Minimal repro:**
1.	Check the preview feature "Show all .Net Core templates in the New project dialog(required restart)" in Tools->Options->Environment->Preview Features
2.	Launch VS and click 'New Project'
3.	In 'Create a new project' dialog, search 'Winforms control library' 
4.	Look at the description for .Net Core VB and C# Windows Forms Control Library templates

**Actual behavior:**
A syntax error in description about 'A controls'
![image](https://user-images.githubusercontent.com/26474449/93173893-c5296680-f75f-11ea-8d20-8010e3186f11.png)

**Expected behavior:**
It should be 'Controls'

**Comment by merriemcgaw** [comment]
#3808 has the fix for this.

**Comment by RussKie** [comment]
Fixed by #4056
