### ISSUE TITLE
ListBindingHelper.GetListName(typeof(Array), new PropertyDescriptor[0]) throws NRE should return "Array"

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#391]

**Comment by hughbe** [comment]
So this is an example where there's a real actual bug. We should simply return `Array` instead of null refing - instead of throwing, we now return a meaningful value. This is breaking, but acceptable. This obviously differs from the other cases where we should throw ANE not NRE

**Comment by zsd4yr** [comment]
approved
