### ISSUE TITLE
The PropertyGrid displays properties of selected object incorrectly with Net 5.0 Windows app (Core)

### ISSUE THREAD

**Issue by ChungNNVN** [dotnet/winforms#3919]
* .NET Core Version: 
.NET SDK 5.0.100-preview.7.20417.9

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The PropertyGrid displays properties of selected object incorrectly in Net 5.0 app. But display correctly with Net 4.5.2 or Net Core 3.1 version. The used VS version is 16.8.0 Preview 2.1.
Sample code:
  `private void Form1_Load(object sender, EventArgs e)`
  `{`
        `propertyGrid1.SelectedObject = new Font(DefaultFont.FontFamily, 15);`
        `propertyGrid1.Refresh();`
  `}`

Result:
![image](https://user-images.githubusercontent.com/13590421/93308182-24ed4380-f82c-11ea-91f0-826e4c4aac53.png)

**Expected behavior:**
The PropertyGrid in Net 5.0 app display all properties of selected object.

**Minimal repro:**
1. Run attached app:
   [TestPropertyGrid.zip](https://github.com/dotnet/winforms/files/5230658/TestPropertyGrid.zip)

2. Observe:
  PropertyGrid display properties of selected object.

**Comment by kirsan31** [comment]
Must be [fixed](https://github.com/dotnet/winforms/issues/3800#issuecomment-683275091) in rc1.

**Comment by RussKie** [comment]
Please try the latest nightly RC2 build: https://github.com/dotnet/installer

**Comment by ChungNNVN** [comment]
> Please try the latest nightly RC2 build: https://github.com/dotnet/installer
This was fixed in RC2, thanks!

**Comment by RC1207Sev** [comment]
The problem seems happening again on 5.0.201 and on 5.0.104.
![image](https://user-images.githubusercontent.com/1739664/110997308-d3d58c80-8342-11eb-93ad-08d8e9372c64.png)

**Comment by kirsan31** [comment]
@RC1207Sev https://github.com/dotnet/winforms/issues/4593

**Comment by RC1207Sev** [comment]
> @RC1207Sev #4593

Thank you for the super fast reply and thank you for working on it. If you tell me the 5.0.5 has the fix and will be released in days, I will wait and upgrade.

Thanks!

**Comment by kirsan31** [comment]
5.0.5 will be contain fix, but I am afraid that it will be release approximately in 1 one month (unless it will be forced).
And yes, your are not alone who come in [troubles](https://github.com/dotnet/winforms/issues/4593#issuecomment-795212201) with this :(
