### ISSUE TITLE
Properties window is blank after installed latest .NET 5.0 SDK

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#3921]
* .NET Core Version: 
.NET 5.0.100-rc.2.20465.34

![dll](https://user-images.githubusercontent.com/62929087/93310626-9da5cd00-f837-11ea-87d1-2b299d308aad.png)

* More info:
This is a regression issue, it cannot reproduce on .NET 5.0.100-rc.2.20464.22 build.
![GoodDll](https://user-images.githubusercontent.com/62929087/93318068-d0a08e80-f840-11ea-9664-8c9368b567aa.png)

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Properties window is blank, we cannot see any properties for form or added controls, and no properties and events toolbar in Properties window.
![blankIssue](https://user-images.githubusercontent.com/62929087/93310646-a1395400-f837-11ea-8730-6deef0a6031f.png)

**Expected behavior:**
All properties and events are in Properties window.
![Correctly](https://user-images.githubusercontent.com/62929087/93310658-a4344480-f837-11ea-9415-ae1444847800.png)

**Minimal repro:**
1. Create a WinForms .Net Core application and change the targetFramework to .NET 5.0.
2. Focus on Form designer, and go to Properties window or press F4.
3. Observe **Properties** window.

**Comment by Amy-Li03** [comment]
@JeremyKuhne could you please investigate this regression issue?

**Comment by IrinaPykhova** [comment]
I also see that with RC2

**Comment by Amy-Li03** [comment]
Installed .net 5.0 rc2 from: https://github.com/dotnet/installer, the latest build is .NET 5.0.100-rc.2.20466.16, this issue doesn't repro on this build.

**Comment by kirsan31** [comment]
Yes it's working. But after first V.S. launch I was waiting far more than 30 seconds for properties to appear. I already started writing here that the fix didn't work for me. Went back to the studio and they showed up. In subsequent launches, properties appear within a couple of seconds ...
