### ISSUE TITLE
VS is restarting when opening the Items Collection Editor

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#3924]
* .NET Core Version: 
.NET 5.0.100-rc.2.20465.34

* More info:
1. This is a regression issue, it cannot reproduce on .NET 5.0.100-rc.2.20464.22 build.
2. ContextMenuStrip, StatusStrip, ToolStrip controls also can repro this issue.

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
VS restarts when opening the Items Collection Editor by click Edit Items on MenuStrip.

**Call Stack:**
[callStack.txt](https://github.com/dotnet/winforms/files/5231136/callStack.txt)

**Expected behavior:**
Items Collection Editor dialog should show up.

**Minimal repro:**
1. Create a WinForms .Net Core application and change the target framework to .NET 5.0
2. Drag and drop a MenuStrip to the form designer
3. Right-click on the MenuStrip control, then click Edit Items

**Comment by Amy-Li03** [comment]
@JeremyKuhne could you please investigate this regression issue?

**Comment by Tanya-Solyanik** [comment]
@Amy-Li03 , I did the following:
Setup:
created a clean VM
Installed SDK 5.0.100-rc.2.20466.13
Installed Version 16.8.0 Preview 4.0 [30516.15.main]
removed SDK that came with the VS (rc1) - I don't think this is necessary.

To re-target - edited the project file because application properties did not open in this build.
<Project Sdk="Microsoft.NET.Sdk">
    <TargetFramework>net5.0-windows7.0</TargetFramework>

Result - menuitem editor works fine

**Comment by RussKie** [comment]
> net5.0-windows7.0

This is concerning though...

**Comment by Amy-Li03** [comment]
@Tanya-Solyanik have shared a VM for you on teams, you can connect it to repro this issue.
We are only need to install latest .NET 5.0 rc2 latest build from here: https://github.com/dotnet/installer, and it doesn' t need to removed SDK that came with the VS (rc1).
VS is not specific, we can repro this issue on latest 16.8 preview 4 and preview 3 build. 
create a winforms core project, then re-target to .NET 5.0, do the above steps on the form designer, VS will crash.

**Comment by Amy-Li03** [comment]
I just installed .net 5.0 rc2 from: https://github.com/dotnet/installer, the latest build is .NET 5.0.100-rc.2.20466.16, this issue doesn't repro on this build.

**Comment by Tanya-Solyanik** [comment]
Not sure why this issue was re-opened. closing again
