### ISSUE TITLE
NumericUpDown drawing issue

### ISSUE THREAD

**Issue by IrinaPykhova** [dotnet/winforms#3931]
* .NET Core Version: .Net 5 RC1 (also reproducible with RC2)
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

standard NumericUpDown draws some garbage around the text area. Here are 2 examples:
at runtime:
![NumericUpDown](https://user-images.githubusercontent.com/19591075/93373371-ad8cd380-f86e-11ea-88d7-8170d76c5274.jpg)
in VS designer:
![NumericUpDown1](https://user-images.githubusercontent.com/19591075/93373386-b087c400-f86e-11ea-8f57-dfac59935dac.jpg)
The actual appearance might be different, sometimes it looks not like lines, but as a part of some underlying text.

**Expected behavior:**
No artifacts, only text, borders and buttons

**Minimal repro:**

- place NumericUpDown to the form
- run application
- collapse application window to tray
- restore application window - you should see artifacts
- if you don't see artifacts on the previous step, collapse app window again, open some other application windows so that they cover desktop and then restore your app window. You should see artifacts. If you had your form opened in VS designer, then you should see bad effects in VS designer as well

**Comment by JeremyKuhne** [comment]
Reproduced- investigating.

**Comment by JeremyKuhne** [comment]
I know what is going on and have a fix- I'm scouring for other places where I may have made the same mistake and I'm writing regression tests.

**Comment by Lydia-Shi** [comment]
Verified this issue with 5.0.100-rc.2.20477.2 from 5.0 RC2 branch, it issue is fixed that NumbericUpDown control displays correctly.
![NumberUpDown](https://user-images.githubusercontent.com/54019172/94404554-ce73f380-01a1-11eb-8454-830e1713e82a.gif)
