### ISSUE TITLE
ControlPaint.DrawBorder dashed and dotted styles don't render correctly

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#3944]
In RC1 `DrawBorder` no longer renders `ButtonBorderStyle.Dotted` and `ButtonBorderStyle.Dashed` correctly. Sample code:

``` C#
            ControlPaint.DrawBorder(e.Graphics, bounds, Color.Red, ButtonBorderStyle.Dotted);
            bounds.Offset(0, 30);
            ControlPaint.DrawBorder(e.Graphics, bounds, Color.Green, ButtonBorderStyle.Dashed);
```

Current is on the left, correct is on the right:

![image](https://user-images.githubusercontent.com/8184940/93552521-79281e80-f925-11ea-8d80-dee9e2a72920.png)

**Comment by Marie-Shi** [comment]
Verified this issue with 5.0.100-rc.2.20477.2 from 5.0 RC2 branch, it is fixed. Now ControlPaint.DrawBorder dashed and dotted styles can render correctly.
![1](https://user-images.githubusercontent.com/45864017/94386085-627d9500-0179-11eb-8487-84ea4264c762.png)
