### ISSUE TITLE
change the color and Font of ListViewGroup

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#3951]
This is a suggestion ticket from the .NET Developer Community and we'd like to consider it for a future release.
https://developercommunity.visualstudio.com/content/idea/567122/change-the-color-and-font-of-listviewgroup.html

**Comment by kirsan31** [comment]
When consider this, may be take in to account ability to set selection fore/back color too?

**Comment by merriemcgaw** [comment]
If it's not part of the API we should close this issue as out of scope
