### ISSUE TITLE
ControlPaint.DrawSizeGrip leaves a gap in rendering

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#3953]
DrawSizeGrip is one pixel too short on the right.

``` C#
            bounds = new Rectangle(500, 300, 20, 20);
            ControlPaint.DrawSizeGrip(e.Graphics, Color.Blue, bounds);
            e.Graphics.DrawRectangle(Pens.Red, bounds);
```

Good is on the left, bad is on the right:

![image](https://user-images.githubusercontent.com/8184940/93653904-be088f80-f9cf-11ea-8165-845cde68d874.png)

**Comment by JeremyKuhne** [comment]
This also leaves a new gap on Forms that aren't drawn using visual styles.

**Comment by John-Qiao** [comment]
Verified the issue in Dev16 16.9.0 Preview 1.0 [30527.11.main] + .NET 5.0.100-rc.2.20477.2 from RC2 branch , this issue has been fixed as below:
![TestResult](https://user-images.githubusercontent.com/45864985/94404080-fb73d680-01a0-11eb-86af-99c02dc8383c.png)
