### ISSUE TITLE
ListView is in virtual mode throws IOE

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#3962]
* .NET Core Version:
.NET SDK 5.0.100-rc.1.20420.14

* Have you experienced this same bug with .NET Framework?: 
No

**Minimal repro:**

1. Create application with ListView in virtual mode
3. Run application
4. Select any item in ListView

![ListViewVirtualMode](https://user-images.githubusercontent.com/23376742/93773875-403fc080-fc29-11ea-926b-9d671694d720.gif)

**Expected behavior:**
Exception should not be displayed.

**Actual behavior:**
'When the ListView is in virtual mode, you cannot enumerate through the ListView items collection using an enumerator or call GetEnumerator. Use the ListView items indexer instead and access an item by index value.' exception is displayed

**Comment by RussKie** [comment]
On further inspection this appears to be a significantly worse problem - listview in a virtual mode is totally unusable.
Investigating.

**Comment by RussKie** [comment]
The regression was introduced in #3224, specifically in 716d1af111818cce43194840971e65faa5f89415.

**Comment by SergeySmirnov-Akvelon** [comment]
Fix is [ported](https://github.com/dotnet/winforms/commit/6391b524dd64e7530eba986c6607bf129b3ec8ae) to master  branch

**Comment by Lydia-Shi** [comment]
Verified this issue in NET 5.0.100-rtm.20513.13, this issue is fixed. No exception is thrown when the ListView is in virtual mode and any items are selected.
![ListView](https://user-images.githubusercontent.com/54019172/95951056-4d1a9300-0e28-11eb-8215-74668751a654.gif)

**Comment by KlausLoeffelmann** [comment]
We need to test, if this still is a problem when using groups.
Working on a simple repo now, because this is happening in an internal Demo, too complex to easy investigate.

**Comment by KlausLoeffelmann** [comment]
I just tried it in .NET Framework. It's doesn't work there, either. Bummer. I am wondering, why not?

**Comment by RussKie** [comment]
From the stack trace it fails here:
https://github.com/dotnet/winforms/blob/a6ae0ec5c8b2d495c3ed293183b89cd71f66fa6c/src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs#L282-L287

`Items` collections can't be iterated over in `VirtualMode`: https://docs.microsoft.com/dotnet/api/system.windows.forms.listview.virtualmode#exceptions. An item can only be retrieved via `index`, which in virtual mode will go through `RetrieveVirtualItem` event.



> I just tried it in .NET Framework. It's doesn't work there, either. Bummer. I am wondering, why not?

With mydaids of permutations of all possible scenarios and configurations it isn't terribly surprising. Once we have a use case we can see what's missing.

**Comment by RussKie** [comment]
@KlausLoeffelmann please raise a new issue with a simple repro.
