### ISSUE TITLE
Improve localisation support by adding a way to bind control string properties to a specific resource type and key

### ISSUE THREAD

**Issue by IanKemp** [dotnet/winforms#3966]
Currently, WinForms allows you to localise your controls, which is good. However, localisation support is limited to the very simple case of having a resource file of the same name next to the control being localised. This prevents reuse of common strings across a project.

Ideally, any string property on a WinForms control should be able to be bound **at design-time** to any arbitrary resource key in any arbitrary resource file. To my mind, this will take one of two forms:

* A new property, `ResourceType`, on every control: if set, this will look on the specific type for resource keys of the same name as the autogenerated localisation resources, and attempt to bind to them.There should be validation to ensure the type being bound to defines the requisite keys for the control.
* The designer for every string property on a control will be changed to have a ... ellipsis button next to the property. If clicked, this will open a popout showing two dropdowns: a **resource type** and a **resource key**. The latter will depend on the former, and once a selection is made for both, the property in question will be bound to that resource type + key.

Note that the above is a hierarchical structure: first the control property's resource type + key will be checked, then the control's ResourceType for a matching key, and the standard infrastructure enabled by `form.Localizable` will be checked last. This enables extreme flexibility for localising resources.

**Will this feature affect UI controls?**

Yes, as above.

**Comment by merriemcgaw** [comment]
Thank you for your suggestion! At this stage, this doesn't fit with the current roadmap and significant effort will be required to analyze the possibilities. For now we're going to close this, but should we get a lot of customer feedback asking for this flexibility we will absolutely consider bringing it up from the backlog.
