### ISSUE TITLE
WInForms TGA support

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#3971]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/823406/winforms-tga-support.html)._

---
Would like for VS2019 WinForms to support TGAs at least as much as it supports other image formats. Simply displaying a TGA in a picturebox would be a good start.

---
#### Feedback Bot on 11/18/2019, 06:12 PM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.   We'll provide an update once the issue has been triaged by the product team.
#### Feedback Bot on 9/22/2020, 05:48 AM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it for community input</p>

**Comment by Olina-Zhang** [comment]
This is from external suggestion ticket, and @merriemcgaw wants to add it in here to track.

**Comment by JeremyKuhne** [comment]
GDI+ doesn't support TGA (System.Drawing.Image). WIC doesn't support this either. Without some native Windows support having this support in WinForms isn't very plausible. Demand would have to be very high to take an external image library dependency.
