### ISSUE TITLE
Review use of `CA1838` warning - Avoid 'StringBuilder' parameters for P/Invokes

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#3983]
To update the underlying SDK/toolsets to 5.0-RC1 we had to suppress `A1838 // Avoid 'StringBuilder' parameters for P/Invokes` in https://github.com/dotnet/winforms/pull/3959/commits/9dfaaa152b889f2040f646697dfb31c77d7058e8.

https://github.com/dotnet/winforms/search?q=CA1838

The suppression needs to be reviewed, and corrected.

**Comment by AraHaan** [comment]
Speaking of updating warnings why is hDrop here an ``IntPtr`` and not ``HandleRef`` or ``SafeHandle``?

https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs#L13-L16

**Comment by weltkante** [comment]
I don't think thats a handle? [doc](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-dragqueryfilew) says its a `HDROP` and I don't think thats something `CloseHandle` can operate on.

**Comment by AraHaan** [comment]
```
lpszFile

Type: LPTSTR

The address of a buffer that receives the file name of a dropped file when the function returns. This file name is a null-terminated string. If this parameter is NULL, DragQueryFile returns the required size, in characters, of this buffer.
```
Ah I thought everwhere that StringBuilder was used was for buffers... I got to change the code a bit more before I open a pr.

**Comment by weltkante** [comment]
> Ah I thought everwhere that StringBuilder was used was for buffers... I got to change the code a bit more before I open a pr.

Yes, your quote is about a buffer. Buffers are often optional, no contradiction here. What exactly did you have in mind?

**Comment by weltkante** [comment]
Looking at your PR you may be misunderstanding what "buffer" means. A buffer is a mutable memory area where the called function can write into. Specifically you can _not_ use C# `string` because it is immutable and not supposed to be modified.

**Comment by AraHaan** [comment]
> Looking at your PR you may be misunderstanding what "buffer" means. A buffer is a mutable memory area where the called function can write into. Specifically you can _not_ use C# `string` because it is immutable and not supposed to be modified. Using a C# string has the semantics of a readonly `LPCTSTR` (node the 'C' for const) but _not_ the semantics of a buffer.

RIP so ``Span<char>`` or ``char*`` might be the only way. I think using ``Span<char>`` could be better then for it.

**Comment by RussKie** [comment]
In the interop signatures we generally use `char*`, and there are different way to get to it depending on a situation.

**Comment by elachlan** [comment]
There is still the usage at:
https://github.com/dotnet/winforms/blob/15ab89b1017e0da7e7448118b3d0a80632c9f146/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeMethods.vb#L30-L33

@RussKie metioned that `Microsoft.VisualBasic.Forms` doesn't reference to the `System.Windows.Forms.Primitives` project directly and that the team would rather not add it as a dependency.

**Comment by RussKie** [comment]
@lonitra  and @JeremyKuhne will provide guidance.

**Comment by AraHaan** [comment]
I feel like at this point it would actually be more beneficial if it did reference it though.

Why? Because Visual Basic is dead in the aspects that it does not get new language features currently, but also the fact that c# makes it more easier to do things that vb lacks. As such I feel that at this point it really does not matter as much of the primitives is probably also internal.
