### ISSUE TITLE
With NET 5 RC2 SDK installed, "net5.0-windows" instead of "net5.0" should be displayed for winforms/wpf help description in CLI.

### ISSUE THREAD

**Issue by vdanche** [dotnet/winforms#3985]
**Repro steps:**
1.Install NET 5 RC2 build(5.0.100-rc.2.20466.4).
2. In CLI, run "dotnet new winforms --help" or "dotnet new wpf --help".
3. Check the help contents displaying.

**Expected Result:**
"net5.0" should be displayed as "net5.0-windows"

**Actual Result:**
Still display as "net5.0"
![image](https://user-images.githubusercontent.com/65637796/93433959-15d4c700-f8fa-11ea-9b46-de6792f0a95e.png)

**Comment by grinrag** [comment]
the TFM version is here https://github.com/dotnet/winforms/blob/ec688d7d10409fe3566e8eebaa066b962f38d9cb/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json#L36

**Comment by eriawan** [comment]
@merriemcgaw 
Could you assign this issue to me? Thanks in advance 🙂

**Comment by RussKie** [comment]
We had an internal discussion yesterday about the change, and resolved that the change to the templates isn't desirable as it would look inconsistent with other templates, and at the same time "net5.0-windows" also lacks clarity what Windows API are targeted.
There will be a follow up work internally (and possible externally as well) going forward, but for now this stays as is.
