### ISSUE TITLE
Winforms is still using netcoreapp5.0 instead of net5.0 as the TargetFramework

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/winforms#3989]
We embed the TargetFramework value in the assembly's metadata as part of the `TargetFrameworkAttribute`. I noticed that both winforms and wpf are still using netcoreapp5.0 as the tfm which got replaced by net5.0.

Do we know who reads that attribute and if we need to fix this before we ship?

cc @RussKie @JeremyKuhne @Tanya-Solyanik @ericstj

**Comment by ericstj** [comment]
I checked a default project and it also gets the value of 
```
[assembly: TargetFramework(".NETCoreApp,Version=v5.0", FrameworkDisplayName = "")]
```

So perhaps this is a complete non-issue.  Do you see anywhere else a binary might "observe" the difference of the project using `netcoreapp5.0` vs `net5.0` and record it in its final output?

**Comment by ViktorHofer** [comment]
I should have double checked as I assumed the short moniker is written into the metadata. I believe that runtimeconfig.json and other places use the net5.0 value instead but need to verify.

**Comment by ericstj** [comment]
No worries, I assumed the same.  I diffed a simple class library and didn't see any observable difference between `net5.0` and `netcoreapp5.0` so it might be fine.

**Comment by RussKie** [comment]
Thank you for checking. 
Is there anything we need to do, or should I close?

**Comment by ViktorHofer** [comment]
I would clean this up and replace all netcoreapp5.0 instances with net5.0 but only in master.

**Comment by RussKie** [comment]
@ViktorHofer should we be replacing `netcoreapp5` and `net5` to `net6` now?

**Comment by Ashley-Li** [comment]
Verified the issue based on .NET 6.0 Preview2[21127.3] Test Pass,the issue has been fixed that when create targets .NET6.0 app, the TargetFramework is net6.0, when create targets .NET5.0 app, TargetFramework is net5.0.
