### ISSUE TITLE
Remove *Permission and *Assert.'s from code

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#40]

**Comment by kevingosse** [comment]
Before I go too far on this (there's **a lot** of them), are we absolutely we want to remove all the SecurityPermission/UIPermission/Assert stuff? I understand they're no-op on .net core, but coreclr/corefx keep a few of them for the parts of code that are shared with .net framework. Are we positive we don't need to do the same thing for winforms?

**Comment by sharwell** [comment]
💭 I'm not sure why we would be removing `Debug.Assert` calls. I sometimes use those to document assumptions made at different points in code and I wouldn't be surprised to see similar things in some places here.

**Comment by kevingosse** [comment]
The CAS asserts, not the debug asserts :) 

For instance, https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/WinFormsSecurity.cs#L488

**Comment by karelz** [comment]
Thanks for picking up the issue @kevingosse! I added you to collaborators list. Once you accept, ping me here and I will be able to assign it to you. (assigning to myself temporarily)

@dotnet/dotnet-winforms FYI about collaborator trick (with Read permissions) - see https://github.com/dotnet/winforms/settings/collaboration

**Comment by kevingosse** [comment]
@karelz accepted
