### ISSUE TITLE
The drew size grip has extra pixels outside the bounds in the upper right corner when setting some specific width & height values for Rectangle object in ControlPaint.DrawSizeGrip method

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#4017]
* .NET Core Version: 
5.0.100-rc.2.20477.2

* Have you experienced this same bug with .NET Framework?: 
Yes

**More Info:**

1. It's not a regression issue, this issue occurs in .NET Framework and .NET Core 3.1 too.
2. If set the width & height values to (100, 100) or (120, 120) or (140, 140) or (160, 160) or others, this issue will not occurs.
3. If set the width & height values to (110, 110) or (130, 130) or (150, 150) or (170, 170) or others, this issue will occurs. 

**Problem description:**

In step2, the drew size grip has extra pixels outside the bounds in the upper right corner.
![Actual](https://user-images.githubusercontent.com/45864985/94423526-5c100d00-01bb-11eb-8d43-d9dc96434258.png)

**Expected behavior:**

In step 4, the drew size grip should not has the extra pixels outside the bounds in the upper right corner.
![Expected](https://user-images.githubusercontent.com/45864985/94423536-5fa39400-01bb-11eb-92c5-3402b3f07898.png)

**Minimal repro:**

[CoreTestApp.zip](https://github.com/dotnet/winforms/files/5291680/CoreTestApp.zip)
1. Launch the attached project in VS.
2. Run it and observe the the upper right corner of the drew size grip.
3. Stop the project, open the Form1.cs file, comment code line 22 and uncomment the code line 24. It will looks like below:
```
            //Rectangle bounds = new Rectangle(50, 30, 150, 150);

            Rectangle bounds = new Rectangle(50, 30, 160, 160);
```
4. Run the project and observe the the upper right corner of the drew size grip again.

**Comment by JeremyKuhne** [comment]
Nice find! This isn't something that we'd want to touch as there isn't a lot of value and the fix probably isn't simple. It does illustrate a good test case- values that are odd numbers or can't be split in to two even numbers.
