### ISSUE TITLE
Unable to identify scroll bar "Page down" or other internal scroll bar object using UIAutomation

### ISSUE THREAD

**Issue by preetipadalia** [dotnet/winforms#4020]
* .NET Core Version: 3.0.1.302

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
 scroll bar page down, page up buttons are unidentifiable using .netcore3.1. The same was working with net472.
![image](https://user-images.githubusercontent.com/36397242/94436977-c5dbe700-01ba-11eb-8655-d66adbba995f.png)

**Expected behavior:**
It should identify the objects with .net core also.

**Minimal repro:**
PFA the sample projects
[WindowsFormsApp1.zip](https://github.com/dotnet/winforms/files/5292473/WindowsFormsApp1.zip)
[NetCoreSample.zip](https://github.com/dotnet/winforms/files/5292475/NetCoreSample.zip)
[netframeworkCode.zip](https://github.com/dotnet/winforms/files/5292476/netframeworkCode.zip)

**Comment by Zheng-Li01** [comment]
@preetipadalia, failed to reproduce the issue with .NET Core SDK 3.1.402 came with the VS 16.7.4 & 5.0.100.rc.1.20452.10 came with the VS 16.8.0 Preview 3.1, could you please try to update your VS or try to upgrade your SDK version from https://dotnet.microsoft.com/download/dotnet-core to see if the issue still on here. 

**Repro Steps:**
1. Create a Core winforms project with a VScrollbar contorl.
2. Run the core project, and open the Inspect tool.
3. Observe the values in the inspect tool.
![UpdateCore](https://user-images.githubusercontent.com/38325459/94540300-df436880-0278-11eb-8ddc-9a531fca8938.PNG)

Please feel free let me know if you have any concerned.

**Comment by preetipadalia** [comment]
@Zheng-Li01 I am sorry if I confused you.  I can also see those objects using inspect tool. Let me reiterate my issue. 
We are automating windows Desktop applications using UIAutomation library. We were using net472 previously and now switched to .net core 3.1.

csproj file entries:

```
<?xml version="1.0" encoding="utf-8"?> 
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop"> 
  <PropertyGroup> 
    <OutputType>Library</OutputType> 
    <TargetFrameworks>netcoreapp3.1</TargetFrameworks> 
    <UseWPF>true</UseWPF> 
    <UseWindowsForms>true</UseWindowsForms>
```

We are using the following code to identify the objects at runtime using UIAutomation library.
```
using System.Windows.Automation;
PropertyCondition condition=new PropertyCondition(AutomationElement.NameProperty, “nameOfObject”)
AutomationElementCollection collection=windowElement.FindAll(TreeScope.Descendants, condition); 
```

Most of the objects are working but the objects inside the scroll bar are not identifiable using code.

**Comment by RussKie** [comment]
> We are using the following code to identify the objects at runtime using UIAutomation library.
> 
> ```
> using System.Windows.Automation;
> PropertyCondition condition=new PropertyCondition(AutomationElement.NameProperty, “nameOfObject”)
> AutomationElementCollection collection=windowElement.FindAll(TreeScope.Descendants, condition); 
> ```
> 
> Most of the objects are working but the objects inside the scroll bar are not identifiable using code.

@preetipadalia as I have already point at https://github.com/dotnet/core/issues/5194#issuecomment-695955384 you're using WPF libraries in this sample. 
We can look at issues pertaining to Windows Forms implementations, however WPF-related issue must be raised in the [WPF repo](https://github.com/dotnet/wpf).

**Comment by preetipadalia** [comment]
Closing as raised the issue in wpf repo.
