### ISSUE TITLE
[Accessibility] AccessibilityInsight for ListView: An element of the given ControlType must not support the Table pattern

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#4028]
* .NET Core Version: 
.Net SDK 5.0.100-rc.2.20477.2

* Have you experienced this same bug with .NET Framework?: 
Yes

**Minimal repro:**
1. Open the attached WinFormsApp9.zip application in VS, then build and run it.
[WinFormsApp9.zip](https://github.com/dotnet/winforms/files/5302743/WinFormsApp9.zip)
2. Open AccessibilityInsight tool to focus on ListView control to get result

**Actual behavior:**
An error about "An element of the given ControlType must not support the Table pattern" for ListView control
![image](https://user-images.githubusercontent.com/26474449/94634630-19f1e300-0303-11eb-9090-abf38f269bed.png)

**Expected behavior:**
No error is detected by AccessiblityInsight

**Comment by vladimir-krestov** [comment]
@Olina-Zhang, please test this issue for .NET 6.0. It looks like we have fixed it before.

**Comment by Olina-Zhang** [comment]
@vladimir-krestov  verified this issue in the latest .Net 6.0 build, it is fixed:
![image](https://user-images.githubusercontent.com/26474449/127626568-1cb2a47d-f43a-481f-b103-8a87aaf0b7a1.png)

Close this issue now.
