### ISSUE TITLE
ListView in virtual mode doesn't throw exception when user tries to add ListViewGroup

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4044]
**Is your feature request related to a problem? Please describe.**
ListView in virtual mode does not support ListViewGroup. If user tries to add ListViewGroup then he will see an exception. But if handle for ListView is not created then user has ability to add group to ListView. As result user has workaround for adding of group ListView in virtual mode, although ListViewGroups  are not supported by ListView

**Describe the solution you'd like and alternatives you've considered**
I suggest to throw exception regardless of whether the ListView has handle or not. Thus, the user will not be able to add a ListViewGroup to ListView in virtual mode

**Will this feature affect UI controls?**
It impacts on adding of ListViewGroups to ListView. But the current behavior of the ListView seems to be incorrect

**Comment by dreddy-work** [comment]
@SergeySmirnov-Akvelon , if this is quick we could take it in 6.0. Please mark PR with `doc-breakingchange`

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .net SDK 6.0 build: 6.0.100-rc.2.21465.13, it is fixed: an error dialog pops up when adding listViewGroup for ListView in virtual mode:
![image](https://user-images.githubusercontent.com/26474449/133572606-d25f6468-1f7d-4234-a35a-7d10906c1f12.png)

**Comment by Lydia-Shi** [comment]
Verified this issue with .NET SDK 7.0.100-alpha.1.21479.26, this issue is fixed.
