### ISSUE TITLE
OutOfMemoryException in .NET 5, thrown from Graphics.FromHdcInternal

### ISSUE THREAD

**Issue by albahari** [dotnet/winforms#4053]
* .NET Core Version: 
5.0.0-rc.1.20451.14 X64

* Have you experienced this same bug with .NET Framework?: 
No. Additionally, this bug does NOT occur in .NET Core 3.1.

**Problem description:**

I'm getting an OutOfMemoryException at least 5-6 times per day in an application when running under .NET 5 RC. The same application (same apart from the .runtimeconfig.json) has been running under .NET 3.1 for months, and by tens of thousands of users without the error occurring.

The exception is always thrown from System.Drawing.Graphics.FromHdcInternal(IntPtr). The exact stack trace varies (because FromHdcInternal is called from a number of places). Here's an example:

  at System.Drawing.Graphics.FromHdcInternal(IntPtr hdc)
  at System.Drawing.Font.GetHeight()
  at System.Drawing.Font.get_Height()

Here's another example:

-System.Drawing.Graphics.FromHdcInternal(IntPtr hdc)
-System.Windows.Forms.DrawingEventArgs.GetOrCreateGraphicsInternal(System.Action`1[System.Drawing.Graphics]) offset: 0x65
-System.Windows.Forms.PaintEventArgs.get_Graphics()

I've checked the process statistics when this error occurs and nothing is out of the ordinary. Here's a typical sample:
  Private working set: 215MB
  Handles: 1247
  User objects: 488
  GDI objects: 288

I've also checked my code base to ensure that there are no cases of GDI objects such as Brushes not being disposed. I've also checked with the individual stack traces that nothing is being disposed that shouldn't (e.g., that the Font objects is not being disposed before calling the .Height property).

This error occurs randomly after the program has been running for a while, so I can not provide a series of steps to reproduce it. As I understand, the OutOfMemoryException doesn't actually indicate an out-of-memory condition. Could the error reporting be upgraded to generate a more meaningful message?

As I mentioned, this application is in use by tens of thousands of people under .NET 3.1. I won't be able to upgrade to .NET 5 if the issue remains at RTM.

**Comment by RussKie** [comment]
Please test the RC2 or better yet the latest daily
________________________________

**Comment by albahari** [comment]
Thanks for the prompt response - I've just installed the latest daily. I'll keep you posted.

**Comment by albahari** [comment]
This seems to be fixed - I'm closing the issue for now

**Comment by RussKie** [comment]
Great to hear. Thanks for the follow-up.
________________________________
