### ISSUE TITLE
Winforms availability in Visual Studio Tools for Office (VSTO)

### ISSUE THREAD

**Issue by AndresLuga** [dotnet/winforms#4061]
Please make the new Winforms available for Visual Studio Tools for Office. VSTO add-ins using C# and Winforms is a very powerful tool for extending Office, which is currently available only using legacy NET. 

For more details and use cases please see:
https://developercommunity.visualstudio.com/idea/757925/please-port-visual-studio-tools-for-office-vsto-to.html?childToView=1201801

**Comment by weltkante** [comment]
Currently there are no plans to interop or integrate with Office, see [here](https://github.com/dotnet/winforms/issues/1763#issuecomment-653125277) for a discussion of fixing Office Addin support which was available on Desktop Framework.

> For now, the guidance from Office for Add-In developers is to use their JavaScript based Add-in engine and I haven't seen much appetite to do much with a .NET based approach. That may change in the future however

While Office Addin support and VSTO support are not the same I assume there is currently no interest and/or capacity to support either.

**Comment by RussKie** [comment]
I am afraid I have bad new for you all - we won't be not be updating VSTO or the COM Add-in platform to use .NET Core or .NET 5+. For more details please refer to https://github.com/dotnet/core/issues/5156#issuecomment-853430132.
