### ISSUE TITLE
Add appcompat for shared assembly System.Drawing between winforms and corefx and also between winforms and Desktop.

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#407]
System.Drawing.dll exists in corefx and winforms. Winforms assembly is expected to be a super-set of corefx version and should win at load time in all applicable scenarios.  To make sure of this,  We made file version of this assembly in winforms higher than the corefx version. We also need to add appcompat in the build process to make sure we never go out of sync of these assumptions.

**Comment by zsd4yr** [comment]
@dreddy-work isn't this in?

**Comment by zsd4yr** [comment]
Need to regenerate our facade in the case the Core FX adds types. This test in the build will ensure *this*.

**Comment by dreddy-work** [comment]
This is not in. this is same as issue #580

**Comment by JeremyKuhne** [comment]
This shouldn't be a problem anymore.
