### ISSUE TITLE
Add API for drawing dotted border around the ToolStipButton

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4070]
**Is your feature request related to a problem? Please describe.**
As a now, while navigating through Keyboard that focus is not clearly visible on "Categorized", "Alphabetical" and " Property Pages". As a result, it is difficult for people with vision problems to use these buttons. As #3659 suggested, a dotted border for these buttons would make it easier for the user to work with this control
![3659-issue](https://user-images.githubusercontent.com/23376742/95464038-2e2c8480-0982-11eb-8e8b-f26176e069db.gif)

**Describe the solution you'd like and alternatives you've considered**
Add the dotted border for ToolStripButton

API:
```
public class ToolStripButtonBorderRenderEventArgs : ToolStripItemRenderEventArgs
{
    /// <summary>
    /// This class represents all the information to render the ToolStrip
    /// </summary>
    public ToolStripButtonBorderRenderEventArgs(Graphics g,
                                                ToolStripItem item,
                                                Rectangle borderRectangle,
                                                Color borderColor,
                                                int borderWidth,
                                                ButtonBorderStyle buttonBorderStyle) : base(g, item)
    {
        if (item is null)
        {
            throw new ArgumentNullException(nameof(item));
        }

        BorderWidth = borderWidth;
        BorderColor = borderColor;
        BorderRectangle = borderRectangle;
        ButtonBorderStyle = buttonBorderStyle;
    }

    ///  The color of border
    internal Color BorderColor { get; set; }

    /// <summary>
    ///  The width of border
    /// </summary>
    public int BorderWidth { get; set; }

    /// <summary>
    ///  The rectangle to draw the border
    /// </summary>
    public Rectangle BorderRectangle { get; set; }

    /// <summary>
    ///  The border style
    /// </summary>
    public ButtonBorderStyle ButtonBorderStyle { get; set; }
}
```
and new methods in ToolStripRender:
```
public event EventHandler<ToolStripButtonBorderRenderEventArgs> RenderButtonBorder
{
    add => AddHandler(EventRenderButtonBorder, value);
    remove => RemoveHandler(EventRenderButtonBorder, value);
}

public void DrawButtonBorder(ToolStripButtonBorderRenderEventArgs e)

protected virtual void OnRenderButtonBorder(ToolStripButtonBorderRenderEventArgs e)

```
This API is suggested in line with the API of other methods in ToolStripRender class and will be used in `ToolStripButton.OnPaint` method:
```
if (Selected)
{
    renderer.DrawButtonBorder(new ToolStripButtonBorderRenderEventArgs(e.Graphics, this, ClientBounds, Color.Black, 1, ButtonBorderStyle.Dotted));
}
```
An excellent visualization of what this might look like after fixing:
![3659-fixed](https://user-images.githubusercontent.com/23376742/95464731-f70aa300-0982-11eb-9ed5-a9bb08d8808c.gif)

**Will this feature affect UI controls?**
Yes.

**Will VS Designer need to support the feature?**
It would be nice to use this to PropertyGrid in VS

**What impact will it have on accessibility?**
This will make it easier for people with vision problems to use this control.

**Will this feature need to be localized or be localizable?**
This feature does not need localization

**Comment by Tanya-Solyanik** [comment]
@SergeySmirnov-Akvelon, could you please experiment with Office, WPF or some win32 applications (mmc.exe for example) and find out what focus indicator they use? On the one hand, we want to be consistent with the existing UI, on the other the dotted border might not be visually prominent enough. Though I can see that chrome uses the dotted line - 
![image](https://user-images.githubusercontent.com/15823268/95525269-84042b00-0988-11eb-9ea5-fa4647c9f7b6.png)

**Comment by SergeySmirnov-Akvelon** [comment]
@Tanya-Solyanik, the use of the dotted box was suggested by Merrie in [this](https://github.com/dotnet/winforms/issues/3659#issuecomment-666772129) comment. But anyway, this API is intended for drawing a border around ToolStripButton and allows to draw any type of border, depending on the passed parameters

**Comment by SergeySmirnov-Akvelon** [comment]
I have investigated several applications (Paint, Office, mms.exe). We mainly use a background color with a thin border for selection:
![4070-paint](https://user-images.githubusercontent.com/23376742/95577452-d69e1f80-0a3a-11eb-81bf-da47ff0d8e35.jpg)
![4070-office-border](https://user-images.githubusercontent.com/23376742/95577492-ec134980-0a3a-11eb-90ac-3167b7cbcc3f.jpg)
![4070-mms](https://user-images.githubusercontent.com/23376742/95577510-f2092a80-0a3a-11eb-9a05-594095b6cccc.jpg)

For case from ProprtyGrid in Office we use next way:
![4070-office](https://user-images.githubusercontent.com/23376742/95577545-00efdd00-0a3b-11eb-88f4-dae865d880d1.jpg)

Unfortunately buttons on PropertyGrid has less background contrast than Office

**Comment by SergeySmirnov-Akvelon** [comment]
Currently, we have two ways for highlighting of focused buttons:
The first way is to highlight the button by color and border. For example Paint:
![paint](https://user-images.githubusercontent.com/23376742/95744515-19aafd80-0c9c-11eb-9e31-d457b684146b.png)
In this case the PropertyGrid will look like this:
![4070 - pg](https://user-images.githubusercontent.com/23376742/95745455-ccc82680-0c9d-11eb-83ba-bc0d46645c38.png)


The second way, highlight the button by color only. For example Word:
![Word](https://user-images.githubusercontent.com/23376742/95744562-2deefa80-0c9c-11eb-8520-b076a26d8023.png)

Unfortunately, both ways has contrast less than 3:1.

@guybark, could you please share your opinion on how to highlight the focused button?

**Comment by merriemcgaw** [comment]
After talking with the internal SMEs we've determined that this new isn't required at this point in time. Color contrast of button borders is a nice to have, rather than a must have and we should consider offering it in the ToolStrip level once new requirements come out. But we don't have to at this point in time so I'm going to close this issue. When we do this work, we will coordinate with the underlying OS and the Controls Club recommendations for ToolStrips when they're formed.
