### ISSUE TITLE
[Accessibility] An element of the given ControlType must support the ExpandCollapse pattern for DateTimePicker control

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#4099]
* More info:
This is not regression issue, also can reproduce on .NET Framework & .NET Core 3.1 & NET Core 5.0.

* .NET Core Version: 
.NET SDK 6.0.100-alpha.1.20513.14

* Have you experienced this same bug with .NET Framework?: 
 Yes 

**Problem description:**
An error appeared for DateTimePicker control that 'An element of the given ControlType must support the ExpandCollapse pattern'.

**Minimal repro:**
1. Create a winforms core project with a DateTimePicker control.
2. Build and run the core project.
3. Observe DateTimePicker  using the Accessibility Insight & Inspect tools .

Or
1. Open the attached project.
[CoreProjectIssue.zip](https://github.com/dotnet/winforms/files/5376061/CoreProjectIssue.zip)
2. Build and run it.
3. Observe the DateTimePicker using Accessibility Insight & Inspect tools.

**Actual behavior:**
In the Accessibility Insight tool, an error 'An element of the given ControlType must support the ExpandCollapse pattern' appeared.
In the inspect tool, the 'IsExpandCollapsePattermAvaliable' property value is false.
![CoreNewIssue](https://user-images.githubusercontent.com/38325459/95951853-b4851280-0e29-11eb-9b53-7e4a43c30a4d.PNG)

**Expected behavior:**
No error appeared.

**Comment by merriemcgaw** [comment]
The bug is in the underlying common control. We will need to see if they can fix it (and then do anything needed to expose it) or eventually do that on our own. Marking for accessibility backlog and future so we don't lose it but it's not high on the priority list.

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .NET 6.0.100-rc.2.21460.37 build, the issue has been fixed that the DataTimePicker control have supported the ExpandCollapse pattern in the inspect tool & Accessibility tool. For Narrator tool, hitting known issue [5478](https://github.com/dotnet/winforms/issues/5487)
![image](https://user-images.githubusercontent.com/38325459/133044924-a5c836eb-d1be-4f34-8e01-075515ac15af.png)

**Comment by Ashley-Li** [comment]
Verified this issue on .NET 6.0 RC2 test pass build: 6.0.100-rc.2.21473.26, it was fixed.

**Comment by Jenna-Zheng** [comment]
Verified this issue with latest .NET 7.0.100-alpha.1.21479.21 build, it was fixed
