### ISSUE TITLE
[Accessibility] Some list items of Cursor property are displayed incorrectly in Inspect

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#4101]
* .NET Core Version: 
.NET SDK 6.0.100-alpha.1.20513.14

* Have you experienced this same bug with .NET Framework?: 
No

* More Info: 
This is a not regression issue, it occurs after issue [2074](https://github.com/dotnet/winforms/issues/2704) fixed.

**Problem description:**
Some list items of Cursor property in Inspect are incorrect. 
when focus on Hsplit list item, it should display "[Cursor: Hsplit]" as Help item, but it displays "[Cursor: System.Windows.Forms.Cursor]".
![actual](https://user-images.githubusercontent.com/62929087/95954029-4b9f9980-0e2d-11eb-844f-8ff7875e5a3c.png)

**Expected behavior:**
When focus on Hsplit list item, it should display "[Cursor: Hsplit]" as Help item in Inspect.

**Minimal repro:** 
[SampleApp.zip](https://github.com/dotnet/winforms/files/5376399/SampleApp.zip)
1. Create a winforms core app with PropertyGrid and Button control.
2. Associate the Button with PropertyGrid as a selected object.
3. Build and run the core project.
4. Start Inspect tool.
5. Open the drop down list items next to Cursor.
6. Focus on HSplit item and observe it in Inspect.

**Comment by merriemcgaw** [comment]
Great find! I don't think this will meet the bar to do anything about unless it starts to block a customer or partner. We'll take another look if that happens. For now, closing.

**Comment by RussKie** [comment]
We've looked at this issue with @SergeySmirnov-Akvelon, and unfortunately it is due to how we instantiate these cursors from stream, and there was no obvious or easy fix.
