### ISSUE TITLE
UI Larger in Framework 5

### ISSUE THREAD

**Issue by CarlosBressan** [dotnet/winforms#4107]
* .NET Core Version: 
.NET 5.0 SDK (SDK 5.0.100-preview.7 de 21/07/2020) x86 

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
The same form has different sizes in net462 and net5.0, even being in the same multi target project.

![image](https://user-images.githubusercontent.com/50844862/96028522-c5388700-0e2f-11eb-8687-f6838ddd4a1e.png)

**Expected behavior:**
The form should has the same size for any framework

**Minimal repro:**
[TestUI.zip](https://github.com/dotnet/winforms/files/5380076/TestUI.zip)

**Comment by RussKie** [comment]
This is by design due to the change of the `DefaultFont` (https://github.com/dotnet/winforms/pull/656).
More information is here: https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core#default-control-font-changed-to-segoe-ui-9-pt
