### ISSUE TITLE
Replace deprecated `SHILCreateFromPath` with `SHParseDisplayName`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#4112]
**Is your feature request related to a problem? Please describe.**

[`SHILCreateFromPath`](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHILCreateFromPath.cs) has been marked as [deprecated](https://docs.microsoft.com/windows/win32/shell/deprecated-api), and needs to be replaced with the [`SHParseDisplayName`](https://docs.microsoft.com/windows/desktop/api/shlobj_core/nf-shlobj_core-shparsedisplayname).

As raised in https://github.com/dotnet/winforms/pull/4108#discussion_r504969458

**Comment by wreuel** [comment]
Hello @RussKie how could help with this one?

**Comment by RussKie** [comment]
Hi @wreuel, as per the original post - [`SHILCreateFromPath`](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHILCreateFromPath.cs) needs to be removed and replaced with the [`SHParseDisplayName`](https://docs.microsoft.com/windows/desktop/api/shlobj_core/nf-shlobj_core-shparsedisplayname). Then the change needs to be verified for correctness.

Please let me know if you keen on tackling this, and I'll assign it to you.

**Comment by wreuel** [comment]
Hi @RussKie just looked up how is it now, and I think I could help you with that!

**Comment by RussKie** [comment]
Awesome! Holler if you get stuck or have questions.

**Comment by wreuel** [comment]
@RussKie I do believe, I have done right, the test for this change is running good, but I couldn't run all the tests, there always getting some issues.
