### ISSUE TITLE
Design Font Size Different From Execution

### ISSUE THREAD

**Issue by CarlosBressan** [dotnet/winforms#4115]
* .NET Core Version: 
.NET 5.0 SDK (SDK 5.0.100-preview.7 de 21/07/2020) x86
Microsoft Visual Studio Community 2019 Version 16.7.6

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
The font size appears different in the execution comparing with the designer.

![image](https://user-images.githubusercontent.com/50844862/96140236-18651500-0ed6-11eb-9385-e0b50287f80c.png)

**Expected behavior:**
Same font size in the design and execution.

**Minimal repro:**
[TestUI.zip](https://github.com/dotnet/winforms/files/5385450/TestUI.zip)

**Comment by dreddy-work** [comment]
Thanks @CarlosBressan  for reporting this. Few questions.

- Did you try this with latest .NET core ([SDK 5.0.100-rc.2](https://dotnet.microsoft.com/download/dotnet/5.0))available?

- I used same test application you provided and i see following. But, I have latest runtime.

![image](https://user-images.githubusercontent.com/36968667/96287044-2f6b3c00-0f96-11eb-8f04-a4e88a8f2459.png)

**Comment by CarlosBressan** [comment]
Hi @dreddy-work , I'm using the preview version ando gonna try the RC.2.

**Comment by CarlosBressan** [comment]
Hi @dreddy-work , I did the upgrade, but it not work.

![image](https://user-images.githubusercontent.com/50844862/96456589-0dbbc000-11f5-11eb-9253-381db61a1133.png)

What more can I try?

**Comment by dreddy-work** [comment]
I see the repro.  In core, we added a new template that brings in some of the High DPi nature and somehow that is interacting with the Font. @KlausLoeffelmann , can you take a look at this porting scenario and see how we can support it?

**Comment by KlausLoeffelmann** [comment]
Well, yes. Can you try to use 16.8 Preview 4 and create a project from the templates provided with that version?
I think, you're app is running in `Unaware`, while the Designer is running in `SystemAware` HighDpiMode.

When you create a net5 VB WinForms app (you need the latest [.NET 5 SDK](https://aka.ms/dotnet/net5/5.0.1xx/daily/Sdk/dotnet-sdk-win-x64.exe) for this to work!), you will be enable to use the VB Application Framework. With it, a) `SystemAware` will automatically be activated as the Default HighDpiMode, and b) you will be able to set `HighDpiMode` yourself, by setting up the `ApplyHighDpiMode` Application event in ApplicationEvents.vb.

**Comment by KlausLoeffelmann** [comment]
Hey @CarlosBressan,

I will close this for now. If you think this still needs to be further investigated, you can reopen this anytime!

**Comment by CarlosBressan** [comment]
Following the new template of the Windows Forms for Visual Basic .Net, it works.
