### ISSUE TITLE
Utilize function pointers for interop

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#4135]
Function pointers provide better performance. Creating this issue to discuss utilizing them in Windows Forms interop.

Things we should consider / look at:

- Win32 callbacks
- High usage COM interfaces
- ?

**Comment by JeremyKuhne** [comment]
Some Runtime changes:

https://github.com/dotnet/runtime/pull/43514
https://github.com/dotnet/runtime/pull/39752
https://github.com/dotnet/runtime/pull/39082

**Comment by elachlan** [comment]
@RussKie Should we close this issue because of #7445 or does this compliment it?

**Comment by RussKie** [comment]
Thank you for going through the backlog. If we're importing callbacks from CsWin32 then, I think, we can close it. If we still have manually created callbacks - then I think this may still be relevant.

I let @JeremyKuhne to make a call on this, since he's opened the issue.

**Comment by JeremyKuhne** [comment]
We've been doing this now, no longer a need to track.
