### ISSUE TITLE
ComponentActionsType is defined in the incorrect namespace

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/winforms#4137]
It appears that this was completely accidental, but the `ComponentActionsType` is declared in the incorrect namespace in .NET Core. On .NET Framework, it was declared in `System.ComponentModel.Design` but is declared in `System.Windows.Forms.Design` in .NET Core. This type is intended to be used the `DesignerActionService.GetComponents(...)` method, which is correctly declared in `System.ComponentModel.Design`.

**Comment by DustinCampbell** [comment]
FWIW, I think usage of this type is probably _extremely_ low, so it's probably not worth fixing. I would assume this was mis-ported in .NET Core 3.x.

**Comment by RussKie** [comment]
Would a type forward fix it?

**Comment by RussKie** [comment]
Accepting the issue. If we get more feedback we'll re-open.
