### ISSUE TITLE
[Designer] Undo / Redo not working correctly.

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#4139]
* .NET Core Version: All.

* Have you experienced this same bug with .NET Framework?: No.

**Problem description:**
As @dreddy-work [asked](https://github.com/dotnet/winforms/issues/3047#issuecomment-712482616) this is tracking only issue.
Undo / Redo not working correctly in new designer (V.S. 16.8 p4):
![vsd1](https://user-images.githubusercontent.com/17767561/96553066-4c1cb200-12bd-11eb-9b7d-f4a81138918d.gif)
![vsd2](https://user-images.githubusercontent.com/17767561/96553075-4f17a280-12bd-11eb-80c3-b2ada4650a1e.gif)

**Expected behavior:**
Undo / Redo working correctly.

**Comment by Zheng-Li01** [comment]
@dreddy-work, @kirsan31, actually, for this issue, the first part, have the issue [2395 ](https://github.com/dotnet/winforms-designer/issues/2395)in the dotnet/winforms-designer repo to track it; for the second part, have the issue  [2396](https://github.com/dotnet/winforms-designer/issues/2396) in the dotnet/winforms-designer repo to track it. please have a look.

**Comment by merriemcgaw** [comment]
Don't forget to file VS Feedback when you have VS related issues and post the link in here. That way it is quickly bumped onto my radar and we've got the ability to collect that diagnostic information. This is a tracked problem area though so I will close this issue and let you know when we've closed the underlying bugs.
