### ISSUE TITLE
VS should not bloat SDK project files with resx designer entries

### ISSUE THREAD

**Issue by madelson** [dotnet/winforms#4144]
(Copied from https://developercommunity2.visualstudio.com/myfeedback?port=1025&fsid=9bbd6d1d-30dd-4380-b94e-af5035a8459d&entry=myfeedback where I was told to report this here instead)

With the new SDK file format, my team was excited to say goodbye to bloated csproj files using the new globbing feature. For example, to include resx files we use the following glob:

```
<!--Configure .resx files as embedded resources with generated . Designer.cs files.-->
<ItemGroup>
<Compile Update="**\*. Designer.cs">
<AutoGen>True</AutoGen>
<DesignTime>True</DesignTime>
<DependentUpon>$([System.String]::Copy('%(FileName)'). Replace('. Designer', '.resx'))</DependentUpon>
</Compile>
<EmbeddedResource Update="**\*.resx">
<Generator>ResXFileCodeGenerator</Generator>
<LastGenOutput>$([System.String]::Copy('%(FileName)')). Designer.cs</LastGenOutput>
</EmbeddedResource>
</ItemGroup>
<LastGenOutput>$([System.String]::Copy('%(FileName)')). Designer.cs</LastGenOutput>
</EmbeddedResource>
```

Unfortunately, when we add new resx files to the project VS insists on still adding an entry for each designer file like:

```
<Compile Update="Globalization\TestResx.Designer.cs">
<DesignTime>True</DesignTime>
<AutoGen>True</AutoGen>
<DependentUpon>TestResx.resx</DependentUpon>
</Compile>
```

It would be great if VS could handle this more gracefully, either by detecting that the designer file is already getting configured in the same way or by emitting a single glob entry that covers all similar designers if one is not already present (not sure how feasible the latter is if you have multiple kinds of designer files).

**Comment by dreddy-work** [comment]
Thanks @madelson for reporting this. While the work for resource Serialization/Deserialization is still in progress for Core, this particular issue might be handled by the https://github.com/dotnet/project-system. Will get a confirmation from the team before transferring the issue there.

**Comment by dreddy-work** [comment]
There are multiple scenarios that end up adding resources to project file. Some of which are Winforms owned and other are from Project System. We are looking into it. Will update this thread as we progress on those.

**Comment by dreddy-work** [comment]
We are moving this to Project system repo. Please follow up on there on progress.

**Comment by dreddy-work** [comment]
@madelson as FYI. This work item will disappear from here :)
