### ISSUE TITLE
Steema.TeeChart.NETCore.WinForm control is not fully supported by current version of Windows Forms Designer for .NET Core

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#4147]
- .NET Core Version:
   3.1.9

- Have you experienced this same bug with .NET Framework?:
   No

**Problem description**:
I've created .NET Core WinForms application and added **Steema.TeeChart.NETCore.WinForm** nuget-package.
As I can see Steema.TeeChart.NETCore.WinForm control is not fully supported by current version of Windows Forms Designer for .NET Core even in latest Visual Studio 2019 16.8.0 Preview 4 (some menu items are missing in .NET Core 3.1.9):

![a](https://user-images.githubusercontent.com/36968667/96782759-2fa67580-13a2-11eb-8f21-f2de18f8fbfb.png)

Same menu in .NET Framework 4.8 looks like:
![b](https://user-images.githubusercontent.com/36968667/96782874-37661a00-13a2-11eb-9082-4addfc6402ea.png)

[Some more info](https://www.steema.com/support/viewtopic.php?f=4&t=17436#p77609)
[Sample repo](https://github.com/bairog/TeeChartTest)

What is the expected timeframe for Windows Forms Designer for .NET Core to fully support third-party components? Is it finally going to be happend in Visual Studio 2019 16.8 in November 2020?

P. S. I've tried to email that problem to @OliaG, but 5 days had no answer.

Thank you.

**Expected behavior:**
Functional parity with Windows Forms Designer for .NET Framework.

**Comment by dreddy-work** [comment]
Bringing this issue back to the runtime repo so the bug owner can see the status and reply from the team.

Winforms Core designer SDK is not publicly available yet for third party controls. If third party control doesn't have a designer derived from the Core designer, its not going to work as expected.

**Comment by merriemcgaw** [comment]
We are working on our external docs to give control vendors the information and architecture they need in order to build 3rd party controls. Stay tuned, and we'll make sure to announce when those docs are available. In the meantime I'm closing this as external and recommend contacting the vendor to begin their work to port controls to .NET Core.
