### ISSUE TITLE
Fresh winforms project in VS can't load the winforms designer

### ISSUE THREAD

**Issue by cadilhac** [dotnet/winforms#4148]
Using VS 2019 preview 16.8.0 preview 5.0

I created a new winforms project (.net core 3.1). Trying to open the form in the designer, I get a VS error letting me know that details are in the activity log xml file:

![forms1](https://user-images.githubusercontent.com/50608/96906283-95106a00-1467-11eb-8941-8dfe4c60600b.png)

In the xml file:

CreateInstance failed for package [Windows Forms Remote Designer Hosting Package]Source: 'mscorlib' Description: Could not load type 'Microsoft.VisualStudio.Design.VSDesignPackage' from assembly 'Microsoft.VisualStudio.WinForms.Package, Version=0.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.Design.VSDesignPackage' from assembly 'Microsoft.VisualStudio.WinForms.Package, Version=0.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)

VS also displays this:

![forms2](https://user-images.githubusercontent.com/50608/96906218-82963080-1467-11eb-81ea-f4a9b8aa07e8.png)

Any idea?

**Comment by merriemcgaw** [comment]
I'm not having any trouble with this scenario at all on a clean machine. Could you try ensuring you have the preview features selected for both "Use WinForms .NET Core Designer" and "Load Projects Faster" are selected. You might also try on a clean VM, or repairing your VS install. If you still have trouble please file a VS Feedback/Developer Community ticket and give us the link here. The direct link will speed getting the feedback into my hands. And doing the VS Feedback allows us (with your consent) to collect more diagnostic telemetry. Let me know how it goes.

**Comment by cadilhac** [comment]
I decided to completely uninstall VS and reinstall. Guess what? IT now works. So something was broken at some point and we will never know what actually happened.
