### ISSUE TITLE
Double click allows to check item in the ListView that is in virtual mode

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4156]
.NET Core Version: 
- .Net SDK 5.0.100-rc.2.20479.15
- .Net SDK 3.1.7

Have you experienced this same bug with .NET Framework?: 
- Yes

**Minimal repro**
1. Create application with textbox and ListView that is in virtual mode
2. Enable Checkboxes and add items to ListView.
3. Or use attached project ([ListViewVirtualMode.zip](https://github.com/dotnet/winforms/files/5438099/ListViewVirtualMode.zip))
4. Run application
5. Execute double click on checkbox of any item
6. Switch the focus to the textbox and move the focus back to the ListView.
![listview-doubleclick](https://user-images.githubusercontent.com/23376742/97159454-f5ffb100-178b-11eb-96c6-90bd4287f899.gif)

**Actual behavior:**
Checkbox changes state

**Expected behavior:**
Checkbox should not change state.

**Note:**
We have additional validation of virtual mode for [mouse click](https://github.com/dotnet/winforms/blob/26ee7b5fea05516d1caa83b94995c54115c148a1/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L5813) and ["space" key](https://github.com/dotnet/winforms/blob/26ee7b5fea05516d1caa83b94995c54115c148a1/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L6587). Looks like we forgot to add a similar validation for double click

**Comment by Zheng-Li01** [comment]
Verified the issue with 6.0.100-alpha.1.20623.10,the issue has been fixed that there have the same behavior between .NET Framework and .NET Core, see below GIF.
![UpdateCoreIssue](https://user-images.githubusercontent.com/38325459/103130637-86009f00-46d8-11eb-92ef-6653968dd27b.gif)

**Comment by Amy-Li03** [comment]
Verified this issue with .Net 6.0 latest build: .NET SDK 6.0.100-alpha.1.21062.11, issue was fixed. The checkbox doesn't change its value on a double click when ListView is in virtual mode.

Fixed:
![Fixed](https://user-images.githubusercontent.com/62929087/104400853-0c005f00-558e-11eb-91f7-4fa663ccab07.gif)
