### ISSUE TITLE
Redrawing doesn't work immediately when user clicks on checkboxes of items of ListView that is in virtual mode.

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4158]
.NET Core Version:
* .Net SDK 5.0.100-rc.2.20479.15
* .Net SDK 3.1.7

Have you experienced this same bug with .NET Framework?: 
* Yes

**Minimal repro:**

1. Create application with ListView that is in virtual mode.
2. Enable checkboxes and add several items.
3. Or use attached project ([ListViewVirtualMode.zip](https://github.com/dotnet/winforms/files/5438564/ListViewVirtualMode.zip))
4. Run application
5. Execute double click on any checkbox.
![listview-redrawing](https://user-images.githubusercontent.com/23376742/97169522-44687c00-179b-11eb-9ca7-c9e12bda2865.gif)

**Actaul:**
Checkbox state is not updated.

**Expected:**
Checkbox state should be updated.

**Note:**
If we enable checkboxes for an items in virtual mode (mouse click and "space" button), the elements are also not redrawn immediately. Moreover, we think that adding functionality that allows changing the checkbox value of ListView that is in virtual mode can create additional problems for the user. ListView in virtual mode can be mapped to DB data and thus the user gets the opportunity to edit this data what was not originally planned. We consider that it is safer if the user himself implements his own behavior for this case.

I found that user can imitate check/uncheck logic for ListView that is in virtual mode using the following code:
```
// Updating the "Checked" property by "Space" button
private void ListView1_KeyPress(object sender, KeyPressEventArgs e)
{
    if (Char.IsWhiteSpace(e.KeyChar))
    {
        listView1.FocusedItem.Checked = !listView1.FocusedItem.Checked;
        listView1.Invalidate();
    }            
}

// Updating the "Checked" property by mouse click
private void ListView1_Click(object sender, EventArgs e)
{
    Point mousePosition = listView1.PointToClient(Control.MousePosition);
    ListViewHitTestInfo hit = listView1.HitTest(mousePosition);
    if (hit.Location == ListViewHitTestLocations.StateImage)
    {
        hit.Item.Checked = !hit.Item.Checked;
        listView1.Invalidate();
    }                      
}
```

Unfortunately, updating of "Checked" property doesn't trigger "onItemCheck" and "onItemChecked" events (although these events are called when ListView is in non-virtual mode)

**Comment by merriemcgaw** [comment]
Let's close this issue, it's been this way forever, and virtualized ListViews aren't a mainline scenario, someone can re-file/reopen if it becomes an issue.
