### ISSUE TITLE
OnInitialize fails to compile if VB Compile Options changes in project

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#4178]
* .NET Core Version: 
 5.0.100-rc.2.20479.15

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Create New VB WInforms Solution, Change Options in 
```XML
<OptionStrict>On</OptionStrict>
<OptionInfer>Off</OptionInfer>
``` 
3 error trying to compile
![image](https://user-images.githubusercontent.com/12789369/97769933-1ca34c00-1aec-11eb-9be0-f25f1782d617.png)

**Expected behavior:**
No Errors

**Minimal repro:**
New VB WinForms Project
This is not the smallest possible, but it is real.
https://github.com/paul1956/DirectoryTestGenerator

**Comment by paul1956** [comment]
If Below
```VB
Dim eventArgs = ApplyHighDpiModeEventArgs(
    If(
        _highDpiMode Is Nothing,
       HighDpiMode.SystemAware,
       _highDpiMode.Value))
```
Was changed to 
```VB
Dim eventArgs As New ApplyHighDpiModeEventArgs(
    If(
        _highDpiMode Is Nothing,
       HighDpiMode.SystemAware,
       _highDpiMode.Value))
```
The code would not break no matter the Option Settings

**Comment by paul1956** [comment]
@RussKie I would submit PR for fix if I know what project this is in, and its not internal.

**Comment by RussKie** [comment]
@paul1956 I wouldn't know where to start myself :) I'll do some leg work to find out.

**Comment by paul1956** [comment]
@RussKie many of the templates still could use some cleanup, this file is the only place I have run into that causes a compile error vs just a suggestion.

**Comment by KlausLoeffelmann** [comment]
Hey Paul - good catch!
However, I don't think this meets the bar for servicing, since this whole thing goes away once we have the .NET 6 changes take over, and also it's a niche case, which can be fixed quite easily. But I would like @KathleenDollard's opinion about this. Thanks.

**Comment by Marie-Shi** [comment]
Verified this issue with .Net 6.0.100-alpha.1.20623.10, it is fixed. There is no error when compiling this solution.
![Untitled](https://user-images.githubusercontent.com/45864017/103070260-2208a880-45fc-11eb-9d57-6cc6b37f4163.png)
