### ISSUE TITLE
Fix XML triple slash docs per docs team suggestions

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/winforms#4194]
See feedback in https://github.com/dotnet/dotnet-api-docs/pull/5078 for suggestions.

1. Make the fixes in winforms source
2. Get those changes merged into main
3. Regenerate the XML docs and PR them into the dotnet-api-docs repo
   * See https://github.com/dotnet/winforms/issues/4163#issuecomment-718165661 for instructions on how to do that

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 @SimonZhao888 @Epica3055  - please review the triple slash comments for instances of empty tags or placeholder strings, for example `TBD` or `To be documented` and fill them in or delete as appropriate. Note that for overridden methods doc-comments come from the base class and are not needed unless they mention a behavior change.

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 @SimonZhao888 @Epica3055  - please review the triple slash comments for instances of empty tags or placeholder strings, for example `TBD` or `To be documented` and fill them in or delete as appropriate. Note that for overridden methods doc-comments come from the base class and are not needed unless they mention a behavior change.

**Comment by LeafShi1** [comment]
> @LeafShi1 @SimonZhao888 @Epica3055 - please review the triple slash comments for instances of empty tags or placeholder strings, for example `TBD` or `To be documented` and fill them in or delete as appropriate. Note that for overridden methods doc-comments come from the base class and are not needed unless they mention a behavior change.

I didn't find `TBD `or `To be documented` characters in the **Winform repo**, but found a triple slash comments containing `ToDo`, do you mean we need to make changes to these.
![image](https://github.com/dotnet/winforms/assets/132890443/940f49f0-e9f8-4fc8-9fc5-450504c8cb11)

**Comment by Tanya-Solyanik** [comment]
No, `todo` is ok. Thank you for the investigation, I'll close this issue
