### ISSUE TITLE
AccessibilityInsight: The edit listview item must support the Text pattern when ListView's LabelEdit is true

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#4198]
* .NET Core Version: 
.Net SDK 6.0.100-alpha.1.20555.6

* Have you experienced this same bug with .NET Framework?: 
Yes

**Minimal repro:**
1. Open the attached WindowsFormsApp7.zip application in VS, then build and run it.
[WindowsFormsApp7.zip](https://github.com/dotnet/winforms/files/5500560/WindowsFormsApp7.zip)
2. Launch AccessibilityInsight  tool to focus on ListView control

**Actual behavior:**
When ListView's LabelEdit property is true, the edit ListView items doesn't support the Text Pattern, and AccessibilityInsight detects this error.
![image](https://user-images.githubusercontent.com/26474449/98354714-10733d80-205c-11eb-8872-da1f3a408db7.png)

**Expected behavior:**
When ListView's LabelEdit property is true, the edit ListView items support the Text Pattern.

**Comment by merriemcgaw** [comment]
Generally when a user needs to edit the value of any cell, our recommendation would be to use the DataGridView rather than a ListView for accessibility purposes so the right patterns are returned at the right time. The underlying OS control is not behaving according to today's standards.

**Comment by vladimir-krestov** [comment]
After #3224 we have the ability to manage a ListView accessible object and its items. We have a chance to implement TextPattern for editable ListView items. 
@merriemcgaw, which priority it has?

**Comment by merriemcgaw** [comment]
Let's get it on the backlog and make sure we hit it in 6, but it's not more important than servicing issues.

**Comment by vladimir-krestov** [comment]
@guybark, @merriemcgaw, what if to change an editable subitem control type to "text", like we made in #5025?
It's impossible to implement Text pattern for a subitem, because it's just a container for it's nested "edit" field, that already supports Text pattern. So we may make the container as "text" without supporting of Text pattern:
![image](https://user-images.githubusercontent.com/49272759/120601419-91f44800-c452-11eb-821f-cc9450d30b87.png)

**Comment by merriemcgaw** [comment]
That sounds reasonable to me, thanks @vladimir-krestov

**Comment by Zheng-Li01** [comment]
Verified the issue with latest 6.0.0-preview.7.21330.1, the issue has been fixed that the edit listview items are support the Text pattern when ListView's LabelEdit is true for now, please see blow screenshot.
![image](https://user-images.githubusercontent.com/38325459/124437334-8b3a5700-dda9-11eb-9233-5081b9352099.png)

**Comment by Ashley-Li** [comment]
Verified with .NET 6.0.100-preview.7.21369.19 build, the issue has been fixed that the edit listview items are support the Text pattern when ListView's LabelEdit is true for now.
