### ISSUE TITLE
[Accessibility] Increase the "group" list level of the ListView control in the inspection tool

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#4206]
* .NET Core Version: 
.NET SDK 6.0.100-alpha.1.20559.3

* Have you experienced this same bug with .NET Framework?: 
No

**More info**

1. The issue also can reproduce on .NET 5.0 RC2.
2. The issue can't reproduce on .NET SDK 3.1 and .NET 4.8.

**Problem description:**
Increase the "group" list level of the ListView control in the inspection tool with UI Automation mode.

**Minimal repro:**

1. Open the attached project.
2. Build and run the core project.
3. Observe the listView1 control in the Inspect tool on UI Automation mode.
[WindowsFormsApp7.zip](https://github.com/dotnet/winforms/files/5516506/WindowsFormsApp7.zip)

**Expected behavior:**
There is the additional "group" list level of the ListView control in the inspection tool.
![image](https://user-images.githubusercontent.com/45864649/98660329-26e10800-2380-11eb-9cce-f5424b0409e3.png)

**Actual Behavior:**
Increase the "group" list level of the ListView control in the inspection tool
![image](https://user-images.githubusercontent.com/45864649/98660433-437d4000-2380-11eb-9e29-605f7f7b1689.png)

**Comment by Ashley-Li** [comment]
@Nechto37 Verified this issue with the latest .Net SDK 6.0.100-6.1.21.52111 build, it is fixed. Now there is the additional "group" list level of the ListView control in the inspection tool and it work well using Inspector. Please see below result:
![image](https://user-images.githubusercontent.com/56664234/138385601-65ec0463-d6b8-4b19-b0c0-8116b6455fdf.png)
