### ISSUE TITLE
`NumericUpDownTests` tests need to split into granular test

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#4211]
`NumericUpDown_BasicRendering` test currently asserts multiple states of the `NumericUpDown` controls such as rendering when the control is enabled and when it is disabled.
https://github.com/dotnet/winforms/blob/57b305f1548d8338170971fe1f5184b7145c8adb/src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs#L24-L82

The test must be split into smaller tests that assert a single case, e.g. `NumericUpDown_BasicRendering_enabled` and `NumericUpDown_BasicRendering_disabled`.

**Comment by willibrandon** [comment]
May I tackle this one?

**Comment by RussKie** [comment]
Sure, thank you
