### ISSUE TITLE
The ControlPaint.DrawCheckBox results in an incorrect image at 150% scaling when ButtonState.Flat is used

### ISSUE THREAD

**Issue by DmitryGaravsky** [dotnet/winforms#4214]
As you can see in the attached screenshot the check-glyph is positioned incorrectly at 150% scaling:
![image](https://user-images.githubusercontent.com/8652582/98800143-0ddc6380-2421-11eb-9997-ea8f1e02f726.png)

* .NET Core Version: 
SDK Version: 5.0.100

* Have you experienced this same bug with .NET Framework?: 
Yes, it reproducible both in .Net Framework and .Net 5/.Net Core 3.1

**Minimal repro:**
```cs
using System.Drawing;
[CheckBoxScalngIssue.zip](https://github.com/dotnet/winforms/files/5523442/CheckBoxScalngIssue.zip)

using System.Windows.Forms;

namespace WindowsFormsApp1 {
    public partial class Form1 : Form {
        public Form1() {
            InitializeComponent();
            // checkBox1.FlatStyle = FlatStyle.Flat; // use optionally to try the real control
        }
        void Form1_Paint(object sender, PaintEventArgs e) {
            int h = checkBox1.Height;
            var bounds = new Rectangle(checkBox1.Left, checkBox1.Top + h * 2, h, h);
            var state = checkBox1.Checked ? ButtonState.Checked : ButtonState.Normal;
            ControlPaint.DrawCheckBox(e.Graphics, bounds, state | ButtonState.Flat);
        }
        void checkBox1_CheckedChanged(object sender, System.EventArgs e) {
            Invalidate();
        }
    }
```
Attached is a sample project: [CheckBoxScalngIssue.zip](https://github.com/dotnet/winforms/files/5523444/CheckBoxScalngIssue.zip).

**Expected behavior:**
The check-glyph should be centered within the check-box bounds

**Comment by Olina-Zhang** [comment]
@dreddy-work  verified this issue in the latest .Net 7.0 SDK build, it doesn't reproduce, here is the testing screenshots on different DPI setting:
150%DPI:
![image](https://user-images.githubusercontent.com/26474449/143196281-6f3435a7-c983-4442-892e-bc2447a8038d.png)
200%DPI:
![image](https://user-images.githubusercontent.com/26474449/143196379-3b4aab1d-dbe8-4cf5-abce-e32e62cef81d.png)
300%DPI:
![image](https://user-images.githubusercontent.com/26474449/143196458-dc1846b3-efba-4030-abfb-d49d8c93d19d.png)
