### ISSUE TITLE
ResXFileCodeGenerator for NetCore.App generates ResourceManager.GetObject() which doesn't compile.

### ISSUE THREAD

**Issue by tarekgh** [dotnet/winforms#4218]
This issue is reported on VS community portal and parked there for awhile. moving it here to decide what to do with it. 

https://developercommunity2.visualstudio.com/t/ResXFileCodeGenerator-for-NetCoreApp-ge/20529

```
ResXFileCodeGenerator for NetCore.App generates ResourceManager.GetObject() which doesn't compile.
Jeff Lill avatar
Jeff Lill
-
Reported Feb 18, 2017
View internal ticket

Visual Studio RC4 Steps: 1. Create a new NetCore.App conosole project 2. Add two small text files named test1.txt and test2.sh 3. Add a new Resources File 4. Add the two text files to the new resources file 5. Rebuild ResXFileCodeGenerator generated the designer with a ResourceManager.GetString() call for test1.txt and a GetObject() call for test2.sh. The GetObject() call doesn't compile. There are two problems with this: #1: The generated designer should always a compile. #2: The missing GetObject() implies that .NET Core apps won't be able to embed binary resources and use the designer. I'll attach my solution.
```

[EDIT]

Sample app: [Solution.zip](https://github.com/dotnet/winforms/files/5527772/Solution.zip)

**Comment by RussKie** [comment]
@tarekgh any reason why you think it is a Windows Forms issue? `ResourceManager` belong to dotnet/runtime, and the original topic talks about a console app.

**Comment by tarekgh** [comment]
@RussKie ResXFileCodeGenerator is owned by winforms.

**Comment by dreddy-work** [comment]
Yes. this is owned by winforms and span across winforms designer and runtime repos.

**Comment by RussKie** [comment]
@dreddy-work assigning to you since you're working in this area.

**Comment by tarekgh** [comment]
You may try the scenario to see if still repro as the issue is old and maybe already fixed. I recall some work has been done in winforms and msbuild to fix some of such scenarios.

**Comment by Tanya-Solyanik** [comment]
Yeah, this is fixed. the repro project is targeting 1.0.

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
