### ISSUE TITLE
"Value cannot be null. Parameter name: instance" in VS2019 .NET WinForms App

### ISSUE THREAD

**Issue by ShreyasZare** [dotnet/winforms#4226]
I am seeing the following error when opening forms editor in any new Windows Forms App (.NET) project is latest updated VS2019 (Version 16.8.1) community build.

![image](https://user-images.githubusercontent.com/10008172/99044033-21203800-25b5-11eb-8e65-1ef0334b4de0.png)

* .NET Core Version: 
.NET 5 updated with VS2019 (Version 16.8.1) community build.

* Have you experienced this same bug with .NET Framework?: 
No. Windows Forms App (.NET Framework) works without issues.

**Problem description:**
Form editor fails to open with an error for Windows Forms App (.NET) projects.

**Minimal repro:**
I am able to reproduce this issue by creating a new Windows Forms App (.NET) project. I get the same error when I add another winform into the project and try to open the form.

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.
