### ISSUE TITLE
Scrollwheel in .NET 5 Designer causes Visual Studio to freeze

### ISSUE THREAD

**Issue by Zinoh** [dotnet/winforms#4227]
* .NET Core Version:  5.0.100
* Visual Studio 16.9.0 Preview 1.0

* Have you experienced this same bug with .NET Framework?:  No

Using the mouse scroll-wheel in the WinForms designer for .NET 5 causes Visual Studio to freeze

.NET 5 New Project
![net5-designer-scrollcrash](https://user-images.githubusercontent.com/18477601/99059871-29ed1b80-256d-11eb-960e-4a436569ff8f.gif)

.NET Framework New Project
![framework-designer-scroll](https://user-images.githubusercontent.com/18477601/99059921-3d988200-256d-11eb-9ce1-a6a63bdd8771.gif)

**Comment by Zinoh** [comment]
Submitted issue through VS Feedback tool instead

**Comment by RussKie** [comment]
Thank you.
If you post the link to the feedback here we can make sure it gets to our team.

**Comment by Zinoh** [comment]
@RussKie Thank you

https://developercommunity2.visualstudio.com/t/Rolling-scrollwheel-over-NET-5-Winforms/1256156

I did use the screen recorder tool, but have no idea if it processed correctly due to the crash.

**Comment by Zinoh** [comment]
Call stack when Visual Studio freezes. Seems VS hangs waiting for a response from the DesignToolsServer after processing a WM_MOUSEWHEEL message. This only occurs if you roll the mousewheel over the designer when scrollbars are not present. 

A correct dump file was also added to my feedback post.

![devenv_2020-11-20_06-01-49](https://user-images.githubusercontent.com/18477601/99871849-a6a27a00-2bab-11eb-9add-e55e57023c5e.png)

**Comment by RussKie** [comment]
@DustinCampbell  @JeremyKuhne FYI

**Comment by Zinoh** [comment]
Setting the form's **Autoscroll** to **True** and adding a control that extends outside the client's current Size (causing a vertical scrollbar to appear) causes Visual Studio to longer crash when using the mouse wheel while hovering over the designer.

Current thought is that some sort of logic needs to be added to only send WM_MOUSEWHEEL to the DesignToolsServer when actual scrollbars are present, otherwise Visual Studio hangs waiting for a response. 
(Unless, of course, my issue is totally isolated to my system in which case I am at a loss)

![scrollbars_nocrash](https://user-images.githubusercontent.com/18477601/99957885-629fa880-2d56-11eb-920d-612bf87ae2b7.gif)

![noscrollbars_crash](https://user-images.githubusercontent.com/18477601/99957922-70552e00-2d56-11eb-882c-716e439333cf.gif)

**Comment by RussKie** [comment]
@Olina-Zhang can you please raise an issue in the Designer repo?

**Comment by Olina-Zhang** [comment]
I will raise it.
