### ISSUE TITLE
Resize grip is missing in PropertyGrid DropDown editor after update to net5.0-windows

### ISSUE THREAD

**Issue by ds1709** [dotnet/winforms#4238]
* .NET Core Version: 
.Net 5 (net5.0-windows)

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
I have simple drop-down editor `IsDropDownResizable => true` and `GetEditStyle => UITypeEditorEditStyle.DropDown`. For `net472` or `netcoreapp3.1` there's resize grip under drop-down editor. After update to `net5.0-windows` resize grip is missing.

**Expected behavior:**
Resize grip is displayed under editor control.

**Minimal repro:**
```csharp
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            propertyGrid1.SelectedObject = new Foo(); // propertyGrid1 added via designer
        }
    }
```
```csharp
    public sealed class Foo
    {
        [Editor(typeof(FooBarEditor), typeof(UITypeEditor))]
        public string Bar { get; set; }
    }
```
```csharp
    public sealed class FooBarEditor : UITypeEditor
    {
        public override bool IsDropDownResizable => true;

        public override UITypeEditorEditStyle GetEditStyle(ITypeDescriptorContext context)
            => UITypeEditorEditStyle.DropDown;

        public override object EditValue(ITypeDescriptorContext context, IServiceProvider provider, object value)
        {
            ((IWindowsFormsEditorService)provider.GetService(typeof(IWindowsFormsEditorService)))
                .DropDownControl(new Panel { BackColor = Color.Yellow });

            return value;
        }
    }
```

**Comment by RussKie** [comment]
Do you mind sharing screenshots from .NET Framework/.NET Core and .NET 5.0 to better visualise the issue? Thanks

**Comment by ds1709** [comment]
net472
![image](https://user-images.githubusercontent.com/5591663/100061219-cb625000-2e3e-11eb-9f3b-689d49e379d7.png)
net5.0-windows
![image](https://user-images.githubusercontent.com/5591663/100061296-e634c480-2e3e-11eb-958a-41e231eee031.png)

**Comment by kirsan31** [comment]
@ds1709 

> I also noticed that size of windows and controls is different in net472 and net5.0.

https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms#net-core-30

**Comment by RussKie** [comment]
@dreddy-work do you think you could have a look at it?

**Comment by willibrandon** [comment]
This issue appears to partially have something to do with the order in which the `ResizeGripSize`, `ResizeBarSize`, and `ResizeBorderSize `are being initialized in `PropertyGridView.DropDownHolder`.

If I change the order from this:

```
private readonly static int ResizeBarSize = ResizeGripSize + 1; // the thickness of the resize bar
private readonly static int ResizeBorderSize = ResizeBarSize / 2; // the thickness of the 2-way resize area along the outer edge of the resize bar
private readonly static int ResizeGripSize = SystemInformation.HorizontalScrollBarHeight; // the size of the 4-way resize grip at outermost corner of the resize bar
```

To this:

```
private readonly static int ResizeGripSize = SystemInformation.HorizontalScrollBarHeight; // The size of the 4-way resize grip at outermost corner of the resize bar.
private readonly static int ResizeBarSize = ResizeGripSize + 1;// The thickness of the resize bar.
private readonly static int ResizeBorderSize = ResizeBarSize / 2;// The thickness of the 2-way resize area along the outer edge of the resize bar.
```

Then the drop down resize bar is now displayed and can resize the drop down, but the resize bar is missing the grip glyph.

![PropertyGridView1](https://user-images.githubusercontent.com/5017479/101310619-42ff8a00-3804-11eb-9975-06438944bdd2.png)

**Comment by weltkante** [comment]
> This issue appears to partially have something to do with the order in which the ResizeGripSize, ResizeBarSize, and ResizeBorderSize are being initialized in PropertyGridView.DropDownHolder.

This regressed when moving initialization from static constructor into the property definitions

> I'll try to figure out why the resize bar is missing the resize grip, any insight would be appreciated.

The size grip for this usage is [mirrored horizontally](https://github.com/dotnet/winforms/blob/6391b524dd64e7530eba986c6607bf129b3ec8ae/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs#L244) to display bottom left instead of the default bottom right

This is a regression caused by PR #3553, previously the glyph was drawn in GDI+ but in order to support callers from WM_PAINT better it was switched to classic GDI drawing. However GDI drawing code [only preserves translations](https://github.com/dotnet/winforms/blob/36f3feb00295caf213e6057171896926450290b7/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs#L195-L198) and drops all other components of the Transform-Matrix without any warning/exception.

Note that this only preserving translation components always has been this way, the regression was moving from GDI+ to the HDC rendering with a caller that uses a nontrivial matrix, which was never supported by WinForms HDC rendering logic.

/cc @JeremyKuhne

**Comment by JeremyKuhne** [comment]
I'm going to move this API back for now as there is no performant way to check if there is a transform that applies. In this particular case, there is not a huge win if you already have a graphics object as drawing will already translate to direct GDI calls.

I've created a new API proposal related to this: https://github.com/dotnet/winforms/issues/4338

**Comment by Amy-Li03** [comment]
@RussKie we saw that you market the milestones of this issue as 5.0.2, but it only fixed on .NET 6.0 by PR: https://github.com/dotnet/winforms/pull/4340 , do we need to service it for .NET 5.0? cc: @JeremyKuhne

**Comment by kirsan31** [comment]
As far as I understand, it didn't make it in 5.0.2?

**Comment by merriemcgaw** [comment]
> As far as I understand, it didn't make it in 5.0.2?

I don't recall taking it for servicing. How blocking is this for our users? Given that I don't see it as an adoption blocker, I'm not convinced we'd get it approved for servicing. Does this block any known customers at this stage? We've got it in 6 and if we get a customer complaint it's always possible to service. I'm just not convinced of the case here (though of course I'm glad we're in 6.0 with it early!).

**Comment by kirsan31** [comment]
@merriemcgaw 
No problem at all for us.
I simply react to [previous comment](https://github.com/dotnet/winforms/issues/4238#issuecomment-745800275) and 5.02 milestone.
