### ISSUE TITLE
Value cannot be null. (Parameter 'rootComponent') when use IRootDesigner

### ISSUE THREAD

**Issue by oudi** [dotnet/winforms#4239]
* .NET Core Version: 
.NET 5 updated with VS2019 (Version 16.8.1) community build.
net5.0-windows

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

When I create the IRootDesigner myself component, open the deisnger of the component in VS 2019, it shows the error below.

```
Value cannot be null.  (Parameter 'rootComponent') 
Call Stack
at Microsoft.VisualStudio.WinForms.Protocol.Endpoints.Sessions.InitializeRootComponentResponse..ctor(IComponent rootComponent, IComponent[] components, String[] componentNames)
at WinFormsSurface.Handlers.Sessions.InitializeRootComponentHandler.HandleRequest(InitializeRootComponentRequest request)
at WinFormsSurface.Requests.RequestHandler`2.WinFormsSurface.Requests.IRequestHandler.HandleRequest(Request request) 
```

Then I create a sample from https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.design.irootdesigner?view=net-5.0 and open the deisgner of `RootDesignedComponent ` it shows the same error!

![20201116233302](https://user-images.githubusercontent.com/2518192/99273544-248d1b00-2864-11eb-8b84-73601bd23513.png)

The proejct use net5.0-windows as TargetFramework. and the Form1 inherit System.Windows.Forms.Form works fine but not the component!

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
```

**Comment by RussKie** [comment]
@safern this wouldn't be related to https://github.com/dotnet/runtime/issues/31428 by any chance, would it?

**Comment by safern** [comment]
I think so. When I tested the repro I was getting null as the designer value. Let me try this repro with my fix.

**Comment by safern** [comment]
I might be doing something wrong but I can't get a repro of this even without my fix. @oudi would you mind sharing a minimal repro zip?

**Comment by oudi** [comment]
@safern Thanks for your reply, I commit the source code at https://github.com/oudi/RootComponentIssue , You can view the `RootViewSampleComponent` in the project `NetCoreDesignerTest`.

**Comment by boris768** [comment]
Converted from Net Framework 4.8 WinForms projects with Progress Telerik framework also affected

**Comment by RussKie** [comment]
> Converted from Net Framework 4.8 WinForms projects with Progress Telerik framework also affected

Which SDK and runtime are you having issues with?

**Comment by boris768** [comment]
> > Converted from Net Framework 4.8 WinForms projects with Progress Telerik framework also affected
> 
> Which SDK and runtime are you having issues with?

Visual studio 16.8.4
.NET 5.0.2 (last release SDK)
Progress Telerik UI for WinForms R1 2021 (ver 2021.1.119.40)
After using any project converting tool (try-convert or Telerik .Net Core Project Converter) i cant open Designer for any form in solution, but project can be compiled without any issues.

**Comment by AteCoder** [comment]
I am seeing the exact same behavior.  It is very easy to reproduce:
(1) Add a new user control (use default name usercontrol1);
(2) Hit Shift-F7--user control 1 displays in design mode; so far so good;
(3) change `public partial class UserControl1 : UserControl` to `public partial class UserControl1 : SplitContainer`
(2) Hit Shift-F7--error: `Value cannot be null. (Parameter 'rootComponent')`

**Comment by Paul-Williams** [comment]
I am getting the same issue when attempting to inherit from System.Windows.Forms.TabControl.

**Comment by safern** [comment]
Thanks all for the info. I was able to reproduce this. Taking a deeper look now.

**Comment by dennis-garavsky** [comment]
Just to indicate that we have been waiting for this Component Designer fix as well (for our commercial product for other .NET developers). We have a Controller class and a custom designer, a descendant of ComponentDocumentDesigner:

```cs
    [Designer("DevExpress.ExpressApp.Design.ControllerDesigner, DevExpress.ExpressApp.Design" + XafAssemblyInfo.VersionSuffix + XafAssemblyInfo.AssemblyNamePostfix, DevExpress.Utils.Design.Aliases.IRootDesigner)]
    [DesignerCategory("Component")]
    [DefaultEvent("Activated")]
#endif
    public abstract class Controller : Component, ISupportUpdate { ... }
    
    [ToolboxItem(false)]
    [ToolboxItemFilter("DevExpress.ExpressApp.Controller", ToolboxItemFilterType.Require)]
    [ToolboxItemFilter("", ToolboxItemFilterType.Custom)]
    public class ControllerDesigner : ComponentDocumentDesigner, IToolboxUser { ...}

```
## Scenario
.NET developers can configure Controller properties in the property grid and also drag & drop Actions from the Visual Studio Toolbox. Actions are child components within the parent Controller component. For more information, see [this tutorial for .NET Framework](https://docs.devexpress.com/eXpressAppFramework/112737/getting-started/in-depth-tutorial-winforms-aspnet/extend-functionality/add-a-simple-action?p=netframework).

The issue affects our ASP.NET Core Blazor and WinForms .NET Core/.NET 5+ developers, because the designer throws this `Value cannot be null` error. As a .NET component vendor, we had to disable the Controller designer for .NET Core/.NET 5+ projects completely for now + write documentation explaining these limitations + offer additional means for code generation such as code snippets. This is all not ideal experience (our .NET users do not want to write code here) and we hope that Component Designer will eventually be supported. Thank you.

**Comment by RussKie** [comment]
The OOP designer still lacks the support for components design, the issue is tracked under https://github.com/dotnet/winforms-designer/issues/4126 (Microsoft internal).
For a possible workaround please refer to https://github.com/dotnet/winforms/blob/main/docs/designer/net-inproc-designer.md.

**Comment by mxashlynn** [comment]
Are you able to share why this issue is now being tracked such that end users are unable to see it's status?

**Comment by RussKie** [comment]
To provide an update: the work to support custom root designers in the out-of-proc designer is under way. There is still no definitive ETA, however, we're aiming for 17.5 timeframe.
