### ISSUE TITLE
Narrator does not announce that the row has been added to the DataGridView

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4243]
* .NET Core Version: 
5.0.100-rc.2.20479.15

* Have you experienced this same bug with .NET Framework?: 
Yes

**Minimal repro:**

1. Create the application with a DataGridView
2. Run the application.
3. Start editing the last row (row to add a new row)

![Issue-4243](https://user-images.githubusercontent.com/23376742/99370940-5c7d7800-28cf-11eb-95e2-d0bc7b927607.gif)

**Actual behavior:**
Narrator does not announce that the row has been added.

**Expected behavior:**
Narrator should announce that the row has been added.

**Comment by Zheng-Li01** [comment]
Verified the issue with .NET SDK 6.0.100-alpha.1.20573.16, the issue has been fixed that  new added row can be announce currently. see below screenshot.
![GH4243](https://user-images.githubusercontent.com/38325459/100041933-53e3ef00-2e45-11eb-9b74-832ef6575bef.PNG)
