### ISSUE TITLE
RichTextBox Monospace Font Rendering is Broken

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#4260]
* .NET Core Version: 
.Net 6.0.100-alpha.1.20568.7 from master branch

* Have you experienced this same bug with .NET Framework?: 
Yes

**More Info:**

1. This issue also can reproduce on .Net Core 3.1.
2. This is a regression issue, it can reproduce from .Net framework 4.7 to 4.8, but cannot reproduce on .Net Framework 4.6.2. In addition, from .Net framework 4.7 to 4.8, there is a workaround: add the quirk to the App.config file.
 ```
 <runtime>
	<AppContextSwitchOverrides value="Switch.System.Windows.Forms.DoNotLoadLatestRichEditControl=true"/>
</runtime>
 ```

**Minimal repro:**

1. Extract the [RichTextBoxDemo.zip](https://github.com/dotnet/winforms/files/5572035/RichTextBoxDemo.zip) and open it in VS.
2. Build and run this application.
3. Observe the length of Text in RichTextBox.

**Expected behavior:**
The Text of the same length in the RichTextBox should be consistent.
![image](https://user-images.githubusercontent.com/45864649/99774896-5e527000-2b49-11eb-9b6a-ed9b99cb6787.png)

**Actual behavior:**
The text of the same length in the RichTextBox is not consistent.
![image](https://user-images.githubusercontent.com/45864649/99774721-277c5a00-2b49-11eb-9b26-a58cafa78498.png)
![image](https://user-images.githubusercontent.com/45864649/99774827-44b12880-2b49-11eb-9f88-36987a397498.png)

**Comment by RussKie** [comment]
If this worked in .NET Framework <4.7, and then changed in 4.7+ then it is a result of .NET Framework 4.7 moving to the newer RichEdit4.1 control. `Switch.System.Windows.Forms.DoNotLoadLatestRichEditControl=true` allowed using older RichEdit2.0/3.0 instead of RichEdit4.1.

**Comment by weltkante** [comment]
I've looked a bit deeper into this to verify its indeed not a regression. If you call `SaveFile` on the Desktop Framework 4.6 Rich Text Box (which appears to render monospaced) and open the resulting rtf in WordPad you get same result as .NET Core and modern Desktop Framework.

Looking at the text in WordPad reveals that most of the displayed characters are not part of the Font `Lucida Console` but instead use a fallback font to render missing characters. The fallback font is apparently not monospace.

I can only guess that the legacy RTF control treated font fallback on missing characters differently.

Alltogether its a user error, the author of the program is trying to display characters in a Font which doesn't have those characters. While the RTF control and/or Windows will try to figure something out to display the text anyways, this fallback strategy will differ between OS versions, Control versions, and also asian installations will often use totally different fallback fonts. Relying in your visual presentation on the exact behavior of the font fallback is inherently nonportable, so there is nothing that needs to be adressed.
