### ISSUE TITLE
The 'Windows Forms Remote Designer Hosting Package' package did not load correctly.

### ISSUE THREAD

**Issue by MojoDK** [dotnet/winforms#4269]
* .NET Core Version: 
Net5.0

* Have you experienced this same bug with .NET Framework?: 
No

Creating a new project gives me this error:

![image](https://user-images.githubusercontent.com/1185948/100077821-18e0bc00-2e43-11eb-9e79-fc0aa17943b5.png)

Activity log:

```
<entry>
    <record>2302</record>
    <time>2020/11/24 09:58:18.678</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Windows Forms Remote Designer Hosting Package]</description>
    <guid>{C78CA057-CC29-421F-AD6D-3B0943DEBDFC}</guid>
  </entry>
  <entry>
    <record>2303</record>
    <time>2020/11/24 09:58:18.679</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [Windows Forms Remote Designer Hosting Package]Source: &apos;mscorlib&apos; Description: Could not load type &apos;Microsoft.VisualStudio.Design.VSDesignPackage&apos; from assembly &apos;Microsoft.VisualStudio.WinForms.Package, Version=0.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos;.&#x000D;&#x000A;System.TypeLoadException: Could not load type &apos;Microsoft.VisualStudio.Design.VSDesignPackage&apos; from assembly &apos;Microsoft.VisualStudio.WinForms.Package, Version=0.3.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35&apos;.&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)</description>
    <guid>{C78CA057-CC29-421F-AD6D-3B0943DEBDFC}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>

```
Restarting VS does not help.

When trying to open Form1 designer, I get this error:
"The designer could not  be shown for this file because none of the classes within it can be designed.  The designer inspected the following classes in the file: Form1 --- The base  class 'System.Windows.Forms.Form' could not be loaded. Ensure the assembly has  been referenced and that all projects have been built. |   | The designer could not  be shown for this file because none of the classes within it can be designed.  The designer inspected the following classes in the file: Form1 --- The base  class 'System.Windows.Forms.Form' could not be loaded. Ensure the assembly has  been referenced and that all projects have been built."

**Expected behavior:**

**Minimal repro:**
Create new project and I got the error right away...
![2020-11-24_10-58-39](https://user-images.githubusercontent.com/1185948/100078809-35c9bf00-2e44-11eb-8dbd-7310c0cf084e.gif)

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.

You're welcome to post the link to the VS Feedback ticket here so we can ensure it doesn't get lost.
