### ISSUE TITLE
ActiveX support in .Net 5 Windows Forms designer?

### ISSUE THREAD

**Issue by rlktradewright** [dotnet/winforms#4272]
* .NET Core Version: 
.Net 5

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The Windows Forms designer for .Net 5 appears to be brain-dead with regard to ActiveX controls.

I have not succeeded in getting any ActiveX controls working in the Toolbox. The 'Choose items' dialog says:

_'The following controls were successfully added to the toolbox but are not enabled in the active designer. .... Make sure the controls to add are compatible with the current designer and .Net Framework version.'_

Well, the controls are all perfectly compatible with .Net 5 and work fine if they are manually included in the form design, so I have to conclude that the current version of the designer simply doesn't do ActiveX.

Please confirm this, and indicate whether there is likely to be full support for ActiveX controls any time soon.

Or tell me what I'm doing wrong!...

**Expected behavior:**

The chosen ActiveX control should appear in the Toolbox and create the control properly when applied to the form.

**Minimal repro:**

For example:

1. Create new .Net 5 C# Windows Forms app in Visual Studio 2019 v16.8 or later
2. Right-click on a category header in the Toolbox and Select 'Choose Items...' .
3. On the 'COM Components' tab of the 'Choose Toolbox Items 'dialog, set the checkbox for a control (for example the Calendar Control 8.0 is conveniently near the top of the list).
4. A new window appears with the error message shown in the description above. The control is not visible in the Toolbox.

**Comment by elu** [comment]
I have the same issue when trying to add the EasyLabel ActiveX-Control of Tharo.com to the toolbox.

**Comment by rlktradewright** [comment]
It's now six months since I raised this issue. There has not been a peep out of Microsoft since then, nor have any of the various pronouncements about Windows Forms in .Net 5 and .Net 6 made any mention of this issue.

It would be helpful if Microsoft could give some indication of when support for ActiveX controls in the .Net 5 Windows Forms Designer is likely to become available. There must be some sort of roadmap for this?

@merriemcgaw  can you provide any information on this?

**Comment by merriemcgaw** [comment]
Sorry about the delay all! We're still in progress when it comes to the designer and are still collecting feedback about how critical ActiveX designer support is to get into the designer. We do listen to your feedback and are taking it into consideration. Though I would suggest filing a suggestion ticket from Visual Studio too so that we get this tracked in the best spot and others can vote. At this time there aren't enough requests to make a commitment to getting it on the active schedule.

**Comment by rlktradewright** [comment]
Sounds like this isn't going to happen any time soon, and probably never...

I have submitted feedback as you suggested, but I won't hold my breath.

It's a shame, because COM interop in the .Net Framework is absolutely marvellous. And while it is possible to use ActiveX controls in .Net 5, having to manually put the code in is, shall we say, non-optimal  (because of course you then can't use the Windows Forms designer at all on such a form).

Would this development be something the community could do, using the .Net Framework forms designer code as a starting point, or is it more a political matter of whether Microsoft wants to go down this path at all?

**Comment by kirsan31** [comment]
> Sounds like this isn't going to happen any time soon, and probably never...

I'm afraid that you are right. The new designer is something very hidden and at the moment has much more important problems than ActiveX support. Designer is the main brake on the path of full migration from net framework :(

**Comment by weltkante** [comment]
Considering the TLB importer (which imports an ActiveX TLB into a .NET assembly) was intentionally never ported to .NET Core its unlikely that this will happen anytime soon. Also the existing COM infrastructure in the .NET runtime is being phased out and replaced by a new one, which will be lacking certain parts historically used for ActiveX controls (like TLB and IDispatch support).

The unfortunate reality is that this part of COM interop is viewed as legacy and is not actively being worked on support for it.

On the plus side, the new COM interop infrastructure is available to everyone and can be used to roll your own COM interop if you are really into it. If you are interested check out `System.Runtime.InteropServices.ComWrappers` and look for issues in the dotnet runtime repository, there were several discussions about it while it was developed. Of course that won't cover the design-time experience.

**Comment by pmeems** [comment]
I'm on VS2022 v17.1.0 using .NET6 and I have still the same issue.
I can't use my own ActiveX control in the designer. Adding it by code, compiling and running works fine.
We are planning to upgrade our existing .NET Framework application to .NET6 but without the Form Designer this is not doable.

@rlktradewright you mentioned you created feedback. Can you provide the link so I can vote for it?
It might help to get this better prioritized.

**Comment by rlktradewright** [comment]
@pmeems  try this: https://developercommunity.visualstudio.com/t/support-for-activex-controls-in-windows-forms-desi/1435698?from=email

I've pretty much given up hoping for this...

**Comment by merriemcgaw** [comment]
@pmeems we've added support in VS. @Shyam-Gupta on my team can answer any questions you might have.

**Comment by Shyam-Gupta** [comment]
@pmeems We added support for ActiveX controls in VS 17.9 release. Please give it a try with latest VS release and let us know if you encounter any issues.
