### ISSUE TITLE
ListView redraws when images are added to its ImageList

### ISSUE THREAD

**Issue by AustinWise** [dotnet/winforms#4275]
* .NET Core Version: release/5.0 branch (af41134ff98cf2793a2fcf40f21f95dc94f3ee79), includes #4222

* Have you experienced this same bug with .NET Framework?: No. The problem is also not in .NET Core 3.1.

**Problem description:**

When adding a image to the ImageList, the entire contents of a ListView that is using that ImageList is redrawn. This causes it flicker and if there are enough item, it slows down the app. This seems to be causes by the fix in #4222. Every time an image is added to an image list, the `ImageList.RecreateHandle` event is raised. This causes the ListView to call `ImageList.CreateUniqueHandle`, which always creates a copy of the native image list.

**Expected behavior:**

I think to prevent the redrawing the `ImageList` needs to share the underlying native image list with the `ListView`, instead of giving it a new copy every time an image is added. This would prevent the `ListView` from redrawing unnecessarily.

I know y'all recently change the lifetime management in #3601 to fix some crashes, so I understand this might not be an easy fix.

**Minimal repro:**

```c#
using System;
using System.Drawing;
using System.Windows.Forms;

class MyForm : Form
{
    [STAThread]
    static void Main()
    {
        Application.SetHighDpiMode(HighDpiMode.SystemAware);
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        Application.Run(new MyForm());
    }

    ListView lv;
    ImageList il;
    Timer tmr;

    MyForm()
    {
        tmr = new Timer
        {
            Interval = 100,
        };
        il = new ImageList()
        {
        };
        lv = new ListView()
        {
            LargeImageList = il,
            View = View.LargeIcon,
            Dock = DockStyle.Fill,
        };
        this.Controls.Add(lv);

        var red = new Bitmap(il.ImageSize.Width, il.ImageSize.Height);
        using (var g = Graphics.FromImage(red))
            g.Clear(Color.Red);
        int redIndex = il.Images.Add(red, Color.Transparent);

        for (int i = 0; i < 1000; i++)
        {
            var lvi = new ListViewItem(i.ToString(), redIndex);
            lv.Items.Add(lvi);
        }

        this.WindowState = FormWindowState.Maximized;
        this.Load += MyForm_Load;
        tmr.Tick += Tmr_Tick;
    }

    private void MyForm_Load(object sender, EventArgs e)
    {
        tmr.Enabled = true;
    }

    private void Tmr_Tick(object sender, EventArgs e)
    {
        il.Images.Add(new Bitmap(il.ImageSize.Width, il.ImageSize.Height), Color.Transparent);
    }
}

```

**Comment by Ashley-Li** [comment]
Verified this issue in .Net SDK 5.0.102-servicing.20614.17 build, this issue is fixed. if there are enough item, there's no flicker and  and does not slows down the app.

**Comment by AustinWise** [comment]
I tested my application with a build off the `release/5.0 branch`. The issue is now fixed. Thanks to @RussKie for the quick fix.
