### ISSUE TITLE
MonthCalendar: UpdateBoldedDates flickers and resets DisplayRange

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#4283]
* .NET Core Version: **all**

* Have you experienced this same bug with .NET Framework?: **yes**

**Problem description:**
After you changed BoldedDates in MonthCalendar you need to call `UpdateBoldedDates` method to see visual changes. The problem is that [UpdateBoldedDates](https://github.com/dotnet/winforms/blob/6391b524dd64e7530eba986c6607bf129b3ec8ae/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L1967) simple calling `RecreateHandle`. That's leads to 2 problems:
1. Control fully redrawing with heavy flickering.
2. If `MonthCalendar` displaying more than one months, you are not on the first page and selected date not in the last month, than  control will scroll one page back - reset current DisplayRange.
![MonthCalendar](https://user-images.githubusercontent.com/17767561/100223926-2f634200-2f2d-11eb-8d06-062265b5c5a7.gif)

I think that the **1** problem appear due to not using `MCM_SETDAYSTATE`. Only `MCN_GETDAYSTATE` is using, so you need full redraw to process all dates. 
**2** problem appear due to that [OnHandleCreated](https://github.com/dotnet/winforms/blob/6391b524dd64e7530eba986c6607bf129b3ec8ae/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L1386)  not care at all of  DisplayRange (only `SelectionRange` is taken into account).
It can be workaround in user code with something like this:
```cs
monthCalendar1.SuspendLayout();
var v = monthCalendar1.GetDisplayRange(true);
var MinDate = monthCalendar1.MinDate;
var MaxDate = monthCalendar1.MaxDate;
monthCalendar1.MinDate = v.Start;
monthCalendar1.MaxDate = v.End;
monthCalendar1.UpdateBoldedDates();
monthCalendar1.MinDate = MinDate;
monthCalendar1.MaxDate = MaxDate;
monthCalendar1.ResumeLayout();
```
Something similar can be added to `OnHandleCreated`. But I think that most efficient way is to solve **1** issue  - use `MCM_SETDAYSTATE`  with all changes to `BoldedDates` (`AnnuallyBoldedDates`, `BoldedDates`, `MonthlyBoldedDates`, `UpdateBoldedDates`). Then **2** will be solve _automatically_.

**Expected behavior:**
No flickering and no DisplayRange reset.

**Minimal repro:**
[MonthCalendar.zip](https://github.com/dotnet/winforms/files/5596679/MonthCalendar.zip)

**Comment by RussKie** [comment]
@vladimir-krestov can you please investigate? Thanks

**Comment by kirsan31** [comment]
After boldeddates modification we need to use `MCM_SETDAYSTATE` to change appearance of current DisplayRange.
I tried implementing this (hastily) from the user side in the above example.
```cs
var DR = monthCalendar1.GetDisplayRange(false);
int Months = (DR.End.Year - DR.Start.Year) * 12 + DR.End.Month - DR.Start.Month + 1;
var BoldedDates = monthCalendar1.BoldedDates;
uint[] Monthdaystates = new uint[Months];
DateTime CurDt = DR.Start;
int curM = 0;
int DayOfMoth = CurDt.Day - 1;
while (CurDt <= DR.End)
{
    if (BoldedDates.Contains(CurDt))
        Monthdaystates[curM] |= 1U << DayOfMoth;
    else
        Monthdaystates[curM] &= ~(1U << DayOfMoth);

    var newdt = CurDt.AddDays(1);
    if (newdt.Month != CurDt.Month || newdt.Year != CurDt.Year)
    {
        curM++;
        DayOfMoth = 0;
    }
    else
        DayOfMoth++;
    CurDt = newdt;
}
fixed (uint* arr = Monthdaystates)
{
    //MCM_SETDAYSTATE 0x1008
    PInvoke.User32.SendMessage(monthCalendar1.Handle, (PInvoke.User32.WindowMessage)0x1008, (void*)Months, arr);                    
}
```
In ideal we no need to do anything if added / removed boldeddates is out of DisplayRange.
Left is code from 1 post (with problem **2** workaround), right is the new implementation (automatically solves problem **2**):
![MonthCalendarOld](https://user-images.githubusercontent.com/17767561/100514239-08eb1400-3184-11eb-90b4-12fa2ff456f9.gif) ![MonthCalendarNew](https://user-images.githubusercontent.com/17767561/100514241-0d173180-3184-11eb-9e4b-a8333be9378c.gif)

Some flickering is still present, but it's much much less then full redraw and may be can somehow workarounded too...

**Comment by vladimir-krestov** [comment]
@kirsan31 Thanks for the great amount of information and comments. I spent the time to question your words and your implementation. But it seems that your implementation is the only thing we can do on our side. I haven't found any other way to improve `MonthCalendar` control to make it work as expected. Thank you so much! Your code example helped a lot in implementing the Calendar improvement. You can see this implementation in PR #4317, please review it.

**Comment by kirsan31** [comment]
@vladimir-krestov Thank you for PR (I commented there).
Is there a chance to reach out to the native team about this flickering?
