### ISSUE TITLE
remove explicit "\r\n" test from the .resx files in this repo because these strings will be escaped by the resx reader and will not be displayed as new lines

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#429]
* .NET Core 3.0 Preview1
* Have you experienced this same bug with .NET Framework?: No - resources are in a different format there

Sample repro:
run this code:
`            (new ThreadExceptionDialog(new Exception("Really long exception description string, because we want to see if it properly wraps around or is truncated."))).Show();`

Actual: 
![image](https://user-images.githubusercontent.com/15823268/52612014-d5b78380-2e3c-11e9-8390-690af42db31a.png)

Expected - "\r\n" text is displayed as a new line

**Comment by zsd4yr** [comment]
- [ ] System.Windows.Forms
- [ ] System.Windows.Forms.Editors
- [ ] System.Windows.Forms.Editors.Design

**Comment by Tanya-Solyanik** [comment]
SR.resx files in System.Windows.Forms.Editors and System.Windows.Forms.Editors.Design don't have any explicit `\r\n` strings
