### ISSUE TITLE
question: new windows forms task dialogs

### ISSUE THREAD

**Issue by ancientmagicwizard** [dotnet/winforms#4291]
hi

I have read windows forms in .net 5.0 has a new task dialog window. It was contributed by an open source developer.
However I can't find this anywhere and also no docs.

Can somebody explain me how to create this in a windows forms .net 5.0 program?

Jessica

**Comment by paul1956** [comment]
https://docs.microsoft.com/en-us/samples/dotnet/samples/winforms-taskdialog-vb/ or https://docs.microsoft.com/en-us/samples/dotnet/samples/winforms-taskdialog-cs/ you can then browse the many samples.
