### ISSUE TITLE
bug: exception when using ListViewItemSorter

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#4292]
Hi

Following code throws an exception, while it works fine in .NET 4.8
I use .NET 5.0 latest SDK and latest VS 2019 community. I'm using a WinForms application .NET 5.0

WHEN: 
The exception is thrown when you click the same column header the THIRD time (first and second time it works and no exception thrown).

WHAT:
Exception thrown: 'System.NullReferenceException' in System.Windows.Forms.dll
Object reference not set to an instance of an object.

WHERE:
Exception thrown on code line:
listViewCardSets.ListViewItemSorter = new ListViewItemStringComparer(e.Column, listViewCardSets.Sorting);

```cs
class ListViewItemStringComparer : IComparer
    {
        private int col;
        private SortOrder order;
        public ListViewItemStringComparer()
        {
            col = 0;
            order = SortOrder.Ascending;
        }

        public ListViewItemStringComparer(int column, SortOrder order)
        {
            col = column;
            this.order = order;
        }

        public int Compare(object x, object y)
        {
            int returnVal = -1;
            returnVal = String.Compare(((ListViewItem)x).SubItems[col].Text,
                                       ((ListViewItem)y).SubItems[col].Text);

            // Determine whether the sort order is descending.
            if (order == SortOrder.Descending)
                // Invert the value returned by String.Compare.
                returnVal *= -1;

            return returnVal;
        }
    }
```

```cs
        private int _sortColumnIndex = -1;
        private void listViewCardSets_ColumnClick(object sender, ColumnClickEventArgs e)
        {
            // Determine whether the column is the same as the last column clicked.
            if (e.Column != _sortColumnIndex)
            {
                // Set the sort column to the new column.
                _sortColumnIndex = e.Column;
                // Set the sort order to ascending by default.
                listViewCardSets.Sorting = SortOrder.Ascending;
            }
            else
            {
                // Determine what the last sort order was and change it.
                if (listViewCardSets.Sorting == SortOrder.Ascending)
                    listViewCardSets.Sorting = SortOrder.Descending;
                else
                    listViewCardSets.Sorting = SortOrder.Ascending;
            }

            // Call the sort method to manually sort.
            listViewCardSets.Sort();

            // Set the ListViewItemSorter property to a new ListViewItemComparer object.
            listViewCardSets.ListViewItemSorter = new ListViewItemStringComparer(e.Column, listViewCardSets.Sorting);
        }
```

**Comment by RussKie** [comment]
Can you please provide a complete sample app? Thanks

**Comment by ancientmagicwizard** [comment]
Make an empty win forms app for .Net 5.0 sdk, add a ListView with name as in the code.
Assign the column_click method to it.

Don't they learn you this at Microsoft?

I now understand where all those bugs come from...

**Comment by ancientmagicwizard** [comment]
You want me to hold your hand too?!?

**Comment by ancientmagicwizard** [comment]
FUCKFACE

**Comment by Amy-Li03** [comment]
We cannot reproduce this issue using .NET 5.0 latest SDK and latest VS 2019, When running the below demo project, then click the same column header three or more times, no exception was throwing.
Demo project: 
[WinFormsApp9.zip](https://github.com/dotnet/winforms/files/5613572/WinFormsApp9.zip)

![reproSteps](https://user-images.githubusercontent.com/62929087/100564241-71a8cc80-32fb-11eb-897c-45581407a321.gif)

**Comment by RussKie** [comment]
Thank you @Amy-Li03
