### ISSUE TITLE
Setter of method this[int index] of class TreeNodeCollection should not allow adding a TreeNode that already exists in the TreeView

### ISSUE THREAD

**Issue by manuelvalenzuela** [dotnet/winforms#4293]
* .NET Core Version: 
.Net 5 (net5.0-windows)

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
Setter of method `public virtual TreeNode this[int index]` of class `TreeNodeCollection` should not allow adding a `TreeNode` that already exists in the `TreeView`, in order to be consistent with the methods: `Insert(int index, TreeNode node)` and `Add(TreeNode node)`.

**Expected behavior:**
It should throw a `System.ArgumentException` with message `Cannot add or insert the item '{0}' in more than one place. You must first remove it from its current location or clone it.`

**Minimal repro:**
- Create a new WinForms App
- Insert a TreeView on the Form.
- Insert the folloing code in the Form_Load event handler.

``` C#
private void Form1_Load(object sender, EventArgs e)
{
    TreeNode node = new TreeNode("Node 1");
    treeView1.Nodes.Add(node);
    treeView1.Nodes[0] = node;
}
```
You can see the expected behavior changing the following:
``` C#
// treeView1.Nodes[0] = node;
treeView1.Nodes.Insert(0, node);
```
or
``` C#
// treeView1.Nodes[0] = node;
treeView1.Nodes.Add(node);
```

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .NET SDK 6.0.100-alpha.1.21062.11 that the issue has been fixed, please see below screenshot.
![image](https://user-images.githubusercontent.com/38325459/104400220-22f28180-558d-11eb-8bbb-d8b1111c05e7.png)
