### ISSUE TITLE
ToolStripStatusLabel not displaying '&' chars

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#4294]
* .NET Core Version: 
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

If you assign a string that contains one or more '&' chars to a ToolStripStatusLabel, the string is displayed WITHOUT any '&' chars.

**Expected behavior:**

For example: 

toolStripStatusLabel.Text = "test&";

It should display "test&" but instead it's displaying "test"

**Comment by John-Qiao** [comment]
To display the "test&" in toolStripStatusLabel item, we can use the following code line:

> `toolStripStatusLabel1.Text = "test&&";`

To display the "test&" in a standard Label control, we can using the following two ways:

> `label1.Text = "test&&";`

or
> `label1.UseMnemonic = false;`

> `label1.Text = "test&";`

Above solutions work in both .NET Framework and .NET Core.

**Comment by the-namelessone** [comment]
In .NET Framework toolStripStatusLabel1.Text = "test&"; displays "test&" but in .NET 5.0 it displays "test" .

Why is the & gone in .NET 5.0 using the same code?

**Comment by John-Qiao** [comment]
@the-namelessone 

In my testing result, it also displays the "test" in .NET Framework when set toolStripStatusLabel1.Text = "test&", please check below screenshot:
![TestResult-Framework](https://user-images.githubusercontent.com/45864985/100816968-34bb1200-3482-11eb-96d7-7c706d30fe79.png)

If you can show the "test&" in .NET Framework when set toolStripStatusLabel1.Text = "test&", please share your .NET Framework sample project here.

**Comment by kirsan31** [comment]
@RussKie I think @John-Qiao mean opposite thing - he can't repro this.
Sadly, I can't test it by myself for now.

**Comment by JeremyKuhne** [comment]
I've validated that the behavior is consistent with .NET Framework (tested 3.5 through 4.8). There is no easy way, afaik, to get the ampersand to show up outside of using `&&`.

You can fully customize the strip's `Renderer`, but that is not a trivial task. Creating a derived renderer also would require some work as you can't simply add the `TextFormatFlags.NoPrefix` before rendering (`OnRenderItemText`). The label size calculations would also have to be adjusted.

@the-namelessone if you can get a repro to share we'd be happy to dig into it further.
