### ISSUE TITLE
Edit Assembly Info button is missing

### ISSUE THREAD

**Issue by manfromarce** [dotnet/winforms#4307]
* .NET Core Version: 3.1 / 5.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
In .NET Framework Windows Forms projects there is a button to edit application assembly information in project Properties page. This button is missing in C# .NET Core projects, while in Vb.Net .NET Core Projects is visible but disabled. I'm using Visual Studio 16.8.2 and this happens in both .NET Core 3.1 and .NET 5.0.

**Expected behavior:**
I'd like to edit assembly information like in .NET Framework.
![Immagine 2020-12-01 175534](https://user-images.githubusercontent.com/45036600/100772381-c6ce0680-33ff-11eb-87f9-2e0d4451c2bc.png)

**Minimal repro:**
Just create a new .NET Core project and go to Project > Properties...

**Comment by Zheng-Li01** [comment]
This is should be a common issue, which also can reproduce on console & WPF core project(C# & VB).

**Comment by RussKie** [comment]
By default a .NET Core/.NET apps don't have AssemblyInfo.cs files, as the responsibility previously carried by this file has been shifted. Version and projects properties can either be expressed directly in a project file, or via `props` files (such as [Directory.Build.props](https://docs.microsoft.com/visualstudio/msbuild/customize-your-build)).

Instead now you have "Package" tab that shows your package related information:
![image](https://user-images.githubusercontent.com/4403806/101112001-82757d00-3630-11eb-818d-571c1cdb7fb5.png)
