### ISSUE TITLE
Cursor static accessors not threadsafe / test flaky

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#4309]
**.NET Core Version:**
master branch

**Have you experienced this same bug with .NET Framework?:**
did not check

**Problem description:**
The static accessors of the `Cursor` class are not threadsafe, if two threads attempt to access the same cursor at roughly the same time then two distinct instances of the cursor will be created.

This causes `CursorConverter_GetStandardValues_Invoke_ReturnsExpected` test to be flaky.

**Expected behavior:**
Either adjust the `Cursor` class to be threadsafe (using a `lock` statement or `Interlocked.CompareExchange` instead of unprotected `??=` syntax) or adjust the test in some way to not be flaky.

**Minimal repro:**
Not reproducable deterministcally, test is flaky and may fail.

**Comment by RussKie** [comment]
We need to fix the test.

**Comment by weltkante** [comment]
One possible solution is to run the CursorConverter twice, the first run being a dry run to ensure variables are initialized, the second call being used to capture the values. I'll prepare a PR.
