### ISSUE TITLE
The value of ListViewGroup’s TitleImageIndex cannot be saved successfully

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#4310]
Duplicate of https://github.com/dotnet/winforms-designer/issues/2057

## Minimal Reproduction Scenario
1.	Create a winforms .NET 5.0 project.
2.	Drag and drop a ListView & a ImageList to Form.
3.	Choose one image to ImageList, then add this code line into Form1.designer.cs file: this.listView1.GroupImageList = this.imageList1;
4.	Open form designer, add a ListViewGroup(Header = Group1) and a ListViewItem(Text = TextStr).
5.	Set the Group property of ListViewItem to ‘Group1’.
6.	Set the TitleImageIndex property of ListViewGroup to ‘0’.
7.	Save the project, close form designer and reopen again.

## Expected Behavior
The image that set previously should not disappear.

## Current Behavior
The image that set previously disappeared.
![CodeLine](https://user-images.githubusercontent.com/18568603/86090448-af9b8d80-badc-11ea-832f-e170241e2ac9.PNG)
![NotSaved](https://user-images.githubusercontent.com/18568603/86090426-a6122580-badc-11ea-85d0-46cb5082a332.gif)

**Comment by RussKie** [comment]
From @DustinCampbell 

> It looks to me like this is probably a runtime issue. `ListViewGroup.TitleImageIndex` lacks the following attribute, which connects it with the correct `ImageList`:
> 
> ```cs
> [RelatedImageList("ListView.TitleImageList")]
> ```
> 
> See `TreeNode.StateImageIndex` for an example.


From @RussKie

> how does it work for the ListView items? None of them decorated with this attribute:
> [dotnet/winforms@`1ddd8c4`/src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs#L431-L442](https://github.com/dotnet/winforms/blob/1ddd8c457179a7b5be28b3cba8bb44f30cf15ee3/src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs#L431-L442)
> [dotnet/winforms@`1ddd8c4`/src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs#L469-L479](https://github.com/dotnet/winforms/blob/1ddd8c457179a7b5be28b3cba8bb44f30cf15ee3/src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs#L469-L479)
> ...but a user can set/select an image from `LargeImage`/`SmallImageList`?
> ![image](https://user-images.githubusercontent.com/4403806/100608267-40aeb300-3360-11eb-999c-f4670252917f.png)


From @DustinCampbell 

> [For `ListView`] It works for `ListViewItem.ImageIndex` because there is an `ImageList` property defined on that type. `ListViewItem.StateImageIndex` defines a `[RelatedItemList]`:
> 
> [dotnet/winforms@`1ddd8c4`/src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs#L684-L692](https://github.com/dotnet/winforms/blob/1ddd8c457179a7b5be28b3cba8bb44f30cf15ee3/src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs#L684-L692)


From @RussKie 

> To confirm, if a type defines `ImageList` property `ImageKey` and `ImageIndex` on that property will automagically work, for other props to work they need `RelatedItemListAttribute` applied, right?

From @DustinCampbell 

> Actually, it's the reverse. If a property has a `[RelatedmageList]` attribute, it will use that. Otherwise, it will look for an `ImageList` on the current type. The relevant code is in [`ImageIndexEditor`](https://github.com/dotnet/winforms/blob/2ae45c66fdcb8e6aadf43288b7429f17f1fd0f49/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageIndexEditor.cs).

**Comment by Jenna-Zheng** [comment]
@RussKie this issue also reproduce on .NET 6.0.
