### ISSUE TITLE
[Accessibility] ListViewItem has no keyboard tooltip

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4320]
- .NET Core Version: 5.0
- Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
* ListViewItem has no keyboard tooltip when pressing the right/left arrow or Tab button to navigate to a ListViewItem which got the keyboard focus

**Expected behavior:**
* ListViewItem has a keyboard tooltip

**Minimal repro:**
1. Create .Net Core 5.0 app
2. Add a ListView to the app
3. Add items to the ListView
4. Set tooltips for ListViewItems
5. allow showing tooltips for items
6. Run the app and try to get a item tooltip using a keyboard navigation

**Comment by Jessie-Zhang01** [comment]
Verified the issue with .Net SDK 6.0.100-preview.3.21169.6, this issue is fixed. ListViewItem has a keyboard tooltip.
![step](https://user-images.githubusercontent.com/45864649/111961391-f9754980-8b2b-11eb-82a0-08f921dfbedb.gif)
