### ISSUE TITLE
Radio button "arrow order" cannot be configured

### ISSUE THREAD

**Issue by wjk** [dotnet/winforms#4321]
## Problem description
When I add multiple RadioButton controls to a form, they are navigated between as a group using the arrow keys instead of the Tab key. (Only the focused radio button in a group has `TabStop=true`.) However, the order in which the controls are added to this "arrow order" array appears to depend on the order with which they were added to the form in the `InitializeComponent()` method. Since the order of calls in this method cannot be manually changed (without being immediately reverted by the designer), I cannot set the "arrow order" myself. In my project, the runtime "arrow order" happens to be bottom-to-top (pressing the up arrow moves the focus to the next radio button _below_ the currently focused button), but I believe that is due to sheer random chance. It could just as well be in a meaningless, seemingly random order.

I need a way to ensure that the "arrow order" is logically related to the visual position of the controls on the form. I don't know what this should look like in terms of API, as (a) the ordering of a group of radio buttons needs to be independent of any other group of radio buttons on the form, and (b) this logic appears to be performed by native code, not by Windows Forms proper.

_Have you experienced this same bug with .NET Framework?_ 
Have not checked, as .NET Framework is EOL.

## Version info
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20262
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik this sounds awfully familiar. Did we have any thoughts on the issue? If I recall correctly it has to do with the order in which the controls are added to the Controls collection, but I could be wrong.

@vladimir-krestov / @SergeySmirnov-Akvelon this may impact our accessibility users too.

**Comment by wjk** [comment]
@merriemcgaw This is very much affected by the order in which controls are added to the collection. I deleted the offending component from the Designer and recreated it manually in my constructor, adding each radio button in the correct order, and it works great.

**Comment by weltkante** [comment]
You should be able to change the control order by "bring to front" / "bring to back" menus in the designer, or through the document outline view. If these no longer work that a defect in the new designer.

**Comment by vladimir-krestov** [comment]
@merriemcgaw, this sounds familiar maybe because of #2164 but it doesn't relate to this issue.
- Objects are in the order of adding in `Controls` property of a form in the accessibility tree.
![image](https://user-images.githubusercontent.com/49272759/101276205-335c5300-37bc-11eb-9431-5ebfbdf276a4.png)
- `TabStop` doesn't affect the order of the arrow keys 
- @wjk, did you tried to use `TabIndex` property? As I see, `TabIndex` values affect the order of moving using the arrow keys.
For example:
```cs
            // 
            // radioButton1
            // 
            ...
            this.radioButton1.TabIndex = 3;
            ...
            // 
            // radioButton2
            // 
            ...
            this.radioButton2.TabIndex = 0;
            ...
            // 
            // radioButton3
            // 
            ...
            this.radioButton3.TabIndex = 2;
            ...
            // 
            // radioButton4
            // 
            ...
            this.radioButton4.TabIndex = 2;
            ...
```
Or just set these values using Designer
![image](https://user-images.githubusercontent.com/49272759/101276508-6acbff00-37be-11eb-869e-8664ec22984f.png)

**Comment by wjk** [comment]
@vladimir-krestov I have not worked on this project since December 3rd. However, when I tried the Edit > Tab Order command, every radio button showed up with a TabIndex of zero, and clicking them did not change that. Thanks!

**Comment by vladimir-krestov** [comment]
The arrow key moving order will be like as the order of adding these `RadioButtons` to a form (to `Controls` property) if all of these `RadioButtons` have `TabIndex` == 0.
But we can set a custom order if to set some `TabIndexes`.
@wjk, can we close this issue?

**Comment by wjk** [comment]
Done. 😄

**Comment by vladimir-krestov** [comment]
Thank you! 😊
