### ISSUE TITLE
Component designer does not display when targeting .NET Core/.NET Standard

### ISSUE THREAD

**Issue by davkean** [dotnet/winforms#4333]
_From @JinShil on April 29, 2017 7:47_

.Net Standard 2.0 and .Net Core 2.0 have included APIs in `System.ComponentModel` for building and extending the Visual Studio designer (e.g `Component` class, `DesignerAttribute`, `TypeConverter`, etc..) 

However, if one tries to use these classes in the current release of Visual Studio 2017 to create designers for their classes, Visual Studio displays errors in the designer like

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;

namespace CoreDesignerTest
{
    public class Class1 : Component
    {
    }
}
```

In Visual Studio, right-click on the "Class1.cs" node and choose "View Designer".

> Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. 

With some hacking in my .config files, I can resolve the above error, but eventually Visual Studio fails to load the .Net Core assemblies with an "Invalid Format" error.

I'm assuming this is due to the fact that Visual Studio, being a .Net Framework-based application, is trying to load a .Net Core assembly into a .Net Framework application, and therefore failing.

My question is, with the coming release of .Net Core 2.0 and .Net Standard 2.0, will there also be an accompanying Visual Studio update that will provide the ability to create designers for .Net Core 2.0 and .Net Standard 2.0 classes?

_Copied from original issue: dotnet/corefx#19139_

**Comment by RussKie** [comment]
The component designer is currently being worked on, and it is currently expected to become available in 16.9 GA.
With that only .NET Core 3.1 and .NET 5.0 scenario will work. Windows Forms does not support anything earlier than that.

**Comment by StevenBonePgh** [comment]
Perhaps the issue I filed in [Developer Community 'WinForms Designer Uses Assembly from Wrong Target Framework of a Project Dependency'](https://developercommunity.visualstudio.com/t/winforms-designer-uses-assembly-from-wrong-target/1379457) is related to this? Perhaps we are talking about different issues with a similar workaround. 

@davkean - I do suspect at least my issue may be related to Project System. If an SDK-style multitargeted library project ‘A’ is referenced by another project ‘B’ (any project file-type), Form or UserControl classes in project ‘B’ that inherit from types in ‘A’ can fail to load in the designer if netstandard2.0 is listed first in <TargetFrameworks> in project ‘A’, and the inherited WinForm types are excluded from the netstandard2.0 compilation. I'd expect that in the case of project B, as an SDK style project, would select a more appropriate target than netstandard from 'A' regardless of ordering. If 'A' is built into a nuget package, and switched from a project reference to package reference, 'B' will not select the netstandard variant and the designer functions properly - so there is certainly a behavioral difference between these reference types.  

Sadly, in my case a reorder workaround is not possible without extra work as this project is also referenced by a Xamarin project which (of course) needs to have netstandard as the first target framework. The only workaround is to change the order in 'A', restart visual studio, design, then revert the order back if compilation with a Xamarin reference is required.

This can be seen in Visual Studio 2019 16.9.2 and 16.10.0 Preview 1.0

**Comment by RussKie** [comment]
This doesn't appear to be an issue in VS 2022.
