### ISSUE TITLE
AccessibilityInsights: ComboBox items should support ScrollItem Pattern when list shows scrollbar

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#4335]
* .NET Core Version: 
6.0.100-alpha.1.20603.2

* Have you experienced this same bug with .NET Framework?: 
Yes,
This is a regression issue, can repro in .Net 4.8 for comboBox with all dropdownstyle values, and in .Net 4.7.2, just comboBox items with comboBox's dropdownstyle: simple can repro this issue.

**Minimal repro:**
1. Create a Winforms .Net Core app with 3 comboBox controls, set their's DropDownHeight property to show scrollbar for comboBox list
Or open attached sample project and run Core app directly
[CoreTesting4.zip](https://github.com/dotnet/winforms/files/5656313/CoreTesting4.zip)
2. Use Accessibility Insights or Inspect tool to test ComboBox dropdown items

**Actual behavior:**
Accessibility Insights detects errors for comboBox items, which don't support ScrollItem Pattern
![image](https://user-images.githubusercontent.com/26474449/101428363-84df1c00-393b-11eb-8429-396ec254c352.png)

**Expected behavior:**
ComboBox items for comboBox's all dropdownstyles support ScrollItem Pattern

**Comment by Zheng-Li01** [comment]
Verified the issue with latest 6.0 SDK 6.0.100-preview.1.21071.29 that the issue has been fixed, the ComboBox items support ScrollItem Pattern when list shows scrollbar, see below screenshot.
![4335](https://user-images.githubusercontent.com/38325459/105462058-1080f200-5cc9-11eb-9648-27e1eb032d7e.PNG)

**Comment by John-Qiao** [comment]
Verified the issue with latest .NET SDK 5.0.103 from February Test Pass, this issue is fixed.
![Result1](https://user-images.githubusercontent.com/45864985/105830228-362b3580-6000-11eb-99f8-cc70db47b2d8.png)
![Result2](https://user-images.githubusercontent.com/45864985/105830233-375c6280-6000-11eb-87f4-b2a895c0f24b.png)
