### ISSUE TITLE
DataBinding object property to static list in ComboBox is calling EndEdit on model containing said property.

### ISSUE THREAD

**Issue by LethiferousMoose** [dotnet/winforms#4349]
* .NET Core Version: .NET 5

* Have you experienced this same bug with .NET Framework?: Haven't tested yet, will try tomorrow.

**Problem description:**
So I've been Googling this for several hours and I haven't found much, so I'm not sure if I am doing it wrong or if this is a bug.

I have a class with a string property, this property can be one of two values, for sake of example we will say A or B:
```c#
internal class Model : IEditableObject
{
    public string TestString { get; set; } = "A";

    public void BeginEdit()
    {
        Debug.WriteLine("BeginEdit");
    }

    public void CancelEdit()
    {
        Debug.WriteLine("CancelEdit");
    }

    public void EndEdit()
    {
        Debug.WriteLine("EndEdit");
    }
}
```

In my form I setup a databinding for `SelectedItem` on `TestString`:

```c#
BindingSource bindingSource = new BindingSource(new Model(), "");
comboBox1.DataSource = new BindingSource(new string[] { "A", "B" }, ""); // Tried this with and without a BindingSource, probably don't need it.
comboBox1.DataBindings.Add("SelectedItem", bindingSource, "TestString");
```

The issue is, whenever the combobox runs it's `OnValidation` call setup via the binding, it is calling `EndEdit` in `Model` even though the `DataSource` for the combobox is not the model, it's supposed to be a static list.

Either I am missing something super obvious, or I've done something wrong, cause I am super confused. I followed the same pattern for `TextBoxes` and NumericUpDowns` and those work fine. Not sure yet if this only applies to .NET 5, I will check tomorrow.

**Expected behavior:**
The property on `Model` should be updated and editing should not be completed.

**Minimal repro:**
See above code snippets.

**Comment by weltkante** [comment]
I couldn't setup a scenario that matches your description, can you provide a small sample form that sets up the controls in a way to reproduce what you are observing?

> The issue is, whenever the combobox runs it's OnValidation call setup via the binding, it is calling EndEdit in Model even though the DataSource for the combobox is not the model, it's supposed to be a static list.

The DataSource for the combobox provides the content of the dropdown, but the combobox does not edit the list. You have explicitly setup a binding which writes `SelectedItem` into your model, this is probably the binding source that calls `EndEdit` - but without a concrete scenario to debug its hard to tell what is happening.

**Comment by LethiferousMoose** [comment]
Okay you were right, there was something else in the mix, here's a stripped down version of my form:

Form1.cs
```c#
    public partial class Form1 : Form
    {
        private readonly Model testModel;
        private readonly BindingSource bindingSource;

        public Form1()
        {
            InitializeComponent();
            testModel = new Model();
            bindingSource = new BindingSource(testModel, "");
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            numericUpDown1.DataBindings.Add("Value", bindingSource, "TestInteger");
            comboBox1.DataBindings.Add("SelectedItem", bindingSource, "TestString");
        }

        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {
            string testValue = comboBox1.SelectedItem.ToString();

            if ("B".Equals(testValue, StringComparison.OrdinalIgnoreCase))
            {
                numericUpDown1.Minimum = 1;
            }
            else
            {
                numericUpDown1.Minimum = 50;
            }
        }

        private void button1_Click(object sender, EventArgs e)
        {
            Debug.WriteLine("Save");
        }
    }
```

Form1.Desginer.cs
```c#
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.numericUpDown1 = new System.Windows.Forms.NumericUpDown();
            this.button1 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown1)).BeginInit();
            this.SuspendLayout();
            // 
            // comboBox1
            // 
            this.comboBox1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "A",
            "B"});
            this.comboBox1.Location = new System.Drawing.Point(12, 12);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(195, 23);
            this.comboBox1.TabIndex = 0;
            this.comboBox1.SelectedIndexChanged += new System.EventHandler(this.comboBox1_SelectedIndexChanged);
            // 
            // numericUpDown1
            // 
            this.numericUpDown1.Location = new System.Drawing.Point(12, 41);
            this.numericUpDown1.Name = "numericUpDown1";
            this.numericUpDown1.Size = new System.Drawing.Size(195, 23);
            this.numericUpDown1.TabIndex = 1;
            this.numericUpDown1.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(12, 137);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(66, 29);
            this.button1.TabIndex = 3;
            this.button1.Text = "Save";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // Form1
            // 
            this.AcceptButton = this.button1;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(219, 178);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.numericUpDown1);
            this.Controls.Add(this.comboBox1);
            this.Name = "Form1";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ComboBox comboBox1;
        private System.Windows.Forms.NumericUpDown numericUpDown1;
        private System.Windows.Forms.Button button1;
    }
```

Model.cs
```c#
    internal class Model : IEditableObject
    {
        public int TestInteger { get; set; } = 1;

        public string TestString { get; set; } = "B";

        public void BeginEdit()
        {
            Debug.WriteLine("BeginEdit");
        }

        public void CancelEdit()
        {
            Debug.WriteLine("CancelEdit");
        }

        public void EndEdit()
        {
            Debug.WriteLine("EndEdit");
        }
    }
```

Repo steps:

1. Change the value in the numeric up down
2. Change the drop down menu to A
3. Press Save

I have two curiosities now:
1. This is related to the second binding
OR
2. Perhaps related to having an accept button bound to the form?

**Comment by weltkante** [comment]
As far as I can tell you have a runtime binding error, `public int TestInteger { get; set; } = 1;` but `numericUpDown1.Minimum = 50;`

During the binding an exception is thrown and caught, the binding system panics and flushes all pending edits before trying to recover.

**Comment by LethiferousMoose** [comment]
So I guess I was confused because it binds the `1` to the numeric up down, so are saying changing the minimum to `50` which by proxy changes the value in the box to `50` is not simply treated as the value changing to a new value?

**Comment by weltkante** [comment]
There are several things happening making everything very complicated:
- your bindings are in `OnValidation` mode, that is they will write back the value to the model on validation (usually when focus leaves the control)
- you change the `Minimum` immediately when the combobox selection changes; the `Value` of the `NumericUpDown` is updated but not written back because all bindings are in `OnValidation` mode
- when you leave the combobox the `SelectedItem` is written back to the model (not the `Value` of the `NumericUpDown` because it is not the control being validated)
- since you don't implement `INotifyPropertyChanged` on your model the binding system refreshes all bindings to make sure everything is up to date after writing back the value
- the model still has `TestInteger = 1` and tries to refresh the `NumericUpDown` but this is no longer possible because `Minimum = 50`
- the binding system catches the exception and calls `EndEdit` to recover from the binding error

**Comment by LethiferousMoose** [comment]
That all makes sense, although I thought you only needed to use `INotifyPropertyChanged` if you planned on updating the model outside of the form in order for it to propagate the new values to form. But if I added that interface I could update the model values to keep them in sync with the new minimum and things should stay happy.

**Comment by weltkante** [comment]
If you don't implement `INotifyPropertyChanged` the binding source will do it for you. Every write to the model will raise a change event (not on the model directly, on the binding source, called `ListItemPropertyChanged`) but without knowing _which_ property might have changed it will pull all properties from the model just to be safe.

In simple scenarios this is fine, but if you have dependent bindings it makes your life more complicated, because you have to pay attention to the order of things you do. If you don't want to pay this attention you can implement `INotifyPropertyChanged` and take over the responibility of notifying the binding engine of which exact properties change.

Alternatively use distinct binding sources instead of sharing the binding source.

**Comment by LethiferousMoose** [comment]
Okay, thanks for the help! I will make corrections based on your feedback.
