### ISSUE TITLE
NotifyIcon.Text limits text to 63 characters, but should be 127

### ISSUE THREAD

**Issue by AlexVallat** [dotnet/winforms#4361]
* .NET Core Version: 5

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
Setting `.Text` on a `NotifyIcon` throws `ArgumentOutOfRangeException` if the value is greater than 63 characters. However, the limit for tooltip characters has been 127 characters since Windows 2000 (ref: https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ns-shellapi-notifyicondataw#nif_showtip-0x00000080) and .NET 5 is not supported on anything prior to Windows 7 (ref https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md)

**Expected behavior:**
No exception to be thrown for strings between 64 and 127 characters in length

**Minimal repro:**
`new NotifyIcon().Text = new string('a', 64);`

**Comment by RussKie** [comment]
.NET Framework supports Windows all the way back to Windows 98, so 63 char restriction would have been placed since the beginning. Since .NET supports newer OS, the limit can be brought to 127. 
You're welcome to send a PR.

**Comment by paul1956** [comment]
@RussKie I would be happy to fix.

**Comment by Ashley-Li** [comment]
Verified this issue with .Net 6.0 latest build: .NET SDK 6.0.100-alpha.1.21062.11, issue was fixed. No exception to be thrown for strings between 64 and 127 characters in length.
![NotifyIcon_issueReTest](https://user-images.githubusercontent.com/56664234/104437512-b7d08d00-5543-11eb-9c8c-69b679d0f1cf.gif)
