### ISSUE TITLE
Control binding to data source is not working.

### ISSUE THREAD

**Issue by elamey** [dotnet/winforms#4362]
* .NET Core Version: 
.NET Core Version: 5.0

* Have you experienced this same bug with .NET Framework?: 
 No

**Problem description:**
Binding a control is not working. Example, when attempting to bind a checkbox "checked" state to a my.settings property, the data binding dialog has no data sources to bind to and there are no options to create on.

**Expected behavior:**
Add binding to a control (example, checkbox) for state, text etc...

**Minimal repro:**
New .NET 5.0 project, added check box to the form. Navigated to properties, data bindings, checked. Dialog box shows no options.

**Comment by RussKie** [comment]
Please refer to our latest blog discussing the databinding in the OOP designer: https://devblogs.microsoft.com/dotnet/databinding-with-the-oop-windows-forms-designer/.

If you still have specific issues, please open a new issue with a clear description of what is not working and provide screenshots/animations to help triaging the issue.
