### ISSUE TITLE
AccessibilityInsights' display about ‘specific item focusable’ on form is not correct when going through some list items for ComboBox/ListBox/CheckedListBox/TreeView controls

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#4364]
* .NET Core Version: 
.Net SDK 6.0.100-alpha1.1.20612.2

* Have you experienced this same bug with .NET Framework?: 
Yes, it is not a regression issue

**Minimal repro:**
1. Open attached sample app and run it in VS
[CoreTesting.zip](https://github.com/dotnet/winforms/files/5694019/CoreTesting.zip)
2. Use Accessibility Insights tool to go through list items for ComboBox/ListBox/CheckedListBox/TreeView controls, and observe the AccessibilityInsights' display about 'which item focusable’ on form

**Actual behavior:**
AccessibilityInsights' display about 'which item focusable’ on form for some items are not correct, don't keep consistent with the list item we are focused by mouse or keyboard
![image](https://user-images.githubusercontent.com/26474449/102184760-ef1f3000-3eea-11eb-939b-6be9e46a4493.png)
![Issue1](https://user-images.githubusercontent.com/26474449/102184800-04945a00-3eeb-11eb-946f-98cb7f4c5752.gif)

**Expected behavior:**
AccessibilityInsights' display about 'which item focusable’ on form keeps consistent with the list item we are focused by mouse or keyboard

**Comment by SergeySmirnov-Akvelon** [comment]
Closed as [external bug](https://github.com/microsoft/accessibility-insights-windows/issues/1123)
