### ISSUE TITLE
Bounding rectangle is displayed for invisible items in ComboBox

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4372]
Have you experienced this same bug with .NET Framework?:
- Yes

**Repro steps:**
CASE 1:
1. Сreate a ComboBox with 10 options
2. Set DropDownStyle = Simple
3. Set Height = 150
4. Run application
5. Select an item in the Inspect that is invisible in the ComboBox
![Issue-4372-case1](https://user-images.githubusercontent.com/23376742/102221998-e848eb00-3ef3-11eb-84ff-c936a7c9f9fd.gif)

CASE 2:
1. Сreate a ComboBox with several options
2. Set DropDownStyle = DropDown or DropDownList
3. Run application
4. Expand drop down list
5. Select an item in the Inspect
![Issue-4372-case2](https://user-images.githubusercontent.com/23376742/102222029-f0a12600-3ef3-11eb-9208-d4c3b378b558.gif)

**Actual:**
Bounding rectangle is displayed for invisible items

**Expected:**
Bounding rectangle should not be displayed for invisible items

**Note:**
The issue is reproduced for the ComboBox in the DataGridView

**Comment by Tanya-Solyanik** [comment]
Do AccessibilityInsights find this issue? Let's re-triage it. This could be a bug in inspect.

**Comment by Jenna-Zheng** [comment]
@SergeySmirnov-Akvelon  Verified this issue with 6.0.100-preview.5.21276.14 from Release/6.0.1XX-preview5 branch of https://github.com/dotnet/installer, it is still reproducing(NET 6.0 preview.5 and .NET 6.0 preview.6 are both reproducing this issue)
![test](https://user-images.githubusercontent.com/64949616/119804544-0559ff00-bf13-11eb-8e74-2828f4bf53f3.gif)

**Comment by SergeySmirnov-Akvelon** [comment]
Hi @Jenna-Zheng. We have left the current behavior of the bounding rectangle unchanged. During the discussion, it was decided that only "IsOffScreen" property and "OffScreen" state should take into account that the item is now invisible.

**Comment by Jenna-Zheng** [comment]
Verified this issue with 6.0.100-preview.5.21276.14 from Release/6.0.1XX-preview5 branch of https://github.com/dotnet/installer, it is fixed.
![image](https://user-images.githubusercontent.com/64949616/119808211-7c44c700-bf16-11eb-8d7f-c04b0b9d8148.png)
![image](https://user-images.githubusercontent.com/64949616/119808422-aeeebf80-bf16-11eb-9cdc-0e290313e6f5.png)
