### ISSUE TITLE
An exception pops up when setting the Combobox control's InteralHieght property value is true with Inspect tool

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#4391]
* .NET Core Version: 
.Net sdk 6.0.0-alpha.1.20570.2.

* More info:
1. The issue also can reproduce on .Net SDK 6.0 & 5.0 & 3.1.
2. The issue also can reproduce on Accessibility Insights tool.
3. The issue can reproduce Combobox control's dropdownstyle is dropdown, dropdownlist, not reproduce simple dropdown style.
4. The issue can't reproduce .NET Framework 4.8.
5. The issue can't reproduce if not opening the Inspect or Accessibility Insights tool.

* Have you experienced this same bug with .NET Framework?: 
No

**Minimal repro:**
1. Opened the application.[[6.0]ComboBox_ScrollIntoView (2).zip](https://github.com/dotnet/winforms/files/5713963/6.0.ComboBox_ScrollIntoView.2.zip)
2. Build and run it.
3. Open the Inspect or Accessibility Insights tool.
4. Checked the InteralHeight check box, and choose the items in the dropdown list.

**Expected behavior:**
[FraTesting1.zip](https://github.com/dotnet/winforms/files/5713981/FraTesting1.zip)
No exception pops up.
![FraNewIssue](https://user-images.githubusercontent.com/38325459/102581058-c55c4800-413a-11eb-8fab-abd4066c39f2.gif)

**Actual behavior:**
An exception pops up.
![CoreNewIssue](https://user-images.githubusercontent.com/38325459/102581018-b1b0e180-413a-11eb-9362-46c5ec914b1b.gif)

**Call Stack:**
[CallStack.txt](https://github.com/dotnet/winforms/files/5713980/CallStack.txt)

**Comment by Zheng-Li01** [comment]
Add more information.

The exception pops up when setting the InteralHieght property values by calling method, please see below details.
**For combobox4,** setting the InteralHieght property values as true in below code section, no exception pops up.
 public Form1()
        {
            InitializeComponent();
            **comboBox4.IntegralHeight = true;**
        }
**For combobox3,** setting the InteralHieght property values as true by calling **checkBox1_CheckedChanged** method, an exception pops up.

**Application:**
[CoreNewIssue.zip](https://github.com/dotnet/winforms/files/5714970/CoreNewIssue.zip)
**GIF:**
![ReproTheIssue](https://user-images.githubusercontent.com/38325459/102601469-2a279a80-415b-11eb-86fd-f0f688ee0993.gif)

**Comment by weltkante** [comment]
In the constructor the ComboBox handle is not created yet, which is likely the relevant difference to the CheckedChange handler.

**Comment by Zheng-Li01** [comment]
The issue also can reproduce when setting the OwnerDrawVariable & OwnerDrawFixed properties by calling method. see below GIF.
![UpdateCoreIssue](https://user-images.githubusercontent.com/38325459/103124724-9ce8c680-46c3-11eb-8435-cdaf377bb04f.gif)

**Comment by Zheng-Li01** [comment]
Verified the issue with NET 6.0.100-preview1 .21107.2, the issue is fixed for comboBox with all dropdownstyle: DropDown, DropDownList, Simple in accessibilityInsight and Inspect, when changing comboBox's IntegralHeight, DrawMode, MeasureItem properties, see below GIF.
![UpdateGH4391](https://user-images.githubusercontent.com/38325459/107310296-1d725380-6ac7-11eb-9156-cc833054b780.gif)

**Comment by Zheng-Li01** [comment]
Verified the issue based on .NET 6.0 Preview2[21127.3] Test Pass,the issue has been fixed.
