### ISSUE TITLE
ListBox ScroolIntoView implementation behavior is not consistent to native ListBox behavior

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#4392]
* .NET Core Version: 6.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
- `ListBox` `ScrollIntoView` implementation  is more complicates than it need to be - it scrolls an item to the bottom of a ListBox
![1](https://user-images.githubusercontent.com/49272759/102604299-08b3b800-4135-11eb-9aed-81c97c695523.gif)

**Expected behavior:**
- `ListBox` should have the same behavior as in .NET Framework or Win32 - scroll an item to the top of a ListBox
![2](https://user-images.githubusercontent.com/49272759/102604308-0baea880-4135-11eb-800d-cb89a5fcbb53.gif)

**Minimal repro:**
- Create a .NET 6.0 app
- Add a ListBox to the app
- Add some items to the ListBox (e.g. 10 items)
- Set a size for the ListBox to see a part of the items and see a vertical scrollbar
- Run the app and use Inspect to call ScrolIntoView method
- Compare with .NET Framework behavior

**Comment by vladimir-krestov** [comment]
@merriemcgaw, now the current behavior looks better to me 😄
Should we change it or keep it as is and close this issue?

**Comment by merriemcgaw** [comment]
Let's close it 😆
