### ISSUE TITLE
Trouble matching StatusBar layout with StatusBarStrip controls

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/winforms#4398]
Following up from twitter: https://twitter.com/clairernovotny/status/1340455330577330176

I've been having trouble trying to fixi the sizing of the statusstrip labels. StatusBar was removed in .NET 3.x and the strip version's don't layout the same.

Top: StatusBar
Bottom: strip... blank stuff isn't sized statically and setting autosize false doesn't work.

![image](https://user-images.githubusercontent.com/1427284/102713719-41b86d80-4298-11eb-886f-c2ece0487252.png)

The idea is that the variable/fill-sized portion is on the left, and there are a few items that should be fixed-width that are aligned to the right. Some of those items have their text set to null/empty sometimes.

If I turn autosize off, then the item doesn't even show up.

To repro, clone https://github.com/RssBandit/RssBandit/

The relevant code is here: https://github.com/RssBandit/RssBandit/blob/main/source/RssBandit/WinGui/Forms/WinGUIMain.cs#L1223-L1273

Note that the WinForms designer doesn't load.... so need to do this all by hand and run to test. Set the Package project as the startup and run that for testing.

**Comment by RussKie** [comment]
How is it supposed to look?

**Comment by clairernovotny** [comment]
The top in the screenshot is correct

**Comment by RussKie** [comment]
Can you please provide a small repro. 

I tried loading your app at origin/main 34b8fe07c340ecef6bb494c79ab62a1ab6d7039a and 57a0f77da19ec2eb4c7fd671cf1e492797815c56 and when the app ran it opened notepad.exe for me.

**Comment by clairernovotny** [comment]
@RussKie That's correct, you have to set the package project as the startup. Notepad.exe is to prevent folders from being added to the real filesystem that will interfere with the file redirection in the MSIX sandbox.

**Comment by clairernovotny** [comment]
Not sure what this is waiting on?

**Comment by RussKie** [comment]
We're waiting on a sample repro. Unfortunately we don't capacity to debug client applications.
