### ISSUE TITLE
Erro on choose image in a picture box

### ISSUE THREAD

**Issue by luismaruccio** [dotnet/winforms#4403]
* .NET Core Version: 
 5.0.101

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

When trying to choose the image of a Picture Box, in the properties windows, and the images in the resources are like "Embedded in .resx", this error is displayed: "Object reference not set to an instance of an object."

**Expected behavior:**
Show the dialog box for selecting the image.

**Minimal repro:**
Just try to select the image through the properties window, and the image inside Resources is in Persistence set to "Embedded in .resx"

**Comment by JeremyKuhne** [comment]
@luismaruccio Can you please share the version of VS your using?

@KlausLoeffelmann when you're back in can you validate where we are with these scenarios currently?

**Comment by luismaruccio** [comment]
Visual Studio Enterprise 2019 - Version 16.8.3

**Comment by Zheng-Li01** [comment]
There have a [designer issue ](https://github.com/dotnet/winforms-designer/issues/2664) to track it.

**Comment by dreddy-work** [comment]
Tracked designer issue is fixed in latest VS versions ( yet to release). Closing this issue.
