### ISSUE TITLE
The focus rectangle for drop down list of ComboBox control doesn't include the "Vertical" scroll bar with Inspect tool

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#4404]
* .NET Core Version: 
.NET SDK 6.0.0-alpha.1.20570.2

* More info:
The issue also can reproduce with Accessibility insights tool.

* Have you experienced this same bug with .NET Framework?: 
 Yes, the issue can reproduce .NET 4.8, ,can't reproduce 4.7.2. 

**Minimal repro:**
1. Extract the application build & run it.[FraTesting1.zip](https://github.com/dotnet/winforms/files/5732859/FraTesting1.zip)
2. Open the Inspect / Accessibility Insights tools.
3. Expand the drop down list by pressing the F4 or Alt + Down arrow.
4. Try to focus on the drop down list, and observe the focus rectangle.

**Expected behavior:**
The focus rectangle include the "Vertical" scroll bar.
![Expected](https://user-images.githubusercontent.com/38325459/102950988-c8728200-4506-11eb-86f6-9987e35cb26f.PNG)

**Actual behavior:**
The focus rectangle doesn't include the "Vertical" scroll bar.
![Actual](https://user-images.githubusercontent.com/38325459/102950996-cc9e9f80-4506-11eb-8d41-701161e839c7.PNG)

**Comment by merriemcgaw** [comment]
Let's leave this on the backlog and compare with the native control. If we get customer or test pass complaints we can prioritize higher.
