### ISSUE TITLE
HelpProvider is unable to show Unicode characters

### ISSUE THREAD

**Issue by r-aghaei** [dotnet/winforms#4422]
**.NET Core Version:** 
* .NET 5

**Have you experienced this same bug with .NET Framework?**
* Yes

**Problem description:**

[HelpProvider](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.helpprovider?view=net-5.0&WT.mc_id=DT-MVP-5003235) component is unable to show Unicode characters (e.g. Persian language):

![image](https://user-images.githubusercontent.com/25272166/103447074-72010280-4cc1-11eb-8997-f8ab7373e648.png)

I also have set the language for non-Unicode programs to "Persian" language (in regional settings):

![image](https://user-images.githubusercontent.com/25272166/103447036-0dde3e80-4cc1-11eb-864a-1c3a6a942f2c.png)

**Expected behavior:**
Like all other controls and components, it should be able to show Unicode characters, regardless of the regional settings, or at least respect to regional settings.

![image](https://user-images.githubusercontent.com/25272166/103447128-fd7a9380-4cc1-11eb-8295-98f70573c530.png)

**Minimal repro:**

    var f = new Form();
    f.HelpButton = true;
    f.MinimizeBox = f.MaximizeBox = false;
    var button = new Button()
    {
        Text = "Click on help button and then on me!",
        AutoSize = true
    };
    f.Controls.Add(button);
    var helpProvider = new HelpProvider();
    helpProvider.SetHelpString(button, "متن آزمایشی");
    helpProvider.SetShowHelp(button, true);
    f.Show();

**Comment by r-aghaei** [comment]
The problem is in `Help` class([.NET 4.X](https://referencesource.microsoft.com/?WT.mc_id=DT-MVP-5003235#System.Windows.Forms/winforms/Managed/System/WinForms/Help.cs,160), [.NET 5](https://github.com/dotnet/winforms/blob/6391b524dd64e7530eba986c6607bf129b3ec8ae/src/System.Windows.Forms/src/System/Windows/Forms/Help.cs?WT.mc_id=DT-MVP-5003235#L106)). I has created the `HH_POPUP` but didn't specified any font. As a result a default font which doesn't support Unicode characters will be used. The fix could be using a default font like `SystemFonts.CaptionFont` which supports Unicode characters.

To demonstrate the possible fix, I've already implemented a [`HelpProvider2`](https://github.com/r-aghaei/HelpProvider2Example?WT.mc_id=DT-MVP-5003235) (by modifying the built-in HelpProvider and fixing the problem as I mentioned above) which supports Unicode characters and also supports Font, ForeColor and BackColor:

![HelpProvider2](https://user-images.githubusercontent.com/25272166/103445456-38270080-4caf-11eb-9121-d540149ff0b4.png)

![HelpProvider2Properties](https://user-images.githubusercontent.com/25272166/103445455-378e6a00-4caf-11eb-994b-8da9b041aa03.png)

**Comment by RussKie** [comment]
Thank you for the investigation.

We'll need to have an internl discussion about it, but a fix could be something like this:
```diff
diff --git a/src/System.Windows.Forms/src/System/Windows/Forms/Help.cs b/src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
index c815ba705..4cf558f62 100644
--- a/src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
+++ b/src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
@@ -111,9 +111,18 @@ namespace System.Windows.Forms
                 clrForeground = new COLORREF(unchecked((uint)-1)),  // Ignore
                 clrBackground = SystemColors.Window
             };
+
+            var font = SystemFonts.CaptionFont;
+            string captionFont = $"{font.Name}, {font.Size}, , " +
+                $"{(font.Bold ? "BOLD" : "")}" +
+                $"{(font.Italic ? "ITALIC" : "")}" +
+                $"{(font.Underline ? "UNDERLINE" : "")}";
+
-            fixed (char* pszText = caption)
+            fixed (char* pszText = caption, pszFont = captionFont)
             {
                 pop.pszText = pszText;
+                pop.pszFont = pszFont;
+
                 ShowHTML10Help(parent, null, HelpNavigator.Topic, pop);
             }
         }
```

...and then it'd work as expected (I don't have any Arabic languages installed or configured):
![image](https://user-images.githubusercontent.com/4403806/103492587-129d2100-4e80-11eb-8e3e-918b22a7e8dc.png)

**Comment by merriemcgaw** [comment]
It looks like we have 2 possible approaches here:

1. The first option would be to identify the best System font to use for the HelpProvider. My thought is that we could/should possibly try to match ToolTip fonts for consistency, but we could look at a couple of options and take a PR with the best looking one 😄 . We'd be more than happy to review a PR from you @r-aghaei 😄 
2. If we hear that customers need more flexibility we can revisit this issue and update the API to take a font parameter to allow developers to establish whatever font they'd like.

For now my preference is #1. I'd like to take a little bit of time to figure out how we get the font for ToolTips, if in fact they do support unicode characters. Then we should attempt to match. Failing that the `SystemFonts.CaptionFont` seems quite reasonable to me.

**Comment by r-aghaei** [comment]
[`SystemFonts.StatusFont`](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.systemfonts.statusfont?view=dotnet-plat-ext-5.0&WT.mc_id=DT-MVP-5003235) looks a good option. Its value comes from [`NONCLIENTMETRICSA.lfStatusFont`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-nonclientmetricsa?WT.mc_id=DT-MVP-5003235) which returns the font used in status bars and tooltips. WPF ToolTip also [uses the same](https://github.com/dotnet/wpf/blob/d49f8ddb889b5717437d03caa04d7c56819c16aa/src/Microsoft.DotNet.Wpf/src/Themes/XAML/ToolTip.xaml?WT.mc_id=DT-MVP-5003235#L33) as its default font.

**Comment by RussKie** [comment]
Thank you, I think it is a good choice. Though it is hard to check, all fonts appear to be the same on W10 by default:
![image](https://user-images.githubusercontent.com/4403806/103718674-6ee87800-501b-11eb-895b-4dd51325fdee.png)

**Comment by elachlan** [comment]
ToolTip uses the following to get the font:
https://github.com/dotnet/winforms/blob/f8a04925b71017892bb20b8c8957282f4df24fb2/src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs#L2356-L2366

Does that mean we should just use `Parent.Font` if Parent is not null? Something like
```csharp
Font font = parent?.Font ?? SystemFonts.StatusFont ?? SystemFonts.DefaultFont;
```

**Comment by elachlan** [comment]
@merriemcgaw is my suggestion above okay? If so, I will put in a PR.

**Comment by Cassie-Li01** [comment]
Verified on latest .NET 8.0.100-preview.2.23101.9, issue is fixed. Screenshot as below:
![image](https://user-images.githubusercontent.com/96758262/216205995-56d08498-eb58-4656-8592-5ef9d896fa2c.png)

**Comment by Cassie-Li01** [comment]
Verified on 8.0 TP version .NET 8.0.100-preview.1.23105.3, issue is fixed. Screenshot same as above.

**Comment by Cassie-Li01** [comment]
Verified with .NET 8 Preview 1 TP build: .NET 8.0.100-preview.1.23108.10, issue is fixed. Screenshot as above
