### ISSUE TITLE
[Accessibility] An element of the given ControlType must support the SelectionItem pattern for some controls which AccessibleRole property is PageTab 

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#4429]
* .NET Core Version: 
.Net SDK 6.0.100-alpha.1.20623.10

* Have you experienced this same bug with .NET Framework?: 
No

* More info: 
1. This is a regression issue, it doesn't repro on .NET Core 3.1 & .NET 5.0
2. These controls reproduce this issue: Button, CheckBox, ComboBox, Label, MonthCalendar, NumericUpdown, ProgressBar, ListBox, ListView
3. These controls doesn't reproduce this issue: CheckListBox, DateTimePicker, LinkLabel, TextBox, RichTextBox, RadioButton, TreeView

**Minimal repro:**
[TestApp.zip](https://github.com/dotnet/winforms/files/5764188/TestApp.zip)

1. Create a winforms .NET core project with a Button control
2. Set button's AccessibleRole property as **PageTab**
3. Build and run the core project
4. Observe Button using the Accessibility Insight

**Actual behavior:**
AccessibilityInsights detected an error: An element of the given ControlType must support the SelectionItem pattern
![Core](https://user-images.githubusercontent.com/62929087/103524272-3f6d2a80-4eb8-11eb-879e-3c3b0da09f8f.png)

**Expected behavior:**
AccessibilityInsights should not detect this error.

**Comment by merriemcgaw** [comment]
@Amy-Li03 is there a customer scenario behind this issue? I'd mark it pri-3 unless we can find a good scenario. What was the behavior before this?

**Comment by Amy-Li03** [comment]
@merriemcgaw There is no customer scenario behind this issue, it was found by ourselves during accessibility app creation.

**Comment by merriemcgaw** [comment]
Given there is no customer issue here I will close this issue.
