### ISSUE TITLE
Performance issue of Core WinForms Designer

### ISSUE THREAD

**Issue by PavelAgurov** [dotnet/winforms#4434]
* .NET Core Version: 3.1

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

Performance of Core WinForms designer is VERY bad to compare with .NET WinForms.
Sometimes I should click on control and wait 10-30 sec to select this control and ability to edit it in Property Grid.
When I save changes in designer it takes much more time then it was in .NET WinForms.

**Expected behavior:**

**Minimal repro:**

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.
