### ISSUE TITLE
Default size of Button in design time

### ISSUE THREAD

**Issue by PavelAgurov** [dotnet/winforms#4435]
* .NET Core Version: 3.1

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
When I added new button on the form I have 8x8 button. In .NET WinForms it was much better - default size was useful.

**Expected behavior:**

**Minimal repro:**

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.

**Comment by PavelAgurov** [comment]
Reported https://developercommunity2.visualstudio.com/t/button-has-size-8x8-when-created/1303980
