### ISSUE TITLE
[Accessibility] Tree node has no keyboard tooltip

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4439]
- .NET Core Version: 5.0
- Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
- TreeNode has no keyboard tooltip when pressing the up/down arrow or Tab button to navigate to a TreeNode which got the keyboard focus

**Expected behavior:**
- TreeNode has a keyboard tooltip

**Minimal repro:**
1. Create .Net Core 5.0 app
2. Add a TreeView to the app
3. Add nodes to the TreeView
4. Set tooltips for TreeNodes
5. Allow showing tooltips for nodes
6. Run the app and try to get a node tooltip using a keyboard navigation

**Comment by Jenna-Zheng** [comment]
Verified this issue with .NET 6.0.0-preview.2.21124.3, it is fixed that TreeNode has a keyboard tooltip
![TestApp](https://user-images.githubusercontent.com/64949616/109626208-38daf680-7b7b-11eb-9744-33936d06b165.gif)
