### ISSUE TITLE
[NET 5.0] NumericUPDown Exception

### ISSUE THREAD

**Issue by LiorBanai** [dotnet/winforms#4441]
Hi,
I have switched from 3.1 to net 5 and have strange exception on winforms launch on newing NumericUpDowm:

```Unable to find an entry point named 'UiaRaiseNotificationEvent' in DLL 'UIAutomationCore.dll'.```

which is not clear what is the source.
The application still  runs ok and I can ignore this error.

![image](https://user-images.githubusercontent.com/36262995/103876599-820f4c80-50dc-11eb-9029-506c2bc7deb1.png)

**Comment by SergeySmirnov-Akvelon** [comment]
Hi @LiorBanai. Could you please share sample project to reproduce the issue?

**Comment by LiorBanai** [comment]
Hi @SergeySmirnov-Akvelon
It appears this issue is localized to single workstation and in other ws it workings with no issues so I'll close this since this is something on my end.
