### ISSUE TITLE
Create #if to diferentiate Winform and WPF

### ISSUE THREAD

**Issue by transis2** [dotnet/winforms#4445]
I'm converting some projects from .Net Framework to .Net 5 and don't know how to separate the code from winform and wpf.
Eg.:
Would be nice if we have:

#IF WINFORM Then
labelStatus.Text = ""
#Else
labelStatus.Content = ""
#End If

**Comment by RussKie** [comment]
You no longer build a Windows Forms or WPF apps in .NET - you build a Windows Desktop apps, which can leverage the Windows Forms SDK, or the WPF SDK, or both.

As @huoyaoyuan pointed you can define constants in your project file, and then #if..#else them:
```xml
  <PropertyGroup>
    <DefineConstants Condition="'$(UseWPF)'=='true'">$(DefineConstants);WPF</DefineConstants>
    <DefineConstants Condition="'$(UseWindowsForms)'=='true'">$(DefineConstants);WINFORM</DefineConstants>
  </PropertyGroup>
```

```cs
#if WINFORM
            MessageBox.Show("Using Windows Forms");
#else
            MessageBox.Show("Not using Windows Forms");
#endif
```
