### ISSUE TITLE
ToolStripItemCollection.AddRange(ToolStripItemCollection toolStripItems) causes ArgumentOutOfRangeException as it deletes from source collection

### ISSUE THREAD

**Issue by max-m-s** [dotnet/winforms#4454]
This method cannot be used as it will always cause an ArgumentOutOfRangeException since items are deleted from the source collection while they are copied into the new collection.

Take this code in Form_Load()
    ContextMenuStrip1.Items.AddRange(EditToolStripMenuItem.DropDownItems)

Before it is executed, ContextMenuStrip1 has 0 items and EditToolStripMenuItem has 16. While it is called and the exception is triggered, both have 8 but alternating. I.e. ContextMenuStrip1 now has indexes 0,2,4,6,8,10,12,14 from the original EditToolStripMenuItem. EditToolStripMenuItem is left with 1,3,5,7,9,11,13,15.

The exception occurs because it is expected there will be 16 items to move, but only 8 exist in the array now.

Expected behavior: Each reference is copied into the target menu. Not removed from source.

Watches before: [https://pasteboard.co/JJhkD66.png](url)
After (at exception): [https://pasteboard.co/JJhkV9w.png](url)
(Apologies for random image site. Most are blocked by our corporate firewall)

This was tested on VB .NET 4.6.

I already have a workaround.

**Comment by Zheng-Li01** [comment]
This is not a regression issue, which can reproduce .NET Framework and .NET Core projects with VB/C#, and can reproduce from .NET 3.5 to .NET 4.8, please see below details.
**Application:**[VBFraTesting6.zip](https://github.com/dotnet/winforms/files/5807568/VBFraTesting6.zip)
**Repro GIF:**
![ReproGIF](https://user-images.githubusercontent.com/38325459/104431675-20128380-55c3-11eb-824a-c9cd0def3614.gif)
[CallStack.txt](https://github.com/dotnet/winforms/files/5807573/CallStack.txt)
![Screenshot](https://user-images.githubusercontent.com/38325459/104431730-31f42680-55c3-11eb-884e-1ac06ff918e4.PNG)

**Comment by weltkante** [comment]
> Expected behavior: Each reference is copied into the target menu. Not removed from source.

This expected behavior is incorrect and does not reflect what happens if the items are added individually. These items can have only one owner and are removed from their origin when added to a differnt parent.

Making `AddRange` behave differently from repeated calls to `Add` would be wrong. Changing semantics of `Add` alltogether would also be a breaking change that requires everyone using it to adjust their code.

The only non-breaking option is to implement `AddRange` in a way that moves all items without throwing an exception (e.g. by first copying the list before adding the items, or by iterating backwards - different strategies are possible)

**Comment by max-m-s** [comment]
Yes I seem to agree now. As manually iterating with Add() is also removing them from the original Control's Collection. I thought it didn't at first. But it does seem a worthless method (overload) if it will always fail halfway through the loop.

Another solution was found online: I was able to move the items to the ContextMenu in design. Then at runtime, replace the Edit menu's dropdown:
    EditToolStripMenuItem.DropDown = ContextMenuStrip1
This allows both to share the menu without having to make copies (since Clone() isn't implemented either).

**Comment by willibrandon** [comment]
`AddRange` makes repeated calls to `Add` and as @weltkante suggested, I can confirm that if `AddRange` is implemented by first reversing the list and then iterating backwards, that the _ArgumentOutOfRangeException_ is avoided and the items get added in the expected order.

```
int currentCount = toolStripItems.Count;
toolStripItems.InnerList.Reverse();
for (int i = currentCount - 1; i >= 0; i--)
{
    Add(toolStripItems[i]);
}
```

**Comment by weltkante** [comment]
> Though we can avoid reversing the collection, and iterate it backwards instead.

The quoted code does both reversing and iterate backwards to keep the original order.

**Comment by willibrandon** [comment]
> 
> 
> > Though we can avoid reversing the collection, and iterate it backwards instead.
> 
> The quoted code does both reversing and iterate backwards to keep the original order.

That is correct, the intent of reversing the collection would be to preserve the original order.

**Comment by willibrandon** [comment]
Another strategy that can be used that preserves the original order, does not require reversing the collection, and avoids the _ArgumentOutOfRangeException_, is to decrement the index in the loop and reset the count.

```
int currentCount = toolStripItems.Count;
for (int i = 0; i < currentCount; i++)
{
    Add(toolStripItems[i--]);
    currentCount = toolStripItems.Count;
}
```

**Comment by Jessie-Zhang01** [comment]
Verified the issue with .Net SDK 6.0.100-preview.3.21169.6, this issue is fixed. 
![step1](https://user-images.githubusercontent.com/45864649/111964169-46a6ea80-8b2f-11eb-9b64-c032a1ce3674.gif)
