### ISSUE TITLE
The code generated by the DataGridView control has extra code for the RowTemplate.Height property

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#4461]
* .NET Core Version: 
3.1+

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The generated code for dataGirdView1 has extra code for the RowTemplate.Height property. For the newly created control *at 100% scaling*, designer should generate the same value as is defined by the DefaultValueAttribute

![image](https://user-images.githubusercontent.com/15823268/104521807-77f4be80-55b2-11eb-9f38-b7e32eff005d.png)

**Expected behavior:**
RowTemplate.Height line should not be generated
 
![image](https://user-images.githubusercontent.com/15823268/104521910-b5f1e280-55b2-11eb-804e-5a05b8b8a195.png)

**Minimal repro:**
1. Create a Winforms .Net Core application.
2. Add a DataGridView to from designer.
3. Double click to open Form1.Designer.cs file in Solution Explorer.
4. Observe the generated code of the dataGridView1.

Note from Dustin: DataGridViewRow.Height has a [DefaultValue(22)] attribute, so the code-gen above is expected if the value is 25.

**Comment by Tanya-Solyanik** [comment]
DefaultValueAttribute should be adjusted to match the new default font

**Comment by RussKie** [comment]
Similar to https://github.com/dotnet/winforms/issues/4463#issuecomment-768831519.

Closing due to age. We can reopen it if/when we receive customer feedback.

**Comment by kirsan31** [comment]
@RussKie 

> Closing due to age. We can reopen it if/when we receive customer feedback.

You [have it](https://developercommunity.visualstudio.com/t/WinForms-DataGridView-styles-designer/1143911) for a long time already.

I was hoping that when you deal with this issue, I will be able to raise [that](https://developercommunity.visualstudio.com/t/WinForms-DataGridView-styles-designer/1143911) too. Instead, you closed this one :)

Current issue is more fatal then my previous. To break Font scaling in my reported issue you was needed to add some styles. But with this - when simple adding new DataGridView (not always - see below) to the form - you completely break DPI and Font scaling 😁 And even if you fix it manually, you have to do it again and again after every use of the designer...

Details:
1. `this.dataGridView1.RowTemplate.Height = 25;` line not always adding to `Form1.Designer.cs`. You need to open properties of `dataGridView1` for this.
2. There is a complete out of sync between the real values and what the designer shows.

https://user-images.githubusercontent.com/17767561/154912798-8bc356b9-c28e-4168-bbf7-98c30ca056ba.mp4

3. Broken DPI scale:
<img width="395" alt="Snipaste_2022-02-21_10-40-55" src="https://user-images.githubusercontent.com/17767561/154912856-9a0ef979-42c3-42b4-8e23-673d2dcde797.png">

**Comment by RussKie** [comment]
Thank you for linking the bug.

**Comment by RussKie** [comment]
@merriemcgaw can you please help prioritising this?

**Comment by dreddy-work** [comment]
@RussKie / @merriemcgaw this needs broader fix for every Control/Property impacted by the default Font change. So far i see two bugs in this context but there could be more.

**Comment by merriemcgaw** [comment]
We'll try to get to this in .NET 7, based on the feedback. We decided to do a deep dive into the default values and figure out what the best path foreword is.

**Comment by John-Qiao** [comment]
I duplicated the feedback ticket: https://developercommunity.visualstudio.com/t/Setting-DataGridViewRowHeight--22-in-P/10227470 with this issue.

**Comment by merriemcgaw** [comment]
Thanks @John-Qiao 
@dmitrii-drobotov  - is this something that can go on your team's backlog?

**Comment by dkazennov** [comment]
@Tanya-Solyanik 
Unlike LixtBox DataGridViewRow has Height property  is set to be equal Thickness, and Thickness is set to be equal Control.DefaultFont.Height + 9. Should we probably separate Height from Thickness?

**Comment by kirsan31** [comment]
@dkazennov thank you very match for doing this!

I want ask the team about related (but designer) [issue](https://developercommunity.visualstudio.com/t/WinForms-DataGridView-styles-designer/1143911) - any chance this will be fixed?
It's really very tiring to delete extra font instances every time after changing the form in the designer, and if you forget about it, font scaling breaks :(

**Comment by paul1956** [comment]
I open 2 separate issue through Feedback with Extra Styles being generated for DataGridView and the format of the file alternates with every change (spaces are added and deleted) in comments and New Lines are deleted if initialized string is last before comment. Is the correct format for a comment the first or second, it seems to be inconsistent.
```
    '
    'Comment
   '
```
or
```
     '
    ' Comment
    '
```
 Are there any test that compare results after each edit to look for side effects?

**Comment by Tanya-Solyanik** [comment]
>I want ask the team about related (but designer) [issue](https://developercommunity.visualstudio.com/t/WinForms-DataGridView-styles-designer/1143911)

The images are gone from the vs feedback website. @kirsan31 - could you please explain repro steps? Or even better - open individual issues in this repo.

@merriemcgaw - FYI.

**Comment by kirsan31** [comment]
> The images are gone from the vs feedback website. @kirsan31 - could you please explain repro steps? 

Yea they are gone :( But we have gif form one of the [responses](https://developercommunity.visualstudio.com/t/WinForms-DataGridView-styles-designer/1143911#T-N1424479):
https://user-images.githubusercontent.com/4403806/118398742-578e5b00-b69d-11eb-9181-35f1045fb1f3.gif
that explain one part of the issue.

> Or even better - open individual issues in this repo.

Wil do...

**Comment by dmitrii-drobotov** [comment]
We have those images in the linked designer issue (https://github.com/microsoft/winforms-designer/issues/2225), I will duplicate it here as well: 
[pic1.png]
![pic1](https://user-images.githubusercontent.com/62929087/89873781-8a2a9500-dbed-11ea-8bb5-0ee5afdaeff6.png)
[pic2.png]
![pic2](https://user-images.githubusercontent.com/62929087/89873786-8d258580-dbed-11ea-93de-281dacbd37e1.png)
[gif1.gif]
![gif1](https://user-images.githubusercontent.com/62929087/89873800-8f87df80-dbed-11ea-8c23-ad0a368a8960.gif)
[gif2.gif]
![gif2](https://user-images.githubusercontent.com/62929087/89873803-91ea3980-dbed-11ea-89c6-e64998ec155e.gif)

@kirsan31 - can you confirm these are the same images from the feedback post?

**Comment by kirsan31** [comment]
@dmitrii-drobotov 

> @kirsan31 - can you confirm these are the same images from the feedback post?

Yes, they are 👍
Do I still need to create a new issue with them + description from original post?

**Comment by dkazennov** [comment]
@kirsan31 it would be great to have a new issue. Thanks!

**Comment by Nora-Zhou01** [comment]
Verified this on .NET latest build: 8.0.100-preview.3.23152.5, issue was fixed, RowTemplate.Height line cannot be generated and DataGridViewRow.Height value is 25. The screenshot as same as above.
![data](https://user-images.githubusercontent.com/104609169/222621656-1269b740-19c8-4afa-9023-9518863a92dc.png)

![p](https://user-images.githubusercontent.com/104609169/222621660-ff05b5d0-d7e9-44d1-b5aa-31d74e23a469.png)
