### ISSUE TITLE
Some default values for control Heights are out of sync with the new default font

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#4462]
* .NET Core Version: 
3.1+

**Problem description:**

We need to enumerate all DefaultValueAttributes to investigate if there are controls other than ListBox and DataGridView whose default sizes are affected by the default font change.

Related issues:
https://github.com/dotnet/winforms/issues/4461
https://github.com/dotnet/winforms/issues/4463

**Comment by RussKie** [comment]
Similar to https://github.com/dotnet/winforms/issues/4463#issuecomment-768831519.

Closing due to age. We can reopen it if/when we receive customer feedback.
