### ISSUE TITLE
.NET 5.0.2 release links are broken

### ISSUE THREAD

**Issue by DrusTheAxe** [dotnet/winforms#4471]
The release page's doc links are broken

Goto https://github.com/dotnet/winforms/releases/tag/v5.0.2 and click on the `Release Notes` and `Install Instructions` links

* https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.2.md
* https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.2-install-instructions.md

Both result in 404 “This is not the web page you are looking for” 

However the [Core](https://github.com/dotnet/core/releases/tag/v5.0.2) link works as expect. I didn't test other links on the page.

Please fix

P.S. Same broken behavior for https://github.com/dotnet/winforms/releases/tag/v5.0.1. I didn't check other versions.

**Comment by RussKie** [comment]
Thank you for reporting. The issue should be resolved as per https://github.com/dotnet/roslyn/issues/50502#issuecomment-761044009.
