### ISSUE TITLE
dpi aware PropertyGrid with expandable items draws tree caret on top of item name

### ISSUE THREAD

**Issue by ScottFerg56** [dotnet/winforms#4475]
* .NET Core Version: 5.0.102

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
A dpi-aware .Net5 PropertyGrid control showing a nested object (with **ExpandableObjectConverter** properties) draws the tree expand/collapse caret on top of the item name. The painting of the caret encroaches more and more over the item name as each level of nesting is expanded.
![Net5 aware](https://user-images.githubusercontent.com/11354336/104858996-cf0ed200-58d7-11eb-9ff2-799362de29f8.png)

**Expected behavior:**
A non-dpi-aware .Net5 PropertyGrid draws the caret properly in its own distinct space. The behavior is correct for a .Net 4.7 grid, regardless of dpi-awareness.
![Net5 non-aware](https://user-images.githubusercontent.com/11354336/104859035-db932a80-58d7-11eb-8f66-ca15839c1426.png)

**Minimal repro:**
The attached ZIP contains quite a simple example with a default PropertyGrid showing a class instance with a single ExpandableObjectConverter property reference to the same class as an example to create nesting. PNG screenshots are included to show the results for .Net 5.0 and 4.7 both aware and not aware. DPI awareness can be switched off/on in Program.cs.
[PropGridBug.zip](https://github.com/dotnet/winforms/files/5826998/PropGridBug.zip)

**Comment by Amy-Li03** [comment]
Verified the issue with .NET 6.0 6.0.100-preview.6.21322.9, it was fixed. A dpi-aware .Net6.0 PropertyGrid can draw the caret properly in its own distinct space.

![image](https://user-images.githubusercontent.com/62929087/123067887-3e787880-d3c6-11eb-8037-df49c77c4692.png)
