### ISSUE TITLE
Consume and expose UI improvements for OS

### ISSUE THREAD

**Issue by OliaG** [dotnet/winforms#4484]
Support Windows 10 UI overhaul

**Comment by AraHaan** [comment]
I already proposed to support theming of the scrollbar where everyone can provide their own renderer that could do what Windows 10 does on the UI overhaul, currently we can easily change the colors on everything else except the scrollbars currently. I also made code on one of my other projects (still needs some debugging as to why it works properly on .NET Framework and on .NET core looks off on some of the custom drawing of the actual form Non-client areas). When that is done I will propose an ThemeableForm that basically just derives from form, sets it to borderless, then then would paint the stuff. At that time then I will implement an NonClientAreaRenderer on forms where the used can basically change how that would be rendered however they like as well too.

**Comment by merriemcgaw** [comment]
Covered by a .NET 7 targeted Epic. #6270
