### ISSUE TITLE
Need some document guide for MVC winforms

### ISSUE THREAD

**Issue by netroby** [dotnet/winforms#4485]
Hello, i am looking for how to wrote a MVC app with winforms  on .net 5

My app need a login winform , then login success , open main window.

If failed, then go to a reset password winform. and also need a register winform.

Any document can help me finish this works?

The document on microsoft i had read , but can not find much more helpful detail.

**Comment by RussKie** [comment]
If you search online for MVC you will find a number of resources that would be helpful with your task.
If you have specific questions about Windows Forms runtime features please let us know.
