### ISSUE TITLE
VS 16.9 Preview 3: WinForms Designer not working when project contains multiple Resource Files

### ISSUE THREAD

**Issue by deng0** [dotnet/winforms#4486]
In VS 16.9 Preview 3 when trying to open the Windows Forms Designer for a Form I get the following error Message:
![image](https://user-images.githubusercontent.com/4224837/105348155-32ef0e80-5be8-11eb-8c75-ac7300f5fa9d.png)
(Unable to find method InitializeAsync/1 ...)

It seems this happens when the project contains multiple resource files. If the project contains only a single resource file this problem does not occur.

I've attached a simple project to reproduce this error:
[WinForms_Designer_NotWorking.zip](https://github.com/dotnet/winforms/files/5849096/WinForms_Designer_NotWorking.zip)

**Comment by Olina-Zhang** [comment]
Filed this issue in Winforms designer repo: https://github.com/dotnet/winforms-designer/issues/2779

**Comment by dreddy-work** [comment]
Its addressed in VS preview 4 ( upcoming release).
