### ISSUE TITLE
ElementHost breaks designer loading

### ISSUE THREAD

**Issue by IngmarBitter** [dotnet/winforms#4489]
Windows 10 Pro, net5.0-windows, 5.0.200-preview.20601.7, Visual Studio 2019 v16.8.4
Used to work in .net4.7.2

**Problem description:**
In the `Solution Explorer`, double click on `ElementHost.cs` opens a new blank white view that cannot be interacted with.

**Expected behavior:**
The visual designer view should open, allowing me to add more controls. 
Note that everything works just fine if I open the same solution with Visual Studio 2019 Preview v16.9.0

**Minimal repro:**
See attached solution folder. No external dependencies. Tiny project. In `ElementHost.Designer.cs` is clearly commented which line causes the problem. Look for
```
      // -!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
      // the next line causes the visual designer view to fail to load. Reproducible with VS 2019, but not with VS 2019 preview
      this.ElementHost = new System.Windows.Forms.Integration.ElementHost();
      // -!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-!-
```
[ElementHost.DesignerFail.VS2019.zip](https://github.com/dotnet/winforms/files/5851865/ElementHost.DesignerFail.VS2019.zip)

**Comment by RussKie** [comment]
@Olina-Zhang could you test it with the latest public preview? Thank you

**Comment by Olina-Zhang** [comment]
@RussKie  Verified in the latest public preview build, this issue cannot repro, and can repro in VS 2019 16.8.4.
the screenshot of the latest preview build, can add controls from toolbox window:
![image](https://user-images.githubusercontent.com/26474449/105435977-558d3000-5c99-11eb-9e13-57bf9995141e.png)
the screenshot of VS 2019 16.8.4, winforms designer is blank
![image](https://user-images.githubusercontent.com/26474449/105436079-82414780-5c99-11eb-8954-aac1c9039352.png)

**Comment by RussKie** [comment]
Thank you @Olina-Zhang 

@IngmarBitter the fix will be available soon.

**Comment by weltkante** [comment]
> the screenshot of the latest preview build, can add controls from toolbox window:

That looks wrong, the ElementHost is not a component, it should be placed on the design surface?

**Comment by IngmarBitter** [comment]
Placing the ElementHost was not the issue, just calling the constructor was.
In addition in the app that I cut down to this mini example it was placed on the design surface as well and it seems to work fine like that.
