### ISSUE TITLE
Default branch will be renamed to main

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#4493]
On Sunday, 31 January 2021 we're going to rename the default branch in this repository to `main`. For more details, see [our earlier announcement](https://github.com/dotnet/announcements/issues/172). Expect the process to begin after 5PM Pacific.

**Comment by RussKie** [comment]
The default branch has been renamed!
`master` is now named `main`

If you have a local clone, you can update it by running:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by KlausLoeffelmann** [comment]
Thanks, man!
