### ISSUE TITLE
Designer becomes busted if you remove WinForms references from the project

### ISSUE THREAD

**Issue by davkean** [dotnet/winforms#4508]
1. Create a new Windows Forms (.NET 5) project
2. Double-click the project file
3. Delete `<UseWindowsForms>true</UseWindowsForms>`
4. Save

Expected: The designer to show a friendly error that it can't render similar to .NET Framework
Actual:
```
---------------------------
Microsoft Visual Studio
---------------------------
Timed out while connecting to named pipe.
---------------------------
OK   
---------------------------
```

And the "designer" itself no longer renders correctly and just shows the last source file behind it:

![image](https://user-images.githubusercontent.com/1103906/106230031-c0fb7280-6242-11eb-852c-dd7f6c5d5742.png)

If you readd back `<UseWindowsForms>true</UseWindowsForms>` and save you get:

```
---------------------------
Microsoft Visual Studio
---------------------------
Could not retrieve IDesignToolsClient for project WinFormsApp4.
---------------------------
OK   
---------------------------
```

**Comment by Zheng-Li01** [comment]
The issue can reproduce from .NET SDK 3.1 to 6.0, the icon of "Form1.cs" node disappeared after uncommented 
`<UseWindowsForms>true</UseWindowsForms>`; and the  icon of "Form1.cs" node appear after re-add back `<UseWindowsForms>true</UseWindowsForms>`, then double click it, the Form1.cs[Design] load successfully, please see below reproduce GIF.
 ![GH4508](https://user-images.githubusercontent.com/38325459/106238855-927a9900-623c-11eb-8c9a-88310d8b83bb.gif)

**Comment by merriemcgaw** [comment]
@Zheng-Li01  can you copy this issue over to the internal designer repo?

**Comment by Zheng-Li01** [comment]
@merriemcgaw, have filed [designer issue ](https://github.com/dotnet/winforms-designer/issues/2853)to track it.
