### ISSUE TITLE
Add Rosyln analyzers to generate ship.api.txt as part of msbuild

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#451]
related to #175 
see also PR #237

This is to ensure any additional API gets captured for the purposes of API review; this file is not used by code.

**Comment by zsd4yr** [comment]
@sharwell Do you have any suggestions here? I feel like you might know something ;)

**Comment by sharwell** [comment]
We generally use https://www.nuget.org/packages/DotNetAnalyzers.PublicApiAnalyzer/.

**Comment by zsd4yr** [comment]
> We're migrating ownership of that package to dotnet/roslyn-analyzers so we can expect it to be available long term.

Is there any public timeline for that? If not, feel free to PM me

**Comment by sharwell** [comment]
@zsd4yr The transition will be seamless. That NuGet package is a direct fork of the original code and the format and behavior are essentially identical. You won't have any disruption if you start using it now (and probably won't even notice that the publishing changed when it does).

**Comment by RussKie** [comment]
Implemented
