### ISSUE TITLE
Question: Suggest how to port winforms

### ISSUE THREAD

**Issue by ericoporto** [dotnet/winforms#4523]
I recently found a libgdiplus here: https://github.com/CoreCompat/libgdiplus-packaging

I was curious, I understand there's no interest in supporting MacOS and Linux, but has anyone ever thought about what would be the roadmap in a what if scenario?

Such roadmap would be useful if some group of people decides to pickup on their own, taking advantage of the now open source codebase.

Edit: label is wrong.

**Comment by weltkante** [comment]
Not speaking for the team, but here's my understanding:

The drawing library is not the point of WinForms (in fact [much of System.Drawing](https://github.com/dotnet/runtime/tree/master/src/libraries/System.Drawing.Common/src/System/Drawing) isn't even inside WinForms). The main point of WinForms is wrapping the native controls Windows provides, as such there is a tight dependency to the underlying platform to actually provide the controls to be wrapped.

Wrapping native MacOS or Linux controls would be an entirely separate library and not in the scope of the WinForms project.

Porting WinForms is not possible without porting or reimplementing the underlying native controls, which are not open source.

The current cross platform story is [MAUI](https://github.com/dotnet/maui)

**Comment by ericoporto** [comment]
Thanks for the information, the information on System.Drawing was very useful.

I checked more of the source, I think I better understand what you mean by wrapping the native controls. 

This can be closed.

**Comment by RussKie** [comment]
FWIW, there's a [Mono](https://www.mono-project.com/docs/about-mono/releases/) implementation of Windows Forms: https://github.com/mono/mono/tree/master/mcs/class/System.Windows.Forms, and it is occasionally being worked on.
It is also possible to run Windows app under Wine, though I can't comment how well they work.
