### ISSUE TITLE
[DPI] Anchored layout issue when form exceeds desktop dimensions

### ISSUE THREAD

**Issue by sampathnarine** [dotnet/winforms#4527]
* .NET Core Version: 
3.0 Preview2

* Have you experienced this same bug with .NET Framework?: 
No, 

**Problem description:**

I have created the project with DataGridView. I have enabled the dpi settings to my project. While launching my NetCore application in 150dpi, the DataGridView is not rendered correctly in the form. Please refer the below image

<img width="683" alt="NetCore_150Dpi" src="https://user-images.githubusercontent.com/63052528/106876685-fc43e880-66fd-11eb-9816-5b0eb1949f1e.png">

Mean while i have launched 4.6 NetFramework project with same settings, i didn't faced the issue like NetCore. please refer below image.

<img width="683" alt="NetFrameWork150Dpi" src="https://user-images.githubusercontent.com/63052528/106877039-5b096200-66fe-11eb-9497-cf0da259f307.png">

Note : Issue in the NetCore occurs only when setting anchor property to the DataGridView.

**Expected behavior:**

This issue not occurs in the 100dpi. Please refer the below image. This should be a expected behavior i believe.

![NetCore_100Dpi](https://user-images.githubusercontent.com/63052528/106877898-52fdf200-66ff-11eb-9bfb-195881d9205c.png)

**Minimal repro:**

Run the NetCore sample below in 150 dpi resolution. 
Above mentioned issue occurs.

[Samples.zip](https://github.com/dotnet/winforms/files/5929896/Samples.zip)

**Comment by RussKie** [comment]
Thank you for the repro. 

Unfortunately it is not clear which project I need to run out of present in the repro, and there are external dependencies that I don't have. 
I have run Grouping_NET50.csproj removing all Syncfusion references, and I was unable to repro the issue:

* 100%
![image](https://user-images.githubusercontent.com/4403806/106963790-3c09df00-6795-11eb-8655-f5157e687391.png)

* 150%
![image](https://user-images.githubusercontent.com/4403806/106963755-2bf1ff80-6795-11eb-8b8e-184a1c979041.png)

**Comment by sampathnarine** [comment]
Thanks for update,

This issue occurs for any netcore projects whether it is Net50 or NetCore 3.1 project. Sorry i have removed the dlls and attached the sample again. Can i get your system settings and system resolution. Please find my system model and I have launched sample in 1366 X 768 resolution

![image](https://user-images.githubusercontent.com/63052528/106988278-652a6f80-6795-11eb-8756-c86e31c07932.png)

OS version : Windows 10.0.19042

**Comment by RussKie** [comment]
I have several 4K monitors. I have tried the updated sample  in different scaling factors from 100% all the way up to 300%, and various [`HighDpiMode`s](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.application.sethighdpimode?view=net-5.0), and I can't repro the issue.

@Olina-Zhang can you try and see whether you can replicate the issue? Thanks

**Comment by Olina-Zhang** [comment]
@RussKie I can repro this issue using above .Net 5.0 app in Samples with added HighDpiMode. Here is the screenshot:
100%:
![image](https://user-images.githubusercontent.com/26474449/107175679-69aa8e80-6a08-11eb-9333-6c6527d17a8a.png)
300%:
![image](https://user-images.githubusercontent.com/26474449/107175767-a1193b00-6a08-11eb-9dcf-275f55f745d1.png)
But I found on 300% environment, DataGridView on core designer has problem, part of dataGridView is out of form designer:
![image](https://user-images.githubusercontent.com/26474449/107175928-01a87800-6a09-11eb-97ce-360d9d9d49c7.png)

**Comment by RussKie** [comment]
I was able to repro it on a laptop. From my observations the issue is only reproducible if the height of the form is greater than the available realestate of the desktop.

There are few workarounds you can employ:
1. Reduce the dimensions of the form in the designer to fit on the screen
2. Adjust the size of the form at runtime to not exceed the available space
3. Replace anchoring with docking

**Comment by dreddy-work** [comment]
@RussKie , lets chat offline, if there is anything that needs to be done for HDPI here.

**Comment by Olina-Zhang** [comment]
@dreddy-work cannot repro this issue in the latest .Net 7.0 SDK build.

**Comment by dreddy-work** [comment]
@Olina-Zhang , please add screenshots from verified build using same customer application for future references on the bugs that do not reproduce.

**Comment by Olina-Zhang** [comment]
Adding the testing screenshots for this issue, cannot repro in the latest .Net 7.0 SDK build:

150%DPI:
![image](https://user-images.githubusercontent.com/26474449/143373051-f38561c0-2d26-4123-9fa2-f0b81b8d5d17.png)

300%DPI:
![image](https://user-images.githubusercontent.com/26474449/143373161-5a7ebb59-ceb8-4c99-852b-4d298caf3d60.png)

**Comment by RussKie** [comment]
Thank you
