### ISSUE TITLE
Versioning of libraries and designer

### ISSUE THREAD

**Issue by filipnavara** [dotnet/winforms#4528]
* .NET Core Version: 5.0.x

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

We are running Visual Studio 16.9.0 Preview 3.0 which ships with some .NET 5.0.2 bits. These bits are consumed by the WinForms designer. The designer then serializes these types into .resx along with the version of the library, eg.:
```
  <assembly alias="System.Windows.Forms.Primitives" name="System.Windows.Forms.Primitives, Version=5.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  <data name="label_Title.Margin" type="System.Windows.Forms.Padding, System.Windows.Forms.Primitives">
    <value>0, 3, 3, 3</value>
  </data>
```

The application itself is however compiled with a fixed version of .NET framework specified in global.json file:
```
{
  "sdk": {
    "version": "5.0.100",
    "allowPrerelease": true,
    "rollForward": "latestFeature"
  }
}
```

This results in issue where the serialized types cannot be loaded at runtime and crash the app.

**Expected behavior:**

Assembly versions (as opposed to file versions!) should not change between service releases, or designer should target the same service release the application is compiled with.

**Comment by weltkante** [comment]
> Assembly versions (as opposed to file versions!) should not change between service releases

I don't believe this can lead to anything good, it is faking identity when there is no identity. It also prevents a program saying that it depends on specific bugfixed version of an assembly.

IMHO this needs to be fixed in the designer and possibly the resx loader
* The designer should target the global.json version, not the currently installed service packs, otherwise you cannot distribute your 3rd party component to someone who doesn't have the service pack installed yet.
* The resx loader needs to support automatic roll forward if there is no exact match in the referenced assembly. This worked on Desktop Framework, I don't know if it currently works on .NET Core due to the changed rules how assemblies are located. This is very important when you compose an application of multiple third party components which may have been compiled against different target versions in their individual global.json/resx files.

**Comment by filipnavara** [comment]
> The resx loader needs to support automatic roll forward if there is no exact match in the referenced assembly.

It relies on the algorithm for assembly loading in .NET which automatically accepts newer assembly versions.

**Comment by filipnavara** [comment]
> I don't believe this can lead to anything good, it is faking identity when there is no identity. It also prevents a program saying that it depends on specific bugfixed version of an assembly.

Well, as a matter of fact that's how it worked for years on .NET Framework. All the assemblies had the identity of 2.0.0.0 or 4.0.0.0. There are multiple reasons why it might be a good idea to keep doing that.

For starters, these assemblies are not consumed by end users as a versioned NuGet. They are distributed with the framework in the same installers (even though they technically don't have to be). Some scenarios may have different requirements, like framework-dependent deployment and self-contained deployment. Should framework dependent deployment simply fail if I resave my form in new Visual Studio version and then deploy it to clients who are not yet on the latest runtime service release?

Likewise I would like to be able to change my global.json without having to check/rebuild all the .resx files. This may even involve a change that downgrades the version number. Consider the situation where I develop an application BabyShark and I store the source code in Git. At some point I branch out version 1.0 and make a GIT branch. The branch would stay on the fixed `global.json` at the time of the branching. Now I focus on future development and bump `global.json` to use .NET 5.0.9000 (hypothetical service release of .NET 5). Then I discover that my SharkForm has incorrect layout on high DPI system. I fix it on the `main` branch but I can no longer backport it to the release branch because the .resx files are serialized with version 5.0.9000. This would not be so bad if there was single service branch for .NET and I could freely bump global.json on the branch but that historically haven't been the case.

**Comment by weltkante** [comment]
> Well, as a matter of fact that's how it worked for years on .NET Framework. All the assemblies had the identity of 2.0.0.0 or 4.0.0.0. There are multiple reasons why it might be a good idea to keep doing that.

You are right, as far as WinForms and resx is concerned, I had a different scenario in my head, so I retract my statement above.

> It relies on the algorithm for assembly loading in .NET which automatically accepts newer assembly versions.

Not entirely, .NET Core has a `.deps.json` version mapping generated at build time and generally differs how it treats lookup of versions not in that mapping. We had some issues with `System.Drawing` specifying a different version in the `.deps.json` and it not automatically loading the newer version.

So I still want to add the additional scenario to consider that consumed 3rd party packages may be referring to different versions in their resx files, this scenario needs to be supported. Since I doubt resx files are consulted when constructing `.deps.json` mappings the designer generating them needs to be compatible with whatever Roslyn considers "the right target version" to construct dependencies.

**Comment by filipnavara** [comment]
I didn't want to go into extra details about the .deps.json files. There are actually two separate components involved in that - the host (corehost, corerun, etc.) and the runtime. The runtime itself doesn't look into these JSON files, it gets the information from the host (corehost for typical apps) in form of "trusted platform assembly list". This affect how the .dll files are looked up but it doesn't necessarily affect how their versions are compared. As far as the versions are concerned the algorithm is stupidly simple - if you reference version X then anything with X or higher is fine.

**Comment by RussKie** [comment]
Thank you for raising this. We have a similar issue tracked in the designer repo: https://github.com/dotnet/winforms-designer/issues/1837

/cc: @JeremyKuhne @KlausLoeffelmann @dreddy-work

**Comment by KlausLoeffelmann** [comment]
Yes, we are aware of that issue.

In a nutshell: We are actually considering writing back even Framework types where possible, so restricting the actually used types to the usual types would allow for multi targeting scenarios.

**Comment by RussKie** [comment]
We may need to update https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs to match the designer implementation (once it is corrected)

**Comment by filipnavara** [comment]
I think the other issue in the [private] designer repository could have been started by my request but I cannot check it. :-) It's not necessarily the same problem although the solution could be the same in the end. If you decide to merge it you may want to note that the designer also incorrectly serializes `null` as `ResXNullRef` from the designer assembly instead of the implementation assembly which renders the resulting app unusable.

**Comment by KlausLoeffelmann** [comment]
Thanks for pointing that out!
Also @JeremyKuhne and @dreddy-work for not missing this.

**Comment by dreddy-work** [comment]
> I think the other issue in the [private] designer repository could have been started by my request but I cannot check it. :-) It's not necessarily the same problem although the solution could be the same in the end. If you decide to merge it you may want to note that the designer also incorrectly serializes `null` as `ResXNullRef` from the designer assembly instead of the implementation assembly which renders the resulting app unusable.

Can you give an example to this and open a new issue with more details?  I am closing this as we fixed it in latest VS.

**Comment by filipnavara** [comment]
> Can you give an example to this and open a new issue with more details?

@dreddy-work I'll file a separate report for that through VS feedback. Basically any `null` that is assigned into control property in the designer ends up as `ResXNullRef` type in the .resx file. Since the designer ships its own copy of ResX classes it happens to use its own copy of `ResXNullRef` that resides in the designer assembly. It puts the wrong assembly name into the .resx file and fails at runtime.

**Comment by dreddy-work** [comment]
> > Can you give an example to this and open a new issue with more details?
> 
> @dreddy-work I'll file a separate report for that through VS feedback. Basically any `null` that is assigned into control property in the designer ends up as `ResXNullRef` type in the .resx file. Since the designer ships its own copy of ResX classes it happens to use its own copy of `ResXNullRef` that resides in the designer assembly. It puts the wrong assembly name into the .resx file and fails at runtime.

We stopped writing designer specific type info into Resx file during serialization. We still yet to do work for the resources added directly from the Resource editor in VisualStudio but not by Winforms designer.  If you still see this issue with latest VS (VS 2019 16.10 preview3) and If you have already opened a feedback ticket, can you please share link here ?
