### ISSUE TITLE
Allow custom controls in StatusStrip

### ISSUE THREAD

**Issue by docfresh** [dotnet/winforms#4531]
StatusStrip control only allows for 4 built-in child controls: StatusLabel, ProgressBar, DropDownButtom, and SplitButton.

It would be cool if you could have your own panel in there, picturebox, custom-drawn tool, or usercontrol.  Like this

![image](https://user-images.githubusercontent.com/8064022/106989892-c53ef880-6738-11eb-92d5-f4f9d39f7116.png)

It seems the old StatusBar [supported this](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-add-panels-to-a-statusbar-control?view=netframeworkdesktop-4.8), but its not useable in .NET 5.

Is this something that can be added?

**Comment by RussKie** [comment]
[`StatusStrip`](https://docs.microsoft.com/dotnet/api/system.windows.forms.statusstrip) is derived from [`ToolStrip`](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstrip), which exposes [`ToolStripItemCollection`](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstripitemcollection). This collection contains [`ToolStripItem`s](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem) (which is an abstract type), which can be [added to the collection](https://docs.microsoft.com/dotnet/api/system.windows.forms.toolstripitemcollection.add#System_Windows_Forms_ToolStripItemCollection_Add_System_Windows_Forms_ToolStripItem_).

Is there something that prevents you from creating a custom toolstripitem derived from [`ToolStripItem`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem)?
