### ISSUE TITLE
Synchronous Control.Invoke overwrites call stack by exception thrown by the UI Thread

### ISSUE THREAD

**Issue by davkean** [dotnet/winforms#4536]
* .NET Core Version: 
All versions

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**

[Control.Invoke rethrows](https://github.com/dotnet/winforms/blob/127afbcc039b7462ca46411504d5a91c5dc1d167/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L6829) any exception thrown from the original method, throwing away the original stack from the UI thread and causing the exception to appear as if began at Control.MarshaledInvoke:

```
System.Windows.Forms.ni!System.Windows.Forms.Control.MarshaledInvoke in f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Control.csControl.cs:line 7783
at System.Windows.Forms.ni!System.Windows.Forms.Control.Invoke in f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Control.csControl.cs:line 7373
at SomeCustomMethodThatControlInvokes
at mscorlib.ni!System.Threading.ThreadHelper.ThreadStart_Context in f:\dd\ndp\clr\src\BCL\system\threading\thread.csthread.cs:line 74
at mscorlib.ni!System.Threading.ExecutionContext.RunInternal in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.csexecutioncontext.cs:line 980
at mscorlib.ni!System.Threading.ExecutionContext.Run in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.csexecutioncontext.cs:line 928
at mscorlib.ni!System.Threading.ExecutionContext.Run in f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.csexecutioncontext.cs:line 917
at mscorlib.ni!System.Threading.ThreadHelper.ThreadStart in f:\dd\ndp\clr\src\BCL\system\threading\thread.csthread.cs:line 111
```
This makes it very difficult to see the original problem in crash dumps, and has made triaging Watsons in Visual Studio much harder.

Please use [ExceptionDispatchInfo.Throw(ex)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.exceptiondispatchinfo.throw?view=net-5.0#System_Runtime_ExceptionServices_ExceptionDispatchInfo_Throw_System_Exception_) so that original call stack is maintained.

**Comment by RussKie** [comment]
Thank you, getting it fixed in .NET 6.0. 

If you think we ought to service this could you please elaborate on what/who is affected, what how much pain this is causing, and how far back you'd want this serviced (i.e. .NET 5.0, .NET Core 3.1, or .NET Framework 4.8). 
Thanks

**Comment by davkean** [comment]
We don't need servicing for this. .NET Core 6.0 is fine.
