### ISSUE TITLE
Resizing the ComboBox with "Simple" dropDownStyle forcibly creates a handle

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4541]
**.NET Core Version:**
- 5.0.200-preview.20614.14

**Have you experienced this same bug with .NET Framework?:**
- Yes

**Minimal repro:**
1. Create application with ComboBox.
2. Set "Simple" drop down style.
3. Set custom size.

For example:
```
ComboBox comboBox = new ComboBox();
comboBox.DropDownStyle = ComboBoxStyle.DropDown;
comboBox.Size = new System.Drawing.Size(50, 50);
bool isHandleCreated = comboBox.IsHandleCreated;
```

**Expected behavior:**
Handle is not created

**Actual behavior**
Handle is created.

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .NET SDK 6.0.100-preview3.21153.9 build, the issue has been fixed as below screenshot.
![image](https://user-images.githubusercontent.com/38325459/109904700-959ff380-7cd8-11eb-848b-63843d46ef81.png)
