### ISSUE TITLE
Issue in the form size while setting Dpi 

### ISSUE THREAD

**Issue by sampathnarine** [dotnet/winforms#4543]
* .NET Core Version: 

   3.1 Preview 1

* Have you experienced this same bug with .NET Framework?: 

   Yes

**Problem description:**

I have created the winforms project with DataGridView. I have enabled the dpi settings to the application. I have found some issues while running the application. 

### Issue 1:

After setting the AutoScaleDimensions as below, the NetCore form size greater than the framework. Please refer the below Image

 Code Snippet

`this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);`

Images

NetFramework :

![NetFrameWorkImage](https://user-images.githubusercontent.com/63052528/107309855-3f60db80-6ab1-11eb-88cf-c6ea13c74140.png)

NetCore :

![NetCoreImage](https://user-images.githubusercontent.com/63052528/107310009-88189480-6ab1-11eb-8c5f-95006a011227.png)

Note : This issue occurs only when setting autoscaledimensions.

Issue 2:

While i launch the application in the 150dpi, the application moves out of screen area. Please refer the below image. And this issue occurs in the both NetFramework and Netcore.

Image:

NetCore Image:

![150% NetCore](https://user-images.githubusercontent.com/63052528/107310271-1c82f700-6ab2-11eb-82de-17383a883676.png)

NetFrameWork Image

![150% NetFrameWork](https://user-images.githubusercontent.com/63052528/107310367-463c1e00-6ab2-11eb-9d9d-39c839cb42dd.png)

Note : I'm running this application in the resolution 1366 X 768 and in the Dell laptop.

**Expected behavior:**

Issue 1: I'm expecting for both the NetFramework and NetCore the form size should be same.

Issue 2 : I'm  expecting this form should not moves out of the screen area. 

**Minimal repro:**

Issue 1:

Run the NetCore and NetFramework2017 applications in the 100% dpi.
you can able to replicate the issue.

Issue 2:

Run the NetCore application in the 150% dpi.
 
Please find the below Sample.

[Sample.zip](https://github.com/dotnet/winforms/files/5948519/Sample.zip)

**Comment by RussKie** [comment]
> Issue 1: I'm expecting for both the NetFramework and NetCore the form size should be same.

This is [by design](https://docs.microsoft.com/dotnet/core/compatibility/winforms#default-control-font-changed-to-segoe-ui-9-pt)

> Issue 2 : I'm expecting this form should not moves out of the screen area.

As noted in https://github.com/dotnet/winforms/issues/4527#issuecomment-775041383 at 150% scale factor the form is greater than the available desktop real estate.
Windows positions the form as it sees most appropriate in this circumstances.
