### ISSUE TITLE
The "FindNearestItem" method incorrectly identifies the item at the bottom when the ListView has "SmallIcon" view

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4558]
**.NET Core Version:**
- 6.0.0-alpha.1.21073.5

**Have you experienced this same bug with .NET Framework?:**
- Yes (4.7.2)

**Minimal repro:**
[Simple example.zip](https://github.com/dotnet/winforms/files/5970977/Issue-4458.zip)
1. Create ListView with 9 items
2. Set `SmallIcon` view
3. Add couple columns to ListView
4. The ListView should display items as follows:
```
1 2 3
4 5 6
7 8 9
```
5. Execute `FindNearestItem(SearchDirectionHint.Down)` for `1` and `4` items.

**Actual behavior:**
The "FindNearestItem" method returns `7` for `1` element
The "FindNearestItem" method returns `null` for `4` element
![image](https://user-images.githubusercontent.com/23376742/107754156-27e45580-6d32-11eb-81ab-87da52d25888.png)

**Expected behavior:**
The "FindNearestItem" method should return `4` for `1` element
The "FindNearestItem" method should return `7` for `4` element

**Comment by John-Qiao** [comment]
Verified the issue with the latest .NET 6.0.100-preview.3.21169.6 from master branch , this issue has been fixed that the "FindNearestItem" method returned the correct result for element. Please check the below gif file:

![4558-TestResult](https://user-images.githubusercontent.com/45864985/111963901-02b3e580-8b2f-11eb-823f-a28d5db5d210.gif)
