### ISSUE TITLE
System.Windows.Forms.Padding is missing "TypeForwardedFrom" attribute.

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#4561]
* .NET Core Version: 
net6.0 and possibly Net5.0+
* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
"Padding" was moved around and is now in a new binary specific to core. However, this type is missing "TypeForwardedFrom" attribute. Every type that have  "TypeforwardTo" attribute and can be serialized, should have "TypeForwardedFrom". We may need to scan "System.Windows.Forms.Primitive.dll" and see if any other types in it need this change.

**Expected behavior:**

"TypeForwardedFrom" attributes  on the types that were moved around in the "System.Windows.Forms.Primitive.dll"

**Comment by filipnavara** [comment]
Related: https://github.com/dotnet/winforms/issues/3306

**Comment by dreddy-work** [comment]
It seems padding is the only type that is serialized and was moved around. Associated PR is adding 'TypeForwardedFrom' attribute for this type.

**Comment by Zheng-Li01** [comment]
Verified the issue with .NET SDK 6.0.0-preview.4.21206.2, for now the Form1.resx can be opened successfully and values of System.Windows.Forms.Padding display correctly in the Form1.resx file after setting the Localizable property of Form1 as true and then updated the Padding property values. 
![Issue4561](https://user-images.githubusercontent.com/38325459/114335654-cdc00f00-9b7f-11eb-91b0-427525825fab.gif)

**Comment by Lydia-Shi** [comment]
Verified this issue with .NET 5.0.6(SDK 5.0.203), this issue is fixed.
