### ISSUE TITLE
Control Arrays in Design Mode

### ISSUE THREAD

**Issue by FANMixco** [dotnet/winforms#4565]
**Is your feature request related to a problem? Please describe.**

I'd like to see a similar solution to the one implemented in VB6 for Control Arrays in Design Mode. When can this be useful? When you have complex cases like this one:

[![Many labels in a window form][2]][2]

I had over 500 pictures that handled an Odontogram. This case was impossible to migrate to .NET because it would have involved a considerable re-engineering process from my side. Also, I believe a similar feature could be brought to **MAUI, WPF, and Avalonia**. This would increase the flexibility when you have to handle multiple related controls.

**Describe the solution you'd like and alternatives you've considered**

After reading several forums over the years, I was able to write this piece of code that more or less fixed "the problem" of Control Arrays in Design Mode. The example uses a series of **Label controls** created in Design Mode.

[![Many labels in a window form][1]][1]

### Code examples:

**VB.NET:**

```vb
Public Class Form1

    'To declare the List of controls
    Dim labels As New List(Of Label)()

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'To get all controls in the form
        For Each control In Me.Controls
            'To search for the specific type that you want to create the array 
            If control.[GetType]().Name.Contains("Label") Then
                'To add the control to the List
                labels.Add(DirectCast(control, Label))
            End If
        Next
        'To sort the labels by the ID
        labels = labels.OrderBy(Function(x) x.Name).ToList()
    End Sub
End Class
```

**C#:**

```csharp
public class Form1
{

    // To declare the List of controls
    private List<Label> labels = new List<Label>();

    private void Form1_Load(object sender, EventArgs e)
    {
        // To get all controls in the form
        foreach (var control in this.Controls)
        {
            // To search for the specific type that you want to create the array 
            if (control.GetType().Name.Contains("Label"))
                // To add the control to the List
                labels.Add((Label)control);
        }
        // To sort the labels by the ID
        labels = labels.OrderBy(x => x.Name).ToList();
    }
}
```

I used a **List** for convenient reasons, but with the pieces of code I shared, anyone can create in design time the controls that they need, and while they keep the "index" as the last character (label**1**, label**2**, ..., label**N**).

Later, they can iterate them with the loop and add them in the blink of an eye. After, they can manipulate them from the object (labels) like before labels(0), labels(1), etc.

There are 3 points to take into consideration:

 1. A `List` can be used to emulate the large collection of controls.
 2. `typeof(Control)` helps us define the type of the control to add to the list.
 3. The **"index"** defined as the last character *(label**1**, label**2**, ..., label**N**)* is the key. This helps us create a logical order.

Furthermore, here is another example running created **design mode** using **Text Boxes**:

[![Many text boxes in one window][3]][3]

**Running:**

[![running example][4]][4]

  [1]: https://i.stack.imgur.com/a2NLj.png
  [2]: https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/3624de11048267.560f05aecb9e9.jpg
  [3]: https://i.stack.imgur.com/uyCjW.png
  [4]: https://i.stack.imgur.com/atES2.png
**Will this feature affect UI controls?**

Up to a certain point. It might need a new property called Index or something that relates to this feature. I'd say a similar code to the one I shared can be used in the background. Also, another property might be needed to identify if it's an array.

**Comment by RussKie** [comment]
Thank you for sharing, but in its current form I am having difficulties to appreciate the general use case you would like address and what exactly you propose.

In my experience controls are given names to provide meanings in a given context, and I haven't seen control-heavy forms/usercontrols that preferred to deal with "label1", "label2"..."labelN" controls instead of "lblUserName", "firstNameLabel", etc.

**Comment by FANMixco** [comment]
Hi @RussKie , I agree with your point of view. Now, let's look at this picture:

<img width="64" alt="Screen Shot 2021-02-15 at 09 37 09" src="https://user-images.githubusercontent.com/1666156/107923178-687de200-6f71-11eb-900f-75a635cd8a0d.png">

Each of the sections can be colored. Therefore, you will have at least 5 arrays:

- UpSection.
- DownSection.
- RightSection.
- LeftSection.
- CenterSection.

I agree that you could handle the 42 pictures one by one per section. I'm sure many coders have done it for years since the feature was completely removed, or you had to build them in real-time. Even when you're coding apps (for Android), you have ListViews that contains lists of controls that you display in real-time, you cannot design it on Design Mode. However, it depends on the complexity, you don't want to design everything in real-time because it's harder to measure and align or do any change since you have to run VS all the time to test. Hopefully, it gives you an idea.

**Comment by RussKie** [comment]
Thank you, though I still can't see a gap in the current Windows Forms API. "Control array" falls into a category of "custom controls" that do not exist in a standard Windows UX. The aim of Windows Forms .NET is to allow developers build apps that look and feel native on Windows. "A feature X existed in language Y" is a weak business proposition, especially when in 20+ years there hasn't been any  significant customer demand for it (if there was 3rd party control vendors would have filled that gap).

> * stackoverflow.com/questions/39541/whats-the-simplest-net-equivalent-of-a-vb6-control-array

I haven't checked all the links, but IMO this thread has a number of good answers and explanations why VB6 controls array is absent and not needed. There are a number of other ways the problem can be solved in .NET Framework/.NET world including but not limited to the use of [user controls](https://docs.microsoft.com/dotnet/api/system.windows.forms.usercontrol), [FlowLayoutPanel](https://docs.microsoft.com/dotnet/api/system.windows.forms.flowlayoutpanel), and [TableLayoutPanel](https://docs.microsoft.com/dotnet/api/system.windows.forms.tablelayoutpanel).
I don't think it is totally reasonable to expect to migrate a VB6 codebase into .NET without some kind of expectations of rearchitect/remodel/rewrite.

The designer is obviously oblivious to dynamically added controls at runtime, and can only visualise the DOM described in `InitializeComponent` method. And this remains the factor with and without control arrays.

**Comment by FANMixco** [comment]
Hi @RussKie, I agree one of the answers in that thread is my own answer. That's why I know it's working. If you read the answers carefully, there is no alternative or option. Also, I didn't say that say in any case "A feature X existed in language Y". This is a poor comparison. I gave the example since from there comes the topic. Also, I gave a pretty clear case when this situation is overcomplicated to use. I understand business reasons pretty easily, I'm not just a coder, I manage projects and have to make budgets.

**Comment by weltkante** [comment]
I think there is a lot of miscommunication going on here.

As a previous user of VB6 I'm familiar with control arrays and understand what their value was and what they could contribute to WinForms.

In my opinion there are two scenarios where they were useful in VB6 - both for when you had larger amounts of controls on a form.
1) it allowed you to generate controls at runtime. This is not a problem in WinForms, you can just do that in code and collect the control references in a list, there is no special support required by WinForms here.
2) at design time it allows you to logically group the controls you placed into a collection you could access at runtime to e.g. iterate over. This is very useful if you have a larger amount of controls and need to operate on logical subgroups, for example if you want to control visibility in a structured way.

The second point would IMHO be valuable for WinForms, at the moment the best you can do is putting everything on a panel and abuse the controls collection of the panel as "control array". This doesn't always work well (sometimes controls are scattered and can't physically be placed on a panel) and the resulting design experience is suboptimal.

However, I believe this can be implemented by user code using the little known feature of [control extenders](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.iextenderprovider). In fact, when I was looking up the doc link just now, I noticed this [already has been implemented in the past and subsequently been deprecated](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.compatibility.vb6.basecontrolarray), probably has been forgotten, I certainly didn't know about that assembly. Maybe it can be used as a starting point, but it doesn't have to, it should be straightforward to design from scratch.

The way you would implement grouping of controls is to implement a control extender component representing a logical group, then place one instance of that component in the designer for each "control array" group you want to have. This will allow other controls on the design surface to be associated with the "control array" components. In fact it allows you to put a control into multiple groups if it makes sense to you (e.g. groups for rows and columns in a matrix layout, so you can easily iterate over individual columns and rows)

I don't know if the new .NET Core designer is up to the task yet, considering they didn't yet publish documentation how to implement custom controls, so control extenders are also not yet documented. Once the designer gets to a point where its actually usable for custom controls I may very well consider writing a prototype implementation of a control extender for logically grouping controls. Whether that is something for a nuget package or something that should be integrated can be decided later.

>  I believe a similar feature could be brought to MAUI, WPF, and Avalonia

I personally don't think there's any value to that, the approach of XAML based frameworks is to not do manual layout, but rather "build up" the UI layout from data objects. In these frameworks you'd describe the control array in your data model and let the UI build up itself around it. I have done that plenty of times and it works much better than manually layouting dozens of controls.

Though if you really wanted to you could easily implement logical grouping via attached properties there (the equivalent of control extenders). Just set the attached property in the designer, and the attached property implementation can add the control to a list, its trivial to implement.

I'd consider this off-topic for the WinForms repo though, so maybe not dwell too much on that part of the discussion.

**Comment by FANMixco** [comment]
Hi @weltkante , I have just one question if it's out off-topic, but you spoke about the ".NET Core designer", then, where can we ask about it?

I partially agree with this point:

_"I personally don't think there's any value to that, the approach of XAML based frameworks is to not do manual layout, but rather "build up" the UI layout from data objects."_

I have built apps with WPF, UWP, Android, and Xamarin.Android. I still believe it's overcomplicated to write too many things in the coding section. I have always felt this situation annoyed when I'm writing my Android apps. Also, this change could improve IMHP the communication between the UI Designers and the Coders. There should be an easier way for the designers to work and don't over-design things that the coder won't necessarily be able to implement (not the first that I have faced this). Some people might be thinking that **Blend** is a good tool for the designers and I partially agree, but it doesn't mean, you could not face the #1 case or simplify case #2.

**Comment by weltkante** [comment]
Its perfectly fine to discuss the _WinForms_ designer for .NET Core here, but I consider WPF/UWP/XAML/etc. discussions a bit too offtopic for the WinForms repo so I won't go into depth, they each have their own repository after all.

**Comment by FANMixco** [comment]
I get it @weltkante. Maybe then this topic should be on-hold and not closed.

**Comment by RussKie** [comment]
I fully appreciate you feel passionate about the control, but the hard reality of business is that the team won't be building a control that has no compelling business case behind it, nor we will be taking contributions of such control for the same reasons.
