### ISSUE TITLE
Move sub-classes to their own files

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4571]
**Controls that contain sub-classes:**
- [x]  ComponentEditorForm (#4572)
- [x]  DataGridViewComboBoxEditingControl (#4572)
- [x]  DocComment (#4572)
- [x]  DomainUpDown (#4573)
- [x]  DropDownButton (#4573)
- [x]  Form (#4573)
- [x]  GridErrorDlg (#4575)
- [x]  HotCommands (#4575)
- [x]  Label (#4575)
- [x]  MDIClient (#4576)
- [x]  MDIWindowDialog (#4576)
- [x]  PropertyGrid (#4602)
- [x]  PropertyGridView (#4603)
- [x]  RichTextBox (#4576)
- [x]  ScrollableControl (#4576)
- [x]  TabPage (#4694)
- [x]  ToolStrip (#4577)
- [x]  ToolStripContainer (#4577)
- [x]  ToolStripDropDown (#4577)
- [x]  ToolStripDropDownMenu (#4578)
- [x]  ToolStripPanel (#4578)
- [x]  UpDownButtons (#4579)
- [x]  WebBrowser (#4579)
- [x]  WebBrowserBase (#4579)

**Components that contain sub-classes:**
- [x]  ColumnHeader (#4605)
- [x]  ErrorProvider (#4605)
- [x]  FileDialog_Vista (#4606)
- [x]  NotifyIcon (#4612)
- [x]  OpenFileDialog (#4606)
- [x]  SaveFileDialog (#4606)
- [x]  ToolStripSplitButton  (#4612)
- [x]  ToolStripStatusLabel  (#4612)
- [x]  ToolTip (#4694)
- [x]  ToolStripLabel (#4613)
- [x]  ToolStripPanelRow (#4613)
- [x]  ToolStripProgressBar (#4614)
- [x]  ToolStripComboBox (#4614)
- [x]  ToolStripDropDownButton (#4613)
- [x]  ToolStripDropDownItem  (#4612)

**Lists and collections that contain sub-classes:**
- [x]  DataGridViewCellLinkedList (#4615)
- [x]  DataGridViewColumnCollection (#4615)
- [x]  DataGridViewIntLinkedList (#4615)
- [x]  DataGridViewRowCollection (#4617)
- [x]  ImageList.ImageCollection (#4615)
- [x]  ListBox.IntegerCollection (#4617)
- [x]  ListBox.SelectedIndexCollection (#4617)

**Classes that contain sub-classes:**
- [x]  CategoryGridEntry (#4618)
- [x]  DataFormats (#4618)
- [x]  DataGridViewComboBoxCell (#4618)
- [x]  DataGridViewHeaderCell (#4618)
- [x]  DataGridViewRow (#5136)
- [x]  DataGridViewTopLeftHeaderCell (#4695)
- [x]  FlatButtonAppearance (#4695)
- [x]  FlowLayout (#4698)
- [x]  FontCache (#4695)
- [x]  GridEntry (#4700)
- [x]  HtmlDocument (#4702)
- [x]  HtmlElement (#4702)
- [x]  HtmlWindow (#4702)
- [x]  KeyboardToolTipStateMachine (#4703)
- [x]  ListViewItemConverter (#4703)
- [x]  ListViewSubItem (#4703)
- [x]  LayoutUtils (#4703)
- [x]  MergePropertyDescriptor (#4705)
- [x]  MultiSelectRootGridEntry (#4705)
- [x]  PrintControllerWithStatusDialog (#4705)
- [x]  PropertyDescriptorGridEntry (#4706)
- [x]  PropertyStore (#4706)
- [x]  Screen (#5136)
- [x]  SendKeys (#5136)
- [x]  TableLayout (#5136)
- [x]  ToolStripItemInternalLayout (#5136)
- [x]  ToolStripSettings (#5136)
- [x]  TreeNode (#5136)

**Comment by RussKie** [comment]
Have we completed the list?
