### ISSUE TITLE
ComboBox does not handle DataBindings and empty BindingLists

### ISSUE THREAD

**Issue by KingMetal7** [dotnet/winforms#4582]
* .NET Framwork Version: 
.NET Framework 4.7.2

**Problem description:**
Problem 1:
If a BindingList is set as the DataSource for a default ComboBox and the BindingList is/gets empty,
on adding Items to the BindingList neither events (SelectedIndexChanged) are fired nor any
additional DataBindings are taken care of.

Problem 2:
DataBindings generally need the WriteValue() function called from the SelectionChangeCommitted event
in order to get set from the GUI ComboBox, which is an unnecessary workaround.

**Expected behavior:**
I set a empty BindingList as DataSource for the ComboBox and setup additional Databindings.
When adding an item to the empty BindingList the SelectedItemChanged, TextUpdate, SelectedIndexChanged
and SelectedValueChanged events of the ComboBox should fire and all associated DataBindings should get
updated/set (e.g. SelectedItem).
Selecting an item via GUI should update/set associated DataBinding without additional
function calls from events.

**Minimal repro:**
https://github.com/KingMetal7/ComboBox_Bug.git

**Comment by RussKie** [comment]
Thank you for the submission.

Given this behaviour existed in for many years there is a significant risk of breaking existing consumers who rely on the existing behaviour and may have worked around it, if we chose to make any changes.

If you wish to investigate it further, and present a solid technical case for changing the behaviour we'll be happy to consider it.
At this stage this goes into the "won't fix" bucket.
