### ISSUE TITLE
WinForms designer debugging is not working for netcore app

### ISSUE THREAD

**Issue by mageshsankar** [dotnet/winforms#4583]
* .NET Core Version: 
NetCore 3.1 and recent version

VS: VS2019

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

I trying to do designer debugging for my WinForms net core application using devenv.exe, but the breakpoint is never hit the source. Is designer debugging working in NETCore application.

**Expected behavior:**
The WinForms designer debugging should work.

**Minimal repro:**
Steps to reproduce:

1. In the attached project, I have created a custom button control with Property Called MyText.

2. Open the project setting and Select the Debug tab.

3. Choose the Launch Executables option. ---> Note: In Framework, it will display as Start with External Program.

4. Choose devenv exe location as the executable path.

5. Then Put the breakpoint in the MyText property setter of CustomButton class.

6. Then Click start program to start debugging.

7. Then click the WinformformsApp1 in the recent list.

8. Open the Form1 designer in the newly open VS instance.

10. Then Change MyText property value in design time.

11.Now the Setter of MyText property should be hit while changing its value. But breakpoint won't hit.

The Same scenario working fine in the 4.6 or less Framework application.

**Project:** 
[169259-windowsformsapp1-copy.zip](https://github.com/dotnet/winforms/files/6006962/169259-windowsformsapp1-copy.zip)

**Reproducible Video:** 
[169273-debugvideo.zip](https://github.com/dotnet/winforms/files/6006964/169273-debugvideo.zip)

**Comment by weltkante** [comment]
> I have created a custom button control with Property Called MyText.

As far as I know creating custom controls is not fully supported yet (at least they didn't document how to do it, still waiting). There have been plenty designer changes that make it impossible to just run a Desktop Framework custom control on .NET Core.

> Choose devenv exe location as the executable path.

The new designer is running in a separate process, so if you want to debug your control before official support is finished you can try identifying that process and attaching to that instead of attaching to the VS host.

**Comment by RussKie** [comment]
> The new designer is running in a separate process, so if you want to debug your control before official support is finished you can try identifying that process and attaching to that instead of attaching to the VS host.

![image](https://user-images.githubusercontent.com/4403806/109444165-aeb66380-7a90-11eb-87b4-4d031b63336d.png)
