### ISSUE TITLE
DataGridView.SelectedCells returns inconsistent results based on selection type

### ISSUE THREAD

**Issue by rvv27** [dotnet/winforms#4594]
* .NET Core Version: 
Any version

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
When using DataGridView.SelectedCells property it returns the Selected Cells. When doing so it ignores the cells from rows which are set Visible = false. i.e. SelectedCells.Count ignores the hidden rows and gets the actual visible cell count

Bug: This however doesn't work if you use rectangular selection. i.e. The selection must include more than 1 column and more than 1 row. In this case the SelectedCells include all the cells from top left to bottom right corners, even from the rows which are set to Visible = false. This is a Inconsistent behavior.

**Expected behavior:**
DatagridView.SelectedCells property should behave the same no matter the selection type. Whether the selection is from the same column or same row or rectangular selection.

**Minimal repro:**
Any Datagridview produces this result

**Comment by RussKie** [comment]
Can you please clarify the customer scenario and repro steps. It is a little unclear what and how you're performing selections. An animated gif will help as well.
Thanks.
