### ISSUE TITLE
Form and CheckedListBox icons contain only 16x16 frames

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#4598]
We need icons with multiple resolution to support HDPI environment. 
https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/Resources/System/Windows/Forms/Form.ico
https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/Resources/System/Windows/Forms/CheckedListBox.ico
![image](https://user-images.githubusercontent.com/15823268/109053876-0c623e80-7692-11eb-973f-bc4994aa8778.png)

 
![image](https://user-images.githubusercontent.com/15823268/109053525-a4abf380-7691-11eb-985b-9b570d6fb797.png)
![image](https://user-images.githubusercontent.com/15823268/109053566-b2fa0f80-7691-11eb-9331-39a818d42078.png)

Ported from 
https://github.com/dotnet/winforms-designer/issues/2904
https://github.com/dotnet/winforms-designer/issues/2905

**Comment by Tanya-Solyanik** [comment]
Winforms Designer has a local work around for this issue that uses larger resolution bmps. I'm not sure where the multiple resolution icons are. We might have to contact UX designers.

**Comment by dreddy-work** [comment]
We do have multiple resolution Icons for all winforms controls. Will get these things fixed as part of the high DPI work.

**Comment by dreddy-work** [comment]
@Tanya-Solyanik , we do have multiple resolution Icons in runtime. I just cross checked. If it is not being picked up in VS, that could be a different issue ( may be we are not querying for right DPI). Please feel free to open a new issue if that is the case and close this one?

**Comment by dreddy-work** [comment]
Closing this for now. @Tanya-Solyanik , feel free to reactivate if you see anything contradicting.

**Comment by weltkante** [comment]
> we do have multiple resolution Icons in runtime

The [folder](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/Resources/System/Windows/Forms) mentioned above only seems to contain 16x16 icons. Maybe they aren't used anymore, but then you could just remove them? If they are still used they probably should be unified with their multi resolution counterparts. Browsing that folder in a local checkout indicates there are plenty of bad resolution icons in that folder.
