### ISSUE TITLE
Inconsistent behavior getting/setting scroll bar visibility for ScrollableControl / UserControl

### ISSUE THREAD

**Issue by techfan101** [dotnet/winforms#4607]
**Environment**

.NET Core Version: 5.0

**Problem description:**

While I was implementing a custom [UserControl](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.usercontrol), I noticed some very strange behavior regarding the visibility of the scroll bars.  Upon further investigation, this behavior seems to point to a bug in its parent class:  [ScrollableControl](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol).

In a class derived from [ScrollableControl](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol), there appear to be three different documented means of getting or setting the visibility of the scroll bars:

1. Via the [HorizontalScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.horizontalscroll) or [VerticalScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.verticalscroll) properties, using their [Visible](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollproperties.visible) field.
2. Via the [HScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.hscroll) or [VScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.vscroll) properties.
3. Via the [GetScrollState](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.getscrollstate)/[SetScrollState](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.setscrollstate) methods, using the [ScrollStateHScrollVisible](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.scrollstatehscrollvisible)/[ScrollStateVScrollVisible](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.scrollstatevscrollvisible) bits.

Setting the visibility using method 1 ([HorizontalScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.horizontalscroll)/[VerticalScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.verticalscroll)) successfully changes the visibility of the scroll bars.  However, the results returned by methods 2 ([HScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.hscroll)/[VScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.vscroll)) and 3 ([GetScrollState](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.getscrollstate)) do not reflect the changed value.

Setting the visibility using methods 2 ([HScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.hscroll)/[VScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.vscroll)) and 3 ([SetScrollState](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.setscrollstate))  does not normally (more on this later) affect the visibility of the scroll bars.  Also, the results returned by method 1 ([HorizontalScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.horizontalscroll)/[VerticalScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.verticalscroll)) do not reflect the changed value.

I'll class the following under the truly weird category, to the point I highly doubted my own results.  Starting with both scroll bars already visible, setting either the horizontal **OR** vertical visibility to true (using methods 2 or 3), will cause **BOTH** scroll bars to vanish.  Even stranger, after they have vanished, the visibility returned by method 1 will indicate that they are both still visible.  This result was so unexpected, that I spent a lot of time confirming the behavior.

**Expected behavior:**

Assuming [AutoScroll](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollablecontrol.autoscroll) is set to false, after changing the visibility using any of these three methods, one would reasonably expect two things to occur:

1. The visibility of the control would actually change.
2. Subsequently, getting that same visibility using any of the three methods would return the same result.

Regrettably, as described earlier, neither of these two assertions is true.

**Minimal repro:**

Here, I've focused solely on the disconnect between the set values and the expected get values.  Below is a derived class, with three test methods:

1. `HorizontalVerticalScrollTest` - This demonstrates failed assertions resulting from setting visibility via method 1.
2. `HVScrollTest` - This demonstrates failed assertions resulting from setting visibility via method 2.
3. `ScrollStateHVScrollVisibleTest` - This demonstrates failed assertions resulting from setting visibility via method 3.

The GUI aspects of visibility are not reproduced here, though this is easily accomplished by hosting this derived control in a form.

```
using System;
using System.Windows.Forms;

namespace ScrollableControlBug
{
	public class DerivedControl : ScrollableControl
	{
		// In this method, the following assertions fail (see AssertAfterState)
		//   After: HScroll
		//   After: VScroll
		//   After: ScrollStateHScrollVisible
		//   After: ScrollStateVScrollVisible
		public void HorizontalVerticalScrollTest()
		{
			AssertBeforeState();

			HorizontalScroll.Visible = true;
			VerticalScroll.Visible = true;

			AssertAfterState();
		}

		// In this method, the following assertions fail (see AssertAfterState)
		//   After: HorizontalScroll.Visible
		//   After: VerticalScroll.Visible
		public void HVScrollTest()
		{
			AssertBeforeState();

			HScroll = true;
			VScroll = true;

			AssertAfterState();
		}

		// In this method, the following assertions fail (see AssertAfterState)
		//   After: HorizontalScroll.Visible
		//   After: VerticalScroll.Visible
		public void ScrollStateHVScrollVisibleTest()
		{
			AssertBeforeState();

			SetScrollState(ScrollStateHScrollVisible, true);
			SetScrollState(ScrollStateVScrollVisible, true);

			AssertAfterState();
		}

		private void AssertBeforeState()
		{
			Assert.IsFalse(AutoScroll, "Before: AutoScroll");
			Assert.IsFalse(HorizontalScroll.Visible, "Before: HorizontalScroll.Visible");
			Assert.IsFalse(VerticalScroll.Visible, "Before: VerticalScroll.Visible");
			Assert.IsFalse(HScroll, "Before: HScroll");
			Assert.IsFalse(VScroll, "Before: VScroll");
			Assert.IsFalse(GetScrollState(ScrollStateHScrollVisible), "Before: ScrollStateHScrollVisible");
			Assert.IsFalse(GetScrollState(ScrollStateVScrollVisible), "Before: ScrollStateVScrollVisible");
		}

		private void AssertAfterState()
		{
			Assert.IsFalse(AutoScroll, "After: AutoScroll");
			Assert.IsTrue(HorizontalScroll.Visible, "After: HorizontalScroll.Visible");
			Assert.IsTrue(VerticalScroll.Visible, "After: VerticalScroll.Visible");
			Assert.IsTrue(HScroll, "After: HScroll");
			Assert.IsTrue(VScroll, "After: VScroll");
			Assert.IsTrue(GetScrollState(ScrollStateHScrollVisible), "After: ScrollStateHScrollVisible");
			Assert.IsTrue(GetScrollState(ScrollStateVScrollVisible), "After: ScrollStateVScrollVisible");
		}

		private static class Assert
		{
			public static void IsFalse(bool value, string message)
			{
				if (value)
					throw new Exception(message);
			}

			public static void IsTrue(bool value, string message)
			{
				if (!value)
					throw new Exception(message);
			}
		}
	}
}
```

**Comment by elachlan** [comment]
@Olina-Zhang could your team please test this?

**Comment by Zheng-Li01** [comment]
@elachlan, verified the issue with the code section that provided by user on .NET5 & .NET9 & .NET Framework 4.8.1, which all have the same results are as described by the user. see below details.

**Repro application:**
[Core_4607.zip](https://github.com/dotnet/winforms/files/13262078/Core_4607.zip)
[Framework_4607.zip](https://github.com/dotnet/winforms/files/13262079/Framework_4607.zip)

**Repro video:**
https://github.com/dotnet/winforms/assets/38325459/418683ce-025c-4d8f-8fbb-4066f4d4e57e

**Exception details:**
System.Exception
  HResult=0x80131500
  Message=After: HScroll
  Source=Core_4607
  StackTrace:
   at Issue_4607.DerivedControl.Assert.IsTrue(Boolean value, String message) in C:\Users\v-zhgl\source\repos\Issue_4607\Issue_4607\DerivedControl.cs:line 85
   at Issue_4607.DerivedControl.AssertAfterState() in C:\Users\v-zhgl\source\repos\Issue_4607\Issue_4607\DerivedControl.cs:line 68
   at Issue_4607.DerivedControl.HorizontalVerticalScrollTest() in C:\Users\v-zhgl\source\repos\Issue_4607\Issue_4607\DerivedControl.cs:line 23
   at Issue_4607.Form1.HorizontalVerticalScrollTest(Object sender, EventArgs e) in C:\Users\v-zhgl\source\repos\Issue_4607\Issue_4607\Form1.cs:line 15
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by merriemcgaw** [comment]
Given the behavior in the Framework is the same, and there has been no more input in the issue, I think we are good to close this unless we get more requests.
