### ISSUE TITLE
maximized MDI child not response to icon changes

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#4621]
* .NET Core Version: **All**

* Have you experienced this same bug with .NET Framework?: **Yes**

**Problem description:**
Icon on maximized child form not react on Hide/Show and Icon (picture) changing - see below:

https://user-images.githubusercontent.com/17767561/109413054-97a64180-79bc-11eb-8a92-c2c0e81cea12.mp4

**Expected behavior:**
Icon on maximized child form properly react on Hide/Show and Icon changing.

**Minimal repro:**
[WinFormsCoreTest_MDI_Icon.zip](https://github.com/dotnet/winforms/files/6056464/WinFormsCoreTest_MDI_Icon.zip)

**Comment by RussKie** [comment]
Since this is a long standing existing behaviour setting is up for grabs. You're welcome to submit a PR with a fix 😉

**Comment by John-Qiao** [comment]
Verified the issue with the latest .NET 6.0.100-preview.3.21169.6 from master branch , this issue has been fixed that the icon on maximized child form properly react on Hide/Show and Icon changing. Please check the below gif file:
![4621-TestResult](https://user-images.githubusercontent.com/45864985/111964579-b9b06100-8b2f-11eb-93c3-ee16747b16bb.gif)
