### ISSUE TITLE
Remove remaining `EnumValidator`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#4639]
An addendum to https://github.com/dotnet/winforms/pull/4043 that replaced enum validations with source generators. We still have runtime enum validations lurking around, and they needs to be cleaned out and replaced with the compile-time validations.
https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs#L334-L377

**Comment by wreuel** [comment]
Hello @RussKie how could I help to solve this one?

**Comment by RussKie** [comment]
In #4043 we have replaced enum runtime validations with compile-time validations facilitated by the source generators. But we missed `ContentAlignment` validations.

To fix the following steps needs to be performed:
1. Find all callsites where `ContentAlignment` is validated
2. Write tests for all these callsites, if those absent. I had a cursory look, and we have at least some test coverage. Missing tests should be easy to add
3. Remove `EnumValidator` and replaced callsites with `SourceGenerated.EnumValidator.Validate`
4. Verify the tests continue to pass.

For the ease of review step 2 should be its own commit, followed by a commit with the actual change.

Please LMK if you want to have a go at it, or have any questions.
Thank you

**Comment by wreuel** [comment]
@RussKie I think I could help with this, maybe it will take more time than the last one. (If this is not a problem)

Could you assigne to me?

**Comment by RussKie** [comment]
No rush :) Thank you

**Comment by wreuel** [comment]
To keep me organized, I did a list.

- [ ] ButtonBase.cs
- [x] ButtonBase.cs - Tests (Already Covered)
- [ ] CheckBox.cs
- [x] CheckBox.cs - Tests (Already Covered)
- [ ] Label.cs
- [x] Label.cs - Tests (Tests needed)
- [ ] RadioButton.cs
- [x] RadioButton.cs - Tests (Tests needed)
- [ ] ToolStripControlHost.cs
- [x] ToolStripControlHost.cs - Tests (Already Covered)
- [ ] ToolStripItem.cs
- [x] ToolStripItem.cs - Tests (Already Covered)

**Comment by RussKie** [comment]
@wreuel have you had a chance to look at what methods use `EnumValidator.IsEnumWithinShiftedRange`?

**Comment by wreuel** [comment]
> @wreuel have you had a chance to look at what methods use `EnumValidator.IsEnumWithinShiftedRange`?

Nope @RussKie , I didn't looked up on theses, should I?

**Comment by RussKie** [comment]
It needs to go away as well. @AraHaan is touching the callsites for `EnumValidator.IsEnumWithinShiftedRange` in  #4746, and I expect it to be removed as part of that work.
I just want to make sure no-one is stepping on someone else's toes.

**Comment by AraHaan** [comment]
@RussKie So you want to to remove all callsites that use ``EnumValidator.IsEnumWithinShiftedRange`` inside of #4746?

**Comment by RussKie** [comment]
Ideally we do it in a separate PR _before_  #4746. Otherwise you may need to write more tests, which will be deleted after.
If you don't mind - create a new PR to address this first, then we can continue on  #4746.

**Comment by AraHaan** [comment]
I think cherry picking https://github.com/dotnet/winforms/pull/4746/commits/51a551c6a190329263240acc4d92ba008e8ea0be into a new pr, then dropping that commit in #4746 might work for this.

**Comment by AraHaan** [comment]
Opened #4809 for removing ``EnumValidator.IsEnumWithinShiftedRange`` from ``MessageBox.cs``.

**Comment by AraHaan** [comment]
should the ``up-for-grabs`` label be removed as well?

**Comment by RussKie** [comment]
Thanks for checking.
This is closed, so I don't think it matters...
