### ISSUE TITLE
Add a new virtual property `StatusStripBorder` to `ToolStripProfessionalRenderer`

### ISSUE THREAD

**Issue by Balkoth** [dotnet/winforms#4643]
# Summary

Currently, if you want to theme your application with a `ToolStripProfessionalRenderer`, there is an issue with the `StatusStrip` border, as the drawing routine uses a hardcoded value for the border color. A new virtual property should be added to the `ProfessionalColorTable` to customize that color. I have create a draft pull request here #4739.

# Proposed API

```diff
public static class ProfessionalColors
{
        [SRDescription(nameof(SR.ProfessionalColorsSeparatorLightDescr))]
        public static Color SeparatorLight => ColorTable.SeparatorLight;

+        [SRDescription(nameof(SR.ProfessionalColorsStatusStripBorderDescr))]
+        public static Color StatusStripBorder => ColorTable.StatusStripBorder;

        [SRDescription(nameof(SR.ProfessionalColorsStatusStripGradientBeginDescr))]
        public static Color StatusStripGradientBegin => ColorTable.StatusStripGradientBegin;
}
```
```diff
public class ProfessionalColorTable
{
        [SRDescription(nameof(SR.ProfessionalColorsSeparatorLightDescr))]
        public virtual Color SeparatorLight => FromKnownColor(KnownColors.msocbvcrCBSplitterLineLight);

+        [SRDescription(nameof(SR.ProfessionalColorsStatusStripBorderDescr))]
+        public virtual Color StatusStripBorder => FromKnownColor(KnownColors.msocbvcrCBShadow);

        [SRDescription(nameof(SR.ProfessionalColorsStatusStripGradientBeginDescr))]
        public virtual Color StatusStripGradientBegin => FromKnownColor(KnownColors.msocbvcrCBGradMainMenuHorzBegin);
}
```

### Implementations

```diff
public class ToolStripProfessionalRenderer : ToolStripRenderer
{
    private void RenderStatusStripBorder(ToolStripRenderEventArgs e)
    {
-        e.Graphics.DrawLine(SystemPens.ButtonHighlight, 0, 0, e.ToolStrip.Width, 0);
+        e.Graphics.DrawLine(ColorTable.StatusStripBorder, 0, 0, e.ToolStrip.Width, 0);
    }
}
```

# Example
Create a custom color table deriving from 'ProfessionalColorTable' and overwrite the new virtual property 'StatusStripBorder' with the desired color:
```cs
public sealed class MyColorTable : ProfessionalColorTable
{
    public override Color StatusStripBorder => Color.FromArgb(50, 50, 50);
}
```
Create a custom renderer deriving from 'ToolStripProfessionalRenderer' feeding the base constructor an instance of the custom color table created earlier:
```cs
public sealed class MyRenderer : ToolStripProfessionalRenderer
{
    public MyRenderer() : base(new MyColorTable())
    {
    }
}
```
Now just set the created renderer to be the renderer of the 'StatusStrip' where desired:
```cs
StatusStrip statusStrip = new StatusStrip();
statusStrip.Renderer = new MyRenderer();
```

**Comment by RussKie** [comment]
> Either respect the Color specified in ToolStripBorder in the ProfessionalColorTable or add a new virtual property StatusStripBorder. Option 2 would be preferred.

Could you please elaborate why you prefer option 2?

**Comment by Balkoth** [comment]
There are alrady existing properties StatusStripGradientBegin and StatusStripGradientEnd so i figured it would be best to have a separate property for the StatusStripBorder as well.

**Comment by RussKie** [comment]
@Balkoth to have a new public API added we need to have a formal [API proposal](https://github.com/dotnet/winforms/blob/main/docs/issue-guide.md#feature-and-api-suggestions) ([examples](https://github.com/dotnet/winforms/issues?q=label%3Aapi-approved)). 
If you'd like to take this proposal further and are willing to champion it and have it implemented, please update your original post. A draft pull request will also help in reviews.
Thank you

**Comment by Balkoth** [comment]
I have updated my original post following your directions.

**Comment by merriemcgaw** [comment]
During implementation we will want to make sure that High Contrast themes are honored and we're able to adjust when a user needs to have High Contrast. Obviously a user can override to something that doesn't work in high contrast, but our defaults need to be accessible.

Other than validating that, I have no personal objections.
