### ISSUE TITLE
ComboBox’s text cannot be partially selected when using mouse slides

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#465]
**OS:** RS5 X64
**VS:** Dev16 16.0.0 Preview 4.0 [28612.88.d16.0]
**.NET SDK:** .NET Core 3.0.100-preview-010334 from release branch

**More info:**
The issue reproduce on when setting the "DropDownStyle" property value of the Combobox control is "Sample"/"DropDown".

**Steps to Reproduce:**
1.  Open the attached .NET Core application and run it.([\\mlangfs1\public\Winforms\v-zhgl\ComboboxIssue\CoreApplication.zip](url))
2. Try to select partially text in the Combobox control using mouse slides.

**Actual**: ComboBox’s text cannot be partially selected when using mouse slides
![comboboxissue](https://user-images.githubusercontent.com/38325459/53146214-549b8180-35de-11e9-813e-012b3a6ad75e.gif)

**Expected**: ComboBox’s text can be partially selected when using mouse slides

**Comment by merriemcgaw** [comment]
@Zheng-Li01 is this a regression from an earlier Core build? Does this repro in 4.8 applications?

**Comment by Zheng-Li01** [comment]
This is a regression issue, which can’t reproduce on the earlier Core build: 009844,  but the issue can reproduce on the 4.8 application, and there have a .NETFramework bug: 790782 to trace it.

**Comment by merriemcgaw** [comment]
@Zheng-Li01 can you see if this is still an issue with the latest builds? @dreddy-work  as fyi.

**Comment by merriemcgaw** [comment]
@M-Lipin could you see if this might be a regression from an accessibility change

**Comment by Zheng-Li01** [comment]
@merriemcgaw, Verified the issue with latest .NET Core 3.0  build [3.0.100..10485] form release branch, the issue still can reproduce.

**Comment by merriemcgaw** [comment]
@M-Lipin , putting this on your plate to port the fix you did in Framework.

**Comment by corbob** [comment]
FWIW: I just downloaded the latest devpack for Framework 4.8, and this issue exists there as well.

**Comment by Zheng-Li01** [comment]
@corbob, Installed the latest devpack for Framework 4.8 from https://dotnet.microsoft.com/download/thank-you/net48-developer-pack, noticed that the build number is 4.8.3761.0 for now. The build is not contains the fix for the issue yet. So you need to wait next builds in the future to verify if the issue was fixed.

**Comment by merriemcgaw** [comment]
@vladimir-krestov or @M-Lipin could you port this .NET Framework fix by the end of this milestone?
