### ISSUE TITLE
`ListViewSubItem` not shown in Inspector tree when `ListViewItem` belongs to group

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4678]
.NET Core Version:
- 5.0.200-preview.20614.14

Have you experienced this same bug with .NET Framework?: 
- No. It is regression from #3223

**Minimal repro:**
1. Create application with ListView.
2. Set View.Tile for ListView.
3. Add couple ColumnHeaders to ListView.
4. Add ListViewGroup to ListView.
5. Add ListViewItem with ListViewSubItem to ListView.
6. Select ListViewGroup as Group of the ListViewItem.
7. Or use [attached project](https://github.com/dotnet/winforms/files/6130214/Issue-4678.zip)
8. Run application.
9. Run Inpsector.
10. Select ListViewItem in Inspector.
11. Try to expand ListViewItem

**Actual behavior:**
ListViewItem is empty.
![Issue-4678-issue - actual](https://user-images.githubusercontent.com/23376742/110942192-865d1d80-834a-11eb-80a1-a499931046a1.png)

**Expected behavior:**
ListViewItem should contains ListViewSubItem
![Issue-4678-issue - expected](https://user-images.githubusercontent.com/23376742/110942221-91b04900-834a-11eb-9c04-2a583547a6a3.png)

**Note**
I think this problem is produced due to strange checking of the `_owningGroup` in [this condition](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs#L150)

**Comment by SergeySmirnov-Akvelon** [comment]
Fixed in scope of #4205

**Comment by Jessie-Zhang01** [comment]
Verified this issue with .Net SDK 6.0.100-preview.4.21201.21, this issue is fixed. ListViewItem contains ListViewSubItem.
![image](https://user-images.githubusercontent.com/45864649/113372240-c9833d00-939a-11eb-98d4-ca2acb52440e.png)
