### ISSUE TITLE
The yellow rectangle is not displayed for a subitem when the user hovers over it or selects in the Inspector tree

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4679]
.NET Core Version:
- 5.0.200-preview.20614.14

Have you experienced this same bug with .NET Framework?: 
- No. It is regression from #3223

**Minimal repro:**

1. Create application with ListView.
2. Set View.Tile for ListView
3. Add couple ColumnHeaders to ListView.
4. Add ListViewItem with ListViewSubItem to ListView.
5. Or use [attached project](https://github.com/dotnet/winforms/files/6130220/Issue-4679.zip)
6. Run application.
7. Run Inpsector.
8. Select ListViewItem in Inspector.
9. Expand ListViewItem
10. Select ListViewSubItem.

**Actual behavior:**
Yellow rectangle is not displayed.
![Issue-4678-issue2 - actual ](https://user-images.githubusercontent.com/23376742/110942414-d6d47b00-834a-11eb-8c37-f5758a16f651.png)

**Expected:**
Yellow rectangle should displaye around the ListViewSubItem
![Issue-4678-issue2 - expected](https://user-images.githubusercontent.com/23376742/110942444-df2cb600-834a-11eb-9b89-301919189116.png)

**Note:**
I think the problem is reproduced due to [this condition](https://github.com/dotnet/winforms/blob/775aef04bf1f5d2c8af3ff01c622749438bc464f/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L3656). `View.Tile` view also supports displaying the first subitem

**Comment by Marie-Shi** [comment]
Verified this issue with 6.0.100-preview.5.21276.14 from Release/6.0.1XX-preview5 branch of https://github.com/dotnet/installer, it is fixed, now Yellow rectangle displays around the ListViewSubItem.
![fix](https://user-images.githubusercontent.com/45864017/119779227-054e0500-befb-11eb-8d27-49ebb14c11dd.png)
