### ISSUE TITLE
Required types and 'This method/object is not implemented by design.'

### ISSUE THREAD

**Issue by alepikhov** [dotnet/winforms#469]
While trying to put our codebase on core3 rails, we faced unexpected exception that frustrated us.
 
The following types are strongly necessary for our application:
- System.Drawing.Design.ToolboxItem
- System.ComponentModel.Design.ComponentDesigner 
 
But we catch this exception: 
System.NotImplementedException: 'This method/object is not implemented by design.' 
 
Could you confirm that these types are in your plan and will be implemented in release v3.0?
 
We are also waiting for the following types from the System.Design lib:
- System.ComponentModel.Design.UndoEngine
- System.ComponentModel.Design.DesignSurface 
- System.ComponentModel.Design.InheritanceService 
- System.ComponentModel.Design.DesignerActionMethodItem
- System.ComponentModel.Design.DesignerActionPropertyItem
 
Can we expect to see all the missed types in the final release?

**Comment by merriemcgaw** [comment]
@JuditRose , are these part of the list you're porting now?

**Comment by merriemcgaw** [comment]
@alepikhov , can I ask what you're doing with these classes in your application? Our assumption is that you are providing some design experience. Our Core 3 designer is a work in progress, so you may need to wait until we've got that completed if you are dependent on VS for your application.  We are in the process of porting most of the System.Design component, but we're curious as to how it's being used in applications.

**Comment by JuditRose** [comment]
Hi,
@alepikhov We are already working on porting some missing components to core. There is a pending PR for issue #177. And the other related issue is #221 .
I have just crossreferenced this list with the list in #221 and all the items here are included there as well. We decided to port the System.Design components from the list in #221. I am already working on Toolbox related components, PR is coming next week. I can prioritize up  ComponentDesigner, so the 2 mostly needed components can be finished first.

**Comment by weltkante** [comment]
@merriemcgaw Not speaking for the original creator of the issue, but the WinForms Designer API is publically available and not reserved to VS for designing forms, it is "commonly" used in end user Designers (i.e. if there is a WinForms end user designer in the product it is most likey based on these APIs). We have multiple of them in our own product (a 3rd party report designer, one full forms designer being implemented ourselves to do visual placement of machines in a hall, one just a property grid without a design form, used to configure services). It used to be well documented in blog posts, articles and samples in the .NET 2 era, but recently most of them started to disappear (or become hard to find) due to their age I assume.

**Comment by alepikhov** [comment]
@merriemcgaw, we are trying to port our end-user report designer component to .Net Core 3.

@JuditRose, it will be great if you prioritize up ComponentDesigner.
Thank you for showing us the current situation and your plans to port System.Design for Core3. We can now hope that we will manage to update our product before Core3 is released.

**Comment by JuditRose** [comment]
Component designer is coming in this PR #552

**Comment by alepikhov** [comment]
Thank you for prioritizing our request. Our customers are looking forward to start using our product in the NetCore 3 environment.
Today we have tried to build and run our app with the latest NetCore 3 build (https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe) and found the following classes, which raise the NotImplemented exception:
- System.Windows.Forms.Design.ComponentTray
- System.Drawing.Design.ToolboxComponentsCreatingEventArgs  (Used in System.Drawing.Design.ToolBoxItem)
- System.ComponentModel.Design.Serialization.CodeDomSerializationProvider 
(we are using CodeDomComponentSerializationService)

Also, System.ComponentModel.Design.ComponentDesigner does not have a full implementation for the System.ComponentModel.Design.IDesignerFilter Interface.
