### ISSUE TITLE
Improve startup performance of applications with crossgen

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#471]
Work planned for composition repository will now be done in core-setup

**Comment by zsd4yr** [comment]
Updating with info from email thread:

Downside:
* crossgen increases the size of our assembly by about a factor of 2 
  * Without crossgen 5.37 MB (5,633,104 bytes)
  * With  12.1 MB (12,783,616 bytes)

Upsides:
* crossgen decreases our JIT time by ~85% (that’s about a 7 fold decrease!)
* crossgen decreases our number of JIT compilations by over 90% (10 fold decreases)
* our native size has also decreases by ~90%
* Startup time drops from 477.28ms to 321.949ms.  That’s an improvement of 155.33ms or 32.55%.
* Reference set (memory touches) drop from 13953 pages to 13845 pages.  That’s an improvement of 108 pages.

## Before Crossgen
Name | JitTime   msec | Num Compilations | IL Size | Native Size | Foreground   msec
-- | -- | -- | -- | -- | --
TOTAL | 273.4 | 1,827 | 130,874 | 441,527 | 247.9
C:\Users\zadanz\Desktop\CrossGen_strawman\Before\shared\Microsoft.WindowsDesktop.App\3.0.0-preview4-27422-21\System.Windows.Forms.dll | 198.0 | 1,459 | 94,962 | 327,054 | 175.2
C:\Users\zadanz\Desktop\CrossGen_strawman\Before\shared\Microsoft.WindowsDesktop.App\3.0.0-preview4-27422-21\System.Drawing.Common.dll | 39.7 | 233 | 27,012 | 82,753 | 39.7
C:\Users\zadanz\Desktop\CrossGen_strawman\Before\shared\Microsoft.NETCore.App\3.0.0-preview4-27424-2\System.Private.CoreLib.dll | 18.7 | 87 | 4,646 | 17,538 | 17.0
C:\Users\zadanz\Desktop\CrossGen_strawman\MyCrossGenWinformsApp\bin\Release\netcoreapp3.0\MyCrossGenWinformsApp.dll | 10.9 | 5 | 490 | 1,464 | 10.9
C:\Users\zadanz\Desktop\CrossGen_strawman\Before\shared\Microsoft.WindowsDesktop.App\3.0.0-preview4-27422-21\Microsoft.Win32.SystemEvents.dll | 3.6 | 23 | 2,752 | 7,804 | 3.6
C:\Users\zadanz\Desktop\CrossGen_strawman\Before\shared\Microsoft.NETCore.App\3.0.0-preview4-27424-2\System.Collections.Concurrent.dll | 1.6 | 11 | 829 | 4,640 | 1.6
C:\Users\zadanz\Desktop\CrossGen_strawman\Before\shared\Microsoft.NETCore.App\3.0.0-preview4-27424-2\System.ComponentModel.Primitives.dll | 0.6 | 3 | 88 | 195 | 0.0
C:\Users\zadanz\Desktop\CrossGen_strawman\Before\shared\Microsoft.NETCore.App\3.0.0-preview4-27424-2\System.Drawing.Primitives.dll | 0.3 | 6 | 95 | 79 | 0.0

## After Crossgen 
Name | JitTime   msec | Num Compilations | IL Size | Native Size | Foreground   msec
-- | -- | -- | -- | -- | --
TOTAL | 98.4 | 505 | 35,751 | 153,301 | 98.4
C:\Users\zadanz\Desktop\CrossGen_strawman\After\shared\Microsoft.WindowsDesktop.App\3.0.0-preview4-27422-21\System.Drawing.Common.dll | 36.6 | 245 | 27,430 | 84,508 | 36.6
C:\Users\zadanz\Desktop\CrossGen_strawman\After\shared\Microsoft.WindowsDesktop.App\3.0.0-preview4-27422-21\System.Windows.Forms.dll | 29.2 | 144 | 0 | 37,979 | 29.2
C:\Users\zadanz\Desktop\CrossGen_strawman\After\shared\Microsoft.NETCore.App\3.0.0-preview4-27424-2\System.Private.CoreLib.dll | 17.7 | 77 | 4,250 | 16,906 | 17.7
C:\Users\zadanz\Desktop\CrossGen_strawman\MyCrossGenWinformsApp\bin\Release\netcoreapp3.0\MyCrossGenWinformsApp.dll | 8.3 | 5 | 490 | 1,464 | 8.3
C:\Users\zadanz\Desktop\CrossGen_strawman\After\shared\Microsoft.WindowsDesktop.App\3.0.0-preview4-27422-21\Microsoft.Win32.SystemEvents.dll | 5.0 | 23 | 2,752 | 7,804 | 5.0
C:\Users\zadanz\Desktop\CrossGen_strawman\After\shared\Microsoft.NETCore.App\3.0.0-preview4-27424-2\System.Collections.Concurrent.dll | 1.7 | 11 | 829 | 4,640 | 1.7

**Comment by merriemcgaw** [comment]
There is no work on WinForms for this issue. @zsd4yr to follow up with @dagood to make sure we're in good shape for Preview 5

**Comment by dagood** [comment]
Completed by https://github.com/dotnet/core-setup/pull/5942. Those changes are being picked by by `master` => `release/3.0` merges for Preview 5. 🎉

**Comment by zsd4yr** [comment]
Amazing @dagood 😄 😃
