### ISSUE TITLE
An error dialog pops up when saving the .NET Framework project that is based on the new SDK style after renaming Form1.cs

### ISSUE THREAD

**Issue by Marie-Shi** [dotnet/winforms#4714]
**Visual Studio Version**:
Version 16.10.0 Preview 2.0 [31122.235.main]

**More info:**
1.	This issue cannot repro without control on form designer.
2.	This issue cannot repro if saved the form designer first, then rename Form1.cs.
3.	This issue cannot repro on .Net Framework and .Net Core project.

**Steps to Reproduce**:
1.	Extract the “WinFormsApp9.zip” and open it in VS.
[WinFormsApp9.zip](https://github.com/dotnet/project-system/files/6188521/WinFormsApp9.zip)
2.	Add a button to the form designer.
3.	Don’t save the project, right click Form1.cs in Solution Explorer, rename it to Form2.cs.
4.	Try to save the project.

**Expected Behavior**:
No error dialog pops up when saving the .NET Framework project that is based on the new SDK style after renaming Form1.cs.

**Actual Behavior**:
An error dialog pops up when saving the .NET Framework project that is based on the new SDK style after renaming Form1.cs.
![Untitled](https://user-images.githubusercontent.com/45864017/112129616-8db1e000-8c02-11eb-8f3e-423d7f23a81d.png)
![12](https://user-images.githubusercontent.com/45864017/112128923-db7a1880-8c01-11eb-8163-647441b8f511.gif)

**Comment by RussKie** [comment]
This has nothing to do with winforms runtime.
Please raise a VS Feedback.
