### ISSUE TITLE
[MDI] Add possibility to align minimized child to default location (TOP LEFT)

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#4720]
**Is your feature request related to a problem? Please describe.**
WinForms [override](https://github.com/dotnet/winforms/blob/61d0963e6578488a9d04aa99f2acb95e0847439a/src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs#L243-L282) standard MDI behavior without option to use original one. It's lead to all child windows layout (with minimized windows) are mess up after main window resize. This can happened after simple resize, or after resolution changed (for example if your connect by rdp from other device), etc...
before res. change (left - WinForms, right - MFC):
![Snipaste_2021-03-24_09-44-51](https://user-images.githubusercontent.com/17767561/112301323-dd4be680-8caa-11eb-803f-6ce5e8ba5413.png)
after  res. change (left - WinForms, right - MFC):
![Snipaste_2021-03-24_09-45-13](https://user-images.githubusercontent.com/17767561/112301308-d91fc900-8caa-11eb-8884-a308e8eadae5.png)

Video:

https://user-images.githubusercontent.com/17767561/112429754-26a14200-8d4e-11eb-83d5-393626ad23b6.mp4

For now we need to manually revert [this move](https://github.com/dotnet/winforms/blob/61d0963e6578488a9d04aa99f2acb95e0847439a/src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs#L243-L282) (with same technique) after each resize :(

<br>

**Draft API Proposal**

  - Will this feature affect UI controls?
  Yes.
  - Will VS Designer need to support the feature? If yes, describe how you expect it to funсtion. 
   Yes - Form will have a new property in PropertyGrid
  - What impact will it have on accessibility?
   No.
  - Will this feature need to be localized or be localizable?
  Yes.

We need to add bool property to `Form` class, let it be `MdiChildrenMinimizedAnchorTop`:
```cs
namespace System.Windows.Forms
{
    public partial class Form : ContainerControl
    {
        /// <summary>
        /// true - anchoring minimized MDI children to the TopLeft of the parent form (windows default). false - anchoring minimized MDI children to the BottomLeft of the parent form (WinForms default)
        /// </summary>
        [SRCategory(nameof(SR.CatWindowStyle))]
        [DefaultValue(false)]
        [SRDescription(nameof(SR.FormMdiChildrenMinimizedAnchorTopDescr))]
        public bool MdiChildrenMinimizedAnchorTop { get; set; }
    }
}
```
**To do.**
1. Discuss a name for the property.
2. Discuss a description for the property. Translations?
3. Category: *Style* or may be *Layout*?
4. Implement trivial logic with this property in `SetBoundsCore` method of `MdiClient` class and do PR.

**Comment by kirsan31** [comment]
Guys, I am bit confused here :thinking:

@RussKie  why this is a **bug**? This is by WinForms [_design_](https://github.com/dotnet/winforms/blob/61d0963e6578488a9d04aa99f2acb95e0847439a/src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs#L250):

> NOTE: This logic is to keep minimized MDI children anchored to the bottom left of the client area, normally they are anchored to the top right which just looks weird!

@dreddy-work And I don't understand how it's related to **HDPI**?

**Comment by dreddy-work** [comment]
> Guys, I am bit confused here 🤔
> 
> @RussKie why this is a **bug**? This is by WinForms [_design_](https://github.com/dotnet/winforms/blob/61d0963e6578488a9d04aa99f2acb95e0847439a/src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs#L250):
> 
> > NOTE: This logic is to keep minimized MDI children anchored to the bottom left of the client area, normally they are anchored to the top right which just looks weird!
> 
> @dreddy-work And I don't understand how it's related to **HDPI**?

From the attached images, we were looking at the nature of minimized MDI windows location being constant after windows resolution that resized Form window to changed resolution/DPI. This is something that need to be handled when DPI changes. Correct us if we are not reading it right.

**Comment by kirsan31** [comment]
@dreddy-work yes you are not reading this right :) This is absolutely not related to HDPI, I don't know how to explain it in more details than I did at [post1](https://github.com/dotnet/winforms/issues/4720#issue-839636272) and [post2](https://github.com/dotnet/winforms/issues/4720#issuecomment-806390543) :(

**Comment by dreddy-work** [comment]
> @dreddy-work yes you are not reading this right :) This is absolutely not related to HDPI. As I wrote, this is WinForms decision - override default anchor (TopLeft) of minimized child mdi windows with (BottomLeft).
> I made a video with difference in WinForms (Bottom-Left anchor) vs MFC (Top-Left anchor):
> 
>  mdi.mp4

Thanks for the GIF.  Earlier images attached were not clear enough to understand the expected behavior around anchoring of minimized MDI windows. Did you try bypassing ‘Setbounds*’ method?

**Comment by kirsan31** [comment]
> Did you try bypassing ‘Setbounds*’ method?

Your mean `SetBoundsCore` of `MDIClient`? If yes, then - no, not directly. We are doing revert move in `OnResize`:
```cs
protected override void OnResize(EventArgs e)
{
    base.OnResize(e);
    if (_OldHeight != -1 && _OldHeight != this.Height)
    {
        int yDelta = _OldHeight - this.Height;
        foreach (var child in ChildrenW)
        {
            if (child.IsHandleCreated && child.WindowState == FormWindowState.Minimized && child.Visible)
            {
                WinApi.User32.GetWindowPlacement(child.Handle, out WinApi.User32.WINDOWPLACEMENT wp);
                wp.ptMinPosition.Y += yDelta;
                wp.flags = WinApi.User32.WPF.SETMINPOSITION;
                WinApi.User32.SetWindowPlacement(child.Handle, ref wp);
            }
        }
    }
    _OldHeight = this.Height;
}
```

And it's work well, except that this is a bit overhead :roll_eyes:
1. System move window to correct place.
2. WinForms move it to wrong place.
3. We move it back to correct place.

**Comment by dreddy-work** [comment]
Yes.  Wanted to check as comments around that code was saying the default behavior was top-right anchored and I observed MFC app was doing top-left.

**Comment by kirsan31** [comment]
> Yes. Wanted to check as comments around that code was saying the default behavior was top-right anchored and I observed MFC app was doing top-left.

Oh I ever didn't notice that :) Yes, It's typo in comment - `Left` everywhere.

**Comment by merriemcgaw** [comment]
I doubt that we can change the default behavior. Perhaps a property that enables the ability to set this. If someone has a proposal for how this might be done we'd be happy to consider it. I'll mark as up for grabs, but move it out to future.

**Comment by kirsan31** [comment]
@merriemcgaw 
> If someone has a proposal for how this might be done we'd be happy to consider it.

The exact proposal  in the first post ;)

**Comment by merriemcgaw** [comment]
We are looking for someone to propose (and implement) an API that would enable this to happen. It has to go through the full API review process, and we can help a bit with that. But it looks like there are more urgent fires to fight for .NET 6 so it doesn't look like we will have the resources to enable this feature just yet. If the community can, that would be something we'd totally take.

**Comment by kirsan31** [comment]
Ok, lets try this slow way.

We need to add `bool` property to `Form` class, let it be `MdiChildrenMinimizedAnchorTop`.


**Draft API Proposal**

```cs
namespace System.Windows.Forms
{
    public partial class Form : ContainerControl
    {
        /// <summary>
        /// true - anchoring minimized MDI children to the TopLeft of the parent form (windows default). false - anchoring minimized MDI children to the BottomLeft of the parent form (WinForms default)
        /// </summary>
        [SRCategory(nameof(SR.CatWindowStyle))]
        [DefaultValue(false)]
        [SRDescription(nameof(SR.FormMdiChildrenMinimizedAnchorTopDescr))]
        public bool MdiChildrenMinimizedAnchorTop { get; set; }
    }
}
```
**To do.**
1. Discuss a name for the property.
2. Discuss a description for the property. Translations?
3. Category: *Style* or may be *Layout*?
4. Implement trivial logic with this property in `SetBoundsCore` method of `MdiClient` class and do PR.

**Comment by merriemcgaw** [comment]
Once we've figured out the name of the property and description (we can get the translations automatically) we may be able to bring this through the API review process. Can you copy the content above to the first comment in the issue? That's what the API folks look for.

**Comment by kirsan31** [comment]
@merriemcgaw 
> Once we've figured out the name of the property and description (we can get the translations automatically) we may be able to bring this through the API review process. Can you copy the content above to the first comment in the issue? That's what the API folks look for.

Done.

**Comment by kirsan31** [comment]
I've created draft PR #5221. May be it's speed up things a bit? :)

**Comment by merriemcgaw** [comment]
@dreddy-work can you start a thread with @terrajobst to get approval for this API change? Let's get that started while @kirsan31 is kindly coding the new API so we know we can get this in .NET 6 for sure

**Comment by dreddy-work** [comment]
Sure.

**Comment by terrajobst** [comment]
Easiest is to file an issue, put in the 6.0.0 milestone, mark it as blocking and api-ready-for-review. We'll look at it first thing Tuesday morning then.

**Comment by terrajobst** [comment]
* It seems beneficial to indicate the Windows Forms behavior instead of describing the Win32 default. This way, should Windows change the behavior we don't have an incorrect description. Hence, the property should flip the default value and describe what Windows Forms does
* Should be in the same property grid category as `MdiChildren`


```C#
namespace System.Windows.Forms
{
    public partial class Form
    {
        [SRCategory(nameof(SR.CatWindowStyle))]
        [DefaultValue(true)]
        [SRDescription(nameof(SR.FormMdiChildrenMinimizedAnchorTopDescr))]
        public bool MdiChildrenMinimizedAnchorBottom { get; set; }
    }
}
```

**Comment by dreddy-work** [comment]
> ```cs
> [SRDescription(nameof(SR.FormMdiChildrenMinimizedAnchorTopDescr))]
> ```
[SRDescription(nameof(SR.FormMdiChildrenMinimizedAnchorBottomDescr))]

> Should be in the same property grid category as MdiChildren

All of them are in CatWindowStyle.

**Comment by Jenna-Zheng** [comment]
Verified this function with .NET SDK 6.0.100-rc.1.21424.1 and .NET SDK 6.0.100-rc.2.21429.3now, it is fixed that Customer can use MdiChildrenMinimizedAnchorBottom to revert for Windows default behavior.
**MdiChildrenMinimizedAnchorBottom=True**
![Issue_Test5 0](https://user-images.githubusercontent.com/64949616/131306160-b81dc820-1bda-4aba-8a9d-534a05e0d6f0.gif)

**MdiChildrenMinimizedAnchorBottom=False**
![Issue_Test](https://user-images.githubusercontent.com/64949616/131306093-753eea61-fe26-41e0-a0bb-72f0310c6414.gif)
