### ISSUE TITLE
Create separate accessibility objects for each ListView view

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4748]
**Problem description:**
The `ListView` is a very complex control with many different behaviors. In the course of working with it, we found more and more criteria that affect his behavior. For example, when displaying `ListViewGroup`, we take into account the following criteria:
- visual styles
- virtual mode
- `ShowGroups` property
- view (we do not show groups for "List" view)

In addition, we found very different behavior of `ListViewSubItems` for different view.
- We do not display `ListViewSubItems` for "List", "SmallIcon", "LargeIcon" views.
- When displaying a `ListView` in "Details" view, the main criterion for us is the number of columns, and not the number of existing `ListViewSubItems` because the user always sees the table on the screen, regardless of whether the `ListViewSubItem` exists or not.
![image](https://user-images.githubusercontent.com/23376742/113119667-60c08700-9219-11eb-8738-c3ff6b52db2f.png)

- For the "Tile" view several criteria are important to us at once, these are the number of `ListViewSubItems`, the number of columns and the size of the item. If the number of columns is less than the number of `ListViewSubItems`, then we will ignore the extra `ListViewSubItems`. If the number of `ListViewSubItems` is less than the number of columns, we also will not display them either or placeholders for them. If the element size is too small, then we will not display `ListViewSubItems` for which there is not enough space to display.
![image](https://user-images.githubusercontent.com/23376742/113120287-1ab7f300-921a-11eb-8a24-cb88da3cb341.png)

As a result, we have a lot of differences for each views. 

**Possible fix:**
Therefore we suggest to create separate accessible objects for each view.

This has several advantages:
- The "List" view has no `ListViewSubItems` and `ListViewGroups`. Therefore, for this mode, we can remove a lot of unnecessary validations and conditions, which optimizes its work. The same applies to "SmallIcon" and "LargeIcon" views, which also do not support `ListViewSubItems`;
- The behavior logic of `ListViewSubItems` for "Tile" and "Details" views is very different, so it is more convenient to have separate accessibility objects that implement their operation, and not a bunch of conditions in one class;
- It will increase the stability of the code. Since I am fixing a bug for one view, we will not worry that the fix may break another view;
- The code will be much clearer and therefore easier to maintain, because the developer sees specific behavior, and not a combination of many conditions;
- It is much easier for us to cover individual classes with tests and, if the behavior is updated, change only the corresponding tests than to update a bunch of tests every time

**Comment by RussKie** [comment]
@merriemcgaw this is an important work, assigning to you for prioritisation.
