### ISSUE TITLE
ToolStripItem.Bounds is not correct for subitems

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/winforms#475]
Mouse over a ToolStripMenuItem
I want to know if the mouse is over any ToolStripMenuItem (in main menu, or context menu, at any level).
I couldn't do it by `GetControlAtPos` method.
I can check if the context menu is visible, then check if the mouse pos is inside the rectangle of one of its items. The problem is that `ToolStripItem.Bounds` property returns the correct rectangle only for the context menu and its direct child items, but the x y pos of the next level is the same as the first level! (try any ContextMenuStrip with items and sub items).

So, Is there a current solution to get the control or menu item under the mouse cursor easily? 
If not, can you solve this in Window Forms Core?
Note that writing handlers to detect mouse hover in each menu items all over the form is not the best solution.

**Comment by merriemcgaw** [comment]
Does this reproduce for you in .NET Framework apps? 

Our current roadmap focuses us on getting to parity with .NET Framework, so we will be doing those types of issues first, but this does look to be an interesting problem.

**Comment by MohammadHamdyGhanem** [comment]
Yes. The image show the case I talk about:
![untitled1](https://user-images.githubusercontent.com/29876310/53271789-2611c980-36f8-11e9-8422-13c7b3e6aed6.jpg)

And these are the tracing data:
Subtitle menu:
Bounds = {X = 0 Y = 2 Width = 385 Height = 40}

Select Current Paragraph:
Bounds = {X = 0 Y = 2 Width = 674 Height = 40}

**Comment by MohammadHamdyGhanem** [comment]
I suggest to add an static method to the ToolStrip class (say "GetMouseOverItem") that returns the ToolStripItem that mouse is directly moving over (that if user  clicks the mouse, this item will receive focus)

**Comment by MohammadHamdyGhanem** [comment]
@merriemcgaw
I wrote the GetMouseOverItem. If there is a direct windows api to do this, it will be better:
```
        public static ToolStripItem GetMouseOverItem(Form frm) =>        
            CheckToolStrip(frm.ContextMenuStrip) ?? 
            CheckToolStrip(frm.MainMenuStrip) ?? 
            CheckControls(frm);
        
        static ToolStripItem CheckControls(Control parent)
        {            
            foreach (Control c in parent.Controls)
            {
                if (c.Visible)
                {
                    var t = CheckToolStrip(c as ToolStrip);
                    if (t != null)
                        return t;

                    t = CheckToolStrip(c.ContextMenuStrip);
                    if (t != null)
                        return t;

                    t = CheckControls(c);
                    if (t != null)
                        return t;
                }
            }

            return null;
        }

        static ToolStripItem CheckToolStrip(ToolStrip m)
        {
            if (m !=null && m.Visible)
            {
                Point p = m.PointToClient(Control.MousePosition);
                foreach (ToolStripItem mi in m.Items)
                {
                    if (mi.Visible)
                    {
                        if (mi.Bounds.Contains(p))
                            return mi;

                        var t = CheckSubItems(mi as ToolStripDropDownItem);
                        if (t != null)
                            return t;
                    }
                }
            }
            return null;
        }

        static ToolStripItem CheckSubItems(ToolStripDropDownItem mi)
        {
            if (mi == null || !mi.Visible)
                return null;

            var p = mi.DropDown.PointToClient(Control.MousePosition);
            foreach (ToolStripItem smi in mi.DropDownItems)
            {
                if (smi.Visible)
                {
                    if (smi.Bounds.Contains(p))
                        return smi;

                    var t = CheckSubItems(smi as ToolStripDropDownItem);
                    if (t != null)
                        return t;
                }
            }

            return null;
        }

```
