### ISSUE TITLE
Native portions of winforms controls are not updating their Font correctly in HDPI scenarios.

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#4762]
* .NET Core Version: 
Net 6.0

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
Some of the native portions in Winforms controls ( ex: Tabtitle in 'TabPage' or 'ColumnHeader' in ListView  or 'ListItem' in ListBox) are not updating their Font when there is a change DPI.

Explicit WM_SETFONT message is not helping update the Font but something between Managed Font and Native Font seems not working as expected. See below example ( in Control class scope).

Snippet 1:

```cs
                IntPtr hwndHdr = User32.SendMessageW(this, (User32.WM)LVM.GETHEADER);
                if (hwndHdr != IntPtr.Zero)
                {                   
                    User32.SendMessageW(new HandleRef(this, hwndHdr), User32.WM.SETFONT, (IntPtr)FontHandle, PARAM.FromBool(false));
                 }
                 var snippet1Font = Font.FromHfont((IntPtr)FontHandle);
```

snippet 2:
```cs
                IntPtr hwndHdr = User32.SendMessageW(this, (User32.WM)LVM.GETHEADER);
                if (hwndHdr != IntPtr.Zero)
                { 
                    var local = Properties.GetObject(s_fontProperty);
                    if (local is null)
                    {
                        Properties.SetObject(s_fontProperty, Font);
                    }                  
                    User32.SendMessageW(new HandleRef(this, hwndHdr), User32.WM.SETFONT, (IntPtr)FontHandle, PARAM.FromBool(false));
                   var snippet2Font = Font.FromHfont((IntPtr)FontHandle);
                 }
```

In both cases, Font from 'Fonthandle' evaluates to same (i.e snippet1Font.equals(snippet2Font)  evaluates to '**true**')

**Expected behavior:**
Result from code snippet 2 above.

**Minimal repro:**

Any windows from app with above listed controls and DPi awareness set to 'PerMonitorV2'. Drag the winforms application from One DPI setting monitor to the other.

![image](https://user-images.githubusercontent.com/36968667/113607096-adcba100-95fd-11eb-9e84-ec6ed5aa6c91.png)

**Comment by Olina-Zhang** [comment]
@dreddy-work  Verified this issue in the latest .Net 7.0 SDK build, it doesn't reproduce now:
100 main screen:
![image](https://user-images.githubusercontent.com/26474449/142993110-b5cac653-dbf1-41f4-8fee-41036b95f0c0.png)
Move to 300% secondary screen:
![image](https://user-images.githubusercontent.com/26474449/142993372-3a62d7ad-f1cd-4db3-a2ca-a6e01901caed.png)

**Comment by dreddy-work** [comment]
@Olina-Zhang , can you try just a list box with multiple entries here? I couldn't repro this either but are there any properties on List box that we could exercise ?

**Comment by Olina-Zhang** [comment]
@dreddy-work verified ListBox with multiple items under 2 modes with AutoScaleMode = Font, Dpi, the result is different when moving form from 100% main screen to 300% secondary screen: the displayed items are different.

100% main screen for 2 modes with AutoScaleMode = Font, Dpi, the results are same:
![image](https://user-images.githubusercontent.com/26474449/143366585-8799336d-0e5a-4a27-9ed3-65cad3f5d8a9.png)

Move to 300% secondary screen with AutoScaleMode = Font (by default value), scaled well:
![image](https://user-images.githubusercontent.com/26474449/143366717-f68d42c4-1b0c-4431-b731-8b89fd1d4635.png)

Move to 300% secondary screen with AutoScaleMode = Dpi
![image](https://user-images.githubusercontent.com/26474449/143367582-30ad9bd8-1c4a-4ff0-be4f-d8e245c9fcee.png)
