### ISSUE TITLE
Error NU1605 trying to build Winforms.sln

### ISSUE THREAD

**Issue by JoeErickson** [dotnet/winforms#477]
* .NET Core Version: 
  3.0.100-preview3-010283 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-010480 [C:\Program Files\dotnet\sdk]

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

After forking dotnet/winforms master Winforms.sln does not build - there are 64 cases of errors like this:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Microsoft.NETCore.Platforms from 3.0.0-preview4.19118.6 to 3.0.0-preview3.19115.9. Reference the package directly from the project to select a different version. 
 System.Windows.Forms -> System.Drawing.Common 4.6.0-preview4.19118.6 -> Microsoft.NETCore.Platforms (>= 3.0.0-preview4.19118.6) 
 System.Windows.Forms -> Microsoft.NETCore.Platforms (>= 3.0.0-preview3.19115.9)	System.Windows.Forms.Ref	C:\Users\JoeErickson\source\repos\winforms\src\System.Windows.Forms\ref\System.Windows.Forms.Ref.csproj	1	
```

This has been an ongoing problem for a while. The workaround has been to change the ~15 C# projects to not treat NU1605 as an error.

NU1605 is explicitly set to be treated as an error in all C# projects in Winforms.sln and this makes good sense but I cannot figure out how to get the correct build of .NET Core 3. Neither the daily build nor the current Preview 3 release works. This problem has persisted for at least several weeks.

**Minimal repro:**
1) Install latest Visual Studio 2019 Preview 3 and .NET Core 3 (Preview 3 or daily build).
2) Fork and clone dotnet/winforms master.
3) Load Winforms.sln into VS 2019.
4) Try to build.

**Comment by merriemcgaw** [comment]
@zsd4yr Can you take a look at this?

**Comment by zsd4yr** [comment]
> NU1605 is explicitly set to be treated as an error in all C# projects in Winforms.sln

@JoeErickson where are you seeing that setting? Thank you for pointing this out

**Comment by zsd4yr** [comment]
@ericstj Do you have any ideas here? Honestly the package version number stuff is a bit beyond me

**Comment by ericstj** [comment]
Don't suppress nu1605: package downgrades are bad.

Looks to be a side-effect of https://github.com/dotnet/sdk/blob/0690b28e426f5b7e6dfe7ab4200b83ce3c96bc95/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props#L81-L87. /cc @dsplaisted 

The SDK you're building with is adding a reference to *it's* version of MS.NC.Platforms which is lagging behind the version that WinForms gets from the CoreFx packages.

You should be able to workaround it by updating the reference added by the SDK (looks like they don't have a great hook for defining it).

So add Microsoft.NETCore.Platforms to the list of packages you get from darc (versions.props), then put something like the following in your root Directory.Build.targets:

```xml
  <ItemGroup>
    <PackageReference Update="Microsoft.NETCore.Platforms" Version="$(MicrosoftNETCorePlatformsPackageVersion)" />
  </ItemGroup>
```

**Comment by JoeErickson** [comment]
> where are you seeing that setting? Thank you for pointing this out

@zsd4yr Open Winforms.sln In VS 2019. In Solution Explorer, right click on a project such as src -> System.Windows.Forms and choose Properties, click on the Build tab, under "Treat warnings as errors" you will see "Specific warnings: NU1605".

I'll be happy to try it out if you make the changes suggested by Eric. Just let me know what branch to clone.

**Comment by zsd4yr** [comment]
Ah @JoeErickson looks like I beat you to it; raceconditions -- please check out the PR tho

**Comment by RussKie** [comment]
I struggled with the same error for the past week, I installed and reinstalled .NET Core 3.0 SDK (SDK 3.0.100-preview-010184) and VS 2019 few times. I was getting to the point of raising the issue myself.

The last thing I installed was CMake (cmake-3.14.0-rc2-win64-x64) and then all of a sudden I was able to build the project in VS.

I somewhat suspect it had nothing to do with CMake, but I struggle to pinpoint what the problem may have been.... 🤷‍♂️

**Comment by zsd4yr** [comment]
@RussKie and @JoeErickson if you guys wouldn't mind, if a few days (once change #497 has had time to propogate to core-sdk), would you mind updating this thread with any struggles you're having related to this?

**Comment by JoeErickson** [comment]
@zsd4yr Will do

**Comment by RussKie** [comment]
Sure thing.

**Comment by RussKie** [comment]
I have checked out the latest master and now I can't compile...

Attempting to compile I get a bunch of errors:
```
Build with surface heuristics started at 17:49:41
Use build tool: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe
0>------- Project started: InternalUtilitiesForTests
1>------- Project started: System.Windows.Forms
2>------- Project started: System.Windows.Forms.Ref
0>C:\Development\winforms\artifacts\obj\InternalUtilitiesForTests\Debug\netcoreapp3.0\InternalUtilitiesForTests.AssemblyInfo.cs(14,12): Error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
0>C:\Development\winforms\artifacts\obj\InternalUtilitiesForTests\Debug\netcoreapp3.0\InternalUtilitiesForTests.AssemblyInfo.cs(15,12): Error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
0>C:\Development\winforms\artifacts\obj\InternalUtilitiesForTests\Debug\netcoreapp3.0\InternalUtilitiesForTests.AssemblyInfo.cs(18,12): Error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
0>C:\Development\winforms\artifacts\obj\InternalUtilitiesForTests\Debug\netcoreapp3.0\InternalUtilitiesForTests.AssemblyInfo.cs(19,12): Error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
0>C:\Development\winforms\artifacts\obj\InternalUtilitiesForTests\Debug\netcoreapp3.0\InternalUtilitiesForTests.AssemblyInfo.cs(20,12): Error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
0>C:\Development\winforms\artifacts\obj\InternalUtilitiesForTests\Debug\netcoreapp3.0\InternalUtilitiesForTests.AssemblyInfo.cs(21,12): Error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
0>C:\Development\winforms\artifacts\obj\InternalUtilitiesForTests\Debug\netcoreapp3.0\InternalUtilitiesForTests.AssemblyInfo.cs(22,12): Error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute
0>------- Project finished: InternalUtilitiesForTests. Succeeded: False. Errors: 7. Warnings: 0
2>C:\Development\winforms\artifacts\obj\System.Windows.Forms.Ref\Debug\netcoreapp3.0\System.Windows.Forms.Ref.AssemblyInfo.cs(14,12): Error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
2>C:\Development\winforms\artifacts\obj\System.Windows.Forms.Ref\Debug\netcoreapp3.0\System.Windows.Forms.Ref.AssemblyInfo.cs(15,12): Error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
2>C:\Development\winforms\artifacts\obj\System.Windows.Forms.Ref\Debug\netcoreapp3.0\System.Windows.Forms.Ref.AssemblyInfo.cs(18,12): Error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
2>C:\Development\winforms\artifacts\obj\System.Windows.Forms.Ref\Debug\netcoreapp3.0\System.Windows.Forms.Ref.AssemblyInfo.cs(19,12): Error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
2>C:\Development\winforms\artifacts\obj\System.Windows.Forms.Ref\Debug\netcoreapp3.0\System.Windows.Forms.Ref.AssemblyInfo.cs(20,12): Error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
2>C:\Development\winforms\artifacts\obj\System.Windows.Forms.Ref\Debug\netcoreapp3.0\System.Windows.Forms.Ref.AssemblyInfo.cs(21,12): Error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
2>C:\Development\winforms\artifacts\obj\System.Windows.Forms.Ref\Debug\netcoreapp3.0\System.Windows.Forms.Ref.AssemblyInfo.cs(22,12): Error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute
2>------- Project finished: System.Windows.Forms.Ref. Succeeded: False. Errors: 7. Warnings: 0
1>------- Project finished: System.Windows.Forms. Succeeded: True. Errors: 0. Warnings: 0
3>------- Project started: WinformsControlsTest
4>------- Project started: System.Windows.Forms.IntegrationTests
5>------- Project started: System.Windows.Forms.Design.Editors
6>------- Project started: System.Windows.Forms.Design
4>------- Project finished: System.Windows.Forms.IntegrationTests. Succeeded: True. Errors: 0. Warnings: 0
5>------- Project finished: System.Windows.Forms.Design.Editors. Succeeded: True. Errors: 0. Warnings: 0
7>------- Project started: System.Windows.Forms.Design.Editors.Tests
7>------- Project finished: System.Windows.Forms.Design.Editors.Tests. Succeeded: True. Errors: 0. Warnings: 0
3>------- Project finished: WinformsControlsTest. Succeeded: True. Errors: 0. Warnings: 0
6>------- Project finished: System.Windows.Forms.Design. Succeeded: True. Errors: 0. Warnings: 0
Build completed in 00:00:27.495
```

I also get the following warning:
![image](https://user-images.githubusercontent.com/4403806/53392916-fc55ec80-39ee-11e9-9434-403845a505ae.png)
