### ISSUE TITLE
.NET 5.0 is not rendering WinForms created in the .NET Framework 4.8 correctly

### ISSUE THREAD

**Issue by luronumen** [dotnet/winforms#4774]
* .NET Core Version: **.NET 5.0**

* Have you experienced this same bug with .NET Framework?: **No**

**Problem description:**
.NET 5.0 is not rendering WinForms created in the .NET Framework 4.8 correctly:

![ISSUE](https://user-images.githubusercontent.com/8019466/114283721-8cb1e880-9a21-11eb-89f8-3faac20bd390.png)

**Expected behavior:** .NET 5.0 should render WinForms created in .NET Framework 4.8 with the same dimensions

**Step to reproduce this issue:** Copy a WinForm created in .NET Framework 4.8 (See: [LoginForm.zip](https://github.com/dotnet/winforms/files/6290700/LoginForm.zip)) to a .NET 5.0 project and check how this WinForm is rendered.

**Minimal repro:** 100%

**Comment by luronumen** [comment]
I found an alternative way to manual fix this issue:
- Go to *LoginForm.resx* file and set *$this.AutoScaleDimensions* to **7, 15** instead of _6, 13_;
- Unlock/Lock the _LoginForm_ for all languages (e.g.: Default and Portuguese) to the _LoginForm.pt.resx_ and _LoginForm.resx_ be updated to the _.NET 5.0_ format;
    - Open _LoginForm.pt.resx_ and replace all _Version=4.0.0.0_ by **Version=5.0.0.0**;

**Comment by kirsan31** [comment]
https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core#default-control-font-changed-to-segoe-ui-9-pt

**Comment by luronumen** [comment]
> https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core#default-control-font-changed-to-segoe-ui-9-pt

Thanks @kirsan31

**Comment by luronumen** [comment]
HOW TO PORT A .NET FRAMEWORK WINFORM TO .NET 5.0
- Added **Font = new System.Drawing.Font(new System.Drawing.FontFamily("Microsoft Sans Serif"), 8f);** at the form constructor after _InitializeComponent();_;

HOW TO PORT A .NET FRAMEWORK WINFORM RESOURCES FILES TO .NET 5.0
- Go to _Form.resx_ file and set **$this.AutoScaleDimensions** to **7, 15**;
- Unlock/Lock the Form for all languages (e.g.: Default and Portuguese) to the _Form.pt.resx_ and _Form.resx_ be updated to the .NET 5.0 format;
- Open _Form.pt.resx_ and replace Version=4.0.0.0 by **Version=5.0.0.0**;

**Comment by AraHaan** [comment]
And what if the form is windows only and is set to be ``Localizable``?

**Comment by luronumen** [comment]
Hi @AraHaan 

It doesn't matter if the form language property is set to True or False: The issue is reproducible in both scenarios and all languages when it set to True.

Best Regards,
Luciano

**Comment by luronumen** [comment]
Hi @kirsan31 @AraHaan and @RussKie 

Look at this example from another form in the same application.
I will have to review all forms if I really want to port this application to .NET 5.0 :(

### .NET Framework 4.8
![NET48](https://user-images.githubusercontent.com/8019466/115162008-4b4fb780-a077-11eb-8e3d-f1874e898c62.png)

### .NET 5.0
![NET50](https://user-images.githubusercontent.com/8019466/115162011-4db21180-a077-11eb-902f-b1fa60cda65f.png)

**Comment by AraHaan** [comment]
I get the same issues from one of my older projects, but it seems to happen on the System.Drawing side for me since I use System.Drawing to try to draw my own ``pseudo`` window frame (which looks ok on framework, on core it's ok until I open a form with a wider width.

I think it's due to some bug on my part.

**Comment by luronumen** [comment]
After this [Visual Studio 2019 v16.10 - WinForms Updates](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-10-and-v16-11-preview-1-are-available-today/#winforms-updates) here are the instruction for porting a .NET Framework form to the .NET 5.0:

HOW TO PORT A WINFORM FROM THE .NET FRAMEWORK TO .NET 5.0 INCLUDING ITS RESOURCE FILES
- Set the form font to "Microsoft Sans Serif 8 pt" (See: https://docs.microsoft.com/en-us/dotnet/core/compatibility/fx-core#default-control-font-changed-to-segoe-ui-9-pt);
- Unlock/Lock the form for all languages (e.g.: Default and Portuguese) to the "Form.pt.resx" and "Form.resx" be updated to the .NET 5.0 format;

**Comment by luronumen** [comment]
From **.NET 6** it will be possible to define a default font for the application: [Windows Forms: default font](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-5/#windows-forms-default-font)

**Comment by AraHaan** [comment]
with that default font, what if that form is localized with it? Would you have to manually delete each entry with the same font entry used in the resx file?

**Comment by RussKie** [comment]
The primary goal for the `SetDefaultFont` API is to enable migrations of existing projects from .NET Framework. The .NET Framework's default font is Microsoft Serif, 8.25f, so even if it is serialized into resources, with having `SetDefaultFont("Microsoft Serif", 8.25f)` the app will continue to render as previously.

If you're thinking of redesigning existing apps into the new font - then, yes, you will need to redo each form and update resx.
