### ISSUE TITLE
[CI Tests] ConvertManagedToNative_Bitmap fails with System.Runtime.InteropServices.COMException.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/winforms#4775]
* .NET Core Version: 

.NET 6.

* Have you experienced this same bug with .NET Framework?: 

No

**Problem description:**

The test can fail and block clean CI on Windows x86 Release mode, for some reason it works in debug mode and not sure why that is. The Test started to fail on (that I know of) https://github.com/dotnet/winforms/pull/4746/commits/dce8d8ff62676c8151f2a6ffbb91e09e71860e4e. 

**Expected behavior:**
The test to not fail and pass CI.

**Minimal repro:**
https://github.com/dotnet/winforms/pull/4746/checks?check_run_id=2315016683

I am filing this in case of test regression.

**Comment by RussKie** [comment]
Thank you. This is a "general" flakiness of CI runs on the public build infra. Unfortunately the successful re-run of the build has rewritten the logs, making it impossible to get more information at this stage.
I'll re-open if this test becomes generally unstable.
