### ISSUE TITLE
Empty ListViewGroups are displayed in the Inspect tree

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4779]
.NET Core Version:
- 6.0.100-preview.2.21155.3

Have you experienced this same bug with .NET Framework?:
- No (regression from #3224)
 
**Minimal repro:**

1. Create an app with a ListView
2. Add several ListViewGroup to the ListView
3. Add ListViewItem related to the first group to the ListView
4. Run the application
5. Run the Inspect

**Actual behavior**
Invisible (empty) ListViewGroups are displayed in the Inspect tree
![Issue-4779-actual](https://user-images.githubusercontent.com/23376742/114397233-1f2fc480-9ba7-11eb-840e-113328d9cead.png)

**Expected behavior**
Invisible (empty) ListViewGroups should not be displayed in the Inspect tree
![Issue-4779-expected](https://user-images.githubusercontent.com/23376742/114397246-23f47880-9ba7-11eb-8daf-641f3a7227dd.png)

**Comment by Ashley-Li** [comment]
Verified in the latest .NET 6.0 P4 build: 6.0.100-preview.4.21224.2, the issue has been fixed that invisible (empty) ListViewGroups cannot be displayed in the Inspect tree. Please see below result:
![image](https://user-images.githubusercontent.com/56664234/116019607-713a0680-a5f9-11eb-9a28-b480b78ef1a7.png)
