### ISSUE TITLE
WinForms designer emits broken code in multi-targeted projects

### ISSUE THREAD

**Issue by PhilPJL** [dotnet/winforms#4780]
VS 16.9, 16.10

**Summary**:

[See initial post here](https://developercommunity.visualstudio.com/t/Winforms-designer-issue-with-ISupportIni/1392601?port=1025&fsid=da8f689d-711c-4ea9-bb1e-6825f9253bbe&entry=suggestion&space=8&scope=follow?port=1025&fsid=da8f689d-711c-4ea9-bb1e-6825f9253bbe&entry=suggestion&space=8&scope=follow&moreInfo=true&viewtype=all)

It's possible to create code which compiles, but then fails at runtime depending on which framework you edit a Form with in the designer.

**Steps to Reproduce**:

1. Create a simple WinForms app targeting .NET 5.
2. Update the project file to support multi-targeting .NET 3.5 and 4.7.2.  
3. Add a Split Container control to the form with the environment set to .NET5 or 4.72.
You will see the designer.cs contains statements like
            `((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();`
4. Remove all unused 'using' statements so that the app will build on .NET 3.5 and 4.7.2
5. Modify Main to
```       
        static void Main()
        {
#if NET5_0_OR_GREATER
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
#endif
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }
```
6. Run the app in environment .NET5 / 4.7.2 - works fine
7. Run the app in environment .NET35 - crashes
![image](https://user-images.githubusercontent.com/271656/114391882-f223e780-9b8f-11eb-9ea7-f00eb11d9896.png)

**Expected Behavior**:
Not to crash.

The entire Designer.cs is rewritten every time a change is made.  The problem is it's rewritten for the specific environment you're currently targeting in the designer.  The designer needs to emit conditional compilation statements and make best efforts to satisfy all targeted  environments. e.g.  for ISupportInitialize we should have
```
#if NET40_OR_GREATER
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
#endif
```
Similarly for any other platform specific code.

**Actual Behavior**:
Crash.

**Comment by Zheng-Li01** [comment]
There have more details for the issue.

**For Core**
VS crashed after targeting to 3.5, and VS working well after comment the below code section, however the below code appeared again after modify the Form1.cs[design], such as re-sized it.
`((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();`
![Core](https://user-images.githubusercontent.com/38325459/114489122-2dccb900-9c45-11eb-82ac-f7dd1fbaab5f.gif)

**For Framework**
VS crashed after targeting to 3.5, and VS working well after comment the below code section, the comment code disappeared after after modify the Form1.cs[design], such as re-sized it. this is different between .NET Core and .NET Framework.
`((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();`
![Framework](https://user-images.githubusercontent.com/38325459/114489282-771d0880-9c45-11eb-88c2-ca767310b330.gif)

**Comment by RussKie** [comment]
Can you please tell us more about your scenario, and why you're targeting 3.5? This could help us better prioritise this work.

As a workaround you could duplicate the designer file and conditionally include it in the build based on the TFM you're targeting.

**Comment by PhilPJL** [comment]
Hi. I was trying to update Unity Mod Manager to use the modern project format (see above) and hit this issue. The author of UMM wants to maintain compatibility with net35. I would happily drop it but it's not my call.  This does highlight the fact that if the designer code differs between TFMs for this or any other reason you can end up with code that could but doesn't run or other issues. I guess the same will be true of WPF and other designers. It's something you need to find a solution for.

**Comment by RussKie** [comment]
To confirm I understand the context correctly - the issue is a result of you switching to the SDK-style projects and multi-targeting, and not so much targeting .NET 5.0?

Whilst the idea of multi-targeting is very enticing, you need to fully embrace the risks and challenges it carries, especially so when targeting vastly different framework versions, such as .NET Framework 3.5, .NET Framework 4x and .NET. There has been a multitude of significant changes between these versions in terms of API surface and behaviours, and some things may outright not work (e.g. throw by design). You will also find that resources may no longer be compatible between these versions making it impossible to use the designer.

We've taken a note of your request, but I'm afraid this isn't something we action in observable future.

**Comment by PhilPJL** [comment]
Yes.  Nothing to do with .NET 5.  Everything to do with you support multi-targeting, but it doesn't work.  
In general I have the option of conditional compilation, and conditional MS Build config to handle different TFMs.  However in this particular case the designer will overwrite any conditional statements I manually insert to fix the issue.  That's the core of the problem. I understand it's a difficult problem to fix.   I also realise that .NET 3.5 is almost deprecated, but I think this issue will occur at some point for .NET 4/5/6 etc so needs addressing.

**Comment by merriemcgaw** [comment]
This is behaving as I would consider by-design. The designer itself can only generate code (and display to the developer) for a single runtime at a time. There are a couple of options for working through this issue. One is to always place the oldest framework version as the first one listed in the TargetFrameworks. This will only generate code that is supported by all versions listed - though the limitation there is that you won't be working with the look/feel of the more modern version and you will not have access to code that doesn't work for every framework on the list (like new properties and controls for example). Workarounds could include putting all of the setting that you want conditionally compile in a separate method from InitializeComponent. That does mean that designing will be a bit more difficult, but conditional compiling will be supported. Unfortunately the versions do diverge in some cases to a degree that you can't easily multi-target.

**Comment by PhilPJL** [comment]
Depends what you consider as by design I suppose.
VS is advertising that it supports multi-targeting but clearly the designers don't and you're implying they won't.
Instead of just closing this which is a cop out you should at least

- Make it clear in the documentation that it's not supported
- Change the designer UI to indicate to, or force the user to use the lowest/oldest framework, or at least warn if not doing that.
