### ISSUE TITLE
Trouble with custom CodeDomSerializer on .NET v5 Winforms

### ISSUE THREAD

**Issue by Atma9** [dotnet/winforms#4790]
Dear All, 

We have trouble debugging custom CodeDomSerializer on .NET v5 Winforms. When the form loads, the components, which are marked with an attribute to use a custom CodeDomSerializer, are simply deleted from the form without any error message. 

The custom serializer works with .NET Framework v2 to 4.8, but fails with .NET Core from v5 and newer (including v6). 

The main problem is that we cant debug in to the C# code used by VS.IDE to serialize/deserialize.

The best what we found on internet to debug custom CodeDomSerializers is here:
https://stackoverflow.com/questions/47290751/serialization-with-codedomserializer-how-to-initialize-manager-object

But no method is known, how to do this for .NET Core Winforms components. 

Minimal repro:
Please provide a method how to debug custom CodeDomSerializers in Visual Studio .NET IDE. 

Thanks!
Atmapuri

**Comment by dang-gun** [comment]
I have the same problem.
I just followed the example.( 
https://docs.microsoft.com/ko-kr/dotnet/api/system.componentmodel.design.serialization.codedomserializer?view=net-5.0 )

An error occurs.
![CodeDomSerializer_001](https://user-images.githubusercontent.com/22692763/120542865-9145bc80-c426-11eb-8b13-5db347e3175b.png)

**Comment by RussKie** [comment]
Can you provide us with a sample repro? Then we may be able to provide you with some guidance.

**Comment by Atma9** [comment]
Dear RussKie,

The main subject of this report is about:
Please provide a method how to debug custom CodeDomSerializers in Visual Studio .NET IDE for .NET Core. 

How does a sample repro look for this? If I knew how to write one, I would be able to solve the problem myself.
Are there no examples on the internet how it is possible to step in to the code of custom CodeDomSerializer? I could not find any. 

Here it is describes, what code needs to be written:

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.design.serialization.codedomserializer?view=net-5.0

But no word how you can debug this considering that it is the IDE which is using this assembly and need to debug a plug-in like class. 

Thanks!
Atmapuri

**Comment by weltkante** [comment]
There currently is no documentation on authoring design time (including serialization) for custom controls, it is to be expected that no examples exists. They are still working on adding support for that.

**Comment by Atma9** [comment]
The related classes are all marked as implemented and as if working for .NET 5.0 including code examples (which compile):
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.design.serialization.codedomserializer?view=net-5.0

But no example, how to debug in case of a problem.

**Comment by dreddy-work** [comment]
.Net core designer is still preview and Control vendors with NDA has access to internal repo.  Core designer run out of proc with  process name "DesignToolsServer.exe". We do publish SDK to a public [feed](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-tools&package=Microsoft.WinForms.Designer.SDK&version=1.0.0-prerelease-preview1.21307.3&protocolType=NuGet) though. If you could install it and attach VS and designer process "DesignToolsServer.exe", you might be able to get a call stack if the failure/exceptions thrown.

**Comment by Atma9** [comment]
Dear Devendar,

Thank you for this info. Is there some indication within VS.IDE, that shows, if the Winforms .NET Core designer is preview or release? How will we know when the release happens?

>.Net core designer is still preview and Control vendors with NDA has access to internal repo.

We are also control vendor for some 20 years. How could we apply for access?

Thanks!
Atmapuri

**Comment by dreddy-work** [comment]
> We are also control vendor for some 20 years. How could we apply for access?

@OliaG would be able to help you on this and they are notified about your request.

**Comment by OliaG** [comment]
@Atma9 , could you please send me email with the name of your company to oliag@microsoft.com so I can see how I can help you with the access.

**Comment by dang-gun** [comment]
The sample doesn't work here.
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.design.serialization.codedomserializer?view=net-5.0
![image](https://user-images.githubusercontent.com/22692763/121434194-edc15280-c9b7-11eb-9e8a-759a147af3eb.png)


source code : https://github.com/dang-gun/ResourceWriterTest
I may have misunderstood the sample code.
Please let me know if there are any mistakes.

**Comment by frrd55l** [comment]
I have the same issue as dang-gun, but i'm trying to use https://github.com/PaulaScholz/WindowsFormsDataVisualization.
![image](https://user-images.githubusercontent.com/17738054/140290195-5c83015a-fb7d-4232-808b-002494ad4255.png)

**Comment by merriemcgaw** [comment]
Hi @frrd55l we currently only have runtime support for the Chart Control, we do not have the VS Control Designer created for the Chart Control. We created that repo in order to help people who were porting from .NET Framework and need to have access to the chart control but have generally already gotten it configured. The recommendation is that whatever code you might have had generated in InitializeComponent in the .NET Framework project be copied over to something like Form Load or similar. Without the Designer support in VS you can only configure programmatically and it can't be in InitializeComponent.

**Comment by Atma9** [comment]
Dear Merrie, Considering that it takes so much time to implement support of VS Control Designer for .NET Core, is it possible to share, if this is something that is actually planned to be implemented? Is this 1 year, 2year in to the future? .NET Core works great, as long as the winforms designer and related api is not used. We would appreciate very much a project with example, how to debug winforms related designer code for .NET Core.

**Comment by kirsan31** [comment]
@Atma9 latest available info on this is [here](https://github.com/dotnet/winforms/discussions/5220).
@frrd55l and [this part](https://github.com/dotnet/winforms/discussions/5220#discussioncomment-982604) is about chart control.

**Comment by Atma9** [comment]
After the introduction of VS 2022, there are no obvious improvements for the Win-forms designers for .NET Core. Roughly the same issues persist as one year ago. However we did seem to manage to find one (reproducible) bug:

[Browsable(false)]

does not hide the property from being serialized. This makes no sense. Why would you want to prevent browsing of property from the VS.IDE, but at the same serialize its value (which will always be default, because it cannot be changed). When declaring [Browsable(false)], the following needs to be included additionally for .NET Core:

[DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]

But this could be implicit, because it does not match behavior for .NET Framework. If this attribute is not specified, there can be issues with attempts to serialize (public) delegates and other non-serializable stuff.

**Comment by RussKie** [comment]
> After the introduction of VS 2022, there are no obvious improvements for the Win-forms designers for .NET Core. Roughly the same issues persist as one year ago. However we did seem to manage to find one (reproducible) bug:
> 
> [Browsable(false)]
> 
> does not hide the property from being serialized. This makes no sense. Why would you want to prevent browsing of property from the VS.IDE, but at the same serialize its value (which will always be default, because it cannot be changed). When declaring [Browsable(false)], the following needs to be included additionally for .NET Core:
> 
> [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
> 
> But this could be implicit, because it does not match behavior for .NET Framework. If this attribute is not specified, there can be issues with IDE attempting to serialize (public) delegates and other non-serializable stuff.

This is an existing behaviour in .NET Framework designer as well.
![image](https://user-images.githubusercontent.com/4403806/149880348-05708ed7-8f6a-47cd-bcdf-9315ec8e8878.png)

If you search through the code you'll see that these attributes are often come together.

**Comment by Atma9** [comment]
Indeed you are correct. I was just surprised (probably again).  Even in your example, what is the purpose to initialize the property with 0, even though we know it is already zero?

**Comment by weltkante** [comment]
> Even in your example, what is the purpose to initialize the property with 0, even though we know it is already zero?

You don't know its zero though. There's no `DefaultValue` attribute which would signal the default value to the designer. The zero could be a "dynamic default value" which depends on context.

> Why would you want to prevent browsing of property from the VS.IDE, but at the same serialize its value (which will always be default, because it cannot be changed).

To store dependant data which is indirectly edited through the property grid.

In summary, there are all necessary attributes available to control exact behavior in Desktop Framework. I don't know if or how much .NET Core deviates from Desktop Framework semantics since designer support for custom controls isn't supported/documented yet as far as I know (apologies if I missed the announcement).

From my point of view the ideal situation would be matching the semantics of Desktop Framework, not reinterpreting or redefining it, but I have no idea where this is going currently, so I'm mostly waiting to see what we'll be given once its supported.

**Comment by RussKie** [comment]
Custom CodeDOM serializers no longer work the same way in the .NET designer, which is run out-of-proc, as they used to in the .NET Framework designer (which is in-proc). You can get more context about inproc/out-of-proc in this blog post: https://devblogs.microsoft.com/dotnet/state-of-the-windows-forms-designer-for-net-applications/.

Custom CodeDOM serializers will need to specially authored and packaged to be available in the OOP designer. @KlausLoeffelmann is currently working on the docs and samples, and we will announce those as soon as they are available.
