### ISSUE TITLE
Some events never called in WinForms dialog when overriding Form methods and not calling base

### ISSUE THREAD

**Issue by Hefaistos68** [dotnet/winforms#4791]
* .NET Core Version: 
.NET SDK (reflecting any global.json):  Version:   5.0.201 Commit:    a09bd5c86c
Runtime Environment: Windows  10.0.19042 win10-x64
Host (useful for support):  Version: 5.0.4  Commit:  f27d337295
.NET SDKs installed:  3.0.101, 3.1.407, 5.0.103, 5.0.104, 5.0.200-preview.21077.7, 5.0.201

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
When overriding for example the `OnLoad `method, but not calling the `base.OnLoad() `method, neither the Load event nor the Shown event is raised. Probably some other events neither. This behavior is not transparent and is not explained in the documentation. Although documentation states: _When overriding OnLoad(EventArgs) in a derived class, be sure to call the base class's OnLoad(EventArgs) method so that registered delegates receive the event._ there is no indication that this may also affect other events not being raised.

**Expected behavior:**
Framework should call the virtual OnLoad() method and then raise the events as expected.

**Minimal repro:**
Create a basic winforms project, override OnLoad() in the Form1 class, remove the call to base.OnLoad() in the generated method, add handlers for the Load and Show events. Those handlers never get called.

**Comment by Hefaistos68** [comment]
I know this opens 3 cans of nasty worms and may break existing code. So at least a documentation fix would be in order, documenting method / event hierarchies, so one can determine which events will or will not be called depending on which base method is called or not.

**Comment by RussKie** [comment]
This is an existing behaviour since day one (which a long time ago), so we can't change for obvious reasons.

If you feel some documentation is lacking it would be appreciated if you could help us make it better by clicking [Edit] button found on each doc page in the top right corner.

Thank you
