### ISSUE TITLE
Deal with globally suppressed warnings (618 and 649) from System.Windows.Forms code

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#48]
618: use of obsolete code.  Used probably because of legacy code, but globally surpressing the warning turns it off for new code too. Hence check if the code can be modified to avoid them. If not then add #pragmas instead of globally suppressing this warning.

649: field is never assigned.  We should not ignore this warning except in the rare cases when we need to preserve an unused field for back-compat (eg: serialization).  Recommend replace with pragma.

**Comment by kevingosse** [comment]
There are two places with unused fields:

- https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs#L37
- https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs#L45

In both cases, they are instances of TraceSwitch used through the file in `Debug.WriteLine` statements. There's quite a few of them, so I think surrounding all of them with `#if DEBUG` would just add useless clutter to the file.

I can think of three solutions:
 - Ignore those two warnings with #pragma 
 - Add an indirection to limit the number of `#if DEBUG` to just one. Something like:
```
[Conditional("DEBUG")]
private static void Trace(string message)
{
	#if DEBUG
		Debug.WriteLineIf(WndProcChoice.TraceVerbose, message);
	#endif
}
```
 - Remove all the `Debug.WriteLineIf` in those two files

**Comment by zsd4yr** [comment]
I prefer indirection, but others may feel differently. 😉

**Comment by kevingosse** [comment]
I'm at loss about what to do for MarshalAs.SafeArray (used for instance here: https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/UnsafeNativeMethods.cs#L2399)
According to the API, we are indeed expected to use a SAFEARRAY: https://msdn.microsoft.com/en-us/windows/ms536782(v=vs.71)
But the attribute is marked as obsolete in .net core, with the message "Marshalling as SafeArray may be unavailable in future releases"  https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L963 (note, it's the same thing for IDispatch)
I'm not sure what we're supposed to do, or the rationale behind obsoleting it. Note that it still works without the `MarshalAs` attribute, I don't know if C arrays are binary compatible with SAFEARRAY or if the marshaller is smart enough to figure out what we need here.

**Comment by zsd4yr** [comment]
Maybe @dreddy-work and @Shyam-Gupta can advise?

**Comment by zsd4yr** [comment]
Looks like only CS0618 is remaining?

**Comment by kevingosse** [comment]
Yes. I can't make progress on it without some expertise on the marshaling part :/

**Comment by dreddy-work** [comment]
I do not have a complete knowledge why it was made obsolete in core. However, Safe/unsafeNative methods along with couple of other common classes are expected to be moved to a new dll that will be referenced instead. I would keep this issue on hold until that is done.

**Comment by Wraith2** [comment]
I think you need @AaronRobinsonMSFT or @jkoritzinsky who are the area owners on that. There's at least one place in corefx that the obsolete on Sarearray has been removed so this one may also be possible to remove.

**Comment by RussKie** [comment]
> But the attribute is marked as obsolete in .net core, with the message "Marshalling as SafeArray may be unavailable in future releases" [dotnet/corefx:src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs@`master`#L963](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L963) [](/dotnet/corefx/blob/HEAD@{2018-12-10T20:37:14Z}/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L963) (note, it's the same thing for IDispatch)

For the general interest, these type are (no longer) marked as obsolete in .NET Core v3-P9.
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L958-L964
