### ISSUE TITLE
WindowsFormsApplicationBase does not raise StartupNextInstance if MainForm is null (it does in Framework)

### ISSUE THREAD

**Issue by AlexVallat** [dotnet/winforms#4805]
* .NET Core Version: found in 5, still present in code in current main branch

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
WindowsFormsApplicationBase.StartupNextInstance event is not raised if MainForm is null.

**Expected behavior:**
StartupNextInstance event is raised. This was the behaviour in .NET Framework

**Minimal repro:**
Create an WindowsFormsApplicationBase, and set IsSingleInstance to true. Do not assign a MainForm, just Application.Run an ApplicationContext. Add an event handler to StartupNextInstance  Run one instance, then a second instance.

Note that StartupNextInstance is not raised. No errors are reported either on first or second instance.

It seems that https://github.com/dotnet/winforms/blob/b53c2eb7a863a8ff01b5ba28ad4c63c77dc88ad8/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb#L801 is specifically checking for MainForm null and not raising the event in this case. Compare with equivalent .NET Framework code which does StartupNextInstanceEvent?.Invoke _before_ the check for MainForm != null

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann can you take a look at this? @cston do you have any insight since we know you've worked in this space?

**Comment by KlausLoeffelmann** [comment]
I have a draft PR for that. 
Testing next week.

**Comment by KlausLoeffelmann** [comment]
@AlexVallat: Help me to understand the scenario. True, in Framework we couldn't do that - but as far as I remember only at that point. Wouldn't you get a `NoStartupFormException` after `OnCreateMainForm` has been called, if you had not defined a Form in that method, anyway? Or is it exactly that what's important in your scenario, namely _not_ to have defined a start Form at an earlier point in time? Thanks!

**Comment by KlausLoeffelmann** [comment]
@KathleenDollard: Would we need to service this?

**Comment by AlexVallat** [comment]
@KlausLoeffelmann The scenario that is important to me is not having a main form at all. This usually because I'm writing some background utility that just shows a notification icon and no form, but should still have single-instance behaviour. You wouldn't get a NoStartupFormException because the usage pattern for WindowsFormsApplicationBase would be to override both `OnStartupNext` and `OnStartup` (returning false). I've also seen `OnRun` overridden instead of `OnStartup`, doesn't make much difference except the naming symmetry is nice with Startup!

For example: https://www.red-gate.com/simple-talk/development/dotnet-development/creating-tray-applications-in-net-a-practical-guide/#seventeenth

**Comment by KlausLoeffelmann** [comment]
Ok, thanks for taking the time to explain your scenario! That makes sense.

**Comment by Ashley-Li** [comment]
@KlausLoeffelmann  Verified with .NET 6.0.100-preview.7.21369.19 build, after I run this App:  [testApp.zip](https://github.com/dotnet/winforms/files/6876515/testApp.zip)
(set IsSingleInstance to true. Do not assign a MainForm) , the result is not same with PR: #5075, there is an exception that appears, please see below gif:
![test_4805](https://user-images.githubusercontent.com/56664234/126954532-74c7f44a-2831-4845-9c57-c326895259a8.gif)
Is this expected behavior, or am I missing something?
