### ISSUE TITLE
bound DataGridView with all invisible columns will display first column anyway

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#4807]
* .NET Core Version:  all up to latest (5.0.5)

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
DataGridView with manual added columns. If your set on all of the columns `Visible = false` and then set `DataSource` you'll get 2 bugs:
1. First column become visible to user.
2. If `RowHeadersVisible = false` and  `AutoGenerateColumns = false` column header will be partially visible.

![Snipaste_2021-04-18_11-05-49](https://user-images.githubusercontent.com/17767561/115138757-aca36680-a036-11eb-85a9-1fcdcf72f866.png)

**Expected behavior:**
All columns must stay invisible.

**Minimal repro:**
[WinFormsCoreTest_Grid_Menu.zip](https://github.com/dotnet/winforms/files/6330756/WinFormsCoreTest_Grid_Menu.zip) (See `Form2.cs`)

**Comment by RussKie** [comment]
Would you like to have a go at fixing it?

**Comment by kirsan31** [comment]
> Would you like to have a go at fixing it?

Ah, I Would. As you know, I've been here for quite some time, and I always want to fix something :) Even creating a bug report takes some effort. And the fix itself need more time, that I don't have :(  Especially the very first attempt (create and configure environment, etc). But I do not lose hope that someday I will still do it :)))

**Comment by RussKie** [comment]
> Even creating a bug report takes some effort.

Yes, I fully appreciate it takes time to submit an actionable bug report. Thank you for doing this.



> Especially the very first attempt (create and configure environment, etc)

Did you check the [developer guide](https://github.com/dotnet/winforms/blob/main/docs/developer-guide.md)? Was there anything missing or confusing that made it hard?

**Comment by kirsan31** [comment]
> Did you check the developer guide? Was there anything missing or confusing that made it hard?

Checked now, everything is good and clear :flushed:

**Comment by kirsan31** [comment]
Hmm this is by strange design:
https://github.com/dotnet/winforms/blob/e572c90a5e12a9f481c5ac3cbe25a21f47fba64c/src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataConnection.cs#L1305-L1314
And  I am afraid that we need some one who really understand what's going on here...
Why we can't show `DataGridView` with all invisible columns at first time, but can hide them after control is shown?

**Comment by RussKie** [comment]
I suppose, it may be a strange scenario to have a grid without any columns, hence it wasn't considered, judging by the comment... ¯\\_(ツ)\_/¯
The team is currently dealing with other high priority items, but you're welcome to experiment here, and propose a possible solution.

**Comment by kirsan31** [comment]
> I suppose, it may be a strange scenario to have a grid without any columns, hence it wasn't considered, judging by the comment... ¯\_(ツ)_/¯
> The team is currently dealing with other high priority items, but you're welcome to experiment here, and propose a possible solution.

Totally agree.

We made a grid with the ability to select columns by the user. And this behavior immediately fell out on tests. I filled out a bug.
But now it's clear that this is not a bug lol. And I think it's not worth to dig here for the grid without columns ;)
Lets levee this issue for some one else who **really want** empty grid :))))

**Comment by RussKie** [comment]
Sounds like a plan :)
