### ISSUE TITLE
ToolStripControlHost with a custom control freezes UIA clients

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#4835]
* .NET Core Version: 6.0

* Have you experienced this same bug with .NET Framework?: Yes

* Original bug: [1313197](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1313197?src=WorkItemMention&src-action=artifact_link)

**Problem description:**
- If a ToolStrip has ToolStripControlHost item, Inspect can't show its accessbiility tree and freezes:
![hMfSttv4cb](https://user-images.githubusercontent.com/49272759/115824301-64a68a00-a410-11eb-8666-6beb0b5c4a04.gif)

**Expected behavior:**
- Inspect shows a correct accessbiility tree for a ToolStrip with a ToolStripControlHost:
![image](https://user-images.githubusercontent.com/49272759/115823495-13e26180-a40f-11eb-92f9-3e9c485cbdce.png)

**Minimal repro:**
- Create a .NET 6.0 app
- Add a ToolStrip to the app
- Create ToolStripControlHost with some control (eg. `new ToolStripControlHost(new RadioButton())`) and add it to the ToolStrip items
- Add several any items to ToolStrip (optional)
- Run the app and check the accessibility tree using Inspect

**Comment by Zheng-Li01** [comment]
Verified the issue with latest 6.0.0-preview.7.21330.1, the issue has been fixed that Inspect & AccessibilityInsight tools are working well when using ToolStripControlHost add custom controls for ToolStrip Control, please see below GIF.
![Issue4835](https://user-images.githubusercontent.com/38325459/124441836-b07d9400-ddae-11eb-80ed-d8fef716cebc.gif)
