### ISSUE TITLE
Winforms-When added the option(button) in panel not shown the option with HighDpi and custom scaling applied in .NET 5.0

### ISSUE THREAD

**Issue by vijayarasan** [dotnet/winforms#4838]
When setting the scaling 100% Control size and alignment are proper in the panel with HighDpi in the .Net 5.0 application. Please refer to the below screenshot for your reference,

**DPI enabled:**
![Dpi100Scaling](https://user-images.githubusercontent.com/58214164/115852229-78b8ae80-a445-11eb-84cb-3c227f5b9c53.png)

**Scaling:**
![Scaling](https://user-images.githubusercontent.com/58214164/115852066-4b6c0080-a445-11eb-9ccd-e4e03c65fa8c.png)

**Control size and alignment are proper in the panel with HighDpi 100% scaling**
![Buttonalignedanddisplayproperly](https://user-images.githubusercontent.com/58214164/115852363-a00f7b80-a445-11eb-935a-e36f5ebac483.png)

When setting the custom scaling 150% Control size and alignment is not proper in the panel with HighDpi in the .Net 5.0 application. Please refer to the below screenshot for your reference,

**DPI enabled:**
<img width="637" alt="DpiAndCustomScaling" src="https://user-images.githubusercontent.com/58214164/115852436-b4ec0f00-a445-11eb-9b36-7fb1c9911c78.png">

**Scaling:**
<img width="435" alt="CustomScaling" src="https://user-images.githubusercontent.com/58214164/115852514-cb926600-a445-11eb-868f-635fa05b9b57.png">

**Control size and alignment are not proper in the panel with HighDpi 150% scaling**
<img width="392" alt="ButtonTextNotDiplayed" src="https://user-images.githubusercontent.com/58214164/115852581-dcdb7280-a445-11eb-9103-32fff2a498a5.png">

Steps to reproduce the bug:

1.Run the Sample.

2.Click the button in the form.

**Sample:** [Sample.zip](https://github.com/dotnet/winforms/files/6364359/Sample.zip)

**Expected Behavior:**
The button should be properly aligned and display the text while setting custom scaling (150%).

**Observed Behavior:**
The button is not properly added and aligned. Button text is not shown while setting custom scaling (150%).

Can anyone share an idea to resolve the reported problem?

Regards,
Vijayarasan S

**Comment by dreddy-work** [comment]
Thanks @vijayarasan for providing the sample. Will be looking in to it on what is going on.

**Comment by kirsan31** [comment]
The problem is `AnchorStyles.Right`, same as https://github.com/dotnet/winforms/issues/3168.
@vijayarasan if you comment it here:
![image](https://user-images.githubusercontent.com/17767561/116005369-45298000-a60f-11eb-817a-f746385c729e.png)
you will get almost desire result:
![image](https://user-images.githubusercontent.com/17767561/116005520-0647fa00-a610-11eb-9769-47d686f71d81.png)

[Blog post](http://blog.davidegrayson.com/2013/04/unusable-ui-caused-by-windows-forms.html) about scaling problems with Anchor Right/Bottom.

**Comment by merriemcgaw** [comment]
@kirsan31 Great blogpost link! We should totally create another issue in the runtime repo describing what's up with Anchor right/bottom properties and see if we can't get it addressed as part of the HDPI effort.

**Comment by Philip-Wang01** [comment]
Verified this issue with latest .NET SDK 7.0.100-alpha.1.21566.13 build, it is fixed that The button properly aligned and display the text while setting custom scaling (150%)
![image](https://user-images.githubusercontent.com/86937911/142134659-d13088a2-f7ed-4a4e-ad8f-4905f234b1bb.png)
