### ISSUE TITLE
ListViewItemAccessibleObject does not update data about ListViewGroup when moved to another ListViewGroup

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#4839]
.NET Core Version: 
- 6.0.100-preview.2.21155.3

Have you experienced this same bug with .NET Framework?: 
- No. It is regression from #3223

**Minimal repro:**
1. Create an app with `ListView`
2. Add several `ListViewItems` to a `ListView`
3. Add "Test" `ListViewGroup` to the `ListView`
4. Add an event so that when you click on a special button, the second `ListViewItem` is moved to the "Test" `ListViewGroup`.
5. Run the application
6. Run Inspect
7. Get data about the second `ListViewItem` through the Inspect
8. Press a special button (the second 'ListViewItem' is moved to the "Test" `ListViewGroup`)

**Actual behavior:**
The `ListViewItem` is still displayed in the default `ListViewGroup` in the Inspect tree. The `ListViewItem` displays the default `ListViewGroup` as a parent.
![Issue-4839-before](https://user-images.githubusercontent.com/23376742/115856625-659de280-a435-11eb-9214-bcc938576d13.png)

**Expected behavior:**
The `ListViewItem` should be displayed in the "Test" `ListViewGroup` in the Inspect tree. The `ListViewItem` should display the "Test" `ListViewGroup` as a parent

**Comment by Zheng-Li01** [comment]
Verified the issue with latest 6.0.100-preview.5.21263.57, the issue has been fixed that ListViewItemAccessibleObject updated data about ListViewGroup when moved to another ListViewGroup, see below GIF.

In addition, have a GH issue [4581](https://github.com/dotnet/winforms/issues/4851) to track the item doesn't refresh timely in the Accessibility tree.
![Update4839](https://user-images.githubusercontent.com/38325459/118210991-ec2a6a80-b49d-11eb-887f-2328b8e1c8a6.gif)
