### ISSUE TITLE
Clarity on style guide

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#484]
What style guide should be followed? 

It looks like the original codebase followed [Brad Adam's guide](https://blogs.msdn.microsoft.com/brada/2005/01/26/internal-coding-guidelines/) that is vastly different to the [CoreFx's one](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md), that is indirectly recommended via the docs ([developer guide](https://github.com/dotnet/winforms/blob/master/Documentation/developer-guide.md) -> [coding guidelines](https://github.com/dotnet/corefx/tree/master/Documentation#coding-guidelines) -> [C# coding style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md)).

Do we use `this.variable` or `_variable`? 
Do we place usings inside or outside namespaces? 
Do we sort class members (I actually very much like that rule)?

**Comment by zsd4yr** [comment]
We follow the CoreFX guidelines on new contributions, but to my understanding, we have not attempted any code-wide refactor. This is for new changes

**Comment by zsd4yr** [comment]
> Do we use `this.variable` or `_variable`?

We use _camelCase for internal and private fields and use readonly where possible. Prefix internal and private instance fields with _, static fields with s_ and thread static fields with t_. When used on static fields, readonly should come after static (e.g. static readonly not readonly static). Public fields should be used sparingly and should use PascalCasing with no prefix when used.

> Do we place usings inside or outside namespaces?

Namespace imports should be specified at the top of the file, outside of namespace declarations, and should be sorted alphabetically, with the exception of System.* namespaces, which are to be placed on top of all others.

> Do we sort class members (I actually very much like that rule)?

Do you mean sorting imports? I am not aware of any guidance on the ordering of class members

**Comment by RussKie** [comment]
Thanks, it would be good to have these guidelines added to the Wiki, as they do diverge from the CoreFx's guidelines.


> Do you mean sorting imports? I am not aware of any guidance on the ordering of class members

Not quite. My questions was about file organisation. E.g. [Brad Adams' guide is quite specific about it](https://blogs.msdn.microsoft.com/brada/2005/01/26/internal-coding-guidelines/#_Toc6325250):

> * Classes member should be **alphabetized**, and grouped into sections (Fields, Constructors, Properties, Events, Methods, Private interface implementations, Nested types)

Personally I quite like this, as it makes tremendously easier to review and reason about the code, especially outside an IDE.

. . .

A little OT, for imports I like these settings:
![image](https://user-images.githubusercontent.com/4403806/53371522-93498700-39a4-11e9-9ed9-e750ceb28efd.png)
![image](https://user-images.githubusercontent.com/4403806/53371554-a5c3c080-39a4-11e9-921b-98f83ba845b4.png)

IIRC there is a StyleCop analyser that can enforce the order of usings.

**Comment by drewnoakes** [comment]
@zsd4yr in https://github.com/dotnet/winforms/issues/484#issuecomment-467191583 your underscores were interpreted as requesting italics, making your examples a bit confusing.

**Comment by sharwell** [comment]
@zsd4yr Expanding on what @drewnoakes said, you can escape your literal underscores in Markdown by using `\_`.

**Comment by zsd4yr** [comment]
> Thanks, it would be good to have these guidelines added to the Wiki, as they do diverge from the CoreFx's guidelines.

That is impossible, as I copied and pasted them from the CoreFx guidelines.

**Comment by RussKie** [comment]
Now it all makes sense, thank you all

**Comment by zsd4yr** [comment]
> for imports I like these settings

For any of these, I am more inclined to discuss them if there is a way to set them in the .editorconfig. Does anyone else have any opinions here?

**Comment by RussKie** [comment]
This can be enforced with StyleCope anaylsers
![image](https://user-images.githubusercontent.com/4403806/53448947-c6efe400-3a6c-11e9-8e01-8aee0c29125a.png)

@sharwell is the man to talk about these

**Comment by zsd4yr** [comment]
Style cop is an institutionally acceptable option. My personal opinion is that I would rather these things me automagically fixed at edit-time ; there should be a way to keep uniform style and avoid additional work necessary on the part of developers.

**Comment by RussKie** [comment]
We should then convince VS team to set the above as defaults, as the 95% of developers don't change settings 😉

**Comment by merriemcgaw** [comment]
The issue appears to be resolved. Thanks guys!
