### ISSUE TITLE
Remove .NET Framework isms

### ISSUE THREAD

**Issue by richlander** [dotnet/winforms#485]
I was just looking through the code-base and did a search on ".NET Framework".  Here are a few hits I found:

* [ResXDataNode.cs](https://github.com/dotnet/winforms/blob/15cda680cff86c1d7654f8dd675249733d002b94/src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs#L803)
* [PropertyDescriptorGridEntry.cs](https://github.com/dotnet/winforms/blob/784d45b66d34ca1f153559b7e6dbd0d20fa95c25/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs#L1016)
* [AssertExtensions.cs](https://github.com/dotnet/winforms/blob/0f2036a5f45740be4718da76cf7bf247140f8864/src/Common/tests/InternalUtilitiesForTests/src/AssertExtensions.cs#L15)

I was wondering if there was going to be a structured effort to remove important .NET Framework-isms. The ones I included are all of different kinds. It would be good to see a statement (and maybe this already exists) on what kinds of .NET Framework isms should be removed/cleanedup before shipping .NET Core 3.0.

**Comment by merriemcgaw** [comment]
Thanks @richlander. We will attempt to get this scrub in for Preview 5.  @dreddy-work will drive.

**Comment by dreddy-work** [comment]
Couple of PRs pending that are cleaning up some of these instances. I will revisit once they get in.

**Comment by danmosemsft** [comment]
```
  <data name="ExDlgSecurityContinueErrorText" xml:space="preserve">
    <value>Application attempted to perform an operation not allowed by the security policy. To grant this application the required permission, contact your system administrator, or use the Microsoft .NET Framework Configuration tool.

If you click Continue, the application will ignore this error and attempt to continue.

{1}.</value>
  </data>
  <data name="ExDlgSecurityErrorText" xml:space="preserve">
    <value>Application attempted to perform an operation not allowed by the security policy. To grant this application the required permission, contact your system administrator, or use the Microsoft .NET Framework Configuration tool.

If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

{1}.</value>
```

**Comment by merriemcgaw** [comment]
#839 and #247 are related.

**Comment by merriemcgaw** [comment]
Remove or reword strings that reference .NET Framework. Then we'll list out where there are functional implications of making a change and evaluate them one by one.
