### ISSUE TITLE
[Accessibility] The Inspect tree displays information doesn't refresh timely when moving a listViewItem from default listViewGroup to another listViewGroup

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#4851]
* .NET Core Version: 
.NET SDK 6.0.100-preview.5.21226.11

* Have you experienced this same bug with .NET Framework?: 
Yes

**More info:**
1. This is a not regression issue, it also reproduced on .NET framework 4.8, .NET core 3.1 & .NET 5.0.
2. The issue is related to the fact that the Inspect tree displays information that is relevant at the time the data is received. To update the data again, the user should collapse and re-expand the item. **This is a general problem for the Inspect, not specifically related to the ListView.**

**Minimal repro:** 
[TestApp_Core.zip](https://github.com/dotnet/winforms/files/6383007/TestApp_Core.zip)

1. Create an app with ListView which added several ListViewItems
2. Add "Test" ListViewGroup to the ListView
3. Add an event so that when you click on a special button, the second ListViewItem is moved to the "Test" ListViewGroup.
4. Run the app
5. Run the Inspect
6. Select the item2 in inspect tree
7. Press the Replace button, at this time, the item2 is moved to the "Test" group
8. Focus on item2 using mouse
9. Observe the structure of listView in inspect tree

**Actual behavior:**
The item2 is displayed in both "default" ListViewGroup and "Test" ListViewGroup.
After click refresh button in inspect, the item2 in "default" ListViewGroup disappeared.
![image](https://user-images.githubusercontent.com/62929087/116208319-63a88c00-a773-11eb-900a-c2a641e4a005.png)

**Expected behavior:**
The item2 should only display in "Test" ListViewGroup.

**Comment by ArtemTatarinov** [comment]
A possible solution for tree updating, needs further investigation and experimenting: https://stackoverflow.com/questions/10782100/outdated-ui-automation-tree/47354168#47354168

**Comment by vladimir-krestov** [comment]
@Amy-Li03, can you please test this case in AI. I think, we don't need to care about Inspect, we can just click "Update" button for it. For the rest UIA tools ListView works well, please check it. If so, please close the issue.

**Comment by Amy-Li03** [comment]
@vladimir-krestov tested this issue in AI tool, the test result is same as mentioned by @NikitaSemenovAkvelon above, so close it.
