### ISSUE TITLE
PropertyGrid: ExpandAllGridItems() on hidden control causes NullRefException on Form Dispose

### ISSUE THREAD

**Issue by MrStefanWolff** [dotnet/winforms#4861]
* .NET Core Version: 3.1

* Have you experienced this same bug with .NET Framework?:  No (tested with identical design)

**Problem description:**
I am using a propertygrid control on a TabControl. 
The propertygrid is located on the second TabPage, which is not the selected index when the application starts.
On creating the form, I assign a simple dataobject to the propertygrid (I picked "Color" as an example, works for all objects as far as I know).
After that, I call **ExpandAllGridItems()**.
Here is the setup, as simple as possible:
![image](https://user-images.githubusercontent.com/83414880/116671458-3e996080-a9a1-11eb-8273-2d8f65e00c0d.png) ![image](https://user-images.githubusercontent.com/83414880/116671326-1c9fde00-a9a1-11eb-88ef-ad0d3b75a465.png)

The bug :
If you close the form _before_ opening the selected "hidden tabPage" at least once, the following exception occurs (while disposing the form):
![image](https://user-images.githubusercontent.com/83414880/116656348-cfb20c80-a98c-11eb-9399-d181a6909fee.png)

If you select the "hidden tabPage" first and close the form afterwards (even if not in focus anymore), the form closes without any errors.

**Expected behavior:**
I would expect to get no exception. I tried the same setup in .NET Framework 4.8 with no errors. 

**Minimal repro:**
[GridControl_Dispose_bug.zip](https://github.com/dotnet/winforms/files/6404100/GridControl_Dispose_bug.zip)

**Comment by RussKie** [comment]
This fails in a11y related code
```
System.Windows.Forms.dll!System.Windows.Forms.PropertyGridInternal.PropertyGridView.PropertyGridViewAccessibleObject.FragmentNavigate(System.Windows.Forms.UnsafeNativeMethods.NavigateDirection direction = Parent)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.AccessibleObject.System.Windows.Forms.UnsafeNativeMethods.IRawElementProviderFragment.Navigate(System.Windows.Forms.UnsafeNativeMethods.NavigateDirection direction)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.InternalAccessibleObject.System.Windows.Forms.UnsafeNativeMethods.IRawElementProviderFragment.Navigate(System.Windows.Forms.UnsafeNativeMethods.NavigateDirection direction)	Unknown	No symbols loaded.
 	[Native to Managed Transition]		Annotated Frame
 	[Managed to Native Transition]		Annotated Frame
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ReleaseUiaProvider(System.IntPtr handle)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WmDestroy(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message})	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.PropertyGridInternal.PropertyGridView.WndProc(ref System.Windows.Forms.Message m)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg = 2, System.IntPtr wparam, System.IntPtr lparam)	Unknown	No symbols loaded.
 	[Native to Managed Transition]		Annotated Frame
 	[Managed to Native Transition]		Annotated Frame
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DestroyHandle()	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.DestroyHandle()	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Dispose(bool disposing = true)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.PropertyGridInternal.PropertyGridView.Dispose(bool disposing)	Unknown	No symbols loaded.
>	System.ComponentModel.Primitives.dll!System.ComponentModel.Component.Dispose() Line 75	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Dispose(bool disposing = true)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.PropertyGrid.Dispose(bool disposing)	Unknown	No symbols loaded.
 	System.ComponentModel.Primitives.dll!System.ComponentModel.Component.Dispose() Line 75	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Dispose(bool disposing = true)	Unknown	No symbols loaded.
 	System.ComponentModel.Primitives.dll!System.ComponentModel.Component.Dispose() Line 75	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Dispose(bool disposing = true)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.TabControl.Dispose(bool disposing)	Unknown	No symbols loaded.
 	System.ComponentModel.Primitives.dll!System.ComponentModel.Component.Dispose() Line 75	C#	Symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Dispose(bool disposing = true)	Unknown	No symbols loaded.
 	System.Windows.Forms.dll!System.Windows.Forms.Form.Dispose(bool disposing)	Unknown	No symbols loaded.
 	GridControlBug.dll!GridControlBug.Form1.Dispose(bool disposing = true) Line 21	C#	Symbols loaded.
```

This was fixed in .NET 5.0.

@MrStefanWolff are you able to migrate to .NET 5.0?

@vladimir-krestov  @SergeySmirnov-Akvelon please investigate feasibility of a fix.
@merriemcgaw we may need to service this...

**Comment by MrStefanWolff** [comment]
Hello again
Thank you for your investigation into this issue. 
Unfortunately, we cannot migrate our code to .NET 5.0

Best regards.

**Comment by Zheng-Li01** [comment]
Verified the issue with latest 6.0.0-preview.7.21330.1, the issue has been fixed that no exception pops up by following the steps provided by customer with attached project. see below GIF.
![Issue4861](https://user-images.githubusercontent.com/38325459/124438616-018b8900-ddab-11eb-93b9-b533e41d08ef.gif)

**Comment by Jenna-Zheng** [comment]
Verified this issue with the .NET SDK 5.0.9, the issue has been fixed that no exception pops up.

**Comment by Lydia-Shi** [comment]
Verified this issue with the .NET SDK 3.1.118, the issue has been fixed that no exception pops up.

**Comment by Philip-Wang01** [comment]
Verified this issue with the .NET SDK 3.1.412, the issue has been fixed that no exception pops up.
