### ISSUE TITLE
WinForms HighDPI PerMonitorV2 ToolStrip scales wrong

### ISSUE THREAD

**Issue by Balkoth** [dotnet/winforms#4872]
**.NET Core Version:**

SDK: 5.0.202 (db7cc87d51)
Runtime: 5.0.5 (2f740adc14)

**Problem description:**

A toolstrip with items set to DisplayStyle=ImageAndText does not scale correct.

Starting the sample application provided below on my main screen with 144dpi, shows that both toolbars are of the same height:
![image](https://user-images.githubusercontent.com/80055480/117140591-dafea100-adad-11eb-8aff-4eb1659a9ccb.png)
![image](https://user-images.githubusercontent.com/80055480/117140616-e225af00-adad-11eb-824f-79bda5f7002a.png)

Now moving the window to my secondary screen with 96dpi, suddenly shows that the toolbars are now longer of the same height:
![image](https://user-images.githubusercontent.com/80055480/117140820-1f8a3c80-adae-11eb-9c3b-d2d11384e057.png)
![image](https://user-images.githubusercontent.com/80055480/117140964-48aacd00-adae-11eb-9141-bd329ef756d1.png)

In my opinion the toolbar only displaying the images has the correct size.

**Minimal repro:**
- Create new .NET-Core 5.0 WinForms app
- Set Application.SetHighDpiMode(HighDpiMode.PerMonitorV2)
- Open the forms designer for Form1
- Set AutoScaleMode = Dpi
- Create 2 ToolBars docked to the top and fill them with standard items
- Edit 1 ToolBar so that the ToolBarItems have DisplayStyle=ImageAndText

I have attached a sample project with the repro steps described above here:
[TestDpiToolStrip.zip](https://github.com/dotnet/winforms/files/6427078/TestDpiToolStrip.zip)

**Comment by dreddy-work** [comment]
Font is controlling scaling in this case and Control font is not updated when moved form one monitor to other with different DPI. OnFontchanged  bypass Font reset on control when owner drawn. We should be making sure to set right Font on control to get them scaled well. Will get the fix out soon.

**Comment by Zheng-Li01** [comment]
Verified the issue with .NET 6.0 6.0.100-preview.7.21369.19, the issue has been fixe that the ToolStrip is scaled well. see below screenshot.
![image](https://user-images.githubusercontent.com/38325459/126731341-170d521b-6191-4e73-b7e1-f39a7c77f952.png)
