### ISSUE TITLE
Require new translation: TreeNodeCircularReference

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#488]
Related to #454

**Comment by manuelvalenzuela** [comment]
Hi @zsd4yr, I can translate to Spanish. How is the procedure to do it, considering that this issue should be closed only when all the languages are ready?

**Comment by zsd4yr** [comment]
Hey @manuelvalenzuela we have a team who uses some algorithms for this. I am in talks with them to discuss how we (both contributors like yourself as well as people like me) can 1) ask for their assistance and 2)  suggest edits to existing translations. They generate [these files](https://github.com/dotnet/winforms/tree/master/src/System.Windows.Forms/src/Resources/xlf) for us. 

This issue is to act as an example of case 1) asking for their assistance in a new translation. Once we have this system in place, we will add it to the contribution guidelines 😄 

However, if you see something strange / missing / not quite right in our Spanish translations for [Sys.Wiin.Forms](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf), [".Design](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf), or [".Design.Editors](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf), (that would look like case 2) suggesting edits to existing translations), this new agreement between us and the loc team would enable you to request those changes as well.

The reason we don't do these kinds of changed ad-hoc is so that all of .NET Core can benefit from a growing corpus of reasonable translations / idioms / grammars.

**Comment by manuelvalenzuela** [comment]
Hey @zsd4yr, thank you for taking the time to explain me!
I will be keeping an eye on the updates in this thread.
In the meantime, I will be taking small issues to keep contributing in the project :)

**Comment by merriemcgaw** [comment]
@vivmishra, @leecow  is there an automated process (yet) so the loc team can pick up new resources? The xlf format should make it easy to create automated tooling.

**Comment by leecow** [comment]
Not that I'm aware of but @vivmishra may have something up his sleeve.
