### ISSUE TITLE
ControlDesigner can not be used in .NetCore winform,but it works in .Net Framework,how to use it in .Net Core winform

### ISSUE THREAD

**Issue by paxtonxuhongzhi** [dotnet/winforms#4886]
ControlDesigner can not be used in .NetCore winform,but it works in .Net Framework,how to use it in .Net Core winform
92764-image.png

![92764-image](https://user-images.githubusercontent.com/42473082/117597581-7316d480-b178-11eb-9504-5bc743bf2129.png)

Such as this(Framework),the panel in framework work well,it visable in designer and controable,but in .Net Core,it just exist but can not use.
![92677-image](https://user-images.githubusercontent.com/42473082/117597577-714d1100-b178-11eb-997a-9fcfd91bdf9e.png)
92677-image.png
such as this（.Net Core）

my code as follow,
```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Windows.Forms.Design;

namespace WindowsFormsAppNetCore
{
[Designer(typeof(LDesigner))]
[DesignTimeVisible(true)]
public class MenuControlEx : SetterControl
{
public MenuControlEx()
{
InitializeComponent();
}
/// <summary>
/// Panel
/// </summary>
[Browsable(false), DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
public Panel MenuPanel
{ get { return setterPanel; } }

     private void InitializeComponent()
     {
         this.setterPanel = new System.Windows.Forms.Panel();
         this.SuspendLayout();
         // 
         // setterPanel
         // 
         this.setterPanel.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
         | System.Windows.Forms.AnchorStyles.Left) 
         | System.Windows.Forms.AnchorStyles.Right)));
         this.setterPanel.AutoScroll = true;
         this.setterPanel.Location = new System.Drawing.Point(104, 66);
         this.setterPanel.Name = "setterPanel";
         this.setterPanel.Size = new System.Drawing.Size(355, 413);
         this.setterPanel.TabIndex = 0;
         // 
         // MenuControlEx
         // 
         this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
         this.Controls.Add(this.setterPanel);
         this.ItemContainer = this.setterPanel;
         this.Name = "MenuControlEx";
         this.Size = new System.Drawing.Size(482, 508);
         this.ResumeLayout(false);
     }
     private System.Windows.Forms.Panel setterPanel;
 }
 //system.Desgin
 public class LDesigner : ParentControlDesigner
 {
     private MenuControlEx _control;
     public override void Initialize(IComponent component)
     {
         base.Initialize(component);
         _control = (MenuControlEx)component;
         bool succ = this.EnableDesignMode(_control.MenuPanel, "setterPanel");
         if (!succ)
             throw new Exception("");
     }
 }
}
```

**Comment by RussKie** [comment]
See https://github.com/dotnet/winforms/pull/4860

**Comment by RussKie** [comment]
Please provide a standalone sample.

**Comment by paxtonxuhongzhi** [comment]
[TestTabControlNetCore.zip](https://github.com/dotnet/winforms/files/6475854/TestTabControlNetCore.zip)
[TestTabControlFramework.zip](https://github.com/dotnet/winforms/files/6475855/TestTabControlFramework.zip)

**Comment by paxtonxuhongzhi** [comment]
> Please provide a standalone sample.
Thank you for your attention. I have uploaded two zips

**Comment by RussKie** [comment]
Can you please clarify how to use your samples? I don't see any design hosts or surfaces... 

When I run the .NET Framework sample I see this:
![image](https://user-images.githubusercontent.com/4403806/118214770-bc865d00-b4b3-11eb-9bde-7722a5d7de93.png)

Please explain what you're trying to achieve, what the issue is, and steps to reproduce.
Thanks

**Comment by paxtonxuhongzhi** [comment]
> Can you please clarify how to use your samples? I don't see any design hosts or surfaces...
> 
> When I run the .NET Framework sample I see this:
> ![image](https://user-images.githubusercontent.com/4403806/118214770-bc865d00-b4b3-11eb-9bde-7722a5d7de93.png)
> 
> Please explain what you're trying to achieve, what the issue is, and steps to reproduce.
> Thanks

https://github.com/dotnet/winforms/issues/4886#issuecomment-840972514

**Comment by paxtonxuhongzhi** [comment]
> Can you please clarify how to use your samples? I don't see any design hosts or surfaces...
> 
> When I run the .NET Framework sample I see this:
> ![image](https://user-images.githubusercontent.com/4403806/118214770-bc865d00-b4b3-11eb-9bde-7722a5d7de93.png)
> 
> Please explain what you're trying to achieve, what the issue is, and steps to reproduce.
> Thanks

It doesn't need to run, you should see the difference in the designer. In the designer, when you drag the custom control to the form, you can see the custom control with the same code. In the designer of. Net framework, you can see the sub control panel of the custom control, change its size, and drag other controls into the sub control of the custom control. But in the design of.Net Core, you can not change the size of the custom control sub control, nor can you drag into other controls in Panel.

The container property of the panel of a custom control cannot be created in. NETCORE

**Comment by RussKie** [comment]
This is the Windows Forms runtime repo. Issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause..

Please post a link to the VS Feedback issue here, so we don't miss it.
