### ISSUE TITLE
Smart Tag support in WF

### ISSUE THREAD

**Issue by SenthilKumaranRajan** [dotnet/winforms#4887]
* .NET Core Version: 
.Netcore 3.1 and NET 5

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The smart tag is not working properly for the NETCore project.

**Expected behavior:**

The smart tag should work properly as like .NETFramework

Attached the code example in the below link

[CustomControlWithSmartTag.zip](https://github.com/dotnet/winforms/files/6457287/CustomControlWithSmartTag.zip)

**Minimal repro:**

![image](https://user-images.githubusercontent.com/44424557/117776267-03c4e180-b259-11eb-87ff-621918cac4a6.png)

**Comment by RussKie** [comment]
The sample code is unreadable. Please provide a stand along repro.

**Comment by SenthilKumaranRajan** [comment]
> The sample code is unreadable. Please provide a stand-along repro.

Hi @RussKie ,

I have attached the sample quotes in attachment. Please check this and let me know if you have any concerns.

Also please share is there any documentation link to create a smart tag support for custom control? for NETCore

**Comment by SenthilKumaranRajan** [comment]
Hi @RussKie ,

Is there any other way to provide the smart tag support?

**Comment by RussKie** [comment]
> Attached the code example in the below link

Thank you. Run your sample against #4860:
![image](https://user-images.githubusercontent.com/4403806/117926666-722ea000-b33c-11eb-8e8f-4da502b1f02b.png)





> Is there any other way to provide the smart tag support?

At runtime - no.

**Comment by Lydia-Shi** [comment]
Verified this issue with .Net 6.0.100-preview.5.21276.15 from Release/6.0.1XX-preview5 branch of https://github.com/dotnet/installer, it is fixed, results as below:
![image](https://user-images.githubusercontent.com/54019172/119791404-624fb800-bf07-11eb-9f69-a442fd3d7429.png)

**Comment by SenthilKumaranRajan** [comment]
Hi Team,

Will this fix be included for .NetCore 3.1 and .Net 5?

**Comment by RussKie** [comment]
No. .NET 6.0 onwards

**Comment by SenthilKumaranRajan** [comment]
Some companies providing a smart tag in Net50

https://www.telerik.com/blogs/dotnet-conf-2020-telerik-ui-for-winforms-wpf-officially-supports-dotnet-5

If smart tag is possible in net 5. Then please suggest how can we do this?

**Comment by weltkante** [comment]
Last I heared they partnered with Microsoft and developed their designers under NDA. Unless I missed the release the WinForms team is still working on support and documentation for everyone else.

**Comment by RussKie** [comment]
That's correct, a number of vendors have access to our Designer SDK under NDA. This SDK is still being worked on, and once it has stabilised and deemed complete it will released to the public.

Also it is worth noting that both .NET Core 3.1 and .NET 5.0 will be retired not long after the release of .NET 6.0. Refer to https://dotnet.microsoft.com/platform/support/policy for more details.

**Comment by RussKie** [comment]
It is also worth noting that Windows Forms runtime (this repo) and the Windows Forms designer (i.e. the design surface and the behaviours in it) are two different codebases, and no longer have tight coupling as they used to in .NET Framework.
#4860 was an enabler to designer scenarios support at runtime, and had nothing to do with the Visual Studio Designer scenarios.

**Comment by Niranjan16-Ninja** [comment]
Hi @RussKie ,

I am facing the same issue while also using the `ComponentDesigner ` class for my custom component control. The same issue is reproducible in .NetCore 3.1 and .NET5 , but works fine in .NET Framework. I have attached the sample for same . Will the fix for this issue will be included in .NET 6 ?

In .NET Framework:
![image](https://user-images.githubusercontent.com/59389414/120435518-711ceb80-c39b-11eb-8592-6fb15929e4fd.png)

In .NET Core:
![image](https://user-images.githubusercontent.com/59389414/120435211-12f00880-c39b-11eb-9647-6bcdd1eef43e.png)

Sample:
[WinFormsApp2.zip](https://github.com/dotnet/winforms/files/6582487/WinFormsApp2.zip)

**Comment by RussKie** [comment]
@Niranjan16-Ninja your use case is in the Designer, please refer to my previous comment.

We are working to ensure the .NET designer is at parity with the .NET Framework designer, and the smart tag support is one the list.

**Comment by SenthilKumaranRajan** [comment]
Hi @RussKie ,

Today I have installed .NET 6 preview 5 and tested this reported issue. Still this issue is not fixed.

Please find the screenshot below.

![image](https://user-images.githubusercontent.com/44424557/123218666-a1166500-d4e9-11eb-9d7d-a78a9843c9ac.png)

**Comment by RussKie** [comment]
> Today I have installed .NET 6 preview 5 and tested this reported issue. Still this issue is not fixed.

Is this at run time or design time?

**Comment by SenthilKumaranRajan** [comment]
Hi @RussKie ,

**Design Time**. I know smart tag will work only on design time. Also, in .NET Framework it works perfectly. Please find screenshot below.

![image](https://user-images.githubusercontent.com/44424557/123235514-9237ae80-d4f9-11eb-8499-96cf678332aa.png)

**Comment by NiranjanKumar16** [comment]
Hi @RussKie ,

I am having the same issue in .NET6 preview 5 at design time in Windows Forms. It seems like you have fixed this issue and set for .NET6 Preview 5. But it is still not working. Can you please check this and update us asap ?

**Comment by weltkante** [comment]
In case you missed it, this issue was implemented for runtime designers, VisualStudio uses a new implementation and disregards many of the old WinForms designer code. There is a new designer SDK with support available under NDA, public documentation for creating design time code usable in VS is not yet available.
