### ISSUE TITLE
ContextMenuStrip doesn’t DPI-scale its items properly

### ISSUE THREAD

**Issue by wjk** [dotnet/winforms#4898]
## .NET Core Version
6.0.0-preview.3.21201.4

**Have you experienced this same bug with .NET Framework?** Didn’t bother to check; I no longer target .NET Framework

## Problem description
The below screenshot illustrates the problem much better than words can. The left menu is the `ContextMenuStrip`; the right menu is a `ToolStripMenuDropDown`.

## Expected behavior
All menu items should have the same height, no matter what kind of container they are located in.

## Minimal repro
<img width="369" alt="Screenshot" src="https://user-images.githubusercontent.com/1915951/117898547-2d9afa00-b293-11eb-98dd-db5faa345996.png">

**Comment by RussKie** [comment]
> .NET Framework is deprecated

This isn't a correct statement, .NET Framework is fully supported and maintained. It is "feature complete", and thus doesn't receive any updates.

**Comment by wjk** [comment]
@RussKie My apologies; that was a poor choice of wording. Updated OP. Thanks!

**Comment by helviett** [comment]
More than a year has passed. Will this issue recieve more attention? 
We use `ContextMenuStrip` for context menus and drop downs. Our application is in PerMonitorV2 dpi awareness mode (set by Application.SetHighDpiMode call), so we recieve a correct DPI value from from and scale our application appropriately. However when DPI is changed `ContextMenuStrip.DeviceDpi` is still the value of DPI when application has started. Recreation of the control doesn't help. So it seems like all the `ContextMenuStrip`s live in another HighDpiMode.SystemAware world.

Is the any way or workaround to set correct DPI value for  `ContextMenuStrip`?

When application is started in 100% scale but then you change it to 150%:

![100_to_150](https://user-images.githubusercontent.com/17850773/204815238-6c9fd994-0e0e-499a-8264-2b306a4c7cad.png)

When application is started in 150% scale but then you change it to 100%:

![150_to_100](https://user-images.githubusercontent.com/17850773/204815420-2c5f0b50-61fa-4379-8a19-150facfca8e8.png)

**Comment by dreddy-work** [comment]
Work on high DPI was delayed until now. We are making progress in .NET 8.0 and prioritizing the issues. @helviett Can you clarify couple of things here? 

> so we recieve a correct DPI value from from and scale our application appropriately

What do you mean by "Scale our application " here? Do you have custom code to scale it in your application? or letting it to be scaled by WinForms?

>when DPI is changed ContextMenuStrip.DeviceDpi is still the value of DPI when application has started

If application is running in `PermonitorV2` mode, we do update this to point to new value. Would you be able to provide a sample repro application here for us?

Is the scenario something like, dynamically changing screen DPI after application is launched? I mean, application is started on 150% DPI monitor and then changing DPI of the monitor to 200% while application is running?

-  Dynamic change in DPI is not fully validated in WinForms yet and currently on low priority. PermonitorV2 mode in WinForms is to support multiple monitors with different DPI settings, connected to one machine.

**Comment by helviett** [comment]
> What do you mean by "Scale our application " here? Do you have custom code to scale it in your application? or letting it to be scaled by WinForms?

Our game engine uses WinForms on Windows as a Window System backend. We create form and a control inside it, take window handle and do I own rendering. We use a `Form.DeviceDpi` to properly scale our UI in the scene editor.

> If application is running in PermonitorV2 mode, we do update this to point to new value. Would you be able to provide a sample repro application here for us?

Our forms invoked `DpiChanged` event when you move `Form` to a monitor with a different scale set or when you set different scale for current window in Windows settings. But `ContextMenuStrip.DeviceDpi` stays the same. I will try to create simple repro using WinForms only tomorrow.

> Is the scenario something like, dynamically changing screen DPI after application is launched? I mean, application is started on 150% DPI monitor and then changing DPI of the monitor to 200% while application is running?

I start application on a monitor with a 150% scale set. Then I change monitors scale in the Windows settings to 100% and get incorrect results for `ContextMenuStrip.DeviceDpi`. However any of my forms reacts to such changes and fires `DpiChanged` event and gets correct `form.DeviceDpi` value. That's why it's strange that `ContextMenuStrip` doesn't recieve new value. As far as I understand `ContextMenuStrip.Show(...)` just opens a separate window which should react to WM_DPICHANGE message the same way `Form` reacts to it.

**Comment by dreddy-work** [comment]
two things here: 

- A sample application will definitely help understand how `ContextMenuStrip `is structured.
- IsHandleCreated for `ContextMenuStrip ` when DPI changed? if not, it won't receive any DPI change messages.
- Top level windows get `WM_DPICHANGE `message while child controls get `WM.DPICHANGED_AFTERPARENT ` and `WM.DPICHANGED_BEFOREPARENT`. How `ContextMenustrip `is created would help what is happening when DPI change happen.

**Comment by helviett** [comment]
> IsHandleCreated for ContextMenuStrip when DPI changed? if not, it won't receive any DPI change messages.

`IsHandleCreated` is always false for `ContextMenuStrip`. 

I created a repro and found out that the main problem causes `ToolStripItem.AutoSize` property set to `false`. With `AutoSize` set to `true` menu items are resized correctly. However they still show wrong `DeviceDpi` and everything should be resized correctly with any `AutoSize` value.

[ContextMenuStripDpiChangedTest.zip](https://github.com/dotnet/winforms/files/10130570/ContextMenuStripDpiChangedTest.zip)

**Comment by Olina-Zhang** [comment]
@dreddy-work tested that application in the latest .Net 8.0 SDK build.
Here is setting AutoSize to true, and get the ContextMenuStrip's DeviceDpi in TextBox to display, all looks good, when changing Windows DPI, value is correct and scale well:
![image](https://github.com/dotnet/winforms/assets/26474449/66fcc32c-7124-48db-9c03-eb6b0bea5c80)

Here is seting AutoSize to false:
![image](https://github.com/dotnet/winforms/assets/26474449/2ecc2abd-f9f5-447d-b8f1-882cedaf24c3)

**Comment by dreddy-work** [comment]
@wjk, seems two different issues were discussed in this thread and one of them doesn't repro with lates. Please reactivate if you still see the issue with lates .NET 8.0 bits..
