### ISSUE TITLE
[Proposal] Streamline application configuration and bootstrap

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#4909]
Moved to https://github.com/dotnet/designs/pull/223

**Comment by RussKie** [comment]
Updated dpi resolution algorithm.

**Comment by RussKie** [comment]
Progress update:
![projectconfiguration](https://user-images.githubusercontent.com/4403806/119747720-aa0a1b80-bed6-11eb-8247-45b1668d4867.gif)

**Comment by omariom** [comment]
If the WinForms related properties were prefixed with "WinForms."  it would be easier to differentiate them  from others
msbuild properties.
Like
```
  <PropertyGroup>
    <WinForms.ApplicationManifest>app1.manifest</WinForms.ApplicationManifest>
    <WinForms.ApplicationVisualStyles>true</WinForms.ApplicationVisualStyles>
    <WinForms.ApplicationFontName>Control.DefaultFont</WinForms.ApplicationFontName>
    <WinForms.WinForms.ApplicationFontSize>9</WinForms.ApplicationFontSize>
    <WinForms.ApplicationHighDpiMode>PerMonitorV2</WinForms.ApplicationHighDpiMode>
  </PropertyGroup>
```

**Comment by jnm2** [comment]
> makes a conscience decision

ℹ The common phrase is "makes a conscious decision."

**Comment by jnm2** [comment]
@omariom I've also seen people do this:

```xml
​  <PropertyGroup>
    <WinForms>
      <ApplicationManifest>app1.manifest</ApplicationManifest>
      <ApplicationVisualStyles>true</ApplicationVisualStyles>
      <ApplicationFontName>Control.DefaultFont<ApplicationFontName>
      <ApplicationFontSize>9<ApplicationFontSize>
      <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    </WinForms>
  </PropertyGroup>
```

**Comment by RussKie** [comment]
> > makes a conscience decision
> 
> ℹ The common phrase is "makes a conscious decision."

Thank you :)

**Comment by RussKie** [comment]
> If the WinForms related properties were prefixed with "WinForms." it would be easier to differentiate them from others
> msbuild properties.

There are other existing "Application*" properties (e.g. `ApplicationIcon` and `ApplicationManifest`, and the new properties will align with those.

**Comment by kirsan31** [comment]
#4978 triggers me: do we need `ApplicationFontStyle` here too?

**Comment by RussKie** [comment]
> #4978 triggers me: do we need `ApplicationFontStyle` here too?

**In my opinion** this starts encroaching into theming/styling territory.  AFAIK Windows has never had a default font that was italic or bold. 
`SetDefaultFont` API was added in response to the changes of the hardcoded default font, and only for the purpose of unblocking and enabling migrations of .NET Framework apps with pixel-perfect layouts.  Our goal is to allow building Windows native apps, and whilst the API can now be used beyond the intended use case allowing making Windows apps that don't look native on Windows (and that includes italic or bold fonts) starts working against that goal.
To me personally allowing to make an application default font is a feature request, which probably/arguably has no valid use case behind it.

Happy to continue this discussion.

**Comment by Amy-Li03** [comment]
Verified this issue with TP build: 6.0.100-rc.1.21453.13, this issue has been fixed.
