### ISSUE TITLE
[regression] PropertyGrid GDI leak 

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#4913]
* .NET Core Version: 5.0.3 - 5.0.6 tested.

* Have you experienced this same bug with .NET Framework?:  **NO**. Also this bug is **not present** in .net core 3.1

**Problem description:**
For several months I am was investigating **huge** (up to critical 10000) GDI leak in our app (beginning after switching from .net core 3.1 to .Net 5). And finally found it out (I am happy :roll_eyes:). Facts:

- Leaking are DC and Bitmap in approximately the same proportions.
- This is not managed leaks - managed heap have not any increasing elements.  So GC not helping here and if `PropertyGrid` inside childe window, closing it will not help too.
- Leaks are not reproduce on local machine. Only when you **connect** to rdp session. So if your rdp session is open - all is fine, to leak you need close rdp window and connect again. Tested on Win10 1909/20H2 hosts.
- ~~I think amount of leaks are some how related to displaying property's, because some window leak more than others.~~

https://user-images.githubusercontent.com/17767561/118251665-8b585d80-b4b0-11eb-995f-ee2df025bf8c.mp4

Our scenario was: we have an mdi app with many child windows that's have `PropertyGrid`, for one rdp connect we losing about 100 GDI objects. So, after ~80 connects, our app was crushing. For now we monitor GDI objects count and restarting app when needed.

**Expected behavior:**
No GDI leak.

**Minimal repro:**
[GDI_test.zip](https://github.com/dotnet/winforms/files/6477978/GDI_test.zip)

**Comment by JeremyKuhne** [comment]
Interesting.  First guess here is that connecting probably fires WM_SETTINGCHANGE and that may be causing the color pickers to drop handles.

**Comment by kirsan31** [comment]
@JeremyKuhne 
> Interesting. First guess here is that connecting probably fires WM_SETTINGCHANGE and that may be causing the color pickers to drop handles.

I am afraid that the problem not in the property's (color pickers etc), but in the `PropertyGrid ` itself, because it's leak with this simple class as `SelectedObject`:
```cs
public class TestClass
{
    public int A { get; set; }
}
```

https://user-images.githubusercontent.com/17767561/118329356-8d9dd480-b50f-11eb-8938-d50b3aecb05d.mp4

**Comment by JeremyKuhne** [comment]
Thanks @kirsan31

**Comment by weltkante** [comment]
`WM_SETTINGCHANGE` causes the PropertyGrid to [reload its ImageList](https://github.com/dotnet/winforms/blob/d46ad2e8dc76248739d9ae22b28b399a6a6b299e/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs#L4427) without disposing the old one, leaking the handles owned by it. See also #4928 and #3567

There may be more things leaking, but disposing the ImageList before reassigning it helps fixing at least some of the leaks.

**Comment by RussKie** [comment]
Am I hearing it right that you're sending a PR? 😉

**Comment by weltkante** [comment]
> Am I hearing it right that you're sending a PR? 😉

Sure, was holding off since @JeremyKuhne was already investigating and I don't know how far he got, its better to coordinate than two people trying to do a PR for the same bug ;)

Also I think thats not the only leak here, but I couldn't see anything immediately obvious, probably needs further investigation. If you want a partial fix for just the ImageList disposal thats easily done.

**Comment by JeremyKuhne** [comment]
> its better to coordinate than two people trying to do a PR for the same bug ;)

@weltkante Thanks for investigating! By all means, please create a PR. :) I've been held up by other things and haven't been able to dig into it fully yet.

**Comment by RussKie** [comment]
I've run [GDI_test.zip](https://github.com/dotnet/winforms/files/6477978/GDI_test.zip) on a private build of #4952 in a VM, and I believe the immediate issue is addressed.
There is still a little GDI handle leak, that is connecting and disconnecting from the VM lead to slight increase in GDI handles, but all of them were collected back to the original starting point.

<details>
<summary>Screenshots</summary>

* Start
I didn't take a screenshot, but I think the GDI handles were at 54 each.

* Reconnect
![image](https://user-images.githubusercontent.com/4403806/119450856-dfe4be00-bd77-11eb-93aa-79c92d33df87.png)

* Again
![image](https://user-images.githubusercontent.com/4403806/119450818-d0fe0b80-bd77-11eb-88d7-ae6fe52821f1.png)

* Again
![image](https://user-images.githubusercontent.com/4403806/119450919-f25ef780-bd77-11eb-8635-1a6157b4a9a7.png)

* Again
![image](https://user-images.githubusercontent.com/4403806/119450959-00147d00-bd78-11eb-8274-cb2ca1467c0d.png)

* GC invoked
![image](https://user-images.githubusercontent.com/4403806/119450628-8a101600-bd77-11eb-8215-ad0a535c2287.png)

</details>

**Comment by Ashley-Li** [comment]
Verified this issue with 6.0.100-preview.5.21276.14 from Release/6.0.1XX-preview5 branch of https://github.com/dotnet/installer, it is fixed. Please see this result: [issue_4913_verify.zip](https://github.com/dotnet/winforms/files/6559466/issue_4913_verify.zip)

**Comment by Ashley-Li** [comment]
The issue also have been fixed in 5.0.8.
