### ISSUE TITLE
WinForms HighDPI PerMonitorV2 TextBox scales wrong

### ISSUE THREAD

**Issue by Balkoth** [dotnet/winforms#4929]
**.NET Core Version:**

SDK: 5.0.203 (383637d63f)
Runtime: 5.0.6 (478b2f8c0e)

**Problem description:**

If the main application window is not launched on the main monitor it scales the textbox and the used font wrong.

This is a screenshot from launching the application on the main display and dragging it onto the second screen:
![image](https://user-images.githubusercontent.com/80055480/118643526-f66da100-b7dc-11eb-832a-403474b181e3.png)

If i start the application on the second screen it looks like this:
![image](https://user-images.githubusercontent.com/80055480/118643579-07b6ad80-b7dd-11eb-8d8c-039740070985.png)

The font on the second screenshot is way to big.

**Minimal repro:**
- Create new .NET-Core 5.0 WinForms app
- Set Application.SetHighDpiMode(HighDpiMode.PerMonitorV2)
- Open the forms designer for Form1
- Set AutoScaleMode = Dpi
- Drag TextBox onto Form1
- Set textBox1 to Multiline and DockStyle.Fill
- Change font to Consolas 11 pt

I have prepared a sample app that also loads text from an embedded resource into the TextBox to directly show the problem here:
[DpiTextBoxTest.zip](https://github.com/dotnet/winforms/files/6500948/DpiTextBoxTest.zip)

**Comment by Balkoth** [comment]
There is another problem with the textbox: If you want to scroll to the caret position when the dpi of the form changes it only scroll the control on the primary display to the caret. On the secondary display it does not bring the caret into the view.

```cs
private void MainForm_DpiChanged(object sender, DpiChangedEventArgs e)
{
  this.textBox.ScrollToCaret();
}
```

**Comment by dreddy-work** [comment]
I can not repro this with current bits. @Balkoth, Can you get latest bits from this repo and see if you still repro? At runtime, window always launch on primary screen. So, wanted to understand the following.
>If i start the application on the second screen it looks like this:

@Olina-Zhang , can you try if you could repro this with latest bits from this repo?

**Comment by Balkoth** [comment]
Sorry but i only got a developer production machine, on which i can not use beta and preview versions.

**Comment by Olina-Zhang** [comment]
@dreddy-work Verified this issue in .Net 6.0 SDK build with latest bits from this repo. We cannot launch runtime on secondary screen, just on primary screen, and then move to secondary screen. It looks good. Here is the screenshot:
300% primary screen:
![TextBox_300%main](https://user-images.githubusercontent.com/26474449/121618802-0e61d900-ca9a-11eb-895b-d0f32c4f6afe.png)
Move to 100% secondary screen:
![TextBox_300%main_to100%sec](https://user-images.githubusercontent.com/26474449/121618850-233e6c80-ca9a-11eb-9c86-11a000b1a87c.png)

**Comment by Olina-Zhang** [comment]
@dreddy-work But if launching built exe on secondary screen, it repro, it seems an issue. see following screenshots:

Run exe on 100% secondary screen:
![TextBoxEXe_100%sec](https://user-images.githubusercontent.com/26474449/121620838-9695ad80-ca9d-11eb-9320-b95bdc5fa228.PNG)
Run exe on 300% secondary screen:
![TextBoxEXe_300%sec](https://user-images.githubusercontent.com/26474449/121620859-a0b7ac00-ca9d-11eb-8033-9d6e44df8ace.PNG)

**Comment by dreddy-work** [comment]
This is being worked on, Related to #4854

**Comment by dreddy-work** [comment]
@Olina-Zhang, can you please verify and close this issue?

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest 8.0 SDK build: 8.0.100-rc.1.23375.11, it was fixed:
**Launch application exe on 100% secondary screen:**
![image](https://github.com/dotnet/winforms/assets/26474449/c1116489-49f3-4d5e-9cdd-e2c3c4061394)

**Launch application exe on 300% secondary screen:**
![image](https://github.com/dotnet/winforms/assets/26474449/afc3d26f-4779-41fa-9f52-77d014da4f24)
