### ISSUE TITLE
WinForms HighDPI PerMonitorV2 MessageBox is blurry

### ISSUE THREAD

**Issue by Balkoth** [dotnet/winforms#4937]
**.NET Core Version:**

SDK: 5.0.203 (383637d63f)
Runtime: 5.0.6 (478b2f8c0e)

**Problem description:**

MessageBoxes not shown on the primary screen are blurry.

This is a screenshot showing a MessageBox on the main display:
![image](https://user-images.githubusercontent.com/80055480/118809319-c2f94800-b8aa-11eb-85a0-16a0c820f430.png)

This is a screenshot showing the same MessageBox but on the secondary display:
![image](https://user-images.githubusercontent.com/80055480/118809368-d4daeb00-b8aa-11eb-8c26-160c564962d3.png)

Everything on the second screenshot is blurry, except the window frame drawn by the dwm.

**Minimal repro:**
- Create new .NET-Core 5.0 WinForms app
- Set Application.SetHighDpiMode(HighDpiMode.PerMonitorV2)
- In Program.cs call MessageBox.Show

I have prepared a sample app here:
[DpiMessageBoxTest.zip](https://github.com/dotnet/winforms/files/6508482/DpiMessageBoxTest.zip)

**Comment by dreddy-work** [comment]
This is the Native messagebox window.  @Balkoth by any chance, did you try this with a native application?

**Comment by Balkoth** [comment]
No i did not.

**Comment by RussKie** [comment]
I'm going to close this as it is an OS level bug and there's little we can go on out end but to wait. I may wish to consider submitting a feedback via the Windows Hub.
