### ISSUE TITLE
ApplicationSettings PropertyBinding

### ISSUE THREAD

**Issue by russgreen** [dotnet/winforms#4941]
Apologies if this is not a WinForms issue but upgrading net48 apps to net50 results in the loss of access to ApplicationSettings PropertyBinding...e.g. https://www.dropbox.com/s/wakm27dyuprh6c1/Screenshot%202021-05-19%20145241.jpg?dl=0.  

Would love to see this supported in .net50 apps.

**Comment by RussKie** [comment]
Please provide a standalone simple repro.

**Comment by russgreen** [comment]
Take a look here https://github.com/russgreen/WinformsAppSettingsBindingSample

**Comment by KlausLoeffelmann** [comment]
Application Settings Binding is a feature which we have not yet enabled in the Designer.
The plan is to implement in the VS 17 timeframe.

**Comment by russgreen** [comment]
Glad to hear it’s not vanished for good.

**Comment by r-aghaei** [comment]
Meanwhile, for those who are looking for a workaround: [Databinding (property binding) to ApplicationSettings - Workaround](https://stackoverflow.com/a/70553881/3110834)

**Comment by merriemcgaw** [comment]
Thanks for the workaround @r-aghaei. We definitely have this feature on our radar for sometime in VS2022 (no firm release plans yet), so it is great to have this workaround in the interim!

**Comment by merriemcgaw** [comment]
There isn't much current customer demand for this feature. We can revisit when there is more.
