### ISSUE TITLE
[Loc] Assistance with translations

### ISSUE THREAD

**Issue by crsuzukimsft** [dotnet/winforms#4944]
For the resource "ParentControlDesignerGridSizeDescr" in the file https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf the translators have the following question:  It looks like two separate strings have been combined into one and without a period. I can find separate duplicate strings for "Place existing controls in new container, '{0}'." and "Determines the size of the positioning grid." For now, we have assumed that there is a period between the two sentences.

**Comment by RussKie** [comment]
@cristianosuzuki77 can you please have a look

**Comment by RussKie** [comment]
Right, hahaha :) I'll have a look

**Comment by Amy-Li03** [comment]
Verified the issue with .NET 6.0 6.0.100-preview.6.21322.9, it was fixed, now the resource "ParentControlDesignerGridSizeDescr" has correct resource string: "Determines the size of the positioning grid."
