### ISSUE TITLE
Right-anchored controls are cut off on the right of the Window/Form.

### ISSUE THREAD

**Issue by myokeeh** [dotnet/winforms#4947]
* .NET Core Version: 
5.0.203

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

Visual Studio 2019 (latest) Designer and running app's anchored listview and textbox don't behave the same way. They look fine in the designer, but running displays the right side beyond the window right border and are cut-off. They're anchored beyond the right side of the window. I don't recall which version, but believe this used to worked as it did with .NET Framework 4.8 on one of the preview versions of .NET 5. Window seems to run smaller (width and height) than what is shown in the Designer.

**Expected behavior:**
Visual Studio designer should reflect UI as it did with .NET Framework 4.8.

Visual Studio Designer
![image](https://user-images.githubusercontent.com/3663297/118930047-1e065b80-b8fa-11eb-967e-95004e65ae02.png)

Running app:
![image](https://user-images.githubusercontent.com/3663297/118930259-60c83380-b8fa-11eb-89aa-298758926a0d.png)

**Comment by myokeeh** [comment]
It appears I needed `Application.SetHighDpiMode(HighDpiMode.SystemAware);`

**Comment by merriemcgaw** [comment]
Did that fix your problem @myokeeh?

**Comment by kirsan31** [comment]
I think this must be related with #3168, #4838 (`AnchorStyles.Right` scaling problems).

**Comment by myokeeh** [comment]
@merriemcgaw yes on one app. still figuring it out on another.

**Comment by myokeeh** [comment]
@kirsan31 seems so.

**Comment by dreddy-work** [comment]
This does not repro with latest binaries in 6.0/7.0 branch here. I am closing the issue but feel free to reopen if you can repro it with latest release here.

![image](https://user-images.githubusercontent.com/36968667/140548780-129826b9-cd7d-424a-9140-7daa3f049399.png)
