### ISSUE TITLE
App freezes when tooltip in treeview showing

### ISSUE THREAD

**Issue by maxzav** [dotnet/winforms#4949]
* .NET Core Version: 
3.1, 5, 6-preview

* Have you experienced this same bug with .NET Framework?: 
Yes (checked on 4.8)

**Problem description:**
If the text is too long, the application freezes for very long time when trying to display the tooltip. For text with length 12000 app not responding about 1 minute on my pc.

**Expected behavior:**
No freezes, text in tooltip must be cutted.

**Minimal repro:**
[Github](https://github.com/maxzav/WindowsFormsAppTreeviewTooltipBug.git)
Run app, move mouse to item in tree to see tooltip - app freezes.

**Comment by RussKie** [comment]
Windows doesn't impose any limits on the length of a tooltip, so neither Windows Forms. 
Please refer to the [Tooltips and Infotips best practices doc](https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-tooltips-and-infotips), and modify your code to present a usable tooltip to your users.
