### ISSUE TITLE
Image handling is causing constant OOM errors

### ISSUE THREAD

**Issue by lxman** [dotnet/winforms#4963]
We have a project that makes heavy use of images. Basically speaking you have a PictureBox and we put in it a full sized png of an 8.5x11 page of text (the png's are mostly under about 1MB in size). Then we place controls (text boxes, etc.) over the places where the user needs to fill out text, etc.

This works well at runtime, but at design time, it's quite the nightmare. Basically speaking we can only work with one or two different forms (there are hundreds) and then the memory pressure in Visual Studio builds up and we start getting out of memory errors in the designer, and we have to unload the project, shut down Visual Studio and start all over again.

I realize that VS has memory issues of its own which are to be addressed in the 2022 version in theory but even with that it seems to me that the winforms aren't disposing these images properly. I would think that we could work with more than one or two before memory issues shut us down.

The project is currently in .NET framework v4.7.2.

**Comment by dreddy-work** [comment]
Thanks @lxman for reporting this. Given the nature of the issue, it may be hard for us to repro locally and investigate. Can you provide following information that help diagnose it further? 

- Dump when Visual Studio crashes? 
- A minimal repro app, if possible?
- Given that you are experiencing this issue in .NET 4.7.2, we have been working on improving the performance in .NET core, Is it possible to try your application on .NET core?

**Comment by lxman** [comment]
Moving to .NET core is not a possible option at this point. This project is probably has about 10 yrs worth of development in it with about 60 projects in the solution. I will do some research to find out how to get a dump when VS crashes. I will see if I can produce a minimal repro as my time permits.

**Comment by weltkante** [comment]
>  I will do some research to find out how to get a dump when VS crashes. I will see if I can produce a minimal repro as my time permits.

I think if you report the problem from within VS the workflow allows you to record steps to reproduce the problem. When it crashes as part of that repro I'd assume they record enough information to diagnose it. Overall, for VS-specific issues its often recommended to report then through the VS bug reporting infrastructure so they can capture additional context, seems like here it would be especially useful.

If you report it in VS you can leave a link here.
