### ISSUE TITLE
do Control.DesiredVisibility public

### ISSUE THREAD

**Issue by trivalik** [dotnet/winforms#4989]
**Is your feature request related to a problem? Please describe.**
Often logic set `Visible` property and wants to rely later on this set value. Making `Control.DesiredVisibility` public would allow this the easy way. This would reduce to introduce a extra flag for an already existing information.

**Describe the solution you'd like and alternatives you've considered**

Making `Control.DesiredVisibility` public would be the solution.

**Will this feature affect UI controls?**
No

**Comment by dreddy-work** [comment]
Can you share a business use case here? Any sample application where you can demonstrate the use of this property would help understand better.

**Comment by trivalik** [comment]
Please find attached example. 
[DemonstrateDesiredVisibility.zip](https://github.com/dotnet/winforms/files/6596156/DemonstrateDesiredVisibility.zip)

Here I try to order only the visible controls. This example is simple implementation of a more complex control reorganization.

**Comment by trivalik** [comment]
I found an additional situation. If you implement a LayoutEngine. We have conditions where asyncronous a condition appear that visible changes, then we force the layout update. In this case all controls are invisible. With `DesiredVisibility` a correct calculation could be made. Another thing would be why `PerformLayout` runs the layout also if Control is invisible.

**Comment by dreddy-work** [comment]
Thank you for reporting this @trivalik . We believe there are various events(HandleCreated, OnLoad or Show etc.) at the Control/Form level available to achieve what you were demonstrating in the sample app here. Given lack of community traction, we are closing this.

**Comment by trivalik** [comment]
Sure, but `Control.DesiredVisibility` would make is more easier.
