### ISSUE TITLE
Update documentation for `System.Windows.Forms.Design` namespace and designer-related classes in `System.ComponentModel.Design` to indicate that .NET 3*/5/6 types are not compatible with the VS 

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#4991]
Theses classes are provided to applications that are implementing IDE functionality outside the VS, for example ability to show and edit controls on the design surface.
 
Currently users are implementing outdated samples, to support VisualStudio design time experience, like this [one](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.design.irootdesigner?view=net-5.0)

See issue  https://github.com/dotnet/winforms/issues/4239

**Comment by RussKie** [comment]
@Tanya-Solyanik I'm happy to help but I'm not exactly sure what the target state is.

**Comment by Tanya-Solyanik** [comment]
I would document the current state.

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik Can you give a quick write up of what you'd like to see?

**Comment by merriemcgaw** [comment]
And would this be better moved to the docs repo?

**Comment by oudi** [comment]
outdated samples? Is there any other sample to support VisualStudio design time at .net core 3*/5/6？

**Comment by dreddy-work** [comment]
@Tanya-Solyanik / @RussKie / @merriemcgaw , what is the decision here. 7.0 milestone need to be closed.

**Comment by merriemcgaw** [comment]
Closing. We did do an update blog and @KlausLoeffelmann is getting samples and docs together.
