### ISSUE TITLE
Editing DropDownButton in StatusStrip

### ISSUE THREAD

**Issue by Njoro007** [dotnet/winforms#4999]
* .NET Core Version:  5.0.3

* Have you experienced this same bug with .NET Framework?:  No

**Problem description:**

    StatusLabel. Trying to rename label Text Name in the designer window and new text would only display after clicking outside the label component
    While typing new text for the statuslabel on the designer, Visual designer freezes until  I click outside the statusStrip. 

**Expected behavior:**

    Comparing with .NET Framework it works as expected. While renaming statusLabel Text it should behave like the MenuStrip.

**Minimal repro:**

    WinForm Project Open New Form
    Add StatusStrip
    Attemp to add and Custom text to StatusLabel

**Comment by dreddy-work** [comment]
Can you please share which version of the VisualStudio you are using here?

**Comment by Njoro007** [comment]
@dreddy-work VIsual Studio 16.10.0

**Comment by dreddy-work** [comment]
> @dreddy-work VIsual Studio 16.10.0

We have been working on menu strips and status strips in the designer in the latest previews.  expect it to be fixed soon there. keeping this open here for community visibility.

**Comment by Njoro007** [comment]
Works in VS 16.11.3

**Comment by RussKie** [comment]
Thank you for the follow up.
