### ISSUE TITLE
Remove unwanted comments from System.Windows.Forms code

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#50]
Feedback from @danmosemsft:

Remove comments like: 
/// <devdoc>
        ///    <para>[To be supplied.]</para>
/// </devdoc>

from ResXResourceWriter.cs and other files.

**Comment by garfbradaz** [comment]
A little unrelated but can Winforms repository make use of the same Dead Code analysis as CoreFX?

https://github.com/dotnet/corefx/issues/17905 

cc @ericstj

**Comment by ericstj** [comment]
I agree the dead code analysis would be good to get going on some of these new repositories.  It's another good testcase for the ILLinker (WPF especially, since it relies on internals and reflection heavily).
