### ISSUE TITLE
ListView evaluates all items in VirtualMode

### ISSUE THREAD

**Issue by MiloszKrajewski** [dotnet/winforms#5033]
* .NET Core Version: 
```
λ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

* Have you experienced this same bug with .NET Framework?: 
No. Actually, DEFINITELY NO.

**Problem description:**

`ListView` instantiates all list items even in virtual mode, for example:

```c#
public Form1()
{
	InitializeComponent();
	var counter = 0L;
	listView.VirtualMode = true;
	listView.VirtualListSize = 100_000_000;
	listView.RetrieveVirtualItem += (s, e) => e.Item = new ListViewItem {
		Text = $@"{e.ItemIndex} - {Interlocked.Increment(ref counter)}",
	};
}
```

This works perfectly fine in .NET Framework (tested with 4.7.2), yet in .NET 5 freezes UI for a long time as it creates all the items.
Note, it will become quick again while scrolling with scrollbar, but will recreate ALL items when any row is clicked!

**Expected behavior:**
Not freezing UI. Working as in .NET Framework.

**Minimal repro:**
[VirtualListView.zip](https://github.com/dotnet/winforms/files/6587700/VirtualListView.zip)
Attached solution with two projects: one targetting .NET 4.7.2 the other one .NET 5.
Same sources, different targets, different behaviours.

**Comment by RussKie** [comment]
@dreddy-work can you please investigate

**Comment by dreddy-work** [comment]
> @dreddy-work can you please investigate

Looks like new  accessibility pattern changes regressed this. @SergeySmirnov-Akvelon.

**Comment by dreddy-work** [comment]
@SergeySmirnov-Akvelon , Do you guys be able to look at this?

**Comment by John-Qiao** [comment]
Verified the issue in .NET 6.0.100-rc.1.21377.28 SDK from Master branch, this issue has been fixed that not freezing UI, and working as in .NET Framework.
![TestResult](https://user-images.githubusercontent.com/45864985/127284654-acedeb6d-93e4-4f91-bc00-9647cb176bce.gif)
