### ISSUE TITLE
merge some of the projects

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/winforms#5039]
So there is a resource overhead IDEs pay for each project. So where possible it would be nice to merge some of the projects, where having multiple projects adds little value. for example:

![image](https://user-images.githubusercontent.com/122666/120723929-10fe8480-c516-11eb-8a2f-66c227cdab09.png)

**Comment by RussKie** [comment]
Thank you for the nudge. 
These are machine automated integration UI (maui) tests projects that are run as own processes during the testing phase to test specific behavioural aspects that may be changing or dependent on process-wide state.

Redesigning our maui/integration tests is on our backlog, but it isn't something we can action now.
