### ISSUE TITLE
ListViewItem.ForeColor not work when mouse is over “Text” of the first row in the ListView

### ISSUE THREAD

**Issue by Jenna-Zheng** [dotnet/winforms#5040]
* .NET Core Version: 
.NET SDK 6.0.100-preview.6.21276.13

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
Color of the first item changed back to default.
![image](https://user-images.githubusercontent.com/64949616/120732551-19f05580-c518-11eb-95ad-ea79cd44f290.png)
![test](https://user-images.githubusercontent.com/64949616/120732978-dea25680-c518-11eb-8a23-0ca428b60825.gif)

**Expected behavior:**
Color of the first item should be Color.Fuchsia
![image](https://user-images.githubusercontent.com/64949616/120732659-473d0380-c518-11eb-8917-96f698d65b7d.png)

**Minimal repro:**
1. Extract the project and open it in VS [ListViewItemHoverChangeColor.zip](https://github.com/dotnet/winforms/files/6595164/ListViewItemHoverChangeColor.zip).
2. Run this app.
3. Set mouse is over “**Text**” of the first row in the **ListView** and press **down** key arrow to change selection, then observe it.

**Comment by RussKie** [comment]
@eriawan thank you for testing.

@Jenna-Zheng can you please retest, and close, if this no longer repros.

**Comment by John-Qiao** [comment]
@RussKie verified with the .NET 6.0.400 and latest .NET 7.0 SDK from main branch, this issue does not repro in them.
![TestResult3](https://user-images.githubusercontent.com/45864985/178951778-1ac13cbb-d0dd-46a5-a6bd-a821f0a09345.gif)
