### ISSUE TITLE
allow use GetPreferredSize caching in Control

### ISSUE THREAD

**Issue by trivalik** [dotnet/winforms#5061]
**Is your feature request related to a problem? Please describe.**
To allow easy to improve performance for custom controls on size/layout requests.

**Describe the solution you'd like and alternatives you've considered**

To be able to use the cache feature implemented in `GetPreferredSize` it would be necessary to make method GetPreferredSizeCore protected.
Additional a method to enable this caching as it for existing controls is done, would be required:
```
SetState2(STATE2_USEPREFERREDSIZECACHE, true);
``` 

**Will this feature affect UI controls?**
No. Only if activation function will be called.

**Comment by dreddy-work** [comment]
@trivalik, can you provide a sample application on what you would be doing without this today? And how this helps in that sample.

**Comment by trivalik** [comment]
I cannot provide sample application. I just found by inspecting code, that this feature can only be used for internal controls.

**Comment by RussKie** [comment]
This functionality has been like this for a long time. To change it we need to have a compelling use- and business cases, which require a sample of how it works (or doesn't work) today, what changes are necessary to overcome any shortcomings of the current API, as well as a thought-out proposal, detailing the solution. If you can't provide these, we can't take it further.

**Comment by trivalik** [comment]
I was just thinking on optimization, reuse already existing code. If this is not wanted, feel free to close it.

**Comment by RussKie** [comment]
Thank you for the suggestion. Closing until there's a compelling use case.
