### ISSUE TITLE
Update C# templates to top level statements

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#5071]
Top level statements have been released in .NET 5 and C# 9. There are a number of active internal discussion about updating other templates (e.g. ASP.NET Core) to use the top level statements approach.

As discussed in https://github.com/dotnet/designs/pull/223#discussion_r646978111 C# Windows Forms apps can be written as top level programs today as well, though `[STAThread]` make it a little awkward. So we can consider updating our application template
https://github.com/dotnet/winforms/blob/c76a4a49db18b4b88ed62170ffcb36f5f4718e50/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Program.cs#L1-L23
...and rewrite it as follows:
```cs
using System.Threading;
using System.Windows.Forms;
using Company.WinFormsApplication1;

// It is unfortunate but we have to set it to Unknown first.
Thread.CurrentThread.SetApartmentState(ApartmentState.Unknown);
Thread.CurrentThread.SetApartmentState(ApartmentState.STA);

Application.EnableVisualStyles();
Application.SetCompatibleTextRenderingDefault(defaultValue: false);
Application.SetHighDpiMode(HighDpiMode.PerMonitorV2);

Application.Run(new Form1());
```

When https://github.com/dotnet/designs/pull/223 will be implemented the template can be further simplified, and would look something like this:
```cs
using System.Threading;
using System.Windows.Forms;
using Company.WinFormsApplication1;

// It is unfortunate but we have to set it to Unknown first.
Thread.CurrentThread.SetApartmentState(ApartmentState.Unknown);
Thread.CurrentThread.SetApartmentState(ApartmentState.STA);

ApplicationConfiguration.Initialize();

Application.Run(new Form1());
```

And, generally speaking, there's nothing that prevents moving `Thread.CurrentThread.SetApartmentState(...)` calls into the source generated `ApplicationConfiguration.Initialize()` method:
```cs
using System.Threading;
using System.Windows.Forms;
using Company.WinFormsApplication1;

ApplicationConfiguration.Initialize();

Application.Run(new Form1());
```

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/121298454-3d136e80-c937-11eb-9b60-5ea95a3527ae.png)

**Comment by AraHaan** [comment]
I would rather the Application.Run() to also be moved to the Initialize method that is source generated and take in the form instance that should be new'd up in that call so it could be simplified to just:

```cs
// make these global usings in "GlobalUsings.cs".
using System.Threading;
using System.Windows.Forms;
using Company.WinFormsApplication1;

ApplicationConfiguration.Initialize(() =>new Form1());
```

So then in the end the actual Program.cs file *could* then be chopped down to just a single line of actual code with the Initialize method running that lambda inside when it calls Run for you.

**Comment by RussKie** [comment]
We won't be changing our templates to use the top level statements (https://github.com/dotnet/winforms/issues/5071). A typical Windows Forms app consist of multiple types split across multiple files (e.g. Form1.cs and Form1.Designer.cs) that won't work with top level statements.

**Comment by Amy-Li03** [comment]
Verified this issue with .NET 6.0 RC2 latest build: 6.0.10-rc.2.21429.3, when using ApplicationConfiguration.Initialize() method on Program class, winforms .NET core project can run successfully.
![image](https://user-images.githubusercontent.com/62929087/131307797-e818602a-5865-4063-b0f3-4b8e2b2b7d8f.png)

**Comment by AraHaan** [comment]
Does this mean it also adds the ``[main: STAThread]`` to the top level program in that case?

**Comment by RussKie** [comment]
AFAIK there is no such thing as `[main: STAThread]`, though it is being discussed.
In the case of top level statements `ApplicationConfiguration.Initialize()` emits this:
https://github.com/dotnet/winforms/blob/07f6de36d1dc4e86daccf4686ab222b950473673/src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilder.cs#L93-L95
