### ISSUE TITLE
Update C# templates with global usings

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#5074]
We can simplify our templates with [global usings](https://youtu.be/GJ_PaRNDe9E?t=1079) and have them implemented similar to this:

```diff
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework Condition="'$(TargetFrameworkOverride)' == ''">FrameworkParameter-windows</TargetFramework>
    <TargetFramework Condition="'$(TargetFrameworkOverride)' != ''">TargetFrameworkOverride-windows</TargetFramework>
    <RootNamespace Condition="'$(name)' != '$(name{-VALUE-FORMS-}safe_namespace)'">Company.WinFormsApplication1</RootNamespace>
    <LangVersion Condition="'$(langVersion)' != ''">$(ProjectLanguageVersion)</LangVersion>
    <Nullable Condition="'$(Nullable)' == 'true'">enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

+ <ItemGroup>
+   <Compile Include=".usings" />
+ </ItemGroup>

</Project>
```

A sample .using file:
```diff
global using System;
global using System.Collections.Generic;
global using System.Drawing;
global using System.Linq;
global using System.Threading.Tasks;
global using System.Windows.Forms;
```

This list of usings looks sensible, but it is up for a discussion.

Credits for this idea go to https://github.com/khalidabuhakmeh/CsharpTenFeatures.

At some point in the future when https://github.com/dotnet/aspnetcore/issues/32451 settles, we could follow in their steps and bake all typical Windows Forms usings into the Windows Desktop SDK.

**Comment by AraHaan** [comment]
I would rather name the file ``GlobalUsings.cs`` 🤔.

Bonus points: using json to store the using directives that should be global then use a source generator to generate the global usings code file.

**Comment by RussKie** [comment]
> I would rather name the file `GlobalUsings.cs` 🤔.

Why?



> Bonus points: using json to store the using directives that should be global then use a source generator to generate the global usings code file. In which case I think using a json file to store the global usings is a good idea.

Why? And why do we need source generators here?

**Comment by AraHaan** [comment]
> > I would rather name the file `GlobalUsings.cs` 🤔.
> 
> Why?
So that way the user could clearly see where the usings are.

> > Bonus points: using json to store the using directives that should be global then use a source generator to generate the global usings code file. In which case I think using a json file to store the global usings is a good idea.
> 
> Why? And why do we need source generators here?
I just stated it as a possible option that a developer *could* opt into to have the global usings file get source generated for them based on a json file to define which global users it should contain.

**Comment by RussKie** [comment]
This work is currently blocked by https://github.com/dotnet/sdk/pull/18459/files

**Comment by DamianEdwards** [comment]
@RussKie the SDK feature was just merged. The epic has been updated with details of which namespaces are imported by default by the various SDKs. Please add the details for WinForms at your convenience.

**Comment by RussKie** [comment]
Refer to https://github.com/dotnet/sdk/issues/19521 for new directions.

**Comment by DamianEdwards** [comment]
@RussKie are you planning to bring this change through ASK mode for rc.1?
