### ISSUE TITLE
Disallow pasting invisible control characters in TextBox

### ISSUE THREAD

**Issue by hyperquantum** [dotnet/winforms#5078]
**Is your feature request related to a problem? Please describe.**

I recently had to debug a problem in our WinForms application that was caused by the presence of an invisible control character (0x1F) in a string that was supposed to be an e-mail address. Our software validates e-mail addresses when entered, but this hasn't always been the case. I figured that the invalid character was probably entered a long time ago, before we did any input validation on that field. But this problem can also occur when dealing with fields that are more free form, like a street name or a comment. A user might copy-paste some text into a TextBox without noticing the presence of an invisible control character.

**Describe the solution you'd like and alternatives you've considered**

Of course, one could attach some kind of generic validation to each TextBox in an application that rejects the content if it contains any control characters. But wouldn't it be preferable to simply automatically filter out any invisible control characters when a paste operation is done on a TextBox? I suppose that in the majority of the cases the presence of control characters in text fields is unintentional.

Proposal:  
Add a new property "AcceptsControlChars" to TextBox (or TextBoxBase). When this property is true, the control acts like it has always done. When this property is false, any control char that is typed is ignored, and any text that is pasted is run through a filter that removes control chars. Control chars in this context are defined as those characters that are non-printable and that aren't whitespace. Newlines aren't considered to be control characters; their presence is already regulated by the Multiline/AcceptsReturn properties. Tabs are also not considered to be control characters in this context; their presence is regulated by the AcceptsTab property.

Ideally, the default value of this new property would be false. But I'm afraid that this may break existing applications, so we probably have no other choice than making it true by default.

When this new property is set to false, the messagebox in the following code can never appear:
```
private void textBox1_TextChanged(object sender, EventArgs e)
{
    if (textBox1.Text.Any(c => char.IsControl(c) && !new[] { '\n', '\r', '\t' }.Contains(c)))
    {
        MessageBox.Show("Control character found!");
    }
}
```

**Will this feature affect UI controls?**

Yes (minor).
VS Designer would need to display the new property. I don't know if this would affect accessibility, but I guess probably not. The description of the property would need to be localized.

**Comment by weltkante** [comment]
While I'm not against this proposal, I don't think it actually solves your problem, there are plenty "invisible" unicode characters not categorized as [control characters](https://www.compart.com/en/unicode/category/Cc) that are common to appear in the modern international web. For example take [zero width spaces](https://en.wikipedia.org/wiki/Zero-width_space), [soft hyphens](https://en.wikipedia.org/wiki/Soft_hyphen), [bidirectional markers](https://www.w3.org/International/questions/qa-bidi-unicode-controls), [join hints for ligatures](https://devblogs.microsoft.com/oldnewthing/20121114-00/?p=6093), etc.

In other words, this property would solve one specific instance of your problem, but you'd eventually run into cases where `char.IsControl` does not properly characterize the input you want to filter.

Maybe you can argue to also exclude [format characters](https://www.compart.com/en/unicode/category/Cf) - some of them are clearly things you'd want to filter in the usecase you have given, but others are important to produce a visually distinguishable output.

In the end I don't think there is any way around doing domain-specific input validation. That said, if the WinForms team thinks filtering out specifically control characters from the input of a textbox is valuable, I'm not against adding such a property. Just wanted to mention that it _might_ be too short sighted to just look at control characters.

**Comment by RussKie** [comment]
I agree with @weltkante's assessment, this proposal targets a rather specific use case. As your examples show it is easy to implement a functionality that addresses your requirements, so I can't see a compelling reason to have this functionality baked into the SDK.
Alternatively you may wish to check out [`MaskedTextBox`](https://docs.microsoft.com/dotnet/api/system.windows.forms.maskedtextbox), and see if it's better suited for your needs.
