### ISSUE TITLE
Painting bug in IconEditor

### ISSUE THREAD

**Issue by cadilhac** [dotnet/winforms#5092]
* .NET Core Version: 
Any

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
The problem happens in System.Drawing.Design.IconEditor.PaintValue.

```
public override void PaintValue(PaintValueEventArgs e)
{
    if (!(e?.Value is Icon icon))
    {
        return;
    }

    // If icon is smaller than rectangle, just center it unscaled in the rectangle
    Rectangle rectangle = e.Bounds;
    if (icon.Width < rectangle.Width)
    {
        rectangle.X = (rectangle.Width - icon.Width) / 2;
        rectangle.Width = icon.Width;
    }

    if (icon.Height < rectangle.Height)
    {
        rectangle.X = (rectangle.Height - icon.Height) / 2;
        rectangle.Height = icon.Height;
    }

    e.Graphics.DrawIcon(icon, rectangle);
}

```
When the icon size is smaller than the provided bounds, the X position is reset as if it was expected to be initially 0. Actually, I guess this code is only called by the MS PropertyGrid and it works well in that case, surely because the provided bounds has X==0.
In my code where I manually ask this editor to paint its value on some bounds inside a window, this makes the drawing appear on the left side of the window instead of in the provided bounds. The solution would be to call rectangle.X += ..... instead of X = ..... This would not break the existing code (for instance the MS PropertyGrid that calls PaintValue) and it would allow custom codes like mine to also behave correctly.

**Expected behavior:**
The painting should occur in the provided bounds.

**Minimal repro:**
Not easy to provide some repro code.

**Comment by RussKie** [comment]
Are you in a position to submit a fix?



> Not easy to provide some repro code.

This makes it hard to triage and fix

**Comment by cadilhac** [comment]
> Are you in a position to submit a fix?

Yes. As I said, replacing "X = " by "X += " fixes it.

**Comment by weltkante** [comment]
looking at the code you copy-pasted it seems the vertical adjustment code is setting `X` instead of `Y` - which is likely to be another bug

> Not easy to provide some repro code.

Why is that so? Can't you just obtain an editor from the TypeDescriptor infrastructure and invoke it to present your scenario, say, in the paint handler of a panel or something?

**Comment by cadilhac** [comment]
> Why is that so? Can't you just obtain an editor from the TypeDescriptor infrastructure and invoke it to present your scenario, say, in the paint handler of a panel or something?

You're right. Finally did a repro code that also includes the fix. Here it is.
[IconEditorBug.zip](https://github.com/dotnet/winforms/files/6657531/IconEditorBug.zip)

**Comment by elachlan** [comment]
@Olina-Zhang can your team please verify this bug?

**Comment by John-Qiao** [comment]
@elachlan yes, we still can repro this issue using that [IconEditorBug.zip](https://github.com/dotnet/winforms/files/13263067/IconEditorBug.zip) project with latest .NET 9.0 SDK.

![5092-testresult](https://github.com/dotnet/winforms/assets/45864985/63d4ca72-60a0-4aa3-afa3-c43c5b139475)

**Comment by Nora-Zhou01** [comment]
Verified this on .NET 9.0.100-alpha.1.23564.26 + private dlls(build from main branch of WinForms repo), issue was fixed. The painting occur in the provided bounds.
![5092](https://github.com/dotnet/winforms/assets/104609169/7ff83df3-9948-461c-9aa5-f1b527a6b6b0)
