### ISSUE TITLE
TextRenderer.MeasureText is very slow

### ISSUE THREAD

**Issue by alanhoman** [dotnet/winforms#5093]
* .NET Core Version: 
6.0.0-preview.4.21254.5

**Problem description:**
The performance of TextRenderer.MeasureText has significantly degraded.  I think the issue is with the .Net 6.0 changes to Control.Font, but it may be something else as well.   When I run the code snippet below here are the performance numbers:

.NET Framework 4.8: **179 ms**
.NET 5.0: **262 ms**
.NET 6.0: **5,646 ms**  **(31x slower)**
```
public void MeasureTextTest()
{
    for (int i = 0; i < 10000; i++)
    {
        TextRenderer.MeasureText("Test String", this.Font);
    }
}
```
This is very important functionality for my company because it is used to set the column widths on ListView. We have thousands of these and many have at least 10 columns and 1,000 rows.  The 5+ second delay is significant especially when a form has more than one long ListView.  Forms that took 500ms to open in .NET 5.0 are now taking 20+ seconds in .NET 6.0 which is completely unusable.

**Comment by RussKie** [comment]
Can you share the benchmarks you used to measure this? The snippet alone is not very meaningful.

**Comment by alanhoman** [comment]
Here is a repo.  It runs in 5,000 ms. on .NET 6.0.  If you change the project to .NET 5.0, it runs in 250 ms.

[MeasureTextSample.zip](https://github.com/dotnet/winforms/files/6651585/MeasureTextSample.zip)

**Comment by RussKie** [comment]
Run a [simple benchmark](https://github.com/RussKie/WinFormsBenchmarks/blob/master/Benchmarks/TextRendererBenchmarks.cs), indeed it looks like we have been regressing since .NET Core days... Now need to identify whether the regression is in our codebase or in the underlying .NET runtime.
/cc: @JeremyKuhne @safern 

``` ini

BenchmarkDotNet=v0.12.1.1513-nightly, OS=Windows 10.0.19043
Intel Core i7-4930K CPU 3.40GHz (Haswell), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.100-preview.6.21309.26
  [Host]     : .NET 6.0.0 (6.0.21.30601), X64 RyuJIT
  Job-EZFZUX : .NET 5.0.7 (5.0.721.25508), X64 RyuJIT
  Job-JSACWP : .NET 6.0.0 (6.0.21.30601), X64 RyuJIT
  Job-VGOPYP : .NET Core 3.1.16 (CoreCLR 4.700.21.26205, CoreFX 4.700.21.26205), X64 RyuJIT
  Job-KSXRFF : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT


```
|      Method |        Job |              Runtime |      Toolchain | iterations |         Mean |       Error |      StdDev | Ratio | RatioSD | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |----------- |--------------------- |--------------- |----------- |-------------:|------------:|------------:|------:|--------:|------:|------:|------:|----------:|
| **MeasureText** | **Job-EZFZUX** |             **.NET 5.0** | **net5.0-windows** |         **10** |     **283.8 μs** |     **5.58 μs** |     **7.64 μs** |  **1.55** |    **0.05** |     **-** |     **-** |     **-** |     **472 B** |
| MeasureText | Job-JSACWP |             .NET 6.0 | net6.0-windows |         10 |     282.0 μs |     1.53 μs |     1.44 μs |  1.54 |    0.02 |     - |     - |     - |     497 B |
| MeasureText | Job-VGOPYP |        .NET Core 3.1 |   netcoreapp31 |         10 |     196.4 μs |     1.78 μs |     1.58 μs |  1.08 |    0.01 |     - |     - |     - |     450 B |
| MeasureText | Job-KSXRFF | .NET Framework 4.7.2 |         net472 |         10 |     182.7 μs |     2.05 μs |     1.82 μs |  1.00 |    0.00 |     - |     - |     - |     860 B |
|             |            |                      |                |            |              |             |             |       |         |       |       |       |           |
| **MeasureText** | **Job-EZFZUX** |             **.NET 5.0** | **net5.0-windows** |        **100** |   **2,778.1 μs** |    **25.34 μs** |    **23.70 μs** |  **1.55** |    **0.02** |     **-** |     **-** |     **-** |     **472 B** |
| MeasureText | Job-JSACWP |             .NET 6.0 | net6.0-windows |        100 |   2,807.6 μs |    23.09 μs |    21.60 μs |  1.56 |    0.02 |     - |     - |     - |     509 B |
| MeasureText | Job-VGOPYP |        .NET Core 3.1 |   netcoreapp31 |        100 |   1,933.1 μs |    11.26 μs |    10.54 μs |  1.08 |    0.01 |     - |     - |     - |     448 B |
| MeasureText | Job-KSXRFF | .NET Framework 4.7.2 |         net472 |        100 |   1,795.0 μs |    12.58 μs |    11.77 μs |  1.00 |    0.00 |     - |     - |     - |   4,480 B |
|             |            |                      |                |            |              |             |             |       |         |       |       |       |           |
| **MeasureText** | **Job-EZFZUX** |             **.NET 5.0** | **net5.0-windows** |      **10000** | **274,098.5 μs** | **2,271.52 μs** | **2,013.64 μs** |  **1.51** |    **0.05** |     **-** |     **-** |     **-** |   **5,896 B** |
| MeasureText | Job-JSACWP |             .NET 6.0 | net6.0-windows |      10000 | 280,867.9 μs | 1,798.71 μs | 1,682.51 μs |  1.55 |    0.05 |     - |     - |     - |   3,872 B |
| MeasureText | Job-VGOPYP |        .NET Core 3.1 |   netcoreapp31 |      10000 | 185,448.3 μs | 1,117.60 μs |   990.72 μs |  1.02 |    0.03 |     - |     - |     - |   2,680 B |
| MeasureText | Job-KSXRFF | .NET Framework 4.7.2 |         net472 |      10000 | 179,639.0 μs | 3,533.11 μs | 4,468.26 μs |  1.00 |    0.00 |     - |     - |     - | 404,139 B |

**Comment by RussKie** [comment]
It is quite bizarre, `SystemFonts.DefaultFont` allocates for each call, and thus suffers a perf hit. Using `control.Font` and a local variables appears to be equally performant.

``` ini

BenchmarkDotNet=v0.12.1.1513-nightly, OS=Windows 10.0.19043
Intel Core i7-4930K CPU 3.40GHz (Haswell), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.100-preview.6.21309.26
  [Host]     : .NET 6.0.0 (6.0.21.30601), X64 RyuJIT
  Job-DQATVH : .NET 5.0.7 (5.0.721.25508), X64 RyuJIT
  Job-ZJUHAJ : .NET 6.0.0 (6.0.21.30601), X64 RyuJIT
  Job-BCAVMD : .NET Core 3.1.16 (CoreCLR 4.700.21.26205, CoreFX 4.700.21.26205), X64 RyuJIT
  Job-QALNKX : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT


```
|                  Method |        Job |              Runtime |      Toolchain | iterations |           Mean |        Error |       StdDev | Ratio | RatioSD |     Gen 0 |     Gen 1 | Gen 2 |    Allocated |
|------------------------ |----------- |--------------------- |--------------- |----------- |---------------:|-------------:|-------------:|------:|--------:|----------:|----------:|------:|-------------:|
| **MeasureText_ControlFont** | **Job-DQATVH** |             **.NET 5.0** | **net5.0-windows** |         **10** |       **283.9 μs** |      **4.99 μs** |      **4.67 μs** |  **1.54** |    **0.04** |         **-** |         **-** |     **-** |          **3 B** |
| MeasureText_ControlFont | Job-ZJUHAJ |             .NET 6.0 | net6.0-windows |         10 |       290.3 μs |      5.68 μs |      9.17 μs |  1.58 |    0.05 |         - |         - |     - |            - |
| MeasureText_ControlFont | Job-BCAVMD |        .NET Core 3.1 |   netcoreapp31 |         10 |       198.3 μs |      3.71 μs |      4.13 μs |  1.08 |    0.03 |         - |         - |     - |            - |
| MeasureText_ControlFont | Job-QALNKX | .NET Framework 4.7.2 |         net472 |         10 |       184.2 μs |      3.34 μs |      4.23 μs |  1.00 |    0.00 |         - |         - |     - |        402 B |
|                         |            |                      |                |            |                |              |              |       |         |           |           |       |              |
| MeasureText_DefaultFont | Job-DQATVH |             .NET 5.0 | net5.0-windows |         10 |     1,330.3 μs |     25.06 μs |     27.86 μs |  0.95 |    0.04 |         - |         - |     - |      4,960 B |
| MeasureText_DefaultFont | Job-ZJUHAJ |             .NET 6.0 | net6.0-windows |         10 |     1,345.6 μs |     26.59 μs |     63.18 μs |  1.00 |    0.05 |         - |         - |     - |      4,960 B |
| MeasureText_DefaultFont | Job-BCAVMD |        .NET Core 3.1 |   netcoreapp31 |         10 |     1,108.9 μs |     26.84 μs |     77.43 μs |  0.81 |    0.05 |         - |         - |     - |      2,480 B |
| MeasureText_DefaultFont | Job-QALNKX | .NET Framework 4.7.2 |         net472 |         10 |     1,397.4 μs |     27.05 μs |     36.12 μs |  1.00 |    0.00 |    1.9531 |         - |     - |     12,768 B |
|                         |            |                      |                |            |                |              |              |       |         |           |           |       |              |
|   MeasureText_LocalFont | Job-DQATVH |             .NET 5.0 | net5.0-windows |         10 |       274.8 μs |      4.18 μs |      3.71 μs |  1.38 |    0.03 |         - |         - |     - |            - |
|   MeasureText_LocalFont | Job-ZJUHAJ |             .NET 6.0 | net6.0-windows |         10 |       276.7 μs |      5.40 μs |      6.00 μs |  1.39 |    0.03 |         - |         - |     - |            - |
|   MeasureText_LocalFont | Job-BCAVMD |        .NET Core 3.1 |   netcoreapp31 |         10 |       184.9 μs |      1.67 μs |      1.39 μs |  0.93 |    0.02 |         - |         - |     - |            - |
|   MeasureText_LocalFont | Job-QALNKX | .NET Framework 4.7.2 |         net472 |         10 |       199.3 μs |      3.20 μs |      2.67 μs |  1.00 |    0.00 |         - |         - |     - |        402 B |
|                         |            |                      |                |            |                |              |              |       |         |           |           |       |              |
| **MeasureText_ControlFont** | **Job-DQATVH** |             **.NET 5.0** | **net5.0-windows** |      **10000** |   **284,404.2 μs** |  **5,555.77 μs** |  **9,730.49 μs** |  **1.61** |    **0.06** |         **-** |         **-** |     **-** |            **-** |
| MeasureText_ControlFont | Job-ZJUHAJ |             .NET 6.0 | net6.0-windows |      10000 |   280,485.2 μs |  4,104.00 μs |  3,427.02 μs |  1.58 |    0.03 |         - |         - |     - |        312 B |
| MeasureText_ControlFont | Job-BCAVMD |        .NET Core 3.1 |   netcoreapp31 |      10000 |   195,399.9 μs |  3,768.62 μs |  4,766.09 μs |  1.10 |    0.03 |         - |         - |     - |            - |
| MeasureText_ControlFont | Job-QALNKX | .NET Framework 4.7.2 |         net472 |      10000 |   177,760.7 μs |  2,580.46 μs |  2,287.51 μs |  1.00 |    0.00 |         - |         - |     - |    401,408 B |
|                         |            |                      |                |            |                |              |              |       |         |           |           |       |              |
| MeasureText_DefaultFont | Job-DQATVH |             .NET 5.0 | net5.0-windows |      10000 | 1,323,331.5 μs | 26,221.54 μs | 26,927.59 μs |  0.95 |    0.03 |         - |         - |     - |  4,960,936 B |
| MeasureText_DefaultFont | Job-ZJUHAJ |             .NET 6.0 | net6.0-windows |      10000 | 1,320,875.5 μs | 16,110.60 μs | 12,578.09 μs |  0.95 |    0.01 |         - |         - |     - |  4,963,864 B |
| MeasureText_DefaultFont | Job-BCAVMD |        .NET Core 3.1 |   netcoreapp31 |      10000 | 1,061,158.3 μs | 17,930.88 μs | 16,772.56 μs |  0.76 |    0.02 |         - |         - |     - |  2,480,000 B |
| MeasureText_DefaultFont | Job-QALNKX | .NET Framework 4.7.2 |         net472 |      10000 | 1,397,382.6 μs | 20,706.98 μs | 16,166.65 μs |  1.00 |    0.00 | 2000.0000 | 1000.0000 |     - | 12,763,256 B |
|                         |            |                      |                |            |                |              |              |       |         |           |           |       |              |
|   MeasureText_LocalFont | Job-DQATVH |             .NET 5.0 | net5.0-windows |      10000 |   284,759.9 μs |  5,421.99 μs |  6,658.69 μs |  1.47 |    0.05 |         - |         - |     - |            - |
|   MeasureText_LocalFont | Job-ZJUHAJ |             .NET 6.0 | net6.0-windows |      10000 |   278,581.5 μs |  5,309.82 μs |  6,114.79 μs |  1.42 |    0.04 |         - |         - |     - |      4,644 B |
|   MeasureText_LocalFont | Job-BCAVMD |        .NET Core 3.1 |   netcoreapp31 |      10000 |   186,094.7 μs |  3,474.80 μs |  3,718.00 μs |  0.96 |    0.02 |         - |         - |     - |            - |
|   MeasureText_LocalFont | Job-QALNKX | .NET Framework 4.7.2 |         net472 |      10000 |   194,823.5 μs |  3,768.39 μs |  3,524.96 μs |  1.00 |    0.00 |         - |         - |     - |    401,408 B |

**Comment by weltkante** [comment]
> Here is a repo. It runs in 5,000 ms. on .NET 6.0.

The repo does not reproduce the regression by itself, I suspect your test environment contains additional aspects required to reproduce the significant regression you are seeing. I'm running 100% DPI (no HiDPI machine) and I'm using the stock default fonts of an european windows installation. Neither `6.0.0-preview.4.21254.5` nor the current nightly build observe the regression.

I think you need to provide additional information about your testing environment, or perform the test on multiple machines yourself, to make sure the right regression is identified.

Also, while the Font accessor may contain a minor regression I'm not sure its guaranteed to be the same one the OP is seeing - I'd like to verify whether what he's seeing is different, so he probably should move the font access out of the loop and see if it still regresses. As it stands his benchmark tests TextRenderer + Font accessor in combination, so its impossible to isolate where his observations are coming from.

**Comment by alanhoman** [comment]
I was using the guide in debugging.md,  Method 2: **Point your project to your experimental binary(-ies)**.  I realized this was the debug version so when I built the release version and changed the references (as shown below), it went from 5,000 ms down to 245 ms.  

I think this can be closed, but I have the following suggestions and questions:

1. It might be good in debugging.md to state that for performance testing, the references should be changed to Release.
2. In most cases, it seems like including System.Windows.Forms.Primitives.dll is required because the method signatures for the daily builds almost always differ from the most recently released beta SDK.  I finally figured out that adding this System.Windows.Forms.Primitives.dll reference fixed the issues I was having with testing and it might be good to add this to the debugging.md instructions.
3. Is Method 2 the best approach?  It seems like it is because method 1 is more invasive and permanently changes the installed SDK.

```
  <ItemGroup>
    <Reference Include="[repo]\artifacts\bin\System.Windows.Forms\Release\net6.0\System.Windows.Forms.dll" />
    <Reference Include="[repo]\artifacts\bin\System.Windows.Forms\Release\net6.0\System.Windows.Forms.Primitives.dll" />
  </ItemGroup>
```

**Comment by RussKie** [comment]
I've run font-only benchmarks, and creating a font is significantly faster. It also doesn't appear to be significant for the text measuring.
``` ini

BenchmarkDotNet=v0.12.1.1513-nightly, OS=Windows 10.0.19043
Intel Core i7-4930K CPU 3.40GHz (Haswell), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.100-preview.6.21309.26
  [Host]     : .NET 6.0.0 (6.0.21.30601), X64 RyuJIT
  Job-TCWUUN : .NET 5.0.7 (5.0.721.25508), X64 RyuJIT
  Job-OYQHEP : .NET 6.0.0 (6.0.21.30601), X64 RyuJIT
  Job-LXPUKN : .NET Core 3.1.16 (CoreCLR 4.700.21.26205, CoreFX 4.700.21.26205), X64 RyuJIT
  Job-ZIRAMO : .NET Framework 4.8 (4.8.4300.0), X64 RyuJIT


```
|            Method |        Job |              Runtime |      Toolchain |         Mean |       Error |      StdDev | Ratio | RatioSD |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
|------------------ |----------- |--------------------- |--------------- |-------------:|------------:|------------:|------:|--------:|-------:|-------:|-------:|----------:|
|        CreateFont | Job-TCWUUN |             .NET 5.0 | net5.0-windows |     647.7 ns |    12.89 ns |    14.33 ns |  0.29 |    0.01 | 0.0153 | 0.0076 |      - |      96 B |
|        CreateFont | Job-OYQHEP |             .NET 6.0 | net6.0-windows |     642.5 ns |    12.78 ns |    18.32 ns |  0.29 |    0.01 | 0.0153 | 0.0076 | 0.0010 |      96 B |
|        CreateFont | Job-LXPUKN |        .NET Core 3.1 |   netcoreapp31 |     672.8 ns |    13.00 ns |    13.35 ns |  0.30 |    0.01 | 0.0153 | 0.0076 |      - |      96 B |
|        CreateFont | Job-ZIRAMO | .NET Framework 4.7.2 |         net472 |   2,237.5 ns |    40.58 ns |    52.77 ns |  1.00 |    0.00 | 0.0572 | 0.0267 |      - |     369 B |
|                   |            |                      |                |              |             |             |       |         |        |        |        |           |
| SystemDefaultFont | Job-TCWUUN |             .NET 5.0 | net5.0-windows |  73,230.1 ns | 1,460.39 ns | 2,230.18 ns |  0.74 |    0.03 |      - |      - |      - |     248 B |
| SystemDefaultFont | Job-OYQHEP |             .NET 6.0 | net6.0-windows |  73,502.4 ns | 1,424.23 ns | 2,174.95 ns |  0.73 |    0.03 |      - |      - |      - |     248 B |
| SystemDefaultFont | Job-LXPUKN |        .NET Core 3.1 |   netcoreapp31 |  73,137.7 ns | 1,384.72 ns | 1,648.41 ns |  0.72 |    0.02 |      - |      - |      - |     248 B |
| SystemDefaultFont | Job-ZIRAMO | .NET Framework 4.7.2 |         net472 | 100,858.1 ns | 1,252.97 ns | 1,110.73 ns |  1.00 |    0.00 | 0.1221 |      - |      - |   1,236 B |

**Comment by safern** [comment]
It looks like SystemFonts are expensive because we need to consider user settings like culture settings, etc. I.e in arabic the default font is `Tahoma` not `Segoe UI`. So I guess that is where the expensive part comes into play.

**Comment by RussKie** [comment]
> 1. It might be good in debugging.md to state that for performance testing, the references should be changed to Release.

Feel free to open a PR and propose an update to the doc.



> 3\. Is Method 2 the best approach? It seems like it is because method 1 is more invasive and permanently changes the installed SDK.

If you make a backup, it isn't. It is possible to "Repair" the installation as well, but certainly requires more time.
From the personal experience Method 2 may not work in all test scenarios.

I have a script that deploys local binaries and reverts the deployment, you're welcome to give it a go: https://gist.github.com/RussKie/bb11e213f04729603e533856865922c1
