### ISSUE TITLE
[Multi-Monitor] The form has scrollbar when DPIs differ

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#5102]
* .NET Core Version: 
.NET SDK 6.0.100-preview.6.21313.2 + private binaries build from main branch in dotnet/winforms repo [Private dlls.zip](https://github.com/dotnet/winforms/files/6654131/Private.dlls.zip)

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The form has scrollbar when moving it from 300% primary screen to 100% secondary screen.
![Move-300-to-100](https://user-images.githubusercontent.com/45864985/122022170-ef947700-cdf8-11eb-9a1d-7e9352aafb88.png)

**Expected behavior:**

The form should not has the scrollbar, like it works in 300% primary screen.
![300](https://user-images.githubusercontent.com/45864985/122022629-5c0f7600-cdf9-11eb-880d-8915abd620af.png)

**Minimal repro:**

1. Set the primary screen as 300% DPI, and second screenshot as 100% DPI.
2. Open and run the test app [PerMonitorHDPCore.zip](https://github.com/dotnet/winforms/files/6654178/PerMonitorHDPCore.zip) on the 300% primary screen.
3. Click the **Simple Layout** button to open form and move it to 100% DPI second screen, the observe the scrollbar in the moved form.

**More info:**

1. Just repro in PerMonitorV2 mode with Form's AutoScaleMode: Font, cannot repro Form's AutoScaleMode: DPI.
2. Cannot repro in SystemAware mode, since this issue is in secondary screen.
3. Also repro in without privates.

**Comment by Olina-Zhang** [comment]
Verified this issue in the .Net 8.0 + dlls built from Winforms main repo, it is fixed now. Closing this issue.

300% main screen:
![image](https://user-images.githubusercontent.com/26474449/202978031-7ff8e8bb-adb8-4784-b5be-2d631a2a9ffc.png)
Move to 100% secondary screen without scrollbar for form
![image](https://user-images.githubusercontent.com/26474449/202978222-16520e0a-31db-42ab-b675-06d7eebd2a2f.png)
