### ISSUE TITLE
[HDPI] The warning properties window is not scaled properly when running on 300% DPI

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#5111]
* .NET Core Version: 
.NET SDK 6.0.100-preview.6.21313.2

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**

On 300% DPI machine, the warning properties window is not scaled properly, see screenshot as below:
![Actual](https://user-images.githubusercontent.com/45864985/122153070-d3deae80-ce94-11eb-8cce-bdf716b145b0.png)

**Expected behavior:**

The warning properties window should be scaled properly as 100% DPI.
![Expected](https://user-images.githubusercontent.com/45864985/122153073-d5a87200-ce94-11eb-962c-24db477b5eee.png)

**Minimal repro:**

1. Set Windows DPI as 300%, create a .NET Core Winforms application.
2. Focus on form designer, and go to **Properties** window.
3. In **Properties** window, go to **BackColor** property, and type a string "fgjj" to it, and press **Enter**.
4. Related VSO bug: [389044](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/389044)

**Comment by dreddy-work** [comment]
@John-Qiao , Can you please attach GIF on how you reproduce this? This window is opening in 'SystemAware' mode for me always. Did you check the DPI awareness of the window displayed?

**Comment by John-Qiao** [comment]
@dreddy-work it can repro in 2 DPI modes: PerMonitorV2/SystemAware for form's AutoScaleMode: Font/DPI when testing in PropertyGrid control. Please check below gif file:
![TestResult3](https://user-images.githubusercontent.com/45864985/122323888-6a28d800-cf5a-11eb-984a-8663ab95b3fd.gif)

And it can repro in **Properties** window when open form in design time too, Please check below gif file:
![TestResult1](https://user-images.githubusercontent.com/45864985/122322594-495f8300-cf58-11eb-8d3a-9faa50d469f1.gif)

**Comment by merriemcgaw** [comment]
@John-Qiao can you try this with the recent .NET 8 builds? I'm wondering if the form size fix Devendar did would address this.

**Comment by John-Qiao** [comment]
@merriemcgaw I tried it, the issue still repro with the latest .NET 8.0 build + Devendar HPDI PR private dlls.

**Comment by merriemcgaw** [comment]
Awesome!!

**Comment by Amy-Li03** [comment]
@merriemcgaw @dreddy-work verified this issue on .NET latest build: 8.0.100-alpha.1.22608.10, issue was fixed on run time, but it is still reproducing on design time, the warning properties window is not scaled properly on 300% DPI, details please see following gif. Do we need to open a new separate designer issue to track it on design time?

**Run time:**
![gif-runtime-8 0](https://user-images.githubusercontent.com/62929087/206648661-7b5e8742-df93-4c66-9475-4f254cbf3723.gif)

**Design time:**
![gif-design-8 0](https://user-images.githubusercontent.com/62929087/206648795-630beedb-e231-4e81-8af9-d3d1287cef5f.gif)

**Comment by merriemcgaw** [comment]
@dreddy-work no we won't unless there is some new requirement.
