### ISSUE TITLE
[Accessibility] Keyboard tooltip of Winforms control should disappear when moving Form

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#5128]
* .NET Core Version: 
.NET SDK 6.0.100-preview.6.21317.3

* Have you experienced this same bug with .NET Framework?: 
Yes

**Minimal repro:**
1. Create a Winforms .Net Core application with targeting .Net 6.0 or using attached app directly
[WinFormsApp16.zip](https://github.com/dotnet/winforms/files/6674251/WinFormsApp16.zip)
2. Add 2 buttons and a tooltip to core designer, and set button2's tooltip property with some string
3. Run application and tab to button2 to shown keyboard tooltip
4. Move form, and check if the keyboard tooltip disappears

**Actualbehavior:**
Keyboard tooltip of Winforms control is displaying when moving Form. And keyboard tooltip eventually diappears after the timeout. Please see following screenshot and GIF:
![image](https://user-images.githubusercontent.com/26474449/122497973-e685ee80-d020-11eb-9bf7-90e4cb99c901.png)
![ToolTip](https://user-images.githubusercontent.com/26474449/122497998-f271b080-d020-11eb-9dbc-cf10f2899752.gif)

**Expected behavior:**
Keyboard tooltip of Winforms control disappears when moving Form

**Comment by merriemcgaw** [comment]
@Olina-Zhang Does it go away ever? Like if you click on some other control in the form?

**Comment by Olina-Zhang** [comment]
@merriemcgaw  here is the cases that tooltip disappears:
1. Like you said:  click on some other control
2. In repro steps said: when waiting for tooltip is timeout, that keyboard tooltip eventually disappears when moving the form.

**Comment by Olina-Zhang** [comment]
Verified in the latest .net SDK 6.0 RC 2 build + private binaries built from this Winforms repo, the issue is fixed:
![fixed1](https://user-images.githubusercontent.com/26474449/131939119-db75db7f-8932-4ff6-9f98-ace210da5261.gif)

**Comment by Philip-Wang01** [comment]
Verified this issue with .NET SDK 7.0.100-alpha.1.21479.33, this issue is fixed.
