### ISSUE TITLE
Information request for RESX file auto-code generation

### ISSUE THREAD

**Issue by Kaelum** [dotnet/winforms#5137]
The .NET 5.0 Release branch of [dotnet / winforms](https://github.com/dotnet/winforms) appears to be using a mechanism for RESX files, that autogenerates a C# partial class file in the bin folder of the project for the RESX file.  With the `Winforms.sln` solution loaded in Visual Studio 2019, all references to that class in the solution/project appear to be resolvable, and enumerable in Intellisense, even when the file does not exist on disk.  The only reference that I see to any of this is the following entry in the `.csproj` file:

```XML
    <EmbeddedResource Update="Resources\SR.resx">
      <GenerateSource>true</GenerateSource>
      <Namespace>System</Namespace>
    </EmbeddedResource>
```

There aren't any other references to this particular RESX file, nor are there any wildcard settings for RESX files that I can find.  Is there any documentation on this mechanism?  If not, how is this working?  Does it only work within Visual Studio and/or Windows?  We need something that also works on a Linux build server, so I'm trying to figure out how to proceed.

**Comment by dreddy-work** [comment]
This comes from a build task from Arcade `Microsoft.DotNet.Arcade.Sdk.GenerateResxSource` that is integrated into our repos. I guess any repo that use Arcade build infrastructure would get this feature.

**Comment by Kaelum** [comment]
@dreddy-work Thank you!

I don't think that we'll be able to implement easily, but it's something that we'll definitely want to consider.

**Comment by RussKie** [comment]
@Kaelum trying asking your question in https://github.com/dotnet/arcade/, it is manned by the engineering team that manages the infra.
