### ISSUE TITLE
Custom control drag and drop throws exception

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/winforms#5140]
* .NET Core Version: 

.net 6.0
* Have you experienced this same bug with .NET Framework?: 

no

**Problem description:**
custom contro; drag and drop throws exception

**Expected behavior:**

**Minimal repro:**

**Comment by RussKie** [comment]
@Barshan-Mandal information you've provided is not sufficient to provide any meaningful help or investigate. Please provide more information, or the issue will be closed.

**Comment by dreddy-work** [comment]
We would need details on how your custom control is developed and if it has any dependencies? What is the exception? screenshots? or GIF of the scenario.
