### ISSUE TITLE
Unable to publish a .NET 5.0 WinForms project via ClickOnce when the WebPageFile (e.g.: Default.htm) is not yet created

### ISSUE THREAD

**Issue by luronumen** [dotnet/winforms#5141]
* .NET Core Version: **.NET 5.0**

* Have you experienced this same bug with .NET Framework?: **No**

**Problem description:**
- Unable to publish a .NET 5.0 WinForms project via ClickOnce when the WebPageFile (e.g.: Default.htm) is not yet created

- The attached Error message is displayed:

![ErrorMessage](https://user-images.githubusercontent.com/8019466/123087911-7a7a0080-d3fb-11eb-8b98-90da73e7754f.png)

**Expected behavior:**
- The Visual Studio should be able to recreate the WebPageFile (e.g.: Default.htm) when it does not exists yet during the publish of a .NET 5.0 WinForms project via ClickOnce like it is happen when it is publishing a .NET 4.8 Framework WinForms project.

**Minimal repro:**
- Make sure that the ClickOnce WebPageFile (e.g.: Default.htm) is not yet created.
- Right Click the .NET 5.0 WinForms project and then select publish option
- From the publish screen just click publish for the already existing ClickOnce (Attached: [MOTOROBOTML.pubxml.txt](https://github.com/dotnet/winforms/files/6701383/MOTOROBOTML.pubxml.txt)) publish method: ErroMessage.png happen!

**Workaround**
- Before click on Publish button, edit the ClickOnce publish method by selecting “More actions” > “Edit” > “Finish”. Those steps will recreate the WebPageFile (e.g.: Default.htm) and now it is possible to publish the .NET 5.0 WinForms project via ClickOnce without any issue.

**Other Information**
- This issue has been opened here following Zheng Li's suggestion described in the following bug reported to Visual Studio:
https://developercommunity.visualstudio.com/t/unable-to-publish-a-net-50-winforms-project-via-cl/1457240

**Comment by dreddy-work** [comment]
@John-Hart Can you please take a look at this publishing scenario?

**Comment by John-Hart** [comment]
@sujitnayak could you please help investigate this?

**Comment by dreddy-work** [comment]
Progress will be tracked in attached feedback item [FeedbackTicket 1345881](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1345881): . This is issue does not belong to winforms but ClickOnce. Closing it.
