### ISSUE TITLE
WinForms HighDPI PerMonitorV2 UserControl Panel scales wrong

### ISSUE THREAD

**Issue by Balkoth** [dotnet/winforms#5148]
**.NET Core Version:**
SDK: 5.0.301 (ef17233f86)
Runtime: 5.0.7 (556582d964)

**Problem description:**
Panels on a UserControl are not scaled correctly when DPI changes occur.

The attached sample contains a form with a tab control and 2 tab pages. On the first tab page the panels are added directly, on the second tab page is a user control with the exact same panel configuration.

Starting the application on the main display, both tab pages look identical and correct:
![image](https://user-images.githubusercontent.com/80055480/123215954-5258d300-d4c9-11eb-8666-3c6207cc9d04.png)
![image](https://user-images.githubusercontent.com/80055480/123215838-335a4100-d4c9-11eb-89dd-22e7bd2b7077.png)

Moving the application to another display with different dpi does not scale the panels on the user control:
![image](https://user-images.githubusercontent.com/80055480/123216121-7c11fa00-d4c9-11eb-8ab7-8e9882b4ee8e.png)
![image](https://user-images.githubusercontent.com/80055480/123216144-80d6ae00-d4c9-11eb-8d59-9c8d277c8647.png)

**Expected behavior:**
The expected behaviour is that panels scale correct.

**Minimal repro:**
A sample is attached here:
[TestDpiUserControlPanel.zip](https://github.com/dotnet/winforms/files/6706968/TestDpiUserControlPanel.zip)

**Comment by Balkoth** [comment]
Sidenote: It does not matter if the UserControl is on a TabControl/TabPage. It also scales wrong if just a Panel is set as containter.

**Comment by dreddy-work** [comment]
Thanks @Balkoth . Panels are the next in line for HDPI work.

**Comment by dreddy-work** [comment]
This is fixed in latest bits. @Olina-Zhang , please confirm and let me know if you still see the issue.

**Comment by Cassie-Li01** [comment]
@dreddy-work Verified on latest 8.0 build: .NET 8.0.100-preview.3.23128.10, issue is fixed. Screenshot is as below:
On 300% main display:
![300_main_tabPage2](https://user-images.githubusercontent.com/96758262/222055157-55c903b3-8d18-4c7f-915f-95e1ab214163.png)
![300_main_tabPage1](https://user-images.githubusercontent.com/96758262/222055160-90546434-d645-4cdd-8453-dae0febac61f.png)

On 100% another display:

![100_another_tabPage1](https://user-images.githubusercontent.com/96758262/222055177-2e062100-613f-4adb-acdb-c35ff93b9b20.png)
![100_another_tabPage2](https://user-images.githubusercontent.com/96758262/222055179-5bba740b-3c62-4bd9-8765-9db20b1431be.png)
