### ISSUE TITLE
In WinformsControlsTest\MainForm.cs, use Show(this) so child forms open on the same monitor as the parent

### ISSUE THREAD

**Issue by alanhoman** [dotnet/winforms#5161]
* .NET Core Version: 
Daily Build - 6.0.0-preview.7.21323.1

In winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MainForm.cs, all of the [form].Show() calls in GetButtonsInitInfo() should be changed to [form].Show(**this**) so that the child form will always open on the monitor the MainForm is on.  I can submit a pull request with this change if you like.  For example:

```
Current:
    new InitInfo("MultipleControls", (obj, e) => new MultipleControls().Show())
Suggested Change:
    new InitInfo("MultipleControls", (obj, e) => new MultipleControls().Show(this))
```

The scenarios I am testing are when MainForm is moved from a monitor at 100% scaling to a monitor at 150% scaling and child forms are opened there.  With this change in place, the child forms will open on the 150% monitor.  This surfaces a number of issues on each form and I plan to start submitting these issues soon.  The current code always opens the new forms on the original monitor which does not test the potential HDPI issues.

**Comment by RussKie** [comment]
> I can submit a pull request with this change if you like.

👍 

> This surfaces a number of issues on each form and I plan to start submitting these issues soon.

👍 
Please check that issues you're seeing aren't already raised. This may be a good start: https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+label%3A%22area%3A+HDPI%22

**Comment by dreddy-work** [comment]
Assuming this is done and merged.

**Comment by alanhoman** [comment]
Yes, this was merged, thanks.
