### ISSUE TITLE
Child MDI windows have rendering issues

### ISSUE THREAD

**Issue by alanhoman** [dotnet/winforms#5162]
* .NET Core Version: 
Daily Build - 6.0.0-preview.7.21326.1

In winforms\src\System.Windows.Forms\tests\IntegrationTests\WinformsControlsTest\MdiChild.cs, change the btnOpenChild_Click event to open the MultipleControls form rather than a blank form then do the following 

1. Run the project on a 100% scaled monitor and click the MDI Parent button.
2. Move the MDI Parent form from a 100% scaled monitor to a 150% monitor.
3. Click on Open new child.  

Here are the issues I see:

1. The label1, radioButton, button1, groupBox1, and Masked edit text box are the correct font size
2. The CheckedListBox with the states has a font that is larger than it should be.
3. The checkBox1 inside tabPage2 is larger than it should be.
4. The RichTextBox with LLL in it has a font that is smaller than it should be.
5. The ListView items are in a font that is larger than it should be.
6. The cutoff header on the child MDI form should not be visible.  This works properly when the child MDI form is opened on a 100% scaled monitor.  
<img width="635" alt="MdiChild Highlighted" src="https://user-images.githubusercontent.com/2184698/123550305-cdb4c180-d721-11eb-9845-1a9446570267.png">

**Comment by dreddy-work** [comment]
Any of those controls has Font set? Can you attach your test app as well?

**Comment by alanhoman** [comment]
This was not from my app, it is from the base WinForms project here on GtitHub (https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.cs).  Please look at my issue again in order to reproduce the issue.  I can create a pull request if you like so that line 26 on MdiChild.cs opens MultipleControls rather than a blank form.

On MultipleControls, the only control that I can see setting the font is the RichTextBox.  For this case, how is the HDPI scaling supposed to be handled?  Is the only supported HDPI scenario an app where all controls use the default font and all other controls are ignored during HDPI resizing?

**Comment by dreddy-work** [comment]
Okay. Just wanted to make sure if you have  used your own test app here. Pull request may not be needed for the repro app. Scaling should work in both cases ( inherited Font and user set Font). We have known issues when launching or creating Forms ( or containers) on a non primary monitor first time. I am working on this scenario.

**Comment by Olina-Zhang** [comment]
@dreddy-work Verified this issue in the latest .Net 7.0 SDK build, it cannot repro. Please see following test result:
100% main screen:
![image](https://user-images.githubusercontent.com/26474449/142973568-0bae85c1-26f8-400c-853e-ad7555a11211.png)
Move to 300%DPI secondary screen:
![image](https://user-images.githubusercontent.com/26474449/142973636-1c00a52b-3d8d-4fdd-a4a2-acacbab21443.png)

**Comment by RussKie** [comment]
Apart from the incorrect position of the child form (https://github.com/dotnet/winforms/issues/3395) and the the updown control this looks awesome!

Do we have a tracking issue for the updown rendering? I couldn't find it.

**Comment by Olina-Zhang** [comment]
https://github.com/dotnet/winforms/issues/5104 is for spinner buttons of DomainUpDown/NumericUpDown.

**Comment by dreddy-work** [comment]
Closing this as incorrect position of child is tracked #3395 here and is Windows related ( a windows bug is opened for this internally).
