### ISSUE TITLE
.NET5 Forms: Cancel edit on ListView triggers event AfterLabelEdit with args.Label is "" instead of null

### ISSUE THREAD

**Issue by RonHeck** [dotnet/winforms#5180]
The behavior of entering the label edit mode and leaving it without change or escape button was changed. In .NET-Framework and .NET-Core 3.1 the event "AfterLabelEdit" provides "LabelEditEventArgs" where the property "Label" is "null". In .NET5 the empty string is returned. So for now it is not possible to detect edit operation cancelation any more. The previous behavior should be established as it is also declared by the  event documentation.

Find attached a little demo with .NET5 and Core3.1 to validate different behavior.
[WinFormsApp1.zip](https://github.com/dotnet/core/files/6733340/WinFormsApp1.zip)

**Comment by RussKie** [comment]
@vladimir-krestov @SergeySmirnov-Akvelon are you able to investigate? It may have regressed in #2459 but not certain.

**Comment by Philip-Wang01** [comment]
Verified the issue with latest .Net 6.0.100-rc.1.21368.3(x64) that this issue is fixed: the event "AfterLabelEdit" provides "LabelEditEventArgs" where the property "Label" is "null.
![konotabi](https://user-images.githubusercontent.com/86937911/126124645-148c134d-3869-42db-9971-65ec3bcc00d7.gif)

**Comment by Marie-Shi** [comment]
Verified this issue with the .NET SDK 5.0.9, this issue is fixed: the event "AfterLabelEdit" provides "LabelEditEventArgs" where the property "Label" is "null.
![issue_update](https://user-images.githubusercontent.com/45864017/126423801-cb623574-79ce-4599-92cc-fa600b6ba8a8.gif)

**Comment by Philip-Wang01** [comment]
Verified with the .Net 6.0 Preview 7 release build: 6.0.100-Preview.7.21369.19, it is fixed as above result.
