### ISSUE TITLE
Microsoft.PointOfService in .Net 5 only referneces .Net 4 Forms to work.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#5182]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MicrosoftPointOfService-in-Net-5-only-/1449438)._

---
[severity:I'm unable to use this version]
The Microsoft PointOfService SDK's statement  New PosExplorer(Me) requires a .Net Framework 4.0 form to pass. The .net 5 Form can not be translated for this object. Is there a work around?

---
#### Feedback Bot on 6/15/2021, 02:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jenna Zheng [MSFT] on 6/15/2021, 04:28 PM: 

<p>Hi darkmatter,<br>
Thanks for your feedback, I’m sorry that I don’t understand what is your problem, could you please provide the screenshot of this problem? and does this reproduce for all project or specific project? If it’s reproduce with the specific project, which project do you use? For us to investigate this further, could you please provide a sample solution that has this problem so that we can conduct further research? It would be very helpful if you could provide the details reproduced steps of this issue. We look forward to hearing from you!</p>
<p>Thanks,<br>
Jenna</p>

#### darkmatter2001 on 6/17/2021, 11:58 PM: 

<p>The Microsoft PointOfService SDK’s works as intended in the .Net Framework 4.0+ but does not work in the  .Net 5.0.<br>
The Me object is the current ‘Form’ being passed to the PosExplorer Class. Since 5.0 uses a different ‘Form’ object the class fails.</p>
<p>Dim peExplorer As PosExplorer<br>
peExplorer = New PosExplorer(<strong>Me</strong>)<br>
<img src="https://aka.ms/dc/image?name=Bb147c805904246069e0c2b08fd9bb0c4637595421810321309_ScreenShot.png&amp;tid=b147c805904246069e0c2b08fd9bb0c4637595421810321309" alt="ScreenShot.png"></p>
<ul>
<li><strong>Error Details:</strong><br>
System.TypeInitializationException<br>
HResult=0x80131534<br>
Message=The type initializer for ‘Microsoft.PointOfService.Management.Explorer’ threw an exception.<br>
Source=Microsoft.PointOfService<br>
StackTrace:<br>
at Microsoft.PointOfService.Management.Explorer.CreateExplorer()<br>
at Microsoft.PointOfService.PosExplorer.LoadExplorer()<br>
at Microsoft.PointOfService.PosExplorer.Initialize()<br>
at Microsoft.PointOfService.PosExplorer…ctor(ISynchronizeInvoke synchronizingObject)<br>
at WinFormsApp1.frmPortal.OpenCashDrawer() in C:\Users\Admin\source\repos\WinFormsApp1\WinFormsApp1\frmPortal.vb:line 79</li>
</ul>
<p>Inner Exception 1:<br>
MissingMethodException: Method not found: ‘Void System.AppDomainSetup.set_ApplicationBase(System.String)’.</p>

#### Jenna Zheng [MSFT] on 6/18/2021, 10:05 AM: 

<p>Hi darkmatter,<br>
Thanks for your reply,for us to investigate this issue in the further, we must reproduce this issue on our side first, so could you please provide a sample app for us which has this problem so that we can conduct further research? We look forward to hearing from you!<br>
Thanks,<br>
Jenna</p>

#### darkmatter2001 on 6/23/2021, 01:10 AM: 

<ol>
<li>Open Project</li>
<li>Click the Open Cash Drawer button.</li>
<li>peExplorer = New PosExplorer(Me) statement will fail.<br>
<a target='_blank' href="https://aka.ms/dc/file?name=Ba90bdc41bbdb4839a38a8cbe0a013aca637599786016584190_MSPOS5.zip&amp;tid=a90bdc41bbdb4839a38a8cbe0a013aca637599786016584190">MSPOS5.zip</a></li>
</ol>

#### darkmatter2001 on 6/30/2021, 01:32 AM: 

<p>You will need the SDK installed. I attached it to this comment.<br>
<a target='_blank' href="https://aka.ms/dc/file?name=B6457ac33c4584371b073c3eff58c280d637605847404021560_PosForDotNet-1.14.1.zip&amp;tid=6457ac33c4584371b073c3eff58c280d637605847404021560">PosForDotNet-1.14.1.zip</a></p>

#### Jenna Zheng [MSFT] on 6/30/2021, 10:03 AM: 

<p>Hi darkmatter,<br>
I have repro this problem, next we will investigate this problem. Please wait patiently. We will inform you the results in time.</p>
<p>Thanks,<br>
Jenna</p>

#### Jenna Zheng [MSFT] on 6/30/2021, 11:15 AM: 

<p>Hi darkmatter,<br>
PosExplorer on initilization checks weather you allowed it to send telemetry to Microsoft during instalation of POS for .NET. The code is trying to read this property:<br>
“RegistryKey.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32).OpenSubKey(“SOFTWARE\<a target='_blank' href="http://POSfor.Net">POSfor.Net</a>\Setup”).GetValue(“CeipOptIn”, (object) 0);”</p>
<p>So if you don’t have POS for .NET instaled, this Subkey isn’t in your registry and then exception is thrown.</p>
<p>Telemetry is contained only in 1.14 version of POS for .NET. I suggest to use version 1.12 which has same functions and is without telemetry.</p>
<p>If still have this problem by using POS for .NET v1.12 SDK, please let me know.</p>
<p>Thanks,<br>
Jenna</p>

#### darkmatter2001 on 7/1/2021, 01:53 AM: 

<p>Thank you for checking into this.</p>
<p>I’ve uninstalled version 1.14 and installed version 1.12 and still getting the same error on the same line.<br>
<strong>peExplorer = New PosExplorer(Me).</strong></p>
<p>I’ve also created the registry point you referred to.<br>
HKeyLocalMachine\SOFTWARE\<a target='_blank' href="http://POSfor.Net">POSfor.Net</a>\Setup<br>
<strong>CeipOptIn</strong> Reg_DWORD Value 1</p>
<p>System.TypeInitializationException<br>
HResult=0x80131534<br>
Message=The type initializer for ‘Microsoft.PointOfService.Management.Explorer’ threw an exception.<br>
Source=Microsoft.PointOfService<br>
StackTrace:<br>
at Microsoft.PointOfService.Management.Explorer.CreateExplorer()<br>
at Microsoft.PointOfService.PosExplorer.LoadExplorer()<br>
at Microsoft.PointOfService.PosExplorer.Initialize()<br>
at Microsoft.PointOfService.PosExplorer…ctor(ISynchronizeInvoke synchronizingObject)<br>
at MSPOS5Test.frmMain.btnOpen_Click(Object sender, EventArgs e) in C:\<a target='_blank' href="http://VB.Net">VB.Net</a> Programs\MSPOS5\frmMain.vb:line 9<br>
at System.Windows.Forms.Control.OnClick(EventArgs e)<br>
at System.Windows.Forms.Button.OnClick(EventArgs e)<br>
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)<br>
at System.Windows.Forms.Control.WmMouseUp(Message&amp; m, MouseButtons button, Int32 clicks)<br>
at System.Windows.Forms.Control.WndProc(Message&amp; m)<br>
at System.Windows.Forms.ButtonBase.WndProc(Message&amp; m)<br>
at System.Windows.Forms.Button.WndProc(Message&amp; m)<br>
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp; m)<br>
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)</p>
<p>This exception was originally thrown at this call stack:<br>
[External Code]</p>
<p>Inner Exception 1:<br>
OverflowException: Arithmetic operation resulted in an overflow.</p>

---
### Original Solutions
(no solutions)

**Comment by Jenna-Zheng** [comment]
- .NET Core Version:
.NET SDK 5.0.400-preview.21323.10

- Have you experienced this same bug with .NET Framework?:
No

**Problem description:**
The exception occurs when clicking the button1.
![image](https://user-images.githubusercontent.com/64949616/124079078-45188700-da7b-11eb-9d7c-db86a7bbcf21.png)

**Expected behavior:**
There is no exception occurs when clicking the button1.
![image](https://user-images.githubusercontent.com/64949616/124079358-99236b80-da7b-11eb-9321-7fc8188cebd7.png)

**Minimal repro:**
1. Create a Core winforms application with a **button1**.
2. Right click on this project and click **Manage Nuget Packages...**
3. Click Browse and search '**PosForDotNet**' in search box.
4. Install the '**PosForDotNet.SDK v1.14.1**' by clicking install button.
5. Return the form designer and double click the **button1**, then input this code '**PosExplorer p = new PosExplorer();**'.
6. Build and Run, then click the **button1** and observe.
 
Or 

1. Open the attached project (Core) [WinFormsApp9.zip](https://github.com/dotnet/winforms/files/6746061/WinFormsApp9.zip) and (Framework) [WindowsFormsApp2.zip](https://github.com/dotnet/winforms/files/6746077/WindowsFormsApp2.zip) in VS and run it.
2. then click the **button1** and observe.
![test](https://user-images.githubusercontent.com/64949616/124082066-e0f7c200-da7e-11eb-9635-85b64172f9fb.gif)

**Comment by RussKie** [comment]
@Jenna-Zheng we don't own the SDK in question, the customer needs to contact the owner, which judging from the NuGet is @ronnieoverby, and confirm the SDK is .NET Standard and/or .NET compatible. If it isn't it won't work, and it is the expected behaviour.

**Comment by OzarkDigitalSolutions** [comment]
The original bug was not found using the Nuget package "PosForDotNet". The reference was using the SDK package from 
"C:\Program Files (x86)\Microsoft Point Of Service\SDK\Microsoft.PointOfService.dll".  
Jenna-Zheng misreported this issue. The matter should be looked into and not closed.

Recreate these conditions using Winfoms .Net 5.0 and this reference and you will see the issue.

**Comment by Jenna-Zheng** [comment]
@OzarkDigitalSolutions "C:\Program Files (x86)\Microsoft Point Of Service\SDK\Microsoft.PointOfService.dll" is also generated after installing the "PosForDotNet" package. Whether it is installed with nuget package "posfordotnet" or [PosForDotNet-1.14.1.zip](https://github.com/dotnet/winforms/files/6761330/PosForDotNet-1.14.1.zip) package, the result is the same.
