### ISSUE TITLE
Child MDI has HDPI issues related to height

### ISSUE THREAD

**Issue by alanhoman** [dotnet/winforms#5189]
* .NET Core Version: 
6.0.0-preview.7.21323.1

Run the repo and select MDIParent - Simple Layout.  Move MDIParent from the primary monitor to the secondary monitor.  

If the MDIParent1 window height is less than 494 or greater than 859, the SimpleForm in MDIParent1 will not render properly when moved to the secondary monitor.  In the repo it is set to 493.

It would be expected that no matter what the MDIParent1 height is, the SimpleForm will render properly when moved to the second monitor.  For other monitor dimensions, the height tolerances may differ, but still exhibit the same issue.

Also, the tabControl1 MinimumSize on SimpleForm is set to 430, 200.  If this is changed to 0, 0 and the MDIParent1 height is set to less than 478, the rendering issue does not occur.  However, a height greater than 859 still exhibits the issue.

Here is the monitor configuration I am using:
Primary Monitor: 1920x1200, 100%
Secondary Monitor: 1920x1200, 150%

MDParent1 Height set to 493, then moved to Secondary:
<img width="425" alt="SecondaryAt493PixelsHigh" src="https://user-images.githubusercontent.com/2184698/124193648-0afbb500-da7c-11eb-86ba-1f697671ff65.png">

MDParent1 Height set to 494, then moved to Secondary:
<img width="425" alt="SecondaryAt494PixelsHigh" src="https://user-images.githubusercontent.com/2184698/124193732-38e0f980-da7c-11eb-9f5f-56a7f1f3d817.png">

The same issue occurs when the height is set above 859 and the screenshot would look the same, so I am not including more screen shots.

Here is the repo:
[PerMonitorHDPICore - NET 6.0.zip](https://github.com/dotnet/winforms/files/6751007/PerMonitorHDPICore.-.NET.6.0.zip)

**Comment by alanhoman** [comment]
I have not seen any updates on this issue.  Is this being worked on and are there any status updates?

**Comment by Olina-Zhang** [comment]
@dreddy-work Verified this issue in the latest .Net 7.0 SDK build, it cannot repro now when setting MDIParent's height is 493 or 860. 
Here is testing result:
100% DPI main screen:
![image](https://user-images.githubusercontent.com/26474449/142971036-915b40fb-f09d-4d83-b1be-791c4953b60b.png)
Move to 300% DPI secondary screen:
![image](https://user-images.githubusercontent.com/26474449/142971080-dd3d7c00-bf8c-4ca1-8377-38aa1287f42a.png)

**Comment by dreddy-work** [comment]
Incorrect position of MDI child is being tracked here:  (#3395). @alanhoman , can you confirm the rest of the issues with latest bits from main branch?

**Comment by alanhoman** [comment]
Hi @dreddy-work, and thanks for all of the excellent work on HDPI!  I have verified that this issue has been resolved by the latest bits.  Most of the major HDPI issues have been fixed and I will be entering a few new ones in the next 1-2 days.
