### ISSUE TITLE
HDPI Performance and Rendering Issues

### ISSUE THREAD

**Issue by alanhoman** [dotnet/winforms#5190]
* .NET Core Version: 
6.0.0-preview.7.21323.1

When moving the application from the primary monitor at 100% to a secondary monitor at 150%, then opening a Child MDI form by selecting File -> New, there are performance and rendering issues:

1. Opening a new Child form on the primary monitor takes 416 ms.  When moved to the secondary at 150% and selecting File -> New, the Child form takes 4,850 ms to open.  This particular form is opened potentially hundreds of times during a day for our users and this delay is significant.
2. The fonts for the GroupBoxes and ListViews are large and appear to become larger on the secondary monitor.

Primary Monitor (100%):
<img width="457" alt="LargeFormOpenOnPrimary" src="https://user-images.githubusercontent.com/2184698/124196864-1e118380-da82-11eb-8984-e2b6d94842e1.png">
Secondary Monitor (150%)
<img width="457" alt="LargeFormOpenOnSecondary" src="https://user-images.githubusercontent.com/2184698/124196870-2073dd80-da82-11eb-9ce4-7ace0fe9d068.png">
Here is the repo:
[LargeFormCore.zip](https://github.com/dotnet/winforms/files/6751105/LargeFormCore.zip)

**Comment by Amy-Li03** [comment]
Verified this on .NET 8.0 latest build: 8.0.100-alpha.1.22565.7, performance issue is still repro, but rendering issue doesn't repro, the fonts for the GroupBoxes and ListViews scale well on the secondary monitor.

100% DPI primary monitor:
![100%](https://user-images.githubusercontent.com/62929087/203006687-46a59597-1fdc-4d86-8a26-0d8466b39f13.png)

200% DPI secondary monitor:
![200%](https://user-images.githubusercontent.com/62929087/203006449-be5562be-fb16-4db3-8118-10872163ac83.png)

**Comment by JeremyKuhne** [comment]
@dreddy-work this might be related to the lack of a global DPI specific font cache.

**Comment by elachlan** [comment]
@Olina-Zhang can your team check if this is still an issue? I think there might have been improvements to the font cache since it was last tested?

**Comment by Philip-Wang01** [comment]
@elachlan Verified this on .NET 9.0 latest build: 9.0.100-preview.5.24265.9, Performance issue have improved dramatically. Rendering issue doesn't repro, the fonts for the GroupBoxes and ListViews scale well on the secondary monitor.

100% DPI primary monitor:
![image](https://github.com/dotnet/winforms/assets/86937911/10d7fba4-b0a1-4260-b8d1-8bf9432796c8)
150% DPI secondary monitor:
![image](https://github.com/dotnet/winforms/assets/86937911/631ea96f-ba28-4629-8815-921e4b8cb91b)

**Comment by elachlan** [comment]
I'll close this issue for now as both the rendering and performance issues are resolved.

CC: @lonitra
