### ISSUE TITLE
[WebBrowser] HtmlElement.AttachEventHandler does nothing

### ISSUE THREAD

**Issue by albahari** [dotnet/winforms#520]
* .NET Core Version: v3.0.0-preview2
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

HtmlElement's AttachEventHandler method is a no-operation in .NET Core 3. Here's a simple repro:

```
var browser = new WebBrowser
{
    Dock = DockStyle.Fill,
    DocumentText = @"<!DOCTYPE HTML>
<html>
  <head>
    <meta http-equiv='Content-Type' content='text/html;charset=utf-8' />
    <meta http-equiv='X-UA-Compatible' content='IE=edge' />
  </head>
  <body>
    <input id='foo'/>
  </body>
</html>"
};
browser.DocumentCompleted += (sender, args) =>
    browser.Document.GetElementById ("foo").AttachEventHandler ("oninput", (s, a) => Console.WriteLine ("this does not fire"));

var form = new Form();
form.Controls.Add (browser);
form.ShowDialog();
```

Note that @AaronRobinsonMSFT is aware of the issue and has done some investigation on the coreclr side.

**Comment by AaronRobinsonMSFT** [comment]
Based on my cursory look through the WinForms implementation, I think there is a potential blocker for this at https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs#L1285-L1295.

Use of the `AttachEvent` method appears to be a nop on IE11+. See https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa703974%28v%3dvs.85%29 for details.

**Comment by albahari** [comment]
It's odd that this call to IHTMLElement2.AttachEvent works in .NET Framework (with IE11).

**Comment by zsd4yr** [comment]
@albahari can you provide any more details on this working in IE11? We default to IE7. Does it work in that scenario? 

What is your specific scenario?

**Comment by albahari** [comment]
I'm sorry, I don't have a setup old enough to run IE7. If I remove "content='IE=edge'", which tells IE to switch rendering engines, I see the same bug. I'm running Windows 10 with automatic updates enabled.

My specific scenario is porting LINQPad to .NET Core. It renders all output using a WebBrowser control. LINQPad exposes wrappers for HTML controls, so you can dump them to create interactive queries. This breaks in .NET Core because event handlers cannot be attached after a control has been rendered. For instance, try running the following code in LINQPad (from one of the built-in samples):

```
var textBox = new LINQPad.Controls.TextBox().Dump ("Here's a simple textbox");

var button = new LINQPad.Controls.Button ("Click me").Dump ("Here's a simple button");

// Responding to button's click event (won't work right now in .NET Core)
button.Click += (sender, args) => textBox.Text = "Updated text";

// Responding to textBox's TextInput event (won't work right now in .NET Core)
textBox.TextInput += (sender, args) => $"You typed: {textBox.Text}".Dump();

textBox.Focus();
```

LINQPad's Interactive Regex Tool relies on these controls:
https://www.facebook.com/LINQPad/posts/2197368833624257
To see this in action, Press Ctrl+Shift+F1 from LINQPad. This is entirely dead at the moment when LINQPad targets .NET Core.

I've not received any reports of HTML controls not working in LINQPad 5, so it's safe to assume that AttachEventHandler works reliably in .NET Framework with IE11 as the browser (most users are running Windows 10 and so will have IE11).

**Comment by merriemcgaw** [comment]
Have you tried [this page ](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/ee330730(v=vs.85)) or [this page](https://stackoverflow.com/questions/38514184/how-can-i-get-the-webbrowser-control-to-show-modern-contents) to change the browser emulation mode of the WebBrowser control? The default emulation mode in WinForms for the control is IE7, which may cause some problems.

**Comment by albahari** [comment]
merriemcgaw - yes, that's exactly what <meta http-equiv="X-UA-Compatible" content="IE=Edge" /> does. It's little use to me in IE7 mode.

**Comment by albahari** [comment]
Please let me know what extra information you need. I have provided a full repro, which I believe stands.

**Comment by albahari** [comment]
Good news - I've just tested this in Preview6 and it appears to be working correctly. Was something fixed recently?

**Comment by AaronRobinsonMSFT** [comment]
@albahari nothing new just some minor bugs. Preview 5 had most of the support for `IDispatch` so this should also work fine there. Either way glad to hear the scenario is unblocked.

**Comment by RussKie** [comment]
Is there something else outstanding, or can we close the issue?
