### ISSUE TITLE
Anchored WinForms controls inside FlowLayoutPanel are not actually anchored

### ISSUE THREAD

**Issue by CristianVladescu** [dotnet/winforms#522]
The example at [this](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-anchor-and-dock-child-controls-in-a-flowlayoutpanel-control) article demonstrates the problem.
Basically, when the form is resized, FlowLayoutPanel does resize, but the controls inside it don't stay anchored as they should.

To better understand, compare these pictures:

![capture](https://user-images.githubusercontent.com/13788125/53681960-64f7de80-3cf9-11e9-9fe7-045ba111a3c0.PNG)
![capture](https://user-images.githubusercontent.com/13788125/53681966-780aae80-3cf9-11e9-9b6a-62e993a58be6.PNG)

The button "Anchored=Left, Right" should have stretched.

Environment:
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.0.0 Preview 4.0
VisualStudio.16.Preview/16.0.0-pre.4.0+28625.133
Microsoft .NET Framework
Version 4.7.03056
and
![capture](https://user-images.githubusercontent.com/13788125/53682176-bdc87680-3cfb-11e9-8677-d2d7b93b94aa.PNG)

**Comment by merriemcgaw** [comment]
This is worth investigating. However, I'm marking it as future because it's the same way in .NET Framework.

**Comment by georgiuk** [comment]
Hi,
here is a subclass of FlowLayoutPanel that I have written that tries to respect anchor settings. It is experimental and works only topdown I think but it does what it is supposed to. 
https://gist.github.com/georgiuk/606d6b807d58113ba40bcd7d3354b6ba

**Comment by RussKie** [comment]
> The button "Anchored=Left, Right" should have stretched.

Could you please explain why you expect this?
The docs explain that implied column/row are calculated from the longest/tallest control:
![image](https://user-images.githubusercontent.com/4403806/75847466-62135a80-5e33-11ea-8da3-e27b825542af.png)

When you resized the form none of the controls on your screenshot got longer or taller, so no change should be expected.

> here is a subclass of FlowLayoutPanel that I have written that tries to respect anchor settings.

It is very hard to see what the actual change is. It would be great if you could show a diff (e.g. open a PR, even for a reference), so we could discuss it.
