### ISSUE TITLE
WinForm Core 5/6 Designer on Visual Studio 2019.10 100% scale mode in 4K display.

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/winforms#5226]
* .NET Core Version: 5, 6-Prev5
* Have you experienced this same bug with .NET Framework?: 

**Problem description:**

.NET Framework Windows Forms is working correctly. 
I tried VS 2019.10 is VM with 96DPI screen mode and Winform designers on autoscale mode works more or less acceptable.

Please Fix that Bug in VS 100% scale core designers.

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.
