### ISSUE TITLE
[Loc]With net6 preview 7 installed on locale OS, some template names are unlocalized after runing "dotnet new --list" in CLI .

### ISSUE THREAD

**Issue by vdanche** [dotnet/winforms#5249]
1. Install net 6 preview 7 SDK[6.0.100-preview.7.21364.30(runtime:6.0.0-preview.7.21360.10)] from https://github.com/dotnet/installer
2. Install it on locale OS
3. Run “dotnet new --list” in CLI
4. Check if  output contents are localized well.
Actual Result:
Some template names are not localized.

e.g 
SC:
![image](https://user-images.githubusercontent.com/65637796/125879083-4b560aaf-0760-4726-807e-21c3294e9b63.png)

DE:
![image](https://user-images.githubusercontent.com/65637796/125880067-89d006ab-6878-4cd6-b823-5430730fd859.png)

Note:
It has been localized well in VS 17.0 preview 3
e,g
SC:
![image](https://user-images.githubusercontent.com/65637796/125879266-7e61ca02-6ff4-45c1-ad30-4bfe1dcec3d8.png)

**Comment by dreddy-work** [comment]
@KlausLoeffelmann , any idea where and how these localized?

**Comment by RussKie** [comment]
I personally don't think it is correct to loc "Windows Forms", as it is the name of the tech stack.

@crsuzukimsft assigning to you as you own the locs.

**Comment by KlausLoeffelmann** [comment]
I agree partly, however I can only speak for German.
It should be:
"Windows Forms App" (No translation here, please! "App" is common German. We want people to understand, so _we_ need to accommodate (to) the tech lingo that is actually spoken in the various communities and tech departments of the German IT companies and households in the (German speaking) world. And sometimes we need to go against a minor group of language theorists who may argue from a language scientific perspective, why it should be for example "Produktrückstandselement" and not "Backlog Item" - the latter being definitely not German; the first one, though, NOONE in Germany really understands! We MUST put understanding, accessibility, discoverability, approachability before technical-theoretical language correctness - which in the end is often discussable, questionable and often enough subject to change by the Duden anyway. See "gedownloadet" and "heruntergeladen" for reference - the first being a Duden-enabled German-English lean word...)

It should be though:

"Windows Forms Klassenbibliothek"
"Windows Forms Steuerelementebibliothek"

We recently changed the templates, but never their description or LOC. So, no, I have not really an idea what is going on.

**Comment by KlausLoeffelmann** [comment]
@Olina-Zhang:

In Addition what I wrote: What concerns me more is the effect on GB18030 for the Chinese Certification. Are tests effected by this, Olina? That's, @crsuzukimsft, why we should address this on really short notice!

**Comment by Olina-Zhang** [comment]
@KlausLoeffelmann I don't think this will have any impact on the test, this issue is just for display in SDK by CLI. And it also no affect in Visual Studio. Cannot be checked or tested on Chinese GB18030.

**Comment by cristianosuzuki77** [comment]
Where is the source of these strings?
https://github.com/dotnet/winforms/tree/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/ ?

**Comment by KlausLoeffelmann** [comment]
Not sure what you mean exactly. 
The localize strings are here:
https://github.com/dotnet/winforms/tree/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config

(As an example for the C# WinForms App template.)

**Comment by KlausLoeffelmann** [comment]
That's what _I_ thought. The question now is, why aren't they surfacing in the product?
@merriemcgaw, @Pilchie: Just FYI, this could become too time-critical if we put it off for too long and I want to avoid doing this again at the last minute, so I plan to spend a bit time on the side investigating this on a German VM.

Also: @phenning - any idea, what might go wrong here?
@KathleenDollard FYI.

**Comment by phenning** [comment]
@vlada-shubina  and @DavidKarlas would be able to better explain how "dotnet new" localization the templates in the CLI. This is a relatively new feature- if you notice the only localized templates are those that are coming from the dotnet/templating repo which is also owned by the template engine. I believe there is some work that needs to be done in order to use the new localization mechanism for .NET 6 templates. 

The existing strings.json mechanism was for Visual Studio only, and we will be also implementing the new mechanism from the NET 6 template engine, hopefully in time for 17.0 GA. One thing I'd like to point out is that  there seem to be both folders with two letter locales (de) as well as the de-DE format. Visual Studio will first try to use de-DE if it exists, then will fallback to using de.  It looks like the most recent checkins your repo was to the two character locale, which would not be the first one that VS will use. I'd suggest removing the xx-XX versions folders from the templates after verifying that it is the correct content.

**Comment by bekir-ozturk** [comment]
Thanks for clarifying Phil. I would like to add a few things.

Localization of template metadata was not supported by template engine until .NET 6.0. Visual Studio had a workaround for this missing feature via strings.json files.

With .NET 6.0, we have added support for this into template engine. This means that there is now a single mechanism to localize template metadata in both dotnet CLI and Visual Studio (not yet integrated as Phil also mentioned).

This new mechanism has a new format for localization files. As an example, please see the templates in template engine repo: https://github.com/dotnet/templating/tree/main/template_feed/Microsoft.DotNet.Common.ProjectTemplates.6.0/content/ClassLibrary-CSharp/.template.config/localize

The "localize" folder you can see in the example above as well as the templatestrings.xx.json files for each supported language can be automatically created by our "Template Localizer" tool. 

```
dotnet tool install --global Microsoft.TemplateEngine.TemplateLocalizer --version 6.0.100-preview.7.21378.11
dotnet template-localizer export "C:/root/of/your/templates" -r
```

If you run this tool on your templates and commit/push the changes, arcade will automatically send them for translation and the translated versions will appear in your repo as a PR. If you need further clarification on this, feel free to ping me.

We did these steps to localize the templates we own, but our availability didn't allow for promoting this to other teams during .NET 6.0 timeframe. We plan to automate the procedure for all the arcade based repos for .NET 7.0.

**Comment by RussKie** [comment]
So am I correct in understanding that we should delete [all currently localised content](https://github.com/dotnet/winforms/tree/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config), and then run the tool to generate a new content that will flow via the OneLocBuild task to the Loc team?

**Comment by bekir-ozturk** [comment]
You shouldn't delete the current content. That would break Visual Studio locs since it hasn't yet switched to the new way. For the time being, localized content for both mechanisms should exist together. You are correct about the rest though.

**Comment by phenning** [comment]
@RussKie  You should probably still delete the "xx-XX" versions of the current localized content though, since it looks like the "xx" versions are the latest. As explained above, VIsual Studio would try to use the xx-XX versions first if they are present.

![image](https://user-images.githubusercontent.com/2433750/129361006-106b7f71-9876-4f21-a551-3b079a28dc50.png)

**Comment by phenning** [comment]
I'd verify first though that the automated check-in has the correct translations for each language.

**Comment by KlausLoeffelmann** [comment]
@bekir-ozturk, @phenning: Thanks for clarifying!

**Comment by RussKie** [comment]
@bekir-ozturk I'm getting errors while running the script. I tried a few different ways, but each time the error is the same:
```powershell
PS C:\Development\winforms> dotnet template-localizer export .\pkg\Microsoft.Dotnet.WinForms.ProjectTemplates\content -r
PS C:\Development\winforms> Get-ChildItem .\pkg\Microsoft.Dotnet.WinForms.ProjectTemplates\content  | foreach { dotnet template-localizer export "$($_.FullName)\.template.config" -r }
```
![image](https://user-images.githubusercontent.com/4403806/129502528-b09767e9-3c00-4e1c-9fd4-ed7cd50638cd.png)

What am I missing?

**Comment by DavidKarlas** [comment]
Short version:
You need to add "id" attributes to post actions, see example in bellow screenshot:
![image](https://user-images.githubusercontent.com/774791/129506111-661b2842-2572-4505-aad7-d4ed942886e2.png)

Long version:
Since postactions are defined as array, if we decided to match localisation by indexes in array user could re-order them or delete 1 or add 1 at beginning of array and all localisations would be wrong, hence we require "id" attribute to be added so we avoid indexes problems.

**Comment by RussKie** [comment]
@DavidKarlas thank you, that did the trick

**Comment by Ashley-Li** [comment]
@RussKie @KlausLoeffelmann Verified this issue with .Net 6.0.100-rc.1.21417.19 from Release/6.0.1XX, it is still repro on OS(CHS,RUS,PTB) , winforms template names are unlocalized after runing "dotnet new --list" in CLI, please see below results.Whether this is expected?
![image](https://user-images.githubusercontent.com/56664234/130171433-f7a01e44-3ed6-4402-a51a-4cea1e6d206f.png)
![image](https://user-images.githubusercontent.com/56664234/130171478-b84f0edb-40be-4776-a940-213f78050708.png)
![image](https://user-images.githubusercontent.com/56664234/130171483-5814085c-8c48-4145-a874-643879083803.png)

**Comment by RussKie** [comment]
@Ashley-Li my PR has enabled the translations infra for the templates. 
I don't believe any translations have been done and/or merged. @dreddy-work and @cristianosuzuki77  can provide more information on where we're at with those.

**Comment by Ashley-Li** [comment]
@RussKie We built binaries from main branch under dotnet/winforms repo, it is empty under ..\source\repos\winforms\artifacts\bin\Microsoft.Dotnet.Winforms.ProjectTemplates, no dll generated. So we cannot verify this accurately. Do you have any ideas?

**Comment by merriemcgaw** [comment]
I think you will just need to wait a while until the localization has completed. @dreddy-work/@russkie do you know when that might be?

**Comment by RussKie** [comment]
@Ashley-Li tl;dr - the templates don't have any binaries. The test procedures are described in https://github.com/dotnet/winforms/tree/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates.

Microsoft.Dotnet.WinForms.ProjectTemplates and Microsoft.Private.Winforms are what we call "transport packages", and those are NuGet packages that are referenced by other repos (such as the SDK). The transport packages are created during the packaging stage, i.e. `.\build.cmd -pack`.

**Comment by RussKie** [comment]
I don't think you need to spend any time on testing because we still haven't got any translations, e.g. https://github.com/dotnet/winforms/blob/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/localize/templatestrings.de.json

@cristianosuzuki77 will know when translations are available, and @dreddy-work will know when those are merged.

**Comment by dreddy-work** [comment]
That is correct. We supposed to get translated PRs after @cristianosuzuki77 re-enabled for this repo. Wait on validations until @cristianosuzuki77  or me update you on this.

**Comment by dreddy-work** [comment]
@Marie-Shi , actual localization commit is in this [PR](https://github.com/dotnet/winforms/pull/5570). It went into main /7.0. It will go into RC2 but towards end of the release. Please keep an eye on RC2 release timeline and validate this change then.

**Comment by Marie-Shi** [comment]
@dreddy-work Thanks for your confirmation! We will keep an eye on RC2 release and validate it again.

**Comment by Marie-Shi** [comment]
Verified this issue with .Net 6.0.100-rc.2.21473.26 from 6.0 RC2 Test Pass, it is fixed. Now Winforms template names are localized after runing "dotnet new --list" in CLI.
![ewe](https://user-images.githubusercontent.com/45864017/135041082-9bf7a5b4-c684-49fb-912d-8eb8d69be19e.png)
