### ISSUE TITLE
Invalid PInvoke definition for SafeNativeMethods.GetThemeMargins()

### ISSUE THREAD

**Issue by creativbox** [dotnet/winforms#526]
`VisualStyleRenderer.GetMargins(...)` throws an AccessViolation because of an invalid PInvoke definition for `SafeNativeMethods.GetThemeMargins(...)`
According to https://docs.microsoft.com/en-us/windows/desktop/api/uxtheme/nf-uxtheme-getthememargins the LPCRECT parameter is missing. 
The method is currently not used as far as I can see, but its wrong behavior is mentioned in some code comments.

**Comment by merriemcgaw** [comment]
Moving this to the Future milestone because it's not a regression from .NET Framework. This can totally be up for grabs by the community.
