### ISSUE TITLE
Unable to find an entry point named 'AdjustWindowRectEx ForDpi' in DLL user32.dll

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#5278]
Recent change for HDPI in .NET 6.0 uses latest API `AdjustWindowRectEx ForDpi()` from windows that was introduced in Windows 10 version >1607.  We were not check for the API availability and thus running the winforms on Windows 7 is throwing `Unable to find an entry point`. 

Fix is to make sure we call this API only on available OS and in other case, default to legacy API.

Customer report: https://developercommunity.visualstudio.com/t/unable-to-find-an-entry-point-named-Adj/1476945?entry=problem&space=61&q=AdjustWindowRectEx&viewtype=all

**Comment by Ashley-Li** [comment]
Verified this issue with OS(Windows-7-Enterprise-SP1)+ .NET dotnet-sdk-6.0.100-rc.1.21377.28, it is fixed. Now there's no exception error( “unable to find an entry point named ‘AdjustWindowRectExForDpi’ in DLL user32.dll”) pops up when clicking and run the exe file, and the form designer can be run successfully. Please see below gif: 
![test](https://user-images.githubusercontent.com/56664234/127300852-8d0d3657-bcee-4301-93de-7564ae1d2e76.gif)

**Comment by cwing2019** [comment]
do you have a release windows.form.dll for this? I can't build it from winforms .

**Comment by cwing2019** [comment]
> 
> 
> Verified this issue with OS(Windows-7-Enterprise-SP1)+ .NET dotnet-sdk-6.0.100-rc.1.21377.28, it is fixed. Now there's no exception error( “unable to find an entry point named ‘AdjustWindowRectExForDpi’ in DLL user32.dll”) pops up when clicking and run the exe file, and the form designer can be run successfully. Please see below gif:
> ![test](https://user-images.githubusercontent.com/56664234/127300852-8d0d3657-bcee-4301-93de-7564ae1d2e76.gif)
do you have a release windows.form.dll for this? I can't build it from winforms .

**Comment by RussKie** [comment]
> do you have a release windows.form.dll for this? I can't build it from winforms .

This is fixed in .NET 6.0 RC1

**Comment by cwing2019** [comment]
> 
> 
> > do you have a release windows.form.dll for this? I can't build it from winforms .
> 
> This is fixed in .NET 6.0 RC1

no. I am using .NET 6.0 Preview 6. and windows7 ,is not ok...
so I am seeking  a download able dll for a patch to it..

**Comment by dreddy-work** [comment]
> > > do you have a release windows.form.dll for this? I can't build it from winforms .
> > 
> > 
> > This is fixed in .NET 6.0 RC1
> 
> no. I am using .NET 6.0 Preview 6. and windows7 ,is not ok...
> so I am seeking a download able dll for a patch to it..

You can't use RC1 bits there? if you want to patch it yourself, you can build repo using VisualStudio 2022 or you can install RC1 on your dev machine and take the binary from there.

**Comment by cwing2019** [comment]
> 
> 
> > > > do you have a release windows.form.dll for this? I can't build it from winforms .
> > > 
> > > 
> > > This is fixed in .NET 6.0 RC1
> > 
> > 
> > no. I am using .NET 6.0 Preview 6. and windows7 ,is not ok...
> > so I am seeking a download able dll for a patch to it..
> 
> You can't use RC1 bits there? if you want to patch it yourself, you can build repo using VisualStudio 2022 or you can install RC1 on your dev machine and take the binary from there.

do you mean  ".net 6 preview 7 "? still not release yet.

**Comment by RussKie** [comment]
This is fixed in .NET 6.0 RC1, which is not yet released.
