### ISSUE TITLE
Form.Show/PropDialogOwner causing memory leaks

### ISSUE THREAD

**Issue by tobster-de** [dotnet/winforms#530]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
Form.Show(IWin32Window) causes memory leaks because of references to the Owner form held within the PropertyStore of the form.

problematic line:
https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L5929

**Actual behavior:** 
In ShowDialog(IWin32Window) I see the property PropDialogOwner is nulled in the finally block. Using Show(...) method it never gets nulled. In Dispose only PropOwner is nulled. So the reference to the provided Owner-Form is held the PropertyStore and child forms will not GCed.

**Expected behavior:**
A: The said property is cleared in Dispose like PropOwner
B: PropDialogOwner is not used at all because it is not ShowDialog

**Minimal repro:**
* open a Form
* open some forms which consume some memory
* let them open child forms with said method 
* and close them
* profile memory for parent forms

```
    static class Program
    {
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }
    }

    public class MainForm : Form
    {
        public MainForm()
        {
            long a = Process.GetCurrentProcess().WorkingSet64;

            var children = new List<Form>();
            for (int i = 0; i < 50; i++)
            {
                ParentForm parent = new ParentForm();
                parent.Show();
                children.Add(parent.Yum());
                parent.Close();
            }
            
            children.ForEach(cf => cf.Close());

            long b = Process.GetCurrentProcess().WorkingSet64;
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            long c = Process.GetCurrentProcess().WorkingSet64;
            
            this.Controls.Add(new Label() { Text = $"{a}\n{b}\n{c}", Dock = DockStyle.Fill, TextAlign = ContentAlignment.MiddleCenter});
        }
    }

    public class ParentForm : Form
    {
        private Byte[] array;

        public Form Yum()
        {
            this.array = new Byte[1024 * 1024];
            Array.Clear(array, 0, this.array.Length);
            
            Form child = new Form();
            child.Show(this); // <-----

            return child;
        }
    }
```

**Workaround**
```
child.Owner = this;
child.Show();
```

**Comment by zsd4yr** [comment]
> A: The said property is cleared in Dispose like PropOwner
> B: PropDialogOwner is not used at all because it is not ShowDialog

Do you prefer either of these solutions? If so, why / why not?

**Comment by zsd4yr** [comment]
@tobster-de Can you post the output of profiling memory to confirm this?

**Comment by tobster-de** [comment]
For me it looks like the use of PropDialogOwner is an error. If I have to guess PropDialogOwner is the right one for ShowDialog and PropOwner is the one for Show. But I might not have the full insight in this. 

I posted an image of the profiler (retention path) at the DeveloperCommunity. You can have a look at the image [there](https://developercommunity.visualstudio.com/content/problem/479123/formshowpropdialogowner-causing-memory-leaks.html). Memory consumption is less interesting, it's about the allocated MB per form in the example.

**Comment by elachlan** [comment]
@dreddy-work should @Olina-Zhang and team verify this? It seems like the fix is not crazy difficult.

**Comment by Olina-Zhang** [comment]
This issue still reproduces using this testSample in .Net 8: 
[TestSample.zip](https://github.com/dotnet/winforms/files/10378378/TestSample.zip)
![image](https://user-images.githubusercontent.com/26474449/211447639-02a17dac-a1ad-42dc-b31d-d02c09070a7f.png)

**Comment by Amy-Li03** [comment]
Verified this using WinformsControlsTest app, issue was fixed, the During isn't growing to 500mb now and the After is lower than the During.
![image](https://user-images.githubusercontent.com/62929087/216221741-10217779-3095-42ac-912c-fd096c5a2c5a.png)

**Comment by John-Qiao** [comment]
Verified in .NET 8 Preview 1 TP build: .NET 8.0.100-preview.1.23108.10 with WinformsControlsTest app, issue was fixed as same as above test result.
![530-testresult](https://user-images.githubusercontent.com/45864985/218407736-423b9d55-83a8-4eac-b32f-f4af020e63ee.png)
