### ISSUE TITLE
DockEditor works like a RadioButton, but have got the LocalizedControlType value is check box

### ISSUE THREAD

**Issue by DmitryGorokhov** [dotnet/winforms#5307]
* .NET Core Version: 
6.0.100-rc.1.21370.2

* Have you experienced this same bug with .NET Framework?: 
Yes

* More info:
Created past the attempt to fix linked issue issue #4102. The described way in issue cause the narrator regression was reported by CTI - The narrator can't announce the status for Dock property: after compared between Dock and ImageAlign properties, due to they are all RadioButton type, found there have some properties are different. The way to fix reported bug wasn't found, so this issue are created.

**Problem description:**
DockEditor works like a RadioButton, but have got the LocalizedControlType value is check box. It is can be checked in Inspect.  

![image](https://user-images.githubusercontent.com/58004471/126497406-097f4579-d3f3-4b6a-9ee6-4542ccb0fdf0.png)

**Expected behavior:**
The LocalizedControlType value is "radio button". The narrator announce the status for Dock property as for some control have type of radio button.

**Minimal repro:**

https://github.com/dotnet/winforms/files/5376383/SampleApp.zip

- Create a winforms core app with PropertyGrid and Button control.
- Associate the Button with PropertyGrid as a selected object.
- Build and run the core project.
- Start Inspect tool.
- Open the drop down list next to ImageAlign.
- Focus on Top Center and observe LocalizedControlType in Inspect.

#### Linked issue
issue #4102

**Comment by vladimir-krestov** [comment]
There are 2 possible ways to fix it:
1) Add `AccessibleRole` as `RadioButton` for `DockEditorCheckBox` and `Change CheckBoxAccessibleObject`:
    - Override `IsItemSelected` property and add `SelectionItemPattern` supporting:

    ![image](https://user-images.githubusercontent.com/49272759/126500852-f09e2c47-4d82-4e43-ab5f-d9fc23c36719.png)

2) Change the base type of  `DockEditorCheckBox` to `RadioButton`. In this case, we have to fix drawing issue - editor is not shown. Hot fix - remove `_dropDownHolder.FocusComponent();` (1563) line in `PropertyGridView.DropDownControl` method. Then we need to get why it happens.

**Comment by vladimir-krestov** [comment]
There is no way to change properties in a common way, because most of necessary properties and method are internal, so we can't override them here. And CheckBox shouldn't know about `DockEditor`.

**Comment by John-Qiao** [comment]
Verified with 8.0.100-alpha.1.22478.15 from main branch, this issue has been fixed that the base type is RadioButton now.
![5307-1](https://user-images.githubusercontent.com/45864985/192930090-e90aaaa4-ced1-43dc-955b-15d8c3b3755e.png)
![5307-2](https://user-images.githubusercontent.com/45864985/192930093-22a02395-4c8b-434c-9341-8cec26a45477.png)
![5307-3](https://user-images.githubusercontent.com/45864985/192930098-548df5ba-9ab0-4923-8f97-09cfd1fa6701.png)
