### ISSUE TITLE
WinForms is testing against a very old shared framework

### ISSUE THREAD

**Issue by ericstj** [dotnet/winforms#531]
Observe https://github.com/dotnet/winforms/blob/7276127fafb6283beaa188a411ad2a43371641d3/global.json#L3

This hasn't been changed in 2 months.  This is determining what version of .NETCore APP that you build against and run your tests against, since you aren't setting RuntimeFrameworkVersion.

You should either set this to update regularly (eg: ingest the CLI as a tool dependency) or use RuntimeFrameworkVersion instead and do something like ASP.NET does to make that easier on folks using VS.

**Comment by zsd4yr** [comment]
Probably due for an update. The latest coherent release 3.0 preview 3 is probably a good candidate

**Comment by zsd4yr** [comment]
@ericstj when I updated https://github.com/dotnet/winforms/blob/7276127fafb6283beaa188a411ad2a43371641d3/global.json#L3 and https://github.com/dotnet/winforms/blob/7276127fafb6283beaa188a411ad2a43371641d3/global.json#L9 to `3.0.100-preview3-010436`, I started getting the following error on build for each of the csproj's

```diff
- E:\winforms\pkg\Microsoft.Private.Winforms.csproj : error NU1604: Project dependency Microsoft.NETCore.Platforms does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results
```

**Comment by zsd4yr** [comment]
I am pretty sure this is defined in out Versions.props https://github.com/dotnet/winforms/blob/c228cecdbfff920d3917f43b1571a68d74455d1b/eng/Versions.props#L20

**Comment by zsd4yr** [comment]
I cannot just include it because it is already implicitly referenced

**Comment by ericstj** [comment]
Looks like you had a bug here: https://github.com/dotnet/winforms/commit/aac2a79861ee60051a08a8fe0b456ed1f347c2f8#diff-56f8482aeb786dd105fbf93dedf2615fR8

MicrosoftNETCorePlatformsPackageVersion vs MicrosoftNETCorePlatformsVersion
