### ISSUE TITLE
[.NET 5/DPI] Switching Visual Studio winforms designer scaling to 100% breaks the designer rendering.

### ISSUE THREAD

**Issue by Tape-Worm** [dotnet/winforms#5389]
* .NET Core Version: 
5.0.8

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
I run my machine at 150% scaling because on these monitors I'd go blind at 100%. So, when I went to edit my form in my application, I got the "gold bar" prompt telling me to switch to 100%. No problem, I switch over and open the form.... and oh my... it did not look right at all.  The single button on the form was now off in space somewhere, the size of the form was massive, and there's this white, thick border around the designer area.

After I closed visual studio, I set it to be DPI unaware through the registry, and re-opened vs with the project, and opened the form in the designer. Now it looked right. However, when I compare my form launched from VS to just double clicking the EXE the sizes mismatch.

**Expected behavior:**
When I switch to 100% scaling, it should be no different than editing it any other time. The form shouldn't just start growing, the child controls should stay in roughly the same place.

**Minimal repro:**
1. Open Visual Studio
2. Create .NET 5 windows forms application
3. Add a form
4. Open in designer
4. Switch to 100% when the gold bar appears
5. Marvel at the chaos wrought by the old gods.

I've attached some images to show what I'm seeing.
![144Dpi](https://user-images.githubusercontent.com/9710137/128090272-8742b193-4f9e-44eb-b72a-ca77ce647065.png)
This is the form in VS at 150% scaling. 

![Madness](https://user-images.githubusercontent.com/9710137/128090296-8cc1faea-d04f-425e-8cd0-6f8887b4bc9e.png)
This is what happens when I switch to 100% scaling.

![Normal](https://user-images.githubusercontent.com/9710137/128090313-add14002-d128-42fe-be78-c0a8b25f05a9.png)
This is what I expect, and what I actually get when I run without DPI awareness on Visual Studio.

**Comment by Tape-Worm** [comment]
And like a dummy, I should have read the instructions closer, because it says to put these kinds of issues up on the VS feedback page instead of here.  I have done so now.  Sorry about that.

[https://developercommunity.visualstudio.com/t/NET-5DPI-Switching-Visual-Studio-win/1494798](https://developercommunity.visualstudio.com/t/NET-5DPI-Switching-Visual-Studio-win/1494798)

**Comment by KlausLoeffelmann** [comment]
We will approach this problem a different way: Simplified put, we will rewrite the CodeDom Serializer (that's the component in the Designer which generates the Code from the designed Form/UserControl) in the new Designer in a way that it serializes the controls as if they would have been designed in 96dpi no matter which the actual HighDPISetting in the Designer was at the time. And we will then disable the switching to 96dpi altogether.

**Comment by dreddy-work** [comment]
We will be removing "Gold bar" soon and the will be reimplementing the serialization in the later releases in the designer. We have a tracking issue in the internal repo and a feedback item already created above.  Closing it here
