### ISSUE TITLE
SplitContainer defaults its sub-panel's cursor to H/VSplit 

### ISSUE THREAD

**Issue by Craftplacer** [dotnet/winforms#5434]
* .NET Core Version: 5.0.400, 6.0.100-preview.7.21379.14
* Have you experienced this same bug with .NET Framework?:  No

**Problem description:**
When creating a `SplitContainer` and running the application, when the user hovers over the content panels (i.e. `Panel1` and `Panel2`) their cursor will be of either `HSplit` or `VSplit`, which is not correct.

**Expected behavior:**
That `HSplit` or `VSplit` appear only on the "split part" of the container.

**Minimal repro:**
![2aTOwtWiBX](https://user-images.githubusercontent.com/22963120/129674864-ee999b9c-aec4-41c4-98cd-860178f53161.gif)

Create an app with a `SplitContainer`, debug it and notice when hovering over the two panels that those are using the split cursor.

The example was built with .NET Core 3.1, but the issue persists up to .NET 5.0.

**Temporary solution:**
Set `Panel1`'s and `Panel2`'s cursor to `Default`.

**Comment by Marie-Shi** [comment]
There is a similar known [Designer issue](https://github.com/dotnet/winforms-designer/issues/3575).

**Comment by xiaoyuvax** [comment]
met the same problem and @Marie-Shi 's link is 404.

**Comment by RussKie** [comment]
@xiaoyuvax the link points to a private repo.

**Comment by RussKie** [comment]
@Craftplacer please provide a sample repro.

The designer exhibited a similar issue which was addressed in VS 17.2.

**Comment by RussKie** [comment]
Thank you @Craftplacer 

@xiaoyuvax please open a new issue and provide as much info as possible.

**Comment by RussKie** [comment]
The link points to a private repo.
________________________________
