### ISSUE TITLE
Not lock controls on base form

### ISSUE THREAD

**Issue by kelicto** [dotnet/winforms#5488]
* .NET Core Version: 

* Have you experienced this same bug with .NET Framework?: 

**Problem description:**

**Expected behavior:**
When close form designer and reopen the form, the state of lock is unlocked.

**Minimal repro:**

**Comment by dreddy-work** [comment]
@kelicto, We would need proper template filled here to understand the severity and priority of the issue. Please follow template guidance and provide complete details.

**Comment by kelicto** [comment]
GDI technology makes me very tired, and it is very troublesome to construct such an example. When the base form is modified, various inconsistent bugs are likely to occur in the sub form. Please test it yourself, I'm tired.

**Comment by kelicto** [comment]
https://github.com/dotnet/winforms/issues/5414
