### ISSUE TITLE
Windows Forms - Core fail w/VS19 RC1 and Core 3 preview 3

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/winforms#549]
_From @jchang6 on March 8, 2019 14:27_

After installing VS2019 RC1 and .NET Core 3.0 preview 3, my previous Windows Forms apps no longer open. In creating a new project, Windows Forms App (.NET Core) is one of the options, but fails to create. Message: No template could be found with the group identity 'Microsoft.Common.Winforms'
Also, in project properties: Target framework, .NET Core 3.0 is not an option

_Copied from original issue: dotnet/corefx#35893_

**Comment by jchang6** [comment]
in https://developercommunity.visualstudio.com/content/problem/471810/no-net-core-30-preview-in-visual-studio-2019-rc.html
on VS 2019 RC, we need to go to Tools->Options …
then check: Use previews of the .NET Core SDK
