### ISSUE TITLE
Designer pannel can't copy and paste controls. IDE problem.

### ISSUE THREAD

**Issue by cwing2019** [dotnet/winforms#5490]
* .NET Core Version: 
 3.1 Preview1 

* Have you experienced this same bug with .NET Framework?: 
  No 

**Problem description:**
when we create a new winform project ,everything is ok. we can create a button on the designer for winform1, and copy and paste .

when the project comes with:
  
![图片](https://user-images.githubusercontent.com/61647879/130218176-8ce20a5e-d396-454d-aa60-ef4573d0ff01.png)

as image above. we should can copy button1 to button2. but no ,we can't.

**Comment by cwing2019** [comment]
I thinks is the bug of the IDE

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.

**Comment by RussKie** [comment]
Please post the link to the VS Feedback issue here, so that our team can track it.
