### ISSUE TITLE
ContextMenuStrip has different behavior if menu item Enabled=false

### ISSUE THREAD

**Issue by roland5572** [dotnet/winforms#5493]
ContextMenuStrip control has different behavior if menu item Enabled=false

**Reproduced process:**

Step 1. Click the right mouse button anywhere on the form to open the context menu. 

![001](https://user-images.githubusercontent.com/88176616/130231525-8ce2c1bf-deba-4d8a-af07-730f9b112083.png)

Step 2. Move the mouse to the menu item. The menu item will display the **blue border**.

![003](https://user-images.githubusercontent.com/88176616/130231527-5303fcc1-c598-4e5e-9ed8-e54370e01a66.png)

Step 3. Then move the mouse outside the Form.

When menu item Enabled = true

The blue border **disappears**.

![004](https://user-images.githubusercontent.com/88176616/130231521-2c78ff7d-84ed-4782-ae4e-98e196348853.png)

When menu item Enabled = false

The **blue border** will still remain on the menu item.

![006](https://user-images.githubusercontent.com/88176616/130233149-cf5b04fa-6688-47f0-8007-ba36d15b4bf9.png)

The same problem exists in the **MenuStrip** control (System.Windows.Forms.MenuStrip).

![020](https://user-images.githubusercontent.com/88176616/130546534-0ff01a85-c75c-434b-ac6e-8e71948b2cd7.png)

Test .net Version:

**.net 5.0**

Test C# code:

```
using System;
using System.Windows.Forms;

namespace ContextMenuStripEnabledTest
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            var contextMenu = new ContextMenuStrip();

            for (int n = 1; n < 7; n++)
            {
                var item = contextMenu.Items.Add("Menu Item " + n);

                if (n > 3)
                    item.Enabled = false;
            }

            var frm = new Form()
            {
                StartPosition = FormStartPosition.CenterScreen,
                ContextMenuStrip = contextMenu,
                Width = 600,
                Height = 400,
            };

            Application.Run(frm);
        }
    }
}
```

**Comment by Ashley-Li** [comment]
Verified this issue with .NET 7.0.100-alpha.1.21566.13, this issue is fixed. 
![test_result](https://user-images.githubusercontent.com/56664234/142159741-df4a5b2c-bf35-457a-93c1-8de9d903d3cd.gif)
.

**Comment by roland5572** [comment]
> Verified this issue with .NET 7.0.100-alpha.1.21566.13, this issue is fixed. ![test_result](https://user-images.githubusercontent.com/56664234/142159741-df4a5b2c-bf35-457a-93c1-8de9d903d3cd.gif) .

Thank you @Ashley-Li 

The same problem exists in the **MenuStrip** control (System.Windows.Forms.MenuStrip).
Is it also fixed?

![020](https://user-images.githubusercontent.com/88176616/130546534-0ff01a85-c75c-434b-ac6e-8e71948b2cd7.png)

**Comment by Ashley-Li** [comment]
@roland5572 Yes, it also fixed.

**Comment by roland5572** [comment]
> @roland5572 Yes, it was also fixed.

@Ashley-Li ,Thank you very much.
