### ISSUE TITLE
Space error by base form

### ISSUE THREAD

**Issue by kelicto** [dotnet/winforms#5495]
* .NET Core Version: 

* Have you experienced this same bug with .NET Framework?: 

**Problem description:**
The position of the label not change value. I will upload the demo.

Base form: the space  is 6px.
![image](https://user-images.githubusercontent.com/23723575/130244111-8a578dde-a411-4c66-80b2-968ff284c375.png)

Current form: the space is 5px.
![image](https://user-images.githubusercontent.com/23723575/130243858-ade1c3b0-9c18-4ce8-b5da-32e25655f2ff.png)

**Expected behavior:**

**Minimal repro:**

**Comment by dreddy-work** [comment]
@kelicto, Please fill all details in this template.

**Comment by kelicto** [comment]
Ok. Please give me some time, I will provide the demo.

**Comment by kelicto** [comment]
Please give me some time, I'm very busy.

**Comment by kelicto** [comment]
GDI technology makes me very tired, and it is very troublesome to construct such an example. When the base form is modified, various inconsistent bugs are likely to occur in the child form. Please test it yourself, I'm tired.
