### ISSUE TITLE
ContextMenuStrip (and perhaps other controls) have unexpected 2px width difference

### ISSUE THREAD

**Issue by wjk** [dotnet/winforms#5497]
* .NET Core Version: 6.0.100-preview.7.21379.14
* Have you experienced this same bug with .NET Framework?: Didn't check, as I no longer target .NET Framework.

**Problem description:**

For some reason, Windows Forms is displaying all controls with 2px less width than they should have. While normally this is not visible, my calculations for menu item drawing are off, and text in controls without margins (e.g. LinkLabel) can become clipped. See below screenshots. I am running at 100% DPI scaling; I have not tested this issue at higher scaling settings yet. I can't tell if this is a regression, as it started happening after I updated my project to .NET 6, but still happens if I retarget my project back to .NET 5. It may be a bug in the Visual Studio designer. I am using VS2022 Preview 3.1. Thanks!

![Screenshot of error](https://user-images.githubusercontent.com/1915951/130271327-3cfd5b38-f9da-4f66-8023-4c11170c9e12.png)
![Another screenshot of error](https://user-images.githubusercontent.com/1915951/130271338-e9ea15bc-812f-4132-963a-fbd87f0f8c92.png)

**Comment by RussKie** [comment]
Are you able to provide a simple standalone repro?
