### ISSUE TITLE
Narrator's rectangle is displayed around TabControl when the user switches between TabPages

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#5571]
.NET Core Version: 
- NET Core SDK 6.0.100-rc.1.21416.15

Have you experienced this same bug with .NET Framework?: 
- No (regression from #3058)

**Repro steps:**

1. Create a form with `TabControl`.
2. Create several `TabPages` and add `TabPages` to the `TabControl`.
3. Run the application.
4. Switch between `TabPages`.

**Actual behavior:**
Rectangle is displayed around `TabControl`

**Expected behavior:**
The rectangle should be displayed around the `TabPage`
![Issue-5571-beforefix](https://user-images.githubusercontent.com/23376742/131138142-94a1de62-337b-46fb-a898-5a414298d4e2.gif)

**Comment by Amy-Li03** [comment]
Verified this issue with .NET SDK 7.0.100-alpha.1.21479.26, this issue is fixed.
![Fixed](https://user-images.githubusercontent.com/62929087/135410301-f3f71ae7-9562-446a-9674-03a2db4d1d29.gif)
