### ISSUE TITLE
Where are the .uex files?

### ISSUE THREAD

**Issue by dsherret** [dotnet/winforms#567]
Probably my bad for opening a question, but it relates to development on this repo.

Where are the .uex files? For example the `Control.uex` file.

```csharp
/// <include file='doc\Control.uex' path='docs/doc[@for="Control.ResetBindings"]/*' />
[EditorBrowsable(EditorBrowsableState.Never)]
public void ResetBindings() {
    // ...etc...
}
```

I'm curious if the xml doc summary for `ResetBindings` on `Control` is still the same as that method on `BindingSource` (the summary for that method on `Control` seems wrong to me).

Thanks!

**Comment by wjk** [comment]
AFAIK these were never released. Furthermore, cleanup and code-style PRs are actively removing them ([example](https://github.com/dotnet/winforms/pull/564/files#diff-6d09dbd56b04f34d80d5efffba3bf9fd)). I would say if there are problems with the documentation, raise it in [dotnet/docs](https://github.com/dotnet/docs) or by using the feedback mechanism on docs.microsoft.com. Hope this helps!

**Comment by dsherret** [comment]
@wjk Thanks! It does.
