### ISSUE TITLE
Change modifier of `ToolStrip` button background rendering methods to `internal`

### ISSUE THREAD

**Issue by ArtemTatarinov** [dotnet/winforms#5672]
If `OnRenderButtonBackground`, `OnRenderDropDownButtonBackground`, `OnRenderSplitButtonBackground` methods at `ToolStripRenderer` would be declared as not `protected` but `internal`, we could call them from derived classes.

Classes to affect: `ToolStripRenderer`, `ToolStripProfessionalRenderer`, `ToolStripSystemRenderer`, `ToolStripHighContrastRenderer`.

When trying to call the method from the derived class now:
![image](https://user-images.githubusercontent.com/87859299/131813764-08811444-e54d-41cb-ba48-0d7cc0037b2e.png)

Inside the class 'A' itself we can call protected methods of the objects with the same type 'A' too, that's why we can call protected method OnRenderSplitButtonBackground from RendererOverride property.

`ToolStripRenderer.cs`:
![image](https://user-images.githubusercontent.com/87859299/131814026-a8ebef63-c952-4677-8e74-1e828ba6bac5.png)

"Changing modifier on base class method from protected to internal may be the right approach here. "

_Originally posted by @dreddy-work in https://github.com/dotnet/winforms/pull/5614#discussion_r700551190_

**Comment by RussKie** [comment]
Unless the types are not public, changing `protected` to `internal` means we change public API, which is a breaking change. We can't do this.

**Comment by ArtemTatarinov** [comment]
We have discussed this issue with @vladimir-krestov, maybe the best approach would be checking & converting `RendererOverride` to the `ToolStripHighContrastRenderer` type, like that:

![image](https://user-images.githubusercontent.com/87859299/132461975-927f3f63-de1b-491a-a817-f612439c5cfd.png)

What do you think about it, should we make this refactoring at the `main` branch?

**Comment by dreddy-work** [comment]
I am fine with later but i do not want to spend dedicated time on this. This should be a cleanup task that can be picked up if you are touching this file again for any other task.

**Comment by Tanya-Solyanik** [comment]
I'm not getting CS1540 anymore. Also only the base class, `ToolStripRenderer` is referencing `RendererOverride`, I don't see why that warning was applicable. Perhaps an analyzer bug?
