### ISSUE TITLE
Accessibility: Color Contrast: Luminosity ratio is less than 3:1 for focus indicator on ToolStrip Buttons with System RenderMode (port to 6.0)

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#5673]
- .NET Core Version:
.Net SDK 6.0.100-rc.1.21417.19

- Have you experienced this same bug with .NET Framework?:
Yes

- More Info:
This issue cannot repro when setting ToolStrip/StatusStrip's RenderMode property to Professional or ManagerRenderMode

**Minimal repro:**
1. Open attached app in VS
[ToolStipButtonSystemRenderer.zip](https://github.com/dotnet/winforms/files/7097581/ToolStipButtonSystemRenderer.1.zip)
2. Build and run app
3. Use Accessibility Insight to detect the checked toolStripButton color contrast

**Expected behavior:**
The focus color(Light blue) for toolStripButton with 'System' RenderMode is contrast enough, greater than 3:1

**Actual behavior:**
The focus color(Light blue) for toolStripButton with 'System' RenderMode is not contrast enough:
![image](https://user-images.githubusercontent.com/23376742/131816031-d816a889-feb7-4f33-aeeb-4aa04ce3fcee.png)

**Comment by Ashley-Li** [comment]
Verified this issue in the latest .net SDK 6.0 build: 6.0.100-rc.2.21466.17, it is fixed: the focus color(Light blue) for toolStripButton with 'System' RenderMode is contrast enough, greater than 3:1.
![image](https://user-images.githubusercontent.com/56664234/133712797-2da24944-f196-48be-a98e-7799439c0a24.png)

**Comment by Amy-Li03** [comment]
Verified this issue on .NET 6.0 RC2 test pass build: 6.0.100-rc.2.21473.26, it was fixed.
