### ISSUE TITLE
Keyboard focus is not clearly visible for ToolStripButtons when ToolStrip is in "System" render mode

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#5676]
- .NET Core Version:
.Net SDK 5.0.100-rc.1.20378.13

**More info**
The issue also can reduce when focus with mouse.

**Repro steps:**
1. Create a form with `ToolStrip`.
2. Set `System` render mode for `ToolStrip`
3. Add two `ToolStripButtons` to the `ToolStrip`.
4. Make the first `ToolStripButton` checked (`ToolStripButton.Checked = true`).
5. Run the application.
6. Set focus on the second `ToolStripButton`.

**Expected behavior:**
Keyboard focus should clearly visible for ToolStripButtons

**Actual behavior:**
Keyboard focus is not clearly visible for ToolStripButtons
![image](https://user-images.githubusercontent.com/23376742/131831276-1f6cd4fa-9038-478d-9ac9-7b8b686edfba.png)

**Note:**
The issue is also reproducible for High Contrast mode
- `System` render mode
![image](https://user-images.githubusercontent.com/23376742/131833747-2c03aa9c-b1e9-450d-aee2-fa773f5b7a6d.png)

- `Professional` render mode
![image](https://user-images.githubusercontent.com/23376742/131835015-9f712855-7c74-41c3-ac0e-9aa27e679281.png)

**Comment by Olina-Zhang** [comment]
@SergeySmirnov-Akvelon  Is this the similar issue: https://github.com/dotnet/winforms/issues/5502?

**Comment by SergeySmirnov-Akvelon** [comment]
`@SergeySmirnov-Akvelon Is this the similar issue: #5502?`

Hi @Olina-Zhang. This bug is more about the fact that it is difficult for the user to see the differences between the checked and the focused button.

**Comment by Amy-Li03** [comment]
Verified this issue on .NET SDK 7.0.100-preview.3.22179.4 build, issue was fixed, now the keyboard focus clearly visible for ToolStripButtons on normal mode and High contrast mode.
![image](https://user-images.githubusercontent.com/62929087/161932932-6464648e-a9a2-4701-8b69-8a5427c63362.png)
![image](https://user-images.githubusercontent.com/62929087/161934996-fb9a14d3-0d2a-4f05-bd96-2d4dcd1e78c7.png)
