### ISSUE TITLE
UIA navigation doesn't work with the TabControl (port to 6.0)

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#5687]
**.NET Core Version:**
.NET SDK 5.0.100-Preview.4.20209.25 + latest VS2019

**Have you experienced this same bug with .NET Framework?:**
Yes

**Problem description:**
UIA navigation to move backwards/forwards through AIWin(Accessibility Insights For Windows) keyboard combination Shift+Ctrl+F5/F6/F7/F8/F9 doesn't work with the TabControl. AIWin can’t move backwards/forwards correctly through the set of sibling tab items. This issue also can reproduce when targeting .NET Core 3.1.

Please see the attached repro video:
[AIWinKeyboard_function_issue_with_Winforms.TabControl.zip](https://github.com/dotnet/winforms/files/7104120/AIWinKeyboard_function_issue_with_Winforms.TabControl.1.zip)

**Expected behavior:**
AIWin should be able to move backwards/forwards through the tab items.
Please see the attached repro video:
[NotReproWithOtherElements.zip](https://github.com/dotnet/winforms/files/7104123/NotReproWithOtherElements.1.zip)

**Minimal repro:**

1. Build a new .NET Core WinForms app with a tab control that have a few tab items. Or open the attached app.
[WinFormsTabTest_AIWinKeyboardIssue.zip](https://github.com/dotnet/winforms/files/7104125/WinFormsTabTest_AIWinKeyboardIssue.1.zip)

2. Run the app, and launch the Accessibility Insights For Windows (AIWin) tool at it. Verify that the UIA hierarchy seems reasonable.
3. Use the AIWin keyboard shortcuts of Shift+Ctrl+F5/F6/F7/F8/F9 to move AIWin around the UIA tree particular ‘tab’ tree. For more details about the shortcuts behavior please visit https://accessibilityinsights.io/docs/en/windows/reference/keyboard.

**Comment by Philip-Wang01** [comment]
Verified this issue with .NET 6.0 RC2 latest build: 6.0.10-rc.2.21465.13. UIA navigation is suitable for TabControl
![image](https://user-images.githubusercontent.com/86937911/133567705-1b35b678-830a-46b1-886f-b456b6db5ccc.png)

**Comment by Jenna-Zheng** [comment]
Verified this issue on .NET 6.0 RC2 test pass build: 6.0.100-rc.2.21473.26, it was fixed.
