### ISSUE TITLE
The "AccessKey" property returns an String.Empty instead of "Alt+n" value for "&Name" text

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#5702]
.NET Core Version: 
- .NET Core 6.0.100-rc.1.21430.12

Have you experienced this same bug with .NET Framework?: 
- No

**Repro steps:**

1. Create a form with any of the controls listed as done in the task #3421
2. Set `&Name` text for this control.
3. Run application.
4. Run Inspect
5. Check `AccessKey` property

**Actual behavior:**
The "AccessKey" property is Empty.String
![image](https://user-images.githubusercontent.com/23376742/132204959-486b72cf-b978-4d4a-a310-9fc72e26e3a2.png)

**Expected behavior:**
The "AccessKey" property must have "Alt+n" value
![image](https://user-images.githubusercontent.com/23376742/132204711-8b404f98-2121-4959-8661-1f2452b5b148.png)

## Notes:
**Controls with correct behavior:**
- [X] ContainerControl
- [X] Control
- [X] DateTimePicker
- [X] LinkLabel
- [X] MaskedTextBox
- [X] MdiClient
- [X] PrintPreviewControl
- [X] RichTextBox
- [X] ScrollableControl
- [X] SplitContainer
- [X] TabControl
- [X] TabPage	
- [X] TextBox	
- [X] ToolStripContainer
- [X] ToolStripPanel
- [X] TreeView
- [X] UserControl
- [X] WebBrowser

**Controls with wrong behavior (we should compare their behavior with .NET Framework 4.7.2 and correct if necessary):**
- [ ] BindingNavigator
- [ ] Button
- [ ] CheckBox
- [ ] CheckedListBox
- [ ] ComboBox
- [ ] ContextMenuStrip
- [ ] DataGridView
- [ ] DataGridViewComboBoxEditingControl
- [ ] DataGridViewTextBoxEditingControl
- [ ] DomainUpDown
- [ ] FlowLayoutPanel
- [ ] Form
- [ ] GroupBox
- [ ] HScrollBar
- [ ] Label
- [ ] ListBox
- [ ] ListView
- [ ] MenuStrip
- [ ] MonthCalendar
- [ ] NumericUpDown
- [ ] Panel
- [ ] PictureBox
- [ ] PrintPreviewDialog
- [ ] ProgressBar
- [ ] PropertyGrid
- [ ] RadioButton
- [ ] Splitter
- [ ] StatusStrip
- [ ] TableLayoutPanel
- [ ] ToolStrip
- [ ] ToolStripContentPanel
- [ ] ToolStripDropDown
- [ ] ToolStripDropDownMenu
- [ ] TrackBar
- [ ] VScrollBar

**Comment by Ashley-Li** [comment]
Verified this issue with .NET SDK 7.0.100-alpha.1.21479.26, it is fixed that the "AccessKey" property have "Alt+n" value.
![image](https://user-images.githubusercontent.com/56664234/135406223-c0be3541-9cf1-422e-a09c-84a214d09dec.png)
