### ISSUE TITLE
No Program.cs file generated for 5.0 core project after installed the latest .NET 6.0 rc.2 

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#5706]
* .NET Core Version: 
.NET 6.0.100-rc.2.21456.3 

* More info: 

1. This is a regression issue, can't reproduce after installed dotnet-sdk-6.0.100-rc.2.21452.43-win-x64. 
2. The issue can't reproduce for core project targetting with 3.1. 
3. For latest .NET 6.0 rc.2, the feature "new application bootstrap logic" was enabled, maybe related the PR: [5035](https://github.com/dotnet/winforms/pull/5035)

* Have you experienced this same bug with .NET Framework?: 
 No 

**Problem description:**
No Program.cs file generated for 5.0 core project after installed the latest .NET 6.0 rc.2. 

**Expected behavior:**
The Program.cs file generated for 5.0 core project after installed the latest .NET 6.0 rc.2 

**Minimal repro:**
1. Installed the latest .NET 6.0 rc.2. 
2. Crete .NET Core 5.0 project. 
3. Observe the Program.cs file for 5.0 core project in the solution explore window.
![image](https://user-images.githubusercontent.com/38325459/132278283-0cf45e39-9388-4fcc-beb7-5dc7e3490a51.png)

**Comment by RussKie** [comment]
If this is RC2, then it is likely caused by https://github.com/dotnet/winforms/pull/5609. I'll investigate.

**Comment by RussKie** [comment]
It is indeed missing from https://github.com/dotnet/winforms/tree/release/6.0/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/net5.0, since #5609...

**Comment by Zheng-Li01** [comment]
Verified the issue with latest .NET 6.0.100-rc.2.21460.37 build, the issue has been fixed that program.cs file generated for 5.0 core project after installed the latest .NET 6.0 rc.2.

Note: hitting known [designer issue ](https://github.com/dotnet/winforms-designer/issues/3724)

**Comment by Philip-Wang01** [comment]
Verified the issue with latest .NET 6.0.100-rc.2.21473.26 build, the issue has been fixed that program.cs file generated for 5.0 core project after installed the latest .NET 6.0 rc.2.
![image](https://user-images.githubusercontent.com/86937911/135032917-04353fdc-90ea-4f37-b0d7-facf06252be6.png)
