### ISSUE TITLE
NET5.0.9 ListView BackgroundImage GDI object leak

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#5717]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET509-ListView-BackgroundImage-GDI-ob/1523781)._

---
[severity:I'm unable to use this version]
When a win forms app shows a form with a ListView Control that has its BackgorundImage set it does not release 3 GDI objects each time it is disposed and Garbage collected, this is causing major memeory leaks in our application.

Attached is a sample application to demonstrate the issue.

All I did to re-create this, is the following.

1. Create a new winforms application

    ![image](https://user-images.githubusercontent.com/4403806/132600350-80182ede-3d00-453f-a30d-afd067ab7bfc.png)
    ![image](https://user-images.githubusercontent.com/4403806/132600509-c962e7e0-cb5f-4b88-9c6a-3dbb370ef60f.png)

2. Add a new form so you have a Form1 and a Form2.

    ![image](https://user-images.githubusercontent.com/4403806/132600525-31ef1d1d-2c89-4eb8-bd46-5231d9e7ca19.png)

3. Add two buttons on Form1, one to garbage collect, and one to open Form2.
    ```cs
        private void btnGarbageCollect_Click(object sender, EventArgs e)
		{
			GC. Collect();
		}

        private void btnOpenFormWithListView_Click(object sender, EventArgs e)
		{
			Form2 oForm = new Form2();
            oForm.Show();
		}
    ```

4. On Form2 add a listview and set a backgroup image from a resource.

    ![image](https://user-images.githubusercontent.com/4403806/132600540-35e3b649-a280-4267-9575-f6a05b960e85.png)

5. Open Task manager with the GDIObjects coulmn enabled, and keep opening and closing from 2 from the app and garbage collecting, you will see a jump of 3 GDI objects each time you open and close the form.

    ![image](https://user-images.githubusercontent.com/4403806/132600563-b781337b-7e2c-4eb6-8968-372bcca59077.png)

---
#### Feedback Bot on 9/8/2021, 09:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Marie Shi [MSFT] solved on 9/8/2021, 05:09 PM, 0 votes: 

We moved this issue to a relevant GitHub project. Please comment and track it at this URL: https://github.com/dotnet/core/issues/6667

**Comment by Marie-Shi** [comment]
**More info:**
1.	This is not a regression issue, it can repro in .Net Framework, also can repro in .NET 3.1, 5.0& 6.0.
2.	This issue cannot repro in imageList.

**Repro Steps:**

1.	Extract the attachment “BackGroundImageIssue.zip” and open it in VS.
2.	Open Task manger, select the 'Details' tab and add GDI objects column if not already visible.
3.	Build and run the application, click ‘Open Form With List View’ button to open Form2 then close Form2, then click ‘Garbage Collect’ button, repeat this operation several times.

**Actual behavior:**
The number of GDI objects are increasing.
![feedback](https://user-images.githubusercontent.com/45864017/132483441-968481b7-0b2d-47a0-9d82-8c734809024d.gif)

**Expected behavior:**
"GDI objects" don't increase.

**Comment by weltkante** [comment]
The GDI handles are leaked every time a BackgroundImage is assigned (given the ListView handle is already created). I've made a memory snapshot comparison and there seem to be no managed objects leaked. Needs investigation of what happens on the native level, I'll continue looking into it, but it may not be fixable on WinForms level if simple reassignment already leaks the previous images handles. Also explicitly clearing the image by sending `LVBKIF.SOURCE_NONE` does not prevent the handle leak.

**Comment by RussKie** [comment]
Are you able to check if MFC exhibiting the same issue?

**Comment by weltkante** [comment]
good point, will check

**Comment by weltkante** [comment]
Oh wow, this has nothing to do with the native `ListView` at all. Winforms `ListView.GenerateRandomName` uses `Bitmap.GetHIcon` to generate a seed for a randomizer and never releases that handle ... that is really weird code (and doesn't even guarantee being colission-free). I'll create a PR to simplify this.

**Comment by Ashley-Li** [comment]
Verified this issue in the latest .net SDK 6.0 build: 6.0.100-rc.2.21466.17, it is fixed: after build and run the application, click ‘Open Form With List View’ button to open Form2 then close Form2, then click ‘Garbage Collect’ button, repeat this operation several times, the"GDI objects" don't increase. Please see below gif:
![gdiissue](https://user-images.githubusercontent.com/56664234/133712056-34c746e8-2065-4fa4-bf8d-db8629015ece.gif)

**Comment by Marie-Shi** [comment]
Verified this issue with .Net 6.0.100-rc.2.21473.26 from 6.0 RC2 Test Pass, it is fixed, now "GDI objects" don't increase. The result is same as above.
