### ISSUE TITLE
Move the implementation of properties "RuntimeId" to the base "ControlAccessibleObject" class for all inheritors

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#5761]
Many accessibility objects for controls have different implementations for `RuntimeId` properties. Although in fact it is one and the same property and its implementation should not have logic specific to which control. Therefore, I suggest to use the implementation of `RuntimeId` properties from the base `ControlAccessibilityObject` class for all accessibility objects. For the base class, I would suggest using one of two implementations:

**Current base implementation:**
```
if (_runtimeId is null)
{
    _runtimeId = new int[] { 0x2a, (int)(long)HandleInternal };
}

return _runtimeId;
```

**Implementation from some accessibility objects:**
```
internal override int[] RuntimeId
{
    get
    {
        var runtimeId = new int[3];
        runtimeId[0] = RuntimeIDFirstItem;
        runtimeId[1] = (int)(long)Owner.InternalHandle;
        runtimeId[2] = Owner.GetHashCode();

        return runtimeId;
    }
}
```

Probably we can even use the current base implementation. Because if the `Handle` is not created, then the external tool will not have access to the control. If the `Handle` is created, then it will be unique for each `Control`.

**Comment by Olina-Zhang** [comment]
Tested some controls on .NET 9.0.100-alpha.1.23564.26 + private dlls(build from main branch of WinForms repo), focus on the RuntimeId property in Inspect tool, no new regression issue found.
