### ISSUE TITLE
With .Net 6.0 Dropdown Combo does not respect mode

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#5786]
* .NET Core Version: 
.Net 6

* Have you experienced this same bug with .NET Framework?: 
No, not with .Net 5.0

**Problem description:**
Under 6.0 with no changes to anything except changing TargetFramework under .Net 6 the dropdown box does drop but shows all items.
![image](https://user-images.githubusercontent.com/12789369/133703131-c2e7bca8-6285-4708-b239-5e3ff77c966a.png)

From designer
![image](https://user-images.githubusercontent.com/12789369/133702773-0e2a884d-df7f-45b6-943e-327dd3a53ccc.png)

Runtime 5.0
![image](https://user-images.githubusercontent.com/12789369/133702706-fbebd103-6cc9-4198-9dfd-1901b275aaa8.png)

Runtime 6.0
![image](https://user-images.githubusercontent.com/12789369/133702975-26255718-1b5f-471f-a78a-4aa5e9280192.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/12789369/133702706-fbebd103-6cc9-4198-9dfd-1901b275aaa8.png)

**Minimal repro:**
https://github.com/paul1956/CSharpToVB and change TagetFramework in all projects to .Net 6

**Comment by RussKie** [comment]
@paul1956 could you please clarify the repro steps. The sample repo contains a lot of files.

**Comment by paul1956** [comment]
In each project just change target framework to .Net 6. I did this under VS 2022 Preview 4 and you see error then undo changes and it runs in .Net 5.0.

**Comment by paul1956** [comment]
@RussKie I made it simple Master is .Net 5.0 and DotNet6 is .Net 6.0 the only different is the project files TargetFramework  setting.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you see if this repros with C# for us? This looks like a ToolStrip/MenuStrip ComboBox control. @paul1956 please correct me if I'm wrong there 😄

**Comment by paul1956** [comment]
@merriemcgaw This is fixed in Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.3.0 Preview 1.1. Sorry but I don't know when it was actually fixed. I or someone else could close.

**Comment by KlausLoeffelmann** [comment]
OK, closing it.
@paul1956, if you stumble over it in the future again, feel free to reopen.
Thanks!
