### ISSUE TITLE
Move refout project settings to a targets file

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#583]
As part of PR https://github.com/dotnet/winforms/pull/237, we have added following two properties in each implementation assembly:
    
    <Deterministic>true</Deterministic>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>

As per Eric's feedback, we should move them to Directory.Build.props under a conditional section like:

<PropertyGroup Condition="''$(IsShipping)' == 'true' And '$(IsFacadeAssembly)' != 'true'"> 

It means we will need to add IsShipping property in implementation assemblies.

But problem is that due to order of evaluation of props files, project properties are not available at that point. 

Hence we need to move these to a targets file.

**Comment by RussKie** [comment]
I'm not seeing a significant value-add apart from spending 0.5-1 day messing with MSBuild props and targets.
We can revisit this when/if it becomes necessary.
