### ISSUE TITLE
System.TypeLoadException : Type 'System.Configuration.ClientSettingsSection' does not inherit from 'System.Configuration.IConfigurationSectionHandler'

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#5836]
### Description

Lately (RC1 timeframe?) dotnet/winforms tests for functionality that depends on `System.Configuration.ApplicationSettingsBase` started randomly failing with the following callstack (e.g. [#1](https://dev.azure.com/dnceng/public/_build/results?buildId=1367547&view=logs&j=fdea2036-e6b2-512d-a259-98f88c972586&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c), [#2](https://dev.azure.com/dnceng/public/_build/results?buildId=1367438&view=results), [#3](https://dev.azure.com/dnceng/public/_build/results?buildId=1367713&view=results)):
```
    System.Windows.Forms.Tests.ToolStripSettingsManagerTests.ToolStripSettingsManager_Save_Load_RoundTripExpected [FAIL]
      System.Configuration.ConfigurationErrorsException : An error occurred creating the configuration section handler for userSettings/System.Windows.Forms.ToolStripSettings.MainForm.Child: Type 'System.Configuration.ClientSettingsSection' does not inherit from 'System.Configuration.IConfigurationSectionHandler'. (C:\Users\vsagent\AppData\Local\.NET_Foundation\xunit.console_StrongName_fmofxrdwgybamyp2bf020liphqsc2hhw\2.4.1.0\user.config line 5)
      ---- System.TypeLoadException : Type 'System.Configuration.ClientSettingsSection' does not inherit from 'System.Configuration.IConfigurationSectionHandler'.
      Stack Trace:
           at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
           at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
           at System.Configuration.BaseConfigurationRecord.GetSection(String configKey, Boolean getLkg, Boolean checkPermission)
           at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
           at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
           at System.Configuration.ConfigurationManager.GetSection(String sectionName)
           at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
           at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
           at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
           at System.Configuration.SettingsBase.SetPropertyValueByName(String propertyName, Object propertyValue)
           at System.Configuration.SettingsBase.set_Item(String propertyName, Object value)
           at System.Configuration.ApplicationSettingsBase.set_Item(String propertyName, Object value)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettings.cs(42,0): at System.Windows.Forms.ToolStripSettings.set_ItemOrder(String value)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs(65,0): at System.Windows.Forms.ToolStripSettingsManager.Save()
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSettingsManagerTests.cs(23,0): at System.Windows.Forms.Tests.ToolStripSettingsManagerTests.ToolStripSettingsManager_Save_Load_RoundTripExpected()
        ----- Inner Stack Trace -----
           at System.Configuration.TypeUtil.VerifyAssignableType(Type baseType, Type type, Boolean throwOnError)
           at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.Init(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord)
           at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory..ctor(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord)
           at System.Configuration.RuntimeConfigurationRecord.CreateSectionFactory(FactoryRecord factoryRecord)
           at System.Configuration.BaseConfigurationRecord.FindAndEnsureFactoryRecord(String configKey, Boolean& isRootDeclaredHere)
```

Upon a restart tests would generally pass (though it may take few attempts). There is no detectable pattern - a failure can occur on any bitness and in any build configuration.

**WHY:** I have no idea why this is starting failing. Has their been any changes in the Settings related area? 
This could be that build agents aren't getting cleaned, and we get something else interfering /cc: @MattGal 

There is nothing Windows Forms specific in this callstack.
We have a [`ToolStripSettings class`](https://github.com/dotnet/winforms/blob/8b918a8f476b7e5742e719aa7a9bb0debcb1590c/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettings.cs#L15):
![image](https://user-images.githubusercontent.com/4403806/133712965-53b2c882-313b-4b1f-97fd-ebbb4e006ae7.png)
which we use to [persist toolstrip-related settings](https://github.com/dotnet/winforms/blob/8b918a8f476b7e5742e719aa7a9bb0debcb1590c/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs#L62):
![image](https://user-images.githubusercontent.com/4403806/133713178-c4e4c21f-f8c9-469b-9c5b-cefce57ba82a.png)

When I run the same test locally I get the following configuration persisted under `C:\Users\<user>\AppData\Local\Microsoft_Corporation\testhost_StrongName_ncwojqheyhc0dhynwiffp31oq4puy42y\15.0.0.0\user.config` with the following content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" >
            <section name="System.Windows.Forms.ToolStripSettings.MainForm.Child" type="System.Configuration.ClientSettingsSection, System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    ...omited for brevity...
</configuration>
```

With a high degree of probability and based on the raft of other similar issues, I can speculate that the issue is caused by the persisted identity `System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51`. 
The original .NET Framework serialised the settings with the following identities:
```xml
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="settings_issue.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
```

The same underlying issue is causing the following issues that are affecting the runtime and design-time (i.e. VS) experience of Windows Forms apps:
* [AB#1388851](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1388851/)
* https://github.com/dotnet/project-system/issues/6784
* https://github.com/dotnet/project-system/issues/6799
* https://github.com/dotnet/winforms/issues/3346
* https://github.com/dotnet/winforms/issues/4308

**FIX:** Instead of writing the versions that the app targets we should continue writing the original .NET Framework versions, which will continue to work via the TF.
@ericstj do you have any thoughts on this?

The only truly affected scenario is custom user types in the Settings editor in VS (and causes [AB#1388857](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1388857/)), but Windows Forms teams has had a number of internal discussions, and we believe this scenario can/should be deprecated, and any customer depending on it should roll their own implementation, if truly necessary:
![image](https://user-images.githubusercontent.com/4403806/133718159-6d8a6152-9d41-47c7-b8cb-aa742d062a47.png)

### Regression?

I believe it is a regression since it breaks back-compat (e.g. in VS scenarios - VS is run on net472 whilst customer apps are built on .NET stack).

/cc: @merriemcgaw  @dotnet/dotnet-winforms

**Comment by merriemcgaw** [comment]
Thanks all!

**Comment by ericstj** [comment]
One more thing.  My conclusion and recommendation here was based on the behavior of the tests which are hitting this.

A question was raised about design time vs runtime and sharing these files in that case.  I think that question is more in the wheelhouse of the designer owners.  Are you dealing with live types?  If so, then you really should be pushing the designer access into the surface process and running on the same framework as the app.  If you're not dealing with live types, or have a very *stable* contract for the types that you're dealing with then you could consider trying to get this to pin all the type names to the desktop identities.  If I understand this scenario correctly, your having a WinForms type save data in settings.  I'm guessing you won't want to be stuck on the set of types that existed in .NETFramework here so it seems to me like limiting to the desktop identity, even if it worked today, might be constraining you moving forward.

**Comment by RussKie** [comment]
Thank you @ericstj 

> If you're not dealing with live types, or have a very _stable_ contract for the types that you're dealing with then you could consider trying to get this to pin all the type names to the desktop identities. If I understand this scenario correctly, your having a WinForms type save data in settings.

I think that _application_ and _user_ settings fall squarely in this scenario. To the best of my knowledge both settings are widely used in Windows Forms apps (.NET Framework) and will continue to be used with apps migrated to .NET. During the transition period it is quite plausible that both .NET Framework and .NET versions of apps may co-exist and attempt to use same configs (as undesirable as it may be).

In addition we are currently constrained by the VS Settings designer (run on .NET Framework, written in VB) that is largely unable to work correctly with .NET types (see https://github.com/dotnet/project-system/issues/6784#issuecomment-909901635). There is little hope this designer will see any uplift or an alternative any time soon.

Also the settings are limited to a pre-defined set of types, all of which exist in both .NET Framework and .NET, and are accessible via the TF:
![image](https://user-images.githubusercontent.com/4403806/135034930-bbb0e72a-3dbf-4ffc-9736-9b2a903b5bec.png)
The only exception to the list is the last option which allows setting an arbitrary type, but 
- the VS Settings designer for this scenario isn't working (AB#1388857), and
- the team had an internal discussion and agreed that this scenario can be deprecated.


> I'm guessing you won't want to be stuck on the set of types that existed in .NETFramework here so it seems to me like limiting to the desktop identity, even if it worked today, might be constraining you moving forward.

The internal discussions concluded that we would like to continue to facilitate the experience but wouldn't want to invest or innovate in this direction further.

**Comment by RussKie** [comment]
@ericstj would you have any recommendation on the best way to proceed if we resolve that pinning Settings type names to the desktop identities is the right thing to do?

**Comment by ericstj** [comment]
> quite plausible that both .NET Framework and .NET versions of apps may co-exist and attempt to use same configs (as undesirable as it may be).

It's plausible however If anyone tried it they'd be blocked and would have raised this issue. The only reason we're looking at this is because tests hit it.  In both cases we've seen it, the tests actually were unintentionally sharing this state so the "right fix" was to clean that up.

> would you have any recommendation on the best way to proceed if we resolve that pinning Settings type names to the desktop identities is the right thing to do?

I think you need to start a discussion by filing an issue in dotnet/runtime as a design change request that the component responsible for writing `user.config` honors the `TypeForwardedFrom` attribute when writing out settings files and that `TypeForwardedFrom` be added to any type that  might be missing this and requires it for your scenario.  You'd also need to evaluate if such a design change has impact on other users to the API you're asking to change: not just the WinForms users, but anyone using the API. 

It'd be good to call out the real user scenario that's impacted by lack of this feature, and list out why existing work arounds aren't sufficient.  It would be good to call out what the designer scenario is for loading these types and why it's constrained just to .NETFramework equivalent types and not user types.  For example it would make no sense to fix this issue if it only worked for toy "hello world" apps, but the moment someone actually used user types break (since those wouldn't load in .NETFramework).

Keep in mind this is a legacy component you'd be asking to change, so we have a pretty high bar to make these types of changes to it due to risk involved.

**Comment by RussKie** [comment]
I believe the designer concerns should be mitigated by https://github.com/dotnet/project-system/pull/7647. No further work for now until we get customer feedback.
