### ISSUE TITLE
MonthCalendar [regression] UpdateBoldedDates reset visual boldness of last month of multipage control

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#5853]
* .NET Core Version: 6.0.0-rc.1.21451.3

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
Last month of 2 page `MonthCalendar` control not display (or reset) visual boldness after `UpdateBoldedDates` call:

https://user-images.githubusercontent.com/17767561/134660612-3c899fb8-d52c-466f-af87-e5fe753fd485.mp4

**Expected behavior:**

https://user-images.githubusercontent.com/17767561/134660989-bf4a4a83-ad3e-43b7-bc7c-834be4724dc5.mp4

First thought that regression was introduced in https://github.com/dotnet/winforms/pull/4317 (I will try to check it a bit later). Last frames of .Net5 video above shows the bug that was fixed in #4317.

**Minimal repro:**
[WinFormsCoreTest_monthCalendar.zip](https://github.com/dotnet/winforms/files/7225031/WinFormsCoreTest_monthCalendar.zip)

**Comment by kirsan31** [comment]
Yes, regression was introduced in #4317. The problem is here:
https://github.com/dotnet/winforms/blob/8fcd2f23e79d3ad09c0502f3871bb0a23a4898ee/src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs#L1892
This code not working when we have more than 1 year on the page. I think must be something like this (not tested!):
```cs
int currentMonthIndex = currentDate.Year == displayRange.Start.Year ? currentDate.Month - displayRange.Start.Month :
    12 + currentDate.Month - displayRange.Start.Month;
```

**Comment by dreddy-work** [comment]
> Can't create PR by myself due to VS 2022 installation needed for this :(

Is this because you can not build from command line as well due to new tool set requirement?

**Comment by kirsan31** [comment]
> > Can't create PR by myself due to VS 2022 installation needed for this :(
> 
> Is this because you can not build from command line as well due to new tool set requirement?

Honestly I haven't tried with command line :worried:

**Comment by RussKie** [comment]
You _don't_ technically need VS to modify or build the repo, you can use something like VS Code to edit and build with `.\build.cmd`.

**Comment by kirsan31** [comment]
Yea, I got it. 
Will try a bit later when I have a time (if @vladimir-krestov doesn't show up).

**Comment by vladimir-krestov** [comment]
@kirsan31, you are awesome as always! Thank you for the filed Issue, investigation and the ready fix. 😊
I have prepared #5869, please review it.
