### ISSUE TITLE
MonthCalendar not firing DateSelected when first click on last date

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#5854]
* .NET Core Version: all up to 6.0 rc1

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
`MonthCalendar` not firing `DateSelected` when first click on last date (`MonthCalendar.MaxDate`):

https://user-images.githubusercontent.com/17767561/134663191-136921ca-8606-4443-8ac2-d041b148452c.mp4

**Expected behavior:**
`DateSelected` must firing on first click.

**Minimal repro:**
[WinFormsCoreTest_monthCalendar.zip](https://github.com/dotnet/winforms/files/7225031/WinFormsCoreTest_monthCalendar.zip)

**Comment by dreddy-work** [comment]
@kirsan31 , is that only for last day of the month?

**Comment by kirsan31** [comment]
@dreddy-work 
> @kirsan31 , is that only for last day of the month?

No, for any date that is `MonthCalendar.MaxDate`.
