### ISSUE TITLE
AL.exe should be converted to .Net Core

### ISSUE THREAD

**Issue by livarcocc** [dotnet/winforms#586]
_From @joperezr on November 16, 2015 19:50_

In order to build corefx repo using .Net Core version of msbuild, we require al.exe to run in .NetCore since we need to generate satellite assemblies. Today, if you try to build a project that needs this task will fail when trying to load it. There should be a workaround for the time being to disable the task from running, and once Al.exe is converted to net core it should be re-added back.

For this, I've used the .NetCore msbuild produced by https://github.com/dsplaisted/msbuild/tree/netcore-selfbuild

_Copied from original issue: Microsoft/msbuild#350_

**Comment by livarcocc** [comment]
_From @joperezr on November 16, 2015 19:51_

cc @dsplaisted

**Comment by livarcocc** [comment]
_From @dsplaisted on November 17, 2015 6:41_

It looks like this was needed for localization.  @weshaggard, what are your plans around enabling localization?  Will you need an equivalent to AL.exe on NET Core?

**Comment by livarcocc** [comment]
_From @weshaggard on November 17, 2015 21:17_

At this point we don't plan to ship satellite assemblies for RTM but we will eventually need support for producing them.

**Comment by livarcocc** [comment]
_From @dsplaisted on November 17, 2015 21:41_

@weshaggard Who needs to deliver xplat and .NET Core version of AL.exe's functionality?

**Comment by livarcocc** [comment]
_From @weshaggard on November 17, 2015 21:44_

That is a good question which I don't actually know an answer to at this point. I don't even know anything about AL.exe right now.

**Comment by livarcocc** [comment]
_From @nguerrera on October 12, 2017 22:11_

@jaredpar

**Comment by livarcocc** [comment]
_From @nguerrera on October 26, 2018 20:25_

IMHO, we should move the Csc-based satellite assembly generation down into common targets. AL.exe is effectively abandoned, bugs like #1490 will never get fixed.

**Comment by livarcocc** [comment]
_From @rainersigwald on October 26, 2018 20:29_

That seems reasonable to me, and 16.0/3.0 like a pretty good time for it, if we can fit it in.

**Comment by livarcocc** [comment]
I don't believe this issue belongs in the msbuild repo given that AL.exe is not really owned by us. Now that we have dotnet/winforms, moving the issue there, I think that's the right repo.

**Comment by nguerrera** [comment]
Not a winforms issue.
