### ISSUE TITLE
Separators for ColumnHeaders are shifted when RightToLeft = true and EnableHeadersVisualStyles = false

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#5874]
.NET Core Version: 
- 6.0.100-rc.1.21430.12

Have you experienced this same bug with .NET Framework?: 
- Yes

**Repro steps:**
1. Create a form with a `DataGridView`
2. Add multiple `Columns`
3. Set `RightToLeft = true`
4. Set `EnableHeadersVisualStyles = false`
5. Run the application

**Actual behavior:**
Separators for `ColumnHeaders` are shifted.
![image](https://user-images.githubusercontent.com/23376742/135073032-c293a5c1-e075-4f3c-be35-53b2bdc33e6b.png)

**Expected behavior:**
Separators for `ColumnHeaders` should not be shifted.

**Comment by dreddy-work** [comment]
That needs very good eye sight :) Is this only for RTL?

**Comment by vladimir-krestov** [comment]
@merriemcgaw, should we care about `EnableHeadersVisualStyles = false` cases? If no, let's close this

**Comment by merriemcgaw** [comment]
I think you're absolutely right. If we're not seeing this in the default configurations I think we should close this. Especially since this needs RTL to be true as well.
