### ISSUE TITLE
An instance of DataGridViewCheckBoxCell class has an incorrect value of ToggleState property.

### ISSUE THREAD

**Issue by DmitryGorokhov** [dotnet/winforms#5886]
* .NET Core Version: 
5.0

* Commit
63f0ca1525151312b065375daaf50d692c95b73b

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

An instance of `DataGridViewCheckBoxCell` class has an incorrect value of `toggleState` property. So if the cell is unchecked then `toggleState` is `On` and if the cell is unchecked then `toggleState` is `Off`.

**Expected behavior:**

The `DataGridViewCheckBoxCell` object has `On` value of `ToggleState` property if the cell is checked and `Off` value if the cell is unchecked.

**Minimal repro:**
1. Create WinForms application.
2. Placed DataGridView control on Form.
3. Add CheckBox column.
4. Build and run.
5. Launch the Inspect and explore CheckBoxCell.

You can detect the following problems:
- cell is unchecked - `Toggle.State` is `On`;
- cell is checked - `Toggle.State` is `Off`.

And `DefaultAction` property value is correct as you can see below.

![1](https://user-images.githubusercontent.com/58004471/135483244-e06592b0-6bb1-4ed6-8798-1d669e7afe8a.png)

![2](https://user-images.githubusercontent.com/58004471/135483262-ed1b0126-611c-4ba0-9c86-29b45fc7f0f8.png)

**Expected behavior example**
Expected like in Framework 4.7.2.

![3](https://user-images.githubusercontent.com/58004471/135483699-310955f5-b9b2-4ce5-88a8-337aef2004db.png)

![4](https://user-images.githubusercontent.com/58004471/135483706-255674fc-dacb-442c-ba84-0ed0bdbe7b81.png)

**Comment by dreddy-work** [comment]
Was this regressed in 6.0?

**Comment by RussKie** [comment]
The regression was introduced in https://github.com/dotnet/winforms/pull/3432 in .NET 5.0 RC1. /cc: @vladimir-krestov

**Comment by DmitryGorokhov** [comment]
Created PR #5889 port to 6.0. Merge it if needed
