### ISSUE TITLE
API Proposal: SplitButton and DropDownButton

### ISSUE THREAD

**Issue by manfromarce** [dotnet/winforms#5911]
**Is your feature request related to a problem? Please describe.**
Native Win32 button has a BS_SPLITBUTTON style (MFC also had SplitButton) but this has long been missing in WinForms.
Alternatives for SplitButton currently are:
- ToolStripSplitButton, but it can only be used inside a ToolStrip
- using a button, setting Image / BackgroundImage to a down arrow and detecting the button portion where clicks occur
- custom drawn button / custom control
However, these solutions don't always work well.
DropDownButton is quite easy to make because you just need to show a ContextMenuStrip when it's clicked, but since it's similar to SplitButton we could also implement it.

**Describe the solution you'd like**
We could implement SplitButton and DropDownButton in Windows Forms as new controls, or by adding a property (e.g. ButtonType) that changes the regular button appearance. Either way, there should be a DropDownItems property.
SplitButton would have a clickable area that doesn't show the drop-down menu and look like this:
![image](https://user-images.githubusercontent.com/45036600/135759524-db350414-56e1-4532-bdcf-75af3737e24d.png)
while DropDownButton should not have the separator and look similar to this:
![image](https://user-images.githubusercontent.com/45036600/135759738-11f2db47-7565-4681-91f3-d5a11eec8697.png)
Drop-down menus could essentially be ContextMenuStrips and should support adding ToolStripMenuItems and ToolStripSeparators.

**Will this feature affect UI controls?**
Yes
        - Will VS Designer need to support the feature? If yes, describe how you expect it to funсtion.
Yes, we could make the DropDownItems property editable with the same window that opens for MenuStrip and ContextMenuStrip's Items property:
![image](https://user-images.githubusercontent.com/45036600/135760097-6eec178a-1dc5-401c-b6ad-364ecd35679a.png)
        - Will this feature need to be localized or be localizable?
 Yes

**Comment by merriemcgaw** [comment]
Thanks for the suggestion! 

We don't have this on our current road map, and it actually comes with its own set of accessibility and usability issues. In fact, it is no longer recommended from a design guidelines perspective. We do use it in a few places currently in our code (and eventually I do want to remove that) and since we're open source you are more than welcome to use this code in your application.
