### ISSUE TITLE
`ErrorProvider` extend with `HasErrors` property

### ISSUE THREAD

**Issue by tugibaev** [dotnet/winforms#5912]
# Summary

`ErrorProvider` have a `Clear()` method which removes all errors on all linked controls. But no any property/method which can show errors are exists. 

# Rationale and Usage

Current version of `ErrorProvider` need to create boolean variable and set in on every `SetError` call to check errors are exists. It makes code less readable.

# Proposed API

Add readonly property `HasErrors`:

``` cs
namespace System.Windows.Forms {
   public class ErrorProvider {
       public bool HasErrors => this.items.Count > 0;
   }
}
```
# Examples

``` cs
// err - ErrorProvider placed on form

private bool CheckData(){
	err.Clear(); // Clears old error before new check
	
	if (!File.Exists("C:\\abc.txt"))	
		err.SetError(txtFileName, "File not exists");	
	if (numValue.Value > 100)	
		err.SetError(numValue, "Can't be greater than 100 percent");
		
	// ... other checks here...	
	
	return !err.HasErrors;
}
 

private void Save(){
	// Check values before save
	if (CheckData()){
		//Do save	
	}
}
```

**Comment by RussKie** [comment]
Marking as ready for the API Review Board to consider.

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.Windows.Forms {
   public class ErrorProvider {
       public bool HasErrors { get; }
   }
}
```

**Comment by RussKie** [comment]
Setting as up for grabs.

**Comment by eriawan** [comment]
@RussKie 

I think this issue is quite straightforward.
Could I have and work on this issue? Please assign to me, thanks in advance! 🙂

**Comment by RussKie** [comment]
Awesome, all yours @eriawan :)
