### ISSUE TITLE
System.ComponentModel.Design.* components from framework to core

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#592]
- [x] System.ComponentModel.Design.UndoEngine
 - [x] System.ComponentModel.Design.DesignSurface
 - [x] System.ComponentModel.Design.InheritanceService
 - [x] System.ComponentModel.Design.DesignerActionMethodItem
 - [x] System.ComponentModel.Design.DesignerActionPropertyItem

Related requests: #221 #469 

Track PR progress: #606

**Comment by 87Alex** [comment]
Hello,
What about the System.ComponentModel.Design.MultilineStringEditor class?
We use it in our designers.
[Editor("System.ComponentModel.Design.MultilineStringEditor, System.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", typeof(System.Drawing.Design.UITypeEditor))]
string ToolTip { get; set; }
