### ISSUE TITLE
[Accessibility] MAS 1.4.11: Luminosity contrast ratio of the sorting arrows of the DataGridView control are less than 3:1

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#5933]
* .NET Core Version: 
6.0.100-rtm.21507.9

* Have you experienced this same bug with .NET Framework?: 
Yes

**Minimal repro:**
1. Create a form with a DataGridView control
2. Add multiple columns
3. Run application
4. Add multiple rows

**Actual behavior:**
Focus on Column header, Luminosity contrast ratio of the sorting arrows of the DataGridView control are less than 3:1
![image](https://user-images.githubusercontent.com/26474449/136504040-41d5498f-579d-4d48-966e-3fcc548cb03e.png)

**Expected behavior:**
Luminosity contrast ratio of the sorting arrows of the DataGridView control are greater than 3:1

**Comment by vladimir-krestov** [comment]
@Olina-Zhang, could you please check, that this Issue is fixed for:
- .NET 6.0: after #6003 
- .NET 7.0: after #5832
If so, please close this Issue.

**Comment by merriemcgaw** [comment]
I left comments in the original AzDO bug, @Olina-Zhang if you could provide those testers with the sample app and 6.0 GA that would be super helpful!

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net 7.0 and the latest .Net 6.0 build, they all are fixed. Please see following testing result:
.Net 7.0:
![image](https://user-images.githubusercontent.com/26474449/140245890-caf8327e-6db6-4639-a251-c5b44d8a3f4d.png)
.Net 6.0:
![image](https://user-images.githubusercontent.com/26474449/140246477-b3d46c98-1463-4d54-a175-c04b0e1d3593.png)
Closing this issue now.
