### ISSUE TITLE
Unify common elements in csproj files and import them to prevent human error

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/winforms#594]
example:

> Build failed: ```error CS8107: Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.```
_Originally posted by @JuditRose in https://github.com/dotnet/winforms/diffs_

**Comment by zsd4yr** [comment]
LangVersion is defined in some / all our csprojects https://github.com/dotnet/winforms/search?q=extension%3A.csproj+langversion&unscoped_q=extension%3A.csproj+langversion

**Comment by eriawan** [comment]
@zsd4yr 
Since we are now going to use .NET Core 5.0 or later on master branch, can I submit a PR to set the C# LangVersion to `8.0`?

**Comment by RussKie** [comment]
We should be using `Directory.Build.props` for shared properties.

You're welcome to submit a PR.

**Comment by RussKie** [comment]
Sorry, responded too soon without checking.

We already use the "preview" version of the language:
https://github.com/dotnet/winforms/blob/0fcea83dfe/Directory.Build.props#L15
