### ISSUE TITLE
Unify namespace macros

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#595]
We need to unify these namespaces macros
WINFORMS_NAMESPACE 
WINFORMS_DESIGN_NAMESPACE
into DRAWING_DESIGN_NAMESPACE

Current name: https://github.com/dotnet/winforms/search?q=DRAWINGDESIGN_NAMESPACE&unscoped_q=DRAWINGDESIGN_NAMESPACE

`DRAWINGDESIGN_NAMESPACE` should be changed to `DRAWING_DESIGN_NAMESPACE`

**Comment by dreddy-work** [comment]
These are macros. Defined in proj file and used at compile time.
