### ISSUE TITLE
Child controls in nested split container scale incorrectly on secondary monitor.

### ISSUE THREAD

**Issue by Backadal441** [dotnet/winforms#5957]
* .NET Core Version:  .NET 6 RC1

* Have you experienced this same bug with .NET Framework?:  Have not tested

**Problem description:**
Child controls in nested split container scale incorrectly on secondary monitor. Look at the following steps.
Put a split container control on the form. Put another inside panel 2 of the first split container, dock=full. Put buttons as depicted below. Form’s AutoScaleMode=DPI. All controls anchor top, left.
These two lines run before Application.Run(New Form2).
`Application.SetDefaultFont(New Font("Segoe UI", 9))`
`Application.SetHighDpiMode(HighDpiMode.PerMonitorV2)`

![image](https://user-images.githubusercontent.com/67511417/137025538-77c573b6-2161-4302-b941-948721abce75.png)
Pic 1. Opened on primary monitor set to 100% DPI. Looks fine.

![image](https://user-images.githubusercontent.com/67511417/137029102-ac6295a4-cfd7-428a-9b59-5174ef5647b5.png)
Pic 2. Opened on primary monitor set to 150% DPI. Looks fine.
Opened on secondary monitor set to 150% DPI when primary primary monitor is set to 150% DPI. Looks fine.

![image](https://user-images.githubusercontent.com/67511417/137029595-b83c922c-db56-4b07-b177-8aa7e9fa37f2.png)
Pic 3. Opened on secondary monitor set to 150% DPI when primary monitor is set at 100% DPI. Sending WM_DPICHANGED on handle created (workaround #4854). Everything is off.

![image](https://user-images.githubusercontent.com/67511417/137029704-08a27e78-5dac-4d7c-accc-47e7bba37e8e.png)
Pic 4. Opened on primary monitor set to 100% DPI then dragged onto secondary monitor at 150% DPI. Scaling of child controls in nested split control is off.

**Expected behavior:**
It should look like Pic 2.

**Minimal repro:**
Put a split container control on the form. Put another inside panel 2 of the first split container, dock=full. Put buttons as depicted above. Form’s AutoScaleMode=DPI. All controls anchor top, left. Have primary monitor set to 100% DPI and secondary monitor set at 150% DPI.

**Comment by Amy-Li03** [comment]
Verified this issue on .NET 7.0.0-alpha.1.21566.13 build, issue was fixed.
1. Opened on secondary monitor set to 150% DPI when primary monitor is set at 100% DPI. Works well
![Pic3](https://user-images.githubusercontent.com/62929087/142169227-c59324a2-c5a8-465b-a6c3-084ee9c5ce23.png)

2. Opened on primary monitor set to 100% DPI then dragged onto secondary monitor at 150% DPI. Works well
![Pic4](https://user-images.githubusercontent.com/62929087/142169237-579b2c19-36e5-44df-8518-699b5b1ca9b9.png)
