### ISSUE TITLE
ListView not firing GroupCollapsedStateChanged when user expands/collapses a ListViewGroup using the keyboard

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#5960]
.NET Core Version: 
- .NET Core SDK: 7.0.0-alpha.1.21512.1

Have you experienced this same bug with .NET Framework?: 
- No. `ListViewGroup.CollapsedState` was implemented in .NET Core 5.0 (#3155)

**Repro steps:**
1. Create a `Form` with a `ListView`.
2. Add `ListViewGroups` to the `ListView` (`ListViewGroups` should have `CollapsedState = ListViewGroupCollapsedState.Expanded` or `CollapsedState = ListViewGroupCollapsedState.Collapsed`).
3. Add `EventHandler` for `GroupCollapsedStateChanged`.
4. Run the application.
5. Expand / collapse a `ListViewGroup` using the keyboard.

**Actual behavior:**
`ListView` not firing `GroupCollapsedStateChanged` when user expands/collapses a `ListViewGroup` using the keyboard
![5960](https://user-images.githubusercontent.com/23376742/137115469-013fdfbc-4036-4d40-8558-53b763edba67.gif)

**Expected behavior:**
`ListView` should firing `GroupCollapsedStateChanged` when user expands/collapses a `ListViewGroup` using the keyboard

**Comment by Jenna-Zheng** [comment]
Verified this issue with .NET SDK 7.0.100-alpha.1.22060.5, it is fixed.
1. Collapsed and expanded ListViewGroup from the keyboard with writing to log at the event handler:
![ListView_Keyboard](https://user-images.githubusercontent.com/64949616/148894977-06ebbace-0001-4089-8e09-7a0a3680b174.gif)
2. Examined Narrator's text while collapsing and expanding ListViewGroup from the keyboard:
![ListView_Narrator](https://user-images.githubusercontent.com/64949616/148895045-eb3ce92f-47b5-4764-99f5-fdd35fe631f1.gif)
3. Watched the ExpandCollapse.ExpandCollapseState property at the Inspect tool after expanding/collapsing group from the keyboard:
![image](https://user-images.githubusercontent.com/64949616/148895072-71cf019a-b5de-4b96-aa96-89ecf5c2a8a1.png)
![image](https://user-images.githubusercontent.com/64949616/148895251-73016361-02ac-4256-aaf3-3947e8c3f88f.png)

**Comment by Lydia-Shi** [comment]
Verified this issue with .NET 7.0.100-preview.1.22101.1, this issue is fixed, results as above.
