### ISSUE TITLE
The TextAlign of a label set MiddleCenter is invalid.

### ISSUE THREAD

**Issue by kelicto** [dotnet/winforms#6001]
* .NET Core Version: 

* Have you experienced this same bug with .NET Framework?: Y

**Problem description:**
![image](https://user-images.githubusercontent.com/23723575/137712723-67aeda32-61b7-47e8-92d6-7c6b3571cfa2.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/23723575/137835929-0db42a38-299a-41b3-99ef-e34e78c49f56.png)

**Minimal repro:**

**Comment by RussKie** [comment]
Please fill out the template correctly explaining what you believe the issue is, what you think the correct behaviour is, and provide a simple standalone sample.
