### ISSUE TITLE
Hardware acceleration for Winforms

### ISSUE THREAD

**Issue by d2phap** [dotnet/winforms#601]
The Winforms in .NET Framework is using GDI+ to render graphics which is not hardware-accelerated.

Please support a way to use GPU acceleration for Winforms.

**Comment by weltkante** [comment]
WinForms is mostly wrappers around native controls. Native controls are based on GDI in their WM_PAINT events. Sounds like it would turn WinForms into something it isn't supposed to be, because if you move away from GDI *and* native controls then there's nothing left of WinForms ...

**Comment by merriemcgaw** [comment]
Thank you for the suggestion, but this is not on our current roadmap. For .NET Core 3.0 we're looking to achieve parity with the .NET Framework version of WinForms and start working on Accessibility and HDPI improvements. Closing this issue for now.
