### ISSUE TITLE
The color contrast of the button border is less than 3:1

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6021]
.NET Core Version: 
- 7.0.0-alpha.1.21519.1

Have you experienced this same bug with .NET Framework?: 
- Yes (based on [#1101503](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1101503))

**Repro steps:**

1. Create a form with a button.
2. Run the application.

**Actual behavior:**
`Button.FlatStyle= FlatStyle.Popup`:

![image](https://user-images.githubusercontent.com/23376742/138100874-e9fd8f6e-329a-404d-a735-dba97584058e.png)

`Button.FlatStyle= FlatStyle.Standard`:

![image](https://user-images.githubusercontent.com/23376742/138101210-b6548454-81ba-4e85-9ba8-9614eccade8f.png)

`Button.FlatStyle= FlatStyle.System`:
![image](https://user-images.githubusercontent.com/23376742/138101603-b5c0f520-37df-4c41-9748-daaf9259df2d.png)

**Expected behavior:**
Luminosity contrast ratio of the button border is greater than 3:1.

**Comment by VinoWang01** [comment]
Verified with .NET SDK 7.0.100-alpha.1.21566.13 build, this issue is fixed now.
![image](https://user-images.githubusercontent.com/90816462/142343518-0ecd4a12-20f9-4555-8fcf-a6ea1edb3c37.png)
