### ISSUE TITLE
ClickOnce - Value Does Not Fall Within the Expected Range

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/winforms#6043]
### Description

Sometimes when trying to run my Click-Once deployed app, I get the above error

### Reproduction Steps

Not Sure.

### Expected behavior

It should work

### Actual behavior

I get this error:
[ExpectedRange.log](https://github.com/dotnet/runtime/files/7390672/ExpectedRange.log)

### Regression?

Not sure.  Just started using ClickOnce + .NET 6.x

### Known Workarounds

Completely uninstall the app.

### Configuration

Windows 11 x64 with .NET 6.0 RC2.

**Comment by TonyValenti** [comment]
Hi @dreddy-work -
I'm going to create a feedback ticket.  This issue is really dragging on us.

We have two different versions of our app and it seems like something in ClickOnce isn't isolating them from each other.
To recreate the issue, install these two apps in any order:
https://get.fasterlaw.com/UniversalMigrator/setup.exe
https://get.fasterlaw.com/UniversalMigrator.clio/setup.exe

You'll get the error.

If you clean out your ```%localappdata%\Apps\2.0``` folder, then the second one will install but not the first.

**Comment by elachlan** [comment]
Closing as this isn't the right repo.
