### ISSUE TITLE
The color contrast of the border of the CheckBox and RadioButton in the button mode is less than 3:1

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6062]
.NET Core Version: 
- 7.0.0-alpha.1.21519.1

Have you experienced this same bug with .NET Framework?: 
- Yes

**Repro steps:**

1. Create a form with a `CheckBox` or `RadioButton`.
2. Set `Appearance = Appearance.Button`.
3. Run the application.

**Actual behavior:**
`CheckBox` and `RadioButton` when
```
Checked = true,
FlatStyle = FlatStyle.Popup
```
![image](https://user-images.githubusercontent.com/23376742/138706224-905e0ac3-d9bc-4ff9-a9e8-f5e8465c6d4c.png)
![image](https://user-images.githubusercontent.com/23376742/138706245-cea7d20b-b034-4393-b5c9-2edb7028ff9f.png)

`CheckBox` and `RadioButton` when
```
Checked = true,
FlatStyle = FlatStyle.Flat
```
![image](https://user-images.githubusercontent.com/23376742/138706409-3c8d8a5c-8bd8-4a13-8169-b5b81246c49c.png)
![image](https://user-images.githubusercontent.com/23376742/138706422-97ba648e-eb97-4cef-a63f-71aed3d4d3f1.png)

**Expected behavior:**
Luminosity contrast ratio of the border is greater than 3:1.

**Comment by Tanya-Solyanik** [comment]
Closing, as the border is not a functional element.
