### ISSUE TITLE
The Index of DataGridViewComboBoxCell error.

### ISSUE THREAD

**Issue by kelicto** [dotnet/winforms#6072]
* .NET Core Version: -

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
![image](https://user-images.githubusercontent.com/23723575/139052349-f8d3676e-cc57-46b7-891f-d13786f8062c.png)
![image](https://user-images.githubusercontent.com/23723575/139051340-b26d33ef-ed6a-464e-a3de-eeccca78dde4.png)

**Expected behavior:**
Please see the above pictures. I don't know why. I have to write code to compare the column name.

```
        private void DgvConcrete_CellBeginEdit(object sender, DataGridViewCellCancelEventArgs e)
        {
            if (!(dgvConcrete[e.ColumnIndex, e.RowIndex] is DataGridViewComboBoxCell cboCell))
                return;

            if (dgvConcrete.Columns[cboCell.ColumnIndex].Name == dgvcMortarNo.Name)
            {
                cboCell.Items.Clear();

                foreach (var item in dgvcMortarNo.Items)
                {
                    if (item.ToString() == Res_Symbol_Forbidden)
                        continue;

                    cboCell.Items.Add(item);
                }
            }

            else if (dgvConcrete.Columns[cboCell.ColumnIndex].Name == dgvcMortarType.Name)
            {
                cboCell.Items.Clear();

                foreach (var item in dgvcMortarType.Items)
                {
                    if (item.ToString() == Res_Symbol_Forbidden)
                        continue;

                    cboCell.Items.Add(item);
                }
            }
        }
```

**Minimal repro:**
I don't know how to build the demo and it may take a lot of time. But, my code is very easy.

**Comment by kelicto** [comment]
@RussKi
[KeLi.ColumnIndexErrorDemo.zip](https://github.com/dotnet/winforms/files/7518746/KeLi.ColumnIndexErrorDemo.zip)
e

**Comment by dreddy-work** [comment]
@kelicto , its still unclear on what the issue here is and what you are expecting. Given this has been the case from .NET framework, we would need detailed explanation of the issue and how its going to help users outside of your application.

**Comment by kelicto** [comment]
I don't get target datagidview column by index. So, I have to use name to get it.

**Comment by RussKie** [comment]
If this is a behaviour that exists in .NET Framework (even if it may appear as a bug) then it is unlikely that we can or will change it because other users may have come to depend on it. 

I have also written a little sample, and I can reference columns by `Name`:
![image](https://user-images.githubusercontent.com/4403806/142551166-4918d210-0d0c-4e0c-a4c2-0bc80216aceb.png)

**Comment by kelicto** [comment]
Yes. Working on .NET Framework 4.x.

**Comment by kelicto** [comment]
My explicitly created columns coincided with the number of entity attributes, and I didn't realize that I had to set AutoGenerateColumns to false. Therefore, I failed to find this problem in time, and I think that if the index value is all 0, it is equivalent to a state of inoperability. If it is obtained, an exception should be thrown: tell the user to obtain it only when AutoGenerateColumns is false.

**Comment by RussKie** [comment]
Please refer to the docs: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview.autogeneratecolumns?view=windowsdesktop-6.0

I am not convinced there is an issue with the SDK, and see no follow up work on our end.

**Comment by kelicto** [comment]
I have described it very clearly. Our concern should be how the problem occurred and how to deal with it. You can leave it alone, but it can always exist, although the impact is really small. Many people in the Chinese Community Forum also have the same problem. This is how I found the pattern and then searched for the answer, and it was resolved smoothly.
