### ISSUE TITLE
Add missing unit tests for "AccessibleObject.FragmentNavigate" method

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6094]
Add missing unit tests for the `AccessibleObject.FragmentNavigate` method to the following classes:
- [x] DataGridViewCellAccessibleObjectTests (https://github.com/dotnet/winforms/pull/7930)
- [x] DirectionButtonAccessibleObjectTests  (https://github.com/dotnet/winforms/pull/8036)
- [x] ListViewItem_ListViewItemBaseAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8037)
- [x] ListViewItem_ListViewItemDetailsAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8037)
- [x] ListViewItem_ListViewItemTileAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8037)
- [ ] MenuStrip_MenuStripAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8248)
- [x] MonthCalendar_CalendarAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarBodyAccessibleObjectTests   (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarButtonAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarCellAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarDayOfWeekCellAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarHeaderAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarNextButtonAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarPreviousButtonAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarRowAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarTodayLinkAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_CalendarWeekNumberCellAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] MonthCalendar_MonthCalendarAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8039)
- [x] PropertyGrid_PropertyGridAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8206)
- [ ] StatusStrip_StatusStripAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8248)
- [X] ToolStripControlHost_ToolStripHostedControlAccessibleObjectTests (https://github.com/dotnet/winforms/pull/5877)
- [ ] ToolStripDropDownButton_ToolStripDropDownButtonAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8248)
- [ ] ToolStripGrip_ToolStripGripAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8248)
- [ ] ToolStripItemAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8248)
- [ ] ToolStripOverflow_ToolStripOverflowAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8248)
- [ ] ToolStripOverflowButton_ToolStripOverflowButtonAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8248)
- [ ] ToolStripSplitButton_ToolStripSplitButtonExAccessibleObjectTests (https://github.com/dotnet/winforms/pull/8248)
- [x] UpDownBase_UpDownButtons_UpDownButtonsAccessibleObject (https://github.com/dotnet/winforms/pull/8036)

**Comment by RussKie** [comment]
Can you please elaborate why we need to skip them, and at what point we will be able to unskip them?

**Comment by SergeySmirnov-Akvelon** [comment]
Sorry for the confusion. Task about missing unit tests, which for some reason we forgot to add, although the accessibility object has an explicit override for the `FragmentNavigate` method. In scope of this task, we plan to add these tests.
