### ISSUE TITLE
Remove unnecessary "DomainItemListAccessibleObject" and "DomainItemListAccessibleObject" classes.

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6095]
**Problem description:**
In accordance with the behavior adopted in the #4207, we should not display the accessibility object for the `Items` component in the Inspect. Thus, we no longer need `DomainItemListAccessibleObject` and `DomainItemListAccessibleObject` classes responsible for this, as well as unit tests that check these classes.

As part of this bug, I propose to remove the `DomainItemListAccessibleObject` and `DomainItemListAccessibleObject` classes and their corresponding unit tests

**Comment by vladimir-krestov** [comment]
Closed as completed in #7330
