### ISSUE TITLE
Localized description doesn't show up for WinForms templates for Chinese locale

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#6099]
**.NET Core Version:** 6.0 RTM

**Have you experienced this same bug with .NET Framework:** No

**Minimal repro:**

1. On an ENU OS, install ENU Dev17 GA VS build
2. From VS installer also install language packs for Chinese Simplified and Traditional
3. Change VS language from ENU to Chinese from VS -> Tools -> Options -> Environment -> International Settings -> Language
4. Restart VS
5. Click on 'Create a new project'
6. In the templates search box type 'WinForms' to search for WinForms templates
7. Check template description for WinForms .NET (Core) projects

**Result**: Template description is not localized

**Expected:** Localized description for WinForms CHS templates

On investigation we found that in [WinForms](https://github.com/dotnet/winforms/tree/main/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config) has 'zh-Hans' and 'zh-Hant' directories for Chinese translations. Looks like for some reason VS doesn't pick translations from these directories. On renaming the directories to zh-CN and zh-TW, and importing the new template in VS, the localized template description gets picked up.
We also found that [aspnetcore](https://github.com/dotnet/aspnetcore/tree/main/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/.template.config) repo uses zh-CN and zh-TW directory names only.

Hence we probably need to rename these directories to zh-CN and zh-TW in WinForms repo. Need to confirm with templating team.

**Note:** Same issue with CHS OS + VS with CHS language pack. Templates' description appears in ENU only.

**Comment by dreddy-work** [comment]
We have checked in localized strings. On renaming directories, VS will be making necessary changes there and we do not need any further changes.

**Comment by Ashley-Li** [comment]
Verified this issue with VS 17.0.2 31919.166 + OS CHS, it is fixed. Now Localized description for WinForms CHS templates. Please see below result:
![image](https://user-images.githubusercontent.com/56664234/143396752-65d29923-6cff-43f2-92ed-593443819a15.png)
![image](https://user-images.githubusercontent.com/56664234/143396771-367769c0-2377-4497-b9b6-429f21c94e76.png)
Verified this issue with test pass build: VS 17.0.2 31919.166 with CHS language pack, it is fixed. Please see below result:
![image](https://user-images.githubusercontent.com/56664234/143397045-6254d3a9-b048-40b1-a4a1-666feaf195a1.png)

**Comment by John-Qiao** [comment]
Verified this issue with VS 17.0.2 Preview 1.0 [31923.300.d17.0] + .NET 6.0.101-servicing.21569.4 build, it is fixed with the same above result.
