### ISSUE TITLE
When targeting to multiple SDKs, winforms project build failed with error: CSC : error CS8630: Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version '8.0' or greater.

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#6126]
* .NET Core Version: 
.NET SDK 6.0.100

* More info: 
1. When targeting to multiple SDKs with `net5.0-windows;net48`, this issue also repro.
2. When targeting to multiple SDKs with `netcoreapp3.1;net48`, this issue doesn't repro.

* Have you experienced this same bug with .NET Framework?: 
No

**Actual behavior:**
The WinForms project build failed with error: CSC : **error CS8630: Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version '8.0' or greater.**
![image](https://user-images.githubusercontent.com/62929087/140443897-b309081f-5755-43df-88e0-adb4eb0b121d.png)

**Expected behavior:**
The WinForms project could be built successfully

**Minimal repro:**
1. Create a WinForms .NET core project
2. Edit .csproj file and change the SDK in <TargetFramework> node 
    from
 `<TargetFramework>net6.0-windows</TargetFramework>`
    to 
 `<TargetFrameworks>net6.0-windows;net48</TargetFrameworks>`
3. Reload this project
4. Build this project

**Comment by Amy-Li03** [comment]
There is a similar issue: https://github.com/dotnet/templating/issues/3297

**Comment by dreddy-work** [comment]
@RussKie to follow-up on this.

**Comment by hdefucom** [comment]
You can specify the language version manually.

![image](https://user-images.githubusercontent.com/51500043/140843554-d0d75190-8c5b-45e6-85e0-a15e10df7571.png)

**Comment by hdefucom** [comment]
Because net6's project template will add `Nullable` by default.
The .Net framework uses c#7.3 by default.
So you can modify the language version or remove the Nullable configuration node

**Comment by Amy-Li03** [comment]
@hdefucom Thanks for your workaround, but it seems that it is not working for me.
After modify the language version and remove the Nullable configuration node, another error pops up once build this project.
![image](https://user-images.githubusercontent.com/62929087/140849063-255c4659-3239-480e-ad66-1ec95073b1f4.png)

**Comment by hdefucom** [comment]
This problem is caused by the different default reference namespaces of NetCore and NetFramework.
you can -->
![image](https://user-images.githubusercontent.com/51500043/140850010-4d0b9525-0b07-4dc7-bb12-ea3705f46127.png)

**Comment by hdefucom** [comment]
This is a change since NETCORE.

![image](https://user-images.githubusercontent.com/51500043/140850254-e133431d-c90d-418c-accd-c4a7af4b1d19.png)

**Comment by Amy-Li03** [comment]
Still build with error
![image](https://user-images.githubusercontent.com/62929087/140854190-b84b2fba-6566-4d8b-b39a-d3ea9f4116e2.png)

**Comment by hdefucom** [comment]
![image](https://user-images.githubusercontent.com/51500043/140854757-0a5a2503-7838-48b2-80c5-7a2767b72327.png)

😓

**Comment by Amy-Li03** [comment]
Thank you! It works for me.

**Comment by hdefucom** [comment]
One more thing, If you use c#10's global using ,`<ImplicitUsings>enable</ImplicitUsings>`  
SDK will automatically add some namespaces, 
but some are not available in the lower version of the framework, 
such as `system.net.http`,
Therefore, it is recommended to disable global using and configure it in your own code

**Comment by RussKie** [comment]
@Amy-Li03 please refer to https://docs.microsoft.com/dotnet/core/compatibility/sdk/6.0/csharp-template-code
