### ISSUE TITLE
HelpProvider

### ISSUE THREAD

**Issue by peterYong** [dotnet/winforms#6127]
I have encountered the following problem when using HelpProvider (.Net Framework 4.5):
When two chm files are associated, the first chm is opened first, then the second chm is opened, both are normal. At this time, the first chm is closed, and then the first chm is opened again, and the problem occurs: the title of the first chm becomes the title of the second chm, but the rest is normal.

**Comment by dreddy-work** [comment]
Can you add a sample and a gif of what you are observing here?

**Comment by peterYong** [comment]
> Can you add a sample and a gif of what you are observing here?

Hi, I uploaded HelpProviderDemo.zip, which includes a C# source code and a video in wmv format.
The operation steps are
1. Click First chm file
2、Click second chm file
3、Close User manuals
4、Click First chm file
As a result, the title bar of User manuals changed to Instruction Manual, why?

[HelpProviderDemo.zip](https://github.com/dotnet/winforms/files/7496596/HelpProviderDemo.zip)

**Comment by merriemcgaw** [comment]
Hi @peterYong, this repo is regarding the new open source version of WinForms, starting with .NET Core 3.0. It looks like your application is built on .NET Framework 4.5. .NET Framework is currently only taking high impacting servicing issues and security issues. Unfortunately, the HelpProvider control is not something that is in wide use anymore so I don't think that a servicing issue for it would be approved. Additionally, I have to say that it is highly unlikely that we would be migrating this control to .NET 7. As such, I'm going to have to close this issue.
