### ISSUE TITLE
When there are a certain number of controls in WinForm project, vs cannot load pdb file for breakpoint debugging.(.NetFramework4.0)

### ISSUE THREAD

**Issue by hdefucom** [dotnet/winforms#6139]
### Describe the bug

When there are a certain number of controls in WinForm project, 
vs cannot load pdb file for breakpoint debuggingm.   
I removed the controls one by one and found that there was a critical point beyond which the pdb file could not be loaded.
But it's not clear how much.   
I'm talking about the number of controls on the **form designer**, not the number of controls dynamically added when the program runs.

---------------------------------
I use **SDK style** project file development .NetFramework project.  
But I've tested old project files, and it seems that there will be this problem.   
I don't know if this is a vs problem or a. Net problem.   
But I also have this problem when I use vscodeu, so I prefer. Net.

**Comment by hdefucom** [comment]
### I found the general problem.

I rely on the nuget package of framework 4.0 for an old style project file.  
This problem occurs when there are too many controls in my project when using this package.  
However, if the package project is updated to the SDK style project file, it can be debugged normally when packaged.

**Comment by hdefucom** [comment]
#### My whole project uses. Netframework 4.0

The entire solution uses SDK style project files.

However, some libraries are installed using nuget.

The problem is with this nuget package.
The nuget package is generated using an older version of the project file.
When I use the SDK style project file to install this nuget package, 
and the number of project controls reaches two or three thousand, 
there will be a problem that I can't load symbols for breakpoint debugging.

If I upgrade the nuget package project to SDK style, this problem will not occur.

But I can't reproduce this problem when I create nuget packages using legacy project files.

**Comment by dreddy-work** [comment]
@hdefucom , this issue is not WinForms specific and Visual Studio feedback ticket would be right place to raise this and it will be redirected to right team. Once raise feedback ticket, please add link to this issue for future reference. //cc: @tmeschter and @drewnoakes .

**Comment by dreddy-work** [comment]
> @dreddy-work This is not a visualstudio problem. Because I also have this problem when testing on vscode. I'm sure it's an SDK problem.

I wasn't saying its Visual Studio problem but it will be redirected to right team if you raise feedback ticket via Visual Studio.
