### ISSUE TITLE
Windows 11 snap layout does not work correctly when initiated from a maximized window

### ISSUE THREAD

**Issue by lhak** [dotnet/winforms#6153]
When the Windows 11 snap layout functionality is invoked, the window is not resized correctly when it is started from a maximized state.

* .NET Core Version: 

.net core 3.1

* Have you experienced this same bug with .NET Framework?: 

**Problem description:**

**Expected behavior:**

The window should be sized correctly.

**Minimal repro:**

- Create a new winforms project
- Maximize the window
- Hover over the maximize button and select one of the snap modes

**Comment by egvijayanand** [comment]
Facing the same issue with target framework as `net6.0`.

Rather than snapping to the selected option, the window gets restored.

**Comment by dreddy-work** [comment]
We may have to do something like described here: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu

**Comment by lhak** [comment]
Workaround I have found:

Handle the WM_WINDOWPOSCHANGED message and reset the saved window coordinates:

```csharp
System.Reflection.FieldInfo restoredBoundsSpecified = typeof(Form).GetField("restoredWindowBoundsSpecified", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
restoredBoundsSpecified.SetValue(this, BoundsSpecified.None);
```

Not sure if there are any negative side effects, but so far it is working fine for me.

**Comment by jbhensley** [comment]
Based on this, any side effect is likely to be seen when programmatically setting location/size. 

https://github.com/dotnet/winforms/blob/e283294aefed00a944d0f8e0345859fdc2425a1c/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L4749-L4753

Seems like the fix is to not restore previous location/size when coming out of a maximized state due to Windows snap layout, but it might be more complicated than that.

**Comment by Philip-Wang01** [comment]
Verified this issue in .NET SDK 7.0.100-preview.4.22227.3 test pass build, it was fixed
![bujugeju](https://user-images.githubusercontent.com/86937911/165708692-c8b7093b-2a2f-4dee-8d43-3237d051ad42.gif)

**Comment by Cassie-Li01** [comment]
Verified this issue in .NET SDK 7.0.100-preview.5.22256.2 test pass build, it was fixed
