### ISSUE TITLE
bug: toolstripstatuslabel text

### ISSUE THREAD

**Issue by kirbypinkgamer** [dotnet/winforms#6160]
* .NET Core Version: 
.NET 6.0 (Visual Studio 2022)

* Have you experienced this same bug with .NET Framework?
No

**Problem description:**

When you create a toolstrip on a winform and add a toolstripstatuslabel with any Text property containing a '&' character in the string, the '&' character is not displayed. All rest of the string however is displayed but not the '&'.

**Expected behavior:**

The '&' character should be displayed as in .NET 4.8

**Minimal repro:**

1. Create a new winform 
2. Add a toolstrip to the winform
3. Add a toolstripstatuslabel to'the toolstrip
4. Assign any string with one or more '&' characters to the Text property of the toolstripstatuslabel
5. Compile and run
6. The '&' characters are not displayed, but all other characters of the string are displayed correctly

**Comment by RussKie** [comment]
This is a duplicated of https://github.com/dotnet/winforms/issues/4294.

The workaround that works on .NET Framework and .NET versions is noted here: https://github.com/dotnet/winforms/issues/4294#issuecomment-735510324

> To display the "test&" in toolStripStatusLabel item, we can use the following code line:
> 
> > `toolStripStatusLabel1.Text = "test&&";`
> 
> To display the "test&" in a standard Label control, we can using the following two ways:
> 
> > `label1.Text = "test&&";`
> 
> or
> 
> > `label1.UseMnemonic = false;`
> 
> > `label1.Text = "test&";`
