### ISSUE TITLE
The application crashes when trying to get data about the DropDownList in the PropertyGrid through the Inspect

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6165]
.NET Core Version: 
- 7.0.0-alpha.1.21558.10

Have you experienced this same bug with .NET Framework?: 
- No (regression from #5638)

**Repro steps:**

1. Create an app with a `PropertyGrid` and button.
2. Set `Button` as `SelectedObject` property of `PropertyGrid`.
3. Run the app.
4. Run the Inspect.
5. Set focus to `Accessible Role` dropdown list.

**Actual behavior:**
The Application crashes:
![Issue-6165](https://user-images.githubusercontent.com/23376742/141281075-9d567d01-06e6-470f-8987-a80368ad7b85.gif)

**Expected behavior:**
The application should not crash.

**Comment by WPMGPRoSToTeMa** [comment]
It is crashing because you're running application without debugger attached. Otherwise it will pause at `Debug.Fail` just like hitting a regular breakpoint. Also there will be no issue if you will run it compiled in release mode no matter with or without debugger attached since assertions aren't compiled in release mode.

**Comment by RussKie** [comment]
> It is crashing because you're running application without debugger attached. Otherwise it will pause at `Debug.Fail` just like hitting a regular breakpoint. Also there will be no issue if you will run it compiled in release mode no matter with or without debugger attached since assertions aren't compiled in release mode.

I don't agree with this view angle - an app must never crash in Debug or Release mode unless it is a developer-originated error that the developer can fix. And it is never ok to accept crashes in Debug because we don't in Release - by doing this we are ignoring the root cause.

**Comment by Ashley-Li** [comment]
Verified this issue with .NET 7.0.100-alpha.1.21568.2, it is fixed. The application does not crash when setting focus to Accessible Role dropdown list.
![6165-verify](https://user-images.githubusercontent.com/56664234/148363354-6a7aecf4-bdca-4e29-891e-31768efe6637.gif)
