### ISSUE TITLE
toolstripstatuslabel question

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#6169]
Hi

You just close this issue here https://github.com/dotnet/winforms/issues/6160
without any explanation.

What's the logic behind using "&&" in order to get "&" displayed on a toolstripstatuslabel ?
Why is this changed compared to .net 4.8?

**Comment by dreddy-work** [comment]
> Why is this changed compared to .net 4.8?

This has been the behavior even in .NET framework 4.8, how are you verifying this with Framework? can you share a sample and screenshots of it with .NET framework 4.8?

**Comment by kirbypinkgamer** [comment]
Hello

You only need to make a toolstripstatuslabel in .net 4.8 and .net 6.0, enter some text like "test&" and compare. You'll see only in .net 4.8 a single '&' is displayed while in .net 6.0 you need '&&' to display only a single '&'
I have no time to make screenshots of this trivial example...

**Comment by dreddy-work** [comment]
> Hello
> 
> You only need to make a toolstripstatuslabel in .net 4.8 and .net 6.0, enter some text like "test&" and compare. You'll see only in .net 4.8 a single '&' is displayed while in .net 6.0 you need '&&' to display only a single '&' I have no time to make screenshots of this trivial example...

We did try on our end [here](https://github.com/dotnet/winforms/issues/4294#issuecomment-736930614):  and we could not repro it hence, requested on how you were able to get it working in Framework 4.8.
