### ISSUE TITLE
For control Name use nameof instead of hardcoding

### ISSUE THREAD

**Issue by mottykohn** [dotnet/winforms#6176]
**Is your feature request related to a problem? Please describe.**

The generates code-behind for any given control looks like this
```
            // 
            // SelectAll
            // 
            this.SelectAll.Dock = System.Windows.Forms.DockStyle.Left;
            this.SelectAll.Location = new System.Drawing.Point(0, 0);
            this.SelectAll.Name = "SelectAll";
            this.SelectAll.Size = new System.Drawing.Size(147, 32);
            this.SelectAll.TabIndex = 1;
            this.SelectAll.Text = "Select All";
            this.SelectAll.UseVisualStyleBackColor = true;

```
The name is hard-coded. When renaming a control using f2 or ctrl-r-r you need to update the hard coded name.

**Describe the solution you'd like and alternatives you've considered**
Was wondering if it would be possible the generate code the looks like this
```
            this.SelectAll.Name = nameof(this.SelectAll);
```
I realize that this may not be that simple as I'm not sure how the designer works so maybe it won't pick up changes to such a construct. I'm also aware that editing the code behind is not directly supported, but the rename functionality exist in the part that we are allowed to edit.

**Will this feature affect UI controls?**
    Yes
    - VS Designer need to support the feature as mentioned above to accommodate picking up any changes
    - Will not impact accessibility
    - Will not need to be localized.

**Comment by RussKie** [comment]
It is currently not technically possible as the CodeDomSerializer isn't aware of the new Roslyn constructs. However we have work in the pipeline that may eventually address this limitation.

/cc: @DustinCampbell
