### ISSUE TITLE
We are not rounding corners in button borders on Win11

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#6187]
* .NET Version: 7.0 Preview1

**Problem description:**

https://github.com/dotnet/winforms/pull/6059 updated the colour of the `Button`'s borders, however it regressed the rendering on W11

Here's .NET 7.0 vs .NET 6.0
![image](https://user-images.githubusercontent.com/4403806/141871191-4bedd74e-88f9-4ff7-b693-8dac5afdb48e.png)
...magnified:
![image](https://user-images.githubusercontent.com/4403806/141883762-b6651b7f-369b-4857-bbcf-98ea7f974661.png)

**Expected behavior:**

The borders are rendered correctly

**Comment by RussKie** [comment]
@merriemcgaw please prioritise

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang  - could you please retest this on the newest windows11?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang - could you please retest this on the newest windows11?

This issue still repro on the newest Windows 11 version with .Net 7.0 installed: Button with FlatStyle: Standard and not focused.
![image](https://user-images.githubusercontent.com/26474449/145925077-ac9544aa-2fab-44f2-a45f-86d5cdf11987.png)
And it doesn't reproduce on .Net 6.0 after .Net 7.0 is uninstalled with same Windows 11 version
![image](https://user-images.githubusercontent.com/26474449/145925519-752b1bd3-9683-4e49-a509-d13ee3cfcab5.png)

**Comment by merriemcgaw** [comment]
Would it be the rectangles we're drawing when we're increasing the contrast of our buttons borders?

**Comment by dmitrii-drobotov** [comment]
I believe it was fixed by https://github.com/dotnet/winforms/pull/6522 and this issue can be closed. @Olina-Zhang could you please retest it on current versions?

**Comment by Olina-Zhang** [comment]
Verified this issue in the .Net 7.0 and .Net 8.0 SDK build, all are fixed as following screenshot. Close this issue now.
![image](https://user-images.githubusercontent.com/26474449/200716939-5b84ac93-fd26-493b-85c1-3cf7eaf1f4fc.png)
