### ISSUE TITLE
Application wide private fonts

### ISSUE THREAD

**Issue by ahdung** [dotnet/winforms#6189]
Consider this API:
```c#
Application.Fonts.Add(fontFileNameOrByteArrayOrStream);
```
like `PrivateFontCollection.AddFontFile`, but more useful, `PrivateFontCollection` not friendly for third-party components, no source code, it maybe load font from configuration file, use `FontConverter` convert from `string`, the finally is `new Font(string)`, but this way is not respect private fonts.

So we need a way to set applicationOrProcess-wide private fonts, and let all font contructors to respect it.

**Comment by RussKie** [comment]
Could you please elaborate more on your request - why is this necessary or useful. Also please provide a customer-facing example of how you expect this to be used.

**Comment by ahdung** [comment]
Sure. First of all thank you for your response.

I'm using a reporting component named [FastReport](https://www.fast-report.com/en/product/fast-report-net/), I made a report file `a.frx` by its designer, this file with follow contents:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Report>
  <ReportPage Name="Page1" PaperWidth="58" PaperHeight="100">
    <ReportTitleBand>
      <TextObject Font="NotInstalledFont, 16pt"/>
    </ReportTitleBand>
  </ReportPage>
</Report>
```
Note there is a `TextObject` with font property, `FastReport` engine read it and render this `TextObject` element, How read? use `FontConverter.ConvertFromString`, and `ConvertFromString` actually use `new Font(string)`.

Yes of cause, `FastReport` also provided programmatically way to set element's font, but this requires more coding, it makes things inelegant, and there are always have products that not provide programmatically way.

Times have changed, data size has become less important, people need more private things, dll is like this, fonts should also be.

**Comment by ahdung** [comment]
use case:
```c#
static void Main {
  Application.EnableVisualStyles();
  Application.SetCompatibleTextRenderingDefault(false);
  ...
  Application.Fonts.Add(xxx);
  // or Application.PrivateFonts.Add(xxx);
  // or Application.AddPrivateFont(xxx);
  // or AppDomain.CurrentDomain.blblblbl... for other project such WPF
  ...
  Application.Run(new Form1());
}
```

**Comment by merriemcgaw** [comment]
Hi @ahdung,

This seems to be a bit specific to the FastReports tool, and in that case it would be better done in that utility. If you have any scenarios that would benefit from it that are not specific to a particular tool, that will help us evaluate whether or not we want to take it into the full WinForms runtime where it exists for all customers.

**Comment by ahdung** [comment]
@merriemcgaw As I know, almost all document presentation solutions store font information in the doc, `html, rdl(your report), xaml(your thing)...`, this is not a difficult to imagine thing. Apps reads text literal and constructs the font, this process is often internal, developers can't control it, can't pass `PrivateFontCollection` or something. Basically I think `PrivateFontCollection` is a thing lacking a complete design, please rethink a more complete solution about private fonts.

**Comment by RussKie** [comment]
[`PrivateFontCollection`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Drawing.Common/src/System/Drawing/Text/PrivateFontCollection.cs) is owned by https://github.com/dotnet/runtime/, where does Windows Form come into the picture?

**Comment by ahdung** [comment]
@RussKie I'm not reporting a issue about `PrivateFontCollection`, I wish winform have a app-wide private fonts solution.

**Comment by merriemcgaw** [comment]
@ahdung I appreciate your suggestion and we will take it under advisement. At this point it does not alight with our current goals for .NET 7 and we haven't heard any more specific requests in this space from other customers, so I am going to close this issue. That said, if we have additional requests from more customers I am more than happy to reconsider that for a future release.

**Comment by ahdung** [comment]
@merriemcgaw It is really so said. This matter does not require a lot of work, just need a global `PraviteFontCollection`, and let the font constructors access it first. This is not a major or breaking change.

In addition, users will not express all their dissatisfaction, most time we tend to overcome. If we think according to the amount of user requests, we don't even need C, Punched tape is enough.
