### ISSUE TITLE
ApplicationConfiguration: bug with DPI scaling when ApplicationDefaultFont is set

### ISSUE THREAD

**Issue by deng0** [dotnet/winforms#6191]
* .NET Core Version: 
6.0.0

**Problem description:**
When ApplicationDefaultFont is set in the csproj, there is a problem with the autogenerated ApplicationConfiguration, namely that Application.SetDefaultFont is called before Application.SetHighDpiMode, which breaks DPI scaling.
When ApplicationConfiguration.Initialize() is not used and the commands are called in the correct order instead, DPI scaling is working correctly.

**Expected behavior:**
Normally I would expect that the order of the commands would be irrelevant, but it's probably easier to fix the order of the commands generated in the ApplicationConfiguration.

**Minimal repro:**
I've attached simple repro project. 
[DefaultFontDpiScalingBug.zip](https://github.com/dotnet/winforms/files/7548000/DefaultFontDpiScalingBug.zip)
When useApplicationConfiguration is set to true, DPI scaling is broken.
Simply set your Windows Scaling to 150% and start this project.
Only when useApplicationConfiguration is set to false, the form and the textbox are correctly scaled up.

**Comment by Jenna-Zheng** [comment]
Verified this issue with .NET SDK 7.0.100-alpha.1.22060.5, it is fixed that when useApplicationConfiguration is set to true or false, the form and the textbox are correctly scaled up.
![image](https://user-images.githubusercontent.com/64949616/148898421-31e9fd77-0dc9-4af7-bfe5-7236fad349bf.png)

**Comment by Lydia-Shi** [comment]
Verified this issue in .NET 6.0.102-servicing.22069.14 build, it is fixed with the same above result on .NET 7.0.

**Comment by VinoWang01** [comment]
Verified this issue with .NET SDK 7.0.100-preview.1.22109.10, it is fixed. The form and the textbox are correctly scaled up when useApplicationConfiguration is set to true or false, 
![image](https://user-images.githubusercontent.com/90816462/153328620-ddc0ac0d-a4d3-47ee-bc7a-3be9664a8180.png)
