### ISSUE TITLE
Fix in #6198 causes assigned fonts to be inadvertently disposed 

### ISSUE THREAD

**Issue by filipnavara** [dotnet/winforms#6201]
There's a new regression introduced in #6198 and described in comments [here](https://github.com/dotnet/winforms/issues/6173#issuecomment-972904545).

We assign a custom `Font` to a control that is propagated by the new code into `ScalableControlFont`:
https://github.com/dotnet/winforms/blob/29e805d6d3e60144a31dad96d848cdcfe454e4eb/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L11421

Once the form with the a control moves to a different display (with different assigned DPI) it receives `WmDpiChangedBeforeParent` and disposes the font assigned by the application:
https://github.com/dotnet/winforms/blob/29e805d6d3e60144a31dad96d848cdcfe454e4eb/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L12278-L12282

The application will crash at some later time when the font is accessed (eg. by setting it to another control, form).

**Comment by filipnavara** [comment]
Note that this was already fixed once in https://github.com/dotnet/winforms/commit/9b77d919753564d3a47799c59ca426686e7daf70#diff-07a0a87cedab0d76c974ce8b105912a1b986c87116c7ee0ac73d6d5d65e4b48a and reintroduced.

**Comment by dreddy-work** [comment]
Thanks @filipnavara reporting this. I am getting this corrected.  QQ: given that you are creating a new Form after moving to a new monitor with different DPI, reusing the old Font may not give the right size for the new monitor. What scenarios, where you still need unscaled Font?

**Comment by filipnavara** [comment]
We hit this in couple of different scenarios. Firstly, we have global cache of fonts derived from the system MessageBoxFont. We never dispose these fonts over the lifetime of the application (at least not unless the system fonts change).

These fonts are then assigned to some controls. When WinForms didn't have the concept of default font we assigned it to every Form. We also assign the derived versions (eg. semibold) to some UI elements like labels.

If any of the fonts get inadvertently disposed, like it happened here, then it will crash the application the next time we try to use it.
