### ISSUE TITLE
Remove CLSCompliant from all binaries in WinForms repo

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#621]
As per feedback received from @sharwell in the refout PR, we should remove usage of CLSCompliant attribute from all binaries in WinForms repo. This concept is now obsolete and is not required anymore. Its drawback is that it slows the build.

However in order to remove it from WinForms repo, it needs to be removed from WindowsFormsIntegration first in DotNet-Trusted.

**Comment by sharwell** [comment]
Depending on how strong the back compat policy is, this might not be an option. Downstream applications using Windows Forms might be similar to WindowsFormsIntegration in expecting types in this library to be CLS Compliant.

**Comment by merriemcgaw** [comment]
Per discussion with the team, for compat reasons we're not going to remove this at this time. We anticipate compat needs with apps that are expecting this attribute.
