### ISSUE TITLE
ComboBox control has incorrect highlighting of opened drop-down list in Inspect 

### ISSUE THREAD

**Issue by DmitryGorokhov** [dotnet/winforms#6210]
**.NET Core Version:** 

- 6.0.100

**Have you experienced this same bug with .NET Framework?:**

- Yes

**Minimal repro:**

1. Create an app with a ComboBox control.
2. Build the app and run it.
3. Run the Inspect.
4. Investigate drop-down list opening using Inspect.

**Actual behavior:**

Inspector highlights entire list when drop-down list is opened. So ComboBox control has incorrect highlighting of opened drop-down list in Inspect. Narrator has the correct behavior. Please see the behavior gif below.

![ComboBoxInspect](https://user-images.githubusercontent.com/58004471/142868495-a0158c06-e320-4145-9adb-108ff3a92285.gif)

**Expected behavior:**

 Inspector must highlight selected item in drop-down list. If the control has no selected item yet the Inspect must highlight top field of ComboBox. So the Inspect must have the same behavior as the Narrator has. Please see current behavior in Narrator gif below.

![ComboBoxNarrator](https://user-images.githubusercontent.com/58004471/142868529-3bd33770-9d64-447a-b78e-a3081e5e63ff.gif)

**Comment by dreddy-work** [comment]
@DmitryGorokhov , how is Accessibility Insights tool treat this? in either case, this doesn't seem to blocking accessibility users. If insights tool matches with narrator, we may just close this.

**Comment by DmitryGorokhov** [comment]
Accessibility Insights works incorrect too, same as the Inspect. Please see screens below. 
Actually, I agree that it doesn't block the accessibility for users apps because the Narrator works clean. But the difference in behavior looks strange and it can confuse other developers. The issue is also similar to the one that we have already resolved. So I think we should keep this one. 

![AI0](https://user-images.githubusercontent.com/58004471/143021985-27f58e73-1c1c-4088-9c94-c64384505e70.png)

![AI1](https://user-images.githubusercontent.com/58004471/143022013-4225db0a-2966-49a0-9edb-6dc183f1b5f9.png)

**Comment by DmitryGorokhov** [comment]
Seems it's known problem #4375 . So I am closing this duplicate
