### ISSUE TITLE
Make WinForm project more modular by separating resources and settings for each form

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/winforms#6216]
**Is your feature request related to a problem? Please describe.**

 The problem is difficult to copy form from one project to another. 
1) Potentially problems in resources (same name image files) and issues of merging settings files.

**Describe the solution you'd like and alternatives you've considered**

Suggestion,
Make WinForm project more modular. 
By Allowing separate resources and settings for each form. 
Benefit: More easily transfer functionality from one project to another.

**Comment by RussKie** [comment]
Please elaborate on what you have in mind, how you see it is used, and how it would benefit all Windows Forms developers.

**Comment by IrakliLomidze** [comment]
Sometimes I need to copy some functionality from one WinForm project to another.
Form is not a Form.cs and Form.designer.cs it keeps resources in the common resource repository in the project file.

So Idea is to have the ability to store form-related resources (strings, images) in  the .resx files and not in the project file.

**Comment by elachlan** [comment]
@IrakliLomidze This exists now, there are form level resx files. Is that what you are after?
