### ISSUE TITLE
The TextRenderer.MeasureText has different return between .Net FrameWork and .Net 6

### ISSUE THREAD

**Issue by Maspapa** [dotnet/winforms#6229]
* .NET Core Version:  
.Net6

* Have you experienced this same bug with .NET Framework?: 
NO

**Problem description:**
The TextRenderer.MeasureText has different return between .Net FrameWork and .Net 6
`The Code below return different between .Net6 and .NetFrameWork

            Font font2 = new Font("Segoe UI", 9);
            Font font = new Font("Arial", 20F, FontStyle.Italic | FontStyle.Bold, GraphicsUnit.Point, ((byte)(128)));
            Size size = TextRenderer.MeasureText("Item77777", font, new Size(int.MaxValue, int.MaxValue), TextFormatFlags.NoPadding | TextFormatFlags.NoPrefix | TextFormatFlags.SingleLine);

            MessageBox.Show(size.Width.ToString());
`

**Expected behavior:**
In FrameWork it return 141
In Net6 it return 129

**Comment by JeremyKuhne** [comment]
Sorry this took so long to get to. This is a side effect of fixing the `TextRenderer` to respect `TextFormatFlags.NoPadding`. On .NET Framework it would be ignored and `TextFormatFlags.GlyphOverhangPadding` would be applied. If you want to get the same behavior on both versions explicitly call out `TextFormatFlags.GlyphOverhangPadding`.
