### ISSUE TITLE
[Question]no authorization to open a file using zip?

### ISSUE THREAD

**Issue by mcguu** [dotnet/winforms#6241]
sorry I am a newbie and I do not know where to ask so I put it here.
I am using uwp
I want to open and read a zipped file using `ZipFile`

```
 FileOpenPicker picker = new FileOpenPicker
                  {
                      ViewMode = PickerViewMode.Thumbnail,
                      SuggestedStartLocation = PickerLocationId.DocumentsLibrary
                  };

                  StorageFile file = await picker.PickSingleFileAsync();

ZipArchive zipArchive = ZipFile.OpenRead(file.Path);
```
the `file` is not null and there is a exception that I do not have access to the file.

what should I do?

**Comment by ryank425** [comment]
Can you share what exceptions you are getting with the exception message and stack trace?

Also, can you try to see if you can open the file using FileStream with Read only access, and pass the stream to ZipFile? 

It would be exactly like the example code with some slight modification from MSDN using https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchiveentry.open?view=net-6.0#examples


```

using System;
using System.IO;
using System.IO.Compression;

namespace ConsoleApplication
{
    class Program
    {
        static void Main(string[] args)
        {
            using (FileStream zipToOpen = new FileStream(@"your path to zip file", FileMode.Open))
            {
                using (ZipArchive archive = new ZipArchive(zipToOpen, ZipArchiveMode.Read))
                {
                    ...
                }
            }
        }
    }
}
```
