### ISSUE TITLE
"DrawIcon" method will translate offset twice

### ISSUE THREAD

**Issue by TempeBrennan** [dotnet/winforms#6252]
* .NET Core Version: 6.0.100

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
If translate transform, DrawIcon paint position is wrong. I'm not sure is this a bug or not, netcore 3.1 is correct
```
using (var icon = new Icon("aa.ico"))
{
    e.Graphics.TranslateTransform(0, 10);
    e.Graphics.DrawRectangle(new Pen(Brushes.Black), 0, 0, 50, 50);
    e.Graphics.DrawIcon(icon, new Rectangle(0, 0, 50, 50));
}
```
**Current behavior:**

![image](https://user-images.githubusercontent.com/51563666/144179146-4e7ee736-22c5-4c9c-8040-c1915f99f759.png)

**Expected behavior:**

![image](https://user-images.githubusercontent.com/51563666/144179195-6637d299-da08-42f5-b721-4bd83f05d351.png)

**Minimal repro:**

[WinFormsApp6.zip](https://github.com/dotnet/winforms/files/7631213/WinFormsApp6.zip)

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you guys help figure out when this regressed? Was it in 5 or 6? And if we can narrow it down further, that would be awesome but not required.

**Comment by Olina-Zhang** [comment]
I ran the provided sample app with .Net 6.0 and 7.0, cannot repro, have same testing result:
![image](https://user-images.githubusercontent.com/26474449/155688679-9132e8e3-9373-4037-aa16-2715678cc979.png)

**Comment by Mandi-Man** [comment]
Verified this issue with 7.0.100-preview.7.22324.4 and 6.0.400-preview.22316.6 from main branch, it doesn't repro. So close this issue now.Please see below screenshots:
![image](https://user-images.githubusercontent.com/104553917/175887064-f8dd575b-8fe3-4fcf-9b61-9548f442fe22.png)
![image](https://user-images.githubusercontent.com/104553917/175886814-0a433752-be52-4473-a7d0-3184f98d24c9.png)
