### ISSUE TITLE
Custom cursors are getting shrank in dpi aware application on extended monitor with high resolution

### ISSUE THREAD

**Issue by AmalRajUmapathySelvam** [dotnet/winforms#6253]
* .NET Core Version: 
Not tested in .NET Core.

* Have you experienced this same bug with .NET Framework?: 
**Yes.**

**Problem description:**
When showing custom cursor, cursor is not shown properly in dpi aware applications when app is build on primary monitor with 175 dpi and extended to secondary monitor with 100 dpi in high resolution.

**Output screenshot with dpi aware:**
![dpiAware_true](https://user-images.githubusercontent.com/44425449/144192354-09ce2860-63ba-4026-9041-f448215513b6.png)

**Output screenshot without dpi aware:**
![dpiaware_false](https://user-images.githubusercontent.com/44425449/144192407-2ecd92ae-b7c5-45ab-bd47-30b962459001.png)

**Expected behavior:**
Custom cursor should be loaded properly.

**Primary screen details:**
DPI – 175%
Screen resolution – 1920*1080 (maximum)
Display Orientation - Landscape

**Secondary screen details :**
DPI – 100%
Screen resolution – 3840*2160 (maximum)
Display Orientation - Landscape

**Minimal repro:**

Sample - [WindowsFormsApp1 - Copy.zip](https://github.com/dotnet/winforms/files/7631711/WindowsFormsApp1.-.Copy.zip)
1) Run the attached sample.
2) Drag the application and extend to secondary monitor.
3) Hover on any button to show custom cursor.

**Comment by dreddy-work** [comment]
@AmalRajUmapathySelvam , attached sample seems not a standalone and it is referencing some control library as well. can you help update test application so that we can try on our end?
