### ISSUE TITLE
FormClosing.Cancel not working

### ISSUE THREAD

**Issue by michael-eddy** [dotnet/winforms#6255]
I used the `FormClosing` event block the form closing before the data has saved.
but it's not working after i set `e.Cancel = true`,it's still closed “automatic”...
so it's that a BUG or it's just???
![微信截图_20211122143023](https://user-images.githubusercontent.com/22364738/142811896-000f91e7-aaf1-4e28-852d-7d907b2d0637.png)
![微信截图_20211122143045](https://user-images.githubusercontent.com/22364738/142811928-e3fe1c23-2f3d-4f0a-8b8e-b959e01ed653.png)
![微信截图_20211122143108](https://user-images.githubusercontent.com/22364738/142811938-6b71664a-4e13-448a-981b-879058f7580c.png)

**Comment by RussKie** [comment]
Please provide a standalone simple repro.
