### ISSUE TITLE
Measure text with charset shiftjis has some change after upgrade to .net6.0

### ISSUE THREAD

**Issue by TempeBrennan** [dotnet/winforms#6295]
* .NET Core Version: 6.0.100

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
When I call "TextRenderer.MeasureText" method, I found result is changed between 3.1.

In framework and 3.1, there is a little bigger than actual paint.

I found in .net6, default charset result is correct now , but for shiftjis our result is smaller than before.

Is this by design?

```
 Font font = new Font("Arial", 20F, FontStyle.Italic | FontStyle.Bold, GraphicsUnit.Point, 1); // replace to 128 can reproduce
 Size size = TextRenderer.MeasureText("Item77777", font, new Size(int.MaxValue, int.MaxValue), TextFormatFlags.NoPadding);

 e.Graphics.DrawRectangle(Pens.Red, new Rectangle(new Point(10, 10), size));
 TextRenderer.DrawText(e.Graphics, "Item77777", font, new Rectangle(new Point(10, 10), size), Color.Black, TextFormatFlags.NoPadding);
```
![image](https://user-images.githubusercontent.com/51563666/144778655-e5fdf031-6a88-4e5a-aa7e-c5dab5b49469.png)

**Expected behavior:**

**Minimal repro:**
[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/7657602/WinFormsApp1.zip)

**Comment by kirsan31** [comment]
Same as https://github.com/dotnet/winforms/issues/6229?
Need some response...

**Comment by TempeBrennan** [comment]
Yes, just need help us confirm is this about no padding strategy? Thanks!
