### ISSUE TITLE
"ComboBox.SelectedItem" property throws an exception if the selected item was removed and Handle is not created

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6304]
.NET Core Version: 
- 7.0.0-alpha.1.21576.4

Have you experienced this same bug with .NET Framework?: 
- No (the issue is not reproduced only in .NET Core 3.0, because when setting the `SelectedItem` property, we forcibly create a `Handle`)

**Repro steps:**
1. Create `ComboBox` and add some `Items`.
2. Set the last `Item` as the `SelectedItem`.
3. Remove last `Item`
4. Try to get the `SelectedItem` property

**Actual behavior:**
User sees an `ArgumentOutOfRangeException`.
![image](https://user-images.githubusercontent.com/23376742/145021646-12781650-1d3a-46b9-8b50-0f0b01903854.png)

**Expected behavior:**
The user should not see the exception.

**Comment by jbhensley** [comment]
I submitted what I believe to be a fix for this.

There is a larger issue, which is that `ComboBox` does not raise `SelectedIndexChanged` or `SelectedValueChanged` in response to mutations in the underlying collection. For this fix, `SelectedIndex` gets set to -1 when the `SelectedItem` is removed from `Items`. In keeping with existing behavior, no events are raised. This matches what is observed in .NET Framework 4.8 and .NET 5.

**Comment by Ashley-Li** [comment]
Verified this issue on .NET SDK 7.0.100-alpha.1.22060.8, it was fixed, please see following video：
![6304_verify](https://user-images.githubusercontent.com/56664234/148906473-de72b762-5b8d-48af-87fc-b8a1df6f2a74.gif)
