### ISSUE TITLE
Epic - Improve WinForms startup performance for ARM64

### ISSUE THREAD

**Issue by OliaG** [dotnet/winforms#6320]
On Windows, .NET 7 Windows Forms startup is 1.1x faster than .NET Framework 4.8 on Arm64 and x64.

**Comment by elachlan** [comment]
@Olina-Zhang Does your team have access to an Arm64 machine? 

I think here we could use PerfView to log the startup performance and compare them.

Related: https://github.com/dotnet/runtime/issues/13339

**Comment by Olina-Zhang** [comment]
@elachlan we have Windows arm64 VMs for testing.
I tried to use PerfView to collect etl data for running winforms simple .Net framework 4.8.1 and .Net 8.0 exe on x64 and arm64 VMs, just getting etl data is successful on x64 VM. I am not sure how to see the startup time for exe, get them following when open Processes form collected etl file. Is that how it works? 
![image](https://github.com/dotnet/winforms/assets/26474449/632dea8a-57ca-4e54-92b2-9e733da95464)
How you get the data time about "Time to load assemblies" from https://github.com/dotnet/runtime/issues/13339#issuecomment-1160970799?

**Comment by elachlan** [comment]
Thanks @Olina-Zhang, in that issue there was a button that caused a control from an external assembly to be loaded. It was focusing more ahead of time scenarios, Ready2Run vs NGEN.

In this issue we can focus specifically at the time to start. Based on your tests, we are within a couple of milliseconds. Which I think is within margin of error.

@merriemcgaw would you say we can close this issue based on those results, or did we want to be measurably faster in showing first form?

**Comment by merriemcgaw** [comment]
I think we can close this.
