### ISSUE TITLE
Selected dropdown button in `PropertyGrid` entry has visual artifacts on Windows 11

### ISSUE THREAD

**Issue by ArtemTatarinov** [dotnet/winforms#6326]
* .NET Core Version:
3.0, 3.1, 5.0, 6.0, 7.0

* Have you experienced this same bug with .NET Framework?: 
Yes, at 4.7.2 and 4.8, but in a bit different manner (see the screenshot below)

**Problem description:**
When the drop down button is selected with the mouse cursor, there're some visual artifacts on this button:
![image](https://user-images.githubusercontent.com/87859299/145568114-c12b791c-63f6-43cd-9ca0-5bb52408a55b.png)

This button at .NET Framework 4.7.2/4.8 at Windows 11 also have some kinds of disruption:
![image](https://user-images.githubusercontent.com/87859299/145568339-13555736-7ca2-4225-b393-d134617572ce.png)

General `ComboBox` control and `ComboBox` in the `DataGridViewComboBoxColumn` look fine at Windows 11 though:
![image](https://user-images.githubusercontent.com/87859299/145567247-ff4053d4-131c-4c07-8e44-649d6fe515b9.png)
![image](https://user-images.githubusercontent.com/87859299/145567416-59fc8c7a-1f73-47a8-971e-5b415ad3a427.png)

**Expected behavior:**
The button should look the same way it looks at Windows 10:
![image](https://user-images.githubusercontent.com/87859299/145568713-dec53d71-1c85-41d5-b348-4846e69d82da.png)

**Minimal repro:**
- Build and run the project from the attached zip file at Windows 11
- Click on PropertyGrid entry named `Flag` to make the ComboBox button visible
- Point the mouse cursor at the DropDown opening button (with down arrow)
![button](https://user-images.githubusercontent.com/87859299/145570544-e9ec47ed-cd8f-431c-84d2-833f6d514c7b.gif)

[TestPgCore.zip](https://github.com/dotnet/winforms/files/7692500/TestPgCore.zip)

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang  - could you please try out Artem's app?

**Comment by merriemcgaw** [comment]
Is this related to Windows perhaps changing the dropdown button to be curved and the selection rectangle isn't taking that into consideration? We had another issue like that with our buttons recently.

**Comment by Tanya-Solyanik** [comment]
Rootcause and fix are probably the same as in  https://github.com/dotnet/winforms/pull/6194 but in different code path

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang - could you please try out Artem's app?

Verified several different Win11 OS versions with Dev17, the results are different. The latest OS version cannot repro this issue

- .Net Core app
Order OS versions can repro it:
![image](https://user-images.githubusercontent.com/26474449/145750193-9de2c3fe-96a7-444d-9abb-28f7d8485f83.png)
![image](https://user-images.githubusercontent.com/26474449/145750240-701421f8-ee51-4b33-b335-242993646710.png)
the latest OS version cannot repro:
![image](https://user-images.githubusercontent.com/26474449/145750315-6bac809c-efd2-44b3-b41d-877b57619e0d.png)

- .Net framework app
Order OS versions can repro it:
![image](https://user-images.githubusercontent.com/26474449/145750413-8e9f02ba-9bf9-4cb0-ab1e-11ea31663836.png)
![image](https://user-images.githubusercontent.com/26474449/145750534-961d43c7-7b09-46e9-8154-49dcddd5ace3.png)
the latest OS version cannot repro:
![image](https://user-images.githubusercontent.com/26474449/145750590-d4275dbd-815a-456c-b26d-f21201f0c923.png)

**Comment by Tanya-Solyanik** [comment]
Thank you, @Olina-Zhang ! this is great to see! 
I'm keeping this bug open for @merriemcgaw to take a look in case we want to document it somewhere.

**Comment by merriemcgaw** [comment]
I will be sure to document that our best experience is on the latest OS builds. But I'm so glad this was filed so we can refer back to it!

**Comment by ArtemTatarinov** [comment]
I've found some kind of a quick workaround for this issue, maybe it would be useful for someone or for a future possible investigation. The calling of the `base.OnPaint(pevent)` at the `OnPaint` method at the `DropDownButton` class should be modified like this:
```
if (!OsVersion.IsWindows11_OrGreater)
{
    base.OnPaint(pevent);
}
else
{
    pevent.Graphics.Clear(SystemColors.Control);
}
```
`else` block is needed because without it when the button is selected for the first time there are some other artifacts that remain (yet just clearing `Graphics` for Win11 version isn't fixing the issue).

![image](https://user-images.githubusercontent.com/87859299/145937477-d4e83829-535b-4c79-a61d-5cb76daa68d9.png)

**Comment by RussKie** [comment]
@ArtemTatarinov is this something you suggest we change in our codebase?

**Comment by ArtemTatarinov** [comment]
> @ArtemTatarinov is this something you suggest we change in our codebase?

No, that's just in case.
