### ISSUE TITLE
Some rewritten MAUI tests fails

### ISSUE THREAD

**Issue by Danil-Andrianov** [dotnet/winforms#6333]
* .NET Core Version: 
7.0.0-alpha.1.21576.4

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Some Integration tests occasionally fails.
![image](https://user-images.githubusercontent.com/74228865/145800747-29800083-d024-42d4-b6dc-64e42d29b553.png)

**Comment by RussKie** [comment]
What are the actual errors? The tests appear to pass on the build agents.

**Comment by Danil-Andrianov** [comment]
@RussKie There are random tests failing. I suspect it's because of form: now we have separate form for each test, so there is a mess with the coordinates, focuses etc.

**Comment by RussKie** [comment]
In the interest of transparency, we had an offline chat and determined that 
a) mnemonics related tests are dependent on the keyboard layout - i.e., the test must be run with the English keyboard layout, and
b) all UI integration must use the `InputSimulator`.
