### ISSUE TITLE
Setting `MainMenuStrip` at the MDI child form several times leads to multiplying `ControlBox` buttons

### ISSUE THREAD

**Issue by ArtemTatarinov** [dotnet/winforms#6339]
* .NET Core Version: 
7.0

* Have you experienced this same bug with .NET Framework?: 
Yes, at 4.8

**Problem description:**
If the `MainMenuStrip` property of the child MDI `Form` class is set to some `MenuStrip` instance, then set to null, and then is set again to the `MenuStrip` instance, then the `ControlBox` buttons (`System`, `Minimize`, `Restore`, `Close`) are cloned:

![mdiMultipleButtons](https://user-images.githubusercontent.com/87859299/145946963-0927f397-3db9-4500-a91c-cfb8f91e786a.gif)

The handler for this checkbox does the following:

![image](https://user-images.githubusercontent.com/87859299/145947627-e5e40594-36bd-42cf-97db-04dfb4e55c0e.png)

**Expected behavior:**
The set of the `ControlBox` buttons should always be single per window.

**Minimal repro:**

1. Run the internal `WinformsControlsTest` test app
2. Click the `MDI Parent` button
3. Check and uncheck the `Set parent menustrip` checkbox several times.

**Comment by RussKie** [comment]
I'm having a deja-vu.... https://github.com/dotnet/winforms/issues/3029#issuecomment-749295542. However this was only an issue in .NET Framework, and it didn't repro in .NET Core 3.1 or .NET 5.0.
Please check when this was regressed.

**Comment by ArtemTatarinov** [comment]
I've reproduced it at the latest build of the 5.0 and 6.0 branches:
![image](https://user-images.githubusercontent.com/87859299/146228225-ee32e6f6-68e8-4a93-8d4b-a087a8b8ea92.png)
![image](https://user-images.githubusercontent.com/87859299/146230736-b4c69ccd-6181-41a4-b384-1a06af38edae.png)

In 3.1 checking/unchecking the `Set parent menu strip` ComboBox isn't affecting the main menu strip at all (it doesn't toggle its visibility), but at least the buttons aren't cloned.

I'll continue investigating.

**Comment by Amy-Li03** [comment]
Verified this issue on .NET SDK 7.0.100-alpha.1.22060.5, issue was fixed, please see following video:
![Fixed](https://user-images.githubusercontent.com/62929087/148873018-c5c6022e-65e0-4771-b962-24f0f74c8197.gif)
