### ISSUE TITLE
ElementHost class causes black areas when maximized

### ISSUE THREAD

**Issue by roland5572** [dotnet/winforms#6349]
If use class **System.Windows.Forms.Integration.ElementHost** in Winforms, and then maximize the interface, it will cause a large area of black on the interface background.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.integration.elementhost

Test Code:
.net 6.0

```
using System.Windows.Forms.Integration;

namespace FormBorderTest
{
    internal static class Program
    {
        [STAThread]
        static void Main()
        {
            ApplicationConfiguration.Initialize();

            var form = new Form()
            {
                Width = 600,
                Height = 400,

                StartPosition = FormStartPosition.CenterScreen,
            };

            var host = new ElementHost()
            {
                Dock= DockStyle.Fill,
            };

            form.Controls.Add(host);

            Application.Run(form);
        }
    }
}
```
Test Steps:

Step 1: Double-click the title bar to start maximizing.

![000](https://user-images.githubusercontent.com/88176616/146145942-43043673-8a47-44b6-8dce-04614b0892f1.png)

Step 2: In the process of maximization, a large black area appeared on the entire interface.

![002](https://user-images.githubusercontent.com/88176616/146144681-15da8498-db0b-4766-afbe-5937ad11daf1.png)

Step 3: After being maximized, the interface returns to normal.

![003](https://user-images.githubusercontent.com/88176616/146144689-6cc35132-1d75-47c7-8893-0d6773ee621b.png)

**Comment by Lydia-Shi** [comment]
Verified this issue with latest .NET 7.0.100-alpha.1.21568.2 and .NET 6.0.200-preview.21573.3, this issue cannot repro.
**Reproduce steps:**
1. Create a Winforms .NET Core application
2. Add WindowsFormsIntegration.dll(Under C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.0) reference to this project
3. Add above code in Program.cs
4. Build and run this project

**Results:**
After Double-clicking on the title bar, Form is maximized and no black area appear.
![ElementHostNotRepro](https://user-images.githubusercontent.com/54019172/146297670-c8f3b663-08c2-45aa-9119-f0619c518373.gif)

**Comment by roland5572** [comment]
@Lydia-Shi , You can see my screenshot, I captured your video first, and then used the video player that comes with Windows to view it **frame by frame**, and then I found out.

It does appear on a black background.

![001](https://user-images.githubusercontent.com/88176616/146304647-274e560d-a723-45cc-97f4-ad44c844870e.png)

The **timestamp** on the screenshot may be inaccurate, because I used the screenshot software to convert it to a video, and because I don’t have your video file, I can’t open it directly.

I wonder why it appears so short on your computer. I think it may be due to the following reasons.

1. The computer hardware you are using is good, and the speed is inherently fast.
2. This is a test sample, it does not carry any business logic, nor does it have any complex controls. Once you store a lot of controls, the effect will become obvious.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you confirm whether this is still a problem?

**Comment by Olina-Zhang** [comment]
@merriemcgaw It seems this issue is reproduced, I checked the records by frames, and during maximized form, there has black background in one frame.
previous frame:
![image](https://user-images.githubusercontent.com/26474449/184117175-4f9be765-e1de-44b6-a342-d3e2fe28702a.png)
next frame:
![image](https://user-images.githubusercontent.com/26474449/184117296-4a0226d7-301a-4c06-bf1c-fceef510b8a3.png)

**Comment by merriemcgaw** [comment]
Huh, so we're looking at a very brief flash that self-corrects. I think we should close this issue, but feel free to reopen if it becomes something that is seriously impacting your applications.
