### ISSUE TITLE
Intellisense Support

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#635]
* [ ] Add Intellisense to transport package
* [ ] Ensure EN Intellisense is checked in
* [ ] Create process to update EN Intellisense

**Comment by vivmishra** [comment]
Can we re-purpose this same issue for reference assemblies too or you want to have a different issue for that?

**Comment by zsd4yr** [comment]
> Can we re-purpose this same issue for reference assemblies too or you want to have a different issue for that?

reference assemblies should already be in the package:

![image](https://user-images.githubusercontent.com/10677481/55113506-aed7a880-509c-11e9-8df3-feaa90cb3a4d.png)

**Comment by merriemcgaw** [comment]
This is likely to need to be added to a transport package to core-setup.

**Comment by merriemcgaw** [comment]
@mairaw let me know when the Intellisense zip file is ready to go.

**Comment by merriemcgaw** [comment]
Looks like EN Intellisense is working.
