### ISSUE TITLE
An exception appears when the user press the left / right arrow in the ListView without ListViewGroup

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6353]
.NET Core Version: 
 - NET Core SDK: 7.0.0-alpha.1.21606.7

Have you experienced this same bug with .NET Framework?: 
- Yes (from #5960)

**Problem description:**

1. Create a `Form` with a `ListView`.
2. Add an `ListViewItem` to the `ListView`.
3. Run the app.
4. Press the left / right arrow.

**Actual behavior:**
User sees an exception.
![Issue-6353](https://user-images.githubusercontent.com/23376742/146353359-81c3ec2f-5d81-4066-82e6-1cdc8e918861.gif)

**Expected behavior:**
User should not see exception.

**Comment by VinoWang01** [comment]
Verified with latest built 7.0 binaries, this issue was fixed.

**Comment by VinoWang01** [comment]
Verified with SDK 7.0.100-alpha.1.22060.5 build by executing the steps in 'Problem description', no exception pops up when pressing Left / Right keyboard.
