### ISSUE TITLE
Windows 11  breaking Development compatibility

### ISSUE THREAD

**Issue by memoarfaa** [dotnet/winforms#6364]
* .NET Core Version: 

* Have you experienced this same bug with .NET Framework?:  Yes 

**Problem description:**

1.  MDIParent Window  that have Custom WM_NCPAINT Windows Message or  its  DWMNCRENDERINGPOLICY set to DWMNCRP_DISABLED will add then new  Snap layouts in maximize button to Mdi Child Window (how  a Child Window can layout all Desktop Windows and layout its parent in Desktop  );

![2021-12-18_14-47-33](https://user-images.githubusercontent.com/12494184/146642641-b4c32095-58ea-411a-aefe-7a6b0d98dbe7.png)

2.  DwmExtendFrameIntoClientArea  Wrong MARGINS 

DwmExtendFrameIntoClientArea will Extend  Frame to both Client and Non Client area

```
[DllImport("dwmapi.dll")]
public static extern int DwmExtendFrameIntoClientArea(IntPtr hWnd, ref MARGINS pMarInset);

   [StructLayout(LayoutKind.Sequential)]
        public struct MARGINS
        {
            internal int cxLeftWidth;

            internal int cxRightWidth;

            internal int cyTopHeight;

            internal int cyBottomHeight;

         
            public MARGINS(int cxLeftWidth, int cxRightWidth, int cyTopHeight, int cyBottomHeight) : this()
            {
                this.cxLeftWidth = cxRightWidth;
                this.cxRightWidth = cxRightWidth;
                this.cyTopHeight = cyTopHeight;
                this.cyBottomHeight = cyBottomHeight;
            }

           
        }
          MARGINS m = new MARGINS(8, 8, 31, 8);
            DwmExtendFrameIntoClientArea(Handle,ref m); 
```

windows 11 
![2021-12-18_15-39-35](https://user-images.githubusercontent.com/12494184/146643316-81785e0b-c31a-45eb-bd66-f7e1a6bb6a2c.png)
Windows 10 and lower
![2021-12-18_15-59-28](https://user-images.githubusercontent.com/12494184/146643657-1c554194-9343-4c68-8a3b-6fe46f383221.png)

**Expected behavior:**

**Minimal repro:**

**Comment by merriemcgaw** [comment]
We're unlikely to have any control over this particular scenario. These were changes directly to the Win32 API set. I'd be interested to know if this happens in an MFC app, and if so we should certainly file a feedback issue on the Windows team

**Comment by merriemcgaw** [comment]
@Olina-Zhang if your team can test the MFC scenario that would be super helpful!

**Comment by John-Qiao** [comment]
@memoarfaa could you please provide your sample project here?

**Comment by dreddy-work** [comment]
@John-Qiao , it seems Windows fixed this issue in the latest builds. Can you try this issue again with latest windows 11 build?

**Comment by John-Qiao** [comment]
@dreddy-work I tested it in my Win11 21H2 OS, and the issue1 is not reproduced in my result, please check below gif:
![TestResult-6364](https://user-images.githubusercontent.com/45864985/157792070-07db9993-a512-4301-abb8-fc2eb5b6c831.gif)

**Comment by dreddy-work** [comment]
Thanks @John-Qiao  for confirming.  Closing as this is fixed in latest windows version.
