### ISSUE TITLE
System.Resources.MissingManifestResourceException occurs on restore resources from .resx

### ISSUE THREAD

**Issue by mikhailovalex** [dotnet/winforms#638]
* .NET Core Version: 3.0.100-preview4-010391
* Have you experienced this same bug with .NET Framework?: No

**It is impossible to read an object from resources when the form or user control has a non default namespace**

Actual behavior:
System.Resources.MissingManifestResourceException: 'Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "DifferentNamespace.Form1.resources" was correctly embedded or linked into assembly "NetCore_Resources" at compile time, or that all the satellite assemblies required are loadable and fully signed.'

Expected behavior:
NetCore project should read an object from resources

Minimal repro:
Run the attached example - NetCore_Resources.NetCore.sln
[NetCore_Resources.zip](https://github.com/dotnet/winforms/files/3011919/NetCore_Resources.zip)

**Comment by Lohnegrim** [comment]
Hi,
I encountered the same problem with my .Core 3 tests, this doesn't only happen, when there is a Namespace, it also happens, when the Classname of the Form is different from the Filename.
In Order to workaround this issue, you currently have to add the following to your NetCore_Resources.NetCore.csproj file:
`    <EmbeddedResource Update="Form1.resx">
      <DependentUpon>Form1.cs</DependentUpon>
    </EmbeddedResource>`

**Comment by merriemcgaw** [comment]
@dreddy-work can you take a look at this as part of the larger RESX work?

**Comment by dreddy-work** [comment]
@mikhailovalex do you see a different behavior on .NET 4.8 for this scenario?

**Comment by mikhailovalex** [comment]
@dreddy-work 
Sure. You can open a project in an attached example NetCore_Resources.sln. It's built and starts without any exception. Otherwise "NetCore_Resources.NetCore.sln" solution shows me this exception :
![image](https://user-images.githubusercontent.com/45847465/56341472-e0d0bc00-61bd-11e9-9858-ca368c19fc04.png)

**Comment by 199621616** [comment]
我遇到了同样的问题。
将.Net4.6.1完全正常运行的项目包含文件复制到.NetCore的WinForm项目中，编译正常通过，但是运行有异常：
Void HandleResourceStreamMissing(System.String)^Message:Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "医保接口工作站_新疆.Form医保接口工作站_新疆.resources" was correctly embedded or linked into assembly "医保接口工作站_新疆" at compile time, or that all the satellite assemblies required are loadable and fully signed.^Source:System.Private.CoreLib^StackTrace:   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)

**Comment by 199621616** [comment]
这是我们迁移桌面程序中遇到的最大障碍。
似乎它与Core3以前版本中资源文件只支持字符、不支持二进制资源有关。希望尽快解决，它阻断了我们向Core3迁移桌面程序。

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you check this scenario now?

**Comment by 199621616** [comment]
3.0.0-Prevew7还不能解决这个问题嘛？希望在3.0.0-Prevew7中能解决，不要再改性到3.0.0-Prevew8

**Comment by RussKie** [comment]
Please write your comments in English

**Comment by dreddy-work** [comment]
@rainersigwald , I am thinking this is one of the scenario that might have been solved by your changes. Can you help me point to the build that i can verify against?

**Comment by dreddy-work** [comment]
@ericstj  and @rainersigwald , it seems Resourcemanager is embedding resources under project name instead of Namespace name.  This was workign when applicatiosn continue with defautl namespace but throw an exception when they do not opt into default name space. FOllowign are the embedded resources from Netcore and classic framework applications with exact same source code. 

![image](https://user-images.githubusercontent.com/36968667/60474777-f1bf9400-9c28-11e9-8766-774fbb0cff60.png)

**Comment by ericstj** [comment]
@nguerrera @dsplaisted

**Comment by nguerrera** [comment]
I believe this will be the issue of DependentUpon not being set and is a duplicate. Will follow up with further details.

**Comment by nguerrera** [comment]
We had talked about having some way to tell msbuild to fall back to a file naming convention when there is no DependentUpon. @davkean I think you were going to propose something? Is there an msbuild issue yet?

**Comment by nguerrera** [comment]
https://github.com/dotnet/winforms/issues/638#issuecomment-477053971

Is the workaround. Without DependentUpon msbuild can’t figure out the namespace and class used in the actual file and will use the file name and RootNamespace (which is defaulted to the project name).

If we add support for convention, we need to put it behind a flag or we will break existing projects. We can then opt in to the flag by default for netcoreapp3.

If there isn’t already an msbuild issue, I will move this one

**Comment by dreddy-work** [comment]
I am not sure if there is already an issue in msbuild repo. Feel free to move this.

**Comment by nguerrera** [comment]
I was asking @davkean if there was an issue because I think he was going to file a proposal.

**Comment by davkean** [comment]
There's an issue here, https://github.com/dotnet/project-system/issues/4807, but I've run out of time to figure out/file a proposal. If MSBuild/SDK could pick this up, that would be great.

**Comment by dreddy-work** [comment]
Now that we are tracking the issue in msbuild repo, closing this issue here.
