### ISSUE TITLE
Setting ShowInTaskbar to false causes the form to close automatically (Abnormal exit).

### ISSUE THREAD

**Issue by roland5572** [dotnet/winforms#6421]
Setting ShowInTaskbar to false causes the form to close automatically (**Abnormal exit**).

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form

Test Code:
.NET 6.0 (Version: 6.0.1)(This problem also appears in .net framework 4.8)
Win10 system (21H2).

```
using System;
using System.Windows.Forms;

namespace FormShowInTaskbarTest
{
    internal static class Program
    {
        private static Form form1;
        private static Form form2;

        [STAThread]
        static void Main()
        {
            ApplicationConfiguration.Initialize();

            form1 = new Form()
            {
                Width = 800,
                Height = 600,
                StartPosition = FormStartPosition.CenterScreen,
            };

            var button1 = new Button()
            {
                Text = "Click here to open new Form.",

                Width = 200,
                Height = 100,
            };

            button1.Click += Button1_Click;
            form1.Controls.Add(button1);

            Application.Run(form1);
        }

        private static void Button1_Click(object sender, EventArgs e)
        {
            form2 = new Form()
            {
                Width = 600,
                Height = 400,

                StartPosition = FormStartPosition.CenterScreen,
            };

            var button2 = new Button()
            {
                Text = "Click here to test ShowInTaskbar.",

                Width = 200,
                Height = 100,
            };

            button2.Click += Button2_Click;
            form2.Controls.Add(button2);

            form2.ShowDialog(form1);
        }

        private static void Button2_Click(object sender, EventArgs e)
        {
            form2.ShowInTaskbar = false;
        }
    }
}
```

Steps to reproduce:
1. Run the appliction.
2. Click the first button, the application will open a new Form.
3. Click the first button in new form.

**Comment by AraHaan** [comment]
This is odd because in my program it works just fine (even when using 7.0.0-dev runtime) 🤔.

**Comment by roland5572** [comment]
> This is odd because in my program it works just fine (even when using 7.0.0-dev runtime) 🤔 (And I change it in a Timer when the application's own settings change from displaying the icon in taskbar to tray or to both).

Did you use Win7 or Win11? I am running on Win10 system (21H2).

**Comment by AraHaan** [comment]
I use Windows 11 on my old computer (that had 11 since it was in preview), and my newer one and it seems to work fine.

**Comment by roland5572** [comment]
> I use Windows 11 on my old computer (that had 11 since it was in preview), and my newer one and it seems to work fine with 6.0.0, 6.0.1, and 7.0.0-dev.

I just used Win11 for testing. I used the test code above. Found the same problem. I am not sure if this problem can be avoided by other codes in your program.

**Comment by fahadabdulaziz** [comment]
I can confirm this problem using Win10 21H2, on .NET 6.0.1 but not Win10 21H2 .NET 6.0.0.
Maybe #6115 is related.

**Comment by AraHaan** [comment]
Odd I now run into this issue now with manually built runtime running at the tip of branch main.

**Comment by AraHaan** [comment]
I think it *could* be that I hide the form the first thing right on the load event on my forms program causing it to terminate ironically right after it loads TerraFX.Interop.Windows 😄.

**Comment by John-Qiao** [comment]
Add test app here: [TestApp6421.zip](https://github.com/dotnet/winforms/files/7826817/TestApp6421.zip)

**Comment by AraHaan** [comment]
I will be testing the changes in #6477 to ensure my program now properly runs the way it was before I installed the 6.0.1 servicing.

**Comment by RussKie** [comment]
I have run the provided sample on Win11 (10.0.22000 Build 22000), and confirmed the behaviour is consistent as far as .NET Framework 4.7.2 and all the way up to .NET 7 Preview1.

@Olina-Zhang would you be able to test [6421.zip](https://github.com/dotnet/winforms/files/7885930/6421.zip) on different versions of Windows 10 and see if there are any differences in behaviours? Thank you.

**Comment by John-Qiao** [comment]
@RussKie we have tested the sample project on 9 different Win10 OSs(20H2, 20H1, 19H1, 19H2, RS5, RS4, RS3, RS2, RS1), they are all the same result when target to .NET 7.0 or .NET 6.0 or .NET Framework 4.7.2 or .NET Framework 4.8.

**Comment by AraHaan** [comment]
What is the result with running it in 8, 8.1 and 7?

**Comment by John-Qiao** [comment]
@AraHaan It's the same result in 8.1 and 7 with .NET 7.0.

**Comment by roland5572** [comment]
@John-Qiao Do you mean the test result is OK, or it's Failed? I just re-tested on my computer. It does not work with .net 6.0. If you need, I can provide the version number of the operating system and the video to you.

**Comment by John-Qiao** [comment]
@roland5572 I mean the issue is still reproduced in that environments: click the button in new form will close the new form automatically.

**Comment by AraHaan** [comment]
Hmm I wonder if it's due to the implementation of the property itself, if only I could add the Windows Forms code as a local project reference just so I can set breakpoints on it in my code to know for sure if that property is what causes my program to randomly terminate.

**Comment by RussKie** [comment]
> if only I could add the Windows Forms code as a local project reference just so I can set breakpoints on it in my code to know for sure if that property is what causes my program to randomly terminate.

Try this https://github.com/dotnet/winforms/blob/main/docs/debugging.md.

**Comment by AraHaan** [comment]
> > if only I could add the Windows Forms code as a local project reference just so I can set breakpoints on it in my code to know for sure if that property is what causes my program to randomly terminate.
> 
> Try this https://github.com/dotnet/winforms/blob/main/docs/debugging.md.

Too bad we cant debug using the source downloaded from sourcelink to set breakpoints so we can debug the actual binaries that get installed from the stable builds of the sdk.

**Comment by RussKie** [comment]
You should be able to with the help of function breakpoints
https://docs.microsoft.com/visualstudio/debugger/using-breakpoints#BKMK_Set_a_breakpoint_in_a_source_file
________________________________

**Comment by roland5572** [comment]
@AraHaan 

You can debug .net WinForms.

1. Download the source code from https://github.com/dotnet/winforms
2. Since the master branch is always improving, if you cannot compile the source code, you may need to download a stable branch (eg. v7.0.0-preview.3.22176.3 or new in the feature).
3. unzip the source code to a folder.
4. run build.cmd
5. run start-vs.cmd file from your folder (You need to call this file every time you open Visual Studio. Otherwise you won't be able to debug .net).
6, In this solution, you can add your own Forms to WinformsControlsTest project, if you cannot find it, just search it.
7. Run WinformsControlsTest project.

**Comment by AraHaan** [comment]
If I am doing all of that work, why not publish the projects that allow one to do the same type of integration tests that this repo uses so they can test their own code too? 😄

**Comment by roland5572** [comment]
@AraHaan Maybe the integration tests are not in the current roadmap. A smarter version may be introduced in the future.

**Comment by RussKie** [comment]
> If I am doing all of that work, why not publish the projects that allow one to do the same type of integration tests that this repo uses so they can test their own code too? 😄

If you have any proposals, you'd like to discuss, or have any questions - please start a [new discussion thread](https://github.com/dotnet/winforms/discussions/new).

**Comment by Ashley-Li** [comment]
Verified this issue on .NET 7.0.100-preview.4.22227.3, issue was fixed, click the button in new form will not close the new form automatically. [TestApp4621.zip](https://github.com/dotnet/winforms/files/8580375/TestApp4621.zip)
![verify_6421](https://user-images.githubusercontent.com/56664234/165695632-5cdf9801-f14c-463c-9948-dc22dde35f19.gif)

**Comment by AraHaan** [comment]
> Verified this issue on .NET 7.0.100-preview.4.22227.3, issue was fixed, click the button in new form will not close the new form automatically. [TestApp4621.zip](https://github.com/dotnet/winforms/files/8580375/TestApp4621.zip) ![verify_6421](https://user-images.githubusercontent.com/56664234/165695632-5cdf9801-f14c-463c-9948-dc22dde35f19.gif)

you mean preview.5.22227.3?

**Comment by Ashley-Li** [comment]
@AraHaan Yesterday, I installed  **Release/7.0.1xx-preview4(7.0.x Runtime)** from  https://github.com/dotnet/installer and test this.

**Comment by AraHaan** [comment]
I see, I been actually looking for the link to download only the daily quality Windows Desktop and ASP.NET Runtimes as it seems that the sdk installer seems to always not install the exact matching version suffix builds.

**Comment by RussKie** [comment]
@AraHaan I don't think there's a way of doing this (outside the team).

@kant2002  has created a service that can help determining what versions the installer has, you can find it here: https://kant2002.github.io/dotnet-installer-viewer/.
E.g.,
![image](https://user-images.githubusercontent.com/4403806/166200047-b8e4cb12-1cad-4f51-a1c5-a52994227ac3.png)

**Comment by AraHaan** [comment]
Wait why is System.Private.Winforms preview 4 still?
