### ISSUE TITLE
Controls are scaled multiple times in PerMonitorV2 HDPI mode

### ISSUE THREAD

**Issue by tbambuch** [dotnet/winforms#6439]
* .NET Core Version: 
6.0

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

ContainerControls with Visible = false are scaled multiple times in the PerMonitorV2 mode if moved to the another screen and then made visible

**Expected behavior:**
scaling (Size, Location, Margins, Paddings) should be made only once

**Minimal repro:**
Sample project attached. My screen setup is 100% primary screen and 150% secondary screen.
The project consists of a single Form with AutoScaleMode = Dpi and a UserControl with AutoScaleMode = Inherit
Application.SetHighDpiMode is called in Program.cs
There are 2 equal controls placed on the form, one has Visible set to false. There is a button which makes the control visible.
If you start on the primary (100%) screen, make the control visible and then move the form on a second screen, everything looks fine (the upper form on the screenshot)
If you first move the form on the second screen and then make the control visible, it gets scaled twice, resulting in wrong Location, Size and Padding (the bottom form on the screenshot)

![image](https://user-images.githubusercontent.com/3384955/147668490-0c3978cf-1793-4acc-8199-235f6b8134a0.png)

[DpiTest.zip](https://github.com/dotnet/winforms/files/7789107/DpiTest.zip)

**Comment by filipnavara** [comment]
FWIW this is working correctly on .NET 7 nighlies.

**Comment by filipnavara** [comment]
This particular bug seems to have been resolved by https://github.com/dotnet/winforms/commit/9b77d919753564d3a47799c59ca426686e7daf70 with the change in ContainerControl.cs. However, we have seen similar errors even with backport of this fix so we are looking into producing new repos.

**Comment by MelonWang1** [comment]
Verified this issue in the latest .Net 7.0 build: 7.0.100-preview.6.22316.8, it doesn't repro. So close this issue now. See below screenshot.
![6439](https://user-images.githubusercontent.com/94418985/174766125-438d1ad2-4031-457d-9a99-463113572e01.gif)
