### ISSUE TITLE
Catastrophic regression introduced in .NET 6.0.1 WinForms, completely broke Paint.NET v4.3.6

### ISSUE THREAD

**Issue by rickbrew** [dotnet/winforms#6464]
* .NET Core Version: 6.0.1

**Problem description:**
Yesterday I rolled out a new update for Paint.NET, version 4.3.5. After quickly pushing out a hotfix (v4.3.6) for something that _I_ broke in the code, I then received numerous reports of another catastrophic breaking issue that rendered the app completely broken. 

After many hours it was finally determined that the culprit was having a certain app setting disabled (the default is enabled): "Translucent windows".
![image](https://user-images.githubusercontent.com/10873410/148103394-a6757fac-930a-4ee5-ab33-24f3b6f0c2ca.png)

I'm pretty sure this was caused by a bug (or bug "fix" ?) introduced in .NET 6.0.1, as it doesn't happen in the previous version of my app (v4.3.4) on .NET 6.0, I had very few changes in the new version, and the workaround I found suggests a change in behavior surrounding `Handle`, `IsHandleCreated`, `OnHandleCreated()`, `OnHandleDestroyed()`. I've since published a new update with that workaround fix applied and everything works fine.

There's a big discussion on my forum that details the issue, the pleas for help and rollbacks, the troubleshooting, the discovery of a workaround in the app, and subsequently a test build that saved the day: https://forums.getpaint.net/topic/119185-many-problems-with-436/

Here are some highlights:

- Dialogs always opening at the top-left of the screen, instead of centered or literally anywhere they're supposed to be

- Truncated window size. This dialog should be 3-4x taller 
<img width="265" alt="image" src="https://user-images.githubusercontent.com/10873410/148103524-15fb1d64-429e-4b6d-b7aa-58600e48b0b2.png">

- Progress dialogs that never complete and can't be closed, resulting in a soft hang that requires Task Manager -> End Process
<img width="233" alt="image" src="https://user-images.githubusercontent.com/10873410/148103556-a7fe4467-f990-4ebf-b6f6-42d95b392259.png">

- Completely scrambled dialog layout for things like File->New, Image->Resize, etc.
<img width="207" alt="image" src="https://user-images.githubusercontent.com/10873410/148103785-f9903aa8-118a-42b7-85ad-1b48c1f93d7d.png"> 

**Here is the change in 6.0.1 that is _highly_ suspicious:** https://github.com/dotnet/winforms/pull/6114 cc @RussKie 

In my code, I'm setting the window's opacity myself via `SetWindowLongPtrW()` and `SetLayeredWindowAttributes()`. This is because, way back with .NET 1.1 in 2004, there was some bug with `Form.Opacity` that I don't remember the details of. (I may be able to remove this code now, but like ... it ain't broke so don't fix it? maybe?) When "Translucent windows" is _disabled_, this ends up causing the window handle to be created in my `Form`s constructor (in a common base class that all other forms derive from), after `SuspendLayout()` and `InitializeComponent()`, and right before `ResumeLayout(false)`. I do consider this to be a bug in my code, but it should only be a performance bug, and it's been working fine for literally 18 years (Paint.NET 1.0 was originally released in May 2004 on .NET 1.1).

My fix, which is in the frantically released 4.3.7 update, is to first check `this.IsHandleCreated` before grabbing `this.Handle` to manually set the form's opacity (via `SetWindowLongPtrW()` and `SetLayeredWindowAttributes()`).

The behavior of the bug(s) seems to indicate some kind of disconnect between what WinForms thinks the handle is, and what handle Win32 is using, or maybe a disconnect between various parts of WinForms itself. Dialogs aren't closing properly, layout is all broken, every new dialog is at the top-left corner of the screen instead of centered, etc. The app will soft hang because modal progress dialogs don't close when they're supposed to. It's just a total disaster.

**Expected behavior:**
Everything works great. In reality, not even close :(

**Minimal repro:**
Here's a ZIP of the "cursed" Paint.NET v4.3.6 build, in portable (self-contained deployment) form: https://www.dotpdn.com/files/zip/test/paint.net.4.3.6.portable.x64.zip

Launch the app by double-clicking `paintdotnet.exe`. You should be able to launch things like File->New, Image->Resize, Layers->Rotate/Zoom, and run effects and adjustments and everything works fine.

Next, go into Settings (gear icon at top right of main window), then uncheck the box "Translucent windows". This is supposed to only affect the floating tool forms, since they're the only forms that use `Opacity`. Anyway, close the window and then try all the things listed above (File->New, etc.). _Everything will be completely, catastrophically broken._

I'm able to provide access to my solution/code for MSFT employees thanks to an NDA/license that @richlander and I set up a few years back. I can then easily show you which lines of code to change to make things broken/fixed.

**Comment by rickbrew** [comment]
Also, to vent a bit, how on earth was a change like this approved for a _servicing release_ of .NET ?! I am completely baffled by this. Please don't do this again :( It took hours of frantic troubleshooting and debugging to figure this all out, and a lot of my users/customers were _really_ unhappy.

**Comment by jeffhandley** [comment]
CC @dotnet/platform-compat-team

**Comment by merriemcgaw** [comment]
@dreddy-work let's take a look asap!

**Comment by rickbrew** [comment]
I'm trying to create a minimal repro, I'll post it when it's ready

**Comment by dreddy-work** [comment]
Looking. @rickbrew , please share your repro when you have.

**Comment by rickbrew** [comment]
And again, the way I'm dealing with opacity by setting it myself is likely something I can remove, it's just an artifact of how things had to be done in 2004 for reasons that are half lost to time. But, it's been working fine for 18 years so it's hard to justify removing it and risk getting crash reports from an unknown number of systems.

**Comment by dreddy-work** [comment]
Nuget package "`TerraFx.*`" available to download? @rickbrew

**Comment by rickbrew** [comment]
TerraFX.Interop.Windows is on nuget.org, it's @tannergooding 's. Is it not downloading for you or something?

**Comment by rickbrew** [comment]
https://www.nuget.org/packages/TerraFX.Interop.Windows/10.0.20348/

**Comment by dreddy-work** [comment]
> TerraFX.Interop.Windows is on nuget.org, it's @tannergooding 's. Is it not downloading for you or something?

Initially it was not resolved for some reason. Now i can install it. Thank you for the link.

**Comment by dreddy-work** [comment]
@rickbrew , are you sure you do not see this issue in .NET 6.0?

**Comment by dreddy-work** [comment]
@rickbrew , I am trying to investigate with sample app provided.  In repro scenario from sample app, i see you were forcing `Handle `creation in setting the Opacity. This Handle creation was taking BaseForm's property `this.StartPosition = System.Windows.Forms.FormStartPosition.WindowsDefaultBounds;` into consideration and thus creating `Form `with windows default bounds instead of Winforms default (300, 300) and you override this in derived form to `FormStartPosition.Manual` but the Handle was already created forcibly. This part of the code hasn't changed recently but there were changes on when and where the Handle should be created in the 5.0-time frame. Was Paint.NET, version 4.3.5 was running against .Net 6.0 without any issues?

**Comment by rickbrew** [comment]
@dreddy-work Yup, everything was working fine from .NET 1.1 up through .NET 6.0, but stopped working correctly with 6.0.1.

**Comment by rickbrew** [comment]
@dreddy-work , TerraFX's last .NET 5 release was v10.0.20348-rc1

Search this page for ".NET 5" and you'll see it: https://github.com/terrafx/terrafx.interop.windows/releases

**Comment by rickbrew** [comment]
btw it should not be setting `StartPosition` to `Manual`, that was just a mistake. I've updated the repo.

**Comment by dreddy-work** [comment]
@rickbrew , something is missing here.  I see the repro scenario all the way to .NET 3.1. i.e. the problem you are defining with your sample app exist in .NET 3.1 as well. Do you have a machine with just 6.0 and you do not see the problem? Can you share a gif with running sample app you provided above?

**Comment by rickbrew** [comment]
Well the tailored repro is Paint.NET itself. I can provide you access to the repo and you can jump between the commits/branches to test it on Framework 4.7, .NET 5.0.x, 6.0, and 6.0.1. I can also provide installers for all versions that use .NET 1.1 through 4.7, and installers / portable ZIPs for the .NET 5+ versions. 

Would that be worth trying out?

**Comment by dreddy-work** [comment]
I see you have standalone installers for Paint.NET (including net runtime/winforms binaries with it). Can you provide a working version of standalone installer targeting net 6.0?

**Comment by rickbrew** [comment]
Sure -- e-mail me at contact@getpaint.net and I'll send you download links

I don't have an FDD build prepared, but I may be able to transform my SCD into one (at build time I do the reverse, so it must be possible)

**Comment by dreddy-work** [comment]
Thanks. I am sending private message. I am not sure how to securely share download links on GitHub either.  If this does not work, i may need access to your repo to play with but that can be later.

**Comment by rickbrew** [comment]
Okay great -- I got your e-mail and have sent over all the things you requested 👍🏼

**Comment by fahadabdulaziz** [comment]
Maybe this issue related to https://github.com/dotnet/winforms/issues/6421

**Comment by dreddy-work** [comment]
For now, I can confirm #6114 is causing this issue. Will get the fix out soon. @rickbrew thank you for sharing paint.Net source.

**Comment by dreddy-work** [comment]
@rickbrew, linked PR is fixing the scenario. I would appreciate if you can validate the change with your app (binaries from linked PR). We would be getting this out in 6.0.2 servicing after validations on our side.

**Comment by rickbrew** [comment]
Many thanks for fixing this @dreddy-work ! I'll be fixing Paint.NET to not do this sort of thing in the first place, of course. I found some other early forced Handle creation locations that need patching, although thankfully none of them have caused anything other than a performance optimization opportunity.

**Comment by dreddy-work** [comment]
> So is the 6.0.2 servicing out yet?
> 
> I would like to try this myself too to make sure my program is now fixed (with the issue that this is related to on the fact that somehow `ShowInTaskbar` would randomly just close a form just by setting it.
 That issue might not be fixed yet. Our CTI said they could repro it with this change too.  I didn't get chance to debug that scenario yet. Let me know how it goes for you @AraHaan.

**Comment by AraHaan** [comment]
Alright, I will let you guys know for sure.

**Comment by VinoWang01** [comment]
Verified with .NET SDK 7.0.100-preview.1.22109.10 build, the results is same as following description by @rickbrew. Is this expected? 
![NotFixed](https://user-images.githubusercontent.com/90816462/153347565-d6fc74cc-8da9-4b60-88ff-84c4e322459a.gif)


> Okay I was able to at least recreate the form starting location and size not working correctly. It's a pretty simple project so that's all that it really manages to illustrate, but it should at least get you started.
> 
> https://github.com/rickbrew/WinForms6464
> 
> In Program.cs,
> 
> <img alt="image" width="287" src="https://user-images.githubusercontent.com/10873410/148266320-44c39b8b-4dfe-4a0c-94b7-b8da7e1d5e0c.png">
> 
> Set `DontCallIsHandleCreatedInCriticalPlaces` to `true` to recreate the bug, `false` to show how it should work.
> 
> With `false`, the main window opens roughly in the center of the screen, and then clicking the button creates a modal dialog that opens centered to that main dialog. This is how it should work.
> 
> ![image](https://user-images.githubusercontent.com/10873410/148266646-0d412353-1b07-4c8a-bedf-b21aefa2e506.png)
> 
> With `true`, it's stuck to the top left, smaller, and the second dialog also hugs the top left corner.
> 
> <img alt="image" width="337" src="https://user-images.githubusercontent.com/10873410/148266712-af90edd1-08cc-480b-a33a-4a49ecf91a00.png">
> 
> <img alt="image" width="313" src="https://user-images.githubusercontent.com/10873410/148266733-6fe174d1-7c16-41bc-a59f-dc1eb2bccf71.png">

**Comment by dreddy-work** [comment]
@VinoWang01 , issue was when you click on "ClickMe" does it open model dialog in the center of parent dialog or to the top-left of the screen. Earlier it was opening model dialog on the top left and now we expect it to open in the center. This was serviced to 6.0 so behavior would be now same in 7.0 and 6.0. Original issue gif if you observe, it was opening model dialog after clicking "ClickMe" to the top-left.

**Comment by VinoWang01** [comment]
Thanks for the clarification, before this I thought the result would be consistent no matter if `DontCallIsHandleCreatedInCriticalPlaces` was set to `true` or `false`. Thank you!
