### ISSUE TITLE
ListView will fire the GroupCollapsedStateChanged when focus is on the ListViewItem and user expands/collapses a ListViewGroup using the keyboard

### ISSUE THREAD

**Issue by VinoWang01** [dotnet/winforms#6468]
.NET Core Version: 

-  .NET Core SDK: 7.0.0-alpha.1.21568.0

Have you experienced this same bug with .NET Framework?: 

- No. `ListViewGroup.CollapsedState` was implemented in .NET Core 5.0 (#3155) and from (#5960)

**Problem description:**
When the user uses the right or left key to expand/collapse the `ListViewGroup`, the focus will be on the `ListViewItem` in the group. At this time, continue to use the left/right key to collapse/expand the `ListViewGroup`, and the `GroupCollapsedStateChanged` event will be triggered, but the state doesn't change correspondingly.
![ExpandCollapsed](https://user-images.githubusercontent.com/90816462/148334551-8c9b1546-3ce3-4a87-852d-48c1619bcb44.gif)

**Expected behavior:**
The expected result should be one of the following:
1. Continue to use the left/right key to collapse/expand the `ListViewGroup`, and the `GroupCollapsedStateChanged` event will be triggered and the state changed correspondingly.
2. Continue to use the left/right key to collapse/expand the `ListViewGroup`, and the `GroupCollapsedStateChanged` event will not be triggered and the state doesn't change correspondingly.

**Minimal repro:**
1. Create a `Form` with a `ListView`.
2. Add` ListViewGroups` to the `ListView` (`ListViewGroups` should have `CollapsedState = ListViewGroupCollapsedState.Expanded` or `CollapsedState = ListViewGroupCollapsedState.Collapsed`).
3. Add `EventHandler` for `GroupCollapsedStateChanged`.
4. Run the application.
5. Expand/collapse a `ListViewGroup` using the keyboard.
[ListViewGroupState.zip](https://github.com/dotnet/winforms/files/7819708/ListViewGroupState.zip)

**More Info:**
This issue can't reproduce when using mouse to expand/collapse `ListViewGroup`.

**Comment by dreddy-work** [comment]
@VinoWang01 , is this regression from any of the previous .NET versions (6.0?)

**Comment by VinoWang01** [comment]
@dreddy-work, this feature is enabled from 7.0, `ListViewGroup.CollapsedState` was implemented in .NET Core 5.0 (Implement Collapsible/Collapsed for ListViewGroup #3155) and from (ListView not firing GroupCollapsedStateChanged when user expands/collapses a ListViewGroup using the keyboard #5960)

**Comment by Philip-Wang01** [comment]
Verified this issue in .Net SDK 7.0.100-preview.4.22227.3 test pass build, it was fixed.
![70ceshi](https://user-images.githubusercontent.com/86937911/165704170-865597ae-860b-497a-bd38-20d34d25fc0a.gif)
