### ISSUE TITLE
[RUS] The ‘Details’ button text overlaps its drop down arrow in unhandled exception dialog

### ISSUE THREAD

**Issue by VinoWang01** [dotnet/winforms#6490]
.NET Core Version: 

- .NET SDK 7.0.100-alpha.1.22060.9

Have you experienced this same bug with .NET Framework?: 

- No

**Problem description:**
The text overlaps the drop down arrow in ‘Details’ button of Unhandled exception window.
![RUS-Core](https://user-images.githubusercontent.com/90816462/148921242-13a34e54-69d9-48da-bd1d-bd17a7923118.png)

**Expected behavior:**
There should be no overlapping.
NetFX:
![RUS-NetFX](https://user-images.githubusercontent.com/90816462/148921265-bd6fd7c5-820d-4510-866d-3a1901180b92.png)

.NET Core 3.1:
![RUS-Core31](https://user-images.githubusercontent.com/90816462/148921302-fe2274b8-c714-4a26-a0b3-6ea0622df9c3.png)

**Minimal repro:**
1.	Create a Winforms core project.
2.	Add a button control on Form designer.
3.	Double click the button and add following code: `throw new Exception("")`; in `button_click` event handler.
4.	Run the project via pressing `Ctrl + F5`.
Or use the sample project with changing the target to 7.0: 
[UnhandledExceptionDialog.zip](https://github.com/dotnet/winforms/files/7859422/UnhandledExceptionDialog.zip)

**More Info:**
1. This is a regression issue, it can’t reproduce when targeting .net core 3.1, it reproduce from .net 5.0 to latest .net 7.0.
2. This issue can’t reproduce with .NET Framework project.

**Comment by Tanya-Solyanik** [comment]
@cristianosuzuki77 , @csigs  - could you please restore the .NET Framework translation?

**Comment by v-mholloway** [comment]
@VinoWang01 can you provide an english screen shot for context...?

**Comment by Cassie-Li01** [comment]
Hi @v-mholloway The ENU screenshot as below, please kindly check:
![image](https://user-images.githubusercontent.com/96758262/180677171-3909d571-0e60-4ebd-a79c-1b69d8e887fe.png)

**Comment by Ashley-Li** [comment]
Verified this issue on .NET SDK latest build: 8.0.100-alpha.1.23068.16, issue was fixed. Now the "Details" button text does not overlap with the drop down arrow in the unhandled exception dialog.
![image](https://user-images.githubusercontent.com/56664234/213411425-9cece81c-3f91-45c2-b5af-fa2620c6b292.png)
