### ISSUE TITLE
The dropdown button is no visible in ComboBox control when set FlatStyle property to Flat or Popup

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#6494]
* .NET Core Version: 
.NET SDK 7.0.100-alpha.1.22060.5

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

The dropdown button is no visible in ComboBox control when set FlatStyle property to Flat or Popup.

Design Time:
![DesignTime](https://user-images.githubusercontent.com/45864985/149062167-cc1f413b-39d9-41b4-a845-a9d5f9f71219.png)

Runtime:
![Runtime](https://user-images.githubusercontent.com/45864985/149062175-e7aa3f83-d00e-448f-a2b7-3498b063a30a.png)

**Expected behavior:**

The dropdown button is no visible in ComboBox control when set FlatStyle property to Flat or Popup.

Design Time:
![Expected-DesignTime](https://user-images.githubusercontent.com/45864985/149062197-6c8787ce-b1ba-42a3-8788-1ae1869d2301.png)

Runtime:
![Expected-Runtime](https://user-images.githubusercontent.com/45864985/149062200-86a92b0c-e668-49a1-9310-526c8677aa91.png)

**Minimal repro:**

1. Open the [TestApp.zip](https://github.com/dotnet/winforms/files/7851589/TestApp.zip) project.
2. Open Form1 designer and observe the dropdown button of ComboBox controls in the second and third columns.
3. Run the project, and observe the dropdown button of ComboBox controls in the second and third columns too.

**More info:**

1. This is a regression issue, it does not occur in .NET 7.0.100-alpha.1.21568.2, and it occurs in .NET 7.0.100-alpha.1.22060.5.
2. This issue does not occur when set FlatStyle property to Standard or System.

**Comment by John-Qiao** [comment]
Verified with 7.0.100-preview.2.22077.9 from main branch, this issue has been fixed that the dropdown button is visible in ComboBox control when set FlatStyle property to Flat or Popup now.

![TR](https://user-images.githubusercontent.com/45864985/151479416-bed23891-cf00-4506-97cb-d941149c7884.png)

**Comment by VinoWang01** [comment]
Verified with .NET SDK 7.0.100-preview.1.22109.10 build, this issue is fixed, the result is same as above screenshot shown.
