### ISSUE TITLE
[CSY] ‘Details’ and ‘Continue’ have the same hotkey: P in unhandled exception dialog

### ISSUE THREAD

**Issue by VinoWang01** [dotnet/winforms#6496]
.NET Core Version: 

- .NET SDK 7.0.100-alpha.1.22060.5 

Have you experienced this same bug with .NET Framework?: 

- No

**Problem description:**
‘Details’ and ‘Continue’ have the same hotkey: P
![image](https://user-images.githubusercontent.com/90816462/149255111-bbeb9aab-4c7d-4c05-9f0a-9904bed71000.png)

**Expected behavior:**
The hot key should be unique.
![image](https://user-images.githubusercontent.com/90816462/149255128-dfbc6f48-5780-47d8-a661-d3d6d8ed45ad.png)

**Minimal repro:**
1.	Create a Winforms core project.
2.	Add a button control on Form designer.
3.	Double click the button and add following code: `throw new Exception("");` in `button_click` event handler.
4.	Run the project via pressing `Ctrl + F5`.
5.	Press `Alt` keyboard, then observe the hot key.
Or use the sample project with changing the target to 7.0.
[UnhandledExceptionDialog.zip](https://github.com/dotnet/winforms/files/7859386/UnhandledExceptionDialog.zip)

**More info:**
This issue can’t reproduce with ENU, CHS, CHT, DEU, ESN, FRA, JPN, ITA, KOR, PLK, PTB, RUS, TRK languages.

**Comment by dreddy-work** [comment]
https://ceapex.visualstudio.com/CEINTL/_workitems/edit/764839

**Comment by dreddy-work** [comment]
Waiting on loc to fix as it overrides any local fixes.

**Comment by Amy-Li03** [comment]
Verified this on .NET latest build: 8.0.100-preview.2.23116.28, issue was fixed, Details’ and ‘Continue’ have the unique hotkey in unhandled exception dialog, so close it.
![image](https://user-images.githubusercontent.com/62929087/219533892-dc547620-64e1-4af7-925f-c0e6a723965f.png)
