### ISSUE TITLE
Misc build failures in 'official/$(reponame)/refs/heads/master' - '20190328.1'

### ISSUE THREAD

**Issue by robertborr** [dotnet/winforms#650]
@dotnet-mc-bot commented on [Thu Mar 28 2019](https://github.com/dotnet/core-eng/issues/5718)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=136611
  - **Agent:** a000010
  - **Error log:** F:\vsagent\3\s\.packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(0,0): error : 'Resources\xlf\SR.cs.xlf' is out-of-date with 'Resources\SR.resx'. Run `msbuild /t:UpdateXlf` to update .xlf files or set UpdateXlfOnBu...

@robertborr

---

@robertborr commented on [Thu Mar 28 2019](https://github.com/dotnet/core-eng/issues/5718#issuecomment-477734036)

Build FAILED.

F:\vsagent\3\s\.packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(92,5): error : 'Resources\xlf\SR.cs.xlf' is out-of-date with 'Resources\SR.resx'. Run `msbuild /t:UpdateXlf` to update .xlf files or set UpdateXlfOnBuild=true to update them on every build, but note that it is strongly discouraged to set UpdateXlfOnBuild=true in official/CI build environments as they should not modify source code during the build. [F:\vsagent\3\s\src\System.Windows.Forms.Design.Editors\src\System.Windows.Forms.Design.Editors.csproj]
    0 Warning(s)
    1 Error(s)

**Comment by merriemcgaw** [comment]
Already addressed.
