### ISSUE TITLE
Bug in code produced by Visual Studio 2022.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#6529]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bug-in-code-produced-by-Visual-Studio-20/1639489)._

---
Hello Microsoft,

I’m trying to convert my Windows Desktop Apps to Windows Forms and .NET Core 6.
I have discovered a bug in the code produced by Visual Studio 2022. 
I have put my reproducible solution on GitHub at https://github.com/CBrauer/Microsoft-2022-bug.
When running the program, you will see a table with four quadrants. In the lower right cell, I have put another table with two cells.  I dragged a “dayChart’ from the Toolbox into each cell. The dayCharts are labeled dayChart1 and dayChart2.
The purpose of two charts is to show yesterday’s data in dayChart1, and today’s data in dayChart2.
The layout shown in the designer is correct.
When running the program dayChar1 is on top of dayChart2.  This is the bug.

Charles

! [image.png] (https://aka.ms/dc/image?name=B742d566573f8443d844a6422155918ff637780528696633101_20220117-134748-image.png&tid=742d566573f8443d844a6422155918ff637780528696633101)

---
#### Feedback Bot on 1/18/2022, 11:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vino wang [MSFT] on 1/19/2022, 02:54 PM: 

<p>Thanks for reporting the ticket here to help us improve our Visual Studio. There are two questions need your confirmation:</p>
<ol>
<li>Does this problem only reproduced in NET 6.0 Windows Forms projects? Or it also reproduce with the .NET Framework project?</li>
<li>Does this issue reproduced with Visual Studio 2019?</li>
<li>Could you please provide us how to create the ‘dayChart’ customer control into Toolbox?</li>
</ol>
<p>We’re looking forward to hearing from you! Thank you!</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Charles Brauer on 1/19/2022, 10:43 PM: 

<p>In answer to “Does this problem only reproduced in NET 6.0 Windows Forms projects”.  I’m trying convert to .NET Core 6.  I don’t have time, nor any good reason, to try other toolkits.</p>
<p>In answer to “Does this issue reproduced with Visual Studio 2019?”. That is a stupid question.  I’m not about to load Visual Studio 2019 on my machine.</p>
<p>In answer to “Could you please provide us how to create the ‘dayChart’ customer control into Toolbox?” Why do you ask this question? I showed you the location of my complete reproducible project source code solution on GitHub.  You obviously have not looked at it.  The source code for “dayChart” is in that project download.</p>
<p>Charles</p>

#### Vino wang [MSFT] on 1/20/2022, 08:46 AM: 

<p>In fact, I have tried to clone and run your <code>HedgeToolsCharts</code> project before replying to you, but the project where the custom controls are loaded failure, but it does not affect the reproduction of the problem after adding <code>ChartLibrary</code> and <code>MyLibrary</code> dlls to the Dependence.<br>
<img src="https://aka.ms/dc/image?name=B8490170f92554999b73a4517b2bcd517637782360783488953_20220120-084117-image.png&amp;tid=8490170f92554999b73a4517b2bcd517637782360783488953" alt="image.png"></p>
<p><img src="https://aka.ms/dc/image?name=B258b19b147d34b3b865a63389b5522e1637782363740808692_20220120-084612-image.png&amp;tid=258b19b147d34b3b865a63389b5522e1637782363740808692" alt="image.png"></p>
<p><img src="https://aka.ms/dc/image?name=Be5bf23193b4d467880d2e61b56cacbf7637782361824296971_20220120-084301-image.png&amp;tid=e5bf23193b4d467880d2e61b56cacbf7637782361824296971" alt="image.png"></p>
<p>Now my problem is to know how to create that control, I can try to create my own project just try the custom controls you mentioned to see if I can reproduce the problem easily without your project. I asked you the first two questions to confirm whether this is a regression problem and whether it is a core-specific problem, because your project seems to be a core project.</p>
<p>Could you please give me a complete project that can load successfully? Thank you very much</p>

#### Charles Brauer on 1/21/2022, 00:49 AM: 

<p>Try the GitHub download again.  It’s a new version.</p>

---
### Original Solutions
(no solutions)

**Comment by VinoWang01** [comment]
.NET Core Version: 

- .NET 7.0.100-alpha.1.22069.1 build



Have you experienced this same bug with .NET Framework?: 

- Don't know



**Problem description:**
When running the project, you will see a table with two quadrants. In the second cell, have dragged a “dayChart’ from the Toolbox into each cell. Then generate the dayChart_Load event to each dayChart control. Build and run the project, only can see the one chart shown.
![image](https://user-images.githubusercontent.com/90816462/150520139-5df16d4b-1294-4c72-a3f2-30554f6bef23.png)



**Expected behavior:**
The dayChart1 and dayChart2 should be displayed in the correct position.


**Minimal repro:**
1. Download the attached project.
[HedgeToolsCharts.zip](https://github.com/dotnet/winforms/files/7912988/HedgeToolsCharts.zip)
2. Build and run it.

**Comment by dreddy-work** [comment]
@VinoWang01 , can you look into if this was a regression either form Framework or from earlier versions of .Net core?

**Comment by VinoWang01** [comment]
Verified it on .NET Framework project, it's still reproducing with .NET Framework application:
![image](https://user-images.githubusercontent.com/90816462/153359442-2e996414-b993-4507-a43c-be9d77cd2b6c.png)

**Comment by merriemcgaw** [comment]
Since this is impacting both .NET and .NET Framework we're going to hold off on addressing it.
