### ISSUE TITLE
Reenable integration tests partially

### ISSUE THREAD

**Issue by kant2002** [dotnet/winforms#6532]
As part of #6091 not only MAUI tests was disabled, but and some end-to-end tests for folder browser dialog box for example. Because I add that tests I did not expect that.

My question is following, can we re-enable non-MAUI test in `System.Windows.Forms.IntegrationTests.csproj`? If they should be rewriten, then how? In order for me to safely migrate code to ComWrappers I would like to have this kind of tests in place and running.

**Comment by RussKie** [comment]
The tests in src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs are generally quite meaningless, they generally don't assert anything beyond "_looks like we were able to open a dialog with controls_", the E2E tests need to be  migrated into the UIIntegrationTests project, where we can assert specific aspects of functionality for each control.

We already have unit tests for the dialogs, and more were added in https://github.com/dotnet/winforms/pull/6244. It'd be great if you could check for any gaps, and fill them, if necessary. Also please have a look at the tests in UIIntegrationTests project, it should be fairly straight forward to add dialog specific tests there.
