### ISSUE TITLE
Can't use windows class names with different capitalization in the same application

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#654]
* .NET Core Version: 3.0 Preview1
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
Potentially the problem is in case sensitive comparison before registering window class, however I did not find confirmation in documentation that window class name is case sensitive or not.
https://github.com/dotnet/winforms/blob/a83e00a9ae61efa4dd9f529a4a7155de026db88e/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs#L1440-#L1452

**Actual behavior:**
Exception thrown: 'System.ComponentModel.Win32Exception' in System.Windows.Forms.dll
An unhandled exception of type 'System.ComponentModel.Win32Exception' occurred in System.Windows.Forms.dll
Class already exists
>	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.WindowClass.RegisterClass() Line 1666	C#
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.WindowClass.WindowClass(string className = "RichEdit50w", int classStyle = 0) Line 1487	C#
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.WindowClass.Create(string className = "RichEdit50w", int classStyle = 0) Line 1517	C#
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams cp = {System.Windows.Forms.CreateParams}) Line 724	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.CreateHandle() Line 5825	C#
 	System.Windows.Forms.dll!System.Windows.Forms.TextBoxBase.CreateHandle() Line 1482	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.CreateControl(bool fIgnoreVisible = false) Line 5883	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.CreateControl(bool fIgnoreVisible = false) Line 5898	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.CreateControl() Line 5850	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WmShowWindow(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 13940	C#

**Expected behavior:**
no crash
**Minimal repro:**
1. create a new winforms app
2. add a richedit text box to the form
3. add a new control derived from the RichTextBox that sets classname to RichEdit50w that is NOT spelled in all caps
4. add this control to the form and hit F5
```cs
    public class Class1 : RichTextBox
    {
        private IntPtr s_module;
        [DllImport("Kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        private static extern IntPtr LoadLibrary(string libname);

        protected override CreateParams CreateParams {
            get {
                if (IntPtr.Zero == s_module)
                {
                    s_module = LoadLibrary("msftedit.dll");

                    if (IntPtr.Zero == s_module)
                    {
                        // Couldn't load Richedit 4.1. We'll just let the base class return what it wants.
                        return base.CreateParams;
                    }
                }

                CreateParams cp = new CreateParams();

                cp.Width = this.Width;
                cp.Height = this.Height;
                cp.X = this.Location.X;
                cp.Y = this.Location.Y;
                cp.ExStyle = 0;
                cp.ClassStyle = 0;
                cp.Style = 0x100 /* ES_NOHIDESEL */ |
                           0x800 /* ES_READONLY */ |
                           0x10000 /* WS_TABSTOP */ |
                           0x2000000 /* WS_CLIPCHILDREN */ |
                           0x4000000 /* WS_CLIPSIBLINGS */ |
                           0x10000000 /* WS_VISIBLE */ |
                           0x40000000 /* WS_CHILD */;

                cp.ClassName = "RichEdit50w";

                return cp;
            }
        }
    }

```

**Comment by RussKie** [comment]
Checked in .NET Core 3.0/3.1 - no exception, but the control is not rendered at all; and the containing form becomes unresponsive (can't resize/maximize/minimize/close) but it can be moved around.
![image](https://user-images.githubusercontent.com/4403806/72854950-0b7e1100-3d0a-11ea-8213-504eb815c14c.png)

**Comment by weltkante** [comment]
The doc doesn't spell it out explicitly that names are not case sensitive but [RegisterClass](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerclassw#return-value) says:

> If the function succeeds, the return value is a class atom that uniquely identifies the class being registered.

Being an atom means that names are not case sensitive, as explained in the [doc about string atoms](https://docs.microsoft.com/en-us/windows/win32/dataxchg/about-atom-tables#string-atoms):

> Case is not significant in searches for an atom name in an atom table.

**Comment by vinicio328** [comment]
@Tanya-Solyanik 
I faced the same issue, but I have a fix for that, based on docs
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.createparams.classname?redirectedfrom=MSDN&view=netcore-3.1#System_Windows_Forms_CreateParams_ClassName

It says: 

> The default value for this property is null, indicating that the control is not derived from an existing control class. To derive from an existing control class, store the system class name in this property. For example, to derive from the standard Button control, set this property to "BUTTON".

So based on that on CreateParams, when I set the ClassName I just did an Upper method call and it fixed the Class Already exists exception. 

`protected override CreateParams CreateParams
        {
            get
            {
                if (_moduleHandle == IntPtr.Zero)
                {
                    string richEditDllPath = GetRichEditDllPath();
                    _moduleHandle = LoadLibrary(richEditDllPath);
                    if ((long)_moduleHandle < 0x20)
                    {
                        throw new Win32Exception(Marshal.GetLastWin32Error(), "Error: Unable to load the Rich Text dll.");
                    }
                }
                CreateParams createParams = base.CreateParams;
                createParams.ClassName = _currentDLLClassName.ToUpper();
            }
        `

**Comment by JeremyKuhne** [comment]
As @weltkante pointed out https://github.com/dotnet/winforms/issues/654#issuecomment-577614294, I don't think there is anything we can do here.
