### ISSUE TITLE
The Inspect draws a border around a DataGridViewRow when the user hovers over a DataGridViewRowHeaderCell

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6570]
.NET Core Version: 
- 7.0.0-preview.2.22076.16

Have you experienced this same bug with .NET Framework?: 
- Yes for `.NET Framework 4.8` (not reproduced in `.NET Framework 4.7.2`)

**Repro steps:**

1. Add a `Form` with a `DataGridView`
2. Add multiple `Columns` and `Rows`
3. Run the application
4. Hover over the `Header` of any `Row`

**Actual behavior:**
The Inspect draws a border around a `DataGridViewRow`
![image](https://user-images.githubusercontent.com/23376742/151553802-f9fc7a3a-9ff6-41a3-94a2-1878731dcc21.png)

**Expected behavior:**
The Inspect should draw a border around a `DataGridViewRowHeaderCell`
![image](https://user-images.githubusercontent.com/23376742/151553981-5613e0c7-9d7d-4119-99b6-bd71ce2f6275.png)

**Comment by dreddy-work** [comment]
Is the hierarchy in Accessible tools shows as expected here?

**Comment by SergeySmirnov-Akvelon** [comment]
In both cases, the UIA tree is displayed in the same way:
**.NET Framework 4.7.2:**
![image](https://user-images.githubusercontent.com/23376742/154959386-8adf741a-de82-423c-a84d-afce158c5885.png)

**.NET Core 6.0:**
![image](https://user-images.githubusercontent.com/23376742/154959470-7ecb14dd-b082-4a5a-ab00-9a372682c821.png)
