### ISSUE TITLE
Code of the DateTimePicker.Text doesn't match its description in documentation

### ISSUE THREAD

**Issue by ArtemTatarinov** [dotnet/winforms#6590]
* .NET Core Version: From 3.0 to 7.0
* Have you experienced this same bug with .NET Framework?: Yes, from 2.0 to 4.8

**Problem description:**
`Text` property of the `DateTimePicker` class returns the value of the `Text` property of the base class (i.e. `Control`):
![image](https://user-images.githubusercontent.com/87859299/151927126-aa0f5ddf-a996-47f0-b2e2-1a56836ab998.png)

Yet the documentation says that `Text` is an equivalent of the formatted `Value` property (https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datetimepicker.text):
![image](https://user-images.githubusercontent.com/87859299/151927841-6770fea0-3355-4ec2-8764-5e34ca5af292.png)

This behavior is the same for all .Net versions: from .Net Framework 2.0 to .Net Core 7.0, and also documentation says the opposite thing for all of these versions. The `Text` property isn't visible at the Visual Studio designer, yet it's visible at the IntelliSense, because it has `public` modifier.

This is how it looks while debugging:
![image](https://user-images.githubusercontent.com/87859299/151927903-3a631906-01f7-4bc0-85ab-c040473482f6.png)

Looks like either the code or the documentation should be changed to be consistent.

**Comment by ArtemTatarinov** [comment]
Hi, @merriemcgaw, @Tanya-Solyanik, @dreddy-work, could you please look at it?

**Comment by Tanya-Solyanik** [comment]
Suggestion:
Change the getter to `return Value;` in .NET 7 and fix documentation for other versions.

**Comment by Ashley-Li** [comment]
Verified with .NET SDK 7.0.100-preview.3.22123.5 build, this issue is fixed.
![image](https://user-images.githubusercontent.com/56664234/155498391-fcecd2d2-19da-4dc7-a970-59000978e720.png)

**Comment by Cassie-Li01** [comment]
Verified on .NET SDK 7.0.100-preview.3.22152.5 build, this issue is fixed.
![image](https://user-images.githubusercontent.com/96758262/156960415-f16fb7e9-2331-4d1f-80f4-991a2064de78.png)
