### ISSUE TITLE
❓ Survey: Repo contribution experience 2022

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#6596]
A couple years ago we surveyed you the members of the community in this repo to learn how we were doing as maintainers.

It's time to repeat the same survey. Whether you've been involved for years or you're relatively new please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:
https://www.surveymonkey.com/r/8QTQTGJ?Source=winforms

**Comment by RussKie** [comment]
Hi folks, if you haven't had a chance to take the survey it'd be really appreciated if you could spare few minutes for it. Thank you.

@weltkante @gpetrou  @kirsan31 @kant2002  @jbhensley @willibrandon @roland5572 @rickbrew @noseratio @paul1956 @alanhoman @Balkoth @filipnavara @tbambuch @2mik @AraHaan @eriawan

**Comment by AraHaan** [comment]
I submitted. Overall I find that it's ok, however it is somewhat a pain to package locally built changes into installers without any manual changes to the files from dotnet/windowsdesktop as well.

If only there was a better way to include them (even if it means having the wpf and winforms repos as submodules of that repo so we can more easily package our local changes in the installers without too much work).

**Comment by RussKie** [comment]
Thank you.

> If only there was a better way to include them (even if it means having the wpf and winforms repos as submodules of that repo) so we can more easily package our local changes in the installers without too much work.

If you start a [new discussion](https://github.com/dotnet/winforms/discussions/new) outlining what you're trying to do I'll try to help you.

**Comment by willibrandon** [comment]
I really like this repo. It is by far the most interesting thing on the internet. It’s like I’ve died and gone to programming heaven. Thank you very much.

**Comment by Balkoth** [comment]
The real problem that i have with this repo is how complex it is to set it up. If you don't want to f... up your production development system, you have to use a VM for it. And then there are the docs, which are sometimes outdated. If it weren't for @RussKie i would have had no chance.

**Comment by kirsan31** [comment]
> The real problem that i have with this repo is how complex it is to set it up. If you don't want to f... up your production development system, you have to use a VM for it. And then there are the docs, which are sometimes outdated. If it weren't for @RussKie i would have had no chance.

Really? Imho comparing to some linux based build repos this one is very easy to setup :man_shrugging:

**Comment by RussKie** [comment]
We're miles ahead from where we were two year ago in terms of repo setup. Yes, it's still impossible to just clone and double click the sln file, but it should be pretty seamless. Please open a new discussion with your pain points and we'll see how we help you.

**Comment by kant2002** [comment]
I miss that survey, because my primary repo was `dotnet\runtime` and after finishing survey for first repo, family capture me. This is so far, best repo for dogdooging across dotnet family. 
Positive things:
- Easy to setup (5 points)
- Easy to use after build (5 points)
- Friendly team and community (5 points)
- NativeAOT and innovation firends (5 points). That's my personal lovely points.

Smallish annoyances (or nice to haves)
- Too strict code style (4 points). I do like that style, but after relatively relaxed runtime repo this was a bit unuual, even if a lot of style decisions similar to mine personal preferences.
- Strict usage for CI (4 points). I do understand that somebody pay for CI and it should not be abused. But I do like a bit relaxed style of runtime repo, where you can use CI for running whole test suite.
- Not enough integration tests (4 points). That's probably require $$$, but I want more integration tests running in CI. Even if this would be long running process.

Even if this is Windows Forms, I can do great deal of code on Linux. Bonus points for being accessible for development from any platform.

**Comment by eriawan** [comment]
> Hi folks, if you haven't had a chance to take the survey it'd be really appreciated if you could spare few minutes for it. Thank you.
> 
> @weltkante @gpetrou @kirsan31 @kant2002 @jbhensley @willibrandon @roland5572 @rickbrew @noseratio @paul1956 @alanhoman @Balkoth @filipnavara @tbambuch @2mik @AraHaan @eriawan

Done. Thanks for this survey! 👍

**Comment by jbhensley** [comment]
I have been working issues in the repo as a means of personal development. Overall, I have found the code easy to build and debug. The maintainers are friendly, responsive, and seem to have the best interest of the WinForms community at large in mind.

**Comment by danmoseley** [comment]
If anyone completed the survey for another repo, then now want to do it for Winforms, you'll see it won't let you in. This link would allow you to jump to another instance - it won't wipe your answers to the link above.
https://www.surveymonkey.com/r/8TWNFZL?Source=winforms
We'll just aggregate all.

**Comment by kant2002** [comment]
and obviously `dotnet/wpf`.

**Comment by RussKie** [comment]
> * Strict usage for CI (4 points). I do understand that somebody pay for CI and it should not be abused. But I do like a bit relaxed style of runtime repo, where you can use CI for running whole test suite.

Could you please elaborate?



> * Not enough integration tests (4 points). That's probably require $$$, but I want more integration tests running in CI. Even if this would be long running process.

I'm not exactly sure what you mean. We run all our tests (unit/rendering/integration/accessibility) in CI. More tests are always welcome :)

**Comment by danmoseley** [comment]
This survey is now closed -- thanks to everyone that responded, we'll now dig through results.
