### ISSUE TITLE
Refactoring `AutomationId` at the `GetPropertyValue` method

### ISSUE THREAD

**Issue by ArtemTatarinov** [dotnet/winforms#6603]
We should consider refactoring the `AutomationId` property at `AccessibleObject` class and its descendants. Now 7 descendants of the `ControlAccessibleObject` class return the `Owner.Name` value for the `AutomationId` property at the `GetPropertyValue` method, and 4 descendants of the `AccessibleObject` class return `AutomationId` (which is not virtual now as each class implements it on its own).
 
We could refactor this property like that: 
- move the AutomationId property to the AccessibleObject class (it will be returned at the GetPropertyValue method here)
- make it virtual with the default implementation returning a `null` value
- keep the current implementations in the 4 classes derived from AO,  but mark them as overrides 
- move returning of the `Owner.Name` to the `ControlAccessibleObjectObject` class itself to make it universal for all its descendants.

This could be risky since some customers could have automation tests that rely on `AutomationId` and have custom controls derived from our control class that don't implement custom `AutomationIdProperty`, but maybe code simplification outweighs the risk and at the worst-case scenario we could just revert the future PR with the single `AutomationId` refactoring.

Original post: https://github.com/dotnet/winforms/pull/6429#issuecomment-1009023639

**Comment by RussKie** [comment]
If you could open a draft PR with the change you propose it would help us visualise the change and make it easier to reason about it.

**Comment by Philip-Wang01** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.100-preview.7.22370.3, issue was fixed, 

Default Control.Name:
![image](https://user-images.githubusercontent.com/86937911/180953095-31ea61ce-d418-4cd2-ae02-debdb14fb4b3.png)
Null:
![image](https://user-images.githubusercontent.com/86937911/180953136-046807f4-0abb-4315-92b9-8e6ef422a13d.png)
String.Empty:
![image](https://user-images.githubusercontent.com/86937911/180953192-d8811234-9575-4ff4-9a60-d6ebb02b0c86.png)

For the results of all controls, please refer to the results of private.

**Comment by Tanya-Solyanik** [comment]
Thank you @Philip-Wang01! This was a big chunk of work!
