### ISSUE TITLE
ToolStrip tests is flaky in arm64 and x86 CI build

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#6610]
* .NET Core Version: 7.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
- `ToolStrip_WndProc_InvokeMouseActivateWithHandle_Success` unit test fails sometime in arm64 CI build for successful PRs, that blocking deployment of fixes into sdk. *Stack trace* ([System.Windows.Forms.Tests_net7.0_arm64.log](https://dev.azure.com/dnceng/public/_build/results?buildId=1584807&view=artifacts&pathAsName=false&type=publishedArtifacts)):
```
System.Windows.Forms.Tests.ToolStripTests.ToolStrip_WndProc_InvokeMouseActivateWithHandle_Success [FAIL]
Assert.Equal() Failure
      Expected: 0
      Actual:   2
      Stack Trace:
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs(7139,0): at System.Windows.Forms.Tests.ToolStripTests.ToolStrip_WndProc_InvokeMouseActivateWithHandle_Success()
```
- `ToolStrip_WndProc_InvokeMouseActivate_Success`:
![image](https://user-images.githubusercontent.com/49272759/153145469-dc9cde28-4051-497d-9b5d-7fd5f34cebbd.png)

**Expected behavior:**
All correct tests pass every time.

**Minimal repro:**
- Run unit tests on arm64 environment (or create a PR with changes, CI build will do it)

**Comment by dmitrii-drobotov** [comment]
`ToolStrip_WndProc_InvokeMouseActivateWithHandle_Success` also fails on [x64](https://dev.azure.com/dnceng/public/_build/results?buildId=1676828&view=ms.vss-test-web.build-test-results-tab)
![image](https://user-images.githubusercontent.com/102954094/162429073-1c72ed41-5709-47f4-bdc1-296fc29849fb.png)

**Comment by Tanya-Solyanik** [comment]
ToolStrip_WndProc_InvokeMouseActivateWithHandle_Success does not show among failures in https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E14+definition%3A267. Thus closing

**Comment by Tanya-Solyanik** [comment]
Never mind, they don't show up in the stats because they are disabled.

**Comment by elachlan** [comment]
related: #7333
