### ISSUE TITLE
Re-enable skipped test: ImageList_FinalizerReleasesNativeHandle_ReturnsExpected

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#6635]
* .NET Core Version: 7.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
- `ImageList_FinalizerReleasesNativeHandle_ReturnsExpected` unit test fails sometime in x86 Debug CI build for successful PRs, that blocking deployment of fixes into sdk.

**Stack trace** ([System.Windows.Forms.UI.IntegrationTests_net7.0_x86.log](https://dev.azure.com/dnceng/public/_build/results?buildId=1596505&view=artifacts&pathAsName=false&type=publishedArtifacts))
```
System.Windows.Forms.UITests.ImageListTests.ImageList_FinalizerReleasesNativeHandle_ReturnsExpected [FAIL]
      Assert.Equal() Failure
      Expected: 32
      Actual:   31
      Stack Trace:
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ImageListTests.cs(47,0): at System.Windows.Forms.UITests.ImageListTests.ImageList_FinalizerReleasesNativeHandle_ReturnsExpected()
      Output:
        GDI handles before: 32
        GDI handles after: 31
```
**Expected behavior:**
- All correct tests pass every time.

**Minimal repro:**
- Run unit tests on x86 environment (or create a PR with changes, CI build will do it)

**Comment by dreddy-work** [comment]
This is still an issue after https://github.com/dotnet/winforms/pull/8772. Keeping it disabled to investigate further.
