### ISSUE TITLE
Needs to add tests attributes with conditional skipping for UI tests 

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#6653]
* .NET Core Version: 7.0

**Problem description:**
- Needs to add the ability to skip some tests in a specific architecture for UI tests and MAUI tests like we did it for unit tests (see [#6599](https://github.com/dotnet/winforms/pull/6599)). We can't use the attributes from unit tests utilities, because UI tests doesn't have a reference to them.
Based on this [comment](https://github.com/dotnet/winforms/pull/6599#issuecomment-1031969657)

**Solutions:**
- Copy-paste `ConditionalWinFormsFactAttribute` and `ConditionalWinFormsTheoryAttribute`
- Or add the dependency to UI tests project

**Will this feature affect UI controls?** No

**Comment by dreddy-work** [comment]
Not sure where you are tracking flaky tests. here is another to add to that list: 
![image](https://user-images.githubusercontent.com/36968667/153511761-e6c66050-ea80-4382-8520-0d5c6cde1b06.png)

**Comment by dreddy-work** [comment]
buildId=1611672
