### ISSUE TITLE
[TextPattern] Getting incorrect rectangles for multiline TextBox

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#6661]
* .NET Core Version: 7.0

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
- TextPattern doesn't show empty lines (RTL and LTR modes):
![image](https://user-images.githubusercontent.com/49272759/153213987-35181cfd-0e9b-4f67-9a1f-28979c8ec30a.png)
It's important, when the caret is in the empty line, Narrator announces it incorrectly:
![qzQ3n0qO2M](https://user-images.githubusercontent.com/49272759/153216185-f0a34a3b-deec-4070-b191-1ca79fe7a517.gif)

- In RTL mode some text ranges are not shown:
![image](https://user-images.githubusercontent.com/49272759/153213632-94c515de-91bb-45f1-a088-683b8a070c2f.png)

**Expected behavior:**
- UIA shows all text ranges correctly:
![image](https://user-images.githubusercontent.com/49272759/153214778-2721c068-815c-408c-b0b7-e5e9b5239dfa.png)

**Minimal repro:**
- Create a .NET 7.0 app
- Add a multiline TextBox to the app
- Run the app and use Narrator and Inspect to check this

**Comment by Nora-Zhou01** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.100-rc.1.22425.12, issue was fixed as belo
![box](https://user-images.githubusercontent.com/104609169/187174200-d99171e6-bcd5-4669-986d-1a3e53c459d2.png)
w

**Comment by Nora-Zhou01** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, issue was fixed, test result is same as above screenshot.
