### ISSUE TITLE
SendKeys Grouping fails

### ISSUE THREAD

**Issue by ak98** [dotnet/winforms#6666]
* .NET Core Version: 
6.0

* Have you experienced this same bug with .NET Framework?: 
NO

**Problem description:**

SendKeys.Send("^(a)^(c)") triggers exception.

ArgumentException
Exception:SendKeys string '^(a)^(c)' is not valid.

**Expected behavior:**
 Sends Ctrl-A then Ctrl-C

**Minimal repro:**
SendKeys.Send("^(a)^(c)")

**Comment by ak98** [comment]
PS. the handling of CancelMods is in error
needs to be byref

**Comment by merriemcgaw** [comment]
@ak98 can you talk about the use case here? There might be alternatives that we can point you to.

**Comment by Cassie-Li01** [comment]
Verified on Version 17.0.8 Preview 1.0 [32324.263.d17.0], it is fixed

**Comment by Philip-Wang01** [comment]
Verified this issue on .NET SDK 7.0.100-preview.3.22179.4 build, it is fixed
