### ISSUE TITLE
System.Drawing.ColorConverter throws exception for ConvertFrom

### ISSUE THREAD

**Issue by stephenjannin** [dotnet/winforms#667]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes/No

**Problem description:**
Migrating from 4.5.2 to .net core preview  3 we found 

var tc = new System.Drawing.ColorConverter()
var color = tc.ConvertFrom("Control");

**Actual behavior:** 
```
System.ArgumentException
  HResult=0x80070057
  Message=Control is not a valid value for Int32.
  Source=System.ComponentModel.TypeConverter
  StackTrace:
   at System.Drawing.ColorConverterCommon.IntFromString(String text, CultureInfo culture)
   at System.Drawing.ColorConverterCommon.ConvertFromString(String strValue, CultureInfo culture)
   at System.Drawing.ColorConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at Sgcib.Daf.Shell.Handler.ShellConfiguration.ConfigValueOf[T](String key, T defaultValue) in H:\SG\Git\SourcesSocgen\XOneTools\DafNetCore30\src\Shell\Handler\ShellConfiguration.cs:line 51

Inner Exception 1:
FormatException: Input string was not in a correct format.
```

**Expected behavior:**

  returns "{Name=Control, ARGB=(255, 240, 240, 240)}"

**Minimal repro:**
```
var tc = new System.Drawing.ColorConverter()
var color = tc.ConvertFrom("Control");
```

**Comment by rido-min** [comment]
@merriemcgaw  can you take a look?

**Comment by merriemcgaw** [comment]
ColorConverter was converted in the corefx repo a while back, but perhaps there was an override that they didn't take. @stephenjannin can you tell us the scenario that you're trying to achieve? Perhaps there is another way to go about it if corefx decides that they don't want to add this particular overload.

**Comment by weltkante** [comment]
There seem to be two different System.Drawing.ColorConverter implementations in corefx - one in [System.ComponentModel.TypeConverter](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/src/System/Drawing/ColorConverter.cs) and one in [System.Drawing.Common](https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/src/System/Drawing/ColorConverter.cs)

The implementation in ComponentModel appears to match the stack trace above. It calls into [ColorTable](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Drawing/ColorTable.cs) which only checks static fields on `Color` class and does not support the static fields on the `SystemColors` static class even though there is a [KnownColorTable](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Drawing/KnownColorTable.cs) class in the same folder which knows about `SystemColors`, but isn't used by the ColorConverter.

Looks like an inconsistency inside corefx?

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you check with the latest builds please?

**Comment by Olina-Zhang** [comment]
@merriemcgaw verified in .Net core 3.0 Preview4 latest release build, this issue **cannot repro** now: the results of .net Core and .net framework are same, all return "{Name=Control, ARGB=(255, 240, 240, 240)}"

**Comment by Olina-Zhang** [comment]
@merriemcgaw verified in .Net core 3.0 Preview4 latest release build, this issue **cannot repro** now: the results of .net Core and .net framework are same, all return "{Name=Control, ARGB=(255, 240, 240, 240)}"

**Comment by Tanya-Solyanik** [comment]
@Olina, thank you for the verification. Closing this issue
