### ISSUE TITLE
winforms .net 6.0.2 SetHighDpiMode

### ISSUE THREAD

**Issue by greengumby** [dotnet/winforms#6703]
.net 6.0.2 desktop sdk 

I am trying to understand how the following line impacts the scaling of controls.

Application.SetHighDpiMode(HighDpiMode.SystemAware);

Specifically a statusStrip with an embedded progress bar. (Splash Screen)

If I run the application without the SetHighDpiMode the progress bar is the correct height however with the SetHighDpiMode enabled the height seems to be around 300% larger vertically.  Horizontally there is no change to the design view.

In addition I have copied the form and startup code into a new project with no other dependencies and no vertical scaling is occurring.

So my question is where should I be looking to figure out what is influencing this control's height.  Other controls are impacted by this but as this is the first screen aka splash screen I thought it a simple form to start with.

Edit:

Found a setting under Display Settings -> Advanced Scaling Options -> Fix scaling for apps.

Toggling this setting off and then on seemed to fix the problem for the progress bar but the icons all still look very small. I'm guessing its supposed to scale the icon size but something is preventing this?

Thanks for any assistance you can provide.

**Comment by dreddy-work** [comment]
`Application.SetHighDpiMode(HighDpiMode.SystemAware);` is making application to scale to the Dpi setting of the Monitor where it is rendered. We would need a standalone app demonstrating the issue here to understand better.
