### ISSUE TITLE
NullReferenceException in CheckListBox

### ISSUE THREAD

**Issue by ThomasLee-Factbook** [dotnet/winforms#6707]
* .NET Core Version: 6.0.102
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
A NullReferenceException occurs in the CheckedListBox RefreshItems method when using a data source, see project [Example.zip](https://github.com/dotnet/winforms/files/8089130/Example.zip) .

**Expected behavior:**
No exception is thrown.

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net7.0/6.0 with provided Example application, it doesn't reproduce now. Close it now. @ThomasLee-Factbook, feel free to re-open it if you still meet it in the latest builds 
![6707_NotRepro](https://user-images.githubusercontent.com/26474449/174548372-c1a5adc0-1842-4c87-972a-185ac90c586a.gif)
