### ISSUE TITLE
ListView.GroupCollapsedStateChanged fires with incorrect GroupIndex/doesn't fire at all

### ISSUE THREAD

**Issue by jbhensley** [dotnet/winforms#6708]
.NET Core Version:  

* .NET Core SDK: 7.0.0-preview.2.22116.9

Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

When a key is pressed, `ListView` determines which group is affected by grabbing the `Group` property of the first selected item:

https://github.com/dotnet/winforms/blob/150aabc4cf47c303f980fbc6313c329e6da8583c/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L6934-L6937

This is incorrect if an item is selected in one group, followed by subsequent selection of a second group which can be done by holding down Ctrl and selecting a different group's header.

Behavior manifests different depending on whether changes in PR #6493 have been applied (note: PR not merged at time of issue creation).

- On most recent build: `ListView.GroupCollapsedStateChanged` event fires with incorrect `GroupIndex`

![ListViewGroup-unpatched](https://user-images.githubusercontent.com/13544395/154516336-a57ff954-fcda-4093-8c93-9a2fea7140a1.gif)

- After #6493 , the event does not fire at all

![ListViewGroup](https://user-images.githubusercontent.com/13544395/154516575-62709402-0a92-4ace-9579-1ea66eeef564.gif)

**Expected behavior:**

`ListView.GroupCollapsedStateChanged` should fire and have the correct value for `GroupIndex`

**Minimal repro:**

Code used for animations:

``` C#
using var form = new Form() { Size = new Size(808, 469) };
using var listView = new ListView();
using var textBox = new TextBox() { Multiline = true };

form.Controls.Add(listView);
listView.Location = new Point(10, 10);
listView.Size = new Size(770, 200);

form.Controls.Add(textBox);
textBox.Location = new Point(10, 220);
textBox.Size = new Size(770, 200);

var group1 = new ListViewGroup("Group 1") { CollapsedState = ListViewGroupCollapsedState.Expanded };
var group2 = new ListViewGroup("Group 2") { CollapsedState = ListViewGroupCollapsedState.Expanded };

listView.Groups.AddRange(new[] { group1, group2 });
listView.Items.Add(new ListViewItem("g1 - i1", group1));
listView.Items.Add(new ListViewItem("g1 - i2", group1));
listView.Items.Add(new ListViewItem("g1 - i3", group1));
listView.Items.Add(new ListViewItem("g2 - i1", group2));
listView.Items.Add(new ListViewItem("g2 - i2", group2));
listView.Items.Add(new ListViewItem("g2 - i3", group2));

listView.GroupCollapsedStateChanged += (_, e) =>
{
	textBox.Text = $"{DateTime.Now.TimeOfDay}: CollapsedStateChanged for {listView.Groups[e.GroupIndex].Header}{Environment.NewLine}{textBox.Text}";
};

form.ShowDialog();
```

**Comment by NikitaSemenovAkvelon** [comment]
In progress

**Comment by Amy-Li03** [comment]
Verified this issue with .NET 7.0 latest build: 7.0.100-preview.7.22370.3, issue was fixed. ListView.GroupCollapsedStateChanged can fire correct GroupIndex.
![Fixed](https://user-images.githubusercontent.com/62929087/181693873-7637875d-3a04-492f-b1b4-66475833967d.gif)
