### ISSUE TITLE
Integrate Framework end-to-end tests into Helix/Arcade

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#671]

**Comment by merriemcgaw** [comment]
This is the .NET Framework Suite @Olina-Zhang has ported it to .NET Core and we need to check it in and hook it up into Arcade.

**Comment by merriemcgaw** [comment]
@AdamYoblick you can close this out once @Olina-Zhang and team have the instructions and are set to go.

**Comment by AdamYoblick** [comment]
Sent instructions to @Olina-Zhang via email, closing this out :)
