### ISSUE TITLE
Re-enable skipped test: Button_AchorNone_NoResizeOnWindowSizeTallerAsync

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#6714]
* Global Issue: #6690

* .NET Core Version: 7.0

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
- Button_AchorNone_NoResizeOnWindowSizeTallerAsync unit test fails sometime in x86 Release CI build for successful PRs, that blocking deployment of fixes into sdk.

**Stack trace** ([System.Windows.Forms.UI.IntegrationTests_net7.0_x86.log](https://dev.azure.com/dnceng/public/_build/results?buildId=1611672&view=artifacts&pathAsName=false&type=publishedArtifacts)):
```
System.Windows.Forms.UITests.ButtonTests.Button_AchorNone_NoResizeOnWindowSizeTallerAsync [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs(151,0): at System.Windows.Forms.UITests.ButtonTests.<Button_AchorNone_NoResizeOnWindowSizeTallerAsync>b__6_0(Form form, Button button)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs(244,0): at System.Windows.Forms.UITests.ControlTestBase.<>c__DisplayClass27_0`1.<<RunFormAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
           at Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(CancellationToken cancellationToken)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs(255,0): at System.Windows.Forms.UITests.ControlTestBase.RunFormAsync[T](Func`1 createDialog, Func`3 testDriverAsync)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs(173,0): at System.Windows.Forms.UITests.ControlTestBase.RunSingleControlTestAsync[T](Func`3 testDriverAsync, Func`1 createControl, Func`1 createForm)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs(394,0): at System.Windows.Forms.UITests.ButtonTests.RunTestAsync(Func`3 runTest)
        /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs(136,0): at System.Windows.Forms.UITests.ButtonTests.Button_AchorNone_NoResizeOnWindowSizeTallerAsync()
        --- End of stack trace from previous location ---
      Output:
        Moving mouse to (276, 318).
        Screen resolution of (1024, 768) translates mouse to (17664, 27136).
```

**Expected behavior:**
- All correct tests pass every time.

**Minimal repro:**
- Run unit tests on x86 environment (or create a PR with changes, CI build will do it)

**Comment by dmitrii-drobotov** [comment]
Also failing on [x64](https://dev.azure.com/dnceng/public/_build/results?buildId=1705641&view=ms.vss-test-web.build-test-results-tab) and [arm64](https://dev.azure.com/dnceng/public/_build/results?buildId=1685056&view=ms.vss-test-web.build-test-results-tab)
![image](https://user-images.githubusercontent.com/102954094/162428272-70e645db-8331-473d-914d-3cedc0feae86.png)
![image](https://user-images.githubusercontent.com/102954094/162428602-1b65e94e-8f28-4142-9b56-63e834216bfa.png)
