### ISSUE TITLE
[PerMonitorV2] Anchoring controls to Bottom/Right does not work property

### ISSUE THREAD

**Issue by WolfgangHG** [dotnet/winforms#6717]
See attached .NET 6 sample: when moving the form from a screen at 100% to a screen at 125%, the controls anchored right/bottom are not rendered correct.
[DpiSample.zip](https://github.com/dotnet/winforms/files/8096436/DpiSample.zip)

This is at 100%:
![100](https://user-images.githubusercontent.com/138049/154667297-cd33fac0-7444-429a-b4a6-4a0dd740b595.png)

This is the result when moving the form to the 125% screen:
![125](https://user-images.githubusercontent.com/138049/154667367-ccc9d37c-8102-4037-9a10-38ad3dab99ac.png)
The groupbox overlaps the button, and the margins to the right are larger than expected.

In the project file, I set this:
`    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>`

And the form applies the OS default font (but removing this line does not change the result):
`this.Font = SystemFonts.MessageBoxFont;`

I saw that there are several other issues about "PerMonitorV2", but I can't say whether this problem is reported elsewhere.

**Comment by kirsan31** [comment]
Yea there are [problems](https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+Anchor) with Bottom/Right anchoring + HDPI in WinForms :(

**Comment by WolfgangHG** [comment]
I do not see my exact issue in this list - most issues deal with sub controls, while in my sample all controls are placed directly on the form. Other issues I found use other high dpi modes than `Application.SetHighDpiMode(HighDpiMode.PerMonitorV2);`
So I am not sure whether there is a duplicate.

**Comment by RussKie** [comment]
Is this PMv2 specific, or this is happening in SystemAware too?

**Comment by WolfgangHG** [comment]
With "SystemAware", it works. 
With "PerMonitor", there are the same problems as with "PerMonitorV2". 

But I don't know how reliable my tests are. Last friday, when creating the issue, I was in the office. But today, I am at home and can test it only in a remote desktop session.

**Comment by dreddy-work** [comment]
Should be addressed by https://github.com/dotnet/winforms/pull/7956. No repro with latest bits.
