### ISSUE TITLE
The ToolStripDropDownMenu is displayed incorrectly in the UIA tree

### ISSUE THREAD

**Issue by SergeySmirnov-Akvelon** [dotnet/winforms#6763]
.NET Core Version: 
- 7.0.0-preview.3.22123.2

Have you experienced this same bug with .NET Framework?: 
- Yes

**Repro steps:**
1. Create a `Form` with a `ToolStrip`.
2. Add `ToolStripDropDownButton` to `ToolStrip`.
3. Add multiple `ToolStripItems` to `ToolStripDropDownMenu`.
4. Run the application.
5. Run Inspect.
6. Open the `ToolStripDropDownMenu` and hover over the `ToolStripItem`

**Actual behavior:**
The `ToolStripDropDownMenu` returns `Form` as `Parent`
![image](https://user-images.githubusercontent.com/23376742/155700408-6fb5818f-73e5-4444-bff7-90c6256e59a1.png)

**Expected behavior:**
The `ToolStripDropDownMenu` should return `ToolStripDropDownButton` as `Parent`.

**Comment by Cassie-Li01** [comment]
This issue is fixed on build: .NET 7.0.100-preview.6.22281.2
![image](https://user-images.githubusercontent.com/96758262/171371387-16534530-a8b3-4b41-ab4c-2c3f24b314c7.png)

**Comment by Amy-Li03** [comment]
Verified this issue on .NET 7.0 test pass build: .NET 7.0.100-preview.5.22305.3, it was fixed.
