### ISSUE TITLE
Can we remove things like RunningOnWin2K

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#682]
E.g. in ListBox.cs

```cs
static bool RunningOnWin2K {
    get {
        if (!checkedOS) {
            if (Environment.OSVersion.Platform != System.PlatformID.Win32NT ||
                Environment.OSVersion.Version.Major < 5) {
                runningOnWin2K = false;
                checkedOS = true;
            }
        }
        return runningOnWin2K;
    }
}

```

**Comment by merriemcgaw** [comment]
That's a great suggestion for cleaning up our code! It's something we certainly should consider. We could also look at getting rid of tests for Win9x and WinXP  where it is looking for less than or equal to XP.

**Comment by zsd4yr** [comment]
I think we should clarify / enumerate which OSes we do not care to distinguish from any longer.

**Comment by hughbe** [comment]
From https://github.com/dotnet/core/blob/master/os-lifecycle-policy.md

**Comment by zsd4yr** [comment]
@merriemcgaw @Tanya-Solyanik can we provide some clarity here?

**Comment by AlanParr** [comment]
I'd like to take a look at this.
Removing from controls looks fairly straightforward.
There is also the [OSFeature.cs](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/OSFeature.cs) class which seems to only exist to allow checking for XP and 2K.

2 questions:
Are you happy with this entire class being removed as it now seems defunct?
If so, do as part of a PR for this issue or better done separately?

**Comment by hughbe** [comment]
> Are you happy with this entire class being removed as it now seems defunct

That would be super breaking. What we’ve done is remove the platform specific checks and essentially return true for these cases

**Comment by AlanParr** [comment]
So just

`internal bool OnXp => true;`

to keep the change isolated?

I've removed the checks from the controls, just need to tackle this class and fix some unrelated local build problems!

**Comment by hughbe** [comment]
Unfortunately I’ve already started on this and submitted a PR several weeks ago!! Sorry :( 
https://github.com/dotnet/winforms/pull/693

**Comment by AlanParr** [comment]
Didn't see that. No worries, I didn't spend a lot of time on it.

Will look at your PR for some tips :)

**Comment by hughbe** [comment]
This is fixed now :)
