### ISSUE TITLE
Renaming objects inside user control broke windows forms project completely

### ISSUE THREAD

**Issue by ooples** [dotnet/winforms#6828]
Using Visual studio 2022 Version 17.2.0 Preview 1.0 and I have 3 user controls with each one having datagrid. I renamed each datagrid in those user controls and suddenly the user controls disappeared from the design view and only appear when you run the application. If I try to add any new user controls to anywhere on my project I now get the error I have pasted below and I'm also getting these build errors whenever I try to add this new control to the project. My guess is that renaming the datagrid items in the user control wasn't successful and the project is still referencing the old names. Just my best guess

Error when adding new test user control to project:
![photo_2022-03-10_10-02-33](https://user-images.githubusercontent.com/3075685/157694176-826854ab-c42c-4e03-a0ff-340f1cccb085.jpg)

Build errors that only appear when adding a new user control to project:
![photo_2022-03-10_09-35-41](https://user-images.githubusercontent.com/3075685/157693644-6ad9ad5c-7741-44bb-aa96-a7eded0952fd.jpg)

Design view showing the far left control missing (watchlist) and the two on the right missing (alpaca overview and alpaca orders)
![photo_2022-03-10_10-22-03](https://user-images.githubusercontent.com/3075685/157693904-8b0c9c07-c269-40c5-894e-65361f35ebe5.jpg)

**Comment by dreddy-work** [comment]
@ooples, can you get us a stand alone WinForms application that we could debug ?

**Comment by ooples** [comment]
@dreddy-work I can share my private repo with this project if that is ok for you to check it out

**Comment by dreddy-work** [comment]
> @dreddy-work I can share my private repo with this project if that is ok for you to check it out

That should work.

**Comment by ooples** [comment]
@dreddy-work I sent you an invite to view the project and so you know my commit from today was many different attempts to try to fix the issue like trying to create new user controls to add to the project with many variations and imho this designer function is fucked in VS 2022 preview because I have been noticing other issues like designer code mysteriously deleting and causing build errors when nothing was done or design views being completely blank. I switched back to the latest release version of 2022 to see if I'm still getting these many errors with Windows Forms

**Comment by dreddy-work** [comment]
Can you please add @KlausLoeffelmann  and @RussKie  too?

**Comment by ooples** [comment]
I added both of them as well. Also to replicate this issue simply add any of the 3 user controls I mentioned to the main form dashboard and you will see one of the many errors. Let me know if you need me to do anything else

**Comment by ooples** [comment]
@dreddy-work Any updates yet or any issues with viewing the project? Also I wanted to specify that the other half of the problem is user controls completely disappearing from the windows form. You can verify that the user controls are added and after some changes like with renaming them they completely disappear from the visual mode

**Comment by dreddy-work** [comment]
> @dreddy-work Any updates yet or any issues with viewing the project? Also I wanted to specify that the other half of the problem is user controls completely disappearing from the windows form. You can verify that the user controls are added and after some changes like with renaming them they completely disappear from the visual mode

I am not in office today. @KlausLoeffelmann  will be taking a look at it as soon as he can.

**Comment by KlausLoeffelmann** [comment]
What are the repo steps exactly?
(I would need a minimal repo sample.).

**Comment by ooples** [comment]
@KlausLoeffelmann First error as I discussed above is error when trying to add the user controls that had renamed items. Simply add one of the user controls (WatchList.cs or AlpacaOverview.cs) to the FormDashboard.cs design view. 

Second error can be viewed by simply looking at the FormDashboard.cs design view and you will see the user controls that have renamed items don't show up at all on the design view and won't show up on the main form when you run the project

**Comment by KlausLoeffelmann** [comment]
No, what I mean is:
Can you provide a simple repro project (as a zip here into the discussion), I can just open in VS, and along with it a step-by-step list, how to hit this bug? (If you provided it already, sorry, then I missed it. Please point me to it.)

**Comment by ooples** [comment]
@KlausLoeffelmann I sent you an invite on here to my private repo that is simply one windows form and I specified the steps to replicate the issue. As far as the steps go I listed them right above. Or if you really need me to I can create a screen recording showing me perform both steps for you if that is what you prefer

**Comment by ooples** [comment]
@KlausLoeffelmann Any updates or progress? Did you run the code yet?

**Comment by KlausLoeffelmann** [comment]
Kudos to the UI Design, btw!

**Comment by KlausLoeffelmann** [comment]
Here are the exception I see, when I try to add the UserControl you described:

![image](https://user-images.githubusercontent.com/9663150/158211513-aafa960e-8786-494c-b440-f1bf2a62c94b.png)

![image](https://user-images.githubusercontent.com/9663150/158211585-2ad224d6-3eac-4222-9d1f-dc07e288632e.png)

![image](https://user-images.githubusercontent.com/9663150/158211633-41de23fe-4577-404f-a077-3cc9be5be13a.png)

![image](https://user-images.githubusercontent.com/9663150/158211672-04b64075-e16e-40d2-8128-c0bbf5407a3f.png)

![image](https://user-images.githubusercontent.com/9663150/158211723-59a82c99-5b84-4351-9923-f82cf50b2864.png)

**Comment by ooples** [comment]
@KlausLoeffelmann Here is a screen recording showing me with the errors adding two user controls that renaming messed up and a third user control that wasn't done with renaming that is able to be added with no issues

![devenv_lg0GIR1oJ9](https://user-images.githubusercontent.com/3075685/158232923-1645cc7d-e514-4e5a-a36a-b16444baa9c4.gif)
.

**Comment by ooples** [comment]
@KlausLoeffelmann All the errors you are showing in your screenshots are from running the program itself which won't work since you don't have valid api keys assigned

**Comment by KlausLoeffelmann** [comment]
Don't bother.
I ask for a specific step-by-step, and here is what you wrote:

> Simply add one of the user controls (WatchList.cs or AlpacaOverview.cs) to the FormDashboard.cs design view.

This is what I did, and then I recorded screenshot the issues I saw while running the Designer with an attached Debugger. The error dialog that you see is the Designer's reaction to the Exceptions, that _your_ code throw.

Please isolate your issue in a simple repro. 
The one you provided is to complex, and clearly not stable, since it throws in Design mode.
It is not suitable to isolate a potential Designer issue.

**Comment by KlausLoeffelmann** [comment]
> All the errors you are showing in your screenshots are from running the program itself which won't work since you don't have valid api keys assigned.

False.

I never ran your program. I ran the WinForms Designer and debugged into it. The exceptions you see are caused by your controls _at designtime._

**Comment by ooples** [comment]
@KlausLoeffelmann Yeah I get that but my confusion is the fact that I haven't changed any of the underlying code other than the rename. Case in point I did a test and created a new user control using the exact same code as the watchlist user control that I showed you throw the error and this new user control with the same code can be added to the design view with no issues.

**Comment by KlausLoeffelmann** [comment]
That may be as it is. But you see those exceptions and should address them. We can't.
Maybe some Databinding definitions weren't updated corrected, since they are defined by strings, and got overlooked in the process?

But you need to understand that we cannot debug your components for so many different reasons.
Once you figured out what causes the exceptions, please derive your findings into a minimal Repro which you can then provide, if that assumed bug still exists, and then we can open a new issue.

**Comment by ooples** [comment]
@KlausLoeffelmann Yeah I totally understand and will move on for now unless I can easily replicate the bugs I'm experiencing

**Comment by RussKie** [comment]
Since the designer is running the user code which is present in either the constructor chain (i.e., the constructor of the immediate form or a control, and all base constructors) _AND_ in several overloads (e.g., `OnLoad()` method gets called as well), it is worth considering isolating the code that is required only at runtime from the designer. There are several ways of achieving this, e.g., 
* with `DesignMode` property (❗ beware of its caveats and limitations, some useful information is available in https://github.com/dotnet/winforms/issues/3300),
* if you're targeting .NET 6+ you can use `IsAncestorSiteInDesignMode` property,
* if all else fails, you can write your own design-time check, e.g., https://github.com/gitextensions/gitextensions/pull/9387.
