### ISSUE TITLE
Improve DesignerCategoryAttribute class

### ISSUE THREAD

**Issue by roland5572** [dotnet/winforms#6834]
If you have written a Control class, but you don't want to use **Visual Studio Form Designer** to design the control, you can use the following class.

**DesignerCategoryAttribute** class:
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.designercategoryattribute

Sample Code:
```
    [DesignerCategory("")]
    internal class NewControl : UserControl
    {
    }
```

Scene:

Suppose you are extending some Controls, Sometimes you don't need to change the UI for it, just adjust the default values of some properties and methods/functions of the original class. So you don't need to use the design interface because Visual Studio may create extra files (like NewControl.Designer.cs and NewControl.resx). And when you double-click the file item from panel, Visual Studio will automatically run the Form Designer (**This step often takes a few extra seconds**) and may create the extra files. Sometimes these steps are not necessary.

If you use the DesignerCategoryAttribute, Visual Studio will not create extra files, and you can quickly start writing your code without opening Form Designer.

But at present there is a problem with the DesignerCategory class. When you use it on a class, all the classes **derived** from it will no longer open the **Form Designer**.

Is there a flexible way that the user can autonomously control whether all inherited classes also need to be treated the same way?

eg:
```
    [DesignerCategory("", CurrentOnly = true)]
    internal class NewControl : UserControl
    {
    }
```

You can use the **CurrentOnly** property to decide that the DesignerCategory class is only valid for the current class.
This way it won't be passed into all derived classes.

Without this setting, when you have dozens of classes all derived from this class, you need to reset for each class, which is very time consuming.

Supplement:

Picture 1.
Suppose you just want to write a **pure** class, but when you double click the file item, Visual Studio will create other files.

![001](https://user-images.githubusercontent.com/88176616/158021175-cd6a01f5-a5b4-4666-bab4-52cc716e0135.png)

Picture 2.
If you use DesignerCategory class, all other controls that inherit from this class will also not be able to use Form Designer.

![002](https://user-images.githubusercontent.com/88176616/158021273-809b5878-07c6-41d5-ad06-9d46f97f22af.png)

**Comment by dreddy-work** [comment]
Thank you @roland5572 for bringing this up. Unfortunately, this would require coordination between multiple teams like Runtime, CPS, Winforms and Visual Studio. This is a nice to have but without business justification would fall on a low priority list. We would be happy to look if there is significant change that require this.

**Comment by roland5572** [comment]
@dreddy-work Thank you. If it is difficult to achieve this effect. I guess there is an easier way. Maybe it might be useful in the future.

It just needs a blank Attribute. When Visual Studio find this Attribute, doesn't open the Form Designer.

```
     public class HideFormDesigner : Attribute
     {

     }
```

There is no need to modify the existing system class, it just needs to be recognized by Visual Studio.

```
    [HideFormDesigner]
    internal class NewControl : UserControl
    {
    }
```

**Comment by RussKie** [comment]
This will still require a coordination from multiple teams across several codebases. The attribute will need to be added into .NET runtime (for example, let's imagine .NET 7), then dotnet/project-system will need to be made aware of the attribute. The it'll somehow needs to flow into VS, which runs on .NET Framework 4.7.2... It's a very significant effort which likely won't have a significant impact for the overall .NET community.
