### ISSUE TITLE
MonthCalendar accessible objects are leaking in memory

### ISSUE THREAD

**Issue by ArtemTatarinov** [dotnet/winforms#6852]
* .NET Core Version: 7.0
* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
MonthCalendar accessible objects are left in memory after the MonthCalendar control instance was inspected with accessibility tool (like Accessibility Insights or Inspect) and the form with MonthCalendar is closed, garbage is collected, but accessibility tool is still opened.

Report from WinDbg:
![image](https://user-images.githubusercontent.com/87859299/158599569-4ab1085a-c2b6-4208-ac6f-34b9754b65e8.png)
 
**Expected behavior:**
Amount of the leaked objects should be minimized to the uncleanable static objects only.

**Minimal repro:**
1. Create a parent form with two buttons: one will be opening a child form with the MonthCalendar control and the other will collect the garbage.
2. Press the second button to open the child form with MonthCalendar.
3. Start the Accessibility Insights tools.
4. Run automated checks for the MonthCalendar control using AI.
5. Close the child form.
6. Clear memory with the first button of the parent form.
7. DON'T close the AI tool.
8. Look for MonthCalendar accessible objects left in memory (using WinDbg, or dotMemory, or another suitable tool).

**Comment by Philip-Wang01** [comment]
Verified this issue on .NET 7.0.100-preview.5.22227.7, issue was fixed
![image](https://user-images.githubusercontent.com/86937911/165721599-6749ce9e-f5d4-494f-93e7-e307c4a3da4c.png)
