### ISSUE TITLE
Empty finalizers

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#6858]
* .NET Core Version: _7.0 now_

* Have you experienced this same bug with .NET Framework?: _probably yes_

**Problem description:**

List of empty finalizers through `Dispose(false)` that doing nothing:
~[ResXResourceReader](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs#L194)~ and ~[ResXResourceWriter](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs#L549)~ [We leave it as is](https://github.com/dotnet/winforms/pull/7431#issuecomment-1188739332).
- [x] [ApplicationContext](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Windows/Forms/ApplicationContext.cs#L91) https://github.com/dotnet/winforms/pull/7431
- [x] [DataGridViewBand](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs#L817) https://github.com/dotnet/winforms/pull/6978
- [x] [DataGridViewCell](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs#L1313) https://github.com/dotnet/winforms/pull/6978
- [x] [HtmlShim](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Windows/Forms/HtmlShim.cs#L107) https://github.com/dotnet/winforms/pull/6878
- [x] [HtmlShimManager](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Windows/Forms/HtmlShimManager.cs#L229) https://github.com/dotnet/winforms/pull/6878
- [x] [FeedbackRectangle](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.FeedbackRectangle.cs#L55) https://github.com/dotnet/winforms/pull/6878

**Expected behavior:**
Due that we cannot remove finalizers from an unsealed public type we can remove only `FeedbackRectangle`, `HtmlShimManager`, `HtmlShim`. And for others we can try to do [this](https://github.com/dotnet/winforms/pull/6878#issuecomment-1087197261) workaround...

Stumbled upon this by setting `DataGridView.DataSource` - old rows/columns/cells are not properly disposed (this is another issue  and I have a strong feeling that with `ContextMenuStrip` we will have a memory leak) and ending up in Freachable queue...

**Comment by dreddy-work** [comment]
THanks @kirsan31 for bringing this up. Do you mind pushing a PR for this?

**Comment by kirsan31** [comment]
> Do you mind pushing a PR for this?

Will do...

**Comment by kirsan31** [comment]
@RussKie can you pls reopen this for further tracking?

**Comment by kirsan31** [comment]
I've looked at `ResXResourceWriter` and `ResXResourceReader` and I think we can leave them as is. They are most using in designer and If used by the user, he _must_ call dispose any way.
What do you think?

**Comment by elachlan** [comment]
Related: #7887

CA1821: Remove empty Finalizers
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1821
