### ISSUE TITLE
User and GDI objects memory leak

### ISSUE THREAD

**Issue by Tragen** [dotnet/winforms#6860]
* .NET Core Version:
5.0.406 and 6.0.201

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
User and GDI objects are leaked in certain scenarios.

**Expected behavior:**
The memory should be cleaned up correctly even without Dispose, latest when the GC was running once.

**Minimal repro:**
Create a new project with Windows Forms.
Create a second form and add MenuStrip or ToolStrips. No problems with simple buttons.
If you show the second form from the first form with a button click with
```
Form2 f;
f = new Form2();
f.ShowDialog();
``` 
and you close it, you can see in the Task Manager the User and GDI objects go up every time you show the second window but it doesn't go back to the original value. The more often you load the form and close it, the more objects leak.
GC.Collect(); doesn't work to clean up the memory.
This doesn't happen if you call Dispose explicitly
```
Form2 f;
f = new Form2();
f.ShowDialog();
f.Dispose();
```
or by using using
```
using ( Form2 f2 = new Form2() )
{
    f2.ShowDialog();
}
```

**Comment by dreddy-work** [comment]
Please refer to the remarks from this documentation. https://docs.microsoft.com/dotnet/api/system.windows.forms.form.showdialog?view=windowsdesktop-6.0

>Because a form displayed as a dialog box is hidden instead of closed, you must call the [Dispose](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.dispose?view=windowsdesktop-6.0) method of the form when the form is no longer needed by your application.

**Comment by Tragen** [comment]
Thank you very much. I must have missed this that it only hides the form.
I still thought that when the variable is out of scoped, it gets disposed automatically.
