### ISSUE TITLE
Cannot search in properties

### ISSUE THREAD

**Issue by janseris** [dotnet/winforms#6869]
### Environment

VS 2022 (17.1.1)

### .NET version

.NET 6

### Did this work in a previous version of Visual Studio and/or previous .NET release?

.NET Framework 4.8

### Issue description

search bar in control properties is not present

### Steps to reproduce

open Windows Forms designer, click F4 to show properties, select any designable control, search bar will be visible which allows to quickly find properties by substring
- this is especially needed when using advanced controls with a lot of properties

**Comment by janseris** [comment]
After 4 days of work, the search bar has appeared (once).
![image](https://user-images.githubusercontent.com/64279914/159388063-338d73e3-2ca1-4335-a353-0fefa643e256.png)

**Comment by dreddy-work** [comment]
@janseris , I do not see this working for .NET framework 4.8 projects either. Did you notice the search bar only for the custom controls like DevExpress here?

![image](https://user-images.githubusercontent.com/36968667/161162025-1fdd217d-501e-45d0-8123-bf8b522265f5.png)
