### ISSUE TITLE
Closing an old WinForm affects ToolStrip ImageLists in a new Winform 

### ISSUE THREAD

**Issue by StuAG** [dotnet/winforms#6881]
### .NET version

.Net Core 6.0.200

### Did it work in .NET Framework?

Yes

### Issue description

For our WinForms Application, we have a number of global classes which are used between various forms. One of which is for ToolStrips where we store a global ImageList class, which is then loaded to each ToolStrip that is created on a form. This is to ensure only one ImageList needs to be created and icons are kept common between the ToolStrips we use throughout the application.

However, we have found that when changing forms (by calling .Show() on the new form and .Close() straight after on the old form), it appeared to set the ImageList properties to empty in the ToolStrips on the new form, meaning none of the images would show on the ToolStrip. After debugging and stepping through every part of the code that may have cause the property to set to null, I found that the .Close() call on the old form was setting the ImageList on the ToolStrips to empty.

The forms and the code behind them were not changed at all when converting the project from .Net Framework to .Net Core. This only seems to affect the .Net Core project.

I've created an example project with 2 identical forms, both having a tool strip with a single item and a button to open another form. The button image shows on Form1, and on Form2 when you open that, however the next time you click the button to switch forms, the image is no longer there.

[ImageListExample.zip](https://github.com/dotnet/winforms/files/8317886/ImageListExample.zip)

Not sure why this works on Framework and not Core. I have been able to get around the issue by loading the global ImageList each time rather than setting it at program start, but it's an extra processing step which could potentially lead to (albeit minor) slowdowns.

### Steps to reproduce

- Run the attached project
- Click button1 on Form1, notice the toolstrip at the top of Form1 and Form2 have an image (just a black square)
- Click button1 on Form2, notice the toolstrip no longer has an image displaying

**Comment by RussKie** [comment]
Looks like the behaviour was changed in .NET 5.0 RC1 timeframe in https://github.com/dotnet/winforms/pull/3676 addressing a possible memory leak.




> I have been able to get around the issue by loading the global ImageList each time rather than setting it at program start, but it's an extra processing step which could potentially lead to (albeit minor) slowdowns.

There's another (possibly better) workaround:
```diff
        private void Button1_Click(object? sender, EventArgs e)
        {
            Form newForm = new Form1();

            newForm.Show();
+           toolStrip1.ImageList = null;
            this.Close();
        }
```

I'm a little skeptical we'd meet the servicing bar to have this fixed in .NET 6, but I'll check.

**Comment by StuAG** [comment]
Thanks for looking at this.

That other workaround isn't ideal for our application as it would require setting every ToolStrip on each form to null on form close. For us, it's easier to have the ImageList reloaded when the ToolStrip is initialised (all our ToolStrips inherit a common class so it only needs to be set in one place) rather than setting to null on each form. But it could work better for others that have this issue.

It'd be a shame if it didn't meet the bar, but I suppose it is fairly niche. If someone else does run into it there are workarounds noted here at least.

**Comment by merriemcgaw** [comment]
This may well be worth taking in servicing (thank @RussKie for advocating the servicing). @StuAG would you be willing to test the fix in your application?

**Comment by StuAG** [comment]
@merriemcgaw, thanks for looking at this. I can confirm I would be willing to test this when a fix is available.

**Comment by Amy-Li03** [comment]
Verified this issue with .NET SDK 7.0.100-preview.4.22213.30, issue was fixed, toolstrip has an image displaying when clicking button1 on Form2.

**Comment by MelonWang1** [comment]
Verified in the .NET 7.0 SDK build: 7.0.100-preview.4.22227.3, it is fixed.
![6881](https://user-images.githubusercontent.com/94418985/165691800-e33ff3cc-d071-4c31-a925-9aef2c587a39.gif)
