### ISSUE TITLE
Allow using ApplicationConfiguration when the project is not runnable

### ISSUE THREAD

**Issue by janseris** [dotnet/winforms#6882]
### Is your feature request related to a problem? Please describe

Hello,

today I came across the new feature of WinForms in .NET 6 - ApplicationConfiguration  which is great. It allows configuring the UI of the application directly in project settings.

I have a Windows Forms Application which uses backend with EF Core 6 etc. 
There are multiple layers. 
Due to this, the application should consume IServiceProvider which provides the services, yet, not depend on Data Access Layer.
Dependency from Windows Forms application to Data Access Layer is created when singleton services are configured in the Wndows Forms application.

Because of this, I created a "Launcher" project which initializes the IServiceProvider and then passes it to the Windows Forms application Main method as an argument.
There is an issue when the Windows Forms application is not runnable, the new .NET 6 ApplicationConfiguration object disappears.
![image](https://user-images.githubusercontent.com/64279914/159339936-e505993f-3d92-4ea4-af8c-08b86ec0ac8d.png)

I need to run the WindowsFormsApplication as a class library from the launcher but at the same time, preserve ApplicationConfiguration which allows configuring Windows Forms properties in project settings.

![image](https://user-images.githubusercontent.com/64279914/159340409-ae20cb4e-9050-4695-b5e8-f90353c52a15.png)

Is that possible and if not what would be a workaround?

Note: ApplicationContext is a custom class which needs to be used in UserControls because they don't allow constructor injection when they are wired into a Forms or other UserControls using the designer.
![image](https://user-images.githubusercontent.com/64279914/159340833-b14628d9-825e-4654-870f-8d7ba2d67bef.png)
![image](https://user-images.githubusercontent.com/64279914/159341079-544639bf-fb70-4008-bfd8-9f726dff98e0.png)

This is the proposed architecture and in this architecture, the Windows Forms GUI project is not directly executable because it depends on a IServiceProvider provided by the Launcher.

Diagram with dependencies below:
Note: the API layer contains interfaces for services and the Service layer implement these interfaces.
left: old architecture
right: new architecture which cannot be used 

![winforms launcher](https://user-images.githubusercontent.com/64279914/159340512-d73d0240-d934-46ec-adc1-4f2dedc94025.png)

Thank you

### Describe the solution you'd like and alternatives you've considered

ApplicationConfiguration  can be used in a WinForms project which is not runnable.

### Will this feature affect UI controls?

No

**Comment by RussKie** [comment]
Thank you for the suggestion, but this behaviour is by [design](https://github.com/dotnet/designs/blob/main/accepted/2021/winforms/streamline-application-bootstrap.md#implementation-details):

> The new bootstrap API must only work for Windows applications projects (i.e. OutputType = WinExe and [OutputType = Exe](https://docs.microsoft.com/dotnet/core/compatibility/sdk/5.0/automatically-infer-winexe-output-type)) because:
> * These projects have an entry point, where an app is initialised; and
> * they also specify an application manifest, if there is one.

`ApplicationConfiguration.Initialize()` can only be called at the very start of an app, which is generally the `Main()` method. If the bootstrap code were to be located in a library project, there's no guarantee that bootstrap would be executed at the start of an app, and as a result it either won't work or would crash an app. Also the source-generated API have compile-time perf costs, i.e. they can affect the build process. 
In all these cases developers would likely comes here and complain, which isn't a great outcome for anyone.

If you Launcher project is a Windows Forms app, then you should be able call `ApplicationConfiguration.Initialize()` from there, and the default font would flow through to your library project.
If not - there are few alternatives, including converting the Launcher project to a Windows Forms app, or not using `ApplicationConfiguration` API.

Hope this makes sense.
