### ISSUE TITLE
TextBox accessible objects are leaking in memory

### ISSUE THREAD

**Issue by ArtemTatarinov** [dotnet/winforms#6885]
### .NET version

7.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

`TextBox` accessible objects are left in memory after the `TextBox` control instance was inspected with accessibility tool (like `Accessibility Insights` or `Inspect`) and the form with `TextBox` is closed, garbage is collected, but accessibility tool is still opened.

Report from WinDbg:
![image](https://user-images.githubusercontent.com/87859299/159481920-cf26ae86-0a41-4d7c-a26f-5cb9d91de3e1.png)

**Expected behavior:**
Amount of the leaked objects should be minimized to the uncleanable static objects only.

### Steps to reproduce

1. Create a parent form with two buttons: one will be opening a child form with the `TextBox` control and the other will collect the garbage.
2. Press the second button to open the child form with `TextBox`.
3. Start the `Accessibility Insights` tools.
4. Run automated checks for the `TextBox` control using AI.
5. Close the child form.
6. Clear memory with the first button of the parent form.
7. DON'T close the AI tool.
8. Look for `TextBox` accessible objects left in memory (using `WinDbg`, or `dotMemory`, or another suitable tool).

**Comment by John-Qiao** [comment]
Verified this issue on .NET 7.0.100-preview.5.22256.2, issue was fixed as below screenshot:

![TestResult](https://user-images.githubusercontent.com/45864985/167247946-43080328-0583-4173-87f6-dab5aa665cd1.png)
