### ISSUE TITLE
NET 6, Windows.Forms ColorEditor, missing resources

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#6915]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-6-WindowsForms-ColorEditor-missin/1700906)._

---
Hi, the screenshot should explain everything. 
A missing resource in Windows.Forms.Design.dll. 
The problem is easy to reproduce, for example: 
In a PropertyGrid Control, Color Property, DropDown, right click on a Custom Color Field what should show the Colorpicker.
Regards, 
Christian Ohle

![image.png](https://aka.ms/dc/image?name=B782a152d7d6b41b1aa7fb9de7f4cb8bd637836471271113195_20220323-164526-image.png&tid=782a152d7d6b41b1aa7fb9de7f4cb8bd637836471271113195)

---
#### Feedback Bot on 3/24/2022, 02:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Olina Zhang [MSFT] on 3/24/2022, 06:08 PM: 

<p>Thanks for your feedback!</p>
<p>Unfortunately we cannot reproduce this issue on our side, in order to investigate this further, could you please provide detail reproduce steps or a minimum sample app how to repro it?<br>
Here is we are trying:</p>
<ol>
<li>Create a Winforms .Net 6.0 application</li>
<li>Add a PropertyGrid control to form designer, bind SelectedObject property to Form1</li>
<li>Build and run application</li>
<li>Find backColor property in PropertyGrid, click dropdown, focus on Custom color tab, pick up any color</li>
</ol>
<p>Result: All work well, please see following gif:<br>
<img src="https://aka.ms/dc/image?name=B74d4f99c2fd643c4894a9911441f0fbf637837137324271049_CustomColor.gif&amp;tid=74d4f99c2fd643c4894a9911441f0fbf637837137324271049" alt="CustomColor.gif"></p>

#### Christian Ohle on 3/24/2022, 11:01 PM: 

<p>Hi, it happens on right click on one of the the custom colors fields in the “user defined colors” tab.<br>
I hope it helps</p>

#### Christian Ohle on 3/24/2022, 11:15 PM: 

<p>VS screen record from the page seems not to work for me. Therefore again as screenshots:</p>
<p><img src="https://aka.ms/dc/image?name=B3a032f1729af49caa39b5908dc63d395637837313621500187_20220324-160921-image.png&amp;tid=3a032f1729af49caa39b5908dc63d395637837313621500187" alt="image.png"></p>
<p><img src="https://aka.ms/dc/image?name=B8c75d28dec6d4562903e7fc5bd7c14b3637837314033081585_20220324-161003-image.png&amp;tid=8c75d28dec6d4562903e7fc5bd7c14b3637837314033081585" alt="image.png"></p>
<p><img src="https://aka.ms/dc/image?name=Bfcaf64004ecb4c48ae2feae507b1404f637837315411226020_20220324-161220-image.png&amp;tid=fcaf64004ecb4c48ae2feae507b1404f637837315411226020" alt="image.png"></p>
<p><img src="https://aka.ms/dc/image?name=Bb3eca83e44dd417ebc1960c3225dcce4637837315926363959_20220324-161312-image.png&amp;tid=b3eca83e44dd417ebc1960c3225dcce4637837315926363959" alt="image.png"></p>

#### Olina Zhang [MSFT] on 3/28/2022, 11:33 AM: 

<p>Thanks for your update, I can repro your issue now.</p>

---
### Original Solutions
(no solutions)

**Comment by Olina-Zhang** [comment]
**Repro steps:**
1. Create a Winforms .Net 6.0/7.0 applciation
2. Add a propertyGrid and a button to form designer
3. Bind this button to propertyGrid's selectedObject property
[WinFormsApp13.zip](https://github.com/dotnet/winforms/files/8359487/WinFormsApp13.zip)
4. Build and run application
5. Focus on BackColor property in PropertyGrid, and expand its dropdownlist, goes to Custom tab, and right-click on any white color at the bottom

**MoreInfo:**
1. This issue cannot repro in color dialog in .Net 6.0/7.0
2. This issue cannot repro in .Net framework 4.8

**Actual Result:** an error dialog pops up:
![image](https://user-images.githubusercontent.com/26474449/160323335-db7c0850-607b-4b92-9a2d-fa53801d046f.png)

**Expected result:** Define color dialog pops up, following is the behavior in framework app
![image](https://user-images.githubusercontent.com/26474449/160323646-21b348b5-b53e-4dff-bbd3-c855d72ddb4e.png)

**Comment by RussKie** [comment]
> **MoreInfo:**
> 
> 1. This issue cannot repro in color dialog in .Net 6.0/7.0

I suppose you meant "it **can** repro".

I've looked at the code, and it doesn't look at ever worked since we ported this code to .NET Core.
![image](https://user-images.githubusercontent.com/4403806/160537257-da1da428-6187-4ea2-a126-45e476ace3a6.png)

**Comment by Olina-Zhang** [comment]
> I suppose you meant "it **can** repro".

In color dialog, there isn't that error dialog popping up, has the same behavior of .Net framework, see it as below:
![ColorDialog](https://user-images.githubusercontent.com/26474449/160731934-968918cd-9deb-41d6-a94a-ce35c0a130e2.gif)

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net 7.0 SDK build: 7.0.100-preview.4.22206.9, it is fixed.
![image](https://user-images.githubusercontent.com/26474449/162170648-bce345ed-02f5-4d97-8b34-6e369b41c4d9.png)

**Comment by Cassie-Li01** [comment]
Verified this issue in the latest .Net 7.0 SDK build: 7.0.100-preview.4.22213.30, it is fixed.
![image](https://user-images.githubusercontent.com/96758262/163299135-40672be7-eac5-4ba7-aa9d-fd2d2aed4737.png)

**Comment by Philip-Wang01** [comment]
Verified this issue in the .NET 7.0 SDK build: 7.0.100-preview.4.22227.3, it is fixed.
![image](https://user-images.githubusercontent.com/86937911/165693700-5d943151-6eeb-4e47-9978-e0b4be8e852f.png)
