### ISSUE TITLE
ToolboxSnapDragDropEventArgs is not implemented.

### ISSUE THREAD

**Issue by generatorXu** [dotnet/winforms#6919]
### .NET version

6.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

no

### Issue description

While draging a toolbox item from an IToolboxService (implemented by myself) onto a custom control at design time, the corresponding designer's OnDragDrop() won't be hit. and an exception: NotImplementedException was thrown by the  constructor() of class ToolboxSnapDragDropEventArgs.

### Steps to reproduce

1、create an instance of DesignSurface.
2、add a custom IToolboxService impl.
3、add a custom control to IToolboxService.
4、drag the custom control onto the DesignFrame.
5、A NotImplementedException was thrown within Debug window.

**Comment by RussKie** [comment]
@generatorXu could you please clarify - is this a runtime scenario (i.e.. while you run your app) or a design time scenario (i.e., while you are designing your control in VS)? Than you.

**Comment by generatorXu** [comment]
Okay，i’ll send you a sample app this weekend.

发自我的iPhone

在 2022年4月1日，06:33，Devendar Reddy Adulla ***@***.***> 写道：

﻿

Thanks @generatorXu<https://github.com/generatorXu> for reporting this. can you help sharing a sample app here for us/community to repro?

**Comment by generatorXu** [comment]
Attachment is the sample app, just unzip and run the exe, hit File(New) menu, drag the SampleControl from the left ‘Toolbox’ and drop in the center ‘RootForm’, then you can see Exceptions occurred in the VS diagnostic window.

发自我的iPhone

在 2022年4月1日，09:06，xu chong ***@***.***> 写道：

﻿a design time scenario

发自我的iPhone

在 2022年4月1日，08:29，Igor Velikorossov ***@***.***> 写道：

a design time scenario

**Comment by willibrandon** [comment]
The `ToolboxSnapDragDropEventArgs` constructor throws `NotImplementedException`.

https://github.com/dotnet/winforms/blob/8dfd08de957e7e2b8f697c816032285fdf1dcf0f/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolboxSnapDragDropEventArgs.cs#L40

Which could be causing upstream calls to `base.OnDragDrop()` to not get executed, as described in the issue description.

**Comment by generatorXu** [comment]
@willibrandon, yes, you got it!

**Comment by generatorXu** [comment]
Yes. you got it.

发自我的iPhone

在 2022年4月14日，01:31，Brandon Williams ***@***.***> 写道：

﻿

The ToolboxSnapDragDropEventArgs constructor throws NotImplementedException.

https://github.com/dotnet/winforms/blob/8dfd08de957e7e2b8f697c816032285fdf1dcf0f/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolboxSnapDragDropEventArgs.cs#L40

Which could be causing upstream calls to base.OnDragDrop() to not get executed, as described in the issue description.

**Comment by John-Qiao** [comment]
@generatorXu have you attached your sample project here? I didn't find it, please check.

**Comment by generatorXu** [comment]
Hi @John-Qiao,

 sample is here: 
[DesignerSample.zip](https://github.com/dotnet/winforms/files/8651342/DesignerSample.zip)

**Comment by John-Qiao** [comment]
@generatorXu I tried your sample project on my side, but it seems there's no exception occurs in the VS diagnostic window. Please check the below gif file, and please let me know if I missed something.

![TestResult](https://user-images.githubusercontent.com/45864985/167531763-77a03108-6a55-45ae-b9bf-1a60cf3b4281.gif)

**Comment by generatorXu** [comment]
Hi @John-Qiao , in Visual Studio, please uncheck "Tools -> Options -> Debugging -> Enable Just My code" options first, then re-run my project.

**Comment by generatorXu** [comment]
and modify DesignerSample.csproject according to the screen shot below:
![2022-05-10-12-05-22](https://user-images.githubusercontent.com/23371488/167540384-c5e476aa-bf9c-4d80-b5f6-9e9eb1be991a.gif)

**Comment by John-Qiao** [comment]
@generatorXu thanks for your info, I can repro this exception using your sample project now.

**Comment by RussKie** [comment]
@generatorXu thank you for the sample. Could you please provide more information on your business scenario and on how this issue affects it, so we can present it to the Servicing Bar for a consideration to taking the fix into the 6.0.x branch. Thanks

**Comment by generatorXu** [comment]
@RussKie , 

I'm a senior developer. My working company is a software vender which provide low-code modeling/developing tools for large scale enterprises. 

The 'drag & drop from toolbox' functionality is making a key role in our design functionality of the UI modeling tool. The UI modeling tool is similar to  Microsoft new WinForms Designer, but it doesn't generate codes, it produces xml document instead. The xml document describes how the UI is composed (using our design-time winforms control-set from the toolbox). Finally our server side run-time will read the xml document then render the actual page (using html widgets) to end user. 

This issue was found during our effort of upgrading from dot net Framework to dot net Core, and blocked our development for several weeks.

Above is our business scenario. Hope that helps.

**Comment by RussKie** [comment]
Thank you, it does.

**Comment by John-Qiao** [comment]
Verified with 7.0.100-preview.6.22306.1 from main branch, this issue has been fixed that SampleControl can drag and drop to form and no exception occurs now.
![TestResult3](https://user-images.githubusercontent.com/45864985/172141177-271ac244-0586-414f-92d6-9770d454a3a3.png)

**Comment by generatorXu** [comment]
That's great, thank you @RussKie!  
When will be the release date of 7.0.100 ? 
Can't wait any more.

**Comment by RussKie** [comment]
.NET 7 GA will be released in Nov 2022, see https://dotnet.microsoft.com/platform/support/policy/dotnet-core. .NET 7 Preview 6 will be released in July 2022.

**Comment by Amy-Li03** [comment]
Verified this issue on .NET 7.0 test pass build: .NET 7.0.100-preview.5.22305.3, it was fixed.

**Comment by John-Qiao** [comment]
Verified this issue on .NET 6.0 test pass build: .NET 6.0.302-servicing.22323.16, it was fixed.
