### ISSUE TITLE
`GetDocFiles` may run more than once

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#6928]
`GetDocFiles` may run more than once:
https://github.com/dotnet/winforms/blob/725161305d1c0fe9a88914ae81466dc79dad3f38/eng/packageContent.targets#L23

This may cause build failures due to a race condition, e.g., [this build](https://dev.azure.com/dnceng/public/_build/results?buildId=1679927&view=results):
```
dotnet-install: Installation finished
  Determining projects to restore...
  Determining projects to restore...
  Determining projects to restore...
  Restored D:\a\_work\1\s\src\System.Windows.Forms\tests\UnitTests\WindowsFormsTests\WindowsFormsTests.proj (in 7.91 sec).
  Restored D:\a\_work\1\s\src\System.Windows.Forms\tests\InteropTests\NativeTests\NativeTests.proj (in 7.65 sec).
D:\a\_work\1\s\eng\packageContent.targets(55,5): error MSB3026: Could not copy "D:\a\_work\1\s\.packages\microsoft.private.intellisense\7.0.0-preview-20220316.2\IntellisenseFiles\windowsdesktop\1033\Accessibility.xml" to "D:\a\_work\1\s\artifacts\bin\docs\Accessibility.xml". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\a\_work\1\s\artifacts\bin\docs\Accessibility.xml' because it is being used by another process.  [D:\a\_work\1\s\src\System.Windows.Forms\tests\InteropTests\NativeTests\NativeTests.proj]
##[error]eng\packageContent.targets(55,5): error MSB3026: (NETCORE_ENGINEERING_TELEMETRY=Restore) Could not copy "D:\a\_work\1\s\.packages\microsoft.private.intellisense\7.0.0-preview-20220316.2\IntellisenseFiles\windowsdesktop\1033\Accessibility.xml" to "D:\a\_work\1\s\artifacts\bin\docs\Accessibility.xml". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\a\_work\1\s\artifacts\bin\docs\Accessibility.xml' because it is being used by another process. 
D:\a\_work\1\s\eng\packageContent.targets(55,5): error MSB3026: Could not copy "D:\a\_work\1\s\.packages\microsoft.private.intellisense\7.0.0-preview-20220316.2\IntellisenseFiles\windowsdesktop\1033\Accessibility.xml" to "D:\a\_work\1\s\artifacts\bin\docs\Accessibility.xml". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\a\_work\1\s\artifacts\bin\docs\Accessibility.xml' because it is being used by another process.  [D:\a\_work\1\s\src\System.Windows.Forms\tests\InteropTests\NativeTests\NativeTests.proj]
##[error]eng\packageContent.targets(55,5): error MSB3026: (NETCORE_ENGINEERING_TELEMETRY=Restore) Could not copy "D:\a\_work\1\s\.packages\microsoft.private.intellisense\7.0.0-preview-20220316.2\IntellisenseFiles\windowsdesktop\1033\Accessibility.xml" to "D:\a\_work\1\s\artifacts\bin\docs\Accessibility.xml". Beginning retry 1 in 1000ms. The process cannot access the file 'D:\a\_work\1\s\artifacts\bin\docs\Accessibility.xml' because it is being used by another process. 
```

[BuildSrc-x86.zip](https://github.com/dotnet/winforms/files/8370456/BuildSrc-x86.zip)

/cc: @singhashish-wpf for visibility

**Comment by RussKie** [comment]
@KirillOsenkov I wonder if you could help me here. Is there some magic switch to prevent re-running a target?

**Comment by kant2002** [comment]
This target is in all projects, and thus they are executed for all projects. Is pushing Inelisense related steps to separate project is proper solution, or maybe create special parameter which will trigger processing of only Intellisense files.

```
dotnet build WinForms.sln /t:GenerateIntellisenseLayout
dotnet build WinForms.sln
``` 

OR maybe create fake `doclayout.proj` (or find appropriate existing one) and execute Intellisense related targets there?

**Comment by RussKie** [comment]
I need to think it through once I get some head space. This target was originally copied from dotnet/runtime, perhaps it's invoked somewhat differently in their build.

**Comment by RussKie** [comment]
Few quick thoughts while I'm at it. 

`CopyIntellisenseXmlsToTargetRefPath` is run for each individual project:
https://github.com/dotnet/winforms/blob/725161305d1c0fe9a88914ae81466dc79dad3f38/eng/packageContent.targets#L125-L130

Maybe it needs to be augmented to copy the intellisense files from the intellisense bundle to the target ref folder. Or, perhaps `GetDocFiles` needs to be rewritten to be called by each individual project to copy only relevant files.

**Comment by kant2002** [comment]
Can you explain why all this machinery needed and what purpose it's serves?

**Comment by RussKie** [comment]
These targets ensure the intellisense definitions (which come from a separate system related to the docs in Microsoft.Private.Intellisense.nupkg) are packaged in when we run `.\build -pack` alongside the respective assemblies, and these artifacts then get packages into the Windows Desktop workload, which users install on their workstations.

**Comment by kant2002** [comment]
How can I test that these thinks packaged properly? Check that list of files inside individual `nupkg` same as after changes (If I manage to make them)?

So I run `.\build -pack` and check for content of nupkg right.

**Comment by RussKie** [comment]
Yes, run `.\build -pack` will produce two nupkg under .\artifacts\\packages\\<Configuration\>\\NonShipping folder. The package for the Windows Desktop workload is Microsoft.Private.Winforms.\<version>.nupkg. The intellisense files are located in the ref folder:
![image](https://user-images.githubusercontent.com/4403806/160719563-0e776015-7cbf-4981-8a75-cfe0159fcdad.png)
These files must be the same as in Microsoft.Private.Intellisense.nupkg.
