### ISSUE TITLE
An incurable bug: Failed to parse method 'InitializeComponent'. 

### ISSUE THREAD

**Issue by kelicto** [dotnet/winforms#6948]
### Environment

![image](https://user-images.githubusercontent.com/23723575/161213470-68e17567-2184-4858-b01b-e48c4b11083d.png)

### .NET version

ALL

### Issue description

An incurable bug: Failed to parse method 'InitializeComponent'. The parser reported the following error 'Invalid symbol kind: NamedType'. Please look in the Task List for potential errors. 

### Steps to reproduce
I don't know.

**Comment by kelicto** [comment]
This is an old problem in history. Can we provide a more friendly and thorough solution?

**Comment by kelicto** [comment]
As long as it happens, no matter where you roll back the code, it's useless. It seems that visual studio is stupid to follow.

**Comment by kelicto** [comment]
I want to improve my understanding of custom controls. I'm still at a loss when I encounter problems. I hope someone can pay attention to this project. Thanks!

References:
https://stackoverflow.com/questions/71705283/about-custom-control-usage
https://github.com/kelicto/KeLi.TreeListViewKit

**Comment by dreddy-work** [comment]
Thanks @kelicto for reporting this. Explicit modification of designer generated code may result in such errors. We would be able to investigate further if you can provide repro sample for this.

**Comment by kelicto** [comment]
I will resume this frustrating project that has been deleted from GitHub immediately. If the official team has the energy, I hope you can improve it again (although I know it's unlikely... That's why I deleted the use of commercial components).

**Comment by RussKie** [comment]
Closing to due to age.
