### ISSUE TITLE
Winforms runtime has stopped working when calling control's dragdrop event

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#6952]
### .NET version

.Net 7.0.100-preview.4.22201.11

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works well with previous .Net 7.0 SDK build: 7.0.100-**preview.3**.22153.22, 7.0.100-**preview.4**.22173.7

### Issue description

Winforms runtime has stopped working when calling control's dragdrop event, see following gif:

![7 0_Issue](https://user-images.githubusercontent.com/26474449/161372761-c5c7eb4a-0ba9-44eb-9942-9b8e97f03030.gif)

### Steps to reproduce

1. Use attached sample application:
[WinFormsApp30.zip](https://github.com/dotnet/winforms/files/8402059/WinFormsApp30.zip)
2. Build and run application
3. Drag and drop item from the left listBox to the right listBox

**Comment by RussKie** [comment]
@Olina-Zhang @John-Qiao it appears this issue is caused by your repro - it references cursor files, which don't exist:
![image](https://user-images.githubusercontent.com/4403806/161474032-4c85d530-b9ab-4b72-80d0-2364eaf82be8.png)

The sample crashes if you target net6.0 as well.

**Comment by Olina-Zhang** [comment]
@RussKie  verified that sample cannot repro in .Net 6.0, previous .Net 7.0.100-preview.3.22153.22, 7.0.100-preview.4.22173.7 builds, and it was found our automation cases, I get a manual repro from MSDN about using dragdrop event. This issue still repro in the latest .Net 7.0 build after commented those .cur files.

**Comment by RussKie** [comment]
> This issue still repro in the latest .Net 7.0 build after commented those .cur files.

Thank you. I can now repro the issue.

@kant2002 this regression is introduced by https://github.com/dotnet/winforms/pull/6746.

**Comment by kant2002** [comment]
Not sure what's going on.
https://github.com/dotnet/winforms/blob/b4d21a581c6fb8c222423f7d225e6dc355cc4838/src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.DoDragDrop.cs#L12-L27

Here I use both built-in COM and ComWrappers in same Interop call.

I change locally to 
```csharp
[DllImport(Libraries.Ole32, ExactSpelling = true)]
private static extern HRESULT DoDragDrop(
    IntPtr pDataObj,
    IntPtr pDropSource,
    DROPEFFECT dwOKEffects,
    out DROPEFFECT pdwEffect);

public static HRESULT DoDragDrop(
    IDataObject pDataObj,
    IDropSource pDropSource,
    DROPEFFECT dwOKEffects,
    out DROPEFFECT pdwEffect)
{
    var dropSourcePtr = WinFormsComWrappers.Instance.GetOrCreateComInterfaceForObject(pDropSource, CreateComInterfaceFlags.None);
    var dataObjectPtr = Marshal.GetIUnknownForObject(pDataObj);
    return DoDragDrop(dataObjectPtr, dropSourcePtr, dwOKEffects, out pdwEffect); // ExecutionEngineException
}
```

And I start receiving `ExecutionEngineException`. There nothing special about this code from my understanding.

**Comment by Olina-Zhang** [comment]
Verified in the latest .Net 7.0 SDK build: 7.0.100-preview.5.22220.23, it is fixed.
![GH6952_Fixed](https://user-images.githubusercontent.com/26474449/164370941-39cc6f66-80bf-4a77-a00f-a3c77cf5d27f.gif)

**Comment by Ashley-Li** [comment]
Verified in the .Net 7.0 SDK build: 7.0.100-preview.4.22222.1, it is fixed.
![6952_issue_verify](https://user-images.githubusercontent.com/56664234/165011048-89c74dff-0ff0-436b-9fa5-942edcab94f1.gif)
