### ISSUE TITLE
Potential memory leak in HtmlElementShim

### ISSUE THREAD

**Issue by kant2002** [dotnet/winforms#6963]
### .NET version

7.0 and earlier

### Did it work in .NET Framework?

No

### Issue description

Look at the code
https://github.com/dotnet/winforms/blob/8bbc3f2f4f2270f62ddf1cca36a0870b36017fa8/src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HtmlElementShim.cs#L101-L111

From what I see some cookies abandoned after they are attached. Does this indicate memory leak? Shouldn't this class has list of cookies instead of just single ConnectionPointCookie?

### Steps to reproduce

Stare at the code until question arise in your heart.

**Comment by RussKie** [comment]
> Stare at the code until question arise in your heart.

😆 


I had a cursory look, and `ConnectionPointCookie` doesn't appear to have been designed as "disposable". Instead it expects to be GC'ed:
https://github.com/dotnet/winforms/blob/6cc092ccf4eedcee415d8779a52bcc061846f7ca/src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ConnectionPointCookie.cs#L137-L147

With that, if you force a GC you should see those abandoned cookies eaten by the GC "cookie eater" :)

**Comment by kant2002** [comment]
How I see code working
1. `HtmlElementShim.ConnectToEvents()` create around 20 `ConnectionPointCookie`s. 
2. Each `ConnectionPointCookie` calls `IConnectionPoint.Advise` allocate connection to the events.
3. At the end of the method just one `ConnectionPointCookie` referenced by `HtmlElementShim`. Last one.
4. Eventually first 19 connection point cookies get's garbage collected. 
5. During each garbage collection called `IConnectionPoint.Unadvise`
6. So after that happens, we have just one `ConnectionPointCookie` which advised to only last one event https://github.com/dotnet/winforms/blob/8bbc3f2f4f2270f62ddf1cca36a0870b36017fa8/src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HtmlElementShim.cs#L46

What am I missing?

**Comment by RussKie** [comment]
You probably haven't missed anything, more like the original developer completely missed it. 
That said, the likelihood of developers using the `WebBrowser` control is diminishing with every passing day. IIRC it's based on IE7 engine, which is almost universally unusable for general web browsing these days. [WebView2](https://docs.microsoft.com/microsoft-edge/webview2/) is a modern replacement for the web browser control.

**Comment by dreddy-work** [comment]
associating it with #6964
