### ISSUE TITLE
String resource containing only whitespace characters are loaded as blank strings

### ISSUE THREAD

**Issue by TheLeftExit** [dotnet/winforms#6977]
### .NET version

Replicated on .NET Core 3 and all later versions.

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

I did not try this with versions prior to .NET Core 3.

### Issue description

If a localized property's value is set to a string that only contains whitespace characters, **ComponentResourceManager** methods such as **ApplyResources** or **GetString** retrieve it as a blank string. This is a breaking change for .NET Framework applications where this is not the case.

I could not find this change documented anywhere, or any issues related to it.

The XML generated for the property is the same in both .NET FX and .NET Core/5+:
```xml
<data name="label1.Text" xml:space="preserve">
  <value>  </value>
</data>
```

### Steps to reproduce

I attached a solution containing two identical forms in .NET Framework 4.8 and .NET 6.
[T1080450.zip](https://github.com/dotnet/winforms/files/8425886/T1080450.zip)

To replicate:
 - Create a new project using the Windows Forms App template.
 - Set the main form's **Localizable** property to **true**.
 - Add a label and set its **Text** property to ` ` (a string with a single whitespace character).
 - Debug the project and check the value of this property after it is set in the **InitializeComponent** method.

**Comment by kant2002** [comment]
I believe this is issue for https://github.com/dotnet/runtime

Tests which should be extended located here https://github.com/dotnet/runtime/blob/da5888aa4d7f8cac2519d5d35d7d8f59385fc6e8/src/libraries/System.ComponentModel.TypeConverter/tests/ComponentResourceManagerTests.cs

**Comment by kant2002** [comment]
Yeah. It’s quite possible that is an issue with how `.resx` files compiled to `.resources` Like stated here https://github.com/dotnet/msbuild/issues/7074#issuecomment-977164313

**Comment by Philip-Wang01** [comment]
@dreddy-work  We try to create resource file manually and add a property there on following without localization of the Form, this issue still repro. Please see the pictures below and Incidental project:

![image](https://user-images.githubusercontent.com/86937911/162404473-e5216011-ddce-4519-9e8a-6689b4b1f084.png)
[WinFormsApp12.zip](https://github.com/dotnet/winforms/files/8450431/WinFormsApp12.zip)

**Comment by kant2002** [comment]
`WinFormsApp12\obj\Debug\net6.0-windows\WinFormsApp12.Resource1.resources` does have `label1.Text` empty.

**Comment by TheLeftExit** [comment]
I guess that's a wrap. Thanks @kant2002!
