### ISSUE TITLE
ContextMenuStrip ToolTip appear behind menu on items with dropdown elements

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#6987]
### .NET version

All up to current 6.0.

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No.

### Issue description

`ContextMenuStrip` item with dropdown elements + ToolTip (`ToolTipText`) will display tip behind itself. So tip will be not visible (not fully visible). Video:

https://user-images.githubusercontent.com/17767561/162386114-90fca9d5-8cf4-4f82-a18a-808e4c639ca9.mp4

### Steps to reproduce

[MenuTip.zip](https://github.com/dotnet/winforms/files/8449594/MenuTip.zip)

**Comment by dreddy-work** [comment]
Thanks @kirsan31 for reporting this. Do you have a fix in mind? If you do, we can help with rest of the process. Otherwise, It's going to be low priority for the team since it is not a regression.

**Comment by kirsan31** [comment]
> Thanks @kirsan31 for reporting this. Do you have a fix in mind? If you do, we can help with rest of the process.

No, I haven't even looked yet. But I'll give it a try if I have time...

**Comment by kirsan31** [comment]
The problem happens due to the fact that we first show the tooltip, and then show the dropdown, which will overlap the tooltip.

**Comment by MandiMan** [comment]
Verified with 7.0.100-rc.1.22371.5 from main branch, this issue has been fixed that the tips are visible. Gif as below:
![issue6987](https://user-images.githubusercontent.com/108860782/180392425-ca8e9e6a-8d7a-4a19-ab00-302938be6f33.gif)

**Comment by MandiMan** [comment]
Verified on latest .NET 7 build .NET 7.0.100-rc.1.22378.6, this issue has been fixed that the tips are visible. Gif as below:
![issue6987](https://user-images.githubusercontent.com/108860782/181697253-9287f969-8b32-4eb9-8469-87cc8abe296e.gif)
