### ISSUE TITLE
ListView Item: Icon picture quality is too low

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#7021]
### Environment

Visual Studio: 17.1.2

### .NET version

ALL

### Did this work in a previous version of Visual Studio and/or previous .NET release?

NO

### Issue description

![image](https://user-images.githubusercontent.com/23723575/163516718-b772fdcc-f636-4d79-8871-1157b59c3ea6.png)

### Steps to reproduce

Nothing

### Diagnostics

```text
Nothing
```

**Comment by dreddy-work** [comment]
Thank you for reporting this @kelicto . Issues are expected to have a simple sample application or animation of the scenario describing the issue as mentioned in the issue template.

**Comment by dreddy-work** [comment]
@kelicto it is always recommended to provide as much details as possible to get better attention to the problem. A straight forward repro for you may not be the same for others. for ex:   you won't get low picture quality if your monitor is running at 100% DPI settings or you may always get low picture quality( even after you fix this issue ) if you are running application in DpiUnaware mode and your monitor is at more then 100% DPI.  It is important to know the customer scenario/environment and business impact to prioritize the issue. None of these are clear from this issue.

**Comment by kelicto** [comment]
I won't create such problems and submit them to the official team for solution. I don't set up DPI amplification.

**Comment by Ashley-Li** [comment]
@kelicto The ImageList control added to the Form designer by default has ColorDepth=Depth8Bit, when you change the ImageSize of the ImageList control, please try to modify the ColorDepth to Depth32Bit and observe the clarity of the image again.

**Comment by kelicto** [comment]
Thinks. The default should be to use the bitmap depth of the default image, and setting it through properties is not a good practice. Although it can solve the problem, this increases the learning cost and not everyone is aware of it.

**Comment by kelicto** [comment]
Sorry. I don't see the FEATURE tag.

**Comment by MelonWang1** [comment]
Verified this issue on .NET SDK latest build: 8.0.100-alpha.1.23068.16, issue was fixed that the default ColorDepth to Depth32Bit.
![7021](https://user-images.githubusercontent.com/94418985/213388146-22c7529d-4461-4e81-8dbc-580162dd1651.png)

**Comment by Cassie-Li01** [comment]
Verified on 8.0 TP version .NET 8.0.100-preview.1.23105.3, issue is fixed. Screenshot same as above.

**Comment by Cassie-Li01** [comment]
Verified with .NET 8 Preview 1 TP build: .NET 8.0.100-preview.1.23108.10, issue is fixed. Screenshot as above
