### ISSUE TITLE
revert https://github.com/dotnet/winforms/pull/7024 when the NUGET warning is fixed

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#7025]
Revert  https://github.com/dotnet/winforms/pull/7024  when https://github.com/dotnet/sdk/issues/24747 is fixed.

### Issue description

NU1505 was disabled because it was causing the following output in the VS:
```
Warning	NU1505	Duplicate 'PackageDownload' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageDownload' items are: 

Microsoft.NETCore.App.Host.win-x64 [7.0.0-preview.4.22214.7], 
Microsoft.NETCore.App.Host.win-x64 [7.0.0-preview.4.22214.7],
Microsoft.NETCore.App.Host.win-x64 [7.0.0-preview.4.22214.7],
Microsoft.NETCore.App.Host.win-x64 [7.0.0-preview.4.22214.7].

AccessibilityTests	D:\winforms\src\System.Windows.Forms\tests\AccessibilityTests\AccessibilityTests.csproj
```

This warning was temporarily disabled in https://github.com/dotnet/winforms/pull/7024, and should be re-enabled when the but is fixed.

**Comment by dreddy-work** [comment]
@Tanya-Solyanik , linked bug is closed. Can you push PR reverting the change?

**Comment by Tanya-Solyanik** [comment]
This change did not make it into our repo yet
