### ISSUE TITLE
TreeView.Sorted Property has Attribute [EditorBrowsable(EditorBrowsableState.Never)]

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#7027]
### .NET version

6.0 / 4.8

### Did it work in .NET Framework?

No

### Issue description

If you have a TreeView control, and you set TreeView.TreeViewNodeSorter = new TreeNodeComparer().
Then .net will set TreeView.Sorted=true.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.treeview.treeviewnodesorter

But if you set  TreeView.TreeViewNodeSorter = null, Then .net will not set TreeView.Sorted=false. This means .net **will still** sort all nodes.

So if you have set  TreeView.TreeViewNodeSorter = new TreeNodeComparer(), you may need to call two steps:
1. Set  TreeView.TreeViewNodeSorter = null
2. Set TreeView.Sorted=false.

Then you can cancel the automatic sorting function of TreeView.

But TreeView.Sorted Property has Attribute [EditorBrowsable(EditorBrowsableState.Never)], **So you may not find** this property in a text editor.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.treeview.sorted

### Steps to reproduce

Full Test .net code: .net 6.0 with Visual studio 2022

```
using System.Collections;

namespace TreeViewNodeSorterTest
{
    internal static class Program
    {
        [STAThread]
        static void Main()
        {
            ApplicationConfiguration.Initialize();
            Test();
        }

        private class TreeNodeComparer : IComparer
        {
            public int Compare(object x, object y)
            {
                throw new NotImplementedException();
            }
        }

        private static void Test()
        {
            TreeView view = new TreeView();

            MessageBox.Show("Sorted: " + view.Sorted);

            view.TreeViewNodeSorter = new TreeNodeComparer();

            MessageBox.Show("Sorted: " + view.Sorted);

            view.TreeViewNodeSorter = null;

            MessageBox.Show("Sorted: " + view.Sorted);
        }
    }
}
```

**Comment by dreddy-work** [comment]
@roland5572 Thanks for reporting this!

As this isn't a regression from .NET Framework it is unlikely that the WinForms team will be able to get to the issue. If you or another community member wants to investigate a possible fix we'll be happy to look at any pull requests.

Note that all changes to existing behavior are considered breaking changes and have to be evaluated for potential impact to existing applications. See [Behavior breaking change](https://docs.microsoft.com/dotnet/standard/library-guidance/breaking-changes#behavior-breaking-change) for the guidelines we follow.

**Comment by RutulPatel8** [comment]
@dreddy-work I have fixed this issue locally. Could you please suggest where I can create a branch and generate a pull request?

**Comment by John-Qiao** [comment]
Verified this issue on .NET 9.0.100-preview.2.24101.9 with dlls built from winforms repo of main branch, it was fixed that: view.Sorted is false when set TreeViewNodeSorter to null.

![7027-testresult](https://github.com/dotnet/winforms/assets/45864985/4a9a4874-98d6-44d4-8b51-e6687f568987)

**Comment by Eudora-Li01** [comment]
Verified this issue with .NET 9 Preview 2 test pass build, it was fixed. Test result is same as above.
