### ISSUE TITLE
ExpandCollapse pattern is available for any tree node in `TreeView`

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#7043]
### .NET version

.NET 7.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, but it was reproduced in https://github.com/dotnet/winforms/pull/6432 as well.

### Issue description

`TreeView TreeNode` accessible object supports `Expand-Collapse` pattern even if the node can't expand:
![image](https://user-images.githubusercontent.com/49272759/163790776-023b84d6-b75b-4c68-861f-8d3ba231fbad.png)

### Steps to reproduce

- Create a .NET 7.0 app
- Add a TreeView with several nodes there
- Run the app and Inspect
- Check nodes available patterns

**Comment by vladimir-krestov** [comment]
@merriemcgaw, should we fix it?

**Comment by merriemcgaw** [comment]
@vladimir-krestov yes, I definitely think we should.

**Comment by MelonWang1** [comment]
Verified on build .NET 7.0.100-preview.5.22261.8, this issue was fixed. Screenshot as below:
![Screenshot 2022-05-11 213143](https://user-images.githubusercontent.com/94418985/167993236-caa9a6f2-198f-4b3c-8357-a20da47871fb.png)

**Comment by John-Qiao** [comment]
Verified with .NET SDK 7.0.100-preview.5.22305.1 TP build, this issue is fixed as same as above test result.
