### ISSUE TITLE
TreeView checkbox state desynchronizes on double-click

### ISSUE THREAD

**Issue by carlreinke** [dotnet/winforms#7063]
### .NET version

.NET 5.0

### Did it work in .NET Framework?

No

### Issue description

If a checkbox in a `TreeView` is double-clicked then the `Checked` property of the `TreeNode` no longer matches the visual state of the checkbox.

### Steps to reproduce

1. Add a `TreeView` to a `Form`.
2. Set the `Checkboxes` property of the `TreeView` to `true`.
3. Add a `TreeNode` to the `TreeView`.
4. Add an event handler to the `AfterCheck` Event of the `TreeView`.  In the handler, include `e.Node.Text = $"Checked: {e.Node.Checked}";`
5. Run the app.
6. Click the checkbox.  The text changes to "Checked: True".
7. Double-click the checkbox.  The text changes to "Checked: False" but the visual state remains checked (becoming desynchronized from the `Checked` property).
8. Double-click the checkbox again.  The text changes to "Checked: True" but the visual state changes to unchecked (remains desynchronized from the `Checked` property).
9. Click the checkbox.  The text changes to "Checked: False" and the visual remains unchecked (becoming synchronized to the `Checked` property).

**Comment by carlreinke** [comment]
A potentially-related issue is that cancelling the `BeforeCheck` event on the `TreeView` does not prevent double-clicking from changing the visual state of a checkbox.

**Comment by dreddy-work** [comment]
@carlreinke Thanks for reporting this!

As this isn't a regression from .NET Framework it is unlikely that the WinForms team will be able to get to the issue. If you or another community member wants to investigate a possible fix we'll be happy to look at any pull requests.

Note that all changes to existing behavior are considered breaking changes and have to be evaluated for potential impact to existing applications. See [Behavior breaking change](https://docs.microsoft.com/dotnet/standard/library-guidance/breaking-changes#behavior-breaking-change) for the guidelines we follow.

**Comment by carlreinke** [comment]
What feedback are you waiting on from me?

**Comment by dreddy-work** [comment]
> What feedback are you waiting on from me?

As mentioned above, we would be happy to co-ordinate if you or any other community member like to contribute to a solution on this. That label is intended to identify if there is sufficient interest and if not, issue will be closed after certain period of time.  To avoid confusion with label, I will create a new one.

**Comment by carlreinke** [comment]
@RussKie This is a report not a feature request. The bug will still be there even if you close the issue in 120 days.

**Comment by RussKie** [comment]
I understand this. However, this bug has been like this for a very long time. You're welcome to propose a fix.

**Comment by carlreinke** [comment]
Yeah, well, maybe it went unreported for that very long time because everyone knew that valid bug reports were met with hostility.

I don't contribute to projects that use stale bot on bug reports.
