### ISSUE TITLE
Empty `DataGridView` has extra NotSortedAccessibleStatus

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#7079]
### .NET version

.NET 7.0 (latest main)

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, there is no this extra property in .NET 6.0.
Regression from https://github.com/dotnet/winforms/pull/6498

### Issue description

Empty `DataGridView` has unexpected `NotSortedAccessibleStatus` item status:

![image](https://user-images.githubusercontent.com/49272759/165031310-d6fe519e-1490-4e8d-be95-ac6f2b4c357d.png)

### Proposal
Make additional check for empty DGV (DataGridViewAccessibleObject.cs - line 279):
```cs

                        if (ColumnCount > 0 && RowCount > 0)
                        {
                            return SR.NotSortedAccessibleStatus;
                        }

                        break;
```

### Steps to reproduce

- Create .NET 7.0  app
- Add a DataGridView there without columns or rows
- Run the app and check ItemStatus property in Inspect

**Comment by Cassie-Li01** [comment]
Verified on build .NET 7.0.100-preview.5.22267.11, this issue was fixed. Screenshot as below:
![image](https://user-images.githubusercontent.com/96758262/168971233-3577a611-ccd6-4cc5-846f-36e01cb15228.png)

**Comment by Ashley-Li** [comment]
Verified with .NET SDK 7.0.100-preview.5.22305.1 TP build, this issue is fixed as same as above test result.
