### ISSUE TITLE
Printing to PDF causes deadlock in Winforms with async Task Main()

### ISSUE THREAD

**Issue by calanchenlins** [dotnet/winforms#7085]
### .NET version

net6.0-windows

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

In netcoreapp3.1 and net5.0-windows, there are the same issues as net6.0-windows;
However, The sample code is worked without any issues in  Net Framework4.8;

### Issue description

When Main() method is async in Winforms,  PrintDocument.Print() will causes deadlock and program  non-responsive。This only happens with  [Microsoft Print To PDF] printer.

### Steps to reproduce

1. Create a .NET 6 Winforms project through Template. Modify Program.Main() method
```
internal static class Program
{
	[STAThread]
	static async Task<int> Main()
	{
		await Task.CompletedTask;
		Application.EnableVisualStyles();
		Application.SetCompatibleTextRenderingDefault(false);
		Application.Run(new Form1());
		return 0;
	}
}
```
2.  Add a Button in Form1,  then bind a EventHandler on Click as shown below
```
public partial class Form1 : Form
{
	public Form1()
	{
		InitializeComponent();
	}

	// Set [Microsoft Print To PDF] as the default printer
	private void button1_Click(object sender, EventArgs e)
	{
		var printDocument = new PrintDocument { DocumentName = AppDomain.CurrentDomain.FriendlyName };
		printDocument.PrintPage += PrintDocumentPrintPageHandler;
		printDocument.Print();
	}

	private void PrintDocumentPrintPageHandler(object sender, PrintPageEventArgs args)
	{
		var fileName = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"print.png");
		using (FileStream fileStream = File.OpenRead(fileName))
		{
			args.Graphics.DrawImage(Image.FromStream(fileStream), args.PageBounds);
		}
		args.HasMorePages = false;
	}
}
```

3. Set [Microsoft Print To PDF] as the default printer, then run then program

**Current behavior:**
Program non-responsive, a thread deadlock may have occurred

**Expected behavior:**
The SaveAs dialog  pops up

**Comment by RussKie** [comment]
`STAThread` and `async Main` don't and aren't meant to work together. This is by design. Please refer to https://github.com/dotnet/roslyn/issues/22112 for more details.

**Comment by calanchenlins** [comment]
@RussKie , After Follow your advice and removed the `STAThread`, The issues still exists.

**Comment by calanchenlins** [comment]
> `STAThread` and `async Main` don't and aren't meant to work together. This is by design. Please refer to [dotnet/roslyn#22112](https://github.com/dotnet/roslyn/issues/22112) for more details.

@RussKie , After Follow your advice and removed the `STAThread`, The issues still exists.

**Comment by tbolon** [comment]
You should have done the opposite : keep `[STAThread]` but remove the `async Task<int> Main` and use simply `int Main()` instead.
