### ISSUE TITLE
Uncaught exception or assertion failure: System.Collections.Generic.KeyNotFoundException for listView's setSorting test scenario

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7089]
### .NET version

**.Net 7.0 SDK:** 7.0.100-preview.5.22226.4

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it is a regression issue in recent .Net 7.0 build from main branch, cannot repro in .Net 7.0 SDK build: 7.0.100-preview.5.22220.23, it may be caused by PR: https://github.com/dotnet/winforms/pull/7029

### Issue description

Uncaught exception or assertion failure: System.Collections.Generic.KeyNotFoundException when running automation XListView case for setSorting scenario

### Steps to reproduce

We cannot get a manual repro, just met it when running our internal automation case about ListView with setSorting scenario, get following calll stack for product code:

_Uncaught exception or assertion failure: System.Collections.Generic.KeyNotFoundException
System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Windows.Forms.ListView.ListViewNativeItemCollection.get_Item(Int32 displayIndex) in D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\ListView.ListViewNativeItemCollection.cs:line 83
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index) in D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\ListView.ListViewItemCollection.cs:line 107
   at System.Windows.Forms.ListView.WmReflectNotify(Message&amp; m) in D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\ListView.cs:line 6614
   at System.Windows.Forms.ListView.WndProc(Message&amp; m) in D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\ListView.cs:line 6908
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&amp; m) in D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.ControlNativeWindow.cs:line 65
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp; m) in D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.ControlNativeWindow.cs:line 114
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam) in D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\NativeWindow.cs:line 369_

**Comment by RussKie** [comment]
@Olina-Zhang are you able to share " XListView case for setSorting scenario" code?

**Comment by Olina-Zhang** [comment]
Here is the testing code snippet for setSorting scenario:

```
protected virtual ScenarioResult set_Sorting(TParams p, SortOrder value)
    {
        SortOrder s = lv.Sorting;
        SortOrder newS = (SortOrder)p.ru.GetEnumValue(typeof(SortOrder));

        p.log.WriteLine("Sorting was: " + s.ToString() + ", now will be: " + newS.ToString());
        lv.Sorting = newS;

        ScenarioResult sr = new ScenarioResult(newS == lv.Sorting);

        lv.Sorting = SortOrder.None;
        return sr;
    }
```

**Comment by RussKie** [comment]
How is the listview populated, and how is this method invoked?

**Comment by Olina-Zhang** [comment]
> How is the listview populated, and how is this method invoked?

Hmm, it's hard to say, we have test cases based on test framework: WFCTestLib, to test current control and based control'
s properties and events
![image](https://user-images.githubusercontent.com/26474449/165432132-1acd35d2-80a8-46ab-ae17-ba77cd0cd232.png)

**Comment by gpetrou** [comment]
In order to address the exception we could use `TryGetValue` instead. However, it is not clear to me how this can be reproduced and if we need to fix something else.

**Comment by RussKie** [comment]
I got the source code for the test harness, and planning to look through to see if we distill a repro from it.

**Comment by gpetrou** [comment]
@RussKie are you able to share the code to reproduce the exception? I am struggling to understand how this can be reproduced.

**Comment by RussKie** [comment]
I still haven't got a repro myself and working with @Olina-Zhang to get it. All my conclusions are currently based purely on comparing the API. 
Once I have a repro, I'll share it with you.

**Comment by RussKie** [comment]
The source code for the failng test does not exhibit the issue - i.e., if I compile and/or debug the test app - no issues. However, the compiled sample fails consistently.

I've attached the debugger, and here's what's causing the issue (still no idea how we end up with this) - the hashtable does not contain an item with "index:0", instead it contains an item with "index:52" despite the fact that the listview only contains only 51 items...
![image](https://user-images.githubusercontent.com/4403806/174981998-55fae285-1f50-4a9b-8c32-e5b70173d763.png)

**Comment by RussKie** [comment]
I spent a little more time trying to reverse-engineer the sample app, and here's how the listview colleciton gets in this state:
```cs
            _listView = new();
            /* form */Controls.Add(_listView);

            _listView.Items.Add("boo");

            for (int i = 0; i < 51; i++)
            {
                ListViewItem toAdd = new ListViewItem(/* generate a random string */);
                _listView.Items.Add(toAdd);
            }

            _listView.Items.RemoveAt(0);

            ListViewItem lvi = _listView.Items[0];
            lvi.Remove();

            _listView.Items.Insert(/* random index between 2 and 50 */, lvi);
```

Then at some point `/* form */Controls.Clear()` is called, and it leads to the exception:
```
>	System.Private.CoreLib.dll!System.ThrowHelper.ThrowKeyNotFoundException<int>(int key = 0) Line 253	C#
 	System.Windows.Forms.dll!System.Windows.Forms.ListView.ListViewNativeItemCollection.this[int].get(int displayIndex) Line 88	C#
 	System.Windows.Forms.dll!System.Windows.Forms.ListView.WmReflectNotify(ref System.Windows.Forms.Message m) Line 6614	C#
 	System.Windows.Forms.dll!System.Windows.Forms.ListView.WndProc(ref System.Windows.Forms.Message m) Line 6905	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m) Line 114	C#
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.Callback(nint hWnd, Interop.User32.WM msg = REFLECT_NOTIFY, nint wparam, nint lparam) Line 369	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ReflectMessage(nint hWnd, ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 10015	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WmNotify(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 12515	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m) Line 13306	C#
 	System.Windows.Forms.dll!System.Windows.Forms.ScrollableControl.WndProc(ref System.Windows.Forms.Message m) Line 1504	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Application.ParkingWindow.WndProc(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 157	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m) Line 114	C#
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.Callback(nint hWnd, Interop.User32.WM msg = NOTIFY, nint wparam, nint lparam) Line 369	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DefWndProc(ref System.Windows.Forms.Message m = {System.Windows.Forms.Message}) Line 515	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m) Line 13396	C#
 	System.Windows.Forms.dll!System.Windows.Forms.ListView.WndProc(ref System.Windows.Forms.Message m) Line 7075	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m) Line 114	C#
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.Callback(nint hWnd, Interop.User32.WM msg = 4173, nint wparam, nint lparam) Line 369	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.Primitives.dll!Interop.User32.SendMessageW<Interop.ComCtl32.LVITEMW>(IHandle hWnd = _listItemsById = Count = 51, Interop.User32.WM Msg, nint wParam, ref Interop.ComCtl32.LVITEMW lParam)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.ListView.InsertItemsNative(int index = 0, System.Windows.Forms.ListViewItem[] items = {System.Windows.Forms.ListViewItem[51]}) Line 4258	C#
 	System.Windows.Forms.dll!System.Windows.Forms.ListView.OnHandleCreated(System.EventArgs e) Line 4681	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WmCreate(ref System.Windows.Forms.Message m) Line 12158	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m) Line 13164	C#
 	System.Windows.Forms.dll!System.Windows.Forms.ListView.WndProc(ref System.Windows.Forms.Message m) Line 7075	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m) Line 114	C#
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.Callback(nint hWnd, Interop.User32.WM msg = CREATE, nint wparam, nint lparam) Line 369	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.Primitives.dll!Interop.User32.CreateWindowExW(Interop.User32.WS_EX dwExStyle, string lpClassName, string lpWindowName, Interop.User32.WS dwStyle, int X, int Y, int nWidth, int nHeight, nint hWndParent, nint hMenu, nint hInst, object lpParam)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams cp) Line 458	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.CreateHandle() Line 4999	C#
 	System.Windows.Forms.dll!System.Windows.Forms.ListView.CreateHandle() Line 2610	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.RecreateHandleCore() Line 9905	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.AssignParent(System.Windows.Forms.Control value) Line 4627	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlCollection.Remove(System.Windows.Forms.Control value = _listItemsById = Count = 51) Line 335	C#
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlCollection.Clear() Line 430	C#
```

I was unable to replicate this locally though, and this would require more digging in and debugging. Unfortunately I don't have more time for this right now.

**Comment by MelonWang1** [comment]
Verified this issue on .NET SDK 7.0.100-preview.7.22327.3, it is fixed. The XListView and XListViewItem Cases automation run passed.

**Comment by Philip-Wang01** [comment]
Verified this issue on .NET SDK 7.0.100-preview.6.22352.1, it is fixed. The XListView and XListViewItem Cases automation run passed.
