### ISSUE TITLE
Automation cases about Label/LinkLabel met an error "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7090]
### .NET version

**.Net 7.0 SDK:** 7.0.100-preview.5.22226.4

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it is a regression issue in recent .Net 7.0 build from main branch, cannot repro in .Net 7.0 SDK build: 7.0.100-preview.5.22220.23, it may be caused by PR: https://github.com/dotnet/winforms/pull/6778

### Issue description

Automation cases about Label/LinkLabel met an error "Object reference not set to an instance of an object" when executing get PreferredSize scenario

### Steps to reproduce

We cannot get a manual repro, just met it when running our internal automation case about Label/LinkLabel with get_PreferredSize scenario, get following calll stack for product code:

                <StackTrace>
                    <Frame function="GetAnchorDestination" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Layout\DockAndAnchorLayout.cs" line="165" />
                    <Frame function="LayoutAnchoredControls" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Layout\DockAndAnchorLayout.cs" line="303" />
                    <Frame function="TryCalculatePreferredSize" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Layout\DockAndAnchorLayout.cs" line="585" />
                    <Frame function="LayoutCore" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Layout\DockAndAnchorLayout.cs" line="527" />
                    <Frame function="Layout" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Layout\LayoutEngine.cs" line="44" />
                    <Frame function="OnLayout" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.cs" line="8275" />
                    <Frame function="OnLayout" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\ScrollableControl.cs" line="628" />
                    <Frame function="OnLayout" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\ContainerControl.cs" line="926" />
                    <Frame function="OnLayout" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Form.cs" line="4038" />
                    <Frame function="PerformLayout" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.cs" line="8992" />
                    <Frame function="PerformLayout" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.cs" line="8938" />
                    <Frame function="ResumeLayout" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.cs" line="10108" />
                    <Frame function="Dispose" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Layout\LayoutTransaction.cs" line="66" />
                    <Frame function="set_Font" file="D:\WinForms\Fork\winforms\src\System.Windows.Forms\src\System\Windows\Forms\Control.cs" line="2133" />
                    <Frame function="IncreaseControlPreferredSize" file="" line="0" />
                    <Frame function="get_PreferredSize" file="" line="0" />
                    <Frame function="InvokeMethod" file="" line="0" />
                    <Frame function="InvokeNonEmitUnsafe" file="" line="0" />
                </StackTrace>

**Comment by dreddy-work** [comment]
Working on this. Regression was in current preview.

**Comment by MelonWang1** [comment]
Verified this issue on .NET SDK 7.0.100-preview.5.22267.11, it is fixed. The Label and LinkLabel Cases automation run passed.

**Comment by Cassie-Li01** [comment]
Verified this issue on .NET SDK 7.0.100-preview.5.22305.3 TP, it is fixed. The Label and LinkLabel cases automation are passed.
