### ISSUE TITLE
Accessibility: Invalid BoundingRectangle value for DataGridView cells and headers

### ISSUE THREAD

**Issue by M-Lipin** [dotnet/winforms#710]
Bounding rectangle of the header and data cells are not being contained within the parent element (row) and the top element (DataGridView). If a magnifier is trying to magnify this element, it will magnify parts of the element that aren’t visible.
This only happens when cells don't fully fit on the screen and scroll bar appears.

**Expected result:**
Bounding rectangle for all cells should be within parent element.

**Comment by vladimir-krestov** [comment]
The fix for this issue has been verified.
