### ISSUE TITLE
Obsolete BinaryFormatter infrastructure

### ISSUE THREAD

**Issue by kant2002** [dotnet/winforms#7105]
### Is your feature request related to a problem? Please describe

Given that https://docs.microsoft.com/en-us/dotnet/standard/serialization/binaryformatter-security-guide and overall plan to obsolete BinaryFormatter, is there time to do the same and mark constructors with `(SerializationInfo info, StreamingContext context)`.  Also all implementations for serialization can be put behind `AppContext` switch, so if somebody want risky behavior he should opt-in into it. 

Example how it is handled with `DataTable` class https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0038

### Describe the solution you'd like and alternatives you've considered

Other alternative is provide more blog posts, and guidance how to move out of this technology, and later on again obsolete it and eventually drop support 😄 

### Will this feature affect UI controls?

Potentially VS designer affected, maybe 3rd party-controls libraries. 
They should be informed about change upfront, even if writing was on the wall for a long time.

**Comment by kant2002** [comment]
I think this is https://github.com/dotnet/winforms/issues/1251 and https://github.com/dotnet/winforms/issues/6267 , so my search foo was broken when I wrote this issue :(

**Comment by dreddy-work** [comment]
@kant2002 , We would be tracking this with epic #6267 and closing this as duplicate.
