### ISSUE TITLE
Fix issues when user removes ListViewItem

### ISSUE THREAD

**Issue by dmitrii-drobotov** [dotnet/winforms#7135]
### .NET version

7.0

### Did it work in .NET Framework?

No

### Issue description

Continuation of work on https://github.com/dotnet/winforms/issues/6230. While https://github.com/dotnet/winforms/pull/6352  resolved the issue, it didn't fix the underlying problem.

### Steps to reproduce

See https://github.com/dotnet/winforms/issues/6230

**Comment by dreddy-work** [comment]
@vladimir-krestov  to prioritize the issue.
