### ISSUE TITLE
[Accessibility] Change DataGridView's Row/Column counting with starting at 1, not 0

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7154]
### .NET version

**.Net 7.0 SDK build:** 7.0.100-preview.5.22256.2

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this is not a regression issue. And @merriemcgaw wants a runtime issue to ask to change the counting with starting at 1.

### Issue description

We need to change DataGridView's Row/Column counting with starting at 1, not 0

**Accessibility Insight:**
![image](https://user-images.githubusercontent.com/26474449/167351421-e205255b-db5e-49d2-a7d2-101f12f660b8.png)

**Inspect:**
![image](https://user-images.githubusercontent.com/26474449/167351625-a95d5566-bbb8-4df6-ba55-d3656b740de2.png)

**Narrator:**
![image](https://user-images.githubusercontent.com/26474449/167351903-ad50b27f-670f-4160-bd85-89ac78ee40f9.png)

### Steps to reproduce

**Repro steps:**
1. Open attached application
[DataGridView_Sample.zip](https://github.com/dotnet/winforms/files/8649203/DataGridView_Sample.zip)
2. Build and run
3. Use Accessibility tools: AccessiblityInsight, Narrator, Inspect focus on the first DataGridView cell, to observe the rows/columns starting count

**Comment by tinodo** [comment]
+1 on this issue!

**Comment by dreddy-work** [comment]
This would be breaking change.

**Comment by dreddy-work** [comment]
@vladimir-krestov , can you guys take a look and see if we can fix this just for accessibility?

**Comment by merriemcgaw** [comment]
We would likely have to make some sort of configuration option for the developer to opt in to counting starting from 1 rather than zero. I can't see any other way to not break our users who have worked around this issue for years. I imagine there's lots of automation that depends on this bug, and probably some AT has worked around this too and we don't want to break either scenario.

**Comment by vladimir-krestov** [comment]
It's easy to change-just add +1 to index:

`DataGridViewRowAccessibleObject.Name`:
![image](https://user-images.githubusercontent.com/49272759/170692343-36b80ea7-9799-46db-8f51-c9adb4496c7c.png)

And `DataGridViewCellAccessibleObject.Row/Column`:
![image](https://user-images.githubusercontent.com/49272759/170692573-1052a92a-d060-4730-b428-709acd51b374.png)

_____________________________

But we need to decide, how to turn on/off our change. My first proposal is to use something like `EnableVisualStyles` method for `Application`.

**Comment by merriemcgaw** [comment]
We would definitely need to quirk this so that those who depend on the "starts at 0" behavior are not broken. @dreddy-work  is working on a quirking strategy for the HDPI scary changes, and I think for this one we'd need to follow that same pattern. Let's hold off on this for a little while, so that we can consider how people and assistive tech can use the new behavior. It's not an urgent issue by any means.

**Comment by merriemcgaw** [comment]
This is a major change in behavior and will need to be behind a quirk of some kind. I don't think we can get this in 7, so let's shoot for 8.

**Comment by Tanya-Solyanik** [comment]
@merriemcgaw - had anyone requested this change? This is breaking from .NET Framework and the first column/row is indexed as a zero in the code.

**Comment by merriemcgaw** [comment]
The accessibility team asked us to consider it. I think it is more of a usability rather than accessibility item and I think fixing it may cause problems with screen readers. That said, it is really illogical to a lot of users.

**Comment by tinodo** [comment]
We're not asking to start numbering columns and rows from 1 in **CODE**, but merely how these columns and rows are **ANNOUNCED** to users through screen readers.
Could we please stop moving this thing from one .NET version to another and either do it or decide not to do it?

**Comment by Tanya-Solyanik** [comment]
Please put this change under a [switch](https://github.com/dotnet/winforms/blob/c0ac1f1723e6cd67563d0c979842ae3c1609fd44/docs/runtime-configuration.md?plain=1#L15). Sample implementation is here - https://github.com/dotnet/winforms/blob/c0ac1f1723e6cd67563d0c979842ae3c1609fd44/src/Common/src/LocalAppContextSwitches.Common.cs#L12

**Comment by Philip-Wang01** [comment]
Verified the issue on 9.0.100-alpha.1.23580.4 with dlls build form main branch, the issue has been fixed that the DataGridView's Row/Column counting with starting at 1, not 0.
Accessibility Insight:
![image](https://github.com/dotnet/winforms/assets/86937911/5a51f9f6-a43f-46ee-ae36-7a00ec29eba1)
Inspect:
![image](https://github.com/dotnet/winforms/assets/86937911/6ee06001-6b29-4d4a-bcef-723c3a1b4f3b)
Narrator:
![image](https://github.com/dotnet/winforms/assets/86937911/3bb56cbc-9980-4602-a14a-c89a02a32ab1)
