### ISSUE TITLE
Create tests for ported components for DevExpress

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#716]
We have ported several components from framework to core. These components were lack of unit tests and during the porting process we agreed to create only minimal unit tests to keep the process faster and unblock the customers porting process as soon as possible.

These components need more through unit tests to be added.

Related issue: #221 

Portability report available: https://microsoft-my.sharepoint.com/:x:/r/personal/dreddy_microsoft_com/_layouts/15/Doc.aspx?sourcedoc={1b3ac7ac-3792-4bcc-8d58-8185fa1d1557}&action=edit&activeCell=%27Details%27!B76&wdInitialSession=b95b5c5e-57b6-47cc-88ff-5ca14cbb4182&wdRldC=1

**Comment by hughbe** [comment]
@RussKie any idea what these components are? issue doesn't really describe it

**Comment by RussKie** [comment]
@merriemcgaw  @dreddy-work I don't appear have access to the linked doc, is there something else to do besides addressing referenced open issues - 714-721?

**Comment by merriemcgaw** [comment]
I think that's all we need to worry about. I can't recall anything else.
