### ISSUE TITLE
Add unit tests to System.ComponentModel.Design.DesignerAction*Collection Components

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#717]
Add unit tests (if not exists) for

Methods:
System.ComponentModel.Design.DesignerActionItemCollection
- [ ] M:System.ComponentModel.Design.DesignerActionItemCollection.#ctor
- [ ] M:System.ComponentModel.Design.DesignerActionItemCollection.Add(System.ComponentModel.Design.DesignerActionItem)
- [ ] M:System.ComponentModel.Design.DesignerActionItemCollection.get_Item(System.Int32)
- [ ] M:System.ComponentModel.Design.DesignerActionItemCollection.Insert(System.Int32,System.ComponentModel.Design.DesignerActionItem)
- [ ] M:System.ComponentModel.Design.DesignerActionItemCollection.set_Item(System.Int32,System.ComponentModel.Design.DesignerActionItem)

System.ComponentModel.Design.DesignerActionListCollection
- [ ] M:System.ComponentModel.Design.DesignerActionListCollection.#ctor
- [ ] M:System.ComponentModel.Design.DesignerActionListCollection.Add(System.ComponentModel.Design.DesignerActionList)
- [ ] M:System.ComponentModel.Design.DesignerActionListCollection.get_Item(System.Int32)

Epic: #716
Related issues: #221, #609
Related PRs: #633

**Comment by hughbe** [comment]
This can be closed. Tests have been written for `DesignerActionItemCollection` and `DesignerActionListCollection`

**Comment by RussKie** [comment]
Thank you!
