### ISSUE TITLE
Add unit tests to Toolbox related components

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#718]
Add unit tests (if not exists) for

Methods:
~~ToolboxItem~~ - #714
~~IToolboxUser~~ interface
~~IToolboxService~~ interface

ToolboxItemCollection
- [ ] M:System.Drawing.Design.ToolboxItemCollection.#ctor(System.Drawing.Design.ToolboxItem[])
- [ ] M:System.Drawing.Design.ToolboxItemCollection.Contains(System.Drawing.Design.ToolboxItem)

ToolboxItemCreatorCallback
- [ ] T:System.Drawing.Design.ToolboxItemCreatorCallback.#ctor

Epic: #716
Related issues: #221, #478
Related PRs: #480

**Comment by hughbe** [comment]
ToolboxItem/ToolboxItemCollection tests added

**Comment by hughbe** [comment]
This can be closed, all tests added /cc @RussKie

**Comment by RussKie** [comment]
Thank you
