### ISSUE TITLE
TreeNode accessible objects are leaking in memory

### ISSUE THREAD

**Issue by dmitrii-drobotov** [dotnet/winforms#7196]
### .NET version

.NET 7.0 Preview 4 (at least .NET 7.0 Preview 3, where `TreeNodeAccessibleObject` was introduced)

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No (there was no `TreeNodeAccessibleObject`)

### Issue description

`TreeNode` accessible objects are left in memory after the `TreeView` control instance with its nodes was inspected with accessibility tool (like Accessibility Insights or Inspect) and the form with `TreeView` is closed, garbage is collected, but accessibility tool is still opened. Same applies for case when `TreeNode` is removed from `TreeView`.

Memory snapshot in VS:
![Screenshot 2022-05-19 173414](https://user-images.githubusercontent.com/102954094/169343473-0b5da5d4-f12c-4e6f-abd2-503d24cd1071.png)

### Steps to reproduce

1. Create a parent form with two buttons: one will be opening a child form with the `TreeView` control and the other will collect the garbage.
2. Press the second button to open the child form with `TreeView`.
3. Start the Accessibility Insights tools.
4. Run automated checks for the `TreeView` control using AI.
5. Close the child form.
6. Clear memory with the first button of the parent form.
7. DON'T close the AI tool.
8. Look for `TreeNodeAccessibleObject` objects left in memory (using WinDbg, or dotMemory, or another suitable tool).

Sample app: [TreeViewSample.zip](https://github.com/dotnet/winforms/files/8731946/TreeViewSample.zip)

**Comment by Nora-Zhou01** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.100-rc.1.22425.12, issue was fixed as below
![treenode](https://user-images.githubusercontent.com/104609169/187161362-a978f8c9-ab14-491e-bfa3-f2596974ef1b.png)
:

**Comment by Tanya-Solyanik** [comment]
@Nora-Zhou01  - These are referenced from a static object and thus expected.

**Comment by Ashley-Li** [comment]
Verified on .NET SDK 8.0.100-alpha.1.22451.15 build, issue was fixed as below:
![image](https://user-images.githubusercontent.com/56664234/188072852-44b8bb93-8e63-4137-8afc-e6bd1dd6d35e.png)
