### ISSUE TITLE
ListBox items' accessible objects are leaking in memory

### ISSUE THREAD

**Issue by dmitrii-drobotov** [dotnet/winforms#7197]
### .NET version

.NET 7.0 Preview 4 

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

`ListBox` items' accessible objects are left in memory after the `ListBox` control instance with its items was inspected with accessibility tool (like Accessibility Insights or Inspect) and the form with `ListBox` is closed, garbage is collected, but accessibility tool is still opened. Same applies for case when `ListBox` item is removed from `ListBox`.

Memory snapshot in VS:
![Screenshot 2022-05-18 174214](https://user-images.githubusercontent.com/102954094/169345773-46837247-3587-4c4a-9c19-713cc48566a8.png)

### Steps to reproduce

1. Create a parent form with two buttons: one will be opening a child form with the `ListBox` control and the other will collect the garbage.
2. Press the second button to open the child form with `ListBox`.
3. Start the Accessibility Insights tools.
4. Run automated checks for the `ListBox` control using AI.
5. Close the child form.
6. Clear memory with the first button of the parent form.
7. DON'T close the AI tool.
8. Look for `ListBoxItemAccessibleObject` accessible objects left in memory (using WinDbg, or dotMemory, or another suitable tool).

Sample app: [ListBoxSample.zip](https://github.com/dotnet/winforms/files/8731986/ListBoxSample.zip)

**Comment by dreddy-work** [comment]
@dmitrii-drobotov , we believe you are working on it hence, assigned to you.

**Comment by MandiMan** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.100-rc.1.22425.12, issue was fixed as below:
![memory link](https://user-images.githubusercontent.com/108860782/187147839-d7393259-3ea9-478b-b01d-1be13be55373.PNG)

**Comment by Philip-Wang01** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, issue was fixed, test result is same as above screenshot.
