### ISSUE TITLE
[Accessibility] An onscreen element must not have a null BoundingRectangle property for PrintPreviewToolStrip Zoom button

### ISSUE THREAD

**Issue by Cassie-Li01** [dotnet/winforms#7199]
### .NET version

.NET 7.0.100-preview.5.22267.11

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

This is a regression issue. .NET 7.0.100-preview.4.22252.9 and Net 6.0 not repro this issue

### Issue description

[Accessibility] An onscreen element must not have a null BoundingRectangle property for PrintPreviewToolStrip Zoom button

### Steps to reproduce

1. Open the attached project, build and run it 
[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/8738010/WinFormsApp1.zip)
2. Launch AccessibilityInsights
3. Click button1, and then in PrintPreview dialog
4. Focus on tool bar PrintPreviewToolStrip zoom button
5. Observe the result using AccessibilityInsights

Actual behavior:
AccessibilityInsights detected an error: An onscreen element must not have a null BoundingRectangle property
![Result](https://user-images.githubusercontent.com/96758262/169495047-f0ff79d1-e6c5-4f40-9643-3f85b0fe2a1e.PNG)

Expected behavior:
AccessibilityInsights should not detect this error.

**Comment by merriemcgaw** [comment]
@vladimir-krestov can you prioritize this for an upcoming preview in .NET 7? This could be a blocking bug for us,

**Comment by merriemcgaw** [comment]
@dmitrii-drobotov and @vladimir-krestov  which one of you would like to investigate this and see what caused this recent regression?

**Comment by vladimir-krestov** [comment]
I couldn't reproduce this bug in the latest main branch and in 7.0.0-preview.5.22269.1.
@Cassie-Li01, could you please test this bug in the latest sdk?

**Comment by Cassie-Li01** [comment]
Hi @vladimir-krestov

Verified on build dotnet-sdk-7.0.100-preview.6.22277.6, issue is not repro, so closed.
![image](https://user-images.githubusercontent.com/96758262/170949630-9f02242e-e45b-4457-b91c-73586402a911.png)
