### ISSUE TITLE
Add unit tests to System.Windows.Forms.Design.* components

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#720]
Add unit tests (if not exists) for

1) Methods:

System.Windows.Forms.Design.WindowsFormsDesignerOptionService
- [ ] M:System.Windows.Forms.Design.WindowsFormsDesignerOptionService.#ctor
- [ ] M:System.Windows.Forms.Design.WindowsFormsDesignerOptionService.get_CompatibilityOptions

System.Windows.Forms.Design.MenuCommands
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyCancel
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyDefaultAction
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyMoveDown
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyMoveLeft
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyMoveRight
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyMoveUp
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyNudgeDown
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyNudgeHeightDecrease
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyNudgeHeightIncrease
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyNudgeLeft
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyNudgeRight
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyNudgeUp
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyNudgeWidthDecrease
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeyNudgeWidthIncrease
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeySelectNext
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeySelectPrevious
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeySizeHeightDecrease
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeySizeHeightIncrease
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeySizeWidthDecrease
- [ ] F:System.Windows.Forms.Design.MenuCommands.KeySizeWidthIncrease

System.Windows.Forms.Design.ComponentTray
- [ ] M:System.Windows.Forms.Design.ComponentTray.#ctor(System.ComponentModel.Design.IDesigner,System.IServiceProvider)
- [ ] M:System.Windows.Forms.Design.ComponentTray.AddComponent(System.ComponentModel.IComponent)
- [ ] M:System.Windows.Forms.Design.ComponentTray.Dispose(System.Boolean)
- [ ] M:System.Windows.Forms.Design.ComponentTray.get_ComponentCount
- [ ] M:System.Windows.Forms.Design.ComponentTray.RemoveComponent(System.ComponentModel.IComponent)
- [ ] M:System.Windows.Forms.Design.ComponentTray.set_AutoArrange(System.Boolean)
- [ ] M:System.Windows.Forms.Design.ComponentTray.set_ShowLargeIcons(System.Boolean)

System.Windows.Forms.Design.DesignerOptions
- [ ] M:System.Windows.Forms.Design.DesignerOptions.set_UseOptimizedCodeGeneration(System.Boolean)

2) Classes

- [ ] System/Windows/Forms/Design/Behavior/Adorner.cs
- [ ] System/Windows/Forms/Design/Behavior/BehaviorService.cs
- [ ] System/Windows/Forms/Design/Behavior/DesignerActionBehavior.cs
- [ ] System/Windows/Forms/Design/Behavior/DesignerActionGlyph.cs
- [ ] System/Windows/Forms/Design/Behavior/DesignerActionKeyboardBehavior.cs
- [ ] System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
- [ ] System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
- [ ] System/Windows/Forms/Design/Behavior/SelectionGlyphBase.cs
- [ ] System/Windows/Forms/Design/Behavior/SelectionManager.cs
- [ ] System/Windows/Forms/Design/Behavior/SnapLine.cs
- [ ] System/Windows/Forms/Design/ComponentTray.cs
- [ ] System/Windows/Forms/Design/ContainerSelectorActiveEventHandler.cs
- [ ] System/Windows/Forms/Design/ControlDesigner.cs
- [ ] System/Windows/Forms/Design/DesignerActionHeaderItem.cs
- [ ] System/Windows/Forms/Design/DesignerActionListsChangedEventHandler.cs
- [ ] System/Windows/Forms/Design/DesignerActionPanel.cs
- [ ] System/Windows/Forms/Design/DesignerActionService.cs
- [ ] System/Windows/Forms/Design/DesignerActionTextItem.cs
- [ ] System/Windows/Forms/Design/DesignerActionUI.cs
- [ ] System/Windows/Forms/Design/DesignerActionUIService.cs
- [ ] System/Windows/Forms/Design/DesignerActionUIStateChangeEventHandler.cs
- [ ] System/Windows/Forms/Design/DesignerActionVerbItem.cs
- [ ] System/Windows/Forms/Design/DesignerFrame.cs
- [ ] System/Windows/Forms/Design/DesignerUtils.cs
- [ ] System/Windows/Forms/Design/NoBorderRenderer.cs
- [ ] System/Windows/Forms/Design/ParentControlDesigner.cs
- [ ] System/Windows/Forms/Design/SelectionRules.cs
- [ ] System/Windows/Forms/Design/SelectionUIService.cs
- [ ] System/Windows/Forms/Design/StatusCommandUI.cs

Epic: #716
Related issues: #221, #585
Related PRs: #632

**Comment by simarjeetss** [comment]
Hey @JuditRose, can I look into this? Is this still active?

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - Could you please review our current code coverage for System.Windows.Forms.Design namespace and add all public classes and Editords that are not covered by unit tests to the list in this bug description.

**Comment by LeafShi1** [comment]
Tracking this issue with issue #10773
