### ISSUE TITLE
[dotnet-sdk-7.0.100-preview.5.22267.11] Some controls are sometimes not displayed due to DPI settings and monitor

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/winforms#7201]
### .NET version

dotnet-sdk-7.0.100-preview.5.22267.11

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

**Verify Scenarios:**
1). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.5.22267.11: Fail
2). Windows10 RS5 x64+dotnet-sdk-5.0.214-win-x64: Pass
3). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.5.22263.22: Pass

### Issue description

**Application Name**:  AutoVersionsDB
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: dotnet-sdk-7.0.100-preview.5.22267.11
**Github Link**: https://github.com/modi-w/AutoVersionsDB

**App Source code or App Checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1543198/
**Github Link**: https://github.com/modi-w/AutoVersionsDB

### Steps to reproduce

**Minimal Repro steps:**
**The machine only has 7.0 installed. And DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2 is set.**
See attachment for source code.
[WinFormsApp.zip](https://github.com/dotnet/winforms/files/8760332/WinFormsApp.zip)

1. Create a Winform project, source code is 5.0
2. Create User Control
3. Add a panel to user control
4. Add labels to panel
5. Add user control to mainform
6. When we run our sample app with 5.0, labels are ok
![5 0](https://user-images.githubusercontent.com/83067197/169543012-6510d339-8d16-4869-8761-52847f3703af.png)
7. when we run against 7, one label is partially shown, other one doesn't show.
![7 0](https://user-images.githubusercontent.com/83067197/169543187-f369494d-3fee-4a5c-8ec7-ef241613a82a.png)

**Findings:**
When we add Application.SetHighDpiMode(HighDpiMode.SystemAware) to program.cs the Process Log button show part, maybe it is related to DPI.

**Repro steps on App**:
**The machine only has 7.0 installed. And DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2 is set.**

1. Install Localdb.
2. Copy [AutoVersionsDB] into your own machine.
3. Launch application from "AutoVersionsDB\AutoVersionsDB.WinApp.exe".
4. Click “New Project” button.
5. Type “test” in Id.
6. Type “test” in Description.
7. Type “(localdb)\mssqllocaldb” in Server.
8. Type “500” in Timeout.
9. Type “master” in DB Name.
10. Type your local folder path for DB Backup.
11. Type your local folder path for Scripts.
12. Type your local folder path for Deploy Artifact.
13. Click “Save” button.
14. Click “Process Log” button.

**Expected Result:** 
Click successfully.

**Actual Result:**
Can't find the button, it should be displayed on the right side.

@dotnet-actwx-bot @dotnet/compat

**Comment by dreddy-work** [comment]
Investigating.

**Comment by dreddy-work** [comment]
@Olina-Zhang , I tried attached sample app [WinFormsApp3.zip](https://github.com/dotnet/winforms/files/8740651/WinFormsApp3.zip) with 200% primary DPI with latest SDK (desktop version 7.0.0-preview.5.22269.1) and i do not repro the issue. Can you help get the repro steps here with this sample app if you could repro it? I tried both SystemAware and UnAware ( in program.cs).

**Comment by Junjun-zhao** [comment]
@dreddy-work @Olina-Zhang Thanks for helping investigate this bug.  I uploaded a new repro sample, there are some changes , location , size and AutoScaleDimensions . [WinFormsApp.zip](https://github.com/dotnet/winforms/files/8759940/WinFormsApp.zip)
We tried it with 7.0.100-preview.5.22273.1 on three machines. It repro . Could you please have a try?  Feel free to let us know if you encounter any problem. Thanks.

**Repro Steps to repro with the sample code:**

1.  Download the Sample code to your local. 
2.  Run "dotnet build"
3.  Go to bin\Debug\net5.0-windows, update the "version" of "Microsoft.WindowsDesktop.App"to .NET 7 runtime like below.

```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.WindowsDesktop.App",
      "version": "7.0.0-preview.5.22269.1"
    }
  }
}
```
4. Run "WinFormsApp3.exe" under bin\Debug\net5.0-windows.

**Comment by Cassie-Li01** [comment]
Verified on latest SDK 7.0.100-preview.5.22273.16 with sample application
[WinFormsApp.zip](https://github.com/dotnet/winforms/files/8761085/WinFormsApp.zip)

**Repro use the sample application and Unaware** 
sample application:
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/96758262/169991670-ae19b79f-593b-4da1-b98f-8ef34a64f230.png)
Unaware:
![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/96758262/169991594-0512f084-6daf-4b34-833c-0485d223b7b0.png)

**Not repro on SystemAware and PermonitorV2**
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/96758262/169991731-1d28f41b-ac2b-4a2f-8bb1-140cbb57eee9.png)

![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/96758262/169991742-e5ac7e78-ee40-40b7-be37-b21029c7e091.png)

Repro Steps:
1. Set 300% primary DPI 
2. Open attached application
3. Change .net 5 to .net 7 in csproj.cs
4. Build and Run
![MicrosoftTeams-image (14)](https://user-images.githubusercontent.com/96758262/169991792-4bc76561-a8fa-4fad-b3be-66b78bc2bac0.png)

**Comment by dreddy-work** [comment]
Thanks @Cassie-Li01. I got repro and investigating.

**Comment by Nora-Zhou01** [comment]
@Junjun-zhao The latest .NET 7.0 SDK build doesn't contain this PR fix. We will verify and add comments once the PR is merged to build.

**Comment by Cassie-Li01** [comment]
Verified on latest .NET Core 7.0 build: .NET 7.0.100-preview.7.22330.8, issue is fixed. Screenshot as below, @Junjun-zhao please kindly check.
![image](https://user-images.githubusercontent.com/96758262/176840867-d7f79b4b-b563-443b-b0b1-146950ba51a5.png)
![image](https://user-images.githubusercontent.com/96758262/176840922-b99140d6-eeff-474c-837d-1a54f5428faa.png)
![image](https://user-images.githubusercontent.com/96758262/176840956-5f894c02-22bc-4420-a044-832e953b9149.png)
![image](https://user-images.githubusercontent.com/96758262/176841006-c1f662c0-5ada-42cd-936d-4dc575392a2e.png)

**Comment by Junjun-zhao** [comment]
Verified and this issue fixed on build .NET 7.0.100-preview.6.22330.5. Thanks.

**Comment by Cassie-Li01** [comment]
Verified on .NET 7.0.100-preview.6.22352.1 TP build, it was fixed, screenshot as above.
