### ISSUE TITLE
[LOC] Comments and region description are not translated in Form.designer.cs

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7224]
### .NET version

.Net 7.0 SDK build: 7.0.100-preview.5.22273.1

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, still repro in previous .Net Core and .Net 5+

### Issue description

Comments and region description are not translated for winforms files

.Net 7.0_CHS:
![image](https://user-images.githubusercontent.com/26474449/170426390-fc2251f7-8005-4344-9cbb-c12218080468.png)

.Net framework_CHS:
![image](https://user-images.githubusercontent.com/26474449/170426483-e926b7a2-ef2a-4c24-a38e-38bc7dcc06c5.png)

### Steps to reproduce

1. Create a Winforms .NET Core application
2. Open Form1.designer.cs, observe the comments and region description

**Comment by merriemcgaw** [comment]
We need to have an internal discussion about whether and how to localize comments in the templates.

**Comment by Tanya-Solyanik** [comment]
Maybe instead of our existing comments we could put a link to docs, like console template is doing - 
```
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
```

**Comment by merriemcgaw** [comment]
.NET doesn't generally localize comments in the templates. If we get a lot of feedback that customers really want this feature, we will work with the SDK folks to figure out how we would deliver the localized templates.
