### ISSUE TITLE
 Rounded Corners are not smooth in WinForms 

### ISSUE THREAD

**Issue by MohanramAnbukkarasu** [dotnet/winforms#7225]
### .NET version

Issue can be reproduced in any .NET version. 

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

I'm creating a custom Form with rounded corners. 

I'm using the below given code to get rounded corners. 

**Note** : It is just a sample code to reproduce my problem. 

```
public partial class Form1 : Form
{
    [DllImport("Gdi32.dll", EntryPoint = "CreateRoundRectRgn")]
    private static extern IntPtr CreateRoundRectRgn
(
    int nLeftRect,     // x-coordinate of upper-left corner
    int nTopRect,      // y-coordinate of upper-left corner
    int nRightRect,    // x-coordinate of lower-right corner
    int nBottomRect,   // y-coordinate of lower-right corner
    int nWidthEllipse, // width of ellipse
    int nHeightEllipse // height of ellipse
);

    [DllImport("user32.dll", CharSet = CharSet.Auto, CallingConvention = CallingConvention.Winapi)]
    internal static extern int SetWindowRgn(IntPtr hWnd, IntPtr hRgn, bool bRedraw);

    [DllImport("gdi32")]
    internal static extern bool DeleteObject(IntPtr hObject);
    public Form1()
    {
        InitializeComponent();

        this.BackColor = Color.DarkGray;
        this.FormBorderStyle = FormBorderStyle.None;
        IntPtr hRgn = CreateRoundRectRgn(0, 0, Width, Height, 10, 10);

        if (hRgn != IntPtr.Zero)
        {
            SetWindowRgn(this.Handle, hRgn, true);
            DeleteObject(hRgn);
        }
    }
}
```

I can get the rounded corners. But, the corners doesn't seem smooth. Is there any way to fix this. Any help would be appreciated. Image attached below.

![image](https://user-images.githubusercontent.com/44049406/170438221-9d354689-718d-435a-9ca6-f7e6c4df557e.png)

![image](https://user-images.githubusercontent.com/44049406/170438257-90a4fee8-bd47-4123-a9f2-0b39cd40f0ad.png)

### Steps to reproduce

Run the attached sample. 
[RoundedCornerIssue_Demo.zip](https://github.com/dotnet/winforms/files/8777093/RoundedCornerIssue_Demo.zip)

**Observed** : You can see the corners are not smooth. 
**Expected** : Corners need to be smooth

**Comment by JeremyKuhne** [comment]
This is a function of GDI drawing not being anti-aliased. GDI+ (System Drawing) can draw anti-aliased, but ironically doesn't have rounded rectangles.  Here is a technique to get nice rounded corners:

https://stackoverflow.com/questions/58903526/creating-smooth-rounded-corners-in-winform-applications

Closing as this is the nature of these APIs. Hopefully the above will work for you.

**Comment by MohanramAnbukkarasu** [comment]
Hi Jeremy,

Thanks for the response. But the solution you have provided doesn't include the non client area(title bar) of the form. It makes the FormBorderStyle as None and have rounded corners only with the client area. 

If there any solution to have smooth rounded corners including the non client area of the form. (Without setting FormBorderStyle as None)
