### ISSUE TITLE
SaveFileDialog gives irritating error message when using ransomware protection in Windows 10 or 11

### ISSUE THREAD

**Issue by SommerEngineering** [dotnet/winforms#7228]
### .NET version

.NET 6.0.5 on latest Windows 11 (21H2 / 22000.675)

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

I don't know 🙁 But I don't think so.

### Issue description

When I use a `SaveFileDialog` to create a none-existing file on a modern Windows system with activated ransomware protection, I get the error message: "File not found." 🙄 It would be better, though, to raise a message like e.g. "Cannot write to this directory".

### Steps to reproduce

- Activate the ransomware protection in Windows 10 or 11
- Use my .NET 6 MWE project located here: https://devops.tsommer.org/mwe/issues/BugWinFormsSaveFileDialog
- Run the program
- Click the button
- Navigate into any protected folder
- Try to create a new file
- Getting the error message "File not found." 🙄

**Comment by Alexislml96** [comment]
Maybe I can figure out what is going on here.

**Comment by JeremyKuhne** [comment]
Thanks for the report. Unfortunately, there is not much we can do here. Windows itself reports `ERROR_FILE_NOT_FOUND` in this case. You can see the same behavior by creating a simple console app and trying to write a file to a protected folder (say, via `File.WriteAllText()`). No idea why they wouldn't return something like `ERROR_ACCESS_DENIED`.
