### ISSUE TITLE
Label edit in ListView has incorrect position in accessibility tree 

### ISSUE THREAD

**Issue by dmitrii-drobotov** [dotnet/winforms#7263]
### .NET version

7.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

Once #6309 is merged, edit control of ListViewItem will be placed as a last child of the ListView in accessibility tree (as of now it's a first child). Even though it's the same behavior as in the Windows File Explorer, it seems incorrect and also ignores ListView group structure. A more logical approach would be to put the edit control inside an item it belongs to — similar to DataGridView. See  screenshots and discussion from https://github.com/dotnet/winforms/pull/6309#issue-1073513870 and https://github.com/dotnet/winforms/pull/6309#issuecomment-1147464953 for more info.

### Steps to reproduce

1. Open Inspect or Accessibility Insights tool
2. Build and run WinformsControlsTest app
3. Open ListView window
4. Click twice on any item on the top ListView to start editing it
5. Find Edit control in the accessibility tool

**Comment by merriemcgaw** [comment]
Inconsistent across UI stacks, not that important if we don't have reports of issues. @dmitrii-drobotov - is this something that is quick and easy to fix now?

**Comment by dmitrii-drobotov** [comment]
> Inconsistent across UI stacks, not that important if we don't have reports of issues. @dmitrii-drobotov - is this something that is quick and easy to fix now?

@merriemcgaw at first glance it seems not so easy — a fixed position at the beginning or the end of ListView is much simpler than determining the correct one.

**Comment by MelonWang1** [comment]
Verified this issue in Winforms main branch for .NET 9.0, it was fixed. Label Edit displays under the edited cell. Screenshot as below:
![9782](https://github.com/dotnet/winforms/assets/94418985/b8c29f59-3d38-4416-8c5a-4a909d77b1f8)
