### ISSUE TITLE
Remove obsolete API usage from Winforms

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#7308]
### .NET version

.NET 7.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes

### Issue description

Latest .NET runtime enforcing to discourage use of obsolete APIs in WinForms. This issue is to track obsolete APIs and replace them.

- [ ] AssemblyName.Codebase
- [ ] AssemblyNAme.EscapedCodebase

### Steps to reproduce
refer to work around commit in https://github.com/dotnet/winforms/pull/7306,  https://github.com/dotnet/winforms/pull/7306/commits/564f1c14c355352c598fbec2c63d1fbf25c457f4

**Comment by elachlan** [comment]
Ran into this issue when looking at enabling `IL3000` analyzer.https://github.com/dotnet/winforms/blob/466d7b9dcd22225249e03f1e1e65df8aebc1f3ae/eng/CodeAnalysis.src.globalconfig#L850-L851

**Comment by elachlan** [comment]
@RussKie AFAIK, you can't get `Assembly` from `AssemblyName` directly. Is this correct?

For `AssemblyName.Codebase` replacement, we would have to do:
```CSharp
System.Reflection.Assembly.Load(AssemblyName).Location;
```

**Comment by dreddy-work** [comment]
> @RussKie AFAIK, you can't get `Assembly` from `AssemblyName` directly. Is this correct?

Yes. Other way is fine though. 

> For `AssemblyName.Codebase` replacement, we would have to do:
> 
> ```cs
> System.Reflection.Assembly.Load(AssemblyName).Location;
> ```

Unfortunately, primary scenario where we use `codebase` is a fall back from assembly load failure. `System.Reflection.Assembly.Load(AssemblyName)` failed and WinForms is trying to load assembly from codebase.

**Comment by dreddy-work** [comment]
[commit](https://github.com/dotnet/winforms/commit/564f1c14c355352c598fbec2c63d1fbf25c457f4) has those instances.

**Comment by elachlan** [comment]
@buyaa-n you were involved in the `AssemblyName.Codebase` obsoleting in https://github.com/dotnet/runtime/issues/42857. Do you have any suggestions on how to get a filepath from `AssemblyName`? We usually do this as a fallback from  `Assembly.Load(assemblyName)` in Winforms.

**Comment by buyaa-n** [comment]
Could try produce location from codeBase (like try create a Uri from codeBase and get the LocalPath) and use the API that supports location for getting Assembly as mentioned here https://github.com/dotnet/runtime/pull/70534#discussion_r894197182

**Comment by dreddy-work** [comment]
@buyaa-n, `CodeBase` itself is Obsolete,  what do you mean by extracting location form `CodeBase`?

**Comment by buyaa-n** [comment]
As you already know the suggested alternative is same as `Assembly.Codbase`, i.e use `Assembly.Location` instead. Form the above conversation it looks like assembly is not available in your case. There is no direct replacement for  `Assembly.Location` in `AssemblyName` so to get the correct path, so could try produce it from `CodeBase` and use `Assembly.LoadFrom(path);` to load the assembly

**Comment by dreddy-work** [comment]
> @dreddy-work could the team discuss this in the new year and see if we just remove the fall back code? It will possibly become non-functional in the future.

Yep. Marking it with label so we go over it when we meet next time.  THnak you @elachlan

**Comment by elachlan** [comment]
These are the remaining spots where `CodeBase` is used.
https://github.com/dotnet/winforms/blob/121360996ec9ff4845732d94d3cee3e2d1b9d7c5/src/System.Windows.Forms/src/System/Resources/AssemblyNamesTypeResolutionService.cs#L62-L68

https://github.com/dotnet/winforms/blob/121360996ec9ff4845732d94d3cee3e2d1b9d7c5/src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs#L513-L530

https://github.com/dotnet/winforms/blob/121360996ec9ff4845732d94d3cee3e2d1b9d7c5/src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ToolboxItemTests.cs#L1205-L1250

**Comment by Tanya-Solyanik** [comment]
I suggest keeping these use cases. In the case of the toolbox items, this is a fallback executed after assembly load had failed, if load from the CodeBase fail as well, we are in the same state as without it. And there is no alternative way to find the path. In the case of resources, there is no alternative way to find the path besides loading the assembly, which has undesirable side effects.

**Comment by merriemcgaw** [comment]
In that case, I think we can close this issue until/unless an issue occurs.
