### ISSUE TITLE
ComboBox items accessible objects are leaking in memory

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#7318]
### .NET version

.NET 7.0 Preview 4

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

`ComboBox` items accessible objects are left in memory after the ComboBox control instance with its items was inspected with accessibility tool (like Accessibility Insights or Inspect) and the form with ComboBox is closed, garbage is collected, but accessibility tool is still opened. Same applies for case when ComboBox item is removed from the control's list.

WinDbg snapshot after disposing:
![image](https://user-images.githubusercontent.com/49272759/174151541-acaad3dd-b23f-408a-8804-13beb5aba75c.png)

### Steps to reproduce

Create a parent form with two buttons: one will be opening a child form with the ComboBox control and the other will collect the garbage.
Press the second button to open the child form with ComboBox.
Start the Accessibility Insights tools or Inspect.
Run automated checks for the ComboBox control using AI/Inspect.
Close the child form.
Clear memory with the first button of the parent form.
DON'T close the AI/Inspect tool.
Look for "ComboBox" objects left in memory (using WinDbg, or dotMemory, or another suitable tool).

**Comment by Ashley-Li** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.100-rc.1.22425.12, issue was fixed as below:
![image](https://user-images.githubusercontent.com/56664234/187154845-48cbb702-d98c-429f-9016-1ee41a0ded8b.png)

**Comment by Tanya-Solyanik** [comment]
@Ashley-Li  - these are referenced from static objects and are expected to stay in the memory

**Comment by MelonWang1** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, issue was fixed, test result is same as above screenshot.
