### ISSUE TITLE
DomainUpDown and its elements accessible objects are leaking in memory

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#7328]
### .NET version

.NET 7.0 Preview 4

### Did it work in .NET Framework?

No

### Issue description

DomainUpDown items accessible objects are left in memory after the DomainUpDown control instance with its items was inspected with accessibility tool (like Accessibility Insights or Inspect) and the form with DomainUpDown is closed, garbage is collected, but accessibility tool is still opened. 

WinDbg snapshot after disposing:
![image](https://user-images.githubusercontent.com/49272759/174756564-763eb20a-df5f-4b25-a66c-efe643f41186.png)

### Steps to reproduce

Create a parent form with two buttons: one will be opening a child form with the DomainUpDown control and the other will collect the garbage.
Press the second button to open the child form with DomainUpDown .
Start the Accessibility Insights tools or Inspect.
Run automated checks for the DomainUpDown control using AI/Inspect.
Close the child form.
Clear memory with the first button of the parent form.
DON'T close the AI/Inspect tool.
Look for "UpDown" objects left in memory (using WinDbg, or dotMemory, or another suitable tool).

**Comment by John-Qiao** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.100-rc.1.22425.12, issue was fixed as below:
![7328-TestResult](https://user-images.githubusercontent.com/45864985/187134998-b1be1c69-1645-4839-ba05-4f06fc65e957.png)
![7328-TestResult-2](https://user-images.githubusercontent.com/45864985/187135001-855ee7e6-8610-4ebf-9b2f-b9e82cce7480.png)

**Comment by Nora-Zhou01** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, issue was fixed, test result is same as above screenshot.
