### ISSUE TITLE
[Discussion] Should we remove some documentation-style summary docs

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#733]
E.g. In ExpressionContext.cs

![image](https://user-images.githubusercontent.com/1275900/55875112-1d803000-5b8c-11e9-8d6b-0e4382c6cf4a.png)

I don't think this adds anything to the code as it just duplicates the online docs. Should we remove things like this where it doesn't add any value in explaining what the code does?

**Comment by weltkante** [comment]
Usually I'd expect such design documentation in `<remarks>` (or some other) tags not in the intellisense `<summary>` tags.

How will the docs keep up with the development of .NET Core WinForms? Right now I only see Desktop WinForms docs online, I suppose sooner or later there need to be new design decisions and inner workings documented.

Removing documentation from inline source comments basically causes it to be lost to the repository history, and you have to rely looking it up in an unrelated framework version and hope they still match up.

Just throwing in some things to think about.

**Comment by hughbe** [comment]
I think that the documentation seen by the user when they call Winforms apis doesn’t come from the source code but from xml docs that are then used to generate the docs website. Accordingly I think that (and i know we did this in .net core in CoreFx) we don’t need these comments that simply duplicate the documentation

**Comment by Tanya-Solyanik** [comment]
XML intellisense docs are initially populated from the <summary> comments in code, so these comments are required for the new publics. As to the old comments, I don't have a strong opinion.

**Comment by merriemcgaw** [comment]
This is not something that we can change currently. The Intellisense team is going to use these comments to generate the first .NET Core WinForms IntelliSense. There's not a lot of value in removing these things even later. We can reactivate this issue later for some simple methods where it doesn't add value, but it will need to be later after we have the first set in place.
