### ISSUE TITLE
WinForms Designer ignores custom Form Font in specific case

### ISSUE THREAD

**Issue by deng0** [dotnet/winforms#7345]
### Environment

Visual Studio 2022 17.2.5

### .NET version

6.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

We think this problem might have been introduced with a recent VS update, but we're not sure.

### Issue description

We have noticed that in a specific case the Visual Studio .NET Core Windows Forms designer ignores the custom font that is set for a Form.
The conditions under which the problem occurs seem to be the following:
- ApplicationDefaultFont is defined in csproj file
- The form is set to be localizable
- The form contains a ToolTip component which has GenerateMember property set to true

When a form has a custom font defined (a font different from the one defined as ApplicationDefaultFont), the Designer ignores the font and loads it with the ApplicationDefaultFont instead, which obviously can screw up your layout.

The problem only happens in the Designer, at program run-time everythings seems to work correctly.

### Steps to reproduce

I've created a simple repro project:
[FormFontToolTipProblem.zip](https://github.com/dotnet/winforms/files/8976392/FormFontToolTipProblem.zip)

The project contains 4 Forms, with LocalizableFormWithToolTip being the one where the problem occurs.

All Forms should look the same:
![image](https://user-images.githubusercontent.com/4224837/175542832-52fef00c-7342-4297-aad6-171862bded30.png)

but when LocalizableFormWithToolTip is loaded in the Designer it uses the ApplicationDefaultFont instead:
![image](https://user-images.githubusercontent.com/4224837/175542941-ee06d298-06ec-4126-a568-60b6129b4451.png)

When the ApplicationDefaultFont entry is removed from the csproj, the problem no longer occurs.

**Comment by Olina-Zhang** [comment]
@deng0 @KlausLoeffelmann I checked that simple repro project, the LocalizableFormWithToolTip and LocalizableFormWithoutToolTip forms have two differences: one is just LocalizableFormWithToolTip has tooltip, another is these 2 forms have different custom font set, LocalizableFormWithToolTip form is "Microsoft Sans Serif, 8.25pt" font, and LocalizableFormWithoutToolTip form is "Segoe UI, 12pt", so I think these designer are different. Once setting these 2 forms have same custom font, the designers have same results. This does not seem to be a real problem, is it right?
![CustomFont](https://user-images.githubusercontent.com/26474449/182282713-a7ad0a04-fccd-4c56-9cd7-9432a07c2a41.gif)

**Comment by deng0** [comment]
@Olina-Zhang Thanks for looking into it.

All 4 forms already have the custom font set.
The problem is that the designer ignores the custom font that is already set in LocalizableFormWithToolTip.
This can obviously screw up your layout. And if you forget to set the custom font every time you open the form in the designer, the designer will remove the custom font from the form code alltogether, which will also break the font at runtime.
Even when you set the custom font again and reload the form in the designer, it will keep ignoring the custom font.

**Comment by Olina-Zhang** [comment]
@deng0  I see the result is the form design and corresponding runtime have same display as we set custom font. 
I may not have understood your issue. I just put a textbox to display current form's custom font, you can see 4 forms results, all are expected:
 
![image](https://user-images.githubusercontent.com/26474449/182320884-23084efd-39c9-4f01-b22d-dd463625ae68.png)
![image](https://user-images.githubusercontent.com/26474449/182321059-221b7fac-d36c-41ce-adf2-5ab732c67070.png)
![image](https://user-images.githubusercontent.com/26474449/182321245-14877c09-2315-401c-8c5c-d0b68faf5a54.png)
![image](https://user-images.githubusercontent.com/26474449/182321521-11803b8c-c6cf-40ea-bb20-1ae62ca39dc6.png)

**Comment by deng0** [comment]
The problem is that the WinForms Designer ignores the custom font that is set in LocalizableFormWithToolTip.
In LocalizableFormWithToolTip.resx the custom font is set:
```
  <data name="$this.Font" type="System.Drawing.Font, System.Drawing">
    <value>Segoe UI, 12pt</value>
  </data>
```

But when you open the form in the designer it shows the form's font as "Microsoft Sans Serif, 8.25pt" (ApplicationDefaultFont set in csproj), which is not correct.

Of course you can set the font again in the designer, but this will be ignored again when you reopen it in the designer.

This problem does not happen to the other 3 forms, but only under specific circumstances outlined in my original post.

**Comment by KlausLoeffelmann** [comment]
@RussKie: I guess we would need to be thinking about a localizable Default Font.

**Comment by deng0** [comment]
> @RussKie: I guess we would need to be thinking about a localizable Default Font.

interesting idea, but this doesn't have anything to do with the reported bug, or am I missing something?
IMHO I don't think localizable default font is something that is needed for WinForms at this stage.
If someone really wants to use different fonts for different cultures, he can specify each form's custom font which is localized.

**Comment by KlausLoeffelmann** [comment]
You would need to apply that font then to every Form in your project separately. 
In a project with 400 Forms, that would be not so good.

**Comment by merriemcgaw** [comment]
This is not a broad enough issue for us to address at this time. Thanks for reporting it, and we will can always reopen this issue if more customer demand comes to our attention.
