### ISSUE TITLE
Generated code should be fully qualified

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/winforms#7346]
### .NET version

6.0.202

### Did it work in .NET Framework?

No

### Issue description

If a user's namespace includes `Application`, then the generated code for `ApplicationConfiguration` will result in compile time issues. Controls should be fully qualified to avoid these issues. This is how the [Logging generator](https://github.com/dotnet/runtime/blob/0488519e709811fd6f96aa0aed4c17a72c00898c/src/libraries/Microsoft.Extensions.Logging.Abstractions/tests/Microsoft.Extensions.Logging.Generators.Tests/Baselines/TestWithDefaultValues.generated.txt) works.

**Current:**

```csharp
internal static partial class ApplicationConfiguration
{
    public static void Initialize()
    {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        Application.SetHighDpiMode(HighDpiMode.SystemAware);
    }
}
```

**Desired:**

```csharp
internal static partial class ApplicationConfiguration
{
    public static void Initialize()
    {
        global::System.Windows.Forms.Application.EnableVisualStyles();
        global::System.Windows.Forms.Application.SetCompatibleTextRenderingDefault(false);
        global::System.Windows.Forms.Application.SetHighDpiMode(global::System.Windows.Forms.HighDpiMode.SystemAware);
    }
}
```

### Steps to reproduce

1. Create a new WinForms project `Something.Application`
2. Try to build

**Comment by merriemcgaw** [comment]
This will need to be serviced.

**Comment by Ashley-Li** [comment]
Verified on latest .NET 7 build .NET 7.0.100-rc.1.22378.6, issue is fixed, screenshot as below:
![image](https://user-images.githubusercontent.com/56664234/181700736-52ee7b03-38b6-4c14-951d-50c6fa4a1f26.png)
