### ISSUE TITLE
DataGridView and its elements accessible objects are leaking in memory

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#7347]
### .NET version

.NET 7.0 Preview 4

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

DataGridView and its elements accessible objects are left in memory after the DataGridView control instance with its rows was inspected with accessibility tool (like Accessibility Insights or Inspect) and the form with DataGridView is closed, garbage is collected, but accessibility tool is still opened. Same applies for case when DataGridView row or column is removed from the control's field.

WinDbg snapshot after disposing:
![image](https://user-images.githubusercontent.com/49272759/175655354-ae3adf5c-b128-458b-9e01-1b1a01a6d739.png)

### Steps to reproduce

- Create a parent form with two buttons: one will be opening a child form with the DataGridView control and the other will collect the garbage.
- Press the second button to open the child form with DataGridView .
- Start the Accessibility Insights tools or Inspect.
- Run automated checks for the ComboBox control using AI/Inspect.
- Close the child form.
- Clear memory with the first button of the parent form.
- DON'T close the AI/Inspect tool.
- Update AI/Inspect cached tree to release accessible objects
- Look for "DataGrid" objects left in memory (using WinDbg, or dotMemory, or another suitable tool).

**Comment by Nora-Zhou01** [comment]
Verified on latest 8.0 build .NET 8.0.100-alpha.1.22607.6, issue is fixed. Screenshot as below:
Accessibility Insight:
![AIII](https://user-images.githubusercontent.com/104609169/206602767-7402b24b-315c-4b5a-b984-3f345b8ede8c.png)
Inspect:
![SSSSSS](https://user-images.githubusercontent.com/104609169/206602819-558ad926-411a-4240-a275-26ef7813bd65.png)
Narrator:
![NNNNNN](https://user-images.githubusercontent.com/104609169/206602870-a326812a-2a15-4e18-b71f-01fd3d8a24b3.png)
