### ISSUE TITLE
Suggest to create and use separate method with asserting `HRESULT` of `UiaDisconnectProvider`

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#7357]
### Is your feature request related to a problem? Please describe

We have to check `UiaDisconnectProvider` result every time and check its arguments for null.
Based on [this comment](https://github.com/dotnet/winforms/pull/7319#discussion_r907681735).`UiaDisconnectProvider`

### Describe the solution you'd like and alternatives you've considered

We may create a separate method for `UiaDisconnectProvider` with its result checking and rework it for all places of `UiaDisconnectProvider` calls. For example, rework `UiaDisconnectProvider` and put its result check inside.
Something like this:
![image](https://user-images.githubusercontent.com/49272759/176028365-526f3692-ddfe-4fa1-973d-7c30c43e50a0.png)

### Will this feature affect UI controls?

No, just refactoring.

**Comment by RussKie** [comment]
Sounds good.

**Comment by Tanya-Solyanik** [comment]
Alternatively, we can remove this assert.
