### ISSUE TITLE
ToolStrip class and it's accessible object are leaking in memory

### ISSUE THREAD

**Issue by dkazennov** [dotnet/winforms#7375]
### .NET version
.NET Version: 7.0

### Issue description
ToolStrip and it's accessible object are left in memory after the ToolStrip control instance was inspected with accessibility tool (like Accessibility Insights or Inspect) and the form with ToolStrip is closed, garbage is collected, but accessibility tool is still opened.

ToolStrip.AccessibilityObject
ToolStripButton.ToolStripButtonAccessibleObject
ToolStripMenuItem.ToolStripMenuItemAccessibleObject
ToolStripSplitButton.ToolStripSplitButtonButton

![image](https://user-images.githubusercontent.com/102961955/177276483-195e6dd2-34ba-40e4-8750-67d0f6c1d4fc.png)

### Expected behavior:
Amount of the leaked objects should be minimized to the uncleanable static objects only.

### Steps to reproduce

Create a parent form with two buttons: one will be opening a child form with the ToolStrip control and the other will collect the garbage.
Press the second button to open the child form with ToolStrip.
Start the Inspect tool.
Select the ToolStrip components using the Inspect tool.
Close the child form.
Clear memory with the first button of the parent form.
DON'T close the Inspect tool.
Look for ToolStrip accessible objects left in memory (using WinDbg, or dotMemory, or another suitable tool).

**Comment by dkazennov** [comment]
Retesting during development (with ToolStripForm from main WinformsContolsTest application).

![image](https://user-images.githubusercontent.com/102961955/177533333-820ced86-9a4b-422e-b029-1c7b523147e6.png)

**Comment by dkazennov** [comment]
It appears that RestoreFocusMessageFilter holds ToolStrip and ToolStripAccessibleObject in memory.
![image](https://user-images.githubusercontent.com/102961955/177985012-ebc7d43b-d489-4e0d-9b94-365d4101163d.png)

**Comment by dkazennov** [comment]
Have found a simple way to leave no accessible objects or corresponding control class objects in the Heap.

Result with the Inspect:
![image](https://user-images.githubusercontent.com/102961955/178154691-ebe15484-7910-4e1b-ba1f-bf1ba4f0328b.png)

Result with the Narrator:
![image](https://user-images.githubusercontent.com/102961955/178154708-048173af-84df-44b0-9338-e467bc91b807.png)

**Comment by dkazennov** [comment]
Retested the fix:
![image](https://user-images.githubusercontent.com/102961955/179269085-874c45ad-7738-4082-99e5-760459ad1eb5.png)
Inconsistent with CIT. Requested retest on more time.

**Comment by Ashley-Li** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.100-rc.1.22425.12, issue is not fix as below:
![image](https://user-images.githubusercontent.com/56664234/187188122-04640135-c3f1-4f7e-b9d2-a4ffca9cc049.png)

**Comment by Olina-Zhang** [comment]
@dkazennov Do we need to reactivate this issue?

**Comment by Tanya-Solyanik** [comment]
I th

**Comment by dkazennov** [comment]
> @dkazennov Do we need to reactivate this issue?

Yes I believe we need to reactivate this issue.

**Comment by dkazennov** [comment]
> @dkazennov - I had reverted some of the changes that seemed risky for NET7 (I think) so we need to revisit this fix.

Yes, thanks. Should we open this issue or create a new one? Should we fix in in NET8?

**Comment by dkazennov** [comment]
> [Ashley-Li](/Ashley-Li)

@Ashley-Li could you please describe steps to reproduce this case?

**Comment by Ashley-Li** [comment]
@dkazennov Focused on ToolStrip controls with items in Narrator, Accessibility Insight and Inspect, there still have toolStrip items memory leak. Please see below test result with Narrator:
**Repro steps:**
1.Create a parent form with two buttons: one will be opening a child form with the ToolStrip control and the other will collect the garbage.
2. Press the second button to open the child form with ToolStrip.
3. Start project without debugging.
4. Attaching project to WinDbg and adding symbols folder.
5. Start the Narrator tool.
3. Automatic reading for the ToolStrip control using Narrator.
6. Close the child form.
7. Clear memory with the first button of the parent form.
8. Don't close the Narrator tool.
9. Look for ToolStrip accessible objects left in memory (using WinDbg).

https://user-images.githubusercontent.com/56664234/187402552-1d94c3a6-ba98-4285-ab9a-9508725f63ca.mp4

**Comment by Tanya-Solyanik** [comment]
@dkazennov  - if repro steps are different now, feel free to open a new issue

**Comment by dkazennov** [comment]
@Ashley-Li Hello, could you please open new issue?

**Comment by Ashley-Li** [comment]
@dkazennov @Tanya-Solyanik Have filed a new issue :[#7713](https://github.com/dotnet/winforms/issues/7713)

**Comment by elachlan** [comment]
I was digging through the backlog and found #4808, is that related to the AccessibleObjects? Should that issue be closed in favour of this one?
