### ISSUE TITLE
DoDragDrop to RichTextBox results in AccessViolationException

### ISSUE THREAD

**Issue by willibrandon** [dotnet/winforms#7381]
### .NET version

7.0

### Did it work in .NET Framework?

Yes

### Issue description

As noted in https://github.com/dotnet/winforms/pull/6576#issuecomment-1176883278, I see an `AccessViolationException` when drag-and-dropping to the `RichTextBox` and the operation fails.  I'm not yet sure if it is related to the work done in #6576 or not.

![AccessViolationException](https://user-images.githubusercontent.com/5017479/177667652-425c91ef-2e40-4172-b503-ded4fd250838.png)

### Steps to reproduce

https://user-images.githubusercontent.com/5017479/177667691-10bb7107-eaa2-4c40-807d-46ee0ea24ec5.mp4

**Comment by willibrandon** [comment]
I have a bead on this issue with a potential fix that I'm testing now.

**Comment by willibrandon** [comment]
Please feel free to assign this issue to me.

**Comment by RussKie** [comment]
All yours :) Thank you

**Comment by Cassie-Li01** [comment]
Verified on TP build 7.0.100-rc.1.22425.12, it is fixed. Screenshot as below:
![7381_fixed](https://user-images.githubusercontent.com/96758262/187130694-5880e3fa-8b9f-4e6d-ba4c-19e99acb9552.gif)
![7381](https://user-images.githubusercontent.com/96758262/187130699-44241537-53b0-4b0c-b923-af09901881e7.gif)

**Comment by MandiMan** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, issue was fixed, test result is same as above screenshot.
