### ISSUE TITLE
ListView accessible objects are leaking in memory

### ISSUE THREAD

**Issue by dmitrii-drobotov** [dotnet/winforms#7385]
### .NET version

7.0 Preview 6

### Did it work in .NET Framework?

No

### Issue description

`ListView` accessible objects are left in memory after the `ListView` control instance with its items was inspected with accessibility tool (like Accessibility Insights or Inspect) and the form with `ListView` is closed, garbage is collected, but accessibility tool is still opened. 

WinDbg snapshot after disposing:
![image](https://user-images.githubusercontent.com/102954094/177788817-2635a13d-3d1f-472f-9b78-17d07206b021.png)

### Steps to reproduce

1. Create a parent form with two buttons: one will be opening a child form with the `ListView` control and the other will collect the garbage.
2. Press the second button to open the child form with `ListView`.
3. Start the Accessibility Insights tools or Inspect.
4. Run automated checks for the `ListView` control using AI/Inspect.
5. Close the child form.
6. Clear memory with the first button of the parent form.
7. DON'T close the AI/Inspect tool.
8. Look for `ListView` objects left in memory (using WinDbg, or dotMemory, or another suitable tool).

**Comment by Cassie-Li01** [comment]
Verified on latest .NET 7 build .NET 7.0.100-rc.1.22378.6, issue is fixed, screenshot as below:
Inspect:
![image](https://user-images.githubusercontent.com/96758262/181669194-592472b3-9e46-45e9-8d36-8a172a9efaed.png)
Accessibility Insight 
![image](https://user-images.githubusercontent.com/96758262/181669867-4d476bad-228d-4977-a3ec-21777868df5a.png)
Narrator:
![image](https://user-images.githubusercontent.com/96758262/181670490-ecf9bb1e-06bf-4993-8c54-37ad2198d9e0.png)
