### ISSUE TITLE
ErrorProvider should use the OS error icon

### ISSUE THREAD

**Issue by 0xC0000054** [dotnet/winforms#7390]
### .NET version

6.0.6

### Issue description

The `ErrorProvider` uses a built-in icon resource with Windows 7 styling, this looks out of place on Windows 10/11.
Ideally it should get the default system error icon from the OS using [SHGetStockIconInfo](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shgetstockiconinfo). 

The built-in `ErrorProvider` icon: ![WinForms ErrorProvider icon](https://user-images.githubusercontent.com/26996983/178137141-891719cb-f298-4972-b669-e3ad04ebd420.png)

The Windows 10 21H2 system error icon: ![Win10 Error icon](https://user-images.githubusercontent.com/26996983/178137230-469573c3-3256-4d00-8db8-2d34ddc31336.png)

### Steps to reproduce

I wrote an sample app the demonstrates this issue: https://github.com/0xC0000054/winforms-ErrorProvider-icon

**Comment by merriemcgaw** [comment]
Thanks for filing this! This looks like a good first issue for someone to pick up. If we don't get to it in .NET 7 we'll plan on getting it in .NET 8.

**Comment by Nora-Zhou01** [comment]
Verified on latest .NET 7 build .NET 7.0.100-rc.1.22378.6, issue is fixed, screenshot as below:
![1111](https://user-images.githubusercontent.com/104609169/181724909-be5d9233-77ca-44f0-8d19-f9e228c784b1.png)
