### ISSUE TITLE
Replace IntPtr with nint where it's used as a win32 Handle or LParam or WParam

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#7394]
### .NET version

.NET 7.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

N/A

### Issue description

Dependency flow from Arcade, brought in changes in Analyzers which resulted in RS0017/16 warnings like this one: 
src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Message.cs#L31
src\System.Windows.Forms.Primitives\src\System\Windows\Forms\Message.cs(31,30): error RS0016: (NETCORE_ENGINEERING_TELEMETRY=Build) Symbol 'HWnd.get' is not part of the declared API.

These errors are generated for code like this:
public **IntPtr** HWnd { get; set; }

because the current API is declared in PublicApi.Shipped.txt with IntPtr parameter:
System.Windows.Forms.Message.HWnd.get -> **IntPtr**
but the analyzer expects:
System.Windows.Forms.Message.HWnd.get -> **nint**

To fix the build, I updated the file with unshipped API declarations with nints. 

However, we should review all the cases where .cs declaration contains IntPtr which the txt listing shows nint and potentially replace IntPtrs with nints. This diff will be in unshipped APIs txt files contained in https://github.com/dotnet/winforms/pull/7376

### Steps to reproduce

https://github.com/dotnet/winforms/pull/7376

**Comment by JeremyKuhne** [comment]
We shouldn't change our public APIs to `nint` from `IntPtr`. The question here is whether or not we care about how this shows up in the Shipped/Unshipped.txt files. I presume no? @RussKie?

**Comment by teo-tsirpanis** [comment]
In .NET 7 [`nint` and `IntPtr` will refer to the exact same thing](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#numeric-intptr-and-uintptr) so changing between them does not make any difference.

**Comment by RussKie** [comment]
Since `nint`/`nuint` are aliases I see no issues updating our APIs to match. Also I don't necessarily think the changes need to be recorded as "unshipped" since we aren't technically changing the meaning.
