### ISSUE TITLE
TabPage class and it's accessible object are leaking in memory

### ISSUE THREAD

**Issue by dkazennov** [dotnet/winforms#7415]
### .NET version

.NET Version: 7.0

### Did it work in .NET Framework?

No

### Issue description

TabPage and it's accessible object are left in memory after the ToolStrip control instance was selected with Narrator and the form with ToolStrip is closed, garbage is collected, but Narrator is still opened.

### Steps to reproduce

Create a parent form with two buttons: one will be opening a child form with the TabPage control and the other will collect the garbage.
Press the second button to open the child form with TabPage.
Start the Narrator.
Select the TabPage components using the Narrator.
Close the child form.
Clear memory with the first button of the parent form.
DON'T close the Narrator.
Look for TabPage accessible objects left in memory (using WinDbg, or dotMemory, or another suitable tool).

**Comment by dkazennov** [comment]
With the Narrator there are only two leaks.
![image](https://user-images.githubusercontent.com/102961955/179677786-89b6722e-d0b2-4fa9-897b-5b3a12824343.png)

**Comment by dkazennov** [comment]
Fix result with Inspect and Narrator:
![image](https://user-images.githubusercontent.com/102961955/179707383-55e03da5-5c37-4b0c-844f-d802e4979f0b.png)

**Comment by John-Qiao** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.100-rc.1.22425.12, issue was fixed as below:
![7415-TestResult](https://user-images.githubusercontent.com/45864985/187133300-70ffeaba-7396-4394-b38d-d624efe5bc23.png)

**Comment by MandiMan** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, issue was fixed, test result is same as above screenshot.
