### ISSUE TITLE
How to reference mshtml.dll in the .net core winform project？

### ISSUE THREAD

**Issue by okman523** [dotnet/winforms#747]
* .NET Core Version: (e.g. 3.0 Preview 3, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes/No

**Problem description:**
How to reference mshtml.dll in the .net core winform project？
**Actual behavior:** 

**Expected behavior:**

**Minimal repro:**

**Comment by merriemcgaw** [comment]
We need to do some work around the WebBrowser control.

**Comment by merriemcgaw** [comment]
Are you having problems referencing mshtml.dll? What issues are you running into?

**Comment by merriemcgaw** [comment]
@okman523. Feel free to reopen with more information.
