### ISSUE TITLE
Properties search bar does not appear in .NET Core

### ISSUE THREAD

**Issue by janseris** [dotnet/winforms#7484]
### Environment

VS 2022 17.2.6

### .NET version

.NET Framework 4.7.2, .NET 6

### Did this work in a previous version of Visual Studio and/or previous .NET release?

.NET Framework

### Issue description

Search bar in properties does not show in WinForms controls.
It takes a very long time to scroll for the right property in Controls with a lot of properties instead of searching which is fast.

![image](https://user-images.githubusercontent.com/64279914/180607092-59d71baa-5339-4803-be51-937e200a8b33.png)

### Steps to reproduce

Use WinForms designer in .NET Core.

**Comment by Tanya-Solyanik** [comment]
@janseris - I'm not getting the search bar in properties in  .NET Framework project either. Is a 3rd party extension displaying this search bar?

**Comment by janseris** [comment]
@Tanya-Solyanik hi no I do not have any extensions which would add this.

**Comment by RussKie** [comment]
@janseris your screenshot clearly shows you are using DevExpress controls. The standard property browser never had the filtering capabilities you're referring to AFAIK.

**Comment by janseris** [comment]
@RussKie this is why went into this again and this time I am showing TableLayoutPanel which is 0 % devexpress.
I am trying to test on a machine where I don't have devexpress installed at all to tell if the extension itself adds search to all controls including original Winforms controls

**Comment by janseris** [comment]
@Tanya-Solyanik @RussKie 
Thank you for checking this. I have tested it in VS where DevExpress is not installed on version 17.0.4 and 17.2.6 and none had the search bar in .NET Framework project. I will be solving it with DevExpress.
Thank you for your time

**Comment by RussKie** [comment]
> I have tested it in VS where DevExpress is not installed on version 17.0.4 and 17.2.6 and none had the search bar in .NET Framework project. I will be solving it with DevExpress.
> It is most probably an issue with the DevExpress extension.

👍 

> this would be a very good feature of for people who don't have dx

Yes, this looks like a nice to have feature. Realistically with the current workload we're unlikely to add anything like this in near future, but we'll certainly keep it in mind.

**Comment by janseris** [comment]
@RussKie
 Hi according to Devexpress (https://supportcenter.devexpress.com/ticket/details/t1105258/designer-properties-search-bar-does-not-show-in-net-core) this feature is not available and cannot be because the required API is missing in. NET Core WinForms designer. Then we are moving back here.

**Comment by RussKie** [comment]
DevExpress team can raise the issue directly to us and let us know what API they require to facilitate this functionality. There is nothing we can do here.
