### ISSUE TITLE
Replacing a TreeNode by index in a TreeView adds a blank space below node

### ISSUE THREAD

**Issue by dmitrii-drobotov** [dotnet/winforms#7504]
### .NET version

7.0.100-preview.5.22307.18

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

When setting a new `TreeNode` by index in `TreeNodeCollection`, the old node seems to be not completely removed, leaving a blank space. It also creates an issue from accessibility side, because focusing on this blank space with Narrator throws an unhandled exception.

**Actual behavior:**
Button click executes following code:
```
treeView1.Nodes[0] = new TreeNode(new Random().Next().ToString());
```
![Animation1](https://user-images.githubusercontent.com/102954094/181269932-2971c94a-2ec5-41c7-8020-198a0b0e7985.gif)

* New blank space is added every time node is replaced
* App throws an exception when blank space is focused with Narrator
* There is a memory leak because old node's accessible object is not disconnected

**Expected behavior:**
Button click executes following code to show expected behavior:
```
treeView1.Nodes.RemoveAt(0);
treeView1.Nodes.Insert(0, new TreeNode(new Random().Next().ToString()));
```
![Animation2](https://user-images.githubusercontent.com/102954094/181270917-fdbb7e94-a8c4-4d9e-b123-8d63138a0057.gif)
* No blank space
* No exceptions with Narrator
* Old node's accessible object is disconnected preventing from memory leak

Also, replacing an item by index in other collection-based controls like `ListView` or `ListBox` works without issues.

### Steps to reproduce

Run attached project, click on the Replace button.

[TreeViewReplaceBug.zip](https://github.com/dotnet/winforms/files/9199900/TreeViewReplaceBug.zip)

**Comment by MelonWang1** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.100-rc.1.22425.12, issue was fixed, there is no blank space is add when replacing a TreeNode by index in a TreeView, and no exception throws with Narrator. But there is still a memory leak for TreeViewAccessibleObject.
![bu](https://user-images.githubusercontent.com/94418985/187150060-52968d3f-5ce0-4544-b159-09c28a5538eb.gif)
<img width="611" alt="Annotation 2022-08-29 000500" src="https://user-images.githubusercontent.com/94418985/187150092-3884f6b4-0ca5-46fd-a908-54ef3d75265d.png">

**Comment by Tanya-Solyanik** [comment]
@MelonWang1 - please open a new bug for this leak with repro app attacked, unless the bug already exists.

**Comment by MelonWang1** [comment]
@Tanya-Solyanik I found this attached project has not step to collect the garbage, so i add a button control to **collect the garbage**. [TreeViewReplaceBug (1).zip](https://github.com/dotnet/winforms/files/9451163/TreeViewReplaceBug.1.zip)
Test result is:
!DumpHeap -type TreeView:
<img width="476" alt="treeview-narrrtor" src="https://user-images.githubusercontent.com/94418985/187386216-9764b10c-a5a0-4b0f-a474-4aacf95a7c4a.png">

!DumpHeap -type TreeNode:
<img width="536" alt="treenode-narrtor" src="https://user-images.githubusercontent.com/94418985/187386182-4c61c958-c057-4bb3-acc7-768068022577.png">

**No collect the garbage**, test result is:
!DumpHeap -type TreeView:
<img width="634" alt="treeview-ai-nograbage" src="https://user-images.githubusercontent.com/94418985/187388500-c2d05c99-c4b2-4f39-909a-9a6d0d4de158.png">

!DumpHeap -type TreeNode:
<img width="935" alt="TREENODE-AI-NOGARBAGE" src="https://user-images.githubusercontent.com/94418985/187388552-6b15cd0b-3c60-47da-acfd-2e7e1d67ee3b.png">

Is this is expected?

**Comment by dmitrii-drobotov** [comment]
@MelonWang1 Thank you! This is expected and means there is no memory leak issue.

**Comment by Tanya-Solyanik** [comment]
@MelonWang1 - thank you for the additional investigation!
