### ISSUE TITLE
.NET 7.0 preview DragEnter bug after update to latest versions. 

### ISSUE THREAD

**Issue by c-ohle** [dotnet/winforms#7518]
#### When trying to drag and drop files from folders or other sources into a Windows.Forms.Controls:

NotImplementedException in [IDropTargetVtbl.cs](https://source.dot.net/#System.Windows.Forms.Primitives/Interop/WinFormsComWrappers.IDropTargetVtbl.cs,77)
VS2022 preview, .NET 7.0 preview, SDK, all latest versions.

It works compiled for  .NET 6.0, it worked for all .NET 7.0 previews before.
Example project is available at [GitHub](https://github.com/c-ohle/RationalNumerics)

![image](https://user-images.githubusercontent.com/63112403/181831855-a223c635-d765-4857-883a-3a398c4a61d4.png)

### Reproduction Steps

Should be easy to reproduce: 
VS2022 - New Project - Windows Forms App - .NET 7.0 preview
Form1 - AllowDrop = true; - override OnDragEnter
on file drop -> exception

### Expected behavior

Should work or message/exception if there is a security problem or what ever. 

### Actual behavior

NotImplementedException

### Known Workarounds

no

### Configuration

Processor: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (2112 MHz) × 8
System: Microsoft Windows 10.0.22622 X64 Runtime: .NET 7.0.0-preview.6.22324.4 X64
BigRational: 1.0.0.5 Runtime: v4.0.30319 .NETCoreApp,Version=v7.0 

For Test project on: [GitHub sample](https://github.com/c-ohle/RationalNumerics)

**Comment by dreddy-work** [comment]
@kant2002, can you take a quick look to see if your latest changes in anyway causing this?

**Comment by kant2002** [comment]
I think issue was introduced in https://github.com/dotnet/winforms/pull/6976

**Comment by c-ohle** [comment]
@kant2002 Yes, this seems to be the same problem. But there is something more. 

Since an earlier NET7 version (3 or so) something is wrong with COM refcounts.
For example in my test app: Previously it was possible to drag and drop 3D objects from the 3D view of one app instance to the 3D view of another app instance.
Now the source app instance hangs after a some deep internal COM exceptions.
Compiled with Target NET 6.0 it works.

So it's easy to reproduce with the app:
[https://github.com/c-ohle/RationalNumerics](https://github.com/c-ohle/RationalNumerics)

**Comment by c-ohle** [comment]
@kant2002 Not really important because the exception is handled but maybe as hint:  
This exception is also new since this version. (3 or so) (the exception is in AxIWebBrowser - wrong debug display)

![image](https://user-images.githubusercontent.com/63112403/182017918-70621295-f358-440f-b306-27649e175b76.png)

**Comment by c-ohle** [comment]
@kant2002 and one more hint to reproduce:
Drag and drop still works within views of an app instance.
But app exit -1, which has always been a sure sign of a forgotten COM release call.

> The program '[14228] Test.exe' has exited with code 4294967295 (0xffffffff).

**Comment by merriemcgaw** [comment]
@c-ohle would it be possible for you to provide trimmed down sample code so that we can test the fix from @kant2002 (and hopefully even incorporate it into our test bed somehow)?

**Comment by c-ohle** [comment]
@merriemcgaw hi, the fastest way is really with Test.exe from the [Project](https://github.com/c-ohle/RationalNumerics)
It's all up to date, last check in yesterday, based on [NET7 dev master-branch](https://github.com/dotnet/installer) 
After download change Target framework from NET 6.0 to NET 7.0.
In debug go to TabPage "Polyhedron" and wait for the short animation to finish.
You can move the 3D-objects with mouse. Hold the **Control-Key** to drag-drop 3D-objects.
This works in the current viewport and also when dragging objects onto the desktop. 
- But dragging the objects from the desktop back into the view fails and the exception occurs. 
- There is also a WB based toolbox (right click). Dragging objects from there fails - same exception.
- Run a second instance to check drag-drop between views, normally it works.
- App-exit-code should be 0 (zero). Currently after any drag action (also only within a view) it's -1.

**Comment by Olina-Zhang** [comment]
@c-ohle I tested your Test.exe from the [Project](https://github.com/c-ohle/RationalNumerics), can drag-drop 3D objects from "Polyhedron" TabPage to desktop, but it doesn't allow dragging the objects from the desktop back into the view, is there something wrong with my operation?
![drag-drop](https://user-images.githubusercontent.com/26474449/182553893-e67241cf-f262-419c-abf2-25f1fab78fb0.gif)

**Comment by c-ohle** [comment]
@Olina-Zhang Yes, but that's exactly the problem - the bug in the latest .NET 7.0 preview.
But thanks for testing, now it's certain it's not just my machine.

**Comment by c-ohle** [comment]
@Olina-Zhang 
VS2022 MainMenu\Debug\Windows\Exception Settings 
Common Language Runtime Exceptions - select all 
Then you get it: 'System.NotImplementedException' in System.Windows.Forms.Primitives.dll

**Comment by Olina-Zhang** [comment]
@c-ohle we also created a simple repro project about drag-dropping image on pictureBox in Winforms from file explorer, the DragEnter event cannot be triggered. So it is the same issue in here.
[WinFormsApp14.zip](https://github.com/dotnet/winforms/files/9249403/WinFormsApp14.zip)
![drag-drop1](https://user-images.githubusercontent.com/26474449/182561029-2ab2a354-6640-4221-8807-149f168cef8a.gif)

**Comment by c-ohle** [comment]
@Olina-Zhang good work, now it should be easy for them to reproduce and to add the missing COM interface request.
But please note: There are actually two issues as I mentioned above:
> Since an earlier NET7 version (3 or so) something is wrong with COM refcounts.

The other issue is some versions older and deeper in the system and can not reproduce with a "drop target only app".

**Comment by c-ohle** [comment]
@Olina-Zhang when I switch back to .Net 6.0. it works. Maybe you forgot a rebuild or something?

**Comment by Olina-Zhang** [comment]
> st .Net 7.0, can't repro in .Net 6.0

yes, this issue cannot repro in Net 6.0, you can see my previous comment. When switch app to .Net 6.0, that DragEnter event can be triggered, I set a breakpoint in that app.

**Comment by c-ohle** [comment]
@Olina-Zhang with my app too? This could also be a SDK version(s) conflict - it would not be the first time.
To make sure - you can compile and test the same project with Target NET 6.0 in a offical VS2022 (not preview).

**Comment by c-ohle** [comment]
@Olina-Zhang sorry, yes you said, I misunderstood earlier and focussed on this.

**Comment by Nora-Zhou01** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, issue was fixed, test result is same as above screenshot.
