### ISSUE TITLE
DataGridView displays tooltips for all cells in a selected row, even if the cell is wide enough for its content.

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#7552]
### .NET version

.NET SDK 7.0.100-rc.1.22405.9

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it's not a regression issue, also repro on .NET 6.0.

### Steps to reproduce

1. Open the attached solution: [DGV_DataBind_ToolTip.zip](https://github.com/dotnet/winforms/files/9280770/DGV_DataBind_ToolTip.zip)
2. Extract and open the project.
3. Build and run the project.
4. The DataGridView cell1 in row1 is selected by default, and the current row's cells have mouse tooltips, then hover with the mouse over next rows' cells to observe

### Current Behavior
DataGridView displays tooltips for all cells in a selected row, even if the cell is wide enough for its content.
![test789415](https://user-images.githubusercontent.com/86937911/183386406-813dfbe0-6071-419e-b200-f4b0aab94937.gif)

### Expected Behavior
DataGridView's cell mouse tooltips should follow the documentation description：https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridview.showcelltooltips.

### More Info
1. The initial feedback ticket is: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1585331
2. This issue may be caused by: https://github.com/dotnet/winforms/pull/1681
3. This issue cannnot repro in DataGridView without dataBind

**Comment by merriemcgaw** [comment]
@vladimir-krestov can you take a first look at this?
@Philip-Wang01- what is the behavior in the Framework? Can you test back to 2.0?

**Comment by RussKie** [comment]
The docs are quite thorough, and it looks like we may have missed on of the cases - https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridview.showcelltooltips.

**Comment by Philip-Wang01** [comment]
@merriemcgaw .NET Framework does not seem to support mouse tooltip, which are only displayed when cell text is truncated. Here are the results of .NET Framework 2.0. .NET Framework 4.8 and 3.5 also have the same results.
![testframwork20](https://user-images.githubusercontent.com/86937911/184088001-6462861c-7bb4-4813-9e85-d5eed086efca.gif)
[Framework20.zip](https://github.com/dotnet/winforms/files/9307042/Framework20.zip)

**Comment by dreddy-work** [comment]
@Philip-Wang01 , it is little ambiguous. Can you confirm if it was regression from .NET framework 2.0 ? or it was never an issue with .NET framework but only in .NET core?

**Comment by Philip-Wang01** [comment]
@dreddy-work This is not a regression issue for .NET framework 2.0. .NET Framework does not seem to support mouse tooltip, so there is no such problem. NET Core may have been added default tooltip text to resources for all cells in this PR:  https://github.com/dotnet/winforms/pull/1681. So, this should only be a .NET Core issue.
![image](https://user-images.githubusercontent.com/86937911/186295232-f1a570b0-d1c8-4bff-b2cf-7318624a2c8e.png)

**Comment by vladimir-krestov** [comment]
From the [docs](https://docs.microsoft.com/dotnet/api/system.windows.forms.datagridview.showcelltooltips):
> Remarks
When the value of this property is true and the mouse pointer is over a cell or the user has navigated to the cell using the keyboard, the cell displays a ToolTip when one of the following conditions is met:
> 1. The value of the [DataSource](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview.datasource?view=windowsdesktop-6.0) property is not null or the value of the [VirtualMode](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview.virtualmode?view=windowsdesktop-6.0) property is true, and a handler for the [CellToolTipTextNeeded](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview.celltooltiptextneeded?view=windowsdesktop-6.0) event sets the [DataGridViewCellToolTipTextNeededEventArgs.ToolTipText](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridviewcelltooltiptextneededeventargs.tooltiptext?view=windowsdesktop-6.0) property to a value other than [String.Empty](https://docs.microsoft.com/en-us/dotnet/api/system.string.empty?view=windowsdesktop-6.0).
> 2. The [ToolTipText](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridviewcell.tooltiptext?view=windowsdesktop-6.0) property of the cell has a value other than [String.Empty](https://docs.microsoft.com/en-us/dotnet/api/system.string.empty?view=windowsdesktop-6.0). Setting this property has no effect when there is a [CellToolTipTextNeeded](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview.celltooltiptextneeded?view=windowsdesktop-6.0) event handler because getting the value of the property automatically raises the event and returns the ToolTip text specified in the event handler.
> 3. The cell value is truncated in the cell display. When the value of the cell [ToolTipText](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridviewcell.tooltiptext?view=windowsdesktop-6.0) property value is [String.Empty](https://docs.microsoft.com/en-us/dotnet/api/system.string.empty?view=windowsdesktop-6.0), the full value of the truncated cell value is displayed in the ToolTip.

So:
1. DataGridView ToolTips work according to the documentation in .NET Framework 4.8.1 well.
2. It doesn't work correctly in .NET, so it a regression. Investigating the reasons...

**Comment by vladimir-krestov** [comment]
Mouse tooltips work correctly in .NET Framework.
#1681 added keyboard tooltips only, but it looks like it brought the regression

**Comment by Philip-Wang01** [comment]
Verified this issue in the latest .Net 8.0 SDK build: 8.0.100-alpha.1.22469.15, it is fixed.
![testrepari](https://user-images.githubusercontent.com/86937911/191182735-d743f9fc-e5fb-4fb7-ac72-22dca448db45.gif)
