### ISSUE TITLE
DataSet corrupting Form Designer Code in NET 6

### ISSUE THREAD

**Issue by AberHatschi** [dotnet/winforms#7575]
### Description

So if you create a class something like

`Public Class Test1 Inherits Control End Class`

and compile so you are able to drag this class onto your form. The designer will create these lines: 
`Friend WithEvents Testcontrol1 As testcontrol`
`Me.Testcontrol1 = New ProjectName.testcontrol()`

In this case the designer recognizes ProjectName as a Namespace

However if you add now a DataSet, the designer will treat ProjectName as a new class, and not like a namespace anymore.
So you get error at the constructor of Testcontrol.
If you add the DataSet first and then the control, the designer will even show you another way, it will produce now this code
`Friend WithEvents Testcontrol1 As ProjectName.testcontrol`
`Me.Testcontrol1 = New ProjectName.testcontrol()`
Both lines throwing an error now

This project creates the issue consistently, but you can do it yourself too
[TestReduziert.zip](https://github.com/dotnet/runtime/files/9090418/TestReduziert.zip)
.

### Reproduction Steps

New Windows Form App
Create your own control class to drag on form
compile
drag on form
add a dataset

### Expected behavior

you should be able to compile and start your application

### Actual behavior

Program wont compile, because of error in designer code. (class not defined)

### Regression?

It works in 4.6

### Known Workarounds

You can manually edit the designer code and fix the errors, by deleting the namespace in front of your own class.

### Configuration

NET 6
Windows 10

### Other information

When adding the DataSet there is a new Namespace created `ProjectName.ProjectName` this is causing all of the above problems and makes it also obvious why you can fix it.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann getting this on your radar.

**Comment by KlausLoeffelmann** [comment]
@AberHatschi:
What are your exact steps to create a DataSet and add it to the Form for .NET Apps in this scenario?

Please note, that the _Data Source Provider Services_, which is responsible for Typed DataSet generation, is not enabled for .NET Apps, and therefore we have limited Designer support for (Typed) DataSets. Porting a Form directly from .NET Framework to .NET should work though, and also the Designer should parse the Form OK. On top, you should be able to do basic DataSet based binding operations like changing the bindings for certain Controls on the Form (or UserControl). 

(For more info about DataBinding, please take a look here: https://devblogs.microsoft.com/dotnet/databinding-with-the-oop-windows-forms-designer/)

**Comment by merriemcgaw** [comment]
We're not supporting the DataSourceProviderService in the .NET designer, though we do support Object Data Sources and recommend EF Core.
