### ISSUE TITLE
[Accessibility] Narrator is reading ToolStripMenuitems even when they are disabled

### ISSUE THREAD

**Issue by Cassie-Li01** [dotnet/winforms#7601]
### .NET version

.NET SDK 7.0.100-rc.1.22416.2

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it's not a regression issue, also repro on .NET 6.0.

### Issue description

[Accessibility] Narrator is reading ToolStripMenuitems even when they are disabled
![repro](https://user-images.githubusercontent.com/96758262/185018197-a48fdd96-237c-48bb-8aae-c16657fb40c4.gif)

### Steps to reproduce

1. Create a .NET Core WinForms project with toolStrip/MenuStrip control added
2. Focus on toolStrip/MenuStrip, add some item, right click an item, unchecked Enabled option
3. Build and Run project, Launch Narrator
4. Used keyboard Tab/Tab control/Left/Right to focus all items
5. Check if the Narrator focus and read disabled items
Or open attached project
[WinFormsApp4.zip](https://github.com/dotnet/winforms/files/9355761/WinFormsApp4.zip)

**Current Behaviors:**
Narrator is reading disabled MenuItems
![repro](https://user-images.githubusercontent.com/96758262/185018440-9a22dd86-db82-41ca-a3d0-02b2b1927fd6.png)
![repro](https://user-images.githubusercontent.com/96758262/185018404-40cb63ea-fadd-424f-95da-1788e66a4ad9.gif)

**Expected Behaviors:**
Narrator skips disabled MenuItems

**Comment by NikitaSemenovAkvelon** [comment]
Should we skip all of `ToolStripItem`, including `ToolStripMenuItem`, `ToolStripTextBox`, `ToolStripButton`, etc. or just  `ToolStripMenuItem`?

**Comment by Cassie-Li01** [comment]
Verified on latest .NET 8.0.100-alpha.1.22469.15, issue is fixed. Please cehck below gif and screenshot:
![image](https://user-images.githubusercontent.com/96758262/191161175-72b66088-37d4-4861-bbfd-6f68cdadeb48.png)
![fixed](https://user-images.githubusercontent.com/96758262/191176069-abbcfe5c-2599-486f-aa78-a540a11e5de0.gif)
