### ISSUE TITLE
System.Windows.Forms.KeysConverter.ConvertFrom exception on .NET SDK 7.0

### ISSUE THREAD

**Issue by Ashley-Li** [dotnet/winforms#7610]
### .NET version

.NET SDK 7.0.100-rc.2.22417.1

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it's a regression issue, cannot repro on .NET 6.0.

### Issue description

When running the application with .NET 7.0, an exception pops up, but the same code does not have an exception on .NET 6.0. Please see below gif:
![reproStep](https://user-images.githubusercontent.com/56664234/185374857-64912a0e-67ff-47b5-882b-b7a09383ce9c.gif)

This is the initial feedback ticket: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1590419

### Steps to reproduce
1. Create a .NET 7.0 WinForms application.
2. Add below codes on Program.cs of the Main() method.
 _Console.WriteLine($"Environment.Version: {Environment.Version}");
 const string keyCombination = "Ctrl + N";
 Console.WriteLine($"Converting {keyCombination}to keys");
Console.WriteLine($"Converted keys are: {new KeysConverter().ConvertFrom(keyCombination)}");_
3. Right click the project and press "Alt+Enter" on keyboard , set the **Output type** of the application is Console Application.
4. Build and run the application.

Or 
1. Open attached application : [TestApp.zip](https://github.com/dotnet/winforms/files/9372682/TestApp.zip)
2. Build and run the application(TestAppNET7).

**Current Behaviors:**
An exception dialog pops up, so the printout has missing result.
![image](https://user-images.githubusercontent.com/56664234/185372196-098a1d5a-15ea-413a-bf27-111edde37a84.png)

**Call Stack：**
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key 'N' was not present in the dictionary.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Windows.Forms.KeysConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at TestAppNET7.Program.Main() in C:\Users\v-huli7\Desktop\TestApp\TestApp\TestAppNET7\Program.cs:line 20

**Expected Behaviors:**
There's no exception dialog pops up and the printout results are correct.
![image](https://user-images.githubusercontent.com/56664234/185371974-8d90899f-df65-44a6-acbd-8e5f0b4604db.png)

**Comment by RussKie** [comment]
This would be a regression from #6448

/cc: @gpetrou

**Comment by gpetrou** [comment]
> This would be a regression from #6448

I suspect we just need to use `TryGetValue` instead of `KeyNames[tokens[i]];` and do a null check as before. I can add a PR with a test sometime next week. The changes should be something like the following inside `ConvertFrom`:

```csharp
if (!KeyNames.TryGetValue(tokens[i], out Keys? obj))
{
    // Key was not found in our dictionary.  See if it is a valid value in
    // the Keys enum.
    obj = Enum.Parse(typeof(Keys), tokens[i]);
}

if (obj is Keys currentKey && (currentKey & Keys.KeyCode) != 0)
{
```

**Comment by RussKie** [comment]
Thank you @gpetrou

**Comment by Philip-Wang01** [comment]
Verified on .NET 8.0 latest build from main branch: NET 8.0.100-alpha.1.22451.15, issue was fixed as below:
![isue123](https://user-images.githubusercontent.com/86937911/188079807-952ba3d8-b53a-47b3-93a9-d02325d99dc3.gif)
