### ISSUE TITLE
[Tracking] Consider renaming "up-for-grabs" label to "help wanted"

### ISSUE THREAD

**Issue by danmoseley** [dotnet/winforms#7624]
It is specially recognized by Github. See context https://github.com/dotnet/runtime/issues/71496

You'll want to make sure you update upforgrabs.net https://github.com/up-for-grabs/up-for-grabs.net/blob/f19d7297a01f8e46d9a95ab2bc5ec5511135737a/_data/projects/dotnet-winforms.yml#L14-L15, with a PR like https://github.com/up-for-grabs/up-for-grabs.net/pull/3320

cc @mairaw

**Comment by danmoseley** [comment]
"good first issue" also has special powers, but you already use that.

**Comment by RussKie** [comment]
Thank you @danmoseley, updated.
