### ISSUE TITLE
When executing PSADT package as NT\LOCALSYTEM (default behavior when we deploy the packages inside SCCM), no text is read by the screen reader.

### ISSUE THREAD

**Issue by msftedad** [dotnet/winforms#7658]
### .NET version

.NET version: 6.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

We are using a customized version of PSAppDeployToolkit to create software packages for SCCM. This powershell templating tool can display different popups to the user. We detected two different behaviors of screen readers :
 When executing PSADT package as user the text popup is correctly processed by the screen readers software
 When executing PSADT package as NT\LOCALSYTEM (default behavior when we deploy the packages inside SCCM), no text is read.

Note: PSAppDeployToolkit team concluded that the issue is with WinForms, not with the PSADT. Please refer: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/702

### Steps to reproduce

The Full way : (see below for the short version)

Download PsAppDeployToolkit 3.8.4 (https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/releases)

Extract the “Toolkit” Folder and use cmdlet Unblock-File . in the “Toolkit” and in the “\AppDeployToolkit“ folders to allow further scripts execution

Open “Deploy-Application.ps1” with a text editor

Line 120, replace the whole line by:
Show-InstallationWelcome -CloseApps 'iexplore,msedge' -AllowDefer -DeferTimes 99 -CheckDiskSpace -PersistPrompt

Start Microsoft Edge

Start the Windows Narrator

Right click on deploy-application.exe and “Execute as Administrator”

After a moment, a pop-up is displayed in the OS language:
<image 1>

The inner text and title are read partially => This is the expected behavior

Click on “Close Program” and the pop-up will close and Microsoft Edge will close.

Open the Edge.

Download the Sysinternal https://download.sysinternals.com/files/SysinternalsSuite.zip

Unzip the downloaded file.

Copy the PSEXEC.EXE tool from the Sysinternal folder and paste it in the same folder as Deploy-application.exe exist

Open a command prompt as administrator :

Run command :
"Full\Path\To\Tookit\ psexec.exe present in the Toolkit folder” -i -s "Full\Path\To\Tookit\Deploy-Application.exe"

This will execute the same file but as NT\LocalSystem with interactive session

After a while, the same pop-up appears :
<image 2>

This time no text is correctly read by the Windows Narrator => We are in this context in our SCCM deployments and we want to have a proper reading of the popup in this context.

The Short way :

Create a powershell test file called… test.ps1
Add :
```powershell
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
$form = New-Object Windows.Forms.Form
$form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::FixedDialog
$form.MaximizeBox = $False
$form.MinimizeBox = $False

$form.Text = "Hello world..."
$form.Size = New-Object System.Drawing.Size(400,370)

$label_prez = New-Object System.Windows.Forms.Label
$label_prez.Location = New-Object System.Drawing.Point(20,20)
$label_prez.Size = New-Object System.Drawing.Size(100,20)
$label_prez.Text = "I am a label"

$button_quit = New-Object System.Windows.Forms.Button
$button_quit.Text = "Close"
$button_quit.Size = New-Object System.Drawing.Size(355,40)
$button_quit.Location = New-Object System.Drawing.Size(20,280)
$button_quit.Add_Click(
{
$form.Close();
})
image 2
image 1

$form.AccessibleRole = [Windows.Forms.AccessibleRole]::Dialog
$label_prez.AccessibleRole = [Windows.Forms.AccessibleRole]::StaticText
$form.Controls.Add($label_prez)
$form.Controls.Add($button_quit)
$form.ShowDialog()
```

Save
Execute with: `powershell.exe -file test.ps1`
The pop-up is correctly read by Windows Narrator
Start it as localsystem with : `psexec.exe -i -s powershell.exe “Full\Path\to\test.ps1”`
The pop-up is not read by Windows Narrator

## Expected Results:
When executed as localsystem, the pop-up should be correctly read by screen readers

## Current Results:
Pop-up content is not read. (the demo involves the Windows Narrator, but we get the same result with NVDA)

## Toolkit Version:
PSAppDeployToolkit 3.8.4

## Powershell Version:
Version of Powershell you are using to run the toolkit. For example: 5.1

## Additional context
We provided two ways of testing the behavior of a Powershell WinForms Window, the first involves PSADT and is closer of what we get, the second is just a plain Winforms window without PSADT (so you can see that the behavior is not related to a PSADT bug)

[EDIT] fix formatting

**Comment by RussKie** [comment]
I think @Sulquendi answered the question in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/702#issuecomment-1070931195 - screenreaders run under non-elevated user aren't allowed to interact with apps run under elevated users. UIA is essentially achieved by executing code in the context of a target app, and allowing to do so from a non-elevated user would be a security risk.

**Comment by merriemcgaw** [comment]
@msftedad - we are going to have to close this issue based on what @RussKie and the original issue poster have determined - there's nothing that WinForms can do. This would need to be raised with the Windows team. Can the user run accessibility tools in an elevated context from the very beginning? That would be the solution that we can think of. This is a deeper design discussion than WinForms can participate in. We are just the consumers here.
