### ISSUE TITLE
With Multiple DataGridViews Problem adding columns

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#7667]
### Environment

Version 17.4.0 Preview 1.0

### .NET version

N/A

### Did this work in a previous version of Visual Studio and/or previous .NET release?

I think so at least it worked differently

### Issue description

If you have multiple DataGridView controls on a form attempting to add columns with the same name doesn't work as expected.
With 2 or more DGV's on a Form add some columns to the first, then add the same column names to the second. It fails with message below and then adds the column anyway. I am assuming Column Names need to be Unique on a Form and it's my job to insure that. First that is a pain to do manually, and it would be better if the designer added the DGV name to the column but if that isn't desirable then when the error happens the column should not be added.
![image](https://user-images.githubusercontent.com/12789369/186759569-1b3ca8b0-a63e-4d08-af38-9982ffc45170.png)

### Steps to reproduce

See above

**Comment by merriemcgaw** [comment]
@Olina-Zhang - what is the behavior in Framework in this scenario?

**Comment by Amy-Li03** [comment]
@merriemcgaw, in WinForms Framework project, with 2 DGV on a Form add some columns to the first, then add the same column names to the second, **it fails with message "The name xxx is already in use by another component", and the column cannot be added to the second DGV.**
![image](https://user-images.githubusercontent.com/62929087/191883166-8441e5d1-1494-4fb4-be43-8a64c1f4187c.png)

**Comment by paul1956** [comment]
@merriemcgaw the different is with the current version the column IS ADDED after getting the error message (don't think program will run).  When you hit OK in Framework you can correct the issue and then hit Add or Cancel and designer file is unchanged.

**Comment by merriemcgaw** [comment]
Thanks @paul1956! @Amy-Li03 can you copy this issue into the designer repo so we can try to get it in for the next VS releases? It seems like it would be a pretty simple fix.

~Merrie

**Comment by Amy-Li03** [comment]
@merriemcgaw have copied this issue into designer repo: [4670](https://github.com/microsoft/winforms-designer/issues/4670).

**Comment by merriemcgaw** [comment]
Internal repo shows this as fixed.
