### ISSUE TITLE
[Tracking] Missing Shell32 enums and structs in CsWin32

### ISSUE THREAD

**Issue by fernandanavamoya** [dotnet/winforms#7675]
These enums and structs are missing in CsWin32 library:
- `BFFM`
- `FDEOR`
- `FDESVR`
- `FOS`
- `NIF`
- `NIIF`
- `NIM`
- `NIN`
- `NOTIFYICONDATAW`
- `SFGAOF`

These are also in the [ComImport] interface:
- `FDESVR`
- `FOS`
- `SFGAOF`

**Comment by elachlan** [comment]
@fernandanavamoya, could you please let me know what functions you are using where you couldn't find these? If you could please provide links to them from https://docs.microsoft.com/en-us/windows/win32/ that would be great.

Its best to check the win32metadata using ilspy, I did this for a few below:
FDEOR = `FDE_OVERWRITE_RESPONSE`
FDESVR = `FDE_SHAREVIOLATION_RESPONSE`
FOS = 'FILEOPENDIALOGOPTIONS'

**Comment by elachlan** [comment]
I believe `NOTIFYICONDATAW` is one of the structs that are architecture specific, which winforms will need to manually manage.

CC: @AArnott

**Comment by elachlan** [comment]
@RussKie I think we can close this issue in favour of #7468. If there are specific problems like this issues should be raised in either CsWin32 or Win32Metadata.

**Comment by RussKie** [comment]
Thank you, closing.
