### ISSUE TITLE
Consider adding a drag and drop test from File Explorer

### ISSUE THREAD

**Issue by willibrandon** [dotnet/winforms#7700]
### Issue description

We currently have a handful of drag and drop UI test cases which drag data from and to the application, but we're missing the case when the users drags data from File Explorer to the application. To support the work being done in #5163, and as a regression test for #7518, I propose we add a drag and drop UI integration test which drags data from File Explorer and drops it to the application, in order to catch any potential issues that may result from work being done in that area.

**Comment by willibrandon** [comment]
Please feel free to assign this issue to me.

**Comment by Ashley-Li** [comment]
Verified this issue in the latest .Net 8.0 SDK build: 8.0.100-alpha.1.22469.15, it was fixed. Please cehck below gif: 
![TestResult-700](https://user-images.githubusercontent.com/56664234/191199304-f0ca45ee-c32a-42c6-89e8-5eec61aed77c.gif)
