### ISSUE TITLE
[Accessibility][HC] The icon of DataTimePicker is not clearly visible

### ISSUE THREAD

**Issue by Cassie-Li01** [dotnet/winforms#7705]
### .NET version

.NET 8.0.100-alpha.1.22430.2

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it is not a regression issue

### Issue description

**Current Behavior:**
The icon of DateTimePicker is not clearly
![image](https://user-images.githubusercontent.com/96758262/187814308-f4292a62-082c-44b3-8bbe-1a69fd37996a.png)

**Expected Behavior:**
Normal theme
![image](https://user-images.githubusercontent.com/96758262/187814947-586f494f-1f94-40a8-9dad-5557ae89e81b.png)

### Steps to reproduce

1. Create a WinForms .NET Core application
2. Add DateTimePicker control
3. Build and Run
4. Observe the icon of the DateTimePicker

**More info:**
1. Windows 10 and 11 all have this issue
2. All HC themes have this issue

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik I'm inclined to also won't fix this issue. I don't know that we have control, and to me it looks like the HC version of the icon simply couldn't be made to look reasonable in HC so they left it at the solid page. This isn't an accessibility concern, just a usability concern, but one over which we may have little to no control.

**Comment by Tanya-Solyanik** [comment]
Yes, this is not ours, and is in fact fixed on Win11 22H2 for all themes. The fix is to remove the image - 
![image](https://user-images.githubusercontent.com/15823268/190843576-debd5864-2fde-4d52-bfa1-600cb6327d7e.png)
