### ISSUE TITLE
[HDPI] The Icon of checkbox in DateTimePicker control is burry 

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#7718]
### .NET version

NET 8.0.100-alpha.1.22451.15

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this is not a regression issue.

### Issue description

The Icon of checkbox in DateTimePicker control is burry in high DPI.

Win11 OS:
![image](https://user-images.githubusercontent.com/62929087/188042110-c7db6b06-145f-4024-b1b9-8c22e4f6a9eb.png)

Win10 OS:
![image](https://user-images.githubusercontent.com/62929087/188042266-8804d04e-cced-4d0e-9254-45d94cba4213.png)

### Steps to reproduce

[TestApp.zip](https://github.com/dotnet/winforms/files/9474349/TestApp.zip)

1. Create a WinForms .NET core project.
2. Drag and drop a DateTimePicker to the form designer, set the "ShowCheckBox" as True.
3. Add an App.manifest to this project and uncomment:
```
<!-- Windows 10 -->
<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
```
4. Set Windows DPI as 200%.
5. Build and run this project.

### More info:
1. This is a high DPI issue, and it doesn't repro on 100% DPI.
2. Individual Checkbox control cannot repro this issue.
3. Win10 and Win11 OS all can repro this issue.

**Comment by merriemcgaw** [comment]
This is Windows UI we don't have control over drawing the CheckBox check mark in a DateTime control. So we are going to close this as External. This isn't that common of a scenario so we don't think bringing it to Windows will make a difference either.
