### ISSUE TITLE
BindingSource.Current and Nullable reference types

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#7719]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/BindingSourceCurrent-and-Nullable-refer/10126279)._

---
[severity:It's more difficult to complete my work]
Since `BindingSource.Current` can be `null`, its signature should be changed from 

    public object Current ...
  
to

    public object? Current ...

---
#### Feedback Bot on 8/22/2022, 02:10 PM: 

(private comment, text removed)
#### John Qiao [MSFT] on 8/22/2022, 04:12 PM: 

(private comment, text removed)
#### d.k on 8/24/2022, 04:14 AM: 

(private comment, text removed)
#### John Qiao [MSFT] on 8/24/2022, 06:25 PM: 

(private comment, text removed)
#### d.k on 8/26/2022, 06:17 PM: 

(private comment, text removed)
#### John Qiao [MSFT] on 9/1/2022, 05:47 PM: 

(private comment, text removed)
#### d.k on 9/1/2022, 11:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by John-Qiao** [comment]
Latest reply from customer:

> I dived deeper into the [source code of BindingSource in the .NET Platform Git-hub repository](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs). There, the #nullable disable command in line 5 indicates that the whole BindingSource source code has not been ported to nullability. I then looked into some other random WinForms classes and discovered that only a part of them have already been ported, which came somewhat as a surprise to me. So what I thought being a single bug was rather a symptom for an unfinished work and a premature release. Nothing of this is mentioned in the [“Nullable reference types” article](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) in the documentation. I would therefore suggest adding a warning to the article “Nullable reference types” that the feature has not yet been fully implemented for all .NET 6 classes. A list of what has already been ported and what is still missing would be good, along with a roadmap of when which part of .NET will be ready.

**Comment by RussKie** [comment]
Nullable annotations is an ongoing effort (https://github.com/dotnet/winforms/issues/1107), there has been a significant progress (https://github.com/dotnet/winforms/issues?q=label%3A%22area%3A+NRT%22), however it is far from being complete.
