### ISSUE TITLE
[Win11][HC] The display of buttons and scrollbar controls in the HC theme is not consistent with the normal theme

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#7720]
### .NET version

.NET 8.0.100-alpha.1.22451.15

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it is not a regression issue

### Issue description

**Current Behavior:**
The display of buttons and scrollbar controls in the HC theme is not consistent with the normal theme.
HC Aquatic theme:
<img width="239" alt="Aquatic" src="https://user-images.githubusercontent.com/94418985/188043568-e7570eb4-0854-4122-a71e-c605f69783ee.png">
HC Desert theme:
<img width="236" alt="Desert" src="https://user-images.githubusercontent.com/94418985/188043586-4506c109-cbce-4c27-b1af-4c404b380ba8.png">
HC Dusk theme:
<img width="237" alt="Dusk" src="https://user-images.githubusercontent.com/94418985/188043600-1e4b7c5a-6848-4618-90b3-6d454bb51586.png">
HC Night Sky theme:
<img width="242" alt="Night sky" src="https://user-images.githubusercontent.com/94418985/188043613-c5a6d339-6c5c-4ed4-96be-fb839ce6873a.png">
**Expected Behavior:**
The display of buttons and scrollbar controls in the HC theme is consistent with the normal theme.
Normal theme:
<img width="232" alt="normal win11" src="https://user-images.githubusercontent.com/94418985/188043389-11420e15-5284-48b9-8883-66c00e411411.png">

### Steps to reproduce

1. Turn on High Contrast theme in Windows settings
2. Create a WinForms .NET core project
3. Add abutton, VScrollBar and HScrollBar control
4. Ctrl+Shift+A add a Application Manifest File and uncomment windows 10
5. Build and run

**More Info:**
1. This issue is repro on all HC themes.
2. This issue is repro on framework project.

**Comment by merriemcgaw** [comment]
I'm going to resolve this one as by design. The Common Controls team didn't change the UI for ScrollBars in HC themes it looks like. We don't have a lot of control here regardless, so there's not much we can do. And the scrollbar outlines do look OK in HC mode.
