### ISSUE TITLE
[.Net Core][LOC]The item '(none)'  in PropertyGrid is not translated in .Net core.

### ISSUE THREAD

**Issue by Jessie-Zhang01** [dotnet/winforms#776]
**OS:** RS3 X64 JPN
**VS:**  Dev16 16.1 d16.1 branch 28811.12 build JPN
**.NET Core:** 3.0.100-preview4-011198 from Release branch

**More info:**
This issue also can reproduce with all 13 local languages: CHS, CHT, CSY, DEU, ESN, FRA, ITA, JPN, KOR, PLK, PTB, RUS, TRK

**Steps to reproduce:**

1. Install the .NET Core 3.0 SDK from https://github.com/dotnet/core-sdk for Release branch.
2. Open the .NET Core app from \\\mlangfs1\public\Winforms\CoreTest\LocalValidation\WindowsFormsApp4.zip in VS.
3. Run it and observe the ‘ImageList’ component in PropertyGrid.

**Actual:** The item '(none)' in PropertyGrid is not translated in .Net core.
![image](https://user-images.githubusercontent.com/45864649/56102896-87208580-5f62-11e9-9d36-3eba1d7363bb.png)

**Expected:** The item '(none)' in PropertyGrid should be translated in .Net core. 
Following is the screenshot of .Net framework, it is translated.
![image](https://user-images.githubusercontent.com/45864649/56102883-7708a600-5f62-11e9-9538-6e115e12a7ef.png)

**Comment by dreddy-work** [comment]
@zsd4yr , can you follow up on this?

**Comment by zsd4yr** [comment]
There appears to be an entry for this in SR.resx for System.Windows.Forms

here is (none) showing up
![image](https://user-images.githubusercontent.com/10677481/56509524-10443900-64dc-11e9-8542-bb14ceaf2cd5.png)

**Comment by zsd4yr** [comment]
there also appears to be an entry in SR.ja.xlf for this attribute:

      <trans-unit id="toStringNone">
        <source>(none)</source>
        <target state="translated">(なし)</target>
        <note />
      </trans-unit>
```

**Comment by zsd4yr** [comment]
repros on all languages.

@Tanya-Solyanik @dreddy-work what type on these objects (example: ImageList) populates the property browser in this way?

**Comment by dreddy-work** [comment]
@zsd4yr , i think it was an empty image list.  check if the code is coming from winforms for this and test is set to SR.*

**Comment by merriemcgaw** [comment]
@vivmishra this is likely another example of where corefx not being localized having weird results in WinForms. Moving this to future.

**Comment by vivmishra** [comment]
Yes, we expected such issues to crop up due to underlying layers not being localized. Moving to future is fine here. Hopefully, we can get CoreFX loc'ed in future release.
