### ISSUE TITLE
Help! We need charts!

### ISSUE THREAD

**Issue by acentrella13** [dotnet/winforms#7761]
### Environment

Visual Studio 2019 / 2022

### .NET version

5.0 on

### Did this work in a previous version of Visual Studio and/or previous .NET release?

yes

### Issue description

We can not design charts or have access to the control in 5.0 on... there are thousands of winforms developers still requiring the development of charts in their forms...please help to add this support!

### Steps to reproduce

Try to create a chart

**Comment by acentrella13** [comment]
Sorry but why is this marked closed?  Those aren't answers or solutions, merely point to band-aids...  we need charts supported in winforms .net 5.0 and greater, thank you

**Comment by RussKie** [comment]
[System.Windows.Forms.DataVisualization](https://github.com/dotnet/winforms-datavisualization) is officially deprecated, if you depend on this control you can fork it and update it as you see fit. 
@kirsan31's fork is likely the most up-to-date.
