### ISSUE TITLE
ComboBox control with DropDownList style should not support Value UIA pattern

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#7762]
ComboBox controls are required to provide Value pattern ([IValueProvider](https://docs.microsoft.com/en-us/windows/desktop/api/UIAutomationCore/nn-uiautomationcore-ivalueprovider))	 only if the end user can add arbitrary values according to [documentation](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-supportcomboboxcontroltype). 

<html>
<body>

IValueProvider | Depends | If the combo box can take arbitrary text values, the Value control pattern must be supported. This pattern enables the string contents of the combo box to be set programmatically. If the Value control pattern is not supported, the user must select from the list items within the subtree of the combo box.
-- | -- | --

</body>
</html>

However we [support](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs#:~:text=%7D-,internal%20override%20bool%20IsPatternSupported(UiaCore.UIA%20patternId),%7D,-return%20base) this pattern unconditionally.

As a result, user will be tempted to enter an arbitrary value into the accessibility tools, will get a success result code but the desired value will not be assigned.
The below screenshot reflects inspect experience with the WinformsControlsApp:
![image](https://user-images.githubusercontent.com/15823268/189775137-71001d44-ff91-44eb-bb2a-67d2409c95fb.png)

The text value entered(via Actions->Value.SetValue) is not available among the DropDownList values. and is not displayed in the combo's edit box, yet inspect reports success. 

The same problem exists on .NET Framework 481

**Comment by merriemcgaw** [comment]
This has been the case since 3.5, and no complaints have been seen from providers or users at this point. There's the potential who expect Value Pattern for this style would be broken if we remove it without a quirk. But, on the other hand, they shouldn't be expecting this pattern.

Given that there's no feedback asking for this fix, I want to close this issue, until someone does flag the issue and we can reopen it.
