### ISSUE TITLE
[.NET Core][LOC] The .NET Core Winforms app Template Name ‘Windows Forms App’ is not translated in Create a new project page

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/winforms#777]
**VS:** Version 16.1.0 Preview 2 [28811.12.d16.1]
**OS:** RS3 X64 CHS
**.NET Core**: 3.0.100-preview4-011198 from Release branch
**Affected Languages:** CHS, CHT, CSY, DEU, ESN, FRA, ITA, JPN, KOR, PLK, PTB, RUS, TRK 

**More info:**
This issue also can reproduce with all 13 local languages: CHS, CHT, CSY, DEU, ESN, FRA, ITA, JPN, KOR, PLK, PTB, RUS, TRK

**Steps to reproduce:**
1. Install the .NET Core 3.0 from https://github.com/dotnet/core-sdk. 
2. Launch VS and click the ‘Create a new project’ item in the Get started page.
3. Then find the Windows Forms app (.NET Core) template in the Create a new project page.

**Actual Result:**
The template name ‘Windows Forms app’ is not localized.
![CHS](https://user-images.githubusercontent.com/38325459/56103784-1af45080-5f67-11e9-9e69-06a79dfdd034.png)

**Expected Result:**
The template name ‘Windows Forms app’ should be localized corresponding to the Framework template name.

**Comment by dreddy-work** [comment]
@zsd4yr  can you please follow up with @jmarolf  on this?

**Comment by jmarolf** [comment]
@dreddy-work can you move this issue to dotnet/templates?

**Comment by merriemcgaw** [comment]
Issue moved to [dotnet/templates #98](https://github.com/dotnet/templates/issues/98) via [**ZenHub**](https://www.zenhub.com/)
