### ISSUE TITLE
[Cleanup] Remove Contract.Requires - they aren't used in .NET Core projects

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#778]
We removed these in corefx/coreclr, and probably should do so in winforms.

However: do we want to replace these with an exception that validates the contract - e..g 
```cs
protected virtual void OnHelpRequested(HelpEventArgs hevent) {
    Contract.Requires(hevent != null);
    HelpEventHandler handler = (HelpEventHandler)Events[EventHelpRequested];
    if (handler != null) {
        handler(this,hevent);
        // Set this to true so that multiple events aren't raised to the Form.
        hevent.Handled = true;
    }

    if (!hevent.Handled) {
        if (ParentInternal != null) {
            ParentInternal.OnHelpRequested(hevent);
        }
    }
}
```

Note that we have `Contract.Requires(hevent != null);` but this is ignored, and leads us to possibly throw NREs elsewhere

**Comment by weltkante** [comment]
Looking into the Desktop WinForms assembly it looks like it didn't make use of Contract.Requires (it is not present and no replacement was compiled in via tooling), so if you start to verify contracts now it might become a breaking change if it could run through as a no-op in Desktop Framework.

If you want to start verifying the contracts it probably requires looking at every single case to avoid adding breaking exceptions which were no-ops before.

**Comment by hughbe** [comment]
The changes would be breaking - IMO in the cases of the `protected virtual OnXYZ...` methods (such as that above) we can just remove the contract instead of verifying things. If we're adding argument validation that should be done on a case-by-case basis
