### ISSUE TITLE
DataGridView Flaky tests due to invalidatedCallCount

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#7799]
### Test

DataGridView_ColumnHeadersHeightSizeMode_SetNonResizeThenResize_RestoresOldValue
DataGridView_ColumnHeadersHeightSizeMode_SetWithHandle_GetReturnsExpected
DataGridView_ColumnHeadersHeight_SetWithHandle_GetReturnsExpected
DataGridView_ColumnHeadersHeight_SetWithParentWithHandle_GetReturnsExpected
DataGridView_OnColumnHeadersHeightChanged_InvokeWithHandle_CallsColumnHeadersHeightChanged
DataGridView_OnColumnHeadersHeightSizeModeChanged_InvokeWithHandle_CallsColumnHeadersHeightSizeModeChanged
DataGridView_OnRowHeadersWidthChanged_InvokeWithHandle_CallsRowHeadersWidthChanged
DataGridView_OnRowHeadersWidthSizeModeChanged_InvokeWithHandle_CallsRowHeadersWidthSizeModeChanged
DataGridView_Parent_SetWithHandle_GetReturnsExpected
DataGridView_RowHeadersWidthSizeMode_SetNonResizeThenResize_RestoresOldValue
DataGridView_RowHeadersWidthSizeMode_SetWithHandle_GetReturnsExpected
DataGridView_RowHeadersWidth_SetWithHandle_GetReturnsExpected
DataGridView_RowHeadersWidth_SetWithParentWithHandle_GetReturnsExpected
DataGridView_TopLeftHeaderCell_GetWithHandle_ReturnsExpected
DataGridView_TopLeftHeaderCell_SetWithHandle_GetReturnsExpected

### Issue description

All these tests may randomly fail due to extra invalidations. This happens when the mouse pointer is above any cell of DataGridView. We can't properly fix this now because of:
- UTs are run in parallel therefore we can't set the mouse pointer and guarantee that it will not be moved until the test is done.
- DataGridView without columns does not visually display the left top header, but still tries to invalidate it's area. https://github.com/dotnet/winforms/issues/8535

Affected issues:
https://github.com/dotnet/winforms/issues/6597 It's hard to say if they are all, but probably yes.
https://github.com/dotnet/winforms/issues/6739
https://github.com/dotnet/winforms/issues/6926

**Comment by merriemcgaw** [comment]
@dmitrii-drobotov can anyone on your team take a look at this flaky test issue? It might be good to get it on the backlog.

**Comment by kirsan31** [comment]
@merriemcgaw 
> @dmitrii-drobotov can anyone on your team take a look at this flaky test issue? It might be good to get it on the backlog.

We already discussed it [here](https://github.com/dotnet/winforms/issues/6926#issuecomment-1246567369) and had a plan.
But I really don't know when I can get to it 😔

**Comment by dmitrii-drobotov** [comment]
@kirsan31 - thank you for the context. I will add it to our backlog, maybe someone on the team will be able to take a look as well.

**Comment by merriemcgaw** [comment]
@kirsan31 - sorry I missed that, my bad! I will let you and @dmitrii-drobotov figure out which one of you can get to it first and go from there. We _always_ appreciate the community pitching in, especially with some of the things we know the feature team can't quite get to. Thanks for being such a great contributor!

**Comment by dkazennov** [comment]
Extra invalidation in given tests will be commented out (with reference to this Issue as was [proposed ](https://github.com/dotnet/winforms/issues/6926#issuecomment-1246567369) by @RussKie).

**Comment by Tanya-Solyanik** [comment]
@dreddy-work - how do you feel about having commented out code in tests? I'm against it because the issue is already documenting the problem. I would remove the unused code and data and keep the reference to the issue.

**Comment by merriemcgaw** [comment]
> @dreddy-work - how do you feel about having commented out code in tests? I'm against it because the issue is already documenting the problem. I would remove the unused code and data and keep the reference to the issue.

That seems appropriate to me.
