### ISSUE TITLE
Consider adding drag and drop UI tests that drop serialized and non-serialized objects

### ISSUE THREAD

**Issue by willibrandon** [dotnet/winforms#7875]
### .NET version

.NET 7.0 RC1

### Did it work in .NET Framework?

Yes

### Issue description

As a result of #7864, we could use some drag and drop tests which drop serialized and non-serialized data to the application, to catch any regressions that might arise from work being done in this area. I've written 2 tests covering both the serialized and non-serialized scenarios, with the serialized case working as expected, and the non-serialized case failing, as reported by the customer. Initial results show that the fix in #7869 alleviates the issue described in #7864. I can submit a PR with the tests.

### Steps to reproduce

Drag and drop non-serialized custom type

1. Create a `DataObject` instance.
2. Create an instance of a custom non-serialized object.
3. On `MouseDown`, call `DataObject.SetData` to store the non-serialized object in the data object.
4. On `MouseDown`, call `Control.DoDragDrop`.
5. On `DragOver`, call `DataObject.GetData` to retrieve the non-serialized object from the data object.
6. Verify that the object retrieved from `DataObject.GetData` is not `null`.

**Comment by Amy-Li03** [comment]
Run the drag and drop UI test cases: DragDrop_NonSerializedObject_ReturnsExpected_Async and 
 DragDrop_SerializedObject_ReturnsExpected_Async, all passed with no errors.
