### ISSUE TITLE
[API Addition] Message.GetLParam<T>()

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#792]
We currently have
```cs
public class Message
{
        // ..
        public object GetLParam(Type cls) => Marshal.PtrToStructure(LParam, cls);
        // ..
}
```

However, this is implemented using `Marshal.PtrToStructure` which has been obsoleted. I propose adding a new API that uses the un-obsoleted marshal API:

```cs
public class Message
{
        // ..
        public T GetLParam<T>() => Marshal.PtrToStructure<T>(LParam);
        // ..
}
```

This would avoid the need for all the casting, e.g
```cs
NativeMethods.NMHDR nmhdr = (NativeMethods.NMHDR)m.GetLParam(typeof(NativeMethods.NMHDR));
```

**Comment by zsd4yr** [comment]
How many instances would be affected by this change? 

Are you proposing we add this API to message in additional to the obsolete one or instead of the obsolete one? If you are proposing the latter, how would other people porting their apps detect this breaking change?

**Comment by sharwell** [comment]
If possible (i.e. if `T` is blittable), it would be more efficient to implement this as returning `ref readonly T`.

**Comment by hughbe** [comment]
So this API addition would be strictly non-breaking to existing users - although we may choose to obsolete the old api that’s a decision to be make by others. 

@sharwell How do we marshal an IntPtr to a blittable struct? Do we just call `ToPointer` then do some unsafe sorcery?

**Comment by sharwell** [comment]
```csharp
internal static unsafe ref readonly T GetParam<T>(IntPtr ptr)
    where T : unmanaged
{
    return ref *(T*)ptr;
}
```

**Comment by hughbe** [comment]
Nice - will bear that in mind!

However, I'm not sure if we can have the following APIs?
```cs
public class Message
{
        // ..
        public object GetLParam<T>() => Marshal.PtrToStructure<T>(LParam);
        public ref readonly T GetParam<T>() where T :unmanaged
        {
            unsafe
            {
                return ref *(T*)ptr;
            }
        }
}
```

Sadly APIs can't differ by return type or constraints

**Comment by weltkante** [comment]
You probably want to return `T` and not `object` in the first case, to avoid boxing the struct? `Marshal.PtrToStructure<T>` doesn't return object either.

**Comment by sharwell** [comment]
For my local experiments, I used three methods:

```
T GetLParam<T>();
ref T GetLParamRef<T>() where T : unmanaged;
ref readonly T GetLParamRefReadonly<T>() where T : unmanaged;
```

**Comment by hughbe** [comment]
@sharwell do you reckon that something like this could be a useful addition to the `Marshal` class itself?

```cs
.. ref Marshal.PtrToStructureRef<T>
``
etc.

**Comment by zsd4yr** [comment]
#835 is adding these as internal to get the benefits. We should consider this API change.
