### ISSUE TITLE
Form designer is not loaded successfully when switching application's target framework from 7.0 to 8.0 in project's properties window

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7939]
### .NET version

8.0.100-alpha.1.22512.32

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro when switching application's target framework from .Net 6.0 to .Net 7.0

### Issue description

Form designer cannot be loaded successfully when switching application's target framework from 7.0 to 8.0 in project's properties window
![image](https://user-images.githubusercontent.com/26474449/195561960-93cd1357-279a-4618-b55a-b314c7167bc3.png)

### More Info
1. This issue cannot repro when creating Winforms .Net 8.0 application directly
2. This issue cannot repro when changing target framework in application's csproj file from net7.0-windows to net8.0-windows directly 

### Steps to reproduce

**Repro steps:**
1. Create a Winforms **.Net 7.0** application
3. In Solution Explorer, right click application node, and choose **Properties** 
4. Expand Target framework, choose .Net 8.0
5. Build this application

There has an error in csproj file about missing -windows, then add it 
![image](https://user-images.githubusercontent.com/26474449/195563185-377b6e27-b58f-4234-889a-f48b0cc5f936.png)

6. Build this application again without any error
7. Open form designer again

Result: Form designer is loaded very long time, and failed finally with an error

**Comment by dreddy-work** [comment]
related https://github.com/microsoft/winforms-designer/issues/4714

**Comment by merriemcgaw** [comment]
Closing as External. We'll track internally to make sure that once .NET 8 SDK is inserted into VS everything works as expected.
