### ISSUE TITLE
Wrong display of selected folder in FolderBrowserDialog in vb.

### ISSUE THREAD

**Issue by Perpete** [dotnet/winforms#7968]
### .NET version

Version .NET 6

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

I dont know.

### Issue description

Hello,

With version 17.6.3 of visual studio with .Net 6 with a WinForm project in VB language, I use the FolderBrowserDialog dialog.
I initialize the SelectedPath property with the value: "P:\Gestion_REDWOOD".
When displaying the dialog, I notice that the folder name displayed in the text box is truncated.
The displayed and selected text is “estion_REDWOOD”.
If I move the cursor to the beginning of the text or if I press the "Home" key, I can see all the text.
The problem is the same with a WPF project.

Here is my test code:

`Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click

	Dim selectPath As String

	Dim openFolderDialog As New FolderBrowserDialog()
	openFolderDialog.SelectedPath = "P:\Gestion_REDWOOD"
	openFolderDialog.Description = "Dossier de destination sur le cloud"
	If openFolderDialog.ShowDialog = DialogResult.OK Then
		selectPath = openFolderDialog.SelectedPath
	End If

End Sub`

Here is a screenshot:

![FolderBrowserDialog1](https://user-images.githubusercontent.com/66659162/196631116-38ed1fb6-15dd-4dc5-8029-43176ee1be23.gif)

### Steps to reproduce

See description

**Comment by Perpete** [comment]
Hello,

The problem is also present with the "OpenFileDialog" dialog box.
The file name is also truncated.

Here is a piece of code for testing:

`
'Sélection du nom du fichier Access à sauvegarder sur le cloud

		Dim openFileDialog As New OpenFileDialog()

		'Sélectionne le dossier et fichier par défaut
		If File.Exists(txtFileSave.Text) = True Then
			openFileDialog.InitialDirectory = txtFileSave.Text
			openFileDialog.FileName = "Gestion_Tables.accdb"
		Else
			openFileDialog.InitialDirectory = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)
		End If

		openFileDialog.Title = "Sélection du nom du fichier Access à sauvegarder sur le cloud"
		openFileDialog.Filter = "Microsoft Access (.accdb)|*.accdb"
		If openFileDialog.ShowDialog() = True Then
			txtFileSave.Text = openFileDialog.FileName
		End If
`
![openFileDialog](https://user-images.githubusercontent.com/66659162/196638282-8e2cffd8-4505-4e85-9b05-629c19554f35.png)

**Comment by dreddy-work** [comment]
@Perpete, this seems an issue with native control here. Did you try a c++ (MFC) app? If it repro there, we may need to redirect this to Windows Operating System team.

**Comment by Perpete** [comment]
Hello,
@dreddy-work, I don't know C++ code.
I have never used it.

**Comment by dreddy-work** [comment]
@Olina-Zhang , can you guys try this and see if it repro for native apps as well?

**Comment by Perpete** [comment]
Hello,

Seems to be an old problem that has never been fixed.

https://stackoverflow.com/questions/60182612/default-filename-appears-truncated-in-windows-ifiledialog
https://stackoverflow.com/questions/24525606/openfiledialog-cuts-off-pre-populated-file-name
https://stackoverflow.com/questions/58171140/initialfilename-of-filedialog-doesnt-display-whole-file-name
https://social.msdn.microsoft.com/Forums/vstudio/en-US/fdef2a08-d90d-4c87-adb1-9963f5bf41e3/openfiledialog-file-name-not-correctly-justified?forum=wpf)

**Comment by RussKie** [comment]
As https://stackoverflow.com/q/60182612/2338036 indicates this is a Windows-level bug.

There are other tickets raised for this issue. E.g.:
* https://developercommunity.visualstudio.com/t/problem-in-display-of-initial-filename-i/1594820?q=OpenFileDialog
* https://developercommunity.visualstudio.com/t/Wrong-display-of-selected-folder-in-Fold/10176303?q=OpenFileDialog&page=1


/cc: @singhashish-wpf

**Comment by Perpete** [comment]
Hello
Does the problem go back to windows?

**Comment by merriemcgaw** [comment]
As @RussKie indicated this definitely is a Windows issue, and there's not really anything we can do on our end. It works the same way for any of the UI stacks that ultimately call into this Win32 dialog, and there's not much we can do on our end to work around the issue. My recommendation is for you as a customer to file feedback directly in Windows. You as a customer are likely to get more traction on the issue, though given how long the issue has been reported, it may not be a high priority for the Windows team however, as this UI is considered legacy.

**Comment by dreddy-work** [comment]
Notified windows team. @Perpete, filing feedback directly via Feedback Hub help you track progress on it. Closing this as external issue.

**Comment by Perpete** [comment]
Hello,
I reported the problem in Windows Feedback Hub.
It is titled "Folder or file name display problem when using dialogs from WIN32 APIs.".
