### ISSUE TITLE
Form.TopMost - Not Working when moving to .NET 6

### ISSUE THREAD

**Issue by deinok** [dotnet/winforms#7970]
### .NET version

Checked with VB.NET 6 and VB.NET 7

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Working on VB.NET Framework 4.8

### Issue description

Moving an application from the TargetFramework `net48` to `net6.0`. (Written in VB.NET)

We have a small WinForms application that has the main Form with `TopMost` at `True`. 
A SCADA program starts the WinForms application. (The SCADA program looks like calls `SetWindowPos(HWND_TOPMOST)` or an equivalent).

When using .NET 4.8, the WinForms app is properly on the foreground. But just changing the target framework to `net6.0-windows` and the WinForms is no more in the Foreground as a TopMost Form.

We use `Microsoft.Extensions.Hosting` to handle the LifeCycle, just like this, nothing more special:
![image](https://user-images.githubusercontent.com/6586053/196703140-dd8a5177-90d9-477f-9ff8-51895ee82818.png)

`Principal` is the Form with the TopMost enabled in the Designer

### Steps to reproduce

I'm unable to give a proper reproduction step, as it only happens when the SCADA software is enabled.

**Comment by RussKie** [comment]
> I'm unable to give a proper reproduction step, as it only happens when the SCADA software is enabled.

To confirm, do I understand it correctly that the issue is not observed if you don't use the 3rd part library?

**Comment by deinok** [comment]
Hi @RussKie, the SCADA is not a library, it works like an application as Full Screen and a button on it executes my application my application that I'm trying to transition to .NET 6.

**Comment by RussKie** [comment]
Is the issue reproducible if SCADA not involved? If so - we need a repro, so that we can investigate. If not - then you need to contact the SCADA developers.

**Comment by deinok** [comment]
Hi @RussKie the problem is that with .NET 4.8 that was working. Did you know something that could be changed from .NET 4.8? 
Any way to force it to be as the priority TopMost? Even if it requires DllImporting some WinAPI

**Comment by dreddy-work** [comment]
Does SCADA stand for "Supervisory Control And Data Aquisition" :). 
I don't think we changed any intentionally in this space but given that you are moving form .NET 48 to .NET6.0, bunch of code now runs default that may earlier conditioned under app.config flags. If you could share your application or a simple repro application, we can investigate further.
