### ISSUE TITLE
The original FolderBrowserDialog cannot be opened

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7981]
### .NET version

8.0.100-alpha.1.22514.14 

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

yes, cannot repro in .Net 7.0 

### Issue description

The FolderBrowserDialog cannot be opened when setting AutoUpgradeEnabled as false. This issue cannot be resolved after the PR fixing: https://github.com/dotnet/winforms/pull/7978
**.Net 8.0 result:**
![image](https://user-images.githubusercontent.com/26474449/197107601-cf2f6dc1-80b4-468f-a1d7-d23fbede2461.png)
_System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Cannot evaluate the exception source
  StackTrace:
Cannot evaluate the exception stack trace_

**.Net 7.0 result:**
![image](https://user-images.githubusercontent.com/26474449/197107687-553518b2-767a-487e-b47e-8fb26a8de564.png)

### Steps to reproduce

1. Open the [TestApp.zip](https://github.com/dotnet/winforms/files/9835559/TestApp.zip) project in VS
2. Build and run it
3. Click the button in the form and observe the result

**Comment by elachlan** [comment]
Related: #79

**Comment by RussKie** [comment]
It would be great to add automated tests since this is not the first regression.

**Comment by MelonWang1** [comment]
Verified this on .NET 8.0 latest build: 8.0.100-alpha.1.22552.10, issue was fixed. When click button the folder browser dialog pops up.
![7981](https://user-images.githubusercontent.com/94418985/199679108-92ee056e-e240-466e-a892-8ccffeb8532c.png)
