### ISSUE TITLE
Remove BinaryFormatter for property bag serialization

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#7988]
Our `IPropertyBag` implementations rely on `BinaryFormatter` to serialize to and from a `Hashtable`/`IStream`. `AxHost.PropertyBagStream` and `Control.ActiveXImpl.PropertyBagStream` are the implementations.

In most of the places we've removed `BinaryFormatter` we've relied on `TypeConverter` to convert to/from either `string` or `byte[]`. The idea here is to serialize to/from JSON (using System.Text.Json) with this same dependency on `TypeConverter`. If there is no such `TypeConverter` for a given type, it would be ignored. Working around this breaking change would require writing and registering a `TypeConverter` that supports one of these two formats.

#7986 is a related change.

cc: @GrabYourPitchforks

**Comment by elachlan** [comment]
Should we convert from `Hashtable` to `Dictionary<TKey,TValue>` as apart of this change? Does it affect the serialization?

**Comment by JeremyKuhne** [comment]
Resolved with: #9104
