### ISSUE TITLE
Form Designer not showing for .NET 6 project

### ISSUE THREAD

**Issue by fiddyschmitt** [dotnet/winforms#7997]
### Environment

Visual Studio Enterprise 17.3.6

### .NET version

.NET 6

### Issue description

When I open the Form Designer, it is blank. This happens even for a new project. It happens for .NET 6 projects, but the form designer works fine if I create a .NET 4.7.2 project.

I've tried all the suggestions in the [troubleshooting guide](https://github.com/dotnet/winforms/blob/main/docs/designer/troubleshooting.md) - timeout, antivirus & confirming UseLegacyPathHandling is disabled.

I've also tried repairing Visual Studio using the Visual Studio Installer.

Using Task Manager, I can see that the OOP designer (`DesignToolsServer.exe`) starts, but then closes almost immediately. A while later Visual Studio shows `Timed out while connecting to named pipe` which I presume is due to DesignToolsServer.exe not being there to respond.

Is there a way to see the output of DesignToolsServer.exe, to work out why it's closing?

Thanks!

### Steps to reproduce

Create new Project: Windows Form App -> .NET 6.0 (though the same happens for .NET 5 and .NET Core 3.1)
Double-click Form1.cs

**Comment by dreddy-work** [comment]
@fiddyschmitt , can you share the verbose log here? you should find instructions to set log level to verbose in troubleshooting guidelines you linked.

**Comment by fiddyschmitt** [comment]
Thanks @dreddy-work! The verbose output revealed that it was DPI awareness causing the problem. (Something I had configured a long time ago).

The fix was to open this registry key:
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers`
And delete the `devenv.exe` value.



For the record, here is the Verbose output I was seeing.

This setting:

```
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.exe"="DPIUNAWARE"
```

Resulted in this error:
```
[10:39:15.156404] fail: [HelloWorld]: Failed to launch design tools server process process
                        System.InvalidOperationException: Failed to set process DPI mode value to: DpiUnaware.
                           at Microsoft.WinForms.Utilities.Desktop.DpiHelper.SetDesignerProcessDpiAwareness(HighDpiMode highDpiMode)
                           at Microsoft.DotNet.DesignTools.Server.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext()
```

And this setting:
```
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.exe"="HIGHDPIAWARE"
```

Resulted in this error:
```
[10:42:14.781446] fail: [pcap2diagram]: Failed to launch design tools server process process
                        System.InvalidOperationException: Failed to set process DPI mode value to: SystemAware.
                           at Microsoft.WinForms.Utilities.Desktop.DpiHelper.SetDesignerProcessDpiAwareness(HighDpiMode highDpiMode)
                           at Microsoft.DotNet.DesignTools.Server.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext()
```

Thanks again,
Fidel

**Comment by dreddy-work** [comment]
@fiddyschmitt , thank you for sharing verbose. DesignToolsServer is a separate process from devenv, though it is launched/triggered by devenv process. This happen only when the designToolsserver process's DpiAwareness is already set and we are trying to set it again. Assuming you are unblocked for now. I will check this scenario and will keep this bug open until i find root cause and see how it needs to be addressed.

**Comment by dreddy-work** [comment]
@fiddyschmitt , can you share which Operating System version you are using this on?

**Comment by fiddyschmitt** [comment]
I see, thanks! Yes unblocked now.
Microsoft Windows 10 Pro Version	10.0.19043 Build 19043

**Comment by merriemcgaw** [comment]
@dreddy-work perhaps we should get this issue added to the troubleshooting guide?

**Comment by fiddyschmitt** [comment]
Thanks, yes adding it to the troubleshooting guide would be nice, given that the DPI suggestion came from MS:

https://learn.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2022

Thanks again,
Fidel

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you take a moment to file an issue in the Designer repo to update the DesignToolsServer process to detect this situation and respond with an erorr message?

**Comment by Olina-Zhang** [comment]
@dreddy-work is this a dup of issue: https://github.com/dotnet/winforms/issues/7609? And you fixed it in designer PR: https://github.com/microsoft/winforms-designer/pull/4578

**Comment by dreddy-work** [comment]
> @dreddy-work is this a dup of issue: #7609? And you fixed it in designer PR: [microsoft/winforms-designer#4578](https://github.com/microsoft/winforms-designer/pull/4578)

It is similar but for the supported modes of designer. If you set the unsupported mode for designer ( in this case, HIGHDPIAWARE, equivalent to PermonV2) we cannot proceed with that mode.

**Comment by Ashley-Li** [comment]
@merriemcgaw @dreddy-work @Olina-Zhang Have filed a designer issue : https://github.com/microsoft/winforms-designer/issues/4743 to track.

**Comment by dreddy-work** [comment]
We are making it easier to set the high PDI of the application in the project file. Documentation was added around it. linked designer bug is closed with same reasoning.
