### ISSUE TITLE
Update the documentation about the templates on learn.microsoft.com for .NET 7 

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/winforms#8015]
learn.microsoft.com features 2 articles where the templates are mentioned:
- https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new#arguments - list of the available templates
- https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates - the documentation on the templates available with .NET SDK, including specific options.

Consider updating the articles for .NET 7:
- in case new templates were added, please them add them to the table list
- in case the template options were added, modified or removed, please adapt the description accordingly

Note that for many cases, the EOL frameworks are present: `netcoreapp3.0`, `net5.0` etc. Consider removing them.

The source code is here:
- https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new.md
- https://github.com/dotnet/docs/blob/main/docs/core/tools/dotnet-new-sdk-templates.md

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann let's work together to decide when and what we want to do.

**Comment by merriemcgaw** [comment]
We have not added new official templates yet. We will update docs when we have a new one. No other teams have updated the out of support templates either.
