### ISSUE TITLE
[Accessibility] The menuItem with Alignment: right setting is not displayed in UIA tree when setting MenuStrip's GripStyle as Visible

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#8033]
### .NET version

8.0.100-alpha.1.22514.14

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No，repro in previous .Net versions: 7.0/6.0 and .Net Core 3.1

### Issue description

The menuItem with Alignment: right setting is not displayed in UIA tree when setting MenuStrip's GripStyle as Visible

.Net 8.0:
![image](https://user-images.githubusercontent.com/26474449/197992664-3312b542-5302-4c6b-92de-250e8543f8a9.png)

.Net Framework 4.8.1:
![image](https://user-images.githubusercontent.com/26474449/197992824-58190ee8-f99d-4b56-a093-ab18c072cf17.png)

### Steps to reproduce

1. Create a Winforms .Net 8.0 application
2. Add a MenuStrip to form designer with "Insert Standard Items"
3. Choose any item, and set its Alignment as Right
4. Set MenuStrip's GripStyle as Visible
5. Build and run application
6. Use AccessibilityInsight or Inspect to check the MenuItems in UIA tree

Tested app:
[MenuStripSample.zip](https://github.com/dotnet/winforms/files/9868207/MenuStripSample.zip)

**Comment by MandiMan** [comment]
Verified on latest 8.0 build .NET 8.0.100-alpha.1.22607.6, issue is fixed. The menuItem with Alignment: right setting could displayed in UIA tree when setting MenuStrip's GripStyle as Visible.please check below screenshot:
![issue8033](https://user-images.githubusercontent.com/108860782/206408900-3c751b90-3941-49cd-b519-9fe2340d2a08.png)
