### ISSUE TITLE
Winforms Designer - Failed to launch the designer server process

### ISSUE THREAD

**Issue by bpradeep771** [dotnet/winforms#8082]
### Environment

Visual Studio Professional 2019  - 16.11

### .NET version

.NetCore - 3.1

### Issue description

In the Winforms project after using “Microsoft.Toolkit.Forms.UI.XamlHost” and setting Platforms is “X64; X86” in the Winforms Netcore project, unable to open the form designer.

please find my source code from the link - [Winforms_Uwp_App](https://drive.google.com/file/d/12xUSk4D5ZD7dp0b3kg4bcBSuEH3H4-29/view)

### Steps to reproduce

I have already reported to the Visual Studio developer community.
please find the discussion [here](https://developercommunity.visualstudio.com/t/Winforms-Failed-to-launch-the-designer-s/10100679).
Please find the video for more info - [video](https://user-images.githubusercontent.com/55428663/184504506-366a66be-cd6e-4312-bd68-bb0a9475db28.mp4)

**Comment by merriemcgaw** [comment]
@bpradeep771 - I suggest that we try having you run this using VS2022, where we have much better diagnostic information. It may also be the case that XAML Islands controls aren't working properly at all, which would be tracked in the [CommunityToolkit repo ](https://github.com/CommunityToolkit/Microsoft.Toolkit.Win32/issues?q=is%3Aissue+label%3A%22XamlIslands+%3Adesert_island%3A%22+)you've already pinged. Unfortunately, if you can't get it to load in VS2022, we won't have enough information to debug further and assistance from those who own XAML Islands is required.
