### ISSUE TITLE
Controls on the Form are truncated on high dpi machines.

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#8089]
### .NET version

.NET 8.0 

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

NO

### Issue description

In PermonitorV2 mode application, child controls placed on the Form, close to border are cut when moved from one monitor to the other with different DPI scaling. It is more evident in anchored controls.

### Steps to reproduce

- Create a simple Form with child controls placed around the border as shown in below pic.
- Set application Dpi mode to PermonitorV2 mode. And run application on a dual monitor with settings 300% primary and 100% secondary.

Actual: 
![image](https://user-images.githubusercontent.com/36968667/199310019-4cd79fae-e3fc-4f98-8778-9dc1c1019484.png)

Expected: 
![image](https://user-images.githubusercontent.com/36968667/199310071-2bf241fe-d250-4fce-9b0e-4bcb19d06c19.png)

**Comment by Ashley-Li** [comment]
Verified this on .NET 8.0 latest build: 8.0.100-alpha.1.22552.11, issue was fixed. Now the margin values are work in these buttons.
![image](https://user-images.githubusercontent.com/56664234/199917897-a7fd3b62-5652-4ef2-b708-908b66fe4595.png)
