### ISSUE TITLE
An exception thrown when opening FileDialog with non-existing InitialDirectory

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#8108]
### .NET version

8.0.100-alpha.1.22552.11

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro previous released .Net versions

### Issue description

An exception thrown when opening FileDialog with filters

**.Net 8.0:**
![image](https://user-images.githubusercontent.com/26474449/199679299-0b3aba10-507a-4587-8aad-847764d7d751.png)
_System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Windows.Forms.Primitives
  StackTrace:
   at Windows.Win32.UI.Shell.IShellItem.Release()
   at System.Windows.Forms.FileDialog.OnBeforeVistaDialog(IFileDialog* dialog)
   at System.Windows.Forms.FileDialog.TryRunDialogVista(HWND hWndOwner, Boolean& returnValue)
   at System.Windows.Forms.FileDialog.RunDialog(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at WinFormsApp1.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\xxx\source\repos\WinFormsApp1\WinFormsApp1\Form1.cs:line 17_

**.Net 7.0:**
![image](https://user-images.githubusercontent.com/26474449/199679610-102e2766-5691-4ee7-9e8e-aa13084ee208.png)

### Steps to reproduce

1. Create a Winforms .Net 8.0 application
2. Add a button to form designer, and double-click it to generate event
3. Add following code:
```
string imagePath = "";
OpenFileDialog open = new OpenFileDialog();
open.InitialDirectory = "C:\Users\Public\Pictures\Sample Pictures";
open.Filter = ".jpg,.jpeg,.bmp,.gif,.ico,.png,.tif,.wmf|.jpg;.jpeg;.bmg;.gif;.ico;.png;.tif;.wmf";
open.Title = "choose picture";
if (open.ShowDialog() == DialogResult.OK)
{
MessageBox.Show("OpenfileDialog is opened");
}
```
4. Build and run to click button

Or using attached simple repro application:
[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/9926806/WinFormsApp1.zip)

**Comment by RussKie** [comment]
@lonitra putting this on your radar

**Comment by RussKie** [comment]
https://github.com/dotnet/winforms/pull/8021 will be useful to increase our test coverage for dialogs and reduce further risks of such regressions.

**Comment by Cassie-Li01** [comment]
Verified on latest 8.0 build .NET 8.0.100-alpha.1.22607.6, issue is fixed. Gif as below:
![fixed](https://user-images.githubusercontent.com/96758262/206336421-d2c9a79f-3260-44fb-add4-8116ea2fa101.gif)
