### ISSUE TITLE
FolderBrowserDialog throws AccessViolationException and crashes when creating a new folder in a USB drive with no space available

### ISSUE THREAD

**Issue by alchemistis** [dotnet/winforms#8116]
### .NET version

6.0.10

### Did it work in .NET Framework?

No

### Issue description

The issue happens when trying to create a new folder in a USB flash drive with no space available through FolderBrowserDialog or SaveFileDialog.

USB Device:
![image](https://user-images.githubusercontent.com/14222884/200080315-a9984053-3590-4a3b-8109-dc94482defe4.png)

![image](https://user-images.githubusercontent.com/14222884/200082157-6cd44b7d-174c-4f9d-899c-96d53c1650ed.png)

![image](https://user-images.githubusercontent.com/14222884/200082951-dbcc1ec1-cd78-45bd-bd39-062711eb27d8.png)

![image](https://user-images.githubusercontent.com/14222884/200079421-73a8047a-e050-4443-ada7-fc942a1c9479.png)

The reference screenshots for this test show a Windows install flash drive with a NTFS partition, but it also happened in previous tests with FAT flash drives.

This issue was originally discovered in a .NET Framework 4.8 application but seems to occur in the .NET 6 implementation as well.

I also tried reproducing the issue in multiple machines with different devices, still persists.

Using a virtual disk (simulating a device with no space available) had the expected behaviour (another dialog shows up notifying the user there's no space available and suggesting them to clean up the device).

Could this be a shell problem? During these tests I figured the issue also seems to happen with explorer.exe itself, I can consistently crash it by trying to create a folder under the same conditions described.

### Steps to reproduce

* Open a FolderBrowserDialog (or SaveFileDialog) with the ShowDialog() method
* Select a full USB device (0 bytes available)
* Create a new folder from within the dialog, either through the context menu option or the New Folder button, in said device
    - Creating the folder with the top left "New Folder" button causes the AccessViolationException to be thrown
![image](https://user-images.githubusercontent.com/14222884/200083410-d574f2e8-209b-43cb-bfd4-a49ea2d20a45.png)
    - Creating the folder with the context menu option causes the application to crash silently with no exceptions, even when "EnableUnmanagedDebugging" is set to true (this seems to show more information in the .NET Framework 4.8 version)

**Comment by elachlan** [comment]
> Could this be a shell problem? During these tests I figured the issue also seems to happen with explorer.exe itself, I can consistently crash it by trying to create a folder under the same conditions described.

This is 100% a windows issue if its happening without any usage of winforms. Winforms is just a wrapper of the WinAPI, it doesn't manage the WinAPI code.

Could you please provide your Windows version details?

**Comment by alchemistis** [comment]
Hey @elachlan, thank you for the fast reply.

> This is 100% a windows issue if its happening without any usage of winforms. Winforms is just a wrapper of the WinAPI, it doesn't manage the WinAPI code.

Yeah, it's likely a Windows problem unfortunately.

> Could you please provide your Windows version details?

 Sure, my main workstation is running Windows 11 (22H2, build 22621.674) and one of the other computers I tested the issue on is running Windows 10 (21H2, build 19044.2130).

![Main](https://user-images.githubusercontent.com/14222884/200197894-401de516-a292-48f9-9702-12b0b4665408.png)

![Aux](https://user-images.githubusercontent.com/14222884/200198091-ff602654-1159-477e-a00e-8223680ca17a.png)

I don't have access to the other laptop I used for testing at the moment, but these should do.

**Comment by RussKie** [comment]
@Olina-Zhang could you please see if you can repro this with an MFC app? Thank you

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang could you please see if you can repro this with an MFC app? Thank you

Sorry, due to office security regulations, we cannot use any USB flash drive. And I cannot repro this issue with a virtual disk:
![image](https://user-images.githubusercontent.com/26474449/200240852-41b9be5d-27f0-4586-a92b-112eaf0be94f.png)

**Comment by KlausLoeffelmann** [comment]
Out of interest: 
Does this "only" happen when you create a new folder, or also with other IO-related functions you try to perform on that device? Like can you query remaining memory or list directory or files without problems?

**Comment by merriemcgaw** [comment]
@alchemistis can you please provide us with the callstack? That will help us to diagnose the issue a little bit faster. Thanks!

**Comment by Tanya-Solyanik** [comment]
@alchemistis - is possible, a mixed mode call stack would be great, just enable native debugging for your sample.

**Comment by alchemistis** [comment]
Hey @KlausLoeffelmann,

Yeah, apparently the issue only happens when creating new items (Folders, text files, bitmaps or any other item available through the dialog's context menu will also cause the issue). The other operations you mentioned seem to work just fine.

**Comment by alchemistis** [comment]
Hey @merriemcgaw, @Tanya-Solyanik, Sorry for not getting back to you sooner.

And of course, here's the call stack (I believe most relevant symbols were loaded, but if you need extra information let me know):
```
windows.storage.dll!CCopyWorkItem::_HandleRemovableFull(struct IShellItem *)	Unknown
windows.storage.dll!CCopyWorkItem::FileFailure(struct IShellItem *,unsigned short const *,long,unsigned short *,unsigned long)	Unknown
windows.storage.dll!CBaseOperation::_FileFailure(struct IShellItem *,unsigned short const *,long,unsigned short *,unsigned int)	Unknown
windows.storage.dll!CCopyOperation::_HandleDestinationCreateError(long,unsigned short const *)	Unknown
windows.storage.dll!CNewOperation::_HandleNewFileError(long,unsigned short const *)	Unknown
windows.storage.dll!CNewOperation::Do(void)	Unknown
windows.storage.dll!CCopyWorkItem::_DoOperation()	Unknown
windows.storage.dll!CCopyWorkItem::_SetupAndPerformOp()	Unknown
windows.storage.dll!CCopyWorkItem::ProcessWorkItem()	Unknown
windows.storage.dll!CRecursiveFolderOperation::Do()	Unknown
windows.storage.dll!CFileOperation::_EnumRootDo()	Unknown
windows.storage.dll!CFileOperation::PrepareAndDoOperations()	Unknown
windows.storage.dll!CFileOperation::PerformOperations()	Unknown
shell32.dll!CNewMenu::_CreateFileOrFolder(struct HWND__ *,unsigned short const *,struct NEWFILEINFO *,struct NEWOBJECTINFO *)	Unknown
shell32.dll!CNewMenu::_CreateItem(struct HWND__ *,unsigned short const *,struct NEWFILEINFO *,struct NEWOBJECTINFO *)	Unknown
shell32.dll!CNewMenu::InvokeCommand(struct _CMINVOKECOMMANDINFO *)	Unknown
shell32.dll!HDXA_LetHandlerProcessCommandEx()	Unknown
shell32.dll!CDefFolderMenu::InvokeCommand()	Unknown
shell32.dll!CContextMenuOnContextMenuArray::InvokeCommand(struct _CMINVOKECOMMANDINFO *)	Unknown
shlwapi.dll!00007ffe0f122179()	Unknown
shlwapi.dll!00007ffe0f123277()	Unknown
shell32.dll!SHInvokeCommandOnSelection(struct IUnknown *,struct IShellItemArray *,enum SHICOIA_FLAGS,char const *)	Unknown
shell32.dll!CCommandFolder::_InvokeItem(struct IDataObject *)	Unknown
shell32.dll!CCommandFolder::CallBack(struct IShellFolder *,struct HWND__ *,struct IDataObject *,unsigned int,unsigned __int64,__int64)	Unknown
shell32.dll!CDefFolderMenu::InvokeCommand()	Unknown
shlwapi.dll!00007ffe0f122179()	Unknown
shlwapi.dll!00007ffe0f123392()	Unknown
shell32.dll!CCommandModuleInner::s_WndProc()	Unknown
user32.dll!UserCallWinProcCheckWow()	Unknown
user32.dll!DispatchMessageWorker()	Unknown
user32.dll!DialogBox2()	Unknown
user32.dll!InternalDialogBox()	Unknown
user32.dll!DialogBoxIndirectParamAorW()	Unknown
user32.dll!DialogBoxIndirectParamW()	Unknown
comdlg32.dll!<lambda>(void)()	Unknown
comdlg32.dll!CFileOpenSave::Show(struct HWND__ *)	Unknown
[Managed to Native Transition]	
System.Windows.Forms.dll!System.Windows.Forms.FolderBrowserDialog.TryRunDialogVista(System.IntPtr owner, out bool returnValue)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.FolderBrowserDialog.RunDialog(System.IntPtr hWndOwner)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.CommonDialog.ShowDialog(System.Windows.Forms.IWin32Window owner)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.CommonDialog.ShowDialog()	Unknown
>	CrashTest.dll!CrashTest.Form1.dialogButton_Click(object sender, System.EventArgs e) Line 16	C#
System.Windows.Forms.dll!System.Windows.Forms.Control.OnClick(System.EventArgs e)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Button.OnClick(System.EventArgs e)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Button.OnMouseUp(System.Windows.Forms.MouseEventArgs mevent)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Control.WmMouseUp(ref System.Windows.Forms.Message m, System.Windows.Forms.MouseButtons button, int clicks)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.ButtonBase.WndProc(ref System.Windows.Forms.Message m)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Button.WndProc(ref System.Windows.Forms.Message m)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.Callback(System.IntPtr hWnd, Interop.User32.WM msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
[Native to Managed Transition]	
user32.dll!UserCallWinProcCheckWow()	Unknown
user32.dll!DispatchMessageWorker()	Unknown
[Managed to Native Transition]	
System.Windows.Forms.dll!System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(System.UIntPtr dwComponentID, Interop.Mso.msoloop uReason, void* pvLoopData)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Interop.Mso.msoloop reason, System.Windows.Forms.ApplicationContext context)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Interop.Mso.msoloop reason, System.Windows.Forms.ApplicationContext context)	Unknown
System.Windows.Forms.dll!System.Windows.Forms.Application.Run(System.Windows.Forms.Form mainForm)	Unknown
CrashTest.dll!CrashTest.Program.Main() Line 14	C#
[Native to Managed Transition]	
hostpolicy.dll!00007ffdfec6971b()	Unknown
hostpolicy.dll!00007ffdfec69a4c()	Unknown
hostpolicy.dll!00007ffdfec6a3e7()	Unknown
hostfxr.dll!00007ffdff5eb77c()	Unknown
hostfxr.dll!00007ffdff5ee3f7()	Unknown
hostfxr.dll!00007ffdff5f075f()	Unknown
hostfxr.dll!00007ffdff5eea53()	Unknown
hostfxr.dll!00007ffdff5e850b()	Unknown
CrashTest.exe!00007ff737741eb8()	Unknown
CrashTest.exe!00007ff73774222b()	Unknown
CrashTest.exe!00007ff7377436d8()	Unknown
kernel32.dll!00007ffe0deb244d()	Unknown
ntdll.dll!RtlUserThreadStart()	Unknown
```

Thank you!

**Comment by Tanya-Solyanik** [comment]
Unfortunatly I don't see any callbacks into winforms that would allow us change anything...

**Comment by RussKie** [comment]
This looks like a bug in Windows (windows.storage.dll), please raise a ticket via Windows Hub.

**Comment by KlausLoeffelmann** [comment]
> The other operations you mentioned seem to work just fine.

So, a potential workaround for the time being is to check if there is enough space before creating a new folder?
