### ISSUE TITLE
"(DataBindings)" for ToolsStripItems appears under Misc section instead of Data section

### ISSUE THREAD

**Issue by OJacot-Descombes** [dotnet/winforms#8154]
### Environment

Visual Studio 2022 Community Version 17.4.0

### .NET version

net7.0-windows

### Did this work in a previous version of Visual Studio and/or previous .NET release?

New preview feature in .NET 7.0: DataBinding for ToolStripItems

### Issue description

Now `ToolStripItem` derives from `BindableComponent` instead of `Component` to allow data binding.

As for `Control` the DataBindings property should appear in the **Data** section of the properties window, but it appears in the **Misc** section.
![image](https://user-images.githubusercontent.com/12754787/200965457-89d49a5a-97d3-4575-ad0b-0a6baea9c058.png)

### Steps to reproduce

1. Add a new Form to the project.
2. Add a ToolStrip to the form (in the designer).
3. Add a ToolStripButton to the ToolStrip by using the design time drop-down on the ToolStrip.
4. Select this button and look at the properties window.

**Comment by merriemcgaw** [comment]
Thank you so much for this feedback. @KlausLoeffelmann will take a look and we will absolutely consider it for .NET 8.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann when you remove the preview attribute, please take a look at this too.

**Comment by KlausLoeffelmann** [comment]
This will be a separate PR.

**Comment by Nora-Zhou01** [comment]
Verified this issue in Winforms main branch for .NET 9.0, it has been fixed that the Databinding property appears in the Data section of the Properties window.
![8154](https://github.com/dotnet/winforms/assets/104609169/4acb2a7e-18aa-4203-8947-2f5a60002d3d)

**Comment by Philip-Wang01** [comment]
Verified this issue in the latest .Net 8.0 SDK build: 8.0.100-rtm.23470.15, it was fixed with same result as above validation.

**Comment by John-Qiao** [comment]
Verified with .NET SDK 8.0.100-rc.2.23477.19 test pass build, it has been fixed with same result as above validation too.
