### ISSUE TITLE
Slow Trackbar when large number for maximum

### ISSUE THREAD

**Issue by conorgee** [dotnet/winforms#8162]
### .NET version

.NET 7

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

Setting the MaxValue on the Trackbar control to a very high number results in slow loading speed and a laggy trackbar.

This appears to be because on initialization of the underlying windows control, when the maximum is set to a large number it loads that many ticks because the tick mark frequency is 1, resulting in it initializing excessive amounts of tickmarks.  This causes the issue of a slow loading time and laggy trackbar. I found this issue after expermenting with #329 .

https://github.com/dotnet/winforms/blob/094bbe94904f2cf2bf87c7af0b5bff2076cdeec9/src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs#L811-L812

### Steps to reproduce

Within a form

```
TrackBar tb = new TrackBar();
tb.Maximum = 1000000000;
this.Controls.Add(tb);
```

**Comment by elachlan** [comment]
I believe this was fixed by #8060
