### ISSUE TITLE
A DirectX control is drawn in an incorrect position when the form is resized and the RightToLeft mode is used

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#8165]
### .NET version

8.0.100-alpha.1.22559.22

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it's not a regression issue. This issue also repro's on .NET 3.1 and .NET 5.0.

### Issue description

**Actual Result:**
A DirectX control is drawn in an incorrect position when the form is resized and the RightToLeft mode is used.
![ReproSteps](https://user-images.githubusercontent.com/86937911/201251676-803b5680-ee6d-4230-8122-cc0de9630f37.gif)

**Expected Result:**
DirectX control should draw in the correct position.

**More Info:**
1. The initial feedback ticket is: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1568826.
2. The original issue is: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1578649.
3. If RightToLeft mode is enabled, the control area that is drawn with the DirectX technique is not displayed correctly. At the same time, the GDI painter uses correct bounds.
4. This issue is only reproduced if the DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL effect is used. However, customer is not able to use another effect, because this effect is recommended for implementing the DirectX rendering.

### Steps to reproduce

1. Open the attached the application.
[DirectX.zip](https://github.com/dotnet/winforms/files/9986088/DirectX.zip)
2. Build & run the application.
3. Resize the form in RightToLeft mode and observe the results.

**Comment by merriemcgaw** [comment]
We will wait for a customer report to report this issue to reopen and deal with it.

**Comment by NadezhdaBobrovaDX** [comment]
Hello,

My name is Nadezhda. I’m a software engineer on the WinForms team at DevExpress. 

Although we understand that there is a low number of requests regarding this bug, we do not agree with your decision not to fix it.

We do not believe that the low number of such customers justifies not resolving this issue, as the same argument could be made for many accessibility issues.
We want to give access to our latest features, including DirectX, to customers of all needs and backgrounds, including those who require RightToLeft layouts and functionality.
The way things are right now, those customers are forced to forfeit the additional functionality and performance improvements that come with the use of DirectX rendering.
We do not believe that this is fair to them, especially considering that this is something that can potentially be resolved.
