### ISSUE TITLE
Use interpolated strings in WinForms

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#8203]
WinForms formatted string usages should be converted to interpolated strings where possible to get the various performance benefits.

https://learn.microsoft.com/dotnet/csharp/language-reference/tokens/interpolated

This is a good community contribution issue. Details:

- Keep PRs to a manageable size
- This includes usages of `+` to concat strings
- `string.Format` is still needed for anything that gets localized strings (`SR.*`)
- In most cases we don't need to specify culture
  - Not needed ever for integers or booleans that aren't special formatted
  - Never really needed in Debug statements

Examples of changes:

``` C#
// No culture needed - non localized string, debug only, boolean
Debug.WriteLineIf(CompModSwitches.ImeMode.Level >= TraceLevel.Info, string.Format(CultureInfo.CurrentCulture, "Inside get_CanEnableIme(), value = {0}, this = {1}", ImeSupported, this));

// Becomes...

Debug.WriteLineIf(CompModSwitches.ImeMode.Level >= TraceLevel.Info, $"Inside get_CanEnableIme(), value = {ImeSupported}, this = {this}");



Debug.WriteLineIf(CompModSwitches.ImeMode.Level >= TraceLevel.Info, "Inside get_CurrentImeContextMode(), this = " + this)

// Becomes...

Debug.WriteLineIf(CompModSwitches.ImeMode.Level >= TraceLevel.Info, $"Inside get_CurrentImeContextMode(), this = {this}")
```

I don't think we have many cases where [raw string literals](https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-11.0/raw-string-literal) are needed, but that can be included in this work if any come up. (`$"""Count {0}"""`)

We should also identify and collect places in the WinForms code where we're frequently passing formatted strings that may not be used so we can look for ways to leverage skipping formatting in much the same way that `Debug.WriteLineIf`, etc. do.

**Comment by elachlan** [comment]
@Youssef1313 Do you know of an analyzer for converting string.format to interpolation and for string concatenation?

**Comment by Youssef1313** [comment]
Not that I know of.

**Comment by JeremyKuhne** [comment]
There is an auto-fix for converting to interpolated strings that will get you some of the way there.

**Comment by halgab** [comment]
I've been working on this for the past few days, and I noticed that the [TraceVerbose](https://github.com/dotnet/winforms/blob/a8e341cb99955ec3cbdea9815dfa71e487661633/src/Common/src/TraceSwitchExtensions.cs#L12) extension method introduced in #8119 was most likely a de-optimisation whenever the message is an interpolated string.

Before this PR, the string was materialised only when tracing was switched to verbose thanks to the interpolated string handler of `Debug.WriteLineIf`. Now it's materialised all the time whenever you're in debug...

Is that something that you would like to see fixed as part of this issue?

**Comment by paul1956** [comment]
Right now, the designer crashes if it sees a $" starting a String at least in VB. Not sure how I would even create one in Designer a refactoring changed it in my case.
