### ISSUE TITLE
[Announcement] Signing off

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#8204]
After three and a half years of being the repository owner and maintainer I'm moving to another .NET team and, thus, signing off here. It was an awesome ride, and together we've built an amazing community. Windows Forms has a special place in my heart, and I expect to stick around, though, more in a role of a contributor.

Feel free to tag me in issues and pull-requests, though I can't guarantee the same level of responsiveness as you've come to expect of me.

Thank you all, and happy coding!
Igor

**Comment by elachlan** [comment]
Congratulations and all the best with your new role!

**Comment by kirsan31** [comment]
This is very bad news for the winforms community  😥 But I hope that this news is at least good for you 😉
Winforms has been repeatedly voted the best .net repository in terms of community friendly, and your have very good role here  - **thank you**!!! 
Bye bye and good luck 😥🙏👍

P.s. Who will be a new maintainer here?

**Comment by tbolon** [comment]
Thank you @RussKie 🙏. For curiosity, where are you going?

**Comment by RussKie** [comment]
Thank you for the kind words 🙇.

@dreddy-work  is the current repo owner and the primary contact for any day-to-day stuff. 
Incoming issues triage lifecycle is described in [this doc](https://aka.ms/winforms/issue-lifecycle). Incoming pull-requests will be reviewed at the regular cadence. If you feel that an issue or a PR is overlooked or forgotten - feel free to ping the team (@dotnet/dotnet-winforms) on it.

I'm moving to another .NET team to work on microservices.

**Comment by KlausLoeffelmann** [comment]
Hey man, thanks for all your support here!

Those will be some shoes to fill, and we'll be doing our best!

My Dad was never able to explain "Abseits" to me in "deutschem Fussball" - but you, as _the_ go-to Git Expert, did a fabulous job with explaining even more difficult things, namely the difference between "Rebase" and "Merge"! 😉 

But joking aside - I really appreciate all the effort you put into providing even the most edge-case-y knowledge to us - _especially_ when it came to anything around Git. And even if we had to agree to disagree in certain areas, I think when it came to WinForms, we came up with quite some cool and useful features together. And _that_ I really like(d)!

**Comment by anirugu** [comment]
Best of luck @RussKie

**Comment by gpetrou** [comment]
Thank you very much for your thorough reviews and your help in general. Best wishes for your new role.

**Comment by merriemcgaw** [comment]
We are going to miss you so much here @RussKie. I give the credit for being such a welcoming and active repo to what you taught all of us. I hope we can live up to the high standards that you set. Congrats on the new role, but I do hope to see you in here now and then.

And Community - if we're not living up to the standards @RussKie  feel free to ping me directly. I am always looking for feedback and learning to make this community experience better and better.

**Comment by dreddy-work** [comment]
Closing this now.
