### ISSUE TITLE
[HDPI] Anchors of user control don't work in form designer when scaling on high DPI 

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#8228]
### .NET version

17.5.0 Preview 2.0 [33115.401.main]

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

**Actual result:**
Anchors of user control don't work in form designer on 300% HDPI monitor.
![Actual](https://user-images.githubusercontent.com/45864985/202604771-e644619c-6974-46a9-8924-54c5a0f27cdc.png)

**Expected result:**
Anchors of user control should work in form designer on 300% HDPI monitor, like that work on 100% monitor.
![Expected](https://user-images.githubusercontent.com/45864985/202604798-f85ea35b-eb1a-454c-96f8-9becdc1ad683.png)

### Steps to reproduce

1. Launch the [ControlScalingBug.zip](https://github.com/dotnet/winforms/files/10037240/ControlScalingBug.zip) sample app on 300% primary monitor.
2. Clean and rebuild project.
3. In Solution Explorer, double click FrmBad.cs to open form designer.
4. Observe the usercontrol in it.

**Comment by dreddy-work** [comment]
fixed by https://github.com/microsoft/winforms-designer/pull/4783

**Comment by John-Qiao** [comment]
Verified this issue in the latest VS build: 17.8.0 Preview 3.0 [34117.8.main], it was fixed that Anchors of user control works well in form designer on 300% HDPI monitor now.

![8228-testresult](https://github.com/dotnet/winforms/assets/45864985/e5af3fb9-6520-4353-a439-85496dbdaf98)
