### ISSUE TITLE
[Tracking] Optimize code around parking windows in the WinForms runtime

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#8252]
While enabling nullability in [this](https://github.com/dotnet/winforms/pull/6386), we noticed opportunity to optimize `ParkingWindow' and try avoiding inserting/caching null values. 
This tracking issue created to capture that work and prioritize.

**Comment by elachlan** [comment]
@lonitra This looks to be resolved as the list is no longer nullable and null is not inserted. I think it was resolved in #6386 unless I am missing something.

https://github.com/dotnet/winforms/blob/c8b7ff46a1405fc8cdbc0ca97569c33215ea801d/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs#L52

**Comment by merriemcgaw** [comment]
Yeah, I think we can close this. Thanks @elachlan!
