### ISSUE TITLE
WinForms on .NET Core should support RESX file serialization and deserialization

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/winforms#826]
@merriemcgaw commented on [Wed Apr 17 2019](https://github.com/dotnet/corefx/issues/36977)

**Comment by merriemcgaw** [comment]
@dreddy-work please link the issues in MSBuild and corefx repos representing the work here. This issue is tracking the whole user store start to finish.

**Comment by dreddy-work** [comment]
Only pending work in the scenario is https://github.com/microsoft/msbuild/issues/2221. could link the isue directly ( may be because repo are in different org?).
