### ISSUE TITLE
[Multi-Monitor][PerMonitorV2] ErrorProvider control is not scaled well on secondary screen

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#8264]
### .NET version

8.0.100-alpha.1.22567.28

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it also repro on .NET 6.0 & 7.0.

### Issue description

ErrorProvider control is not scaled well in secondary screen under PermonitorV2 mode.

### Steps to reproduce

1. Launch VS instance on 300% primary monitor.
2. Create a winforms .net core project.
3. Drag and drop textbox, ErrorProvider control.
4. Double click textbox control and add below code:
	try     
	 {        
		 int x = Int32.Parse(textBox1.Text);         
		errorProvider1.SetError(textBox1, "");   
	  }      
	catch (Exception ex)     
	 {        
	 errorProvider1.SetError(textBox1, "Not an integer value.");     
	 }
5. Build and run, input "d" to textbox control.
6. Move to 100% secondary monitor.
	
Or:
1. Extract and open [errorprovider.zip](https://github.com/dotnet/winforms/files/10073158/errorprovider.zip) on 300% primary screen.
2. Build and run it, input "d" to textbox control.
3. Move to 100% secondary monitor.

**Actual result:**
ErrorProvider control is not scaled well.
Move form 300 primary screen to 100 secondary screen:
![Untitled](https://user-images.githubusercontent.com/94418985/203483930-8a364dc2-7d1d-4b01-80e0-7a1dee9c8e11.png)
Move form 100 primary screen to 300 secondary screen:
![Untitled1](https://user-images.githubusercontent.com/94418985/203484072-94377cf4-9913-4b4c-9404-40849dbf8566.png)

**Expected result:**
ErrorProvider control should scaled well.
Move form 300 primary screen to 100 secondary screen:
![100ci-normal](https://user-images.githubusercontent.com/94418985/203484181-d854f1b8-3f52-44c0-b89b-7ddefb8c8a7e.png)
Move form 100 primary screen to 300 secondary screen:
![300ci-normal](https://user-images.githubusercontent.com/94418985/203484195-169c6c88-4c79-4fcf-9f64-f1031cb1449b.png)

**More Info:**
1. This issue also repro on moved VS from 100% primary to 300% secondary.
2. This issue also repro on .NET7.0, .NET6.0.
3. This issue not repro on framework project.
4. This issue doesn't repro on SystemAware and DpiUnware mode.

**Comment by Philip-Wang01** [comment]
Verified with .NET SDK 8.0.100-alpha.1.23068.16 build from main branch, this issue is fixed that ErrorProvider control is scaled well on secondary screen under PermonitorV2 mode.
Move form 300 primary screen to 100 secondary screen:
![image](https://user-images.githubusercontent.com/86937911/213382226-fda36a7f-d8f9-4ee8-a841-59420df670e6.png)
Move form 100 primary screen to 300 secondary screen:
![image](https://user-images.githubusercontent.com/86937911/213382325-d3d277c4-7097-4543-b62d-b1bf7ef8f8ba.png)

**Comment by John-Qiao** [comment]
Verified with .NET 8 Preview 1 TP build: .NET 8.0.100-preview.1.23108.10, issue was fixed as same as above test result.
