### ISSUE TITLE
[Multi-Monitor][PermonitorV2] Buttons are not not scaled well (with Anchor=Top,Bottom) when move from 300% primary screen to 100% secondary monitor

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#8266]
### .NET version

.NET 8.0.100-alpha.1.225727.7 + private dlls build from Winforms repo, regression from PR: https://github.com/dotnet/winforms/pull/7956

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it'a regression issue, not repro on .NET 6.0 & 7.0, only repro on .NET 8.0.100-alpha.1.225727.7 + private dlls build from Winforms repo, regression from PR: https://github.com/dotnet/winforms/pull/7956

### Issue description

Buttons are not not scaled well (with Anchor=Top,Bottom) when move from 300% primary screen to 100% secondary monitor
![image](https://user-images.githubusercontent.com/86937911/203485453-844e455b-1f45-4966-8806-94b5443fe5f4.png)

### Steps to reproduce

1. Launch VS instance on 300% primary screen.
2. Create a WinForms .NET Core project.
3. Add PerMonitorV2 in csproj file.
4. Add some buttons with different anchor properties to form designer.
5. Build and run it, move to 100% secondary monitor.

Or:
1. Extract and open [Testbuttonanchor.zip](https://github.com/dotnet/winforms/files/10073263/Testbuttonanchor.zip) on 300% primary screen.
2. Build and run it, move to 100% secondary monitor.

**Actual result:**
Buttons are not not scaled well (with Anchor=Top,Bottom) when move from 300% primary screen to 100% secondary monitor.
![image](https://user-images.githubusercontent.com/86937911/203485453-844e455b-1f45-4966-8806-94b5443fe5f4.png)

**Expected result:**
Buttons should be scaled well (with Anchor=Top,Bottom) when move from 300% primary screen to 100% secondary monitor.
![image](https://user-images.githubusercontent.com/86937911/203488293-9fece9d6-1328-4909-a028-2e69ad035d1a.png)

**More info:**
1. This issue doesn't repro on SystemAware and DpiUnware mode.
2. This issue does not occur when move from 100% primary to 300% secondary monitor.
3. This issue only repro on Anchor = Top,Bottom, Anchor = Top,Bottom,Left, Anchor = Top,Bottom,Right and Anchor = Top,Bottom,Left,Right.
4. This is a reduce behavior on private testing, regression from PR: https://github.com/dotnet/winforms/pull/7956

**Comment by dreddy-work** [comment]
In PermonV2 mode applications, when moved from one monitor to the other, scale factor computed with respect to new DPI on the monitor is not aligning with the Window's `SuggestedRectangle` for top-level window on the monitor. This is causing issue in scaling anchors with `AutoScaleFactor`. Anchors are tightly coupled with parent's `DisplayRectangle` and computing scale factor based on the change in `DisplayRectangle` should help solve this issue.

**Comment by Ashley-Li** [comment]
Verified this issue on .NET latest build: 8.0.100-alpha.1.23055.16, issue was fixed that buttons can be scaled well (with Anchor=Top,Bottom) when move from 300% primary screen to 100% secondary monitor.
![image](https://user-images.githubusercontent.com/56664234/210955055-3c24b3cd-a526-465a-ba99-4bcf466b83d2.png)
