### ISSUE TITLE
[Multi-Monitor][PerMonitorV2]HScrollBar is not scaled well on secondary screen

### ISSUE THREAD

**Issue by MandiMan** [dotnet/winforms#8270]
### .NET version

8.0.100-alpha.1.22567.28

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it also repro on .NET 6.0 & 7.0.

### Issue description

HScrollBar control is not scaled well in secondary screen under PermonitorV2 mode.

### Steps to reproduce

1. Launch VS instance on 300% primary monitor. 
2. Create a winforms .net core project. 
3. Add` <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>` in csproj file.
4. Drag and drop a HScrollBar control. 
5. Build and run. 
6. Move to 100% secondary monitor. 

Or:

1. Extract and open [HScrollBar.zip](https://github.com/dotnet/winforms/files/10074564/HScrollBar.zip)on 300% primary screen.
2. Build and run it
3. Move to 100% secondary monitor.

**Actual result:**
HScrollBar control is not scaled well when move from 300% primary to 100% secondary monitor.
300% primary monitor:
![image](https://user-images.githubusercontent.com/108860782/203524161-e4c353b1-7aff-4f1f-a60d-62e6dbb690ef.png)
Move to 100% secondary monitor:
![image](https://user-images.githubusercontent.com/108860782/203523940-eed32049-e3b0-4148-aa05-1aa622137898.png)

**Expected result:**
HScrollBar control should be scaled well when move from 300% primary screen to 100% secondary monitor.
![image](https://user-images.githubusercontent.com/108860782/203524466-c4b75e47-c552-457e-b1a7-7414cf2a79e0.png)

**More Info:**

1. This issue also repro on .NET7.0, .NET6.0.
2. This issue doesn't repro on .NET Framework.
3. This issue doesn't repro on SystemAware and DpiUnware mode.
4. This issue also repro on moved VS from 100% primary to 300% secondary. When move to 300% secondary screen, HScrollBar is also not scaled well, It may get bigger or disappear. Gif as follows：

https://user-images.githubusercontent.com/108860782/203524982-b893635d-d875-4fcf-8d52-ce5eed0767b6.mp4

**Comment by dreddy-work** [comment]
We are double scaling in .NET for Scrollbars. Working on fix.

**Comment by Ashley-Li** [comment]
@dreddy-work Verified this issue on latest .NET 8.0.100-alpha.1.22615.5, it is repro. Please see below result:
Move to 100% secondary monitor:
![image](https://user-images.githubusercontent.com/56664234/208076340-fd45e0c9-f7ad-472e-8d29-dacf7ce9da0b.png)
Is the fix not in yet or is there another reason?

**Comment by dreddy-work** [comment]
> @dreddy-work Verified this issue on latest .NET 8.0.100-alpha.1.22615.5, it is still repro, is this fix not included in the latest .NET SDK build? 

Can you try after [8270](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fissues%2F8270&data=05%7C01%7Cdreddy%40microsoft.com%7Cdd82ef9bcbfa4a88bb7d08dadf4ee5ea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638067827303611106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=H1dfoYPSriymoW%2FmNNwLRuJf1PVLe8kzY8Mx3nmqkbA%3D&reserved=0) is merged.

**Comment by Ashley-Li** [comment]
> > @dreddy-work Verified this issue on latest .NET 8.0.100-alpha.1.22615.5, it is still repro, is this fix not included in the latest .NET SDK build?
> 
> Can you try after [8270](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fissues%2F8270&data=05%7C01%7Cdreddy%40microsoft.com%7Cdd82ef9bcbfa4a88bb7d08dadf4ee5ea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638067827303611106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=H1dfoYPSriymoW%2FmNNwLRuJf1PVLe8kzY8Mx3nmqkbA%3D&reserved=0) is merged.


Verified this issue on latest .NET 8.0.100-alpha.1.23054.7, it was fix,. HScrollBar control can be scaled well when move from 300% primary screen to 100% secondary monitor.
![image](https://user-images.githubusercontent.com/56664234/210700798-7efa18ac-adf1-4e0b-a3d7-5b2fb8d7bbc1.png)
