### ISSUE TITLE
Enable CA1815 Override equals and operator equals on value types

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#8284]
### Is your feature request related to a problem? Please describe

https://learn.microsoft.com/en-au/dotnet/fundamentals/code-analysis/quality-rules/ca1815
> For [non-blittable](https://learn.microsoft.com/en-au/dotnet/framework/interop/blittable-and-non-blittable-types) value types, the inherited implementation of [Equals](https://learn.microsoft.com/en-us/dotnet/api/system.object.equals) uses the [System.Reflection](https://learn.microsoft.com/en-us/dotnet/api/system.reflection) library to compare the contents of all fields. Reflection is computationally expensive, and comparing every field for equality might be unnecessary. If you expect users to compare or sort instances, or use them as hash table keys, your value type should implement [Equals](https://learn.microsoft.com/en-us/dotnet/api/system.object.equals).

`ImeModeConversion`
https://github.com/dotnet/winforms/blob/5a28fa9c294581314d5675188316fbf09882c114/src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs#L1316

`ThemedScrollbarWindow`
https://github.com/dotnet/winforms/blob/5a28fa9c294581314d5675188316fbf09882c114/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ThemedScrollbarWindow.cs#L1-L12

### Describe the solution you'd like and alternatives you've considered

Add Equals/GetHashCode to the structs.

This involves an API change to the public types.

### Will this feature affect UI controls?

Unknown

**Comment by elachlan** [comment]
These were the only two it found I believe. So if we can't change them, then it is probably not worth it.

**Comment by JeremyKuhne** [comment]
@elachlan can we turn it on and exclude the current instances? Or has that already been done?

**Comment by elachlan** [comment]
It has not been done. Did you want in-source supressions?
