### ISSUE TITLE
Inherited forms don't work in the designer with Reference dll

### ISSUE THREAD

**Issue by memoarfaa** [dotnet/winforms#8287]
### Environment

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.4.0

### .NET version

net7.0 ,net6.0 , net3.1

### Issue description

Inherited forms don't work in the designer with Reference dll

[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/10097441/WinFormsApp1.zip)

![2022-11-27_05-17-27](https://user-images.githubusercontent.com/12494184/204117659-3b6f8180-b286-4df0-b430-76c484c46303.png)

### Steps to reproduce

1- create new WinForms Forms class library  project create Form inherit form other .
2- create new WinForms Forms  project Add  previous class library dll as Reference or edit project.
<ItemGroup>

    <Reference Include="SkinFramWorkCore">
      <HintPath>SkinFramWorkCore.dll</HintPath>
    </Reference>
  </ItemGroup>
3- open Form

### Diagnostics

```text
[05:04:53.583297] fail: Request failures: Sessions/FindDesignableClass.
                        Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: The designer could not be shown for this file because none of the classes within it can be designed.  The designer inspected the following classes in the file: \r\n
                        	Form1 --- The base class 'SkinFramWorkCore.SkinForm' could not be loaded.  Ensure the assembly has been referenced and that all projects have been built.

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[05:04:53.680295] fail: Request failures: Sessions/FindDesignableClass.
                        Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: The designer could not be shown for this file because none of the classes within it can be designed.  The designer inspected the following classes in the file: \r\n
                        	Form1 --- The base class 'SkinFramWorkCore.SkinForm' could not be loaded.  Ensure the assembly has been referenced and that all projects have been built.

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
```

**Comment by merriemcgaw** [comment]
@memoarfaa thanks for reporting this issue. It is fixed and will be in the next available VS update. You can check when it ships by following the [feedback ticket](https://developercommunity.visualstudio.com/t/1740-NET6-WinForms-designer-regress/10198799) that was created for it in Developer Community.

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team close this when the associated feedback ticket is closed? Thanks!

**Comment by memoarfaa** [comment]
OK I will waiting until it's fixed  the only solution now is Pack the dll  as Nuget Package and install it by Nuget locally

**Comment by kirsan31** [comment]
Very similar (same?) but error message is different: https://github.com/dotnet/winforms/issues/8327
Is this will be fixed too?

**Comment by Tanya-Solyanik** [comment]
@memoarfaa - the fix is in the pipeline targeting the December patch Tuesday for VisualStudio 2022 v17.4

![image](https://user-images.githubusercontent.com/15823268/205744826-ed868927-da0c-4940-a5e1-d250db45cbb1.png)

**Comment by memoarfaa** [comment]
Still present

https://user-images.githubusercontent.com/12494184/205769309-360e453b-8024-49ef-ae61-61250bc97712.mp4

**Comment by Tanya-Solyanik** [comment]
The fix is not shipped yet, it will be shipped on the second Tuesday in December is everything goes well with the sign off.

**Comment by memoarfaa** [comment]
ok
