### ISSUE TITLE
ComWrapper needs to return vtable based on types, not interfaces

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#8291]
``` C#
protected override unsafe ComInterfaceEntry* ComputeVtables(object obj, CreateComInterfaceFlags flags, out int count)
```

The implementation here needs to go off of specific class types, not interfaces. Not all classes that implement an interface will only implement a single interface (many won't).

The best place to start is by hard tying specific class types to entries. We can iterate with additional flexibility as warranted.

I plan to tackle this imminently.

**Comment by elachlan** [comment]
@kant2002 things are happening!

**Comment by kant2002** [comment]
Honestly I did not get the idea. Any example from existing COM patterns?

**Comment by JeremyKuhne** [comment]
This has been completely rewritten.
