### ISSUE TITLE
Add test coverage for ResX classes

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#8295]
We recently ported `StronglyTypedResourceBuilder` and that has some end-to-end tests, but we don't have good coverage for `ResxResourceReader` and `ResxResourceWriter` on their own.

`BinaryFormatter` depreciation makes filling in test coverage here much more important.

**Comment by ssflynn77** [comment]
I created a PR that adds a few additional tests for the ResxResourceReader - #8955.  Let me know if this looks like what you are looking for, and I will create additional tests for the Reader and the Writer.

**Comment by JeremyKuhne** [comment]
#8955 didn't fix this, it contributed to it. :)

**Comment by ssflynn77** [comment]
I have added additional tests for ResxResourceWriter in PR #9070
