### ISSUE TITLE
API Proposal: Support Multiselect property in FolderBrowserDialog class

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#8298]
### Summary
If the user needs to select multiple files, this function can be easily realized by using OpenFileDialog.Multiselect.
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog.multiselect

Currently there is no Multiselect property in the FolderBrowserDialog class, so when the user needs to select multiple folders at the same time, he has to perform multiple repeated operations. Providing the Multiselect property allows users to select multiple folders at once when using the FolderBrowserDialog.

### Rationale and Usage
The underlying Windows control has already implemented support for selecting multiple folders at the same time, so we can simply use flag FOS.ALLOWMULTISELECT to implement support for Multiselect Property in .Net internal code.

We can extend the FolderBrowserDialog class and provide two new properties to enable simultaneous selection of multiple folders.

FolderBrowserDialog class:
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.folderbrowserdialog

### Proposed API
```c#
namespace System.Windows.Forms
{
    public sealed class FolderBrowserDialog : CommonDialog
    {
        public bool Multiselect { get; set; }

        public string[] SelectedPaths { get; }
    }
}
```
### Public Property Descriptions
`public bool Multiselect { get; set; }`
Gets or sets a value indicating whether the dialog box allows multiple folders to be selected.

`public string[] SelectedPaths { get; }`
Gets the paths selected by the user.

### Examples
```c#
            FolderBrowserDialog folderBrowserDialog1 = new FolderBrowserDialog();

            folderBrowserDialog1.Multiselect = true;

            if (folderBrowserDialog1.ShowDialog() == DialogResult.OK)
            {
                var paths = folderBrowserDialog1.SelectedPaths;

                MessageBox.Show(string.Join(Environment.NewLine, paths));
            }
```
### Impacts
OpenFileDialog class provides both SafeFileName property and SafeFileNames Property.

SafeFileName property returns single path.
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog.safefilename

SafeFileNames property returns multiple paths.
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog.safefilenames

OpenFileDialog.SafeFileName is similar to FolderBrowserDialog.SelectedPath
OpenFileDialog.SafeFileNames is similar to FolderBrowserDialog.SelectedPaths

Now we just add new Properties, without modifying the original API names.
The new changes will not affect the original API names or events.

-----------------------------------------------------------------------------------------------------------

### Is your feature request related to a problem? Please describe

If the user needs to select multiple files, this function can be easily realized by using **OpenFileDialog.Multiselect**.
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog.multiselect

But currently there is no **Multiselect** property in the **FolderBrowserDialog** class, so when the user needs to select multiple folders at the same time, he has to perform multiple repeated operations.

FolderBrowserDialog class:
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.folderbrowserdialog

### Describe the solution you'd like and alternatives you've considered

API Proposal:

Add properties:

Gets or sets a value indicating whether the dialog box allows multiple folders to be selected.
`public bool Multiselect { get; set; }`

Gets the paths selected by the user.
`public string[] SelectedPaths { get; }`

### Will this feature affect UI controls?

Yes, it will affect UI controls.

**Comment by dreddy-work** [comment]
Team agrees principally on the proposal.  @roland5572, please send formal proposal and we will help it drive through API review board.  [API proposal Guidelines](https://github.com/dotnet/winforms/blob/efac9b9581547df2b94a8bcfba2c2895d3ea91ce/docs/issue-guide.md#feature-and-api-suggestions) for reference.

**Comment by roland5572** [comment]
@dreddy-work , Thank you. I have created a proposal based on your template.

### Summary

If the user needs to select multiple files, this function can be easily realized by using OpenFileDialog.Multiselect.
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog.multiselect

Currently there is no Multiselect property in the FolderBrowserDialog class, so when the user needs to select multiple folders at the same time, he has to perform multiple repeated operations. Providing the Multiselect property allows users to select multiple folders at once when using the FolderBrowserDialog.

### Rationale and Usage
The underlying Windows control has already implemented support for selecting multiple folders at the same time, so we can simply use flag FOS.ALLOWMULTISELECT to implement support for Multiselect Property in .Net internal code.

We can extend the FolderBrowserDialog class and provide two new properties to enable simultaneous selection of multiple folders.

FolderBrowserDialog class:
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.folderbrowserdialog

### Proposed API
```
namespace System.Windows.Forms
{
    public sealed class FolderBrowserDialog : CommonDialog
    {
        public bool Multiselect { get; set; }

        public string[] SelectedPaths { get; }
    }
}
```
### Public Property Descriptions
`public bool Multiselect { get; set; }`
Gets or sets a value indicating whether the dialog box allows multiple folders to be selected.

`public string[] SelectedPaths { get; }`
Gets the paths selected by the user.

### Examples

```
            FolderBrowserDialog folderBrowserDialog1 = new FolderBrowserDialog();

            folderBrowserDialog1.Multiselect = true;

            if (folderBrowserDialog1.ShowDialog() == DialogResult.OK)
            {
                var paths = folderBrowserDialog1.SelectedPaths;

                MessageBox.Show(string.Join(Environment.NewLine, paths));
            }
```

**Comment by dreddy-work** [comment]
Thanks @roland5572. Did you experiment with the changes and how this change impact existing public variables like `SelectedPath` or any other method or property that wasn't expecting multi selects (if any). Do you see any events/callback methods impacted by this change? Please link your changes as draft as it helps in the review process.

**Comment by roland5572** [comment]
@dreddy-work Can I open a pull request draft? I have completed the implementation of it these days.

**Comment by dreddy-work** [comment]
> @dreddy-work Can I open a pull request draft? I have completed the implementation of it these days.

Thanks @roland5572. I will go over these and get back to you on the next steps.

**Comment by dreddy-work** [comment]
@roland5572 , please go ahead and open a draft pull request for reference.

**Comment by roland5572** [comment]
Thank you. I tried to write some code, the code includes some COM interaction, I'm learning Winforms COM interaction, so I haven't finished the code yet. If someone is proficient in COM interaction, he may be better able to implement this function now.

**Comment by Symbai** [comment]
First you dupe an existing issue. Then in December you said you have already completed the implementation, now you say the code isn't finished. I think it would have been better to close this and leave the original open...

**Comment by JeremyKuhne** [comment]
@Symbai sorry about missing the dupe.  🙏🏼 This one has more context so we're going to leave it open.

If anyone wants to take the implementation on, we'd welcome the assistance. It is unclear when we would be able to get to it ourselves.

**Comment by FenPhoenix** [comment]
I took a crack at it. https://github.com/FenPhoenix/winforms/commit/c91001686dbfacba4d596fcfb082b3c5dbc0f723

I tried to stick close to what OpenFileDialog's code does. Some comments:

- The folder browser dialog can fall back to the old pre-Vista style, and that style doesn't support multiselect. So that's a wrinkle, there'd have to be some note about how it only applies to the Vista-style dialog, I guess?
- OpenFileDialog has FileName / FileNames and SafeFileName / SafeFileNames properties. The Safe versions are just the filename, not the full path. FolderBrowserDialog does not have this concept, so I left it out.
- I'm not sure what's expected of contributions that involve localization, with the SRDescription attribute and then SR.resx, and modifying that seems to generate the string in English in all the other resx files? I left the localizable description attributes commented out.

I've been wanting this for years, so I'd be happy to work through whatever issues come up and get this in.

**Comment by RussKie** [comment]
> I took a crack at it. [FenPhoenix@c910016](https://github.com/FenPhoenix/winforms/commit/c91001686dbfacba4d596fcfb082b3c5dbc0f723)

It's best to open a draft PR, this way it is easy to see the diff and provide suggestions or bounce ideas.



> * The folder browser dialog can fall back to the old pre-Vista style, and that style doesn't support multiselect. So that's a wrinkle, there'd have to be some note about how it only applies to the Vista-style dialog, I guess?

It's ok to ignore the pre-Vista dialog, after all .NET Windows Forms is supported on W7Sp1. In those scenarios where visual styles aren't enabled and the old style dialog is shown the lack of the new functionality is totally expected.



> * I'm not sure what's expected of contributions that involve localization, with the SRDescription attribute and then SR.resx, and modifying that seems to generate the string in English in all the other resx files? I left the localizable description attributes commented out.

Contributors are expected to implement the necessary infra (i.e., create new resources), but the actual localizations are handled by the MS teams.

**Comment by FenPhoenix** [comment]
Okay, I opened a draft PR. #10357

**Comment by lonitra** [comment]
Completed via https://github.com/dotnet/winforms/pull/10357
