### ISSUE TITLE
VS 17.4 designer can't load any user control referenced by dll

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#8327]
### Environment

Microsoft Visual Studio Community 2022
Version 17.4.2
VisualStudio.17.Release/17.4.2+33122.133
Microsoft .NET Framework
Version 4.8.04084

### .NET version

.Net6, .Net7

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes in all version before 17.4 Preview 2.0.

### Issue description

Any form that uses user control referenced by dll in project settings will not open with error (could not load the assembly), or open without this control on the form.
Error:
![image](https://user-images.githubusercontent.com/17767561/205635212-84016464-49be-452a-b62b-ea72764e4231.png)

Empty designer without error:
![Snipaste_2022-12-05_14-40-03](https://user-images.githubusercontent.com/17767561/205631115-9c0ef16a-d244-4185-adf3-ee03d6189412.png)

Same reports:
https://github.com/kirsan31/winforms-datavisualization/issues/4 Here we naively thought that the problem concerns only chart control...

https://developercommunity.visualstudio.com/t/1740-NET6-WinForms-designer-regress/10198799#T-N10221437

https://github.com/dotnet/winforms/issues/8287 related?

### Steps to reproduce

Any form with any user control.
Here test project:
[WinFormsDesignerRefBug.zip](https://github.com/dotnet/winforms/files/10153897/WinFormsDesignerRefBug.zip)

Open `WinFormsDesignerRefBug\WinFormsApp1\WinFormsApp1.sln` rebuild and try to open designer - you will see empty form. 

If in example above we will create `Form2`, add our control to it, then derive `Form1` from `Form2`: `public partial class Form1 : Form2` then we will see _Could not load file or assembly_ error in designer.

Lots of discussion on this bug was in https://github.com/kirsan31/winforms-datavisualization/issues/4 but without any result :(

### Diagnostics

```text
fail: Request failures: Sessions/InitializeRootComponent.
                        Microsoft.DotNet.DesignTools.Client.DesignToolsServerException: Could not load file or assembly 'WinFormsControlLibrary1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

**Comment by dreddy-work** [comment]
@Tanya-Solyanik / @Shyam-Gupta , Can you guys take a look if any of the recent changes regressed this? @merriemcgaw as FYI.

**Comment by Tanya-Solyanik** [comment]
Yes, this is a HintPath case, it had been serviced in the latest update for 17.4.

```
	<ItemGroup>
		<Reference Include="WinFormsControlLibrary1">
			<HintPath>..\WinFormsControlLibrary1\bin\$(Configuration)\$(TargetFramework)\WinFormsControlLibrary1.dll</HintPath>
		</Reference>
	</ItemGroup>
```

**Comment by Tanya-Solyanik** [comment]
Fix is in the pipeline targeting the December patch Tuesday for VisualStudio 2022 17.4
![image](https://user-images.githubusercontent.com/15823268/205742799-581a2f32-ace7-453c-b341-dcd4e2755602.png)
