### ISSUE TITLE
PMv2 mode application shrink in Size when moved between monitors

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#8341]
### .NET version

All .NET versions including .NET framework

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

In a PermonitorV2 mode applications, Windows Form when moved between monitors of different DPI settings repetitively, shrinks the Form size and eventually reaches to Zero after few iterations. Please see below gif on how Form's size is impacted when moved between monitors.

### Steps to reproduce

Clean simple Winforms application running in PermonitorV2 mode. 
Multimonitor setup where monitors have different DPI scale settings on them ( i.e 100% and 200%)
Run the app and move between monitors couple of times as shown in gif.

![FormSizeCache](https://user-images.githubusercontent.com/36968667/206037110-1b9914b5-809f-4b65-bfb5-da0bd477a2ab.gif)

**Comment by MelonWang1** [comment]
Verified this issue on latest .NET 8.0.100-alpha.1.22615.5, the main screen dpi is 250%, secondary screen dpi is 100%, this issue also repro. Please see below gif. Could you please help me to confirm if this verification application is correct?
[WinFormsApp33.zip](https://github.com/dotnet/winforms/files/10244622/WinFormsApp33.zip)

![runtime-8 0-gif](https://user-images.githubusercontent.com/94418985/208070309-84e679b4-e395-4c09-a50b-3d6f60a487ac.gif)

**Comment by dreddy-work** [comment]
This is OS dependent fix. Latest Windows 11 OS should help fix this. We verified locally. I can check back when i come back from vacation but yes, this is the right way to verify the app.

**Comment by MelonWang1** [comment]
Verified this issue on .NET latest build: 8.0.100-alpha.1.23055.16, issue was fixed that Form's size is not impacted when moved between monitors when the main screen dpi is 250%, secondary screen dpi is 100% in win10 22h2.
![111](https://user-images.githubusercontent.com/94418985/210951518-cc5a78f0-e1fe-4174-9429-f934368bca3f.gif)
