### ISSUE TITLE
Update Winforms C#/VB templates designer code in InitializeComponent() for modernized CodeDom Serialization

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#8350]
### .NET version

8.0.100-alpha.1.22607.6

### Did it work in .NET Framework?

N/A

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

N/A

### Issue description
WinForms Designer GH https://github.com/microsoft/winforms-designer/pull/4425  for OutOf-Proc Designer had modernized CodeDom serialization,  code for `InitializeComponent()`, is generated taking into account .editorconfig preferences and  `<ImplicitUsings>enable</ImplicitUsings>` project property. However, Winforms C#/VB templates do not respect these settings.

**Template Winforms C# designer code:** --- need to update
![image](https://user-images.githubusercontent.com/26474449/206338199-235a20df-c947-45df-9441-81c75e1c5694.png)
After added a button with modernized CodeDom serialized code
![image](https://user-images.githubusercontent.com/26474449/206338402-7770a982-d9b4-490b-807f-996e8a0429c3.png)

**Template Winforms VB designer code:** --- need to update
![image](https://user-images.githubusercontent.com/26474449/206338507-f8983ffe-3021-4ca1-9af3-684ba8c21eb5.png)
After added a button with modernized CodeDom serialized code
![image](https://user-images.githubusercontent.com/26474449/206338545-4db2622b-87e8-4850-b25d-d6b414006990.png)

### Steps to reproduce

1. Just create a Winforms .Net C#/VB application
2. Go to Form designer file, check the code in `InitializeComponent()`

**Comment by dreddy-work** [comment]
@Tanya-Solyanik / @KlausLoeffelmann ,  what would be user experience if they use older VS version (that has legacy serialization) but with new updated templates from .NET 8.0 if we do this change?

**Comment by KlausLoeffelmann** [comment]
Other than that saving with a previous version would simply revert the `InitializeComponent` code to a previous coding style - nothing. I would totally be in favor of doing this. 

And this is a real good suggestion by @Olina-Zhang!

**Comment by dreddy-work** [comment]
> Other than that saving with a previous version of Visual Studio would simply revert the `InitializeComponent` code to a previous coding style

To me, that may cause confusion given the scenario is more common (for that fact that VS is paid, and .NET is not).

**Comment by KlausLoeffelmann** [comment]
> To me, that may cause confusion given the scenario is more common (for that fact that VS is paid, and .NET is not).

What? I don't understand what you mean.
The Code in `InitializeComponent` is technically an implementation detail and can be understand as a black box. I know, there are some scenarios around HighDPI, where it makes sense to patch that code directly when it comes to change coordinates - but nothing changes here conceptually, and we're not moving any cheese for customers. So, I don't really know what you mean.

**Comment by Tanya-Solyanik** [comment]
When the same project is opened in both VS2022 and VS2019, the workaround to ensure that codegen follows the same rules is to opt out from this - <ImplicitUsings>enable</ImplicitUsings>. This will reduce code churn in the designer file. 

This change could be conditioned in the same way as the implicit usings are:
    <ImplicitUsings Condition="'$(csharpFeature_ImplicitUsings)' == 'true'">enable</ImplicitUsings>

**Comment by dreddy-work** [comment]
> So, I don't really know what you mean.

My concern was about code churn they see when they open project in older VS versions.

**Comment by merriemcgaw** [comment]
I'm OK changing the templates in .NET 8 to match the new codegen. In fact it looks much cleaner. We'll do a brag blog to talk about the modern codegen and that should alleviate a lot of the confusion from most people.

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann do you think we really need this one in .NET 8?

**Comment by JeremyKuhne** [comment]
@KlausLoeffelmann if we intend to do this we should bring it back in. Moving to future for now as we've punted this a few times.

**Comment by merriemcgaw** [comment]
This is definitely something that we want on the backlog. Hopefully we can get out a suite of new templates for .NET 10.

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - please make sure to test template updates on both Dev17 and dev16. Particularly, item template on dev16

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 
>Do you mean update the template on main branch and test it in Dev17 and Dev16?

Update template in winforms repo, build the package, then install that package on a machine with dev16

>Currently, InitializeComponent() and Item templates in Dev16 are old (same as .netFramwork), and InitializeComponent() in Dev17 is as described in this issue

Current templates have `this.` and full namespace names in InitializeComponent - https://github.com/dotnet/winforms/blob/d223c9e1eb6b46b3be6ca0652b0d73b0820eb517/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/net6.0/Form1.Designer.cs#L71
We want to remove them. Note that source code in .designer file is updated by the designer on Ctrl+S. 

.NET templates are installed with dev16, and when you install a new fversion of .NET, new templates are added. You want to test the case when the updated templates are installed on top of dev16

**Comment by LeafShi1** [comment]
> [@LeafShi1](https://github.com/LeafShi1) - please make sure to test template updates on both Dev17 and dev16. Particularly, item template on dev16

Dev16 does not seem to support .net9.0, when installing the [.net 9.0.100 SDK](https://github.com/dotnet/sdk/blob/main/documentation/package-table.md) and then creating a Winforms .Net C# application I get the error
![Image](https://github.com/user-attachments/assets/eecc3f43-47e3-4a7b-a421-87f4dd913f3f)

![Image](https://github.com/user-attachments/assets/fbe425d2-c5a8-4a6f-8f7b-fadc07063478)

On Dev17, after [Update InitializeComponent() template](https://github.com/dotnet/winforms/pull/12398), the `this. ` is removed from Form1.Designer.cs successfully, but other item templates are still using the old template, the item templates are located in the [VSProject repo](https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsproject/Templates/Windows/CSharp/ItemTemplates&version=GBmain), Do we need to update them, if we change them, .NetFramework projects should also be affected

**Comment by Tanya-Solyanik** [comment]
@lonitra @Shyam-Gupta  - do you know if VS2019 is supposed to work with NET6+

**Comment by lonitra** [comment]
I believe for .NET6+ is only supported by VS2022 https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by Shyam-Gupta** [comment]
I am not sure about that. Perhaps CTI team can test and confirm.

**Comment by LeafShi1** [comment]
@Olina-Zhang Can you help confirm whether VS2019 is supposed to work with NET6+?

**Comment by Olina-Zhang** [comment]
> [@Olina-Zhang](https://github.com/Olina-Zhang) Can you help test and confirm whether VS2019 is supposed to work with NET6+?

VS 2019 only targets up to .NET 5.0 when there are high versions of .NET on the machine:

![Image](https://github.com/user-attachments/assets/436be679-ccdb-4ae2-b078-e1b805a189fc)
