### ISSUE TITLE
local variables in WinForms projects are not captured by debugger

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#8354]
Created based on [this](https://github.com/dotnet/winforms/issues/8348#issuecomment-1343424116) discussion.

### .NET version

`net6.0-windows; net7.0-windows; net472`

### V.S.

```
Microsoft Visual Studio Community 2022
Version 17.4.2
VisualStudio.17.Release/17.4.2+33122.133
Microsoft .NET Framework
Version 4.8.09032
```

17.4.1 and 17.5.p1 - same behavior.

### Windows.

```
OS Name	Microsoft Windows 11 Home
Version	10.0.22621 Build 22621
```

### Issue description

V.S. Debugger not capturing local variables in any WinForms .Net / .net framework projects. In console projects all are ok: 
![Snipaste_2022-12-08_08-40-36](https://user-images.githubusercontent.com/17767561/206388114-1ad2e844-a614-4a1d-863f-c59a4af11542.png)
Reset settings and repair installation - nothing helps.

developercommunity issues:
https://developercommunity.visualstudio.com/t/Net-local-variables-not-captured-by-deb/10216016 (closed in favor of next one)
https://developercommunity.visualstudio.com/t/CS0103-in-the-watch-window-for-local-var/10222843

### Steps to reproduce

Any WinForms project.

**Comment by Olina-Zhang** [comment]
Verified it in different VS versions: cannot repro in 17.3.7 release build and previous versions. Repro in 17.4.2 release build for Winforms .Net Core and .Net framework apps. Doesn't repro in WPF app.
![image](https://user-images.githubusercontent.com/26474449/206678831-25f78529-99b5-4c00-81f4-35af180819e7.png)
![image](https://user-images.githubusercontent.com/26474449/206678875-2042742d-223d-490e-b5a5-47a6df5a3cfe.png)

**Comment by kirsan31** [comment]
> Repro in 17.4.2 release build for Winforms .Net Core and .Net framework apps. Doesn't repro in WPF app.

OMG I'm not alone??? 😯 And why we have not seeing dozens of report about it? 🤔

**Comment by kirsan31** [comment]
@Olina-Zhang What version of windows did you test on? Because on my PC with win 10 everything is working fine...

**Comment by Olina-Zhang** [comment]
> What version of windows did you test on?

My VM is Win10 22H2 with different release Visual Studios installed, from 17.4.2, this issue is reproduced.

**Comment by kirsan31** [comment]
@merriemcgaw

> I am currently looking for other feedback tickets that might be filed differently.

I found the same report, my was closed in favor of it 😏 :
https://developercommunity.visualstudio.com/t/CS0103-in-the-watch-window-for-local-var/10222843

**Comment by merriemcgaw** [comment]
@kirsan31 - I see that there is an active workitem on the internal ssystems with the appropriate priority. I think things should move just fine from here. I'm going to close this issue, and you can continue to track it through the developercommunity issue. Ping me if you don't see traction for a while after the holidays. I would assume delays from folks being out for holidays but I'll go poke someone if  we don't see some movement.
