### ISSUE TITLE
Port FxCop rule CA2232: MarkWindowsFormsEntryPointsWithStaThread

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/winforms#8384]
**Title:** Mark Windows Forms entry points with STAThread

**Description:**

STAThreadAttribute indicates that the COM threading model for the application is a single-threaded apartment. This attribute must be present on the entry point of any application that uses Windows Forms; if it is omitted, the Windows components might not work correctly.

https://learn.microsoft.com/en-us/visualstudio/code-quality/ca2232

**Comment by Youssef1313** [comment]
If it was decided not to implement this analyzer in dotnet/winforms, please make sure https://github.com/dotnet/roslyn-analyzers/issues/545 is reopened.

**Comment by RussKie** [comment]
It looks like you've copy-pasted the wrong wording ;)

**Comment by Youssef1313** [comment]
> It looks like you've copy-pasted the wrong wording ;)

Fixed now. Thanks for noting!

**Comment by Youssef1313** [comment]
@merriemcgaw Why this was closed?

**Comment by JeremyKuhne** [comment]
> Why this was closed?

Sorry the justification got missed. As our templates have this already and the runtime error you get is pretty clear we don't feel it has enough value.

**Comment by RussKie** [comment]
It's worth noting that some developers are trying to run `async Main`, so this analyzer would help avoiding that. https://github.com/dotnet/roslyn/issues/22112
