### ISSUE TITLE
Continuous stream of window paint message occurs when overriding CreateParams 

### ISSUE THREAD

**Issue by sethuramkumar** [dotnet/winforms#8421]
### .NET version

.Net6.0

### Did it work in .NET Framework?

No

### Issue description

Continuous stream of window paint message occurs when overriding CreateParams  and using BitBlt() function

### Steps to reproduce

Create a custom control by deriving form control class.
Override Wndproc and handle the WM_NCPAINT and customize the border drawing using BitBlt() function.
Also override the Create Params.

Note:
Continuous stream of window message occurs.

Expected behavior:
Continuous stream of window message calls should not occurs, Border should be properly rendered.

Attached the sample :
[WinformsSample.zip](https://github.com/dotnet/winforms/files/10293445/WinformsSample.zip)

Samples Replication procedure:
1.Run the sample
2.Note in output window, continuous message calls will be shown using Debug.WriteLine().

**Comment by memoarfaa** [comment]
You mean like this

![2022-12-24_18-20-30](https://user-images.githubusercontent.com/12494184/209443979-0fda5986-4b72-45ad-9f3c-56c68a8b9e4b.png)

You need to handle WM_NCCALCSIZE message also

You also forget to Release HDC

[WinformsSample.zip](https://github.com/dotnet/winforms/files/10298887/WinformsSample.zip)

**Comment by sethuramkumar** [comment]
@memoarfaa thanks, it worked
