### ISSUE TITLE
[.NET 7.0.1] InvalidCastException in ErrorProvider

### ISSUE THREAD

**Issue by kambet1** [dotnet/winforms#8424]
### .NET version

7.0.1

### Did it work in .NET Framework?

Yes

### Issue description

System.InvalidCastException exception is thrown in ErrorProvider.

### Steps to reproduce

1. Create a .NET 7.0 WinForm app.
2. Replace Form1.cs with the following code
3. Launch the app.

```
namespace WinFormsApp1
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            var model = new MyModel();
            this.DataBindings.Add("Text", model, "Error");
            new ErrorProvider(this).DataSource = model; // InvalidCastException !!!
        }
    }

    public class MyModel : System.ComponentModel.IDataErrorInfo
    {
        public string this[string columnName] => "";
        public string Error => "";
    }
}
```
_Excepted Result:_
No exception thrown.

_Actual Result:_
This exception is thrown in code:

> System.InvalidCastException
>   HResult=0x80004002
>   Message=Unable to cast object of type 'System.Collections.Generic.KeyValuePair`2[System.Windows.Forms.Control,System.String]' to type 'System.Collections.DictionaryEntry'.
>   Source=System.Windows.Forms
>   Stack Trace:
>    at System.Windows.Forms.ErrorProvider.ErrorManager_CurrentChanged(Object sender, EventArgs e)
>    at System.Windows.Forms.ErrorProvider.SetErrorManager(Object newDataSource, String newDataMember, Boolean force)
>    at WinFormsApp1.Form1..ctor() (Form1.cs):line 13
>    at WinFormsApp1.Program.Main() (Program.cs):line 14

**Other information**
https://github.com/dotnet/winforms/pull/7037
```
// Hashtable controlError = new Hashtable(bindingsCount);
Dictionary<Control, string> controlError = new(bindingsCount);
...
IEnumerator enumerator = controlError.GetEnumerator();
while (enumerator.MoveNext())
{
    DictionaryEntry entry = (DictionaryEntry)enumerator.Current; // Invalid Cast !!!
    SetError((Control)entry.Key, (string?)entry.Value);
}
```

**Comment by gpetrou** [comment]
Sorry, I should have checked that part of the code. I added a small PR with a fix.

**Comment by Nora-Zhou01** [comment]
Verified with .NET SDK 8.0.100-alpha.1.23061.8 build from main branch, this issue is fixed that no exception thrown.
![8 0](https://user-images.githubusercontent.com/104609169/211990780-e2a8fd74-dee4-490a-b214-f0862744ea80.gif)

**Comment by Nora-Zhou01** [comment]
Verified this issue on .NET 7.0.200 TP build, issue was fixed. The screenshot as same as above.

**Comment by Nora-Zhou01** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.200-rtm.23075.9, issue was fixed. The screenshot as same as above.

**Comment by Ashley-Li** [comment]
Verified with .NET 8 Preview 1 TP build: .NET 8.0.100-preview.1.23108.10, issue was fixed as same as above test result.
