### ISSUE TITLE
UIA focus is not returned back to menu item after closing dropdown

### ISSUE THREAD

**Issue by dmitrii-drobotov** [dotnet/winforms#8432]
### .NET version

.NET 8.0.0-alpha.1.22622.1

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

Related to #7770.

After closing MenuStrip's submenu, UIA focus doesn't switch back to the top-level menu item, which may cause issues for screen readers. 

#### Current behavior

In Narrator:
![A gif demonstrating the issue when using Narrator: after closing the dropdown via Escape, focus highlight rectangle stays on now invisible menu item](https://user-images.githubusercontent.com/102954094/209823124-e658ca9d-81ed-4d93-854b-d75f109dc3f1.gif)

> [Press Alt]
> menuStrip1, Project, menu item, collapsed, 
> [Press Down arrow]
> Project, menu, 
> New, menu item, Ctrl+ N, 
> [Press Escape]

There is no announcement that focus is now on Project menu item after pressing Escape.

In JAWS:
![A gif demonstrating the issue when using JAWS: after closing the dropdown via Escape, menu is reopened and announced again as context menu](https://user-images.githubusercontent.com/102954094/209821377-4e6a0727-787c-4392-a1e7-5e9c9e7a4ba1.gif)

> [Press Alt]
> Menu bar 
> Project sub menu 
> [Press Down arrow]
> menu 
> New Ctrl+N 
> [Press Escape]
> Context Menu 
> Project 
> menu 
> New Ctrl+N 
> [Press Escape]
> Context Menu 
> Project 
> menu 
> New Ctrl+N

After closing the dropdown, submenu is reopened and announced again as a context menu.

NVDA is similar to Narrator but focus moves to the whole window instead of staying on closed dropdown item.

#### Expected behavior

After dropdown is dismissed, top-level menu item is announced as currently focused item, and the focus highlight moves to it. 

### Steps to reproduce

1. Add a MenuStrip with a menu item with submenu (e.g. via Insert Standard Items button), or open Menus form on WinformsControlsTest app.
2. Start Narrator
3. Expand and close the menu item

**Comment by Nora-Zhou01** [comment]
Verified this on .NET latest build: 8.0.100-preview.2.23116.17,issue was fixed , Tested in Narrator, NVDA, JAWS, after the drop-down menu is cancelled, the top-level menu item is declared as the current focus item and the focus moves to it. please check below gif:
Narrator:
![menu](https://user-images.githubusercontent.com/104609169/219566829-03a2a0e4-d306-4b09-ac66-43f2a2aa72ba.gif)
NVDA:
![NVDA](https://user-images.githubusercontent.com/104609169/219566884-54239a0b-2929-48ee-8dd3-543106e8a72b.gif)
