### ISSUE TITLE
System.InvalidOperationException: 'Object is currently in use elsewhere.'  occurs when using BackgroundWorker.

### ISSUE THREAD

**Issue by VasanthkumarDurairaj** [dotnet/winforms#8438]
### .NET version

.Net 6.0

### Did it work in .NET Framework?

No

### Issue description

I have drawn and animated an image inside the BackgroundWorker in a ButtonClick.
If I click the button continuously to show the animated image, the form is sent to not respond for a few seconds. When debugging the code, it throws a System.InvalidOperationException: 'Object is currently in use elsewhere.' in the DrawImage method.

**Image Reference**
<img width="547" alt="image" src="https://user-images.githubusercontent.com/92776903/209958924-fda9b301-3712-49d5-92c2-3944d9ffec87.png">

### Steps to reproduce

1. Run the sample.
2. Click the button continuously, the form is not responding for a few seconds. If I add breakPoint in a button click, then throws an exception in Graphics.DrawImage method.

[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/10319714/WinFormsApp1.zip)

**Comment by elachlan** [comment]
Is the example code in the screenshot happening in the background workers dowork or onworkcompleted event?

Any graphics operations should happen on the UI thread as far as I am aware. So you will need to either do the drawimage call in onworkcompleted, or use this.beginInvoke to have it execute on the UI thread.

**Comment by merriemcgaw** [comment]
> Any graphics operations should happen on the UI thread as far as I am aware. 

Agreed 💯

**Comment by VasanthkumarDurairaj** [comment]
@elachlan, thanks and it worked.

**Comment by elachlan** [comment]
@VasanthkumarDurairaj not a problem. Feel free to close the issue.
