### ISSUE TITLE
[LOC] Don't translate Home, Backspace, End and Enter keys in KeysConverter for Japanese.

### ISSUE THREAD

**Issue by turqTanza** [dotnet/winforms#8440]
### Which files are affected?

src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf

### Which languages are affected?

Japanese

### Problem
Currently, following keys is translated in Japanese:
- toStringHome
- toStringBack
- toStringEnd
- toStringEnter

### Expected
Home, Backspace, End and Enter keys in Japanese keyboard is not translated.

(Reference) Japanese osk.exe screenshot:
![JapaneseOsk](https://user-images.githubusercontent.com/38393610/210160934-084589d8-a1b6-4236-b3a7-f1ed8c31123f.png)

**Comment by elachlan** [comment]
@dreddy-work / @merriemcgaw should we not be translating these keys in any language?

List of keys which are translated:
https://github.com/dotnet/winforms/blob/1be4ac0524287c704cc14b4f28fb580649bf0f1e/src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs#L39-L61

My quick google of different culture's keyboards shows that the keys show their values in English.

**Comment by turqTanza** [comment]
@elachlan Extracted from "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\ja\System.Windows.Forms.resources.dll". (Win11 22H2 10.0.22621.1105)
```
  <data name="toStringHome" xml:space="preserve">
    <value>Home</value>
  </data>
  <data name="toStringEnd" xml:space="preserve">
    <value>End</value>
  </data>
  <data name="toStringBack" xml:space="preserve">
    <value>Back</value>
  </data>
  <data name="toStringEnter" xml:space="preserve">
    <value>Enter</value>
  </data>

  <data name="toStringControl" xml:space="preserve">
    <value>Ctrl</value>
  </data>
  <data name="toStringPageDown" xml:space="preserve">
    <value>PgDn</value>
  </data>
  <data name="toStringInsert" xml:space="preserve">
    <value>Ins</value>
  </data>
  <data name="toStringNone" xml:space="preserve">
    <value>(なし)</value>
  </data>
  <data name="toStringDelete" xml:space="preserve">
    <value>Del</value>
  </data>
  <data name="toStringAlt" xml:space="preserve">
    <value>Alt</value>
  </data>
  <data name="toStringPageUp" xml:space="preserve">
    <value>PgUp</value>
  </data>
  <data name="toStringShift" xml:space="preserve">
    <value>Shift</value>
  </data>
```

**Comment by turqTanza** [comment]
NOTE: Please careful localization in German.

.NET Framework System.Windows.Forms.resources.dll in German:
```
  <data name="toStringControl" xml:space="preserve">
    <value>Strg</value>
  </data>
  <data name="toStringInsert" xml:space="preserve">
    <value>Einfg</value>
  </data>
  <data name="toStringHome" xml:space="preserve">
    <value>Pos1</value>
  </data>
  <data name="toStringBack" xml:space="preserve">
    <value>Zurück</value>
  </data>
  <data name="toStringDelete" xml:space="preserve">
    <value>Entf</value>
  </data>
  <data name="toStringEnd" xml:space="preserve">
    <value>Ende</value>
  </data>
  <data name="toStringEnter" xml:space="preserve">
    <value>Eingabetaste</value>
  </data>
  <data name="toStringShift" xml:space="preserve">
    <value>Umschalttaste</value>
  </data>
```

**Comment by dreddy-work** [comment]
So, for some reason, only Japanese key strings are not translated on OS key layout?

**Comment by turqTanza** [comment]
> So, for some reason, only Japanese key strings are not translated on OS key layout?

Yes. For Japanese, we expected that Enter, Backspace, Home and End keys are not translated.
.NET Framework version is expected, .NET Core or later is bugged.
(Our stakeholder says "too bad design" for "Ctrl+終了". Japanese users could not understand "Ctrl+終了".)

![image](https://user-images.githubusercontent.com/38393610/211924940-a9c56b1b-59f9-49d0-8c7e-61a238ab2a99.png)

**Comment by turqTanza** [comment]
FYI
Additionaly, I researched .NET Framework 4.8 Language Packs for Simplified Chinese, Traditional Chinese and Korean. 
I think there is a similar problem with these language resources.

|Identifier|Japanese|Simplified Chinese|Traditional Chinese|Korean|
|---|---|---|---|---|
|toStringHome|Home|Home|Home|Home|
|toStringEnd|End|End|End|End|
|toStringBack|Back|BackSpace|Back|Back|
|toStringEnter|Enter|Enter|Enter|Enter|
|toStringControl|Ctrl|Ctrl|Ctrl|Ctrl|
|toStringShift|Shift|Shift|Shift|Shift|
|toStringAlt|Alt|Alt|Alt|Alt|
|toStringPageDown|PgDn|Page Down|Page Down|PgDn|
|toStringPageUp|PgUp|Page Up|Page Up|PgUp|
|toStringInsert|Ins|Insert|Ins|Ins|
|toStringDelete|Del|Delete|Del|Del|
|toStringNone|(なし)|(无)|(無)|(없음)|

**Comment by elachlan** [comment]
@dreddy-work will the internal loc team review each languages keys/keyboard layout for the special keys that are outlined here? Or just Japanese?

**Comment by dreddy-work** [comment]
@elachlan, They will go over the list that we specify here.

**Comment by elachlan** [comment]
@merriemcgaw did the internal lock team get to doing this?

**Comment by merriemcgaw** [comment]
Great catch - that totally slipped off our radar and the internal item had been closed. We will circle back and try to get this wrapped up for .NET 8. Thanks once again!!

**Comment by dreddy-work** [comment]
Following up with loc team.

**Comment by dreddy-work** [comment]
@Olina-Zhang, can you help confirm what are all the languages we need to prevent localization for these keys? We can check windows on screen keyboard layout for .NET supported languages here or if you can get the list form .NET framework languages packs, that should help too. 

@turqTanza, is your list above is a complete set or they are just what you checked so far?

**Comment by turqTanza** [comment]
@dreddy-work
> complete set or they are just what you checked so far?

I checked the parts that I thought were suspicious.
If possible, I would like to ask for someone to cross-check.

**Comment by Olina-Zhang** [comment]
@dreddy-work Do we just need to verify the 13 localized languages supported by VS to see if this over-translation problem exists？In that case, we will install machines to confirm next week.

**Comment by dreddy-work** [comment]
Yes. Please. Please check in what languages they need to be translated and in which they don't. I would compare with Windows onscreen keyboard for consistency.

**Comment by Olina-Zhang** [comment]
@dreddy-work, tested this issue on 13 local languages Visual Studio supported in created Winforms .Net 8.0 and .Net framework 4.8.1 application, compared with Windows onscreen keyboard. It reproduces in 4 kinds of local languages: Czech, German, Japanese, Russian, and doesn't reproduce in other 9 local languages: Chinese(Simplified), Chinese(Traditional), French, Italian, Korean, Polish, Portuguese(Brazil), Spanish, Turkish.
Details is in our internal OneNote page: [here ](https://microsoft.sharepoint.com/teams/MerriesWinFormsandSetup/_layouts/OneNote.aspx?id=%2Fteams%2FMerriesWinFormsandSetup%2FShared%20Documents%2FTest%20Requests%2FTesting%20Results%20from%20CTI&wd=target%28Private%20testing%20in%20.Net%208.0.one%7CC02A9429-C1BF-4485-A4B3-B3A7B1AFDDF4%2FRepro%20GH%20issue%3A%208440%7C764FED2F-5078-4462-8CB1-5B7B0F5E10E5%2F%29).

**Comment by dreddy-work** [comment]
Thanks @Olina-Zhang.

**Comment by Philip-Wang01** [comment]
Verified this on .NET latest build: 8.0.100-rc.1.23402.12, issue was fixed in 3 kinds of local languages: Czech, Japanese, Russian.
But this issue still repro's in German local language. Here are the test results:

![image](https://github.com/dotnet/winforms/assets/86937911/561778f0-bdd2-4445-9060-4a5ae4e57ec6)

.NET framework 4.8.1 in German local language:
![image](https://github.com/dotnet/winforms/assets/86937911/aa55922d-6f12-4478-9943-3399d0de4b14)

**Comment by Philip-Wang01** [comment]
@dreddy-work Please see this: https://github.com/dotnet/winforms/issues/9660.

**Comment by Eudora-Li01** [comment]
Verified this issue on release/8.0-rc1 branch, it was fixed in 4 kinds of local languages: Czech, Japanese, Russian and German.
.NET Core:
![image](https://github.com/dotnet/winforms/assets/130345015/cd69279b-67dd-4ae4-b297-5a175807649c)
.NET Framework:
![image](https://github.com/dotnet/winforms/assets/130345015/57e083e8-053e-4c9b-9626-b5b8cf0e28b1)
