### ISSUE TITLE
WinForms MDI - StartupNextInstance event handler doesn't display new mdi child

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#8441]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinForms-MDI---StartupNextInstance-event/10240419)._

---
[severity:It bothers me. A fix would be nice]
It fails to display a new MDI child within the StartupNextInstance event handler. After completion of the handler the following error is reported: "System.InvalidOperationException" in System.Windows.Forms.dll

An example can be found here: https://github.com/RalphLAtGitHub/WinFormsDemo

---
#### Feedback Bot on 12/29/2022, 11:03 AM: 

(private comment, text removed)
#### Melon Wang [MSFT] on 12/29/2022, 04:33 PM: 

(private comment, text removed)
#### RalphL on 12/29/2022, 05:10 PM: 

(private comment, text removed)
#### Melon Wang [MSFT] on 12/30/2022, 10:13 AM: 

(private comment, text removed)
#### RalphL on 12/30/2022, 02:02 PM: 

(private comment, text removed)
#### Melon Wang [MSFT] on 12/30/2022, 02:41 PM: 

(private comment, text removed)
#### RalphL on 12/30/2022, 02:48 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MelonWang1** [comment]
**.NET Core build:** 
.NET SDK 8.0.100-alpha.1.22622.3

**Did it work in .NET Framework?**
Yes

**Did it work in any of the earlier releases of .NET Core or .NET 5+?**
Yes, it does not repro on .NET 5.0.

**Repro Steps:**

1. Build and run attached project [WinFormsDemo.zip](https://github.com/dotnet/winforms/files/10334082/WinFormsDemo.zip).
2. Click button "Start 2nd instance"

**Actual result:**
The "TestForm 2" designer does not displayed.
![8](https://user-images.githubusercontent.com/94418985/210293183-3d35aaac-a91f-4430-b54a-8b578f676f63.gif)
**Expected result:**
The "TestForm 2" designer displayed.
![Screenshot 2023-01-02 180153](https://user-images.githubusercontent.com/94418985/210293189-d671b38b-dab4-4d59-ad9a-f1c5c4a736b0.png)
![5](https://user-images.githubusercontent.com/94418985/210293201-df14bb7a-a77d-4b48-83aa-b0df2fb26a76.gif)
**More info:**

1. This issue does not repro on .NET Framework.
2. This issue does not repro on .NET5.0.

**Comment by Tanya-Solyanik** [comment]
@MelonWang1  - does this issue repro in .NET 7?

**Comment by MelonWang1** [comment]
@Tanya-Solyanik Yes, this issue repro in .NET 8.0, .NET 7.0, .NET 6.0, and it does not repro in .NET 5.0.

**Comment by JeremyKuhne** [comment]
In the ScratchProject this can be added to Form1:

``` C#
    protected override void OnLoad(EventArgs e)
    {
        base.OnLoad(e);

        Button m_Button = new()
        {
            Font = new Font(Font, FontStyle.Bold),
            Height = 50,
            Width = ClientRectangle.Width - 6,
            Text = "Start 2nd instance"
        };

        Controls.Add(m_Button);
        m_Button.Location = new Point(ClientRectangle.Right - m_Button.Width - 3, ClientRectangle.Bottom - m_Button.Height - 3);
        m_Button.Click += (object? sender, EventArgs e) => Process.Start(Application.ExecutablePath);

        Form m_TestForm = new() { MdiParent = this, Text = "TestForm 1" };
        m_TestForm.Show();
        m_TestForm.Location = new Point(10, 10);
        m_Button.Select();
    }
```

And the Designer.cs:

``` C#
    private void InitializeComponent()
    {
        this.components = new System.ComponentModel.Container();
        this.AutoScaleDimensions = new SizeF(7.0f, 15.0f);
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        this.ClientSize = new System.Drawing.Size(800, 450);
        this.IsMdiContainer = true;
        this.Name = "Form1";
        this.StartPosition = FormStartPosition.CenterScreen;
        this.Text = "MDI-Parent";
    }
```

**Comment by JeremyKuhne** [comment]
Took me a few to recognize this is a feature of the VB `WinFormsApplicationBase`.

The exception is the following:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cross-thread operation not valid: Control 'Form1' accessed from a thread other than the thread it was created on.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.get_Handle()


>	System.Windows.Forms.dll!System.Windows.Forms.Control.Handle.get()	Unknown
 	System.Windows.Forms.Primitives.dll!Interop.User32.SetForegroundWindow(IHandle hWnd)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Form.Activate()	Unknown
 	Microsoft.VisualBasic.Forms.dll!Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnStartupNextInstanceMarshallingAdaptor(string[] args)	Unknown
 	Microsoft.VisualBasic.Forms.dll!Microsoft.VisualBasic.ApplicationServices.SingleInstanceHelpers.VB$StateMachine_2_WaitForClientConnectionsAsync.MoveNext()	Unknown
 	[Resuming Async Method]	
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<Microsoft.VisualBasic.ApplicationServices.SingleInstanceHelpers.VB$StateMachine_2_WaitForClientConnectionsAsync>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<Microsoft.VisualBasic.ApplicationServices.SingleInstanceHelpers.VB$StateMachine_2_WaitForClientConnectionsAsync>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<Microsoft.VisualBasic.ApplicationServices.SingleInstanceHelpers.VB$StateMachine_2_WaitForClientConnectionsAsync>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.SetExistingTaskResult(System.Threading.Tasks.Task<System.__Canon> task, System.__Canon result)	Unknown
 	[Completed] Microsoft.VisualBasic.Forms.dll!Microsoft.VisualBasic.ApplicationServices.SingleInstanceHelpers.VB$StateMachine_4_ReadArgsAsync.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.AsyncStateMachineBox<Microsoft.VisualBasic.ApplicationServices.SingleInstanceHelpers.VB$StateMachine_4_ReadArgsAsync>.ExecutionContextCallback(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread threadPoolThread, System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<string[]>.AsyncStateMachineBox<Microsoft.VisualBasic.ApplicationServices.SingleInstanceHelpers.VB$StateMachine_4_ReadArgsAsync>.MoveNext(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.AsyncStateMachineBox<Microsoft.VisualBasic.ApplicationServices.SingleInstanceHelpers.VB$StateMachine_4_ReadArgsAsync>.ExecuteFromThreadPool(System.Threading.Thread threadPoolThread)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	System.Private.CoreLib.dll!System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()	Unknown

```

**Comment by JeremyKuhne** [comment]
@KlausLoeffelmann you'll have much more success navigating this than I would. The callback is not happening on the UI thread as it used to.

**Comment by KlausLoeffelmann** [comment]
I might have an idea, why that is. In the .NET 6 timeline, I remember I fixed a Framework 2.0-old bug, which effectively lead to a spin-wait for the splash-dialog. That might have regressed this, but it should be an easy fix. Let's schedule this for .NET 9.

**Comment by John-Qiao** [comment]
Verified this issue in Winforms main branch for .NET 9.0, it has been fixed that "TestForm 2" designer shows after clicked button.

![8441-testresult](https://github.com/dotnet/winforms/assets/45864985/b2a137be-1c1a-4fb4-809e-77a0a0a1def4)

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net 8.0 SDK build: 8.0.100-rtm.23470.15, it was fixed with same result as above validation.

**Comment by Nora-Zhou01** [comment]
Verified with .NET SDK 8.0.100-rc.2.23477.19 test pass build, it has been fixed that "TestForm 2" designer shows after clicked button.
