### ISSUE TITLE
Error in Menustrip's shortcutkey property

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#8456]
### .NET version

8.0.100-alpha.1.23054.7

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes,it cannot repro on .NET 6.0 & 7.0 SDK builds.

### Issue description

Error in MenuStrip's shortcutkey property, default is "none"

### Steps to reproduce

1. Create a .NET 8.0 WinForms project.
2. Add **MenuStrip** control.
3. Add MenuItem control inside MenuStrip.
4. Click "**Type here**" to set the text property to "TEST".
5. Observe MenuItem's **Shortcutkey** property value in Properties Window.

Or 

1. Extract and open [WinFormsApp28.zip](https://github.com/dotnet/winforms/files/10350587/WinFormsApp28.zip) use VS.
2. Observe MenuItem's Shortcutkey property in Properties Window.

**Actual result:**
Error in MenuStrip's shortcutkey property, displaying "Enter+F12+F11+F10+End+Ctrl+F8+F9+Alt+F4+F5+F6+F7+F1+F2+F3+PgDn+Ins+Home+Del+Shift+PgUp+Back+0+1+2+3+4+5+6+7+8+9+0"
![T1](https://user-images.githubusercontent.com/104609169/210736985-a49e699f-25b7-4d32-9499-44eac8c81159.png)
![TEST](https://user-images.githubusercontent.com/104609169/210737692-59d40a45-ecc3-488b-8bca-bc0287bb6aa1.gif)

**Expected result:**
The shortcutkey property in MenuStrip should default to "none".
![T2](https://user-images.githubusercontent.com/104609169/210737529-bec4d2bf-11a3-405b-9e8d-b0ae2ded2e72.png)
**More Info:**

1. This issue doesn't repro on .NET Framework.
3. This issue doesn't repro on .NET 7.0, .NET 6.0.
4. VS Version:The latest main VS build.
5. This is a regression issue, it cannot reproduce on .NET version 8.0.100-alpha.1.22601.15. build.
6. Reproduced in version 8.0.100-alpha.1.22607.6 and above.

**Comment by merriemcgaw** [comment]
@dmitrii-drobotov - can you see if this is a regression from recent code changes? @Tanya-Solyanik can consult of course.

**Comment by merriemcgaw** [comment]
And @Nora-Zhou01 - great find!

**Comment by elachlan** [comment]
We did some refactoring of `KeysConverter` which might have caused this in #8255

**Comment by elachlan** [comment]
Confirmed. This test below fails, I will put in a PR to fix it.
```csharp
[Fact]
public void ConvertToString_None()
{
    KeysConverter converter = new();
    var result = converter.ConvertToString(Keys.None);
    Assert.Equal("None", result);
}
```

**Comment by elachlan** [comment]
I don't believe it would have been isolated to the MenuStrip control. It would have been all controls.

**Comment by Olina-Zhang** [comment]
> I don't believe it would have been isolated to the MenuStrip control. It would have been all controls.

We found this issue in ToolStripMenuItem and sub-MenuItems for MenuStrip/ToolStrip/StatusStrip/ContextMenuStrip controls

**Comment by elachlan** [comment]
I'd say where ever `ShortcutKeys` is present, this bug would also be present.

**Comment by MelonWang1** [comment]
Verified this issue on .NET SDK latest build: 8.0.100-alpha.1.23068.16, issue was fixed that the shortcutkey property in MenuStrip is default to "none".
![8456](https://user-images.githubusercontent.com/94418985/213388529-ce0023aa-6c95-449d-b099-77803b0ed6a2.png)

**Comment by John-Qiao** [comment]
Verified with .NET 8 Preview 1 TP build: .NET 8.0.100-preview.1.23108.10, issue was fixed as same as above test result.
