### ISSUE TITLE
Updating the bounds of anchored controls leads to an incorrect location of the control

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#8494]
### .NET version

8.0.100-alpha.1.23061.8 + latest winforms dlls

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in .NET Core 3.1 and .NET 5.0/6.0/7.0/8.0(without latest winforms dlls)

### Issue description

The X and Y values in **newRect** should be the same as values in **c.Bounds**.
![GetImage](https://user-images.githubusercontent.com/45864985/212028009-b281fc59-46a7-47f5-bbb9-68dae6ee278e.png)

### Steps to reproduce

1. Download the test case project from here: https://microsoft-my.sharepoint.com/:u:/g/personal/v-peqiao_microsoft_com1/ERuveT35qepKkfb15DOVQl0BoIsTvsTQfUc1XyNSeqyYyg?e=FUvmnA
2. Open the **XPropertyGrid** project in VS.
3. Open the **XControl.cs** in **WFCTestLib** project>>**ReflectTools**>>**AutoPME** node.
4. Set the debug point at 3791 line.
5. Star to debug the **XPropertyGrid** project.
6. Check the X and Y values in **newRect** and **c.Bounds** when debug stopped at 3791 line in XControl.cs file.

![Setbounds](https://user-images.githubusercontent.com/45864985/212031866-a1b03e66-646f-420e-9e7f-9f858a0eed36.gif)

**Comment by dreddy-work** [comment]
Can we get a simple repro app here?

**Comment by John-Qiao** [comment]
@dreddy-work we tried, but it works well in the new created app.

**Comment by elachlan** [comment]
@John-Qiao are values for `MaximumSize` and `MinimumSize` set?

Additionally, is the controls handle created when this code is triggered?

**Comment by dreddy-work** [comment]
Anchors of the control is interfering with setting bounds at runtime. I will be digging further to see if i can create a simple scenario here before looking into fix.  Meanwhile, we can unblock the test by opting out from the Anchor Layout if needed. Will update as i make progress here.

**Comment by dreddy-work** [comment]
Found the issue. A layout pass is done before updating anchors for the new bounds assigned and thus resetting the location. Working on solution.

**Comment by Philip-Wang01** [comment]
Verified this on .NET 8.0.100-preview.5.23253.20, issue was fixed, anchors of the control do not interfere with setting bounds at runtime. In addition, ran migrated automation cases with no issue.

**Comment by Olina-Zhang** [comment]
Verified it in VS insertion PR with .Net 8 Preview 4 test pass build: 8.0.0-preview.4.23253.2, affected automation cases were passed
