### ISSUE TITLE
[ 8.0.100-alpha.1.23060.3] mRemoteNg app Error creating window handle error while creating Combobox

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/winforms#8495]
### .NET version

```
.NET SDK:
 Version:   8.0.100-alpha.1.23060.3
 Commit:    c5ebd18478

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-alpha.1.23060.3\

Host:
  Version:      8.0.0-alpha.1.23058.2
  Architecture: x64
  Commit:       5da4a9e919

.NET SDKs installed:
  8.0.100-alpha.1.23060.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-alpha.1.23058.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-alpha.1.23058.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-alpha.1.23057.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Did it work in .NET Framework?

N/A

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

**Verify Scenarios:**

1) Windows 10 21H2 AMD64 + 8.0.100-alpha.1.23061.8: Fail
2). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-alpha.1.23060.31: Fail
3) Windows 10 21H2 AMD64 + dotnet-sdk-7.0.102-win-x64: Pass
4). Windows 10 21H2 AMD64 + dotnet-sdk-6.0.405-win-x64: Pass

### Issue description

When test 3rd party mRemoteNg app with .NET 8 runtime, exception "error creating window handle error" shows while creating Combobox.

**Application Name**:  mRemoteNg(1.77.3)
**OS**: Windows 10 21H2
**CPU**: X64
**.NET Build Number:** dotnet-sdk-8.0.100-alpha.1.23060.3
App or App Source checking at: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1717274
**Github Link**: https://github.com/mRemoteNG/mRemoteNG

### Steps to reproduce

**The machine only has 8.0 installed. And DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2 is set.**

1.Copy app from AppSource\SourceShare\mRemoteNG  to machine
2.Launch the app from mRemoteNG.exe
3.If you see update window, click ask me later
4.Click Tools=>Port Scan

**Expected Result:** 
Port Scan Tab should open without error

**Actual Result:**
![image](https://user-images.githubusercontent.com/83067197/212040757-a0389789-ff38-4cbb-8aeb-868cb001bb3d.png)

**Exception:**
Exception Message
"Error creating window handle."
```
Stack trace
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.ComboBox.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, WM msg, WPARAM wparam, LPARAM lparam)

Environment
OS: Microsoft Windows NT 10.0.19045.0
mRemoteNG Version: 1.77.3
Edition: MSI
Cmd line args:

```
**Findings:**
We think this error happens when creating combobox control, app is overriding OnCreateControl, when we remove DrawMode = DrawMode.OwnerDrawFixed, issue does not repro.
In this file: mRemoteNG-1.77.3-dev\mRemoteNG\UI\Controls\mrngComboBox.cs
```
 protected override void OnCreateControl()
  {
            base.OnCreateControl();
            _themeManager = ThemeManager.getInstance();
            if (!_themeManager.ActiveAndExtended) return;
            BackColor = _themeManager.ActiveTheme.ExtendedPalette.getColor("ComboBox_Background");
            ForeColor = _themeManager.ActiveTheme.ExtendedPalette.getColor("ComboBox_Foreground");
             DrawMode = DrawMode.OwnerDrawFixed;  //if we remove, issue does not repro
            SetStyle(ControlStyles.OptimizedDoubleBuffer |
                     ControlStyles.UserPaint, true);
}
```
@dotnet-actwx-bot @dotnet/compat

**Comment by dreddy-work** [comment]
@Olina-Zhang , can you confirm if this is regression only in .NET 8.0?

**Comment by dreddy-work** [comment]
> @Olina-Zhang , can you confirm if this is regression only in .NET 8.0?

Nevermind. it is.

**Comment by JeremyKuhne** [comment]
@merriemcgaw @dreddy-work @Olina-Zhang: The share has nothing in it. Perhaps a rights issue?

**Comment by dreddy-work** [comment]
@JeremyKuhne , i attached app here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1717274

**Comment by JeremyKuhne** [comment]
@dreddy-work Thanks- can you elaborate/follow up on why I can't see things?

**Comment by JeremyKuhne** [comment]
First guess is something elsewhere is throwing when attempting to create the handle.

**Comment by dreddy-work** [comment]
> @dreddy-work Thanks- can you elaborate/follow up on why I can't see things?

Assuming you are on VPN. I do not know if it required in specific access permissions. Will check.

**Comment by JeremyKuhne** [comment]
> Assuming you are on VPN

Yes

**Comment by JeremyKuhne** [comment]
@dreddy-work The attached zip is empty.

**Comment by Junjun-zhao** [comment]
@JeremyKuhne I have granted you the access to source share folder, please try it again and let me know if you still have problems. Thanks.

**Comment by lonitra** [comment]
@Junjun-zhao could you also give me access? The attached zip is empty for me as well.

**Comment by Junjun-zhao** [comment]
@lonitra Done. Please have a try and let me know if any issues. Thanks.

**Comment by lonitra** [comment]
Hm, am I doing something wrong here? Going to the app source link that is in azure gives me file not found error. I've also tried the attachments, but after downloading that is empty. Is there some other way I can get to these?

**Comment by dreddy-work** [comment]
I'm not sure why Azdo is not uploading it correctly. @lonitra , i copied to OneDrive here: https://microsoft-my.sharepoint.com/:u:/p/dreddy/Ebz2q8akUuZHpiUADzOsE_IBgzJvxHH4TZ5YQSzUC7sGPw?e=01cYFd . Let me know if you still can not connect.

**Comment by lonitra** [comment]
I can access it through your link, thank you @dreddy-work !

**Comment by merriemcgaw** [comment]
@lonitra are you able to debug through the scenario yet? This does seem to be a corner case with a custom ComboBox control that is setting its `DrawMode` to `OwnerDraw.Fixed`. Maybe we can look at their code to set up a very small repro and play with that setting?

@Junjun-zhao do you/can you provide lab machines for us to connect to with the repo app already set up for testing? I _think_ we can come up with the trimmed down repro ourselves but it would save a lot of effort if we had a VM where the app and code were ready to go.

**Comment by Junjun-zhao** [comment]
@merriemcgaw Sure. We have setup a repro machine today, please get the repro machine information from https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1717274.

**Comment by Junjun-zhao** [comment]
@Cassie-Li01 Done. Please have a try and let me know if any questions. Refer to Devdiv bug for the [specific path](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1717274).

**Comment by Cassie-Li01** [comment]
Verified on latest .NET 8.0 version 8.0.100-preview.2.23123.5, issue is fixed. Gif as below:
![fixed](https://user-images.githubusercontent.com/96758262/221081669-5e790373-41b1-49dc-841f-fe641a1eb44b.gif)

**Comment by MandiMan** [comment]
Verified this on .NET 8.0 Preview 2.0 TP build: 8.0.100-preview.2.23151.8, issue was fixed and Port Scan Tab could open without error. Test result is same as above GIF.
