### ISSUE TITLE
RichTextBox could not be used in VS designer

### ISSUE THREAD

**Issue by ismlsmile** [dotnet/winforms#8514]
### Environment

17.4.4

### .NET version

7.0.102

### Issue description
when drag a RichTextBox to a Form, VS Designer will show this error:
Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more

![image](https://user-images.githubusercontent.com/1876179/213693437-a7444221-4877-457d-a087-415f1a4e3970.png)

### Steps to reproduce

just drag a RichTextBox to a Form

**Comment by r-aghaei** [comment]
I could not reproduce the issue. 
@ismlsmile I tested in the the following environment and it works as expected:
```
VS: 17.4.4
.NET SDK :   7.0.102
Windows:  10.0.19043
.NET Runtime:  7.0.2
```

**Comment by merriemcgaw** [comment]
@ismlsmile - is your project bringing in anything trimmed or AOT'ed? Or there's a switch by which you can turn this off that might have gotten set for the project. This is not the default behavior for a vanilla WinForms app in Visual Studio.

**Comment by elachlan** [comment]
@ismlsmile could you put together a small project to reproduce the problem?
