### ISSUE TITLE
[LOC] KeysConverter returns "None" for Windows.Forms.Keys::None in all languages

### ISSUE THREAD

**Issue by riverar** [dotnet/winforms#8527]
### Which files are affected?

Previously reported at https://github.com/File-New-Project/EarTrumpet/issues/548.
Related area https://github.com/dotnet/winforms/issues/8440.

Steps to reproduce:
1. Log into a non-English machine
2. Run the following PowerShell snippet:

  ```powershell
  [Reflection.Assembly]::LoadFile("C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.10\System.Windows.Forms.dll") | Out-Null
  $Converter = New-Object Windows.Forms.KeysConverter
  $Converter.ConvertToString($Null, [System.Globalization.CultureInfo]::CurrentUICulture, [Windows.Forms.Keys]::None)
  ```
3. Observe `None` output

### Which languages are affected?

All non-English

**Comment by elachlan** [comment]
@riverar see: #8401

**Comment by riverar** [comment]
Thanks, looks promising. Looks like it may regress app persisted shortcuts though.

**Comment by elachlan** [comment]
Could you please bring that up in the PR?

**Comment by riverar** [comment]
PR looks great, we can close this as a dupe if you'd like.

**Comment by dreddy-work** [comment]
addressing in #8401.
