### ISSUE TITLE
[API Proposal]: add ToolStripItem.SelectedChanged event

### ISSUE THREAD

**Issue by v-elnovikova** [dotnet/winforms#8548]
### Background and motivation

This is a follow-up to #3572

.NET Core 3.1 introduced a [breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/winforms#removed-controls) in using Menus. MenuItem control was removed and ToolStripMenuItem is recommended as a replacement.

However, the new ToolStripMenuItem class is missing the equivalent to MenuItem's [Select](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.menuitem.select?view=netframework-4.8) event, that fires when menu item is highlighted by mouse or keyboard.

This event is most commonly used to display hints/descriptions/feedback to user when they navigate through menu items.

Some workarounds are the following ToolStripMenuItem's events: `MouseEnter`, `MouseLeave`, `MouseHover`, etc. But this does not cover the selection of a ToolStripMenuItem via keyboard (e.g. arrow keys).

Adding a new `SelectedChanged` event to the ToolStripItem class could be a solution to the problem. The event fires every time the [Selected](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem.selected?view=windowsdesktop-7.0) property value changes, similar to [AvailableChanged](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem.availablechanged?view=windowsdesktop-7.0) or [EnabledChanged](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem.enabledchanged?view=windowsdesktop-7.0) events.

### API Proposal

```csharp
namespace System.Windows.Forms
{
    public class ToolStripItem
    {
        ...
        public event EventHandler? SelectedChanged;
        protected virtual void OnSelectedChanged(EventArgs e);
    }
}
```

### API Usage

Here the SelectedChanged event is used to show a hint whenever user selects menu item with mouse or keyboard:
```csharp
ToolStripMenuItem menuItem = new();
Label hintLabel = new();

menuItem.SelectedChanged += (object sender, EventArgs e) => 
{
    hintLabel.Text = menuItem.Selected ? "Menu item selected!" : string.Empty;
};
```

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.Windows.Forms
{
    public partial class ToolStripItem
    {
        public event EventHandler? SelectedChanged;
        protected virtual void OnSelectedChanged(EventArgs e);
    }
}
```

**Comment by Olina-Zhang** [comment]
Tested the fix in the latest .Net 9.0 SDK build: 9.0.100-alpha.1.23618.4, when using keyboard to focus or leave toolStripMenuItem, the SelectedChanged event is invoked once, but when using mouse to focus, the SelectedChanged event is invoked twice. @Epica3055 could you please look at it if the behavior is expected?

https://github.com/dotnet/winforms/assets/26474449/cc77886c-230b-40bc-a0d5-3f115c43baed

**Comment by Epica3055** [comment]
@Tanya-Solyanik hi, I need to discuss this with you.

In framework, `MenuItem` have `Select` event. when the item's selection status turns from unselected to selected, the event will be fired. But when status turns from selected to unselected, the event won't be fired.

The question is what is expected behavior in .Net?

In the issue description, `ToolStripItem.SelectedChanged` , from semantic view, I think the event should be fired when the item's selection status turns from unselected to selected **and** from selected to unselected.

But that's not the case in Framework.

**Comment by Tanya-Solyanik** [comment]
@Epica3055  - what you are saying about symmetric behavior makes sense, if we were implementing a completely new event, we would had raised it in both cases - Selected->Unselected and Unselected -> Selected. However, the purpose of this implementation is to simplify migration from .NET Framework, so we should implement the same behaviour as the .NET Framework has.

**Comment by elachlan** [comment]
Closing issue as the PR and follow up have been merged.
