### ISSUE TITLE
Accessibility: Invalid BoundingRectangle value for PropertyGridView entries

### ISSUE THREAD

**Issue by vladimir-krestov** [dotnet/winforms#856]
In case the PropertyGrid's viewport is smaller than the space required to show all bound object properties, a vertical scroll bar appears. So some of the property entries are out of the viewport (and fully hidden) and some are shown partially (for instance, the half of a row height is visible for the row in the bottom). These entries' BoundingRectangle property is not correct as has the height and width of a similar row but which fits in the viewport entirely and is fully visible to the user. This incorrect behavior can be observed using Inspect tool.

**Expected result:**
Bounding rectangle for all PropertyGrid items should be within the parent element.

**Comment by M-Lipin** [comment]
Issue in DevDiv: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1046781
