### ISSUE TITLE
[Tracking] Investigate Windows 10 Restriction Check on Switches

### ISSUE THREAD

**Issue by lonitra** [dotnet/winforms#8566]
Via discussion https://github.com/dotnet/winforms/pull/8556#discussion_r1096222194 , it may not be necessary to do a check if OS version is Windows 10 here
https://github.com/dotnet/winforms/blob/81e690c4e5fccb0843815c05dfbe261f669862ee/src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs#L97
but investigation needs to be done.

**Comment by dreddy-work** [comment]
https://github.com/dotnet/winforms/pull/8695
