### ISSUE TITLE
[Tracking] WCAF* analyzer diagnostics needs to be documented

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#8572]
The [analyzer dignostics](https://github.com/dotnet/winforms/blob/a8f51bd3d2690890a6ea2ae0d8d084aab0a1b926/docs/list-of-diagnostics.md#analyzer-warnings) need to be documented at [https://learn.microsoft.com](https://learn.microsoft.com/dotnet/desktop/winforms/wfdev-diagnostics/obsoletions-overview) and the links updated at aka.ms.

**Comment by dreddy-work** [comment]
Very old. @lonitra can you cross check and close accordingly.

**Comment by lonitra** [comment]
https://github.com/dotnet/docs/issues/37626
