### ISSUE TITLE
Editing with nested TableLayoutPanel adds additional Row and Column Styles whenever form is edited

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#8576]
### Environment

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.5.0 Preview 5.0

### .NET version

.New 7.0 but don't matter issue is designer.

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Before OOP Designer

### Issue description

Before edit
```
        TableLayoutPanelTopEx1.ColumnStyles.Add(New ColumnStyle())
        TableLayoutPanelTopEx1.ColumnStyles.Add(New ColumnStyle(SizeType.Percent, 100.0F))
        TableLayoutPanelTopEx1.Dock = DockStyle.Fill
        TableLayoutPanelTopEx1.LabelText = ""
        TableLayoutPanelTopEx1.Location = New Point(3, 3)
        TableLayoutPanelTopEx1.Name = "TableLayoutPanelTopEx1"
        TableLayoutPanelTopEx1.RowCount = 1
        TableLayoutPanelTopEx1.RowStyles.Add(New RowStyle(SizeType.Percent, 50.0F))
```
After any edit
```
        Me.TableLayoutPanelTopEx1.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle())
        Me.TableLayoutPanelTopEx1.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100.0!))
        Me.TableLayoutPanelTopEx1.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle())
        Me.TableLayoutPanelTopEx1.ColumnStyles.Add(New System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100.0!))
        Me.TableLayoutPanelTopEx1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.TableLayoutPanelTopEx1.LabelText = ""
        Me.TableLayoutPanelTopEx1.Location = New System.Drawing.Point(3, 3)
        Me.TableLayoutPanelTopEx1.Name = "TableLayoutPanelTopEx1"
        Me.TableLayoutPanelTopEx1.RowCount = 1
        Me.TableLayoutPanelTopEx1.RowStyles.Add(New System.Windows.Forms.RowStyle())
        Me.TableLayoutPanelTopEx1.RowStyles.Add(New System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50.0!))
```

### Steps to reproduce

Open Project, Open form1 change anything, Save and additional Row and Column Styles are added equal to the number of Rows and Columns. 

https://github.com/paul1956/WinFormsTableListViewIssue

### Diagnostics

```text
None
```

**Comment by MelonWang1** [comment]
We have the same design time bug as this issue: [4880](https://github.com/microsoft/winforms-designer/issues/4880).

**Comment by paul1956** [comment]
@MelonWang1  I can't see 4800 is that private?

**Comment by MelonWang1** [comment]
@paul1956 Yes, it's an internal ticket. If this issue has updated or resolved, will let you know.

**Comment by paul1956** [comment]
> We have the same design time bug as this issue: [4880](https://github.com/microsoft/winforms-designer/issues/4880).

Ping

**Comment by paul1956** [comment]
Ping @MelonWang1 

Will this ever be fixed?

**Comment by MelonWang1** [comment]
@paul1956 This issue will be fixed in the future but not sure when.

**Comment by merriemcgaw** [comment]
I'll close this issue, but note that the internal issue is still on the backlog.
