### ISSUE TITLE
 .NET 6 Winforms Cursors leak CPicture objects (User and GDI objects leak) due to ref count bug

### ISSUE THREAD

**Issue by TATKINSMSFT** [dotnet/winforms#8583]
### .NET version

.NET 6

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Works in .NET Core 3.1 (also works in .NET 7)

### Issue description

*****[Mainly for tracking]  Customer running into this has been unblocked by moving to .NET 7******

.NET 6 Windows Forms System.Windows.Forms.Cursor object creation leaks ole32!CPicture objects which leaks USER (Cursor) and GDI objects (Surf) due to a ref count bug.  If you do this long enough, you could experience an OutOfMemoryException (or other variation of exhausting resources) due to hitting the 10K per-process limit for GDI objects.  Example exceptions:

Exception object: 000001b919ae0340
Exception type:   System.OutOfMemoryException
Message:          Insufficient memory to continue the execution of the program.
InnerException:   <none>
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 8007000e

Exception object: 000001b919b68360
Exception type:   System.ArgumentException
Message:          Parameter is not valid.
InnerException:   <none>
StackTrace (generated):
<none>
StackTraceString: <none>
HResult: 80070057

The bug is in https://github.com/dotnet/winforms/blob/release/6.0/src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs#L56

There should be a Marshal.Release (externalComObject) after the QueryInterface (QI does an AddRef, unbalancing the ref count and leading to the leak without the Release call) call.

This bug doesn't occur in .NET Core 3.1 or .NET 7 (has a Marshal.Release call).

### Steps to reproduce

Create a new Windows Forms project targeting .NET 6
Add a Button to the newly created Form1 in the Designer
Add the following contrived code to Form1.cs

        private Cursor[] cur;
        private void button1_Click(object sender, EventArgs e)
        {                                       
                int i = 0;
                cur = new Cursor[3350];
                while (i < 3350)
                    {       
                        cur[i] = new Cursor("c:\\windows\\cursors\\aero_helpsel.cur");
                        cur[i].Dispose();
                        cur[i] = null;
                        i++;
                    }
                GC.Collect();
                GC.WaitForPendingFinalizers();         
        }

F5/Run the application
Click the button

Result:  A System.OutOfMemoryException will occur due to hitting the 10K per-process limit for GDI objects

Expected result:  No USER/GDI object leak or exception(s)

**Comment by Tanya-Solyanik** [comment]
The leak in itself does not meet the servicing bar because the customer can move to NET 7 to get rid of it. We will revisit this decision if we get more reports.
