### ISSUE TITLE
NotSupportedException when deserializing DBNull from RESX

### ISSUE THREAD

**Issue by TheLeftExit** [dotnet/winforms#8584]
### Description

Hello,

My name is Norton and I'm writing on behalf of the WinForms team at DevExpress.

We came across the following issue:
If [`DBNull.Value`](https://learn.microsoft.com/en-us/dotnet/api/system.dbnull.value) is assigned to a property of a component in the WinForms designer, it is stored in the RESX file associated with the form. If the same form is opened afterward, a [`SerializationException`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.serializationexception) is thrown on an attempt to call the [`ResourceManager.GetObject`](https://learn.microsoft.com/en-us/dotnet/api/system.resources.resourcemanager.getobject) method in the designer-generated code.

### Reproduction Steps

0. Install Visual Studio 2022 with the ".NET desktop development" workload.
1. Open Visual Studio 2022 and create a new project using the "Windows Forms App [C#]" template (further template configuration doesn't matter).
2. Once the project is created, close the designer tab without waiting for it to load.
3. Open **Form1.Designer.cs** and add `this.Tag = DBNull.Value;` at the end of the `InitializeComponent` method.
4. Open the form designer by double-clicking **Form1.cs** in the Solution Explorer.
5. Resize the form, save the file and close the tab.
*This forces the form designer to regenerate **Form1.Designer.cs**, store `DBValue.Null` in `Form1.resx` and generate a call to the `ResourceManager.GetObject` method for that value.*
6. Run the project.

I attached a project created using these steps - it is sufficient to simply run it.
[T1143850c.zip](https://github.com/dotnet/runtime/files/10556207/T1143850c.zip)

*These steps do not represent a realistic use case where this issue occurs, but the fastest way to reproduce it. A realistic use case would involve creating a custom control with a custom property initialized with `DBNull.Value`. If necessary, I can add steps and a project for this use case.*

### Expected behavior

The application launches without any exceptions and an empty form is displayed.

### Actual behavior

An exception is thrown.

```
Exception thrown: 'System.NotSupportedException' in System.Private.CoreLib.dll
Only one DBNull instance may exist, and calls to DBNull deserialization methods are not allowed.
```

### Regression?

This issue does not occur in .NET Framework.

### Known Workarounds

We are not aware of workarounds that do not sacrifice usability (such as disabling serialization of the property completely with [`DesignerSerializationVisibilityAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.designerserializationvisibilityattribute)).

### Other information

We are not certain whether the issue lies in the way the WinForms designer or .NET SDK serializes the value, or the way the standard .NET serialization API serializes/deserializes it, but we consider the latter more likely, based on our findings. If this happens to be an issue with a different product, please let me know.

It's also possible that this use case is not supported in general, although we have several reasons to believe why this is not the case:
 - The same use case works as expected in .NET Framework applications (i.e. this behavior is a regression).
 - With this limitation, it isn't possible to define a serializable component property whose default value is `DBNull.Value`, which we consider a valid use case.
 - The `DBNull` type is still marked with [`SerializableAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.serializableattribute), and it's stated in https://github.com/dotnet/runtime/issues/23253 that support for its serialization was explicitly added.

**Comment by Tanya-Solyanik** [comment]
@ericstj - I did not know it was possible to transfer issues across the orgs, so I copied it manually - https://github.com/microsoft/winforms-designer/issues/4915

**Comment by ericstj** [comment]
I think it's still valuable to keep this one since dotnet/winforms is a public repo.  I don't think the original issue filer has access to https://github.com/microsoft/winforms-designer/issues/4915.

**Comment by TheLeftExit** [comment]
@ericstj I do, so that shouldn't be a problem (aside from other considerations).
