### ISSUE TITLE
ToolStrip/MenuStrip/StatusStrip with TabStop=true arrow keys navigation goes in the wrong direction

### ISSUE THREAD

**Issue by v-elnovikova** [dotnet/winforms#8587]
### .NET version

7.0.2

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET 6.0 - No
.NET 5.0 - Yes
.NET Core 3.1 - Yes

Most likely, it's a regression after PR #5924

### Issue description

When navigating through ToolStrip via keyboard arrow keys, Left key switches focus to the right item, not to the left one as expected. 

https://user-images.githubusercontent.com/113603457/217529055-8cac1aec-8786-4197-955d-c4a5a1007b59.mp4

Notice that when the **Left key** is pressed, the focus goes **right**.

MenuStrip and StatusStrip have the same problem.
The issue is reproducing only controls with **TabStop** set to **true**.

### Steps to reproduce

Sample app:  [SampleApp.zip](https://github.com/dotnet/winforms/files/10685452/SampleApp.zip)

Build and run app. 
Initially focus is on ToolStrip first item. 
Press Right arrow key several times. Notice that focus switches to the right.
Press Left key. Focus switches to the right again.

**Comment by Philip-Wang01** [comment]
Verified this on .NET 8.0 Preview 2.0 TP build: 8.0.100-preview.2.23151.8, issue was fixed that the Left key works well now. Test result is same as above screenshot.
