### ISSUE TITLE
Menu item without sub menu leaking focus on arrow keys

### ISSUE THREAD

**Issue by v-elnovikova** [dotnet/winforms#8591]
### .NET version

7.0.2

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

When menu item without sub menu has focus, and a user presses Up or Down arrow keys, focus switches to form controls.

https://user-images.githubusercontent.com/113603457/217561753-d8336f66-818d-4a50-b8a4-5d37fa05e9cd.mp4

Screen reader announces exiting menu mode and switching to form buttons. But when Enter key is pressed, menu item is clicked, not the focused button.

Expected behavior: Up and Down keys do nothing on empty menu items, since there is no drop-down sub menu to open.

### Steps to reproduce

Sample app: [SampleApp.zip](https://github.com/dotnet/winforms/files/10686647/SampleApp.zip)

Build and run app.
Using Alt and Left/Right keys move focus to *Empty item*. 
Press Up or Down key.
Notice that focus moves to buttons on the form.

**Comment by Ashley-Li** [comment]
Verified this on .NET latest build: 8.0.100-preview.2.23116.17, issue was fixed, when empty menu item is focused, Down/Up keys does nothing, menu is still focused.
![8591_issue_retest](https://user-images.githubusercontent.com/56664234/219538211-d313cd25-05e1-4316-bd8d-bd4f5d81ad14.gif)

**Comment by Olina-Zhang** [comment]
Verified this on .NET 8.0 Preview 2.0 TP build: 8.0.100-preview.2.23151.8, issue was fixed with the same above testing results.
