### ISSUE TITLE
DataGridView styles designer bugs

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#8593]
### Environment

All

### .NET version

All

### Did this work in a previous version of Visual Studio and/or previous .NET release?

No

### Issue description

Referenceses:
https://developercommunity.visualstudio.com/t/WinForms-DataGridView-styles-designer/1143911
https://github.com/microsoft/winforms-designer/issues/2225

For now DataGridView styles in designer can be split to 3 groups by designer behavior:
![pic1](https://user-images.githubusercontent.com/62929087/89873781-8a2a9500-dbed-11ea-8bb5-0ee5afdaeff6.png)

### Group 1.
Work absolutely correct, but not displaying default values (because they are absent).

### Groups 2 and 3.
Have common bugs / incorrect behavior. When you change any parameter in this styles - the designer will wright to *.Designer.cs this parameter new value + ALL other parameters with default values.
![gif1](https://user-images.githubusercontent.com/62929087/89873800-8f87df80-dbed-11ea-8c23-ad0a368a8960.gif)

This can lead to confusing errors. For example this will break system font scaling because of explicitly font set. Also when you open this styles settings it’s impossible to determinate what are default values and what you have changed (if any):
![pic2](https://user-images.githubusercontent.com/62929087/89873786-8d258580-dbed-11ea-93de-281dacbd37e1.png) 

### Group 2.
Didn't not remove all it's code from *.Designer.cs when all changes are removed in designer.

### Group 3.
You can’t delete default values from *.Designer.cs - **this completely break system font scaling**.
![gif2](https://user-images.githubusercontent.com/62929087/89873803-91ea3980-dbed-11ea-89c6-e64998ec155e.gif) 
**And if you delete def. values manually, they will be bring back after any designer manipulation.**

------------------------------------------------

Ideal solution will be that Groups 2 and 3 behave identical and:

- Place in *.Designer.cs only those values, that you have changed and NO default values.
- Display default values in styles with not bold text, like in every other place.

This will solve all problems above.

**Comment by dkazennov** [comment]
This issue is put on hold until there will be decisions on #8474 and #8518 (the new task #8599 to define a pattern for default values).

**Comment by Tanya-Solyanik** [comment]
Since this scenario had not been working in the In Proc designer, it does not meet the current bug bar.
