### ISSUE TITLE
❓ Survey: Repo contribution experience 2023

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#8605]
Last year we surveyed you the members of the community in this repo to learn how we were doing as maintainers.

It's time to repeat the same survey. Whether you've been involved for years or you're relatively new please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:

Survey link: https://www.surveymonkey.com/r/8KTX9VT?Source=RepoLink

**Comment by RussKie** [comment]
Is this part correct `?Source=RepoLink`?

**Comment by kirsan31** [comment]
How long this survey will be open?

**Comment by dreddy-work** [comment]
> How long this survey will be open?

until 3/3. 3 weeks.

**Comment by JulieLeeMSFT** [comment]
The response rate has decreased now, so we are closing the survey early now. 

> How long this survey will be open?
