### ISSUE TITLE
[suggestion] move Dispose(bool disposing) from Form1.Designer.cs to Form1.cs

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#8614]
### Issue description

What do you think about moving this method for newly created form? This will save a few seconds of time for each form :)
But most importantly It's location raises many questions for beginners (ppl afraid to modify anything in `*.Designer.cs`):
https://stackoverflow.com/questions/1052147/how-do-i-extend-a-winforms-dispose-method
https://stackoverflow.com/questions/672980/dispose-on-user-controls-really-meant-to-edit-the-designer-cs-file
https://stackoverflow.com/questions/4382693/when-modifying-disposebool-in-a-winforms-generated-designer-cs-file-is-it-nec
and so on...

Also it can be modernize a bit.
```cs
protected override void Dispose(bool disposing)
{
    if (disposing && (components != null))
    {
        components.Dispose();
    }
    base.Dispose(disposing);
}
```
To
```cs
protected override void Dispose(bool disposing)
{
    if (disposing)
    {
        components?.Dispose();
    }

    base.Dispose(disposing);
}
```

Or are we afraid that this method will simply be deleted, or corrupted by the user?

**Comment by elachlan** [comment]
I think this would be more correct than what we have now for the new form template. Its not "generated" code and isn't updated as far as I know. It would allow easier visibility on what is happening. The `*designer.cs` hides implementation from users to a degree and this makes it harder to learn the lifecycle.

**Comment by merriemcgaw** [comment]
We'll take this up internally, and explore whether or not this is the right way to ensure that our components are disposed. In general, we like this idea and just want to think about it 😄

**Comment by KlausLoeffelmann** [comment]
We should not treat Visual Basic and C# differently, and I don't like the VB main class file to be unnecessarily cluttered. So...what do you think of this approach:

```VB
    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing Then
                Dispose()
                If components IsNot Nothing Then
                    components.Dispose()
                End If
            End If

        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    Partial Private Overloads Sub Dispose()
    End Sub
```

Then, a VB (and C#) Form could still look the same, but if someone needs it, you'd just do this:

```VB
Public Class Form1

    Private Overloads Sub Dispose()
        ' Your code here.
    End Sub

End Class
```

@JeremyKuhne, @merriemcgaw.

**Comment by kirsan31** [comment]
> We should not treat Visual Basic and C# differently, and I don't like the VB main class file to be unnecessarily cluttered. 

I am sorry I don't know anything about VB, so can only say about c#.
The main goal of my proposal was to not confuse ppl and save some seconds on refactoring. 

>So...what do you think of this approach:
> 
> ```vbnet
>     'Form overrides dispose to clean up the component list.
>     <System.Diagnostics.DebuggerNonUserCode()>
>     Protected Overrides Sub Dispose(ByVal disposing As Boolean)
>         Try
>             If disposing Then
>                 Dispose()
>                 If components IsNot Nothing Then
>                     components.Dispose()
>                 End If
>             End If
> 
>         Finally
>             MyBase.Dispose(disposing)
>         End Try
>     End Sub
> 
>     Partial Private Overloads Sub Dispose()
>     End Sub
> ```
> 
> Then, a VB (and C#) Form could still look the same, but if someone needs it, you'd just do this:
> 
> ```vbnet
> Public Class Form1
> 
>     Private Overloads Sub Dispose()
>         ' Your code here.
>     End Sub
> 
> End Class
> ```


But this proposal will do opposite thigs - this approach will confuse ppl much stronger  - we not solve original problem but introduce some more 🤷‍♂️
If I have to choose between the current decision and this one, I definitely want to leave everything as it is 🙄

**Comment by elachlan** [comment]
I like Klaus's design here for VB.NET. It makes it easier for a new user to add in needed disposal code.

**Comment by KlausLoeffelmann** [comment]
Yeah, but we should it do consistently, so, also for C#. Discoverability is a bit of a problem here. But docs and a small blog post would definitely help.

**Comment by KlausLoeffelmann** [comment]
We _could_ have an analyzer on the Form's class definition, which then exposes the partial Dispose method to the actual Form class. That would help with discoverability.

In that context: WinForms domain specific Analyzers is something we should think about and utilize more in general. They are a GREAT benefit for our developer-customers! (A bit of a OT-comment, but worth mentioning in the context, I think 😸 ).

**Comment by paul1956** [comment]
I have the outline/prototype of a simple Analyzer the detects missing (deleted) Handles Clauses (in VB for VB) that I would be happy to contribute. Editing Forms frequently deletes the handles clause if for any reason a control is removed and added back, or the Designer file has major changes. Prototype is not perfect but covers the vast majority of cases and provides a CodeFix to restore them. It also renames Handler Subs that were not renamed when control name changes thought this is something the designer/Visual Studio should handle.

**Comment by elachlan** [comment]
@paul1956 put in a PR and lets see if we can get that merged!

**Comment by KlausLoeffelmann** [comment]
> the detects missing (deleted) Handles Clauses (in VB for VB) that I would be happy to contribute

Sounds tempting...but! 😄 

Help me understand the scenario(s), because we recently completely rewrote how VB handles `Handles` (ha!). Are those issues still there? What are the scenarios where a handles clause is deleted? Or what are the exact scenarios where a change would qualify as a 'major change' according to your definition?

Do we have an issue which describes those Handles-get-lost scenarios with reliable repros?

**Comment by kirsan31** [comment]
> Yeah, but we should it do consistently, so, also for C#. Discoverability is a bit of a problem here. But docs and a small blog post would definitely help.

@KlausLoeffelmann suggestion for C#.

**pros** 
- Nothing here sorry.

**cons**
- We are not solving any of the problems I described, on the contrary, we are exacerbating them by adding a new entity to the known dispose pattern. Furthermore, this entity also hide the original `Dispose` method. All of this will lead to even greater confusion. And yes, as you correctly noted, it will be necessary to train people one way or another. But for what???? 
- We are restrict ppl from using original (right one) dispose pattern. **That will lead to errors and memory leaks** in case some one add unmanaged resources to the form and then forget to call `Dispose()` (after `ShowDialog` or  exception before form became visible).  Because our new `Dispose()` method is under `if (disposing)` condition.
- After creating new form I will need to do a bit more work to transfer `Dispose(bool disposing)` from `Form1.Designer.cs` to `Form1.cs`.
- Suggested code will not compile in c#  🤷‍♂️ You can't declare `partial` method with access modifier or `new` keyword. So we can do only `partial void Dispose();` and this will generate `CS0108` warning...

Сan I delete this issue and we forget about it like a bad dream? 😁😁😁

**Comment by RussKie** [comment]
> We should not treat Visual Basic and C# differently, and I don't like the VB main class file to be unnecessarily cluttered. So...what do you think of this approach:
> 

Why would we make VB folks do more work? 
I remember one guy saying something like this:
![image](https://user-images.githubusercontent.com/4403806/219330111-bd2e96cd-86b2-40f0-ab01-f3a28fc456a7.png)

**Comment by KlausLoeffelmann** [comment]
Not really sure what that has to do with this. (Apart from that, I set that in quotes, because that was exactly what I was doing: quoting the conclusion of an internal meeting at the time.)

Closing this then.

**Comment by RussKie** [comment]
My point is - we don't have to align C# and VB templates because the way C# and VB developers work isn't the same.
