### ISSUE TITLE
[dotnet-sdk-8.0.100-preview.1.23107.4] Build with warnings after retargeting to .NET 8.0 for paint.net app

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/winforms#8638]
**Application Name**: paint.net
**OS**: Windows10 21h2
**CPU**: x64
**App Source checking at:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1745300

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.1.23107.4 + app (default 7.0): Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.1.23107.4 + app (retarget 8.0): Fail
3). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.1.23108.10-win-x64 + app (retarget 8.0): Fail

**Repro steps:**
**The machine has Visual Studio 2022 Preview installed because this app needs to build with Visual Studio and need to retarget .NET 8.0.**
1.Copy app source paint.net to local machine.
2. Follow the steps in paintnet_Readme.txt file to configure the build environment. (File attached https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1745300)
3. Build the solution in Visual Studio
**Expected Result:**
Build successful.
**Actual Result**:
Build with following warnings (There are some other errors related to arm64 projects and build platform 143, please ignore them):

![image](https://user-images.githubusercontent.com/83067197/218431062-8660f0c2-138f-446b-8e0b-3649d50de3fe.png)

**Minimal Repro sample:**
Minimal repro sample attached.
[paint.net demo.zip](https://github.com/dotnet/sdk/files/10721220/paint.net.demo.zip)

**Repro steps:**
1. Create a default .net 7.0 WinForm app.
2. Add a new Class1.cs.
3. Add following code in Class1.cs
```
internal class Class1: Class2
    {
        private void Method1(object? sender, EventArgs e)
        {
            Class2 c2 = (Class2)sender!;
            Class3 c3 = (Class3)c2!.Tag;
            Method2(c3);
        }

        public void Method2(Class3 c3)
        {    }
    }

    internal class Class2: ToolStripMenuItem
    { 
        protected override void OnParentChanged(ToolStrip oldParent, ToolStrip newParent)
        {
            base.OnParentChanged(oldParent, newParent);
        }
    }

    internal class Class3
    {   }
```
5. Build the project, there is no warning in Error List windows of Visual Studio.
6. Retarget the project to .net8.0-windows.
7. Rebuild the project.

**Expected Result**:
Build successful.

**Actual Result:**

Build with warning:
```
Warning CS8604 Possible null reference argument for parameter 'c3' in 'void Class1.Method2(Class3 c3)'.
Warning CS8765 Nullability of type of parameter 'oldParent' doesn't match overridden member (possibly because of nullability attributes).
Warning CS8765 Nullability of type of parameter 'newParent' doesn't match overridden member (possibly because of nullability attributes).
Warning CS8600 Converting null literal or possible null value to non-nullable type.
```
**Findings**:

1. When the custom class inherit from ToolStripMenuItem (come from System.Windows.Forms.dll), these warnings will appear in .NET 8.0, but not in .NET 7.0. The behavior changed in .NET 8.0.

2. According to the document: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings There are some ways recommended to resolve these warnings in document. We can add ? or ! to let the warnings disappear.
```
 internal class Class1 : Class2
    {
        private void Method1(object? sender, EventArgs e)
        {
            Class2 c2 = (Class2)sender!;
            Class3 c3 = (Class3)c2!.Tag!;
            Method2(c3);
        }

        public void Method2(Class3? c3)
        { }
    }

    internal class Class2 : ToolStripMenuItem
    {
        protected override void OnParentChanged(ToolStrip? oldParent, ToolStrip? newParent)
        {
            base.OnParentChanged(oldParent, newParent);
        }
    }
```
@dotnet-actwx-bot @dotnet/compat

**Comment by marcpopMSFT** [comment]
Not sure whether to transfer to Winforms or Roslyn for the doc updates and template changes.

**Comment by elachlan** [comment]
Winforms is currently going through a community initiative to null annotate the code base see: #1107 and #8342

**Comment by merriemcgaw** [comment]
This is currently by-design. There is no action item on WinForms at this point, the application has some work it could do while we're going through the community led effort. (Thanks @elachlan!!)
@rickbrew, wanted to get this on your radar early in .NET 8.

**Comment by elachlan** [comment]
Its mostly been @gpetrou. They have done the lions share and deserve some pretty big praise.

**Comment by rickbrew** [comment]
> This is currently by-design. There is no action item on WinForms at this point, the application has some work it could do while we're going through the community led effort. (Thanks @elachlan!!) @rickbrew, wanted to get this on your radar early in .NET 8.

Saw this in .NET 7, glad to see more coming in .NET 8 :)

`BinaryFormatter` will be my biggest blocker moving forward, that's a lot of work to migrate away from. Nullability annotations are no sweat.

**Comment by Junjun-zhao** [comment]
@merriemcgaw Thank you for your quickly update.  Will we be going to create a breaking change issue for this nullability annotation change or list of these changes in .NET 8 like the similar list in .NET 6?

**Comment by elachlan** [comment]
@Junjun-zhao can you link the .NET6 breaking change?

**Comment by gpetrou** [comment]
As far as I remember, API changes are in https://github.com/dotnet/core/tree/main/release-notes.
For example, https://github.com/dotnet/core/tree/main/release-notes/7.0/preview/api-diff and more specifically https://github.com/dotnet/core/blob/main/release-notes/7.0/preview/api-diff/rc1/Microsoft.WindowsDesktop.App/7.0-rc1_System.Windows.Forms.md
I guess at some point we will see version 8 there as well.

**Comment by Junjun-zhao** [comment]
> @Junjun-zhao can you link the .NET6 breaking change?



> 
 Do you mean share the breaking change link for .NET 6? Here is the one that @KalleOlaviNiemitalo shared [a list of breaking changes in nullability annotations in .NET 6](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/nullable-ref-type-annotation-changes) and also there is one [breaking change for a single API change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/nullable-ref-type-annotations-added)

**Comment by merriemcgaw** [comment]
@rickbrew let's work closely together so we know what scenarios are the ones that will break you the most to see what (if anything) we can do on our side to help you and other customers. We'll also be working on guidance in the coming months which we will make sure you get.

**Comment by Junjun-zhao** [comment]
**[Update API changes are in .NET 8**] (https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.1/api-diff/Microsoft.WindowsDesktop.App/8.0.1_System.Windows.Forms.md)

**[system.windows.forms.toolstripitem.onparentchanged Windowsdesktop-8.0**] (https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.toolstripitem.onparentchanged?view=windowsdesktop-8.0#system-windows-forms-toolstripitem-onparentchanged(system-windows-forms-toolstrip-system-windows-forms-toolstrip)

**Comment by elachlan** [comment]
Closing this as there isn't anything actionable here.
