### ISSUE TITLE
Binding.ReadValue without a control throws NRE should be a nop

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#864]

**Comment by merriemcgaw** [comment]
This seems like a reasonable result. If we change this it will make porting of existing applications which have the issue have to change how they're responding to the scenario.

**Comment by weltkante** [comment]
@merriemcgaw is that even a reasonable scenario to expect to happen in existing applications? I mean a WinForms Binding connects a control property to some binding source property, right? So if the control is null it's disconnected, and why would you try to refresh a disconnected binding? Unless I'm understanding something wrong this is more of an edge case I think.
