### ISSUE TITLE
[.Net Core]The ElementHost icon still shows the gear icon

### ISSUE THREAD

**Issue by Judy-Gao** [dotnet/winforms#865]
**OS**: RS4 X64
**VS**: Dev16 16.1 d16.1 branch 28823.117 build
**.NET Core**: 3.0.100-preview5-11552 from Release branch

**More Info:**
1. This issue also reproduce .NET Framework project.
2. Affect control and it's dependence dll.

Controls | DLL | Repositories
-- | -- | --
ElementHost | WindowsFormsIntegration.dll | dotnet/wpf

**Steps to reproduce:**
 1. Install the .NET Core 3.0 SDK from https://github.com/dotnet/core-sdk for Release branch.
 2. Open the .NET Core app from \\\mlangfs1\public\Winforms\CoreTest\IconChange\4.22\Elemenhost1.zip  in VS.
 3. Run it and observe the control icon such as ElementHost

**Actual:**  ElementHost icon shows gear
![FileSystemWatcher](https://user-images.githubusercontent.com/49627041/56650382-7df98c00-66b9-11e9-8233-d206e640cd4d.PNG)

**Expected:** ElementHost can show it's own icon.

**Comment by merriemcgaw** [comment]
This is how it is in the Framework. This is not a priority to address any time soon.
