### ISSUE TITLE
Renaming/editing a VB Control using Designer breaks Handlers Clauses

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#8658]
### Environment

Preview 6

### .NET version

N/A

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes under FrameWork

### Issue description

When editing/renaming controls on a form ( Form1 for example) in OOP designer, handler clauses in Form1 are deleted or duplicated.

### Steps to reproduce

Create a VB WinForms Project, add several controls (labels, TextBox...) using Designer, add handlers to the controls in Form1 from DropDown List in Visual Studio. Handlers should be for Form1 AND the controls on Form1.

Now rename a control and all the handler subs associated with that control with have 2 handlers the original and a renamed one and the With Events declarations for old and new name will still be there.

It is possible that all handlers' clauses for the entire Form1 and all controls will be removed. I don't know why sometimes handlers are duplicated and sometimes all are removed but both are extremely aggravating.

### Diagnostics

```text
None, app silently stops working because Handler clauses are missing.
```

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang - could you please create a copy of this issue in the designer repo. We'll keep this one for tracking purposes.

**Comment by KlausLoeffelmann** [comment]
Hey Paul,

thanks for reporting this. I am on it!

Appreciate your repeated help here a lot!

**Comment by paul1956** [comment]
@KlausLoeffelmann: Related what is the expected behavior if I select a control on a container control, cut it and then paste it somewhere else on the same container or on another container. I believe in both cases the Handler Clauses are deleted BEFORE I save the designer. I would prefer an error on the handler clauses if I actually intended to delete the control. Also, if Designer gets an error (Object is Null?) while saving Form.Designer all handler clauses are deleted on the associated form.

**Comment by Olina-Zhang** [comment]
The fixing of this issue now is in public release: Visual Studio 17.5.3.
