### ISSUE TITLE
[.Net Core]The icons still show the gear icon

### ISSUE THREAD

**Issue by Judy-Gao** [dotnet/winforms#866]
**OS**: RS4 X64
**VS**: Dev16 16.1 d16.1 branch 28823.117 build
**.NET Core**: 3.0.100-preview5-11552 from Release branch

**More Info:**
1. This issue not reproduce .NET Framework project.
2. Affect controls and these's dependence dll.

Controls | DLL | Repositories
-- | -- | --
FileSystemWatcher | System.IO.FileSystem.Watcher.dll | dotnet/Corefx
PerformanceCounter | System.Diagnostics.PerformanceCounter.dll | dotnet/Corefx
Process | System.Diagnostics.Process.dll | dotnet/Corefx
SerialPort | System.IO.Ports.dll | dotnet/Corefx
ServiceController | System.ServiceProcess.ServiceController.dll | dotnet/Corefx
PrintDocument | System.Drawing.Common.dll | dotnet/Corefx
DataSet | System.Data.Common.dll | dotnet/Corefx
BackgroundWorker | System.ComponentModel.EventBasedAsync.dll | dotnet/Corefx
DirectoryEntry | System.DirectoryServices.dll | dotnet/Corefx
DirectorySearcher | System.DirectoryServices.dll | dotnet/Corefx
EventLog | System.Diagnostics.EventLog.dll | dotnet/Corefx

**Steps to reproduce:**
 1. Install the .NET Core 3.0 SDK from https://github.com/dotnet/core-sdk for Release branch.
 2. Open the .NET Core app from \\\mlangfs1\public\Winforms\CoreTest\IconChange\4.22\Issue1.zip  in VS.
 3. Run it and observe the control icon such as FileSystemWatcher

**Actual:**  FileSystemWatcher icon show gear
![FileSystemWatcher](https://user-images.githubusercontent.com/49627041/56650382-7df98c00-66b9-11e9-8233-d206e640cd4d.PNG)

**Expected:** FileSystemWatcher can show it's own icon.

**Comment by merriemcgaw** [comment]
@dreddy-work can you take a look and determine why this is happening or where we need to make adjustments so it can work properly?

**Comment by merriemcgaw** [comment]
Issue moved to [dotnet/corefx #37305](https://github.com/dotnet/corefx/issues/37305) via [**ZenHub**](https://www.zenhub.com/)
