### ISSUE TITLE
If you switch from light mode to dark mode, the font of the label will be blurred

### ISSUE THREAD

**Issue by Simple-2021** [dotnet/winforms#8680]
### .NET version

.NET SDK:
 Version:   7.0.200
 Commit:    534117727b

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.25300
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.200\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  7.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Unknown

### Issue description

I applied the 'Mica Material' for Winform, but if you switch from 'light mode' to 'dark mode', the label, checkbox, radiobutton are blurred.
> Image

![image](https://user-images.githubusercontent.com/78424351/220970585-ee08f9ef-e587-406d-a4fe-71554104a6dd.png)

### Steps to reproduce

[demo](https://github.com/Simple-2021/LibMaterial)

**Comment by elachlan** [comment]
@Olina-Zhang could your team please test this?

**Comment by elachlan** [comment]
@MelonWang1 thank you!

@Simple-2021 Are you able to use a different font for now?

**Comment by elachlan** [comment]
@merriemcgaw Could the team please assess this? Does the QA team need to do an MFC app to see if its isolated to winforms?

**Comment by Simple-2021** [comment]
@MelonWang1 Thanks for the test, I'm testing, it seems to be a matter of ForeColor vs. BackColor

**Comment by Simple-2021** [comment]
@elachlan Thanks for testing, I'm testing, it seems that Winform has adopted an issue with font shadows adapting to background colors

**Comment by Simple-2021** [comment]
@elachlan @MelonWang1 I switched ForeColor and BacKColor appropriately for 'Light Mode' and 'Dark Mode' and reapplied Transparency.
This allows the font to display correctly in general.
However, if you choose the semi-transparent style, fonts suspended over dark areas in Light mode are still blurred, and fonts suspended over light areas in Dark mode are blurred.
I have updated the code of the [demo](https://github.com/Simple-2021/LibMaterial)

**Comment by Simple-2021** [comment]
![image](https://user-images.githubusercontent.com/78424351/221997103-7a8f95bc-256f-4b66-bd26-9986f699c9e7.png)
![image](https://user-images.githubusercontent.com/78424351/221997176-c7706922-5975-4c7e-a07f-b1e3c5334359.png)
![image](https://user-images.githubusercontent.com/78424351/221997229-3de0db72-26d2-451b-913f-a380676b6d46.png)

**Comment by Simple-2021** [comment]
![image](https://user-images.githubusercontent.com/78424351/221998070-d93d1fbd-5380-4138-b669-d1e618de1c2e.png)

**Comment by MelonWang1** [comment]
@merriemcgaw The .NET Core 3.1 also have same behavior. 
@Simple-2021  Where choose the semi-transparent style? I use your demo, In Light Mode, the font has a white border around it. Fonts blurred in dark areas.
![light](https://user-images.githubusercontent.com/94418985/222318134-7d2260e2-b402-44ee-9421-c1850df461da.png)
![Screenshot 2023-03-01 183819](https://user-images.githubusercontent.com/94418985/222318161-28288d5f-c3df-456d-997c-86fa40be4809.png)

In Dark Mode, the font color is black. Looks like different with your result, your font color is white. Font not blurred in light areas, but in dark areas can't see words.
![dack](https://user-images.githubusercontent.com/94418985/222318186-454f842e-1d28-4d59-a3e2-92ce87000c82.png)
![Screenshot 2023-03-01 183900](https://user-images.githubusercontent.com/94418985/222318200-b9c9396c-36f0-4925-978e-11e5f24fa0e2.png)

**Comment by Simple-2021** [comment]
@MelonWang1  Making Form's BackColor equal to Transparency creates a transparent style.
But at this point, the mouse click will pass through the Form.
To make the Form transparent and clickable, you need to make BackColor.R not equal to BackColor.B, at which point the Form is transparent and the mouse can click.
In this mode, Apply_Backdrop_Effect (Hwnd: YouFormHandle, BackdropFlag: YouBackdropFlg) can take effect.
The type of BackdropFlag is [DWM_SYSTEMBACKDROP_TYPE](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_systembackdrop_type) enumeration.
Flags for specifying the system-drawn backdrop material of a window, including behind the non-client area.

**Comment by MelonWang1** [comment]
I 'm sorry, this issue may need to be looked at by our development team.  @merriemcgaw

**Comment by Simple-2021** [comment]
@elachlan Thanks for the tip, it's really the font reason.
@merriemcgaw  @MelonWang1 Sorry, this is the reason for the form font, when the font is "宋体" or "新宋体", the font does not blur on a background similar to 'ForeColor'. At the same time, the new problem seems to be that only "宋体" and "新宋体" are not vague, which also exists in the 4.7.1 and 4.8 versions of the NET Framework. Sorry very much.

![屏幕截图 2023-03-04 045849](https://user-images.githubusercontent.com/78424351/222829130-22db6004-ae57-4da1-af0b-880f108ff804.png)

**Comment by merriemcgaw** [comment]
Not a problem at all @Simple-2021 I'm so glad you were able to find a solution! Since you've resolved your problem I'm going to close this issue, but don't hesitate to open new ones as you run into issues. And I might play with your library - it looks pretty cool!
