### ISSUE TITLE
Incorrect designer generation for VB when last property of a component is of string type

### ISSUE THREAD

**Issue by ehasis** [dotnet/winforms#8684]
### Environment

Visual Studio 2022 version 17.5.0

### .NET version

6.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Visual Studio 2022 version 17.4.5

### Issue description

When last property of a component is of a String type, then it not insert new line character and the comment of next section get on the same line, for example, look the single quote of Form1 comment right after "Label1":

```vb
Private Sub InitializeComponent()
    Label1 = New Label()
    SuspendLayout()
    ' 
    ' Label1
    ' 
    Label1.AutoSize = True
    Label1.Location = New Point(413, 91)
    Label1.Name = "Label1"
    Label1.Size = New Size(41, 15)
    Label1.TabIndex = 0
    Label1.Text = "Label1"' 
    ' Form1
    ' 
    AutoScaleDimensions = New SizeF(7F, 15F)
    AutoScaleMode = AutoScaleMode.Font
    ClientSize = New Size(800, 450)
    Controls.Add(Label1)
    Name = "Form1"
    Text = "Form1"
    ResumeLayout(False)
    PerformLayout()
End Sub
```

### Steps to reproduce

- Create new Windows Forms application with Visual Basic
- Place a Label componente on the Form
- Save

**Comment by KlausLoeffelmann** [comment]
We have fixed this already in a later version of VS.
We're currently thinking about servicing a couple of issues around VB, including this one, to 17.5.

Leaving this open for visibility, until we finally decide. 
@merriemcgaw FYI.

**Comment by paul1956** [comment]
@KlausLoeffelmann  On Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.6.0 Preview 1.0

```
        ' 
        ' Ok_Button
        ' 
        Me.Ok_Button.Anchor = AnchorStyles.Bottom Or AnchorStyles.Right
        Me.Ok_Button.DialogResult = DialogResult.OK
        Me.Ok_Button.Location = New Point(235, 277)
        Me.Ok_Button.Name = "Ok_Button"
        Me.Ok_Button.Size = New Size(94, 23)
        Me.Ok_Button.TabIndex = 0
        Me.Ok_Button.Text = "&OK"' 
        ' Cancel_Button
        ' 
```

**Comment by KlausLoeffelmann** [comment]
It's fixed in Preview 2. It's not public, yet.

**Comment by paul1956** [comment]
Does it fix all the forms in the project, or do I need to open each and save or edit save and restore?

**Comment by KlausLoeffelmann** [comment]
You will need to save those affected again, yes.

**Comment by paul1956** [comment]
So just saving without changing will work?

**Comment by KlausLoeffelmann** [comment]
No. You would need to trigger the serialization.

**Comment by ehasis** [comment]
Tested with 17.5.3 and now is working as expected. Thanks!

**Comment by merriemcgaw** [comment]
Glad to hear it @ehasis! I'm going to go ahead and close this issue. Please feel free to reopen this issue if we need to.
