### ISSUE TITLE
Serialization causes DataGridViewColumns to be defined after they are added to DataGridView

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#8697]
### Environment

Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.6.0 Preview 1.0

### .NET version

N/A

### Did this work in a previous version of Visual Studio and/or previous .NET release?

the same bug is present in VS2019

### Issue description

```VB
        ' DgvCareLinkUsers
        ' 
       ' Stuff removed
        Me.DgvCareLinkUsers.Columns.AddRange(New DataGridViewColumn() {Me.DgvCareLinkUsersUserID, Me.DgvCareLinkUsersDeleteRow, Me.DgvCareLinkUsersCareLinkUserName, Me.DgvCareLinkUsersCareLinkPassword, Me.DgvCareLinkUsersCountryCode, Me.DgvCareLinkUsersUseLocalTimeZone, Me.DgvCareLinkUsersAutoLogin})
        Me.DgvCareLinkUsers.DataSource = Me.CareLinkUserDataRecordBindingSource
        ' Stuff Removed
        ' 
        ' DgvCareLinkUsersUserID
        ' 
        Me.DgvCareLinkUsersUserID.DataPropertyName = "ID"
        Me.DgvCareLinkUsersUserID.HeaderText = "ID"
        Me.DgvCareLinkUsersUserID.Name = "DgvCareLinkUsersUserID"
        Me.DgvCareLinkUsersUserID.ReadOnly = True
        Me.DgvCareLinkUsersUserID.Width = 43

```
If DgvCareLinkUsers has a Handler on ColumnAdded can't use DataPropertyName  or Name because they are initialized AFTER the column is added. Those values are blank at the time of the add.

### Steps to reproduce

Add DataGridView and then some columns with DataPropertyName  and Name set

The AddRange statement happens BEFORE the values of the columsn are filled in

### Diagnostics

```text
N/A
```

**Comment by paul1956** [comment]
This is a bigger issue for Visual Basic because it allows Event Handlers to be setup BEFORE Form is initialized so the order of initialization matters.

**Comment by elachlan** [comment]
@Olina-Zhang could your team please confirm this bug and create an issue in the designer repo?

**Comment by Olina-Zhang** [comment]
@paul1956 We tested your mentioned scenarios as we designed, .Net framework designer and previous OOP designer have same behavior, could you please look at following to see if it is consitent with yours? If so, @elachlan I am not sure if it is a real issue.

**Steps**:
1. Create a Winforms VB .Net Core application with DataGridView added
2. Bind a DataSource to DataGridView and bind a Table with columns, in here we can see Columns with DataPropertyName or Name set
3. Generate DataGridView's ColumnAdded event, and add some code with breakpoint
4. Build and F5 app

**Result:** Form is not displayed and hitting that breakpoint in DataGridView's ColumnAdded event
**Record:**
![123 gif](https://user-images.githubusercontent.com/26474449/221472294-026782fe-703d-46e3-b9d1-ad4ce3a09248.gif)

**Comment by paul1956** [comment]
When you hit breakpoint I can't tell if any column properties are set. I don't know how to stop video. Is you test app on GitHub?

I can repo this every time if I move adding columns to after creation of columns application works as expected. If I open Form in designer make any change to form (even just adding space to Title), the initialization of DataGridView is always moved above creation of columns and application breaks. In other cases adding items to container happens after they are initialized Me.Add to populate controls on Form is always last. The same should be true for DataGridView.

**Comment by paul1956** [comment]
In your example you are not looking at the columns in the ColumnsAdded handler you are just changing values that will be over written when the columns are initialized. In my example I look at the column HeaderText or other properties and take action based on them or modify them but because of initialization order add the fields are Nothing (Null). I hide certain columns based on their name for example.

**Comment by Olina-Zhang** [comment]
@paul1956 Could you please provide a sample application in order to understand your issue? Thanks a lot!

**Comment by paul1956** [comment]
https://github.com/paul1956/DataGridViewSerializationFailure

All you need be concerned with is Form1 and the placement of the initialization of the column initialization with respect to the DataGridViews (I cloned the columns for simplicity). There is an #IF around failing code, and an identical handler in the other case.'

The one difference is the placement of the Initialization of the DataGridView. If only fails where there is a BindingSource.

**Comment by Olina-Zhang** [comment]
@paul1956 Thanks for your detail description. And we verified previous VS and the latest VS, all have same Initialization sequence for DataGridView in C# and VB, first is DataGridView Initialization, then column initialization as following screenshot. Once Form UI has some change, like add space to Form title you did, all of Designer initialization will be generated automatically, so you see the behavior about the DataGridView Initialization is moved before column initialization. It seems not a real issue. Please let our engineering team to confirm. @dreddy-work or @Tanya-Solyanik 
![image](https://user-images.githubusercontent.com/26474449/221828941-8baae3db-4bfb-48ba-b98a-1f041cdd0ec9.png)

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann can you take a look while you're working in Serialization?

**Comment by paul1956** [comment]
@drago-draganov @Tanya-Solyanik @KlausLoeffelmann It is definitely a real issue when you have a BindingSource, the ColumnAdded Events happen before the columns are initialized. I have not seen, the code that deals with ColumnsAdded is very old.

It seems to me that all components should be initialized BEFORE they are added to a container like is done with Form (and some others) so that events work correctly. I don't see how that could break anything.

**Comment by Tanya-Solyanik** [comment]
@paul1956  - are you saying that `BeginInit` on DataGridView is not working anymore? Do you experience uniitialized values at the runtime - 
>If DgvCareLinkUsers has a Handler on ColumnAdded can't use DataPropertyName or Name because they are initialized AFTER the column is added. Those values are blank at the time of the add.

**Comment by paul1956** [comment]
@Tanya-Solyanik I am not sure what BeginIntit is (don't know what it does or where it is) but yes, all the values that are set in Form1.Designer for the Columns are uninitialized when the handler gets called UNLESS I move the initialization of the DataGridView control (that contains the columns) until after the columns are initialized (which are the 2 cased shown in the code I posted) in Form1.Designer. The difference with VB vs. C# is that I can set up the handlers in Form1 BEFORE the Form is initialized so when the columns are added the Columns_Added handler is getting invoked but the columns are uninitialized.

**Comment by KlausLoeffelmann** [comment]
@paul1956, do you have the chance to create a small repro for this issue with VS 2019 .Net 5 by any chance, then open it with 2022 >=17.5, make a small size change to the form, save it, and show the delta of both `InitializeComponent` versions of 2019 and 2022? That would be extremely helpful! Could you also check, if in 2019 the behavior at runtime is still as expected?

**Comment by paul1956** [comment]
I don't have 2019 but every version I had tried of 2022 moves moves the creation of the  DataGridView before the columns are initialized which I thought was the issue but reading some of this thread it's not the order of initialization in DataGridView vs DataGridViewColumn but that beginInit is supposed to somehow delay the events from being called until the end of the initialization and that is what is not happening.

**Comment by paul1956** [comment]
@KlausLoeffelmann I can't even download VS 2019.

**Comment by KlausLoeffelmann** [comment]
Does this work for you?
https://visualstudio.microsoft.com/vs/older-downloads/

**Comment by paul1956** [comment]
@KlausLoeffelmann thanks I downloaded it. 

After changing name of Form1, the file is very different, but the same reordering happens, and the app will crash unless I move below from near top to bottom.
Below fails
```
        CType(Me.DgvCareLinkUsers, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.CareLinkUserDataListBindingSource, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'DgvCareLinkUsers
        '
        Me.DgvCareLinkUsers.AllowUserToAddRows = False
        Me.DgvCareLinkUsers.AllowUserToResizeColumns = False
        Me.DgvCareLinkUsers.AllowUserToResizeRows = False
        Me.DgvCareLinkUsers.AutoGenerateColumns = False
        Me.DgvCareLinkUsers.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells
        Me.DgvCareLinkUsers.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells
        Me.DgvCareLinkUsers.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DgvCareLinkUsers.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.AutoLoginDataGridViewCheckBoxColumn, Me.CareLinkPasswordDataGridViewTextBoxColumn, Me.CareLinkUserNameDataGridViewTextBoxColumn, Me.CountryCodeDataGridViewTextBoxColumn, Me.IDDataGridViewTextBoxColumn, Me.UseLocalTimeZoneDataGridViewCheckBoxColumn})
        Me.DgvCareLinkUsers.DataSource = Me.CareLinkUserDataListBindingSource
        Me.DgvCareLinkUsers.EditMode = System.Windows.Forms.DataGridViewEditMode.EditOnEnter
        Me.DgvCareLinkUsers.Location = New System.Drawing.Point(0, 0)
        Me.DgvCareLinkUsers.Name = "DgvCareLinkUsers"
        Me.DgvCareLinkUsers.RowTemplate.Height = 25
        Me.DgvCareLinkUsers.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.CellSelect
        Me.DgvCareLinkUsers.Size = New System.Drawing.Size(800, 450)
        Me.DgvCareLinkUsers.TabIndex = 0
```

Below works
```
        '
        'DgvCareLinkUsers
        '
        Me.DgvCareLinkUsers.AllowUserToAddRows = False
        Me.DgvCareLinkUsers.AllowUserToResizeColumns = False
        Me.DgvCareLinkUsers.AllowUserToResizeRows = False
        Me.DgvCareLinkUsers.AutoGenerateColumns = False
        Me.DgvCareLinkUsers.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells
        Me.DgvCareLinkUsers.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells
        Me.DgvCareLinkUsers.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DgvCareLinkUsers.Columns.AddRange(New System.Windows.Forms.DataGridViewColumn() {Me.AutoLoginDataGridViewCheckBoxColumn, Me.CareLinkPasswordDataGridViewTextBoxColumn, Me.CareLinkUserNameDataGridViewTextBoxColumn, Me.CountryCodeDataGridViewTextBoxColumn, Me.IDDataGridViewTextBoxColumn, Me.UseLocalTimeZoneDataGridViewCheckBoxColumn})
        Me.DgvCareLinkUsers.DataSource = Me.CareLinkUserDataListBindingSource
        Me.DgvCareLinkUsers.EditMode = System.Windows.Forms.DataGridViewEditMode.EditOnEnter
        Me.DgvCareLinkUsers.Location = New System.Drawing.Point(0, 0)
        Me.DgvCareLinkUsers.Name = "DgvCareLinkUsers"
        Me.DgvCareLinkUsers.RowTemplate.Height = 25
        Me.DgvCareLinkUsers.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.CellSelect
        Me.DgvCareLinkUsers.Size = New System.Drawing.Size(800, 450)
        Me.DgvCareLinkUsers.TabIndex = 0
        '
        'Form1
        '
```

**Comment by Tanya-Solyanik** [comment]
@paul1956 - Do I understand correctly that this is not a regression from VS 2019?

**Comment by paul1956** [comment]
I believe that is correct, I don't know the last time it worked. But given what BeginInit is supposed to do it's not doing it now.

This code predates .NetCore but only recent releases of 2022 Designer was functional  for VB, so I just made adjustments by editing FormX.Design.VB and initialize of DataGridView was after Columns and they didn't move.  Since the designer has gotten better I want to use it and the issue is obvious because every edit  reorders the Designer file and breaks the application.

**Comment by paul1956** [comment]
@KlausLoeffelmann 
If DataGridViewColumn initialization were turned into below it would simplify the code and address the BeginInit issue.
```
Me.DgvCareLinkUsersUserID = New DataGridViewTextBoxColumn With {
            .DataPropertyName = "ID",
            .HeaderText = "ID",
            .Name = "DgvCareLinkUsersUserID",
            .ReadOnly = True,
            .Width = 43
        }
```

Its similar to what is done for TableLayoutPanel Styles. without all the formatting

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team create this issue in the designer repo and we will try to get it on the backlog there. You can close this one.

**Comment by Olina-Zhang** [comment]
Created in designer repo: https://github.com/microsoft/winforms-designer/issues/6139, closing this one now.
