### ISSUE TITLE
pls remove the Limit of ContainsGenericParameters 

### ISSUE THREAD

**Issue by sgf** [dotnet/winforms#8704]
### Environment

VS2022 Version  17.4.4

### .NET version

.net 6.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

no work

### Issue description

base class is a Generic Class with Generic Paramaters

### Steps to reproduce

```C#
    public class XLabelBase<T, TMainControl> : UserControl
        where T : XLabelBase<T, TMainControl>
        where TMainControl : Control

    {
        public XLabelBase()
        {

        }

}


public partial class XLabelBox : XLabelBase<XLabelBox, TextBox>{


}

```
the XLabelBox  oepn in designer will throw error:

`Cannot create an instance of  because Type.ContainsGenericParameters is true.`

**Comment by merriemcgaw** [comment]
Thank you for bringing this to our attention! Generic Classes with Generic Parameters is not something the designer currently supports, and it is not aligned with our current roadmap. We will continue to listen to customer feedback and if there is enough demand we will try to get this on the backlog. For now, we will close this issue.

**Comment by sgf** [comment]
ok,tks reply
