### ISSUE TITLE
WebBrowser Control Printing API Suggestions

### ISSUE THREAD

**Issue by csturm83** [dotnet/winforms#873]
I have used the WebBrowser control in WinForms applications to display/print simple(ish) HTML reports generated dynamically using XSLT. In my experience, this has proven to be a lighter-weight/more accessible solution than using the ReportViewerControl (last I checked the ReportViewerControl was not that accessible to screen readers like JAWS).

One of my requirements is to print reports (HTML) sequentially in batch using user selected print settings. The current WebBrowser control print methods do not make this particularly easy. (Admittedly, this may not be a use case for which the WebBrowser control was originally intended).

The [ShowPrintDialog()](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser.showprintdialog?view=netframework-4.8) method does not return user selected print settings like [PrintDialog.PrinterSettings](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.printdialog.printersettings?view=netframework-4.8) does. The WebBrowser control [Print()](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser.print?view=netframework-4.8) method always uses the current print and page settings.

It would be useful to have a Print overload that took something along the lines of PrinterSettings as an argument if possible.

```csharp
public void Print(PrinterSettings settings);  // perhaps print to a non-default printer
```

It also might be useful to directly expose the PrintTemplateTeardown event to be able to easily determine when printing has completed.

Another somewhat related (maybe less feasible) idea I had would be to expose a PrintPdf() function which could use feature detection to determine if the Win10 Print to PDF Driver is available. If so, print using that driver, if not, throw PNSE.

```csharp
public void PrintPdf(string filename);
public void PrintPdf(string filename, PrinterSettings settings);
```

**Comment by dreddy-work** [comment]
WebBrowser control is outdated and being replaced with [WebView2](https://github.com/MicrosoftEdge/WebView2Feedback).  Any improvements in this control needs to be redirected to WebView2. Closing this suggestion.
