### ISSUE TITLE
SplitContainerDesigner is missing in .net6.0.

### ISSUE THREAD

**Issue by PanchRajMaurya** [dotnet/winforms#8749]
### Environment

 I have a project that uses the SplitContainer and its designer at runtime. It was working fine in .NET framework(4.8) but after upgrading to .net6.0 the control is not visible on designer site.

### .NET version

I have upgraded the project from .Net framework(4.8) to .Net6.0.

### Did this work in a previous version of Visual Studio and/or previous .NET release?

It was working fine in .Net Framework 4.8.

### Issue description

We have provided a feature to our customers in which the controls of the forms can be resized and relocated at runtime.
Then it is stored as a xml file and reloaded when reopened the same form.
After upgrading to .net6.0 the designer of the form is not visible in edit mode at runtime.

### Steps to reproduce

https://www.c-sharpcorner.com/UploadFile/asmabegam/easy-form-design-at-run-time-C-Sharp-winform/

**Comment by RussKie** [comment]
Related https://github.com/dotnet/winforms/issues/4908.

**Comment by PanchRajMaurya** [comment]
As per #4908, SplitContainerDesigner is out of scope. Then what are the alternatives for the same.

**Comment by merriemcgaw** [comment]
This is the first request we've had for this designer at runtime. The out of process WinForms designer already implements this for working in VS. It looks like you were also using the designer at runtime, so we should consider porting it.

@dmitrii-drobotov can your team take a look and let me know what you think about picking up this issue?

**Comment by dmitrii-drobotov** [comment]
@merriemcgaw sure, porting this designer doesn't seem too complicated, I think we can pick it up. 

@PanchRajMaurya as a workaround, could you try an approach from [this comment](https://github.com/dotnet/winforms/issues/8508#issuecomment-1396632170)? The designer won't be very functional but at least would appear on the form.

**Comment by PanchRajMaurya** [comment]
> @merriemcgaw sure, porting this designer doesn't seem too complicated, I think we can pick it up.
> 
> @PanchRajMaurya as a workaround, could you try an approach from [this comment](https://github.com/dotnet/winforms/issues/8508#issuecomment-1396632170)? The designer won't be very functional but at least would appear on the form.

After implementing the SplitContainerDesigner as per the comment, the existing forms are visible on designer site but still not able to create new form by using SplitContainer because there are no Panels in dropped control.

**Comment by PanchRajMaurya** [comment]
Any timeline to fix the issue?

**Comment by merriemcgaw** [comment]
We don't yet have a timeline for this fix unfortunately. @dreddy-work do you think we can get this on the backlog and have it done for .NET 8?

**Comment by dreddy-work** [comment]
Will take a look and update the scope here.
