### ISSUE TITLE
[API Proposal]: Define a pattern for default values that used to be constants proportional to the default system font.

### ISSUE THREAD

**Issue by dkazennov** [dotnet/winforms#8751]
### Related bugs and PRs:

- #4463 
- #8518 
- #8755 
- https://github.com/dotnet/winforms/pull/10142
- #8640 

### Background

The `ListBox` control `ItemHeight` property was decorated with a [DefaultValueAttribute] (This was changed by the #8518).
The `DefaultValueAttribute` for the `ListBox.ItemHeight` was the public const `DefaultItemHeight` property (a constant with value `13`). The problem with the constant value is that if application's default font is changed then the DefaultItemHeight will lose relevance.

As being explained in the DotNet Issue **[Define a pattern for default values that used to be constants proportional to the default system font](https://github.com/dotnet/winforms/issues/8599)** this leeds to extra code being generated for the `ListBox` control at the runtime: the generated code for ListBox had extra code for the ListBox .ItemHeight property.  And the generated property has value was not consistent with the old constant value.

### Suggestion
Use Control.DefaultFont.Height value as the default for the ItemHeight property.

1. remove the default value attribute from ItemHeight property;
2. make DefaultItemHeight` constant obsolete;
3. set the default ItemHeight value to the value of the static property `Control.DefaultFont.Height` (thus the ListBox.ItemHeight will be dependent on the height of the Application's Default Font);
4. change `ResetItemHeight` and add `ShouldSerializeItemHeight` methods that compare actual value against the dynamic runtime default.

### This is a breaking change

Per https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#attributes. We make one attribute obsolete and we change the value of an attribute that is observable.

**Comment by merriemcgaw** [comment]
@Tanya-Solyanik would love your thoughts on the impact and effort for this one.

**Comment by Tanya-Solyanik** [comment]
@merriemcgaw this was fixed by #10142
