### ISSUE TITLE
TreeNodeCollection.AddRange works incorrectly for non-empty collection of the sorted TreeView

### ISSUE THREAD

**Issue by snnz** [dotnet/winforms#8768]
### .NET version

6.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

When the tree nodes are appended to the non-empty `TreeNodeCollection` owned by the sorted `TreeView` with already created underlying window, the resulting order of items in the actual window does not match the one in the collection (which is correct).

The cause is how method `TreeNode.PrevNode` works: when called from within `TreeNodeCollection.AddRange` of non-empty collection, it always uses fixed index as the position of the previous node, assuming the normal backward insertion of the nodes in the unsorted tree. Yet in case of the sorted `TreeView`, insertions are made at various positions according to a sort order.

There obviously should be a check for the sorted state of the tree in `TreeNode.PrevNode` to avoid this.

### Steps to reproduce

```
namespace TreeViewTest
{
  internal static class Program
  {
    [STAThread]
    static void Main()
    {
      ApplicationConfiguration.Initialize();

      var treeView = new TreeView();
      treeView.Nodes.Add(new TreeNode("2"));
      treeView.Sort();

      var form = new Form();
      form.Controls.Add(treeView);
      form.Load += (sender, e) => treeView.Nodes.AddRange(new TreeNode[] {
        new TreeNode("3"),
        new TreeNode("5"),
        new TreeNode("1"),
        new TreeNode("4")
      });
      Application.Run(form);
    }
  }
}
```

This results in:
![Clipboard01](https://user-images.githubusercontent.com/20656895/223826227-6cf6d1aa-3605-4e39-98a8-65116d5db21a.png)

**Comment by merriemcgaw** [comment]
Thanks for filing this issue. I will hand this over to the community if someone has ideas for how to fix this and put it under a configuration switch. Given that this has been the behvavior since .NET Framework days, the team will not be able to prioritize it on our end.

**Comment by snnz** [comment]
I've submitted a possible fix as PR #8774; it is very simple.

**Comment by elachlan** [comment]
See #8556 for examples of context switches.

**Comment by RutulPatel8** [comment]
https://github.com/dotnet/winforms/pull/11300

**Comment by RutulPatel8** [comment]
@Tanya-Solyanik Can you please review my PR.
I can see the issue in XUnit Test but It is not related to the my code.

**Comment by RutulPatel8** [comment]
I'm not sure, but I can say one thing: There have been lots of changes made with these PRs, and I've made the same change by altering a single 'if' condition. Could you please review my PR?"

**Comment by Tanya-Solyanik** [comment]
I had verified again, this is reproing in .NET Framework, my experiment was wrong because I re-sorted the TreeView after adding the unsorted range

**Comment by RutulPatel8** [comment]
@Tanya-Solyanik It means still you have facing the same issue and my changes wasn't working with.net framework?

**Comment by Tanya-Solyanik** [comment]
@RutulPatel8  - your change is good, except for the failing tests. All failing tests are related to treeviews and that they are not failing for other PRs.

**Comment by Tanya-Solyanik** [comment]
Moving to triage to confirm that we don't want an opt-in switch for this change.

**Comment by merriemcgaw** [comment]
This has been present since .NET Framework so we will need an opt-out switch for this behavior. @Tanya-Solyanik suggests `TreeNodeCollectionAddRangeRespectsSortOrder`

This will potentially be a breaking change, but the current behavior is not what we'd expected.

**Comment by merriemcgaw** [comment]
@RutulPatel8, are you planning on picking this one up, or should we have a team member wrap up the work? Thanks!

**Comment by Liv-Goh** [comment]
Verified this issue on 9.0.100-preview.6.24312.9 with dlls built from winforms repo of main branch, it was fixed: the tree nodes added by using TreeNodeCollection.AddRange are sorted correctly
![image](https://github.com/dotnet/winforms/assets/169347065/05699204-8e3d-40d8-a4e5-50950d1fc4a1)

**Comment by Philip-Wang01** [comment]
Verified the issue with .NET 9.0.100-preivew.6.24325.8 TP build. the issue has been fixed that have the same results as above.
