### ISSUE TITLE
TablelayoutPanelDesigner,TabControlDesigner is missing in .net7.0.

### ISSUE THREAD

**Issue by ravipoddar10** [dotnet/winforms#8790]
### .NET version

.net7.0

### Did it work in .NET Framework?

Yes

### Issue description

Designer surface code generation issue occur with table layout panel

https://learn.microsoft.com/en-us/answers/questions/1187787/private-member-code-generation-and-resize-issue-wi

### Steps to reproduce

https://learn.microsoft.com/en-us/answers/questions/1187787/private-member-code-generation-and-resize-issue-wi

**Comment by elachlan** [comment]
Related: #4908

**Comment by elachlan** [comment]
@dmitrii-drobotov I suspect based on previous issues the winforms team will ask you to add this to your teams backlog.

CC: @merriemcgaw

**Comment by merriemcgaw** [comment]
@ravipoddar10 - can you help me understand your user scenario for needing to have a designer during runtime? Happy to look into it, just wanting to make sure we enable the right scenario 😄

**Comment by elachlan** [comment]
@merriemcgaw I think the use case is highlighted in the provided link?

**Comment by ravipoddar10** [comment]
Hi [merriemcgaw](https://github.com/merriemcgaw)

Our team develop a DataEntry product and where user design  our predefine control and after that build the designer surface generated code....  and that dll is use as a runtime where a dataentry operator enter and post the data 

sample code (https://learn.microsoft.com/en-us/answers/questions/1187787/private-member-code-generation-and-resize-issue-wi)

**Comment by deinok** [comment]
Same:
[16:00:14.298963] warn: [IntegraNet]: Could not resolve type for Microsoft.WinForms.DesignTools.Designers.TableLayoutPanel.TableLayoutPanelDesigner+DesignerTableLayoutControlCollectionCodeDomSerializer.

**Comment by Tanya-Solyanik** [comment]
Use https://devdiv.visualstudio.com/DevDiv/_git/VS?path=/src/vsip/Designer/WinForms/System/WinForms/Design as the source
