### ISSUE TITLE
Test: System.Drawing.Tests.FontFamilyTests/Ctor_Name failed with "System.ArgumentException"

### ISSUE THREAD

**Issue by dotnet-mc-bot** [dotnet/winforms#8805]
Opened on behalf of @Jiayili1

The test `System.Drawing.Tests.FontFamilyTests/Ctor_Name(name: \"Microsoft Sans Serif\", expectedName: \"Microsoft Sans Serif\")` has failed.

System.ArgumentException : Font 'Microsoft Sans Serif' cannot be found.

        Stack Trace:

           at System.Drawing.FontFamily.CreateFontFamily(String name, FontCollection fontCollection)
       at System.Drawing.Tests.FontFamilyTests.Ctor_Name(String name, String expectedName)
Build : Master - 20170726.01 (Core Tests)
Failing configurations:
- Windows.10.Amd64.Core-x86
  - Release
- Windows.10.Amd64.Core-x64
  - Release

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170726.01/workItem/System.Drawing.Common.Tests/analysis/xunit/System.Drawing.Tests.FontFamilyTests~2FCtor_Name(name:%20%5C%22Microsoft%20Sans%20Serif%5C%22,%20expectedName:%20%5C%22Microsoft%20Sans%20Serif%5C%22)

**Comment by JeremyKuhne** [comment]
No longer disabled.
