### ISSUE TITLE
ArgumentException: "Parameter is not valid" in Bitmap when file is not found or null

### ISSUE THREAD

**Issue by Zermond** [dotnet/winforms#8809]
# Issue Title

A Wrong exception of class Bitmap

# General

I have a code: 

```
            using (Bitmap bitmap = new Bitmap(fileName))
            {
                Console.WriteLine(bitmap.Size);
            }
```

If a file on path the fileName null or file not found I have an exception: 
`Unhandled Exception: System.ArgumentException: Parameter is not valid.`

I had this bug with 3 other ways: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.505
 Commit:    b220231234

Runtime Environment:
 OS Name:     altlinux
 OS Version:  8.2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/lib64/dotnet/sdk/2.1.505/
```
```Version:   3.0.100
 Commit:    04339c3a26

 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33
```

And with docker which I get from based images of Microsoft 
`FROM mcr.microsoft.com/dotnet/core/runtime:2.1`

[ConsoleApp2.zip](https://github.com/dotnet/core/files/3681659/ConsoleApp2.zip)

**Comment by JeremyKuhne** [comment]
I'm fine with adding a null check and throwing `ArgumentNullException` here (particularly as it already throws `ArgumentException`). I don't want to add a `File.Exists` check as it is transient, and we generally leave IO related errors to the code that actually creates and interacts with the IO handles.

**Comment by elachlan** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.-ctor?view=dotnet-plat-ext-7.0#system-drawing-bitmap-ctor(system-string)

According to the documentation the constructor with just a filename string will throw a `filenotfoundexception`. Based on the code, it doesn't do this.

I think its better to add `ArgumentException.ThrowIfNullOrWhiteSpace(filename, nameof(filename));` and avoid checking if the file exists.

**Comment by elachlan** [comment]
The constructor already calls `Path.GetFullPath(filename);` which will throw:
https://github.com/dotnet/winforms/blob/fdad5bc2e99e33622b24d4c5265ff24ddd7c8766/src/System.Drawing.Common/src/System/Drawing/Bitmap.cs#L28-L32

https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=net-7.0

I don't know how we can improve this.

@JeremyKuhne I suggest we close this.

**Comment by JeremyKuhne** [comment]
@elchan, you're right, `Path.GetFullPath` throws `ArgumentNullException`. Sorry that I missed this.

There isn't really anything we can do here as GDI+ doesn't give us any further context as to why it failed. Even if we tried to check for the file existing, it would break existing code that was handling this case by doing their own checking of `File.Exists` after catching the current exception. Generally speaking we can't change to anything other than a derived exception for compatibility. (We deliberately make an exception for `NullReferenceException` which we change to either `ArgumentException` or `InvalidOperationException` based on available context.)
