### ISSUE TITLE
Add support for converting the format of a Bitmap

### ISSUE THREAD

**Issue by reflectronic** [dotnet/winforms#8827]
### Background

GDI+ 1.1 added support for converting the pixel format of an bitmap in-place. Naturally, one can specify a target pixel format, but the function accepts many other parameters to control aspects of the conversion. Unfortunately, the API is not very well designed — it's poorly documented, and many combinations of options seem to be outright ignored or result in vague errors — but [a not insubstantial amount of people have wondered how to do this](https://stackoverflow.com/questions/2016406/converting-bitmap-pixelformats-in-c-sharp), and the workaround is slow, less flexible, and certainly not obvious.

When converting to an indexed pixel format, the `ditherType`, `paletteType`, and `palette` parameters become relevant. Color palettes can be provided in order to constrain the colors in the converted image. There are effectively three categories of palettes:

- *Custom palettes.* All available colors are specified by the user.
- *Optimal palettes.* An optimal palette is created using an image, and consists of the best *n* colors (where *n* is specified by the user) from the image to be used when converting the image.
- *Standard palettes.* The user can specify one of many predefined fixed palettes, and may use them in combination with an ordered or spiral dither type to produce a halftone image.

When a standard fixed palette type is used, any dither type is valid. Otherwise, only `None`, `Solid`, and `ErrorDiffusion` are valid. (As an exception, `DitherTypeOrdered4x4` may be used when converting to a 16 bits-per-pixel format using any palette.) GDI+ will convert from a standard palette specified with `paletteType` to a custom palette passed in `palette` using a nearest-color conversion.

One can also specify an alpha threshold percent. Passing a value *t* specifies that a pixel that is less than *t* percent fully opaque will map to the transparent color. (If there is no transparent color, the color closest to black will be selected.)

This proposal is one of many to add missing GDI+ 1.1 functionality to `System.Drawing`.

### Usage Example

```cs
Bitmap bitmap = (Bitmap) Image.FromFile("immo.jpg");
ColorPalette palette = new ColorPalette(PaletteType.FixedHalftone8);
image.ConvertFormat(PixelFormat.Format8bppIndexed, DitherType.Ordered16x16, PaletteType.FixedHalftone8, palette);
```

![Before and after sample of above code sample](https://user-images.githubusercontent.com/27514983/109404758-1d7fa980-7937-11eb-8c1d-b5afa72126ac.png)

### API Proposal -- Updated: https://github.com/dotnet/winforms/issues/8827#issuecomment-1920392878

See the documentation for:
- [Bitmap::ConvertFormat](https://docs.microsoft.com/en-us/windows/win32/api/gdiplusheaders/nf-gdiplusheaders-bitmap-convertformat)
- [Bitmap::InitializePalette](https://docs.microsoft.com/en-us/windows/win32/api/gdiplusheaders/nf-gdiplusheaders-bitmap-initializepalette)
- [DitherType](https://docs.microsoft.com/en-us/windows/win32/api/gdipluspixelformats/ne-gdipluspixelformats-dithertype)
- [PaletteType](https://docs.microsoft.com/en-us/windows/win32/api/gdipluspixelformats/ne-gdipluspixelformats-palettetype)

```diff
namespace System.Drawing.Imaging
{
+   public enum PaletteType
+   {
+       Custom,
+       Optimal,
+       FixedBW,
+       FixedHalftone8,
+       FixedHalftone27,
+       FixedHalftone64,
+       FixedHalftone125,
+       FixedHalftone216,
+       FixedHalftone252,
+       FixedHalftone256
+   }
    
+   public enum DitherType
+   {
+       None,
+       Solid,
+       ErrorDiffusion,
+       Ordered4x4,
+       Ordered8x8,
+       Ordered16x16,
+       Spiral4x4,
+       Spiral8x8,
+       DualSpiral4x4,
+       DualSpiral8x8
+   }

    public sealed class ColorPalette
    {
+       public ColorPalette(Color[] customColors);
+       public ColorPalette(PaletteType fixedPaletteType);
+       public static ColorPalette CreateOptimalPalette(int colors, Bitmap bitmap);
    }
}

namespace System.Drawing
{
    public sealed class Bitmap : System.Drawing.Image
    {
!       Overload for simplicity.
+       public void ConvertFormat(PixelFormat format);
+       public void ConvertFormat(PixelFormat format, DitherType ditherType, PaletteType paletteType, ColorPalette? palette, float alphaThresholdPercent);
    }
}
```

This requires changes to libgdiplus in order to support it on non-Windows platforms.

**Comment by JeremyKuhne** [comment]
Minor tweak from the original proposal.

```diff
namespace System.Drawing.Imaging
{
+   public enum PaletteType
+   {
+       Custom,
+       Optimal,
+       FixedBW,
+       FixedHalftone8,
+       FixedHalftone27,
+       FixedHalftone64,
+       FixedHalftone125,
+       FixedHalftone216,
+       FixedHalftone252,
+       FixedHalftone256
+   }
    
+   public enum DitherType
+   {
+       None,
+       Solid,
+       ErrorDiffusion,
+       Ordered4x4,
+       Ordered8x8,
+       Ordered16x16,
+       Spiral4x4,
+       Spiral8x8,
+       DualSpiral4x4,
+       DualSpiral8x8
+   }

    public sealed class ColorPalette
    {
+       public ColorPalette(params Color[] customColors);
+       public ColorPalette(PaletteType fixedPaletteType);
+       public static ColorPalette CreateOptimalPalette(int colors, bool useTransparentColor, Bitmap bitmap);
    }
}

namespace System.Drawing
{
    public sealed class Bitmap : System.Drawing.Image
    {
+       public void ConvertFormat(PixelFormat format, DitherType ditherType, PaletteType paletteType, ColorPalette? palette, float alphaThresholdPercent);
    }
}
```

**Comment by JeremyKuhne** [comment]
@reflectronic Now that we've fully transferred ownership of System.Drawing to WinForms and transitioned to CsWin32 I'm pushing forward on getting these GDI+ features implemented. If you have any additional feedback please let me know.

**Comment by JeremyKuhne** [comment]
Using these "auto-picked" arguments:

``` C#
public void ConvertFormat(PixelFormat format)
{
    PixelFormat currentFormat = PixelFormat;
    int targetSize = ((int)format >> 8) & 0xff;
    int sourceSize = ((int)currentFormat >> 8) & 0xff;

    if (!format.HasFlag(PixelFormat.Indexed))
    {
        ConvertFormat(format, targetSize > sourceSize ? DitherType.None : DitherType.Solid);
        return;
    }

    int paletteSize = 1 << targetSize;
    bool hasAlpha = format.HasFlag(PixelFormat.Alpha);
    ColorPalette palette = ColorPalette.CreateOptimalPalette(paletteSize, hasAlpha, this);
    ConvertFormat(format, DitherType.ErrorDiffusion, PaletteType.Custom, palette, .25f);
}
```

Here are some results:

1BppIndexed
![bill-gates-Format1bppIndexed](https://github.com/dotnet/winforms/assets/8184940/40bf0e96-7ed0-45eb-8a50-77833d2f81b1)
4BppIndexed
![bill-gates-Format4bppIndexed](https://github.com/dotnet/winforms/assets/8184940/e16eb2d1-7d3a-4304-9356-7061b49fe35e)
8bppIndexed
![bill-gates-Format8bppIndexed](https://github.com/dotnet/winforms/assets/8184940/1f50b9a8-1225-4d96-b8e1-b4fc79fc9eb2)
16bppArgb1555
![bill-gates-Format16bppArgb1555](https://github.com/dotnet/winforms/assets/8184940/422779d7-5c36-48ca-852d-fb6c5811b058)
16bppRgb565
![bill-gates-Format16bppRgb565](https://github.com/dotnet/winforms/assets/8184940/faa3a2bf-ba76-40b2-b030-c118262bebb0)

The original:
![bill-gates](https://github.com/dotnet/winforms/assets/8184940/54df2cc1-657e-4a28-b421-92e0ad80a16f)

**Comment by terrajobst** [comment]
```C#
namespace System.Drawing.Imaging
{
    public enum PaletteType
    {
        Custom,
        FixedBlackAndWhite,
        FixedHalftone8,
        FixedHalftone27,
        FixedHalftone64,
        FixedHalftone125,
        FixedHalftone216,
        FixedHalftone252,
        FixedHalftone256
    }
    
    public enum DitherType
    {
        None,
        Solid,
        ErrorDiffusion,
        Ordered4x4,
        Ordered8x8,
        Ordered16x16,
        Spiral4x4,
        Spiral8x8,
        DualSpiral4x4,
        DualSpiral8x8
    }

    public sealed class ColorPalette
    {
        public ColorPalette(params Color[] customColors);
        public ColorPalette(PaletteType fixedPaletteType);
        public static ColorPalette CreateOptimalPalette(int colors,
                                                        bool useTransparentColor,
                                                        Bitmap bitmap);
    }
}

namespace System.Drawing
{
    public sealed class Bitmap : System.Drawing.Image
    {
        public void ConvertFormat(PixelFormat format);
        public void ConvertFormat(PixelFormat format,
                                  DitherType ditherType,
                                  PaletteType paletteType = PaletteType.Custom,
                                  ColorPalette? palette = null,
                                  float alphaThresholdPercent = 0.0f);
    }
}
```
