### ISSUE TITLE
`System.Drawing.SystemFonts.DefaultFont` cannot switch automatically according to the system and Do some reflections

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#8843]
**Version Used**: 

Test IDEs: Visual Studio 2017; Visual Studio 2019; Visual Studio 2021;

**Steps to Reproduce**:

1. Install English OS, the default font size is 8.25.
2. Change the display language and region to Chinese, I want to change it as 9.

**Expected Behavior**:

I'm a Chinese. My Chinese colleagues use Chinese systems and the default font size for projects is 9. We know that `default font` is not written to the `winform designer`, which I consider a great harm and torture. When I started, their interface was messed up and I knew I should give feedback to the `winform` project, but I wasn't sure and the project team had very limited human input.

I think the font design should be written into the code so that people from different countries don't see it inconsistently, or at least the font size shouldn't change automatically.

The worst case is that when I install a language pack, it should be handled automatically instead of ignoring it, they have certain dependencies. I hope you should notice a lot of dependency details instead of simply ignoring them. Unless you actually write all the details of the parameters into every use of the code, only then can you disregard them.

**Actual Behavior**:

When I fetch the code, my local designer and run state do not match the original design font size.

I think this is a flaw, my original system is native English and when I installed the Chinese language pack I wasn't able to configure all the behavior I should have.

**Reflection**

If you think this is a `winform` issue, then I hope you will consider whether you have noticed any side effects or defects hidden elsewhere in this issue?

**Comment by JeremyKuhne** [comment]
Closing as the original author account is gone and it doesn't appear that we can do anything here (at least without more details).
