### ISSUE TITLE
Documentation should not redirect to .NET 4.8 documentation if it doesn't apply to .Net 3+ Winforms.

### ISSUE THREAD

**Issue by TrevorFellman-MSFT** [dotnet/winforms#8866]
### Environment

learn.microsoft.com

Microsoft Visual Studio Enterprise 2022
Version 17.5.0
VisualStudio.17.Release/17.5.0+33414.496
Microsoft .NET Framework
Version 4.8.09032

### .NET version

.NET 6+

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes, the docs are correct for .NET 4.8

### Issue description

Users evaluating .NET 6/7 will search the internet and find documentation on learn.microsoft.com (but for .NET 4.8)
They use the combobox to select .NET 6/7 and are redirected back to the 4.8 documentation.
When it is wrong, they assume nothing has changed and the documentation is relevant for them.
They don't go to the Github repro and check the wiki/docs there that are more correct.
They get confused and call Microsoft.

example, customer wondering why his controls wouldn't show up in the Winform's designer toolbox even though he was following the documentation.
here are a few links in that area.
learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-display-a-control-in-the-choose-toolbox-items-dialog-box?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-6.0

https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/walkthrough-automatically-populating-the-toolbox-with-custom-components?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-6.0

https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-display-a-control-in-the-choose-toolbox-items-dialog-box?view=netframeworkdesktop-4.8&viewFallbackFrom=netdesktop-6.0

### Steps to reproduce

1.  navigate to learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-display-a-control-in-the-choose-toolbox-items-dialog-box?view=netframeworkdesktop-4.8
2. Change the combobox from .NET Famework 4.8 to .NET 7

Expected Results
===========
No documentation

Actual Results
==========
Still looking at the 4.8 docs even though things don't work that way anymore, but thinking they still apply.
We need correct documentation.

### Diagnostics

```text
NA
There is a banner at the top that states...
"The requested page is not available for .NET 6.0. You have been redirected to the newest product version this page is available for."
However, every customer and support engineer I have talked to miss it.  I think it looks too much like an Ad, and we've been trained to ignore content that doesn't look like it's part of the article, but that is just a guess.
```

**Comment by TrevorFellman-MSFT** [comment]
@merriemcgaw, @adegeo, can you take a look at this as this has/is causing confusion for customers and support engineers.  I've already brought this up to Merrie.

**Comment by merriemcgaw** [comment]
@Olina-Zhang do you have the ability to create issues in the dotnet/docs repo? If so, can you please copy this issue there and close this one. Otherwise, let me know and I will.

**Comment by MelonWang1** [comment]
@merriemcgaw  Filed a docs issue https://github.com/dotnet/docs/issues/43199. Closed this.
