### ISSUE TITLE
Windows Automation RaiseAutomationPropertyChangedEvent throws System.AccessViolationException

### ISSUE THREAD

**Issue by gc-maximloverov** [dotnet/winforms#8867]
### .NET version

6.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

Windows Automation RaiseAutomationPropertyChangedEvent method for SelectionPatternIdentifiers.SelectionProperty throws System.AccessViolationException.
No exception is thrown if the AutomationPropertyChangedEvent for SelectionPatternIdentifiers.SelectionProperty values are "null" or "new IRawElementProviderSimple[0]".

### Steps to reproduce

1. Run attached app:
[UiaAccessViolationException6.zip](https://github.com/dotnet/winforms/files/11000223/UiaAccessViolationException6.zip)
2. Run "Accessibility Insights For Windows" or similar application
3. Start listening to all events
4. Press button "button1"
5. Observe thrown System.AccessViolationException

**Comment by elachlan** [comment]
@Olina-Zhang can your team test this please?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang can your team test this please?

Verified in the latest .Net 8.0 SDK build, it can reproduce.
![image](https://user-images.githubusercontent.com/26474449/226528652-2362bc6f-6a20-4f13-991d-4bde5fee0142.png)

**Comment by gc-maximloverov** [comment]
Hi, can you suggest a workaround? for example, a workaround like in the previous similar bug https://github.com/dotnet/winforms/issues/6965?

**Comment by merriemcgaw** [comment]
@dmitrii-drobotov do you happen to have a workaround you would suggest?

**Comment by dmitrii-drobotov** [comment]
@gc-maximloverov - unfortunately, I'm not able to find a workaround in this case, and as I understand, passing a non-empty `IRawElementProviderSimple[]` should work. As an alternative, I can suggest trying other UIA events to represent selection change. For controls with Selection pattern, we raise `UIA_SelectionItem_ElementSelectedEventId` with selected item's UIA Provider, for example:
https://github.com/dotnet/winforms/blob/ee9fe7b0e30fd80fbd938e47a15bac97212068be/src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs#L1926-L1932

Another option I see is to raise `UIA_SelectionItemIsSelectedPropertyId` changed event for item's UIA Provider. We do so for TreeView nodes:
https://github.com/dotnet/winforms/blob/ee9fe7b0e30fd80fbd938e47a15bac97212068be/src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs#L2343-L2347

There are also couple useful links to the documentation on how to correctly implement Selection and SelectionItem patterns: [Selection Control Pattern](https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-implementingselection), [SelectionItem Control Pattern](https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-implementingselectionitem).

Let me know if any of that works out for you or if you have additional questions. Thanks!

**Comment by gc-maximloverov** [comment]
@dmitrii-drobotov thanks, this alternative worked for us.
