### ISSUE TITLE
Issue involving GetPropertyItem / PropertyItems and Nikon cameras

### ISSUE THREAD

**Issue by rrose-github** [dotnet/winforms#8872]
When I attempt to retrieve EXIF tags for either the Artists/Authors (tag 0x013B) or Copyright tag 0x8298) from Nikon cameras, both GetPropertyItem and ProperyItems methods for System.Drawing.Image object fails to retrieve the information.  

I've tried it with both .NET 4.8 and .NET 7.0 with the same results.

GetPropertyItem will throw a "System.ArgumentException", while PropertyItems will just return the other EXIF tags.

I've encountered this issue with photographs taken using Nikon's D850, D5, D6 and Z9 cameras.  I have not encountered this issue with photographs taken with various Canon cameras.

FYI, Windows Explore property displays the information when you examine Properties on the photographs.  Also, I am able to retrieve the information by using Shell32.dll calls.

And FWIW, when you load and then save a photograph from a Nikon camera using either Photoshop or MS Paint, then the GetPropertyItem and PropertyItems methods will work properly.  Both of those apps must correct whatever the precise issue is when they save the image.

I've placed a sample Nikon photograph at https://app.box.com/s/wwltqsks3r24i8ugxb4ztmyh97hd22wn for testing purposes.

Here's a sample GetPropertyItem call that I've simplified down to the bare essentials:

```
   Const EXIF_ArtistName As UInt16 = &H13B

    Dim img As Bitmap
    Dim prop As System.Drawing.Imaging.PropertyItem
    Dim value As String

    img = New Bitmap(fileName)
    prop = img.GetPropertyItem(EXIF_ArtistName)  ' this statement will trigger an exception with a photograph from a Nikon camera
    value = System.Text.Encoding.UTF7.GetString(prop.Value, 0, prop.Len - 1)  ' remove trailing 00H character

```

**Comment by elachlan** [comment]
@ViktorHofer how do we add the test image to `System.Drawing.Common.TestData` so its available for tests?

**Comment by elachlan** [comment]
@rrose-github can you please provide the whole error/stack trace? `Image.GetPropertyItem` calls `Gdip.CheckStatus`, which checks the error code returned by `Gdip.GdipGetPropertyItemSize` and `Gdip.GdipGetPropertyItem` (both are generated via `LibraryImportGenerator`).

https://github.com/dotnet/winforms/blob/87ff94fd200859b9b01f2c8fed9803fd19d01d05/src/System.Drawing.Common/src/System/Drawing/Image.cs#L798-L826

https://github.com/dotnet/winforms/blob/87ff94fd200859b9b01f2c8fed9803fd19d01d05/src/System.Drawing.Common/src/System/Drawing/Gdiplus.cs#L86-L144

**Comment by ViktorHofer** [comment]
> @ViktorHofer how do we add the test image to System.Drawing.Common.TestData so its available for tests?

@elachlan feel free to submit a PR that adds it to the [runtime-assets repo](https://github.com/dotnet/runtime-assets/tree/main/src/System.Drawing.Common.TestData).

**Comment by rrose-github** [comment]
elachlan,

As requested, here's the output of the exception object when GetPropertyItem generates an exception.  The exception is thrown whenever the GetPropertyItem method is invoked for both the Artists/Authors (tag 0x013B) and Copyright tag 0x8298) tags.  The exception is the same for both.

{"Property cannot be found."}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2147024809
    HelpLink: Nothing
    InnerException: Nothing
    Message: "Property cannot be found."
    ParamName: Nothing
    Source: "System.Drawing.Common"
    StackTrace: "   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)" & vbCrLf & "   at System.Drawing.Image.GetPropertyItem(Int32 propid)" & vbCrLf & "   at EXIFtest.Program.UseSystemDrawing(String[]& filesList) in D:\Projects\EXIFtest\EXIFtest\Program.vb:line 126"
    TargetSite: {Void CheckStatus(Int32)}

**Comment by JeremyKuhne** [comment]
Thanks for reporting this. We're dependent on GDI+ for our imaging functionality and GDI+ is not taking changes. To get more robust EXIF support you'll want to use other Windows APIs directly (such as WIC) or use libraries that are built on the more modern imaging functionality such as [ImageSharp](https://sixlabors.com/products/imagesharp/).
