### ISSUE TITLE
How to add custom smart tag on .net6 WinForms in design mode?

### ISSUE THREAD

**Issue by idea-zone** [dotnet/winforms#8873]
### Environment

Microsoft Visual Studio Community 2022 (64 位) - Current
Version 17.5.2

### .NET version

.net 6.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

no 

### Issue description

I can do it in .net6: [Walkthrough: Adding Smart Tags to a Windows Forms Component](https://learn.microsoft.com/en-us/previous-versions/ms171829(v=vs.140)?redirectedfrom=MSDN)

Is There anywhere allow I add custom Smart Tag in .NET 6 winfroms Application?

### Steps to reproduce

[Walkthrough: Adding Smart Tags to a Windows Forms Component](https://learn.microsoft.com/en-us/previous-versions/ms171829(v=vs.140)?redirectedfrom=MSDN)

**Comment by idea-zone** [comment]
@merriemcgaw  yes ,it's what i want. Is there some way to add custom smart tag on .net6 Winfroms in desigan Mode?

**Comment by merriemcgaw** [comment]
@idea-zone there is indeed a way to create DesignerAction Panes in .NET 6 and beyond. I've assigned this to @KlausLoeffelmann because what's missing is the documentation about how to do it. Hopefully we will be able to both unblock you, and get the docs appropriately updated to indicate that there is a new approach in .NET 6.

**Comment by idea-zone** [comment]
> @idea-zone there is indeed a way to create DesignerAction Panes in .NET 6 and beyond. I've assigned this to @KlausLoeffelmann because what's missing is the documentation about how to do it. Hopefully we will be able to both unblock you, and get the docs appropriately updated to indicate that there is a new approach in .NET 6.

Thanks you very much.

**Comment by KlausLoeffelmann** [comment]
I just checked in a new sample app in the Designer Extensibility Repo:

https://github.com/microsoft/winforms-designer-extensibility/tree/main/Samples/TypeEditor/Dotnet/TileRepeater_Simplified

The Action List implementation [you find here](https://github.com/microsoft/winforms-designer-extensibility/tree/main/Samples/TypeEditor/Dotnet/TileRepeater_Simplified/TileRepeater.Controls.Simplified/Designer).

Take a look at that - it demos the easiest way to implement Action Lists.
**Note**: This simplified version of the demo works as long as you do not need to kick of a Type Editor Dialog from the Action List (or the Property Browser - the approach is the same). If the latter is the case, please refer to [this Blog-Post](https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/), which describes in detail how to develop custom controls for the Out-Of-Process WinForms Designer, whose Control Designers use custom Type Editors.

**Comment by KlausLoeffelmann** [comment]
Tagging @adegeo FYI for this thread.
