### ISSUE TITLE
Question/Documentation In VB Project Properties under Package I can set Release Notes but no way to retrieve

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#8880]
### .NET version

N/A

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

N/A

### Issue description

I can't find any way to retrieve Release Notes <PackageReleaseNotes> at runtime. I can get Title, Version, Description and the rest of the information.

### Steps to reproduce

Add the following lines to .vbprog file, you can use Visual Studio
```
<PackageReleaseNotes>Requires Windows 10 or later and .Net 7.0 of later
</PackageReleaseNotes>
```
![image](https://user-images.githubusercontent.com/12789369/226584159-757b4e27-25ed-4d5a-bbf6-bbd82b712bc4.png)

The description says I can use in UI but I don't see it available at runtime.

**Comment by KlausLoeffelmann** [comment]
> Our thought is that release notes would be for packaging purposes, rather than runtime purposes.

I would think so, too.
@melytc, you might know it or someone on your team might know this - can you confirm?

**Comment by melytc** [comment]
Not really, it doesn't get to be on the assembly, so one cannot access it. It's used to build the package and to provide info to the consumers. The description is referring that the package metadata is used to populate interfaces like the VS Package Manager or the NuGet package. Here's some documentation: https://learn.microsoft.com/en-us/nuget/reference/nuspec

**Comment by KlausLoeffelmann** [comment]
Thanks!!
