### ISSUE TITLE
GetLineFromCharIndex return an error result

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#8885]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/GetLineFromCharIndex-return-an-error-res/10314554)._

---
[severity:I'm unable to use this version]
Pasting a hyperlink into a rich text box will cause the characters after the hyperlink to return an error result when using GetLineFromCharIndex

![spell_checker.png](https://aka.ms/dc/image?name=Bc4918333086944a9a6af5a08fdc774a0638148746714906418_spell_checker.png&tid=c4918333086944a9a6af5a08fdc774a0638148746714906418)

---
#### Feedback Bot on 3/20/2023, 10:42 AM: 

(private comment, text removed)
#### Melon Wang [MSFT] on 3/21/2023, 03:22 PM: 

(private comment, text removed)
#### Brian Zhao on 3/22/2023, 10:17 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MelonWang1** [comment]
**.NET Core build:**

.NET SDK 8.0.100-preview.4.23171.23

**Did it work in .NET Framework?**

No, but behavior is difference. It seems that the line number returned is wrong.

**Did it work in any of the earlier releases of .NET Core or .NET 5+?**

No, it also repro on .NET 3.1 & 5.0 & 6.0 & 7.0.
.NET 3.1 behavior is same as framework app.
![3 1](https://user-images.githubusercontent.com/94418985/226833211-5d80649a-d11f-4982-a8eb-8c978e308a21.png)

**Repro Steps:**

  Please see h[ttps://github.com/endruz/GetLineFromCharIndexIssueDemo](https://github.com/endruz/GetLineFromCharIndexIssueDemo)

**Actual result:**
In Core app, It seems that Text has some problems.
In Framework app, It seems that the line number returned is wrong.
![Untitled111](https://user-images.githubusercontent.com/94418985/226835705-d074abba-f243-49f1-bfca-54dec0831421.png)

**Expected result:**
![Untitled](https://user-images.githubusercontent.com/94418985/226835486-79b77ebd-079e-447b-9b66-2ecb638b2ea3.png)

**Comment by dreddy-work** [comment]
We have some examples available at [LoadOlderRichEditControl](https://github.com/dotnet/winforms/blob/d25d6a71f703fe45b9408d26e886462f0da5cd69/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs#L10787) that demonstrate how to load an older version of RichEdit in Winforms to support existing applications, given that the current result is due to the use of a newer RichEdit version.
