### ISSUE TITLE
Win Forms DataGridView doesn't auto generate columns when items in the bound list are declared the wrong way

### ISSUE THREAD

**Issue by TimAtMicro** [dotnet/winforms#8895]
### Description

Columns in the DataGridView control are not auto generated when data binding if you declare the bound items the "wrong" way.

If the items in the list define property members with getters and setters, columns are created.

If the items in the list define public data members instead, no columns are generated.

### Reproduction Steps

List<T> listOfT = new();
BindingSource bindingSource = new();
bindingSource.DataSource = listOfT;
dataGridView1.AutoGenerateColumns = true;
dataGridView1.DataSource = bindingSource;

=================================

SCENARIO 1

If T is declared as -

public class T
{
    public int Field1 { get; set; }
}

then a column will be auto generated in the DataGridView.

=================================

SCENARIO 2

If T is declared as -

public class T
{
    public int Field1;
}

no columns will be auto generated.

=================================

It took a while to work this one out! I was able to drill down into DataGridView.DataConnection.props and see they were being populated in scenario 1, but not in scenario 2, which then caused no columns to be auto generated. I'm guessing the reflection code that is part of the generation of props is flawed - doesn't generate props for fields defined as in scenario 2.

### Expected behavior

Columns should be auto generated.

### Actual behavior

Columns are not auto generated.

### Other information

.NET Framework 4.7.2

**Comment by elachlan** [comment]
@TimAtMicro the team won't do anything if this is in .net framework and not .NET.

Have you tried it in .NET6?

If the behavior was to change how would you expect it to work? Would both properties and fields be populated as columns? Or only properties first and if no properties are present, then fields?

**Comment by TimAtMicro** [comment]
Hi Lachlan, 

I haven't tried it in .NET 6. Hopefully the behaviour is different (more intuitive), but it's not practical to update our app atm for a small UI issue with a workaround. We are talking 23 assemblies (main + dependencies). 

Basically, I was doing some refactoring (9k + lines of code) and came across a number of classes like this, used to bind List<T> collections to DaraGridViews - 

[Serializable] 
public class ServicedItemSummary 
{ 
public int ServicedItemId { get; set; } 
public int OfficeId { get; set; } 
public string ProductCode { get; set; } 
public string SerialNumber { get; set; } 
public string Config { get; set; } 
public DateTime? ManufacturedDate { get; set; } 
} 

I changed them to this - 

[Serializable] 
public class ServicedItemSummary 
{ 
public int ServicedItemId; 
public int OfficeId; 
public string ProductCode; 
public string SerialNumber; 
public string Config; 
public DateTime? ManufacturedDate; 
} 

as that's clearer / cleaner to read (gets rid of the redundant info "{ get; set:}" that is distracting from the relevant info on each line, as we already know a public field can be got and set)... A class with say 20+ props/fields becomes much easier to read at a glance. 

And in possibly all other scenarios apart from the reflection API, fields are functionally equivalent... 

But then of course all the bound DataGridViews stopped working. I was surprised this innocent looking change broke data binding, so for me, definitely not intuitive. 

I realise the underlying issue is the reflection API treats them differently. But still, it's a bit of a trap for an unsuspecting programmer and not easy to work out why binding is not working. You just end up with empty rows in your grid, no columns. 

The programmer who wrote this app has in some circumstances relied on this behaviour to hide columns on the UI, by declaring them as properties. So this behaviour has encourage/enabled some very fragile, dangerous code and a maintenance nightmare. But I digress... 

To answer your question , I would expect the DataGridView to create columns for all public members, properties and fields. 

Thanks.

**Comment by elachlan** [comment]
@Olina-Zhang is your team able to reproduce this issue?

**Comment by TimAtMicro** [comment]
Yes. Want me to put together a sample project and send it to you?

**Comment by elachlan** [comment]
@TimAtMicro you are welcome to put together a small project and link it here. That would be very helpful.

**Comment by TimAtMicro** [comment]
Hi - attached is a 61 KB ZIP file containing a sample project that demonstrates the problem here for me.

**Comment by elachlan** [comment]
@TimAtMicro can you please add it to the issue via github? Emails do not add attachments.

**Comment by TimAtMicro** [comment]
Hi - I sent through the sample as a ZIP attachment, but not sure if that'll get blocked. 

Here it is again as a .zi_ file - please rename to .zip. 

Or if I need to send it to you another way please let me know how. Thanks.

**Comment by TimAtMicro** [comment]
[DGV Binding.zip](https://github.com/dotnet/winforms/files/11084599/DGV.Binding.zip)

**Comment by TimAtMicro** [comment]
Done 👍

**Comment by MelonWang1** [comment]
@elachlan Test this issue use [DGV.Binding.zip](https://github.com/dotnet/winforms/files/11087157/DGV.Binding.zip) in .Net framework 4.8.1 and .Net Core different versions(.NET 8.0--3.1), all have same result: If the items in the list define public data members instead, build and run, no columns are generated.
![8895](https://user-images.githubusercontent.com/94418985/228177746-a6889f02-39c2-4b98-a741-66c088bbe9b4.png)

**Comment by merriemcgaw** [comment]
Thanks so much for the detailed report! I see what your concern is. However, fundamentally WinForms has always worked from Properties not fields. It may or may not even be feasible to know when to pull in fields as opposed to Properties - that would change the existing behavior for people. Given that this has always been the behavior in WinForms and the risk of regressing existing behaviors is so high, we're not going to pursue this feature and I'm going to close this issue.

**Comment by TimAtMicro** [comment]
Hi Merrie. No problem. I understand your reasoning. It's a bit late in the day to be changing behaviour. 

I did find this very counter-intuitive though. I would expect the grid to display whatever type of object you give it to the best of it's ability, in full - i.e. display all public fields, even snapshots of calculated values returned from functions, because as you know property values can be calculated and change over time anyway. Filtering on an undocumented criteria confused me! 

Thanks for taking the time to consider this. Cheers, Tim.

**Comment by elachlan** [comment]
@TimAtMicro for what its worth, its probably better to use properties so you can use [INotifyPropertyChanged](https://learn.microsoft.com/en-us/dotnet/api/System.ComponentModel.INotifyPropertyChanged?view=net-7.0). This allows you to better use the class in databinding scenarios.

**Comment by TimAtMicro** [comment]
Thanks Lachlan - good tip, appreciated!
