### ISSUE TITLE
WinForms should test for binary serialization

### ISSUE THREAD

**Issue by ericstj** [dotnet/winforms#890]
Once you decide which types need to remain serializable #889 you need to test the remaining types for binary serialization.

These types should be tested to ensure they are serializable today, remain serializable in the future, and that they can round-trip to desktop.

Tests will likely involve consuming in binary payloads in test data and consuming this in tests.  You'll also likely want to annotate members that are forzen for serialization purposes.  @ViktorHofer did a lot of this work for CoreFx and may be able to provide some pointers.

This work should be semi-parallelizable with #889 since you know you have some types already that need to stay Serializable (EG: ImageList).

**Comment by merriemcgaw** [comment]
@dreddy-work getting this on your radar for 3.0
