### ISSUE TITLE
Add ListBox Control Test to WinformsControlsTest

### ISSUE THREAD

**Issue by dkazennov** [dotnet/winforms#8904]
As @Tanya-Solyanik proposed we need a separate form for ListBox Control Test to WinformsControlsTest.

This new feature would be for internal purposes only and would not affect UI controls.

**Comment by Amy-Li03** [comment]
In latest WinformsControlsTest, we can see the test for CheckedListBox and ListBoxes with DrawMode.Normal, DrawMode.OwnerDrawFixed and DrawMode.OwnerDrawVariable, they work well.
![image](https://user-images.githubusercontent.com/62929087/230530402-5632c94b-c5de-4fd1-bf36-f2e4706afefa.png)

**Comment by Olina-Zhang** [comment]
Switch to Winforms release/8.0-Preview4 branch from this repo, WinformsControlsTest app contains ListBoxs with DrawMode test, has the same result as above test displayed.
