### ISSUE TITLE
Since Windows 11 build 22621.1344 it's no longer possible to middle click on NotifyIcon

### ISSUE THREAD

**Issue by ptdev** [dotnet/winforms#8914]
### .NET version

.NET7

### Did it work in .NET Framework?

Yes

### Issue description

Ever since Microsoft released the so called "Moment 2 Update" for Windows 11, which is build 22621.1344 (but the issue is still present on the current build 22621.1413), it's no longer possible to distinguish between middle-click and left-click when clicking on a tray icon generated by System.Windows.Forms.NotifyIcon.

Before the update, middle clicking would correctly trigger a "middle click" event. After the update, middle clicking the tray icon instead triggers a left-click event.

This breaks any application that may be using middle click to perform any actions.

This is most likely an issue related with Windows and not Winforms as it's also present on other libraries that use tray icons on both WPF and WinUI.

I was recommended by a Microsoft Twitter account to report this on the feedback hub, which I have done here: https://aka.ms/AAk0sn4

Unfortunately, there has been no feedback from Microsoft regarding this issue, so I'm posting this here as it affects a native WinForms element (NotifyIcon), so perhaps the developers/maintainers of this project have better ways to reach Microsoft regarding this issue.

### Steps to reproduce

1. Create an empty WinForms app and drag a NotifyIcon to it. 
2. Go into the NotifyIcon properties and set a test icon 
3. Edit Form1.cs to contain the following code:

```
public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            notifyIcon1.MouseClick += Icon_MouseClick;
        }

        private void Icon_MouseClick(object? sender, MouseEventArgs e)
        {
            Debug.WriteLine(e.Button.ToString());
        }
    }

```

4. Use your mouse to left-click, right-click and middle-click the tray icon and watch the Debug window.
5. Note that left and right clicks work as intended. But the middle click triggers the left click instead.

This works as intended on windows 10 (tested on a VirtualBox VM) and on any Windows 11 version before the builds mentioned above.

**Comment by elachlan** [comment]
@Olina-Zhang could your team please test this?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang could your team please test this?

This issue can be reproduced on Windows 11 build 22621, not Windows 10. Left and right clicks work as intended. But the middle click triggers the left click instead.
![image](https://user-images.githubusercontent.com/26474449/228771011-ce42de3f-f8e4-4275-b900-f090ecab1702.png)

**Comment by dreddy-work** [comment]
@Olina-Zhang, can you see if there is an issue on Windows side for this?

**Comment by merriemcgaw** [comment]
We have an internal feedback ticket in the Windows Feedback hub. I have just voted it up. This was a specific Windows change as they redesigned the System Tray. You should file another feedback ticket or see if you can find other feedback items about this issue. There is nothing we can do on the WinForms side of this unfortunately.
