### ISSUE TITLE
Still issue with layouts missing on toolbox and not rendering on designer.

### ISSUE THREAD

**Issue by djinnet** [dotnet/winforms#8931]
### Environment

Microsoft Visual Studio Community 2022
Version 17.4.2
VisualStudio.17.Release/17.4.2+33122.133

### .NET version

.Net 7

### Did this work in a previous version of Visual Studio and/or previous .NET release?

It still works in .Net Framework, but I would like to assumed that it have never worked in core and then .net 5+ version.

### Issue description

I managed to find this issue that was made for 3 years ago: https://github.com/dotnet/winforms/issues/2842
and I do not think that tablelayoutpanel or flowlayoutpanel has been available for core or .net 5+ version, and I could not find any more information for why they haven't been available when it was expected that they should have been available for today's designer.
The fact that it still is same issue today after three years in newer version (especially in .net 5+) is concerning. So I hope it is acceptable that I am reporting that this is still an on-going issue and brought to the winform designer team's attention. 
So at least that they are being aware of it, even if they have many things on their plate.

### Steps to reproduce

Create empty winfroms project in .net 7 version. Do not choose the framework one.
Try to find TableLayoutPanel or Flowtablelayout in toolbox window.

**Comment by kirsan31** [comment]
![image](https://user-images.githubusercontent.com/17767561/229370537-45c246b5-d8c5-4004-86d3-043c435cbc94.png)
🤔

**Comment by djinnet** [comment]
@kirsan31 
Before update:
![image](https://user-images.githubusercontent.com/9974608/229371919-10d6135f-2da8-4d51-b4cc-44b1a772e511.png)

Hmm... I noticed my visual studio version is outdated compared to the version that you have. So I tried to verified by updating the version.

The result: It doesn't work. I even tried to search within the search field in the toolbox. Nothing shows up. I have also tried to create an new project just to check, but no. It is still the same issue. 

After update: 
![image](https://user-images.githubusercontent.com/9974608/229372934-f682687a-723a-41ca-90ea-197116a41cef.png)

Can you verify if your newcreated project looks like this? 
![image](https://user-images.githubusercontent.com/9974608/229373107-32a9e584-2a57-4022-96e2-1da7d2b9d071.png) 🤔

**Comment by kirsan31** [comment]
> Can you verify if your newcreated project looks like this?

Yea - the same.

Looks like it's something wrong with you VS installation... I can only advise to check WinForms Designer settings and try to reset toolbox:
![image](https://user-images.githubusercontent.com/17767561/229373705-5bd8c60c-602f-4464-b066-cd697c151a05.png)

**Comment by djinnet** [comment]
Actually the very second that ya replied back; I managed to solved it by reset the toolbox by accidentally misclick. I didnt realized that was the major issue. One would had assumed that the toolbox would reset every time someone is created an new project. Doesnt look like the case tho.
Anyhow I am just super glad to know that it works now. So thank you very much, @kirsan31. 😄 

I'll marked this as close since it wasn't the issue that I thought it was in the first place. And it is solved. Thanks a lot!
