### ISSUE TITLE
Align and Anchor editors in PropertyGrid do not fill whole width 

### ISSUE THREAD

**Issue by dmitrii-drobotov** [dotnet/winforms#8933]
### .NET version

8.0.0-preview.4.23177.1

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Confirmed that it works in .NET 6 and 7

### Issue description

Anchor and Align editors' UI in PropertyGrid is not filled to the whole width of container.

#### Current Behavior
.NET 8:
![Screenshot 2023-04-03 174935](https://user-images.githubusercontent.com/102954094/229567686-d6521eb5-a8b2-4a0e-ae5b-8c349a9f8096.png)
![Screenshot 2023-04-03 142235](https://user-images.githubusercontent.com/102954094/229567814-4540ce25-33eb-4306-b6b5-354bae5e1da1.png)

#### Expected behavior
.NET 7 and .NET Framework:

![Screenshot 2023-04-03 175456](https://user-images.githubusercontent.com/102954094/229567851-215c8cb6-990c-4129-86db-3ee3b46c8b23.png)
![Screenshot 2023-04-03 142322](https://user-images.githubusercontent.com/102954094/229567863-077d4e21-1023-4f9f-8e3d-ca4e1377e99c.png)

### Steps to reproduce

Issue is visible if PropertyGrid is wide enough (at least 400px) and doesn't seem to be affected by DPI settings. Sample app: 
[AlignAnchorEditorsTest.zip](https://github.com/dotnet/winforms/files/11140356/AlignAnchorEditorsTest.zip)

**Comment by dreddy-work** [comment]
Seems so. Will take a look this week.

**Comment by dmitrii-drobotov** [comment]
> Is this runtime only or design time as well?

It's both, I added a copy of AnchorUI to a separate app, and have the same result in design time. 
.NET 8: 
![image](https://user-images.githubusercontent.com/102954094/229580143-e151e20e-5424-46e5-bf29-2cde20c3dfa6.png)
 
.NET 7:
![image](https://user-images.githubusercontent.com/102954094/229580208-9582f34a-fd8d-4d2e-9b5b-43660f9b8cb9.png)

Control's code is the same in both versions.

**Comment by Amy-Li03** [comment]
Verified this on .NET 8.0.100-preview.5.23253.14, issue was fixed, Align and Anchor editors in PropertyGrid filled whole width.
![image](https://user-images.githubusercontent.com/62929087/236098804-a4273865-9e97-483e-a15d-457d61151d17.png)
![image](https://user-images.githubusercontent.com/62929087/236099102-12073523-7dee-4802-9fa8-6e12a9bc2b56.png)

**Comment by Olina-Zhang** [comment]
Verified it in VS insertion PR with .Net 8 Preview 4 test pass build: 8.0.0-preview.4.23253.2, Align and Anchor editors in PropertyGrid runtime have a good scale on HDPI machine, as above testing result displayed.
