### ISSUE TITLE
[API Proposal]: Allow ControlCollection.AddRange to use params keyword.

### ISSUE THREAD

**Issue by ALiwoto** [dotnet/winforms#8938]
### Background and motivation

Currently [Control.ControlCollection.AddRange](https://github.com/dotnet/winforms/blob/a37c1817d3f965d9a8bdd3d89fd0b98609715e84/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs#L153) method is accepting an array of `Control`, this means each time that we want to add multiple controls at once, we have to make a new array. By using `params` keyword using this method will become easier.

### API Proposal

- Add `params` keyword to all collection `AddRange` methods that don't already have it.

```csharp
namespace System.Windows.Forms;

public class Control
{
    public class ControlCollection
    {
        public virtual void AddRange(params Control[] controls);
    }
}
```

Likewise we want to update our other collections that have an [`AddRange`](https://github.com/dotnet/winforms/pull/8928#issuecomment-1495242738):

``` C#
// Note that parameter names are left as they currently are.

System.ComponentModel.Design.DesignerActionListCollection.AddRange(params DesignerActionList[] value)
System.Windows.Forms.AutoCompleteStringCollection.AddRange(params string[] value)
System.Windows.Forms.ComboBox.ObjectCollection.AddRange(params object[] items)
System.Windows.Forms.Design.Behavior.BehaviorServiceAdornerCollection.AddRange(params Adorner[] value)
System.Windows.Forms.Design.Behavior.GlyphCollection.AddRange(params Glyph[] value)
System.Windows.Forms.ImageList.ImageCollection.AddRange(params Image[] images)
System.Windows.Forms.ListBox.IntegerCollection.AddRange(params int[] items)
System.Windows.Forms.ListBox.ObjectCollection.AddRange(params object[] items)
System.Windows.Forms.ListView.ListViewItemCollection.AddRange(params ListViewItem[] items)
System.Windows.Forms.ListView.ColumnHeaderCollection.AddRange(params ColumnHeader[] values)
System.Windows.Forms.ListViewGroupCollection.AddRange(params ListViewGroup[] groups)
System.Windows.Forms.ListViewItem.ListViewSubItemCollection.AddRange(params ListViewSubItem[] items)
System.Windows.Forms.ListViewItem.ListViewSubItemCollection.AddRange(params string[] items)
System.Windows.Forms.TabControl.TabPageCollection.AddRange(params TabPage[] pages)
System.Windows.Forms.ToolStripItemCollection.AddRange(params ToolStripItem[] toolStripItems)
System.Windows.Forms.ToolStripPanel.ToolStripPanelRowCollection.AddRange(params ToolStripPanelRow[] value)
System.Windows.Forms.TreeNodeCollection.AddRange(params TreeNode[] nodes)

```

### API Usage

```csharp
this.Controls.AddRange(this.BtnControl1, this.BtnControl2);
```

### Risks

No known risks.

### Will this feature affect UI controls?

- No, VS Designer doesn't need to support this feature.
- The impact will be easier use of this method by users.
- No, this feature doesn't need to be localized.

**Comment by JeremyKuhne** [comment]
This is great, we should expand it to list the other collections where we have an `AddRange()`. @ALiwoto you can find the other ones by looking through the `PublicAPI.shipped.txt` file, would you be able to add the others? All you need is the API surface area. I've added one to the summary. If you can't, that's fine, I'll get to it when I have some time free.

**Comment by ALiwoto** [comment]
@JeremyKuhne Sure, should I make another PR after finding them? Or I can just push to my current fork?

**Comment by JeremyKuhne** [comment]
@ALiwoto listing them here is the priority. You can just expand the existing PR, but we won't be able to take it until we've got this approved by the .NET API review board. Please tag me when you think you've got everything listed here and I'll work on getting the official approval.

**Comment by elachlan** [comment]
Awesome! Great idea, minimal impact, and improves usability.

**Comment by ALiwoto** [comment]
@JeremyKuhne 
Here is the list I found:

  - [System.ComponentModel.Design.DesignerActionListCollection.AddRange(DesignerActionList?[] value)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionListCollection.cs#L28)
  - [System.Windows.Forms.Design.Behavior.BehaviorServiceAdornerCollection.AddRange(Adorner[] value)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/AdornerCollection.cs#L99)
  - [System.Windows.Forms.Design.Behavior.GlyphCollection.AddRange(Glyph[] value)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/GlyphCollection.cs#L60)
  - [System.Windows.Forms.ListBox.AddRange(object[] items)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ObjectCollection.cs#L173)
  - [System.Windows.Forms.ListViewGroupCollection.AddRange(ListViewGroup[] groups)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs#L153)
  - [System.Windows.Forms.ListViewGroupItemCollection.AddRange(ListViewItem[] items)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupItemCollection.cs#L50)
  - [System.Windows.Forms.AutoCompleteStringCollection.AddRange(string[] value)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs#L73)
  - [System.Windows.Forms.ListView.ListViewItemCollection.AddRange(ListViewItem[] items)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.cs#L250)
  - [System.Windows.Forms.ListView.ColumnHeaderCollection.AddRange(ColumnHeader[] values)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ListView.ColumnHeaderCollection.cs#L273)
  - [System.ComponentModel.Design.DesignerActionListCollection.AddRange(DesignerActionList?[] value)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionListCollection.cs#L28)
  - [System.Windows.Forms.ComboBox.ObjectCollection.AddRange(object[] items)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs#L179)
  - [System.Windows.Forms.Design.ControlDesigner.DesignerControlCollection.AddRange(Control[] controls)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DesignerControlCollection.cs#L37)
  - [System.Windows.Forms.ListBox.IntegerCollection.AddRange(int[] items)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ListBox.IntegerCollection.cs#L162)
  - [System.Windows.Forms.ImageList.ImageCollection.AddRange(Image[] images)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs#L378)
  - [System.Windows.Forms.ListView.ListViewNativeItemCollection.AddRange(ListViewItem[] values)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs#L126)
  - [System.Windows.Forms.ToolStripPanel.ToolStripPanelRowCollection.AddRange(ToolStripPanelRow[] value)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelRowCollection.cs#L54)
  - [System.Windows.Forms.ToolStripItemCollection.AddRange(ToolStripItem[] toolStripItems)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs#L118)
  - [System.Windows.Forms.ListViewItem.ListViewSubItemCollection.AddRange(ListViewSubItem[] items)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs#L137)
  - [System.Windows.Forms.ListViewItem.ListViewSubItemCollection.AddRange(string[] items)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs#L154)
  - [System.Windows.Forms.TreeNodeCollection.AddRange(TreeNode[] nodes)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs#L263)
  - [System.Windows.Forms.Control.ControlCollection.AddRange(Control[] controls)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs#L153)
  - [System.Windows.Forms.TabControl.TabPageCollection.AddRange(TabPage[] pages)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs#L141)
  - [System.Windows.Forms.ToolStripPanelRow.ToolStripPanelRowControlCollection.AddRange(Control[] value)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs#L91)
  - [System.Windows.Forms.Design.CustomMenuItemCollection.AddRange(ToolStripItem[] value)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CustomMenuItemCollection.cs#L32)

24 in total.


<hr/>

I also found about [System.Windows.Forms.NonNullCollection&lt;T&gt;.AddRange(IEnumerable&lt;T&gt; items)](https://github.com/dotnet/winforms/blob/a13c2fdfd66fefc29b355ebafde9242f7f476c18/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/NonNullCollection.cs#L74):

```cs
/// <summary>
///  Adds the items in <paramref name="items"/> to the collection.
/// </summary>
public void AddRange(IEnumerable<T> items)
```

But the issue with it is that it takes `IEnumerable<T>` as argument, so we can't use `params` keyword for it (Perhaps we can overload it?)

**Comment by elachlan** [comment]
`NonNullCollection` is `Internal`. So we can make a breaking change if it makes sense.

**Comment by JeremyKuhne** [comment]
> Here is the list I found:

Thanks @ALiwoto. I've double checked and removed the internal ones. I've updated the proposal with the complete list.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Windows.Forms;

public partial class Control
{
    public partial class ControlCollection
    {
        // Existing signature:
        // public virtual void AddRange(Control[] controls);
        public virtual void AddRange(params Control[] controls);
    }
}
```

**Comment by elachlan** [comment]
@ALiwoto did you want to do the PR to implement it?

**Comment by ALiwoto** [comment]
@elachlan 
> did you want to do the PR to implement it?

Yes.

@JeremyKuhne can I commit the changes to my current PR? Or I have to revert the [last commit ](https://github.com/dotnet/winforms/pull/8928/commits/caf5b7aebd3890cc4990b238803610cb32a83daf) from it first?

**Comment by JeremyKuhne** [comment]
@ALiwoto you should probably change all of these in one PR. You can do it in your existing [PR](https://github.com/dotnet/winforms/pull/8928). Note, however, that you don't add to the `shipped` API file. There is an autofix for adding the changes to the `unshipped` file. Just build in VS and you can use the lightbulb to add them. You need to build both release and debug.

**Comment by John-Qiao** [comment]
Verified this issue in feature/9.0 branch, the params keyword is added to arguments of ControlCollection.AddRange method now, so closed it.
![8938-testresult](https://github.com/dotnet/winforms/assets/45864985/3fcf5aef-1056-47e1-811c-73157f13eca6)
