### ISSUE TITLE
PerMonitorV2 - Opening a dialog whose owner is on a secondary screen results in broken scaling in .NET 7+

### ISSUE THREAD

**Issue by TheLeftExit** [dotnet/winforms#8946]
### .NET version

.NET 7.0
.NET 8.0 Preview 2

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it worked in .NET 6 and earlier.

### Issue description

If a form is opened as a dialog, and the dialog's owner is located on a monitor whose DPI scaling factor doesn't match the primary monitor, the dialog will either be scaled incorrectly on initial scaling, or start scaling incorrectly after it has been moved to a different screen. The issue only occurs in .NET 7 and later. Changing [`ShowInTaskbar`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.showintaskbar)/[`StartPosition`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.startposition) of the dialog seems to produce different (but still incorrect) behavior.

I attached a project that can be used to reproduce the issue, plus 4 videos that demonstrate various side effects. These different effects occur after following *the same replication steps* in different monitor/form configurations. The videos demonstrate correct behavior in .NET 6, and its deterioration as the project is upgraded to .NET 7 and .NET 8 Preview 2.

[WinFormsApp19.zip](https://github.com/dotnet/winforms/files/11172134/WinFormsApp19.zip)
<details>
<summary>Main100_DefaultProperties</summary>

https://user-images.githubusercontent.com/47351802/230427392-03372cc2-2cef-4585-a5ae-e3eef2cdb452.mp4
</details>
<details>
<summary>Main200_DefaultProperties</summary>

https://user-images.githubusercontent.com/47351802/230427985-42082230-3b55-4178-8db7-7b3198d711b2.mp4
</details>
<details>
<summary>Main100_TaskbarAndPositionModified</summary>

https://user-images.githubusercontent.com/47351802/230428166-95fbddfe-355c-47f5-9806-3e74ea5c31e7.mp4
</details>

<details>
<summary>Main200_TaskbarAndPositionModified</summary>

https://user-images.githubusercontent.com/47351802/230428274-631bcbaf-d306-43b3-a424-ed4053121f38.mp4
</details>

### Steps to reproduce

 - Prerequisite: ensure the system has two monitors with different scaling settings. Reboot the system.
1. In Visual Studio 2022, create a new project with the Windows Forms App template. Select .NET 7.
2. In the form designer, add a button to the form. Configure this button to launch another instance of the main form using the `ShowDialog` method: `button1.Click += (sender, e) => { using (var form = new Form1()) form.ShowDialog(); };`.
3. Add `<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>` to the project file.
4. Run the project.
5. Move the main form to the secondary monitor and click on the button.
6. Move the newly opened dialog to the secondary monitor.
7. **The button's bounds are not scaled.**

**Comment by dreddy-work** [comment]
Thanks you @TheLeftExit for details and sample. I will get this prioritized for upcoming preview release.

**Comment by Eudora-Li01** [comment]
Verified this on .NET 8.0.100-preview.5.23274.2, issue was fixed, the dialog scaled well on the primary monitor and second monitor while switching dialog between monitors.

**Comment by John-Qiao** [comment]
Verified this on .NET 8.0 Preview 5.0 TP build: 8.0.100-preview.5.23276.4, issue was fixed as same as above result.

**Comment by Amy-Li03** [comment]
Verified this on .NET 8.0 TP build: 8.0.100-preview.5.23276.4 issue was fixed, test result is same as above video.
