### ISSUE TITLE
[API Proposal] System.Drawing.Drawing2D.GraphicsPathIterator.CopyData spanify

### ISSUE THREAD

**Issue by wstaelens** [dotnet/winforms#8954]
### Background and motivation

When converting graphicsPaths I'm iterating over a lot of subpaths.

```
for (int i = ...
{
    // ...
    var subPathPoints = new GDIP.PointF[cnt];
    var subPathTypes = new byte[cnt];
    pathIterator.CopyData(ref subPathPoints, ref subPathTypes, startIndexSubPath, endIndexSubPath);
 } 
``` 

I'd like rent the subPathPoints and subPathTypes from an ArrayPool. Because the arraypool would give me larger arrays, I should need to use Spans and slice them to the actual size.

_original question:_ Can a `CopyData` overload using Spans be added?

### API Proposal

``` C#
namespace System.Drawing.Drawing2D;

public class GraphicsPathIterator
{
    // Existing API (note that the `ref` is completely unnecessary)
    public int Enumerate(ref PointF[] points, ref byte[] types);
    public int CopyData(ref PointF[] points, ref byte[] types, int startIndex, int endIndex);

    // Proposed
    public int Enumerate(Span<PointF> points, Span<byte> types);
    public int CopyData(Span<PointF> points, Span<byte> types, int startIndex, int endIndex);
}
```

### API Usage

```csharp
pathIterator.CopyData(pointsSpan, pathTypesSpan, startIndexSubPath, endIndexSubPath);
```

### Alternative Designs

None

### Risks

None

### Will this feature affect UI controls

No

Only impact is performanceboost and less allocations! 😄

**Comment by elachlan** [comment]
@wstaelens You should format this as an API proposal. The team will explain a bit more about the process. I don't see any issues with adding span overloads.

https://github.com/dotnet/winforms/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml

**Comment by wstaelens** [comment]
Updated the template. Thanks for pointing out.

**Comment by wstaelens** [comment]
@JeremyKuhne sounds fine for me!

**Comment by elachlan** [comment]
@wstaelens I think GraphicsPath was spanified for .net9. If you could review it and let us know of any suggestions that would be great.

**Comment by KrzysztofCwalina** [comment]
Should the source span of the copy method be read-only?

**Comment by JeremyKuhne** [comment]
> Should the source span of the copy method be read-only?

Both of the spans are targets from the `GraphicsPath`. The existing API is really misleading with the `ref`.

**Comment by terrajobst** [comment]
Reviewed and approved offline.

**Comment by elachlan** [comment]
@JeremyKuhne can we close this or is there more to do?

**Comment by JeremyKuhne** [comment]
We're good here now I think. Just forgot to close.
