### ISSUE TITLE
Fix ELEMDESC native interop definition

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#896]
This is a follow-up issue to PR #818 where it was noted ([link to comment](https://github.com/dotnet/winforms/pull/818#discussion_r276114126)) that the definition of `ELEMDESC` that WinForms uses seems to be wrong.

Currently the definition is embedding the `TYPEDESC` by reference (it was a class before, so the interop rules should already have been embedding it as a pointer before PR #818)
```c#
public unsafe struct tagELEMDESC {
    public NativeMethods.tagTYPEDESC* tdesc;
    public NativeMethods.tagPARAMDESC paramdesc;
}
```
while the definition of [ELEMDESC](https://docs.microsoft.com/en-us/windows/desktop/api/oaidl/ns-oaidl-tagelemdesc) and [TYPEDESC](https://docs.microsoft.com/en-us/windows/desktop/api/oaidl/ns-oaidl-typedesc) on msdn is
```C++
typedef struct tagELEMDESC {
  TYPEDESC tdesc;
  PARAMDESC paramdesc;
} ELEMDESC, *LPELEMDESC;

typedef struct tagTYPEDESC {
  union {
    struct tagTYPEDESC  *lptdesc;
    struct tagARRAYDESC *lpadesc;
    HREFTYPE            hreftype;
  } DUMMYUNIONNAME;
  VARTYPE vt;
} TYPEDESC;
```

Notes taken from the previous [discussion](https://github.com/dotnet/winforms/pull/818#discussion_r276114126) in the PR
* @sharwell wants to have tests to make sure nothing breaks, because fixing this likely requires also correcting all usage of `ELEMDESC` in WinForms
* @zsd4yr suggests taking a look into the old source control system to see if there's any history to the definition explaining the way it is
* @JeremyKuhne [suggests](https://github.com/dotnet/winforms/pull/818#pullrequestreview-229705078) using the version in `System.Runtime.InteropServices.ComTypes` - note that this still requires reviewing and adjusting callers in WinForms which previously used the broken version

**Comment by zsd4yr** [comment]
Who is taking point on this?

**Comment by sharwell** [comment]
I was not able to construct a case where any of this code gets used. Is any of this COM stuff supported in .NET Core?

**Comment by weltkante** [comment]
Look through the `Com2Interop` namespace it looks like it could be related to hosting ActiveX controls inside WinForms. Maybe its about the design time experience of ActiveX controls? I could find a [reference to VS](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IVsPerPropertyBrowsingHandler.cs)

Hosting 3rd party non-managed ActiveX controls inside WinForms is something we have occasionally used, so I don't think it should be dropped entirely. However if VS is the only consumer of this particular namespace (i.e. if you only need it at design time and not at runtime) I'm all for moving it out of WinForms and into the project system. Since this stuff is not public I don't think it's used by 3rd party WinForms designers.

(I don't know what the plans for the WinForms Core designer in VS are, but you can't use the Desktop Framework designer forever, once .NET Core starts moving beyond Desktop Framework it needs its own designer.)
