### ISSUE TITLE
[Meta/Repository] Guidelines on submitting designer-related issues

### ISSUE THREAD

**Issue by TheLeftExit** [dotnet/winforms#8962]
### .NET version

N/A

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

N/A

### Issue description

I see that the [designer-related issue template](https://github.com/dotnet/winforms/blob/main/.github/ISSUE_TEMPLATE/bug_report_designer.yml) was recently added, however, the README doesn't acknowledge this and still asks to file issues through Visual Studio:

https://github.com/dotnet/winforms/blob/21c401d08a57af296089bd1ff41e46d77082222b/README.md?plain=1#L19-L25

What are the latest recommendations on this? If filing an issue on GitHub is no longer discouraged, perhaps the README should be updated.

This is all assuming the person doesn't have access to the designer repository.

### Steps to reproduce

N/A

**Comment by merriemcgaw** [comment]
We will make the change to the readme that says they can do their preference for the out of process (.NET) designer. Thanks for the suggestion!

**Comment by Eudora-Li01** [comment]
Check on main branch, README file has been updated as following:
![image](https://github.com/dotnet/winforms/assets/130345015/2ca4b548-bf84-4b5a-9ee1-732f8cd8c4a2)
