### ISSUE TITLE
[Tracking] Remove suppressions against Obsolete methods

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#8984]
This is tracking issue related to the [comment ](https://github.com/dotnet/winforms/pull/8967#discussion_r1164758407)  and [comment ](https://github.com/dotnet/winforms/pull/8967#discussion_r1164758407)

Obsolete suppression needs to be revisited and mark appropriate public methods obsolete.

**Comment by elachlan** [comment]
Duplicate of #7308
