### ISSUE TITLE
Disposing of an MDI parent form twice throws an exception

### ISSUE THREAD

**Issue by TheLeftExit** [dotnet/winforms#8990]
### .NET version

.NET 8 Preview 3

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in .NET 7 and earlier

### Issue description

Calling `this.Dispose()` twice inside a form that has a child MDI form crashes the application with `NullReferenceException`.

Inspecting platform code code reveals an inconsistency inside the [PropertyStore.TryGetObject](https://github.com/dotnet/winforms/blob/f3a6aa1d4313472705cf3f00515a496c44552b10/src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs#L190-L195) method:

![image](https://user-images.githubusercontent.com/47351802/232063776-1816b30e-6359-43fc-8c7c-afb8f10202c5.png)

### Steps to reproduce

1. In Visual Studio 2022, create a new project with the Windows Forms App template. Select .NET 8 Preview 3.
2. In the form designer, add a button to the form.
3. Configure the form to be an MDI container, add an MDI child form, and add a handler to `Button.Click`:
```cs
public Form1() {
    InitializeComponent();
    IsMdiContainer = true;
    var form = new Form();
    form.Text = "TEST";
    form.MdiParent = this;
    form.Show();

    button1.Click += (sender, e) =>
    {
        this.Dispose();
        this.Dispose();
    };
}
```
4. Run the project and click on the button.
5. **The application crashes.**

**Comment by TheLeftExit** [comment]
Hi team,

We want to clarify that this regression impacts all developers who use DevExpress WinForms controls in their projects. Our internal logic does not take measures to avoid repeated disposal of controls. The same exception will be thrown in many of our customers' projects, and avoiding it will take a significant amount of code rewrite on our side.

This regression also prevents us from properly testing our components' compatibility with .NET 8 pre-release builds.

Please confirm that this will be resolved by the time of general release of .NET 8. Please also let us know if you have a rough timeline of when a pre-release build with the fix may be released.

Thank you.

**Comment by elachlan** [comment]
@TheLeftExit Would love a review on the PR fixing this issue if you have some time.

**Comment by TheLeftExit** [comment]
Thanks @elachlan! I'm not that fluent in under-the-hood, so my review won't mean much. The test is very reassuring, and we're eager to test it once it makes it into the preview.

**Comment by Nora-Zhou01** [comment]
Verified this issue on .NET 8.0.100-rc.1.23414.11, now the project doesn't crash when the button is clicked.

https://github.com/dotnet/winforms/assets/104609169/b8dba958-b018-44fd-8324-9d66c4a535aa

**Comment by Nora-Zhou01** [comment]
Verified with .NET SDK 8.0.100-rc.1.23421.2 test pass build, this issue was fixed, test result is same as above.
