### ISSUE TITLE
Support rounded rectangle in Graphics class

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#9001]
### Background and motivation

In modern interfaces, rounded rectangles are used in many places instead of right-angled rectangles, such as github buttons and labels.

GDI has [RoundRect](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-roundrect), but GDI+ doesn't have a direct equivalent. We can, however, do the necessary path generation in GDI+ to implement this fairly common request.

![001](https://user-images.githubusercontent.com/88176616/232976414-7108e93d-a823-4223-a7ac-c99dcfb7c0d9.png)

The current Graphics class provides Graphics.DrawRectangle and Graphics.FillRectangle to support drawing rectangles, but currently there is no corresponding method for drawing rounded rectangles.

### API Proposal

```diff
namespace System.Drawing;

public class Graphics
{
     public void DrawRectangle(System.Drawing.Pen pen, System.DrawingRectangle rect);
     // ...
+    public void DrawRoundedRectangle(System.Drawing.Pen pen, System.Drawing.Rectangle rect, Size corner);
+    public void DrawRoundedRectangle(System.Drawing.Pen pen, System.Drawing.RectangleF rect, SizeF corner);
+    public void FillRoundedRectangle(System.Drawing.Brush brush, System.Drawing.Rectangle rect, Size corner);
+    public void FillRoundedRectangle(System.Drawing.Brush brush, System.Drawing.RectangleF rect, SizeF corner);
}

namespace System.Drawing.Drawing2D;

public class GraphicsPath
{
     public void AddRectangle(Rectangle rect);
     // ...
+    public void AddRoundedRectangle(Rectangle rect, Size corner);
+    public void AddRoundedRectangle(RectangleF rect, SizeF corner);
}
```

### API Usage

graphics.DrawRoundedRectangle(new Pen(Color.Black), new Rectangle(0, 0, 100, 100), new Size(5, 5));
graphics.FillRoundedRectangle(new SolidBrush(Color.Black), new Rectangle(0, 0, 100, 100), new Size(5, 5));

**Comment by RussKie** [comment]
Kind of feels like you're asking for [`CreateRoundRectRgn`](https://learn.microsoft.com/windows/win32/api/wingdi/nf-wingdi-createroundrectrgn)...

**Comment by roland5572** [comment]
Yes, it looks like this is a feature that Win32 already supports, but it's not currently included in winForms.

**Comment by bartonjs** [comment]
* Based on the naming from GDI and from WPF, `Size corner` => `Size radius`.

```diff
namespace System.Drawing;

public class Graphics
{
     public void DrawRectangle(System.Drawing.Pen pen, System.DrawingRectangle rect);
     // ...
+    public void DrawRoundedRectangle(System.Drawing.Pen pen, System.Drawing.Rectangle rect, Size radius);
+    public void DrawRoundedRectangle(System.Drawing.Pen pen, System.Drawing.RectangleF rect, SizeF radius);
+    public void FillRoundedRectangle(System.Drawing.Brush brush, System.Drawing.Rectangle rect, Size radius);
+    public void FillRoundedRectangle(System.Drawing.Brush brush, System.Drawing.RectangleF rect, SizeF radius);
}

namespace System.Drawing.Drawing2D;

public class GraphicsPath
{
     public void AddRectangle(Rectangle rect);
     // ...
+    public void AddRoundedRectangle(Rectangle rect, Size radius);
+    public void AddRoundedRectangle(RectangleF rect, SizeF radius);
}
```
