### ISSUE TITLE
HDPI PMv2 issue in ContainerControl.ScaleContainerForDpi

### ISSUE THREAD

**Issue by tbambuch** [dotnet/winforms#9004]
### .NET version

7.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

worked in .net 5

### Issue description

The order of functions in ScaleContainerForDpi() is wrong.
Now, it first calls `PInvoke.SetWindowPos` and later it sets Font by calling `GetScaledFont `and raising `OnFontChanged`.

But, in my Per-monitor setup (175% dpi scaling for primary screen and 100% secondary), the `SetWindowPos()` call generates another `OnDpiChanged`, resulting in another `ScaleContainerForDpi `being called (see stacktrace attached).
This inner `ScaleContainerForDpi` call sets the correct font, but the Font is then overwritten by the incorrect value, after the function returns.

So I suppose the correct order should be: First raise OnFontChanged, then call PInvoke.SetWindowPos

[stacktrace.txt](https://github.com/dotnet/winforms/files/11270667/stacktrace.txt)

### Steps to reproduce

I did not found a reliable way how to replicate the issue on smallest scenario possible, it just happens for some of the forms in my application, while some other forms behave correctly

**Comment by dreddy-work** [comment]
@tbambuch, were those forms been launched at the monitor's periphery to activate another DpiChanged event if the majority of the form is shifted to another monitor using the SetWindowPos API?

**Comment by dreddy-work** [comment]
@tbambuch, can you check if linked PR help solve your issue?

**Comment by tbambuch** [comment]
> @tbambuch, can you check if linked PR help solve your issue?

Yes, it works for me

**Comment by dreddy-work** [comment]
> Yes, it works for me

Thank you for confirming.
