### ISSUE TITLE
An error dialog pops up when clicking AutoCompleteCustomSource in properyGrid with binding ComboBox 

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9008]
### .NET version

dotnet-sdk-8.0.100-preview.4.23218.19

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it doesn't reproduce in .Net 7.0 SDK build.

### Issue description

An error dialog pops up when clicking AutoCompleteCustomSource in propertyGrid with binding ComboBox control.

**Result on .Net 8.0 Preview 4 build:**
![image](https://user-images.githubusercontent.com/26474449/233242927-0d02986d-4873-4f39-ba96-69a295c20c40.png)

**Result on .Net 7.0 build:**
When clicking AutoCompleteCustomSource property, it will pops up String Collection editor dialog:
![image](https://user-images.githubusercontent.com/26474449/233243073-144096be-e8b2-46a6-94c4-c6c97afc13d2.png)

### Steps to reproduce

Tested app: 
[WinFormsApp89.zip](https://github.com/dotnet/winforms/files/11279282/WinFormsApp89.zip)

**Comment by dmitrii-drobotov** [comment]
Looks like it was introduced in https://github.com/dotnet/winforms/pull/8142, invalid cast is here:
https://github.com/dotnet/winforms/blob/024a9ab98d4bea535ce9fe6c473326bcd00464b7/src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs#L171
The fix should be pretty simple - cast to `ICollection` instead like in other similar places:
https://github.com/dotnet/winforms/blob/024a9ab98d4bea535ce9fe6c473326bcd00464b7/src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs#L48
https://github.com/dotnet/winforms/blob/024a9ab98d4bea535ce9fe6c473326bcd00464b7/src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutStyleCollection.cs#L130

Will make a PR now.

**Comment by MelonWang1** [comment]
Verified this on .NET 8.0 latest build: 8.0.100-preview.5.23226.2, issue is fixed. When clicking AutoCompleteCustomSource property, it will pops up String Collection editor dialog:
![9008](https://user-images.githubusercontent.com/94418985/234749305-4710a717-85e0-476c-a6fd-84dbd231effd.gif)

**Comment by John-Qiao** [comment]
Verified it in VS insertion PR with .Net 8 Preview 4 test pass build: 8.0.0-preview.4.23253.2, issue was fixed as above test result.
