### ISSUE TITLE
WinForms Designer appears to be completely broken in .NET 7 (ToolStripContainer issue?)

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/winforms#9016]
### Environment

Visual Studio Version 17.5.4

### .NET version

7.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Yes

### Issue description

I haven't worked with WinForms for a little while and created a *brand new* project.

1. Once the project was created, it was automatically loaded into the IDE. I got a message saying it was trying to load the form but after several minutes, it never loaded. I was finally able to load the form by restarting Visual Studio and reloading the project.
2. I created a menu, and double clicked one of the menu commands. This took me to the editor and positioned the cursor in the Form1_Load method. No handler was created for the menu command. I tried this about a dozen times. Then I went to the Properties window to the Click even dropdown. It showed an expected name for the handler. But when I double click on this, it again takes me to the Form_Load handler, and no handler was created for the menu command.
3. So I tried deleting the Form_Load handler. As expected, this gave me an error, which I corrected in the designer source. Then I got about a half dozen error messages in the IDE. I saved everything and rebuilt.
4. Now I was able to run the app without errors again. But all my menus and previous work was gone!

### Steps to reproduce

The steps were outlined above. I would think anyone who spent 15 minutes creating a new WinForms app and adding some event handlers will surely see there are problems here.

### Diagnostics

I tried to go through the steps in your troubleshooting guide, but for me, the Show output from dropdown only has one option: Package Manager. This is way beyond sending you an error report. It seems that virtually nothing is working for me here.

**Comment by SoftCircuits** [comment]
I seemed to have slightly more luck after switching to .NET 6.0.

**Comment by elachlan** [comment]
@Olina-Zhang could your team please see if they can reproduce this?

**Comment by Olina-Zhang** [comment]
@elachlan  I cannot reproduce this issue in 17.5.4 when creating Winforms VB/C# application with targeting .Net 7.0. 
@SoftCircuits  Could you please look at following gif and let us know if there has some steps are different from you?

**Comment by SoftCircuits** [comment]
@Olina-Zhang One thing I think I did was create a ToolStripContainer and placed the menu in that.

Let me see if I can do a video capture that duplicates the issues.
