### ISSUE TITLE
WinformsControlTest does not work for outside contributors

### ISSUE THREAD

**Issue by jnm2** [dotnet/winforms#9025]
### .NET version

8.0.100-preview.3.23178.7

### Issue description

The app shows a prompt to install Preview 4, but Preview 4 is not available to community contributors.

This link is given:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&&framework_version=8.0.0-preview.4.23221.1&&arch=x64&&rid=win10-x64&&gui=true

As you can see, when this link is used, it redirects to downloading Preview 3 instead of 4:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.0-preview.3-windows-x64-installer?cid=getdotnetcore

(Also, the "Show details/hide details" window is extremely broken on 200% DPI screens. If you click it multiple times, it blocks everything on the screen.)

![image](https://user-images.githubusercontent.com/8040367/233797337-a63eb333-4d55-4827-9ecb-1ad30712d099.png)

### Steps to reproduce

Clone repo, run `Restore.cmd`, install .NET SDK 8.0.100-preview.3.23178.7, select the WinformsControlTest project as the startup project, press F5.

**Comment by jnm2** [comment]
Running unit tests also doesn't work, and the link provided here starts the preview 3 download.

```
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.0-preview.4.23221.1' (x64)
.NET location: C:\Program Files\dotnet
The following frameworks were found:
  3.1.32 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  5.0.17 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.12 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.16 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  7.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  8.0.0-preview.3.23174.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Learn more:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0-preview.4.23221.1&arch=x64&rid=win10-x64
```

**Comment by jnm2** [comment]
I figured out how to obtain the required runtime version using https://aka.ms/dotnet/8.0/daily/dotnet-runtime-win-x64.exe found via https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#daily-builds-table. The current URLs provided by the test run output and the WinformsControlTest prompt should just work.

There should also be some explanation in the repo (e.g. in CONTRIBUTING.md) of how to perform any steps that aren't configured for you by simply cloning and pressing F5.

**Comment by jnm2** [comment]
This experience could be more community-friendly.

![Uploading image.png…]()

**Comment by jnm2** [comment]
The Task Dialog button also opens a window with buttons that can't be read, on 200% DPI.

![image](https://user-images.githubusercontent.com/8040367/233813126-6ad0621d-41fd-44a6-8b37-7846e54d6df3.png)

**Comment by RussKie** [comment]
Are you following the "how to build" guide? https://github.com/dotnet/winforms/blob/main/docs/building.md#building-from-visual-studio

**Comment by elachlan** [comment]
Does it work if you run `start-vs.cmd`?

**Comment by jnm2** [comment]
@RussKie Not yet! How would I have been able to know that this document existed, in a way that new contributors would also likely see?

**Comment by RussKie** [comment]
The docs are linked from the front page:
![image](https://user-images.githubusercontent.com/4403806/233978154-dee44888-3554-4ecc-996c-471bbffa6adc.png)
![image](https://user-images.githubusercontent.com/4403806/233978404-3ffa1458-c718-4d6f-b723-44baa07f21fb.png)

Feel free to share any suggestions on how this can be improved.

**Comment by jnm2** [comment]
Ah, I see what I missed. My only suggestion anecdotally would be to have a blurb in CONTRIBUTING.md which is where I usually look first, linking to the build instructions.

**Comment by jnm2** [comment]
> (Also, the "Show details/hide details" window is extremely broken on 200% DPI screens. If you click it multiple times, it blocks everything on the screen.)

Tracked the problem to code in the https://github.com/dotnet/runtime/issues/85571 repo.

**Comment by jnm2** [comment]
> 

Fixed in https://github.com/dotnet/winforms/pull/9057

**Comment by John-Qiao** [comment]
Verified this on .NET 8.0.100-preview.5.23253.14 using Task Dialog demo, it works well on 200% DPI now.
![9025 -Testresult](https://user-images.githubusercontent.com/45864985/236125434-38752d7c-122f-4e1f-ad92-408cb4e0d945.png)
