### ISSUE TITLE
advanceddatagridview from Nuget can not be used in Visual Studio 17.5.4

### ISSUE THREAD

**Issue by jory999** [dotnet/winforms#9026]
### .NET version

have to rollback to 17.5.3

### Did it work in .NET Framework?

No

### Issue description

advanceddatagridview from Nuget can not be used in Visual Studio 17.5.4

https://github.com/davidegironi/advanceddatagridview

### Steps to reproduce

。。。

**Comment by RussKie** [comment]
The author of that library has to provide a designer for the .NET designer, which is an out-of-process designer. Please refer the author to https://github.com/microsoft/winforms-designer-extensibility/.
