### ISSUE TITLE
PropertyGrid GDI handle leak in .NET 7.0

### ISSUE THREAD

**Issue by Soreepeong** [dotnet/winforms#9028]
### .NET version

* `dotnet --info` says 7.0.200.
* `System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription` says 7.0.3.

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET 5.0 and .NET 6.0.

### Issue description

Using PropertyGrid will leak GDI objects whenever PropertyGridView's OnPaint gets called.

Using reflection API...
* Setting Visible=false for `_commandsPane` made no difference.
* Setting Visible=false for `_helpPane` made no difference.
* Setting Visible=false for `_gridView` stopped the leak.

Using different framework versions...
* Using `.NET 5.0` stopped the leak. (.NET 5.0.17)
* Using `.NET 6.0` stopped the leak. (.NET 6.0.14)
* Using `.NET 7.0` has the leak. (.NET 7.0.3)

### Steps to reproduce

1. Open Windows Task Manager, go to Details tab, and enable "GDI objects" column in the list view.
2. Run the program with Target framework set as `.NET 5.0`, and see how "GDI objects" stays around 70 when you resize the window.
3. Run the program with Target framework set as `.NET 6.0`, and see how "GDI objects" stays around 80 to 90 when you resize the window.
4. Run the program with Target framework set as `.NET 7.0`, and see how "GDI objects" skyrockets when you resize the window, and once it reaches 9,999, it starts to fail to draw, and soon crash.
![image](https://user-images.githubusercontent.com/3614868/233840754-6ca41e0c-d65e-45e3-802d-9f235b2c31e2.png)

```cs
using System;
using System.Windows.Forms;

class Program {
    [STAThread]
    static void Main() {
        var pg = new PropertyGrid() {
            Anchor = AnchorStyles.Left | AnchorStyles.Top,
            Dock = DockStyle.Fill,
        };
        var form = new Form {
            Controls = { pg },
        };
        pg.SelectedObject = form;
        Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription);
        Application.Run(form);
    }
}
```

**Comment by elachlan** [comment]
@Olina-Zhang can your team please verify this?

**Comment by Amy-Li03** [comment]
@elachlan we can repro this issue on .NET 7.0 & 8.0, as @Soreepeong said, after resizing the form window, and once it reaches 9,999, it starts to fail to draw, and soon crash.
When targeting to .NET 6.0, "GDI objects" stays around 60 to 80 when resizing form window.
When targeting to .NET 5.0, "GDI objects" stays around 60 to 70 when resizing form window.

**Call Stack:**
_System.Runtime.InteropServices.ExternalException
  HResult=0x80004005
  Message=A generic error occurred in GDI+.
  Source=System.Drawing.Common
  StackTrace:
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawString(String s, Font font, Brush brush, RectangleF layoutRectangle, StringFormat format)
   at System.Windows.Forms.Label.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, WM msg, WPARAM wparam, LPARAM lparam)_

**Comment by JeremyKuhne** [comment]
Reopening for 7.0 servicing.

**Comment by JeremyKuhne** [comment]
The fix has been approved for 7.0 servicing and is checked in.

**Comment by MandiMan** [comment]
Verified this on .NET 8.0.100-preview.5.23253.14, issue was fixed, When targeting to .NET 8.0, "GDI objects" stays around 60 to 80 when resizing form window.
![image](https://user-images.githubusercontent.com/108860782/236126175-b5ba1738-879c-4bc4-a8f0-bf359fdaccf8.png)

**Comment by MandiMan** [comment]
Verified it in VS insertion PR with .Net 8 Preview 4 test pass build: 8.0.0-preview.4.23253.2, When targeting to .NET 8.0, "GDI objects" stays around 60 to 80 when resizing form window, as above testing result displayed.

**Comment by MandiMan** [comment]
Verified on .NET 7.0 test pass build: .NET 7.0.400-preview.23225.8, issue was fixed. When targeting to .NET 7.0, "GDI objects" stays around 60 to 80 when resizing form window. The screenshot as same as above.
