### ISSUE TITLE
Form is removed from Application.OpenForms after RecreateHandle

### ISSUE THREAD

**Issue by kirsan31** [dotnet/winforms#9029]
### .NET version

.Net6, .Net7 checked.

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

I checked only .Net6, .Net7 but according to the code, problem exist in all versions (.net framework too).

### Issue description

While working on https://github.com/dotnet/winforms/issues/3606  I found that after calling to `RecreateHandle`, the form is completely removed from `Application.OpenForms`.

The form is added to `Application.OpenForms` in two cases:
1. `OnLoad`.
2. `SetVisibleCore(true)`  🤔

The form is removed from `Application.OpenForms` in two cases:
1. `OnFormClosed`.
2. `OnHandleDestroyed` 🤔🤷‍♂️

Here we clearly see that after `RecreateHandle` we will completely lost our form from `Application.OpenForms` :( We call `RecreateHandle` for the form in several cases (`ShowInTaskbar` \ `RightToLeft` change etc...).
I still can't say for sure how much duplication of the `Application.OpenForms.Remove` call in `OnHandleDestroyed` is necessary.

### Steps to reproduce

[FormCloseTest.zip](https://github.com/dotnet/winforms/files/11304011/FormCloseTest.zip)

0. Build.
1. Run.
2. Press button2 => `Application.OpenForms` will contains 3 forms (main, mdiParent and mdiChild).
3. Press button3 => `Application.OpenForms` will contains 1 form - main.

**Comment by elachlan** [comment]
@kirsan31 I imagine the fix is to add it back in `RecreateHandle`?

**Comment by kirsan31** [comment]
@elachlan 

The main logic is clear: add in `OnLoad` and remove in `OnFormClosed`.
Removal in `OnHandleDestroyed` looks like some kind of safety net, the comment also confirms this::
```cs
// just make sure we're no longer in the forms collection list
Application.OpenForms.Remove(this);
```

> imagine the fix is to add it back in RecreateHandle?

May be add flag `_callFromRecreateHandle` (set it to true in `RecreateHandle`) and simple not remove form in `OnHandleDestroyed` if `_callFromRecreateHandle == true`? Another advantage of this approach is that we will not violate the order of the forms in `OpenForms`.

**Comment by elachlan** [comment]
Probably, but I'd try and keep them as separate commits and make sure the merge isn't done via a squash.

**Comment by merriemcgaw** [comment]
This does appear to be a bug that should be fixed. If either of you would like to propose a fix (submit a pr 😉 ), we'd be happy to take it.

**Comment by kirsan31** [comment]
@merriemcgaw 
> This does appear to be a bug that should be fixed. If either of you would like to propose a fix (submit a pr 😉 ), we'd be happy to review.

I'm going to do it...

**Comment by merriemcgaw** [comment]
@kirsan31, we always love having your contributions, thank you!

**Comment by Nora-Zhou01** [comment]
Verified this on .NET 8.0.100-preview.5.23253.14, issue was fixed, when opening a new form, the old one still exists.

https://user-images.githubusercontent.com/104609169/236135570-70461e25-8e1d-41f6-b672-7513a8a78c35.mp4

**Comment by MandiMan** [comment]
Verified this on .NET 8.0 TP build: 8.0.100-preview.5.23276.4, issue was fixed, test result is same as above video.
