### ISSUE TITLE
Invalid code generation when component's name hides inherited member

### ISSUE THREAD

**Issue by ViIvanov** [dotnet/winforms#9032]
### Environment

Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.6.0 Preview 4.0

### .NET version

net472, net70

### Did this work in a previous version of Visual Studio and/or previous .NET release?

It is not works when preview feature "Windows Forms out-of-process designer" is unchecked.

### Issue description

Wrong .NET code generated is case when component on the form has a name, that hides name from base class.
For example: add a `TextBox` to the new form and set name "Text" to this component.

Actually, following C# generated in `InitializeComponent()`:
```cs
    private void InitializeComponent() {
      Text = new TextBox();
      SuspendLayout();
      // 
      // Text
      // 
      Text.Location = new Point(49, 59);
      Text.Name = "Text";
      Text.Size = new Size(100, 23);
      Text.TabIndex = 0;
      // 
      // Form1
      // 
      AutoScaleDimensions = new SizeF(7F, 15F);
      AutoScaleMode = AutoScaleMode.Font;
      ClientSize = new Size(800, 450);
      Controls.Add(Text);
      Name = "Form1";
      Text = "Form1"; // Error
      ResumeLayout(false);
      PerformLayout();
    }

    private TextBox Text; // Warning
```

At the first, declaration of the `private TextBox Text;` generated a warning
> warning CS0108: 'Form1.Text' hides inherited member 'Form.Text'. Use the new keyword if hiding was intended.

At the second, setting `Text` property of the form failed with compilation error:
> error CS0029: Cannot implicitly convert type 'string' to 'System.Windows.Forms.TextBox'

It looks like designer should generate following code:
```cs
    private void InitializeComponent() {
      Text = new TextBox();
      SuspendLayout();
      // 
      // Text
      // 
      Text.Location = new Point(49, 59);
      Text.Name = "Text";
      Text.Size = new Size(100, 23);
      Text.TabIndex = 0;
      // 
      // Form1
      // 
      AutoScaleDimensions = new SizeF(7F, 15F);
      AutoScaleMode = AutoScaleMode.Font;
      ClientSize = new Size(800, 450);
      Controls.Add(Text);
      Name = "Form1";
      base.Text = "Form1";
      ResumeLayout(false);
      PerformLayout();
    }

    private new TextBox Text;
```

### Steps to reproduce

1. Add new Form
2. Add new `TextBox` component to this form
3. Set component name ("(Name)" in Property Grid) "Text" to text box component above
4. Compile project

Warning and error produced:
> warning CS0108: 'Form1.Text' hides inherited member 'Form.Text'. Use the new keyword if hiding was intended.
> error CS0029: Cannot implicitly convert type 'string' to 'System.Windows.Forms.TextBox'

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you please repro this and copy the issue into our internal designer repo? @KlausLoeffelmann would like to take a look.

**Comment by RussKie** [comment]
I kind of think that this scenario _has to fail_. The designer can't decide for a developer that a `base` has to be called.

**Comment by Olina-Zhang** [comment]
@merriemcgaw Verified this case also reproduces in classic designer, do we still need to open an issue in designer repo?

**Comment by merriemcgaw** [comment]
@Olina-Zhang, no I don't think we need a designer repo issue. And I agree with @RussKie now that I've considered it. I think we're doing the right thing here and I will close this issue.
