### ISSUE TITLE
Unckeck one listview item is unchecking all checked items

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#9033]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unckeck-one-listview-item-is-unchecking-/10347342)._

---
[severity:It's more difficult to complete my work]
In a Windows form I have a tabcontrol. In code, I create a tabpage with a listview and I add a handler for the listview ItemCheck event. 
The listview multiselect property is set to TRUE. 
The handler select/deselect the listview item conforms the user check/uncheck it.
It works fine for check listview items, but when you uncheck just one item, all the others checked items are unchecked too.

This is the code:
```
Imports Microsoft.VisualBasic.Logging
Imports System.Globalization
Imports System.Security.Policy
Public Class Form1

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim txt As String = "02/2023"
        Dim lv As ListView
        Dim pg As TabPage

        Me.TabControl1.TabPages.Clear()
        pg = NewTabPage(Me.TabControl1, txt)
        lv = pg.Controls(0)
        Me.TabControl1.SelectTab(0)
    End Sub

    Private Function NewTabPage(ByRef TabCtrl As TabControl, ByVal txt As String) As TabPage

        For Each tp As TabPage In TabCtrl.TabPages
            If tp.Text = txt Then
                tp.Select()
                NewTabPage = tp
                Exit Function
            End If
        Next

        Dim lv As New ListView
        Dim pg As New TabPage With {.Text = txt}
        TabCtrl.TabPages.Add(pg)

        With lv
            .Parent = pg
            .Name = txt
            .View = View.Details
            .Dock = DockStyle.Fill
            .LabelEdit = False
            .AllowColumnReorder = True
            .CheckBoxes = True
            .FullRowSelect = True
            .GridLines = True
            .HeaderStyle = ColumnHeaderStyle.Clickable
            .MultiSelect = True
            .Columns.Add("MONTH", 100, HorizontalAlignment.Center)
            .Columns.Add("BRANCH", 60, HorizontalAlignment.Center)
            .Columns.Add("ACCT", 60, HorizontalAlignment.Left)
            .Columns.Add("SSN", 100, HorizontalAlignment.Center)
            .Columns.Add("CUSTOMER", 140, HorizontalAlignment.Left)
            pg.Controls.Add(lv)
            AddHandler .ItemCheck, AddressOf Me.lv_ItemCheck
        End With

        For i As Integer = 1 To 10
            Dim lvi As New ListViewItem(txt & Format(i, "-00"))
            With lvi
                .SubItems.Add("0001")
                .SubItems.Add("BB" & Format(100 * i, "-0000"))
                .SubItems.Add("001.01234-12" & Format(i, "-00"))
                .SubItems.Add("STAR DRUGSTORE " & Format(i, "00"))
                lv.Items.Add(lvi)
            End With
        Next
        pg.Select()
        pg.Focus()
        NewTabPage = pg

    End Function

    Public Sub lv_ItemCheck(sender As Object, e As ItemCheckEventArgs)
        Dim lv As ListView = sender
        Dim ix As Integer = e.Index

        If e.CurrentValue = CheckState.Checked Then
            lv.Items(ix).Selected = False
        Else
            lv.Items(ix).Selected = True
        End If
    End Sub

End Class

```
- Windows 10 Pro Version 10.0.19044, PT-BR
- MS Visual Studio&nbsp;Professional 2022(64 bits) - Current Version 17.5.4
- Directs to .NET 6.0.
- MS .NET Framework version 4.8.04084

---
#### Feedback Bot on 4/25/2023, 10:21 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by MandiMan** [comment]
**.NET version**
.NET SDK 8.0.100-preview.4.23224.19

**Did it work in .NET Framework?**
No

**Did it work in any of the earlier releases of .NET Core or .NET 5+?**
No, it also repro on .NET 5.0 & 6.0 & 7.0.

**Issue description**
when you uncheck just one item, all the others checked items are unchecked too.


**Repro Steps:**

1. Unzip the folder [test.zip](https://github.com/dotnet/winforms/files/11320702/test.zip)
2. Then build and run attached project “[test.zip](https://github.com/dotnet/winforms/files/11320702/test.zip)”
3. Check more than one item in the list
4. Uncheck just one item

**Actual result:**
when uncheck just one item, all the others checked items are unchecked too.
![1808229](https://user-images.githubusercontent.com/108860782/234229108-a7fe54d6-531d-4d26-8a02-29e0291a5377.gif)

**Expected result:**
when uncheck just one item, only that item is unchecked, the other checked items are still checked.

**Comment by merriemcgaw** [comment]
Given that this has been this way even in .NET Framework I'm afraid that changing any behavior here will result in breaking changes for people who are used to this behavior. We don't think this should be fixed in either .NET or .NET Framework. Please resolve the underlying ticket accordingly.
