### ISSUE TITLE
Printer tray changes are not detected by papersources

### ISSUE THREAD

**Issue by N3IS** [dotnet/winforms#9034]
### .NET version

.NET6

### Did it work in .NET Framework?

No

### Issue description

The papersources of printersettings do not detect tray changes made with printer driver while the application is running. To detect these changes I need to restart the application. Added and removed printers are detected live but trays (papersources) not.

### Steps to reproduce

    while (true) 
    {
        var printerNames = PrinterSettings.InstalledPrinters.Cast<string>().ToList();

        foreach (var printerName in printerNames)
        {
            var printerSettings = new PrinterSettings { PrinterName = printerName };
            var trays = printerSettings.PaperSources.Cast<PaperSource>().Select(ps => ps.SourceName);

           Console.WriteLine($"{printerName} - {string.Join(", ", trays)}");
        }

        Console.WriteLine("----------------------------------------------------------------------------------------");
        Console.ReadLine();
    }

**Comment by JeremyKuhne** [comment]
I don't know that we can do much here.  We just ask Windows for the [data](https://learn.microsoft.com/windows/win32/api/wingdi/nf-wingdi-devicecapabilitiesw) and I don't see any information about how it caches or might not be cached.

@N3IS can you give more explicit details about your scenario? If I can reproduce the caching behavior, I can try to reach out to the Windows team to see if there is anything we can do.

**Comment by N3IS** [comment]
My scenario is that we provide a printing service. The user can define to which printer and to which tray (papersource) he wants to print at. If now e.g. a new tray of a printer gets added via windows printer driver because it should be used from now on we need to restart our application on production to detect these change and make it usable.

To reproduce this locally I installed some printer driver from our printserver and added or removed some trays inside the driver configuration while my example code was running. The changes are only displayed in the console if I restart the application.

**Comment by elachlan** [comment]
@kennykerr does rust have a similar issue with `DeviceCapabilitiesW`?

**Comment by kennykerr** [comment]
@jonwis may know who can help with this API. Otherwise, you can try:

https://docs.microsoft.com/en-us/answers/topics/windows-api.html

**Comment by jonwis** [comment]
Hey @mziller - can you help out here? Is there an event that the Win32 https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-devicecapabilitiesw API offers to determine changes in the printer? Maybe https://learn.microsoft.com/en-us/windows/win32/printdocs/findfirstprinterchangenotification needs to track changes in the printer?

**Comment by mziller** [comment]
Right I'd start with [DeviceCapabilities](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-devicecapabilitiesw) passing DC_BINNAMES (you should be able to pass nullptr for the port and DevMode, giving just the printer name) and see if that also has the same issue. If so I suspect the config DLL for the driver may be caching the information (the driver DLL is loaded in the printing application's address space). You can see the config file used by the driver in printmanagement.msc in the driver properties dialog.

**Comment by elachlan** [comment]
@N3IS can you please check the driver config?

**Comment by N3IS** [comment]
I can confirm by using DeviceCapabilitiesW function that we have the same result. So tray changes aren't recognized.
We used this piece of code to validate it. We also updated the application to .NET8 with updated libraries.
```
internal static class Program
{
    private const int DC_BINNAMES = 12;

    [DllImport("winspool.drv", EntryPoint = "DeviceCapabilitiesW", SetLastError = true, CharSet = CharSet.Unicode)]
    private static extern int DeviceCapabilities(string pDevice, string pPort, int fwCapability, IntPtr pOutput, IntPtr pDevMode);

    private static void Main(string[] _)
    {
        while (true)
        {
            const string printerName = "SHARP MX-3060N PS";

            var pOutput = Marshal.AllocHGlobal(1000);
            var result = DeviceCapabilities(printerName, null, DC_BINNAMES, pOutput, IntPtr.Zero);

            Console.WriteLine(printerName);

            for (var i = 0; i < result; i++)
            {
                var trayName = Marshal.PtrToStringAuto(pOutput + 48 * i);
                Console.WriteLine("\t" + trayName);
            }

            Marshal.FreeHGlobal(pOutput);

            Console.WriteLine("----------------------------------------------------------------------------------------");
            Console.ReadLine();
        }
    }
}
``` 
Here are screenshots of the used printer and it's config how we change the amount of trays. We have the printer driver only available in German.
![image](https://github.com/dotnet/winforms/assets/34442847/0ed370da-1957-4744-90f9-95209e7adbe3)
![image](https://github.com/dotnet/winforms/assets/34442847/25592106-9614-4cf7-8be7-f7f91340eb6a)

**Comment by elachlan** [comment]
@mziller Please see response above. Does that mean the driver is probably caching the results?

**Comment by mziller** [comment]
Right the driver would have had to specify the optional trays that can be added as installable options in the driver config file (GPD or PPD) for this to work dynamically:

https://learn.microsoft.com/en-us/windows-hardware/drivers/print/handling-installable-features-and-options
https://learn.microsoft.com/en-us/windows-hardware/drivers/print/v4-driver-property-bags#queue-property-bag

**Comment by elachlan** [comment]
@N3IS This is something you have to raise with the Printer manufacturer, so they can support it via their driver.
