### ISSUE TITLE
can't resolve licx file with vs2022 and reuturn code -1073741819

### ISSUE THREAD

**Issue by wangrd** [dotnet/winforms#9037]
### Issue Description
It's not successful when I build my C# project with vs2022，bucause of the license.licx which used by a third-party component in my project. But it's ok in vs2019 or older.

### Steps to Reproduce
add a licx file in cs project and build it.

### Expected Behavior
Work well like vs2019.

### Actual Behavior
Can't compile successfuly.

### Analysis
In my mind, it may be related with the 64bit envirenment, because vs2022 is woking with it. some helps, the same problem occured when i build it with vs2019 and run with IDesignerHost  in 64bit app，which tips Unauthorized.

### Versions & Configurations
- vs2022 17.3.0 Preview 2.0 or older

**Comment by Olina-Zhang** [comment]
Cannot repro this issue when using GrapeCity controls in Visual Studio 2022, build application successfully. Whether to close this issue? @merriemcgaw /@Tanya-Solyanik 
![image](https://user-images.githubusercontent.com/26474449/234524777-82837b85-909b-435c-9da8-77af422203e3.png)

**Comment by merriemcgaw** [comment]
Unfortunately, since we can't repro on our end, I do think we have to close this issue.
