### ISSUE TITLE
`MessageBox.Show` overload with `StartPosition` parameter

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#9043]
### Background and motivation

When Messagebox.Show is called, often it will be associated to an open window. The messagebox will show in the middle of the monitor. This is not really user friendly when the user has a large monitor or when using non-maximized forms.

Example of users working around the problem:
https://stackoverflow.com/questions/1732443/center-messagebox-in-parent-form

### API Proposal

```csharp
namespace System.Windows.Forms;

public enum MessageBoxStartPosition
{
Default = 0,
CenterScreen = 1,
CenterParent = 2
}

public static DialogResult Show(
            string? text,
            string? caption,
            MessageBoxButtons buttons,
            MessageBoxIcon icon,
            MessageBoxDefaultButton defaultButton,
            MessageBoxOptions options,
            MessageBoxStartPosition startPosition)
```

### API Usage

```csharp
MessageBox.Show("Test Message box text","Test Caption", 
MessageBoxButtons.OK, MessageBoxIcon.Error, MessageBoxStartPosition.CenterParent)
```

### Will this feature affect UI controls?

No.

**Comment by RussKie** [comment]
Generally, Windows Forms is positioned as an "easy to use" wrapper over the Win32 API. The Windows Forms' `MessageBox` is a wrapper over `MessageBoxW` API, which doesn't allow to customise the location of the dialog. If the location is important I'd suggest using [`TaskDialog`](https://learn.microsoft.com/dotnet/api/system.windows.forms.taskdialog.showdialog#system-windows-forms-taskdialog-showdialog(system-intptr-system-windows-forms-taskdialogpage-system-windows-forms-taskdialogstartuplocation)) instead, which provides this functionality out of the box (as well as more modern and more advanced features).

**Comment by elachlan** [comment]
This is mostly for legacy code already using `MessageBox`. Additionally, `TaskDialog` is a bit more verbose for showing an error message box. The link provides a solution that makes uses `SetWindowsHookEx` for a callback to then call `MoveWindow` on the messagebox. This seems like a good quality of life improvement.

**Comment by RussKie** [comment]
I agree that TD is a bit more verbose, but it's also feature-ruch and (which _is_ important) it is test-friendly. Migrating from MB to TD isn't that difficult, one can add a quick helper method that would translate MB calls to comparable TD calls.

**Comment by elachlan** [comment]
I am in this awkward situation where I am targeting .net48/.net6 at the same time. A helper method could have different implementations based on the compiled framework I guess.

**Comment by RussKie** [comment]
Something like this should work:

```cs
// code
ShowMessage(owner, message, heading);


// 
private static void ShowMessage(I32Window owner, string message, string heading)
{
#if NET5_OR_GREATER
     MessageBox.Show(owner, message, heading);
#else
     TaskDialogPage page = new(...);
     TaskDiaglog.Show(owner, page);
#endif
}
```

**Comment by dreddy-work** [comment]
Enhancements for the thin WinForms wrappers like this are allowed if the underlying native API is enhanced over the time and support new features that WinForms wrapper doesn't. In this case, we have an alternative to MessageBox.

**Comment by merriemcgaw** [comment]
As mentioned above, this wouldn't be something we want to invest in. Thanks for the suggestion! We're also pondering ways to use Roslyn Analyzers and fixers to help people migrate their easy to use MessageBoxes to TaskDialog.

**Comment by elachlan** [comment]
Could we pivot to make a method on Task dialog to represent a similar API to Message box to avoid the need to create a page?

That would allow a quick way to migrate them with a codefix.

**Comment by RussKie** [comment]
> make a method on Task dialog to represent a similar API to Message box to avoid the need to create a page?

I don't think that's a good idea.

**Comment by elachlan** [comment]
Okay. An analyser with a code fix would be great.

**Comment by elachlan** [comment]
@merriemcgaw do you have a tracking issue for the analyser?

**Comment by RussKie** [comment]
> We're also pondering ways to use Roslyn Analyzers and fixers to help people migrate their easy to use MessageBoxes to TaskDialog.

What'd be the compelling reason for devs to do that? The only reason I can think of is testability of the TD - meaning a dev will be able to test a code flow that would surface a TD; but multiple reports suggest that a lot of devs don't use automated tests, especially working on GUI apps...
I'd think that helping VB devs to move away from MsgBox to MessageBox could be significantly more valuable (to the end users). That was the motivation behind https://github.com/dotnet/runtime/pull/73838.

In any case, if you think such analyzer would be really useful, it'd go in to https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms.Analyzers since it should target both C# and VB devs.

**Comment by merriemcgaw** [comment]
We don't have an issue yet tracking that - feel free to open one if I don't get to it in the next day or so.
