### ISSUE TITLE
ContextMenu items with checkboxes are displayed badly in PMv2 HDPI

### ISSUE THREAD

**Issue by tbambuch** [dotnet/winforms#9044]
### .NET version

.NET 7

### Did it work in .NET Framework?

Yes

### Issue description

In Per-Monitor v2 scenario, the contextmenu items with checkbox causes the contextmenu items having wrong height and the checkbox is not fully visible.
My scenario is 175% primary screen, 100% secondary screen. The sample app looks fine on the primary one, but gets broken on the secondary.

![image](https://user-images.githubusercontent.com/3384955/234545227-eea00d20-c53c-4f31-af7d-840966cb5b15.png)
![image](https://user-images.githubusercontent.com/3384955/234545240-ae65cda4-839f-4280-94bd-dc520b310502.png)
[DpiTest.zip](https://github.com/dotnet/winforms/files/11331626/DpiTest.zip)

### Steps to reproduce

Set up a primary screen to 175%, secondary to 100%
Run the attached DpiTest project on the secondary screen.
One button opens simple context menu, while the second button opens a contextmenu where the first item is checked.
On the secondary screen, the second contextmenu is not displayed correctly

**Comment by elachlan** [comment]
@dreddy-work

**Comment by MelonWang1** [comment]
Verified this on .NET8.0.100-preview.5.23261.16, issue was fixed, set primary screen to 175%, and run the project in 100% secondary screen, the second contextmenu displayed correctly where the first item is checked. Please see screenshot:
![run 100](https://github.com/dotnet/winforms/assets/94418985/58b9f006-3f20-42c8-b3ec-d58d7b96bf99)

![run100-1](https://github.com/dotnet/winforms/assets/94418985/2a42fc99-528a-4c1c-ba96-bfe6cc5b1a84)

**Comment by MelonWang1** [comment]
Verified this on .NET 8.0 TP build: 8.0.100-preview.5.23276.4, issue was fixed, screenshot is same as above.
