### ISSUE TITLE
[8.0.100-preview.4.23253.2] WinForm Application's Window control type changed from WinWindow to Caret in Coded UI Test

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/winforms#9096]
### .NET version

8.0.100-preview.4.23253.2

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-7.0.300-rtm.23215.1: Pass
2). Windows 10 21H2 AMD64 + dotnet-6.0.409-servicing.23215.9: Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk- 8.0.100-preview.4.23225.2: Pass
4). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.4.23253.2: Fail
5). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.4.23259.1: Fail

### Issue description

**Application Name**: More than 30+ apps affected (paintnetcore, ConicSectionPlayground, Core2D, DragonEngine, EnvelopeWarpPlayground, Estoque, GameofLife, GlucoseTray, Greenshot and so on)
**OS:** Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-8.0.100-preview.4.23253.2
**Checking repro machine at** : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1816978

When automation testing for WinForm applications in Coded UI Test, the recorded root control type is changed from WinWindow to Caret starts from dotnet-sdk-8.0.100-preview.4.23253.2. It results to automation code cannot find controls under this root when applications running on dotnet-sdk-8.0.100-preview.4.23253.2. There are more than 260+ test cases (more than 30+ apps) are affected and all these test cases must to be re-designed.
**Repro Video:**  
![CodedUIRepro](https://github.com/dotnet/winforms/assets/83067197/320ea799-4d08-4689-b23f-96f088d51f43)

On default .NET 6.0 runtime, the operated control type is WinWindow. And check from the UIMap.uitest designer page, it also shows the root controls is
```
            WinWindow uIForm1Window = this.UIForm1Window;
            // Maximize window 'Form1'
            uIForm1Window.Maximized = this.MaxNET6WinFormWindowParams.UIForm1WindowMaximized;
```
Start from dotnet-sdk-8.0.100-preview.4.23253.2, the root control type becomes Caret and the operated control becomes the Button under Caret > TitleBar > MaximizeButton.
```
            WinButton uIMaximizeButton = this.UIForm1Caret.UIItemTitleBar.UIMaximizeButton;
            // Click 'Maximize' button
            Mouse.Click(uIMaximizeButton, new Point(22, 17));
```
![image](https://github.com/dotnet/winforms/assets/83067197/b7afa91a-d201-4f0d-a8c6-9d30f4d7c3c6)

### Steps to reproduce

**Minimal Repro steps on repro machine:**

1.Launch the demo app "C:\WinFormsAppDemo\WinFormsAppDemo.exe"
2. Open VS2017 and create a default Coded UI Test Project.
3. When Generate Cod for Coded UI Test window appear, click OK button.
4. Click Record button to start recording actions.
5. Click the Maximized button on WinFormsAppDemo app window.
6. Click Generate code button.
7. Set name for the record method.
8. Stop the recording and check the generated code.
9. Go to the UIMap.Designer.cs, and check the recorded method. The root control is WinWindow.
```
WinWindow uIForm1Window = this.UIForm1Window;          
//Maximize window 'Form1'          
uIForm1Window.Maximized = this.MaxNET6WinFormWindowParams.UIForm1WindowMaximized;
```
10. Change the WinFormsAppDemo.runtime.config file from 6.0.0 to run against with SDK dotnet 8.0.100-preview.4.23253.2:
```
"frameworks": [

      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0-preview.4.23228.5"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "8.0.0-preview.4.23252.6"
      }
    ]
```
11. Repeat steps 1~8.
12. Check the recorded code, the root control type is Caret:
``` 
WinButton uIMaximizeButton = this.UIForm1Caret.UIItemTitleBar.UIMaximizeButton;          
// Click 'Maximize' button          
Mouse.Click(uIMaximizeButton, new Point(22, 17));
```

**Expected Result:**
The control type is same.

**Actual Result:**
The Control type is changed from WinWindow to Caret.  

@dotnet-actwx-bot @dotnet/compat

**Comment by merriemcgaw** [comment]
@dmitrii-drobotov can you have someone on your team help us narrow down the problem. You'll need VS 2019 Enterprise to debug the CodedUI Test framework, but that's probably the easiest way to narrow down the issues.

**Comment by Olina-Zhang** [comment]
@merriemcgaw @dmitrii-drobotov Here is a simple repro when creating a winforms application:

**Repro steps:**
1. Create a Winforms applicaiton with button control
2. Open Inspect tool by UIA automation and MSAA 

**Actual result:**
In Inspect: UIA automation, the Role and controlType for form window and control: button are correct, no change.
![image](https://github.com/dotnet/winforms/assets/26474449/b4e3f71e-effe-4b27-a653-0782b7dac525)

But in Inspect: MSAA, the Role for form window and control: button are not correct, change to **caret**
![MicrosoftTeams-image](https://github.com/dotnet/winforms/assets/26474449/ec5a4274-7f40-4527-ae0b-2280232bba31)

**Comment by dmitrii-drobotov** [comment]
@Olina-Zhang great job finding a simple repro! 

Based on it I would guess that it was introduced in https://github.com/dotnet/winforms/pull/9015 (merge date matches first fail version) and specifically these changes to the role property:
https://github.com/dotnet/winforms/blob/b6da3f99f9752be0e6fe21e79f9cac32aaab3256/src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs#L1569-L1572
We are now returning child count as role, but previously it was a query to systemIAccessible role if count is 0:
https://github.com/dotnet/winforms/blob/f033a225944dfab4f4034a3faa47342432fccd76/src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs#L1455-L1460
A quick fix by changing it back to return systemIAccessible role seem to resolve the issue:
```diff
-        return count == 0 ? null : count;
+        return count == 0 || childID is not int id ? null : SystemIAccessible.TryGetRole(id);
```
![image](https://github.com/dotnet/winforms/assets/102954094/847268a8-3a91-499b-bcc6-26a7293653b8)

**Comment by JeremyKuhne** [comment]
@Olina-Zhang, @dmitrii-drobotov you both rock! 🙇🏼

**Comment by Junjun-zhao** [comment]
Verify the issue on latest SDK build 8.0.100-preview.5.23273.2, it has been fixed.

**Comment by Ashley-Li** [comment]
Verified this issue in the latest .Net 8.0 SDK build: 8.0.100-preview.5.23274.2, it is fixed, see following test results in  Inspect: 
![image](https://github.com/dotnet/winforms/assets/56664234/845c8db0-e64a-49e2-b9c5-41ed57ac733a)

**Comment by Ashley-Li** [comment]
Verified this on .NET 8.0 Preview 5.0 TP build: 8.0.100-preview.5.23276.4, issue was fixed as same as above result.

**Comment by Ashley-Li** [comment]
Verified this on .NET 8.0 test pass build: 8.0.100-preview.5.23276.4, issue was fixed, test result is same as above result.
