### ISSUE TITLE
Public WinForms / .NET types require the BinaryFormatter when serializing public properties.

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#9110]
When serializing public types (for ActiveX purposes, Resx, etc.) they will try to use a registered `TypeConverter` if one exists that can round-trip to/from `string` or to/from `byte[]`. If they don't have a type converter that can do so they will serialize with `[Serializable]` or `ISerializable` and the `BinaryFormatter`.

This issue is to track the known types in the WinForms stack that fall into the `BinaryFormatter` category.

### System.Windows.Forms

System.Resources.ResXDataNode
System.Windows.Forms.ImageListStreamer
System.Windows.Forms.ListViewGroup
System.Windows.Forms.ListViewItem
System.Windows.Forms.OwnerDrawPropertyBag
System.Windows.Forms.TreeNode
System.Windows.Forms.AxHost+InvalidActiveXStateException
System.Windows.Forms.AxHost+State
System.Windows.Forms.ListViewItem+ListViewSubItem

### System.Drawing.Primitives

System.Drawing.PointF
System.Drawing.RectangleF

### System.Drawing.Common

System.Drawing.Printing.InvalidPrinterException

### System.Private.CoreLib

(Some reflection and other types are not listed here as they are extremely unlikely to be exposed as public properties.)

System.Array
System.Attribute
System.ValueType
System.DBNull
System.EventArgs
System.IntPtr
System.OperatingSystem
System.StringComparer
System.CultureAwareComparer
System.OrdinalComparer
System.TimeZoneInfo
System.TimeZoneInfo+AdjustmentRule
System.TimeZoneInfo+TransitionTime
System.UIntPtr
System.ValueTuple
System.Globalization.CompareInfo
System.Globalization.SortVersion
System.Text.StringBuilder
System.IO.DirectoryInfo
System.IO.FileInfo
System.IO.FileSystemInfo
System.Collections.ArrayList
System.Collections.Comparer
System.Collections.DictionaryEntry
System.Collections.Hashtable
System.Collections.ListDictionaryInternal
System.Collections.Generic.ByteEqualityComparer
System.Collections.Generic.NonRandomizedStringEqualityComparer

(Still under investigation)

**Comment by weltkante** [comment]
> System.Windows.Forms.AxHost+State
is probably just a binary blob and can be serialized as such in any form, no need to rely specifically on BinaryFormatter

(this came up in a question somewhere else so I'm also noting it here)

**Comment by merriemcgaw** [comment]
@JeremyKuhne can you update this with the latest work done? Should we move this to .NET 10 or put it in .NET 9? We don't have a milestone currently.

**Comment by JeremyKuhne** [comment]
We've done the ones we expect to see that we can handle.
