### ISSUE TITLE
AccessibilityInsight: An on-screen element must not have a null BoundingRectangle property when ListView has DataBinding

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9125]
### .NET version

.NET 8.0.100-preview.5.23261.16

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in previous .Net 7.0 and 6.0.

### Issue description

AccessibilityInsight detects an error about "An on-screen elememt must not have a null BoundingRectangle property" for ListView with DataBinding, and in Inspect, ListView has extra Image for every ListItem in UIA hierarchy
This issue doesn't repro ListView without DataBinding.

**.Net 8.0 in AccessibilityInsight:**
![image](https://github.com/dotnet/winforms/assets/26474449/b108df72-6629-44d8-be3f-200264c1fb4a)

**.Net 8.0 in Inspect:**
![image](https://github.com/dotnet/winforms/assets/26474449/302ced9e-6bc9-4fc6-899c-f7fe7d40910b)

**.Net 7.0 in AccessibilityInsight:**
![image](https://github.com/dotnet/winforms/assets/26474449/46431950-244d-4f9f-a727-323d7f2fe402)

**.Net 7.0 in Inspect:**
![image](https://github.com/dotnet/winforms/assets/26474449/db5ceb48-44a2-4192-8361-31285528704f)

### Steps to reproduce

**Repro steps:**
1.	Create a Winforms .Net Core application with ListView added
2.	Create a DataSet with TableData by code
3.	Bind this DataSet table data to ListView
4.	Build and run application 
5.	Use AccessibilityInsight to detect this ListView

or use attached sample application:
[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/11483200/WinFormsApp1.zip)

**Comment by MelonWang1** [comment]
Verified this issue in the latest .NET 8.0 SDK build: 8.0.100-preview.6.23315.26, it was fixed. Screenshot as below:
Accessibility Insights:
![acce](https://github.com/dotnet/winforms/assets/94418985/677a3f59-14e0-4186-8e4c-816578ccfe4b)
Inspect:
![inspect](https://github.com/dotnet/winforms/assets/94418985/b6f33501-1831-4295-a039-1a5b256f21e6)

**Comment by Ashley-Li** [comment]
Verified with .NET SDK 8.0.100-preview.6.23328.9 test pass build, this issue was fixed, test result is same as above screenshot.
