### ISSUE TITLE
Control._reflectParent is not updated when Parent changes (memory leak)

### ISSUE THREAD

**Issue by rickbrew** [dotnet/winforms#9143]
### .NET version

.NET 7.0.5 (latest public release)

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

I don't think this is a regression, it was probably always like this. I've never needed to worry about this in the past -- my use of `Control`s did not include reparenting until now.

### Issue description

The `Control._reflectParent` field points to a control's parent control. It is updated by calling `set_ReflectParent` via
`UpdateReflectParent()`, which is called by `CreateHandle()`, `Dispose(bool)`, and `OnHandleDestroyed(EventArgs)`.

Notably absent from that list is `OnParentChanged()` (or any method to that effect). This means that `_reflectParent` is not set to `null` when a control is removed from its parent, nor is it updated when the control is added to a new parent.

Here is the ILSpy analysis tree for `_reflectParent` :

<img width="421" alt="image" src="https://github.com/dotnet/winforms/assets/10873410/1e65aa0d-2de6-4ff3-a186-f7101d39a4fc">

This results in a memory leak if a control is re-used, which is something I'm doing in Paint.NET to implement a large memory use optimization. This optimization depends on a control's `Handle` _not_ being recreated during a reparenting operation (which does work fine).

In SciTech Memory Profile we can see this clearly. In this case, the `CanvasControlImpl` (child) has been removed from the `CanvasControl` (parent), but it (child) still has a reference to it (parent) whether it (child) has been reparented yet or not. The yellow exclamation mark indicates that `CanvasControl` is disposed.

<img width="319" alt="image" src="https://github.com/dotnet/winforms/assets/10873410/ece13987-9f16-49d0-bdf0-eb36fa3b8f2b">

I don't know if there are other behavioral bugs that result from this -- `ReflectParent` only seems to be read by `OnParentHandleRecreated()`.

### Steps to reproduce

1. Create two `Controls`, `c1` and `c2`
2. Add `c1` to a `Form`
3. Add `c2` as a child of `c1`
4. Show the form
5. Remove `c2` from `c1`
6. Inspect `c2._reflectParent`. It should be `null`, but it still references `c1`.

**Comment by rickbrew** [comment]
cc @JeremyKuhne as requested https://twitter.com/Tofudebeast/status/1660084410094604289

**Comment by elachlan** [comment]
Nice find!

**Comment by Nora-Zhou01** [comment]
@rickbrew We have made some attempts but we don't seem to find the most accurate sample app, could you please provide the sample project, thanks in advance.

**Comment by rickbrew** [comment]
> @rickbrew We have made some attempts but we don't seem to find the most accurate sample app, could you please provide the sample project, thanks in advance.

I'm not sure I understand ... @JeremyKuhne landed a fix for this in #9159. What is it exactly that you need from me? Like a minimal repro? As in, a Visual Studio project you can run that will reproduce the issue?

**Comment by JeremyKuhne** [comment]
@Nora-Zhou01 there really isn't much of value you can do to repro- I added a unit test that does this.

Apparently, I didn't mark my PR correctly. I'm closing this now.
