### ISSUE TITLE
TypeLoadException on System.Windows.Forms.Control.SetAcceptDrops in DotNet 8 Preview 4 when Trimming

### ISSUE THREAD

**Issue by fitdev** [dotnet/winforms#9155]
### .NET version

8.0.100-preview.4.23260.5

### Did it work in .NET Framework?

No (Not applicable)

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works fine in DotNet 7.

### Issue description

During runtime, after I publish my app as a self-contained, trimmed (does not matter the mode) executable, I get the following error even before any form is shown:

```
System.TypeLoadException
   at System.Windows.Forms.Control.SetAcceptDrops(Boolean)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs)
   at System.Windows.Forms.Control.WmCreate(Message&)
   at System.Windows.Forms.Control.WndProc(Message&)
   at System.Windows.Forms.ScrollableControl.WndProc(Message&)
   at System.Windows.Forms.ContainerControl.WndProc(Message&)
   at System.Windows.Forms.Application.ParkingWindow.WndProc(Message&)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message&)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&)
   at System.Windows.Forms.NativeWindow.Callback(HWND, WM, WPARAM, LPARAM)
```

### Steps to reproduce

1. Mae a simple WinForms app with a User Control in it on the main form.
2. Publish with trimming enabled.

**Comment by elachlan** [comment]
Related: #4649

**Comment by merriemcgaw** [comment]
I'll move to .NET 9 since we're not going to close on #4649 in .NET 8

**Comment by fitdev** [comment]
But this is critical! I mean it has worked in DotNet 7 just fine, so it appears to be a regression and a very important one to address. Right now it means no trimming support at all for WinForms, since all but the most trivial apps do make use of User Controls. Is there a chance to address the User Control aspect of it still in time for DotNet 8?

Or at least, perhaps you could advise if it would be possible to still trim the app assembly-wise, by excluding certain assemblies, like the app itself, WinForms assemblies presumably and perhaps some others?

**Comment by cyanfish** [comment]
With .NET 8 you can set TrimMode to partial, which will probably fix it:
https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0#trimming-granularity

**Comment by fitdev** [comment]
Thanks for the suggestion @cyanfish 

As a temporary workaround, I instead added: `<TrimmerRootAssembly Include="System.Windows.Forms" />` and `<TrimmerRootAssembly Include="System.Windows.Forms.Primitives" />` to `ItempGroup` and that seems to have "fixed" it albeit at a cost of a huge size of WinForms dlls.

**Comment by JeremyKuhne** [comment]
We do not officially support trimming in WinForms as there are a variety of scenarios that do not work and are unlikely to get addressed in the near term. Most notably we have dependencies on `BinaryFormatter` for OLE (clipboard, etc.). We also cannot do data binding in a trim-safe way.
