### ISSUE TITLE
The part of "Today" date in DateTimePicker is not highlight

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#9156]
### .NET version

.NET 8.0.100-preview.5.23269.37

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it also repro in .NET7.0 & 6.0 & 5.0 & 3.1.

### Issue description

As you can see on the screenshot, the number '023' is not highlighted when hover over "Today":
![88](https://github.com/dotnet/winforms/assets/94418985/c6c6fd1d-d2d9-4d08-9655-4c59cdc47884)

### Steps to reproduce

1. Create a winforms .net core project with a DataTimePicker control
2. Build and run
3. Expanded DataTimePicker control
4. Mouse hover over “Today” and observe it

**More info:**
1. This issue also repro on .NET7.0, .NET6.0, .NET5.0, .NET3.1.
2. This issue also repro on framework project.
3. This issue also repro in MonthCalendar control.
4. The initial feedback ticket is: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1822667

**Comment by JeremyKuhne** [comment]
Nice bug! Yes, this isn't something we're able to fix unfortunately.
