### ISSUE TITLE
A11y_.NET Core_WinForms_MainForm_ConmonControl1_Keyboard : The Date Picker button is not Accessible by Keyboard

### ISSUE THREAD

**Issue by Ashutoshsahoo164** [dotnet/winforms#9161]
### .NET version

Microsoft.Net SDK6.0.311 (x64)

### Did it work in .NET Framework?

No

### GitHubTags:
#A11yMAS;#A11yTCS;#BM_.NET Core-Win32-May2023;#.NET Core;#A11ySev2;#WCAG2.1.1;#DesktopApp;#Win11;#Benchmark;#keyboard

### Actual:

The Date picker button is not Accessible  by Keyboard.

### Expected:

The Date picker button should be accessible by keyboard.

### User Impact:

Keyboard Users will face difficulty in Accessing the Date picker control and Selecting the Date

### Steps to reproduce

1. Install and Open Winforms App
2. Main Form screen would appear.
3. Tab till "Common_Controls1:Testing the controls under the Common_controls"  and Hit enter.
4. Navigate to DataTimerPicker section.
5. Observe with keyboard that the Date picker button is not accessible by keyboard.

**Comment by JeremyKuhne** [comment]
@Olina-Zhang can you get more details on this and verify if this can be fixed on the application level?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang can you get more details on this and verify if this can be fixed on the application level?

@JeremyKuhne It is a dup of GH issue: https://github.com/dotnet/winforms/issues/3613, and the original AzDo bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1154531, which is won't fix since pressing Alt+down/F4 works for the DatePicker button of DateTimePicker, and Narrator can anounce the expand/collaspe state.

**Comment by Tanya-Solyanik** [comment]
This bug was triaged as a low priority(Sev3) issue. This drop down is opened using ALT+DOWN of F4 keys when navigating with the keyboard. See the duplicates mentioned by Olina.

**Comment by Ashutoshsahoo164** [comment]
I have verified the bug . The bug is fixed if we use the ALT+Down Arrow key.

GitHubTags:#Closed

Closing Attachment:
![Date picker solve1](https://github.com/dotnet/winforms/assets/85863895/735c1296-e5f7-464e-808f-f38e97809c09)
