### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by danmoseley** [dotnet/winforms#917]
I didn't see an issue for this already (feel free to close if there is one). Looks like coverage is less than 30%.
```
@@                 Coverage Diff                 @@
##              master        #914         +/-   ##
===================================================
- Coverage   28.94861%   28.94235%   -0.00626%     
===================================================
  Files           1083        1083                 
  Lines         294135      294133          -2     
  Branches       38407       38407                 
===================================================
- Hits           85148       85129         -19     
- Misses        204950      204965         +15     
- Partials        4037        4039          +2
```

@hughbe you've spent more time looking at the code/tests than many of us, how feasible do you think it is to get this number up? That would help increase confidence in the upcoming release, for sure - and make refactors less risky.

I wonder if the debt could be categorized somehow eg by namespace to make this easier to drive.

**Comment by zsd4yr** [comment]
We have a user epic issue tracking functional testing parity with Core. #672

We have about 100-200 apps which are used in testing automation using Maddog in the .NET FX, and we've had an enormous backlog item to get them driven by xunit and incorporated into our CI. 

As far as I know, this will not change the number above representing our Code Coverage but it will increase the surface area over which we test. @sharwell may have a better idea about that.

**Comment by zsd4yr** [comment]
For tracking down the areas for our code coverage, if you click any of the buttons for code coverage on the top-level README here: https://github.com/dotnet/winforms#code-coverage

You will be directed to an interactive dashboard showing what parts of our code have coverage in xunit tests. https://codecov.io/gh/dotnet/winforms

In particular, the outermost rings of the sunburst chart may be what you are looking for. **Click on it** For example, here is the sunburst for System.Windows.Forms src:

![image](https://user-images.githubusercontent.com/10677481/57158462-4f09a700-6d98-11e9-8314-21b733925832.png)


I would also recommend looking through the files tab https://codecov.io/gh/dotnet/winforms/tree/master/src

![image](https://user-images.githubusercontent.com/10677481/57158260-db679a00-6d97-11e9-8827-bc9d3ee4da18.png)

For example, by exploring the Files, you can hone in on that although System.Windows.Forms.Design has very low code coverage, that low code coverage is not really in Drawing/Design

![image](https://user-images.githubusercontent.com/10677481/57158343-0a7e0b80-6d98-11e9-9edf-32ceb275d0cf.png)

**Comment by zsd4yr** [comment]
> For tracking down the areas for our code coverage, if you click any of the buttons for code coverage on the top-level README here: https://github.com/dotnet/winforms#code-coverage
> 
> You will be directed to an interactive dashboard showing what parts of our code have coverage in xunit tests. https://codecov.io/gh/dotnet/winforms
> 
> In particular, the outermost rings of the sunburst chart may be what you are looking for. **Click on it** For example, here is the sunburst for System.Windows.Forms src:
> 
> ![image](https://user-images.githubusercontent.com/10677481/57158462-4f09a700-6d98-11e9-8314-21b733925832.png)
> 
> I would also recommend looking through the files tab https://codecov.io/gh/dotnet/winforms/tree/master/src
> 
> ![image](https://user-images.githubusercontent.com/10677481/57158260-db679a00-6d97-11e9-8827-bc9d3ee4da18.png)
> 
> For example, by exploring the Files, you can hone in on that although System.Windows.Forms.Design has very low code coverage, that low code coverage is not really in Drawing/Design
> 
> ![image](https://user-images.githubusercontent.com/10677481/57158343-0a7e0b80-6d98-11e9-9edf-32ceb275d0cf.png)

**Comment by Tanya-Solyanik** [comment]
Superseded by another item -  https://github.com/dotnet/winforms/issues/10453
