### ISSUE TITLE
Bounds for PrintPreviewControl and its accessible object don't match

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#9175]
### .NET version

.NET 8.0.100-preview.5.23274.2

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in .NET 6.0/7.0. Regression form: https://github.com/dotnet/winforms/pull/9136

### Issue description

Testapp: [testapp.zip](https://github.com/dotnet/winforms/files/11563155/testapp.zip)

.NET 8.0
![image](https://github.com/dotnet/winforms/assets/86937911/f83342cb-8025-4354-9e3e-6c16ea8fd211)

.NET 7.0
![image](https://github.com/dotnet/winforms/assets/86937911/b4e2145b-ff3f-49f0-884e-c324cfbe7ca5)

### Steps to reproduce

1. Create a WinForms .NET Core project.
2. Add a button and printPreviewControl control to form designer.
3. Double click button1 and type below code in function button1_Click.
```
AccessibleObject accessibleObject = printPreviewControl1.AccessibilityObject;
Rectangle rectangle1 = accessibleObject.Bounds;
Rectangle rectangle2 = printPreviewControl1.RectangleToScreen(printPreviewControl1.ClientRectangle);
```
4. Add a breakpoint at the end of the event, build and run the application.
5. Compare the values of rectangle1 and rectangle2.

**Comment by v-elnovikova** [comment]
This is the correct behavior. `Control.ClientRectangle` does not include non-client area, like scrollbars, but `AccessibleObject.Bounds` should include it, and that was the exact problem that PR #9136 was for.

So here `AccessibleObject.Bounds` should be equal to `Control.Bounds`, not `Control.ClientRectangle`:
![debug](https://github.com/dotnet/winforms/assets/113603457/269f2595-3b0a-402f-a372-344dd3e338a6)

**Comment by Philip-Wang01** [comment]
@v-elnovikova This is reasonable from your response. But [this PR ](https://github.com/dotnet/winforms/pull/9136)affects our automation test cases. This test case passed in .net framework 4.8/4.8.1, .net core 5.0/6.0/7.0.

**Comment by MandiMan** [comment]
Verified this on .NET8.0.100-preview.6.23281.16, issue was fixed,Bounds for PrintPreviewControl and its accessible object can be match and automation test case passed.
![image](https://github.com/dotnet/winforms/assets/108860782/2ca55fbe-eba6-4c94-806a-5b97d0607181)

**Comment by John-Qiao** [comment]
Verified this on .NET 8.0 TP build: 8.0.100-preview.6.23327.6, issue was fixed, result is same as above test result.
