### ISSUE TITLE
Failed to Clipboard.GetData() as the specified format

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#9180]
### .NET version

.NET 8.0.100-preview.5.23274.2

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works in .NET 6.0/7.0/8.0.100-preview5.23253.20. Maybe caused by: https://github.com/dotnet/winforms/pull/9088

### Issue description

Testapp: [Testapp.zip](https://github.com/dotnet/winforms/files/11572062/Testapp.zip)

.NET 8.0
![image](https://github.com/dotnet/winforms/assets/86937911/281bcb3c-3ec9-4f26-8b21-8f113dc4eae4)

.NET 7.0
![image](https://github.com/dotnet/winforms/assets/86937911/eb312cea-aab2-4f02-b255-5f60521144b2)

### Steps to reproduce

1. Create a WinForms .NET Core project.
2. Add a button control to form designer, double click button1 and type below code in function button1_Click.
```
Color c = System.Drawing.Color.Black;
string format = "testabc";
Clipboard.Clear();
Clipboard.SetData(format, c);
Clipboard.ContainsData(format);
object ob = null;
ob = Clipboard.GetData(format);
```
3. Add a breakpoint at the end of the event, build and run the application, click button1.
4. Observe the value of ob.

**Comment by elachlan** [comment]
@JeremyKuhne I guess you are still working through the binary formatter changes?

#6267

**Comment by JeremyKuhne** [comment]
This doesn't reproduce for me with the current bits when the `BinaryFormatter` is enabled, which it should be. When it is disabled, it returns null. @Philip-Wang01 can you debug with first chance exceptions to see if you're getting a NotSupportedException with the binary formatter?

Some notes on the BinaryFormatter being disabled:

Unfortunately, the OLE clipboard window always swallows errors when setting data (in `WM_RENDERFORMAT` it always returns an `LRESULT` of `0`). So setting always succeeds. If we try to get the data out it will fail with `CLIPBRD_E_BAD_DATA`, which we swallow. I've added some debug assistance around that in the #9195 PR.

I'm thinking through what we might be able to do to surface that the `BinaryFormatter` has been disabled and will likely create an issue to track soon.

**Comment by Philip-Wang01** [comment]
@JeremyKuhne I have built debug and release dlls under winforms repro. when I use the debug dll I get NotSupportedException with the binary formatter and the release dll does not get NotSupportedException. I also found that when I get NotSupportedException, clicking on the “Copy Details” gives an error message, is this the expected behavior?

https://github.com/dotnet/winforms/assets/86937911/64395837-b519-47bd-93ee-8519585850d5

![image](https://github.com/dotnet/winforms/assets/86937911/eb32e4b0-e6ed-408b-9821-f6f3f08ab517)

**Comment by Philip-Wang01** [comment]
Verified this test steps in the latest .Net 8.0 SDK build: 8.0.100-preview.6.23307.24, it was fixed. However, this issue still affects automated test cases and will be updated after investigation.
![image](https://github.com/dotnet/winforms/assets/86937911/2d8b4a98-c76d-4408-b597-3cad10a6d945)
Automation test cases:
![image](https://github.com/dotnet/winforms/assets/86937911/ca1704e2-5bb8-4ea9-bcf3-c1e896d3baf9)

**Comment by Philip-Wang01** [comment]
After investigation, the test cases failed for similar reasons as [9322](https://github.com/dotnet/winforms/issues/9322). 
This test case is not a "winforms application" because it does not have -    <UseWindowsForms>true</UseWindowsForms> and instead refereces winforms binaries directly.
It can be fixed when `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` is added in the project file.
But the status of this issue is still work in progress, @JeremyKuhne do we still need to keep the issue open?

**Comment by JeremyKuhne** [comment]
@Philip-Wang01 we don't need it open, I'm going to close it. Thanks for the heads up.
