### ISSUE TITLE
The next focus position is not correct when selecting on a ToolStripButton using mouse or typing "enter" keyboard and then typing "right or left" keyboard. 

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#9181]
### .NET version

.NET SDK 8.0.100-preview.5.23274.2

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

For .NET core 3.1 and .NET 5.0, the behavior is same as .NET framework: 
When typing Right keyboard, the next focus position is first item on the left. 
When typing Left keyboard, the next focus position is first item on the Right. 

For .NET 6.0/7.0/8.0, the behavior is: the next focus position is first item on the left, regardless of whether the right or left key is typed. 

### Issue description

When selecting on a ToolStripButton using mouse or typing "enter" keyboard and then typing "right or left" keyboard, the next focus position is first item on the left, regardless of whether the right or left key is typed. 
![ReproSteps](https://github.com/dotnet/winforms/assets/62929087/41a14002-002c-4f1c-b19d-3d7366eb3fa4)

### Steps to reproduce

1. Extract and open the test app. 
[TestApp.zip](https://github.com/dotnet/winforms/files/11572425/TestApp.zip)
2. Build and run this project.
3. Select on a ToolStripButton using mouse or typing "enter" keyboard.
4. Type "right or left" keyboard.

**Comment by Tanya-Solyanik** [comment]
@Amy-Li03  - this issue is happening only for `Checked` buttons, right?

**Comment by Amy-Li03** [comment]
@Tanya-Solyanik no, this issue also reproduced for `Unchecked `buttons.

**Comment by Tanya-Solyanik** [comment]
@dmitrii-drobotov  - If you had not started on this bug, please send it to @LeafShi1, @SimonZhao888 an @Epica3055

**Comment by MandiMan** [comment]
Verified this on latest .NET 8.0.100-preview.7.23362.29, issue was fixed. When typing Right keyboard, the next focus position is first item on the left, and if typing Left keyboard, the next focus position is first item on the Right.


https://github.com/dotnet/winforms/assets/108860782/c1e7f93c-2869-4f2c-be3f-104ee4c224a9

**Comment by Amy-Li03** [comment]
Verified this issue on .NET 8.0.100-preview.7.23376.3 build, it was fixed, test result is same as above.
