### ISSUE TITLE
Exception on keyboard layout switch with InvariantGlobalization

### ISSUE THREAD

**Issue by OwnageIsMagic** [dotnet/winforms#9191]
### .NET version

Microsoft.WindowsDesktop.App 7.0.5

### Did it work in .NET Framework?

Yes

### Issue description

```
Unhandled exception. System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'culture')
1049 (0x0419) is an invalid culture identifier.
   at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
   at System.Globalization.CultureInfo..ctor(Int32 culture, Boolean useUserOverride)
   at System.Windows.Forms.InputLanguage.get_Culture()
   at System.Windows.Forms.InputLanguageChangedEventArgs..ctor(InputLanguage inputLanguage, Byte charSet)
   at System.Windows.Forms.InputLanguage.CreateInputLanguageChangedEventArgs(Message m)
   at System.Windows.Forms.Control.WmInputLangChange(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by elachlan** [comment]
@Olina-Zhang is there enough information for your team to go off of here for repro?

**Comment by OwnageIsMagic** [comment]
@elachlan here is repro 
```sh
dotnet new winforms -o winformsInvariantRepro && cd winformsInvariantRepro
# add <InvariantGlobalization>true</InvariantGlobalization> to csproj
dotnet run
# change input language
```

**Comment by Olina-Zhang** [comment]
@OwnageIsMagic verified .Net 7.0 and 8.0 using above CLI, no exception:
![image](https://github.com/dotnet/winforms/assets/26474449/70518321-eabe-49e3-92fc-7c4be41ae59f)

**Comment by OwnageIsMagic** [comment]
@Olina-Zhang add additional input language to Windows here `ms-settings:regionlanguage` 
https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2
press `Shift + Alt` or `Shift + Ctrl` or `Win + Space` while `Form1` is focused.
![img](https://github.com/dotnet/winforms/assets/10534634/65333a24-a0f5-4170-b38c-cda4964179e4)

**Comment by OwnageIsMagic** [comment]
@elachlan problem is obvious from stacktrace provided
`Control.WmInputLangChange(ref Message m)` creates `InputLanguageChangedEventArgs`

https://github.com/dotnet/winforms/blob/761aebdbcb4fa9e206adb838ad056547b434efc4/src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangedEventArgs.cs#L35-L38
 calls `InputLanguage.Culture`  which passing LCID to `CultureInfo` `.ctor`
https://github.com/dotnet/winforms/blob/761aebdbcb4fa9e206adb838ad056547b434efc4/src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs#L30
that ends up here
https://github.com/dotnet/runtime/blob/73cb995cff35b053d5b0d3daf319ac33769657d0/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs#L860-L872

**Comment by elachlan** [comment]
@DJm00n is your PR touching this stuff?

**Comment by DJm00n** [comment]
@elachlan no, it shouldn’t. It seems related to [this](https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/6.0/culture-creation-invariant-mode) breaking change. I can include a fix into my PR and return InvariantCulture from InputLanguage.Culture in globalization-invariant mode.

**Comment by OwnageIsMagic** [comment]
@elachlan the line is mostly the same for since 2018
https://github.com/dotnet/winforms/blame/a7ca739d35a6369a10d50fb3d7e39c2aeb9dd620/src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs#L43
The problem is that `InvariantGlobalization` need special handling: with it enabled there is only 1 predefined `CultureInfo` instance (`CultureInfo.Invariant`)
possible workaround is to guard InputLanguage.Culture with check for InvariantGlobalization

**Comment by OwnageIsMagic** [comment]
https://github.com/dotnet/runtime/issues/81429

**Comment by OwnageIsMagic** [comment]
There is potential workaround using `PredefinedCulturesOnly` https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization#predefined-cultures , but it only checked for from string ctor
see
https://github.com/dotnet/runtime/blob/182591af3ea67a09bca7e0516b950dafce71d5a6/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs#L860-L872
and
https://github.com/dotnet/runtime/blob/182591af3ea67a09bca7e0516b950dafce71d5a6/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.cs#L670-L682

**Comment by elachlan** [comment]
@OwnageIsMagic thanks for the explaination.

@DJm00n if your code is touching that area, then it might be a good idea to fix it whilst you are working on it.

**Comment by OwnageIsMagic** [comment]
@elachlan can you move [this](https://github.com/dotnet/winforms/issues/9191#issuecomment-1567569773) comment to new issue in dotnet/runtime?

**Comment by elachlan** [comment]
@OwnageIsMagic thanks! Yeah I am just a community member. Feel free to link the opened issue here.

**Comment by OwnageIsMagic** [comment]
@elachlan @DJm00n This issue can now be worked around by setting `<PredefinedCulturesOnly>false</PredefinedCulturesOnly>`.
On WinForms side we can lazy init this property, since we store `InputLanguage` from which this property value comes.
It's not used internally.
https://source.dot.net/#System.Windows.Forms/System/Windows/Forms/InputLanguageChangedEventArgs.cs,5bdc3016f89c5e99,references

**Comment by merriemcgaw** [comment]
@OwnageIsMagic and @elachlan you guys did all the work for us 😸 . Thanks a ton!
