### ISSUE TITLE
Click events getting lost when pressing Space keyboard continuously to toolStripButton

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9199]
### .NET version

.Net 8.0 SDK build: 8.0.100-preview.6.23280.8

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

After the PR: https://github.com/dotnet/winforms/pull/9115, the control type for checkable/checked `toolStripButton ` is changed from `Button `to `CheckBox`, so Narrator should announce the check/uncheck state when using keyboard or mouse to change state, the PR is: https://github.com/dotnet/winforms/pull/9142.

The problem is Screen readers: Narrator/JAWS/NVDA cannot announce the check/uncheck state continuously when pressing **Space** keyboard continuously to checkable/checked `toolStripButton`.  Cannot reproduce it for standalone `checkBox` control using keyboard.
![Issue1_CheckStateChange](https://github.com/dotnet/winforms/assets/26474449/2ba3521d-c236-486b-a307-8003acb9b3eb)

This issue doesn't repro when using **mouse** to change check/uncheck state of toolStripButton continuously

### Steps to reproduce

1. Create a Winforms .Net application with ToolStrip, 
2. Add a ToolStripButton, set its CheckOnClick propterty to True
3. Build and run
4. Launch Narrator, use keyboard to focus on this ToolStripButton
5. Press **Space** keyboard continuously to checkable/checked `toolStripButton`

[WinFormsApp14.zip](https://github.com/dotnet/winforms/files/11610360/WinFormsApp14.zip)

**Comment by Olina-Zhang** [comment]
Here is the comment from @dmitrii-drobotov :
_I can see it's also reproduced in .NET 8, and the button is actually not clicked when pressing space continuously, without Narrator it's visible that it doesn't change from checked to unchecked or back. I also confirmed it by adding a method to button's Click handler, and it was called only on a first space press. So it's expected that Narrator doesn't announce checked/unchecked in this case, but the problem is that Narrator's focus rectangle stays on button, when in fact it's not focused on button anymore._

**Comment by merriemcgaw** [comment]
I agree with @dmitrii-drobotov and will update this issue. This may be related to the other #9243

**Comment by Amy-Li03** [comment]
Hi @v-elnovikova, verified this on .NET 8.0.100-preview.7.23356.13 from main branch, now Narrator can announce "checked" "unchecked" when pressing Space keyboard continuously to checkable/checked toolStripButton.
![IssueFixed](https://github.com/dotnet/winforms/assets/62929087/dd4d3ef7-1e84-4f43-a7bd-80a37d281742)

But after using mouse to change check/uncheck state of toolStripButton, then pressing Space keyboard, Narrator cannot announce "checked", "unchecked".
![NewIssue](https://github.com/dotnet/winforms/assets/62929087/47706c77-2c08-4aa2-aa1b-28ef10ebb358)

**Comment by Amy-Li03** [comment]
We don't have a tracking issue, will create a new issue for it later.

**Comment by John-Qiao** [comment]
Verified this issue in the .NET 8 Preview 7 build: 8.0.100 -preview.7.23376.3, it was fixed that: result same as above Amy's test result.
