### ISSUE TITLE
Add InternalsVisibleTo to System.Windows.Forms.Design and System.Windows.Forms.Design.Editors

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#92]
As per feedback received from @ericstj we should avoid using IVT even for test code.

**Comment by zsd4yr** [comment]
Discussed within the internal team today. We are not removing this and instead allowing it to be added to other binaries. Testing publics is the ciritcal, yet we should also allow testing internals. Changing the issue name to correspond with the new strategy.
