### ISSUE TITLE
.NET 8.0 Preview 3 Winforms application doesn't quit on shutdown or logoff

### ISSUE THREAD

**Issue by epikgit** [dotnet/winforms#9210]
### .NET version

.NET 8.0 Preview 3

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, the code works well in .NET 7.0 and previous.

### Issue description

I created a simple Winforms application written in C# with VS Professional 2022 (64-bit) version 17.6.2.4 and .NET 8.0 Preview 3
The application contains an empty form that does nothing.
If I try to shutdown Windows the system stucks and tells me: "This app is preventing shutdown".
The Windows system is Windows 10 Pro (v. 10.0.18362) but the behaviour is the same in Windows 11 too.

### Steps to reproduce

Create an empty Winforms application targeting .NET 8.0 Preview 3.
Compile in release, execute, and shutdown Windows.

**Comment by elachlan** [comment]
@Olina-Zhang Could your team please test this?

**Comment by MelonWang1** [comment]
@elachlan Verified this issue in .NET 8.0 Preview 6 on win10 21h1, WinForms application and WPF all can repro this issue. But there is a difference. Please see below screenshot:
![111](https://github.com/dotnet/winforms/assets/94418985/e305c5a4-9c11-4a5c-ba89-9c93922b6957)

In WinForms app, this issue also repro in .NET 8.0/7.0/ 6.0/5.0/3.1. And the framework app behavior is same as .NET 7.0.
![22](https://github.com/dotnet/winforms/assets/94418985/a9133099-dcef-4383-8065-8051e3982131)

The windows self-contained software Media Player, Paint and File Explorer behavior as below:
Media Player will shut down immediately.
Paint, File Explorer will displays "This app is preventing shutdown".
![windows](https://github.com/dotnet/winforms/assets/94418985/c9925582-a42f-4bbe-b926-7aab948981ff)

**Comment by tbolon** [comment]
@MelonWang1 I suggest you try to reproduce the problem without running the app inside visual studio (with debugger attached) if you have done so. Instead, run it directly from the .exe in the Release folder. There is a different behavior when VS is running, where it will ask if you want to stop debbuging.

**Comment by epikgit** [comment]
> @MelonWang1 I suggest you try to reproduce the problem without running the app inside visual studio (with debugger attached) if you have done so. Instead, run it directly from the .exe in the Release folder. There is a different behavior when VS is running, where it will ask if you want to stop debbuging.

I agree with you @tbolon, the test with VS debugger can be misleading.
The outcome of my tests are different from the @MelonWang1 ones probably because I tested the issue directly with executable files compiled in Release mode and not with VS debugger attached.
My test with .NET 7 told me there is no problem at all, while my test with .NET 8 preview told me the shutdown regularly stops because the executable refuses to exit at WM_QUERYENDSESSION.

**Comment by merriemcgaw** [comment]
@MelonWang1 can you test .NET 7 on Win11 one machine, and .NET 8 on a different Win11 box? We'd like to make sure it's a clean test and that it's the latest generally available Windows update.

**Comment by MelonWang1** [comment]
Verified this issue in .NET8.0 on Win11 21h2 machine, run .exe in the Release folder, then shut down windows, it will show "This app is preventing shutdown".

https://github.com/dotnet/winforms/assets/94418985/97e47f06-0be6-489a-aa56-b3f5981dea05


In .NET7.0 on another Win11 21h2 machine, run .exe in the Release folder, then shut down windows, the windows will close immediately.

https://github.com/dotnet/winforms/assets/94418985/9b814966-6f12-4546-9d4d-2f22a0d49f70

**Comment by Rustaud** [comment]
Hello,

I have a similar problem with an application (WPF) that works perfectly with .NET version 7. 
With version 8 (preview 4) from time to time, when I quit my application (Application.Current.Shutdown()) from the main form, the application seems to close normally but if I restart it again I have problems because during the previous shutdown, the main window is invisible but remained active . After a bit of research, I realized that when the shutdown doesn't work properly, the application goes into the background process in the task manager. 

OS : Win11 22H2

Best regards,
Thierry

**Comment by elachlan** [comment]
@Rustaud please raise an issue in the WPF github (https://github.com/dotnet/wpf). Then link the created issue here in case it is caused by the same problem.

**Comment by merriemcgaw** [comment]
@JeremyKuhne can you take a look at this to determine what might be different between .NET 7 and .NET 8?

**Comment by lonitra** [comment]
Tried to repro this with both WPF and WinForms apps targeting NET 8 and this only repros for WinForms. I am suspicious that for some reason we are getting a cancel is coming from [Form.RaiseFormClosingOnAppExit](https://github.com/dotnet/winforms/blob/65bc7b4786df818a74aba2dbdb6b9553418b840d/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs#L4659)

**Comment by Nora-Zhou01** [comment]
Verified this in main branch (.NET 9.0 alpha branch) on Win11 21h2 machine, run .exe in the Release folder, then shut down windows, the windows will close immediately.

https://github.com/dotnet/winforms/assets/104609169/2578b7aa-e121-4299-9853-5bc4caac3afe

**Comment by Ashley-Li** [comment]
Verified this issue on .NET 8.0.100-RC.2.23431.5, it was fixed, run .exe in the Release folder, then shut down windows, the windows will close immediately.
![PRTest](https://github.com/dotnet/winforms/assets/56664234/7165bd2e-aa43-4a84-803e-9da0de8daec7)

**Comment by MelonWang1** [comment]
Verified with .NET SDK 8.0.100-rc.2.23477.19 test pass build, this issue was fixed, run .exe in the Release folder, then shut down windows, the windows will close immediately. Screenshot is same as above.
