### ISSUE TITLE
A11y_.Net Core_Winforms_MainForm_ConmonControl1_Keyboard : The Buttons present in the "Button Sections" are not having the proper functionality

### ISSUE THREAD

**Issue by Ashutoshsahoo164** [dotnet/winforms#9226]
### .NET version

Microsoft.Net SDK6.0.311 (x64)

### Did it work in .NET Framework?

No

### GitHubTags:
#A11yFunctional;#A11yTCS;#BM_.NET Core[Winforms]-Win32-May2023;#.NET Core;#DesktopApp;#Win11;#Benchmark;#keyboard

### Actual:
The Buttons like "Flat" , "Popup" , "Standard" , "System" , "Auto Size True" , "Auto Size False" Are not performing any functionality when activated using keyboard.

### Expected:
The Buttons when activated using keyboard , should have proper functionality so that user can Consume the productivity.

### User Impact:
Keyboard Users will face difficulty and be confused with the functionality of the buttons when they will navigate using keybaord.

### Steps to reproduce

1. Install and Open Winforms App
2. Main Form screen would appear.
3. Tab till "Common_Controls1:Testing the controls under the Common_controls" and Hit enter.
4. Navigate to Button section.
5. Observe with keyboard that few buttons are not having proper functionality.

### Attachment:
![Button Section Not Accessible](https://github.com/dotnet/winforms/assets/85863895/5da07a10-b5a6-42ae-bfc4-00aa619cec7b)

**Comment by Amy-Li03** [comment]
We add these buttons on from designer and set some properties for them, don't add any keyboard event, so there is no performing functionality when activated using keyboard.

**Comment by Ashutoshsahoo164** [comment]
As per the above mentioned comment closing this bug.
