### ISSUE TITLE
A11y_.Net Core_Winforms_MainForm_Resize : While Resizing the Screen to 200% all the Button Names, Texts are getting truncated.

### ISSUE THREAD

**Issue by Ashutoshsahoo164** [dotnet/winforms#9230]
### .NET version

.NET-SDK-8.0.100-preview.4.23260.5

### Did it work in .NET Framework?

No

### GitHubTags:
#A11yMAS;#A11yTCS;#BM_.NET Core[Winforms]-Win32-May2023;#.NET Core;#A11ySev2;#WCAG1.4.4;#DesktopApp;#Win11;#Benchmark;#Zoom;

### Pre Requisite:

1. Change the Resolution to 1280*768
2. Increase the Text Size to 200%

### Actual:
When the screen is zoomed to 200% , all the button Labels are getting truncated. 

**Note :** This Issue is present through out the Application

### Expected:
At 200% zoom all the contents must be visible properly without any truncation.

### User Impact:
Users who use zoom functionality to navigate through the UI will face difficulty in seeing the Button Names.

### Steps to reproduce

1. Install and Open Winforms App
2. Main Form screen would appear.
3. Apply Resize and Observe the Issue. 

### Attachment:
[9230_A11y_.Net Core_Winforms_MainForm_Resize.zip](https://github.com/dotnet/winforms/files/11659388/9230_A11y_.Net.Core_Winforms_MainForm_Resize.zip)

**Comment by MandiMan** [comment]
@merriemcgaw This problem is reproduced when increasing the text size to 200%, But when set machine as 200%DPI, the display is normal. 
Increase the Text Size to 200%:
![image](https://github.com/dotnet/winforms/assets/108860782/7c9e1a4f-0900-41ed-9218-4e7e110f73fd)

Set machine as 200%DPI:
![image](https://github.com/dotnet/winforms/assets/108860782/0cfd6eec-5fd9-4fc3-9a0c-4d85c4b9ff5b)

**Comment by merriemcgaw** [comment]
@Ashutoshsahoo164 only one needs to be supported, the font scaling OR the DPI Scaling. WinForms only supports the DPI scaling. This is by-design.

**Comment by Ashutoshsahoo164** [comment]
I have verified the bug. The bug is not repro in DPI Scaling. Closing this bug.
![MicrosoftTeams-image (1)](https://github.com/dotnet/winforms/assets/85863895/3a5eb2aa-9e47-4826-b3a5-6c62ef071b96)

GitHubTags:#Closed;
