### ISSUE TITLE
ToolStripButton OnClicked handler is not called if be clicked when the app has no focus

### ISSUE THREAD

**Issue by panxn** [dotnet/winforms#9240]
### .NET version

.NET6 and .NET7

### Did it work in .NET Framework?

Yes

### Issue description

My project is upgraded from .NET framework 47 to .NET6. `ToolBar/ToolBarButton` has to be replaced with `ToolStrip/ToolStripButton`.

![image](https://github.com/dotnet/winforms/assets/4163729/e5c8fd14-90dd-48bb-82f2-db979361b46c)

I created a sample app to reproduce the problem, there are one `ToolStrip` (three `ToolStripButton` in it) and one `Button`.

If the app is active (has focus), click any button, the event handler for "Clicked" gets called as expected.
If the app is not active, click `ToolStripButton`, the event handler is **not** called, it just active the app, then user has to click again to trigger the event handler. But `Button` still works for this scenario.

In .NET framework, `ToolBarButton` can work if the app is not active. Is it a bug or as design? Is there any way to make `ToolStripButton` keep same behavior as `ToolBarButton` used to do.

### Steps to reproduce

See above

**Comment by merriemcgaw** [comment]
@dmitrii-drobotov and @v-elnovikova can you take a first look and see if something jumps out at you.

**Comment by panxn** [comment]
I find [this article](https://learn.microsoft.com/en-us/archive/blogs/rickbrew/how-to-enable-click-through-for-net-2-0-toolstrip-and-menustrip), it works for the sample app but doesn't work in my project, still investigating.

**Comment by Epica3055** [comment]
Could you please tell me which .net framework version were you using?
because I tested it and I found that .net and .net framework worked the same.

**Comment by Zheng-Li01** [comment]
@elachlan, verified the issue on the latest .NET SDK 9.0.100-preview.7.24329.1 + private dlls built from dotnet/winforms main repo, the issue has been fixed when the **AllowClickThrough** property value setting as true, that the toolStripButton OnClicked handler is called after clicked it when the app has no focus as below screenshot.

**Before Fixed:**
![9240BeforeFix](https://github.com/dotnet/winforms/assets/38325459/09767f9e-22e9-4d67-8dff-47f854a72ef3)

**After Fixed:**
![9240AfterFix](https://github.com/dotnet/winforms/assets/38325459/1fc253b9-93cf-436e-973f-2e0ec902549a)

**Comment by Philip-Wang01** [comment]
Verified the issue with .NET 9.0.100-preview.7.24402.8 test pass build that the issue has been fixed, which have the same results as above.
