### ISSUE TITLE
A11y_.NET Core_WinForms_Print_Preference_Usability: Keyboard focus is going to the non-interactive text i.e "Layout" which is present on the top of the page.

### ISSUE THREAD

**Issue by HindujaArugula** [dotnet/winforms#9247]
### .NET version

.NET-SDK-8.0.100-preview.4.23260.5

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No response

### GitHubTags:
#A11yTCS;#BM_.NET Core[Winforms]-Win32-May2023;#.NET Core;#A11ySev4;#DesktopApp;#Win11;#NonBenchmark;#A11yUsable

### Actual:
Keyboard focus is going to the non-interactive text i.e. "Layout" which is present on the top of the page 

### Expected:
Keyboard focus is going to the non-interactive text i.e. "Layout" which is present on the top of the page 

### User Impact:
Keyboard only users will get confused if keyboard focus goes to non-interactive text i.e., "Layout".

### Attachment:
![keyboard focus](https://github.com/dotnet/winforms/assets/125462007/8a840c8e-16b5-48be-8cc8-6b024d02451a)

### Steps to reproduce

1. Install and Open "Winforms" App.
2. "Main Form" screen would appear.
3. TAB to "Printing_Controls:Testing the controls under Printing Tab" and press ENTER key.
4. TAB to "Print' button and press ENTER key.
5. Now "Printing from win32 application - Print" appears on the screen.
6. TAB to "More Settings" button and press ENTER key.
7. Now "Printing Preference" Screen will appear.
8.Now observe that Keyboard focus is going to the non-interactive text i.e., "Layout" which is present on the top of the page.

**Comment by merriemcgaw** [comment]
Another Common Dialog Printing issue. Since this is Sev4 I'm going to close it.

**Comment by 12-shweta** [comment]
Github tags: #Closed;
