### ISSUE TITLE
Remove redundant initialization

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#925]
From @danmosemsft
> We should have an issue to remove all these redundant field initializations. Oddly, Roslyn doesn't remove them.

https://github.com/dotnet/winforms/pull/914#discussion_r280598315

**Comment by merriemcgaw** [comment]
@AdamYoblick is there any tool you know of we can run to clean this up everywhere?

**Comment by AdamYoblick** [comment]
Stylecop is the one to use usually. Sam mentioned it in that PR, but I'm not sure that we enforce stylecop rules in the winforms build because most other repos don't do it as far as I know.

**Comment by elachlan** [comment]
@merriemcgaw, `CA1805: Do not initialize unnecessarily` is enabled on the code base. So I think that should close this issue? Unless there are other code analyzers that I am missing.

**Comment by RussKie** [comment]
Thank you for taking on the task of reviewing the backlog. 
Yes, this is done.

**Comment by merriemcgaw** [comment]
Yes, thank you VERY much @elachlan it is very much appreciated. 💯
