### ISSUE TITLE
[Multi-Monitor] ThreadExceptionDialog doesn't scaled well when DPI is differ

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9251]
### .NET version

.NET 8.0.100-preview.6.23307.24

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, the result on the latest 8.0 is different from .Net 7.0

### Issue description

ThreadExceptionDialog doesn't scaled well when application is in PerMonitorV2 mode and DPI is differ
The result on the latest 8.0 is different from .Net 7.0, but all aren't scaled well.

**.Net 8.0: from 100% primary monitor to 300% secondary monitor**

https://github.com/dotnet/winforms/assets/26474449/637fdfdb-49a7-4e57-9a04-e5b30d032cdb

**.Net 8.0: from 300% primary monitor to 100% secondary monitor**

https://github.com/dotnet/winforms/assets/26474449/f952cdb4-8467-41cd-83dd-179167fc21bd

**.Net 7.0: from 100% primary monitor to 300% secondary monitor**

https://github.com/dotnet/winforms/assets/26474449/1eb1296b-2cd5-482a-8349-4b61659361bb

**.Net 7.0: from 300% primary monitor to 100% secondary monitor**

https://github.com/dotnet/winforms/assets/26474449/597b6b79-523e-4e9f-9b88-0cad43de322c

### Steps to reproduce

**Repro steps:**
1. Create a Winforms .Net Core application with a button
2. Double click button to generate event
3. In the event, add following code to show ThreadException dialog
```
private void button1_Click(object sender, EventArgs e)
{
    using ThreadExceptionDialog dialog = new(new Exception("Really long exception description string, because we want to see if it properly wraps around or is truncated."));
    dialog.ShowDialog(this);
}
```
4. Do some testing between 2 different monitors

**Test application:** 
[WinFormsApp6.zip](https://github.com/dotnet/winforms/files/11685438/WinFormsApp6.zip)

**Comment by merriemcgaw** [comment]
Assigning to @dreddy-work for HDPI backlog.

**Comment by Tanya-Solyanik** [comment]
Please start investigating if this dialog can be converted to  Per Monitor V2, perhaps re-initialize the dialog when it receives the WM_)DPICHANGED message, but don't spend too much time on it. If this work takes more than 2 days, then change code to always start this dialog in SystemAware more.

**Comment by Olina-Zhang** [comment]
Verified this issue in the latest .Net 8.0 SDK build: 8.0.100-preview.7.23356.13, threadExpectionDialog is basically scaled well. But have an issue when expanding Details button in threadExpectionDialog on 300%DPI primary screen, then move to 100% secondary screen, and collapse Details button, the buttons at the bottom of this dialog are truncated as following screenshot:

![100%Secondary](https://github.com/dotnet/winforms/assets/26474449/23ef999f-47ae-46d1-a707-2cbf80679ee7)

Testing result: 300%DPI primary screen to 100%DPI secondary screen:

https://github.com/dotnet/winforms/assets/26474449/f334b889-31e0-4d68-a6d0-204aea48535c

Testing result: 100%DPI primary screen to 300%DPI secondary screen:

https://github.com/dotnet/winforms/assets/26474449/89b9ce8b-cf90-45f6-9c3e-b93aae56d219

@Tanya-Solyanik Do I need to open a separate issue about buttons truncation in that case?

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang  - yes, please open a new issue.
@LeafShi1  - please do not spend much time on that issue, but take a quick look to see if the dialog can perhaps be re-initialized after it receives the WM_DPICHANGED message.

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang - yes, please open a new issue.

Filed https://github.com/dotnet/winforms/issues/9449.

**Comment by Eudora-Li01** [comment]
Verified this issue in the .NET 8 Preview 7 build: 8.0.100 -preview.7.23376.3, it was fixed. Result same as above.
