### ISSUE TITLE
Extend WinForms Designer SDK by Root Designer functionality

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/winforms#9279]
This is an informative issue targeted at Custom Control and Designer Library providers.

Root Designers are needed in the WinForms Designer, to provide Designer functionality, which are not scoped to a single control, but for a top-level-document. For example, the Forms and UserControl designers in the WinForms Designers are root designers themselves. Root Designer support is also needed, to provide special design support, like for custom Report Designers.

We are primarily tracking this work in our internal WinForms Designer repository. This issue has rather informative purpose, to point our progress and plans, and what breaking changes in contrast to the .NET Framework root designer APIs we will expect.

- [x] **Refactoring of the Toolbox handling for .NET Components in the Out-of-Proc Designers.** Part of the required foundation for the implementation for Root Designer APIs is the refactoring of the Toolbox item handling.  PRs for that are pending and will be merged soon.
- [x] **Create Solution Templates for Root Designer solutions**, so the necessary Client- and Server-projects can get properly packed and loaded into both the client- and server-process at design time.
- [x] **Replicate `ToolboxItemFilter` attributes from NuGet-packaged and referenced components including Type and Project information, for correct filtering.
- [x] **API design process:** Conventionalize the principal approach for public surfacing APIs to provide custom toolbox item control, filtering, and the principal design surface at design time. Requirements need to be synced with our first- and third-party Partners and Control Library vendors. 
- [x] **Implement Rendering functionality and the required inter-process-communication**
- [x] **Support infrastructure for selection, overlays, adorners.**

## What are the principal challenges and difference the Designers?

Please read up on the Out-of-process Designer design principles for Control Designers first, to get a basic understanding about the architectural challenges:
https://devblogs.microsoft.com/dotnet/custom-controls-for-winforms-out-of-process-designer/

* Implementing Root Designer functionality requires document designers, each respective for the client (Visual Studio) and the server process (DesignToolsServer). 
* The Toolbox handling can only be happening on the client, and user-interaction with the toolbox needs to be communicated to the server process. To this end, a client-side document designer needs to be implemented and needs to be inherited from a proxy designer base class. (Details to be provided).
* The rendering of graphical content and design-adornments on the other hand, can only be happening at the server-side. This will be happening and controlled by a document designer which will implement the `IRootDesigner` interface. **Note**: Since the Toolbox handling need to be handled exclusively on the client-side, `IRootDesigner` and `IToolboxUser` cannot be implemented on the same designer base class. `IToolboxUser` needs to be implemented on the client-side Designer; both Designers need to be communicating between the processed with internal Designer infrastructure.
* The server-side root designer will not be able to use classic controls for the render-surface the same way it was possible for the in-proc-designer. The reason is, that due to inter-process-limitations, we need to send mouse-event information from the client to the server-side. We will provide a special Designer View via the SDK, with exact details yet to be determined.

We expect a Designer SDK preview (with API definitions subject to change) in the Visual Studio 17 time-frame.

Note: The work on this is an ongoing process, and we will provide more details when they become available. If you have specific questions around this topic, please get engaged in the discussion for this issue.

**Comment by GCAronChen** [comment]
Hi @KlausLoeffelmann , is there any progress about this work? Seems you have completed part of works.

Could we try a preview SDK to verify our framework design time features recently?

**Comment by KlausLoeffelmann** [comment]
We have release a preview of the SDK today.
Note, that you'll need Visual Studio 2022 17.9 Preview 3 to be in parity with the APIs.

**Comment by KlausLoeffelmann** [comment]
In the making. Let me see, if I can come up with something quick as a starter in the meantime. I need to talk to @adegeo about introducing docs for the SDK, anyway. But it'll be a while, and also happen iteratively.

**Comment by KlausLoeffelmann** [comment]
Closing this as done. @merriemcgaw FYI, and also note the Twitter discussion about this here:
https://x.com/loeffelmann/status/1749612000345485616?s=20

**Comment by GCAronChen** [comment]
> Let me see, if I can come up with something quick as a starter in the meantime.

That sounds great! ok, We will start to investigate it recently.
