### ISSUE TITLE
Add `ClickThrough` to `ToolStrip`/`MenuStrip` to bring behavior in-line with other controls.

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#9288]
### Background and motivation

There have recently been a couple of issues asking for this feature. 
- #9240
- #9277

Outline explaining the feature from associated blog post:
> ToolStrip classes do not support "Click Through" between forms. For more information on what click through is, I recommend reading https://daringfireball.net/2003/05/interface_details_itunes_vs_safari . In Windows, pretty much all applications use "click through," whereby if you have one window active and click on to another one, the mouse click activates the window and the click is processed by whatever control you had the mouse over.

https://learn.microsoft.com/en-us/archive/blogs/rickbrew/how-to-enable-click-through-for-net-2-0-toolstrip-and-menustrip

### API Proposal

```csharp
public class ToolStrip
{
   public bool ClickThrough { get; set; }

   protected override void WndProc(ref Message m)
    {
        base.WndProc(ref m);
        if (ClickThrough &&
            m.Msg == NativeConstants.WM_MOUSEACTIVATE &&
            m.Result == (IntPtr)NativeConstants.MA_ACTIVATEANDEAT)
        {
            m.Result = (IntPtr)NativeConstants.MA_ACTIVATE;
        }

    }
}
```

### API Usage

Enable/Disable the `ClickThrough` property to change the behavior.

### Alternative Designs

default value of property set to `false`

### Risks

If default is true, then behavior could change in existing applications.

### Will this feature affect UI controls?

Yes. Toolstrip will allow click through by default or at least allow click through after the developer enables it.

Unsure on accessibility impact.

Feature is not localizable.

**Comment by elachlan** [comment]
CC: @merriemcgaw

**Comment by elachlan** [comment]
Based on the blog we should probably also add it for `MenuStrip`.

**Comment by merriemcgaw** [comment]
Agreed on the `MenuStrip` for sure. Based on our current workload it's unlikely that we will get an implementation done before platform shutdown for .NET 8 - once we hit RC1 timeframe we're no longer able to add API Surface area. We've got another month or so, but this isn't the top of the priority stack. If you have an implementation PR you want to push, I can take the API proposal itself to the API review board. Otherwise, we might have to wait to get this in until .NET 9.

**Comment by elachlan** [comment]
Do you want a PR prior to API review? I am happy to do a PR either way. It seems quite straight forward.

**Comment by merriemcgaw** [comment]
@elachlan you are the absolute best! Go ahead and put up a PR and we'll review it before the API review so it's a simple matter to get it in.

**Comment by elachlan** [comment]
@merriemcgaw when is the next API review?

**Comment by merriemcgaw** [comment]
Sorry for the delay, I was on vacation. I'll talk to the team about this and do the internal review of the API structure on Weds and submit it for official review hopefully this week. I'll keep you posted. Marking as untriaged to make sure it shows up when we talk runtime later this week.

**Comment by merriemcgaw** [comment]
Sorry for the delay on this one. As a team, we want to take this. Timeline wise however, we are far too close to platform shutdown for .NET 8 and the teams have several very hot irons in the fire. We're going to branch soon for .NET 9, and will get it for the first round of reviews there.

**Comment by elachlan** [comment]
Understood. Sorry I didn't get it in sooner.

**Comment by terrajobst** [comment]
Reviewed and approved offline.
