### ISSUE TITLE
Ensure that Facade assemblies get dropped to both ref and lib folder in the package

### ISSUE THREAD

**Issue by Shyam-Gupta** [dotnet/winforms#93]
Got following feedback from Eric regarding Facade assemblies:

_"There was one special case for these facades that you will want to check, they use the property **IsRuntimeAndReferenceAssembly** in order to ensure that we use the same dll in both the ref and lib folder in the package."_

**Comment by AdamYoblick** [comment]
Yep, in progress. @zsd4yr is working on it with me :)

**Comment by zsd4yr** [comment]
@AdamYoblick this is done, yes?

**Comment by AdamYoblick** [comment]
:shipit:
