### ISSUE TITLE
Graphics.Clear not working with alpha 0 values

### ISSUE THREAD

**Issue by JPasterkampRotec** [dotnet/winforms#9301]
### Description

The `Clear(System.Drawing.Color color)` method of `System.Drawing.Graphics` does not set the RGB values correctly when a color with alpha 0 is used.

### Reproduction Steps

This unit test will fail:
``` csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Drawing;
using System.Drawing.Imaging;

[TestMethod]
public void ClearlyNotWorking()
{
    var image = new Bitmap(3, 3, PixelFormat.Format32bppArgb);
    
    Color initialColor = image.GetPixel(0, 0);
    Assert.AreEqual(0, initialColor.A);
    Assert.AreEqual(0, initialColor.R);
    Assert.AreEqual(0, initialColor.G);
    Assert.AreEqual(0, initialColor.B);
    
    using (var graphics = Graphics.FromImage(image))
    {
        // Color.Transparent is A=0, R=255, G=255, B=255
        graphics.Clear(Color.Transparent);
    }
    
    Color newColor = image.GetPixel(0, 0);
    Assert.AreEqual(Color.Transparent.A, newColor.A);
    // Expecting 255 on the RGB values, but actually they remain 0.
    Assert.AreEqual(Color.Transparent.R, newColor.R);
    Assert.AreEqual(Color.Transparent.G, newColor.G);
    Assert.AreEqual(Color.Transparent.B, newColor.B);
}
```

### Expected behavior

I expect all pixels in the bitmap to have exactly the color specified in the `System.Drawing.Graphics.Clear(System.Drawing.Color color)` method.

### Actual behavior

RGB values remain 0 when a color with alpha 0 is provided to the `System.Drawing.Graphics.Clear(System.Drawing.Color color)` method.

### Known Workarounds

You can work around this by:
- Locking the bitmap and getting the `BitmapData`.
- Manually changing all values in the data
- Unlocking the bitmap

### Configuration

Tested and found the issue in:
- .NET 7 console application 
- .NET Framework WPF application.

I'm on Windows 10 Pro 21H2 19044.2251 (x64), although I don't think that matters for this issue.

**Comment by elachlan** [comment]
@JeremyKuhne

**Comment by JeremyKuhne** [comment]
@JPasterkampRotec as this has been the behavior of GDI+ (and System.Drawing) we really can't change it. We could potentially create an overload that allows you to force it, but I don't see an easy way to do that with the existing GDI+ APIs. GDI+ just creates a SolidBrush with the color you specify and does a rectangle fill, so whatever Alpha you have is going to be respected. Note that there is also a special code path for metafiles.

We're always happy to look at proposed solutions, but I suspect that this would not be a trivial thing to implement. It is also something that would have to be community driven.

**Comment by JPasterkampRotec** [comment]
@JeremyKuhne Understandable, it would be nice to be warned about this in the documentation comment of the `System.Drawing.Graphics.Clear(System.Drawing.Color color)` method though.

------------------------------------------------

Here's a workaround for anyone that needs it:
``` csharp
public static unsafe void Clear(this Bitmap source, Color color, Rectangle? area = null)
{
	if (source is null) throw new ArgumentNullException(nameof(source));
	if (area.HasValue && !area.Value.FitsIn(source)) throw new ArgumentOutOfRangeException(nameof(area), $"The {nameof(area)} does not fit in the {nameof(Bitmap)} {nameof(source)}");
	// Make the area encompass the entire image when none is specified.
	if (area is null) area = new Rectangle(0, 0, source.Width, source.Height);

	BitmapData data = source.LockBits(
		area.Value,
		ImageLockMode.ReadWrite,
		source.PixelFormat);

	try
	{
		int bytesPerPixel = Image.GetPixelFormatSize(source.PixelFormat) / 8;
		byte* bytes = (byte*)data.Scan0;

		switch (source.PixelFormat)
		{
			case PixelFormat.Format24bppRgb:
				for (int y = 0; y < data.Height; y++)
				{
					for (int x = 0; x < data.Width; x++)
					{
						// Calculate index where the pixel bgr values start.
						int i = (y * data.Stride) + (x * bytesPerPixel);
						bytes[i] = color.B;
						bytes[i + 1] = color.G;
						bytes[i + 2] = color.R;
					}
				}
				break;
			case PixelFormat.Format32bppArgb:
				for (int y = 0; y < data.Height; y++)
				{
					for (int x = 0; x < data.Width; x++)
					{
						// Calculate index where the pixel bgra values start.
						int i = (y * data.Stride) + (x * bytesPerPixel);
						bytes[i] = color.B;
						bytes[i + 1] = color.G;
						bytes[i + 2] = color.R;
						bytes[i + 3] = color.A;
					}
				}
				break;
			default: throw new NotSupportedException();
		}
	}
	finally
	{
		source.UnlockBits(data);
	}
}

public static bool FitsIn(this Rectangle source, Bitmap image)
{
    if (image is null) throw new ArgumentNullException(nameof(image));
    if (source.Height < 0 || source.Width < 0 || source.X < 0 || source.Y < 0) 
        throw new ArgumentException($"All values of the {nameof(source)} {nameof(Rectangle)} must be positive", nameof(source));

    return source.X + source.Width <= image.Width
        && source.X >= 0
        && source.Y + source.Height <= image.Height
        && source.Y >= 0;
}
```

**Comment by elachlan** [comment]
@JPasterkampRotec I'd suggest looking at submitting a PR to provide the functionality if you think other people will find it useful.

**Comment by JeremyKuhne** [comment]
> @JPasterkampRotec thanks for the sample code! You're welcome to open a doc PR that clarifies that Clear is effectively "fill with a solid brush".  There is an edit button on the doc page that will let you do so.

>  I'd suggest looking at submitting a PR to provide the functionality if you think other people will find it useful.

@elachlan We generally caution people on opening PRs like this without an API that there has been consensus on. We don't want to unnecessarily waste people's time or disappoint them if there isn't agreement on moving forward. In this particular case it's a difficult thing to accomplish as there are so many supported pixel formats.

**Comment by JPasterkampRotec** [comment]
@JeremyKuhne I'm not really sure what a clear and short addition to the documentation to correctly describe this behavior would look like. It really needs to point out that the issues occur when using colors with an alpha of 0 or else people will still fall for the trap.

**Comment by JeremyKuhne** [comment]
I've made a proposal myself. Closing this issue.
