### ISSUE TITLE
How to disable row shifting when column is sorting in datatable

### ISSUE THREAD

**Issue by idmansourid** [dotnet/winforms#9303]
When it is sorted, when I give a value to the cell, the row moves. I don't want this to happen. I work with DataGridView and DataTable . (vb.net-vs2019)
This is a weakness in 'DataTable' or 'DataGridView'?
the biggest problem. Will this problem be solved in the future? In other versions of DataTable or DataGridView.
It would be great if it had an option named (orderFix).
How can this feedback be reported?
![20230609_155121 (1)](https://github.com/dotnet/dotnet-api-docs/assets/77550842/2808c114-ff4e-4512-aab7-d1eba83a41d4)

```
 Dim MyDataTable As New DataTable
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
     MyDataTable.Columns.Add("id")
        MyDataTable.Columns.Add("f1")
        MyDataTable.Columns.Add("f2")
        MyDataTable.Columns.Add("f3")
    MyDataTable.Rows.Add({"1", "a1", "b1", "c1"})
    MyDataTable.Rows.Add({"2", "a2", "b2", "c2"})
    MyDataTable.Rows.Add({"3", "a3", "b3", "c3"})
    dgv.DataSource = MyDataTable
'There is no difference between the two (Programmatic /NotSortable)
    dgv.Columns(0).SortMode = DataGridViewColumnSortMode.Programmatic' /NotSortable
    dgv.Columns(1).SortMode = DataGridViewColumnSortMode.Programmatic '/NotSortable
    dgv.Columns(2).SortMode = DataGridViewColumnSortMode.Programmatic' /NotSortable
    dgv.Columns(3).SortMode = DataGridViewColumnSortMode.Programmatic' /NotSortable
End Sub

 Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
    MyDataTable.DefaultView.Sort = "[f2] asc"
End Sub
```

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team take a look and see if there's any workaround for this? I have a sneaking suspicion this is the way it has always been in WinForms and is a built in limitation, so we wouldn't want to change that default behavior. If there's a workaround for @idmansourid it would be great.

**Comment by idmansourid** [comment]
Hi @merriemcgaw  Thank you for your attention
I saw the answer to this question written somewhere (MyDataTable.DefaultView..ToTable). But this answer is very, very illogical (because with this, all the data that causes filtering of the MyDataTable will be lost.) In my opinion, the connection between the DataTable and the DataGridView should be stable (due to the operation of several filters), but the sorting (or several sorting) should be for a moment.

**Comment by John-Qiao** [comment]
@idmansourid I didn't find a default property or method to achieve that in DGV control, but maybe you can try below workaround to sort only column f2 in an array and re-assign values to column f2.

```
    Dim MyDataTable As New DataTable
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        MyDataTable.Columns.Add("id")
        MyDataTable.Columns.Add("f1")
        MyDataTable.Columns.Add("f2")
        MyDataTable.Columns.Add("f3")
        MyDataTable.Rows.Add({"1", "a1", "b1", "c1"})
        MyDataTable.Rows.Add({"2", "a2", "b2", "c2"})
        MyDataTable.Rows.Add({"3", "a3", "b3", "c3"})
        dgv.DataSource = MyDataTable
        dgv.Columns(0).SortMode = DataGridViewColumnSortMode.Programmatic
        dgv.Columns(1).SortMode = DataGridViewColumnSortMode.Programmatic
        dgv.Columns(2).SortMode = DataGridViewColumnSortMode.Programmatic
        dgv.Columns(3).SortMode = DataGridViewColumnSortMode.Programmatic
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        'MyDataTable.DefaultView.Sort = "[f2] asc"

        Dim array1 As String() = New String(MyDataTable.Rows.Count - 1) {}

        For i As Integer = 0 To MyDataTable.Rows.Count - 1
            array1(i) = MyDataTable.Rows(i).Item(2).ToString()
        Next

        Array.Sort(array1)

        For i As Integer = 0 To MyDataTable.Rows.Count - 1
            MyDataTable.Rows(i).Item(2) = array1(i)
        Next

    End Sub
```

**Comment by merriemcgaw** [comment]
After discussion this behavior is by design when sorting a table. If I enter data into the sorted column that is out of order, the whole row would be out of the sort order. Perhaps you can remove sort mode when a value is entered in an existing row when the cell in the sort column has been addressed. This is not a bug in WinForms, I think you should be able to find a solution. @John-Qiao's suggestion is definitely an option for you.
