### ISSUE TITLE
Add SplitContainer to the integration test in DemoConsole

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#9329]
Please add an integration test for [Porting SplitContainerDesigner/SplitterPanelDesigner/SplitterDesigner. by dreddy-work · Pull Request #9320 · dotnet/winforms (github.com)](https://github.com/dotnet/winforms/pull/9320)

This PR provides a copy of our designer component in the runtime and thus enables developers to write their own IDE, like this one - [winforms/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface at main · dotnet/winforms · GitHub](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface).

Please add SplitContainer control to the MainForm.cs file. Feel free to select the most appropriate tab, or to add a new Tab.

**Comment by MelonWang1** [comment]
Verified this issue in the latest .NET 8.0 SDK build: 8.0.100-preview.7.23328.8 on winforms repo, it was fixed. The SplitContainer is in the DemoConsle  integration test. Screenshot as below:
![9329](https://github.com/dotnet/winforms/assets/94418985/95e34f6c-25ae-4ff9-aa76-8d711cdf07c8)

**Comment by Nora-Zhou01** [comment]
Verified this on .NET 8.0 TP build: 8.0.100-preview.6.23328.9, the SplitContainer is in the DemoConsle integration test. result is same as above test result.

**Comment by dmitrii-drobotov** [comment]
@MelonWang1 @Nora-Zhou01 I just noticed that if I try to move splitter left or right on this added SplitContainer in the DemoConsole app, the app crashes with a StackOverflowException. Can you also reproduce it? If yes, could you create an issue for it?

**Comment by Nora-Zhou01** [comment]
@dmitrii-drobotov  Yes, you are right, the DemoConsole application crashes when moving the SplitContainer splitter size. Created issue : https://github.com/dotnet/winforms/issues/9410
