### ISSUE TITLE
HeaderText cannot be gotten in DataGridColumnStyle class

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#934]
* .NET Core Version: 3.0.100-Preview6-011777
* Have you experienced this same bug with .NET Framework?: No

**MoreInfo:** This is a regression issue, cannot repro in .Net Core 3.0 SDK Preview5 build
**Problem description:**
1. Open attached Winforms .Net Core app
[WindowsFormsApp6.zip](https://github.com/dotnet/winforms/files/3151978/WindowsFormsApp6.zip)
2. Open Form1.cs file, and set breakpoint in following code:
![image](https://user-images.githubusercontent.com/26474449/57291512-769c9000-7074-11e9-9952-c6034231dc9b.png)
3. Build and run this application to check **col** value

**Actual behavior:** 
There is an error for getting HeaderText property, see following screenshot:
![image](https://user-images.githubusercontent.com/26474449/57291696-c67b5700-7074-11e9-9697-8a98140e1e39.png)

**Expected behavior:**
no error:
![image](https://user-images.githubusercontent.com/26474449/57291975-74870100-7075-11e9-9dd5-786f2fc8d634.png)

**Comment by hughbe** [comment]
Hmm, I don’t see any reference to `headerName` in DataGridColumnStyle: https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/DataGridColumnStyle.cs#L19

**Comment by dreddy-work** [comment]
@hughbe, Did you get a chance to debug this further?

**Comment by hughbe** [comment]
Not yet, will soon. I don't quite understand why it shows a compiler error (CS0103) in this pane!

**Comment by merriemcgaw** [comment]
@Olina-Zhang is this blocking any runtime customer scenarios?

**Comment by merriemcgaw** [comment]
@Olina-Zhang you might compile from the command line to see if there are any warnings or errors.

**Comment by Olina-Zhang** [comment]
@merriemcgaw, I don't know if this issue blocks the customer specific runtime scenario. It was found in our migrated RT core automation cases. If compile and run app from the command line, there is no warning and error. And just occur when debugging app in VS.

**Comment by Olina-Zhang** [comment]
@merriemcgaw @dreddy-work This issue cannot repro in .Net Core 3.0 3.0-100-preview6-012101 build from Master branch. We will track several builds for verification.

**Comment by Olina-Zhang** [comment]
Verified several builds, all cannot repro. Closing this issue.
