### ISSUE TITLE
Cannot get the DateTimePicker's Text value

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9363]
### .NET version

8.0.100-preview.7.23323.19

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro in previous .Net SDK version: 7.0, and doesn't work in .Net 6.0

### Issue description

Cannot get the DateTimePicker's Text value. 

**.Net 8.0 Preview 7:**
![image](https://github.com/dotnet/winforms/assets/26474449/6485eb69-dcda-44cc-a026-219aabe8626c)

**.Net 7.0:**
![image](https://github.com/dotnet/winforms/assets/26474449/a135420a-99eb-416f-8ab4-c53913d56d8a)

### Steps to reproduce

Sample app:
[WinFormsApp30.zip](https://github.com/dotnet/winforms/files/11859131/WinFormsApp30.zip)

**Comment by Epica3055** [comment]
It looks like by design. See the comments below.

https://github.com/dotnet/winforms/pull/9253#discussion_r1228062033



So you can make this happen by this:
![image](https://github.com/dotnet/winforms/assets/135201996/b0d7b268-051c-4732-8d92-52d2c1e534bb)

**Comment by Olina-Zhang** [comment]
But button's Text is gotten by same method:
![image](https://github.com/dotnet/winforms/assets/26474449/43644b36-9415-4257-9d30-527f70042d46)

**Comment by dmitrii-drobotov** [comment]
@Olina-Zhang did it work in .NET 6 and .NET Framework 4.8.1?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang did it work in .NET 6 and .NET Framework 4.8.1?

It doesn't work in .Net 6 and .Net framework 4.8.1,  corrected the issue template.

**Comment by dmitrii-drobotov** [comment]
The .NET 7 version returned correct `Text` value only for custom format, in other cases it didn't match displayed text on the DateTimePicker, so we had to roll it back. Now we have the same behavior as in .NET 6 and before: `Text` matches displayed value on DateTimePicker after its handle is created (for example in `Form.Shown` or later), but it's empty until that, for example in form's constructor. I think there's just no way to get correct `Text` for DateTimePicker for all formats at that step.

**Comment by Tanya-Solyanik** [comment]
@dreddy-work  - could you please add pointers on how to update the documentation for this change in behavior.

**Comment by dreddy-work** [comment]
Please open a doc issue here :https://github.com/dotnet/docs/issues and provide as much details/context as possible on the new behavior compared to old and reasoning.

**Comment by Epica3055** [comment]
@Tanya-Solyanik @dreddy-work We have created a doc issue here [35982](https://github.com/dotnet/docs/issues/35982).
