### ISSUE TITLE
Clickonce couldn't publish a rdlc report

### ISSUE THREAD

**Issue by Deny01** [dotnet/winforms#9368]
### .NET version

 .net 6.0     VS 2022 17.6.4

### Did it work in .NET Framework?

No

### Issue description

when i use clickonce publish a rdlc report  in a c# winform project at visual studio 2022 environment,get below message:Unable to apply publication properties for item 'report\*.rdlc',

### Steps to reproduce
after copy the rdlc report to target machine by hand, everything is ok.
...

**Comment by Tanya-Solyanik** [comment]
@Deny01  - please copy/paste this report into Visual Studio Feedback - https://learn.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022 in order for this issue to get forwarded to the right team. Winforms runtime does not own ClickOnce publishing in the designer.
