### ISSUE TITLE
Suggestion: run `dotnet  format` Over the whole codebase

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#937]
`dotnet format` is a global tool that takes an editor config file and cleans up all the code to match the style.

Talking to some of y’all at build, i know that it’s been quite hard for the team to review cleanup prs as it’s hard to differentiate automated cleanup and manual cleanup. The former comes at little risk but the latter may be breaking if something goes wrong (and even if there’s one bug, things can still break!!)

I propose either getting the bot to run `DotNet format` (or I can do it) and submit either a big PR or something split up to fix this

Thoughts?

**Comment by hughbe** [comment]
Url: https://github.com/dotnet/format

**Comment by RussKie** [comment]
I had the same idea 👍

**Comment by merriemcgaw** [comment]
Considering doing this right before we snap for Preview 7. @zsd4yr
