### ISSUE TITLE
PropertyGrid cannot get the ComboBox's items when setting PropertyGrid's selectedObject to ComboBox

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9389]
### .NET version

.Net 8.0 SDK: 8.0.100-preview.7.23328.8

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro in .Net 6.0. Regression from .Net 7.0.

### Issue description

When setting PropertyGrid's selectedObject to ComboBox, open String Collection Editor dialog in propertyGrid, there is nothing displayed for added items in ComboBox.
Cannot repro in other controls: ListBox/CheckedListBox.

**.Net 8.0/.Net 7.0 result:**
![image](https://github.com/dotnet/winforms/assets/26474449/f1f40896-9565-4d09-8fe9-f1dc85657dab)

**.Net 6.0 result:**
![image](https://github.com/dotnet/winforms/assets/26474449/7518c0c8-1dc8-4063-a345-8bcce876981e)

### Steps to reproduce

Use following sample application:
[WinFormsApp53.zip](https://github.com/dotnet/winforms/files/11902593/WinFormsApp53.zip)

**Comment by MandiMan** [comment]
Verified this on latest .NET 8.0.100-preview.7.23362.29, issue was fixed. When setting PropertyGrid's selectedObject to ComboBox, open String Collection Editor dialog in propertyGrid, all added items are displayed correctly.
![image](https://github.com/dotnet/winforms/assets/108860782/9be6a84d-a7d0-4d22-bfa4-47417731e05e)
