### ISSUE TITLE
The GridView's columns display incorrectly when setting PropertyGrid's selectedObject to GridView and slide the scrollbar in DataGridViewColumn Collection Editor dialog 

### ISSUE THREAD

**Issue by Ashley-Li** [dotnet/winforms#9392]
### .NET version

.Net 8.0 SDK: 8.0.100-preview.7.23328.8

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, cannot repro in .Net 6.0 and Net 7.0.

### Issue description

When setting PropertyGrid's selectedObject to GridView with Columns, open DataGridViewColumn Collection Editor dialog in propertyGrid, use the mouse to slide the scrollbar left and right to observe the Columns, the GridView's columns display incorrectly.
The issue also can repro in ListView control.

**.Net 8.0 result:**
![image](https://github.com/dotnet/winforms/assets/56664234/5fab052a-5b5d-4d71-a5d3-c3aa015c66b6)

**.Net 7.0/.Net 6.0**
When using the mouse to slide the scrollbar left and right, the GridView's columns display correctly.
![image](https://github.com/dotnet/winforms/assets/56664234/a3124009-9b1d-4de5-8b67-08281b89486e)

### Steps to reproduce

Use following sample application:
[WinFormsApp9.zip](https://github.com/dotnet/winforms/files/11903662/WinFormsApp9.zip)

https://github.com/dotnet/winforms/assets/56664234/a9324606-f2c2-4d4a-aa9d-44cc98f82ca9

**Comment by Philip-Wang01** [comment]
Verified this on .NET latest build: 8.0.100-rc.1.23369.12, issue was fixed. When using the mouse to slide the scrollbar left and right, the GridView's columns display correctly.

https://github.com/dotnet/winforms/assets/86937911/4c5f2a9a-7600-4d67-8d8c-007a5ccdc616

**Comment by Olina-Zhang** [comment]
Verified with .NET SDK 8.0.100-preview.7.23376.3 test pass build, this issue was fixed with above same verification result.
