### ISSUE TITLE
TreeView custom sort fails if TreeNode has child nodes

### ISSUE THREAD

**Issue by v-elnovikova** [dotnet/winforms#9394]
### .NET version

.NET 8.0.100-preview.7.23328.11

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes.
Regression after PR [#9078](https://github.com/dotnet/winforms/pull/9078)

### Issue description

`TreeView.TreeViewNodeSorter` instance is supposed to compare `TreeNode` objects, as described in [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.treeview.treeviewnodesorter?view=windowsdesktop-7.0):
> Gets or sets the implementation of IComparer to perform a custom sort of the TreeView nodes.

After PR #9078 TreeViewNodeSorter receives tree node text instead of the tree node itself, when sorting non-top level nodes.

Example from the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.treeview.treeviewnodesorter?view=windowsdesktop-7.0#examples) throws `NullReferenceException`:
![nullreferenceexception_treeview_custom_sorting](https://github.com/dotnet/winforms/assets/113603457/f9d6e770-8de3-4436-9062-d28dbf9bb33b)

### Steps to reproduce

1. Install .NET 8.0.100-preview.7.23328.11 or older
2. Create a Windows Form App (.NET) project and copy the code from [documentation example](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.treeview.treeviewnodesorter?view=windowsdesktop-7.0#examples) or open the [sample app](https://github.com/dotnet/winforms/files/11903966/ScratchProject.zip)
3. Run the app and click "Set Sorter" button.

**Comment by MelonWang1** [comment]
Verified this issue in the latest .NET 8.0 SDK build: 8.0.100-preview.7.23356.13, it was fixed. There is no exception when click "Set Sorter" button. Screenshot as below:

https://github.com/dotnet/winforms/assets/94418985/81e7ed8c-89c9-4503-b2bb-7d5a0b8facad

![屏幕截图 2023-07-06 200649](https://github.com/dotnet/winforms/assets/94418985/cda9cf3e-732b-46d4-89cd-e5380347a0e1)
