### ISSUE TITLE
Moving the SplitContainer splitter size at runtime crashes the DemoConsole application.

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#9410]
### .NET version

.Net 8.0 SDK: 8.0.100-preview.7.23328.8

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, This is the new SplitContainer integration test added to the DemoConsole application.

### Issue description

In Winforms repo, there has a [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app, the DemoConsole application crashes when moving the SplitContainer splitter size in .Net 8.0. But build and run the application in Release and Debug modes gives different results.

**Release mode：**

https://github.com/dotnet/winforms/assets/104609169/feef2f95-dd97-4f11-af12-3eb88433ac91

**Debug mode:**

https://github.com/dotnet/winforms/assets/104609169/62268dd9-7457-4224-8e33-f5d50eefa4d8

**Call stack:**
System.StackOverflowException
  HResult=0x800703E9
  Message=Exception of type 'System.StackOverflowException' was thrown.

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

### More Info

1. Resizing other controls or forms in the DemoConsole application also crashes.
2. Probably caused by the PR [9364](https://github.com/dotnet/winforms/pull/9364)

**Comment by elachlan** [comment]
The underlying bug is caused by #9341

**Comment by halgab** [comment]
Really sorry I let that slip through...

**Comment by elachlan** [comment]
It happens. It wasn't obvious to me either until I tested it. At least it was an easy fix!

**Comment by Eudora-Li01** [comment]
Verified this issue in the latest .NET 8.0 SDK build: 8.0.100-preview.7.23356.13 on winforms repo, it was fixed. SplitContainer splitter and other controls can be moved in size now.

https://github.com/dotnet/winforms/assets/130345015/00f3f6a5-4705-4b40-aa77-bdaefb748ad1

**Comment by Amy-Li03** [comment]
Verified this issue on winforms repo with DemoConsole test app from release/8.0-preview7 branch, it was fixed. Test result is same as above.
