### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.' occurs when delete button control then click undo in DemoConsole application

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#9412]
### .NET version

.NET 8.0.100-preview.7.23330.16

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it doesn't reproduce in .NET 7.0.

### Issue description

In Winforms repo, there has a [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app, System.NullReferenceException: 'Object reference not set to an instance of an object.' occurs when delete button control then click undo.
In .NET8.0:

https://github.com/dotnet/winforms/assets/94418985/f90cc598-5b3a-4eec-aa36-eaa601feda53

![undo-1](https://github.com/dotnet/winforms/assets/94418985/43dd7cf6-68e7-4144-80df-097376ddc23c)

**Call Stack:**
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Windows.Forms.Design
  StackTrace:
   at System.ComponentModel.Design.Serialization.ResourceCodeDomSerializer.SerializationResourceManager.GetMetadataEnumerator() in C:\test\winforms\src\System.Windows.Forms.Design\src\System\ComponentModel\Design\Serialization\ResourceCodeDomSerializer.SerializationResourceManager.cs:line 304

In .NET 7.0:

https://github.com/dotnet/winforms/assets/94418985/fa1d1fc2-b802-4e08-af7f-cc7f8d21b920

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by elachlan** [comment]
Have you been able to bisect it?

**Comment by MelonWang1** [comment]
@elachlan  This issue maybe caused by [#8332](https://github.com/dotnet/winforms/pull/8332)

**Comment by elachlan** [comment]
Thanks, I'll have a look.

**Comment by Ashley-Li** [comment]
Verified this on latest .NET 8.0.100-preview.7.23362.29, issue was fixed in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) project, there's no exception error when deleting button control then click undo.
![9412test](https://github.com/dotnet/winforms/assets/56664234/db6f8201-29d9-4479-8d3c-93edbf7fb0a7)

**Comment by Philip-Wang01** [comment]
Verified this issue on winforms repo with [DemoConsole](https://github.com/dotnet/winforms/tree/release/8.0-preview7/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app from release/8.0-preview7 branch, it was fixed. Test result is same as above.
