### ISSUE TITLE
An exception popped up when click "Type Here" on ContextMenuStrip control in DemoConsole application

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#9413]
### .NET version

.NET 8.0.100-preview.7.23330.16

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

It also repro's in .NET 7.0.

### Issue description

In Winforms repo, there has a [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app, System.NullReferenceException: 'Object reference not set to an instance of an object.' occurs when click "Type Here" on ContextMenuStrip control in DemoConsole application.

https://github.com/dotnet/winforms/assets/94418985/4ae6cb77-9592-41ae-96df-65fe24d9241b

![menu-1](https://github.com/dotnet/winforms/assets/94418985/d9a6ef8a-76fc-4638-9ddd-8fa88128324f)

**Call Stack:**
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Windows.Forms.Design
  StackTrace:
   at System.Windows.Forms.Design.ToolStripMenuItemDesigner.InitializeDropDown() in C:\test\winforms\src\System.Windows.Forms.Design\src\System\Windows\Forms\Design\ToolStripMenuItemDesigner.cs:line 1618

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by elachlan** [comment]
`MenuItem.Owner` is null for some reason.

**Comment by elachlan** [comment]
@MelonWang1 does it repro in .net6?

**Comment by MelonWang1** [comment]
@elachlan NET 6.0 fails when I build it in Winforms repo.

**Comment by elachlan** [comment]
`EditTemplateNode` in `ToolStripMenuItemDesigner` calls `InitializeDropDown` for the designer for a "dummyItem" created via `CreateDummyItem`. For whatever reason the dummy item has no owner, hence the exception. I haven't been able to work out how the owner gets set on a menu item.

If we wrap the Invalidate call in a null check:
```csharp
if (MenuItem.Owner is not null)
{
    GetService<BehaviorService>()?.Invalidate(MenuItem.Owner.Bounds);
}
```

This ends up triggering an assert at:
https://github.com/dotnet/winforms/blob/386d51b6a85689a0964d0596e8e0d03a471fc225/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemDesigner.cs#L1219

Hope that helps.

**Comment by elachlan** [comment]
@dmitrii-drobotov any suggestions here I am a bit stuck.

**Comment by dmitrii-drobotov** [comment]
It also reproduced in release/6.0 branch. I will take a look.

**Comment by dkazennov** [comment]
@elachlan I'll take a look a little bit closer. Need some more time to investigate. Probably will come with some solution next week.

**Comment by dkazennov** [comment]
So this Issue only reproduces in DemoConsole. It has not been reported in Windows Forms applications and it doesn't reproduce there.
![image](https://github.com/dotnet/winforms/assets/102961955/67c512a1-700a-4841-b3a6-bde97a2f8bfb)
We must take a cation: any change in ToolStripMenuItemDesigner may lead for unforeseen regression. 

And we can't simply assign `newItem.Owner` in `CreateDummyItem()`. This leads to exceptions in `ToolStripItemDesigner.CommitEdit()`

**Comment by Syareel-Sukeri** [comment]
Verified this on .NET 9.0.100-preview.3.24163.23, this issue was fixed. No exception popped up when click "Type Here" on ContextMenuStrip control in DemoConsole application.
[Video 3-14 at 8.16.webm](https://github.com/dotnet/winforms/assets/156630333/0787bd0e-b555-4bcb-80a4-ad888fd4a528)

**Comment by Syareel-Sukeri** [comment]
Verified this on latest release/9.0-preview3 repo from main branch, this issue was fixed. Test result is the same as above.
