### ISSUE TITLE
Unable to resize `PictureBox` control at runtime in designer - DemoConsole

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#9416]
### .NET version

Main branch.

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes. We had a similar issue previously and fixed it in #8522

### Issue description

From #9411:

I cannot change the size of the picturebox control in the designer workspace, but can resize it through the properties window.

https://github.com/dotnet/winforms/assets/104609169/0a5c9320-1638-42d4-a390-54fe6794085f

_Originally posted by @Nora-Zhou01 in https://github.com/dotnet/winforms/issues/9411#issuecomment-1617719621_
            

### Steps to reproduce

Run DemoConsole and resize picture box.

**Comment by elachlan** [comment]
@Nora-Zhou01, I've created the ticket here for the resize issue. It was working in #8522, so we can bisect from there.

CC: @Tanya-Solyanik

**Comment by elachlan** [comment]
Additionally the delete functionality doesn't work properly. The button isn't removed.

**Comment by elachlan** [comment]
I have bisected it to changes in #8353

**Comment by elachlan** [comment]
![image](https://github.com/dotnet/winforms/assets/2433737/340e923c-6f87-4a4f-9f32-48c33cacf204)
I think the issue is in `CodeDomComponentSerializationService` because of its dependency on `BinaryFormatter`.

CC: @JeremyKuhne

**Comment by elachlan** [comment]
If I add `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` to the project file it fixes it. But I don't think this is a long term solution.

**Comment by JeremyKuhne** [comment]
There is some hope that we can tackle some part of this with the `BinaryFormat` stuff I wrote.

#6267

**Comment by elachlan** [comment]
We need a follow up issue around removing the binary formatter and adding in the type converter to allow moving of picture box.

**Comment by John-Qiao** [comment]
Verified this on latest .NET 8.0.100-preview.7.23362.29, issue was fixed in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) project, we can change the size of the picturebox control in the designer workspace now.

![9416-testresult](https://github.com/dotnet/winforms/assets/45864985/23b1300f-e9df-4adc-96dc-ce697c618d4c)

**Comment by Philip-Wang01** [comment]
Verified this issue on winforms repo with [DemoConsole](https://github.com/dotnet/winforms/tree/release/8.0-preview7/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app from release/8.0-preview7 branch, it was fixed. Test result is same as above.
