### ISSUE TITLE
Moving icon of GroupBox/Panel is not clear in DemoConsole application

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9421]
### .NET version

.NET 8.0.100-preview.7.23330.16

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it doesn't reproduce in .Net 7.0

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, the moving icon of GroupBox/Panel is not clear now.

**The result of Main branch for .Net 8.0:**
![image](https://github.com/dotnet/winforms/assets/26474449/05b94f8a-82ad-4958-b188-bd9c3c700c93)

**The result of release/7.0 branch for .Net 7.0:**
![image](https://github.com/dotnet/winforms/assets/26474449/d1d7947e-b388-4d6a-a933-e95d92dade55)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by elachlan** [comment]
Caused by #8358

@dreddy-work the `MoverGlyph` bitmap was replaced with an icon and is now scaling incorrectly.

It is loaded in and used here:
https://github.com/dotnet/winforms/blob/918e34631094c184e6b29d659842b540f092ed98/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ContainerSelectorGlyph.cs#L55-L71

**Comment by elachlan** [comment]
This gets it 70% there.
![image](https://github.com/dotnet/winforms/assets/2433737/f0334f3a-6c01-4b99-b808-f754c460f903)

```csharp
private Icon MoveGlyph
        {
            get
            {
                _glyph ??= new Icon(typeof(ContainerSelectorGlyph), "MoverGlyph");
                return _glyph;
            }
        }

        /// <summary>
        ///  Very simple paint logic.
        /// </summary>
        public override void Paint(PaintEventArgs pe)
        {
            using (Brush brush = new SolidBrush(SystemColors.Control))
            {
                // Draw and fill the rectangle
                pe.Graphics.FillRectangle(brush, _glyphBounds);
            }

            pe.Graphics.DrawIcon(MoveGlyph, _glyphBounds);
        }
```

**Comment by dreddy-work** [comment]
We should change glyph type to Icon, its private and impact is limited to `Paint` override. Icon constructors are designed to query for the right sizes on the default.

I do not see the need to make it square. Given this is not going to be serviced, it shouldn't be an issue for the existing applications. @elachlan, can you push PR?

**Comment by dreddy-work** [comment]
@Olina-Zhang, can you check the PR on different DPIs on how it looks now?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang, can you check the PR on different DPIs on how it looks now?

100%DPI:
![image](https://github.com/dotnet/winforms/assets/26474449/bb5d455f-c996-4b55-b8e1-675cf74a9cbb)
175%DPI by DemoConsole application with default setting as following, we can see controls on form are blurry, so we may need to do some setting in this console application to support HDPI: SystemAware or PerMonitorV2 mode, is it right? I tried to add it in .csproj, but it doesn't work, still blurry. Can you please give us guidance how to set HDPI support in that DemoConsole application?
![image](https://github.com/dotnet/winforms/assets/26474449/e1d89e42-e4e6-469c-8216-484ebe997c14)

**Comment by Olina-Zhang** [comment]
@dreddy-work I added  the setting: `Application.SetHighDpiMode(HighDpiMode.PerMonitorV2)` in Program.cs file, it works. Here is the 300% DPI result: the ContainerSelectorGlyph is clear, but the controls on tabpage are not arranged well:
![image](https://github.com/dotnet/winforms/assets/26474449/d1b435fd-be5d-41b0-ba9f-56513e567146)

**Comment by elachlan** [comment]
@dreddy-work want me to add it to the pr?

**Comment by dreddy-work** [comment]
> @dreddy-work want me to add it to the pr?

high DPI mode can be set at SystemAware on proj file. But we need to find why it is blurry on primary monitor when set to SystemAware. This should be done in separate PR and verify blurriness.

**Comment by John-Qiao** [comment]
Verified this on latest .NET 8.0.100-preview.7.23362.29, issue was fixed in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) project, the moving icon of GroupBox/Panel is clear now.

![9421-testresult](https://github.com/dotnet/winforms/assets/45864985/ef98c505-2398-47fc-9918-e651f32def8d)

**Comment by Olina-Zhang** [comment]
Verified with release/8.0-preview7 branch, this issue was fixed with above same verification result.
