### ISSUE TITLE
[Multi-Monitor] Buttons on ThreadExceptionDialog are truncated when DPI is differ

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9449]
### .NET version

.Net 8.0.100-preview.7.23356.13

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

Buttons on ThreadExceptionDialog are truncated when expanding Details button in threadExpectionDialog on 300%DPI primary screen, then move to 100% secondary screen, and collapse Details button. --- This issue was found after PR: https://github.com/dotnet/winforms/pull/9399 merged
**The screenshot:** 
![100%Secondary](https://github.com/dotnet/winforms/assets/26474449/44eadf01-6abc-425d-978e-5521785f86e8)

**The testing result from 300%DPI primary screen to 100%DPI secondary screen:**

https://github.com/dotnet/winforms/assets/26474449/5b45f518-ebb7-410d-8b1c-8532dd14bf85

**The testing result from 100%DPI primary screen to 300%DPI secondary screen:**

https://github.com/dotnet/winforms/assets/26474449/5a70c21c-b20e-4d00-9086-ddda1df08f28

### Steps to reproduce

1. Open following testing app on 300% primary screen:
[WinFormsApp6.zip](https://github.com/dotnet/winforms/files/11996946/WinFormsApp6.zip)
2. Build and run it, click **Open ThreadExceptionDialog** button to open ThreadExceptionDialog
3. Expand **Details** button in ThreadExpectionDialog
4. Move this ThreadExpectionDialog to 100% secondary screen
5. Collapse **Details** button, and observe the buttons on ThreadExceptionDialog

**Comment by elachlan** [comment]
@LeafShi1 did you do the changes for `ThreadExceptionDialog`?

**Comment by LeafShi1** [comment]
> @LeafShi1 did you do the changes for `ThreadExceptionDialog`?

No, I'm investigating this issue, but I haven't made any changes yet.

**Comment by Tanya-Solyanik** [comment]
@LeafShi1 - feel free to remove the `untriaged` label when you start working on the issue.

**Comment by LeafShi1** [comment]
> @LeafShi1 - feel free to remove the `untriaged` label when you start working on the issue.

OK, get it.

**Comment by Eudora-Li01** [comment]
Verified this on .NET latest build: 8.0.100-rc.1.23369.12, issue was fixed. Buttons on ThreadExceptionDialog can be fully displayed when expanding Details button in threadExpectionDialog on 300%DPI primary screen, then move to 100% secondary screen, and collapse Details button.

https://github.com/dotnet/winforms/assets/130345015/812f82db-1338-4b3d-af84-d73f08d0b9f8

**Comment by MandiMan** [comment]
Verified with .NET SDK 8.0.100-preview.7.23376.3 test pass build, this issue was fixed, test result same as above.
