### ISSUE TITLE
DesignerHost throws NRE when calling `Activate` when disposed

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#946]
```
[Fact]
public void ComponentContainer_ActivateDisposed_Nop()
{
    var surface = new DesignSurface();
    int viewActivatedCallCount = 0;
    int activatedCallCount = 0;
    surface.ViewActivated += (sender, e) =>
    {
        Assert.Same(surface, sender);
        Assert.Same(EventArgs.Empty, e);
        viewActivatedCallCount++;
    };
    IDesignerHost host = Assert.IsAssignableFrom<IDesignerHost>(surface.ComponentContainer);
    surface.Dispose();
    host.Activated += (sender, e) => activatedCallCount++;
    host.Activate();
    Assert.Equal(1, viewActivatedCallCount);
    Assert.Equal(0, activatedCallCount);
}
```

> [xUnit.net 00:00:02.21]     System.ComponentModel.Design.Tests.DesignSurfaceTests.ComponentContainer_ActivateDisposed_Nop [FAIL]
Failed   System.ComponentModel.Design.Tests.DesignSurfaceTests.ComponentContainer_ActivateDisposed_Nop
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.Activate() in /Users/hugh/Documents/GitHub/winforms/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs:line 1011
   at System.ComponentModel.Design.Tests.DesignSurfaceTests.ComponentContainer_ActivateDisposed_Nop() in /Users/hugh/Documents/GitHub/winforms/src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignSurfaceTests.cs:line 103

**Comment by weltkante** [comment]
As far as I can tell this also throws on Desktop now, so whats the reason for `Assert.Equal(1, viewActivatedCallCount);` instead of just throwing an `ObjectDisposedException` instead of `NRE`?

I mean, acivation of a disposed object is not a reasonable operation, is it? And if you dispose the surface it also has to dispose the host, otherwise it wouldn't have cleaned up all of its used resources.

**Comment by hughbe** [comment]
Essentially what happens is that we call `_surface.ViewActivated()` in `IDesignerHost` without checking for null because surface is nulled out on dispose. Proposed fix is non breaking by turning this into a nop
`_surface?.ViewActivated()`

The reason I suggest this is because other areas where we call methods on surface check for null before calling and don’t do anything if null, so this seems like an oversight.

**Comment by weltkante** [comment]
ok that sounds reasonable
