### ISSUE TITLE
Winforms template for non Windows platforms.

### ISSUE THREAD

**Issue by speed2048** [dotnet/winforms#947]
I installed .dotnet 3 preview 5 on Linux and Mac OS and did a dotnet new. To my surprise Windows Forms was listed as a template.  From the reading I have done is that WinForms is not supported on these platforms.

I was able to do a dotnet new winforms without issues, but could not run it.

Expected behavior is not to have winforms show as a template or be available on non Windows platforms.

**Comment by tomrus88** [comment]
> Expected behavior is not to have winforms show as a template or be available on non Windows platforms.
Why not? You can develop/publish it on linux or mac and then copy to windows machine where it will be running. I don't see anything wrong with windows only template being available on all OS.

**Comment by speed2048** [comment]
Is this a valid use case? . If is valid then at least present the developer friendly error message that running winforms on (Linux, MacOS ) is not supported... Maybe project mono could provide this functionality in the future.

**Comment by damageboy** [comment]
Techinically I see no reason why BUILDING on Linux/OSX should be a no-go..

I do however get a weird compilation error when trying to compile and otherwise valid .NET Core 3.0p5 project on linux:
```
error MSB4019: The imported project "/home/damageboy/dotnet/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.WinFX.targets"
```

**Comment by weltkante** [comment]
> Techinically I see no reason why BUILDING on Linux/OSX should be a no-go.

I don't know about resx building, but I think compiling licensed controls (licx files) requires loading and executing code. When using licensed 3rd party native controls thats pretty guaranteed to not work on non-Windows systems. I'm not entirely against cross-compiling, but if thats going to supported this really needs better diagnostics than it currently has.

**Comment by merriemcgaw** [comment]
@OliaG @richlander

**Comment by weltkante** [comment]
dotnet/core-sdk#2088 resolved this as "not supported" for the 3.x timeframe

**Comment by dreddy-work** [comment]
Closing the issue as associated issues were resolved.
