### ISSUE TITLE
PrintPreviewControl is unable to show another document after printing failure

### ISSUE THREAD

**Issue by v-elnovikova** [dotnet/winforms#9474]
### .NET version

8.0

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

Setting `PrintPreviewControl.Document` property value invokes generating preview of that document. If there was any exception during that process, PrintPreviewControl shows failure message:
![print_failure](https://github.com/dotnet/winforms/assets/113603457/9ddcd536-436a-4025-a9b0-34bc1446b795)

In this case, after failing to generate preview, PrintPreviewControl is unable to show any other document.
Whatever value is set to `PrintPreviewControl.Document` property, PrintPreviewControl always shows failure.

In a video below:
- "Print successfully" button sets `PrintPreviewControl.Document` property to a document of 1 page;
- "Print with error" button sets `PrintPreviewControl.Document` property to a document that fails to generate a preview;
- "Reset" button sets `PrintPreviewControl.Document` property to `null`.

https://github.com/dotnet/winforms/assets/113603457/ceafae8d-58be-403b-9e9a-d731c4435bd5

Note that after "Print with error" other buttons have no effect, `PrintPreviewControl` always shows error message.

### Steps to reproduce

1. Build and run [SampleApp.zip](https://github.com/dotnet/winforms/files/12028839/SampleApp.zip)
2. Click "Print with error" button to show print failure.
3. Click "Print successfully" button. PrintPreview is expected to show a document page, but it still shows print failure.
4. Click "Reset" button. PrintPreview is expected to show "Document does not contain any pages." message, but it still shows print failure.

**Comment by MandiMan** [comment]
@v-elnovikova Verified this on .NET latest build: 8.0.100-rc.1.23369.12, An exception pops up a few seconds after clicking "Print with error" button, is this the expected result? please check below screenshot:

Call Stack: [Call Stack.txt](https://github.com/dotnet/winforms/files/12103620/Call.Stack.txt)


https://github.com/dotnet/winforms/assets/108860782/9b105146-9df1-4ce5-b316-d76d2fa742c0

![image](https://github.com/dotnet/winforms/assets/108860782/fef32010-059f-4770-8938-0473b80e3f04)

**Comment by Tanya-Solyanik** [comment]
@MandiMan  - please open a new bug.

**Comment by MandiMan** [comment]
> 

Filed a new issue [9533](https://github.com/dotnet/winforms/issues/9533) to track it.

**Comment by MandiMan** [comment]
> @MandiMan - please open a new bug.

Filed a new issue https://github.com/dotnet/winforms/issues/9533 to track it.

**Comment by MelonWang1** [comment]
@Tanya-Solyanik Verified this issue with .NET SDK 8.0.100-preview.7.23376.3 test pass build, when clicking "Print successfully" button, the print page will display "Page 0 of 1", but the PR after result is "Page 1 of 1", is this the expected result?


https://github.com/dotnet/winforms/assets/94418985/5391da69-e241-4273-8e84-1e68f9136fff

![9474-1](https://github.com/dotnet/winforms/assets/94418985/ddf420f9-15f7-42db-9d9e-4707248eddab)

**Comment by v-elnovikova** [comment]
> @Tanya-Solyanik Verified this issue with .NET SDK 8.0.100-preview.7.23376.3 test pass build, when clicking "Print successfully" button, the print page will display "Page 0 of 1", but the PR after result is "Page 1 of 1", is this the expected result?

Yes, that's expected. Test app shown in PR's Screenshots section used a different PrintDocument object as a demo. But for this issue document contents does not matter.

**Comment by MelonWang1** [comment]
@v-elnovikova Ok, thanks for your confirming.
