### ISSUE TITLE
Cannot open smart tag window for ImageList in DemoConsole application

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9482]
### .NET version

.Net 8.0 SDK: 8.0.100-preview.7.23362.29

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, still reproduces in .Net 7.0

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, cannot open smart tag window for ImageList to do some operation. 
![image](https://github.com/dotnet/winforms/assets/26474449/e6e1727e-61c8-4de0-97c0-dc71156428c4)

**Expected result:**
![image](https://github.com/dotnet/winforms/assets/26474449/18490c4b-56cd-4d8c-99fd-1762cd2004af)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by elachlan** [comment]
#4908 it looks like there is no `ImageListDesigner`.

**Comment by elachlan** [comment]
CC: @dmitrii-drobotov

**Comment by Olina-Zhang** [comment]
Verified this issue in this repo: feature/9.0 branch, imageListDesigner is supported now. Closing this issue manually.
![ImageListDesigner](https://github.com/dotnet/winforms/assets/26474449/622e66cc-907b-4448-bea9-b73403665815)
