### ISSUE TITLE
The next focus position is first item on the right/top when setting RightToLeft=Yes, regardless of whether the right or left key is typed

### ISSUE THREAD

**Issue by Eudora-Li01** [dotnet/winforms#9484]
### .NET version

.NET SDK 8.0.100-preview7.23362.29

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

When setting GripStyle=Hidden:
It's a regression issue, it reproduces on .NET Framework 4.8.1, .NET 3.1 & 5.0 & 6.0 & 7.0 & 8.0. and it doesn't reproduce on .NET Framework 4.7.2.
When setting GripStyle=Visible:
It's a regression issue, it reproduces on .NET 6.0 & 7.0 & 8.0. and it doesn't reproduce on .NET Framework and .NET Core 3.1 & 5.0.

### Issue description

The next focus position is first item on the right/top when setting RightToLeft=Yes, regardless of whether the right or left key is typed.  

### Steps to reproduce

Extract and open the test app. [Test-App.zip](https://github.com/dotnet/winforms/files/12037865/Test-App.zip)
Build and run this project.
Select on a ToolStripButton using mouse or typing "enter" keyboard.
Type "right or left" keyboard.

https://github.com/dotnet/winforms/assets/130345015/e07655e1-9409-4671-aca4-8bf02a1fd3d3

**Comment by merriemcgaw** [comment]
Agreed.
