### ISSUE TITLE
Nullability annotations in ComponentDesigner and child classes

### ISSUE THREAD

**Issue by halgab** [dotnet/winforms#9502]
### Background and motivation

As discussed [here](https://github.com/dotnet/winforms/pull/9408#discussion_r1249753476), `ComponentDesigner` has a public `Component` property that is not set in the constructor, but in the `Initialize` method. This property implicitly implements the `IDesigner` interface, that expects it not to be null. Many parts of the code both in `ComponentDesigner` and its child classes also don't guard its value against null.
Also, all internal construction of this class call the `Initialize` method right after creation.

### API Proposal

There are 2 main ways to adress this issue.
1. Forcing `Component` to be not null as an auto-property.
2. Having a non-null `Component` getter backed by a nullable private field, and throw when the property is called at a time where the backing field is null (see [here](https://github.com/dotnet/winforms/issues/9502#issuecomment-1637216273))

### API Usage

NA

### Alternative Designs

An alternative would be to make this property nullable, with an explicit implementation of the `IDesigner` interface, and add many `!` (or null checks) all over the codebase.
Another one would be not to annotate this property and leave it undefinitely in an undefined state.

### Risks

The main risk of option 1 here is to manipulate an uninitialized `ComponentDesigner` (which I think already comes with risks) without alerting users that `Component` can actually be null in such a case.
Option 2 is breaking as it throws a new exception, and it adds null checks all over the place which may hurt performance if the property is called in perf-sensitive code

### Will this feature affect UI controls?

Not directly

**Comment by elachlan** [comment]
What about something like this?

```csharp
private IComponent? _component;
    /// <summary>
    ///  Gets or sets the component this designer is designing.
    /// </summary>
    public IComponent Component
    {
        get => _component == null ? throw new InvalidOperationException("Component not initialized") : _component;
        private set => _component = value;
    }
```

**Comment by halgab** [comment]
> What about something like this?
> 
> ```cs
> private IComponent? _component;
>     /// <summary>
>     ///  Gets or sets the component this designer is designing.
>     /// </summary>
>     public IComponent Component
>     {
>         get => _component ?? throw new InvalidOperationException("Component not initialized");
>         private set => _component = value;
>     }
> ```
> 
> There is a precedent for it:
> 
> https://github.com/dotnet/winforms/blob/43c5f2b3ea81496793f0b14ae5d28877f593bfeb/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs#L252-L256

I updated the issue description to include your proposed fix

**Comment by elachlan** [comment]
@halgab I believe we resolved this. Can I close the issue?

**Comment by halgab** [comment]
No, this is still pending, waiting a decision from the team

**Comment by lonitra** [comment]
I believe this was addressed as part of https://github.com/dotnet/winforms/pull/9408, closing.
Please feel free to holler if I am misunderstanding on this.
