### ISSUE TITLE
Request to backport fix to NET framework

### ISSUE THREAD

**Issue by rauhs** [dotnet/winforms#9515]
### .NET version

NET 4.8

### Did it work in .NET Framework?

No

### Issue description

Hi,

I'm aware I'm wrong here for NET framework issues (as noted in https://github.com/dotnet/winforms#please-note).

However: Both  of these links do not work.

- The "developers community" link fails immediatly with a 403. And if I try to submit I get a "Unexpected error. Sorry, we couldn't send your report, because the server connection timed out.". If I try to submit it from with Visual Studio it also just hangs with "Trying to log in". Frustrating.
- The link to "Product support" website works, but it asks me for a "eligible support plan". Do I need to purchase support for this?

Background: We're running into #2979 and have no easy way to fix it (third party library: DevExpress) and would like to see it fixed.

Again, sorry for the ticket but I have no clue what else to do.

I'd appreciate any help.

Cheers from Germany

### Steps to reproduce

Try to report the issue.

**Comment by elachlan** [comment]
Not a particularly sensitive question but can your app upgrade to .NET 7 or 8(when its released)?

**Comment by rauhs** [comment]
@elachlan I cannot any time soon unfortunately. We've been investing a lot of time and resources converting our about 400 net472 assemblies to netstandard and net6.0 (multi target) but we still have a few years left until we have a shippable net6 application.

**Comment by merriemcgaw** [comment]
My team and I were able to access both sets of links appropriately. I do want to set expectations that changes in .NET Framework (which is part of Windows) is very high at this point. Most changes are generally security vulnerabilities or high impacting bugs - usually going through customer service contracts to request patching for an issue.

**Comment by rauhs** [comment]
@merriemcgaw Thanks for quickly getting back and setting expectations. I could successfully access developercommunity.visualstudio.com today (even clearing cookies and whatnot yesterday was resulting in constant errors).

I submitted my request there.

Cheers
