### ISSUE TITLE
An exception popped up when click "Print with error" button

### ISSUE THREAD

**Issue by MandiMan** [dotnet/winforms#9533]
### .NET version

 .NET 8.0.100-rc.1.23369.12

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

In a video below:
- "Print successfully" button sets PrintPreviewControl.Document property to a document of 1 page;
- "Print with error" button sets PrintPreviewControl.Document property to a document that fails to generate a preview;
- "Reset" button sets PrintPreviewControl.Document property to null.

Note that an exception pops up a few seconds after clicking "Print with error" button

https://github.com/dotnet/winforms/assets/108860782/28cd18ab-dac4-40e0-a5b9-a004dea2bb13

![image](https://github.com/dotnet/winforms/assets/108860782/30de529b-a432-42d9-8b2e-c157bf311e9f)
**Call Stack:**
System.Exception
  HResult=0x80131500
  Message=Something went wrong.
  Source=SampleApp
  StackTrace:
   at SampleApp.Form1.ErroneousDocument.OnPrintPage(PrintPageEventArgs e) in C:\Users\v-mandiman\Desktop\SampleApp\SampleApp\Form1.cs:line 73
   at System.Drawing.Printing.PrintController.PrintLoop(PrintDocument document)
   at System.Drawing.Printing.PrintController.Print(PrintDocument document)
   at System.Windows.Forms.PrintPreviewControl.ComputePreview()
   at System.Windows.Forms.PrintPreviewControl.CalculatePageInfo()

### Steps to reproduce

- Build and run [SampleApp.zip](https://github.com/dotnet/winforms/files/12115642/SampleApp.zip)
- Click "Print with error" button and observe it

**Comment by dmitrii-drobotov** [comment]
@v-elnovikova this is expected, right?

**Comment by Tanya-Solyanik** [comment]
Oh, I see this is the exception from user code... @v-elnovikova - please close this issue if it's expected.

**Comment by v-elnovikova** [comment]
Yes, this is a user exception. Closing the issue.
