### ISSUE TITLE
SetWindowsHookEx API is not working for mouse actions in .NET7.0

### ISSUE THREAD

**Issue by GokulThanu** [dotnet/winforms#9535]
### .NET version

.net .7.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes , it is working in .net6.0 and earlier versions

### Issue description

The mouse action is not captured by the SetWindowsHookEx API in .Net7.0 which works in the earlier version.

I have already created an issue regarding this but the solution given in that was not worked for me.
link-https://github.com/dotnet/winforms/issues/8965

### Steps to reproduce

https://github.com/dotnet/winforms/files/11198683/WinFormsApp1.zip

Run the attached sample

- Perform the mouse action(mouse move, mousedown, Mouse up)

- The Writeline operation in the method MouseHookProc will not be performed

Note- These will be working in .NET6.0 and earlier version

**Comment by elachlan** [comment]
Cc: @JeremyKuhne

**Comment by JeremyKuhne** [comment]
As described in the linked issue, you should NEVER cast `MSG` to `Message`. It has never matched `MSG`'s layout and has always been unsafe.

This works for me without a problem:

``` C#
public struct MSG
{
    public nint hwnd;
    public uint message;
    public nuint wParam;
    public nint lParam;
    public uint time;
    public Point pt;
}

// Define the hook procedure
private unsafe static IntPtr MouseHookProc(int nCode, IntPtr wParam, IntPtr lParam)
{
    // If hooking WH_MOUSE (7)
    // int msg = (int)(long)wParam;

    // If hooking WH_GETMESSAGE (3)
    int msg = (int)((MSG*)(void*)lParam)->message;

    if (msg == 0x0202 || msg == 0x0201)
    {
        Debug.WriteLine("mouse click");
    }
}
```

Or if you really want to cast out the whole struct:

``` C#
    MSG msgStruct = *(MSG*)(void*)lParam;
    int msg = (int)msgStruct.message;
```

If all you're looking at are mouse messages, it makes a lot more sense to use `WH_MOUSE`. That way you're only getting call backs for mouse messages (better performance), and you can just cast the `WPARAM` to get the message ID.

**Comment by JeremyKuhne** [comment]
I'll also leave a plug for [CsWin32](https://github.com/microsoft/CsWin32/) again. It generates interop code directly from Windows provided metadata, which can make direct interop so much easier / less error prone.

**Comment by GokulThanu** [comment]
Hi @JeremyKuhne , In my application these codes will be shared for different frame work like .net6.0, net7.0 ,.net framework4.6,.net  framework 4.7 etc. In .net framework 4.6 and framework 4.7 , the error occurs with the given code . Is any other solution which can be used in all the framework

**Comment by JeremyKuhne** [comment]
@GokulThanu the code should work on 4.x, what error are you seeing?
