### ISSUE TITLE
Unify line endings

### ISSUE THREAD

**Issue by JuditRose** [dotnet/winforms#955]
Currently we have both CRLF and LF line endings "randomly" in our files.
The team agreed to use the windows style line endings. 

This task contains:
- [ ] clean up the line endings in the files
- [ ] set up .git/config (https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) to keep the settings clean in the project
- [ ] check if there is a config for the project, if yes, set it there as well

**Comment by RussKie** [comment]
* [ ] Update .editorconfig as well with `end_of_line=crlf`
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#end_of_line

**Comment by weltkante** [comment]
Discussion in PR #954 indicates that forcing line endings to `crlf` is the wrong solution. Just mentioning it on the issue as well for future readers.
