### ISSUE TITLE
Font size of context menu items does not update when screen dpi changes

### ISSUE THREAD

**Issue by tbambuch** [dotnet/winforms#9580]
### .NET version

8.0

### Did it work in .NET Framework?

Yes

### Issue description

The font of contextmenu items will does not update after the system dpi scaling is changed if the contextmenu has already been opened before, the app must be restarted to take effect.

![image](https://github.com/dotnet/winforms/assets/3384955/683b4c4f-9a50-4c51-87d6-12282f6e3fc8)
![image](https://github.com/dotnet/winforms/assets/3384955/79ca25ac-1df8-4ed8-abc4-ba19c3374d2b)
[DpiTest.zip](https://github.com/dotnet/winforms/files/12182569/DpiTest.zip)

### Steps to reproduce

Run the attached sample. Open the contextmenu, then change the dpi scaling in Windows, app still running. The font of the button is correctly changed, but the contextmenu items still have the original font.
In my case I change from 150% (default) to 200%, only a single monitor attached. Windows 11
Does not work in .net7, either

**Comment by elachlan** [comment]
CC: @dreddy-work

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test?

**Comment by Olina-Zhang** [comment]
@tbambuch I tried to run the application you provided in a single monitor with different DPI set when runtime keeps opening, it doesn't reproduce: Font size of context menu items is updated when DPI is changed. Could you help confirm if any my operation isn't same as you?

https://github.com/dotnet/winforms/assets/26474449/2dd6cfbb-c54d-4a10-b6a4-5e9a514d83dc

**Comment by tbambuch** [comment]
Sorry, my bad. I was on NET 8 preview.4. After updating to preview.6 the issue is resolved

**Comment by elachlan** [comment]
@tbambuch can you please close the issue?
