### ISSUE TITLE
PrintPreviewControl lacks UI Automation Scroll pattern support

### ISSUE THREAD

**Issue by v-elnovikova** [dotnet/winforms#9584]
### .NET version

.NET SDK 8.0.0-rc.1.23371.3

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, regression after PR #9477 

### Issue description

After replacing native scrolling with .NET ScrollBars in PR #9477 PrintPreviewControl no longer supports Scroll pattern.

**Before PR #9477**
Narrator was announcing scroll percent of PrintPreviewControl:

![PrintPreviewControl_Narrator_before_PR_9477](https://github.com/dotnet/winforms/assets/113603457/dca29359-08d6-4fc9-af22-b504d656c91f)

ScrollPattern was supported:
![PrintPreviewControl_before_PR_9477](https://github.com/dotnet/winforms/assets/113603457/ddd5ea0d-4c23-435e-96ef-4672780bbd81)

**After PR #9477**
Narrator does not announce scroll percent:
![PrintPreviewControl_Narrator_after_PR_9477](https://github.com/dotnet/winforms/assets/113603457/ee3eebe4-6ca7-4117-8a5a-6a21ab6ca176)

ScrollPattern is not supported:
![PrintPreviewControl_after_PR_9477](https://github.com/dotnet/winforms/assets/113603457/73ce80ef-7c37-4fa8-9559-8de5f32604e5)

### Steps to reproduce

1. Create .NET project with PrintPreviewControl and PrintDocument, or run Accessibility_Core_App.
2. Run Narrator and switch focus to PrintPreviewControl.

**Comment by dmitrii-drobotov** [comment]
Here is some additional info about implementing Scroll pattern: https://learn.microsoft.com/en-us/windows/win32/winauto/uiauto-implementingscroll.

**Comment by Amy-Li03** [comment]
@Tanya-Solyanik @Epica3055 verified this from main branch (.NET 9.0 alpha branch) of winforms repo, ScrollPattern was supported, but Narrator does not announce scroll percent.
![image](https://github.com/dotnet/winforms/assets/62929087/f0c8d175-e1ab-47d8-b4b6-aff9f9659f21)
![image](https://github.com/dotnet/winforms/assets/62929087/2c0d078e-30ed-441f-aef0-36e9bde21264)

**Comment by Nora-Zhou01** [comment]
Verified this issue on .NET 8.0.100-RC.2.23431.5, it was fixed, ScrollPattern was supported.
![9584](https://github.com/dotnet/winforms/assets/104609169/a71dfac8-c483-4507-943b-24970e9642bb)

**Comment by Philip-Wang01** [comment]
Verified with .NET SDK 8.0.100-rc.2.23477.19 test pass build, this issue was fixed, ScrollPattern was supported. Screenshot is same as above.
