### ISSUE TITLE
Support HelpProvider HelpKeyword for local HTML files

### ISSUE THREAD

**Issue by decobeirne** [dotnet/winforms#9599]
### Background and motivation

Where `HelpNamespace` is set to a local HTML file, e.g. a HTML file that is bundled with the application (surely a common use case?), a HTML anchor that is specified using `SetHelpKeyword` will not be shown when pressing F1.

In `Help::ShowHTMLFile`, the URI is constructed correctly to include the keyword, `file = new Uri($"{file}#{stringParam}");`, but the URI is then presented using:

```
PInvoke.ShellExecute(handle.Handle, lpOperation: null, file.ToString(), lpParameters: null, lpDirectory: null, SHOW_WINDOW_CMD.SW_NORMAL);
```

For a local HTML file, this will throw away the anchor. However, at this point we already know that the URI is a HTML file, therefore this command could be updated to use the default browser to open the URI.

### API Proposal

In `Help`, first determine the default browser, e.g. by reading the registry key:

```
Registry.CurrentUser.OpenSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FileExts\\.htm\\UserChoice", false);
```

Then in `Help::ShowHTMLFile`, update the `ShellExecute` command to use the default browser to open the URI:

```
PInvoke.ShellExecute(handle.Handle, lpOperation: null, defaultBrowser, lpParameters: file.ToString(), lpDirectory: null, SHOW_WINDOW_CMD.SW_NORMAL);
```

### API Usage

No change

### Will this feature affect UI controls?

No

**Comment by elachlan** [comment]
Can you please provide the code you use to trigger the showing of the help file?

Are you using Help.ShowHelp?
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.help.showhelp?view=windowsdesktop-7.0

I just tested it in main and it opens in the default browser with the anchor included.

**Comment by elachlan** [comment]
> After some back-and-forth with Microsoft's MSDN team, they reviewed the source code to the ShellExecute() call and it was determined that yes, when processing File:/// based URLs in ShellExecute(), the ShellExecute() call will strip off the # and any data it finds after the # before launching the default browser and sending in the HTML page to open. MS's stance is that they do this deliberately to prevent injections into the function.

https://stackoverflow.com/questions/26305322/shellexecute-fails-for-local-html-or-file-urls

The solutions also note that the registry solution doesn't work in windows 10.

There is a solution using `FindExecutable`. So my solution would be to add a code path which uses it to establish the exe before calling `ShellExecute` here:
https://github.com/dotnet/winforms/blob/f364069f17e2778ceab92f94699181891f92a13b/src/System.Windows.Forms/src/System/Windows/Forms/Help.cs#L213-L257

**Comment by decobeirne** [comment]
Hi Lachlan. Thanks a lot for investigating.

I had missed that stackoverflow post.

The proposal sounds great, I didn't think of FindExecutable. This would make much more sense than checking the registry.

**Comment by elachlan** [comment]
@merriemcgaw I don't think this is an API change, but a slight behavior change to fix a bug in the `Help` class. I imagine that still rules it out for .net8 and so I'll have to base it on .NET9?

**Comment by merriemcgaw** [comment]
.NET 9 is great for me! Thanks once again @elachlan!

**Comment by elachlan** [comment]
@decobeirne the PR has just been merged to .NET 9 branch. Up to the team if they want to service it to .NET8.

**Comment by decobeirne** [comment]
Awesome! This is great for us. Thanks for the heads-up.

**Comment by Nora-Zhou01** [comment]
According to @decobeirne description, the issue has been fixed, so close it.
