### ISSUE TITLE
TabControl with Appearance=Normal renders TabPage within a littlebit incorrect rectangle

### ISSUE THREAD

**Issue by mikola-akbal** [dotnet/winforms#9612]
### .NET version

7

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

On image you see white color borders that belong to TabControl. Widthes are different: top and right 1px, bottom 2 px, left 3 px. You don't see these borders if you use default transparent color of TabPage. But if you use another color, you see its. This difference of widthes creates impression of some kind of incompleteness of application.

![TabControl](https://github.com/dotnet/winforms/assets/45461294/e1abf6c5-9125-4716-af0b-ccea8e70da7b)

### Steps to reproduce

See it in Designer.

.NET Framework has it too.

**Comment by mikola-akbal** [comment]
Is there some way to repair it before patch? Some playing with margins, paddings?

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang - could you please see if an MFC TabControl has the same borders?

**Comment by Nora-Zhou01** [comment]
@Tanya-Solyanik  The MFC TabControl has the same borders and the width varies.
![MFC](https://github.com/dotnet/winforms/assets/104609169/d828e5ec-c8f3-4731-8af1-24942d2ac6ff)

**Comment by Tanya-Solyanik** [comment]
@Nora-Zhou01  - could you please add several tab pages to this control?

**Comment by Nora-Zhou01** [comment]
@Tanya-Solyanik  When adding tabs to Tabcontrol, the white border at the top disappears, but white borders of different widths remain on the left, right, and bottom.

https://github.com/dotnet/winforms/assets/104609169/fbae77dd-8ff5-4f87-82c2-fb62f1898abb

![image](https://github.com/dotnet/winforms/assets/104609169/b7f6301e-b1f1-4328-af45-eac8733b72fc)

**Comment by merriemcgaw** [comment]
This looks like we have to file a bug against Windows Common Controls. (@Olina-Zhang can you please take care of filing it?). Do be aware that Windows is not making any real changes to Common Controls as it is consider legacy. But there's nothing we can do on our end given that this is how the underlying Windows control behaves.

**Comment by mikola-akbal** [comment]
> Do be aware that Windows is not making any real changes to Common Controls as it is consider legacy.

Sounds like Microsoft will do nothing with problem.

**Comment by Olina-Zhang** [comment]
Created an internal Windows bug: https://microsoft.visualstudio.com/OS/_workitems/edit/45893343. Closing this issue.
