### ISSUE TITLE
Mark some properties and methods as `readonly`

### ISSUE THREAD

**Issue by hamarb123** [dotnet/winforms#9618]
### Background and motivation

Some properties and methods should be marked `readonly`. This way they can be used on `readonly` references without causing defensive copies.

This is something I ran into recently with `Padding`, so I went and found (hopefully) all of the types which could be improved by marking them / some of their members as `readonly`. I have an analyser which detected a defensive copy for my use of `Padding`, and I have currently worked around it by using `Unsafe.AsRef` (obviously I could have also accepted the defensive copy) - but I would like to remove this workaround as it should be unnecessary.

Note that `Point`, `PointF`, etc. have already had this done to them in https://github.com/dotnet/corefx/pull/40407.

I would like to make a PR for this when approved.

### API Proposal

```diff
namespace System.Drawing
{
	//`: IEquatable<CharacterRange>` is currently not in ref-only dll, but is in source dll:
-	public struct CharacterRange
+	public struct CharacterRange : IEquatable<CharacterRange>
	{
-		public int First { get; set; }
+		public int First { readonly get; set; }
-		public int Length { get; set; }
+		public int Length { readonly get; set; }
-		public override bool Equals(object? obj);
+		public override readonly bool Equals(object? obj);
		//`bool Equals(CharacterRange other)` is currently not in ref-only dll, but is in source dll:
+		public readonly bool Equals(CharacterRange other);
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
		//...
	}
}

namespace System.Windows.Forms
{
-	public struct BindingMemberInfo
+	public readonly struct BindingMemberInfo
	{
		public string BindingPath { get; }
		public string BindingField { get; }
		public string BindingMember { get; }
		public override bool Equals(object? otherObject);
		public bool Equals(BindingMemberInfo other);
		public override int GetHashCode();
		//...
	}
	//or we could make each member readonly instead? (applicable members listed above if this is what we do)

-	public struct ImeModeConversion
+	public readonly struct ImeModeConversion
	{
		//...
	}

	public struct LinkArea
	{
-		public int Start { get; set; }
+		public int Start { readonly get; set; }
-		public int Length { get; set; }
+		public int Length { readonly get; set; }
-		public bool IsEmpty { get; }
+		public bool IsEmpty { readonly get; }
-		public override bool Equals(object? o);
+		public override readonly bool Equals(object? o);
-		public bool Equals(LinkArea other);
+		public readonly bool Equals(LinkArea other);
-		public override string ToString();
+		public override readonly string ToString();
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
		//...
	}

	public struct Message
	{
-		public int Msg { get; set; }
+		public int Msg { readonly get; set; }
-		public IntPtr WParam { get; set; }
+		public IntPtr WParam { readonly get; set; }
-		public IntPtr LParam { get; set; }
+		public IntPtr LParam { readonly get; set; }
-		public IntPtr Result { get; set; }
+		public IntPtr Result { readonly get; set; }
-		public object? GetLParam(Type cls);
+		public readonly object? GetLParam(Type cls);
-		public override bool Equals(object? o);
+		public override readonly bool Equals(object? o);
-		public bool Equals(Message other);
+		public readonly bool Equals(Message other);
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
-		public override string ToString();
+		public override readonly string ToString();
		//...
	}

	public struct Padding
	{
-		public int All { get; set; }
+		public int All { readonly get; set; }
-		public int Bottom { get; set; }
+		public int Bottom { readonly get; set; }
-		public int Left { get; set; }
+		public int Left { readonly get; set; }
-		public int Right { get; set; }
+		public int Right { readonly get; set; }
-		public int Top { get; set; }
+		public int Top { readonly get; set; }
-		public int Horizontal { get; }
+		public int Horizontal { readonly get; }
-		public int Vertical { get; }
+		public int Vertical { readonly get; }
-		public Size Size { get; }
+		public Size Size { readonly get; }
-		public override bool Equals(object? other);
+		public override readonly bool Equals(object? other);
-		public bool Equals(Padding other);
+		public readonly bool Equals(Padding other);
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
-		public override string ToString();
+		public override readonly string ToString();
		//...
	}

	public struct TableLayoutPanelCellPosition
	{
-		public override bool Equals(object? other);
+		public override readonly bool Equals(object? other);
-		public bool Equals(TableLayoutPanelCellPosition other);
+		public readonly bool Equals(TableLayoutPanelCellPosition other);
-		public override string ToString();
+		public override readonly string ToString();
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
		//...
	}
}
```

Pre-existing attributes omitted for clarity.

Edit: Removed `TableLayoutPanelCellPosition.Row`, `TableLayoutPanelCellPosition.Column`, `Message.HWnd`, and all of the properties on `TextMetrics`, as these were already marked as `readonly` due to being auto properties.

Edit 2: Add implementation of `IEquatable<CharacterRange>` to `CharacterRange` + its method, since it's declared in source, but not in the ref project.

Edit 3: Add missing `Padding.GetHashCode()` and `Padding.ToString()` members.

Edit 4 (question): Should we fix the `NotSupported.cs`'s definition of `CharacterRange` to have the correct fields. It doesn't really matter, but would better match what C# would generate for a ref assembly.

### API Usage

The applicable APIs can now be used anywhere that these types are declared as readonly without causing a defensive copy, thus improving performance.

e.g. (a simplified version of my scenario)
```csharp
struct SomeLargeStruct
{
	public Padding Padding;
	//...
}

int SomeMethod(in SomeLargeStruct referenceToABunchOfFields, int index)
{
	//some condition
	if (condition) return referenceToABunchOfFields.Padding.Top;
}
```

### Alternative Designs

For `BindingMemberInfo`, we could do:
```diff
namespace System.Windows.Forms
{
	public struct BindingMemberInfo
	{
-		public string BindingPath { get; }
+		public readonly string BindingPath { get; }
-		public string BindingField { get; }
+		public readonly string BindingField { get; }
-		public string BindingMember { get; }
+		public readonly string BindingMember { get; }
-		public override bool Equals(object? otherObject);
+		public override readonly bool Equals(object? otherObject);
-		public bool Equals(BindingMemberInfo other);
+		public bool readonly Equals(BindingMemberInfo other);
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
	}
}
```
instead of
```diff
namespace System.Windows.Forms
{
-	public struct BindingMemberInfo
+	public readonly struct BindingMemberInfo
	{
		public string BindingPath { get; }
		public string BindingField { get; }
		public string BindingMember { get; }
		public override bool Equals(object? otherObject);
		public bool Equals(BindingMemberInfo other);
		public override int GetHashCode();
	}
}
```

### Risks

This should be pretty uncontroversial.

Maybe I have missed an API somewhere, I'm pretty sure I got all the public structs, but I may have missed a nested one or something like that.

### Will this feature affect UI controls?

I would hope not.

**Comment by elachlan** [comment]
Did you have a look at Internal/Private structs as well? I guess we can approach them in a separate PR (especially the Primitives project).

**Comment by elachlan** [comment]
I'd also like to see `System.Windows.Forms.Design` public API surface covered as well in this API review.

**Comment by hamarb123** [comment]
> I'd also like to see `System.Windows.Forms.Design` public API surface covered as well in this API review.

The only struct I can see in this namespace is `ThemedScrollbarWindow`, which exposes fields instead. Fields do not share this issue, only methods have this issue (properties are just methods in disguise). Are you referring to something else?

> Did you have a look at Internal/Private structs as well? I guess we can approach them in a separate PR (especially the Primitives project).

These could be done in the same PR (depending on the maintainers' preference), they would not require API review as they are not publicly exposed (but still needs to be approved by the maintainers obviously).

**Comment by elachlan** [comment]
@Youssef1313 do you know of an analyzer that identifies these?

**Comment by hamarb123** [comment]
I've had a look through the following dlls, and I don't think I missed checking any structs:
- Microsoft.VisualBasic.dll
- Microsoft.VisualBasic.Forms.dll
- System.Windows.Forms.Design.dll
- System.Windows.Forms.Design.Editors.dll
- System.Windows.Forms.dll
- System.Windows.Forms.Primitives.dll

**Comment by merriemcgaw** [comment]
@JeremyKuhne for his input. This is certainly something we would consider for .NET 9.

**Comment by JeremyKuhne** [comment]
I don't have a problem with this, particularly with the members.  We shouldn't need a formal API review for this sort of change, but I'll double check.

https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md

Presuming I don't have to drag this through a formal API review I'm fine with taking this for .NET 8 if someone wants to tackle it. It would have to happen soon, though. Again, I'll check and update the issue.

**Comment by elachlan** [comment]
@hamarb123 I'll leave the PR to you if you have time. Let me know if you want me to jump in and get it done.

**Comment by hamarb123** [comment]
I've made a PR for it now, I haven't yet checked whether there are any internal structs which could benefit from it yet though.

**Comment by JeremyKuhne** [comment]
We don't have to do the formal API review. I'm going to try and find some time tomorrow to sanity check this. We can never remove `readonly` so I want to take another look to make sure I've thought it through a bit for each of these.
