### ISSUE TITLE
windows forms: listview column click sort

### ISSUE THREAD

**Issue by ghost** [dotnet/winforms#9631]
hi

In .net 4 I implemented listview column click sorting by implementing a listviewitemsorter class and use this for the listview.
The same code throws an exception in .net 5.0 and also makes the program crash completely while this same code works in .net 4 without any problems or crash.

Is this a bug or how to implement column click sorting in a listview correctlly for .net 5.0?

I don't find any docs for this, and no explanation what the exception means.

Jessica

**Comment by marcpopMSFT** [comment]
Old issue triage: moving to winforms.
