### ISSUE TITLE
TreeNode colors - NotSelectedBackColor, NotSelectedForeColor, SelectedBackColor, SelectedForeColor

### ISSUE THREAD

**Issue by mikola-akbal** [dotnet/winforms#9657]
### Background and motivation

Now, I can customize only main BackColor and ForeColor of not-selected TreeNode. When I select TreeNode, both these colors are changed, and I can not customize BackColor and ForeColor of selected TreeNode. It breaks color scheme of control.

So, current BackColor and ForeColor should be renamed to NotSelectedBackColor and NotSelectedForeColor, that they are in fact. And two new properties should be added: SelectedBackColor and SelectedForeColor.

### API Proposal

```csharp
public
Color
NotSelectedBackColor // Former BackColor
{ get; set; }

public
Color
NotSelectedForeColor // Former ForeColor
{ get; set; }

public
Color
SelectedBackColor // New property
{ get; set; }

public
Color
SelectedForeColor // New property
{ get; set; }
```

### API Usage

```csharp
TreeNode.SelectedForeColor = Color.Green;
```

### Risks

I don't see risks.

### Will this feature affect UI controls?

VS Designer need to support the feature

**Comment by RussKie** [comment]
The Windows Forms TreeView controls is a wrapper over Win32 TreeView control. How does your proposal maps to the underlying Windows control? Does it support for the features you propose?

**Comment by mikola-akbal** [comment]
> How does your proposal maps to the underlying Windows control? Does it support for the features you propose?

I don't know. Your speach sounds like "no".

If no, this should be added to Windows control too. It gives full coloring logic to control. Developer can assign to these colors  it's senses.

**Comment by paul1956** [comment]
@mikola-akbal the Win32 Control supports events and in these events your app can set appropriate colors to available properties.

https://stackoverflow.com/questions/21198668/treenode-selected-backcolor-while-treeview-not-focused

**Comment by mikola-akbal** [comment]
> @mikola-akbal the Win32 Control supports events and in these events your app can set appropriate colors to available properties.

It seems, I will lose cross-platformity of code with this approach.

**Comment by merriemcgaw** [comment]
@mikola-akbal - what specifically doesn't work for you after you read the [stackoverflow](https://stackoverflow.com/questions/21198668/treenode-selected-backcolor-while-treeview-not-focused) link that @paul1956 provided?

**Comment by paul1956** [comment]
> > @mikola-akbal the Win32 Control supports events and in these events your app can set appropriate colors to available properties.
> 
> It seems, I will lose cross-platformity of code with this approach.

Sorry if it wasn't clear, three approaches.:
1) You use the events in Win32 Control to implement the properties you want in WinForms answering @RussKie question. But you can't rename existing properties as that would break existing code.
2) You use the example from StackOverflow in your code to achieve the same results using the existing controls in WinForms.
3) You create your own custom control using either of the above 2 approaches and optionally post on NuGet.

**Comment by merriemcgaw** [comment]
Closing this issue. There is a workaround as @paul1956 mentions and there has been only this single request for the feature. Windows allows developers to do this, so the developer can use the native approach that @paul1956 mentions.
