### ISSUE TITLE
[LOC] Don't translate End and Insert keys in KeysConverter for German.

### ISSUE THREAD

**Issue by Philip-Wang01** [dotnet/winforms#9660]
### .NET version

.NET 8.0.100-rc.1.23403.2

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No

### Issue description

**Current Behavior:** End and Insert keys are not translated.
.NET 8.0.100-rc.1.23403.2: 
![image](https://github.com/dotnet/winforms/assets/86937911/1d79f560-dec4-45ab-85e0-35fdc8472a9d)

**Expected Behavior:** End and Insert keys are translated.
.NET Framework 4.8.1:
![image](https://github.com/dotnet/winforms/assets/86937911/2b0291aa-80ac-46e5-a63d-ade528cb8564)

### Steps to reproduce

1. Create a WinForms .NET Core project.
2. Drag MenuStrip control to form designer.
3. Set the Type Here in MenuStrip as below:
![image](https://github.com/dotnet/winforms/assets/86937911/8195394a-bf75-45ee-b958-959597721da5)
4. Set the ShortcutKeys = Ctrl+End  in toolStripMenuItem1 property window.
5. Set the ShortcutKeys = Ctrl+Insert  in toolStripMenuItem2 property window.

**Comment by elachlan** [comment]
@merriemcgaw could you please ping the Internal LOC team?

**Comment by Tanya-Solyanik** [comment]
@Philip-Wang01 - what locale is used for your OS, VS and application.

**Comment by Philip-Wang01** [comment]
@Tanya-Solyanik This issue was found in bug verification, original issue: https://github.com/dotnet/winforms/issues/8440

**Here are the test environment:**
**OS:** German (Windows-11-Enterprise-22H2-DE-DE)
**VS:** German (17.8.0 Preview 2.0 [34006.21.main])
**Application:** German ([Testapp.zip](https://github.com/dotnet/winforms/files/12271504/Testapp.zip))
.NET 7.0 have the same result with .NET 8.0.

**Comment by Olina-Zhang** [comment]
This issue title doesn't quite fit. From the issue description, it seems the behaviors between .Net 7.0/8.0 and .Net framework 4.8.1 are different. .Net framework 4.8.1 and German keyboard has the consistent result, but .Net 7.0/8.0 not.

**Comment by dreddy-work** [comment]
https://dev.azure.com/ceapex/CEINTL/_workitems/edit/880034

**Comment by lonitra** [comment]
There was a PR that went in recently that changes the translations of end and insert (https://github.com/dotnet/winforms/pull/9708), so does this issue still persist?

**Comment by Philip-Wang01** [comment]
Verified this on .NET latest build: 8.0.100-rc.1.23415.19, End and Insert keys are currently translated as source string.
![image](https://github.com/dotnet/winforms/assets/86937911/431d5aa1-6e68-4eb8-8a1e-b4d2018d7eb5)

**Comment by Tanya-Solyanik** [comment]
@lonitra  - 
>There was a PR that went in recently that changes the translations of end and insert (https://github.com/dotnet/winforms/pull/9708), so does this issue still persist?

I think this is the other way around, we should fix the translation, not the unit test here :). I suppose we need a comment in the resx file, but it's best to follow up with the loc team.

**Comment by lonitra** [comment]
> I think this is the other way around, we should fix the translation, not the unit test here :). I suppose we need a comment in the resx file, but it's best to follow up with the loc team.

I'm not sure I follow here. In #9708 the change included Beenden -> Ende and Einfügen -> Einfg , which is what is expected for this issue if I understand correctly.

**Comment by Philip-Wang01** [comment]
@Tanya-Solyanik Verified this on .NET latest build: 8.0.100-rc.2.23422.11, this issue has been fixed.

Designer Time:
![image](https://github.com/dotnet/winforms/assets/86937911/2b081a96-85a5-4a29-983c-e925f30e7d75)

Run Time(a not-localized form with the code):
![image](https://github.com/dotnet/winforms/assets/86937911/7b1e7e78-5ccf-4854-b02b-07d68fc3eba8)
