### ISSUE TITLE
Form with FormBorderStyle = None adds additional height when height is small

### ISSUE THREAD

**Issue by mikola-akbal** [dotnet/winforms#9671]
### .NET version

7

### Issue description

I create Form with FormBorderStyle = None. When height of this Form is small, additional height is added. If height of Form is big enough, resulting height is OK.

That is what I see in Designer:

![1) What I see in Designer](https://github.com/dotnet/winforms/assets/45461294/6c068ebf-0de2-4d48-929f-8ea215669cee)

That is what I get when run:

![2) What I get when run](https://github.com/dotnet/winforms/assets/45461294/a14f9e71-2033-4011-80de-0f6a61b4c8bb)

I see additional 15 pixels below TextBox. Why do I get it? I need exact certain height.

### Steps to reproduce

Repository that reproduce it, is here:

[https://github.com/mikola-akbal/Form-Minimal-Height-Is-Greater-Than-Zero](https://github.com/mikola-akbal/Form-Minimal-Height-Is-Greater-Than-Zero)

There are screen-saves too.

**Comment by elachlan** [comment]
@mikola-akbal Are you using `Form.MaximumSize`?

**Comment by mikola-akbal** [comment]
> Are you using `Form.MaximumSize`?

`MinimumSize` and `MaximumSize` are zeros. You may see all in repository. It's very small.

**Comment by elachlan** [comment]
If you are trying to keep it from resizing then you can use maximum/minimum size to keep it static.

**Comment by mikola-akbal** [comment]
> If you are trying to keep it from resizing then you can use maximum/minimum size to keep it static.

Just wanted to ask: "Can it affect?"

:) Yes, it solves. Thanks.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this?

**Comment by JeremyKuhne** [comment]
It looks like this is resolved https://github.com/dotnet/winforms/issues/9671#issuecomment-1667701452.
