### ISSUE TITLE
TextRenderer.MeasureText() returns wrong value

### ISSUE THREAD

**Issue by mikola-akbal** [dotnet/winforms#9672]
### .NET version

7

### Did it work in .NET Framework?

Not tested/verified

### Issue description

TextRenderer.MeasureText() returns size that is wrong. If I use this size as width of DataGridView.Column, the text is truncated, the width of column is not enough for this text. When displaying text in TextBox, it's the same.

On the screen-save below you see Text_Size = {Width=407, Height=16}, calculated by TextRenderer.MeasureText(). You see - width 407 is less then actual 449 when TextBox and DataGridView render this text. This creates problems for placement of controls. I can not know exact size that control need to display whole text.

![Measure](https://github.com/dotnet/winforms/assets/45461294/6ed32c09-18e6-45a2-9513-4a7f1fc824f7)

### Steps to reproduce

Repository that reproduces it, is here:

[https://github.com/mikola-akbal/TextRenderer-MeasureText-Returns-Not-Certain-Value](https://github.com/mikola-akbal/TextRenderer-MeasureText-Returns-Not-Certain-Value)

It contains this screen-save too.

**Comment by elachlan** [comment]
@mikola-akbal have you tested .NET8?

**Comment by mikola-akbal** [comment]
> have you tested .NET8?

No. Is there sense?

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this?

**Comment by Olina-Zhang** [comment]
Tested it in .Net 6.0 to 8.0, they are same:
![image](https://github.com/dotnet/winforms/assets/26474449/23ed96e7-06f9-4ce8-93a0-15da3446fb42)

And in .Net framework 4.7.2 to 4.8.1,  they have same result, a little difference about the width of Text_Size
![image](https://github.com/dotnet/winforms/assets/26474449/e2346475-7fd9-4d16-b19d-aaf1cbafde20)

**Comment by mikola-akbal** [comment]
> have you tested .NET8?

I don't use yet .NET 8. I thought it's pointer to possible solution.

I can do this work. My talents are ergonomics, reliability and researching.

**Comment by JeremyKuhne** [comment]
The `Font` on the cell style is `null`, so you're getting the width of the default font. As to the width, there needs to be an extra pixel added to the width to allow for the difference between the way GDI+ (System.Drawing) and GDI (TextRenderer) handle width. (I presume the difference is this, I don't have time to dig into it to be 100% sure. You can see exactly how the full width is calculated by debugging into `column.GetPreferredWidth(DataGridViewAutoSizeColumnMode.AllCells, fixedHeight: true);` to see why it has the +1)

If you want to see some of the bounds involved, you can do something like this:

``` C#
dataGridView1.Paint += (sender, e) =>
{
    Rectangle cellRectangle = dataGridView1.GetCellDisplayRectangle(0, 0, cutOverflow: true);
    e.Graphics.DrawRectangle(Pens.Red, cellRectangle);

    var cell = dataGridView1.Rows[0].Cells[0];
    string cellText = (string)cell.Value;
    Size textSize =
    TextRenderer.MeasureText(e.Graphics, (string)cell.Value, dataGridView1.Font, new(int.MaxValue, int.MaxValue), TextFormatFlags.NoClipping);
    e.Graphics.DrawRectangle(Pens.Blue, new(cellRectangle.Location, textSize));

    Rectangle bounds = cell.ContentBounds;
    e.Graphics.DrawRectangle(
        new Pen(Color.Green)
        {
            DashStyle = System.Drawing.Drawing2D.DashStyle.Dash,
            DashPattern = new [] { 5.0f, 5.0f }
        },
        new(cellRectangle.Location, bounds.Size));
};
```

**Comment by elachlan** [comment]
I may get time to look into this in a bit.

**Comment by elachlan** [comment]
We did have a related issue in #7341. Where we found differences in MeasureText. But the core issue there was elsewhere.

**Comment by mikola-akbal** [comment]
> We did have a related issue in #7341. Where we found differences in MeasureText. But the core issue there was elsewhere.

So, you will solve this problem in [#7341](https://github.com/dotnet/winforms/issues/7341) ?

If it is, you can close this issue.

**Comment by elachlan** [comment]
No, they are separate issues. I suggest you go over Jeremy's response and debug it a bit and report results back here. Then we can fix it if there is a problem.

**Comment by mikola-akbal** [comment]
> No, they are separate issues. I suggest you go over Jeremy's response and debug it a bit and report results back here. Then we can fix it if there is a problem.

Work must be paid. I have no free time for this. You, must be, have salary for your activity. I have not.

I think, Microsoft is intersted in making its product better. I gave you documented bug. You are welcome. Good luck in researching.

I have talent of researcher, but my work costs money.

**Comment by elachlan** [comment]
I don't work for Microsoft. I am a community member.

**Comment by mikola-akbal** [comment]
> [elachlan](https://github.com/elachlan) I don't work for Microsoft. I am a community member.

I have no time for it, sorry.

**Comment by elachlan** [comment]
@Olina-Zhang could your team test the fix suggested by Jeremy here please? I am fairly confident it will be resolved.

The documentation examples all use the paint event to make use of the `e.graphics`.
https://learn.microsoft.com/dotnet/api/system.windows.forms.textrenderer.measuretext

**Comment by Olina-Zhang** [comment]
@elachlan tested the fix suggested by Jememy, it works: can get dataGridView renderring this text's actual width and height values, it same as the provided text's width and height values. See following result:

**dataGridView renderring this text's actual width and height values:**
![image](https://github.com/dotnet/winforms/assets/26474449/2e1ecc56-6cbf-418e-a6de-972f957f141a)

**The provided text's width and height values:**
![image](https://github.com/dotnet/winforms/assets/26474449/b0bc050e-5bef-4e69-88c7-d84503d88273)

**Comment by elachlan** [comment]
Closing as we have the correct method of using measuretext demonstrated above.
