### ISSUE TITLE
Investigate `.editorconfig` setting for xml comment indentation

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#9680]
The code style of two spaces for xml comment content should be enforced.

**Comment by elachlan** [comment]
@Youssef1313 I don't suppose you know if there are settings for it?

**Comment by Youssef1313** [comment]
I don't know a way for enforcing it. So far I see every repo just set their settings in editorconfig and rely on the IDE when they do format the csproj

**Comment by elachlan** [comment]
This is for XML comments in C# code. We have a two space indent code style.

**Comment by Youssef1313** [comment]
Oh sorry I mis-read it and thought it's for csproj XML.

Though I'm still not aware of anything to enforce spacing in doc comments.

**Comment by merriemcgaw** [comment]
If someone finds a way to do this then we would be happy to enforce it?

**Comment by elachlan** [comment]
Closing in favor of #10587
