### ISSUE TITLE
Missing System.Drawing.Common NuGet package for .NET 8 Preview 6 and newer.

### ISSUE THREAD

**Issue by jlaanstra** [dotnet/winforms#9689]
### .NET version

.NET 8 Preview 6 and newer.

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Last available NuGet package is targeting .NET 8 Preview 5

### Issue description

There haven't been any new preview packages for System.Draing.Common since .NET 8 preview 5: https://www.nuget.org/packages/System.Drawing.Common/8.0.0-preview.5.23280.5

Is this simply an oversight or is the package effectively deprecated? Related to the migration from runtime to winforms?

### Steps to reproduce

N/A

**Comment by merriemcgaw** [comment]
@ViktorHofer was this automated during the handoff to WinForms? Let's make sure we can get this taken care of for RC1
FYI @JeremyKuhne

**Comment by ViktorHofer** [comment]
@mmitche fixed this in the publishing pipeline recently AFAIK

**Comment by mmitche** [comment]
It got fixed in arcade-services but we'll need to update darc in the staging pipeline so that it picks up the changes. That update missed preview7.

**Comment by mmitche** [comment]
Took another look. It's just a matter of an arcade-services rollout, which happened today. So this should be resolved for RC 1+.

**Comment by mmitche** [comment]
@rbhanda We'll need to publish this package as a 1-off for p6 and p7

**Comment by rbhanda** [comment]
both the p6 and p7 System.Drawing.Common nuget packages are pushed

**Comment by mmitche** [comment]
Closed as resovld by @rbhanda
