### ISSUE TITLE
[GB18030] Graphics.DrawString does not render correctly when the input text is GB18030 characters. 

### ISSUE THREAD

**Issue by MandiMan** [dotnet/winforms#9693]
### .NET version

.NET SDK 8.0.100-rc.1.23402.12

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it also repro on .NET6.0 & 7.0.

### Issue description

The print preview does not display correctly when the input text is Dehong Dai(eg: ᥘᥣᥭᥰᥖᥭᥰᥖᥬᥲᥑᥨᥒᥰ) and Xishuangbanna Dai(eg: ᦎᦷᦑᦺᦖᦺᧈᦉᦲᧇᦉᦸᧂᦗᧃᦓᦱ) 

![image](https://github.com/dotnet/winforms/assets/108860782/0c7cb17d-a4cf-4b01-844c-5e235b46993d)
![image](https://github.com/dotnet/winforms/assets/108860782/7069ca85-b692-430d-867c-f4f4b299c4bf)

### Steps to reproduce

1. Unzip the folder [TestAPP.zip](https://github.com/dotnet/winforms/files/12300135/TestAPP.zip)
2. Build and run this project. 
3. In the textbox, input **ᥘᥣᥭᥰ ᥖᥭᥰ ᥖᥬᥲᥑᥨᥒᥰ** or **ᦷᦎᦺᦑᦺᦖᧈᦉᦲᧇᦉᦸᧂᦗᧃᦓᦱ** 
4. Click on the preview button and observe

**Comment by elachlan** [comment]
@Olina-Zhang could your team please test this?

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang could your team please test this?
> 
> Is it a regression from .Net 4.8?

This issue was found by our team. It also reproduces in .Net framework versions.

**Comment by JeremyKuhne** [comment]
This is an issue/limitation with GDI+ `GdipDrawString`. It doesn't have anything to do with the print preview. You can replicate this with the `Form.OnPaint()`. It works fine with `TextRenderer` as it doesn't use GDI+ to render the text:

``` C#
protected override void OnPaint(PaintEventArgs e)
{
    base.OnPaint(e);

    using Font font = new("Times New Roman", 14);
    for (int i = 1; i <= 5; i++)
    {
        // This works fine, but uses GDI, not GDI+.
        // TextRenderer.DrawText(e.Graphics, "ᦎᦷᦑᦺᦖᦺᧈᦉᦲᧇᦉᦸᧂᦗᧃᦓᦱ", font, new Point(i * 20, i * 20), Color.Red);

        e.Graphics.DrawString("ᦎᦷᦑᦺᦖᦺᧈᦉᦲᧇᦉᦸᧂᦗᧃᦓᦱ", font, Brushes.Blue, i * 20, i * 20);
    }
}
```

@merriemcgaw we need to get this one to GDI+.

**Comment by merriemcgaw** [comment]
@Olina-Zhang I think we can change the Print Preview part of the app to use the code @JeremyKuhne provides and close this issue.

@Olina-Zhang can your team also file a Windows bug for GDI team to make sure they're aware?

**Comment by JeremyKuhne** [comment]
> I think we can change the Print Preview part of the app to use the code @JeremyKuhne provides and close this issue.

This is not a thing to fix in PrintPreview. This is completely orthogonal to PrintPreview.

> can your team also file a Windows bug for GDI team to make sure they're aware?

To be clear: I don't know if the same team owns GDI and GDI+. This is GDI+.

**Comment by Olina-Zhang** [comment]
We will update that testing application about Print Preview with above code. and waiting for your confirm if need a Windows bug @merriemcgaw.

**Comment by elachlan** [comment]
@Olina-Zhang Jeremy is saying above that the bug is in `GDI+` as it hasn't implemented everything that `GDI` has. So I think a bug report is appropriate. Its not something we can fix in winforms.

**Comment by Olina-Zhang** [comment]
Filed an internal Windows bug: https://microsoft.visualstudio.com/OS/_workitems/edit/46032769. Closing this issue now.
