### ISSUE TITLE
Designer crashes when running Visual Studio 17.7.0 as a DpiUnaware process

### ISSUE THREAD

**Issue by rafcolson** [dotnet/winforms#9714]
### Environment

Version 17.7.0

### .NET version

.NET 6.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Same issue as described in #7609. Reemerged after the last update released on August 8th, 2023 (Visual Studio 2022 version 17.7).

### Issue description

In order to run VS in DpiUnaware mode, I use this registry setting:

`
[HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe"="DPIUNAWARE"
`

Having added the key and value to the registry, VS fails to launch the designer when viewing the form's designer in my solution, throwing this error:

```[15:35:29.751860] warn: DPI mode SystemAware specified for the project is different from the DPI mode specified for the designer. Winforms designer will have DPI mode DpiUnaware 
[15:35:39.852848] fail: [MyProject]: Failed to launch design tools server process process
                        System.InvalidOperationException: Failed to set process DPI mode value to: DpiUnaware.
                           at Microsoft.WinForms.Utilities.Desktop.DpiHelper.SetDesignerProcessDpiAwareness(DpiAwarenessContext dpiContext)
                           at Microsoft.DotNet.DesignTools.Server.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext()

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
```

### Steps to reproduce

- add key and value to the registry
- open solution
- view the form's designer (Right-click on the form and choose "View Designer")

**Comment by Olina-Zhang** [comment]
Reproduce it in Version 17.7.0 and the latest VS build from main branch.  It doesn't reproduce in Version 17.6.5.

**Comment by Shyam-Gupta** [comment]
@rafcolson Fix for this issue has been implemented and it should be available in next 17.8 Preview release.

I would also like to mention that starting with `17.8 Preview 1`, a new project property `ForceDesignerDpiUnaware` has been introduced which will help launch WinForms out-of-process designer in DPIUnaware mode. More details about this property are available [here](https://aka.ms/winforms/designer/unaware-mode). Thanks.

**Comment by rafcolson** [comment]
@Shyam-Gupta That's great! Thanks for that fix. Also looking forward to using the `ForceDesignerDpiUnaware` option. It surely will make it a lot less awkward to work on projects in DpiUnaware mode.

**Comment by MandiMan** [comment]
Verified this issue in the latest VS build: 17.8.0 Preview 2.0 [34017.374.main], it cannot repro.  When using registry key as following screenshot to set VS as DpiUnaware mode, the form designer loads successfully.
![image](https://github.com/dotnet/winforms/assets/108860782/9376156b-a37c-4664-bd18-6d1e470ecb58)
