### ISSUE TITLE
When will WinForms fully support VB.NET in .NET Core 3.0?

### ISSUE THREAD

**Issue by camleng** [dotnet/winforms#974]
I'm currently trying to convert a .NET Framework WinForms app over to .NET Core 3.0. I'm in the process of converting my class libraries to .NET Standard 2.0. After installing the `Microsoft.Windows.Compatibility` NuGet package to try to get Windows-specific functionality back, I'm getting type errors for WinForms controls like Buttons, Labels, GroupBoxes. i.e. `Type 'System.Windows.Forms.Button' is not defined`. Any idea of when this will be resolved? Is this an issue with the compatibility NuGet package?

**Comment by Berrysoft** [comment]
>I'm in the process of converting my class libraries to .NET Standard 2.0.

.NET Standard 2.0 doesn't support WinForms. Maybe you should target the project to multi-frameworks, e.g., `<TargetFrameworks>net48;netcoreapp3.0</TargetFrameworks>`

>...try to get Windows-specific functionality back,...

`Microsoft.Windows.Compatibility` doesn't contains WinForms. Instead, you should change the `Sdk` property in the proj file to `Microsoft.NET.Sdk.WindowsDesktop` and set `<UseWindowsForms>true</UseWindowsForms>`

>When will WinForms fully support VB.NET in .NET Core 3.0?

I don't know when to *fully* support, but you can now use `dotnet new winforms -lang VB` to create a new Visual Basic WinForms project.

**Comment by merriemcgaw** [comment]
@camleng is there something specific missing? What currently is not working?

**Comment by Lohnegrim** [comment]
@merriemcgaw it may not directly releated to winforms, but the whole support for the My-Namepsace is missing, and this includes the autogenerated My.MyProject.Forms Class that is often used to access a DefaultInstance of all the Forms in the Assembly.

**Comment by camleng** [comment]
This was my mistake. Instead of just targeting my class libraries to netstandard2.0, I mistakenly targeted everything to netstandard2.0 instead of netcoreapp3.0. Thank you for the help!

**Comment by RussKie** [comment]
Thank you for the follow up.
