### ISSUE TITLE
Winforms designer moves anchored control

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#9740]
### .NET version

.NET 8.0.100-rc.1.23415.19

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, this issue cannot repro in .NET7.0 & .NET 6.0.

https://github.com/dotnet/winforms/assets/94418985/f2cb9dc0-b311-4640-933c-a204eb936646

### Issue description

**Current Behavior:**
The button's been moved.
After step5:
![design](https://github.com/dotnet/winforms/assets/94418985/927cca43-91d8-45be-9dfc-19dedad86988)

After step6:
![moved design](https://github.com/dotnet/winforms/assets/94418985/fbcf067c-c90e-4468-8027-4519bde76d9c)

But in runtime, the button is not moved.
![moved run](https://github.com/dotnet/winforms/assets/94418985/b293678c-8ce6-46eb-9e09-dd23bfc44817)

https://github.com/dotnet/winforms/assets/94418985/9858de36-6082-48d6-a586-1d62fc831b4e

 
**Expected Behavior:**
The button shouldn't be moved.

https://github.com/dotnet/winforms/assets/94418985/02cb3533-bcd2-43aa-8846-e72e3345d59d

### Steps to reproduce

1. Create a Winforms .NET Core 8.0 application
2. Add a panel to form designer
3. Change the panel's Dock property to Bottom
4. Add a button to the panel
5. Change the button's anchor property from top & left to bottom & right
6. Close and reopen form designer
7. Observe the location of the button control

**More Info:**
1. This issue also reproes in other container controls and common controls.
2. The initial ticket link is here: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1866799

**Comment by KlausLoeffelmann** [comment]
@MelonWang1: This happens independent of the selected HighDPI mode, is that correct?

**Comment by MelonWang1** [comment]
@KlausLoeffelmann Yes, you are right. It reproduces whether the VS is set to the 3 modes of HighDPI or the application is set to the 3 modes of HighDPI.

**Comment by dreddy-work** [comment]
Working on solution. We post-phoned discussion on updating designer deserialization order to match with runtime to avoid issues like this. Working on fix that doesn't depend on the deserialization order.

**Comment by dreddy-work** [comment]
@MelonWang1, given we removed default opt in of new anchor feature, can you cross check this with latest runtime and close if it doesn't repro?

**Comment by NJ-Brad** [comment]
I had also seen this problem previously.  Fix looks good to me.

**Comment by MelonWang1** [comment]
@dreddy-work Verified this issue in VS 17.9.0 Preview 1.0 [34216.203.main] with default .NET SDK 8.0.100-rc.2.23502.2 build, it has been fixed. Screenshot as below. So closed it.

https://github.com/dotnet/winforms/assets/94418985/d31e5d82-2cfd-4f1a-8ea6-774c06ad1468
