### ISSUE TITLE
System.Drawing.Common xml docs limited after .NET 6.0

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#9742]
@JeremyKuhne

Yes, the absence of a README is _certainly unfortunate_, but there is a much more significant issue - the lack of documentation (hints in Visual Studio) for most elements from `System.Drawing.Common`:

![image](https://github.com/dotnet/winforms/assets/17767561/a7fd743a-0df9-4c32-a861-eed9738e2ff3)

I quickly checked the NuGet packages and found that starting from Net6, the XML file has been significantly slimmed down:
![image](https://github.com/dotnet/winforms/assets/17767561/cf8b85cb-3f5b-46b2-bd0f-70ac62f0192f)

The line from the V.S. screenshot above (`"T:System.Drawing.Drawing2D.GraphicsPath"`) is only present in version 4.70: 
![image](https://github.com/dotnet/winforms/assets/17767561/03e0635f-4665-4292-bec4-e11a43beb552)

_Originally posted by @kirsan31 in https://github.com/dotnet/winforms/issues/9729#issuecomment-1681843321_

**Comment by JeremyKuhne** [comment]
@ericstj do you have any idea what might have happened in .NET 6 to cause this?

**Comment by kirsan31** [comment]
@JeremyKuhne I need to clarify a bit that this might happens **prior** .Net6 (Net5?). Because as you can see on my screenshot I have only these packages installed:
![image](https://github.com/dotnet/winforms/assets/17767561/69495975-bb80-46a1-9d1f-0fcf4db8d85e)

So, strictly speaking I didn't check [4.7.1 - 6.0.0-rc.2.21480.5].

**Comment by ericstj** [comment]
I think @carlossanlop noticed this - and we might have even made some servicing changes to fix it should we ever service a new build - it had to do with not pulling the authored docs correctly out of `Microsoft.Private.Intellisense`.  @ViktorHofer do you know if we looked at hooking up docs in the latest builds of this after it was moved to Winforms repo?

**Comment by ViktorHofer** [comment]
System.Drawing.Common uses the intellisense package as the rest of the winforms repository: https://github.com/dotnet/winforms/blob/89f89590ddb6910cc1605ba430b5b72f3ed54fab/src/System.Drawing.Common/src/packaging.targets#L111-L117

The lookup path is here: https://github.com/dotnet/winforms/blob/89f89590ddb6910cc1605ba430b5b72f3ed54fab/eng/packageContent.targets#L6

System.Drawing.Common.xml exists under that path meaning that System.Drawing.Common in winforms should use the "correct" documentation intellisense XML file. All that said, ideally winforms would switch over to compiler generated XML files in the future.

**Comment by JeremyKuhne** [comment]
@kirsan31 Can you validate that you see the "better" IntelliSense in 8.0?

**Comment by kirsan31** [comment]
@JeremyKuhne 

> Can you validate that you see the "better" IntelliSense in 8.0?

I have VS 1`7.6.5` and with it can try only `.NET 8.0 SDK (v8.0.100-**preview.3**)`.
And with it I have really better IntelliSense with `System.Drawing.Common` 👍
But for some reason with this SDK I have no docs for `System.Drawing` (with net6-7 all are good) 😁
For example:
![image](https://github.com/dotnet/winforms/assets/17767561/c55be789-98a2-4a5a-8acd-f502e28ae7a5)

**Comment by JeremyKuhne** [comment]
@ericstj is there a known issue with libraries IntelliSense or should I transfer this over for that part?

**Comment by ViktorHofer** [comment]
As Eric mentioned above, we had an issue that impacted the Intellisense file for packages released during 6.0 and 7.0:

> I think @carlossanlop noticed this - and we might have even made some servicing changes to fix it should we ever service a new build - it had to do with not pulling the authored docs correctly out of Microsoft.Private.Intellisense.

Please inspect the latest System.Drawing.Common and Microsoft.WindowsDesktop.App.Ref packages and check if the Intellisense file for System.Drawing.Common is now correct.

**Comment by JeremyKuhne** [comment]
We appear to be in good shape for the current platforms.
