### ISSUE TITLE
.NET 6 Winforms Cursors leak CPicture objects (User and GDI objects leak)

### ISSUE THREAD

**Issue by ilCosmico** [dotnet/winforms#9774]
### .NET version

.NET6

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Works in .NET Core 3.1 (also works in .NET 7)

### Issue description

.NET 6 Windows Forms System.Windows.Forms.Cursor object creation leaks ole32!CPicture objects which leaks USER (Cursor) and GDI objects (Surf) due to a ref count bug. If you do this long enough, you could experience an OutOfMemoryException (or other variation of exhausting resources) due to hitting the 10K per-process limit for GDI objects.

I'd like to highlight that this issue has been previously reported [here](https://github.com/dotnet/winforms/issues/8583). It's worth noting that .NET6 benefits from long-term support, which is why I'm a bit surprised that a fix hasn't been implemented yet.
Since upgrading to .NET7 isn't a viable option for me at the moment, I would greatly appreciate your attention to resolving this matter within the .NET6. Thank you for considering my request.

### Steps to reproduce

```
for (int i = 0; i < 10000; i++)
{
    Console.WriteLine(String.Format("Creating cursor {0}", i));

    var cursor = new Cursor("pan.cur");
    cursor.Dispose();
}


Console.ReadKey();
```

**Comment by merriemcgaw** [comment]
@ilCosmico - are you saying that the leaks do not happen in .NET 7, but they do in .NET 6? Is this an upgrade blocker for your company? 

/cc: @JeremyKuhne

**Comment by ilCosmico** [comment]
@merriemcgaw Yes, that's so.

**Comment by JeremyKuhne** [comment]
Need to do a bar check with tactics.

**Comment by JeremyKuhne** [comment]
@dreddy-work the fix has been merged into 6.0. Is there anything else we need to do to get this to flow?

**Comment by ilCosmico** [comment]
Thank you @JeremyKuhne for fixing the issue. What is the .net6 version I will find the fix?

**Comment by Eudora-Li01** [comment]
Verified this issue on release/6.0 branch of Winforms repo, it was fixed. No USER/GDI object leak or exception(s).

https://github.com/dotnet/winforms/assets/130345015/b3d02828-39c6-43fa-a3bb-5de05320fc1b

**Comment by ilCosmico** [comment]
Usually, I check "GDI objects" column of the Task Manager. @Eudora-Li01 where I can see this info in the Diagnostic Tools of Visual Studio?

**Comment by Eudora-Li01** [comment]
> 

The above video displays that no exception thrown in VS. I also check "GDI objects" column of the Task Manager to check if GDI objects leak or not. It seems like no such info in the Diagnostic Tools of Visual Studio.
![image](https://github.com/dotnet/winforms/assets/130345015/c24ccd81-722a-4787-98cc-1f9e1542f6b2)

**Comment by ilCosmico** [comment]
I see there are 27 GDI objects... @Eudora-Li01  what's the result using the previous version of .NET6? I suppose you will see to grow a lot this number :)

**Comment by JeremyKuhne** [comment]
@ilCosmico I believe this should show up in 6.0.23 in October (it is too late for September), verifying.

**Comment by MelonWang1** [comment]
Verified with .NET 6.0.23 service test pass build, it was fixed, test result was same as above video.

**Comment by ilCosmico** [comment]
> Verified with .NET 6.0.23 service test pass build, it was fixed, test result was same as above video.

At https://dotnet.microsoft.com/en-us/download/dotnet/6.0, I cannot yet view this build. Will it be released in October?

**Comment by MelonWang1** [comment]
@ilCosmico Yes, you can check this in 6.0.23 in October.
