### ISSUE TITLE
Triggering a flush in the WinForms Designer (Saving, Doc-Tab change) is VERY slow.

### ISSUE THREAD

**Issue by 2Tadmin** [dotnet/winforms#9794]
### .NET version

NET 7

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

I haven't test. I test only with full framework 4.7.2 (in VS 2022 last revision)

### Issue description

using the editor in VS2022 adding controls from toolbox to winform (windows form app NET 7) , when the  controls are enough, for example 30-40 if you try to save form, select control, double click on button to show handler code,..., the hourglass appears and lock for some seconds, If you have many controls the cursor with hourglass still for also 20 seconds and is not possible to do nothing.
If I use the IDENTICAL winform  so with the same controls BUT for framework Target 4.7.2 the speed is good during design editor.
The problem is for new editor for NET 7 and it will be fixed (becouse is not possible working in this condition) ore is another problem that is necessary do something?
Thanks

### Steps to reproduce

to reproduce is very simple add loto of controls label and text box and button on winform and try to save, doubble click on button, do Copy and paste of control and you can see.

**Comment by JeremyKuhne** [comment]
@2Tadmin How many controls are you talking about? Also, can you please share the exact version of Visual Studio (from the about box)?

**Comment by 2Tadmin** [comment]
Hello,
my VS studio 2022 version is 17.7.2 and I show you a video that is possible to see when I click on button spent many seconds before show the code. This is not always but very very often.
I Attach Video. The number of controls less then 80
If you can see the CPU all cores go to 100% 
Thanks
NOTE: in this form there are also some telerik control but in this case a click on microsoft button

https://github.com/dotnet/winforms/assets/107557346/47c41c98-fb9a-4d65-a79a-a249ca52cb6c

**Comment by KlausLoeffelmann** [comment]
We did some extensive work around this in 17.6, and then again in 17.8.
Please test it with those versions, and if this problem remains, reopen this issue.

Closing this as fixed.

**Comment by 2Tadmin** [comment]
Hello,
with version 17.7.2 the issue there is, so very slow, when version 17.8 will be available (not in preview) I'll download it and test.
This 'slow designer' is much, much worse if I using Telerik Winform controls.
Thanks a lot for your answer.
