### ISSUE TITLE
Make AccessibleObject trimmable

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#9795]
In order for AOT/Trimming to be a viable option we need to change AccessibleObject to fully utilize native VARIANTs and pointers and use ComWrappers for our CCW projections.

There are a number of steps to this, including:

- Implement the CsWin32 IAccessible.Interface on AccessibleObject and have the existing public IAccessible interface projection just wrap this.
- Convert the UIA interfaces to use CsWin32.
- Ensure that we're using IManagedWrapper on all of our accessible objects.

`AccessibleObject` is a little difficult to make efficient due to it being public with numerous virtual members.

**Comment by elachlan** [comment]
Related: #9784
