### ISSUE TITLE
Optimize AccessibleObject when transitioning to support trimming

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#9815]
There are numerous places in the WinForms code that we do a lot of wasted work to satisfy public virtual methods. This often shows up as object creation for methods that don't technically need to be created.

A common strategy to use is to check the type in a method to see if the current instance is the internal class and therefore a virtual defined in the class hasn't been overridden. A theoretical example:

``` C#
if (GetType() == typeof(Button))
{
    // Not derived, take an optimized path
}
else
{
    // Derived class, take the less optimized path
}
```

While this works, it doesn't scale to more complicated scenarios. `AccessibleObject`, for example, has a complicated tree.

In `AccessibleObject` the thing we would probably do is something like this:

``` C#
internal static class TypeExtensions
{
    private static readonly Assembly s_windowsFormsAssembly = typeof(Control).Assembly;
    public static bool IsWindowsFormsAssemblyType(this Type type) => type.Assembly == s_windowsFormsAssembly;
}

public class AccessibleObject
{
    private protected bool IsWindowsFormsAssemblyType { get; }
    public AccessibleObject() => IsWindowsFormsAssemblyType = GetType().IsWindowsFormsAssemblyType();
}
```

Then we could leverage that to avoid extra work:

``` C#
public virtual AccessibleObject? Parent => TryGetAccessibleObject(GetParentDispatch());

private protected virtual bool UseGetParentDispatchForParent => IsWindowsFormsAssemblyType;

private protected virtual IDispatch* GetParentDispatch()
{
    using var accessible = SystemIAccessible.TryGetIAccessible(out HRESULT result);
    if (result.Succeeded)
    {
        IDispatch* dispatch;
        result = accessible.Value->get_accParent(&dispatch);
        return dispatch;
    }

    return null;
}

// ...

/// <inheritdoc cref="UIA.IAccessible.get_accParent(IDispatch**)"/>
HRESULT UIA.IAccessible.Interface.get_accParent(IDispatch** ppdispParent)
{
    if (ppdispParent is null)
    {
        return HRESULT.E_POINTER;
    }

    if (UseGetParentDispatchForParent)
    {
        *ppdispParent = GetParentDispatch();
        return *ppdispParent is null ? HRESULT.S_FALSE : HRESULT.S_OK;
    }

    AccessibleObject? accessibleObject = Parent;
    if (accessibleObject is null)
    {
        *ppdispParent = null;
        return HRESULT.S_FALSE;
    }

    *ppdispParent = ComHelpers.GetComPointer<IDispatch>(accessibleObject);
    return HRESULT.S_OK;
}

object? IAccessible.accParent
{
    get
    {
        IDispatch* dispatch = null;
        ((UIA.IAccessible.Interface)this).get_accParent(&dispatch);
        return Marshal.GetObjectForIUnknown((nint)(void*)dispatch);
    }
}
```

This avoids unnecessary wrapping of native handles and is trim/AOT friendly.

**Comment by elachlan** [comment]
This is really cool.

Maybe we can prompt runtime/C# to add something that would allow us to avoid `typeof(Control).Assembly;`. I had to do this in my own code and it feels very hacky.

SO, I asked chatGPT on how it would solve it and this was the best approach:

> **Compiler Intrinsics:** Similar to how nameof gives you the name of a variable or type at compile-time, introduce a construct that lets you get the assembly of the current code file at compile-time.
> 
> ```csharp
> var assembly = assemblyof;
> ```
> Of the above solutions, the third (compiler intrinsics) feels like it might fit best with existing patterns in C# like nameof and typeof. However, any such change would need careful design, thorough community feedback, and likely be part of a larger revision of the C# language.

**Comment by elachlan** [comment]
Are `AccessibleObjects` complex enough that we can't use a sourcegenerator to create them?

**Comment by JeremyKuhne** [comment]
I think @lonitra covered this well enough with the port to ComWrappers. Anything left should be incrementatl.
