### ISSUE TITLE
Handle wrapping COM pointers in managed objects

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#9816]
Built-in COM interop is not available when trimming or AOT are enabled. We need to use `ComWrappers` in those scenarios. This is important where we currently publicly expose COM RCWs. One concrete example of this is in `AxHost`. `AxHost.GetOcx` exposes the ActiveX instance and it is also exposed via the customizable construction virtual `AxHost.CreateInstanceCore(Guid clsid)`.

We need to add a helper in `ComHelpers` that handles falling back to `ComWrappers` when necessary. The simple implementation would be something like this:

``` C#
internal static unsafe partial class ComHelpers
{
    internal static bool BuiltInComSupported { get; }
        = AppContext.TryGetSwitch("System.Runtime.InteropServices.BuiltInComInterop.IsSupported", out bool supported)
            ? supported
            : true;

    public static object GetObjectForIUnknown(IUnknown* unknown)
        => BuiltInComSupported
            ? Marshal.GetObjectForIUnknown((nint)unknown)
            : ComInterfaceMarshaller<object>.ConvertToManaged(unknown).OrThrowIfNull();
}
```

We should also consider a switch that allows forcing the `ComInterfaceMarshaller` and potentially picking it by default if the reflection based support for casting to `[ComImport]` interfaces is enabled. ("System.Runtime.InteropServices.Marshalling.EnableGeneratedComInterfaceComImportInterop" AppContext flag or "EnableGeneratedComInterfaceComImportInterop" in MSBuild)

The only issue with the `ComInterfaceMarshaller` is that presumes objects are free-threaded. We can deal with this by implementing our own `IUnknownStrategy` that wraps the GIT much as our `AgileComPointer` does. This would require deriving from `StrategyBasedComWrappers` and returning a new instance of the strategy by overriding `GetOrCreateIUnknownStrategy()`.

**Comment by JeremyKuhne** [comment]
Fyi @jkoritzinsky

**Comment by weltkante** [comment]
not sure how much this is related, but there is desire of having AxHost work in trimming scenarios, currently doing handwritten bindings in #10583 to get the basics working - but while the ActiveX control currently can be (manually) written using COM source generators, WinForms itself needs work done to drop classic COM interop

**Comment by JeremyKuhne** [comment]
ComHelpers.GetObjectForIUnknown now does this.
