### ISSUE TITLE
System.Drawing.ImageConverter cannot convert from System.Drawing.Icon

### ISSUE THREAD

**Issue by Vino-Wang** [dotnet/winforms#985]
* OS: RS4 X64
* VS: Dev16 16.2.0 Preview 1.0 [28913.52.d16.2]
* .NET Core Version: 3.0 Preview 6 3.0.100.11867 from Master branch
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
System.Drawing.ImageConverter cannot convert from System.Drawing.Icon

**Actual behavior:** 
System.Drawing.ImageConverter cannot convert from System.Drawing.Icon, and the value of the result_obj is null.
![ImageConverterIssue(Actual)](https://user-images.githubusercontent.com/18568603/57668656-91ee3900-763a-11e9-9e13-e141412b1f07.png)

**Expected behavior:**
System.Drawing.ImageConverter can convert from System.Drawing.Icon, the value of the result_obj isn’t null.
![ImageConverterIssue(Expected)](https://user-images.githubusercontent.com/18568603/57668661-94e92980-763a-11e9-9b76-c43937ed64a7.png)

**Minimal repro:**
1.	Create a Winforms .NET Core app.
2.	Add following code into Form.cs file.
   public Form1()
   {
    InitializeComponent();

    Icon test_Icon = Icon;
    myObj = new ImageConverter();
    Object result_obj = myObj.ConvertFrom(test_Icon);

    }
    protected System.Drawing.ImageConverter myObj = null;
3.	Make a breakpoint at this code line: Object result_obj = myObj.ConvertFrom(test_Icon);
4.	Run the app.

Here are the simple apps:
[ImageConverterIssue_NETCore.zip](https://github.com/dotnet/winforms/files/3175706/ImageConverterIssue_NETCore.zip)
[ImageConverterIssue_NETFramework.zip](https://github.com/dotnet/winforms/files/3175707/ImageConverterIssue_NETFramework.zip)

**Comment by danmosemsft** [comment]
I think this is an issue in ImageConverter, which is in the dotnet/corefx repo. @Vino-Wang could you please close this and open an issue there?

@safern is this intentional? This line is missing from .NET Core, which is present in .NET Framework:
https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/ImageConverter.cs,40

**Comment by RussKie** [comment]
> I think this is an issue in ImageConverter, which is in the dotnet/corefx repo. @Vino-Wang could you please close this and open an issue there?

I think the issue can be moved via Zendesk, I think I saw @merriemcgaw doing this.

**Comment by safern** [comment]
> @safern is this intentional? This line is missing from .NET Core, which is present in .NET Framework:
https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/ImageConverter.cs,40

No I don't think it is intentional, we just messed up when porting from framework into Drawing. Moving the issue into corefx and marking it as 3.0

**Comment by safern** [comment]
Opened: https://github.com/dotnet/winforms/issues/985

**Comment by Judy-Gao** [comment]
Verified in .Net Core SDK 3.0.100 Preview7 latest build 3.0.100.12261 from Master branch. This bug is fixed. So closed the bug.
![985-fixed](https://user-images.githubusercontent.com/49627041/58939859-ad1c1680-87aa-11e9-8c18-c784455fd5a5.PNG)
