### ISSUE TITLE
Remove hardcoded .NET versions when Arcade updates SDK to 9.0

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#9851]
Until Arcade updates to a 9.0 SDK, you want to set these properties in your root Directory.Build.props file with a TODO to remove it when a 9.0 SDK is used: 

```
<NetMinimum>net8.0</NetMinimum>
<NetPrevious>net8.0</NetPrevious>
<NetCurrent>net8.0</NetCurrent>
```

This will drop the net6.0 and net7.0 assets from System.Drawing.Common (which is intentional) and doesn't yet use the net9.0 TFM (which would require some msbuild work). I think winforms in the past continued building the current TFM until an SDK is used that supports the newer TFM.

_Originally posted by @ViktorHofer in https://github.com/dotnet/winforms/issues/9836#issuecomment-1708860563_

Once Arcade is upgraded, we should revert [that change](https://github.com/dotnet/winforms/pull/9836/commits/3be1f719e3944b0a7b51a487f5c002f1e469e79a) and re-evaluate if we still need conditional compilation in System.Drawing.Common

**Comment by dreddy-work** [comment]
@Tanya-Solyanik / @ViktorHofer , i would need your help to sttream line this. I expect to get SDK on 9.0 in couple of days and what we do here and why should be documented for next major release.  @lonitra / @JeremyKuhne .

**Comment by ViktorHofer** [comment]
@dreddy-work can you please elaborate on what you exactly need help with? Is it the why or what and how?

**Comment by dreddy-work** [comment]
@ViktorHofer, within this context, we have introduced three new constants that appear to be utilized by `System.Drawing.Common`. To my understanding, this was carried out exclusively for generating the 8.0 package for System.Drawing.Common, excluding the legacy targets. I have a few questions based on this understanding:

- If we were to remove these constants, would this result in the creation of legacy targets for System.Drawing.Common alongside the 9.0 target?
- Is it necessary to perform this action each time a major release occurs? or there is a better way to do this? eitherway, we need to document this on our side in release activities section.
- Are we consistently producing only the Current, minimum, and previous target framework monikers (TFMs)? What should be done in the event of any other TFM that is still under support?

@Tanya-Solyanik / @JeremyKuhne

**Comment by Tanya-Solyanik** [comment]
@dreddy-work  - these constants are defined in arcade. Right now they are pointing to the old versions, but at some point arcade will update them to point to 8.0. Once that happens, PR #9864 can be merged.

**Comment by lonitra** [comment]
Looks like this was done as part of https://github.com/dotnet/winforms/pull/10486/files#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16e . Closing.
