### ISSUE TITLE
When branding to NET9 is done, remove conditional compilation in System.Drawing.Common

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#9863]
Interop with GDI+ in System.Drawing.Common is done differently for .NET6 and .NET7+, so it is conditionally compiled using `#if NET7_0_OR_GREATER` in the code and conditional inclusion in the project file. This was required because the .NET8.0 version of the standalone package was [multitargeted ](https://github.com/dotnet/winforms/blob/1be42ac61d472f01dc6a2da06230b6e67e4cdfde/src/System.Drawing.Common/src/System.Drawing.Common.csproj#L3)to .NET6, .NET7, .NET8, netstandard2.0 and net472. NETFX version is a facade assembly, i.e. contains only type forwards. And the netstandard2.0 version does not contain [implementations](https://github.com/dotnet/winforms/blob/release/8.0/src/System.Drawing.Common/src/NotSupported.cs).  

The NET9 version will target .NET8, .NET9, netstandard2.0 and NET472, as these will be in support by the RTM time, so we will not need conditional compilation after branding is done.

**Comment by merriemcgaw** [comment]
This can be done in main soon.

**Comment by elachlan** [comment]
I think it would make sense to just do this along with the CsWin32 conversion.

**Comment by merriemcgaw** [comment]
@JeremyKuhne @lonitra is this done? Do we need to do it?

**Comment by JeremyKuhne** [comment]
@merriemcgaw I'm currently working through this

**Comment by JeremyKuhne** [comment]
Did this.
