### ISSUE TITLE
Failed to load assembly: System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by BoltBait** [dotnet/winforms#9874]
## Environment

I just bought a new laptop with Windows 11 Home and did a fresh install of VS 2022 Community.  Here's the info from the about box:

Microsoft Visual Studio Community 2022
Version 17.7.3
VisualStudio.17.Release/17.7.3+34024.191
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA783
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.273.65229
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.273.65229
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.273.65229
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.10.1
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20628.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

## .NET version

Here are the first few lines of my solution file:

```
Microsoft Visual Studio Solution File, Format Version 12.00
Visual Studio Version 17
VisualStudioVersion = 17.4.33103.184
MinimumVisualStudioVersion = 10.0.40219.1

```
and the first few lines of the project file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <RootNamespace>PaintDotNet.Effects</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;Release;FastDebug</Configurations>
    <Deterministic>false</Deterministic>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

```

## Did this work in a previous version of Visual Studio and/or previous .NET release?

I am able to build my project and the build works fine.

## Issue description

I'm just not able to edit any Windows forms using the Designer.  It simply won't open. 

![image](https://github.com/dotnet/winforms/assets/14893317/7f8e2dfe-b201-465c-a61c-6d82f0d071b4)

The specific error message I'm getting is listed in the Diagnostics section below.

I've tried lots of stuff from the web, like whitelisting the vs directory, cleaning the solution, refreshing my nuget packages, and running vs without a project loading it later. Google is failing me at this point.  Please help!

## Steps to reproduce

1. Open project
2. Double click on any form to open it

My project's forms run from complicated to very simple.  None will open.

The code is actually available at GitHub here: https://github.com/BoltBait/CodeLab
It is a plugin for Paint.NET which is available here: https://www.dotpdn.com/downloads/pdn.html

## Diagnostics

```text
[16:27:49.012726] fail: [CodeLab]: Failed to load assembly: \\?\C:\Users\BoltBait\AppData\Local\Microsoft\VisualStudio\17.0_f1477706\WinFormsDesigner\qyeil1bu.gma\UserAppData\System.Private.CoreLib.dll
                        System.IO.FileLoadException: Could not load file or assembly 'System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
                           at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr ptrNativeAssemblyBinder, UInt16* ilPath, UInt16* niPath, ObjectHandleOnStack retAssembly)
                           at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
                           at Microsoft.DotNet.DesignTools.Services.TypeResolutionService.LoadFromAssemblyPath(String filePath)
```
The file does exist in the specified directory.  Nothing special about it--not marked readonly or anything.  Here are the file's properties:
![image](https://github.com/dotnet/winforms/assets/14893317/b763468a-fc8d-4be9-a55c-cb96a81c6fa3)

EDIT: I just tried loading my project on my old laptop and get the same error.  Super bummed now.

**Comment by BoltBait** [comment]
I did find a workaround:

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.8.0 Preview 1.0

Seems to work fine.

**Comment by JeremyKuhne** [comment]
@Shyam-Gupta, does this ring any bells?

**Comment by kirsan31** [comment]
> @Shyam-Gupta, does this ring any bells?

Yea - does it mean I need to stay on 17.6.5 until 17.8x?

**Comment by Shyam-Gupta** [comment]
@BoltBait I can repro the issue. I'll investigate and get back.

**Comment by Shyam-Gupta** [comment]
Looks like designer is failing to load because of conflicting dependencies between those of `DesignToolsServer` process and the NuGet packages referenced by the designer project.

Using `ExcludeAssets\PrivateAssets` option while referencing NuGet packages in following manner should help resolve this issue:

`<PackageReference Include="ILRepack" Version="2.0.18" ExcludeAssets="Runtime" PrivateAssets="all" />`

**Comment by BoltBait** [comment]
Thank you, @Shyam-Gupta !

That did fix my problem.

This is a much better work around than what I'd found. Feel free to close this issue if you don't plan on making this automatic within the Designer itself.

**Comment by Shyam-Gupta** [comment]
I am glad your problem is now resolved. Also, I want to add that this is not a workaround. It is the recommended approach for referencing NuGet packages. More details about it are available [here](https://learn.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support).
