### ISSUE TITLE
[.Net Core] ComponentDesigner is not fully ported

### ISSUE THREAD

**Issue by MrB0nd** [dotnet/winforms#989]
* .NET Core Version: 3.0.0-preview6-27712-03
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**
ComponentDesigner currently has not implemented methods PreFilterAttributes and PreFilterEvents.
https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs#L225

And I have a question about IDesignerFilter methods implementation in ComponentDesigner. Shouldn't it call the corresponding virtual methods? (the way it's done in the .NET Framework)

**Actual behavior:**
Throws NotImplementedException

**Expected behavior:**
Implemented :)

**Comment by merriemcgaw** [comment]
@JuditRose if you can get this in before the end of the month, great. If not just let me know. I betcha @RussKie  will grab it 😊

**Comment by kfrancis** [comment]
@RussKie @JuditRose Any luck yet?

**Comment by merriemcgaw** [comment]
@kfrancis, @MrB0nd can you help us to prioritize our work and let us know specifically which ones you need in order to unblock your migrations?

**Comment by RussKie** [comment]
No, sorry. We're currently focusing on P7 milestone items.
Hopefully we'll get to this soon.

**Comment by MrB0nd** [comment]
@merriemcgaw @RussKie  While I see that you're likely have the other priorities this time, I still want to answer your question. We have been trying to migrate DevExpress End-User Report Designer to finish our work before the official .NET Core 3 release. Our tool has visual report components whose designers are derived from ComponentDesigner and they use events, attributes and property filtering. The ComponentTray I mentioned in my other opened issue https://github.com/dotnet/winforms/issues/988 also is a crucial part and for now we can't move forward because of not implemented EventHandlerService.

**Comment by kfrancis** [comment]
We're waiting on Telerik to support designing reports, very likely similar to @MrB0nd's requirements.
