### ISSUE TITLE
THIRD-PARTY-NOTICES.txt file contains test-only notices

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/winforms#9905]
Test-only notices should **not** be included in the main repo's TPN file: https://github.com/dotnet/winforms/blob/main/THIRD-PARTY-NOTICES.TXT

Please remove this notice and include it alongside tests that need it. See this as an example: https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Performance/CodeQuality/Burgers/THIRD-PARTY-NOTICES

This issue was uncovered while updating TPN file for .NET 8 release: https://github.com/dotnet/runtime/pull/91933 The process assembles notices from all repos into a shared TPN file that ships with SDK.

**Comment by John-Qiao** [comment]
Verified it in the main branch of Winforms repo for .Net 9.0, the content of THIRD-PARTY-NOTICES.TXT is changed to below:

![9905-testresult](https://github.com/dotnet/winforms/assets/45864985/31d0220c-e69f-4bb4-8574-a1c42d73888f)
