### ISSUE TITLE
Better support of library and control metadata in the Toolbox for referenced packages

### ISSUE THREAD

**Issue by tbolon** [dotnet/winforms#9922]
### Environment

VS version: Version 17.8.0 Preview 1.0

### .NET version

multiples

### Did this work in a previous version of Visual Studio and/or previous .NET release?

yes, at least the designer handled packages references better in some points, worse on others.

### Issue description

For a detailed description of this issue, see [my repository](https://github.com/tbolon/winforms-playground/tree/main/ToolboxTests/PackageRefApps) where I made experiments.

My goal was to track the inconsistencies beetween the differents ways the designer handle toolbox items in visual studio, depending on how you reference controls in your projects (project ref vs package ref) and who is responsible for populating the toolbox (out-of-proc designer vs in-proc designer).

I have found inconsistencies on both project ref and package ref, and wanted to submit here an issue about the package references.

You will find in the readme of the repo linked a table with a summary about what is different, and suggestions about what could be fixed/enhanced.

The main points are:

- The toolbox populating service should better implement features already present in the legacy designer: use product name and description set on the custom control
- The legacy designer could display custom icons set on controls on packages. It already read come metadatas from packages and was supposed to handle toolboxbitmap [long ago](https://github.com/NuGet/Home/issues/6440#issuecomment-434827530) based on what @mgoertz-msft said on the issue linked.

I would *love* to add some horsepower and help fixing these gaps between the different experiences. If I could help in any way...

Back story: I am starting to investigate how to migrate the UI of our massive internal codebase to winforms in .net 8, since almost everything else has already been migrated. So I am examinating how our projects will handle multi-targeting.

PS: I will certainly create another issue regarding project references, which are handled differently.

### Steps to reproduce

- Clone the repo <https://github.com/tbolon/winforms-playground/>
- Follow the [README](https://github.com/tbolon/winforms-playground/tree/main/ToolboxTests/PackageRefApps) to fix the Nuget.config and open the vs solution
- Compare the README result table with what you observe.

**Comment by tbolon** [comment]
Will close for now, need to investigate further 😅

**Comment by ilCosmico** [comment]
> Will close for now, need to investigate further 😅

Why did you close this?

**Comment by tbolon** [comment]
Because in the case of packages, it's relatively [well supported](https://github.com/tbolon/winforms-playground/tree/main/ToolboxTests/PackageRefApps): icons are missing on the VS integrated designer (which I suppose is not really well supported, as control packages were added recently for compatibility reasons) ; and the new designer is only missing product title and description.

I think priority should be given to project references, which should benefit from metadata's support (icons) and custom designer.

**Comment by ilCosmico** [comment]
Are you suggesting that it should also be able to support VisualStudioToolsManifest.xml?
