### ISSUE TITLE
Label edit in TreeView has incorrect position in accessibility tree

### ISSUE THREAD

**Issue by MelonWang1** [dotnet/winforms#9956]
### .NET version

.NET 8.0.100-rc.2.23469.4

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, this issue also repro's in .NET3.1/5.0/6.0/7.0.

### Issue description

This issue is similar with [7263](https://github.com/dotnet/winforms/issues/7263). Edit control of TreeViewNode will be placed as a first child of the TreeView in accessibility tree.

![before](https://github.com/dotnet/winforms/assets/94418985/4af43965-e1b5-4f05-b8fb-3761104158a0)
![before2](https://github.com/dotnet/winforms/assets/94418985/27c2e478-5444-4950-8f1c-cff0c3d2a878)

### Steps to reproduce

1. Create a Winforms .NET Core application
2. Add a TreeView control
3. Add some root node and child node
4. Set TreeView control LabelEdit property is true
5. Build and run
6. Open Inspect or Accessibility Insights tool 
7. Click twice on any tree node to start editing it and find Edit control place in tools

**Comment by Amy-Li03** [comment]
Verified this on .NET 9.0.100-alpha.1.23551.16, issue was fixed. The LabelEdit control of TreeViewNode was placed as a child of the Editing TreeNode.
![image](https://github.com/dotnet/winforms/assets/62929087/a2b0669d-d9a6-4352-9738-949130c7fd05)
