### ISSUE TITLE
"Select Resource" dialog should be opened for PictureBox in DemoConsole application

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9964]
### .NET version

.Net 9.0:  Main branch of Winforms repo

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it also repro in .Net 8.0 from Release/8.0 branch of Winforms repo

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, "Select Resource" dialog doesn't pop up when clicking "Choose Image..." in PictureBox's smart tag window or its properties window

Actual result in DemoConsole application:
![NoSelectResourceDialog](https://github.com/dotnet/winforms/assets/26474449/fe247780-f984-428b-abb0-65afa131d8bf)

Expected result in Winforms designer:
![Expected_SelectResourceDialog](https://github.com/dotnet/winforms/assets/26474449/0b8c57d5-fce8-4c1b-912a-731ce1c77318)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by dreddy-work** [comment]
ResourcePickerDialog is in the design time assembly `Microsoft.VisualStudio.Windows.Forms`.  Did this ever work in .NET core?

**Comment by Tanya-Solyanik** [comment]
@dreddy-work  - this bug is about the test IDE that is part of our test project

**Comment by dreddy-work** [comment]
'ResourcePickerDialog' is Visual Studio design time editor and is not available outside of Visual Studio. Editor being opened here is a fallback editor from the runtime. Workflow is not broken, and the image property is set successfully and rendered. Given we don't expect Image to be serialized into Resource.resx file in this runtime scenario ( Or atleast, we are not aware of any such scenarios), there is no reason to block it.

Closing. We will revisit if we get a real customer scenario here.
