### ISSUE TITLE
Failed to "Add Tab" for TabControl in DemoConsole application

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9968]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works well in .Net 8.0 from Release/8.0 branch of Winforms repo

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, failed to "Add Tab" for TabControl with popping up an error dialog. And "Remove Tab" works well.

Actual result in DemoConsole application when **testing main branch**:
![image](https://github.com/dotnet/winforms/assets/26474449/232361d2-c506-4928-ac61-6663725e31a1)
![AddTab_Failed](https://github.com/dotnet/winforms/assets/26474449/ec914f41-85cf-452c-b4d7-5a83dd5dd6b3)

Expected result in DemoConsole application when **testing release/8.0 branch**:
![AddTab_success](https://github.com/dotnet/winforms/assets/26474449/5c089f86-a6d8-4fe1-9723-70a59ff419b4)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by MelonWang1** [comment]
Verified this issue from main branch with winforms repo, TabControl's "Add Tab" and "Remove Tab" both works well.

https://github.com/dotnet/winforms/assets/94418985/799b6dff-596a-456b-afcc-14e69c0811aa
