### ISSUE TITLE
Exception in .Net Core(5.0/6.0/7.0) when Corsor of Form is Disposed

### ISSUE THREAD

**Issue by Lohnegrim** [dotnet/winforms#9985]
### .NET version

7.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.Net Core 3.1 works, 
.Net Core 5.0, 6.0, 7.0 doesn't work
.Net Core 8.0 seems to work

### Issue description

When the Cursor of a Form gets Disposed, then there are endless exceptions and the App may even crash.
This didn't happen in the .Net Framework, and doesn't seems to happen in .Net Core 3.1 or 8.0 Preview.
This Exception seems to happen in .Net Core 5.0, 6.0 & 7.0

As far as I tracked this back, the Problem seems that in the FW when the cursor is set, then it uses the internal Value of 'System.Windows.Forms.handle', and .Net Core 7.0 seems to use 'System.Windows.Forms.Handle'.
'System.Windows.Forms.handle' throws a exception when System.Windows.Forms.handle is IntPtr.Zero.

This is even more problematic when (acidently) any one of teh Cursors returned by the 'System.Windows.Forms.Cursors'-Properties gets Disposed, since they are used internal and there is no way to replace the Disposed Cursors with Not Disposed ones, prevent the Dispose or react to the Dispose (No Event)

### Steps to reproduce

1.) Create a New WinForms Project.
2.) Add a Button
3.) Add this Click-Event Code:
`
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim cur As Cursor
        cur = System.Windows.Forms.Cursors.Default
        Me.Cursor = cur
        Me.Cursor.Dispose()
    End Sub
`
4.) Click the Button and move the Mousecursor around the Form

**Comment by elachlan** [comment]
@Lohnegrim are you using a custom cursor? You should not dispose of a cursor provided by the `Cursors` class. You should only dispose of cursors created and managed by yourself.

**Comment by elachlan** [comment]
Are you talking about a custom cursor you have created or one of the `Cursors`?

**Comment by Lohnegrim** [comment]
@elachlan 
In my current legacy Code, one of the Cursors from 'System.Windows.Forms.Cursors' gets Disposed, and I'm trying to trackdown where it gets Disposed.
But since it's no Problem in the FW 4.8 that is currently used in the Legacy App, seens as a big/important problem .

**Comment by JeremyKuhne** [comment]
On .NET 6 this is result:

```
System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed object.
Object name: 'Disposed 'Cursor' can no longer be used.'.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Cursor.get_Handle() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs:line 149
   at Interop.User32.SetCursor(IHandle hCursor)
   at System.Windows.Forms.Control.WmSetCursor(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 12736
   at System.Windows.Forms.Control.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 13135
   at System.Windows.Forms.ButtonBase.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs:line 1351
   at System.Windows.Forms.Button.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Button.cs:line 396
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 68
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs:line 122
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam) in /_/src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs:line 370
```

The issue here is that we're destroying `Cursors` objects when we shouldn't be. There was a mistake made when updating the interop code in Core. #8865 fixed this for .NET 8.

This should be considered for servicing, it's pretty bad to destroy our static `Cursor` objects.

**Comment by lonitra** [comment]
It looks like bot did not close this for some reason.. @JeremyKuhne is this issue resolved?

**Comment by Lohnegrim** [comment]
If this gets serviced, will this get fixed in FWC 5.0 - 7.0?

**Comment by JeremyKuhne** [comment]
@Lohnegrim a fix has gone in for 6.0 and 7.0. 5.0 is out of support so it will not get the fix.

**Comment by John-Qiao** [comment]
Verified this issue on release/7.0 branch of Winforms repo, it was fixed. There's no exception after clicked the Button and moved the Mousecursor around the Form now.

![9985-7 0-testresult](https://github.com/dotnet/winforms/assets/45864985/3ff091a5-e815-4479-a629-f04286fb8375)

**Comment by Ashley-Li** [comment]
Verified this issue on release/6.0 branch of Winforms repo, it was fixed. There's no exception after clicked the Button and moved the Mousecursor around the Form now. 
![9985Retest](https://github.com/dotnet/winforms/assets/56664234/89d6221b-5fd2-4954-a6f5-fa0607ba8287)

**Comment by Ashley-Li** [comment]
Verified this issue on .NET SDK 6.0.320 TP build, it was fixed. The test result is the same as above.

**Comment by John-Qiao** [comment]
Verified this issue on .NET SDK 7.0.114 TP build, it was fixed. The test result is the same as above.
