### ISSUE TITLE
After clicking on a component control on the Manually Align Controls by hand page of the DemoConsole application, it fails to focus on other controls.

### ISSUE THREAD

**Issue by Nora-Zhou01** [dotnet/winforms#9989]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it works well in .Net 8.0 from Release/8.0 branch of Winforms repo

### Issue description

In the Align Controls by hand page of the [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test application in the Winforms repo, clicking on the component control does not focus on other controls.

### Steps to reproduce

Actual result in DemoConsole application when **testing main branch**:

https://github.com/dotnet/winforms/assets/104609169/22b8bb87-cfd8-4627-b9fe-786484f1e9e6

Expected result in DemoConsole application when **testing release/8.0 branch**:

https://github.com/dotnet/winforms/assets/104609169/355e2ec7-59b9-4d0b-aa29-0f7b94332606

**Comment by MandiMan** [comment]
@LeafShi1 verified this issue from main branch with winforms repo, it was not fixed well, after moving Button3 or Button4 and then clicking on component control, the component control cannot be focused and moved.

https://github.com/dotnet/winforms/assets/108860782/f7c9aeac-af3c-4280-9d9c-9842fa283872

**Comment by Tanya-Solyanik** [comment]
@MandiMan - Please open a new bug to track this - 

>after moving Button3 or Button4 and then clicking on component control, the component control cannot be focused and moved.

**Comment by MandiMan** [comment]
> @MandiMan - Please open a new bug to track this -
> 
> > after moving Button3 or Button4 and then clicking on component control, the component control cannot be focused and moved.

Filed a new issue [10082](https://github.com/dotnet/winforms/issues/10082) to track it.
