### ISSUE TITLE
Component controls in Component tray should not be modified when TabOrder is enabled in DemoConsole application

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9997]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it doesn't work in .Net 8.0 from Release/8.0 branch of Winforms repo

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, when enabling "Tab Order", the component tray controls in component tray still can  be modified: open smart tag window to edit. --- it is not expected.

**Actual result in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app**:
![image](https://github.com/dotnet/winforms/assets/26474449/7f1a4097-3682-48e2-9cef-79d312067b0c)
![TabOrder_ActualInDemoConsole](https://github.com/dotnet/winforms/assets/26474449/3b507b49-0efa-437c-9467-ecee248d0d73)

**Expected result:**
when enabling "Tab Order", component tray controls in component tray cannot be focused to modify.
![TabOrder_expected](https://github.com/dotnet/winforms/assets/26474449/0c552e3c-8b15-474b-aaff-a333d54fe31e)

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by Tanya-Solyanik** [comment]
@merriemcgaw  - this application is only a sample for testing our designers, and this issue does not block anyone from working with this sample, I would "won't fix" this bug.
