### ISSUE TITLE
The icon property of the NotifyIcon control cannot be modified in DemoConsole application 

### ISSUE THREAD

**Issue by Ashley-Li** [dotnet/winforms#9999]
### .NET version

.Net 9.0: Main branch of Winforms repo

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No, it doesn't work in .Net 8.0 from Release/8.0 branch of Winforms repo

### Issue description

In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, when changing the icon property of the NotifyIcon control, cannot be modified.

**Actual result** in [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app:

https://github.com/dotnet/winforms/assets/56664234/dab536e8-e545-4370-a641-0008ba2bc5a8

**Expected result:**
When changing the icon property of the NotifyIcon control, can be modified.

https://github.com/dotnet/winforms/assets/56664234/df710638-e2e2-477a-85da-5dd0f85c5f1f

### Steps to reproduce

Test sample: [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) in Winforms repo

**Comment by Tanya-Solyanik** [comment]
@Ashley-Li  - This is not really a DemoConsole issue, this reproduces in any runtime property grid. Could you please investigate, in what version of .NET this regressed?

**Comment by Eudora-Li01** [comment]
Checked in .NET 6.0, 7.0 and 8.0 version, this issue reproduces on all version of .NET, which is not a regression issue.

https://github.com/dotnet/winforms/assets/130345015/9758e0b7-fac4-4609-85ac-eb6f2d3fcbe6

**Comment by Tanya-Solyanik** [comment]
Thank you, @Eudora-Li01!
 
>Checked in .NET 6.0, 7.0 and 8.0 version, this issue reproduces on all version of .NET, which is not a regression issue.

Wow!  This scenario is working correctly on .NET Framework, could you please verify .NET5 and below to find where we introduced this issue.

**Comment by Eudora-Li01** [comment]
It works well on .NET 3.1 and 5.0, broken from .NET 6.0.

https://github.com/dotnet/winforms/assets/130345015/fb6fa48f-6c0f-417d-8d93-8b5a50276133

**Comment by Tanya-Solyanik** [comment]
@LeafShi1  - this issue was introduced in .NET6, it might be easier to isolate the change now.

**Comment by Zheng-Li01** [comment]
Verified the issue on 9.0.0-alpha.1.24053.2 which have been fixed that the icon property of the NotifyIcon control can be modified  in runtime property grid.
![PropertyGrid_RunTime](https://github.com/dotnet/winforms/assets/38325459/632662e5-a401-4e33-be77-c6637f28bcfb)

And also verified the issue in DemoConsole application from main branch of winforms repo which have been fixed that the icon property of the NotifyIcon control can be modified, **However another issue was found that selected icon for Icon property cannot be refreshed in time when adding the icon by using "Choose Icon..." command line until clicked any where in the propertyGide Window.**  @Tanya-Solyanik  @LeafShi1 want to confirm with you if  the current behavior is expected? or we need to file a issue to track it?  see below details. 
![DemoConsole](https://github.com/dotnet/winforms/assets/38325459/e6c7b54f-ea00-434e-95c3-5a107fff2078)

**More info:**
 The selected icon for Icon property can be refreshed in time when adding the icon by using "Choose Icon..." command line in Design time property grid.
![PropertyGrid_DesignTime](https://github.com/dotnet/winforms/assets/38325459/452bef3f-ccbe-428d-a4ca-4ebe843b09d7)

**Comment by Tanya-Solyanik** [comment]
@Zheng-Li01  - I think something is missing in System.Windows.Forms.Design components that processing of a verb does not update the property grid entry value immediately. Please open a new bug. But it will be a low priority one.

**Comment by Zheng-Li01** [comment]
@Tanya-Solyanik  filed the new issue [10579](https://github.com/dotnet/winforms/issues/10579) to track it.

**Comment by Amy-Li03** [comment]
Verified this issue on .NET 8.0.200 with dlls built form winforms repo of release/8.0 branch, it was fixed, the icon property of the NotifyIcon control can be modified in runtime property grid.
There is no NotifyIcon control in DemoConsole application of winforms repo's release/8.0 branch, so we don't verify it.

**Comment by Zheng-Li01** [comment]
Verified with .NET SDK 8.0.2 test pass build, this issue was fixed. Test result is same as above.
